BeUtility.cpp
FLOAT_ERR_RATIO
Referenced by IsAngleBetween.
D3DX_PI
Referenced by AdjustRadian, IsInRect.
D3DX_2PI
Referenced by AdjustRadian, IsAngleBetween.
const char* g_apcActionName[BUAN_NUM][BUAN_NUM]
Referenced by GetIndexByActionName.
char acGameDataDirectory[1024][1024]
Referenced by GetGameDataDirectory, SetGameDataDirectory.
Es::NormalLock logLock
Referenced by LogRaceFileLog, LogRaceOtherLog, LogRaceOtherLogFlush, LogRaceUpdateAppend, LogRaceUpdateBegin, LogRaceUpdateEnd, LogRaceUpdateTime, RecordFileLog.
char g_LogTemp[4096][4096]
Referenced by LogRaceUpdateAppend, LogRaceUpdateBegin, LogRaceUpdateEnd, LogRaceUpdateTime.
void WarnInfo(const char *format,...)
float GetBuyDistance(void)
References makeCallback.f.
float GetDistance(float fx1, float fy1, float fx2, float fy2)
float GetDot(float fx1, float fy1, float fx2, float fy2)
float GetDistance2(float fx1, float fy1, float fx2, float fy2)
Referenced by IsInRect.
float GetDistance3D(float fx1, float fy1, float fz1, float fx2, float fy2, float fz2)
bool IsInTriangle(int x0, int y0, int x1, int y1, int x2, int y2, int x, int y)
Referenced by IsInQuadrangle.
bool IsInQuadrangle(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3, int x, int y)
References IsInTriangle.
Referenced by IsInRect.
float AntiClockWiseDelta(float fRadian0, float fRadian1)
References AdjustRadian.
void AdjustRadian(float &fRadian)
References D3DX_2PI, D3DX_PI.
Referenced by AntiClockWiseDelta.
bool IsAngleBetween(float fStart, float fEnd, float fAngle)
References D3DX_2PI, makeCallback.f, FLOAT_ERR_RATIO.
unsigned int ReverseDWORD(unsigned int dwOrgin)
void GetPosByDistance(float fDistance, float fPosX, float fPosY, float fTargetPosX, float fTargetPosY, float &fGetX, float &fGetY)
References makeCallback.f, fScale.
float GetPointToLineDistance2(float fPosX, float fPosY, float fA, float fB, float fC)
float GetPointToLineDistance(float fPosX, float fPosY, float fA, float fB, float fC)
int GetIndexByActionName(const char *pcName)
References BUAN_NUM, g_apcActionName.
int TruncToInt(float fValue)
References makeCallback.f.
void RecordFileLog(const char *pch)
References logLock.
void SetGameDataDirectory(const char *acWorkingDir, const char *acGameDataDir)
References acGameDataDirectory.
const char* GetGameDataDirectory()
References acGameDataDirectory.
void LogRaceFileLog(const char *pch)
References logLock.
void LogRaceUpdateBegin(const char *format,...)
References g_LogTemp, logLock.
void LogRaceUpdateAppend(const char *format,...)
References g_LogTemp, logLock.
void LogRaceUpdateEnd(int iUTime, const char *format,...)
References g_LogTemp, logLock, LogRaceUpdateTime.
char* ConvCmdName(char *ch, DWord cmd)
References SPRCT_ATTACHDATA, SPRCT_BEGIN, SPRCT_BUFFERDATA, SPRCT_CHAINEFFECTDATA, SPRCT_DAMAGEDATA, SPRCT_EFFECTDATA, SPRCT_EFFECTDEL, SPRCT_GLOBALDATA, SPRCT_HERODATA, SPRCT_KILLHERODATA, SPRCT_MAPITEMDATA, SPRCT_MAPPOINTDATA, SPRCT_PING, SPRCT_UIWINDOWDATA, SPRCT_UNITDISAPPEAR, SPRCT_UNITSHOWDATA, SPRCT_USERDATA, SRC_ADJUSTFRAME, SRC_END, SRC_FRAME, SRC_HERO_ATTACK_CANCEL, SRC_HERO_ATTACK_POS, SRC_HERO_ATTACK_UNIT, SRC_HERO_DIRECT_MOVE, SRC_HERO_HOLD, SRC_HERO_MOVE, SRC_HERO_RT_DIRECT, SRC_HERO_SELECT, SRC_HERO_STOP, SRC_LOAD, SRC_LOCKUNIT, SRC_PAUSE_BEGIN, SRC_PAUSE_CANCEL, SRC_PAUSE_END, SRC_PING, SRC_PLAYER_GUANQIA_CMD, SRC_PLAYER_INFO, SRC_PLAYER_LEAVE, SRC_PLAYER_RECON_END, SRC_PLAYER_RELIVEHERO, SRC_PLAYER_TOWNITEM, SRC_RACE_PAUSE, SRC_RELINKBEGIN, SRC_RELINKEND, SRC_REPLAYVERSION, SRC_SAVE_RECONDATA_BEGIN, SRC_SAVE_RECONDATA_END, SRC_SHOP_LIST, SRC_START, SRC_SWITCH_HEROFOCUS, SRC_SWITCH_MODE, SRC_SYSTEM_CHEAT, SRC_SYSTEM_SURRENDER, SRC_SYSTEM_SUSPEND, SRC_TRAN_LOADEND, SRC_UNIT_ACTIVE_SKILL, SRC_UNIT_ATTACK, SRC_UNIT_ATTACK_POS, SRC_UNIT_ATTACK_UNIT, SRC_UNIT_BUY_ITEM, SRC_UNIT_DIRECTBUY_ITEM, SRC_UNIT_DIRECTSELL_ITEM, SRC_UNIT_DISPLACE_ITEM, SRC_UNIT_DROP_ITEM, SRC_UNIT_FOLLOW, SRC_UNIT_GIVEUP_DISPLACE_ITEM, SRC_UNIT_HOLD, SRC_UNIT_LEARN_SKILL, SRC_UNIT_MOVE, SRC_UNIT_PATROL, SRC_UNIT_PICK_ITEM, SRC_UNIT_PICK_ITEM_AUTO, SRC_UNIT_SPELL, SRC_UNIT_SPELLXULI, SRC_UNIT_STOP, SRC_UNIT_SWAP_ITEM, SRC_UNIT_USE_ITEM, SRC_VIEW_SELHERO, SRC_WATCH_POINT.
Referenced by SeRaceRecord::PrintCmdLog, SeRaceRecord::PushRaceData.
void LogRaceOtherLog(const char *pcLogFile, const char *format,...)
References logLock.
void LogRaceOtherLogFlush(const char *pcLogFile)
References logLock.
void LogRaceUpdateTime(const char *pcName, int iUpdateTime)
References g_LogTemp, logLock.
Referenced by LogRaceUpdateEnd, AutoLogRaceUpdate::~AutoLogRaceUpdate.
struct tm __GetLocalTime(time_t dwTime)
int GetTypeID2Index(int iTypeID)
int GetIndex2TypeID(int iIndex)
void CopyStringIfNotEmpty(std::string &kDst, const std::string &kSrc)
SePos2 GetPointOnBezier(SePos2 *pkPos, float fValueT)
References SePos2::fX, SePos2::fY.
void TranslateSkillTargetType(int iSkillTargetFlag, int &iStaticProcFlag, int &iDynaPropFlag)
References BUDP_CAMP_ALLY, BUDP_CAMP_ENEMY, BUDP_CAMP_NATURE, BUDP_CAMP_SELF, BUDP_INVINCIBLE, BUDP_INVISIBLE, BUDP_MAGIC_IMMUNITY, BUDP_NOTSUMMON, BUDP_SUMMON, BUSP_CLASS_BOSS, BUSP_CLASS_BUILDING, BUSP_CLASS_HERO, BUSP_CLASS_MONSTER, BUSP_CLASS_NORMAL, BUSP_PROP_ANCIENT, SKILL_TARGETTYPE_BOSS, SKILL_TARGETTYPE_BUILDING, SKILL_TARGETTYPE_DIJUN, SKILL_TARGETTYPE_HERO, SKILL_TARGETTYPE_MOMIAN, SKILL_TARGETTYPE_SELF, SKILL_TARGETTYPE_SOLIDER, SKILL_TARGETTYPE_WUDI, SKILL_TARGETTYPE_YEGUAI, SKILL_TARGETTYPE_YINSHEN, SKILL_TARGETTYPE_YOUJUN, SKILL_TARGETTYPE_YUANGU, SKILL_TARGETTYPE_ZHONGLI.
bool IsInRect(float fPointX, float fPointY, float fPosX, float fPosY, float fWidth, float fHeight, float fFace, float fCollision)
References D3DX_PI, GetDistance2, IsInQuadrangle.