SeRaceMgr.cpp
SeRaceMgr g_kRaceMgr
int iTmpCount
uint32_t uiCountNum
uint32_t uiRoomCountNum
uint32_t uiCountNum1
uint32_t uiCountNum2
const char* csRobotName[][]
IMPLEMENT_POOL(SeReconJoinPlayer, 256, 64)
IMPLEMENT_POOL(SeRace, 256, 64)
static double calTimeCoef(int race_time)
Referenced by SeRaceMgr::OnRaceEndGradeDetail.
static void calOdds(int scoreA, int scoreB, double &oddsA, double &oddsB)
Referenced by SeRaceMgr::OnRaceEndGradeDetail.
static double calP3(int index, int *scores)
Referenced by calRaceScore_Win.
static double calP5(int index, int *scores)
Referenced by calRaceScore_Win.
static double calP6(int selfScore, int selfTotalScore)
Referenced by calRaceScore_Lose.
static double calP7(int index, int *grades)
Referenced by calRaceScore_Win.
static double calP8(int index, int *grades)
Referenced by calRaceScore_Lose.
static int calRaceScore_Win(double timeCeof, double oods, int index, int *selfScores, int *selfGrades)
References calP3, calP5, calP7, SeLogDebug.
Referenced by SeRaceMgr::OnRaceEndGradeDetail.
static int calRaceScore_Lose(double timeCeof, double oods, int index, int selfScore, int selfTotalScore, int *selfGrades)
References calP6, calP8, SeLogDebug.
Referenced by SeRaceMgr::OnRaceEndGradeDetail.