SeTool.cpp
COMPRESS_NEED_SIZE
void StrCat(char *dest, int iDstSize, const char *src)
void StrCpy(char *pcDst, int iDstSize, const char *pcSrc)
Referenced by SeMatchReconMgr::AddPlayer, SeMatchReconMgr::AddReconPlayerName, SeSessionMgr::AddSession, SeOpenRoomMgr::ConvOpenRoomInfo, SeRaceHistory::Copy, NexusLinkUserMgr::create, NexusMeasureMgr::create_guest_measure, NexusTeamMgr::create_member, NexusMeasureMgr::create_user_measure, RaceDetailMgr::CreateRaceDetail, EnableFileLog, SeRaceHistory::GetPtlRaceHistory, GetRangeValue, SeRaceRoomMgr::GetReloadRoomInfo, SeRaceRecord::GetReplayInfo, SeFileLog::Initialize, BlockServer::KickPlayerByID, LadderRankItem::LadderRankItem, SeCharLadderData::Load, SeDBMemMgr::LoadConfig, TownServer::LoadConfig, WatchServer::CWatchServer::LoadConfig, WorldServer::LoadConfig, DBServer::LoadConfig, LoginServer::LoadDynamicConfig, LadderRankItem::LoadInfo, RaceServer::LoadRSTempConfig, MkDir, SeOpenRoomMgr::OnCreateRoom, GlobalServer::OnLoginQueryRet, SeMatchMgr::OnMatchReq, TcpServer::OnNetAccept, DBServer::OnNetAccept, BackendServer::OnNetAccept, NexusServer::OnNetAccept, WatchServer::CWatchServer::OnNetAccept, MatchServer::OnNetAccept, RaceServer::OnNetAccept, WorldServer::OnNetAccept, WatchServer::CWatchServer::OnPlayerConnected, RaceServer::OnPlayerConnected, SeRaceMgr::OnPlayerRaceViewBegin, SeRaceMgr::OnPlayerReconBegin, SeRaceMgr::OnRaceModeEnd, SeRaceQueryMgr::OnRaceSeatUpdateState, SeRaceQueryMgr::OnRaceSvrUpdateRoomLoadInfo, SeRaceQueryMgr::OnReloadPlayerInfo, SePlayer::OnRenameEnd, SeOpenRoomMgr::OnRoomInviteRspOk, SeOpenRoomMgr::OnRoomJoin, SeOpenRoomMgr::OnRoomKickSomeone, SeOpenRoomMgr::OnRoomSwitchSeat, WorldServer::OnSendBSRaceEndRace, SeMatchMgr::openRoom, ParseSetupVal, RaceServer::ParseSetupVal, WorldServer::ProcessBLW_PlayerLoadComplete, WorldServer::ProcessBW_InitGenIDRet, LoginServer::ProcessCL_PlayerLogin_NEW, RaceServer::ProcessCR_RaceValidate, RaceServer::ProcessCR_Talk, GlobalServer::ProcessDB_AccountQuery, DBServer::ProcessDB_CharNexusFriendLoad, DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery, DBServer::ProcessDB_IsPlayerExistByAccountOrName, DBServer::ProcessDB_IsPlayerExistByID, LoginServer::ProcessGL_AccountLoginSuccess, WorldServer::ProcessHS_QueryNearestRaceInfoRet, GlobalServer::ProcessLG_AccountLogin, GlobalServer::ProcessLG_PlayerLogin, BlockServer::ProcessMBL_GetPlayerMatchValue, TownServer::ProcessTCPSvr_ClientConnect, TownServer::ProcessTCPSvr_ReLoadReadyID, DBServer::ProcessWB_IsPlayerExist, TownServer::ProcessWT_InitPlayerInfo, CItem::save, BlockServer::SeBSProcess_CharNexusFriend, WorldServer::SeDBSerProcess_CharRename, DBServer::SendDB_CharData, DBServer::SendDBLog_SqlLog, MatchServer::SendHS_BiVoiceCreateChatRoom, MatchServer::SendHS_BiVoiceUserLoginRet, GlobalServer::SendHS_DHAccountLogin, SeRaceMgr::SendMatchAddrMsg, TcpServer::SendParent_ClientConnect, ServerMain, SeCacheMgr::SetClearAccount, SetName, SPrintf, NexusLinkUserMgr::verify_user_attr.
void MemCpy(void *pkDst, int iDstSize, const void *pkSrc, int iCpySize)
Referenced by SeCacheMgr::AddAccount, DBServer::Excu_SelectData, SeRaceMgr::GenRaceID, SePtlHSock::GetHSock, SeRaceRecord::GetRaceBigData, SeRaceRecord::GetRaceData, RaceServer::LoadConfig, SeDBMemMgr::MemCheckOutFunc, RaceService::OnAchievementCounts, RaceService::OnRaceEvent, RaceService::OnRaceSvrModelPack, RaceServer::OnSendMatchRoomLoadInfo, ParseSetupVal, RaceServer::ParseSetupVal, WorldServer::ProcessBLW_ShowNotice, TownServer::ProcessCT_CreateChar, TownServer::ProcessCT_QueryName, WorldServer::ProcessHS_QueryNearestRaceInfoRet, WorldServer::ProcessTW_CreateChar, WorldServer::ProcessTW_QueryName, WorldServer::ProcessTW_SearchUserArchivesInfoReq, TownServer::ProcessWT_ShowNotice, SeThreadMsgMgr::PushMsg, RaceServer::PushRSC_RaceStream, DBServer::SendDB_IsPlayerExistByID, DBServer::SendDB_IsPlayerExistByName, TcpServer::SendParent_RecvData, TcpServer::SendParent_ReLoadReadyID, SeRaceRoomMgr::SendRacePlayerBaseInfo, TownServer::SendTCPSvr_SendData, SePtlHSock::SePtlHSock.
bool CHStrStr(const char *pcDstChar, const char *pcSrcChar)
bool CHStrStr_s(const char *pcDstChar, const char *pcSrcChar)
const char* GetAString(const char *pcSrcStr, char *pcGetStr, int iGetSize)
Referenced by SeConfig::GetDBAddr, SeConfig::GetDBTableAddrFromStr, SeConfig::GetLogDBAddr, SeConfig::GetNetAddr, SeConfig::GetRedisAddrFromStr, WorldServer::InitLeagueInfo, SeRaceSvrMgr::InitPlayerRaceSvr, MatchServer::InitRaceBetInfo, DBServer::LoadConfig.
int GetAccountType(const char *pcAccount)
References SSD_MAX_ACCOUNT, SSD_MIN_ACCOUNT.
bool GetDBTime(SeDBTime &rkTime, const char *pcDBTime)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear.
Referenced by GetIDCardAge, WorldServer::InitLeagueInfo, MatchServer::InitRaceBetInfo, LadderLevelMgr::joinTop, NowTime, onTabSelect, GlobalServer::ProcessDB_AccountQuery, DBServer::ProcessDB_CharNexusFriendLoad, DBServer::ProcessDB_CharQueryValid, LadderLevelMgr::updateScore.
UInt64 DiffDBTime(const SeDBTime &rkBeginTime, const SeDBTime &rkEndTime)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear.
Referenced by SeDBPlayerMgr::GetCharMemoryByIndex, GetWeekOfYear, IsDiffWeek, SeCharMemory::IsOverdue, SePlayer::UpdateOnlineTime.
UInt64 DiffDailyDBTime(const SeDBTime &rkBeginTime, const SeDBTime &rkEndTime)
References SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iSecond.
void AddDBTime(const SeDBTime &rkBeginTime, SeDBTime &rkEndTime, int iDay, int iHour, int iMin, int iSec)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::IsValid, SeDBTime::iYear.
Referenced by DBServer::SaveSqlLog2File, DBServer::UpdateSqlLog2File.
void NowTime(SeDBTime &rkTime)
References GetDBTime.
Referenced by adjustDefeat, AchieveFinishMgr::ComposeInfo, DBServer::DBServer, DBServer::Finialize, WorldServer::GenLeagueTime, SePlayer::GetAllExchange, GetBattleField, SeDBPlayerMgr::GetCharMemoryByIndex, GetDayEndTime, GetIDCardAge, SePlayer::GetLadder, GetMatch, SePlayer::GetMemoryValue, TownServer::GetWSTime, SePlayer::LoadingComplete, NowTime, SeCacheMgr::OnUpdateAccountDynamic, GlobalServer::ProcessDB_AccountQuery, GlobalServer::ProcessLG_PlayerTownIndex, BlockServer::ProcessRBL_RaceEndArenaBaseInfoSync, BlockServer::ProcessRBL_UpdateScore, NexusServer::ProcessTN_NexusUserActionReq, TaskMgr::RefreshTask, SeRaceRecord::SaveToFile, SeDBPlayerMgr::SeDBPlayerMgr, DBServer::SendDB_CharInfoAdd, DBServer::SendDBLog_SqlLog, WorldServer::SendDBServer_CharQueryValid, SePlayer::SePlayer, TownServer::TownServer, HeroMgr::unlockHero, SePlayer::UpdateMemoryData, SePlayer::UpdateOnlineTime, SeDBPlayerMgr::UpdatePlayerLastLoginTime, WorldServer::UpdateQueryFreeHeroList, MatchServer::UpdateRaceBetInfo, DBServer::UpdateSqlLog2File, WorldServer::WorldServer.
void GetDBTime(time_t time, SeDBTime &rkTime)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear.
int GetDayOfWeek(const SeDBTime &rkTime)
References SeDBTime::iDay, SeDBTime::iMonth, SeDBTime::iYear.
Referenced by GetDiffWeek, GetWeekOfYear, IsDiffWeek.
bool IsDiffWeek(const SeDBTime &rkBeginTime, const SeDBTime &rkEndTime)
References DiffDBTime, GetDayOfWeek, SeDBTime::iDay, SeDBTime::iMonth, SeDBTime::iYear.
Referenced by WorldServer::UpdateQueryFreeHeroList.
bool IsDiffDay(const SeDBTime &rkBeginTime, const SeDBTime &rkEndTime)
References SeDBTime::iDay, SeDBTime::iMonth, SeDBTime::iYear.
Referenced by TaskMgr::RefreshTask, MatchServer::UpdateRaceBetInfo.
bool IsDiffMonth(const SeDBTime &rkBeginTime, const SeDBTime &rkEndTime)
References SeDBTime::iMonth, SeDBTime::iYear.
const char* NowTime(void)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear, NowTime.
void GetDayEndTime(SeDBTime &rkEndTime)
References SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iSecond, NowTime.
Referenced by BlockServer::ProcessWBL_MatchRaceLoad.
int GetWeekOfYear(SeDBTime &rkTime)
References DiffDBTime, GetDayOfWeek, SeDBTime::iDay, SeDBTime::iMonth, SeDBTime::iYear.
int GetDiffWeek(SeDBTime &rkBeginTime, SeDBTime &rkEndTime)
References DiffDBDay, GetDayOfWeek.
int DiffDBDay(const SeDBTime &rkBeginTime, const SeDBTime &rkEndTime)
References SeDBTime::iDay, SeDBTime::iMonth, SeDBTime::iYear.
Referenced by GetDiffWeek.
time_t GetTDBTime(const SeDBTime &rkDBTime)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear.
Referenced by adjustDefeat, SePlayer::GetLadder, GetMatchBaseInfo, SeCharAchievementData::GetPtlData, onLadderLoad, BlockServer::ProcessRBL_UpdateScore.
unsigned int GetStr2ID(const char *acID)
Referenced by SeRaceMgr::CreateRobotRace, SeRaceSvrMgr::InitPlayerRaceSvr, SeDBMemMgr::LoadConfig, TcpServer::LoadConfig, GlobalServer::LoadConfig, LoginServer::LoadConfig, BackendServer::LoadConfig, HttpServer::LoadConfig, TownServer::LoadConfig, WatchServer::CWatchServer::LoadConfig, MatchServer::LoadConfig, NexusServer::LoadConfig, WorldServer::LoadConfig, DBServer::LoadConfig, MatchServer::LoadDynamicConfig, RaceServer::LoadRSTempConfig, ParseSetupVal, RaceServer::ParseSetupVal.
Word GetStr2Word(const char *acID)
unsigned int GetCheckCode(void *pkData, int iSize, unsigned int dwOrgCRC)
void GenEncryptKey(void *pkKey, int iSize)
Referenced by SeRaceMgr::CreateRobotRace, LoginServer::OnNetAccept, WatchServer::CWatchServer::OnPlayerConnected, RaceServer::OnPlayerConnected, SeRaceMgr::OnRaceModeEnd, TownServer::ProcessTCPSvr_ClientConnect.
void EncodeProtocol(void *pkData, int iSize, Byte abyKey[])
void DecodeProtocol(void *pkData, int iSize, Byte abyKey[])
bool CompressProtocal(void *pkData, int &iSize)
bool UnCompressProtocal(void *pkDstData, int &iDstSize, void *pkSrcData, int iSrcSize)
float GetDistance2D(float fX1, float fY1, float fX2, float fY2)
void GetParabolaParamater(float fOrgX, float fOrgY, float fMaxX, float fMaxY, float fTarX, float fTarY, float &fParaA, float &fParaB, float &fParaC)
void CharToFileFun(const char *pcLogName, const char *pcInfo)
Referenced by SeRaceMgr::LocalCheckEnd_Guanqia, SeRaceMgr::LocalCheckEnd_Race, DBServer::OnPrintfNetState, MatchServer::PrintUpdateTime, DBServer::PrintUpdateTime, WorldServer::Update.
bool CopyText(FILE *pSource, FILE *pDest)
std::string GetVersion(unsigned int dwVersion)
void SplitStr(const std::string &rkStr, const std::string &rkSep, std::vector< std::string > &rkResult)
Referenced by SetHonorDataStrToInt, SplitModel_ID_Index_Texture.
void SplitStr(const Es::StdString &rkStr, const Es::StdString &rkSep, std::vector< Es::StdString > &rkResult)
bool SplitStrByPair(std::vector< std::pair< std::string, std::string > > kSep, const std::string &kString, std::vector< std::string > &akResult)
unsigned int SplitStrColor(const std::string &kString, std::string &kResult, unsigned int dwDefaultColor)
bool SplitIDLevel(const std::string &kStr, int &iSkillTypeID, int &iSkillLevel)
References STRING2INT.
bool SplitModel_ID_Index_Texture(const std::string &kStr, int &iTypeID, int &iIndex, int &iTexture)
References SplitStr, STRING2INT.
bool IsRightIpString(const char *acIP)
Referenced by GetIPString2DWord.
unsigned int HexCharToDec(const char *pcStr)
unsigned int Fun_ARGB(int a, int r, int g, int b)
void Get_ARGB(unsigned int col, int &a, int &r, int &g, int &b)
int GetIDCardAge(const char *pcIDCard)
References GetDBTime, SeDBTime::IsValid, SeDBTime::iYear, NowTime.
void ChangeVerifyCodeByKey(char *pData, int iLength, char cKey)
UInt64 GetCPUCountS(void)
unsigned int GetIPString2DWord(const char *acIP)
References IsRightIpString.
Referenced by SePlayerMgr::GetPlayerIP, LoginServer::ProcessCL_PlayerLogin, LoginServer::ProcessCL_PlayerLogin_NEW, TownServer::ProcessCT_PlayerValidate, TcpServer::ProcessParent_RegisterRet.
bool CanID2Str(unsigned int dwID)
int GetMaxValue(int iValue1, int iValue2, int iValue3, int iValue4, int iValue5)
unsigned int AToDw(const char *pcStr)
int DiffDay(const SeDBTime &rkBeginTime, const SeDBTime &rkEndTime)
References SeDBTime::iDay, SeDBTime::iMonth, SeDBTime::iYear.
void SetHonorDataStrToInt(std::vector< int > &rkHonorInfo, const char *acSqlData)
References SplitStr.
bool GetFileMD5(const char *pcFileName, TeMD5 &rkMD5)
void MyOutputDebugString(const char *pcFmt,...)
SeDBTime GetLocalTime()
References GetLocalTime, SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear.
Referenced by TcpServer::DisconnectPlayerSock, TownServer::DisconnectTcpUser, SeLogShow::Display, GetLocalTime, SeLogShow::Initialize, SeRaceMgr::LocalCheckEnd_Guanqia, SeRaceMgr::LocalCheckEnd_Race, MyExceptionFilter, DBServer::OnPrintfNetState, MatchServer::PrintUpdateTime, DBServer::PrintUpdateTime, WorldServer::Update.