SeTCStream.cpp
int EncodeSeTC_EncryptKey(const SeTC_EncryptKey &kData, char *pcBuf, int iMaxLen)
References SeTC_EncryptKey::abyEncryptKey, SeTC_EncryptKey::dwVersion, EncodeSeTC_EncryptKey.
Referenced by EncodeSeTC_EncryptKey.
int EncodeSeTC_EncryptKey(const char *abyEncryptKey, DWord dwVersion, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_EncryptKey(const char *pkData, int iLen, SeTC_EncryptKey &kStruct)
References SeTC_EncryptKey::abyEncryptKey, SeNetStream::Attach, SeTC_EncryptKey::dwVersion, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeTC_ShowNotice(const SeTC_ShowNotice &kData, char *pcBuf, int iMaxLen)
References SeTC_ShowNotice::acMessage, SeTC_ShowNotice::dwParam, EncodeSeTC_ShowNotice, SeTC_ShowNotice::eNoticeCode.
Referenced by EncodeSeTC_ShowNotice.
int EncodeSeTC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, const char *acMessage, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_ShowNotice(const char *pkData, int iLen, SeTC_ShowNotice &kStruct)
References SeTC_ShowNotice::acMessage, SeNetStream::Attach, SeTC_ShowNotice::dwParam, SeTC_ShowNotice::eNoticeCode, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeTC_PlayerValidateRet(const SeTC_PlayerValidateRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_PlayerValidateRet, SeTC_PlayerValidateRet::eValidateType.
Referenced by EncodeSeTC_PlayerValidateRet.
int EncodeSeTC_PlayerValidateRet(SeValidateType eValidateType, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_PlayerValidateRet(const char *pkData, int iLen, SeTC_PlayerValidateRet &kStruct)
References SeNetStream::Attach, SeTC_PlayerValidateRet::eValidateType, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_QueryNameRet(const SeTC_QueryNameRet &kData, char *pcBuf, int iMaxLen)
References SeTC_QueryNameRet::bHasExist, EncodeSeTC_QueryNameRet.
Referenced by EncodeSeTC_QueryNameRet.
int EncodeSeTC_QueryNameRet(bool bHasExist, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_QueryNameRet(const char *pkData, int iLen, SeTC_QueryNameRet &kStruct)
References SeNetStream::Attach, SeTC_QueryNameRet::bHasExist, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_CreateCharRet(const SeTC_CreateCharRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_CreateCharRet, SeTC_CreateCharRet::eResult.
Referenced by EncodeSeTC_CreateCharRet.
int EncodeSeTC_CreateCharRet(SeCreateCharRet eResult, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_CreateCharRet(const char *pkData, int iLen, SeTC_CreateCharRet &kStruct)
References SeNetStream::Attach, SeTC_CreateCharRet::eResult, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_PlayerLeaveRet(const SeTC_PlayerLeaveRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_PlayerLeaveRet.
Referenced by EncodeSeTC_PlayerLeaveRet.
int EncodeSeTC_PlayerLeaveRet(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeTC_PlayerLeaveRet(const char *pkData, int iLen, SeTC_PlayerLeaveRet &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeTC_InitPlayerInfo(const SeTC_InitPlayerInfo &kData, char *pcBuf, int iMaxLen)
References SeTC_InitPlayerInfo::acName, SeTC_InitPlayerInfo::byEquipSetIndex, SeTC_InitPlayerInfo::dwExp, SeTC_InitPlayerInfo::dwLevel, SeTC_InitPlayerInfo::dwOnlineTime, SeTC_InitPlayerInfo::dwPlayerID, SeTC_InitPlayerInfo::dwServerTime, EncodeSeTC_InitPlayerInfo, SeTC_InitPlayerInfo::iDiamond, SeTC_InitPlayerInfo::iGold, SeTC_InitPlayerInfo::kLadder.
Referenced by EncodeSeTC_InitPlayerInfo.
int EncodeSeTC_InitPlayerInfo(DWord dwPlayerID, const char *acName, DWord iGold, DWord iDiamond, DWord dwLevel, DWord dwExp, const SeLadderInfo &kLadder, Byte byEquipSetIndex, DWord dwServerTime, DWord dwOnlineTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeLadderInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_InitPlayerInfo(const char *pkData, int iLen, SeTC_InitPlayerInfo &kStruct)
References SeTC_InitPlayerInfo::acName, SeNetStream::Attach, SeTC_InitPlayerInfo::byEquipSetIndex, DecodeSeLadderInfo, SeTC_InitPlayerInfo::dwExp, SeTC_InitPlayerInfo::dwLevel, SeTC_InitPlayerInfo::dwOnlineTime, SeTC_InitPlayerInfo::dwPlayerID, SeTC_InitPlayerInfo::dwServerTime, SeNetStream::GetCurPos, SeTC_InitPlayerInfo::iDiamond, SeTC_InitPlayerInfo::iGold, SeTC_InitPlayerInfo::kLadder, SeNetStream::Read, SeNetStream::ReadString, SeNetStream::SetCurPos.
int EncodeSeTC_MatchRaceAddr(const SeTC_MatchRaceAddr &kData, char *pcBuf, int iMaxLen)
References SeTC_MatchRaceAddr::akPlayerInfo, SeTC_MatchRaceAddr::dwKey, SeTC_MatchRaceAddr::dwSessionID, EncodeSeTC_MatchRaceAddr, SeTC_MatchRaceAddr::eValidType, SeTC_MatchRaceAddr::iNum, SeTC_MatchRaceAddr::iSeat, SeTC_MatchRaceAddr::kRaceAddr, SeTC_MatchRaceAddr::kRaceAddrUdp.
Referenced by EncodeSeTC_MatchRaceAddr.
int EncodeSeTC_MatchRaceAddr(DWord dwSessionID, int dwKey, SeRaceValidType eValidType, const SePtlNetAddr &kRaceAddr, const SePtlNetAddr &kRaceAddrUdp, int iSeat, int iNum, const SeNoticeMatchPlayerInfo *akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNoticeMatchPlayerInfo, EncodeSePtlNetAddr, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_MatchRaceAddr(DWord dwSessionID, int dwKey, SeRaceValidType eValidType, const SePtlNetAddr &kRaceAddr, const SePtlNetAddr &kRaceAddrUdp, int iSeat, int iNum, std::vector< SeNoticeMatchPlayerInfo > &akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNoticeMatchPlayerInfo, EncodeSePtlNetAddr, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_MatchRaceAddr(const char *pkData, int iLen, SeTC_MatchRaceAddr &kStruct)
References SeTC_MatchRaceAddr::akPlayerInfo, SeNetStream::Attach, DecodeSeNoticeMatchPlayerInfo, DecodeSePtlNetAddr, SeTC_MatchRaceAddr::dwKey, SeTC_MatchRaceAddr::dwSessionID, SeTC_MatchRaceAddr::eValidType, SeNetStream::GetCurPos, SeTC_MatchRaceAddr::iNum, SeTC_MatchRaceAddr::iSeat, SeTC_MatchRaceAddr::kRaceAddr, SeTC_MatchRaceAddr::kRaceAddrUdp, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_PlayerAppear(const SeTC_PlayerAppear &kData, char *pcBuf, int iMaxLen)
References SeTC_PlayerAppear::akPlayerList, EncodeSeTC_PlayerAppear, SeTC_PlayerAppear::iNum.
Referenced by EncodeSeTC_PlayerAppear.
int EncodeSeTC_PlayerAppear(int iNum, const SePlayerAppear *akPlayerList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePlayerAppear, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_PlayerAppear(int iNum, std::vector< SePlayerAppear > &akPlayerList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePlayerAppear, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_PlayerAppear(const char *pkData, int iLen, SeTC_PlayerAppear &kStruct)
References SeTC_PlayerAppear::akPlayerList, SeNetStream::Attach, DecodeSePlayerAppear, SeNetStream::GetCurPos, SeTC_PlayerAppear::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_PlayerDisappear(const SeTC_PlayerDisappear &kData, char *pcBuf, int iMaxLen)
References SeTC_PlayerDisappear::adwID, EncodeSeTC_PlayerDisappear, SeTC_PlayerDisappear::iNum.
Referenced by EncodeSeTC_PlayerDisappear.
int EncodeSeTC_PlayerDisappear(int iNum, const SePlayerDisappear *adwID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePlayerDisappear, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_PlayerDisappear(int iNum, std::vector< SePlayerDisappear > &adwID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePlayerDisappear, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_PlayerDisappear(const char *pkData, int iLen, SeTC_PlayerDisappear &kStruct)
References SeTC_PlayerDisappear::adwID, SeNetStream::Attach, DecodeSePlayerDisappear, SeNetStream::GetCurPos, SeTC_PlayerDisappear::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_PlayerGoPos(const SeTC_PlayerGoPos &kData, char *pcBuf, int iMaxLen)
References SeTC_PlayerGoPos::dwPlayerID, EncodeSeTC_PlayerGoPos, SeTC_PlayerGoPos::fDirect.
Referenced by EncodeSeTC_PlayerGoPos.
int EncodeSeTC_PlayerGoPos(DWord dwPlayerID, float fDirect, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_PlayerGoPos(const char *pkData, int iLen, SeTC_PlayerGoPos &kStruct)
References SeNetStream::Attach, SeTC_PlayerGoPos::dwPlayerID, SeTC_PlayerGoPos::fDirect, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_ExchangeInit(const SeTC_ExchangeInit &kData, char *pcBuf, int iMaxLen)
References SeTC_ExchangeInit::akPtlExchange, EncodeSeTC_ExchangeInit, SeTC_ExchangeInit::iNum.
Referenced by EncodeSeTC_ExchangeInit.
int EncodeSeTC_ExchangeInit(int iNum, const SePtlExchange *akPtlExchange, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlExchange, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ExchangeInit(int iNum, std::vector< SePtlExchange > &akPtlExchange, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlExchange, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ExchangeInit(const char *pkData, int iLen, SeTC_ExchangeInit &kStruct)
References SeTC_ExchangeInit::akPtlExchange, SeNetStream::Attach, DecodeSePtlExchange, SeNetStream::GetCurPos, SeTC_ExchangeInit::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_ViewResult(const SeTC_ViewResult &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_ViewResult, SeTC_ViewResult::eResult, SeTC_ViewResult::iData.
Referenced by EncodeSeTC_ViewResult.
int EncodeSeTC_ViewResult(SeViewResultType eResult, int iData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_ViewResult(const char *pkData, int iLen, SeTC_ViewResult &kStruct)
References SeNetStream::Attach, SeTC_ViewResult::eResult, SeNetStream::GetCurPos, SeTC_ViewResult::iData, SeNetStream::Read.
int EncodeSeTC_QueryRaceRoomListRet(const SeTC_QueryRaceRoomListRet &kData, char *pcBuf, int iMaxLen)
References SeTC_QueryRaceRoomListRet::akRoomInfo, EncodeSeTC_QueryRaceRoomListRet, SeTC_QueryRaceRoomListRet::iCurPage, SeTC_QueryRaceRoomListRet::iMaxPage, SeTC_QueryRaceRoomListRet::iRoomNums.
Referenced by EncodeSeTC_QueryRaceRoomListRet.
int EncodeSeTC_QueryRaceRoomListRet(int iCurPage, int iMaxPage, int iRoomNums, const SeMatchRoomListInfo *akRoomInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeMatchRoomListInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_QueryRaceRoomListRet(int iCurPage, int iMaxPage, int iRoomNums, std::vector< SeMatchRoomListInfo > &akRoomInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeMatchRoomListInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_QueryRaceRoomListRet(const char *pkData, int iLen, SeTC_QueryRaceRoomListRet &kStruct)
References SeTC_QueryRaceRoomListRet::akRoomInfo, SeNetStream::Attach, DecodeSeMatchRoomListInfo, SeNetStream::GetCurPos, SeTC_QueryRaceRoomListRet::iCurPage, SeTC_QueryRaceRoomListRet::iMaxPage, SeTC_QueryRaceRoomListRet::iRoomNums, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_ItemExchangeRet(const SeTC_ItemExchangeRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_ItemExchangeRet, SeTC_ItemExchangeRet::iReturn, SeTC_ItemExchangeRet::iTypeID.
Referenced by EncodeSeTC_ItemExchangeRet.
int EncodeSeTC_ItemExchangeRet(int iTypeID, int iReturn, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_ItemExchangeRet(const char *pkData, int iLen, SeTC_ItemExchangeRet &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeTC_ItemExchangeRet::iReturn, SeTC_ItemExchangeRet::iTypeID, SeNetStream::Read.
int EncodeSeTC_UpdateMisc(const SeTC_UpdateMisc &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_UpdateMisc, SeTC_UpdateMisc::eType, SeTC_UpdateMisc::iValue, SeTC_UpdateMisc::iValue2.
Referenced by EncodeSeTC_UpdateMisc.
int EncodeSeTC_UpdateMisc(SeMiscType eType, int iValue, int iValue2, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_UpdateMisc(const char *pkData, int iLen, SeTC_UpdateMisc &kStruct)
References SeNetStream::Attach, SeTC_UpdateMisc::eType, SeNetStream::GetCurPos, SeTC_UpdateMisc::iValue, SeTC_UpdateMisc::iValue2, SeNetStream::Read.
int EncodeSeTC_DelayCheckRet(const SeTC_DelayCheckRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_DelayCheckRet.
Referenced by EncodeSeTC_DelayCheckRet.
int EncodeSeTC_DelayCheckRet(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeTC_DelayCheckRet(const char *pkData, int iLen, SeTC_DelayCheckRet &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeTC_BiVoiceEnterInfo(const SeTC_BiVoiceEnterInfo &kData, char *pcBuf, int iMaxLen)
References SeTC_BiVoiceEnterInfo::acLoginSession, SeTC_BiVoiceEnterInfo::acRoomSession, EncodeSeTC_BiVoiceEnterInfo, SeTC_BiVoiceEnterInfo::roomid.
Referenced by EncodeSeTC_BiVoiceEnterInfo.
int EncodeSeTC_BiVoiceEnterInfo(int roomid, const char *acLoginSession, const char *acRoomSession, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_BiVoiceEnterInfo(const char *pkData, int iLen, SeTC_BiVoiceEnterInfo &kStruct)
References SeTC_BiVoiceEnterInfo::acLoginSession, SeTC_BiVoiceEnterInfo::acRoomSession, SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString, SeTC_BiVoiceEnterInfo::roomid.
int EncodeSeTC_TaskQueryListRet(const SeTC_TaskQueryListRet &kData, char *pcBuf, int iMaxLen)
References SeTC_TaskQueryListRet::akList, EncodeSeTC_TaskQueryListRet, SeTC_TaskQueryListRet::iNum.
Referenced by EncodeSeTC_TaskQueryListRet.
int EncodeSeTC_TaskQueryListRet(int iNum, const SePtlTask *akList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_TaskQueryListRet(int iNum, std::vector< SePtlTask > &akList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_TaskQueryListRet(const char *pkData, int iLen, SeTC_TaskQueryListRet &kStruct)
References SeTC_TaskQueryListRet::akList, SeNetStream::Attach, DecodeSePtlTask, SeNetStream::GetCurPos, SeTC_TaskQueryListRet::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_TaskReselRet(const SeTC_TaskReselRet &kData, char *pcBuf, int iMaxLen)
References SeTC_TaskReselRet::dwSrcTaskID, EncodeSeTC_TaskReselRet, SeTC_TaskReselRet::kNewTask.
Referenced by EncodeSeTC_TaskReselRet.
int EncodeSeTC_TaskReselRet(DWord dwSrcTaskID, const SePtlTask &kNewTask, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_TaskReselRet(const char *pkData, int iLen, SeTC_TaskReselRet &kStruct)
References SeNetStream::Attach, DecodeSePtlTask, SeTC_TaskReselRet::dwSrcTaskID, SeNetStream::GetCurPos, SeTC_TaskReselRet::kNewTask, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_AskEnterWaitRace(const SeTC_AskEnterWaitRace &kData, char *pcBuf, int iMaxLen)
References SeTC_AskEnterWaitRace::akPlayerList, SeTC_AskEnterWaitRace::dwMapID, EncodeSeTC_AskEnterWaitRace, SeTC_AskEnterWaitRace::iNum.
Referenced by EncodeSeTC_AskEnterWaitRace.
int EncodeSeTC_AskEnterWaitRace(DWord dwMapID, int iNum, const SeRaceWaitPlayer *akPlayerList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceWaitPlayer, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_AskEnterWaitRace(DWord dwMapID, int iNum, std::vector< SeRaceWaitPlayer > &akPlayerList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceWaitPlayer, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_AskEnterWaitRace(const char *pkData, int iLen, SeTC_AskEnterWaitRace &kStruct)
References SeTC_AskEnterWaitRace::akPlayerList, SeNetStream::Attach, DecodeSeRaceWaitPlayer, SeTC_AskEnterWaitRace::dwMapID, SeNetStream::GetCurPos, SeTC_AskEnterWaitRace::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_CardUpdate(const SeTC_CardUpdate &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_CardUpdate.
Referenced by EncodeSeTC_CardUpdate.
int EncodeSeTC_CardUpdate(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeTC_CardUpdate(const char *pkData, int iLen, SeTC_CardUpdate &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeTC_StartMatchRet(const SeTC_StartMatchRet &kData, char *pcBuf, int iMaxLen)
References SeTC_StartMatchRet::dwMapID, EncodeSeTC_StartMatchRet, SeTC_StartMatchRet::iResult.
Referenced by EncodeSeTC_StartMatchRet.
int EncodeSeTC_StartMatchRet(int iResult, DWord dwMapID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_StartMatchRet(const char *pkData, int iLen, SeTC_StartMatchRet &kStruct)
References SeNetStream::Attach, SeTC_StartMatchRet::dwMapID, SeNetStream::GetCurPos, SeTC_StartMatchRet::iResult, SeNetStream::Read.
int EncodeSeTC_FriendRequestInit(const SeTC_FriendRequestInit &kData, char *pcBuf, int iMaxLen)
References SeTC_FriendRequestInit::akRequest, EncodeSeTC_FriendRequestInit, SeTC_FriendRequestInit::iNum.
Referenced by EncodeSeTC_FriendRequestInit.
int EncodeSeTC_FriendRequestInit(int iNum, const SePtlFriendRequest *akRequest, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlFriendRequest, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_FriendRequestInit(int iNum, std::vector< SePtlFriendRequest > &akRequest, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlFriendRequest, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_FriendRequestInit(const char *pkData, int iLen, SeTC_FriendRequestInit &kStruct)
References SeTC_FriendRequestInit::akRequest, SeNetStream::Attach, DecodeSePtlFriendRequest, SeNetStream::GetCurPos, SeTC_FriendRequestInit::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_FriendRequestAdd(const SeTC_FriendRequestAdd &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_FriendRequestAdd, SeTC_FriendRequestAdd::kInfo.
Referenced by EncodeSeTC_FriendRequestAdd.
int EncodeSeTC_FriendRequestAdd(const SePtlFriendRequest &kInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlFriendRequest, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_FriendRequestAdd(const char *pkData, int iLen, SeTC_FriendRequestAdd &kStruct)
References SeNetStream::Attach, DecodeSePtlFriendRequest, SeNetStream::GetCurPos, SeTC_FriendRequestAdd::kInfo, SeNetStream::SetCurPos.
int EncodeSeTC_FriendInit(const SeTC_FriendInit &kData, char *pcBuf, int iMaxLen)
References SeTC_FriendInit::akFriend, EncodeSeTC_FriendInit, SeTC_FriendInit::iNum.
Referenced by EncodeSeTC_FriendInit.
int EncodeSeTC_FriendInit(int iNum, const SePtlFriend *akFriend, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlFriend, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_FriendInit(int iNum, std::vector< SePtlFriend > &akFriend, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlFriend, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_FriendInit(const char *pkData, int iLen, SeTC_FriendInit &kStruct)
References SeTC_FriendInit::akFriend, SeNetStream::Attach, DecodeSePtlFriend, SeNetStream::GetCurPos, SeTC_FriendInit::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_FriendAdd(const SeTC_FriendAdd &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_FriendAdd, SeTC_FriendAdd::kFriend.
Referenced by EncodeSeTC_FriendAdd.
int EncodeSeTC_FriendAdd(const SePtlFriend &kFriend, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlFriend, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_FriendAdd(const char *pkData, int iLen, SeTC_FriendAdd &kStruct)
References SeNetStream::Attach, DecodeSePtlFriend, SeNetStream::GetCurPos, SeTC_FriendAdd::kFriend, SeNetStream::SetCurPos.
int EncodeSeTC_FriendDel(const SeTC_FriendDel &kData, char *pcBuf, int iMaxLen)
References SeTC_FriendDel::dwFriendID, EncodeSeTC_FriendDel.
Referenced by EncodeSeTC_FriendDel.
int EncodeSeTC_FriendDel(DWord dwFriendID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_FriendDel(const char *pkData, int iLen, SeTC_FriendDel &kStruct)
References SeNetStream::Attach, SeTC_FriendDel::dwFriendID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_FriendUpdateStatus(const SeTC_FriendUpdateStatus &kData, char *pcBuf, int iMaxLen)
References SeTC_FriendUpdateStatus::dwFriendID, EncodeSeTC_FriendUpdateStatus, SeTC_FriendUpdateStatus::eStatus.
Referenced by EncodeSeTC_FriendUpdateStatus.
int EncodeSeTC_FriendUpdateStatus(DWord dwFriendID, SeOnlineStatus eStatus, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_FriendUpdateStatus(const char *pkData, int iLen, SeTC_FriendUpdateStatus &kStruct)
References SeNetStream::Attach, SeTC_FriendUpdateStatus::dwFriendID, SeTC_FriendUpdateStatus::eStatus, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_FriendRemarkRet(const SeTC_FriendRemarkRet &kData, char *pcBuf, int iMaxLen)
References SeTC_FriendRemarkRet::acRemarks, SeTC_FriendRemarkRet::dwFriendID, EncodeSeTC_FriendRemarkRet.
Referenced by EncodeSeTC_FriendRemarkRet.
int EncodeSeTC_FriendRemarkRet(DWord dwFriendID, const char *acRemarks, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_FriendRemarkRet(const char *pkData, int iLen, SeTC_FriendRemarkRet &kStruct)
References SeTC_FriendRemarkRet::acRemarks, SeNetStream::Attach, SeTC_FriendRemarkRet::dwFriendID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeTC_QueryRaceBetInfoRet(const SeTC_QueryRaceBetInfoRet &kData, char *pcBuf, int iMaxLen)
References SeTC_QueryRaceBetInfoRet::dwdwConstellIDA, SeTC_QueryRaceBetInfoRet::dwdwConstellIDB, EncodeSeTC_QueryRaceBetInfoRet, SeTC_QueryRaceBetInfoRet::fOddsA, SeTC_QueryRaceBetInfoRet::fOddsB.
Referenced by EncodeSeTC_QueryRaceBetInfoRet.
int EncodeSeTC_QueryRaceBetInfoRet(DWord dwdwConstellIDA, DWord dwdwConstellIDB, float fOddsA, float fOddsB, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_QueryRaceBetInfoRet(const char *pkData, int iLen, SeTC_QueryRaceBetInfoRet &kStruct)
References SeNetStream::Attach, SeTC_QueryRaceBetInfoRet::dwdwConstellIDA, SeTC_QueryRaceBetInfoRet::dwdwConstellIDB, SeTC_QueryRaceBetInfoRet::fOddsA, SeTC_QueryRaceBetInfoRet::fOddsB, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_ItemDel(const SeTC_ItemDel &kData, char *pcBuf, int iMaxLen)
References SeTC_ItemDel::dwItemID, EncodeSeTC_ItemDel, SeTC_ItemDel::eType.
Referenced by EncodeSeTC_ItemDel.
int EncodeSeTC_ItemDel(DWord dwItemID, SeItemDelType eType, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_ItemDel(const char *pkData, int iLen, SeTC_ItemDel &kStruct)
References SeNetStream::Attach, SeTC_ItemDel::dwItemID, SeTC_ItemDel::eType, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_KickPlayer(const SeTC_KickPlayer &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_KickPlayer.
Referenced by EncodeSeTC_KickPlayer.
int EncodeSeTC_KickPlayer(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeTC_KickPlayer(const char *pkData, int iLen, SeTC_KickPlayer &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeTC_ReceiveMail(const SeTC_ReceiveMail &kData, char *pcBuf, int iMaxLen)
References SeTC_ReceiveMail::akMail, EncodeSeTC_ReceiveMail, SeTC_ReceiveMail::iNum.
Referenced by EncodeSeTC_ReceiveMail.
int EncodeSeTC_ReceiveMail(int iNum, const SePtlMail *akMail, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlMail, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ReceiveMail(int iNum, std::vector< SePtlMail > &akMail, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlMail, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ReceiveMail(const char *pkData, int iLen, SeTC_ReceiveMail &kStruct)
References SeTC_ReceiveMail::akMail, SeNetStream::Attach, DecodeSePtlMail, SeNetStream::GetCurPos, SeTC_ReceiveMail::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_UpdateMail(const SeTC_UpdateMail &kData, char *pcBuf, int iMaxLen)
References SeTC_UpdateMail::akInfo, EncodeSeTC_UpdateMail, SeTC_UpdateMail::iNum.
Referenced by EncodeSeTC_UpdateMail.
int EncodeSeTC_UpdateMail(int iNum, const SeMailUpdate *akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeMailUpdate, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_UpdateMail(int iNum, std::vector< SeMailUpdate > &akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeMailUpdate, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_UpdateMail(const char *pkData, int iLen, SeTC_UpdateMail &kStruct)
References SeTC_UpdateMail::akInfo, SeNetStream::Attach, DecodeSeMailUpdate, SeNetStream::GetCurPos, SeTC_UpdateMail::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_MailOprRet(const SeTC_MailOprRet &kData, char *pcBuf, int iMaxLen)
References SeTC_MailOprRet::dwMailID, EncodeSeTC_MailOprRet, SeTC_MailOprRet::iRet, SeTC_MailOprRet::iType.
Referenced by EncodeSeTC_MailOprRet.
int EncodeSeTC_MailOprRet(int iType, DWord dwMailID, int iRet, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_MailOprRet(const char *pkData, int iLen, SeTC_MailOprRet &kStruct)
References SeNetStream::Attach, SeTC_MailOprRet::dwMailID, SeNetStream::GetCurPos, SeTC_MailOprRet::iRet, SeTC_MailOprRet::iType, SeNetStream::Read.
int EncodeSeTC_PlayerRename(const SeTC_PlayerRename &kData, char *pcBuf, int iMaxLen)
References SeTC_PlayerRename::acName, EncodeSeTC_PlayerRename.
Referenced by EncodeSeTC_PlayerRename.
int EncodeSeTC_PlayerRename(const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::WriteString.
int DecodeSeTC_PlayerRename(const char *pkData, int iLen, SeTC_PlayerRename &kStruct)
References SeTC_PlayerRename::acName, SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::ReadString.
int EncodeSeTC_HeartBeat(const SeTC_HeartBeat &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_HeartBeat.
Referenced by EncodeSeTC_HeartBeat.
int EncodeSeTC_HeartBeat(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeTC_HeartBeat(const char *pkData, int iLen, SeTC_HeartBeat &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeTC_QueryMapTaskListRet(const SeTC_QueryMapTaskListRet &kData, char *pcBuf, int iMaxLen)
References SeTC_QueryMapTaskListRet::akPtlMapTask, SeTC_QueryMapTaskListRet::dwMapID, EncodeSeTC_QueryMapTaskListRet, SeTC_QueryMapTaskListRet::iNum.
Referenced by EncodeSeTC_QueryMapTaskListRet.
int EncodeSeTC_QueryMapTaskListRet(DWord dwMapID, int iNum, const SePtlMapTask *akPtlMapTask, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlMapTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_QueryMapTaskListRet(DWord dwMapID, int iNum, std::vector< SePtlMapTask > &akPtlMapTask, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlMapTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_QueryMapTaskListRet(const char *pkData, int iLen, SeTC_QueryMapTaskListRet &kStruct)
References SeTC_QueryMapTaskListRet::akPtlMapTask, SeNetStream::Attach, DecodeSePtlMapTask, SeTC_QueryMapTaskListRet::dwMapID, SeNetStream::GetCurPos, SeTC_QueryMapTaskListRet::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_QueryNearestRaceInfoRet(const SeTC_QueryNearestRaceInfoRet &kData, char *pcBuf, int iMaxLen)
References SeTC_QueryNearestRaceInfoRet::akRaceInfo, SeTC_QueryNearestRaceInfoRet::dwQueriedID, EncodeSeTC_QueryNearestRaceInfoRet, SeTC_QueryNearestRaceInfoRet::iNum.
Referenced by EncodeSeTC_QueryNearestRaceInfoRet.
int EncodeSeTC_QueryNearestRaceInfoRet(DWord dwQueriedID, int iNum, const SePtlRaceHistory *akRaceInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlRaceHistory, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_QueryNearestRaceInfoRet(DWord dwQueriedID, int iNum, std::vector< SePtlRaceHistory > &akRaceInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlRaceHistory, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_QueryNearestRaceInfoRet(const char *pkData, int iLen, SeTC_QueryNearestRaceInfoRet &kStruct)
References SeTC_QueryNearestRaceInfoRet::akRaceInfo, SeNetStream::Attach, DecodeSePtlRaceHistory, SeTC_QueryNearestRaceInfoRet::dwQueriedID, SeNetStream::GetCurPos, SeTC_QueryNearestRaceInfoRet::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_ResIncompleteRaceList(const SeTC_ResIncompleteRaceList &kData, char *pcBuf, int iMaxLen)
References SeTC_ResIncompleteRaceList::akIncmpRaceList, EncodeSeTC_ResIncompleteRaceList, SeTC_ResIncompleteRaceList::iNum.
Referenced by EncodeSeTC_ResIncompleteRaceList.
int EncodeSeTC_ResIncompleteRaceList(int iNum, const SeIncompleteRaceBaseInfo *akIncmpRaceList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeIncompleteRaceBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ResIncompleteRaceList(int iNum, std::vector< SeIncompleteRaceBaseInfo > &akIncmpRaceList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeIncompleteRaceBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ResIncompleteRaceList(const char *pkData, int iLen, SeTC_ResIncompleteRaceList &kStruct)
References SeTC_ResIncompleteRaceList::akIncmpRaceList, SeNetStream::Attach, DecodeSeIncompleteRaceBaseInfo, SeNetStream::GetCurPos, SeTC_ResIncompleteRaceList::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_AddIncompleteRace(const SeTC_AddIncompleteRace &kData, char *pcBuf, int iMaxLen)
References SeTC_AddIncompleteRace::akIncmpRace, EncodeSeTC_AddIncompleteRace.
Referenced by EncodeSeTC_AddIncompleteRace.
int EncodeSeTC_AddIncompleteRace(const SeIncompleteRaceBaseInfo &akIncmpRace, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeIncompleteRaceBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_AddIncompleteRace(const char *pkData, int iLen, SeTC_AddIncompleteRace &kStruct)
References SeTC_AddIncompleteRace::akIncmpRace, SeNetStream::Attach, DecodeSeIncompleteRaceBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int EncodeSeTC_RemoveIncompleteRace(const SeTC_RemoveIncompleteRace &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_RemoveIncompleteRace, SeTC_RemoveIncompleteRace::iRoomID.
Referenced by EncodeSeTC_RemoveIncompleteRace.
int EncodeSeTC_RemoveIncompleteRace(DWord iRoomID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_RemoveIncompleteRace(const char *pkData, int iLen, SeTC_RemoveIncompleteRace &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeTC_RemoveIncompleteRace::iRoomID, SeNetStream::Read.
int EncodeSeTC_ResIncmpRaceSeatBaseInfo(const SeTC_ResIncmpRaceSeatBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeTC_ResIncmpRaceSeatBaseInfo::dwRoomID, EncodeSeTC_ResIncmpRaceSeatBaseInfo, SeTC_ResIncmpRaceSeatBaseInfo::iNum, SeTC_ResIncmpRaceSeatBaseInfo::oIncmpRaceBaseInfo.
Referenced by EncodeSeTC_ResIncmpRaceSeatBaseInfo.
int EncodeSeTC_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, const SeSeatBaseInfo *oIncmpRaceBaseInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeSeatBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, std::vector< SeSeatBaseInfo > &oIncmpRaceBaseInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeSeatBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ResIncmpRaceSeatBaseInfo(const char *pkData, int iLen, SeTC_ResIncmpRaceSeatBaseInfo &kStruct)
References SeNetStream::Attach, DecodeSeSeatBaseInfo, SeTC_ResIncmpRaceSeatBaseInfo::dwRoomID, SeNetStream::GetCurPos, SeTC_ResIncmpRaceSeatBaseInfo::iNum, SeTC_ResIncmpRaceSeatBaseInfo::oIncmpRaceBaseInfo, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_InGameDisconn(const SeTC_InGameDisconn &kData, char *pcBuf, int iMaxLen)
References SeTC_InGameDisconn::dwRoomID, EncodeSeTC_InGameDisconn, SeTC_InGameDisconn::iReconTime, SeTC_InGameDisconn::iSeat.
Referenced by EncodeSeTC_InGameDisconn.
int EncodeSeTC_InGameDisconn(DWord dwRoomID, int iSeat, int iReconTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_InGameDisconn(const char *pkData, int iLen, SeTC_InGameDisconn &kStruct)
References SeNetStream::Attach, SeTC_InGameDisconn::dwRoomID, SeNetStream::GetCurPos, SeTC_InGameDisconn::iReconTime, SeTC_InGameDisconn::iSeat, SeNetStream::Read.
int EncodeSeTC_CreateRoomRet(const SeTC_CreateRoomRet &kData, char *pcBuf, int iMaxLen)
References SeTC_CreateRoomRet::akInfo, EncodeSeTC_CreateRoomRet, SeTC_CreateRoomRet::eType, SeTC_CreateRoomRet::iNum.
Referenced by EncodeSeTC_CreateRoomRet.
int EncodeSeTC_CreateRoomRet(SeCreateRoomRetType eType, int iNum, const SeOpenRoomInfo *akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeOpenRoomInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_CreateRoomRet(SeCreateRoomRetType eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeOpenRoomInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_CreateRoomRet(const char *pkData, int iLen, SeTC_CreateRoomRet &kStruct)
References SeTC_CreateRoomRet::akInfo, SeNetStream::Attach, DecodeSeOpenRoomInfo, SeTC_CreateRoomRet::eType, SeNetStream::GetCurPos, SeTC_CreateRoomRet::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_QueryRoomListRet(const SeTC_QueryRoomListRet &kData, char *pcBuf, int iMaxLen)
References SeTC_QueryRoomListRet::akInfo, EncodeSeTC_QueryRoomListRet, SeTC_QueryRoomListRet::iNum.
Referenced by EncodeSeTC_QueryRoomListRet.
int EncodeSeTC_QueryRoomListRet(int iNum, const SeOpenRoomInfo *akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeOpenRoomInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_QueryRoomListRet(int iNum, std::vector< SeOpenRoomInfo > &akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeOpenRoomInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_QueryRoomListRet(const char *pkData, int iLen, SeTC_QueryRoomListRet &kStruct)
References SeTC_QueryRoomListRet::akInfo, SeNetStream::Attach, DecodeSeOpenRoomInfo, SeNetStream::GetCurPos, SeTC_QueryRoomListRet::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_RoomJoinRet(const SeTC_RoomJoinRet &kData, char *pcBuf, int iMaxLen)
References SeTC_RoomJoinRet::akInfo, EncodeSeTC_RoomJoinRet, SeTC_RoomJoinRet::eType, SeTC_RoomJoinRet::iNum.
Referenced by EncodeSeTC_RoomJoinRet.
int EncodeSeTC_RoomJoinRet(SeRoomJoinRetType eType, int iNum, const SeOpenRoomInfo *akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeOpenRoomInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_RoomJoinRet(SeRoomJoinRetType eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeOpenRoomInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_RoomJoinRet(const char *pkData, int iLen, SeTC_RoomJoinRet &kStruct)
References SeTC_RoomJoinRet::akInfo, SeNetStream::Attach, DecodeSeOpenRoomInfo, SeTC_RoomJoinRet::eType, SeNetStream::GetCurPos, SeTC_RoomJoinRet::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_RoomSwitchSeatRet(const SeTC_RoomSwitchSeatRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_RoomSwitchSeatRet, SeTC_RoomSwitchSeatRet::eType.
Referenced by EncodeSeTC_RoomSwitchSeatRet.
int EncodeSeTC_RoomSwitchSeatRet(SeRoomJoinRetType eType, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_RoomSwitchSeatRet(const char *pkData, int iLen, SeTC_RoomSwitchSeatRet &kStruct)
References SeNetStream::Attach, SeTC_RoomSwitchSeatRet::eType, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_RoomMemberNotify(const SeTC_RoomMemberNotify &kData, char *pcBuf, int iMaxLen)
References SeTC_RoomMemberNotify::akInfo, SeTC_RoomMemberNotify::dwRoomID, SeTC_RoomMemberNotify::dwRoomLeaderID, EncodeSeTC_RoomMemberNotify, SeTC_RoomMemberNotify::eNoticeCode, SeTC_RoomMemberNotify::iNum.
Referenced by EncodeSeTC_RoomMemberNotify.
int EncodeSeTC_RoomMemberNotify(SeRoomNtfCode eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, const SeRoomMember *akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRoomMember, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_RoomMemberNotify(SeRoomNtfCode eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, std::vector< SeRoomMember > &akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRoomMember, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_RoomMemberNotify(const char *pkData, int iLen, SeTC_RoomMemberNotify &kStruct)
References SeTC_RoomMemberNotify::akInfo, SeNetStream::Attach, DecodeSeRoomMember, SeTC_RoomMemberNotify::dwRoomID, SeTC_RoomMemberNotify::dwRoomLeaderID, SeTC_RoomMemberNotify::eNoticeCode, SeNetStream::GetCurPos, SeTC_RoomMemberNotify::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_RoomLeaveRet(const SeTC_RoomLeaveRet &kData, char *pcBuf, int iMaxLen)
References SeTC_RoomLeaveRet::dwRoomID, EncodeSeTC_RoomLeaveRet.
Referenced by EncodeSeTC_RoomLeaveRet.
int EncodeSeTC_RoomLeaveRet(DWord dwRoomID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_RoomLeaveRet(const char *pkData, int iLen, SeTC_RoomLeaveRet &kStruct)
References SeNetStream::Attach, SeTC_RoomLeaveRet::dwRoomID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_RoomStartRet(const SeTC_RoomStartRet &kData, char *pcBuf, int iMaxLen)
References SeTC_RoomStartRet::dwRoomID, EncodeSeTC_RoomStartRet.
Referenced by EncodeSeTC_RoomStartRet.
int EncodeSeTC_RoomStartRet(DWord dwRoomID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_RoomStartRet(const char *pkData, int iLen, SeTC_RoomStartRet &kStruct)
References SeNetStream::Attach, SeTC_RoomStartRet::dwRoomID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_RoomKickSomeoneRet(const SeTC_RoomKickSomeoneRet &kData, char *pcBuf, int iMaxLen)
References SeTC_RoomKickSomeoneRet::dwRoomID, EncodeSeTC_RoomKickSomeoneRet, SeTC_RoomKickSomeoneRet::eType, SeTC_RoomKickSomeoneRet::iseat.
Referenced by EncodeSeTC_RoomKickSomeoneRet.
int EncodeSeTC_RoomKickSomeoneRet(DWord dwRoomID, int iseat, SeRoomKickCode eType, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_RoomKickSomeoneRet(const char *pkData, int iLen, SeTC_RoomKickSomeoneRet &kStruct)
References SeNetStream::Attach, SeTC_RoomKickSomeoneRet::dwRoomID, SeTC_RoomKickSomeoneRet::eType, SeNetStream::GetCurPos, SeTC_RoomKickSomeoneRet::iseat, SeNetStream::Read.
int EncodeSeTC_RoomInviteNotify(const SeTC_RoomInviteNotify &kData, char *pcBuf, int iMaxLen)
References SeTC_RoomInviteNotify::acName, SeTC_RoomInviteNotify::dwInviteeID, SeTC_RoomInviteNotify::dwPlayerID, SeTC_RoomInviteNotify::dwRoomID, EncodeSeTC_RoomInviteNotify.
Referenced by EncodeSeTC_RoomInviteNotify.
int EncodeSeTC_RoomInviteNotify(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_RoomInviteNotify(const char *pkData, int iLen, SeTC_RoomInviteNotify &kStruct)
References SeTC_RoomInviteNotify::acName, SeNetStream::Attach, SeTC_RoomInviteNotify::dwInviteeID, SeTC_RoomInviteNotify::dwPlayerID, SeTC_RoomInviteNotify::dwRoomID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeTC_GetRaceHistoryRet(const SeTC_GetRaceHistoryRet &kData, char *pcBuf, int iMaxLen)
References SeTC_GetRaceHistoryRet::acURLBase, SeTC_GetRaceHistoryRet::akInfo, EncodeSeTC_GetRaceHistoryRet, SeTC_GetRaceHistoryRet::iMaxPage, SeTC_GetRaceHistoryRet::iNum, SeTC_GetRaceHistoryRet::iPage, SeTC_GetRaceHistoryRet::iType.
Referenced by EncodeSeTC_GetRaceHistoryRet.
int EncodeSeTC_GetRaceHistoryRet(int iType, int iPage, int iMaxPage, const char *acURLBase, int iNum, const SePtlRaceHistory *akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlRaceHistory, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int EncodeSeTC_GetRaceHistoryRet(int iType, int iPage, int iMaxPage, const char *acURLBase, int iNum, std::vector< SePtlRaceHistory > &akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlRaceHistory, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_GetRaceHistoryRet(const char *pkData, int iLen, SeTC_GetRaceHistoryRet &kStruct)
References SeTC_GetRaceHistoryRet::acURLBase, SeTC_GetRaceHistoryRet::akInfo, SeNetStream::Attach, DecodeSePtlRaceHistory, SeNetStream::GetCurPos, SeTC_GetRaceHistoryRet::iMaxPage, SeTC_GetRaceHistoryRet::iNum, SeTC_GetRaceHistoryRet::iPage, SeTC_GetRaceHistoryRet::iType, SeNetStream::Read, SeNetStream::ReadString, SeNetStream::SetCurPos.
int EncodeSeTC_ResAchievementDat(const SeTC_ResAchievementDat &kData, char *pcBuf, int iMaxLen)
References SeTC_ResAchievementDat::akAchevementDat, SeTC_ResAchievementDat::dwPlayerID, EncodeSeTC_ResAchievementDat, SeTC_ResAchievementDat::iMaxPage, SeTC_ResAchievementDat::iNum, SeTC_ResAchievementDat::iPage.
Referenced by EncodeSeTC_ResAchievementDat.
int EncodeSeTC_ResAchievementDat(DWord dwPlayerID, int iPage, int iMaxPage, int iNum, const SeAchievementPtlDat *akAchevementDat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeAchievementPtlDat, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ResAchievementDat(DWord dwPlayerID, int iPage, int iMaxPage, int iNum, std::vector< SeAchievementPtlDat > &akAchevementDat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeAchievementPtlDat, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ResAchievementDat(const char *pkData, int iLen, SeTC_ResAchievementDat &kStruct)
References SeTC_ResAchievementDat::akAchevementDat, SeNetStream::Attach, DecodeSeAchievementPtlDat, SeTC_ResAchievementDat::dwPlayerID, SeNetStream::GetCurPos, SeTC_ResAchievementDat::iMaxPage, SeTC_ResAchievementDat::iNum, SeTC_ResAchievementDat::iPage, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_ResAchievementCounts(const SeTC_ResAchievementCounts &kData, char *pcBuf, int iMaxLen)
References SeTC_ResAchievementCounts::akAchevementCounts, SeTC_ResAchievementCounts::dwPlayerID, EncodeSeTC_ResAchievementCounts, SeTC_ResAchievementCounts::iNum.
Referenced by EncodeSeTC_ResAchievementCounts.
int EncodeSeTC_ResAchievementCounts(DWord dwPlayerID, int iNum, const SeAchievementCounts *akAchevementCounts, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeAchievementCounts, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ResAchievementCounts(DWord dwPlayerID, int iNum, std::vector< SeAchievementCounts > &akAchevementCounts, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeAchievementCounts, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ResAchievementCounts(const char *pkData, int iLen, SeTC_ResAchievementCounts &kStruct)
References SeTC_ResAchievementCounts::akAchevementCounts, SeNetStream::Attach, DecodeSeAchievementCounts, SeTC_ResAchievementCounts::dwPlayerID, SeNetStream::GetCurPos, SeTC_ResAchievementCounts::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_GetAchievement(const SeTC_GetAchievement &kData, char *pcBuf, int iMaxLen)
References SeTC_GetAchievement::a_ID, SeTC_GetAchievement::dwPlayerID, EncodeSeTC_GetAchievement, SeTC_GetAchievement::GetTime.
Referenced by EncodeSeTC_GetAchievement.
int EncodeSeTC_GetAchievement(DWord dwPlayerID, DWord a_ID, int GetTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_GetAchievement(const char *pkData, int iLen, SeTC_GetAchievement &kStruct)
References SeTC_GetAchievement::a_ID, SeNetStream::Attach, SeTC_GetAchievement::dwPlayerID, SeNetStream::GetCurPos, SeTC_GetAchievement::GetTime, SeNetStream::Read.
int EncodeSeTC_ResView(const SeTC_ResView &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_ResView, SeTC_ResView::kViewAddr, SeTC_ResView::rID.
Referenced by EncodeSeTC_ResView.
int EncodeSeTC_ResView(const Byte *rID, const SePtlNetAddr &kViewAddr, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlNetAddr, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ResView(std::vector< Byte > &rID, const SePtlNetAddr &kViewAddr, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlNetAddr, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ResView(const char *pkData, int iLen, SeTC_ResView &kStruct)
References SeNetStream::Attach, DecodeSePtlNetAddr, SeNetStream::GetCurPos, SeTC_ResView::kViewAddr, SeNetStream::Read, SeTC_ResView::rID, SeNetStream::SetCurPos.
int EncodeSeTC_ResViewList(const SeTC_ResViewList &kData, char *pcBuf, int iMaxLen)
References SeTC_ResViewList::akSeViewList, EncodeSeTC_ResViewList, SeTC_ResViewList::iMaxPage, SeTC_ResViewList::iNum, SeTC_ResViewList::iPage.
Referenced by EncodeSeTC_ResViewList.
int EncodeSeTC_ResViewList(int iPage, int iMaxPage, int iNum, const SeViewList *akSeViewList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeViewList, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ResViewList(int iPage, int iMaxPage, int iNum, std::vector< SeViewList > &akSeViewList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeViewList, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ResViewList(const char *pkData, int iLen, SeTC_ResViewList &kStruct)
References SeTC_ResViewList::akSeViewList, SeNetStream::Attach, DecodeSeViewList, SeNetStream::GetCurPos, SeTC_ResViewList::iMaxPage, SeTC_ResViewList::iNum, SeTC_ResViewList::iPage, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_PlayerNewItem(const SeTC_PlayerNewItem &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_PlayerNewItem, SeTC_PlayerNewItem::iNum, SeTC_PlayerNewItem::SeItemArray.
Referenced by EncodeSeTC_PlayerNewItem.
int EncodeSeTC_PlayerNewItem(int iNum, const SeItemNoti *SeItemArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeItemNoti, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_PlayerNewItem(int iNum, std::vector< SeItemNoti > &SeItemArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeItemNoti, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_PlayerNewItem(const char *pkData, int iLen, SeTC_PlayerNewItem &kStruct)
References SeNetStream::Attach, DecodeSeItemNoti, SeNetStream::GetCurPos, SeTC_PlayerNewItem::iNum, SeNetStream::Read, SeTC_PlayerNewItem::SeItemArray, SeNetStream::SetCurPos.
int EncodeSeTC_PlayerOperRep(const SeTC_PlayerOperRep &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_PlayerOperRep, SeTC_PlayerOperRep::iResult.
Referenced by EncodeSeTC_PlayerOperRep.
int EncodeSeTC_PlayerOperRep(int iResult, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_PlayerOperRep(const char *pkData, int iLen, SeTC_PlayerOperRep &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeTC_PlayerOperRep::iResult, SeNetStream::Read.
int EncodeSeTC_OpenRandBoxRet(const SeTC_OpenRandBoxRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_OpenRandBoxRet, SeTC_OpenRandBoxRet::iNum, SeTC_OpenRandBoxRet::iResult, SeTC_OpenRandBoxRet::ItemArray.
Referenced by EncodeSeTC_OpenRandBoxRet.
int EncodeSeTC_OpenRandBoxRet(int iResult, int iNum, const SeRandBoxItem *ItemArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRandBoxItem, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_OpenRandBoxRet(int iResult, int iNum, std::vector< SeRandBoxItem > &ItemArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRandBoxItem, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_OpenRandBoxRet(const char *pkData, int iLen, SeTC_OpenRandBoxRet &kStruct)
References SeNetStream::Attach, DecodeSeRandBoxItem, SeNetStream::GetCurPos, SeTC_OpenRandBoxRet::iNum, SeTC_OpenRandBoxRet::iResult, SeTC_OpenRandBoxRet::ItemArray, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_PutOnEquipRet(const SeTC_PutOnEquipRet &kData, char *pcBuf, int iMaxLen)
References SeTC_PutOnEquipRet::dwItemID, EncodeSeTC_PutOnEquipRet, SeTC_PutOnEquipRet::iResult, SeTC_PutOnEquipRet::wEquipPos.
Referenced by EncodeSeTC_PutOnEquipRet.
int EncodeSeTC_PutOnEquipRet(int iResult, Word wEquipPos, DWord dwItemID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_PutOnEquipRet(const char *pkData, int iLen, SeTC_PutOnEquipRet &kStruct)
References SeNetStream::Attach, SeTC_PutOnEquipRet::dwItemID, SeNetStream::GetCurPos, SeTC_PutOnEquipRet::iResult, SeNetStream::Read, SeTC_PutOnEquipRet::wEquipPos.
int EncodeSeTC_TakeOffEquipRet(const SeTC_TakeOffEquipRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_TakeOffEquipRet, SeTC_TakeOffEquipRet::iResult, SeTC_TakeOffEquipRet::wEquipPos.
Referenced by EncodeSeTC_TakeOffEquipRet.
int EncodeSeTC_TakeOffEquipRet(int iResult, Word wEquipPos, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_TakeOffEquipRet(const char *pkData, int iLen, SeTC_TakeOffEquipRet &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeTC_TakeOffEquipRet::iResult, SeNetStream::Read, SeTC_TakeOffEquipRet::wEquipPos.
int EncodeSeTC_ResRaceDetailInfo(const SeTC_ResRaceDetailInfo &kData, char *pcBuf, int iMaxLen)
References SeTC_ResRaceDetailInfo::akRaceDetailInfo, EncodeSeTC_ResRaceDetailInfo, SeTC_ResRaceDetailInfo::iNum, SeTC_ResRaceDetailInfo::page_max_number, SeTC_ResRaceDetailInfo::page_number.
Referenced by EncodeSeTC_ResRaceDetailInfo.
int EncodeSeTC_ResRaceDetailInfo(int page_number, int page_max_number, int iNum, const SeRaceDetailInfo *akRaceDetailInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceDetailInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_ResRaceDetailInfo(int page_number, int page_max_number, int iNum, std::vector< SeRaceDetailInfo > &akRaceDetailInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceDetailInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ResRaceDetailInfo(const char *pkData, int iLen, SeTC_ResRaceDetailInfo &kStruct)
References SeTC_ResRaceDetailInfo::akRaceDetailInfo, SeNetStream::Attach, DecodeSeRaceDetailInfo, SeNetStream::GetCurPos, SeTC_ResRaceDetailInfo::iNum, SeTC_ResRaceDetailInfo::page_max_number, SeTC_ResRaceDetailInfo::page_number, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_PlayerMoneyAndDiamond(const SeTC_PlayerMoneyAndDiamond &kData, char *pcBuf, int iMaxLen)
References SeTC_PlayerMoneyAndDiamond::dwDiamond, SeTC_PlayerMoneyAndDiamond::dwGold, SeTC_PlayerMoneyAndDiamond::dwPlayerID, EncodeSeTC_PlayerMoneyAndDiamond.
Referenced by EncodeSeTC_PlayerMoneyAndDiamond.
int EncodeSeTC_PlayerMoneyAndDiamond(DWord dwPlayerID, DWord dwGold, DWord dwDiamond, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_PlayerMoneyAndDiamond(const char *pkData, int iLen, SeTC_PlayerMoneyAndDiamond &kStruct)
References SeNetStream::Attach, SeTC_PlayerMoneyAndDiamond::dwDiamond, SeTC_PlayerMoneyAndDiamond::dwGold, SeTC_PlayerMoneyAndDiamond::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_ShopItemGmRep(const SeTC_ShopItemGmRep &kData, char *pcBuf, int iMaxLen)
References SeTC_ShopItemGmRep::dwPlayerID, EncodeSeTC_ShopItemGmRep, SeTC_ShopItemGmRep::GmItem, SeTC_ShopItemGmRep::iResult.
Referenced by EncodeSeTC_ShopItemGmRep.
int EncodeSeTC_ShopItemGmRep(DWord dwPlayerID, int iResult, const ShopItem &GmItem, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeShopItem, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_ShopItemGmRep(const char *pkData, int iLen, SeTC_ShopItemGmRep &kStruct)
References SeNetStream::Attach, DecodeShopItem, SeTC_ShopItemGmRep::dwPlayerID, SeNetStream::GetCurPos, SeTC_ShopItemGmRep::GmItem, SeTC_ShopItemGmRep::iResult, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_NexusFriendDetailInfoRes(const SeTC_NexusFriendDetailInfoRes &kData, char *pcBuf, int iMaxLen)
References SeTC_NexusFriendDetailInfoRes::akNexusFriendInfo, EncodeSeTC_NexusFriendDetailInfoRes, SeTC_NexusFriendDetailInfoRes::iNum, SeTC_NexusFriendDetailInfoRes::page_max_number, SeTC_NexusFriendDetailInfoRes::page_number.
Referenced by EncodeSeTC_NexusFriendDetailInfoRes.
int EncodeSeTC_NexusFriendDetailInfoRes(int page_number, int page_max_number, int iNum, const SeNexusPlayerInfo *akNexusFriendInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusPlayerInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_NexusFriendDetailInfoRes(int page_number, int page_max_number, int iNum, std::vector< SeNexusPlayerInfo > &akNexusFriendInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusPlayerInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_NexusFriendDetailInfoRes(const char *pkData, int iLen, SeTC_NexusFriendDetailInfoRes &kStruct)
References SeTC_NexusFriendDetailInfoRes::akNexusFriendInfo, SeNetStream::Attach, DecodeSeNexusPlayerInfo, SeNetStream::GetCurPos, SeTC_NexusFriendDetailInfoRes::iNum, SeTC_NexusFriendDetailInfoRes::page_max_number, SeTC_NexusFriendDetailInfoRes::page_number, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_NexusUserPromotionDetailInfoRes(const SeTC_NexusUserPromotionDetailInfoRes &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_NexusUserPromotionDetailInfoRes, SeTC_NexusUserPromotionDetailInfoRes::nexus_user_promotion.
Referenced by EncodeSeTC_NexusUserPromotionDetailInfoRes.
int EncodeSeTC_NexusUserPromotionDetailInfoRes(const SeNexusUserPromotionInfo &nexus_user_promotion, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusUserPromotionInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_NexusUserPromotionDetailInfoRes(const char *pkData, int iLen, SeTC_NexusUserPromotionDetailInfoRes &kStruct)
References SeNetStream::Attach, DecodeSeNexusUserPromotionInfo, SeNetStream::GetCurPos, SeTC_NexusUserPromotionDetailInfoRes::nexus_user_promotion, SeNetStream::SetCurPos.
int EncodeSeTC_SearchUserArchivesInfoRes(const SeTC_SearchUserArchivesInfoRes &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_SearchUserArchivesInfoRes, SeTC_SearchUserArchivesInfoRes::user_archives_info.
Referenced by EncodeSeTC_SearchUserArchivesInfoRes.
int EncodeSeTC_SearchUserArchivesInfoRes(const SeUserArchivesInfo &user_archives_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserArchivesInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_SearchUserArchivesInfoRes(const char *pkData, int iLen, SeTC_SearchUserArchivesInfoRes &kStruct)
References SeNetStream::Attach, DecodeSeUserArchivesInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeTC_SearchUserArchivesInfoRes::user_archives_info.
int EncodeSeTC_SearchUserArchivesDetailInfoRes(const SeTC_SearchUserArchivesDetailInfoRes &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_SearchUserArchivesDetailInfoRes, SeTC_SearchUserArchivesDetailInfoRes::user_archives_info.
Referenced by EncodeSeTC_SearchUserArchivesDetailInfoRes.
int EncodeSeTC_SearchUserArchivesDetailInfoRes(const SeUserArchivesInfo &user_archives_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserArchivesInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_SearchUserArchivesDetailInfoRes(const char *pkData, int iLen, SeTC_SearchUserArchivesDetailInfoRes &kStruct)
References SeNetStream::Attach, DecodeSeUserArchivesInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeTC_SearchUserArchivesDetailInfoRes::user_archives_info.
int EncodeSeTC_NexusUserActionSync(const SeTC_NexusUserActionSync &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_NexusUserActionSync, SeTC_NexusUserActionSync::sync_info.
Referenced by EncodeSeTC_NexusUserActionSync.
int EncodeSeTC_NexusUserActionSync(const SeNexusUserInfo &sync_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusUserInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_NexusUserActionSync(const char *pkData, int iLen, SeTC_NexusUserActionSync &kStruct)
References SeNetStream::Attach, DecodeSeNexusUserInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeTC_NexusUserActionSync::sync_info.
int EncodeSeTC_ReqMatchRep(const SeTC_ReqMatchRep &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_ReqMatchRep, SeTC_ReqMatchRep::ReqResult.
Referenced by EncodeSeTC_ReqMatchRep.
int EncodeSeTC_ReqMatchRep(MatchReqResult ReqResult, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_ReqMatchRep(const char *pkData, int iLen, SeTC_ReqMatchRep &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeTC_ReqMatchRep::ReqResult.
int EncodeSeTC_CancelMatchRep(const SeTC_CancelMatchRep &kData, char *pcBuf, int iMaxLen)
References SeTC_CancelMatchRep::CancelResult, SeTC_CancelMatchRep::dwPlayerID, EncodeSeTC_CancelMatchRep.
Referenced by EncodeSeTC_CancelMatchRep.
int EncodeSeTC_CancelMatchRep(MatchCancelResult CancelResult, DWord dwPlayerID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_CancelMatchRep(const char *pkData, int iLen, SeTC_CancelMatchRep &kStruct)
References SeNetStream::Attach, SeTC_CancelMatchRep::CancelResult, SeTC_CancelMatchRep::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_NotiMatcherPre(const SeTC_NotiMatcherPre &kData, char *pcBuf, int iMaxLen)
References SeTC_NotiMatcherPre::dwPlayerNum, EncodeSeTC_NotiMatcherPre, SeTC_NotiMatcherPre::WaitID.
Referenced by EncodeSeTC_NotiMatcherPre.
int EncodeSeTC_NotiMatcherPre(DWord WaitID, DWord dwPlayerNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_NotiMatcherPre(const char *pkData, int iLen, SeTC_NotiMatcherPre &kStruct)
References SeNetStream::Attach, SeTC_NotiMatcherPre::dwPlayerNum, SeNetStream::GetCurPos, SeNetStream::Read, SeTC_NotiMatcherPre::WaitID.
int EncodeSeTC_NotiMatcherResult(const SeTC_NotiMatcherResult &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_NotiMatcherResult, SeTC_NotiMatcherResult::ResultKind.
Referenced by EncodeSeTC_NotiMatcherResult.
int EncodeSeTC_NotiMatcherResult(DWord ResultKind, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_NotiMatcherResult(const char *pkData, int iLen, SeTC_NotiMatcherResult &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeTC_NotiMatcherResult::ResultKind.
int EncodeSeTC_SingleMatchConfirm(const SeTC_SingleMatchConfirm &kData, char *pcBuf, int iMaxLen)
References SeTC_SingleMatchConfirm::BolConfirm, EncodeSeTC_SingleMatchConfirm, SeTC_SingleMatchConfirm::MaxPlayerNum, SeTC_SingleMatchConfirm::PlayerID, SeTC_SingleMatchConfirm::PlayerIndex.
Referenced by EncodeSeTC_SingleMatchConfirm.
int EncodeSeTC_SingleMatchConfirm(DWord PlayerID, bool BolConfirm, DWord PlayerIndex, DWord MaxPlayerNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_SingleMatchConfirm(const char *pkData, int iLen, SeTC_SingleMatchConfirm &kStruct)
References SeNetStream::Attach, SeTC_SingleMatchConfirm::BolConfirm, SeNetStream::GetCurPos, SeTC_SingleMatchConfirm::MaxPlayerNum, SeTC_SingleMatchConfirm::PlayerID, SeTC_SingleMatchConfirm::PlayerIndex, SeNetStream::Read.
int EncodeSeTC_SeUserRaceArenaDetailInfoRes(const SeTC_SeUserRaceArenaDetailInfoRes &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_SeUserRaceArenaDetailInfoRes, SeTC_SeUserRaceArenaDetailInfoRes::race_arena_info.
Referenced by EncodeSeTC_SeUserRaceArenaDetailInfoRes.
int EncodeSeTC_SeUserRaceArenaDetailInfoRes(const SeRaceEndArenaResult &race_arena_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceEndArenaResult, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_SeUserRaceArenaDetailInfoRes(const char *pkData, int iLen, SeTC_SeUserRaceArenaDetailInfoRes &kStruct)
References SeNetStream::Attach, DecodeSeRaceEndArenaResult, SeNetStream::GetCurPos, SeTC_SeUserRaceArenaDetailInfoRes::race_arena_info, SeNetStream::SetCurPos.
int EncodeSeTC_TeamChangeSync(const SeTC_TeamChangeSync &kData, char *pcBuf, int iMaxLen)
References SeTC_TeamChangeSync::acLeaderName, SeTC_TeamChangeSync::dwLeaderID, SeTC_TeamChangeSync::dwTeamID, EncodeSeTC_TeamChangeSync.
Referenced by EncodeSeTC_TeamChangeSync.
int EncodeSeTC_TeamChangeSync(DWord dwTeamID, DWord dwLeaderID, const char *acLeaderName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_TeamChangeSync(const char *pkData, int iLen, SeTC_TeamChangeSync &kStruct)
References SeTC_TeamChangeSync::acLeaderName, SeNetStream::Attach, SeTC_TeamChangeSync::dwLeaderID, SeTC_TeamChangeSync::dwTeamID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeTC_TeamLeaderSync(const SeTC_TeamLeaderSync &kData, char *pcBuf, int iMaxLen)
References SeTC_TeamLeaderSync::acGuestName, SeTC_TeamLeaderSync::dwGuestID, SeTC_TeamLeaderSync::dwMark, EncodeSeTC_TeamLeaderSync.
Referenced by EncodeSeTC_TeamLeaderSync.
int EncodeSeTC_TeamLeaderSync(DWord dwGuestID, const char *acGuestName, DWord dwMark, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_TeamLeaderSync(const char *pkData, int iLen, SeTC_TeamLeaderSync &kStruct)
References SeTC_TeamLeaderSync::acGuestName, SeNetStream::Attach, SeTC_TeamLeaderSync::dwGuestID, SeTC_TeamLeaderSync::dwMark, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeTC_TeamMemberSync(const SeTC_TeamMemberSync &kData, char *pcBuf, int iMaxLen)
References SeTC_TeamMemberSync::acInviterName, SeTC_TeamMemberSync::dwInviterID, SeTC_TeamMemberSync::dwMark, SeTC_TeamMemberSync::dwTeamID, EncodeSeTC_TeamMemberSync.
Referenced by EncodeSeTC_TeamMemberSync.
int EncodeSeTC_TeamMemberSync(DWord dwTeamID, DWord dwInviterID, const char *acInviterName, DWord dwMark, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTC_TeamMemberSync(const char *pkData, int iLen, SeTC_TeamMemberSync &kStruct)
References SeTC_TeamMemberSync::acInviterName, SeNetStream::Attach, SeTC_TeamMemberSync::dwInviterID, SeTC_TeamMemberSync::dwMark, SeTC_TeamMemberSync::dwTeamID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeTC_TeamUserStateRes(const SeTC_TeamUserStateRes &kData, char *pcBuf, int iMaxLen)
References SeTC_TeamUserStateRes::dwStateID, EncodeSeTC_TeamUserStateRes.
Referenced by EncodeSeTC_TeamUserStateRes.
int EncodeSeTC_TeamUserStateRes(DWord dwStateID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_TeamUserStateRes(const char *pkData, int iLen, SeTC_TeamUserStateRes &kStruct)
References SeNetStream::Attach, SeTC_TeamUserStateRes::dwStateID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_TeamMemberInfoRes(const SeTC_TeamMemberInfoRes &kData, char *pcBuf, int iMaxLen)
References SeTC_TeamMemberInfoRes::dwTeamID, EncodeSeTC_TeamMemberInfoRes, SeTC_TeamMemberInfoRes::iNum, SeTC_TeamMemberInfoRes::member_info.
Referenced by EncodeSeTC_TeamMemberInfoRes.
int EncodeSeTC_TeamMemberInfoRes(DWord dwTeamID, int iNum, const SeTeamMemberBaseInfo *member_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeTeamMemberBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_TeamMemberInfoRes(DWord dwTeamID, int iNum, std::vector< SeTeamMemberBaseInfo > &member_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeTeamMemberBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_TeamMemberInfoRes(const char *pkData, int iLen, SeTC_TeamMemberInfoRes &kStruct)
References SeNetStream::Attach, DecodeSeTeamMemberBaseInfo, SeTC_TeamMemberInfoRes::dwTeamID, SeNetStream::GetCurPos, SeTC_TeamMemberInfoRes::iNum, SeTC_TeamMemberInfoRes::member_info, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_UserHeroSync(const SeTC_UserHeroSync &kData, char *pcBuf, int iMaxLen)
References SeTC_UserHeroSync::akHeroSyncInfo, SeTC_UserHeroSync::dwPlayerID, EncodeSeTC_UserHeroSync, SeTC_UserHeroSync::num.
Referenced by EncodeSeTC_UserHeroSync.
int EncodeSeTC_UserHeroSync(DWord dwPlayerID, int num, const SeUserHeroSyncInfo *akHeroSyncInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserHeroSyncInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_UserHeroSync(DWord dwPlayerID, int num, std::vector< SeUserHeroSyncInfo > &akHeroSyncInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserHeroSyncInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_UserHeroSync(const char *pkData, int iLen, SeTC_UserHeroSync &kStruct)
References SeTC_UserHeroSync::akHeroSyncInfo, SeNetStream::Attach, DecodeSeUserHeroSyncInfo, SeTC_UserHeroSync::dwPlayerID, SeNetStream::GetCurPos, SeTC_UserHeroSync::num, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_NexusFriendStatusSync(const SeTC_NexusFriendStatusSync &kData, char *pcBuf, int iMaxLen)
References SeTC_NexusFriendStatusSync::dwFriendID, SeTC_NexusFriendStatusSync::dwOnlineID, EncodeSeTC_NexusFriendStatusSync.
Referenced by EncodeSeTC_NexusFriendStatusSync.
int EncodeSeTC_NexusFriendStatusSync(DWord dwFriendID, DWord dwOnlineID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_NexusFriendStatusSync(const char *pkData, int iLen, SeTC_NexusFriendStatusSync &kStruct)
References SeNetStream::Attach, SeTC_NexusFriendStatusSync::dwFriendID, SeTC_NexusFriendStatusSync::dwOnlineID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_PlayerLadder(const SeTC_PlayerLadder &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_PlayerLadder, SeTC_PlayerLadder::kLadder.
Referenced by EncodeSeTC_PlayerLadder.
int EncodeSeTC_PlayerLadder(const SeLadderInfo &kLadder, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeLadderInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_PlayerLadder(const char *pkData, int iLen, SeTC_PlayerLadder &kStruct)
References SeNetStream::Attach, DecodeSeLadderInfo, SeNetStream::GetCurPos, SeTC_PlayerLadder::kLadder, SeNetStream::SetCurPos.
int EncodeSeTC_NexusFriendLimitRes(const SeTC_NexusFriendLimitRes &kData, char *pcBuf, int iMaxLen)
References SeTC_NexusFriendLimitRes::dwLimitID, EncodeSeTC_NexusFriendLimitRes.
Referenced by EncodeSeTC_NexusFriendLimitRes.
int EncodeSeTC_NexusFriendLimitRes(DWord dwLimitID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_NexusFriendLimitRes(const char *pkData, int iLen, SeTC_NexusFriendLimitRes &kStruct)
References SeNetStream::Attach, SeTC_NexusFriendLimitRes::dwLimitID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_NexusFriendCleanRefuseNoticeRes(const SeTC_NexusFriendCleanRefuseNoticeRes &kData, char *pcBuf, int iMaxLen)
References SeTC_NexusFriendCleanRefuseNoticeRes::dwGuestID, EncodeSeTC_NexusFriendCleanRefuseNoticeRes.
Referenced by EncodeSeTC_NexusFriendCleanRefuseNoticeRes.
int EncodeSeTC_NexusFriendCleanRefuseNoticeRes(DWord dwGuestID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_NexusFriendCleanRefuseNoticeRes(const char *pkData, int iLen, SeTC_NexusFriendCleanRefuseNoticeRes &kStruct)
References SeNetStream::Attach, SeTC_NexusFriendCleanRefuseNoticeRes::dwGuestID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_UserStatusQueryReqRes(const SeTC_UserStatusQueryReqRes &kData, char *pcBuf, int iMaxLen)
References SeTC_UserStatusQueryReqRes::base_info, EncodeSeTC_UserStatusQueryReqRes, SeTC_UserStatusQueryReqRes::iNum.
Referenced by EncodeSeTC_UserStatusQueryReqRes.
int EncodeSeTC_UserStatusQueryReqRes(int iNum, const SeUserStatusBaseInfo *base_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserStatusBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_UserStatusQueryReqRes(int iNum, std::vector< SeUserStatusBaseInfo > &base_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserStatusBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_UserStatusQueryReqRes(const char *pkData, int iLen, SeTC_UserStatusQueryReqRes &kStruct)
References SeNetStream::Attach, SeTC_UserStatusQueryReqRes::base_info, DecodeSeUserStatusBaseInfo, SeNetStream::GetCurPos, SeTC_UserStatusQueryReqRes::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_EquipSchema(const SeTC_EquipSchema &kData, char *pcBuf, int iMaxLen)
References SeTC_EquipSchema::akEquips, EncodeSeTC_EquipSchema, SeTC_EquipSchema::iNum.
Referenced by EncodeSeTC_EquipSchema.
int EncodeSeTC_EquipSchema(int iNum, const SeEquipSchemaInfo *akEquips, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeEquipSchemaInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_EquipSchema(int iNum, std::vector< SeEquipSchemaInfo > &akEquips, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeEquipSchemaInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_EquipSchema(const char *pkData, int iLen, SeTC_EquipSchema &kStruct)
References SeTC_EquipSchema::akEquips, SeNetStream::Attach, DecodeSeEquipSchemaInfo, SeNetStream::GetCurPos, SeTC_EquipSchema::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_LadderRankQueryAck(const SeTC_LadderRankQueryAck &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_LadderRankQueryAck, SeTC_LadderRankQueryAck::iNum, SeTC_LadderRankQueryAck::RankList.
Referenced by EncodeSeTC_LadderRankQueryAck.
int EncodeSeTC_LadderRankQueryAck(int iNum, const SeLadderRankInfo *RankList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeLadderRankInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_LadderRankQueryAck(int iNum, std::vector< SeLadderRankInfo > &RankList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeLadderRankInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_LadderRankQueryAck(const char *pkData, int iLen, SeTC_LadderRankQueryAck &kStruct)
References SeNetStream::Attach, DecodeSeLadderRankInfo, SeNetStream::GetCurPos, SeTC_LadderRankQueryAck::iNum, SeTC_LadderRankQueryAck::RankList, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_FriendLadderInfoNtf(const SeTC_FriendLadderInfoNtf &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_FriendLadderInfoNtf, SeTC_FriendLadderInfoNtf::iNum, SeTC_FriendLadderInfoNtf::RankList.
Referenced by EncodeSeTC_FriendLadderInfoNtf.
int EncodeSeTC_FriendLadderInfoNtf(int iNum, const SeLadderRankInfo *RankList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeLadderRankInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_FriendLadderInfoNtf(int iNum, std::vector< SeLadderRankInfo > &RankList, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeLadderRankInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_FriendLadderInfoNtf(const char *pkData, int iLen, SeTC_FriendLadderInfoNtf &kStruct)
References SeNetStream::Attach, DecodeSeLadderRankInfo, SeNetStream::GetCurPos, SeTC_FriendLadderInfoNtf::iNum, SeTC_FriendLadderInfoNtf::RankList, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_UserRaceMapHeroAck(const SeTC_UserRaceMapHeroAck &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_UserRaceMapHeroAck, SeTC_UserRaceMapHeroAck::hero_info, SeTC_UserRaceMapHeroAck::iNum.
Referenced by EncodeSeTC_UserRaceMapHeroAck.
int EncodeSeTC_UserRaceMapHeroAck(int iNum, const SeUserRaceMapHeroBase *hero_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserRaceMapHeroBase, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_UserRaceMapHeroAck(int iNum, std::vector< SeUserRaceMapHeroBase > &hero_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserRaceMapHeroBase, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_UserRaceMapHeroAck(const char *pkData, int iLen, SeTC_UserRaceMapHeroAck &kStruct)
References SeNetStream::Attach, DecodeSeUserRaceMapHeroBase, SeNetStream::GetCurPos, SeTC_UserRaceMapHeroAck::hero_info, SeTC_UserRaceMapHeroAck::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeTC_SetActiveAvatarAck(const SeTC_SetActiveAvatarAck &kData, char *pcBuf, int iMaxLen)
References SeTC_SetActiveAvatarAck::dwItemID, EncodeSeTC_SetActiveAvatarAck, SeTC_SetActiveAvatarAck::iResult.
Referenced by EncodeSeTC_SetActiveAvatarAck.
int EncodeSeTC_SetActiveAvatarAck(int iResult, DWord dwItemID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_SetActiveAvatarAck(const char *pkData, int iLen, SeTC_SetActiveAvatarAck &kStruct)
References SeNetStream::Attach, SeTC_SetActiveAvatarAck::dwItemID, SeNetStream::GetCurPos, SeTC_SetActiveAvatarAck::iResult, SeNetStream::Read.
int EncodeSeTC_ActiveAvatarNtf(const SeTC_ActiveAvatarNtf &kData, char *pcBuf, int iMaxLen)
References SeTC_ActiveAvatarNtf::avartars, EncodeSeTC_ActiveAvatarNtf, SeTC_ActiveAvatarNtf::iNum.
Referenced by EncodeSeTC_ActiveAvatarNtf.
int EncodeSeTC_ActiveAvatarNtf(int iNum, const DWord *avartars, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeTC_ActiveAvatarNtf(int iNum, std::vector< DWord > &avartars, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_ActiveAvatarNtf(const char *pkData, int iLen, SeTC_ActiveAvatarNtf &kStruct)
References SeNetStream::Attach, SeTC_ActiveAvatarNtf::avartars, SeNetStream::GetCurPos, SeTC_ActiveAvatarNtf::iNum, SeNetStream::Read.
int EncodeSeTC_UserAlterNickNameAck(const SeTC_UserAlterNickNameAck &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_UserAlterNickNameAck, SeTC_UserAlterNickNameAck::iResult.
Referenced by EncodeSeTC_UserAlterNickNameAck.
int EncodeSeTC_UserAlterNickNameAck(int iResult, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_UserAlterNickNameAck(const char *pkData, int iLen, SeTC_UserAlterNickNameAck &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeTC_UserAlterNickNameAck::iResult, SeNetStream::Read.
int EncodeSeTC_UserAlterAvatarAndFrameNtf(const SeTC_UserAlterAvatarAndFrameNtf &kData, char *pcBuf, int iMaxLen)
References SeTC_UserAlterAvatarAndFrameNtf::dwAvatarFrameID, SeTC_UserAlterAvatarAndFrameNtf::dwAvatarID, EncodeSeTC_UserAlterAvatarAndFrameNtf.
Referenced by EncodeSeTC_UserAlterAvatarAndFrameNtf.
int EncodeSeTC_UserAlterAvatarAndFrameNtf(DWord dwAvatarID, DWord dwAvatarFrameID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeTC_UserAlterAvatarAndFrameNtf(const char *pkData, int iLen, SeTC_UserAlterAvatarAndFrameNtf &kStruct)
References SeNetStream::Attach, SeTC_UserAlterAvatarAndFrameNtf::dwAvatarFrameID, SeTC_UserAlterAvatarAndFrameNtf::dwAvatarID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeTC_LadderDetailInfoAck(const SeTC_LadderDetailInfoAck &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_LadderDetailInfoAck, SeTC_LadderDetailInfoAck::info.
Referenced by EncodeSeTC_LadderDetailInfoAck.
int EncodeSeTC_LadderDetailInfoAck(const SeLadderDetailInfo &info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeLadderDetailInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeTC_LadderDetailInfoAck(const char *pkData, int iLen, SeTC_LadderDetailInfoAck &kStruct)
References SeNetStream::Attach, DecodeSeLadderDetailInfo, SeNetStream::GetCurPos, SeTC_LadderDetailInfoAck::info, SeNetStream::SetCurPos.
int EncodeSeTC_AchieveInfoAck(const SeTC_AchieveInfoAck &kData, char *pcBuf, int iMaxLen)
References EncodeSeTC_AchieveInfoAck, SeTC_AchieveInfoAck::finishInfo, SeTC_AchieveInfoAck::iNum1, SeTC_AchieveInfoAck::iNum2, SeTC_AchieveInfoAck::scheduleInfo.
Referenced by EncodeSeTC_AchieveInfoAck.
int EncodeSeTC_AchieveInfoAck(int iNum1, const SeAchieveFinish *finishInfo, int iNum2, const SeAchieveSchedule *scheduleInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeAchieveFinish, EncodeSeAchieveSchedule, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeTC_AchieveInfoAck(int iNum1, std::vector< SeAchieveFinish > &finishInfo, int iNum2, std::vector< SeAchieveSchedule > &scheduleInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeAchieveFinish, EncodeSeAchieveSchedule, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeTC_AchieveInfoAck(const char *pkData, int iLen, SeTC_AchieveInfoAck &kStruct)
References SeNetStream::Attach, DecodeSeAchieveFinish, DecodeSeAchieveSchedule, SeTC_AchieveInfoAck::finishInfo, SeNetStream::GetCurPos, SeTC_AchieveInfoAck::iNum1, SeTC_AchieveInfoAck::iNum2, SeNetStream::Read, SeTC_AchieveInfoAck::scheduleInfo, SeNetStream::SetCurPos.