SeServerTool.h
void SPrintf(char *pcDst, size_t iDstSize, const char *format,...)
References StrCpy.
Referenced by SeFileLog::__CheckLog, CallWindowBat, SeRaceMgr::CreateRobotRace, TcpServer::DisconnectPlayerSock, TownServer::DisconnectTcpUser, DBServer::Finialize, GlobalServer::GenGameAccount, PlayerDataStrategy::getInitGenIDSql, WorldServer::GetRaceAreaInfo, SeFileLog::Initialize, WorldServer::InitLeagueInfo, MatchServer::InitRaceBetInfo, IntToStr, GlobalServer::LoadDynamicConfig, SeRaceMgr::LocalCheckEnd_Guanqia, SeRaceMgr::LocalCheckEnd_Race, SeFileLog::Log, MyExceptionFilter, GlobalServer::OnLoginQueryRet, DBServer::OnPrintfNetState, SeRaceMgr::OnRaceModeEnd, MatchServer::PrintUpdateTime, DBServer::PrintUpdateTime, WorldServer::ProcessBW_InitGenIDRet, DBServer::ProcessDB_ChraRenameEndQuery, GlobalServer::ProcessLG_PlayerLogin, DBServer::ProcessWB_TabDelete, DBServer::ProcessWB_TabInsert, DBServer::ProcessWB_TabSelect, DBServer::ProcessWB_TabUpdate, HttpServer::ProcessWH_QueryFreeHeroList, SeRaceMgr::SaveAllRaceRecord, WorldServer::SaveLeagueInfo, MatchServer::SaveRaceBetInfo, SeRaceRecordSaveThread::saveRecord, WatchServer::SeRaceRecordSaveThread::saveRecord, DBServer::SaveSqlLog2File, SeDBVariant::SeDBVariant, GlobalServer::SendDB_AccountInitGenID, GlobalServer::SendDB_AccountInsertData, GlobalServer::SendDB_AccountQuery, GlobalServer::SendDB_AccountUpdateData, DBServer::SendDB_CharInfoAdd, DBServer::SendDB_CharLoginLoad, DBServer::SendDB_CharNexusFriendLoad, DBServer::SendDB_CharQueryValid, DBServer::SendDB_CharRenameBegin, DBServer::SendDB_CharRenameEnd, DBServer::SendDB_CharRenameEndQuery, DBServer::SendDB_FriendLadderInfoLoad, DBServer::SendDB_InitGenID, DBServer::SendDB_IsPlayerExistByID, DBServer::SendDB_IsPlayerExistByName, BackendServer::SendDB_Online_Num, BackendServer::SendDB_Race_Num, BackendServer::SendDB_User_Create, BackendServer::SendDB_User_Race, BackendServer::SendDB_User_Town, BackendServer::SendDB_User_Watch, BackendServer::SendDB_Watch_Num, SeRaceMgr::SendMatchAddrMsg, ServerMain, GlobalServer::ShowConsoleTitle, TcpServer::ShowConsoleTitle, LoginServer::ShowConsoleTitle, HttpServer::ShowConsoleTitle, NexusServer::ShowConsoleTitle, BackendServer::ShowConsoleTitle, TownServer::ShowConsoleTitle, WorldServer::ShowConsoleTitle, WatchServer::CWatchServer::ShowConsoleTitle, MatchServer::ShowConsoleTitle, RaceServer::ShowConsoleTitle, UintToStr, WorldServer::Update, SeRaceMgr::UpdateReconBegin, RaceServer::UpdateSaveThreadUpdateTime, DBServer::UpdateSqlLog2File.
void ParseSetupVal(VIntVec &rakInt, const char *pcValue, bool bNum=false)
References GetStr2ID, MemCpy, StrCpy.
const char* GetServerNameByIndex(int iIndex)
References SSI_NUM.
Referenced by SeVirtConnMgr::Connect, SeVirtConnMgr::HeartBeat, SeVirtConnMgr::OnClientDisconnect, SeVirtConnMgr::OnServerConnected, SeVirtConnMgr::OnServerDisconnect, SeVirtConnMgr::Register, moba::ServerSessionMgr::update, SeVirtConnMgr::UpdateClientConn.
bool MkDir(const char *pszDir)
References StrCpy.
Referenced by DBServer::Finialize, SeFileLog::Initialize, DBServer::LoadConfig, DBServer::SaveSqlLog2File, DBServer::UpdateSqlLog2File.
std::string IntToStr(int iValue)
References SPrintf.
std::string UintToStr(unsigned int uiValue)
References SPrintf.