SeMiniDump.h
void CreateDumpFilePath(char *pcFilePath)
Referenced by MyExceptionFilter.
LONG WINAPI MyExceptionFilter(EXCEPTION_POINTERS *pExp, DWord dwExceptionCode, DWord &dwExceptionFlag, char *pkDumName=NULL, bool bRecordDate=false, char *pkDumpDir=NULL)
References CallWindowBat, CreateDumpFilePath, GetLocalTime, SPrintf.
Referenced by ServerMain, RaceService::Update, BlockServer::Update.
void CallWindowBat(char *arg1, char *batName=NULL)
References SPrintf.
Referenced by MyExceptionFilter.