SeMiniDump.cpp
typedef bool(WINAPI * MINIDUMPWRITEDUMP)(IN HANDLE hProcess, IN DWord ProcessId, IN HANDLE hFile, IN MINIDUMP_TYPE DumpType, IN CONST PMINIDUMP_EXCEPTION_INFORMATION ExceptionParam, OPTIONAL IN CONST PMINIDUMP_USER_STREAM_INFORMATION UserStreamParam, OPTIONAL IN CONST PMINIDUMP_CALLBACK_INFORMATION CallbackParam OPTIONAL))(IN HANDLE hProcess, IN DWord ProcessId, IN HANDLE hFile, IN MINIDUMP_TYPE DumpType, IN CONST PMINIDUMP_EXCEPTION_INFORMATION ExceptionParam, OPTIONAL IN CONST PMINIDUMP_USER_STREAM_INFORMATION UserStreamParam, OPTIONAL IN CONST PMINIDUMP_CALLBACK_INFORMATION CallbackParam OPTIONAL)
void CreateDumpFilePath(char *pcFilePath)
Referenced by MyExceptionFilter.
void CallWindowBat(char *arg1, char *batName)
References SPrintf.
Referenced by MyExceptionFilter.
LONG WINAPI MyExceptionFilter(EXCEPTION_POINTERS *pExp, DWord dwExceptionCode, DWord &dwExceptionFlag, char *pkDumName, bool bRecordDate, char *pkDumpDir)
References CallWindowBat, CreateDumpFilePath, GetLocalTime, SPrintf.
Referenced by ServerMain, RaceService::Update, BlockServer::Update.