SeCRStream.h
int EncodeSeCR_HeartPackage(const SeCR_HeartPackage &kData, char *pcBuf, int iMaxLen)
References EncodeSeCR_HeartPackage.
Referenced by EncodeSeCR_HeartPackage.
int EncodeSeCR_HeartPackage(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCR_HeartPackage(const char *pkData, int iLen, SeCR_HeartPackage &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCR_RaceValidate(const SeCR_RaceValidate &kData, char *pcBuf, int iMaxLen)
References SeCR_RaceValidate::dwFrame, SeCR_RaceValidate::dwKey, SeCR_RaceValidate::dwPlayerID, SeCR_RaceValidate::dwSessionId, EncodeSeCR_RaceValidate, SeCR_RaceValidate::eValidType, SeCR_RaceValidate::iOffset, SeCR_RaceValidate::iSeat.
Referenced by EncodeSeCR_RaceValidate.
int EncodeSeCR_RaceValidate(DWord dwPlayerID, DWord dwSessionId, DWord dwKey, SeRaceValidType eValidType, int iSeat, int iOffset, DWord dwFrame, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_RaceValidate(const char *pkData, int iLen, SeCR_RaceValidate &kStruct)
References SeNetStream::Attach, SeCR_RaceValidate::dwFrame, SeCR_RaceValidate::dwKey, SeCR_RaceValidate::dwPlayerID, SeCR_RaceValidate::dwSessionId, SeCR_RaceValidate::eValidType, SeNetStream::GetCurPos, SeCR_RaceValidate::iOffset, SeCR_RaceValidate::iSeat, SeNetStream::Read.
int EncodeSeCR_RaceLoadEnd(const SeCR_RaceLoadEnd &kData, char *pcBuf, int iMaxLen)
References SeCR_RaceLoadEnd::dwRate, SeCR_RaceLoadEnd::eLoadType, EncodeSeCR_RaceLoadEnd.
Referenced by EncodeSeCR_RaceLoadEnd.
int EncodeSeCR_RaceLoadEnd(SeRaceLoadType eLoadType, DWord dwRate, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_RaceLoadEnd(const char *pkData, int iLen, SeCR_RaceLoadEnd &kStruct)
References SeNetStream::Attach, SeCR_RaceLoadEnd::dwRate, SeCR_RaceLoadEnd::eLoadType, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCR_RaceCmd(const SeCR_RaceCmd &kData, char *pcBuf, int iMaxLen)
References SeCR_RaceCmd::acData, EncodeSeCR_RaceCmd, SeCR_RaceCmd::iSize.
Referenced by EncodeSeCR_RaceCmd.
int EncodeSeCR_RaceCmd(int iSize, const char *acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeCR_RaceCmd(int iSize, std::vector< char > &acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_RaceCmd(const char *pkData, int iLen, SeCR_RaceCmd &kStruct)
References SeCR_RaceCmd::acData, SeNetStream::Attach, SeNetStream::GetCurPos, SeCR_RaceCmd::iSize, SeNetStream::Read.
int EncodeSeCR_RaceLeave(const SeCR_RaceLeave &kData, char *pcBuf, int iMaxLen)
References EncodeSeCR_RaceLeave.
Referenced by EncodeSeCR_RaceLeave.
int EncodeSeCR_RaceLeave(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCR_RaceLeave(const char *pkData, int iLen, SeCR_RaceLeave &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCR_RaceEndRace(const SeCR_RaceEndRace &kData, char *pcBuf, int iMaxLen)
References SeCR_RaceEndRace::akPlayerInfo, SeCR_RaceEndRace::bValid, SeCR_RaceEndRace::dwRaceTime, EncodeSeCR_RaceEndRace, SeCR_RaceEndRace::iMapID, SeCR_RaceEndRace::iNums.
Referenced by EncodeSeCR_RaceEndRace.
int EncodeSeCR_RaceEndRace(DWord dwRaceTime, int iMapID, bool bValid, int iNums, const SeRaceSendInfo *akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeCR_RaceEndRace(DWord dwRaceTime, int iMapID, bool bValid, int iNums, std::vector< SeRaceSendInfo > &akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeCR_RaceEndRace(const char *pkData, int iLen, SeCR_RaceEndRace &kStruct)
References SeCR_RaceEndRace::akPlayerInfo, SeNetStream::Attach, SeCR_RaceEndRace::bValid, DecodeSeRaceSendInfo, SeCR_RaceEndRace::dwRaceTime, SeNetStream::GetCurPos, SeCR_RaceEndRace::iMapID, SeCR_RaceEndRace::iNums, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeCR_RaceEndGuanqia(const SeCR_RaceEndGuanqia &kData, char *pcBuf, int iMaxLen)
References SeCR_RaceEndGuanqia::akPlayerInfo, SeCR_RaceEndGuanqia::bValid, SeCR_RaceEndGuanqia::dwRaceTime, EncodeSeCR_RaceEndGuanqia, SeCR_RaceEndGuanqia::iMapID, SeCR_RaceEndGuanqia::iNums.
Referenced by EncodeSeCR_RaceEndGuanqia.
int EncodeSeCR_RaceEndGuanqia(DWord dwRaceTime, int iMapID, bool bValid, int iNums, const SeGuanqiaSendInfo *akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeGuanqiaSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeCR_RaceEndGuanqia(DWord dwRaceTime, int iMapID, bool bValid, int iNums, std::vector< SeGuanqiaSendInfo > &akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeGuanqiaSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeCR_RaceEndGuanqia(const char *pkData, int iLen, SeCR_RaceEndGuanqia &kStruct)
References SeCR_RaceEndGuanqia::akPlayerInfo, SeNetStream::Attach, SeCR_RaceEndGuanqia::bValid, DecodeSeGuanqiaSendInfo, SeCR_RaceEndGuanqia::dwRaceTime, SeNetStream::GetCurPos, SeCR_RaceEndGuanqia::iMapID, SeCR_RaceEndGuanqia::iNums, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeCR_SelHeroChoiceHero(const SeCR_SelHeroChoiceHero &kData, char *pcBuf, int iMaxLen)
References SeCR_SelHeroChoiceHero::bDreamHero, SeCR_SelHeroChoiceHero::dwHeroCardID, EncodeSeCR_SelHeroChoiceHero.
Referenced by EncodeSeCR_SelHeroChoiceHero.
int EncodeSeCR_SelHeroChoiceHero(DWord dwHeroCardID, bool bDreamHero, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_SelHeroChoiceHero(const char *pkData, int iLen, SeCR_SelHeroChoiceHero &kStruct)
References SeNetStream::Attach, SeCR_SelHeroChoiceHero::bDreamHero, SeCR_SelHeroChoiceHero::dwHeroCardID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCR_SelHeroCancelHero(const SeCR_SelHeroCancelHero &kData, char *pcBuf, int iMaxLen)
References EncodeSeCR_SelHeroCancelHero.
Referenced by EncodeSeCR_SelHeroCancelHero.
int EncodeSeCR_SelHeroCancelHero(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCR_SelHeroCancelHero(const char *pkData, int iLen, SeCR_SelHeroCancelHero &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCR_SelHeroPrapared(const SeCR_SelHeroPrapared &kData, char *pcBuf, int iMaxLen)
References EncodeSeCR_SelHeroPrapared.
Referenced by EncodeSeCR_SelHeroPrapared.
int EncodeSeCR_SelHeroPrapared(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCR_SelHeroPrapared(const char *pkData, int iLen, SeCR_SelHeroPrapared &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCR_RaceReportSyn(const SeCR_RaceReportSyn &kData, char *pcBuf, int iMaxLen)
References SeCR_RaceReportSyn::dwFrame, EncodeSeCR_RaceReportSyn, SeCR_RaceReportSyn::iFrameRand.
Referenced by EncodeSeCR_RaceReportSyn.
int EncodeSeCR_RaceReportSyn(DWord dwFrame, int iFrameRand, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_RaceReportSyn(const char *pkData, int iLen, SeCR_RaceReportSyn &kStruct)
References SeNetStream::Attach, SeCR_RaceReportSyn::dwFrame, SeNetStream::GetCurPos, SeCR_RaceReportSyn::iFrameRand, SeNetStream::Read.
int EncodeSeCR_Talk(const SeCR_Talk &kData, char *pcBuf, int iMaxLen)
References SeCR_Talk::acMessage, EncodeSeCR_Talk, SeCR_Talk::eType.
Referenced by EncodeSeCR_Talk.
int EncodeSeCR_Talk(SeTalkType eType, const char *acMessage, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCR_Talk(const char *pkData, int iLen, SeCR_Talk &kStruct)
References SeCR_Talk::acMessage, SeNetStream::Attach, SeCR_Talk::eType, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeCR_RaceRobotLogin(const SeCR_RaceRobotLogin &kData, char *pcBuf, int iMaxLen)
References SeCR_RaceRobotLogin::dwMapID, SeCR_RaceRobotLogin::dwPlayerID, EncodeSeCR_RaceRobotLogin.
Referenced by EncodeSeCR_RaceRobotLogin.
int EncodeSeCR_RaceRobotLogin(DWord dwPlayerID, DWord dwMapID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_RaceRobotLogin(const char *pkData, int iLen, SeCR_RaceRobotLogin &kStruct)
References SeNetStream::Attach, SeCR_RaceRobotLogin::dwMapID, SeCR_RaceRobotLogin::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCR_Ping(const SeCR_Ping &kData, char *pcBuf, int iMaxLen)
References SeCR_Ping::dwPackIndex, EncodeSeCR_Ping.
Referenced by EncodeSeCR_Ping.
int EncodeSeCR_Ping(DWord dwPackIndex, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_Ping(const char *pkData, int iLen, SeCR_Ping &kStruct)
References SeNetStream::Attach, SeCR_Ping::dwPackIndex, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCR_BuyRaceItem(const SeCR_BuyRaceItem &kData, char *pcBuf, int iMaxLen)
References SeCR_BuyRaceItem::dwItemTypeID, SeCR_BuyRaceItem::dwTarUnitID, EncodeSeCR_BuyRaceItem.
Referenced by EncodeSeCR_BuyRaceItem.
int EncodeSeCR_BuyRaceItem(DWord dwItemTypeID, DWord dwTarUnitID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_BuyRaceItem(const char *pkData, int iLen, SeCR_BuyRaceItem &kStruct)
References SeNetStream::Attach, SeCR_BuyRaceItem::dwItemTypeID, SeCR_BuyRaceItem::dwTarUnitID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCR_GetHeroInfo(const SeCR_GetHeroInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeCR_GetHeroInfo, SeCR_GetHeroInfo::iSeat.
Referenced by EncodeSeCR_GetHeroInfo.
int EncodeSeCR_GetHeroInfo(int iSeat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_GetHeroInfo(const char *pkData, int iLen, SeCR_GetHeroInfo &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCR_GetHeroInfo::iSeat, SeNetStream::Read.
int EncodeSeCR_ReplayReport(const SeCR_ReplayReport &kData, char *pcBuf, int iMaxLen)
References SeCR_ReplayReport::acMessage, SeCR_ReplayReport::Camera_x, SeCR_ReplayReport::Camera_y, EncodeSeCR_ReplayReport, SeCR_ReplayReport::iReportFrame.
Referenced by EncodeSeCR_ReplayReport.
int EncodeSeCR_ReplayReport(int iReportFrame, int Camera_x, int Camera_y, const char *acMessage, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCR_ReplayReport(const char *pkData, int iLen, SeCR_ReplayReport &kStruct)
References SeCR_ReplayReport::acMessage, SeNetStream::Attach, SeCR_ReplayReport::Camera_x, SeCR_ReplayReport::Camera_y, SeNetStream::GetCurPos, SeCR_ReplayReport::iReportFrame, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeCR_SetEquipSetReq(const SeCR_SetEquipSetReq &kData, char *pcBuf, int iMaxLen)
References SeCR_SetEquipSetReq::byIndex, EncodeSeCR_SetEquipSetReq.
Referenced by EncodeSeCR_SetEquipSetReq.
int EncodeSeCR_SetEquipSetReq(Byte byIndex, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_SetEquipSetReq(const char *pkData, int iLen, SeCR_SetEquipSetReq &kStruct)
References SeNetStream::Attach, SeCR_SetEquipSetReq::byIndex, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCR_SetAvatarReq(const SeCR_SetAvatarReq &kData, char *pcBuf, int iMaxLen)
References SeCR_SetAvatarReq::dwItemID, EncodeSeCR_SetAvatarReq.
Referenced by EncodeSeCR_SetAvatarReq.
int EncodeSeCR_SetAvatarReq(DWord dwItemID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCR_SetAvatarReq(const char *pkData, int iLen, SeCR_SetAvatarReq &kStruct)
References SeNetStream::Attach, SeCR_SetAvatarReq::dwItemID, SeNetStream::GetCurPos, SeNetStream::Read.