SeNetStream.h
std::enable_if<std::is_arithmetic<T>::value, bool>::type Write(SeNetStream &rkStream, const T &obj)
References SeNetStream::Write.
Referenced by SeRaceMgr::CreateRobotRace, SeRaceMgr::OnRaceModeEnd, MatchServer::OnSendRSValidatePlayerInfo, BlockServer::ProcessMBL_RaceMatchLoadDetail, Write.
std::enable_if<std::is_arithmetic<T>::value, bool>::type Read(SeNetStream &rkStream, T &obj)
References SeNetStream::Read.
Referenced by MatchServer::ProcessBLM_RaceMatchLoadDetailRet, RaceServer::ProcessMR_ValidatePlayerInfo, SeRaceRecord::ProcessRecordLabel, Read.
std::enable_if<std::is_enum<T>::value, bool>::type Write(SeNetStream &rkStream, const T &obj)
References Write.
std::enable_if<std::is_enum<T>::value, bool>::type Read(SeNetStream &rkStream, T &obj)
References Read.
bool Write(SeNetStream &rkStream, const std::vector< T > &vec)
References Write.
bool Read(SeNetStream &rkStream, std::vector< T > &vec)
References Read.