SeCommStream.cpp
int EncodeSePtlNetAddr(const SePtlNetAddr &kData, char *pcBuf, int iMaxLen)
References SePtlNetAddr::acIP, EncodeSePtlNetAddr, SePtlNetAddr::iPort.
Referenced by EncodeSePtlNetAddr, EncodeSeTC_MatchRaceAddr, EncodeSeTC_ResView.
int EncodeSePtlNetAddr(const char *acIP, int iPort, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSePtlNetAddr(const char *pkData, int iLen, SePtlNetAddr &kStruct)
References SePtlNetAddr::acIP, SeNetStream::Attach, SeNetStream::GetCurPos, SePtlNetAddr::iPort, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeTC_MatchRaceAddr, DecodeSeTC_ResView.
int EncodeSeMatchSelPlayerInfo(const SeMatchSelPlayerInfo &kData, char *pcBuf, int iMaxLen)
References SeMatchSelPlayerInfo::acName, SeMatchSelPlayerInfo::dwAreaID, SeMatchSelPlayerInfo::dwPlayerID, SeMatchSelPlayerInfo::dwScore, SeMatchSelPlayerInfo::eCamp, EncodeSeMatchSelPlayerInfo, SeMatchSelPlayerInfo::iSeat.
Referenced by EncodeSeMatchSelPlayerInfo, EncodeSeRC_RoomPlayerBaseInfo.
int EncodeSeMatchSelPlayerInfo(DWord dwPlayerID, const char *acName, SeRoomPlayerCamp eCamp, int iSeat, DWord dwAreaID, DWord dwScore, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeMatchSelPlayerInfo(const char *pkData, int iLen, SeMatchSelPlayerInfo &kStruct)
References SeMatchSelPlayerInfo::acName, SeNetStream::Attach, SeMatchSelPlayerInfo::dwAreaID, SeMatchSelPlayerInfo::dwPlayerID, SeMatchSelPlayerInfo::dwScore, SeMatchSelPlayerInfo::eCamp, SeNetStream::GetCurPos, SeMatchSelPlayerInfo::iSeat, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeRC_RoomPlayerBaseInfo.
int EncodeSePlayerAppear(const SePlayerAppear &kData, char *pcBuf, int iMaxLen)
References SePlayerAppear::dwHeroTypeID, SePlayerAppear::dwPlayerID, EncodeSePlayerAppear, SePlayerAppear::fMoveDirect, SePlayerAppear::fMoveSpeed, SePlayerAppear::fX, SePlayerAppear::fY.
Referenced by EncodeSePlayerAppear, EncodeSeTC_PlayerAppear.
int EncodeSePlayerAppear(DWord dwPlayerID, DWord dwHeroTypeID, float fMoveSpeed, float fX, float fY, float fMoveDirect, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSePlayerAppear(const char *pkData, int iLen, SePlayerAppear &kStruct)
References SeNetStream::Attach, SePlayerAppear::dwHeroTypeID, SePlayerAppear::dwPlayerID, SePlayerAppear::fMoveDirect, SePlayerAppear::fMoveSpeed, SePlayerAppear::fX, SePlayerAppear::fY, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_PlayerAppear.
int EncodeSePtlExchange(const SePtlExchange &kData, char *pcBuf, int iMaxLen)
References SePtlExchange::dwTypeID, EncodeSePtlExchange, SePtlExchange::iCount.
Referenced by EncodeSePtlExchange, EncodeSeTC_ExchangeInit.
int EncodeSePtlExchange(DWord dwTypeID, int iCount, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSePtlExchange(const char *pkData, int iLen, SePtlExchange &kStruct)
References SeNetStream::Attach, SePtlExchange::dwTypeID, SeNetStream::GetCurPos, SePtlExchange::iCount, SeNetStream::Read.
Referenced by DecodeSeTC_ExchangeInit.
int EncodeSePtlMapTask(const SePtlMapTask &kData, char *pcBuf, int iMaxLen)
References SePtlMapTask::dwState, SePtlMapTask::dwTypeID, EncodeSePtlMapTask, SePtlMapTask::iNum.
Referenced by EncodeSePtlMapTask, EncodeSeTC_QueryMapTaskListRet.
int EncodeSePtlMapTask(DWord dwTypeID, DWord dwState, int iNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSePtlMapTask(const char *pkData, int iLen, SePtlMapTask &kStruct)
References SeNetStream::Attach, SePtlMapTask::dwState, SePtlMapTask::dwTypeID, SeNetStream::GetCurPos, SePtlMapTask::iNum, SeNetStream::Read.
Referenced by DecodeSeTC_QueryMapTaskListRet.
int EncodeSePtlTask(const SePtlTask &kData, char *pcBuf, int iMaxLen)
References SePtlTask::dwState, SePtlTask::dwTaskID, SePtlTask::dwTaskType, EncodeSePtlTask, SePtlTask::iConditionNum, SePtlTask::ifinishCount, SePtlTask::iSchedule.
Referenced by EncodeSePtlTask, EncodeSeTC_TaskQueryListRet, EncodeSeTC_TaskReselRet.
int EncodeSePtlTask(DWord dwTaskID, DWord dwTaskType, SeTaskState dwState, int iConditionNum, int iSchedule, int ifinishCount, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSePtlTask(const char *pkData, int iLen, SePtlTask &kStruct)
References SeNetStream::Attach, SePtlTask::dwState, SePtlTask::dwTaskID, SePtlTask::dwTaskType, SeNetStream::GetCurPos, SePtlTask::iConditionNum, SePtlTask::ifinishCount, SePtlTask::iSchedule, SeNetStream::Read.
Referenced by DecodeSeTC_TaskQueryListRet, DecodeSeTC_TaskReselRet.
int EncodeSePlayerDisappear(const SePlayerDisappear &kData, char *pcBuf, int iMaxLen)
References SePlayerDisappear::dwPlayerID, EncodeSePlayerDisappear.
Referenced by EncodeSePlayerDisappear, EncodeSeTC_PlayerDisappear.
int EncodeSePlayerDisappear(DWord dwPlayerID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSePlayerDisappear(const char *pkData, int iLen, SePlayerDisappear &kStruct)
References SeNetStream::Attach, SePlayerDisappear::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_PlayerDisappear.
int EncodeSeRaceTask(const SeRaceTask &kData, char *pcBuf, int iMaxLen)
References SeRaceTask::dwTaskID, EncodeSeRaceTask, SeRaceTask::iNum.
Referenced by EncodeSeGuanqiaSendInfo, EncodeSeRaceSendInfo, EncodeSeRaceTask.
int EncodeSeRaceTask(DWord dwTaskID, int iNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceTask(const char *pkData, int iLen, SeRaceTask &kStruct)
References SeNetStream::Attach, SeRaceTask::dwTaskID, SeNetStream::GetCurPos, SeRaceTask::iNum, SeNetStream::Read.
Referenced by DecodeSeGuanqiaSendInfo, DecodeSeRaceSendInfo.
int EncodeSeRaceSendInfo(const SeRaceSendInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceSendInfo::akRaceTask, SeRaceSendInfo::bAssist, SeRaceSendInfo::bBear, SeRaceSendInfo::bBestHero, SeRaceSendInfo::bDamage, SeRaceSendInfo::bKill, SeRaceSendInfo::bOutput, SeRaceSendInfo::bRich, SeRaceSendInfo::bSoul, SeRaceSendInfo::bTeamwork, SeRaceSendInfo::dwHeroTypeID, SeRaceSendInfo::dwHorseTypeID, SeRaceSendInfo::dwWishID, EncodeSeRaceSendInfo, SeRaceSendInfo::iAssistanceNums, SeRaceSendInfo::iCardExp, SeRaceSendInfo::iComboMaxKills, SeRaceSendInfo::iCrown, SeRaceSendInfo::iDeathNums, SeRaceSendInfo::iDifficult, SeRaceSendInfo::iGold, SeRaceSendInfo::iHeroLevel, SeRaceSendInfo::iHorseExp, SeRaceSendInfo::iKillBoss, SeRaceSendInfo::iKilledBuild, SeRaceSendInfo::iKillHeroNums, SeRaceSendInfo::iKillSoildiers, SeRaceSendInfo::iRaceEndFlag, SeRaceSendInfo::iScore, SeRaceSendInfo::iSeatIndex, SeRaceSendInfo::iTaskNum, SeRaceSendInfo::iTeamBeKill, SeRaceSendInfo::iTeamKill.
Referenced by EncodeSeCR_RaceEndRace, EncodeSeRaceSendInfo, EncodeSeWSRaceSendInfo.
int EncodeSeRaceSendInfo(int iSeatIndex, DWord dwHeroTypeID, DWord dwHorseTypeID, int iScore, int iCardExp, int iHorseExp, int iGold, int iDifficult, int iRaceEndFlag, int iDeathNums, int iKillSoildiers, int iKillBoss, int iKillHeroNums, int iComboMaxKills, int iAssistanceNums, bool bBestHero, int iHeroLevel, int iKilledBuild, int iCrown, DWord dwWishID, int iTaskNum, bool bSoul, bool bRich, bool bKill, bool bAssist, bool bDamage, bool bOutput, bool bBear, bool bTeamwork, int iTeamKill, int iTeamBeKill, const SeRaceTask *akRaceTask, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeRaceSendInfo(int iSeatIndex, DWord dwHeroTypeID, DWord dwHorseTypeID, int iScore, int iCardExp, int iHorseExp, int iGold, int iDifficult, int iRaceEndFlag, int iDeathNums, int iKillSoildiers, int iKillBoss, int iKillHeroNums, int iComboMaxKills, int iAssistanceNums, bool bBestHero, int iHeroLevel, int iKilledBuild, int iCrown, DWord dwWishID, int iTaskNum, bool bSoul, bool bRich, bool bKill, bool bAssist, bool bDamage, bool bOutput, bool bBear, bool bTeamwork, int iTeamKill, int iTeamBeKill, std::vector< SeRaceTask > &akRaceTask, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeRaceSendInfo(const char *pkData, int iLen, SeRaceSendInfo &kStruct)
References SeRaceSendInfo::akRaceTask, SeNetStream::Attach, SeRaceSendInfo::bAssist, SeRaceSendInfo::bBear, SeRaceSendInfo::bBestHero, SeRaceSendInfo::bDamage, SeRaceSendInfo::bKill, SeRaceSendInfo::bOutput, SeRaceSendInfo::bRich, SeRaceSendInfo::bSoul, SeRaceSendInfo::bTeamwork, DecodeSeRaceTask, SeRaceSendInfo::dwHeroTypeID, SeRaceSendInfo::dwHorseTypeID, SeRaceSendInfo::dwWishID, SeNetStream::GetCurPos, SeRaceSendInfo::iAssistanceNums, SeRaceSendInfo::iCardExp, SeRaceSendInfo::iComboMaxKills, SeRaceSendInfo::iCrown, SeRaceSendInfo::iDeathNums, SeRaceSendInfo::iDifficult, SeRaceSendInfo::iGold, SeRaceSendInfo::iHeroLevel, SeRaceSendInfo::iHorseExp, SeRaceSendInfo::iKillBoss, SeRaceSendInfo::iKilledBuild, SeRaceSendInfo::iKillHeroNums, SeRaceSendInfo::iKillSoildiers, SeRaceSendInfo::iRaceEndFlag, SeRaceSendInfo::iScore, SeRaceSendInfo::iSeatIndex, SeRaceSendInfo::iTaskNum, SeRaceSendInfo::iTeamBeKill, SeRaceSendInfo::iTeamKill, SeNetStream::Read, SeNetStream::SetCurPos.
Referenced by DecodeSeCR_RaceEndRace, DecodeSeWSRaceSendInfo.
int EncodeSeWSRaceSendInfo(const SeWSRaceSendInfo &kData, char *pcBuf, int iMaxLen)
References SeWSRaceSendInfo::abyRaceID, SeWSRaceSendInfo::bAutoMatchRace, SeWSRaceSendInfo::dwAreaID, SeWSRaceSendInfo::dwMapID, SeWSRaceSendInfo::dwOrgPlayerID, SeWSRaceSendInfo::dwPlayerID, SeWSRaceSendInfo::dwRaceTime, SeWSRaceSendInfo::eCmp, EncodeSeWSRaceSendInfo, SeWSRaceSendInfo::eRaceModel, SeWSRaceSendInfo::iLeagueMMR, SeWSRaceSendInfo::iLeagueScore, SeWSRaceSendInfo::iOtherLeagueScore, SeWSRaceSendInfo::iTeamMemberNum, SeWSRaceSendInfo::kInfo.
Referenced by EncodeSeWSRaceSendInfo.
int EncodeSeWSRaceSendInfo(DWord dwOrgPlayerID, DWord dwPlayerID, DWord dwMapID, DWord dwAreaID, const Byte *abyRaceID, DWord dwRaceTime, bool bAutoMatchRace, SeRaceModel eRaceModel, int iTeamMemberNum, SeRoomPlayerCamp eCmp, int iLeagueScore, int iLeagueMMR, int iOtherLeagueScore, const SeRaceSendInfo &kInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeWSRaceSendInfo(DWord dwOrgPlayerID, DWord dwPlayerID, DWord dwMapID, DWord dwAreaID, std::vector< Byte > &abyRaceID, DWord dwRaceTime, bool bAutoMatchRace, SeRaceModel eRaceModel, int iTeamMemberNum, SeRoomPlayerCamp eCmp, int iLeagueScore, int iLeagueMMR, int iOtherLeagueScore, const SeRaceSendInfo &kInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeWSRaceSendInfo(const char *pkData, int iLen, SeWSRaceSendInfo &kStruct)
References SeWSRaceSendInfo::abyRaceID, SeNetStream::Attach, SeWSRaceSendInfo::bAutoMatchRace, DecodeSeRaceSendInfo, SeWSRaceSendInfo::dwAreaID, SeWSRaceSendInfo::dwMapID, SeWSRaceSendInfo::dwOrgPlayerID, SeWSRaceSendInfo::dwPlayerID, SeWSRaceSendInfo::dwRaceTime, SeWSRaceSendInfo::eCmp, SeWSRaceSendInfo::eRaceModel, SeNetStream::GetCurPos, SeWSRaceSendInfo::iLeagueMMR, SeWSRaceSendInfo::iLeagueScore, SeWSRaceSendInfo::iOtherLeagueScore, SeWSRaceSendInfo::iTeamMemberNum, SeWSRaceSendInfo::kInfo, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeGuanqiaSendInfo(const SeGuanqiaSendInfo &kData, char *pcBuf, int iMaxLen)
References SeGuanqiaSendInfo::adwBossID, SeGuanqiaSendInfo::akRaceTask, SeGuanqiaSendInfo::dwHeroTypeID, EncodeSeGuanqiaSendInfo, SeGuanqiaSendInfo::iAddExp, SeGuanqiaSendInfo::iAddGold, SeGuanqiaSendInfo::iDeathNums, SeGuanqiaSendInfo::iDifficult, SeGuanqiaSendInfo::iKillBossNums, SeGuanqiaSendInfo::iPrize, SeGuanqiaSendInfo::iRaceEndFlag, SeGuanqiaSendInfo::iSeatIndex, SeGuanqiaSendInfo::iTaskNum, SeGuanqiaSendInfo::iTotalBeDamage, SeGuanqiaSendInfo::iTotalCure, SeGuanqiaSendInfo::iTotalDamage.
Referenced by EncodeSeCR_RaceEndGuanqia, EncodeSeCT_RaceEndGuanka, EncodeSeGuanqiaSendInfo, EncodeSeWSGuanqiaSendInfo.
int EncodeSeGuanqiaSendInfo(int iSeatIndex, DWord dwHeroTypeID, int iAddExp, int iAddGold, int iDifficult, int iRaceEndFlag, int iDeathNums, DWord iTotalDamage, DWord iTotalBeDamage, DWord iTotalCure, char iPrize, int iKillBossNums, const DWord *adwBossID, int iTaskNum, const SeRaceTask *akRaceTask, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeGuanqiaSendInfo(int iSeatIndex, DWord dwHeroTypeID, int iAddExp, int iAddGold, int iDifficult, int iRaceEndFlag, int iDeathNums, DWord iTotalDamage, DWord iTotalBeDamage, DWord iTotalCure, char iPrize, int iKillBossNums, std::vector< DWord > &adwBossID, int iTaskNum, std::vector< SeRaceTask > &akRaceTask, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceTask, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeGuanqiaSendInfo(const char *pkData, int iLen, SeGuanqiaSendInfo &kStruct)
References SeGuanqiaSendInfo::adwBossID, SeGuanqiaSendInfo::akRaceTask, SeNetStream::Attach, DecodeSeRaceTask, SeGuanqiaSendInfo::dwHeroTypeID, SeNetStream::GetCurPos, SeGuanqiaSendInfo::iAddExp, SeGuanqiaSendInfo::iAddGold, SeGuanqiaSendInfo::iDeathNums, SeGuanqiaSendInfo::iDifficult, SeGuanqiaSendInfo::iKillBossNums, SeGuanqiaSendInfo::iPrize, SeGuanqiaSendInfo::iRaceEndFlag, SeGuanqiaSendInfo::iSeatIndex, SeGuanqiaSendInfo::iTaskNum, SeGuanqiaSendInfo::iTotalBeDamage, SeGuanqiaSendInfo::iTotalCure, SeGuanqiaSendInfo::iTotalDamage, SeNetStream::Read, SeNetStream::SetCurPos.
Referenced by DecodeSeCR_RaceEndGuanqia, DecodeSeCT_RaceEndGuanka, DecodeSeWSGuanqiaSendInfo.
int EncodeSeWSGuanqiaSendInfo(const SeWSGuanqiaSendInfo &kData, char *pcBuf, int iMaxLen)
References SeWSGuanqiaSendInfo::abyRaceID, SeWSGuanqiaSendInfo::bAutoMatchRace, SeWSGuanqiaSendInfo::dwAreaID, SeWSGuanqiaSendInfo::dwMapID, SeWSGuanqiaSendInfo::dwPlayerID, SeWSGuanqiaSendInfo::dwRaceTime, EncodeSeWSGuanqiaSendInfo, SeWSGuanqiaSendInfo::kInfo.
Referenced by EncodeSeWSGuanqiaSendInfo.
int EncodeSeWSGuanqiaSendInfo(DWord dwPlayerID, DWord dwMapID, DWord dwAreaID, const Byte *abyRaceID, DWord dwRaceTime, bool bAutoMatchRace, const SeGuanqiaSendInfo &kInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeGuanqiaSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeWSGuanqiaSendInfo(DWord dwPlayerID, DWord dwMapID, DWord dwAreaID, std::vector< Byte > &abyRaceID, DWord dwRaceTime, bool bAutoMatchRace, const SeGuanqiaSendInfo &kInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeGuanqiaSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeWSGuanqiaSendInfo(const char *pkData, int iLen, SeWSGuanqiaSendInfo &kStruct)
References SeWSGuanqiaSendInfo::abyRaceID, SeNetStream::Attach, SeWSGuanqiaSendInfo::bAutoMatchRace, DecodeSeGuanqiaSendInfo, SeWSGuanqiaSendInfo::dwAreaID, SeWSGuanqiaSendInfo::dwMapID, SeWSGuanqiaSendInfo::dwPlayerID, SeWSGuanqiaSendInfo::dwRaceTime, SeNetStream::GetCurPos, SeWSGuanqiaSendInfo::kInfo, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSePlayerInfoSeat(const SePlayerInfoSeat &kData, char *pcBuf, int iMaxLen)
References SePlayerInfoSeat::acName, SePlayerInfoSeat::dwPlayerID, SePlayerInfoSeat::dwTeamID, EncodeSePlayerInfoSeat, SePlayerInfoSeat::iSeatIndex, SePlayerInfoSeat::uiScore.
Referenced by EncodeSePlayerInfoSeat, EncodeSeRC_ViewPlayerInfo, EncodeSeWCSC_ViewPlayerInfo.
int EncodeSePlayerInfoSeat(int iSeatIndex, DWord dwPlayerID, DWord uiScore, const char *acName, DWord dwTeamID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSePlayerInfoSeat(const char *pkData, int iLen, SePlayerInfoSeat &kStruct)
References SePlayerInfoSeat::acName, SeNetStream::Attach, SePlayerInfoSeat::dwPlayerID, SePlayerInfoSeat::dwTeamID, SeNetStream::GetCurPos, SePlayerInfoSeat::iSeatIndex, SeNetStream::Read, SeNetStream::ReadString, SePlayerInfoSeat::uiScore.
Referenced by DecodeSeRC_ViewPlayerInfo, DecodeSeWCSC_ViewPlayerInfo.
int EncodeSeMatchRoomListInfo(const SeMatchRoomListInfo &kData, char *pcBuf, int iMaxLen)
References SeMatchRoomListInfo::dwMapID, SeMatchRoomListInfo::dwRaceTime, SeMatchRoomListInfo::dwRoomSession, EncodeSeMatchRoomListInfo.
Referenced by EncodeSeMatchRoomListInfo, EncodeSeTC_QueryRaceRoomListRet.
int EncodeSeMatchRoomListInfo(DWord dwRoomSession, DWord dwMapID, DWord dwRaceTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeMatchRoomListInfo(const char *pkData, int iLen, SeMatchRoomListInfo &kStruct)
References SeNetStream::Attach, SeMatchRoomListInfo::dwMapID, SeMatchRoomListInfo::dwRaceTime, SeMatchRoomListInfo::dwRoomSession, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_QueryRaceRoomListRet.
int EncodeSeNoticeMatchPlayerInfo(const SeNoticeMatchPlayerInfo &kData, char *pcBuf, int iMaxLen)
References SeNoticeMatchPlayerInfo::acName, SeNoticeMatchPlayerInfo::byCamp, SeNoticeMatchPlayerInfo::dwGuanqiaScore, SeNoticeMatchPlayerInfo::dwLeagueScore, SeNoticeMatchPlayerInfo::dwPlayerID, EncodeSeNoticeMatchPlayerInfo, SeNoticeMatchPlayerInfo::iSeatIndex.
Referenced by EncodeSeNoticeMatchPlayerInfo, EncodeSeTC_MatchRaceAddr.
int EncodeSeNoticeMatchPlayerInfo(DWord dwPlayerID, DWord dwLeagueScore, DWord dwGuanqiaScore, const char *acName, int iSeatIndex, Byte byCamp, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeNoticeMatchPlayerInfo(const char *pkData, int iLen, SeNoticeMatchPlayerInfo &kStruct)
References SeNoticeMatchPlayerInfo::acName, SeNetStream::Attach, SeNoticeMatchPlayerInfo::byCamp, SeNoticeMatchPlayerInfo::dwGuanqiaScore, SeNoticeMatchPlayerInfo::dwLeagueScore, SeNoticeMatchPlayerInfo::dwPlayerID, SeNetStream::GetCurPos, SeNoticeMatchPlayerInfo::iSeatIndex, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeTC_MatchRaceAddr.
int EncodeSeMobileInfo(const SeMobileInfo &kData, char *pcBuf, int iMaxLen)
References SeMobileInfo::acDeviceImei, SeMobileInfo::acDeviceOSVer, SeMobileInfo::acDeviceRes, SeMobileInfo::acDeviceType, SeMobileInfo::dwDeviceOS, SeMobileInfo::dwNetworkIsp, SeMobileInfo::dwNetworkType, EncodeSeMobileInfo.
Referenced by EncodeSeCT_PlayerValidate, EncodeSeMobileInfo.
int EncodeSeMobileInfo(DWord dwDeviceOS, DWord dwNetworkType, DWord dwNetworkIsp, const char *acDeviceType, const char *acDeviceRes, const char *acDeviceOSVer, const char *acDeviceImei, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeMobileInfo(const char *pkData, int iLen, SeMobileInfo &kStruct)
References SeMobileInfo::acDeviceImei, SeMobileInfo::acDeviceOSVer, SeMobileInfo::acDeviceRes, SeMobileInfo::acDeviceType, SeNetStream::Attach, SeMobileInfo::dwDeviceOS, SeMobileInfo::dwNetworkIsp, SeMobileInfo::dwNetworkType, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeCT_PlayerValidate.
int EncodeSeSelHeroInfo(const SeSelHeroInfo &kData, char *pcBuf, int iMaxLen)
References SeSelHeroInfo::dwActiveSkin, SeSelHeroInfo::dwActiveWeapon, SeSelHeroInfo::dwActiveWing, SeSelHeroInfo::dwHeroTypeID, EncodeSeSelHeroInfo.
Referenced by EncodeSeRC_SelHeroList, EncodeSeSelHeroInfo.
int EncodeSeSelHeroInfo(DWord dwHeroTypeID, DWord dwActiveSkin, DWord dwActiveWeapon, DWord dwActiveWing, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeSelHeroInfo(const char *pkData, int iLen, SeSelHeroInfo &kStruct)
References SeNetStream::Attach, SeSelHeroInfo::dwActiveSkin, SeSelHeroInfo::dwActiveWeapon, SeSelHeroInfo::dwActiveWing, SeSelHeroInfo::dwHeroTypeID, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeRC_SelHeroList.
int EncodeSeRaceWaitPlayer(const SeRaceWaitPlayer &kData, char *pcBuf, int iMaxLen)
References SeRaceWaitPlayer::byCamp, SeRaceWaitPlayer::dwIconID, SeRaceWaitPlayer::dwPlayerID, EncodeSeRaceWaitPlayer.
Referenced by EncodeSeRaceWaitPlayer, EncodeSeTC_AskEnterWaitRace.
int EncodeSeRaceWaitPlayer(DWord dwPlayerID, DWord dwIconID, Byte byCamp, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceWaitPlayer(const char *pkData, int iLen, SeRaceWaitPlayer &kStruct)
References SeNetStream::Attach, SeRaceWaitPlayer::byCamp, SeRaceWaitPlayer::dwIconID, SeRaceWaitPlayer::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_AskEnterWaitRace.
int EncodeSePtlFriendRequest(const SePtlFriendRequest &kData, char *pcBuf, int iMaxLen)
References SePtlFriendRequest::acSrcName, SePtlFriendRequest::dwSrcIcon, SePtlFriendRequest::dwSrcPlayerID, EncodeSePtlFriendRequest.
Referenced by EncodeSePtlFriendRequest, EncodeSeTC_FriendRequestAdd, EncodeSeTC_FriendRequestInit.
int EncodeSePtlFriendRequest(DWord dwSrcPlayerID, DWord dwSrcIcon, const char *acSrcName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSePtlFriendRequest(const char *pkData, int iLen, SePtlFriendRequest &kStruct)
References SePtlFriendRequest::acSrcName, SeNetStream::Attach, SePtlFriendRequest::dwSrcIcon, SePtlFriendRequest::dwSrcPlayerID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeTC_FriendRequestAdd, DecodeSeTC_FriendRequestInit.
int EncodeSePtlFriend(const SePtlFriend &kData, char *pcBuf, int iMaxLen)
References SePtlFriend::acLastLoginTime, SePtlFriend::acName, SePtlFriend::acRemarks, SePtlFriend::dwFriendID, SePtlFriend::dwIcon, SePtlFriend::dwIntimacy, SePtlFriend::dwScore, EncodeSePtlFriend, SePtlFriend::eStatus.
Referenced by EncodeSePtlFriend, EncodeSeTC_FriendAdd, EncodeSeTC_FriendInit.
int EncodeSePtlFriend(DWord dwFriendID, SeOnlineStatus eStatus, DWord dwIcon, DWord dwScore, DWord dwIntimacy, const char *acName, const char *acRemarks, const char *acLastLoginTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSePtlFriend(const char *pkData, int iLen, SePtlFriend &kStruct)
References SePtlFriend::acLastLoginTime, SePtlFriend::acName, SePtlFriend::acRemarks, SeNetStream::Attach, SePtlFriend::dwFriendID, SePtlFriend::dwIcon, SePtlFriend::dwIntimacy, SePtlFriend::dwScore, SePtlFriend::eStatus, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeTC_FriendAdd, DecodeSeTC_FriendInit.
int EncodeSePtlStaMap(const SePtlStaMap &kData, char *pcBuf, int iMaxLen)
References SePtlStaMap::dwMapID, EncodeSePtlStaMap, SePtlStaMap::iLose, SePtlStaMap::iNums, SePtlStaMap::iWin.
Referenced by EncodeSePtlStaMap.
int EncodeSePtlStaMap(DWord dwMapID, int iNums, int iWin, int iLose, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSePtlStaMap(const char *pkData, int iLen, SePtlStaMap &kStruct)
References SeNetStream::Attach, SePtlStaMap::dwMapID, SeNetStream::GetCurPos, SePtlStaMap::iLose, SePtlStaMap::iNums, SePtlStaMap::iWin, SeNetStream::Read.
int EncodeSePtlRaceHistory(const SePtlRaceHistory &kData, char *pcBuf, int iMaxLen)
References SePtlRaceHistory::acCreateTime, SePtlRaceHistory::acRaceID, SePtlRaceHistory::dwCharID, SePtlRaceHistory::dwHeroID, SePtlRaceHistory::dwID, SePtlRaceHistory::dwMapID, EncodeSePtlRaceHistory, SePtlRaceHistory::iDeath, SePtlRaceHistory::iKill, SePtlRaceHistory::iResult.
Referenced by EncodeSePtlRaceHistory, EncodeSeQueryPlayerRaceInfo, EncodeSeTC_GetRaceHistoryRet, EncodeSeTC_QueryNearestRaceInfoRet.
int EncodeSePtlRaceHistory(DWord dwID, DWord dwCharID, const char *acRaceID, DWord dwMapID, DWord dwHeroID, int iResult, int iKill, int iDeath, const char *acCreateTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSePtlRaceHistory(const char *pkData, int iLen, SePtlRaceHistory &kStruct)
References SePtlRaceHistory::acCreateTime, SePtlRaceHistory::acRaceID, SeNetStream::Attach, SePtlRaceHistory::dwCharID, SePtlRaceHistory::dwHeroID, SePtlRaceHistory::dwID, SePtlRaceHistory::dwMapID, SeNetStream::GetCurPos, SePtlRaceHistory::iDeath, SePtlRaceHistory::iKill, SePtlRaceHistory::iResult, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeQueryPlayerRaceInfo, DecodeSeTC_GetRaceHistoryRet, DecodeSeTC_QueryNearestRaceInfoRet.
int EncodeSeQueryPlayerRaceInfo(const SeQueryPlayerRaceInfo &kData, char *pcBuf, int iMaxLen)
References SeQueryPlayerRaceInfo::akRaceHistory, EncodeSeQueryPlayerRaceInfo, SeQueryPlayerRaceInfo::iFiveKills, SeQueryPlayerRaceInfo::iFourKills, SeQueryPlayerRaceInfo::iLeagueScore, SeQueryPlayerRaceInfo::iMvps, SeQueryPlayerRaceInfo::iThreeKills, SeQueryPlayerRaceInfo::iTotalNum, SeQueryPlayerRaceInfo::iWinNum, SeQueryPlayerRaceInfo::iWorldStrongest.
Referenced by EncodeSeQueryPlayerRaceInfo.
int EncodeSeQueryPlayerRaceInfo(int iLeagueScore, int iTotalNum, int iWinNum, int iThreeKills, int iFourKills, int iFiveKills, int iWorldStrongest, int iMvps, const SePtlRaceHistory *akRaceHistory, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlRaceHistory, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SSD_SHOW_RACE_HISTORY_NUM, SeNetStream::Write.
int EncodeSeQueryPlayerRaceInfo(int iLeagueScore, int iTotalNum, int iWinNum, int iThreeKills, int iFourKills, int iFiveKills, int iWorldStrongest, int iMvps, std::vector< SePtlRaceHistory > &akRaceHistory, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePtlRaceHistory, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SSD_SHOW_RACE_HISTORY_NUM, SeNetStream::Write.
int DecodeSeQueryPlayerRaceInfo(const char *pkData, int iLen, SeQueryPlayerRaceInfo &kStruct)
References SeQueryPlayerRaceInfo::akRaceHistory, SeNetStream::Attach, DecodeSePtlRaceHistory, SeNetStream::GetCurPos, SeQueryPlayerRaceInfo::iFiveKills, SeQueryPlayerRaceInfo::iFourKills, SeQueryPlayerRaceInfo::iLeagueScore, SeQueryPlayerRaceInfo::iMvps, SeQueryPlayerRaceInfo::iThreeKills, SeQueryPlayerRaceInfo::iTotalNum, SeQueryPlayerRaceInfo::iWinNum, SeQueryPlayerRaceInfo::iWorldStrongest, SeNetStream::Read, SeNetStream::SetCurPos, SSD_SHOW_RACE_HISTORY_NUM.
int EncodeSePtlRaceBetInfo(const SePtlRaceBetInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSePtlRaceBetInfo, SePtlRaceBetInfo::fAddtionA, SePtlRaceBetInfo::fAddtionB, SePtlRaceBetInfo::fOddsA, SePtlRaceBetInfo::fOddsB, SePtlRaceBetInfo::iConstellIDA, SePtlRaceBetInfo::iConstellIDB.
Referenced by EncodeSePtlRaceBetInfo.
int EncodeSePtlRaceBetInfo(int iConstellIDA, int iConstellIDB, float fOddsA, float fOddsB, float fAddtionA, float fAddtionB, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSePtlRaceBetInfo(const char *pkData, int iLen, SePtlRaceBetInfo &kStruct)
References SeNetStream::Attach, SePtlRaceBetInfo::fAddtionA, SePtlRaceBetInfo::fAddtionB, SePtlRaceBetInfo::fOddsA, SePtlRaceBetInfo::fOddsB, SeNetStream::GetCurPos, SePtlRaceBetInfo::iConstellIDA, SePtlRaceBetInfo::iConstellIDB, SeNetStream::Read.
int EncodeSeMatchStartInfo(const SeMatchStartInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeMatchStartInfo, SeMatchStartInfo::iLeagueMMR, SeMatchStartInfo::iLeagueScore.
Referenced by EncodeSeMatchStartInfo.
int EncodeSeMatchStartInfo(int iLeagueScore, int iLeagueMMR, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeMatchStartInfo(const char *pkData, int iLen, SeMatchStartInfo &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeMatchStartInfo::iLeagueMMR, SeMatchStartInfo::iLeagueScore, SeNetStream::Read.
int EncodeSeMatchFightInfo(const SeMatchFightInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeMatchFightInfo, SeMatchFightInfo::iLeagueMMR, SeMatchFightInfo::iLeagueScore, SeMatchFightInfo::iOtherLeagueScore.
Referenced by EncodeSeMatchFightInfo.
int EncodeSeMatchFightInfo(int iLeagueScore, int iLeagueMMR, int iOtherLeagueScore, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeMatchFightInfo(const char *pkData, int iLen, SeMatchFightInfo &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeMatchFightInfo::iLeagueMMR, SeMatchFightInfo::iLeagueScore, SeMatchFightInfo::iOtherLeagueScore, SeNetStream::Read.
int EncodeSeMailAttach(const SeMailAttach &kData, char *pcBuf, int iMaxLen)
References SeMailAttach::dwParam1, SeMailAttach::dwParam2, EncodeSeMailAttach.
Referenced by EncodeSeMailAttach.
int EncodeSeMailAttach(DWord dwParam1, DWord dwParam2, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeMailAttach(const char *pkData, int iLen, SeMailAttach &kStruct)
References SeNetStream::Attach, SeMailAttach::dwParam1, SeMailAttach::dwParam2, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSePtlMail(const SePtlMail &kData, char *pcBuf, int iMaxLen)
References SePtlMail::acCreateTime, SePtlMail::acMessage, SePtlMail::dwAttach11, SePtlMail::dwAttach12, SePtlMail::dwAttach21, SePtlMail::dwAttach22, SePtlMail::dwAttach31, SePtlMail::dwAttach32, SePtlMail::dwID, EncodeSePtlMail, SePtlMail::iFlag, SePtlMail::iTextClass, SePtlMail::iType.
Referenced by EncodeSePtlMail, EncodeSeTC_ReceiveMail.
int EncodeSePtlMail(DWord dwID, int iType, int iTextClass, int iFlag, const char *acMessage, DWord dwAttach11, DWord dwAttach12, DWord dwAttach21, DWord dwAttach22, DWord dwAttach31, DWord dwAttach32, const char *acCreateTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSePtlMail(const char *pkData, int iLen, SePtlMail &kStruct)
References SePtlMail::acCreateTime, SePtlMail::acMessage, SeNetStream::Attach, SePtlMail::dwAttach11, SePtlMail::dwAttach12, SePtlMail::dwAttach21, SePtlMail::dwAttach22, SePtlMail::dwAttach31, SePtlMail::dwAttach32, SePtlMail::dwID, SeNetStream::GetCurPos, SePtlMail::iFlag, SePtlMail::iTextClass, SePtlMail::iType, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeTC_ReceiveMail.
int EncodeSeMailUpdate(const SeMailUpdate &kData, char *pcBuf, int iMaxLen)
References SeMailUpdate::dwID, EncodeSeMailUpdate, SeMailUpdate::iFlag.
Referenced by EncodeSeMailUpdate, EncodeSeTC_UpdateMail.
int EncodeSeMailUpdate(DWord dwID, int iFlag, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeMailUpdate(const char *pkData, int iLen, SeMailUpdate &kStruct)
References SeNetStream::Attach, SeMailUpdate::dwID, SeNetStream::GetCurPos, SeMailUpdate::iFlag, SeNetStream::Read.
Referenced by DecodeSeTC_UpdateMail.
int EncodeSeRoomMember(const SeRoomMember &kData, char *pcBuf, int iMaxLen)
References SeRoomMember::acName, SeRoomMember::byCamp, SeRoomMember::bySeat, SeRoomMember::dwIconID, SeRoomMember::dwPlayerID, EncodeSeRoomMember.
Referenced by EncodeSeOpenRoomInfo, EncodeSeRoomMember, EncodeSeTC_RoomMemberNotify.
int EncodeSeRoomMember(DWord dwPlayerID, const char *acName, DWord dwIconID, Byte byCamp, Byte bySeat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeRoomMember(const char *pkData, int iLen, SeRoomMember &kStruct)
References SeRoomMember::acName, SeNetStream::Attach, SeRoomMember::byCamp, SeRoomMember::bySeat, SeRoomMember::dwIconID, SeRoomMember::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeOpenRoomInfo, DecodeSeTC_RoomMemberNotify.
int EncodeSeOpenRoomInfo(const SeOpenRoomInfo &kData, char *pcBuf, int iMaxLen)
References SeOpenRoomInfo::acRoomName, SeOpenRoomInfo::akMember, SeOpenRoomInfo::bPass, SeOpenRoomInfo::dwGameMode, SeOpenRoomInfo::dwLeaderID, SeOpenRoomInfo::dwMapID, SeOpenRoomInfo::dwRoomID, EncodeSeOpenRoomInfo, SeOpenRoomInfo::iCurrPlayerNum, SeOpenRoomInfo::iMaxPlayerNum, SeOpenRoomInfo::iNum.
Referenced by EncodeSeOpenRoomInfo, EncodeSeTC_CreateRoomRet, EncodeSeTC_QueryRoomListRet, EncodeSeTC_RoomJoinRet.
int EncodeSeOpenRoomInfo(DWord dwRoomID, DWord dwMapID, DWord dwLeaderID, int dwGameMode, int iMaxPlayerNum, int iCurrPlayerNum, const char *acRoomName, bool bPass, int iNum, const SeRoomMember *akMember, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRoomMember, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int EncodeSeOpenRoomInfo(DWord dwRoomID, DWord dwMapID, DWord dwLeaderID, int dwGameMode, int iMaxPlayerNum, int iCurrPlayerNum, const char *acRoomName, bool bPass, int iNum, std::vector< SeRoomMember > &akMember, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRoomMember, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeOpenRoomInfo(const char *pkData, int iLen, SeOpenRoomInfo &kStruct)
References SeOpenRoomInfo::acRoomName, SeOpenRoomInfo::akMember, SeNetStream::Attach, SeOpenRoomInfo::bPass, DecodeSeRoomMember, SeOpenRoomInfo::dwGameMode, SeOpenRoomInfo::dwLeaderID, SeOpenRoomInfo::dwMapID, SeOpenRoomInfo::dwRoomID, SeNetStream::GetCurPos, SeOpenRoomInfo::iCurrPlayerNum, SeOpenRoomInfo::iMaxPlayerNum, SeOpenRoomInfo::iNum, SeNetStream::Read, SeNetStream::ReadString, SeNetStream::SetCurPos.
Referenced by DecodeSeTC_CreateRoomRet, DecodeSeTC_QueryRoomListRet, DecodeSeTC_RoomJoinRet.
int EncodeSeIncompleteRaceBaseInfo(const SeIncompleteRaceBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeIncompleteRaceBaseInfo::dwMapID, SeIncompleteRaceBaseInfo::dwRoomID, SeIncompleteRaceBaseInfo::emptySeatNum, EncodeSeIncompleteRaceBaseInfo.
Referenced by EncodeSeIncompleteRaceBaseInfo, EncodeSeTC_AddIncompleteRace, EncodeSeTC_ResIncompleteRaceList.
int EncodeSeIncompleteRaceBaseInfo(DWord dwRoomID, DWord dwMapID, int emptySeatNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeIncompleteRaceBaseInfo(const char *pkData, int iLen, SeIncompleteRaceBaseInfo &kStruct)
References SeNetStream::Attach, SeIncompleteRaceBaseInfo::dwMapID, SeIncompleteRaceBaseInfo::dwRoomID, SeIncompleteRaceBaseInfo::emptySeatNum, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_AddIncompleteRace, DecodeSeTC_ResIncompleteRaceList.
int EncodeSeSeatBaseInfo(const SeSeatBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeSeatBaseInfo::bConn, SeSeatBaseInfo::dwPlayerID, EncodeSeSeatBaseInfo, SeSeatBaseInfo::iAssist, SeSeatBaseInfo::iDie, SeSeatBaseInfo::iKill, SeSeatBaseInfo::iSeatIndex.
Referenced by EncodeSeSeatBaseInfo, EncodeSeTC_ResIncmpRaceSeatBaseInfo.
int EncodeSeSeatBaseInfo(int iSeatIndex, DWord dwPlayerID, int iKill, int iDie, int iAssist, bool bConn, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeSeatBaseInfo(const char *pkData, int iLen, SeSeatBaseInfo &kStruct)
References SeNetStream::Attach, SeSeatBaseInfo::bConn, SeSeatBaseInfo::dwPlayerID, SeNetStream::GetCurPos, SeSeatBaseInfo::iAssist, SeSeatBaseInfo::iDie, SeSeatBaseInfo::iKill, SeSeatBaseInfo::iSeatIndex, SeNetStream::Read.
Referenced by DecodeSeTC_ResIncmpRaceSeatBaseInfo.
int EncodeSeWCSViewInfo(const SeWCSViewInfo &kData, char *pcBuf, int iMaxLen)
References SeWCSViewInfo::dwFrame, SeWCSViewInfo::dwOffset, EncodeSeWCSViewInfo, SeWCSViewInfo::raceID.
Referenced by EncodeSeWCSViewInfo.
int EncodeSeWCSViewInfo(const Byte *raceID, DWord dwOffset, DWord dwFrame, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeWCSViewInfo(std::vector< Byte > &raceID, DWord dwOffset, DWord dwFrame, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeWCSViewInfo(const char *pkData, int iLen, SeWCSViewInfo &kStruct)
References SeNetStream::Attach, SeWCSViewInfo::dwFrame, SeWCSViewInfo::dwOffset, SeNetStream::GetCurPos, SeWCSViewInfo::raceID, SeNetStream::Read.
int EncodeSeViewList(const SeViewList &kData, char *pcBuf, int iMaxLen)
References EncodeSeViewList, SeViewList::raceID.
Referenced by EncodeSeTC_ResViewList, EncodeSeViewList.
int EncodeSeViewList(const Byte *raceID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeViewList(std::vector< Byte > &raceID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeViewList(const char *pkData, int iLen, SeViewList &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeViewList::raceID, SeNetStream::Read.
Referenced by DecodeSeTC_ResViewList.
int EncodeSeAchievementPtlDat(const SeAchievementPtlDat &kData, char *pcBuf, int iMaxLen)
References SeAchievementPtlDat::a_ID, SeAchievementPtlDat::a_lvl, EncodeSeAchievementPtlDat, SeAchievementPtlDat::iGetTime.
Referenced by EncodeSeAchievementPtlDat, EncodeSeTC_ResAchievementDat.
int EncodeSeAchievementPtlDat(DWord a_ID, DWord a_lvl, int iGetTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeAchievementPtlDat(const char *pkData, int iLen, SeAchievementPtlDat &kStruct)
References SeAchievementPtlDat::a_ID, SeAchievementPtlDat::a_lvl, SeNetStream::Attach, SeNetStream::GetCurPos, SeAchievementPtlDat::iGetTime, SeNetStream::Read.
Referenced by DecodeSeTC_ResAchievementDat.
int EncodeSeAchievementCounts(const SeAchievementCounts &kData, char *pcBuf, int iMaxLen)
References SeAchievementCounts::a_ID, SeAchievementCounts::counts, EncodeSeAchievementCounts.
Referenced by EncodeSeAchievementCounts, EncodeSeTC_ResAchievementCounts.
int EncodeSeAchievementCounts(DWord a_ID, DWord counts, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeAchievementCounts(const char *pkData, int iLen, SeAchievementCounts &kStruct)
References SeAchievementCounts::a_ID, SeNetStream::Attach, SeAchievementCounts::counts, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_ResAchievementCounts.
int EncodeSePlayerAchievementCounts(const SePlayerAchievementCounts &kData, char *pcBuf, int iMaxLen)
References SePlayerAchievementCounts::dwAID, SePlayerAchievementCounts::dwCounts, EncodeSePlayerAchievementCounts.
Referenced by EncodeSePlayerAchievementCounts.
int EncodeSePlayerAchievementCounts(DWord dwAID, DWord dwCounts, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSePlayerAchievementCounts(const char *pkData, int iLen, SePlayerAchievementCounts &kStruct)
References SeNetStream::Attach, SePlayerAchievementCounts::dwAID, SePlayerAchievementCounts::dwCounts, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeAttrUnit(const SeAttrUnit &kData, char *pcBuf, int iMaxLen)
References SeAttrUnit::dwIndex, SeAttrUnit::dwValue, EncodeSeAttrUnit.
Referenced by EncodeSeAttrUnit, EncodeSeItemNoti.
int EncodeSeAttrUnit(DWord dwIndex, float dwValue, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeAttrUnit(const char *pkData, int iLen, SeAttrUnit &kStruct)
References SeNetStream::Attach, SeAttrUnit::dwIndex, SeAttrUnit::dwValue, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeItemNoti.
int EncodeSeExternAttrUnit(const SeExternAttrUnit &kData, char *pcBuf, int iMaxLen)
References SeExternAttrUnit::dwIndex, SeExternAttrUnit::dwSubID, SeExternAttrUnit::dwValue, EncodeSeExternAttrUnit.
Referenced by EncodeSeCiTiao, EncodeSeExternAttrUnit.
int EncodeSeExternAttrUnit(DWord dwSubID, DWord dwIndex, float dwValue, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeExternAttrUnit(const char *pkData, int iLen, SeExternAttrUnit &kStruct)
References SeNetStream::Attach, SeExternAttrUnit::dwIndex, SeExternAttrUnit::dwSubID, SeExternAttrUnit::dwValue, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeCiTiao.
int EncodeSeCiTiao(const SeCiTiao &kData, char *pcBuf, int iMaxLen)
References SeCiTiao::dwID, EncodeSeCiTiao, SeCiTiao::SkillAdd.
Referenced by EncodeSeCiTiao, EncodeSeItemNoti.
int EncodeSeCiTiao(DWord dwID, const SeExternAttrUnit *SkillAdd, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeExternAttrUnit, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SSD_MAX_ATTR_NUM, SeNetStream::Write.
int EncodeSeCiTiao(DWord dwID, std::vector< SeExternAttrUnit > &SkillAdd, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeExternAttrUnit, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SSD_MAX_ATTR_NUM, SeNetStream::Write.
int DecodeSeCiTiao(const char *pkData, int iLen, SeCiTiao &kStruct)
References SeNetStream::Attach, DecodeSeExternAttrUnit, SeCiTiao::dwID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::SetCurPos, SeCiTiao::SkillAdd, SSD_MAX_ATTR_NUM.
Referenced by DecodeSeItemNoti.
int EncodeSeItemNoti(const SeItemNoti &kData, char *pcBuf, int iMaxLen)
References SeItemNoti::bNew, SeItemNoti::citiaoAttr, SeItemNoti::dwAddedLevel, SeItemNoti::dwID, SeItemNoti::dwLostTime, SeItemNoti::dwOverlap, EncodeSeItemNoti, SeItemNoti::Index, SeItemNoti::ItemID, SeItemNoti::ItemOper, SeItemNoti::pveAttr, SeItemNoti::pvpAttr.
Referenced by EncodeSeItemNoti, EncodeSeTC_PlayerNewItem.
int EncodeSeItemNoti(SeItemOper ItemOper, DWord dwID, Word Index, DWord ItemID, DWord dwAddedLevel, DWord dwLostTime, DWord dwOverlap, const SeAttrUnit *pveAttr, const SeAttrUnit *pvpAttr, const SeCiTiao *citiaoAttr, bool bNew, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeAttrUnit, EncodeSeCiTiao, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SSD_MAX_ATTR_NUM, SeNetStream::Write.
int EncodeSeItemNoti(SeItemOper ItemOper, DWord dwID, Word Index, DWord ItemID, DWord dwAddedLevel, DWord dwLostTime, DWord dwOverlap, std::vector< SeAttrUnit > &pveAttr, std::vector< SeAttrUnit > &pvpAttr, std::vector< SeCiTiao > &citiaoAttr, bool bNew, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeAttrUnit, EncodeSeCiTiao, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SSD_MAX_ATTR_NUM, SeNetStream::Write.
int DecodeSeItemNoti(const char *pkData, int iLen, SeItemNoti &kStruct)
References SeNetStream::Attach, SeItemNoti::bNew, SeItemNoti::citiaoAttr, DecodeSeAttrUnit, DecodeSeCiTiao, SeItemNoti::dwAddedLevel, SeItemNoti::dwID, SeItemNoti::dwLostTime, SeItemNoti::dwOverlap, SeNetStream::GetCurPos, SeItemNoti::Index, SeItemNoti::ItemID, SeItemNoti::ItemOper, SeItemNoti::pveAttr, SeItemNoti::pvpAttr, SeNetStream::Read, SeNetStream::SetCurPos, SSD_MAX_ATTR_NUM.
Referenced by DecodeSeTC_PlayerNewItem.
int EncodeSeRaceGameInfo(const SeRaceGameInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeRaceGameInfo, SeRaceGameInfo::game_mode, SeRaceGameInfo::game_time, SeRaceGameInfo::race_mmr, SeRaceGameInfo::watch_user_num.
Referenced by EncodeSeRaceGameInfo, EncodeSeRaceInfo.
int EncodeSeRaceGameInfo(int game_mode, int game_time, int watch_user_num, int race_mmr, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceGameInfo(const char *pkData, int iLen, SeRaceGameInfo &kStruct)
References SeNetStream::Attach, SeRaceGameInfo::game_mode, SeRaceGameInfo::game_time, SeNetStream::GetCurPos, SeRaceGameInfo::race_mmr, SeNetStream::Read, SeRaceGameInfo::watch_user_num.
Referenced by DecodeSeRaceInfo.
int EncodeSeRaceUserHeroInfo(const SeRaceUserHeroInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceUserHeroInfo::dwHeroID, SeRaceUserHeroInfo::dwHeroSkinID, EncodeSeRaceUserHeroInfo, SeRaceUserHeroInfo::race_assist, SeRaceUserHeroInfo::race_death, SeRaceUserHeroInfo::race_kill.
Referenced by EncodeSeRaceUserHeroInfo, EncodeSeRaceUserInfo.
int EncodeSeRaceUserHeroInfo(DWord dwHeroID, DWord dwHeroSkinID, int race_kill, int race_death, int race_assist, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceUserHeroInfo(const char *pkData, int iLen, SeRaceUserHeroInfo &kStruct)
References SeNetStream::Attach, SeRaceUserHeroInfo::dwHeroID, SeRaceUserHeroInfo::dwHeroSkinID, SeNetStream::GetCurPos, SeRaceUserHeroInfo::race_assist, SeRaceUserHeroInfo::race_death, SeRaceUserHeroInfo::race_kill, SeNetStream::Read.
Referenced by DecodeSeRaceUserInfo.
int EncodeSeRaceUserInfo(const SeRaceUserInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceUserInfo::acName, SeRaceUserInfo::dwPlayerID, SeRaceUserInfo::dwTeamID, SeRaceUserInfo::eCamp, EncodeSeRaceUserInfo, SeRaceUserInfo::iSeatIndex, SeRaceUserInfo::race_user_hero.
Referenced by EncodeSeRaceInfo, EncodeSeRaceUserInfo.
int EncodeSeRaceUserInfo(DWord dwPlayerID, int iSeatIndex, const char *acName, DWord dwTeamID, SeRoomPlayerCamp eCamp, const SeRaceUserHeroInfo &race_user_hero, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceUserHeroInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeRaceUserInfo(const char *pkData, int iLen, SeRaceUserInfo &kStruct)
References SeRaceUserInfo::acName, SeNetStream::Attach, DecodeSeRaceUserHeroInfo, SeRaceUserInfo::dwPlayerID, SeRaceUserInfo::dwTeamID, SeRaceUserInfo::eCamp, SeNetStream::GetCurPos, SeRaceUserInfo::iSeatIndex, SeRaceUserInfo::race_user_hero, SeNetStream::Read, SeNetStream::ReadString, SeNetStream::SetCurPos.
Referenced by DecodeSeRaceInfo.
int EncodeSeRaceMapPosInfo(const SeRaceMapPosInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceMapPosInfo::barrack_pos, SeRaceMapPosInfo::base_pos, SeRaceMapPosInfo::camp_id, SeRaceMapPosInfo::defense_town_pos, EncodeSeRaceMapPosInfo.
Referenced by EncodeSeRaceMapInfo, EncodeSeRaceMapPosInfo.
int EncodeSeRaceMapPosInfo(int camp_id, const int *base_pos, const int *barrack_pos, const int *defense_town_pos, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRaceMapPosInfo(int camp_id, std::vector< int > &base_pos, std::vector< int > &barrack_pos, std::vector< int > &defense_town_pos, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceMapPosInfo(const char *pkData, int iLen, SeRaceMapPosInfo &kStruct)
References SeNetStream::Attach, SeRaceMapPosInfo::barrack_pos, SeRaceMapPosInfo::base_pos, SeRaceMapPosInfo::camp_id, SeRaceMapPosInfo::defense_town_pos, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeRaceMapInfo.
int EncodeSeRaceBaseBuildingInfo(const SeRaceBaseBuildingInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceBaseBuildingInfo::dwMapBuildingType, EncodeSeRaceBaseBuildingInfo, SeRaceBaseBuildingInfo::pos_x, SeRaceBaseBuildingInfo::pos_y.
Referenced by EncodeSeRaceBaseBuildingInfo, EncodeSeRaceCampBuildingInfo.
int EncodeSeRaceBaseBuildingInfo(DWord dwMapBuildingType, int pos_x, int pos_y, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceBaseBuildingInfo(const char *pkData, int iLen, SeRaceBaseBuildingInfo &kStruct)
References SeNetStream::Attach, SeRaceBaseBuildingInfo::dwMapBuildingType, SeNetStream::GetCurPos, SeRaceBaseBuildingInfo::pos_x, SeRaceBaseBuildingInfo::pos_y, SeNetStream::Read.
Referenced by DecodeSeRaceCampBuildingInfo.
int EncodeSeRaceCampBuildingInfo(const SeRaceCampBuildingInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceCampBuildingInfo::alive_num, SeRaceCampBuildingInfo::base_building, SeRaceCampBuildingInfo::camp_id, EncodeSeRaceCampBuildingInfo.
Referenced by EncodeSeRaceCampBuildingInfo, EncodeSeRaceMapBuildingInfo.
int EncodeSeRaceCampBuildingInfo(int camp_id, int alive_num, const SeRaceBaseBuildingInfo *base_building, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceBaseBuildingInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeRaceCampBuildingInfo(int camp_id, int alive_num, std::vector< SeRaceBaseBuildingInfo > &base_building, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceBaseBuildingInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeRaceCampBuildingInfo(const char *pkData, int iLen, SeRaceCampBuildingInfo &kStruct)
References SeRaceCampBuildingInfo::alive_num, SeNetStream::Attach, SeRaceCampBuildingInfo::base_building, SeRaceCampBuildingInfo::camp_id, DecodeSeRaceBaseBuildingInfo, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::SetCurPos.
Referenced by DecodeSeRaceMapBuildingInfo.
int EncodeSeRaceMapBuildingInfo(const SeRaceMapBuildingInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceMapBuildingInfo::camp_building, EncodeSeRaceMapBuildingInfo.
Referenced by EncodeSeRaceMapBuildingInfo, EncodeSeRaceMapInfo.
int EncodeSeRaceMapBuildingInfo(const SeRaceCampBuildingInfo *camp_building, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceCampBuildingInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int EncodeSeRaceMapBuildingInfo(std::vector< SeRaceCampBuildingInfo > &camp_building, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceCampBuildingInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeRaceMapBuildingInfo(const char *pkData, int iLen, SeRaceMapBuildingInfo &kStruct)
References SeNetStream::Attach, SeRaceMapBuildingInfo::camp_building, DecodeSeRaceCampBuildingInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
Referenced by DecodeSeRaceMapInfo.
int EncodeSeRaceMapInfo(const SeRaceMapInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceMapInfo::dwMapID, EncodeSeRaceMapInfo, SeRaceMapInfo::race_map_building, SeRaceMapInfo::race_map_pos.
Referenced by EncodeSeRaceInfo, EncodeSeRaceMapInfo.
int EncodeSeRaceMapInfo(DWord dwMapID, const SeRaceMapPosInfo *race_map_pos, const SeRaceMapBuildingInfo &race_map_building, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceMapBuildingInfo, EncodeSeRaceMapPosInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeRaceMapInfo(DWord dwMapID, std::vector< SeRaceMapPosInfo > &race_map_pos, const SeRaceMapBuildingInfo &race_map_building, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceMapBuildingInfo, EncodeSeRaceMapPosInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeRaceMapInfo(const char *pkData, int iLen, SeRaceMapInfo &kStruct)
References SeNetStream::Attach, DecodeSeRaceMapBuildingInfo, DecodeSeRaceMapPosInfo, SeRaceMapInfo::dwMapID, SeNetStream::GetCurPos, SeRaceMapInfo::race_map_building, SeRaceMapInfo::race_map_pos, SeNetStream::Read, SeNetStream::SetCurPos.
Referenced by DecodeSeRaceInfo.
int EncodeSeRaceInfo(const SeRaceInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeRaceInfo, SeRaceInfo::race_game, SeRaceInfo::race_map, SeRaceInfo::race_user.
Referenced by EncodeSeRaceDetailInfo, EncodeSeRaceInfo.
int EncodeSeRaceInfo(const SeRaceGameInfo &race_game, const SeRaceMapInfo &race_map, const SeRaceUserInfo *race_user, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceGameInfo, EncodeSeRaceMapInfo, EncodeSeRaceUserInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int EncodeSeRaceInfo(const SeRaceGameInfo &race_game, const SeRaceMapInfo &race_map, std::vector< SeRaceUserInfo > &race_user, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceGameInfo, EncodeSeRaceMapInfo, EncodeSeRaceUserInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeRaceInfo(const char *pkData, int iLen, SeRaceInfo &kStruct)
References SeNetStream::Attach, DecodeSeRaceGameInfo, DecodeSeRaceMapInfo, DecodeSeRaceUserInfo, SeNetStream::GetCurPos, SeRaceInfo::race_game, SeRaceInfo::race_map, SeRaceInfo::race_user, SeNetStream::SetCurPos.
Referenced by DecodeSeRaceDetailInfo.
int EncodeSeRaceDetailInfo(const SeRaceDetailInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeRaceDetailInfo, SeRaceDetailInfo::race_info, SeRaceDetailInfo::rase_id.
Referenced by EncodeSeRaceDetailInfo, EncodeSeTC_ResRaceDetailInfo.
int EncodeSeRaceDetailInfo(const Byte *rase_id, const SeRaceInfo &race_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeRaceDetailInfo(std::vector< Byte > &rase_id, const SeRaceInfo &race_info, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeRaceInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeRaceDetailInfo(const char *pkData, int iLen, SeRaceDetailInfo &kStruct)
References SeNetStream::Attach, DecodeSeRaceInfo, SeNetStream::GetCurPos, SeRaceDetailInfo::race_info, SeRaceDetailInfo::rase_id, SeNetStream::Read, SeNetStream::SetCurPos.
Referenced by DecodeSeTC_ResRaceDetailInfo.
int EncodeShopItem(const ShopItem &kData, char *pcBuf, int iMaxLen)
References ShopItem::dwFeature, ShopItem::dwItemID, ShopItem::dwPrice, ShopItem::dwResetCount, ShopItem::dwShopID, ShopItem::dwSingleCount, ShopItem::dwStockCount, EncodeShopItem, ShopItem::fDisco.
Referenced by EncodeSeCT_ShopItemGM, EncodeSeTC_ShopItemGmRep, EncodeShopItem.
int EncodeShopItem(DWord dwShopID, DWord dwItemID, DWord dwPrice, float fDisco, DWord dwFeature, DWord dwStockCount, DWord dwSingleCount, DWord dwResetCount, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeShopItem(const char *pkData, int iLen, ShopItem &kStruct)
References SeNetStream::Attach, ShopItem::dwFeature, ShopItem::dwItemID, ShopItem::dwPrice, ShopItem::dwResetCount, ShopItem::dwShopID, ShopItem::dwSingleCount, ShopItem::dwStockCount, ShopItem::fDisco, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeCT_ShopItemGM, DecodeSeTC_ShopItemGmRep.
int EncodeSeNexusUserBaseInfo(const SeNexusUserBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeNexusUserBaseInfo::acName, SeNexusUserBaseInfo::dwPlayerId, EncodeSeNexusUserBaseInfo.
Referenced by EncodeSeNexusPlayerInfo, EncodeSeNexusUserBaseInfo, EncodeSeNexusUserInfo, EncodeSeNexusUserPromotionInfo.
int EncodeSeNexusUserBaseInfo(DWord dwPlayerId, const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeNexusUserBaseInfo(const char *pkData, int iLen, SeNexusUserBaseInfo &kStruct)
References SeNexusUserBaseInfo::acName, SeNetStream::Attach, SeNexusUserBaseInfo::dwPlayerId, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeNexusPlayerInfo, DecodeSeNexusUserInfo, DecodeSeNexusUserPromotionInfo.
int EncodeSeNexusKeyInfo(const SeNexusKeyInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeNexusKeyInfo, SeNexusKeyInfo::key.
Referenced by EncodeSeNexusKeyInfo, EncodeSeNexusPlayerInfo, EncodeSeNexusUserInfo, EncodeSeNexusUserPromotionInfo.
int EncodeSeNexusKeyInfo(int key, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeNexusKeyInfo(const char *pkData, int iLen, SeNexusKeyInfo &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNexusKeyInfo::key, SeNetStream::Read.
Referenced by DecodeSeNexusPlayerInfo, DecodeSeNexusUserInfo, DecodeSeNexusUserPromotionInfo.
int EncodeSeNexusUserInfo(const SeNexusUserInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeNexusUserInfo, SeNexusUserInfo::friend_info, SeNexusUserInfo::mark, SeNexusUserInfo::user_info.
Referenced by EncodeSeCT_NexusUserActionReq, EncodeSeNexusUserInfo, EncodeSeTC_NexusUserActionSync.
int EncodeSeNexusUserInfo(const SeNexusUserBaseInfo &user_info, const SeNexusUserBaseInfo &friend_info, const SeNexusKeyInfo &mark, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusKeyInfo, EncodeSeNexusUserBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeNexusUserInfo(const char *pkData, int iLen, SeNexusUserInfo &kStruct)
References SeNetStream::Attach, DecodeSeNexusKeyInfo, DecodeSeNexusUserBaseInfo, SeNexusUserInfo::friend_info, SeNetStream::GetCurPos, SeNexusUserInfo::mark, SeNetStream::SetCurPos, SeNexusUserInfo::user_info.
Referenced by DecodeSeCT_NexusUserActionReq, DecodeSeTC_NexusUserActionSync.
int EncodeSeNexusUserPromotionInfo(const SeNexusUserPromotionInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeNexusUserPromotionInfo, SeNexusUserPromotionInfo::options_apply, SeNexusUserPromotionInfo::options_hide, SeNexusUserPromotionInfo::options_invite, SeNexusUserPromotionInfo::options_outlander, SeNexusUserPromotionInfo::user_info.
Referenced by EncodeSeCT_NexusUserPromotionReq, EncodeSeNexusUserPromotionInfo, EncodeSeTC_NexusUserPromotionDetailInfoRes.
int EncodeSeNexusUserPromotionInfo(const SeNexusUserBaseInfo &user_info, const SeNexusKeyInfo &options_apply, const SeNexusKeyInfo &options_invite, const SeNexusKeyInfo &options_outlander, const SeNexusKeyInfo &options_hide, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusKeyInfo, EncodeSeNexusUserBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeNexusUserPromotionInfo(const char *pkData, int iLen, SeNexusUserPromotionInfo &kStruct)
References SeNetStream::Attach, DecodeSeNexusKeyInfo, DecodeSeNexusUserBaseInfo, SeNetStream::GetCurPos, SeNexusUserPromotionInfo::options_apply, SeNexusUserPromotionInfo::options_hide, SeNexusUserPromotionInfo::options_invite, SeNexusUserPromotionInfo::options_outlander, SeNetStream::SetCurPos, SeNexusUserPromotionInfo::user_info.
Referenced by DecodeSeCT_NexusUserPromotionReq, DecodeSeTC_NexusUserPromotionDetailInfoRes.
int EncodeSeNexusPlayerInfo(const SeNexusPlayerInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeNexusPlayerInfo, SeNexusPlayerInfo::mark, SeNexusPlayerInfo::status, SeNexusPlayerInfo::user_info.
Referenced by EncodeSeNexusPlayerInfo, EncodeSeTC_NexusFriendDetailInfoRes.
int EncodeSeNexusPlayerInfo(const SeNexusUserBaseInfo &user_info, const SeNexusKeyInfo &mark, const SeNexusKeyInfo &status, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusKeyInfo, EncodeSeNexusUserBaseInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeNexusPlayerInfo(const char *pkData, int iLen, SeNexusPlayerInfo &kStruct)
References SeNetStream::Attach, DecodeSeNexusKeyInfo, DecodeSeNexusUserBaseInfo, SeNetStream::GetCurPos, SeNexusPlayerInfo::mark, SeNetStream::SetCurPos, SeNexusPlayerInfo::status, SeNexusPlayerInfo::user_info.
Referenced by DecodeSeTC_NexusFriendDetailInfoRes.
int EncodeSeUserArchivesNameInfo(const SeUserArchivesNameInfo &kData, char *pcBuf, int iMaxLen)
References SeUserArchivesNameInfo::acName, EncodeSeUserArchivesNameInfo.
Referenced by EncodeSeCT_SearchUserArchivesInfoReq, EncodeSeUserArchivesNameInfo.
int EncodeSeUserArchivesNameInfo(const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::WriteString.
int DecodeSeUserArchivesNameInfo(const char *pkData, int iLen, SeUserArchivesNameInfo &kStruct)
References SeUserArchivesNameInfo::acName, SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::ReadString.
Referenced by DecodeSeCT_SearchUserArchivesInfoReq.
int EncodeSeUserArchivesInfo(const SeUserArchivesInfo &kData, char *pcBuf, int iMaxLen)
References SeUserArchivesInfo::acName, SeUserArchivesInfo::dwPlayerId, EncodeSeUserArchivesInfo.
Referenced by EncodeSeTC_SearchUserArchivesDetailInfoRes, EncodeSeTC_SearchUserArchivesInfoRes, EncodeSeUserArchivesInfo.
int EncodeSeUserArchivesInfo(DWord dwPlayerId, const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeUserArchivesInfo(const char *pkData, int iLen, SeUserArchivesInfo &kStruct)
References SeUserArchivesInfo::acName, SeNetStream::Attach, SeUserArchivesInfo::dwPlayerId, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeTC_SearchUserArchivesDetailInfoRes, DecodeSeTC_SearchUserArchivesInfoRes.
int EncodeSeNexusFriendSyncInfo(const SeNexusFriendSyncInfo &kData, char *pcBuf, int iMaxLen)
References SeNexusFriendSyncInfo::acName, SeNexusFriendSyncInfo::dwMark, SeNexusFriendSyncInfo::dwPlayerFriendID, SeNexusFriendSyncInfo::dwPlayerID, EncodeSeNexusFriendSyncInfo.
Referenced by EncodeSeNexusFriendSyncInfo.
int EncodeSeNexusFriendSyncInfo(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeNexusFriendSyncInfo(const char *pkData, int iLen, SeNexusFriendSyncInfo &kStruct)
References SeNexusFriendSyncInfo::acName, SeNetStream::Attach, SeNexusFriendSyncInfo::dwMark, SeNexusFriendSyncInfo::dwPlayerFriendID, SeNexusFriendSyncInfo::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeNexusTeamBaseInfo(const SeNexusTeamBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeNexusTeamBaseInfo::acTeamId, SeNexusTeamBaseInfo::acTeamName, SeNexusTeamBaseInfo::dwCreateTime, SeNexusTeamBaseInfo::dwMembers, SeNexusTeamBaseInfo::dwType, EncodeSeNexusTeamBaseInfo.
Referenced by EncodeSeNexusTeamBaseInfo.
int EncodeSeNexusTeamBaseInfo(const char *acTeamId, const char *acTeamName, DWord dwType, DWord dwMembers, DWord dwCreateTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeNexusTeamBaseInfo(const char *pkData, int iLen, SeNexusTeamBaseInfo &kStruct)
References SeNexusTeamBaseInfo::acTeamId, SeNexusTeamBaseInfo::acTeamName, SeNetStream::Attach, SeNexusTeamBaseInfo::dwCreateTime, SeNexusTeamBaseInfo::dwMembers, SeNexusTeamBaseInfo::dwType, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeNexusTeamMemberInfo(const SeNexusTeamMemberInfo &kData, char *pcBuf, int iMaxLen)
References SeNexusTeamMemberInfo::acName, SeNexusTeamMemberInfo::acTeamId, SeNexusTeamMemberInfo::dwAction, SeNexusTeamMemberInfo::dwInviteTime, SeNexusTeamMemberInfo::dwJoinTime, SeNexusTeamMemberInfo::dwMark, SeNexusTeamMemberInfo::dwOrderId, SeNexusTeamMemberInfo::dwPlayerID, EncodeSeNexusTeamMemberInfo.
Referenced by EncodeSeNexusTeamMemberInfo.
int EncodeSeNexusTeamMemberInfo(DWord dwPlayerID, const char *acName, const char *acTeamId, DWord dwMark, DWord dwAction, DWord dwJoinTime, DWord dwInviteTime, DWord dwOrderId, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeNexusTeamMemberInfo(const char *pkData, int iLen, SeNexusTeamMemberInfo &kStruct)
References SeNexusTeamMemberInfo::acName, SeNexusTeamMemberInfo::acTeamId, SeNetStream::Attach, SeNexusTeamMemberInfo::dwAction, SeNexusTeamMemberInfo::dwInviteTime, SeNexusTeamMemberInfo::dwJoinTime, SeNexusTeamMemberInfo::dwMark, SeNexusTeamMemberInfo::dwOrderId, SeNexusTeamMemberInfo::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeScoreInfo(const SeScoreInfo &kData, char *pcBuf, int iMaxLen)
References SeScoreInfo::defeat, EncodeSeScoreInfo, SeScoreInfo::level, SeScoreInfo::score.
Referenced by EncodeMatchValueStru, EncodeSeScoreInfo.
int EncodeSeScoreInfo(Byte defeat, DWord score, DWord level, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeScoreInfo(const char *pkData, int iLen, SeScoreInfo &kStruct)
References SeNetStream::Attach, SeScoreInfo::defeat, SeNetStream::GetCurPos, SeScoreInfo::level, SeNetStream::Read, SeScoreInfo::score.
Referenced by DecodeMatchValueStru.
int EncodeMatchValueStru(const MatchValueStru &kData, char *pcBuf, int iMaxLen)
References MatchValueStru::dwMatchNum, MatchValueStru::dwPlayerID, EncodeMatchValueStru, MatchValueStru::NameStr, MatchValueStru::ScoreInfo.
Referenced by EncodeMatchValueStru.
int EncodeMatchValueStru(DWord dwPlayerID, const char *NameStr, DWord dwMatchNum, const SeScoreInfo &ScoreInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeScoreInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeMatchValueStru(const char *pkData, int iLen, MatchValueStru &kStruct)
References SeNetStream::Attach, DecodeSeScoreInfo, MatchValueStru::dwMatchNum, MatchValueStru::dwPlayerID, SeNetStream::GetCurPos, MatchValueStru::NameStr, SeNetStream::Read, SeNetStream::ReadString, MatchValueStru::ScoreInfo, SeNetStream::SetCurPos.
int EncodePlayerGradeStru(const PlayerGradeStru &kData, char *pcBuf, int iMaxLen)
References PlayerGradeStru::bolWin, PlayerGradeStru::dwGrade, EncodePlayerGradeStru.
Referenced by EncodePlayerGrades, EncodePlayerGradeStru.
int EncodePlayerGradeStru(DWord dwGrade, bool bolWin, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodePlayerGradeStru(const char *pkData, int iLen, PlayerGradeStru &kStruct)
References SeNetStream::Attach, PlayerGradeStru::bolWin, PlayerGradeStru::dwGrade, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodePlayerGrades.
int EncodePlayerGrades(const PlayerGrades &kData, char *pcBuf, int iMaxLen)
References EncodePlayerGrades, PlayerGrades::Num, PlayerGrades::playerGradeStru.
Referenced by EncodePlayerGrades.
int EncodePlayerGrades(DWord Num, const PlayerGradeStru *playerGradeStru, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodePlayerGradeStru, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodePlayerGrades(DWord Num, std::vector< PlayerGradeStru > &playerGradeStru, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodePlayerGradeStru, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodePlayerGrades(const char *pkData, int iLen, PlayerGrades &kStruct)
References SeNetStream::Attach, DecodePlayerGradeStru, SeNetStream::GetCurPos, PlayerGrades::Num, PlayerGrades::playerGradeStru, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeLadderDetailInfo(const SeLadderDetailInfo &kData, char *pcBuf, int iMaxLen)
References SeLadderDetailInfo::dwMvpNUm, SeLadderDetailInfo::dwRaceNum, SeLadderDetailInfo::dwSuperNUm, SeLadderDetailInfo::dwWinNUm, EncodeSeLadderDetailInfo.
Referenced by EncodeSeLadderDetailInfo, EncodeSeTC_LadderDetailInfoAck.
int EncodeSeLadderDetailInfo(DWord dwRaceNum, DWord dwMvpNUm, DWord dwWinNUm, DWord dwSuperNUm, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeLadderDetailInfo(const char *pkData, int iLen, SeLadderDetailInfo &kStruct)
References SeNetStream::Attach, SeLadderDetailInfo::dwMvpNUm, SeLadderDetailInfo::dwRaceNum, SeLadderDetailInfo::dwSuperNUm, SeLadderDetailInfo::dwWinNUm, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_LadderDetailInfoAck.
int EncodeSeRaceEndArenaDetailInfo(const SeRaceEndArenaDetailInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceEndArenaDetailInfo::dwMapID, SeRaceEndArenaDetailInfo::dwPlayerID, EncodeSeRaceEndArenaDetailInfo, SeRaceEndArenaDetailInfo::iAssists, SeRaceEndArenaDetailInfo::iBest, SeRaceEndArenaDetailInfo::iBlood_1, SeRaceEndArenaDetailInfo::iDies, SeRaceEndArenaDetailInfo::iEnemyEyes, SeRaceEndArenaDetailInfo::iKills, SeRaceEndArenaDetailInfo::iKills_3, SeRaceEndArenaDetailInfo::iKills_4, SeRaceEndArenaDetailInfo::iKills_5, SeRaceEndArenaDetailInfo::iMvp, SeRaceEndArenaDetailInfo::iPlaceEyes, SeRaceEndArenaDetailInfo::iRaceFlag, SeRaceEndArenaDetailInfo::iRaceNum, SeRaceEndArenaDetailInfo::iSuper, SeRaceEndArenaDetailInfo::iTitle, SeRaceEndArenaDetailInfo::iTotalBeDamage, SeRaceEndArenaDetailInfo::iTotalDamage, SeRaceEndArenaDetailInfo::iTotalGold.
Referenced by EncodeSeRaceEndArenaDetailInfo.
int EncodeSeRaceEndArenaDetailInfo(DWord dwPlayerID, DWord dwMapID, DWord iKills, DWord iAssists, DWord iDies, DWord iTotalGold, DWord iTotalDamage, DWord iTotalBeDamage, DWord iKills_3, DWord iKills_4, DWord iKills_5, DWord iBlood_1, DWord iMvp, DWord iSuper, DWord iTitle, DWord iBest, DWord iPlaceEyes, DWord iEnemyEyes, DWord iRaceFlag, DWord iRaceNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceEndArenaDetailInfo(const char *pkData, int iLen, SeRaceEndArenaDetailInfo &kStruct)
References SeNetStream::Attach, SeRaceEndArenaDetailInfo::dwMapID, SeRaceEndArenaDetailInfo::dwPlayerID, SeNetStream::GetCurPos, SeRaceEndArenaDetailInfo::iAssists, SeRaceEndArenaDetailInfo::iBest, SeRaceEndArenaDetailInfo::iBlood_1, SeRaceEndArenaDetailInfo::iDies, SeRaceEndArenaDetailInfo::iEnemyEyes, SeRaceEndArenaDetailInfo::iKills, SeRaceEndArenaDetailInfo::iKills_3, SeRaceEndArenaDetailInfo::iKills_4, SeRaceEndArenaDetailInfo::iKills_5, SeRaceEndArenaDetailInfo::iMvp, SeRaceEndArenaDetailInfo::iPlaceEyes, SeRaceEndArenaDetailInfo::iRaceFlag, SeRaceEndArenaDetailInfo::iRaceNum, SeRaceEndArenaDetailInfo::iSuper, SeRaceEndArenaDetailInfo::iTitle, SeRaceEndArenaDetailInfo::iTotalBeDamage, SeRaceEndArenaDetailInfo::iTotalDamage, SeRaceEndArenaDetailInfo::iTotalGold, SeNetStream::Read.
int EncodeSeRaceEndArenaBaseInfo(const SeRaceEndArenaBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeRaceEndArenaBaseInfo::dwPlayerID, EncodeSeRaceEndArenaBaseInfo, SeRaceEndArenaBaseInfo::iCumuGold, SeRaceEndArenaBaseInfo::iExp, SeRaceEndArenaBaseInfo::iGold.
Referenced by EncodeSeRaceEndArenaBaseInfo.
int EncodeSeRaceEndArenaBaseInfo(DWord dwPlayerID, DWord iGold, DWord iExp, DWord iCumuGold, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceEndArenaBaseInfo(const char *pkData, int iLen, SeRaceEndArenaBaseInfo &kStruct)
References SeNetStream::Attach, SeRaceEndArenaBaseInfo::dwPlayerID, SeNetStream::GetCurPos, SeRaceEndArenaBaseInfo::iCumuGold, SeRaceEndArenaBaseInfo::iExp, SeRaceEndArenaBaseInfo::iGold, SeNetStream::Read.
int EncodeSeTeamMemberBaseInfo(const SeTeamMemberBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeTeamMemberBaseInfo::acMemberName, SeTeamMemberBaseInfo::dwBattleScores, SeTeamMemberBaseInfo::dwInviterID, SeTeamMemberBaseInfo::dwLadderScores, SeTeamMemberBaseInfo::dwMatchScores, SeTeamMemberBaseInfo::dwMemberID, SeTeamMemberBaseInfo::dwOrderID, SeTeamMemberBaseInfo::dwPunishTime, EncodeSeTeamMemberBaseInfo.
Referenced by EncodeSeTC_TeamMemberInfoRes, EncodeSeTeamMemberBaseInfo.
int EncodeSeTeamMemberBaseInfo(DWord dwMemberID, DWord dwOrderID, DWord dwInviterID, DWord dwPunishTime, DWord dwMatchScores, DWord dwLadderScores, DWord dwBattleScores, const char *acMemberName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeTeamMemberBaseInfo(const char *pkData, int iLen, SeTeamMemberBaseInfo &kStruct)
References SeTeamMemberBaseInfo::acMemberName, SeNetStream::Attach, SeTeamMemberBaseInfo::dwBattleScores, SeTeamMemberBaseInfo::dwInviterID, SeTeamMemberBaseInfo::dwLadderScores, SeTeamMemberBaseInfo::dwMatchScores, SeTeamMemberBaseInfo::dwMemberID, SeTeamMemberBaseInfo::dwOrderID, SeTeamMemberBaseInfo::dwPunishTime, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
Referenced by DecodeSeTC_TeamMemberInfoRes.
int EncodeSeUnlockHeroBaseInfo(const SeUnlockHeroBaseInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeUnlockHeroBaseInfo, SeUnlockHeroBaseInfo::heroID, SeUnlockHeroBaseInfo::mark.
Referenced by EncodeSeUnlockHeroBaseInfo.
int EncodeSeUnlockHeroBaseInfo(DWord heroID, DWord mark, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeUnlockHeroBaseInfo(const char *pkData, int iLen, SeUnlockHeroBaseInfo &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeUnlockHeroBaseInfo::heroID, SeUnlockHeroBaseInfo::mark, SeNetStream::Read.
int EncodeSeUserHeroSyncInfo(const SeUserHeroSyncInfo &kData, char *pcBuf, int iMaxLen)
References SeUserHeroSyncInfo::dwSkin, SeUserHeroSyncInfo::dwWeapon, SeUserHeroSyncInfo::dwWing, EncodeSeUserHeroSyncInfo, SeUserHeroSyncInfo::heroID, SeUserHeroSyncInfo::mark.
Referenced by EncodeSeTC_UserHeroSync, EncodeSeUserHeroSyncInfo.
int EncodeSeUserHeroSyncInfo(DWord heroID, SeUnLockHeroStatus mark, DWord dwSkin, DWord dwWeapon, DWord dwWing, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeUserHeroSyncInfo(const char *pkData, int iLen, SeUserHeroSyncInfo &kStruct)
References SeNetStream::Attach, SeUserHeroSyncInfo::dwSkin, SeUserHeroSyncInfo::dwWeapon, SeUserHeroSyncInfo::dwWing, SeNetStream::GetCurPos, SeUserHeroSyncInfo::heroID, SeUserHeroSyncInfo::mark, SeNetStream::Read.
Referenced by DecodeSeTC_UserHeroSync.
int EncodeSeLadderInfo(const SeLadderInfo &kData, char *pcBuf, int iMaxLen)
References SeLadderInfo::byLadderDefeat, SeLadderInfo::dwLadderScore, SeLadderInfo::dwLadderTime, EncodeSeLadderInfo, SeLadderInfo::wLadderLevel.
Referenced by EncodeSeLadderInfo, EncodeSeTC_InitPlayerInfo, EncodeSeTC_PlayerLadder.
int EncodeSeLadderInfo(Word wLadderLevel, DWord dwLadderScore, Byte byLadderDefeat, DWord dwLadderTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeLadderInfo(const char *pkData, int iLen, SeLadderInfo &kStruct)
References SeNetStream::Attach, SeLadderInfo::byLadderDefeat, SeLadderInfo::dwLadderScore, SeLadderInfo::dwLadderTime, SeNetStream::GetCurPos, SeNetStream::Read, SeLadderInfo::wLadderLevel.
Referenced by DecodeSeTC_InitPlayerInfo, DecodeSeTC_PlayerLadder.
int EncodeSeLadderRankInfo(const SeLadderRankInfo &kData, char *pcBuf, int iMaxLen)
References SeLadderRankInfo::acName, SeLadderRankInfo::dwPlayerID, EncodeSeLadderRankInfo, SeLadderRankInfo::iLadderLevel, SeLadderRankInfo::iLadderScore, SeLadderRankInfo::iPlayerLevel, SeLadderRankInfo::wIconID.
Referenced by EncodeSeLadderRankInfo, EncodeSeTC_FriendLadderInfoNtf, EncodeSeTC_LadderRankQueryAck.
int EncodeSeLadderRankInfo(DWord dwPlayerID, Word wIconID, int iLadderLevel, int iLadderScore, int iPlayerLevel, const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeLadderRankInfo(const char *pkData, int iLen, SeLadderRankInfo &kStruct)
References SeLadderRankInfo::acName, SeNetStream::Attach, SeLadderRankInfo::dwPlayerID, SeNetStream::GetCurPos, SeLadderRankInfo::iLadderLevel, SeLadderRankInfo::iLadderScore, SeLadderRankInfo::iPlayerLevel, SeNetStream::Read, SeNetStream::ReadString, SeLadderRankInfo::wIconID.
Referenced by DecodeSeTC_FriendLadderInfoNtf, DecodeSeTC_LadderRankQueryAck.
int EncodeSeUserStatusBaseInfo(const SeUserStatusBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeUserStatusBaseInfo::dwStatusID, SeUserStatusBaseInfo::dwUserID, EncodeSeUserStatusBaseInfo.
Referenced by EncodeSeTC_UserStatusQueryReqRes, EncodeSeUserStatusBaseInfo.
int EncodeSeUserStatusBaseInfo(DWord dwUserID, DWord dwStatusID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeUserStatusBaseInfo(const char *pkData, int iLen, SeUserStatusBaseInfo &kStruct)
References SeNetStream::Attach, SeUserStatusBaseInfo::dwStatusID, SeUserStatusBaseInfo::dwUserID, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_UserStatusQueryReqRes.
int EncodeSeEquipSchemaInfo(const SeEquipSchemaInfo &kData, char *pcBuf, int iMaxLen)
References SeEquipSchemaInfo::byIndex, SeEquipSchemaInfo::dwPart1, SeEquipSchemaInfo::dwPart10, SeEquipSchemaInfo::dwPart2, SeEquipSchemaInfo::dwPart3, SeEquipSchemaInfo::dwPart4, SeEquipSchemaInfo::dwPart5, SeEquipSchemaInfo::dwPart6, SeEquipSchemaInfo::dwPart7, SeEquipSchemaInfo::dwPart8, SeEquipSchemaInfo::dwPart9, EncodeSeEquipSchemaInfo.
Referenced by EncodeSeEquipSchemaInfo, EncodeSeTC_EquipSchema.
int EncodeSeEquipSchemaInfo(Byte byIndex, DWord dwPart1, DWord dwPart2, DWord dwPart3, DWord dwPart4, DWord dwPart5, DWord dwPart6, DWord dwPart7, DWord dwPart8, DWord dwPart9, DWord dwPart10, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeEquipSchemaInfo(const char *pkData, int iLen, SeEquipSchemaInfo &kStruct)
References SeNetStream::Attach, SeEquipSchemaInfo::byIndex, SeEquipSchemaInfo::dwPart1, SeEquipSchemaInfo::dwPart10, SeEquipSchemaInfo::dwPart2, SeEquipSchemaInfo::dwPart3, SeEquipSchemaInfo::dwPart4, SeEquipSchemaInfo::dwPart5, SeEquipSchemaInfo::dwPart6, SeEquipSchemaInfo::dwPart7, SeEquipSchemaInfo::dwPart8, SeEquipSchemaInfo::dwPart9, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_EquipSchema.
int EncodeSeRandBoxItem(const SeRandBoxItem &kData, char *pcBuf, int iMaxLen)
References SeRandBoxItem::dwItemID, SeRandBoxItem::dwNum, EncodeSeRandBoxItem.
Referenced by EncodeSeRandBoxItem, EncodeSeTC_OpenRandBoxRet.
int EncodeSeRandBoxItem(DWord dwItemID, DWord dwNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRandBoxItem(const char *pkData, int iLen, SeRandBoxItem &kStruct)
References SeNetStream::Attach, SeRandBoxItem::dwItemID, SeRandBoxItem::dwNum, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_OpenRandBoxRet.
int EncodeSeAwardItem(const SeAwardItem &kData, char *pcBuf, int iMaxLen)
References SeAwardItem::dwItemID, SeAwardItem::dwNum, EncodeSeAwardItem.
Referenced by EncodeSeAwardItem.
int EncodeSeAwardItem(DWord dwItemID, DWord dwNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeAwardItem(const char *pkData, int iLen, SeAwardItem &kStruct)
References SeNetStream::Attach, SeAwardItem::dwItemID, SeAwardItem::dwNum, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeUserRaceMapHeroBase(const SeUserRaceMapHeroBase &kData, char *pcBuf, int iMaxLen)
References SeUserRaceMapHeroBase::dwHeroID, SeUserRaceMapHeroBase::dwUseCounts, SeUserRaceMapHeroBase::dwWinCounts, EncodeSeUserRaceMapHeroBase.
Referenced by EncodeSeTC_UserRaceMapHeroAck, EncodeSeUserRaceMapHeroBase.
int EncodeSeUserRaceMapHeroBase(DWord dwHeroID, DWord dwUseCounts, DWord dwWinCounts, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeUserRaceMapHeroBase(const char *pkData, int iLen, SeUserRaceMapHeroBase &kStruct)
References SeNetStream::Attach, SeUserRaceMapHeroBase::dwHeroID, SeUserRaceMapHeroBase::dwUseCounts, SeUserRaceMapHeroBase::dwWinCounts, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_UserRaceMapHeroAck.
int EncodeSeUserBaseAttrInfo(const SeUserBaseAttrInfo &kData, char *pcBuf, int iMaxLen)
References SeUserBaseAttrInfo::acUserNickName, SeUserBaseAttrInfo::dwUserLevel, EncodeSeUserBaseAttrInfo.
Referenced by EncodeSeUserBaseAttrInfo.
int EncodeSeUserBaseAttrInfo(int dwUserLevel, const char *acUserNickName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeUserBaseAttrInfo(const char *pkData, int iLen, SeUserBaseAttrInfo &kStruct)
References SeUserBaseAttrInfo::acUserNickName, SeNetStream::Attach, SeUserBaseAttrInfo::dwUserLevel, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeSeatScore(const SeSeatScore &kData, char *pcBuf, int iMaxLen)
References EncodeSeSeatScore, SeSeatScore::iChanged, SeSeatScore::iOld.
Referenced by EncodeSeRC_SeatScoreNtf, EncodeSeSeatScore.
int EncodeSeSeatScore(int iOld, int iChanged, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeSeatScore(const char *pkData, int iLen, SeSeatScore &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeSeatScore::iChanged, SeSeatScore::iOld, SeNetStream::Read.
Referenced by DecodeSeRC_SeatScoreNtf.
int EncodeSeRaceEndArenaResult(const SeRaceEndArenaResult &kData, char *pcBuf, int iMaxLen)
References EncodeSeRaceEndArenaResult, SeRaceEndArenaResult::iAssists, SeRaceEndArenaResult::iBest, SeRaceEndArenaResult::iBlood_1, SeRaceEndArenaResult::iDies, SeRaceEndArenaResult::iEnemyEyes, SeRaceEndArenaResult::iKills, SeRaceEndArenaResult::iKills_3, SeRaceEndArenaResult::iKills_4, SeRaceEndArenaResult::iKills_5, SeRaceEndArenaResult::iMvp, SeRaceEndArenaResult::iPlaceEyes, SeRaceEndArenaResult::iRaceFlag, SeRaceEndArenaResult::iRaceNum, SeRaceEndArenaResult::iSuper, SeRaceEndArenaResult::iTitle, SeRaceEndArenaResult::iTotalBeDamage, SeRaceEndArenaResult::iTotalDamage, SeRaceEndArenaResult::iTotalGold.
Referenced by EncodeSeRaceEndArenaResult, EncodeSeTC_SeUserRaceArenaDetailInfoRes.
int EncodeSeRaceEndArenaResult(DWord iKills, DWord iAssists, DWord iDies, DWord iTotalGold, DWord iTotalDamage, DWord iTotalBeDamage, DWord iKills_3, DWord iKills_4, DWord iKills_5, DWord iBlood_1, DWord iMvp, DWord iSuper, DWord iTitle, DWord iBest, DWord iPlaceEyes, DWord iEnemyEyes, DWord iRaceFlag, DWord iRaceNum, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRaceEndArenaResult(const char *pkData, int iLen, SeRaceEndArenaResult &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeRaceEndArenaResult::iAssists, SeRaceEndArenaResult::iBest, SeRaceEndArenaResult::iBlood_1, SeRaceEndArenaResult::iDies, SeRaceEndArenaResult::iEnemyEyes, SeRaceEndArenaResult::iKills, SeRaceEndArenaResult::iKills_3, SeRaceEndArenaResult::iKills_4, SeRaceEndArenaResult::iKills_5, SeRaceEndArenaResult::iMvp, SeRaceEndArenaResult::iPlaceEyes, SeRaceEndArenaResult::iRaceFlag, SeRaceEndArenaResult::iRaceNum, SeRaceEndArenaResult::iSuper, SeRaceEndArenaResult::iTitle, SeRaceEndArenaResult::iTotalBeDamage, SeRaceEndArenaResult::iTotalDamage, SeRaceEndArenaResult::iTotalGold, SeNetStream::Read.
Referenced by DecodeSeTC_SeUserRaceArenaDetailInfoRes.
int EncodeSeAchieveFinish(const SeAchieveFinish &kData, char *pcBuf, int iMaxLen)
References SeAchieveFinish::bState, SeAchieveFinish::dwAchieveID, SeAchieveFinish::dwReachTime, EncodeSeAchieveFinish.
Referenced by EncodeSeAchieveFinish, EncodeSeTC_AchieveInfoAck.
int EncodeSeAchieveFinish(DWord dwAchieveID, bool bState, DWord dwReachTime, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeAchieveFinish(const char *pkData, int iLen, SeAchieveFinish &kStruct)
References SeNetStream::Attach, SeAchieveFinish::bState, SeAchieveFinish::dwAchieveID, SeAchieveFinish::dwReachTime, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_AchieveInfoAck.
int EncodeSeAchieveSchedule(const SeAchieveSchedule &kData, char *pcBuf, int iMaxLen)
References SeAchieveSchedule::dwGroupID, SeAchieveSchedule::dwParameter, EncodeSeAchieveSchedule.
Referenced by EncodeSeAchieveSchedule, EncodeSeTC_AchieveInfoAck.
int EncodeSeAchieveSchedule(DWord dwGroupID, DWord dwParameter, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeAchieveSchedule(const char *pkData, int iLen, SeAchieveSchedule &kStruct)
References SeNetStream::Attach, SeAchieveSchedule::dwGroupID, SeAchieveSchedule::dwParameter, SeNetStream::GetCurPos, SeNetStream::Read.
Referenced by DecodeSeTC_AchieveInfoAck.