SeLCStream.cpp
int EncodeSeLC_EncryptKey(const SeLC_EncryptKey &kData, char *pcBuf, int iMaxLen)
References SeLC_EncryptKey::abyEncryptKey, EncodeSeLC_EncryptKey.
Referenced by EncodeSeLC_EncryptKey.
int EncodeSeLC_EncryptKey(const char *abyEncryptKey, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::WriteString.
int DecodeSeLC_EncryptKey(const char *pkData, int iLen, SeLC_EncryptKey &kStruct)
References SeLC_EncryptKey::abyEncryptKey, SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::ReadString.
int EncodeSeLC_PlayerLoginRet(const SeLC_PlayerLoginRet &kData, char *pcBuf, int iMaxLen)
References SeLC_PlayerLoginRet::dwPlayerID, SeLC_PlayerLoginRet::dwSessionID, EncodeSeLC_PlayerLoginRet, SeLC_PlayerLoginRet::eReason, SeLC_PlayerLoginRet::strNickName.
Referenced by EncodeSeLC_PlayerLoginRet.
int EncodeSeLC_PlayerLoginRet(DWord dwPlayerID, SeLoginReason eReason, DWord dwSessionID, const char *strNickName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeLC_PlayerLoginRet(const char *pkData, int iLen, SeLC_PlayerLoginRet &kStruct)
References SeNetStream::Attach, SeLC_PlayerLoginRet::dwPlayerID, SeLC_PlayerLoginRet::dwSessionID, SeLC_PlayerLoginRet::eReason, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString, SeLC_PlayerLoginRet::strNickName.
int EncodeSeLC_GateList(const SeLC_GateList &kData, char *pcBuf, int iMaxLen)
References SeLC_GateList::acIP, EncodeSeLC_GateList, SeLC_GateList::iPort.
Referenced by EncodeSeLC_GateList.
int EncodeSeLC_GateList(const char *acIP, int iPort, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeLC_GateList(const char *pkData, int iLen, SeLC_GateList &kStruct)
References SeLC_GateList::acIP, SeNetStream::Attach, SeNetStream::GetCurPos, SeLC_GateList::iPort, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeLC_ClientVersion(const SeLC_ClientVersion &kData, char *pcBuf, int iMaxLen)
References EncodeSeLC_ClientVersion, SeLC_ClientVersion::main, SeLC_ClientVersion::sub, SeLC_ClientVersion::ver.
Referenced by EncodeSeLC_ClientVersion.
int EncodeSeLC_ClientVersion(DWord main, DWord sub, const char *ver, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeLC_ClientVersion(const char *pkData, int iLen, SeLC_ClientVersion &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeLC_ClientVersion::main, SeNetStream::Read, SeNetStream::ReadString, SeLC_ClientVersion::sub, SeLC_ClientVersion::ver.
int EncodeSeLC_SteamCheckReturn(const SeLC_SteamCheckReturn &kData, char *pcBuf, int iMaxLen)
References EncodeSeLC_SteamCheckReturn, SeLC_SteamCheckReturn::eResult.
Referenced by EncodeSeLC_SteamCheckReturn.
int EncodeSeLC_SteamCheckReturn(SteamCheckResult eResult, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeLC_SteamCheckReturn(const char *pkData, int iLen, SeLC_SteamCheckReturn &kStruct)
References SeNetStream::Attach, SeLC_SteamCheckReturn::eResult, SeNetStream::GetCurPos, SeNetStream::Read.