SeCLStream.cpp
int EncodeSeCL_PlayerLogin(const SeCL_PlayerLogin &kData, char *pcBuf, int iMaxLen)
References SeCL_PlayerLogin::acAccount, SeCL_PlayerLogin::acPassword, SeCL_PlayerLogin::bForceKick, SeCL_PlayerLogin::dwMSangoMagic, SeCL_PlayerLogin::dwVersion, EncodeSeCL_PlayerLogin.
Referenced by EncodeSeCL_PlayerLogin.
int EncodeSeCL_PlayerLogin(DWord dwMSangoMagic, DWord dwVersion, bool bForceKick, const char *acAccount, const char *acPassword, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCL_PlayerLogin(const char *pkData, int iLen, SeCL_PlayerLogin &kStruct)
References SeCL_PlayerLogin::acAccount, SeCL_PlayerLogin::acPassword, SeNetStream::Attach, SeCL_PlayerLogin::bForceKick, SeCL_PlayerLogin::dwMSangoMagic, SeCL_PlayerLogin::dwVersion, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeCL_PlayerLogin_NEW(const SeCL_PlayerLogin_NEW &kData, char *pcBuf, int iMaxLen)
References SeCL_PlayerLogin_NEW::acAccount, SeCL_PlayerLogin_NEW::acLoginType, SeCL_PlayerLogin_NEW::acMobileInfo, SeCL_PlayerLogin_NEW::acToken, SeCL_PlayerLogin_NEW::bForceKick, SeCL_PlayerLogin_NEW::dwAccountID, SeCL_PlayerLogin_NEW::dwVersion, EncodeSeCL_PlayerLogin_NEW, SeCL_PlayerLogin_NEW::iPlatFlag.
Referenced by EncodeSeCL_PlayerLogin_NEW.
int EncodeSeCL_PlayerLogin_NEW(int iPlatFlag, DWord dwVersion, bool bForceKick, const char *acAccount, DWord dwAccountID, const char *acLoginType, const char *acToken, const char *acMobileInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCL_PlayerLogin_NEW(const char *pkData, int iLen, SeCL_PlayerLogin_NEW &kStruct)
References SeCL_PlayerLogin_NEW::acAccount, SeCL_PlayerLogin_NEW::acLoginType, SeCL_PlayerLogin_NEW::acMobileInfo, SeCL_PlayerLogin_NEW::acToken, SeNetStream::Attach, SeCL_PlayerLogin_NEW::bForceKick, SeCL_PlayerLogin_NEW::dwAccountID, SeCL_PlayerLogin_NEW::dwVersion, SeNetStream::GetCurPos, SeCL_PlayerLogin_NEW::iPlatFlag, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeCL_PlayerSteamLogin(const SeCL_PlayerSteamLogin &kData, char *pcBuf, int iMaxLen)
References SeCL_PlayerSteamLogin::acToken, SeCL_PlayerSteamLogin::dwLen, SeCL_PlayerSteamLogin::dwSecret, EncodeSeCL_PlayerSteamLogin.
Referenced by EncodeSeCL_PlayerSteamLogin.
int EncodeSeCL_PlayerSteamLogin(DWord dwLen, const char *acToken, DWord dwSecret, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCL_PlayerSteamLogin(const char *pkData, int iLen, SeCL_PlayerSteamLogin &kStruct)
References SeCL_PlayerSteamLogin::acToken, SeNetStream::Attach, SeCL_PlayerSteamLogin::dwLen, SeCL_PlayerSteamLogin::dwSecret, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.