SeWCSCStream.cpp
int EncodeSeWCSC_EncryptKey(const SeWCSC_EncryptKey &kData, char *pcBuf, int iMaxLen)
References SeWCSC_EncryptKey::abyEncryptKey, SeWCSC_EncryptKey::dwVersion, EncodeSeWCSC_EncryptKey.
Referenced by EncodeSeWCSC_EncryptKey.
int EncodeSeWCSC_EncryptKey(const char *abyEncryptKey, DWord dwVersion, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeWCSC_EncryptKey(const char *pkData, int iLen, SeWCSC_EncryptKey &kStruct)
References SeWCSC_EncryptKey::abyEncryptKey, SeNetStream::Attach, SeWCSC_EncryptKey::dwVersion, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeWCSC_ViewValidateRet(const SeWCSC_ViewValidateRet &kData, char *pcBuf, int iMaxLen)
References EncodeSeWCSC_ViewValidateRet, SeWCSC_ViewValidateRet::res.
Referenced by EncodeSeWCSC_ViewValidateRet.
int EncodeSeWCSC_ViewValidateRet(SeWCSValidateCode res, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeWCSC_ViewValidateRet(const char *pkData, int iLen, SeWCSC_ViewValidateRet &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeWCSC_ViewValidateRet::res.
int EncodeSeWCSC_ViewPack(const SeWCSC_ViewPack &kData, char *pcBuf, int iMaxLen)
References SeWCSC_ViewPack::acData, EncodeSeWCSC_ViewPack, SeWCSC_ViewPack::iOffset, SeWCSC_ViewPack::iSize.
Referenced by EncodeSeWCSC_ViewPack.
int EncodeSeWCSC_ViewPack(int iOffset, int iSize, const char *acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeWCSC_ViewPack(int iOffset, int iSize, std::vector< char > &acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeWCSC_ViewPack(const char *pkData, int iLen, SeWCSC_ViewPack &kStruct)
References SeWCSC_ViewPack::acData, SeNetStream::Attach, SeNetStream::GetCurPos, SeWCSC_ViewPack::iOffset, SeWCSC_ViewPack::iSize, SeNetStream::Read.
int EncodeSeWCSC_ViewPlayerInfo(const SeWCSC_ViewPlayerInfo &kData, char *pcBuf, int iMaxLen)
References SeWCSC_ViewPlayerInfo::akSeat, EncodeSeWCSC_ViewPlayerInfo, SeWCSC_ViewPlayerInfo::iNum.
Referenced by EncodeSeWCSC_ViewPlayerInfo.
int EncodeSeWCSC_ViewPlayerInfo(int iNum, const SePlayerInfoSeat *akSeat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePlayerInfoSeat, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeWCSC_ViewPlayerInfo(int iNum, std::vector< SePlayerInfoSeat > &akSeat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePlayerInfoSeat, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeWCSC_ViewPlayerInfo(const char *pkData, int iLen, SeWCSC_ViewPlayerInfo &kStruct)
References SeWCSC_ViewPlayerInfo::akSeat, SeNetStream::Attach, DecodeSePlayerInfoSeat, SeNetStream::GetCurPos, SeWCSC_ViewPlayerInfo::iNum, SeNetStream::Read, SeNetStream::SetCurPos.