SeCTStream.cpp
int EncodeSeCT_PlayerValidate(const SeCT_PlayerValidate &kData, char *pcBuf, int iMaxLen)
References SeCT_PlayerValidate::dwMaxMailID, SeCT_PlayerValidate::dwMSangoMagic, SeCT_PlayerValidate::dwPlayerID, SeCT_PlayerValidate::dwSessionId, SeCT_PlayerValidate::dwVersion, EncodeSeCT_PlayerValidate, SeCT_PlayerValidate::kMobileInfo.
Referenced by EncodeSeCT_PlayerValidate.
int EncodeSeCT_PlayerValidate(DWord dwMSangoMagic, DWord dwPlayerID, DWord dwSessionId, DWord dwVersion, DWord dwMaxMailID, const SeMobileInfo &kMobileInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeMobileInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeCT_PlayerValidate(const char *pkData, int iLen, SeCT_PlayerValidate &kStruct)
References SeNetStream::Attach, DecodeSeMobileInfo, SeCT_PlayerValidate::dwMaxMailID, SeCT_PlayerValidate::dwMSangoMagic, SeCT_PlayerValidate::dwPlayerID, SeCT_PlayerValidate::dwSessionId, SeCT_PlayerValidate::dwVersion, SeNetStream::GetCurPos, SeCT_PlayerValidate::kMobileInfo, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeCT_QueryName(const SeCT_QueryName &kData, char *pcBuf, int iMaxLen)
References SeCT_QueryName::acName, EncodeSeCT_QueryName.
Referenced by EncodeSeCT_QueryName.
int EncodeSeCT_QueryName(const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::WriteString.
int DecodeSeCT_QueryName(const char *pkData, int iLen, SeCT_QueryName &kStruct)
References SeCT_QueryName::acName, SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::ReadString.
int EncodeSeCT_CreateChar(const SeCT_CreateChar &kData, char *pcBuf, int iMaxLen)
References SeCT_CreateChar::acName, SeCT_CreateChar::dwCardID, EncodeSeCT_CreateChar, SeCT_CreateChar::iSex.
Referenced by EncodeSeCT_CreateChar.
int EncodeSeCT_CreateChar(const char *acName, int iSex, DWord dwCardID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCT_CreateChar(const char *pkData, int iLen, SeCT_CreateChar &kStruct)
References SeCT_CreateChar::acName, SeNetStream::Attach, SeCT_CreateChar::dwCardID, SeNetStream::GetCurPos, SeCT_CreateChar::iSex, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeCT_LeaveTown(const SeCT_LeaveTown &kData, char *pcBuf, int iMaxLen)
References SeCT_LeaveTown::bExitGame, EncodeSeCT_LeaveTown.
Referenced by EncodeSeCT_LeaveTown.
int EncodeSeCT_LeaveTown(bool bExitGame, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_LeaveTown(const char *pkData, int iLen, SeCT_LeaveTown &kStruct)
References SeNetStream::Attach, SeCT_LeaveTown::bExitGame, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_PlayerGoDirect(const SeCT_PlayerGoDirect &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_PlayerGoDirect, SeCT_PlayerGoDirect::fDirect.
Referenced by EncodeSeCT_PlayerGoDirect.
int EncodeSeCT_PlayerGoDirect(float fDirect, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_PlayerGoDirect(const char *pkData, int iLen, SeCT_PlayerGoDirect &kStruct)
References SeNetStream::Attach, SeCT_PlayerGoDirect::fDirect, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_RaceEndGuanka(const SeCT_RaceEndGuanka &kData, char *pcBuf, int iMaxLen)
References SeCT_RaceEndGuanka::akPlayerInfo, SeCT_RaceEndGuanka::bValid, SeCT_RaceEndGuanka::dwRaceTime, EncodeSeCT_RaceEndGuanka, SeCT_RaceEndGuanka::iMapID, SeCT_RaceEndGuanka::iNums, SeCT_RaceEndGuanka::iType.
Referenced by EncodeSeCT_RaceEndGuanka.
int EncodeSeCT_RaceEndGuanka(int iType, DWord dwRaceTime, int iMapID, bool bValid, int iNums, const SeGuanqiaSendInfo *akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeGuanqiaSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeCT_RaceEndGuanka(int iType, DWord dwRaceTime, int iMapID, bool bValid, int iNums, std::vector< SeGuanqiaSendInfo > &akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeGuanqiaSendInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeCT_RaceEndGuanka(const char *pkData, int iLen, SeCT_RaceEndGuanka &kStruct)
References SeCT_RaceEndGuanka::akPlayerInfo, SeNetStream::Attach, SeCT_RaceEndGuanka::bValid, DecodeSeGuanqiaSendInfo, SeCT_RaceEndGuanka::dwRaceTime, SeNetStream::GetCurPos, SeCT_RaceEndGuanka::iMapID, SeCT_RaceEndGuanka::iNums, SeCT_RaceEndGuanka::iType, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeCT_ViewBegin(const SeCT_ViewBegin &kData, char *pcBuf, int iMaxLen)
References SeCT_ViewBegin::dwDstPlayerID, SeCT_ViewBegin::dwRoomSession, EncodeSeCT_ViewBegin.
Referenced by EncodeSeCT_ViewBegin.
int EncodeSeCT_ViewBegin(DWord dwRoomSession, DWord dwDstPlayerID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ViewBegin(const char *pkData, int iLen, SeCT_ViewBegin &kStruct)
References SeNetStream::Attach, SeCT_ViewBegin::dwDstPlayerID, SeCT_ViewBegin::dwRoomSession, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_QueryRaceRoomList(const SeCT_QueryRaceRoomList &kData, char *pcBuf, int iMaxLen)
References SeCT_QueryRaceRoomList::dwMapID, SeCT_QueryRaceRoomList::dwRoomSession, EncodeSeCT_QueryRaceRoomList, SeCT_QueryRaceRoomList::iPage.
Referenced by EncodeSeCT_QueryRaceRoomList.
int EncodeSeCT_QueryRaceRoomList(DWord dwRoomSession, int iPage, DWord dwMapID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_QueryRaceRoomList(const char *pkData, int iLen, SeCT_QueryRaceRoomList &kStruct)
References SeNetStream::Attach, SeCT_QueryRaceRoomList::dwMapID, SeCT_QueryRaceRoomList::dwRoomSession, SeNetStream::GetCurPos, SeCT_QueryRaceRoomList::iPage, SeNetStream::Read.
int EncodeSeCT_ItemExchange(const SeCT_ItemExchange &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ItemExchange, SeCT_ItemExchange::iTypeID.
Referenced by EncodeSeCT_ItemExchange.
int EncodeSeCT_ItemExchange(int iTypeID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ItemExchange(const char *pkData, int iLen, SeCT_ItemExchange &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_ItemExchange::iTypeID, SeNetStream::Read.
int EncodeSeCT_ReconQuery(const SeCT_ReconQuery &kData, char *pcBuf, int iMaxLen)
References SeCT_ReconQuery::dwFrame, SeCT_ReconQuery::dwRoomID, EncodeSeCT_ReconQuery, SeCT_ReconQuery::iOffset, SeCT_ReconQuery::iSeat.
Referenced by EncodeSeCT_ReconQuery.
int EncodeSeCT_ReconQuery(DWord dwRoomID, int iSeat, int iOffset, DWord dwFrame, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ReconQuery(const char *pkData, int iLen, SeCT_ReconQuery &kStruct)
References SeNetStream::Attach, SeCT_ReconQuery::dwFrame, SeCT_ReconQuery::dwRoomID, SeNetStream::GetCurPos, SeCT_ReconQuery::iOffset, SeCT_ReconQuery::iSeat, SeNetStream::Read.
int EncodeSeCT_DelayCheck(const SeCT_DelayCheck &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_DelayCheck.
Referenced by EncodeSeCT_DelayCheck.
int EncodeSeCT_DelayCheck(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_DelayCheck(const char *pkData, int iLen, SeCT_DelayCheck &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_TaskQueryList(const SeCT_TaskQueryList &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_TaskQueryList.
Referenced by EncodeSeCT_TaskQueryList.
int EncodeSeCT_TaskQueryList(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_TaskQueryList(const char *pkData, int iLen, SeCT_TaskQueryList &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_TaskResel(const SeCT_TaskResel &kData, char *pcBuf, int iMaxLen)
References SeCT_TaskResel::dwTaskID, EncodeSeCT_TaskResel.
Referenced by EncodeSeCT_TaskResel.
int EncodeSeCT_TaskResel(DWord dwTaskID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_TaskResel(const char *pkData, int iLen, SeCT_TaskResel &kStruct)
References SeNetStream::Attach, SeCT_TaskResel::dwTaskID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_GetTaskReward(const SeCT_GetTaskReward &kData, char *pcBuf, int iMaxLen)
References SeCT_GetTaskReward::dwTaskID, EncodeSeCT_GetTaskReward.
Referenced by EncodeSeCT_GetTaskReward.
int EncodeSeCT_GetTaskReward(DWord dwTaskID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_GetTaskReward(const char *pkData, int iLen, SeCT_GetTaskReward &kStruct)
References SeNetStream::Attach, SeCT_GetTaskReward::dwTaskID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_QueryRaceBetInfo(const SeCT_QueryRaceBetInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_QueryRaceBetInfo.
Referenced by EncodeSeCT_QueryRaceBetInfo.
int EncodeSeCT_QueryRaceBetInfo(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_QueryRaceBetInfo(const char *pkData, int iLen, SeCT_QueryRaceBetInfo &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_DelReconInfo(const SeCT_DelReconInfo &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_DelReconInfo.
Referenced by EncodeSeCT_DelReconInfo.
int EncodeSeCT_DelReconInfo(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_DelReconInfo(const char *pkData, int iLen, SeCT_DelReconInfo &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_MailOpr(const SeCT_MailOpr &kData, char *pcBuf, int iMaxLen)
References SeCT_MailOpr::dwMailID, EncodeSeCT_MailOpr, SeCT_MailOpr::iType.
Referenced by EncodeSeCT_MailOpr.
int EncodeSeCT_MailOpr(int iType, DWord dwMailID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_MailOpr(const char *pkData, int iLen, SeCT_MailOpr &kStruct)
References SeNetStream::Attach, SeCT_MailOpr::dwMailID, SeNetStream::GetCurPos, SeCT_MailOpr::iType, SeNetStream::Read.
int EncodeSeCT_PlayerRename(const SeCT_PlayerRename &kData, char *pcBuf, int iMaxLen)
References SeCT_PlayerRename::acName, EncodeSeCT_PlayerRename.
Referenced by EncodeSeCT_PlayerRename.
int EncodeSeCT_PlayerRename(const char *acName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::WriteString.
int DecodeSeCT_PlayerRename(const char *pkData, int iLen, SeCT_PlayerRename &kStruct)
References SeCT_PlayerRename::acName, SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::ReadString.
int EncodeSeCT_HeartBeat(const SeCT_HeartBeat &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_HeartBeat.
Referenced by EncodeSeCT_HeartBeat.
int EncodeSeCT_HeartBeat(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_HeartBeat(const char *pkData, int iLen, SeCT_HeartBeat &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_MapTaskOpr(const SeCT_MapTaskOpr &kData, char *pcBuf, int iMaxLen)
References SeCT_MapTaskOpr::dwParam, EncodeSeCT_MapTaskOpr, SeCT_MapTaskOpr::iOprType.
Referenced by EncodeSeCT_MapTaskOpr.
int EncodeSeCT_MapTaskOpr(int iOprType, DWord dwParam, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_MapTaskOpr(const char *pkData, int iLen, SeCT_MapTaskOpr &kStruct)
References SeNetStream::Attach, SeCT_MapTaskOpr::dwParam, SeNetStream::GetCurPos, SeCT_MapTaskOpr::iOprType, SeNetStream::Read.
int EncodeSeCT_QueryNearestRaceInfo(const SeCT_QueryNearestRaceInfo &kData, char *pcBuf, int iMaxLen)
References SeCT_QueryNearestRaceInfo::dwMapID, SeCT_QueryNearestRaceInfo::dwQueriedID, EncodeSeCT_QueryNearestRaceInfo.
Referenced by EncodeSeCT_QueryNearestRaceInfo.
int EncodeSeCT_QueryNearestRaceInfo(DWord dwMapID, DWord dwQueriedID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_QueryNearestRaceInfo(const char *pkData, int iLen, SeCT_QueryNearestRaceInfo &kStruct)
References SeNetStream::Attach, SeCT_QueryNearestRaceInfo::dwMapID, SeCT_QueryNearestRaceInfo::dwQueriedID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_ReqIncompleteRaceList(const SeCT_ReqIncompleteRaceList &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ReqIncompleteRaceList.
Referenced by EncodeSeCT_ReqIncompleteRaceList.
int EncodeSeCT_ReqIncompleteRaceList(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_ReqIncompleteRaceList(const char *pkData, int iLen, SeCT_ReqIncompleteRaceList &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_CloseIncompleteRaceList(const SeCT_CloseIncompleteRaceList &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_CloseIncompleteRaceList.
Referenced by EncodeSeCT_CloseIncompleteRaceList.
int EncodeSeCT_CloseIncompleteRaceList(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_CloseIncompleteRaceList(const char *pkData, int iLen, SeCT_CloseIncompleteRaceList &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_ReqIncompleteRaceKDA(const SeCT_ReqIncompleteRaceKDA &kData, char *pcBuf, int iMaxLen)
References SeCT_ReqIncompleteRaceKDA::dwRoomSession, EncodeSeCT_ReqIncompleteRaceKDA.
Referenced by EncodeSeCT_ReqIncompleteRaceKDA.
int EncodeSeCT_ReqIncompleteRaceKDA(DWord dwRoomSession, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ReqIncompleteRaceKDA(const char *pkData, int iLen, SeCT_ReqIncompleteRaceKDA &kStruct)
References SeNetStream::Attach, SeCT_ReqIncompleteRaceKDA::dwRoomSession, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_CreateRoom(const SeCT_CreateRoom &kData, char *pcBuf, int iMaxLen)
References SeCT_CreateRoom::bPlayBoss, SeCT_CreateRoom::bUseRobot, SeCT_CreateRoom::dwCamp, SeCT_CreateRoom::dwGameMode, SeCT_CreateRoom::dwMapID, EncodeSeCT_CreateRoom, SeCT_CreateRoom::iDifficulty, SeCT_CreateRoom::strPass, SeCT_CreateRoom::strRoomName.
Referenced by EncodeSeCT_CreateRoom.
int EncodeSeCT_CreateRoom(DWord dwMapID, DWord dwCamp, int iDifficulty, bool bPlayBoss, bool bUseRobot, DWord dwGameMode, const char *strRoomName, const char *strPass, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCT_CreateRoom(const char *pkData, int iLen, SeCT_CreateRoom &kStruct)
References SeNetStream::Attach, SeCT_CreateRoom::bPlayBoss, SeCT_CreateRoom::bUseRobot, SeCT_CreateRoom::dwCamp, SeCT_CreateRoom::dwGameMode, SeCT_CreateRoom::dwMapID, SeNetStream::GetCurPos, SeCT_CreateRoom::iDifficulty, SeNetStream::Read, SeNetStream::ReadString, SeCT_CreateRoom::strPass, SeCT_CreateRoom::strRoomName.
int EncodeSeCT_QueryRoomList(const SeCT_QueryRoomList &kData, char *pcBuf, int iMaxLen)
References SeCT_QueryRoomList::dwMapID, EncodeSeCT_QueryRoomList, SeCT_QueryRoomList::iCurPage.
Referenced by EncodeSeCT_QueryRoomList.
int EncodeSeCT_QueryRoomList(int iCurPage, DWord dwMapID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_QueryRoomList(const char *pkData, int iLen, SeCT_QueryRoomList &kStruct)
References SeNetStream::Attach, SeCT_QueryRoomList::dwMapID, SeNetStream::GetCurPos, SeCT_QueryRoomList::iCurPage, SeNetStream::Read.
int EncodeSeCT_RoomJoin(const SeCT_RoomJoin &kData, char *pcBuf, int iMaxLen)
References SeCT_RoomJoin::dwCamp, SeCT_RoomJoin::dwDstRoom, EncodeSeCT_RoomJoin, SeCT_RoomJoin::iseat, SeCT_RoomJoin::strPass.
Referenced by EncodeSeCT_RoomJoin.
int EncodeSeCT_RoomJoin(DWord dwDstRoom, DWord dwCamp, int iseat, const char *strPass, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCT_RoomJoin(const char *pkData, int iLen, SeCT_RoomJoin &kStruct)
References SeNetStream::Attach, SeCT_RoomJoin::dwCamp, SeCT_RoomJoin::dwDstRoom, SeNetStream::GetCurPos, SeCT_RoomJoin::iseat, SeNetStream::Read, SeNetStream::ReadString, SeCT_RoomJoin::strPass.
int EncodeSeCT_RoomLeave(const SeCT_RoomLeave &kData, char *pcBuf, int iMaxLen)
References SeCT_RoomLeave::dwDstRoom, SeCT_RoomLeave::dwPlayerID, EncodeSeCT_RoomLeave.
Referenced by EncodeSeCT_RoomLeave.
int EncodeSeCT_RoomLeave(DWord dwDstRoom, DWord dwPlayerID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_RoomLeave(const char *pkData, int iLen, SeCT_RoomLeave &kStruct)
References SeNetStream::Attach, SeCT_RoomLeave::dwDstRoom, SeCT_RoomLeave::dwPlayerID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_RoomSwitchSeat(const SeCT_RoomSwitchSeat &kData, char *pcBuf, int iMaxLen)
References SeCT_RoomSwitchSeat::dwCamp, SeCT_RoomSwitchSeat::dwDstRoom, EncodeSeCT_RoomSwitchSeat, SeCT_RoomSwitchSeat::iseat.
Referenced by EncodeSeCT_RoomSwitchSeat.
int EncodeSeCT_RoomSwitchSeat(DWord dwDstRoom, DWord dwCamp, int iseat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_RoomSwitchSeat(const char *pkData, int iLen, SeCT_RoomSwitchSeat &kStruct)
References SeNetStream::Attach, SeCT_RoomSwitchSeat::dwCamp, SeCT_RoomSwitchSeat::dwDstRoom, SeNetStream::GetCurPos, SeCT_RoomSwitchSeat::iseat, SeNetStream::Read.
int EncodeSeCT_RoomStart(const SeCT_RoomStart &kData, char *pcBuf, int iMaxLen)
References SeCT_RoomStart::dwRoomID, EncodeSeCT_RoomStart.
Referenced by EncodeSeCT_RoomStart.
int EncodeSeCT_RoomStart(DWord dwRoomID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_RoomStart(const char *pkData, int iLen, SeCT_RoomStart &kStruct)
References SeNetStream::Attach, SeCT_RoomStart::dwRoomID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_RoomKickSomeone(const SeCT_RoomKickSomeone &kData, char *pcBuf, int iMaxLen)
References SeCT_RoomKickSomeone::dwKickedPlayerID, SeCT_RoomKickSomeone::dwRoomID, EncodeSeCT_RoomKickSomeone, SeCT_RoomKickSomeone::iseat.
Referenced by EncodeSeCT_RoomKickSomeone.
int EncodeSeCT_RoomKickSomeone(DWord dwRoomID, DWord dwKickedPlayerID, int iseat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_RoomKickSomeone(const char *pkData, int iLen, SeCT_RoomKickSomeone &kStruct)
References SeNetStream::Attach, SeCT_RoomKickSomeone::dwKickedPlayerID, SeCT_RoomKickSomeone::dwRoomID, SeNetStream::GetCurPos, SeCT_RoomKickSomeone::iseat, SeNetStream::Read.
int EncodeSeCT_RoomInvite(const SeCT_RoomInvite &kData, char *pcBuf, int iMaxLen)
References SeCT_RoomInvite::dwInviteeID, SeCT_RoomInvite::dwRoomID, EncodeSeCT_RoomInvite.
Referenced by EncodeSeCT_RoomInvite.
int EncodeSeCT_RoomInvite(DWord dwInviteeID, DWord dwRoomID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_RoomInvite(const char *pkData, int iLen, SeCT_RoomInvite &kStruct)
References SeNetStream::Attach, SeCT_RoomInvite::dwInviteeID, SeCT_RoomInvite::dwRoomID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_RoomInviteRsp(const SeCT_RoomInviteRsp &kData, char *pcBuf, int iMaxLen)
References SeCT_RoomInviteRsp::dwInvitorID, SeCT_RoomInviteRsp::dwRoomID, EncodeSeCT_RoomInviteRsp, SeCT_RoomInviteRsp::option.
Referenced by EncodeSeCT_RoomInviteRsp.
int EncodeSeCT_RoomInviteRsp(DWord dwRoomID, DWord dwInvitorID, bool option, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_RoomInviteRsp(const char *pkData, int iLen, SeCT_RoomInviteRsp &kStruct)
References SeNetStream::Attach, SeCT_RoomInviteRsp::dwInvitorID, SeCT_RoomInviteRsp::dwRoomID, SeNetStream::GetCurPos, SeCT_RoomInviteRsp::option, SeNetStream::Read.
int EncodeSeCT_GetRaceHistory(const SeCT_GetRaceHistory &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_GetRaceHistory, SeCT_GetRaceHistory::iPage, SeCT_GetRaceHistory::iType.
Referenced by EncodeSeCT_GetRaceHistory.
int EncodeSeCT_GetRaceHistory(int iType, int iPage, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_GetRaceHistory(const char *pkData, int iLen, SeCT_GetRaceHistory &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_GetRaceHistory::iPage, SeCT_GetRaceHistory::iType, SeNetStream::Read.
int EncodeSeCT_ReqAchievement(const SeCT_ReqAchievement &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ReqAchievement, SeCT_ReqAchievement::iPage.
Referenced by EncodeSeCT_ReqAchievement.
int EncodeSeCT_ReqAchievement(int iPage, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ReqAchievement(const char *pkData, int iLen, SeCT_ReqAchievement &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_ReqAchievement::iPage, SeNetStream::Read.
int EncodeSeCT_ReqView(const SeCT_ReqView &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ReqView, SeCT_ReqView::rID.
Referenced by EncodeSeCT_ReqView.
int EncodeSeCT_ReqView(const Byte *rID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeCT_ReqView(std::vector< Byte > &rID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ReqView(const char *pkData, int iLen, SeCT_ReqView &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeCT_ReqView::rID.
int EncodeSeCT_ReqAchievementCounts(const SeCT_ReqAchievementCounts &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ReqAchievementCounts.
Referenced by EncodeSeCT_ReqAchievementCounts.
int EncodeSeCT_ReqAchievementCounts(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_ReqAchievementCounts(const char *pkData, int iLen, SeCT_ReqAchievementCounts &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_ReqViewList(const SeCT_ReqViewList &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ReqViewList, SeCT_ReqViewList::iPage.
Referenced by EncodeSeCT_ReqViewList.
int EncodeSeCT_ReqViewList(int iPage, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ReqViewList(const char *pkData, int iLen, SeCT_ReqViewList &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_ReqViewList::iPage, SeNetStream::Read.
int EncodeSeCT_ReqItemStrenth(const SeCT_ReqItemStrenth &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ReqItemStrenth, SeCT_ReqItemStrenth::iNum, SeCT_ReqItemStrenth::SrcPosArray, SeCT_ReqItemStrenth::wPos.
Referenced by EncodeSeCT_ReqItemStrenth.
int EncodeSeCT_ReqItemStrenth(Word wPos, int iNum, const Word *SrcPosArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeCT_ReqItemStrenth(Word wPos, int iNum, std::vector< Word > &SrcPosArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ReqItemStrenth(const char *pkData, int iLen, SeCT_ReqItemStrenth &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_ReqItemStrenth::iNum, SeNetStream::Read, SeCT_ReqItemStrenth::SrcPosArray, SeCT_ReqItemStrenth::wPos.
int EncodeSeCT_RaceDetailInfoReq(const SeCT_RaceDetailInfoReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_RaceDetailInfoReq, SeCT_RaceDetailInfoReq::page_counts, SeCT_RaceDetailInfoReq::page_number.
Referenced by EncodeSeCT_RaceDetailInfoReq.
int EncodeSeCT_RaceDetailInfoReq(int page_number, int page_counts, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_RaceDetailInfoReq(const char *pkData, int iLen, SeCT_RaceDetailInfoReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_RaceDetailInfoReq::page_counts, SeCT_RaceDetailInfoReq::page_number, SeNetStream::Read.
int EncodeSeCT_ReqItemCiTiaoChange(const SeCT_ReqItemCiTiaoChange &kData, char *pcBuf, int iMaxLen)
References SeCT_ReqItemCiTiaoChange::BolLock, EncodeSeCT_ReqItemCiTiaoChange, SeCT_ReqItemCiTiaoChange::iIndex, SeCT_ReqItemCiTiaoChange::iNum, SeCT_ReqItemCiTiaoChange::SrcPosArray, SeCT_ReqItemCiTiaoChange::wPos.
Referenced by EncodeSeCT_ReqItemCiTiaoChange.
int EncodeSeCT_ReqItemCiTiaoChange(Word wPos, int iIndex, Byte BolLock, int iNum, const Word *SrcPosArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeCT_ReqItemCiTiaoChange(Word wPos, int iIndex, Byte BolLock, int iNum, std::vector< Word > &SrcPosArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ReqItemCiTiaoChange(const char *pkData, int iLen, SeCT_ReqItemCiTiaoChange &kStruct)
References SeNetStream::Attach, SeCT_ReqItemCiTiaoChange::BolLock, SeNetStream::GetCurPos, SeCT_ReqItemCiTiaoChange::iIndex, SeCT_ReqItemCiTiaoChange::iNum, SeNetStream::Read, SeCT_ReqItemCiTiaoChange::SrcPosArray, SeCT_ReqItemCiTiaoChange::wPos.
int EncodeSeCT_ReqItemDepart(const SeCT_ReqItemDepart &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ReqItemDepart, SeCT_ReqItemDepart::wPos.
Referenced by EncodeSeCT_ReqItemDepart.
int EncodeSeCT_ReqItemDepart(Word wPos, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ReqItemDepart(const char *pkData, int iLen, SeCT_ReqItemDepart &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeCT_ReqItemDepart::wPos.
int EncodeSeCT_GMAddItem(const SeCT_GMAddItem &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_GMAddItem, SeCT_GMAddItem::ItemID, SeCT_GMAddItem::Level, SeCT_GMAddItem::Num.
Referenced by EncodeSeCT_GMAddItem.
int EncodeSeCT_GMAddItem(DWord ItemID, int Num, int Level, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_GMAddItem(const char *pkData, int iLen, SeCT_GMAddItem &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_GMAddItem::ItemID, SeCT_GMAddItem::Level, SeCT_GMAddItem::Num, SeNetStream::Read.
int EncodeSeCT_DelelteItem(const SeCT_DelelteItem &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_DelelteItem, SeCT_DelelteItem::wPos.
Referenced by EncodeSeCT_DelelteItem.
int EncodeSeCT_DelelteItem(Word wPos, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_DelelteItem(const char *pkData, int iLen, SeCT_DelelteItem &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeCT_DelelteItem::wPos.
int EncodeSeCT_PutOnEquip(const SeCT_PutOnEquip &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_PutOnEquip, SeCT_PutOnEquip::PutPos, SeCT_PutOnEquip::wPos.
Referenced by EncodeSeCT_PutOnEquip.
int EncodeSeCT_PutOnEquip(Word wPos, Word PutPos, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_PutOnEquip(const char *pkData, int iLen, SeCT_PutOnEquip &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_PutOnEquip::PutPos, SeNetStream::Read, SeCT_PutOnEquip::wPos.
int EncodeSeCT_TakeOffEquip(const SeCT_TakeOffEquip &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_TakeOffEquip, SeCT_TakeOffEquip::wPos.
Referenced by EncodeSeCT_TakeOffEquip.
int EncodeSeCT_TakeOffEquip(Word wPos, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_TakeOffEquip(const char *pkData, int iLen, SeCT_TakeOffEquip &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeCT_TakeOffEquip::wPos.
int EncodeSeCT_OpenRandBox(const SeCT_OpenRandBox &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_OpenRandBox, SeCT_OpenRandBox::wPos.
Referenced by EncodeSeCT_OpenRandBox.
int EncodeSeCT_OpenRandBox(Word wPos, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_OpenRandBox(const char *pkData, int iLen, SeCT_OpenRandBox &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeCT_OpenRandBox::wPos.
int EncodeSeCT_ClearItemNewFlag(const SeCT_ClearItemNewFlag &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ClearItemNewFlag, SeCT_ClearItemNewFlag::iNum, SeCT_ClearItemNewFlag::PosArray.
Referenced by EncodeSeCT_ClearItemNewFlag.
int EncodeSeCT_ClearItemNewFlag(int iNum, const Word *PosArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeCT_ClearItemNewFlag(int iNum, std::vector< Word > &PosArray, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_ClearItemNewFlag(const char *pkData, int iLen, SeCT_ClearItemNewFlag &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_ClearItemNewFlag::iNum, SeCT_ClearItemNewFlag::PosArray, SeNetStream::Read.
int EncodeSeCT_BuyShopItem(const SeCT_BuyShopItem &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_BuyShopItem, SeCT_BuyShopItem::Num, SeCT_BuyShopItem::ShopID, SeCT_BuyShopItem::types.
Referenced by EncodeSeCT_BuyShopItem.
int EncodeSeCT_BuyShopItem(int types, int ShopID, int Num, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_BuyShopItem(const char *pkData, int iLen, SeCT_BuyShopItem &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_BuyShopItem::Num, SeNetStream::Read, SeCT_BuyShopItem::ShopID, SeCT_BuyShopItem::types.
int EncodeSeCT_ShopItemGM(const SeCT_ShopItemGM &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_ShopItemGM, SeCT_ShopItemGM::GmItems, SeCT_ShopItemGM::iNum.
Referenced by EncodeSeCT_ShopItemGM.
int EncodeSeCT_ShopItemGM(int iNum, const ShopItem *GmItems, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeShopItem, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeCT_ShopItemGM(int iNum, std::vector< ShopItem > &GmItems, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeShopItem, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeCT_ShopItemGM(const char *pkData, int iLen, SeCT_ShopItemGM &kStruct)
References SeNetStream::Attach, DecodeShopItem, SeNetStream::GetCurPos, SeCT_ShopItemGM::GmItems, SeCT_ShopItemGM::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeCT_GetItemGM(const SeCT_GetItemGM &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_GetItemGM, SeCT_GetItemGM::ShopID.
Referenced by EncodeSeCT_GetItemGM.
int EncodeSeCT_GetItemGM(DWord ShopID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_GetItemGM(const char *pkData, int iLen, SeCT_GetItemGM &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeCT_GetItemGM::ShopID.
int EncodeSeCT_NexusFriendDetailInfoReq(const SeCT_NexusFriendDetailInfoReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_NexusFriendDetailInfoReq, SeCT_NexusFriendDetailInfoReq::page_counts, SeCT_NexusFriendDetailInfoReq::page_number.
Referenced by EncodeSeCT_NexusFriendDetailInfoReq.
int EncodeSeCT_NexusFriendDetailInfoReq(int page_number, int page_counts, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_NexusFriendDetailInfoReq(const char *pkData, int iLen, SeCT_NexusFriendDetailInfoReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_NexusFriendDetailInfoReq::page_counts, SeCT_NexusFriendDetailInfoReq::page_number, SeNetStream::Read.
int EncodeSeCT_NexusUserActionReq(const SeCT_NexusUserActionReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_NexusUserActionReq, SeCT_NexusUserActionReq::nexus_user_actions.
Referenced by EncodeSeCT_NexusUserActionReq.
int EncodeSeCT_NexusUserActionReq(const SeNexusUserInfo &nexus_user_actions, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusUserInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeCT_NexusUserActionReq(const char *pkData, int iLen, SeCT_NexusUserActionReq &kStruct)
References SeNetStream::Attach, DecodeSeNexusUserInfo, SeNetStream::GetCurPos, SeCT_NexusUserActionReq::nexus_user_actions, SeNetStream::SetCurPos.
int EncodeSeCT_NexusUserPromotionReq(const SeCT_NexusUserPromotionReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_NexusUserPromotionReq, SeCT_NexusUserPromotionReq::nexus_user_promotion.
Referenced by EncodeSeCT_NexusUserPromotionReq.
int EncodeSeCT_NexusUserPromotionReq(const SeNexusUserPromotionInfo &nexus_user_promotion, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeNexusUserPromotionInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeCT_NexusUserPromotionReq(const char *pkData, int iLen, SeCT_NexusUserPromotionReq &kStruct)
References SeNetStream::Attach, DecodeSeNexusUserPromotionInfo, SeNetStream::GetCurPos, SeCT_NexusUserPromotionReq::nexus_user_promotion, SeNetStream::SetCurPos.
int EncodeSeCT_SearchUserArchivesInfoReq(const SeCT_SearchUserArchivesInfoReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_SearchUserArchivesInfoReq, SeCT_SearchUserArchivesInfoReq::username.
Referenced by EncodeSeCT_SearchUserArchivesInfoReq.
int EncodeSeCT_SearchUserArchivesInfoReq(const SeUserArchivesNameInfo &username, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeUserArchivesNameInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos.
int DecodeSeCT_SearchUserArchivesInfoReq(const char *pkData, int iLen, SeCT_SearchUserArchivesInfoReq &kStruct)
References SeNetStream::Attach, DecodeSeUserArchivesNameInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeCT_SearchUserArchivesInfoReq::username.
int EncodeSeCT_SearchUserArchivesDetailInfoReq(const SeCT_SearchUserArchivesDetailInfoReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_SearchUserArchivesDetailInfoReq, SeCT_SearchUserArchivesDetailInfoReq::userid.
Referenced by EncodeSeCT_SearchUserArchivesDetailInfoReq.
int EncodeSeCT_SearchUserArchivesDetailInfoReq(DWord userid, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_SearchUserArchivesDetailInfoReq(const char *pkData, int iLen, SeCT_SearchUserArchivesDetailInfoReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Read, SeCT_SearchUserArchivesDetailInfoReq::userid.
int EncodeSeCT_NexusUserPromotionDetailInfoReq(const SeCT_NexusUserPromotionDetailInfoReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_NexusUserPromotionDetailInfoReq.
Referenced by EncodeSeCT_NexusUserPromotionDetailInfoReq.
int EncodeSeCT_NexusUserPromotionDetailInfoReq(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_NexusUserPromotionDetailInfoReq(const char *pkData, int iLen, SeCT_NexusUserPromotionDetailInfoReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_PlayerMatchReq(const SeCT_PlayerMatchReq &kData, char *pcBuf, int iMaxLen)
References SeCT_PlayerMatchReq::bySeats, EncodeSeCT_PlayerMatchReq, SeCT_PlayerMatchReq::MapID.
Referenced by EncodeSeCT_PlayerMatchReq.
int EncodeSeCT_PlayerMatchReq(DWord MapID, Byte bySeats, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_PlayerMatchReq(const char *pkData, int iLen, SeCT_PlayerMatchReq &kStruct)
References SeNetStream::Attach, SeCT_PlayerMatchReq::bySeats, SeNetStream::GetCurPos, SeCT_PlayerMatchReq::MapID, SeNetStream::Read.
int EncodeSeCT_PlayerMatchCancel(const SeCT_PlayerMatchCancel &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_PlayerMatchCancel.
Referenced by EncodeSeCT_PlayerMatchCancel.
int EncodeSeCT_PlayerMatchCancel(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_PlayerMatchCancel(const char *pkData, int iLen, SeCT_PlayerMatchCancel &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_MatchConfirm(const SeCT_MatchConfirm &kData, char *pcBuf, int iMaxLen)
References SeCT_MatchConfirm::BoolConfirm, EncodeSeCT_MatchConfirm, SeCT_MatchConfirm::WaitID.
Referenced by EncodeSeCT_MatchConfirm.
int EncodeSeCT_MatchConfirm(DWord WaitID, bool BoolConfirm, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_MatchConfirm(const char *pkData, int iLen, SeCT_MatchConfirm &kStruct)
References SeNetStream::Attach, SeCT_MatchConfirm::BoolConfirm, SeNetStream::GetCurPos, SeNetStream::Read, SeCT_MatchConfirm::WaitID.
int EncodeSeCT_SeUserRaceArenaDetailInfoReq(const SeCT_SeUserRaceArenaDetailInfoReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_SeUserRaceArenaDetailInfoReq.
Referenced by EncodeSeCT_SeUserRaceArenaDetailInfoReq.
int EncodeSeCT_SeUserRaceArenaDetailInfoReq(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_SeUserRaceArenaDetailInfoReq(const char *pkData, int iLen, SeCT_SeUserRaceArenaDetailInfoReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_UserInviteReq(const SeCT_UserInviteReq &kData, char *pcBuf, int iMaxLen)
References SeCT_UserInviteReq::acGuestName, SeCT_UserInviteReq::acUserName, SeCT_UserInviteReq::dwGuestID, EncodeSeCT_UserInviteReq.
Referenced by EncodeSeCT_UserInviteReq.
int EncodeSeCT_UserInviteReq(const char *acUserName, DWord dwGuestID, const char *acGuestName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeCT_UserInviteReq(const char *pkData, int iLen, SeCT_UserInviteReq &kStruct)
References SeCT_UserInviteReq::acGuestName, SeCT_UserInviteReq::acUserName, SeNetStream::Attach, SeCT_UserInviteReq::dwGuestID, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeCT_UserConfirmInviteReq(const SeCT_UserConfirmInviteReq &kData, char *pcBuf, int iMaxLen)
References SeCT_UserConfirmInviteReq::dwTeamID, EncodeSeCT_UserConfirmInviteReq.
Referenced by EncodeSeCT_UserConfirmInviteReq.
int EncodeSeCT_UserConfirmInviteReq(DWord dwTeamID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_UserConfirmInviteReq(const char *pkData, int iLen, SeCT_UserConfirmInviteReq &kStruct)
References SeNetStream::Attach, SeCT_UserConfirmInviteReq::dwTeamID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_UserRefuseInviteReq(const SeCT_UserRefuseInviteReq &kData, char *pcBuf, int iMaxLen)
References SeCT_UserRefuseInviteReq::dwTeamID, EncodeSeCT_UserRefuseInviteReq.
Referenced by EncodeSeCT_UserRefuseInviteReq.
int EncodeSeCT_UserRefuseInviteReq(DWord dwTeamID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_UserRefuseInviteReq(const char *pkData, int iLen, SeCT_UserRefuseInviteReq &kStruct)
References SeNetStream::Attach, SeCT_UserRefuseInviteReq::dwTeamID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_UserLeaveTeamReq(const SeCT_UserLeaveTeamReq &kData, char *pcBuf, int iMaxLen)
References SeCT_UserLeaveTeamReq::dwTeamID, EncodeSeCT_UserLeaveTeamReq.
Referenced by EncodeSeCT_UserLeaveTeamReq.
int EncodeSeCT_UserLeaveTeamReq(DWord dwTeamID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_UserLeaveTeamReq(const char *pkData, int iLen, SeCT_UserLeaveTeamReq &kStruct)
References SeNetStream::Attach, SeCT_UserLeaveTeamReq::dwTeamID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_LeaderKickMemberReq(const SeCT_LeaderKickMemberReq &kData, char *pcBuf, int iMaxLen)
References SeCT_LeaderKickMemberReq::dwMemberID, SeCT_LeaderKickMemberReq::dwTeamID, EncodeSeCT_LeaderKickMemberReq.
Referenced by EncodeSeCT_LeaderKickMemberReq.
int EncodeSeCT_LeaderKickMemberReq(DWord dwTeamID, DWord dwMemberID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_LeaderKickMemberReq(const char *pkData, int iLen, SeCT_LeaderKickMemberReq &kStruct)
References SeNetStream::Attach, SeCT_LeaderKickMemberReq::dwMemberID, SeCT_LeaderKickMemberReq::dwTeamID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_LeaderDismissTeamReq(const SeCT_LeaderDismissTeamReq &kData, char *pcBuf, int iMaxLen)
References SeCT_LeaderDismissTeamReq::dwTeamID, EncodeSeCT_LeaderDismissTeamReq.
Referenced by EncodeSeCT_LeaderDismissTeamReq.
int EncodeSeCT_LeaderDismissTeamReq(DWord dwTeamID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_LeaderDismissTeamReq(const char *pkData, int iLen, SeCT_LeaderDismissTeamReq &kStruct)
References SeNetStream::Attach, SeCT_LeaderDismissTeamReq::dwTeamID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_GMSetGold(const SeCT_GMSetGold &kData, char *pcBuf, int iMaxLen)
References SeCT_GMSetGold::dwGold, EncodeSeCT_GMSetGold.
Referenced by EncodeSeCT_GMSetGold.
int EncodeSeCT_GMSetGold(DWord dwGold, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_GMSetGold(const char *pkData, int iLen, SeCT_GMSetGold &kStruct)
References SeNetStream::Attach, SeCT_GMSetGold::dwGold, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_GMSetDiamond(const SeCT_GMSetDiamond &kData, char *pcBuf, int iMaxLen)
References SeCT_GMSetDiamond::dwDiamond, EncodeSeCT_GMSetDiamond.
Referenced by EncodeSeCT_GMSetDiamond.
int EncodeSeCT_GMSetDiamond(DWord dwDiamond, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_GMSetDiamond(const char *pkData, int iLen, SeCT_GMSetDiamond &kStruct)
References SeNetStream::Attach, SeCT_GMSetDiamond::dwDiamond, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_NexusFriendCleanRefuseNoticeReq(const SeCT_NexusFriendCleanRefuseNoticeReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_NexusFriendCleanRefuseNoticeReq, SeCT_NexusFriendCleanRefuseNoticeReq::guest_id.
Referenced by EncodeSeCT_NexusFriendCleanRefuseNoticeReq.
int EncodeSeCT_NexusFriendCleanRefuseNoticeReq(DWord guest_id, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_NexusFriendCleanRefuseNoticeReq(const char *pkData, int iLen, SeCT_NexusFriendCleanRefuseNoticeReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_NexusFriendCleanRefuseNoticeReq::guest_id, SeNetStream::Read.
int EncodeSeCT_UserStatusQueryReq(const SeCT_UserStatusQueryReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_UserStatusQueryReq, SeCT_UserStatusQueryReq::num, SeCT_UserStatusQueryReq::user_ids.
Referenced by EncodeSeCT_UserStatusQueryReq.
int EncodeSeCT_UserStatusQueryReq(DWord num, const DWord *user_ids, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeCT_UserStatusQueryReq(DWord num, std::vector< DWord > &user_ids, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_UserStatusQueryReq(const char *pkData, int iLen, SeCT_UserStatusQueryReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeCT_UserStatusQueryReq::num, SeNetStream::Read, SeCT_UserStatusQueryReq::user_ids.
int EncodeSeCT_LadderRankQueryReq(const SeCT_LadderRankQueryReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_LadderRankQueryReq.
Referenced by EncodeSeCT_LadderRankQueryReq.
int EncodeSeCT_LadderRankQueryReq(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_LadderRankQueryReq(const char *pkData, int iLen, SeCT_LadderRankQueryReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_FriendLadderInfoReq(const SeCT_FriendLadderInfoReq &kData, char *pcBuf, int iMaxLen)
References SeCT_FriendLadderInfoReq::dwFriendID, EncodeSeCT_FriendLadderInfoReq.
Referenced by EncodeSeCT_FriendLadderInfoReq.
int EncodeSeCT_FriendLadderInfoReq(DWord dwFriendID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_FriendLadderInfoReq(const char *pkData, int iLen, SeCT_FriendLadderInfoReq &kStruct)
References SeNetStream::Attach, SeCT_FriendLadderInfoReq::dwFriendID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_UserMapRaceHeroReq(const SeCT_UserMapRaceHeroReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_UserMapRaceHeroReq.
Referenced by EncodeSeCT_UserMapRaceHeroReq.
int EncodeSeCT_UserMapRaceHeroReq(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_UserMapRaceHeroReq(const char *pkData, int iLen, SeCT_UserMapRaceHeroReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_SetActiveAvatarReq(const SeCT_SetActiveAvatarReq &kData, char *pcBuf, int iMaxLen)
References SeCT_SetActiveAvatarReq::bActive, SeCT_SetActiveAvatarReq::dwItemID, EncodeSeCT_SetActiveAvatarReq.
Referenced by EncodeSeCT_SetActiveAvatarReq.
int EncodeSeCT_SetActiveAvatarReq(bool bActive, DWord dwItemID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_SetActiveAvatarReq(const char *pkData, int iLen, SeCT_SetActiveAvatarReq &kStruct)
References SeNetStream::Attach, SeCT_SetActiveAvatarReq::bActive, SeCT_SetActiveAvatarReq::dwItemID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_UserAlterNickNameReq(const SeCT_UserAlterNickNameReq &kData, char *pcBuf, int iMaxLen)
References SeCT_UserAlterNickNameReq::acNickName, EncodeSeCT_UserAlterNickNameReq.
Referenced by EncodeSeCT_UserAlterNickNameReq.
int EncodeSeCT_UserAlterNickNameReq(const char *acNickName, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::WriteString.
int DecodeSeCT_UserAlterNickNameReq(const char *pkData, int iLen, SeCT_UserAlterNickNameReq &kStruct)
References SeCT_UserAlterNickNameReq::acNickName, SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::ReadString.
int EncodeSeCT_UserAlterAvatarReq(const SeCT_UserAlterAvatarReq &kData, char *pcBuf, int iMaxLen)
References SeCT_UserAlterAvatarReq::dwAvatarID, EncodeSeCT_UserAlterAvatarReq.
Referenced by EncodeSeCT_UserAlterAvatarReq.
int EncodeSeCT_UserAlterAvatarReq(DWord dwAvatarID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_UserAlterAvatarReq(const char *pkData, int iLen, SeCT_UserAlterAvatarReq &kStruct)
References SeNetStream::Attach, SeCT_UserAlterAvatarReq::dwAvatarID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_UserAlterAvatarFrameReq(const SeCT_UserAlterAvatarFrameReq &kData, char *pcBuf, int iMaxLen)
References SeCT_UserAlterAvatarFrameReq::dwAvatarFrameID, EncodeSeCT_UserAlterAvatarFrameReq.
Referenced by EncodeSeCT_UserAlterAvatarFrameReq.
int EncodeSeCT_UserAlterAvatarFrameReq(DWord dwAvatarFrameID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_UserAlterAvatarFrameReq(const char *pkData, int iLen, SeCT_UserAlterAvatarFrameReq &kStruct)
References SeNetStream::Attach, SeCT_UserAlterAvatarFrameReq::dwAvatarFrameID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_UserPurchaseAvatarReq(const SeCT_UserPurchaseAvatarReq &kData, char *pcBuf, int iMaxLen)
References SeCT_UserPurchaseAvatarReq::dwAvatarID, EncodeSeCT_UserPurchaseAvatarReq.
Referenced by EncodeSeCT_UserPurchaseAvatarReq.
int EncodeSeCT_UserPurchaseAvatarReq(DWord dwAvatarID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeCT_UserPurchaseAvatarReq(const char *pkData, int iLen, SeCT_UserPurchaseAvatarReq &kStruct)
References SeNetStream::Attach, SeCT_UserPurchaseAvatarReq::dwAvatarID, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeCT_LadderDetailInfoReq(const SeCT_LadderDetailInfoReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_LadderDetailInfoReq.
Referenced by EncodeSeCT_LadderDetailInfoReq.
int EncodeSeCT_LadderDetailInfoReq(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_LadderDetailInfoReq(const char *pkData, int iLen, SeCT_LadderDetailInfoReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeCT_AchieveInfoReq(const SeCT_AchieveInfoReq &kData, char *pcBuf, int iMaxLen)
References EncodeSeCT_AchieveInfoReq.
Referenced by EncodeSeCT_AchieveInfoReq.
int EncodeSeCT_AchieveInfoReq(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeCT_AchieveInfoReq(const char *pkData, int iLen, SeCT_AchieveInfoReq &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.