SeRaceRecord.h
HOLD_MAX_PACK
Referenced by SeRaceRecord::Clear, SeRaceRecord::GenRacePack, SeRaceRecord::GenRecordPack, SeRaceRecord::GetRacePack, SeRaceRecord::OnHostStop, SeRaceRecord::PushRacePack, SeRaceRecord::SeRaceRecord.
AI_UPDATE_TIME_RATIO
GAME_FRAME_LOCK_LIMIT
GAME_FRAME_PACK
GAME_DELAY_FRAME
VIEW_PACK_TIME
Referenced by SeRaceMgr::UpdateView.
RECON_PACK_TIME
Referenced by SeRaceMgr::UpdateReconBegin.
LIVE_PACK_TIME
VIEV_BARRAGE_PACK_TIME
SAVE_RECON_DATA_TIME
Referenced by SeRaceRecord::DragToTime, SeRaceRecord::GetReconOffPosByTime.
bool IsValidPlayerCmd(void *pkData, int iSize, bool bCheating=false)
References SeRaceCmd::dwCmd, GetRaceCmdSize, SRC_PLAYER_TOWNITEM, SRC_SYSTEM_CHEAT.
int GetRaceCmdSize(void *pkData, int iSize)
References SeRaceCmd::dwCmd, SIZEOF_A, SIZEOF_B, SIZEOF_C, SIZEOF_D, SIZEOF_E, SPRCT_BEGIN, SPRCT_END, SRC_ADJUSTFRAME, SRC_END, SRC_FIGHT_FOR_MAPITEM, SRC_FRAME, SRC_HERO_ATTACK_CANCEL, SRC_HERO_ATTACK_POS, SRC_HERO_ATTACK_UNIT, SRC_HERO_DIRECT_MOVE, SRC_HERO_HOLD, SRC_HERO_MOVE, SRC_HERO_RT_DIRECT, SRC_HERO_SELECT, SRC_HERO_STOP, SRC_HERO_SUPER_SKILL, SRC_HERO_TP_INTERRUPT, SRC_LOAD, SRC_LOCKUNIT, SRC_PAUSE_CANCEL, SRC_PING, SRC_PLAYER_ACHIEVEMENT, SRC_PLAYER_CAREER, SRC_PLAYER_GUANQIA_CMD, SRC_PLAYER_INFO, SRC_PLAYER_LEAVE, SRC_PLAYER_RECON_END, SRC_PLAYER_RELIVEHERO, SRC_PLAYER_SET_SIGHT_BALL, SRC_PLAYER_TOWNITEM, SRC_QUICK_TALK, SRC_RACE_PAUSE, SRC_RELINKBEGIN, SRC_RELINKEND, SRC_REPLAY_REPROT, SRC_REPLAYVERSION, SRC_SAVE_RECONDATA_BEGIN, SRC_SAVE_RECONDATA_END, SRC_SHOP_LIST, SRC_START, SRC_SWITCH_HEROFOCUS, SRC_SWITCH_MODE, SRC_SYSTEM_CHEAT, SRC_SYSTEM_SURRENDER, SRC_SYSTEM_SUSPEND, SRC_TRAN_LOADEND, SRC_UNIT_ACTIVE_SKILL, SRC_UNIT_ATTACK, SRC_UNIT_ATTACK_POS, SRC_UNIT_ATTACK_UNIT, SRC_UNIT_BUY_ITEM, SRC_UNIT_DIRECTBUY_ITEM, SRC_UNIT_DIRECTSELL_ITEM, SRC_UNIT_DISPLACE_ITEM, SRC_UNIT_DROP_ITEM, SRC_UNIT_FOLLOW, SRC_UNIT_GIVEUP_DISPLACE_ITEM, SRC_UNIT_HOLD, SRC_UNIT_LEARN_SKILL, SRC_UNIT_MOVE, SRC_UNIT_PATROL, SRC_UNIT_PICK_ITEM, SRC_UNIT_PICK_ITEM_AUTO, SRC_UNIT_SPELL, SRC_UNIT_SPELLXULI, SRC_UNIT_STOP, SRC_UNIT_SWAP_ITEM, SRC_UNIT_USE_DIR_ITEM, SRC_UNIT_USE_ITEM, SRC_WATCH_POINT.
Referenced by SeRaceRecord::EraseSRCFrameCmd, SeRaceRecord::GetRaceCmd, IsValidPlayerCmd, SeRaceRecord::PopRaceCmd, SeRaceRecord::PrintCmdLog, SeRaceRecord::PushRaceCmd, SeRaceRecord::PushRaceData, SeRaceRecord::PushRacePack.