SeFileLog.cpp
SeFileLog g_kFileLog
Referenced by RaceServer::ExecuteAction, RaceServer::Initialize.
void BeginConsoleColor(ELogLevel log_level)
References ELOGLV_DBG, ELOGLV_ERR, ELOGLV_INF, ELOGLV_SYS, ELOGLV_WRN.
Referenced by SeFileLog::Log.
void EndConsoleColor(void)
Referenced by SeFileLog::Log.
bool EnableFileLog(const char *pcDir)
References ELOGLV_DBG, ELOGLV_ERR, ELOGLV_INF, ELOGLV_SYS, ELOGLV_WRN, SeFileLog::Initialize, SeFileLog::SetLogLevel, StrCpy.
Referenced by ServerMain.