SeRCStream.cpp
int EncodeSeRC_EncryptKey(const SeRC_EncryptKey &kData, char *pcBuf, int iMaxLen)
References SeRC_EncryptKey::abyEncryptKey, SeRC_EncryptKey::dwVersion, EncodeSeRC_EncryptKey.
Referenced by EncodeSeRC_EncryptKey.
int EncodeSeRC_EncryptKey(const char *abyEncryptKey, DWord dwVersion, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeRC_EncryptKey(const char *pkData, int iLen, SeRC_EncryptKey &kStruct)
References SeRC_EncryptKey::abyEncryptKey, SeNetStream::Attach, SeRC_EncryptKey::dwVersion, SeNetStream::GetCurPos, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeRC_HeartBeat(const SeRC_HeartBeat &kData, char *pcBuf, int iMaxLen)
References EncodeSeRC_HeartBeat.
Referenced by EncodeSeRC_HeartBeat.
int EncodeSeRC_HeartBeat(char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int DecodeSeRC_HeartBeat(const char *pkData, int iLen, SeRC_HeartBeat &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos.
int EncodeSeRC_ValidateRet(const SeRC_ValidateRet &kData, char *pcBuf, int iMaxLen)
References SeRC_ValidateRet::bReturn, EncodeSeRC_ValidateRet.
Referenced by EncodeSeRC_ValidateRet.
int EncodeSeRC_ValidateRet(bool bReturn, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_ValidateRet(const char *pkData, int iLen, SeRC_ValidateRet &kStruct)
References SeNetStream::Attach, SeRC_ValidateRet::bReturn, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeRC_ShowNotice(const SeRC_ShowNotice &kData, char *pcBuf, int iMaxLen)
References SeRC_ShowNotice::acMessage, SeRC_ShowNotice::dwParam, EncodeSeRC_ShowNotice, SeRC_ShowNotice::eNoticeCode, SeRC_ShowNotice::iSize.
Referenced by EncodeSeRC_ShowNotice.
int EncodeSeRC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, int iSize, const char *acMessage, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, int iSize, std::vector< char > &acMessage, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_ShowNotice(const char *pkData, int iLen, SeRC_ShowNotice &kStruct)
References SeRC_ShowNotice::acMessage, SeNetStream::Attach, SeRC_ShowNotice::dwParam, SeRC_ShowNotice::eNoticeCode, SeNetStream::GetCurPos, SeRC_ShowNotice::iSize, SeNetStream::Read.
int EncodeSeRC_RoomPlayerBaseInfo(const SeRC_RoomPlayerBaseInfo &kData, char *pcBuf, int iMaxLen)
References SeRC_RoomPlayerBaseInfo::akPlayerInfo, SeRC_RoomPlayerBaseInfo::dwMapID, EncodeSeRC_RoomPlayerBaseInfo, SeRC_RoomPlayerBaseInfo::eRaceModel, SeRC_RoomPlayerBaseInfo::iNum.
Referenced by EncodeSeRC_RoomPlayerBaseInfo.
int EncodeSeRC_RoomPlayerBaseInfo(DWord dwMapID, SeRaceModel eRaceModel, int iNum, const SeMatchSelPlayerInfo *akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeMatchSelPlayerInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeRC_RoomPlayerBaseInfo(DWord dwMapID, SeRaceModel eRaceModel, int iNum, std::vector< SeMatchSelPlayerInfo > &akPlayerInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeMatchSelPlayerInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeRC_RoomPlayerBaseInfo(const char *pkData, int iLen, SeRC_RoomPlayerBaseInfo &kStruct)
References SeRC_RoomPlayerBaseInfo::akPlayerInfo, SeNetStream::Attach, DecodeSeMatchSelPlayerInfo, SeRC_RoomPlayerBaseInfo::dwMapID, SeRC_RoomPlayerBaseInfo::eRaceModel, SeNetStream::GetCurPos, SeRC_RoomPlayerBaseInfo::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeRC_RacePack(const SeRC_RacePack &kData, char *pcBuf, int iMaxLen)
References SeRC_RacePack::acData, SeRC_RacePack::dwPackIndex, EncodeSeRC_RacePack, SeRC_RacePack::iSize.
Referenced by EncodeSeRC_RacePack.
int EncodeSeRC_RacePack(DWord dwPackIndex, int iSize, const char *acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRC_RacePack(DWord dwPackIndex, int iSize, std::vector< char > &acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_RacePack(const char *pkData, int iLen, SeRC_RacePack &kStruct)
References SeRC_RacePack::acData, SeNetStream::Attach, SeRC_RacePack::dwPackIndex, SeNetStream::GetCurPos, SeRC_RacePack::iSize, SeNetStream::Read.
int EncodeSeRC_RaceStream(const SeRC_RaceStream &kData, char *pcBuf, int iMaxLen)
References SeRC_RaceStream::acData, EncodeSeRC_RaceStream, SeRC_RaceStream::iSize.
Referenced by EncodeSeRC_RaceStream.
int EncodeSeRC_RaceStream(int iSize, const char *acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRC_RaceStream(int iSize, std::vector< char > &acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_RaceStream(const char *pkData, int iLen, SeRC_RaceStream &kStruct)
References SeRC_RaceStream::acData, SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_RaceStream::iSize, SeNetStream::Read.
int EncodeSeRC_RacePlayerLoadEnd(const SeRC_RacePlayerLoadEnd &kData, char *pcBuf, int iMaxLen)
References SeRC_RacePlayerLoadEnd::dwRate, EncodeSeRC_RacePlayerLoadEnd, SeRC_RacePlayerLoadEnd::iSeat.
Referenced by EncodeSeRC_RacePlayerLoadEnd.
int EncodeSeRC_RacePlayerLoadEnd(int iSeat, DWord dwRate, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_RacePlayerLoadEnd(const char *pkData, int iLen, SeRC_RacePlayerLoadEnd &kStruct)
References SeNetStream::Attach, SeRC_RacePlayerLoadEnd::dwRate, SeNetStream::GetCurPos, SeRC_RacePlayerLoadEnd::iSeat, SeNetStream::Read.
int EncodeSeRC_BeginSelectHero(const SeRC_BeginSelectHero &kData, char *pcBuf, int iMaxLen)
References SeRC_BeginSelectHero::dwCamp, EncodeSeRC_BeginSelectHero.
Referenced by EncodeSeRC_BeginSelectHero.
int EncodeSeRC_BeginSelectHero(DWord dwCamp, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_BeginSelectHero(const char *pkData, int iLen, SeRC_BeginSelectHero &kStruct)
References SeNetStream::Attach, SeRC_BeginSelectHero::dwCamp, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeRC_SelHeroMessage(const SeRC_SelHeroMessage &kData, char *pcBuf, int iMaxLen)
References SeRC_SelHeroMessage::bDreamHero, SeRC_SelHeroMessage::dwDstPlayerID, SeRC_SelHeroMessage::dwHeroID, SeRC_SelHeroMessage::dwOrgPlayerID, SeRC_SelHeroMessage::eMessageType, EncodeSeRC_SelHeroMessage, SeRC_SelHeroMessage::iDecMoney.
Referenced by EncodeSeRC_SelHeroMessage.
int EncodeSeRC_SelHeroMessage(SeSelHeroMsgType eMessageType, DWord dwHeroID, bool bDreamHero, int iDecMoney, DWord dwOrgPlayerID, DWord dwDstPlayerID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_SelHeroMessage(const char *pkData, int iLen, SeRC_SelHeroMessage &kStruct)
References SeNetStream::Attach, SeRC_SelHeroMessage::bDreamHero, SeRC_SelHeroMessage::dwDstPlayerID, SeRC_SelHeroMessage::dwHeroID, SeRC_SelHeroMessage::dwOrgPlayerID, SeRC_SelHeroMessage::eMessageType, SeNetStream::GetCurPos, SeRC_SelHeroMessage::iDecMoney, SeNetStream::Read.
int EncodeSeRC_ReconResult(const SeRC_ReconResult &kData, char *pcBuf, int iMaxLen)
References EncodeSeRC_ReconResult, SeRC_ReconResult::eResult, SeRC_ReconResult::iData.
Referenced by EncodeSeRC_ReconResult.
int EncodeSeRC_ReconResult(SeReconResultType eResult, int iData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_ReconResult(const char *pkData, int iLen, SeRC_ReconResult &kStruct)
References SeNetStream::Attach, SeRC_ReconResult::eResult, SeNetStream::GetCurPos, SeRC_ReconResult::iData, SeNetStream::Read.
int EncodeSeRC_ReconPack(const SeRC_ReconPack &kData, char *pcBuf, int iMaxLen)
References SeRC_ReconPack::acData, EncodeSeRC_ReconPack, SeRC_ReconPack::iOffset, SeRC_ReconPack::iSize.
Referenced by EncodeSeRC_ReconPack.
int EncodeSeRC_ReconPack(int iOffset, int iSize, const char *acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRC_ReconPack(int iOffset, int iSize, std::vector< char > &acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_ReconPack(const char *pkData, int iLen, SeRC_ReconPack &kStruct)
References SeRC_ReconPack::acData, SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_ReconPack::iOffset, SeRC_ReconPack::iSize, SeNetStream::Read.
int EncodeSeRC_ViewPack(const SeRC_ViewPack &kData, char *pcBuf, int iMaxLen)
References SeRC_ViewPack::acData, EncodeSeRC_ViewPack, SeRC_ViewPack::iOffset, SeRC_ViewPack::iSize.
Referenced by EncodeSeRC_ViewPack.
int EncodeSeRC_ViewPack(int iOffset, int iSize, const char *acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRC_ViewPack(int iOffset, int iSize, std::vector< char > &acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_ViewPack(const char *pkData, int iLen, SeRC_ViewPack &kStruct)
References SeRC_ViewPack::acData, SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_ViewPack::iOffset, SeRC_ViewPack::iSize, SeNetStream::Read.
int EncodeSeRC_ViewResult(const SeRC_ViewResult &kData, char *pcBuf, int iMaxLen)
References EncodeSeRC_ViewResult, SeRC_ViewResult::eResult, SeRC_ViewResult::iData.
Referenced by EncodeSeRC_ViewResult.
int EncodeSeRC_ViewResult(SeViewResultType eResult, int iData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_ViewResult(const char *pkData, int iLen, SeRC_ViewResult &kStruct)
References SeNetStream::Attach, SeRC_ViewResult::eResult, SeNetStream::GetCurPos, SeRC_ViewResult::iData, SeNetStream::Read.
int EncodeSeRC_ViewPlayerInfo(const SeRC_ViewPlayerInfo &kData, char *pcBuf, int iMaxLen)
References SeRC_ViewPlayerInfo::akSeat, EncodeSeRC_ViewPlayerInfo, SeRC_ViewPlayerInfo::iNum.
Referenced by EncodeSeRC_ViewPlayerInfo.
int EncodeSeRC_ViewPlayerInfo(int iNum, const SePlayerInfoSeat *akSeat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePlayerInfoSeat, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeRC_ViewPlayerInfo(int iNum, std::vector< SePlayerInfoSeat > &akSeat, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSePlayerInfoSeat, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeRC_ViewPlayerInfo(const char *pkData, int iLen, SeRC_ViewPlayerInfo &kStruct)
References SeRC_ViewPlayerInfo::akSeat, SeNetStream::Attach, DecodeSePlayerInfoSeat, SeNetStream::GetCurPos, SeRC_ViewPlayerInfo::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeRC_Talk(const SeRC_Talk &kData, char *pcBuf, int iMaxLen)
References SeRC_Talk::acMsg, SeRC_Talk::dwSrcID, EncodeSeRC_Talk, SeRC_Talk::eType, SeRC_Talk::iSize.
Referenced by EncodeSeRC_Talk.
int EncodeSeRC_Talk(SeTalkType eType, DWord dwSrcID, int iSize, const char *acMsg, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write, SeNetStream::WriteString.
int DecodeSeRC_Talk(const char *pkData, int iLen, SeRC_Talk &kStruct)
References SeRC_Talk::acMsg, SeNetStream::Attach, SeRC_Talk::dwSrcID, SeRC_Talk::eType, SeNetStream::GetCurPos, SeRC_Talk::iSize, SeNetStream::Read, SeNetStream::ReadString.
int EncodeSeRC_SelPetList(const SeRC_SelPetList &kData, char *pcBuf, int iMaxLen)
References SeRC_SelPetList::akPetID, EncodeSeRC_SelPetList, SeRC_SelPetList::iNum.
Referenced by EncodeSeRC_SelPetList.
int EncodeSeRC_SelPetList(int iNum, const int *akPetID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRC_SelPetList(int iNum, std::vector< int > &akPetID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_SelPetList(const char *pkData, int iLen, SeRC_SelPetList &kStruct)
References SeRC_SelPetList::akPetID, SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_SelPetList::iNum, SeNetStream::Read.
int EncodeSeRC_SelHeroList(const SeRC_SelHeroList &kData, char *pcBuf, int iMaxLen)
References SeRC_SelHeroList::akInfo, EncodeSeRC_SelHeroList, SeRC_SelHeroList::iNum.
Referenced by EncodeSeRC_SelHeroList.
int EncodeSeRC_SelHeroList(int iNum, const SeSelHeroInfo *akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeSelHeroInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int EncodeSeRC_SelHeroList(int iNum, std::vector< SeSelHeroInfo > &akInfo, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeSelHeroInfo, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SeNetStream::Write.
int DecodeSeRC_SelHeroList(const char *pkData, int iLen, SeRC_SelHeroList &kStruct)
References SeRC_SelHeroList::akInfo, SeNetStream::Attach, DecodeSeSelHeroInfo, SeNetStream::GetCurPos, SeRC_SelHeroList::iNum, SeNetStream::Read, SeNetStream::SetCurPos.
int EncodeSeRC_SelHorseList(const SeRC_SelHorseList &kData, char *pcBuf, int iMaxLen)
References SeRC_SelHorseList::akHorseID, EncodeSeRC_SelHorseList, SeRC_SelHorseList::iNum.
Referenced by EncodeSeRC_SelHorseList.
int EncodeSeRC_SelHorseList(int iNum, const int *akHorseID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRC_SelHorseList(int iNum, std::vector< int > &akHorseID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_SelHorseList(const char *pkData, int iLen, SeRC_SelHorseList &kStruct)
References SeRC_SelHorseList::akHorseID, SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_SelHorseList::iNum, SeNetStream::Read.
int EncodeSeRC_PingRet(const SeRC_PingRet &kData, char *pcBuf, int iMaxLen)
References SeRC_PingRet::dwPackIndex, EncodeSeRC_PingRet.
Referenced by EncodeSeRC_PingRet.
int EncodeSeRC_PingRet(DWord dwPackIndex, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_PingRet(const char *pkData, int iLen, SeRC_PingRet &kStruct)
References SeNetStream::Attach, SeRC_PingRet::dwPackIndex, SeNetStream::GetCurPos, SeNetStream::Read.
int EncodeSeRC_GetHeroInfoRet(const SeRC_GetHeroInfoRet &kData, char *pcBuf, int iMaxLen)
References SeRC_GetHeroInfoRet::acData, EncodeSeRC_GetHeroInfoRet, SeRC_GetHeroInfoRet::iSize.
Referenced by EncodeSeRC_GetHeroInfoRet.
int EncodeSeRC_GetHeroInfoRet(int iSize, const char *acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int EncodeSeRC_GetHeroInfoRet(int iSize, std::vector< char > &acData, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_GetHeroInfoRet(const char *pkData, int iLen, SeRC_GetHeroInfoRet &kStruct)
References SeRC_GetHeroInfoRet::acData, SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_GetHeroInfoRet::iSize, SeNetStream::Read.
int EncodeSeRC_RaceEndNotifyDown(const SeRC_RaceEndNotifyDown &kData, char *pcBuf, int iMaxLen)
References SeRC_RaceEndNotifyDown::acRaceID, SeRC_RaceEndNotifyDown::acURLBase, EncodeSeRC_RaceEndNotifyDown.
Referenced by EncodeSeRC_RaceEndNotifyDown.
int EncodeSeRC_RaceEndNotifyDown(const char *acURLBase, const char *acRaceID, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::WriteString.
int DecodeSeRC_RaceEndNotifyDown(const char *pkData, int iLen, SeRC_RaceEndNotifyDown &kStruct)
References SeRC_RaceEndNotifyDown::acRaceID, SeRC_RaceEndNotifyDown::acURLBase, SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::ReadString.
int EncodeSeRC_RaceGoldExpPlus(const SeRC_RaceGoldExpPlus &kData, char *pcBuf, int iMaxLen)
References EncodeSeRC_RaceGoldExpPlus, SeRC_RaceGoldExpPlus::RaceExp, SeRC_RaceGoldExpPlus::RaceGold.
Referenced by EncodeSeRC_RaceGoldExpPlus.
int EncodeSeRC_RaceGoldExpPlus(int RaceGold, int RaceExp, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_RaceGoldExpPlus(const char *pkData, int iLen, SeRC_RaceGoldExpPlus &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_RaceGoldExpPlus::RaceExp, SeRC_RaceGoldExpPlus::RaceGold, SeNetStream::Read.
int EncodeSeRC_SetEquipSetAck(const SeRC_SetEquipSetAck &kData, char *pcBuf, int iMaxLen)
References EncodeSeRC_SetEquipSetAck, SeRC_SetEquipSetAck::iResult.
Referenced by EncodeSeRC_SetEquipSetAck.
int EncodeSeRC_SetEquipSetAck(int iResult, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_SetEquipSetAck(const char *pkData, int iLen, SeRC_SetEquipSetAck &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_SetEquipSetAck::iResult, SeNetStream::Read.
int EncodeSeRC_SetAvatarAck(const SeRC_SetAvatarAck &kData, char *pcBuf, int iMaxLen)
References EncodeSeRC_SetAvatarAck, SeRC_SetAvatarAck::iResult.
Referenced by EncodeSeRC_SetAvatarAck.
int EncodeSeRC_SetAvatarAck(int iResult, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeNetStream::Write.
int DecodeSeRC_SetAvatarAck(const char *pkData, int iLen, SeRC_SetAvatarAck &kStruct)
References SeNetStream::Attach, SeNetStream::GetCurPos, SeRC_SetAvatarAck::iResult, SeNetStream::Read.
int EncodeSeRC_SeatScoreNtf(const SeRC_SeatScoreNtf &kData, char *pcBuf, int iMaxLen)
References EncodeSeRC_SeatScoreNtf, SeRC_SeatScoreNtf::scores.
Referenced by EncodeSeRC_SeatScoreNtf.
int EncodeSeRC_SeatScoreNtf(const SeSeatScore *scores, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeSeatScore, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SSD_MAX_ROOM_PLAYER.
int EncodeSeRC_SeatScoreNtf(std::vector< SeSeatScore > &scores, char *pcBuf, int iMaxLen)
References SeNetStream::Attach, EncodeSeSeatScore, SeNetStream::GetCurPos, SeNetStream::SetCurPos, SSD_MAX_ROOM_PLAYER.
int DecodeSeRC_SeatScoreNtf(const char *pkData, int iLen, SeRC_SeatScoreNtf &kStruct)
References SeNetStream::Attach, DecodeSeSeatScore, SeNetStream::GetCurPos, SeRC_SeatScoreNtf::scores, SeNetStream::SetCurPos, SSD_MAX_ROOM_PLAYER.