SeToolTemplate.inl
void AttachList(T *pkT, T *&pkFirst, T *&pkLast)
Referenced by SeDBPlayerMgr::AttachLink, SeCacheMgr::OnAccountLogout.
void DetachList(T *pkT, T *&pkFirst, T *&pkLast)
Referenced by SeDBPlayerMgr::AttachLink, SeDBPlayerMgr::ClearDBPlayer, SeCacheMgr::DelAccount, SeDBPlayerMgr::DetachLink, SeCacheMgr::OnAccountLogin, SeCacheMgr::OnAccountLogout.
size_t CountOf(const T(&temp)[N])