SeMatchMgr.cpp
MATCH_DEBUG
SeMatchMgr g_kMatchMgr
Referenced by SeRaceMgr::DoRaceOver, MatchPrepareMgr::onDataResult, MatchServer::ProcessTM_MatchConfirm, MatchServer::ProcessTM_PlayerLeave, MatchServer::ProcessTM_PlayerMatchCancel, MatchServer::Update.
const int TURN_FALSE_FORCE_GAME
Referenced by SeMatchMgr::match.
const int TURN_NOVICE_JOIN_FALSE
MatchRule s_matchRules[][]
Referenced by getMatchRules.
int s_matchRulesSize
Referenced by getMatchRules.
MatchRule s_ladderRules[][]
Referenced by getMatchRules.
int s_ladderRulesSize
Referenced by getMatchRules.
const int CAMP_SIZE
Referenced by SeMatchMgr::openRoom.
int s_fiveCombination[][6][][6]
const int s_fiveCombinationSize
int s_fourCombination[][6][][6]
const int s_fourCombinationSize
int s_threeCombination[][6][][6]
const int s_threeCombinationSize
int s_twoCombination[][6][][6]
const int s_twoCombinationSize
int s_oneCombination[][6][][6]
const int s_oneCombinationSize
CombinationItem s_combinations[][]
IMPLEMENT_POOL(SeMatchMgr::MatchItem, 256, 256)
IMPLEMENT_POOL(SeMatchMgr::WaitItem, 256, 256)
static double maxPercent(double force, double param)
static double minPercent(double force, double param)
static double maxValue(double force, double param)
static double minValue(double force, double param)
static MatchRule* getMatchRules(MatchType eMatchType, int &size)
References EMT_LADDER, s_ladderRules, s_ladderRulesSize, s_matchRules, s_matchRulesSize.
Referenced by SeMatchMgr::match, SeMatchMgr::OnMatchReq, SeMatchMgr::rejoinMatch.