TeMisc.cpp
PRIVATE_CODE
Referenced by FilterText, IsFilterText.
TeEnDef
int Char2Index(char cChar)
References TED_DIG_POS, TED_LOW_POS, TED_SUP_POS.
Referenced by DecodePassword, EncodePassword.
char Index2Char(int iIndex)
References TED_END_POS, TED_LOW_POS, TED_SUP_POS.
Referenced by DecodePassword, EncodePassword.
bool EncodePassword(char *pcPassword)
References Char2Index, Index2Char, TED_END_POS.
bool DecodePassword(char *pcPassword)
References Char2Index, Index2Char, TED_END_POS.
void EncodeData(void *pkData, int iSize, Byte abyKey[])
void DecodeData(void *pkData, int iSize, Byte abyKey[])
bool CompressData(void *pkDst, int &iDstSize, void *pkSrc, int iSrcSize)
bool UncompressData(void *pkDst, int &iDstSize, void *pkSrc, int iSrcSize)
int GetCRC32(void *pkData, int iSize, int iOrgCrc)
const TeMD5& GetMD5(void *pkData, int iSize)
References TeMD5::abyMD5, g_kMD5Check, TeMD5Check::GetMD5.
Referenced by SeRaceMgr::GenRaceID, GlobalServer::ProcessLG_PlayerLogin.
bool IsFilterText(const char *pcText)
References PRIVATE_CODE.
void FilterText(const char *pcText)
References PRIVATE_CODE.
DWord GetClientVersion(Byte *abyEncryptKey, Byte *abyClientVersion)
DWord GetClientNum(Byte *abyEncryptKey, Byte *abyClientVersion)
bool DecryptData(Byte *abyEncryptKey, Byte abyDstData[], int iDstLen, Byte abySrcData[])