SePlayer.inl
DWord GetClientID(void) const
DWord GetID(void) const
Referenced by CItemMgr::doExchangeItem, CItemMgr::doMoveItem, CItemMgr::notiChangeItem, HeroMgr::notifyChanged, CItemMgr::PackAllItem, ActiveAvatarMgr::sendInitData, EquipSchemaMgr::sendInitData.
const char* GetName(void) const
void SetName(const char *pcName)
References StrCpy.
void SetHeroCardTypeID(DWord dwHeroCardTypeID)
DWord GetHeroCardTypeID(void) const
SePlayerState GetPlayerState(void) const
void SetSingleMatching(bool bSingleMatching)
bool IsSingleMatching(void)
void SetMatchLoading(bool bLoading)
bool IsMatchLoading(void)
void SetMatchSession(DWord dwSession)
DWord GetMatchSession()
void ClearSingleMatchInfo()
float GetPosX(void)
float GetPosY(void)
void SetPos(float fX, float fY)
void SetMapEntityID(DWord dwID)
DWord GetMapEntityID(void)
void SetTeamID(DWord dwTeamID)
DWord GetTeamID(void)
void SetTeamMemberNum(int iNum)
int GetTeamMemberNum(void)
void SetDeviceOS(SeDeviceOS eOSType)
SeDeviceOS GetDeviceOS(void)
int GetLeagueScore(void)
void SetLeagueScore(int iLeagueScore)
int GetLeagueMMR(void)
void SetLeagueMMR(int iMMR)
SeMatchStartInfo GetMatchStartInfo()
References SeMatchStartInfo::iLeagueMMR, SeMatchStartInfo::iLeagueScore.