SePlayer.inl
const int DEFAULT_DEFEAT
Referenced by GetBattleField, GetMatch.
const int DEFAULT_SCORE
Referenced by GetBattleField, GetMatch.
const int DEFEAT_RESTORE2_THRESHOLD
Referenced by adjustDefeat.
const int DEFEAT_RESTORE5_THRESHOLD
Referenced by adjustDefeat.
DWord GetID(void) const
void SetAccountInfo(SePtlAccountInfo &rkAccountInfo)
const SePtlAccountInfo& GetAccountInfo(void) const
const char* GetAccount(void) const
int GetPlatFlag(void) const
void SetMobileInfo(SeMobileInfo &rkMobileInfo)
const SeMobileInfo& GetMobileInfo(void) const
void SetSessionID(DWord dwSessionID)
DWord GetSessionID(void)
void SetTownIndex(int iIndex)
int GetTownIndex(void) const
void SetTownServerID(DWord dwTownServerID)
DWord GetTownServerID(void) const
void SetTownSock(HSock kTownSock)
HSock& GetTownSock(void)
Referenced by CItemMgr::doExchangeItem, CItemMgr::doMoveItem, CItemMgr::notiChangeItem, HeroMgr::notifyChanged, CItemMgr::PackAllItem, ActiveAvatarMgr::sendInitData, EquipSchemaMgr::sendInitData.
void SetState(SePlayerState eState)
void SetTemState(SePlayerState eState)
SePlayerState GetState(void)
bool HasFlag(int iFlag) const
void SetFlag(int iFlag)
void setLoadingFlag(SeDBTableIndex eTable)
void clearLoadingFlag(SeDBTableIndex eTable)
void ClrFlag(int iFlag)
void SetLoadComplete(bool bComplete)
bool IsLoadComplete(void)
void SetLoadInfoAgain(bool bLoadInfoAgain)
bool GetLoadInfoAgain(void)
void SetBeginLoadAgainTime(DWord dwTime)
void SetLoadFlag(int iFlag)
bool isLoadingComplete()
References HasLoadFlag, PLF_ALL_FLAG.
bool HasLoadFlag(int iFlag)
Referenced by isLoadingComplete.
void SetLoadFlagCount(SeLoadFlag eFlag, int iCount)
int GetLoadFlagCount(SeLoadFlag eFlag)
void SetLoadFlagCount(SeDBTableIndex eTable, int iCount)
int GetLoadFlagCount(SeDBTableIndex eTable)
void SetBlockServer(BlockServer *pkBlockServer)
void SetPlayerIP(DWord dwPlayerIP)
DWord GetPlayerIP()
void SetMaxMailID(DWord dwMaxMailID)
DWord GetMaxMailID()
void SetBeginLoadTime(DWord dwTime)
void SetName(const char *pcName)
References SSD_MAX_CHAR_NAME, StrCpy.
const char* GetName(void) const
void SetGold(int iGold)
int GetGold(void) const
Referenced by CItemMgr::doItemMergeCharge, CItemMgr::StrenthEquip.
void SetDiamond(int iDiamond)
int GetDiamond(void) const
void SetCreateTime(SeDBTime &ctCreateTime)
const SeDBTime& GetCreateTime() const
void SetCharLevel(DWord level)
const DWord GetCharLevel() const
void SetExp(DWord dwExp)
const DWord GetExp() const
void GetMatchBaseInfo(SeMatchBaseInfo &rkBaseInfo)
References SeMatchBaseInfo::acName, GetTDBTime, SeMatchBaseInfo::iDiamond, SeMatchBaseInfo::iExp, SeMatchBaseInfo::iGold, SeMatchBaseInfo::iRaceArenaTime, SeMatchBaseInfo::iRaceCumuGolds.
void GetScoreInfo(MatchType eMatchType, SeScoreInfo &rkScore, DWord &matchNum)
References SeScoreInfo::defeat, EMT_BATTLEFIELD, EMT_LADDER, EMT_MATCH, GetBattleField, GetMatch, SeScoreInfo::level, SeScoreInfo::score.
const SeDBTime& GetEnterTime(void) const
void SetOnlineTime(UInt uiOnlineTime)
UInt GetOnlineTime(void) const
void SetBattleTime(SeDBTime &time)
const SeDBTime& GetBattleTime() const
void SetLoginTime(SeDBTime &time)
const SeDBTime& GetLoginTime() const
static void adjustDefeat(SeDBTime &dbTime, DWord &defeat)
References DEFEAT_RESTORE2_THRESHOLD, DEFEAT_RESTORE5_THRESHOLD, moba::getDiffDays, GetTDBTime, NowTime.
Referenced by GetBattleField, GetMatch.
void SetBattleField(const SeDBTime &time, int defeat, int score)
void GetBattleField(int &defeat, int &score)
References adjustDefeat, DEFAULT_DEFEAT, DEFAULT_SCORE, NowTime.
Referenced by GetScoreInfo.
void SetMatch(const SeDBTime &time, int defeat, int score, int num)
void GetMatch(int &defeat, int &score, int &num)
References adjustDefeat, DEFAULT_DEFEAT, DEFAULT_SCORE, NowTime.
Referenced by GetScoreInfo.
void SetLadder(const SeDBTime &time, int defeat, int score, int no, int level)
void SetEquipSetIndex(Byte index)
Byte GetEquipSetIndex() const
void SetRaceCumuGolds(DWord golds)
DWord GetRaceCumuGolds() const
void SetUserAvatar(DWord avatar)
DWord GetUserAvatar() const
void SetUserAvatarFrame(DWord avatarFrame)
DWord GetUserAvatarFrame() const
const SeDBTime& GetTaskResetTime() const
void SetTaskResetTime(const SeDBTime &time)
DWord GetTaskResetCount() const
void SetTaskResetCount(DWord count)
int GetEquipFightScore()