RenJiConditionsTableMgr
std::map<unsigned int,RenJiConditionsTable*> RenJiConditionsTableMgr::m_kRenJiConditionsTableMap
Referenced by FillData, GetRenJiConditionsTable, GetRenJiConditionsTableMap, GetRenJiConditionsTableVec, ~RenJiConditionsTableMgr.
RenJiConditionsTableMgr * RenJiConditionsTableMgr::m_pkRenJiConditionsTableMgr
Referenced by Get, ReLoad.
RenJiConditionsTableMgr * RenJiConditionsTableMgr::Get()
References m_pkRenJiConditionsTableMgr, RenJiConditionsTableMgr.
Referenced by TableMgr::InitRenjiCondition, ReLoad.
RenJiConditionsTableMgr * RenJiConditionsTableMgr::ReLoad()
References Get, m_pkRenJiConditionsTableMgr.
RenJiConditionsTableMgr::RenJiConditionsTableMgr()
References Load.
Referenced by Get.
RenJiConditionsTableMgr::~RenJiConditionsTableMgr()
References m_kRenJiConditionsTableMap.
const RenJiConditionsTable * RenJiConditionsTableMgr::GetRenJiConditionsTable(unsigned int iTypeID)
References m_kRenJiConditionsTableMap.
const std::map< unsigned int, RenJiConditionsTable * > & RenJiConditionsTableMgr::GetRenJiConditionsTableMap()
References m_kRenJiConditionsTableMap.
Referenced by TableMgr::InitRenjiCondition.
TableResArray RenJiConditionsTableMgr::GetRenJiConditionsTableVec()
References m_kRenJiConditionsTableMap, TableResArray::pushBack.
bool RenJiConditionsTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RenJiConditionsTableMgr.
void RenJiConditionsTableMgr::FillData(RenJiConditionsTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RenJiConditionsTable::fConditionValue, RenJiConditionsTable::iConditionScope, RenJiConditionsTable::iDelTime, RenJiConditionsTable::iSpecConditionValue, RenJiConditionsTable::iTypeID, RenJiConditionsTable::kDiscription, m_kRenJiConditionsTableMap, RenJiConditionsTable::uiCompareType, RenJiConditionsTable::uiConditionID, RenJiConditionsTable::uiConditionTarget, RenJiConditionsTable::uiConditionType, RenJiConditionsTable::uiConditionUnit, RenJiConditionsTable::uiProperty, RenJiConditionsTable::uiSpecialValue.
Referenced by Load.