TableMgr
TableMgr * TableMgr::m_pkAllTableMgr
Referenced by Get.
std::map<int, int> TableMgr::m_akHeroID2PosIndex
Referenced by GetPosIndexByHeroID, InitHeroPosIndex.
std::map<int, int> TableMgr::m_akPosIndex2HeroID
Referenced by GetHeroIDByPosIndex, InitHeroPosIndex.
std::map<int, int> TableMgr::m_akPetID2PosIndex
Referenced by GetPosIndexByPetID, InitPetPosIndex.
std::map<int, int> TableMgr::m_akPosIndex2PetID
Referenced by GetPetIDByPosIndex, InitPetPosIndex.
std::map<int, int> TableMgr::m_akHorseID2PosIndex
Referenced by GetPosIndexByHorseID, InitHorsePosIndex.
std::map<int, int> TableMgr::m_akPosIndex2HorseID
Referenced by GetHorseIDByPosIndex, InitHorsePosIndex.
MPreTask TableMgr::m_MainTaskPre
Referenced by GetNextMainTaskID, InitTaskList.
VTaskTypeID TableMgr::m_TaskTypeID
Referenced by GetDailyTaskIDList, GetFirstDailyTaskID, GetTaskIDInfo, InitTaskList, IsFirstWinTask.
std::map<int, std::vector<std::string> > TableMgr::m_akUnit2Model
Referenced by GetModelResByUnit, InitModelRes.
std::map<int, std::vector<std::string> > TableMgr::m_akUnit2Voice
Referenced by GetVoiceResByUnit, InitVoiceRes.
std::vector<RenJiConditionsTable*> TableMgr::m_akRenjiVec
Referenced by GetRenjiConditionByID, InitRenjiCondition.
std::map<int, std::vector<int> > TableMgr::m_akRaceHelperSkill
Referenced by GetRaceHelpSkillTypes, InitRaceHelperRes.
std::map<unsigned long long, std::vector<int> > TableMgr::m_akRaceHeperMasteryRecom
Referenced by GetRaceHelpMasterySkillTypes, InitRaceHelperRes.
SeGlobalLanguage TableMgr::m_eLanguage
Referenced by GetLanguage, GetText, SetLanguage, TableMgr.
SeGlobalLanguage TableMgr::m_eSoundLanguage
Referenced by GetSoundLanguage, GetVoiceInfo, SetSoundLanguage, TableMgr.
TableLoader* TableMgr::m_pkLoader
Referenced by GetTableLoader, SetTableLoader, ~TableMgr.
std::vector<ChoiceItemTable*> TableMgr::WishBuyOrderVec
Referenced by GetWishBuyID, InitWishBuyOrder.
std::map<unsigned int, UnitTable*> TableMgr::m_mapCreateSightUnits
Referenced by InitCreateSightUnit, IsCreateSightUnit.
std::map<unsigned int, std::vector<unsigned int> > TableMgr::ItemReelMap
Referenced by GetWishAttrItems, InitReelMap.
std::map<unsigned int, AchieveTypeInfo*> TableMgr::m_AchieveGroupIDMap
Referenced by GetAchieveInfo, LoadAchieveInfo.
static void TableMgr::LoadTable()
References KillBountyTableMgr::Get, TaskRecomTableMgr::Get, ChoiceItemTableMgr::Get, AvatarShopTableMgr::Get, MapShopResTableMgr::Get, AddtionalTableMgr::Get, RandomNameTableMgr::Get, SystemPromptTableMgr::Get, AttackArmorRatioTableMgr::Get, LevelTableMgr::Get, EffectSwitchTableMgr::Get, LanguageTableMgr::Get, AITableMgr::Get, RacehelpTableMgr::Get, AchievementTableMgr::Get, VoiceTableMgr::Get, PresetShopTableMgr::Get, UpgradeCostTableMgr::Get, AcSystemTableMgr::Get, AppendCostTableMgr::Get, RankStageTableMgr::Get, ChanceTableMgr::Get, ItemComposeTableMgr::Get, CreepTowerGrowthTableMgr::Get, FreeHeroesTableMgr::Get, PropagandaTableMgr::Get, DecomposeTableMgr::Get, ShopTableMgr::Get, ModelResTableMgr::Get, HeroInfoTableMgr::Get, RacedropTableMgr::Get, RackTableMgr::Get, BufferTableMgr::Get, BattleTipsTableMgr::Get, SkillTipsTableMgr::Get, VideoTagTableMgr::Get, AvatarTableMgr::Get, SelHeroTableMgr::Get, AppendSkillTableMgr::Get, ItemExchangeTableMgr::Get, TaskInfoTableMgr::Get, MapInfoTableMgr::Get, StrengthenTableMgr::Get, ItemTableMgr::Get, UnitTableMgr::Get, SkillTableMgr::Get, TownItemTableMgr::Get, InitData.
Referenced by SeResMgr::Initialize, SeReMgr::Initialize, RaceServer::Initialize.
TableMgr * TableMgr::Get()
References m_pkAllTableMgr, TableMgr.
Referenced by TaskMgr::GetDailyTaskNextTask, SeFormula::GetHorseFlag2HorseID, SeFormula::GetHorseID2HorseFlag, TaskMgr::GetMainTaskNextTask, GlobalTableMgr::GetText, TaskMgr::GetWinTaskNextTask, InitData, KillBountyTableMgr::Load, TaskRecomTableMgr::Load, AvatarShopTableMgr::Load, MapShopResTableMgr::Load, AppendGroupTableMgr::Load, ChoiceItemTableMgr::Load, RandomNameTableMgr::Load, AvatarModelTableMgr::Load, AddtionalTableMgr::Load, RaceTextTableMgr::Load, AttackArmorRatioTableMgr::Load, SystemPromptTableMgr::Load, UnitHeadAreaTableMgr::Load, LevelTableMgr::Load, EffectSwitchTableMgr::Load, LanguageTableMgr::Load, DressTableMgr::Load, AITableMgr::Load, RacehelpTableMgr::Load, AchievementTableMgr::Load, HorseTableMgr::Load, AvatarAnimationTableMgr::Load, AIPrioTableMgr::Load, VoiceTableMgr::Load, PresetShopTableMgr::Load, IndexofferTableMgr::Load, AvatarEffectTableMgr::Load, AcSystemTableMgr::Load, AccountLevelTableMgr::Load, UpgradeCostTableMgr::Load, ChanceTableMgr::Load, RenJiTableMgr::Load, SearchChoiceTableMgr::Load, ItemComposeTableMgr::Load, PetTableMgr::Load, AppendCostTableMgr::Load, RankStageTableMgr::Load, CreepTowerGrowthTableMgr::Load, FreeHeroesTableMgr::Load, LeagueRankTableMgr::Load, ShopTableMgr::Load, PropagandaTableMgr::Load, DecomposeTableMgr::Load, MapMiscTableMgr::Load, ModelResTableMgr::Load, RenJiActionsTableMgr::Load, RenJiCustomDataTableMgr::Load, HeroInfoTableMgr::Load, StarWheelTableMgr::Load, RacedropTableMgr::Load, RackTableMgr::Load, BufferTableMgr::Load, MissionInfoTableMgr::Load, BattleTipsTableMgr::Load, PVERuleTableMgr::Load, VideoTagTableMgr::Load, AppendSkillPRTableMgr::Load, RenJiConditionsTableMgr::Load, RaceStaMissionTableMgr::Load, AvatarTableMgr::Load, MapsInfoTableMgr::Load, AppendSkillTableMgr::Load, SelHeroTableMgr::Load, ItemExchangeTableMgr::Load, TaskInfoTableMgr::Load, AchievementTaskTableMgr::Load, MapInfoTableMgr::Load, StrengthenTableMgr::Load, UnitTableMgr::Load, ItemTableMgr::Load, TownItemTableMgr::Load, SkillTableMgr::LoadSkillFile, SystemPromptTableMgr::UpdateLanguadgeContent, AchievementTableMgr::UpdateLanguadgeContent, RankStageTableMgr::UpdateLanguadgeContent, PropagandaTableMgr::UpdateLanguadgeContent, HeroInfoTableMgr::UpdateLanguadgeContent, BattleTipsTableMgr::UpdateLanguadgeContent, MissionInfoTableMgr::UpdateLanguadgeContent, SkillTipsTableMgr::UpdateLanguadgeContent, SelHeroTableMgr::UpdateLanguadgeContent, MapInfoTableMgr::UpdateLanguadgeContent, UnitTableMgr::UpdateLanguadgeContent, ItemTableMgr::UpdateLanguadgeContent.
void TableMgr::InitData()
References Get, InitCreateSightUnit, InitHeroPosIndex, InitHorsePosIndex, InitModelRes, InitPetPosIndex, InitRaceHelperRes, InitReelMap, InitRenjiCondition, InitTaskList, InitVoiceRes, InitWishBuyOrder.
Referenced by LoadTable, ReloadTable.
void TableMgr::ReloadTable()
References InitData, KillBountyTableMgr::ReLoad, TaskRecomTableMgr::ReLoad, AvatarShopTableMgr::ReLoad, MapShopResTableMgr::ReLoad, ChoiceItemTableMgr::ReLoad, AddtionalTableMgr::ReLoad, AvatarModelTableMgr::ReLoad, RandomNameTableMgr::ReLoad, SystemPromptTableMgr::ReLoad, AttackArmorRatioTableMgr::ReLoad, LevelTableMgr::ReLoad, EffectSwitchTableMgr::ReLoad, LanguageTableMgr::ReLoad, AITableMgr::ReLoad, RacehelpTableMgr::ReLoad, AchievementTableMgr::ReLoad, AvatarAnimationTableMgr::ReLoad, VoiceTableMgr::ReLoad, PresetShopTableMgr::ReLoad, AvatarEffectTableMgr::ReLoad, UpgradeCostTableMgr::ReLoad, AcSystemTableMgr::ReLoad, AppendCostTableMgr::ReLoad, ChanceTableMgr::ReLoad, ItemComposeTableMgr::ReLoad, SearchChoiceTableMgr::ReLoad, CreepTowerGrowthTableMgr::ReLoad, FreeHeroesTableMgr::ReLoad, DecomposeTableMgr::ReLoad, ShopTableMgr::ReLoad, ModelResTableMgr::ReLoad, HeroInfoTableMgr::ReLoad, RacedropTableMgr::ReLoad, RackTableMgr::ReLoad, BufferTableMgr::ReLoad, BattleTipsTableMgr::ReLoad, SkillTipsTableMgr::ReLoad, VideoTagTableMgr::ReLoad, AvatarTableMgr::ReLoad, AppendSkillTableMgr::ReLoad, SelHeroTableMgr::ReLoad, ItemExchangeTableMgr::ReLoad, TaskInfoTableMgr::ReLoad, MapInfoTableMgr::ReLoad, StrengthenTableMgr::ReLoad, UnitTableMgr::ReLoad, ItemTableMgr::ReLoad, SkillTableMgr::ReLoad, TownItemTableMgr::ReLoad.
void TableMgr::UpdateLanguageContent()
References SystemPromptTableMgr::Get, AchievementTableMgr::Get, RankStageTableMgr::Get, PropagandaTableMgr::Get, HeroInfoTableMgr::Get, MissionInfoTableMgr::Get, BattleTipsTableMgr::Get, SkillTipsTableMgr::Get, MapInfoTableMgr::Get, UnitTableMgr::Get, ItemTableMgr::Get, SystemPromptTableMgr::UpdateLanguadgeContent, AchievementTableMgr::UpdateLanguadgeContent, RankStageTableMgr::UpdateLanguadgeContent, PropagandaTableMgr::UpdateLanguadgeContent, HeroInfoTableMgr::UpdateLanguadgeContent, BattleTipsTableMgr::UpdateLanguadgeContent, MissionInfoTableMgr::UpdateLanguadgeContent, SkillTipsTableMgr::UpdateLanguadgeContent, MapInfoTableMgr::UpdateLanguadgeContent, UnitTableMgr::UpdateLanguadgeContent, ItemTableMgr::UpdateLanguadgeContent.
TableMgr::TableMgr()
References m_eLanguage, m_eSoundLanguage, SGL_ZH_CN.
Referenced by Get.
TableMgr::~TableMgr()
References m_pkLoader.
int TableMgr::GetItemComposee(unsigned int iTypeID, unsigned int *iOutComposee)
References ItemComposeTableMgr::Get, ItemComposeTableMgr::GetItemComposeTable, MAX_COMPOSEE, ItemComposeTable::uiItemIDA, ItemComposeTable::uiItemIDB, ItemComposeTable::uiItemIDC, ItemComposeTable::uiItemIDD.
int TableMgr::GetAllMapMissionID(std::vector< int > &rkID, int iMap, bool bHasNoMissionRate=true) const
References RacedropTableMgr::Get, RacedropTableMgr::GetRacedropTableMap, RacedropTable::uiMapID.
int TableMgr::GetModleIndex(std::string kName)
References ModelResTableMgr::Get, ModelResTableMgr::GetModelResTableMap, ModelResTable::kPath, ModelResTable::uiID.
int TableMgr::GetHeroIDByPosIndex(int iPosIndex)
References m_akPosIndex2HeroID.
int TableMgr::GetPosIndexByHeroID(int iHeroID)
References m_akHeroID2PosIndex.
int TableMgr::GetPetIDByPosIndex(int iPosIndex)
References m_akPosIndex2PetID.
int TableMgr::GetPosIndexByPetID(int iPetID)
References m_akPetID2PosIndex.
int TableMgr::GetHorseIDByPosIndex(int iPosIndex)
References m_akPosIndex2HorseID.
Referenced by SeFormula::GetHorseFlag2HorseID.
int TableMgr::GetPosIndexByHorseID(int iHorseID)
References m_akHorseID2PosIndex.
Referenced by SeFormula::GetHorseID2HorseFlag.
float TableMgr::GetRenJiCustomValue(int iTypeID)
References RenJiCustomDataTable::fValue, RenJiCustomDataTableMgr::Get, RenJiCustomDataTableMgr::GetRenJiCustomDataTable.
bool TableMgr::IsCreateSightUnit(unsigned int iTypeID)
References m_mapCreateSightUnits.
int TableMgr::GetLeagueLevelByScore(int iScore)
References LeagueRankTableMgr::Get, LeagueRankTableMgr::GetLeagueRankTableMap, LeagueRankTable::iLevel, LeagueRankTable::iMinScore.
int TableMgr::GetMaxCampPlayerNumByMapID(int iMapID)
References MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, MapInfoTable::iCampNum, MapInfoTable::iMaxPlayer.
const RenJiConditionsTable * TableMgr::GetRenjiConditionByID(int iID)
References m_akRenjiVec.
bool TableMgr::GetRaceHelpSkillTypes(int iTypeID, std::vector< int > &rakResult, std::vector< int > &indexResult)
References UnitTableMgr::Get, UnitTableMgr::GetUnitTable, UnitTable::iSkillList, m_akRaceHelperSkill.
bool TableMgr::GetRaceHelpMasterySkillTypes(int iTypeID, int iPetID, std::vector< int > &rakResult)
References PetTableMgr::Get, SelHeroTableMgr::Get, PetTableMgr::GetPetTable, SelHeroTableMgr::GetSelHeroTable, PetTable::iShop_list_4, PetTable::iShop_list_5, SelHeroTable::iTalent4, SelHeroTable::iTalent5, SelHeroTable::iTalent6, m_akRaceHeperMasteryRecom, SelHeroTable::uiLocation.
SeGlobalLanguage TableMgr::GetLanguage() const
References m_eLanguage.
void TableMgr::SetLanguage(SeGlobalLanguage eLanguage)
References m_eLanguage.
std::string TableMgr::GetText(int iKey)
Referenced by GlobalTableMgr::GetText, SystemPromptTableMgr::UpdateLanguadgeContent, AchievementTableMgr::UpdateLanguadgeContent, RankStageTableMgr::UpdateLanguadgeContent, PropagandaTableMgr::UpdateLanguadgeContent, HeroInfoTableMgr::UpdateLanguadgeContent, BattleTipsTableMgr::UpdateLanguadgeContent, MissionInfoTableMgr::UpdateLanguadgeContent, SkillTipsTableMgr::UpdateLanguadgeContent, SelHeroTableMgr::UpdateLanguadgeContent, MapInfoTableMgr::UpdateLanguadgeContent, UnitTableMgr::UpdateLanguadgeContent, ItemTableMgr::UpdateLanguadgeContent.
const std::string & TableMgr::GetText(const std::string &sKey)
References LanguageTable::akLanguage, LanguageTableMgr::Get, LanguageTableMgr::GetLanguageTable, m_eLanguage.
SeGlobalLanguage TableMgr::GetSoundLanguage() const
References m_eSoundLanguage.
void TableMgr::SetSoundLanguage(SeGlobalLanguage eLanguage)
References m_eSoundLanguage.
std::string TableMgr::GetVoiceInfo(const char *pcAudioInfoStr)
References VoiceTableMgr::Get, VoiceTableMgr::GetVoiceTable, VoiceTable::kContent, VoiceTable::kContent_English, m_eSoundLanguage, SGL_EN_US, SGL_ZH_CN.
const std::vector< std::string > & TableMgr::GetModelResByUnit(int iUnitTypeID)
References m_akUnit2Model.
const std::vector< std::string > & TableMgr::GetVoiceResByUnit(int iUnitTypeID)
References m_akUnit2Voice.
void TableMgr::GetActionResVecAll(std::vector< std::string > &vec)
References ModelResTable::bActionRes, ModelResTableMgr::Get, ModelResTableMgr::GetModelResTableMap, ModelResTable::kPath.
void TableMgr::GetActionResVec(std::vector< std::string > &vec, std::set< int > PreLoadHeroVec)
References ModelResTable::bActionRes, ModelResTableMgr::Get, ModelResTableMgr::GetModelResTableMap, ModelResTable::kPath, ModelResTable::uiOwner.
std::vector< std::string > TableMgr::GetPreLoadRes(E_MODELRESTABLE_PRELOADLEVEL eLevel)
References VoiceTableMgr::Get, ModelResTableMgr::Get, ModelResTableMgr::GetModelResTableMap, VoiceTableMgr::GetVoiceTableMap, VoiceTable::iPreLoad, ModelResTable::iPreLoad, VoiceTable::kPreLoadContent, ModelResTable::kPreLoadPath.
void TableMgr::GetAllCanSelHeroSet(std::vector< int > &kHeroSet)
References SelHeroTableMgr::Get, SelHeroTableMgr::GetSelHeroTableMap, SelHeroTable::iOpen, SelHeroTable::uiUnitID.
void TableMgr::SetTableLoader(TableLoader *pkTableLoader)
References m_pkLoader.
TableLoader * TableMgr::GetTableLoader()
References m_pkLoader.
Referenced by KillBountyTableMgr::Load, AppendGroupTableMgr::Load, AvatarShopTableMgr::Load, TaskRecomTableMgr::Load, MapShopResTableMgr::Load, ChoiceItemTableMgr::Load, AddtionalTableMgr::Load, AvatarModelTableMgr::Load, RaceTextTableMgr::Load, RandomNameTableMgr::Load, SystemPromptTableMgr::Load, UnitHeadAreaTableMgr::Load, LevelTableMgr::Load, AttackArmorRatioTableMgr::Load, EffectSwitchTableMgr::Load, LanguageTableMgr::Load, DressTableMgr::Load, RacehelpTableMgr::Load, AITableMgr::Load, AchievementTableMgr::Load, AIPrioTableMgr::Load, AvatarAnimationTableMgr::Load, HorseTableMgr::Load, VoiceTableMgr::Load, PresetShopTableMgr::Load, IndexofferTableMgr::Load, AvatarEffectTableMgr::Load, AcSystemTableMgr::Load, AccountLevelTableMgr::Load, UpgradeCostTableMgr::Load, ChanceTableMgr::Load, AppendCostTableMgr::Load, PetTableMgr::Load, SearchChoiceTableMgr::Load, RenJiTableMgr::Load, ItemComposeTableMgr::Load, CreepTowerGrowthTableMgr::Load, RankStageTableMgr::Load, FreeHeroesTableMgr::Load, LeagueRankTableMgr::Load, ShopTableMgr::Load, PropagandaTableMgr::Load, DecomposeTableMgr::Load, MapMiscTableMgr::Load, ModelResTableMgr::Load, RenJiActionsTableMgr::Load, RenJiCustomDataTableMgr::Load, HeroInfoTableMgr::Load, StarWheelTableMgr::Load, RacedropTableMgr::Load, RackTableMgr::Load, BufferTableMgr::Load, BattleTipsTableMgr::Load, MissionInfoTableMgr::Load, PVERuleTableMgr::Load, VideoTagTableMgr::Load, AppendSkillPRTableMgr::Load, RaceStaMissionTableMgr::Load, RenJiConditionsTableMgr::Load, AvatarTableMgr::Load, MapsInfoTableMgr::Load, AppendSkillTableMgr::Load, SelHeroTableMgr::Load, ItemExchangeTableMgr::Load, TaskInfoTableMgr::Load, AchievementTaskTableMgr::Load, MapInfoTableMgr::Load, StrengthenTableMgr::Load, UnitTableMgr::Load, ItemTableMgr::Load, TownItemTableMgr::Load, SkillTableMgr::LoadSkillFile.
int TableMgr::GetWishBuyID(int Order)
References WishBuyOrderVec.
const std::vector< unsigned int > & TableMgr::GetWishAttrItems(unsigned int ReelID)
References ItemReelMap.
const TaskInfoTable * TableMgr::GetTaskInfo(unsigned int dwTaskID)
References TaskInfoTableMgr::Get, TaskInfoTableMgr::GetTaskInfoTable.
const std::vector< unsigned int > * TableMgr::GetTaskIDInfo(unsigned int dwTaskID, unsigned int uiType)
References m_TaskTypeID, TASKINFO_TYPE_RONGYU, TASKINFO_TYPE_SHENGCHANG, TASKINFO_TYPE_YINGXIONG, TASKINFO_TYPE_ZHANYI, TASKINFO_TYPE_ZHUXIAN.
bool TableMgr::IsFirstWinTask(unsigned int dwTaskID)
References m_TaskTypeID, TASKINFO_TYPE_SHENGCHANG.
unsigned int TableMgr::GetNextMainTaskID(unsigned int dwTaskID)
References GetFirstDailyTaskID, m_MainTaskPre, TASKINFO_TYPE_ZHUXIAN.
Referenced by TaskMgr::GetMainTaskNextTask.
void TableMgr::GetDailyTaskIDList(E_TASKINFOTABLE_TYPE eType, VTaskID &vID)
References m_TaskTypeID, TASKINFO_TYPE_RONGYU, TASKINFO_TYPE_SHENGCHANG, TASKINFO_TYPE_YINGXIONG, TASKINFO_TYPE_ZHANYI.
Referenced by TaskMgr::GetDailyTaskNextTask, TaskMgr::GetWinTaskNextTask.
unsigned int TableMgr::GetFirstDailyTaskID(E_TASKINFOTABLE_TYPE eType)
References m_TaskTypeID, TASKINFO_TYPE_RONGYU, TASKINFO_TYPE_SHENGCHANG, TASKINFO_TYPE_YINGXIONG, TASKINFO_TYPE_ZHANYI, TASKINFO_TYPE_ZHUXIAN.
Referenced by GetNextMainTaskID, TaskMgr::GetWinTaskNextTask.
void TableMgr::LoadAchieveInfo()
References ACHIEVE_TASK_MAP_LIST_LENGTH, AchieveTypeInfo::AddMapID, AchievementTaskTableMgr::Get, AchievementTaskTableMgr::GetAchievementTaskTableMap, AchievementTaskTable::iMapList, AchievementTaskTable::iValue_Number, m_AchieveGroupIDMap, AchievementTaskTable::uiCondition, AchievementTaskTable::uiGameType, AchievementTaskTable::uiTask_ID, AchievementTaskTable::uiTaskgroups.
const AchieveTypeInfo * TableMgr::GetAchieveInfo(int iGroupID)
References m_AchieveGroupIDMap.
void TableMgr::InitHeroPosIndex()
References SelHeroTableMgr::Get, SelHeroTableMgr::GetSelHeroTableMap, SelHeroTable::iOpen, m_akHeroID2PosIndex, m_akPosIndex2HeroID.
Referenced by InitData.
void TableMgr::InitPetPosIndex()
References PetTableMgr::Get, PetTableMgr::GetPetTableMap, m_akPetID2PosIndex, m_akPosIndex2PetID.
Referenced by InitData.
void TableMgr::InitHorsePosIndex()
References HorseTableMgr::Get, HorseTableMgr::GetHorseTableMap, m_akHorseID2PosIndex, m_akPosIndex2HorseID.
Referenced by InitData.
void TableMgr::InitTaskList()
References TaskInfoTableMgr::Get, TaskInfoTableMgr::GetTaskInfoTableMap, m_MainTaskPre, m_TaskTypeID, TASKINFO_TRIGGERTYPE_QIANZHI, TASKINFO_TYPE_ZHUXIAN, TaskInfoTable::uiPreconditionTaskID, TaskInfoTable::uiTaskID, TaskInfoTable::uiTriggerType, TaskInfoTable::uiType.
Referenced by InitData.
void TableMgr::InitCreateSightUnit()
References UnitTableMgr::Get, UnitTableMgr::GetUnitTableMap, m_mapCreateSightUnits.
Referenced by InitData.
void TableMgr::InitRenjiCondition()
References RenJiConditionsTableMgr::Get, RenJiConditionsTableMgr::GetRenJiConditionsTableMap, m_akRenjiVec.
Referenced by InitData.
void TableMgr::InitModelRes()
References ModelResTableMgr::Get, ModelResTableMgr::GetModelResTableMap, ModelResTable::kPreLoadPath, m_akUnit2Model, ModelResTable::uiOwner.
Referenced by InitData.
void TableMgr::InitVoiceRes()
References VoiceTableMgr::Get, VoiceTableMgr::GetVoiceTableMap, VoiceTable::kPreLoadContent, m_akUnit2Voice, VoiceTable::uiOwner.
Referenced by InitData.
void TableMgr::InitRaceHelperRes()
References RacehelpTableMgr::Get, RacehelpTableMgr::GetRacehelpTableMap, RacehelpTable::kArcherRecom, RacehelpTable::kMageRecom, RacehelpTable::kMasteryRecom, RacehelpTable::kSkillRecom, RacehelpTable::kTankRecom, m_akRaceHelperSkill, m_akRaceHeperMasteryRecom, SELHERO_LOCATION_ARCHER, SELHERO_LOCATION_MAGE, SELHERO_LOCATION_TANK, SplitTableStr.
Referenced by InitData.
void TableMgr::InitWishBuyOrder()
References ChoiceItemTableMgr::Get, ChoiceItemTableMgr::GetChoiceItemTableMap, WishBuyOrderVec.
Referenced by InitData.
void TableMgr::InitReelMap()
References ItemComposeTableMgr::Get, ItemComposeTableMgr::GetItemComposeTableMap, ItemReelMap.
Referenced by InitData.