RandomNameTableMgr
std::map<unsigned int,RandomNameTable*> RandomNameTableMgr::m_kRandomNameTableMap
Referenced by FillData, GetRandomNameTable, GetRandomNameTableMap, GetRandomNameTableVec, ~RandomNameTableMgr.
RandomNameTableMgr * RandomNameTableMgr::m_pkRandomNameTableMgr
Referenced by Get, ReLoad.
RandomNameTableMgr * RandomNameTableMgr::Get()
References m_pkRandomNameTableMgr, RandomNameTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
RandomNameTableMgr * RandomNameTableMgr::ReLoad()
References Get, m_pkRandomNameTableMgr.
Referenced by TableMgr::ReloadTable.
RandomNameTableMgr::RandomNameTableMgr()
References Load.
Referenced by Get.
RandomNameTableMgr::~RandomNameTableMgr()
References m_kRandomNameTableMap.
const RandomNameTable * RandomNameTableMgr::GetRandomNameTable(unsigned int iTypeID)
References m_kRandomNameTableMap.
const std::map< unsigned int, RandomNameTable * > & RandomNameTableMgr::GetRandomNameTableMap()
References m_kRandomNameTableMap.
TableResArray RandomNameTableMgr::GetRandomNameTableVec()
References m_kRandomNameTableMap, TableResArray::pushBack.
bool RandomNameTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RandomNameTableMgr.
void RandomNameTableMgr::FillData(RandomNameTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RandomNameTable::ksName1, RandomNameTable::ksName2, RandomNameTable::ksName3, m_kRandomNameTableMap, RandomNameTable::uiUnitID.
Referenced by Load.