RacedropTableMgr
std::map<unsigned int,RacedropTable*> RacedropTableMgr::m_kRacedropTableMap
Referenced by FillData, GetRacedropTable, GetRacedropTableMap, GetRacedropTableVec, ~RacedropTableMgr.
RacedropTableMgr * RacedropTableMgr::m_pkRacedropTableMgr
Referenced by Get, ReLoad.
RacedropTableMgr * RacedropTableMgr::Get()
References m_pkRacedropTableMgr, RacedropTableMgr.
Referenced by TableMgr::GetAllMapMissionID, BlockServer::GetRaceDropChanceID, TableMgr::LoadTable, ReLoad.
RacedropTableMgr * RacedropTableMgr::ReLoad()
References Get, m_pkRacedropTableMgr.
Referenced by TableMgr::ReloadTable.
RacedropTableMgr::RacedropTableMgr()
References Load.
Referenced by Get.
RacedropTableMgr::~RacedropTableMgr()
References m_kRacedropTableMap.
const RacedropTable * RacedropTableMgr::GetRacedropTable(unsigned int iTypeID)
References m_kRacedropTableMap.
const std::map< unsigned int, RacedropTable * > & RacedropTableMgr::GetRacedropTableMap()
References m_kRacedropTableMap.
Referenced by TableMgr::GetAllMapMissionID, BlockServer::GetRaceDropChanceID.
TableResArray RacedropTableMgr::GetRacedropTableVec()
References m_kRacedropTableMap, TableResArray::pushBack.
bool RacedropTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RacedropTableMgr.
void RacedropTableMgr::FillData(RacedropTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RacedropTable::iAddAccountExpAward, RacedropTable::iAddGoldAward, RacedropTable::iAddHeroExpAward, RacedropTable::iAddHeroPetAward, RacedropTable::iAddMountExpAward, RacedropTable::iBasicAccountExpAward, RacedropTable::iBasicGoldAward, RacedropTable::iBasicHeroExpAward, RacedropTable::iBasicMountExpAward, RacedropTable::iBasicPetExpAward, RacedropTable::iCrownAward, RacedropTable::iRefValueA, RacedropTable::kComment, RacedropTable::kDesc, m_kRacedropTableMap, RacedropTable::uiChanceID, RacedropTable::uiDifficulty, RacedropTable::uiMapID, RacedropTable::uiPrizeCond, RacedropTable::uiTypeID.
Referenced by Load.