SkillTipsTableMgr
std::map<unsigned int,SkillTipsTable*> SkillTipsTableMgr::m_kSkillTipsTableMap
Referenced by GetSkillTipsTableMap, GetSkillTipsTableVec, UpdateLanguadgeContent.
std::set<unsigned int> SkillTipsTableMgr::m_kSimpleDescFormatFlag
SkillTipsTableMgr * SkillTipsTableMgr::m_pkSkillTipsTableMgr
Referenced by Get, ReLoad.
SkillTipsTableMgr * SkillTipsTableMgr::Get()
References m_pkSkillTipsTableMgr, SkillTipsTableMgr.
Referenced by GlobalTableMgr::GetSkillTipsTable, TableMgr::LoadTable, ReLoad, TableMgr::UpdateLanguageContent.
SkillTipsTableMgr * SkillTipsTableMgr::ReLoad()
References Get, m_pkSkillTipsTableMgr.
Referenced by TableMgr::ReloadTable.
SkillTipsTableMgr::SkillTipsTableMgr()
Referenced by Get.
SkillTipsTableMgr::~SkillTipsTableMgr()
const SkillTipsTable* SkillTipsTableMgr::GetSkillTipsTable(unsigned int iTypeID)
Referenced by GlobalTableMgr::GetSkillTipsTable.
const std::map< unsigned int, SkillTipsTable * > & SkillTipsTableMgr::GetSkillTipsTableMap()
References m_kSkillTipsTableMap.
TableResArray SkillTipsTableMgr::GetSkillTipsTableVec()
References m_kSkillTipsTableMap, TableResArray::pushBack.
void SkillTipsTableMgr::EvalFormatElement(SkillTipsFormatElement &ele)
void SkillTipsTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, SkillTipsTable::kName_China, SkillTipsTable::kName_ChinaKey, SkillTipsTable::kSimpleDesc, SkillTipsTable::kSimpleDescKey, SkillTipsTable::kskillDesc, SkillTipsTable::kskillDescKey, SkillTipsTable::kTips1, SkillTipsTable::kTips1Key, SkillTipsTable::kTips2, SkillTipsTable::kTips2Key, SkillTipsTable::kTips3, SkillTipsTable::kTips3Key, SkillTipsTable::kTips4, SkillTipsTable::kTips4Key, SkillTipsTable::kTips5, SkillTipsTable::kTips5Key, SkillTipsTable::kTips6, SkillTipsTable::kTips6Key, m_kSkillTipsTableMap.
Referenced by TableMgr::UpdateLanguageContent.
bool SkillTipsTableMgr::Load()
void SkillTipsTableMgr::FillData(SkillTipsTable *row, TiXmlElement *element)