TeMD5Check
BYTE TeMD5Check::m_abyBuffer[64][64]
Referenced by BeginMD5, GetMD5, TeMD5Check, Update.
UINT TeMD5Check::m_auiCount[2][2]
Referenced by BeginMD5, EndMD5, GetMD5, TeMD5Check, Update.
UINT TeMD5Check::m_auiMD5[4][4]
Referenced by BeginMD5, EndMD5, GetMD5, TeMD5Check, Transform.
TeMD5Check::TeMD5Check()
References m_abyBuffer, m_auiCount, m_auiMD5, MD5_INIT_STATE_0, MD5_INIT_STATE_1, MD5_INIT_STATE_2, MD5_INIT_STATE_3.
unsigned char * TeMD5Check::GetMD5(BYTE *pbyData, int iSize)
References DWordToByte, m_abyBuffer, m_auiCount, m_auiMD5, MD5_INIT_STATE_0, MD5_INIT_STATE_1, MD5_INIT_STATE_2, MD5_INIT_STATE_3, s_abyPaddin, Update.
Referenced by GetMD5.
void TeMD5Check::BeginMD5(void)
References m_abyBuffer, m_auiCount, m_auiMD5, MD5_INIT_STATE_0, MD5_INIT_STATE_1, MD5_INIT_STATE_2, MD5_INIT_STATE_3.
void TeMD5Check::Update(BYTE *Input, UINT uiLen)
References m_abyBuffer, m_auiCount, Transform.
Referenced by EndMD5, GetMD5.
unsigned char * TeMD5Check::EndMD5(void)
References DWordToByte, m_auiCount, m_auiMD5, s_abyPaddin, Update.
DWORD TeMD5Check::RotateLeft(DWORD x, int n)
void TeMD5Check::FF(DWORD &A, DWORD B, DWORD C, DWORD D, DWORD X, DWORD S, DWORD T)
Referenced by Transform.
void TeMD5Check::GG(DWORD &A, DWORD B, DWORD C, DWORD D, DWORD X, DWORD S, DWORD T)
Referenced by Transform.
void TeMD5Check::HH(DWORD &A, DWORD B, DWORD C, DWORD D, DWORD X, DWORD S, DWORD T)
Referenced by Transform.
void TeMD5Check::II(DWORD &A, DWORD B, DWORD C, DWORD D, DWORD X, DWORD S, DWORD T)
Referenced by Transform.
void TeMD5Check::Transform(BYTE Block[64])
References ByteToDWord, FF, GG, HH, II, m_auiMD5, MD5_S11, MD5_S12, MD5_S13, MD5_S14, MD5_S21, MD5_S22, MD5_S23, MD5_S24, MD5_S31, MD5_S32, MD5_S33, MD5_S34, MD5_S41, MD5_S42, MD5_S43, MD5_S44, MD5_T01, MD5_T02, MD5_T03, MD5_T04, MD5_T05, MD5_T06, MD5_T07, MD5_T08, MD5_T09, MD5_T10, MD5_T11, MD5_T12, MD5_T13, MD5_T14, MD5_T15, MD5_T16, MD5_T17, MD5_T18, MD5_T19, MD5_T20, MD5_T21, MD5_T22, MD5_T23, MD5_T24, MD5_T25, MD5_T26, MD5_T27, MD5_T28, MD5_T29, MD5_T30, MD5_T31, MD5_T32, MD5_T33, MD5_T34, MD5_T35, MD5_T36, MD5_T37, MD5_T38, MD5_T39, MD5_T40, MD5_T41, MD5_T42, MD5_T43, MD5_T44, MD5_T45, MD5_T46, MD5_T47, MD5_T48, MD5_T49, MD5_T50, MD5_T51, MD5_T52, MD5_T53, MD5_T54, MD5_T55, MD5_T56, MD5_T57, MD5_T58, MD5_T59, MD5_T60, MD5_T61, MD5_T62, MD5_T63, MD5_T64.
Referenced by Update.
void TeMD5Check::DWordToByte(BYTE *Output, UINT *Input, UINT nLength)
Referenced by EndMD5, GetMD5.
void TeMD5Check::ByteToDWord(DWORD *Output, BYTE *Input, UINT nLength)
Referenced by Transform.