AchievementTableMgr
std::map<unsigned int,AchievementTable*> AchievementTableMgr::m_kAchievementTableMap
Referenced by FillData, GetAchievementTable, GetAchievementTableMap, GetAchievementTableVec, UpdateLanguadgeContent, ~AchievementTableMgr.
AchievementTableMgr * AchievementTableMgr::m_pkAchievementTableMgr
Referenced by Get, ReLoad.
AchievementTableMgr * AchievementTableMgr::Get()
References AchievementTableMgr, m_pkAchievementTableMgr.
Referenced by GlobalTableMgr::GetAchievementTable, GlobalTableMgr::GetAchievementTableMap, TableMgr::LoadTable, ReLoad, TableMgr::UpdateLanguageContent.
AchievementTableMgr * AchievementTableMgr::ReLoad()
References Get, m_pkAchievementTableMgr.
Referenced by TableMgr::ReloadTable.
AchievementTableMgr::AchievementTableMgr()
References Load.
Referenced by Get.
AchievementTableMgr::~AchievementTableMgr()
References m_kAchievementTableMap.
const AchievementTable * AchievementTableMgr::GetAchievementTable(unsigned int iTypeID)
References m_kAchievementTableMap.
Referenced by GlobalTableMgr::GetAchievementTable.
const std::map< unsigned int, AchievementTable * > & AchievementTableMgr::GetAchievementTableMap()
References m_kAchievementTableMap.
Referenced by GlobalTableMgr::GetAchievementTableMap.
TableResArray AchievementTableMgr::GetAchievementTableVec()
References m_kAchievementTableMap, TableResArray::pushBack.
void AchievementTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, AchievementTable::kDescription, AchievementTable::kDescription2, AchievementTable::kDescription2Key, AchievementTable::kDescriptionKey, AchievementTable::kName, AchievementTable::kNameDescription, AchievementTable::kNameDescriptionKey, AchievementTable::kNameKey, m_kAchievementTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool AchievementTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by AchievementTableMgr.
void AchievementTableMgr::FillData(AchievementTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AchievementTable::iExe, AchievementTable::kDescription2Key, AchievementTable::kDescriptionKey, AchievementTable::kNameDescriptionKey, AchievementTable::kNameKey, m_kAchievementTableMap, AchievementTable::uiItemTypeID, AchievementTable::uiLvMax.
Referenced by Load.