AvatarModelTableMgr
std::map<unsigned int,AvatarModelTable*> AvatarModelTableMgr::m_kAvatarModelTableMap
Referenced by FillData, GetAvatarModelTable, GetAvatarModelTableMap, GetAvatarModelTableVec, ~AvatarModelTableMgr.
AvatarModelTableMgr * AvatarModelTableMgr::m_pkAvatarModelTableMgr
Referenced by Get, ReLoad.
AvatarModelTableMgr * AvatarModelTableMgr::Get()
References AvatarModelTableMgr, m_pkAvatarModelTableMgr.
Referenced by GlobalTableMgr::GetAvatarModelTable, GlobalTableMgr::GetAvatarModelTableMap, ReLoad.
AvatarModelTableMgr * AvatarModelTableMgr::ReLoad()
References Get, m_pkAvatarModelTableMgr.
Referenced by TableMgr::ReloadTable.
AvatarModelTableMgr::AvatarModelTableMgr()
References Load.
Referenced by Get.
AvatarModelTableMgr::~AvatarModelTableMgr()
References m_kAvatarModelTableMap.
const AvatarModelTable * AvatarModelTableMgr::GetAvatarModelTable(unsigned int iTypeID)
References m_kAvatarModelTableMap.
Referenced by GlobalTableMgr::GetAvatarModelTable.
const std::map< unsigned int, AvatarModelTable * > & AvatarModelTableMgr::GetAvatarModelTableMap()
References m_kAvatarModelTableMap.
Referenced by GlobalTableMgr::GetAvatarModelTableMap.
TableResArray AvatarModelTableMgr::GetAvatarModelTableVec()
References m_kAvatarModelTableMap, TableResArray::pushBack.
bool AvatarModelTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AvatarModelTableMgr.
void AvatarModelTableMgr::FillData(AvatarModelTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AvatarModelTable::kNameTips, AvatarModelTable::kResPath, AvatarModelTable::kWeaponPoint, m_kAvatarModelTableMap, AvatarModelTable::uiAvatarModelID.
Referenced by Load.