SeXmlBase
@47
@48
friend class SeXmlNode
friend class SeXmlElement
friend class SeXmlDocument
const int SeXmlBase::utf8ByteTable[256]
Referenced by GetChar, SeXmlParsingData::Stamp.
const char * SeXmlBase::errorString[SeXml_ERROR_STRING_COUNT]
Referenced by SeXmlDocument::SetError.
SeXmlCursor SeXmlBase::location
Referenced by Column, SeXmlNode::CopyTo, SeXmlDocument::LoadFile, SeXmlAttribute::Parse, SeXmlElement::Parse, SeXmlComment::Parse, SeXmlText::Parse, SeXmlDeclaration::Parse, SeXmlUnknown::Parse, SeXmlDocument::Parse, Row.
void* SeXmlBase::userData
Field containing a generic user pointer.
Referenced by SeXmlNode::CopyTo, GetUserData, SetUserData.
SeXmlBase::Entity SeXmlBase::entity[NUM_ENTITY]
Referenced by EncodeString, GetEntity.
bool SeXmlBase::condenseWhiteSpace
Referenced by IsWhiteSpaceCondensed, ReadText, SetCondenseWhiteSpace.
SeXmlBase::SeXmlBase()
virtual SeXmlBase::~SeXmlBase()
virtual void SeXmlBase::Print(FILE *cfile, int depth) const =0
All SeXml classes can print themselves to a filestream or the string class (SeXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.This is a formatted print, and will insert tabs and newlines.(For an unformatted stream, use the << operator.)
Referenced by SeXmlElement::Print.
int SeXmlBase::Row() const
Return the position, in the original source file, of this node or attribute. The row and column are 1-based. (That is the first row and first column is 1,1). If the returns values are 0 or less, then the parser does not have a row and column value.Generally, the row and column value will be set when the SeXmlDocument::Load(), SeXmlDocument::LoadFile(), or any SeXmlNode::Parse() is called. It will NOT be set when the DOM was created from operator>>.The values reflect the initial load. Once the DOM is modified programmatically (by adding or changing nodes and attributes) the new values will NOT update to reflect changes in the document.There is a minor performance cost to computing the row and column. Computation can be disabled if SeXmlDocument::SetTabSize() is called with 0 as the value.SeXmlDocument::SetTabSize()
References location, SeXmlCursor::row.
int SeXmlBase::Column() const
See Row()
References SeXmlCursor::col, location.
void SeXmlBase::SetUserData(void *user)
Set a pointer to arbitrary user data.
References userData.
void* SeXmlBase::GetUserData()
Get a pointer to arbitrary user data.
References userData.
const void* SeXmlBase::GetUserData() const
Get a pointer to arbitrary user data.
References userData.
virtual const char* SeXmlBase::Parse(const char *p, SeXmlParsingData *data, SeXmlEncoding encoding)=0
Referenced by operator>>, SeXmlDocument::Parse, SeXmlElement::ReadValue.
static void SeXmlBase::SetCondenseWhiteSpace(bool condense)
The world does not agree on whether white space should be kept or not. In order to make everyone happy, these global, static functions are provided to set whether or not SeXml will condense all white space into a single space or not. The default is to condense. Note changing this value is not thread safe.
References condenseWhiteSpace.
static bool SeXmlBase::IsWhiteSpaceCondensed()
Return the current white space setting.
References condenseWhiteSpace.
Referenced by SeXmlElement::ReadValue.
void SeXmlBase::EncodeString(const SeXml_STRING &str, SeXml_STRING *out)
Expands entities in a string. Note this should not contian the tag's '<', '>', etc, or they will be transformed into entities!
References entity, SeXml_SNPRINTF.
Referenced by SeXmlAttribute::Print, SeXmlText::Print, SeXmlPrinter::Visit.
const char * SeXmlBase::SkipWhiteSpace(const char *, SeXmlEncoding encoding)
References IsWhiteSpace, SeXml_ENCODING_UTF8, SeXml_UTF_LEAD_0, SeXml_UTF_LEAD_1, SeXml_UTF_LEAD_2.
Referenced by SeXmlNode::Identify, SeXmlAttribute::Parse, SeXmlElement::Parse, SeXmlComment::Parse, SeXmlDeclaration::Parse, SeXmlUnknown::Parse, SeXmlDocument::Parse, ReadText, SeXmlElement::ReadValue.
static bool SeXmlBase::IsWhiteSpace(char c)
Referenced by SeXmlText::Blank, IsWhiteSpace, SeXmlAttribute::Parse, SeXmlDeclaration::Parse, ReadText, SkipWhiteSpace, SeXmlElement::StreamIn, StreamWhiteSpace.
static bool SeXmlBase::IsWhiteSpace(int c)
References IsWhiteSpace.
bool SeXmlBase::StreamWhiteSpace(std::istream *in, SeXml_STRING *tag)
References IsWhiteSpace.
Referenced by SeXmlElement::StreamIn.
bool SeXmlBase::StreamTo(std::istream *in, int character, SeXml_STRING *tag)
Referenced by SeXmlDocument::StreamIn.
const char * SeXmlBase::ReadName(const char *p, SeXml_STRING *name, SeXmlEncoding encoding)
References IsAlpha, IsAlphaNum.
Referenced by SeXmlAttribute::Parse, SeXmlElement::Parse.
const char * SeXmlBase::ReadText(const char *in, SeXml_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, SeXmlEncoding encoding)
References condenseWhiteSpace, GetChar, IsWhiteSpace, SkipWhiteSpace, StringEqual.
Referenced by SeXmlAttribute::Parse, SeXmlText::Parse.
const char * SeXmlBase::GetEntity(const char *in, char *value, int *length, SeXmlEncoding encoding)
References SeXmlBase::Entity::chr, ConvertUTF32ToUTF8, entity, NUM_ENTITY, SeXml_ENCODING_UTF8.
Referenced by GetChar.
static const char* SeXmlBase::GetChar(const char *p, char *_value, int *length, SeXmlEncoding encoding)
References GetEntity, SeXml_ENCODING_UTF8, utf8ByteTable.
Referenced by ReadText.
bool SeXmlBase::StringEqual(const char *p, const char *endTag, bool ignoreCase, SeXmlEncoding encoding)
References ToLower.
Referenced by SeXmlNode::Identify, SeXmlElement::Parse, SeXmlComment::Parse, SeXmlText::Parse, SeXmlDeclaration::Parse, SeXmlDocument::Parse, SeXmlElement::QueryBoolAttribute, ReadText, SeXmlElement::ReadValue.
int SeXmlBase::IsAlpha(unsigned char anyByte, SeXmlEncoding encoding)
Referenced by SeXmlNode::Identify, ReadName.
int SeXmlBase::IsAlphaNum(unsigned char anyByte, SeXmlEncoding encoding)
Referenced by ReadName.
static int SeXmlBase::ToLower(int v, SeXmlEncoding encoding)
References SeXml_ENCODING_UTF8.
Referenced by StringEqual.
void SeXmlBase::ConvertUTF32ToUTF8(unsigned long input, char *output, int *length)
Referenced by GetEntity.
SeXmlBase::SeXmlBase(const SeXmlBase &)
void SeXmlBase::operator=(const SeXmlBase &base)