DefaultPlayerDataStrategy
SeDBTableIndex DefaultPlayerDataStrategy< TABLE, T >::getTableIndex()
DWord DefaultPlayerDataStrategy< TABLE, T, DATA >::getCacheInitID()
References PlayerDataStrategy::getCacheInitID.
void DefaultPlayerDataStrategy< TABLE, T, DATA >::rebuildMem()
References PlayerDataStrategy::rebuildMem.
int DefaultPlayerDataStrategy< TABLE, T, DATA >::saveToDB(SeDBPlayer &player)
References PlayerDataStrategy::saveToDB.
void DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert(SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
References PlayerDataStrategy::dataInsert.
Referenced by AchieveFinishMgr::AddFinishAchieve, TaskMgr::CharTaskInfoInsert, CItemMgr::notiChangeItem, EquipSchemaMgr::putOnEquip, RaceHeroMgr::saveData, RaceMapMgr::saveData, ActiveAvatarMgr::setActiveAvatar, HeroMgr::unlockHero, AchieveScheduleMgr::UpdateSchedule.
void DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate(SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
References PlayerDataStrategy::dataUpdate.
Referenced by TaskMgr::CharTaskInfoUpdate, CItemMgr::doExchangeItem, CItemMgr::doMoveItem, EquipSchemaMgr::fixData, HeroMgr::fixData, CItemMgr::notiChangeItem, EquipSchemaMgr::putOnEquip, HeroMgr::setAvatar, EquipSchemaMgr::takeOffEquip, AchieveFinishMgr::TryGetTaskReward, HeroMgr::unlockHero, RaceHeroMgr::updateData, RaceMapMgr::updateData, AchieveScheduleMgr::UpdateSchedule.
void DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete(SeDBPlayer &player, uint64_t dwlID)
References PlayerDataStrategy::dataDelete.
Referenced by ActiveAvatarMgr::fixData, EquipSchemaMgr::fixData, EquipSchemaMgr::loadData, CItemMgr::notiChangeItem, ActiveAvatarMgr::setActiveAvatar, EquipSchemaMgr::takeOffEquip.
void DefaultPlayerDataStrategy< TABLE, T, DATA >::onLoadData(SeDBPlayer &player, TeDBResSet &rkResSet)
References PlayerDataStrategy::onLoadData.
void DefaultPlayerDataStrategy< TABLE, T, DATA >::getRecordCount(SeDBPlayer &player, int &count)
References PlayerDataStrategy::getRecordCount.
void DefaultPlayerDataStrategy< TABLE, T, DATA >::getFieldData(SeDBPlayer &player, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1, void *&ret)
References PlayerDataStrategy::getFieldData.
int DefaultPlayerDataStrategy< TABLE, T, DATA >::safeDeleteDBPlayer(SeDBPlayer &player, DWord dwMagic)
References PlayerDataStrategy::safeDeleteDBPlayer.
SeDBTableIndex DefaultPlayerDataStrategy< TABLE, T, DATA >::getTableIndex()
DWord DefaultPlayerDataStrategy< TABLE, T, DATA >::getCacheInitID()
void DefaultPlayerDataStrategy< TABLE, T, DATA >::rebuildMem()
int DefaultPlayerDataStrategy< TABLE, T, DATA >::saveToDB(SeDBPlayer &player)
void DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert(SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
void DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate(SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
void DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete(SeDBPlayer &player, uint64_t dwlID)
void DefaultPlayerDataStrategy< TABLE, T, DATA >::onLoadData(SeDBPlayer &player, TeDBResSet &rkResSet)
void DefaultPlayerDataStrategy< TABLE, T, DATA >::getRecordCount(SeDBPlayer &player, int &count)
void DefaultPlayerDataStrategy< TABLE, T, DATA >::getFieldData(SeDBPlayer &player, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1, void *&ret)
int DefaultPlayerDataStrategy< TABLE, T, DATA >::safeDeleteDBPlayer(SeDBPlayer &player, DWord dwMagic)
SeDBTableIndex DefaultPlayerDataStrategy< TABLE, T, DATA >::getTableIndex()
void DefaultPlayerDataStrategy< TABLE, T >::onLoadData(SePlayer &player, SeBBL_SelectDataRet *pkData)
void DefaultPlayerDataStrategy< TABLE, T >::fixData(SePlayer &player)
References SePlayer::getDataMgr.
SeDBTableIndex DefaultPlayerDataStrategy< TABLE, T, DATA >::getTableIndex()
void DefaultPlayerDataStrategy< TABLE, T, DATA >::onLoadData(SePlayer &player, SeBBL_SelectDataRet *pkData)
void DefaultPlayerDataStrategy< TABLE, T, DATA >::fixData(SePlayer &player)