DecomposeTableMgr
std::map<unsigned int, DecomposeTable*> DecomposeTableMgr::m_kDecomposeTableMap
Referenced by FillData, GetDecomposeTable, GetDecomposeTableMap, GetDecomposeTableVec, ~DecomposeTableMgr.
std::map<int, DecomposeTable*> DecomposeTableMgr::m_kColorMap
Referenced by FillData, GetDecomposeTable.
DecomposeTableMgr * DecomposeTableMgr::m_pkDecomposeTableMgr
Referenced by Get, ReLoad.
DecomposeTableMgr * DecomposeTableMgr::Get()
References DecomposeTableMgr, m_pkDecomposeTableMgr.
Referenced by GlobalTableMgr::GetDecomposeTable, CItemMgr::ItemDepart, TableMgr::LoadTable, ReLoad.
DecomposeTableMgr * DecomposeTableMgr::ReLoad()
References Get, m_pkDecomposeTableMgr.
Referenced by TableMgr::ReloadTable.
DecomposeTableMgr::DecomposeTableMgr()
References Load.
Referenced by Get.
DecomposeTableMgr::~DecomposeTableMgr()
References m_kDecomposeTableMap.
const DecomposeTable * DecomposeTableMgr::GetDecomposeTable(unsigned int iTypeID)
References m_kDecomposeTableMap.
Referenced by GlobalTableMgr::GetDecomposeTable.
const std::map< unsigned int, DecomposeTable * > & DecomposeTableMgr::GetDecomposeTableMap()
References m_kDecomposeTableMap.
TableResArray DecomposeTableMgr::GetDecomposeTableVec()
References m_kDecomposeTableMap, TableResArray::pushBack.
Referenced by CItemMgr::ItemDepart.
const DecomposeTable * DecomposeTableMgr::GetDecomposeTable(int iColorLevel)
References m_kColorMap.
bool DecomposeTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by DecomposeTableMgr.
void DecomposeTableMgr::FillData(DecomposeTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, DecomposeTable::iItemCount1, DecomposeTable::iItemCount2, DecomposeTable::iItemCount3, DecomposeTable::iItemCount4, DecomposeTable::iItemCount5, m_kColorMap, m_kDecomposeTableMap, DecomposeTable::uiDecomposeItem1, DecomposeTable::uiDecomposeItem2, DecomposeTable::uiDecomposeItem3, DecomposeTable::uiDecomposeItem4, DecomposeTable::uiDecomposeItem5, DecomposeTable::uiQualityType, DecomposeTable::uiTypeID.
Referenced by Load.