SeRaceDataMgr
MapRaceData SeRaceDataMgr::m_kMapRaceData
Referenced by Clear, GetRaceData, PushHeroInfo, PushRaceData, UpdateRaceData, ~SeRaceDataMgr.
DWord SeRaceDataMgr::m_dwLastSendTime
Referenced by SeRaceDataMgr.
SeRaceDataMgr::SeRaceDataMgr(void)
References m_dwLastSendTime.
SeRaceDataMgr::~SeRaceDataMgr(void)
References m_kMapRaceData, SAFE_ARRAY_DELETE.
void SeRaceDataMgr::Clear(int iSeat=-1)
References m_kMapRaceData, SeLogicRaceData::ResetDataPos.
Referenced by SeThreadRaceMgr::PlayerRelink, SeSvrRace::SeSvrRace, UpdateRaceData.
void SeRaceDataMgr::UpdateRaceData(VSvrRacePlayer &rkRacePlayer, DWord dwServerTime, bool bForceSend=false)
References Clear, g_kRaceServer, GetRaceData, M_BeforeStartInverval, m_kMapRaceData, M_QDoMutiInterval_FN, RaceServer::OnSendPlayerRaceStream, SeLogInfo, SeLogicRaceData::SendHeroInfo.
Referenced by SeThreadRaceMgr::DelRace, SeThreadRaceMgr::UpdateRace.
bool SeRaceDataMgr::PushHeroInfo(int iSeat, char *pkData, int iSize)
References m_kMapRaceData, SeLogicRaceData::PushHeroInfo.
Referenced by SeThreadRaceMgr::PushGetHeroInfo.
bool SeRaceDataMgr::PushRaceData(int iSeat, DWord dwFrame, char *pkData, int iSize, bool bMustSend)
References m_kMapRaceData, SeLogicRaceData::PushData.
Referenced by SeThreadRaceMgr::PushRaceData.
char * SeRaceDataMgr::GetRaceData(int iSeat, int &riSize, bool bMustSend)
References SeLogicRaceData::GetRacePack, m_kMapRaceData.
Referenced by UpdateRaceData.
SeRaceDataMgr::SeRaceDataMgr(void)
SeRaceDataMgr::~SeRaceDataMgr(void)
void SeRaceDataMgr::Clear(int iSeat=-1)
void SeRaceDataMgr::UpdateRaceData(VSvrRacePlayer &rkRacePlayer, DWord dwServerTime, bool bForceSend=false)
bool SeRaceDataMgr::PushHeroInfo(int iSeat, char *pkData, int iSize)
bool SeRaceDataMgr::PushRaceData(int iSeat, DWord dwFrame, char *pkData, int iSize, bool bMustSend)
char* SeRaceDataMgr::GetRaceData(int iSeat, int &riSize, bool bMustSend)