RackTableMgr
std::map<unsigned int,RackTable*> RackTableMgr::m_kRackTableMap
Referenced by FillData, GetRackTable, GetRackTableMap, GetRackTableVec, ~RackTableMgr.
RackTableMgr * RackTableMgr::m_pkRackTableMgr
Referenced by Get, ReLoad.
RackTableMgr * RackTableMgr::Get()
References m_pkRackTableMgr, RackTableMgr.
Referenced by CShop::BuyItem, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold, GlobalTableMgr::GetRackMap, GlobalTableMgr::GetRackTable, CShop::GMModiItem, TableMgr::LoadTable, ReLoad.
RackTableMgr * RackTableMgr::ReLoad()
References Get, m_pkRackTableMgr.
Referenced by TableMgr::ReloadTable.
RackTableMgr::RackTableMgr()
References Load.
Referenced by Get.
RackTableMgr::~RackTableMgr()
References m_kRackTableMap.
const RackTable * RackTableMgr::GetRackTable(unsigned int iTypeID)
References m_kRackTableMap.
Referenced by CShop::BuyItem, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold, GlobalTableMgr::GetRackTable, CShop::GMModiItem.
const std::map< unsigned int, RackTable * > & RackTableMgr::GetRackTableMap()
References m_kRackTableMap.
Referenced by GlobalTableMgr::GetRackMap.
TableResArray RackTableMgr::GetRackTableVec()
References m_kRackTableMap, TableResArray::pushBack.
bool RackTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RackTableMgr.
void RackTableMgr::FillData(RackTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RackTable::fDiscount, RackTable::iRank, RackTable::iResetTime, RackTable::iRestrictionsCount, RackTable::iStockCount, RackTable::kItemTips, RackTable::kLanguageID, RackTable::kLargeIcon, RackTable::kName, RackTable::kSmallIcon, m_kRackTableMap, RackTable::uifeature, RackTable::uiItemID, RackTable::uiPrice1, RackTable::uiPrice2, RackTable::uiShopID, RackTable::uiToolControl, RackTable::uitype.
Referenced by Load.