SeThreadMsgMgr
Es::NormalLock SeThreadMsgMgr::m_kLock
Referenced by Empty, GetBuffSize, PopMsg, PushMsg.
int SeThreadMsgMgr::m_iBufSize
Referenced by Empty, ExpandBuffer, GetBuffSize, Initialize, PushMsg, SeThreadMsgMgr.
Byte* SeThreadMsgMgr::m_pbyBuffer
Referenced by Empty, ExpandBuffer, Initialize, PopMsg, PushMsg, SeThreadMsgMgr, ~SeThreadMsgMgr.
int SeThreadMsgMgr::m_iPushOffset
Referenced by Empty, ExpandBuffer, PopMsg, PushMsg, SeThreadMsgMgr.
int SeThreadMsgMgr::m_iPopOffset
Referenced by Empty, PopMsg, SeThreadMsgMgr.
SeMsgData SeThreadMsgMgr::m_kTemMsgData
Referenced by PopMsg, SeThreadMsgMgr.
int SeThreadMsgMgr::m_iCmdNum
Referenced by GetCmdNum, PopMsg, PushMsg, SeThreadMsgMgr.
SeThreadMsgMgr::SeThreadMsgMgr()
References m_iBufSize, m_iCmdNum, m_iPopOffset, m_iPushOffset, m_kTemMsgData, m_pbyBuffer.
SeThreadMsgMgr::~SeThreadMsgMgr()
References m_pbyBuffer.
bool SeThreadMsgMgr::Initialize(int iBaseBuffSize)
References m_iBufSize, m_pbyBuffer.
Referenced by SeLogThread::Initialize, DBServer::Initialize, RaceService::Initialize, WorldServer::Initialize, BlockServer::Initialize, RaceServer::InitializeRaceService.
bool SeThreadMsgMgr::PushMsg(void *pkData, int iSize)
References ExpandBuffer, SeThreadMsgHead::iSize, m_iBufSize, m_iCmdNum, m_iPushOffset, m_kLock, m_pbyBuffer, MemCpy.
Referenced by SeLogThread::PushLog, BlockServer::PushMsg, RaceService::PushMsg, RaceServer::PushRSMsg, WorldServer::PushWSMsg, DBServer::SendDBLog_SqlLog.
SeMsgData * SeThreadMsgMgr::PopMsg(void)
References SeMsgData::abyData, SeThreadMsgHead::iSize, SeMsgData::iSize, m_iCmdNum, m_iPopOffset, m_iPushOffset, m_kLock, m_kTemMsgData, m_pbyBuffer.
Referenced by SeLogThread::DoWork, BlockServer::Update, RaceService::UpdateRSCMsg, RaceServer::UpdateRSMsg, WorldServer::UpdateWSMsg, DBServer::WriteLogUpdate.
bool SeThreadMsgMgr::PopMsg(Byte *pkByte, int &riSize)
References SeThreadMsgHead::iSize, m_iCmdNum, m_iPopOffset, m_iPushOffset, m_kLock, m_pbyBuffer.
bool SeThreadMsgMgr::Empty(void)
References m_iBufSize, m_iPopOffset, m_iPushOffset, m_kLock, m_pbyBuffer.
int SeThreadMsgMgr::GetCmdNum()
References m_iCmdNum.
int SeThreadMsgMgr::GetBuffSize()
References m_iBufSize, m_kLock.
bool SeThreadMsgMgr::ExpandBuffer(int iSize)
References m_iBufSize, m_iPushOffset, m_pbyBuffer, SeLogDebug, SeLogError.
Referenced by PushMsg.