RenJiCustomDataTableMgr
std::map<unsigned int,RenJiCustomDataTable*> RenJiCustomDataTableMgr::m_kRenJiCustomDataTableMap
Referenced by FillData, GetRenJiCustomDataTable, GetRenJiCustomDataTableMap, GetRenJiCustomDataTableVec, ~RenJiCustomDataTableMgr.
RenJiCustomDataTableMgr * RenJiCustomDataTableMgr::m_pkRenJiCustomDataTableMgr
Referenced by Get, ReLoad.
RenJiCustomDataTableMgr * RenJiCustomDataTableMgr::Get()
References m_pkRenJiCustomDataTableMgr, RenJiCustomDataTableMgr.
Referenced by TableMgr::GetRenJiCustomValue, ReLoad.
RenJiCustomDataTableMgr * RenJiCustomDataTableMgr::ReLoad()
References Get, m_pkRenJiCustomDataTableMgr.
RenJiCustomDataTableMgr::RenJiCustomDataTableMgr()
References Load.
Referenced by Get.
RenJiCustomDataTableMgr::~RenJiCustomDataTableMgr()
References m_kRenJiCustomDataTableMap.
const RenJiCustomDataTable * RenJiCustomDataTableMgr::GetRenJiCustomDataTable(unsigned int iTypeID)
References m_kRenJiCustomDataTableMap.
Referenced by TableMgr::GetRenJiCustomValue.
const std::map< unsigned int, RenJiCustomDataTable * > & RenJiCustomDataTableMgr::GetRenJiCustomDataTableMap()
References m_kRenJiCustomDataTableMap.
TableResArray RenJiCustomDataTableMgr::GetRenJiCustomDataTableVec()
References m_kRenJiCustomDataTableMap, TableResArray::pushBack.
bool RenJiCustomDataTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RenJiCustomDataTableMgr.
void RenJiCustomDataTableMgr::FillData(RenJiCustomDataTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RenJiCustomDataTable::fValue, m_kRenJiCustomDataTableMap, RenJiCustomDataTable::uiType.
Referenced by Load.