SeReMgr
MLvl2VConstellID SeReMgr::m_kMConstellList
Referenced by InitStarWheelRes, RandGetConstellByLevel.
SeReMgr::SeReMgr()
SeReMgr::~SeReMgr()
bool SeReMgr::Initialize(void)
References InitStarWheelRes, TableMgr::LoadTable.
Referenced by WorldServer::Initialize, MatchServer::Initialize.
void SeReMgr::Finialize(void)
void SeReMgr::RandGenDayConstell(int &iConstellA, int &iConstellB)
References RandGetConstellByLevel, STARWHEEL_LEVEL_HIGH, STARWHEEL_LEVEL_LOW, STARWHEEL_LEVEL_MID.
Referenced by MatchServer::UpdateRaceBetInfo.
int SeReMgr::RandGetConstellByLevel(int iLevel)
References m_kMConstellList.
Referenced by RandGenDayConstell.
SeReMgr::SeReMgr()
SeReMgr::~SeReMgr()
bool SeReMgr::Initialize(void)
void SeReMgr::Finialize(void)
void SeReMgr::RandGenDayConstell(int &iConstellA, int &iConstellB)
int SeReMgr::RandGetConstellByLevel(int iLevel)
bool SeReMgr::InitStarWheelRes()
References StarWheelTableMgr::Get, StarWheelTableMgr::GetStarWheelTableMap, StarWheelTable::iOdds, m_kMConstellList, SeLogError, StarWheelTable::uiLevel.
Referenced by Initialize.
bool SeReMgr::InitStarWheelRes()