ChanceTableMgr
std::map<unsigned int,ChanceTable*> ChanceTableMgr::m_kChanceTableMap
Referenced by FillData, GetChanceTable, GetChanceTableMap, GetChanceTableVec, ~ChanceTableMgr.
ChanceTableMgr * ChanceTableMgr::m_pkChanceTableMgr
Referenced by Get, ReLoad.
ChanceTableMgr * ChanceTableMgr::Get()
References ChanceTableMgr, m_pkChanceTableMgr.
Referenced by GlobalTableMgr::GetChanceTableMap, SeResMgr::initializeRandBox, TableMgr::LoadTable, ReLoad.
ChanceTableMgr * ChanceTableMgr::ReLoad()
References Get, m_pkChanceTableMgr.
Referenced by TableMgr::ReloadTable.
ChanceTableMgr::ChanceTableMgr()
References Load.
Referenced by Get.
ChanceTableMgr::~ChanceTableMgr()
References m_kChanceTableMap.
const ChanceTable * ChanceTableMgr::GetChanceTable(unsigned int iTypeID)
References m_kChanceTableMap.
const std::map< unsigned int, ChanceTable * > & ChanceTableMgr::GetChanceTableMap()
References m_kChanceTableMap.
Referenced by GlobalTableMgr::GetChanceTableMap, SeResMgr::initializeRandBox.
TableResArray ChanceTableMgr::GetChanceTableVec()
References m_kChanceTableMap, TableResArray::pushBack.
bool ChanceTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by ChanceTableMgr.
void ChanceTableMgr::FillData(ChanceTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, ChanceTable::iNumbers, ChanceTable::iProbability, ChanceTable::iRandomMax, ChanceTable::iRandomMin, ChanceTable::kName, m_kChanceTableMap, ChanceTable::uiConnectTypeID, ChanceTable::uiOrgTypeID, ChanceTable::uiType, ChanceTable::uiTypeID.
Referenced by Load.