TiXmlDeclaration
TIXML_STRING TiXmlDeclaration::version
Referenced by CopyTo, Parse, Print, TiXmlDeclaration, Version.
TIXML_STRING TiXmlDeclaration::encoding
Referenced by CopyTo, Encoding, Parse, Print, TiXmlDeclaration.
TIXML_STRING TiXmlDeclaration::standalone
Referenced by CopyTo, Parse, Print, Standalone, TiXmlDeclaration.
TiXmlDeclaration::TiXmlDeclaration()
Construct an empty declaration.
Referenced by Clone.
TiXmlDeclaration::TiXmlDeclaration(const char *_version, const char *_encoding, const char *_standalone)
Construct.
References encoding, standalone, version.
TiXmlDeclaration::TiXmlDeclaration(const TiXmlDeclaration &copy)
References CopyTo.
void TiXmlDeclaration::operator=(const TiXmlDeclaration &copy)
References TiXmlNode::Clear, CopyTo.
virtual TiXmlDeclaration::~TiXmlDeclaration()
const char* TiXmlDeclaration::Version() const
Version. Will return an empty string if none was found.
References version.
const char* TiXmlDeclaration::Encoding() const
Encoding. Will return an empty string if none was found.
References encoding.
Referenced by TiXmlDocument::Parse.
const char* TiXmlDeclaration::Standalone() const
Is this a standalone document?
References standalone.
TiXmlNode * TiXmlDeclaration::Clone() const
Creates a copy of this Declaration and returns it.
References CopyTo, TiXmlDeclaration.
void TiXmlDeclaration::Print(FILE *cfile, int depth, TIXML_STRING *str) const
References encoding, standalone, version.
Referenced by Print, TiXmlPrinter::Visit.
virtual void TiXmlDeclaration::Print(FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.This is a formatted print, and will insert tabs and newlines.(For an unformatted stream, use the << operator.)
References Print.
const char * TiXmlDeclaration::Parse(const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
References TiXmlParsingData::Cursor, encoding, TiXmlNode::GetDocument, TiXmlBase::IsWhiteSpace, TiXmlBase::location, TiXmlAttribute::Parse, TiXmlDocument::SetError, TiXmlBase::SkipWhiteSpace, TiXmlParsingData::Stamp, standalone, TiXmlBase::StringEqual, TiXmlBase::TIXML_ERROR_PARSING_DECLARATION, TiXmlAttribute::Value, version.
virtual const TiXmlDeclaration* TiXmlDeclaration::ToDeclaration() const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlDeclaration* TiXmlDeclaration::ToDeclaration()
Cast to a more defined type. Will return null not of the requested type.
bool TiXmlDeclaration::Accept(TiXmlVisitor *visitor) const
Walk the XML tree visiting this node and all of its children.
References TiXmlVisitor::Visit.
void TiXmlDeclaration::CopyTo(TiXmlDeclaration *target) const
References TiXmlNode::CopyTo, encoding, standalone, version.
Referenced by Clone, operator=, TiXmlDeclaration.