AddtionalTableMgr
std::map<unsigned int,AddtionalTable*> AddtionalTableMgr::m_kAddtionalTableMap
Referenced by FillData, GetAddtionalTable, GetAddtionalTableMap, GetAddtionalTableVec, ~AddtionalTableMgr.
AddtionalTableMgr * AddtionalTableMgr::m_pkAddtionalTableMgr
Referenced by Get, ReLoad.
AddtionalTableMgr * AddtionalTableMgr::Get()
References AddtionalTableMgr, m_pkAddtionalTableMgr.
Referenced by AddtionalFunction::GetAddtionalTable, TableMgr::LoadTable, ReLoad.
AddtionalTableMgr * AddtionalTableMgr::ReLoad()
References Get, m_pkAddtionalTableMgr.
Referenced by TableMgr::ReloadTable.
AddtionalTableMgr::AddtionalTableMgr()
References Load.
Referenced by Get.
AddtionalTableMgr::~AddtionalTableMgr()
References m_kAddtionalTableMap.
const AddtionalTable * AddtionalTableMgr::GetAddtionalTable(unsigned int iTypeID)
References m_kAddtionalTableMap.
Referenced by AddtionalFunction::GetAddtionalTable.
const std::map< unsigned int, AddtionalTable * > & AddtionalTableMgr::GetAddtionalTableMap()
References m_kAddtionalTableMap.
TableResArray AddtionalTableMgr::GetAddtionalTableVec()
References m_kAddtionalTableMap, TableResArray::pushBack.
bool AddtionalTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AddtionalTableMgr.
void AddtionalTableMgr::FillData(AddtionalTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AddtionalTable::kAdditional0, AddtionalTable::kAdditional1, AddtionalTable::kAdditional2, m_kAddtionalTableMap, AddtionalTable::uiTypeID.
Referenced by Load.