CIntervalCloneFolderSet
const char * CIntervalCloneFolderSet::m_szFolderName
Referenced by FolderName.
CRC_ID CIntervalCloneFolderSet::m_FolderNameCRC
Referenced by FolderNameCRC.
PerformanceTiming::TConstIntervalCloneArray CIntervalCloneFolderSet::m_vIntervals
Referenced by AddInterval, Intervals.
CIntervalCloneFolderSet::CIntervalCloneFolderSet(const char *szName, CRC_ID folderNameCRC)
const char* CIntervalCloneFolderSet::FolderName() const
References m_szFolderName.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
CRC_ID CIntervalCloneFolderSet::FolderNameCRC() const
References m_FolderNameCRC.
void CIntervalCloneFolderSet::AddInterval(const PerformanceTiming::CIntervalClone *pInterval)
References m_vIntervals.
Referenced by BuildFolderSets.
const PerformanceTiming::TConstIntervalCloneArray& CIntervalCloneFolderSet::Intervals() const
References m_vIntervals.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
CIntervalCloneFolderSet::CIntervalCloneFolderSet(const char *szName, CRC_ID folderNameCRC)
const char* CIntervalCloneFolderSet::FolderName() const
References m_szFolderName.
CRC_ID CIntervalCloneFolderSet::FolderNameCRC() const
References m_FolderNameCRC.
void CIntervalCloneFolderSet::AddInterval(const PerformanceTiming::CIntervalClone *pInterval)
References m_vIntervals.
const PerformanceTiming::TConstIntervalCloneArray& CIntervalCloneFolderSet::Intervals() const
References m_vIntervals.
void CIntervalCloneFolderSet::BuildFolderSets(std::vector< CIntervalCloneFolderSet > &vFolderSets, PerformanceTiming::TIntervalCloneArray &vAllIntervals)
References AddInterval, PerformanceTiming::CIntervalClone::GetFolderName, PerformanceTiming::CIntervalClone::GetFolderNameCRC.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
static void CIntervalCloneFolderSet::BuildFolderSets(std::vector< CIntervalCloneFolderSet > &vFolderSets, PerformanceTiming::TIntervalCloneArray &vAllIntervals)