SeXmlAttributeSet
SeXmlAttribute SeXmlAttributeSet::sentinel
Referenced by Add, Find, First, Last, Remove, SeXmlAttributeSet, ~SeXmlAttributeSet.
SeXmlAttributeSet::SeXmlAttributeSet()
References SeXmlAttribute::next, SeXmlAttribute::prev, sentinel.
SeXmlAttributeSet::~SeXmlAttributeSet()
References SeXmlAttribute::next, SeXmlAttribute::prev, sentinel.
void SeXmlAttributeSet::Add(SeXmlAttribute *attribute)
References Find, SeXmlAttribute::Name, SeXmlAttribute::next, SeXmlAttribute::prev, sentinel, SeXml_STRING.
Referenced by FindOrCreate, SeXmlElement::Parse.
void SeXmlAttributeSet::Remove(SeXmlAttribute *attribute)
References SeXmlAttribute::next, SeXmlAttribute::prev, sentinel.
Referenced by SeXmlElement::ClearThis, SeXmlElement::RemoveAttribute.
const SeXmlAttribute* SeXmlAttributeSet::First() const
References SeXmlAttribute::next, sentinel.
Referenced by SeXmlElement::Accept, SeXmlElement::ClearThis, SeXmlElement::CopyTo, SeXmlElement::FirstAttribute, SeXmlElement::Print.
SeXmlAttribute* SeXmlAttributeSet::First()
References SeXmlAttribute::next, sentinel.
const SeXmlAttribute* SeXmlAttributeSet::Last() const
References SeXmlAttribute::prev, sentinel.
Referenced by SeXmlElement::LastAttribute.
SeXmlAttribute* SeXmlAttributeSet::Last()
References SeXmlAttribute::prev, sentinel.
SeXmlAttribute * SeXmlAttributeSet::Find(const char *_name) const
References SeXmlAttribute::next, sentinel.
Referenced by Add, SeXmlElement::Attribute, FindOrCreate, SeXmlElement::Parse, SeXmlElement::QueryBoolAttribute, SeXmlElement::QueryDoubleAttribute, SeXmlElement::QueryIntAttribute, SeXmlElement::QueryUnsignedAttribute, SeXmlElement::QueryValueAttribute, SeXmlElement::RemoveAttribute.
SeXmlAttribute * SeXmlAttributeSet::FindOrCreate(const char *_name)
References Add, Find, SeXmlAttribute::SetName.
Referenced by SeXmlElement::SetAttribute, SeXmlElement::SetDoubleAttribute.
SeXmlAttribute * SeXmlAttributeSet::Find(const std::string &_name) const
References SeXmlAttribute::next, sentinel.
SeXmlAttribute * SeXmlAttributeSet::FindOrCreate(const std::string &_name)
References Add, Find, SeXmlAttribute::SetName.
SeXmlAttributeSet::SeXmlAttributeSet(const SeXmlAttributeSet &)
void SeXmlAttributeSet::operator=(const SeXmlAttributeSet &)