VoiceTableMgr
std::map<unsigned int,VoiceTable*> VoiceTableMgr::m_kVoiceTableMap
Referenced by FillData, GetVoiceTable, GetVoiceTableMap, GetVoiceTableVec, ~VoiceTableMgr.
VoiceTableMgr * VoiceTableMgr::m_pkVoiceTableMgr
Referenced by Get, ReLoad.
VoiceTableMgr * VoiceTableMgr::Get()
References m_pkVoiceTableMgr, VoiceTableMgr.
Referenced by TableMgr::GetPreLoadRes, TableMgr::GetVoiceInfo, GlobalTableMgr::GetVoiceTable, GlobalTableMgr::GetVoiceTableMap, TableMgr::InitVoiceRes, TableMgr::LoadTable, ReLoad.
VoiceTableMgr * VoiceTableMgr::ReLoad()
References Get, m_pkVoiceTableMgr.
Referenced by TableMgr::ReloadTable.
VoiceTableMgr::VoiceTableMgr()
References Load.
Referenced by Get.
VoiceTableMgr::~VoiceTableMgr()
References m_kVoiceTableMap.
const VoiceTable * VoiceTableMgr::GetVoiceTable(unsigned int iTypeID)
References m_kVoiceTableMap.
Referenced by TableMgr::GetVoiceInfo, GlobalTableMgr::GetVoiceTable.
const std::map< unsigned int, VoiceTable * > & VoiceTableMgr::GetVoiceTableMap()
References m_kVoiceTableMap.
Referenced by TableMgr::GetPreLoadRes, GlobalTableMgr::GetVoiceTableMap, TableMgr::InitVoiceRes.
TableResArray VoiceTableMgr::GetVoiceTableVec()
References m_kVoiceTableMap, TableResArray::pushBack.
bool VoiceTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by VoiceTableMgr.
void VoiceTableMgr::FillData(VoiceTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, VoiceTable::iPreLoad, VoiceTable::kContent, VoiceTable::kContent_English, VoiceTable::kContent_FT, VoiceTable::kContent_Japanese, VoiceTable::kContent_Vientnam, VoiceTable::kDesc, VoiceTable::kPreLoadContent, VoiceTable::kSubSet, VoiceTable::kTopLayer, m_kVoiceTableMap, VoiceTable::uiKey, VoiceTable::uiOwner.
Referenced by Load.