BattleTipsTableMgr
std::map<unsigned int,BattleTipsTable*> BattleTipsTableMgr::m_kBattleTipsTableMap
Referenced by FillData, GetBattleTipsTable, GetBattleTipsTableMap, GetBattleTipsTableVec, UpdateLanguadgeContent, ~BattleTipsTableMgr.
BattleTipsTableMgr * BattleTipsTableMgr::m_pkBattleTipsTableMgr
Referenced by Get, ReLoad.
BattleTipsTableMgr * BattleTipsTableMgr::Get()
References BattleTipsTableMgr, m_pkBattleTipsTableMgr.
Referenced by GlobalTableMgr::GetBattleTipsTable, TableMgr::LoadTable, ReLoad, TableMgr::UpdateLanguageContent.
BattleTipsTableMgr * BattleTipsTableMgr::ReLoad()
References Get, m_pkBattleTipsTableMgr.
Referenced by TableMgr::ReloadTable.
BattleTipsTableMgr::BattleTipsTableMgr()
References Load.
Referenced by Get.
BattleTipsTableMgr::~BattleTipsTableMgr()
References m_kBattleTipsTableMap.
const BattleTipsTable * BattleTipsTableMgr::GetBattleTipsTable(unsigned int iTypeID)
References m_kBattleTipsTableMap.
Referenced by GlobalTableMgr::GetBattleTipsTable.
const std::map< unsigned int, BattleTipsTable * > & BattleTipsTableMgr::GetBattleTipsTableMap()
References m_kBattleTipsTableMap.
TableResArray BattleTipsTableMgr::GetBattleTipsTableVec()
References m_kBattleTipsTableMap, TableResArray::pushBack.
void BattleTipsTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, BattleTipsTable::kDesc, BattleTipsTable::kDescKey, m_kBattleTipsTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool BattleTipsTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by BattleTipsTableMgr.
void BattleTipsTableMgr::FillData(BattleTipsTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, BattleTipsTable::kDescKey, m_kBattleTipsTableMap, BattleTipsTable::uiID.
Referenced by Load.