TiXmlDocument
bool TiXmlDocument::error
Referenced by ClearError, CopyTo, Error, SetError.
int TiXmlDocument::errorId
Referenced by ClearError, ErrorId, SetError.
TIXML_STRING TiXmlDocument::errorDesc
Referenced by ClearError, CopyTo, ErrorDesc, SetError.
int TiXmlDocument::tabsize
Referenced by SetTabSize, TabSize, TiXmlDocument.
TiXmlCursor TiXmlDocument::errorLocation
Referenced by ClearError, ErrorCol, ErrorRow, SetError.
bool TiXmlDocument::useMicrosoftBOM
Referenced by Parse, SaveFile, TiXmlDocument.
TiXmlDocument::TiXmlDocument()
Create an empty document, that has no name.
References ClearError, tabsize, useMicrosoftBOM.
Referenced by Clone.
TiXmlDocument::TiXmlDocument(const char *documentName)
Create a document with a name. The name of the document is also the filename of the xml.
References ClearError, tabsize, useMicrosoftBOM, TiXmlNode::value.
TiXmlDocument::TiXmlDocument(const TiXmlDocument &copy)
References CopyTo.
void TiXmlDocument::operator=(const TiXmlDocument &copy)
References TiXmlNode::Clear, CopyTo.
virtual TiXmlDocument::~TiXmlDocument()
bool TiXmlDocument::LoadFile(TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the current document value. Returns true if successful. Will delete any existing document data before loading.
References TiXmlNode::Value.
Referenced by LoadFile.
bool TiXmlDocument::SaveFile() const
Save a file using the current document value. Returns true if successful.
References TiXmlNode::Value.
Referenced by SaveFile.
bool TiXmlDocument::LoadFile(const char *filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
References LoadFile, SetError, TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_OPENING_FILE, TIXML_STRING, TiXmlNode::value.
bool TiXmlDocument::SaveFile(const char *filename) const
Save a file using the given filename. Returns true if successful.
References SaveFile.
bool TiXmlDocument::LoadFile(FILE *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*. Returns true if successful. Note that this method doesn't stream - the entire object pointed at by the FILE* will be interpreted as an XML file. TinyXML doesn't stream in XML from the current file location. Streaming may be added in the future.
References TiXmlCursor::Clear, TiXmlNode::Clear, Error, TiXmlBase::location, Parse, SetError, TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, TiXmlBase::TIXML_ERROR_OPENING_FILE, TIXML_STRING.
bool TiXmlDocument::SaveFile(FILE *) const
Save a file using the given FILE*. Returns true if successful.
References Print, TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, useMicrosoftBOM.
const char * TiXmlDocument::Parse(const char *p, TiXmlParsingData *data=0, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Parse the given null terminated block of xml data. Passing in an encoding to this method (either TIXML_ENCODING_LEGACY or TIXML_ENCODING_UTF8 will force TinyXml to use that encoding, regardless of what TinyXml might otherwise try to detect.
References TiXmlCursor::Clear, ClearError, TiXmlCursor::col, TiXmlParsingData::Cursor, TiXmlParsingData::cursor, TiXmlDeclaration::Encoding, TiXmlNode::firstChild, TiXmlNode::Identify, TiXmlNode::LinkEndChild, TiXmlBase::location, TiXmlBase::Parse, TiXmlCursor::row, SetError, TiXmlBase::SkipWhiteSpace, TiXmlBase::StringEqual, TabSize, TIXML_ENCODING_LEGACY, TIXML_ENCODING_UNKNOWN, TIXML_ENCODING_UTF8, TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, TiXmlNode::ToDeclaration, useMicrosoftBOM.
Referenced by KillBountyTableMgr::Load, AppendGroupTableMgr::Load, AvatarShopTableMgr::Load, TaskRecomTableMgr::Load, MapShopResTableMgr::Load, ChoiceItemTableMgr::Load, AddtionalTableMgr::Load, AvatarModelTableMgr::Load, RaceTextTableMgr::Load, RandomNameTableMgr::Load, SystemPromptTableMgr::Load, UnitHeadAreaTableMgr::Load, LevelTableMgr::Load, AttackArmorRatioTableMgr::Load, EffectSwitchTableMgr::Load, LanguageTableMgr::Load, DressTableMgr::Load, RacehelpTableMgr::Load, AITableMgr::Load, AchievementTableMgr::Load, AIPrioTableMgr::Load, AvatarAnimationTableMgr::Load, HorseTableMgr::Load, VoiceTableMgr::Load, PresetShopTableMgr::Load, IndexofferTableMgr::Load, AvatarEffectTableMgr::Load, AcSystemTableMgr::Load, AccountLevelTableMgr::Load, UpgradeCostTableMgr::Load, ChanceTableMgr::Load, AppendCostTableMgr::Load, PetTableMgr::Load, SearchChoiceTableMgr::Load, RenJiTableMgr::Load, ItemComposeTableMgr::Load, CreepTowerGrowthTableMgr::Load, RankStageTableMgr::Load, FreeHeroesTableMgr::Load, LeagueRankTableMgr::Load, ShopTableMgr::Load, PropagandaTableMgr::Load, DecomposeTableMgr::Load, MapMiscTableMgr::Load, ModelResTableMgr::Load, RenJiActionsTableMgr::Load, RenJiCustomDataTableMgr::Load, HeroInfoTableMgr::Load, StarWheelTableMgr::Load, RacedropTableMgr::Load, RackTableMgr::Load, BufferTableMgr::Load, BattleTipsTableMgr::Load, MissionInfoTableMgr::Load, PVERuleTableMgr::Load, VideoTagTableMgr::Load, AppendSkillPRTableMgr::Load, RaceStaMissionTableMgr::Load, RenJiConditionsTableMgr::Load, AvatarTableMgr::Load, MapsInfoTableMgr::Load, AppendSkillTableMgr::Load, SelHeroTableMgr::Load, ItemExchangeTableMgr::Load, TaskInfoTableMgr::Load, AchievementTaskTableMgr::Load, MapInfoTableMgr::Load, StrengthenTableMgr::Load, UnitTableMgr::Load, ItemTableMgr::Load, TownItemTableMgr::Load, LoadFile, SkillTableMgr::LoadSkillFile.
const TiXmlElement* TiXmlDocument::RootElement() const
Get the root element the only top level element of the document. In well formed XML, there should only be one. TinyXml is tolerant of multiple elements at the document level.
References TiXmlNode::FirstChildElement.
TiXmlElement* TiXmlDocument::RootElement()
References TiXmlNode::FirstChildElement.
bool TiXmlDocument::Error() const
If an error occurs, Error will be set to true. Also, The ErrorId() will contain the integer identifier of the error (not generally useful)The ErrorDesc() method will return the name of the error. (very useful)The ErrorRow() and ErrorCol() will return the location of the error (if known)
References error.
Referenced by KillBountyTableMgr::Load, AppendGroupTableMgr::Load, AvatarShopTableMgr::Load, TaskRecomTableMgr::Load, MapShopResTableMgr::Load, ChoiceItemTableMgr::Load, AddtionalTableMgr::Load, AvatarModelTableMgr::Load, RaceTextTableMgr::Load, RandomNameTableMgr::Load, SystemPromptTableMgr::Load, UnitHeadAreaTableMgr::Load, LevelTableMgr::Load, AttackArmorRatioTableMgr::Load, EffectSwitchTableMgr::Load, LanguageTableMgr::Load, DressTableMgr::Load, RacehelpTableMgr::Load, AITableMgr::Load, AchievementTableMgr::Load, AIPrioTableMgr::Load, AvatarAnimationTableMgr::Load, HorseTableMgr::Load, VoiceTableMgr::Load, PresetShopTableMgr::Load, IndexofferTableMgr::Load, AvatarEffectTableMgr::Load, AcSystemTableMgr::Load, AccountLevelTableMgr::Load, UpgradeCostTableMgr::Load, ChanceTableMgr::Load, AppendCostTableMgr::Load, PetTableMgr::Load, SearchChoiceTableMgr::Load, RenJiTableMgr::Load, ItemComposeTableMgr::Load, CreepTowerGrowthTableMgr::Load, RankStageTableMgr::Load, FreeHeroesTableMgr::Load, LeagueRankTableMgr::Load, ShopTableMgr::Load, PropagandaTableMgr::Load, DecomposeTableMgr::Load, MapMiscTableMgr::Load, ModelResTableMgr::Load, RenJiActionsTableMgr::Load, RenJiCustomDataTableMgr::Load, HeroInfoTableMgr::Load, StarWheelTableMgr::Load, RacedropTableMgr::Load, RackTableMgr::Load, BufferTableMgr::Load, BattleTipsTableMgr::Load, MissionInfoTableMgr::Load, PVERuleTableMgr::Load, VideoTagTableMgr::Load, AppendSkillPRTableMgr::Load, RaceStaMissionTableMgr::Load, RenJiConditionsTableMgr::Load, AvatarTableMgr::Load, MapsInfoTableMgr::Load, AppendSkillTableMgr::Load, SelHeroTableMgr::Load, ItemExchangeTableMgr::Load, TaskInfoTableMgr::Load, AchievementTaskTableMgr::Load, MapInfoTableMgr::Load, StrengthenTableMgr::Load, UnitTableMgr::Load, ItemTableMgr::Load, TownItemTableMgr::Load, LoadFile, SkillTableMgr::LoadSkillFile.
const char* TiXmlDocument::ErrorDesc() const
Contains a textual (english) description of the error if one occurs.
References errorDesc.
Referenced by KillBountyTableMgr::Load, AppendGroupTableMgr::Load, AvatarShopTableMgr::Load, TaskRecomTableMgr::Load, MapShopResTableMgr::Load, ChoiceItemTableMgr::Load, AddtionalTableMgr::Load, AvatarModelTableMgr::Load, RaceTextTableMgr::Load, RandomNameTableMgr::Load, SystemPromptTableMgr::Load, UnitHeadAreaTableMgr::Load, LevelTableMgr::Load, AttackArmorRatioTableMgr::Load, EffectSwitchTableMgr::Load, LanguageTableMgr::Load, DressTableMgr::Load, RacehelpTableMgr::Load, AITableMgr::Load, AchievementTableMgr::Load, AIPrioTableMgr::Load, AvatarAnimationTableMgr::Load, HorseTableMgr::Load, VoiceTableMgr::Load, PresetShopTableMgr::Load, IndexofferTableMgr::Load, AvatarEffectTableMgr::Load, AcSystemTableMgr::Load, AccountLevelTableMgr::Load, UpgradeCostTableMgr::Load, ChanceTableMgr::Load, AppendCostTableMgr::Load, PetTableMgr::Load, SearchChoiceTableMgr::Load, RenJiTableMgr::Load, ItemComposeTableMgr::Load, CreepTowerGrowthTableMgr::Load, RankStageTableMgr::Load, FreeHeroesTableMgr::Load, LeagueRankTableMgr::Load, ShopTableMgr::Load, PropagandaTableMgr::Load, DecomposeTableMgr::Load, MapMiscTableMgr::Load, ModelResTableMgr::Load, RenJiActionsTableMgr::Load, RenJiCustomDataTableMgr::Load, HeroInfoTableMgr::Load, StarWheelTableMgr::Load, RacedropTableMgr::Load, RackTableMgr::Load, BufferTableMgr::Load, BattleTipsTableMgr::Load, MissionInfoTableMgr::Load, PVERuleTableMgr::Load, VideoTagTableMgr::Load, AppendSkillPRTableMgr::Load, RaceStaMissionTableMgr::Load, RenJiConditionsTableMgr::Load, AvatarTableMgr::Load, MapsInfoTableMgr::Load, AppendSkillTableMgr::Load, SelHeroTableMgr::Load, ItemExchangeTableMgr::Load, TaskInfoTableMgr::Load, AchievementTaskTableMgr::Load, MapInfoTableMgr::Load, StrengthenTableMgr::Load, UnitTableMgr::Load, ItemTableMgr::Load, TownItemTableMgr::Load, SkillTableMgr::LoadSkillFile.
int TiXmlDocument::ErrorId() const
Generally, you probably want the error string ( ErrorDesc() ). But if you prefer the ErrorId, this function will fetch it.
References errorId.
int TiXmlDocument::ErrorRow() const
Returns the location (if known) of the error. The first column is column 1, and the first row is row 1. A value of 0 means the row and column wasn't applicable (memory errors, for example, have no row/column) or the parser lost the error. (An error in the error reporting, in that case.)SetTabSize, Row, Column
References errorLocation, TiXmlCursor::row.
int TiXmlDocument::ErrorCol() const
The column where the error occured. See ErrorRow()
References TiXmlCursor::col, errorLocation.
void TiXmlDocument::SetTabSize(int _tabsize)
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column. It does not change the output or input in any way.By calling this method, with a tab size greater than 0, the row and column of each node and attribute is stored when the file is loaded. Very useful for tracking the DOM back in to the source file.The tab size is required for calculating the location of nodes. If not set, the default of 4 is used. The tabsize is set per document. Setting the tabsize to 0 disables row/column tracking.Note that row and column tracking is not supported when using operator>>.The tab size needs to be enabled before the parse or load. Correct usage: TiXmlDocument doc; doc.SetTabSize( 8 ); doc.Load( "myfile.xml" ); Row, Column
References tabsize.
int TiXmlDocument::TabSize() const
References tabsize.
Referenced by Parse.
void TiXmlDocument::ClearError()
If you have handled the error, it can be reset with this call. The error state is automatically cleared if you Parse a new XML block.
References TiXmlCursor::col, error, errorDesc, errorId, errorLocation, TiXmlCursor::row.
Referenced by Parse, TiXmlDocument.
void TiXmlDocument::Print() const
Write the document to standard out using formatted printing ("pretty print").
References Print.
Referenced by Print, SaveFile.
void TiXmlDocument::Print(FILE *cfile, int depth=0) const
Print this Document to a FILE stream.
References TiXmlNode::FirstChild, TiXmlAttribute::Print.
void TiXmlDocument::SetError(int err, const char *errorLocation, TiXmlParsingData *prevData, TiXmlEncoding encoding)
References TiXmlCursor::Clear, TiXmlParsingData::Cursor, error, errorDesc, errorId, errorLocation, TiXmlBase::errorString, TiXmlParsingData::Stamp, TiXmlBase::TIXML_ERROR_STRING_COUNT.
Referenced by TiXmlNode::Identify, TiXmlNode::InsertAfterChild, TiXmlNode::InsertBeforeChild, TiXmlNode::InsertEndChild, TiXmlNode::LinkEndChild, LoadFile, TiXmlAttribute::Parse, TiXmlElement::Parse, TiXmlComment::Parse, TiXmlText::Parse, TiXmlDeclaration::Parse, TiXmlUnknown::Parse, Parse, TiXmlElement::ReadValue, TiXmlElement::SetAttribute.
virtual const TiXmlDocument* TiXmlDocument::ToDocument() const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlDocument* TiXmlDocument::ToDocument()
Cast to a more defined type. Will return null not of the requested type.
bool TiXmlDocument::Accept(TiXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
References TiXmlNode::FirstChild, TiXmlVisitor::VisitEnter, TiXmlVisitor::VisitExit.
TiXmlNode * TiXmlDocument::Clone() const
Create an exact duplicate of this node and return it. The memory must be deleted by the caller.
References CopyTo, TiXmlDocument.
void TiXmlDocument::CopyTo(TiXmlDocument *target) const
References TiXmlNode::Clone, TiXmlNode::CopyTo, error, errorDesc, TiXmlNode::firstChild, TiXmlNode::LinkEndChild, TiXmlNode::NextSibling.
Referenced by Clone, operator=, TiXmlDocument.