NexusTeamMgr
MTeam NexusTeamMgr::map_team_
Referenced by alter_leader, check_team, create_team, dismiss_team, gen_team_id, get_team, get_team_id, trim_member_num, Update.
MTeamMember NexusTeamMgr::map_team_member_
Referenced by alter_member, create_member, dismiss_team_linkuser, dismiss_team_member, get_member_leader_id, get_member_map, get_team_member, trim_member_order, verify.
NexusTeamMgr::NexusTeamMgr()
NexusTeamMgr::~NexusTeamMgr()
void NexusTeamMgr::Update()
References check_valid, dismiss, dismiss_team, map_team_, NexusTeam::member_num, SeLogDebug, NexusTeam::team_id.
Referenced by NexusServer::UpdateLogicl.
DWord NexusTeamMgr::gen_team_id()
References map_team_.
Referenced by gen_team.
DWord NexusTeamMgr::gen_order_id(const DWord team_id)
References get_team, NexusTeam::member_num.
Referenced by gen_member, verify.
NexusTeamMember NexusTeamMgr::gen_member(const DWord user_id, const DWord team_id, const DWord inviter_id, const DWord create_time, const DWord mark, const char *user_name)
References NexusTeamMemberBase::create_time, ETM_Invite, gen_order_id, NexusTeamMemberBase::inviter_id, NexusTeamMemberBase::mark, NexusTeamMember::member_base, NexusTeamMemberBase::order_id, NexusTeamMemberBase::team_id, NexusTeamMember::team_id, NexusTeamMemberBase::user_id, NexusTeamMemberBase::user_name.
Referenced by create_member.
NexusTeam NexusTeamMgr::gen_team(const DWord leader_id, const DWord create_time)
References NexusTeam::create_time, gen_team_id, NexusTeam::leader_id, NexusTeam::member_num, NexusTeam::team_id.
Referenced by create_team.
NexusTeamParam NexusTeamMgr::gen_param(const DWord mark, const DWord team_id, const DWord user_id, const DWord guest_id, const DWord create_time, const char *user_name, const char *guest_name)
References NexusTeamParam::create_time, NexusTeamParam::guest_id, NexusTeamParam::guest_name, NexusTeamParam::mark, NexusTeamParam::team_id, NexusTeamParam::user_id, NexusTeamParam::user_name.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq, NexusServer::ProcessTN_UserRefuseInviteReq.
DWord NexusTeamMgr::get_team_id(const DWord user_id)
References NexusTeam::leader_id, map_team_, NexusTeam::team_id.
DWord NexusTeamMgr::get_order_id(const DWord user_id, const DWord team_id)
References get_team_member, NexusTeamMember::member_base, NexusTeamMemberBase::order_id.
Referenced by trim_member_order.
DWord NexusTeamMgr::get_member_leader_id(const DWord team_id)
References map_team_member_, NexusTeamMember::member_base, NexusTeamMemberBase::order_id, NexusTeamMemberBase::user_id.
Referenced by alter_leader.
DWord NexusTeamMgr::get_team_leader_id(const DWord team_id)
References get_team, NexusTeam::leader_id.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_MatchTeamMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq.
DWord NexusTeamMgr::get_member_state(const DWord user_id, const DWord team_id)
References ETUNS_Unknow, get_team_member, NexusTeamMemberBase::mark, NexusTeamMember::member_base.
Referenced by check_member_state.
DWord NexusTeamMgr::get_member_inviter_id(const DWord user_id, const DWord team_id)
References ETUNS_Unknow, get_team_member, NexusTeamMemberBase::inviter_id, NexusTeamMember::member_base.
Referenced by NexusServer::ProcessTN_UserLeaveTeamReq.
void NexusTeamMgr::create_team(const DWord user_id, const DWord create_time, DWord &team_id)
References gen_team, map_team_, NexusTeam::team_id.
Referenced by custom_invite.
void NexusTeamMgr::create_member(DWord user_id, DWord team_id, const DWord inviter_id, DWord create_time, DWord mark, const char *user_name)
References NexusTeamMemberBase::create_time, gen_member, NexusTeamMemberBase::inviter_id, map_team_member_, NexusTeamMemberBase::mark, NexusTeamMember::member_base, NexusTeamMemberBase::order_id, StrCpy, NexusTeamMemberBase::team_id, NexusTeamMember::team_id, NexusTeamMemberBase::user_id, NexusTeamMemberBase::user_name.
Referenced by custom_invite, leader_invite, member_invite.
void NexusTeamMgr::verify(const DWord user_id, const DWord team_id, const DWord create_time, const DWord mark)
References NexusTeamMemberBase::create_time, ETM_Confirm, gen_order_id, get_team_member, map_team_member_, NexusTeamMemberBase::mark, NexusTeamMember::member_base, NexusTeamMemberBase::order_id.
Referenced by confirm, depart, refuse.
void NexusTeamMgr::alter_leader(const DWord team_id)
References check_valid, get_member_leader_id, get_team, NexusTeam::leader_id, map_team_.
Referenced by leave.
void NexusTeamMgr::alter_member(const DWord user_id, const DWord team_id)
References get_team, map_team_member_.
Referenced by depart.
void NexusTeamMgr::trim_member_order(const DWord user_id, const DWord team_id)
References check_valid, get_order_id, map_team_member_, NexusTeamMember::member_base, NexusTeamMemberBase::order_id.
Referenced by depart.
void NexusTeamMgr::trim_member_num(const DWord team_id, const DWord spread_id)
References ETMS_Negative, ETMS_Positive, get_team, map_team_, NexusTeam::member_num.
Referenced by confirm, custom_invite, depart.
void NexusTeamMgr::make(const NexusTeamParam param)
References confirm, NexusTeamParam::create_time, dismiss, ETM_Confirm, ETM_Dismiss, ETM_Invite, ETM_Kick, ETM_Leave, ETM_Offline, ETM_Refuse, NexusTeamParam::guest_id, NexusTeamParam::guest_name, invite, kick, leave, NexusTeamParam::mark, offline, refuse, NexusTeamParam::team_id, NexusTeamParam::user_id, NexusTeamParam::user_name.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq, NexusServer::ProcessTN_UserRefuseInviteReq.
void NexusTeamMgr::invite(const DWord user_id, const DWord guest_id, const DWord create_time, const char *user_name, const char *guest_name)
References check_member, check_team_leader, check_valid, custom_invite, g_kNexusLinkUserMgr, NexusLinkUserMgr::get_link_user_team, leader_invite, member_invite.
Referenced by make.
void NexusTeamMgr::confirm(const DWord user_id, const DWord team_id, const DWord create_time)
References ETM_Confirm, ETMS_Positive, link_team, trim_member_num, verify.
Referenced by make.
void NexusTeamMgr::refuse(const DWord user_id, const DWord team_id, const DWord create_time)
References ETM_Refuse, verify.
Referenced by make.
void NexusTeamMgr::leave(const DWord user_id, const DWord team_id, const DWord create_time)
References alter_leader, check_team_leader, depart, ETM_Leave.
Referenced by make, offline.
void NexusTeamMgr::kick(const DWord user_id, const DWord team_id, const DWord create_time)
References depart, ETM_Kick.
Referenced by make.
void NexusTeamMgr::dismiss(const DWord team_id)
References dismiss_team_linkuser, dismiss_team_member.
Referenced by disband, make, Update.
void NexusTeamMgr::dismiss_team(const DWord team_id)
References map_team_.
Referenced by disband, Update.
void NexusTeamMgr::dismiss_team_linkuser(const DWord team_id)
References link_team, map_team_member_, NexusTeamMember::member_base, NexusTeamMemberBase::user_id.
Referenced by dismiss.
void NexusTeamMgr::dismiss_team_member(const DWord team_id)
References map_team_member_.
Referenced by dismiss.
void NexusTeamMgr::offline(const DWord user_id, const DWord create_time)
References check_valid, g_kNexusLinkUserMgr, NexusLinkUserMgr::get_link_user_team, leave.
Referenced by make.
void NexusTeamMgr::link_team(const DWord user_id, const DWord team_id)
References g_kNexusLinkUserMgr, NexusLinkUserMgr::verify.
Referenced by confirm, custom_invite, depart, dismiss_team_linkuser.
void NexusTeamMgr::depart(const DWord user_id, const DWord team_id, const DWord create_time, const DWord mark)
References alter_member, ETMS_Negative, link_team, trim_member_num, trim_member_order, verify.
Referenced by kick, leave.
void NexusTeamMgr::disband(const DWord team_id)
References check_valid, dismiss, dismiss_team.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserLeaveTeamReq.
void NexusTeamMgr::custom_invite(const DWord user_id, const DWord guest_id, const DWord create_time, const char *user_name, const char *guest_name)
References check_valid, create_member, create_team, ETM_Confirm, ETM_Invite, ETMS_Positive, link_team, trim_member_num.
Referenced by invite.
void NexusTeamMgr::leader_invite(const DWord user_id, const DWord team_id, const DWord guest_id, const DWord create_time, const char *guest_name)
References check_team_leader, create_member, ETM_Invite.
Referenced by invite.
void NexusTeamMgr::member_invite(const DWord user_id, const DWord team_id, const DWord guest_id, const DWord create_time, const char *guest_name)
References check_member, create_member, ETM_Invite.
Referenced by invite.
NexusTeam * NexusTeamMgr::get_team(const DWord team_id)
References map_team_.
Referenced by alter_leader, alter_member, check_disband, check_team_leader, check_team_state, gen_order_id, get_member_map, get_team_leader_id, get_team_member, trim_member_num.
NexusTeamMember * NexusTeamMgr::get_team_member(const DWord user_id, const DWord team_id)
References get_team, map_team_member_.
Referenced by check_member, get_member_inviter_id, get_member_state, get_order_id, NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq, NexusServer::ProcessTN_UserRefuseInviteReq, verify.
bool NexusTeamMgr::check_valid(const DWord id)
Referenced by alter_leader, custom_invite, disband, invite, offline, NexusServer::ProcessTN_MatchTeamMemberReq, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq, trim_member_order, Update.
bool NexusTeamMgr::check_team(const DWord team_id)
References map_team_.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq, NexusServer::ProcessTN_UserRefuseInviteReq.
bool NexusTeamMgr::check_team_state(const DWord team_id)
References get_team, NexusTeam::member_num, team_member_num_max.
Referenced by NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq.
bool NexusTeamMgr::check_team_leader(const DWord user_id, const DWord team_id)
References get_team, NexusTeam::leader_id.
Referenced by invite, leader_invite, leave, NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_UserLeaveTeamReq.
bool NexusTeamMgr::check_member_state(const DWord user_id, const DWord team_id, const DWord mark)
References get_member_state.
Referenced by check_invite.
bool NexusTeamMgr::check_invite(const DWord user_id, const DWord team_id)
References check_member_state, ETM_Invite.
Referenced by NexusServer::ProcessTN_UserInviteReq.
bool NexusTeamMgr::check_member(const DWord user_id, const DWord team_id)
References ETM_Confirm, get_team_member, NexusTeamMemberBase::mark, NexusTeamMember::member_base.
Referenced by invite, member_invite, NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq.
bool NexusTeamMgr::check_disband(const DWord team_id)
References get_team, NexusTeam::member_num.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserLeaveTeamReq.
MMember NexusTeamMgr::get_member_map(const DWord team_id)
References get_team, map_team_member_.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_MatchTeamMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq.