BackendStatisticsMgr
BackendStatisticsMgr::BackendStatisticsMgr()
BackendStatisticsMgr::~BackendStatisticsMgr()
DWord BackendStatisticsMgr::get_online_users()
References g_kLinkUserMgr, LinkUserMgr::get_online_users.
Referenced by BackendServer::UpdateStatistic_OnlineNum.
DWord BackendStatisticsMgr::get_race_users()
References g_kLinkUserMgr, LinkUserMgr::get_race_users.
Referenced by BackendServer::UpdateStatistic_RaceNum.
DWord BackendStatisticsMgr::get_watch_users()
References g_kLinkUserMgr, LinkUserMgr::get_watch_users.
Referenced by BackendServer::UpdateStatistic_WatchNum.