SeXmlElement
SeXmlAttributeSet SeXmlElement::attributeSet
Referenced by Accept, Attribute, ClearThis, CopyTo, FirstAttribute, LastAttribute, Parse, Print, QueryBoolAttribute, QueryDoubleAttribute, QueryIntAttribute, QueryUnsignedAttribute, QueryValueAttribute, RemoveAttribute, SetAttribute, SetDoubleAttribute.
SeXmlElement::SeXmlElement(const char *in_value)
Construct an element.
References SeXmlNode::firstChild, SeXmlNode::lastChild, SeXmlNode::value.
Referenced by Clone.
SeXmlElement::SeXmlElement(const std::string &_value)
std::string constructor.
References SeXmlNode::firstChild, SeXmlNode::lastChild, SeXmlNode::value.
SeXmlElement::SeXmlElement(const SeXmlElement &)
References CopyTo, SeXmlNode::firstChild, SeXmlNode::lastChild.
SeXmlElement & SeXmlElement::operator=(const SeXmlElement &base)
References ClearThis, CopyTo.
SeXmlElement::~SeXmlElement()
References ClearThis.
const char * SeXmlElement::Attribute(const char *name) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::Value.
Referenced by SeXmlHandle::CreatePath, SeXmlHandle::GetPath, QueryStringAttribute.
const char * SeXmlElement::Attribute(const char *name, int *i) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists. If the attribute exists and can be converted to an integer, the integer value will be put in the return 'i', if 'i' is non-null.
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryIntValue, SeXmlAttribute::Value.
const char * SeXmlElement::Attribute(const char *name, double *d) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists. If the attribute exists and can be converted to an double, the double value will be put in the return 'd', if 'd' is non-null.
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryDoubleValue, SeXmlAttribute::Value.
int SeXmlElement::QueryIntAttribute(const char *name, int *_value) const
QueryIntAttribute examines the attribute - it is an alternative to the Attribute() method with richer error checking. If the attribute is an integer, it is stored in 'value' and the call returns SeXml_SUCCESS. If it is not an integer, it returns SeXml_WRONG_TYPE. If the attribute does not exist, then SeXml_NO_ATTRIBUTE is returned.
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryIntValue, SeXml_NO_ATTRIBUTE.
int SeXmlElement::QueryUnsignedAttribute(const char *name, unsigned *_value) const
QueryUnsignedAttribute examines the attribute - see QueryIntAttribute().
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryIntValue, SeXml_NO_ATTRIBUTE.
int SeXmlElement::QueryBoolAttribute(const char *name, bool *_value) const
QueryBoolAttribute examines the attribute - see QueryIntAttribute(). Note that '1', 'true', or 'yes' are considered true, while '0', 'false' and 'no' are considered false.
References attributeSet, SeXmlAttributeSet::Find, SeXml_ENCODING_UNKNOWN, SeXml_NO_ATTRIBUTE, SeXml_SUCCESS, SeXml_WRONG_TYPE, SeXmlBase::StringEqual, SeXmlAttribute::Value.
int SeXmlElement::QueryDoubleAttribute(const char *name, double *_value) const
QueryDoubleAttribute examines the attribute - see QueryIntAttribute().
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryDoubleValue, SeXml_NO_ATTRIBUTE.
Referenced by QueryFloatAttribute.
int SeXmlElement::QueryFloatAttribute(const char *name, float *_value) const
QueryFloatAttribute examines the attribute - see QueryIntAttribute().
References QueryDoubleAttribute, SeXml_SUCCESS.
int SeXmlElement::QueryStringAttribute(const char *name, std::string *_value) const
QueryStringAttribute examines the attribute - see QueryIntAttribute().
References Attribute, SeXml_NO_ATTRIBUTE, SeXml_SUCCESS.
int SeXmlElement::QueryValueAttribute(const std::string &name, T *outValue) const
Template form of the attribute query which will try to read the attribute into the specified type. Very easy, very powerful, but be careful to make sure to call this with the correct type.NOTE: This method doesn't work correctly for 'string' types that contain spaces.SeXml_SUCCESS, SeXml_WRONG_TYPE, or SeXml_NO_ATTRIBUTE
References attributeSet, SeXmlAttributeSet::Find, SeXml_NO_ATTRIBUTE, SeXml_SUCCESS, SeXml_WRONG_TYPE, SeXmlAttribute::ValueStr.
int SeXmlElement::QueryValueAttribute(const std::string &name, std::string *outValue) const
References attributeSet, SeXmlAttributeSet::Find, SeXml_NO_ATTRIBUTE, SeXml_SUCCESS, SeXmlAttribute::ValueStr.
void SeXmlElement::SetAttribute(const char *name, const char *_value)
Sets an attribute of name to a given value. The attribute will be created if it does not exist, or changed if it does.
References attributeSet, SeXmlAttributeSet::FindOrCreate, SeXmlAttribute::SetValue.
Referenced by CopyTo, SeXmlHandle::CreatePath.
const std::string * SeXmlElement::Attribute(const std::string &name) const
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::ValueStr.
const std::string * SeXmlElement::Attribute(const std::string &name, int *i) const
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryIntValue, SeXmlAttribute::ValueStr.
const std::string * SeXmlElement::Attribute(const std::string &name, double *d) const
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryDoubleValue, SeXmlAttribute::ValueStr.
int SeXmlElement::QueryIntAttribute(const std::string &name, int *_value) const
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryIntValue, SeXml_NO_ATTRIBUTE.
int SeXmlElement::QueryDoubleAttribute(const std::string &name, double *_value) const
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttribute::QueryDoubleValue, SeXml_NO_ATTRIBUTE.
void SeXmlElement::SetAttribute(const std::string &name, const std::string &_value)
STL std::string form.
STL std::string form.
References attributeSet, SeXmlAttributeSet::FindOrCreate, SeXmlAttribute::SetValue.
void SeXmlElement::SetAttribute(const std::string &name, int _value)
STL std::string form.
References attributeSet, SeXmlAttributeSet::FindOrCreate, SeXmlAttribute::SetIntValue.
void SeXmlElement::SetDoubleAttribute(const std::string &name, double value)
References attributeSet, SeXmlAttributeSet::FindOrCreate, SeXmlAttribute::SetDoubleValue.
void SeXmlElement::SetAttribute(const char *name, int value)
Sets an attribute of name to a given value. The attribute will be created if it does not exist, or changed if it does.
References attributeSet, SeXmlAttributeSet::FindOrCreate, SeXmlAttribute::SetIntValue.
void SeXmlElement::SetDoubleAttribute(const char *name, double value)
Sets an attribute of name to a given value. The attribute will be created if it does not exist, or changed if it does.
References attributeSet, SeXmlAttributeSet::FindOrCreate, SeXmlAttribute::SetDoubleValue.
void SeXmlElement::RemoveAttribute(const char *name)
Deletes an attribute with the given name.
References attributeSet, SeXmlAttributeSet::Find, SeXmlAttributeSet::Remove, SeXml_STRING.
void SeXmlElement::RemoveAttribute(const std::string &name)
STL std::string form.
References RemoveAttribute.
Referenced by RemoveAttribute.
const SeXmlAttribute* SeXmlElement::FirstAttribute() const
Access the first attribute in this element.
References attributeSet, SeXmlAttributeSet::First.
Referenced by SeXmlHandle::CreatePath, SeXmlHandle::GetPath.
SeXmlAttribute* SeXmlElement::FirstAttribute()
References attributeSet, SeXmlAttributeSet::First.
const SeXmlAttribute* SeXmlElement::LastAttribute() const
Access the last attribute in this element.
References attributeSet, SeXmlAttributeSet::Last.
SeXmlAttribute* SeXmlElement::LastAttribute()
References attributeSet, SeXmlAttributeSet::Last.
const char * SeXmlElement::GetText() const
Convenience function for easy access to the text inside an element. Although easy and concise, GetText() is limited compared to getting the SeXmlText child and accessing it directly.If the first child of 'this' is a SeXmlText, the GetText() returns the character string of the Text node, else null is returned.This is a convenient method for getting the text of simple contained text: <foo>This is text</foo> const char* str = fooElement->GetText(); 'str' will be a pointer to "This is text".Note that this function can be misleading. If the element foo was created from this XML: <foo><b>This is text</b></foo> then the value of str would be null. The first child node isn't a text node, it is another element. From this XML: <foo>This is <b>text</b></foo> GetText() will return "This is ".WARNING: GetText() accesses a child node - don't become confused with the similarly named SeXmlHandle::Text() and SeXmlNode::ToText() which are safe type casts on the referenced node.
References SeXmlNode::FirstChild, SeXmlNode::ToText, SeXmlNode::Value.
SeXmlNode * SeXmlElement::Clone() const
Creates a new Element and returns it - the returned element is a copy.
References CopyTo, SeXmlElement, SeXmlNode::Value.
void SeXmlElement::Print(FILE *cfile, int depth) const
All SeXml classes can print themselves to a filestream or the string class (SeXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.This is a formatted print, and will insert tabs and newlines.(For an unformatted stream, use the << operator.)
References attributeSet, SeXmlAttributeSet::First, SeXmlNode::firstChild, SeXmlNode::lastChild, SeXmlAttribute::Next, SeXmlNode::NextSibling, SeXmlBase::Print, SeXmlNode::ToText, SeXmlNode::value.
const char * SeXmlElement::Parse(const char *p, SeXmlParsingData *data, SeXmlEncoding encoding)
References SeXmlAttributeSet::Add, attributeSet, SeXmlParsingData::Cursor, SeXmlAttributeSet::Find, SeXmlNode::GetDocument, SeXmlBase::location, SeXmlAttribute::NameTStr, SeXmlAttribute::Parse, SeXmlBase::ReadName, ReadValue, SeXmlAttribute::SetDocument, SeXmlDocument::SetError, SeXmlBase::SeXml_ERROR_FAILED_TO_READ_ELEMENT_NAME, SeXmlBase::SeXml_ERROR_PARSING_ELEMENT, SeXmlBase::SeXml_ERROR_PARSING_EMPTY, SeXmlBase::SeXml_ERROR_READING_ATTRIBUTES, SeXmlBase::SeXml_ERROR_READING_END_TAG, SeXml_STRING, SeXmlBase::SkipWhiteSpace, SeXmlParsingData::Stamp, SeXmlBase::StringEqual, SeXmlNode::value.
virtual const SeXmlElement* SeXmlElement::ToElement() const
Cast to a more defined type. Will return null not of the requested type.
Referenced by SeXmlHandle::CreatePath, SeXmlHandle::GetPath.
virtual SeXmlElement* SeXmlElement::ToElement()
Cast to a more defined type. Will return null not of the requested type.
bool SeXmlElement::Accept(SeXmlVisitor *visitor) const
Walk the XML tree visiting this node and all of its children.
References attributeSet, SeXmlAttributeSet::First, SeXmlNode::FirstChild, SeXmlNode::NextSibling, SeXmlVisitor::VisitEnter, SeXmlVisitor::VisitExit.
void SeXmlElement::CopyTo(SeXmlElement *target) const
References attributeSet, SeXmlNode::Clone, SeXmlNode::CopyTo, SeXmlAttributeSet::First, SeXmlNode::firstChild, SeXmlNode::LinkEndChild, SeXmlAttribute::Name, SeXmlAttribute::Next, SeXmlNode::NextSibling, SetAttribute, SeXmlAttribute::Value.
Referenced by Clone, operator=, SeXmlElement.
void SeXmlElement::ClearThis()
References attributeSet, SeXmlNode::Clear, SeXmlAttributeSet::First, SeXmlAttributeSet::Remove.
Referenced by operator=, ~SeXmlElement.
void SeXmlElement::StreamIn(std::istream *in, SeXml_STRING *tag)
References SeXmlNode::GetDocument, SeXmlNode::Identify, SeXmlBase::IsWhiteSpace, SeXmlDocument::SetError, SeXml_DEFAULT_ENCODING, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_EMBEDDED_NULL, SeXmlNode::StreamIn, SeXmlText::StreamIn, SeXmlBase::StreamWhiteSpace.
const char * SeXmlElement::ReadValue(const char *in, SeXmlParsingData *prevData, SeXmlEncoding encoding)
References SeXmlText::Blank, SeXmlNode::GetDocument, SeXmlNode::Identify, SeXmlBase::IsWhiteSpaceCondensed, SeXmlNode::LinkEndChild, SeXmlBase::Parse, SeXmlText::Parse, SeXmlDocument::SetError, SeXmlBase::SeXml_ERROR_READING_ELEMENT_VALUE, SeXmlBase::SkipWhiteSpace, SeXmlBase::StringEqual.
Referenced by Parse.