DBServer
char DBServer::m_acSend[SSD_SEND_SIZE]
Referenced by DBServer, Excu_SelectData.
DWord DBServer::m_dwTickCount
Referenced by DBServer, Initialize, Update.
DWord DBServer::m_dwCurTime
Referenced by DBServer, GetServerTime, ProcessWB_Register, ProcessWB_TabDelete, ProcessWB_TabInsert, ProcessWB_TabSelect, ProcessWB_TabUpdate, SendDB_CharData, SendDB_CharLoginLoad, SendDB_CharNexusFriendLoad, SendDB_CharQueryValid, SendDB_CharRenameBegin, SendDB_CharRenameEnd, SendDB_CharRenameEndQuery, SendDB_FriendLadderInfoLoad, SendDB_InitGenID, SendDB_IsPlayerExistByID, SendDB_IsPlayerExistByName, Update.
SeDBServerConfig DBServer::m_kConfig
Referenced by GetLogShowType, GetMaxCacheNums, GetMaxDBQueryNums, InitializeDB, InitializeNet, LoadConfig, LoadDynamicConfig, OnNetAccept, SetMaxCacheNums, SetMaxDBQueryNums, UpdateLogShow.
DWord DBServer::m_dwSaveSpaceTime
Referenced by DBServer, GetSaveSpaceTime, LoadConfig.
TeNetMgr DBServer::m_kNetMgr
Referenced by Finialize, InitializeNet, OnNetRecv, ProcessWB_Register, SendBWData, Update.
SeServerData DBServer::m_kWSData
Referenced by OnNetAccept, OnNetDisconnect, OnNetRecv, ProcessWB_Register, SendBWData.
TeDataBaseMgr DBServer::m_kDBMgr
Referenced by Finialize, InitializeDB, PostExecutSQL, ProcessWB_TabDelete, ProcessWB_TabInsert, ProcessWB_TabSelect, ProcessWB_TabUpdate, SendDB_CharData, SendDB_CharInfoAdd, SendDB_CharLoginLoad, SendDB_CharNexusFriendLoad, SendDB_CharQueryValid, SendDB_CharRenameBegin, SendDB_CharRenameEnd, SendDB_CharRenameEndQuery, SendDB_FriendLadderInfoLoad, SendDB_InitGenID, SendDB_IsPlayerExistByID, SendDB_IsPlayerExistByName, Update, UpdateDissconectDB.
MapDBQuery DBServer::m_kAllDBQuery
Referenced by Finialize, GetDBQueryNums, ProcessDB, ProcessWB_TabDelete, ProcessWB_TabInsert, ProcessWB_TabSelect, ProcessWB_TabUpdate, PushDBQuery, SendDB_CharData, SendDB_CharInfoAdd, SendDB_CharLoginLoad, SendDB_CharNexusFriendLoad, SendDB_CharQueryValid, SendDB_CharRenameBegin, SendDB_CharRenameEnd, SendDB_CharRenameEndQuery, SendDB_FriendLadderInfoLoad, SendDB_InitGenID, SendDB_IsPlayerExistByID, SendDB_IsPlayerExistByName.
MID2DBIndex DBServer::m_kMID2DBIndex
Referenced by GetDBIndex, GetDBNums, InitializeDB, SendDB_InitGenID.
MID2DBConnectNums DBServer::m_kMID2DBConnectNums
Referenced by GetDBConnectNums, InitializeDB.
MID2DBName DBServer::m_kMID2DBName
Referenced by InitializeDB, SendDBLog_SqlLog.
SeThreadMsgMgr DBServer::m_kThreadMsgMgr
Referenced by Initialize, SendDBLog_SqlLog, WriteLogUpdate.
MapSqlLog DBServer::m_kSqlLog
Referenced by Finialize, SaveSqlLog2File, UpdateSqlLog2File.
SeDBTime DBServer::m_kHourDBTime
Referenced by DBServer, UpdateSqlLog2File.
char DBServer::m_acSqlLogPath[256]
Referenced by DBServer, Finialize, LoadConfig, SaveSqlLog2File, UpdateSqlLog2File.
int DBServer::m_iServerErrorCode
Referenced by DBServer, GetServerDBError, SetServerErrorCode.
VInt DBServer::m_aiDissconectDBIndex
Referenced by ProcessDB_Common, UpdateDissconectDB.
DWord DBServer::m_dwLoadCount
Referenced by DBServer, SetLoginLogInfo, UpdateLogShow.
DWord DBServer::m_dwLoadSumTime
Referenced by DBServer, SetLoginLogInfo, UpdateLogShow.
SeFlux DBServer::m_kFlux
Referenced by OnPrintfNetState, Update.
DBServer::DBServer(void)
References m_acSend, m_acSqlLogPath, m_dwCurTime, m_dwLoadCount, m_dwLoadSumTime, m_dwSaveSpaceTime, m_dwTickCount, m_iServerErrorCode, m_kHourDBTime, NowTime.
DBServer::~DBServer(void)
bool DBServer::Initialize(void)
References g_kDBMemMgr, InitDBMem, SeDBMemMgr::Initialize, SeThreadMsgMgr::Initialize, InitializeDB, InitializeNet, LoadConfig, m_dwTickCount, m_kThreadMsgMgr, SeLogError, SeLogInfo.
void DBServer::Update(void)
References g_kDBPlayerMgr, m_dwCurTime, m_dwTickCount, m_kDBMgr, m_kFlux, m_kNetMgr, OnPrintfNetState, PrintUpdateTime, SeDBPlayerMgr::Update, UpdateDissconectDB, UpdateLogShow.
void DBServer::Finialize(void)
References SeSqlLogCache::acLogBuffer, SqlLogSaveThread::Finialize, g_kDBPlayerMgr, SeDBTime::iDay, SeDBTime::iHour, SeSqlLogCache::iLogSize, SeDBTime::iMonth, SeDBTime::iYear, m_acSqlLogPath, m_kAllDBQuery, m_kDBMgr, m_kNetMgr, m_kSqlLog, MkDir, NowTime, SPrintf, SeDBPlayerMgr::Update.
void DBServer::ShowConsoleTitle(int iDTime)
References g_kDBMemMgr, g_kDBPlayerMgr, SeDBMemMgr::GetAllocSize, SeDBPlayerMgr::GetCycleNums, SeDBPlayerMgr::GetDBPlayerNums, GetDBQueryNums, GetMaxCacheNums, SeDBPlayerMgr::GetNameRecordCount, GetSaveSpaceTime.
SeServerActionResult DBServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F5, LoadDynamicConfig, SeLogHideTime, SeLogInfo.
void DBServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
void DBServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeNetAddr::iPort, SeServerData::kSock, SeDBServerConfig::kWSServer, m_kConfig, m_kWSData, SeLogInfo, SSD_IP_LEN, StrCpy.
void DBServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References SeServerData::kSock, m_kNetMgr, m_kWSData, ProcessBLBData, ProcessWBData, SeLogError, SSD_SEND_SIZE, STCB_BLS_BS, STCB_INTERVAL, SeCMD::wCmd, SeCMD::wFlag.
void DBServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeServerData::bConnecting, SeServerData::bRegistered, SeServerData::dwRegisterTime, SeServerData::kSock, m_kWSData, SeLogError.
void DBServer::OnDBResponse(int iDB, TeDBResSet &rkResSet)
References ProcessDB.
DWord DBServer::GetServerTime(void)
References m_dwCurTime.
Referenced by SeDBPlayerMgr::DBPlayerLoad, SeDBPlayerMgr::onLoadingComplete, SeDBPlayerMgr::Update, UpdateDissconectDB, UpdateLogShow.
void DBServer::SetMaxCacheNums(int iNums)
References SeDBServerConfig::iMaxCacheNums, m_kConfig.
int DBServer::GetMaxCacheNums()
References SeDBServerConfig::iMaxCacheNums, m_kConfig.
Referenced by SeDBPlayerMgr::AttachLink, ShowConsoleTitle.
DWord DBServer::GetSaveSpaceTime()
References m_dwSaveSpaceTime.
Referenced by ShowConsoleTitle, SeDBPlayerMgr::Update.
void DBServer::SetServerErrorCode(int iErrorCode)
References m_iServerErrorCode, SeLogError, SendBW_DBServerError.
Referenced by ProcessDB_Common, UpdateDissconectDB.
bool DBServer::GetServerDBError(void)
References m_iServerErrorCode.
Referenced by SeDBPlayerMgr::Update, UpdateDissconectDB.
int DBServer::GetDBQueryNums()
References m_kAllDBQuery.
Referenced by ShowConsoleTitle, SeDBPlayerMgr::Update.
void DBServer::SetMaxDBQueryNums(int iNums)
References SeDBServerConfig::iMaxDBQueryNum, m_kConfig.
int DBServer::GetMaxDBQueryNums()
References SeDBServerConfig::iMaxDBQueryNum, m_kConfig.
Referenced by SeDBPlayerMgr::Update.
void DBServer::SetLoginLogInfo(DWord dwCount, DWord dwCousumeTime)
References m_dwLoadCount, m_dwLoadSumTime.
Referenced by SeDBPlayerMgr::DBPlayerLoad, SeDBPlayerMgr::onLoadingComplete.
int DBServer::GetLogShowType(void)
References SeDBServerConfig::iLogShowType, m_kConfig.
Referenced by SeDBPlayerMgr::DBPlayerLoad, SeDBPlayerMgr::onLoadingComplete.
void DBServer::WriteLogUpdate(void)
References SeMsgData::abyData, SeSqlLog2File::acDBName, SeSqlLog2File::acSql, SeMsgData::iSize, SeSqlLog2File::kLogTime, m_kThreadMsgMgr, SeThreadMsgMgr::PopMsg, SaveSqlLog2File, UpdateSqlLog2File.
Referenced by SqlLogSaveThread::DoWork.
bool DBServer::SendDBLog_SqlLog(int iDBIndex, const char *pcSql)
References SeSqlLog2File::acDBName, SeSqlLog2File::acSql, SeSqlLog2File::kLogTime, m_kMID2DBName, m_kThreadMsgMgr, NowTime, SeThreadMsgMgr::PushMsg, SeLogError, StrCpy.
Referenced by SendDB_CharInfoAdd, SendDB_CharNexusFriendLoad, SendDB_CharRenameEnd.
SeDBTableIndex DBServer::GetTableIndex(const char *pcTableName)
References SDTI_NONE, SeLogError.
Referenced by InitializeDB.
const char * DBServer::GetTableName(SeDBTableIndex eTable)
References SeLogError.
Referenced by PlayerDataStrategy::getInitGenIDSql, ProcessWB_TabDelete, ProcessWB_TabInsert, ProcessWB_TabSelect, ProcessWB_TabUpdate, SendDB_CharData.
const char * DBServer::GetTableFieldName(SeDBTableIndex eTable, int fieldIndex)
References SeLogError.
Referenced by appendWhereClause, ProcessWB_TabInsert, ProcessWB_TabSelect, ProcessWB_TabUpdate, SendDB_CharData.
int DBServer::GetTableFieldCount(SeDBTableIndex eTable)
Referenced by SendDB_CharData.
int DBServer::GetDBConnectNums(int iDBIndex)
References m_kMID2DBConnectNums.
Referenced by ProcessWS_Insert_NoReceipt_Offline_NexusFriend, CharInfoStrategy::saveToDB, PlayerDataStrategy::saveToDB, SeDBPlayerMgr::SaveToDB, SendDB_CharData, SendDB_CharInfoAdd, SendDB_CharLoginLoad, SendDB_CharNexusFriendLoad, SendDB_CharQueryValid, SendDB_FriendLadderInfoLoad, SendDB_IsPlayerExistByID.
int DBServer::GetGMDBConnect(SeDBTableIndex eTableIndex)
Referenced by InitializeDB.
int DBServer::GetDBIndex(DWord dwID, SeDBTableIndex eTableIndex)
References m_kMID2DBIndex.
Referenced by ProcessWB_TabDelete, ProcessWB_TabInsert, ProcessWB_TabSelect, ProcessWB_TabUpdate, ProcessWS_Insert_NoReceipt_Offline_NexusFriend, CharInfoStrategy::saveToDB, PlayerDataStrategy::saveToDB, SeDBPlayerMgr::SaveToDB, SendDB_CharData, SendDB_CharInfoAdd, SendDB_CharLoginLoad, SendDB_CharNexusFriendLoad, SendDB_CharQueryValid, SendDB_CharRenameBegin, SendDB_CharRenameEnd, SendDB_CharRenameEndQuery, SendDB_FriendLadderInfoLoad, SendDB_InitGenID, SendDB_IsPlayerExistByID, SendDB_IsPlayerExistByName.
int DBServer::GetDBNums(SeDBTableIndex eTableIndex)
References m_kMID2DBIndex.
Referenced by SendDB_CharRenameBegin, SendDB_InitGenID, SendDB_IsPlayerExistByName.
void DBServer::PushDBQuery(DWord dwKey, SeDBQuery *pkQuery)
References m_kAllDBQuery.
DWord DBServer::PostExecutSQL(int iDB, const char *pcSql, UInt uiHash=0, int iExeFlag=0)
References m_kDBMgr.
SeFieldFormat DBServer::GetFieldFormat(SeDBTableIndex eTable, int iIndex)
References SeLogError, SFF_NULL.
Referenced by appendWhereClause, Excu_SelectData, ProcessWB_TabInsert, ProcessWB_TabSelect, ProcessWB_TabUpdate, ProcessWS_Insert_NoReceipt, ProcessWS_Insert_NoReceipt_Offline_NexusFriend, ProcessWS_Update_NoReceipt.
DWord DBServer::GetPlayerFieldNum(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, int iIndex, int iCount, uint64_t dwlID=0, DWord dwPara1=0)
References g_kDBPlayerMgr, GetPlayerFieldData, SeDBPlayerMgr::IsPlayerLoadComplete, SeLogError, SFF_NUM.
Referenced by Excu_SelectData, SeDBPlayerMgr::OnDataUpdateNum.
uint64_t DBServer::GetPlayerFieldNum64(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, int iIndex, int iCount, uint64_t dwlID=0, DWord dwPara1=0)
References g_kDBPlayerMgr, GetPlayerFieldData, SeDBPlayerMgr::IsPlayerLoadComplete, SeLogError, SFF_NUM64.
Referenced by Excu_SelectData, SeDBPlayerMgr::OnDataUpdateNum64.
SeDBTime DBServer::GetPlayerFieldDate(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, int iIndex, DWord iCount)
References g_kDBPlayerMgr, GetPlayerFieldData, SeDBPlayerMgr::IsPlayerLoadComplete, SeLogError, SFF_DATETIME.
Referenced by Excu_SelectData.
const char * DBServer::GetPlayerFieldStr(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, int iIndex, DWord iCount)
References g_kDBPlayerMgr, GetPlayerFieldData, SeDBPlayerMgr::IsPlayerLoadComplete, SeLogError, SFF_STRING.
Referenced by Excu_SelectData.
bool DBServer::SendDB_LoadInfo(DWord dwID)
References g_kDBPlayerMgr, g_kPlayerDataMgr, SeDBPlayerMgr::GetDBPlayer, PlayerDataMgr::loadData, PLF_CHAR_MEMORY, SeDBPlayerMgr::SeLoadingFlag, SendDB_CharNexusFriendLoad.
Referenced by SeDBPlayerMgr::DBPlayerLoad.
bool DBServer::SendDB_InitGenID(SeInitGenIDType eType, SeDBTableIndex eTableIndex)
References SeDBQuery::acSql, SeDBQuery::callback, SeDBQuery::dwTime, g_kDBPlayerMgr, g_kPlayerDataMgr, SeDBPlayerMgr::GenCacheInitID, PlayerDataMgr::getCacheInitID, GetDBIndex, GetDBNums, PlayerDataMgr::getInitGenIDSql, SeDBQuery::iDBIndex, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, m_kMID2DBIndex, onInitGenID, SDTI_CharNexusFriend, SDTI_NONE, SeLogError, SIGT_NEXUSFRIEND, SIGT_NULL, SPrintf, SQT_NULL.
Referenced by ProcessWB_InitGenID.
bool DBServer::SendDB_CharLoginLoad(SeDBStream &rkDBStream, int iSize)
References SeDBQuery::acSql, SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::GetData, GetDBConnectNums, GetDBIndex, SeDBPlayerMgr::GetDBPlayer, SeDBQuery::iDBIndex, SeDBStream::InitData, SeDBPlayerMgr::IsPlayerLoadComplete, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, POSITIVE_INT, SeDBStream::ReadDword, SAFE_DELETE, SDQT_CHAR_LOGIN_LOAD, SDTI_CharInfo, SeLogError, SendBW_DBQueryRet, SPrintf, SQT_CHAR_LOGIN_LOAD, SeDBStream::WriteDword.
Referenced by ProcessWB_DBQuery.
bool DBServer::SendDB_CharQueryValid(SeDBStream &rkDBStream, int iSize)
References SeDBQuery::acSql, SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::GetData, GetDBConnectNums, GetDBIndex, SeDBPlayerMgr::GetDBPlayer, GetDBTime2Str, SeDBQuery::iDBIndex, SeDBStream::InitData, SeDBPlayerMgr::IsPlayerLoadComplete, SeDBQuery::kString, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, POSITIVE_INT, SeDBStream::ReadDBTime, SeDBStream::ReadDword, SAFE_DELETE, SDQT_CHAR_QUERY_VALID, SDTI_CharInfo, SeLogError, SendBW_DBQueryRet, SPrintf, SQT_CHAR_QUERY_VALID, SeDBStream::WriteDword.
Referenced by ProcessWB_DBQuery.
bool DBServer::SendDB_CharInfoAdd(DWord dwPlayerID, const char *pcAccount, const char *pcName)
References SeDBQuery::acSql, SeDBQuery::dwPlayerID, GetDBConnectNums, GetDBIndex, SeDBQuery::iDBIndex, SeDBQuery::kString, m_kAllDBQuery, m_kDBMgr, NowTime, POSITIVE_INT, SAFE_DELETE, SDTI_CharInfo, SeLogError, SeLogInfo, SendDBLog_SqlLog, SPrintf, SQT_CHAR_INFO_ADD.
Referenced by ProcessDB_IsPlayerExistByAccountOrName.
bool DBServer::SendDB_IsPlayerExistByID(DWord dwPlayerID, SePlayerExistQueryType eType, int iSize, char *pcData)
References SeDBQuery::acSql, SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, GetDBConnectNums, GetDBIndex, SeDBQuery::iDBIndex, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, MemCpy, SeDBQuery::pkVoid, POSITIVE_INT, SAFE_DELETE, SDTI_CharInfo, SeLogError, SPrintf, SQT_CHAR_IS_EXIST_BY_ID.
Referenced by ProcessWB_IsPlayerExist.
bool DBServer::SendDB_IsPlayerExistByName(char *pcStr, SePlayerExistQueryType eType, int iSize, char *pcData, bool bDBServerQuery=false)
References SeDBQuery::acSql, SeDBQuery::apkVoid, SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwParam3, SeDBQuery::dwParam4, SeDBQuery::dwTime, GetDBIndex, GetDBNums, SeDBQuery::iDBIndex, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, MemCpy, SeDBQuery::pkVoid, SDTI_CharInfo, SeLogError, SPrintf, SQT_CHAR_IS_EXIST_BY_ACCOUNT_OR_NAME, SSD_MAX_ACCOUNT.
Referenced by ProcessWB_IsPlayerExist, ProcessWS_CharAdd.
bool DBServer::SendDB_CharRenameBegin(SeDBStream &rkDBStream, int iSize)
References SeDBQuery::acSql, SeDBPlayerMgr::AddCreateQueryName, SeDBQuery::apkVoid, SeDBQuery::dwParam1, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, g_kDBPlayerMgr, SeDBStream::GetCurPos, GetDBIndex, GetDBNums, SeDBQuery::iDBIndex, SeDBQuery::kString, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, SeDBStream::ReadDword, SeDBStream::ReadString, SDTI_CharInfo, SeLogError, SPrintf, SQT_CHAR_RENAME_BEGIN.
Referenced by ProcessWB_DBQuery.
bool DBServer::SendDB_CharRenameEnd(DWord dwPlayerID, const char *pcName)
References SeDBQuery::acSql, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, GetDBIndex, SeDBQuery::iDBIndex, SeDBQuery::kString, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, SDTI_CharInfo, SendDBLog_SqlLog, SPrintf, SQT_CHAR_RENAME_END.
Referenced by ProcessDB_CharRenameBegin.
bool DBServer::SendDB_CharTaskLoad(DWord dwPlayerID)
bool DBServer::SendDB_CharMemoryUpdate(SeDBStream &rkDBStream, int iSize)
References g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::ReadDBTime, SeDBStream::ReadDword, SeLogError, SeDBPlayerMgr::UpdateCharMemoryData.
Referenced by ProcessWB_DBQuery.
bool DBServer::SendDB_CharNexusFriendLoad(DWord dwPlayerID)
References SeDBQuery::acSql, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, GetDBConnectNums, GetDBIndex, SeDBQuery::iDBIndex, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, POSITIVE_INT, SAFE_DELETE, SDTI_CharNexusFriend, SeLogError, SendDBLog_SqlLog, SPrintf, SQT_CHAR_PLAYERNEXUSFRIEND_LOAD.
Referenced by SendDB_LoadInfo.
bool DBServer::SendDB_CharData(SeDBTableIndex eTable, DWord dwPlayerID)
References SeDBQuery::acSql, SeDBQuery::callback, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, GetDBConnectNums, GetDBIndex, GetTableFieldCount, GetTableFieldName, GetTableName, SeDBQuery::iDBIndex, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, onLoadCharData, POSITIVE_INT, SAFE_DELETE, SeLogError, SQT_NULL, StrCpy.
Referenced by PlayerDataStrategy::loadData.
bool DBServer::SendDB_FriendLadderInfoLoad(DWord dwPlayerID, DWord dwFriendID, const SeBBReceipt &eType)
References SeDBQuery::acSql, SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::GetData, GetDBConnectNums, GetDBIndex, SeDBPlayerMgr::GetDBPlayer, SeDBQuery::iDBIndex, SeDBStream::InitData, SeDBPlayerMgr::IsPlayerLoadComplete, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, SeDBPlayer::pkCharInfo, POSITIVE_INT, SAFE_DELETE, SDTI_CharInfo, SeLogError, SendBBL_SelectFriendDataRet, SPrintf, SQT_CHAR_FRIEND_LADDER_LOAD, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by ProcessWB_SelectFriendData.
void DBServer::ProcessDB(int iDB, TeDBResSet &rkResSet)
References SeDBQuery::callback, SeDBQuery::eType, SeDBCallback::execute, m_kAllDBQuery, ProcessDB_CharAdd, ProcessDB_CharFriendLadderLoad, ProcessDB_CharLoginLoad, ProcessDB_CharNexusFriendLoad, ProcessDB_CharNexusFriendOperation, ProcessDB_CharQueryValid, ProcessDB_CharRenameBegin, ProcessDB_CharRenameEnd, ProcessDB_ChraRenameEndQuery, ProcessDB_Common, ProcessDB_IsPlayerExistByAccountOrName, ProcessDB_IsPlayerExistByID, ProcessDB_OperPlayerItem, SQT_CHAR_FRIEND_LADDER_LOAD, SQT_CHAR_INFO_ADD, SQT_CHAR_IS_EXIST_BY_ACCOUNT_OR_NAME, SQT_CHAR_IS_EXIST_BY_ID, SQT_CHAR_LOGIN_LOAD, SQT_CHAR_PLAYERNEXUSFRIEND_LOAD, SQT_CHAR_PLAYERNEXUSFRIEND_OPERATION, SQT_CHAR_QUERY_VALID, SQT_CHAR_RENAME_BEGIN, SQT_CHAR_RENAME_END, SQT_CHAR_RENAME_END_QUERY, SQT_COMMON, SQT_OPER_PLAYER_ITEM.
Referenced by OnDBResponse.
void DBServer::ProcessDB_Common(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::acSql, SeDBQuery::dwPlayerID, SeDBQuery::iDBIndex, m_aiDissconectDBIndex, SeLogError, SetServerErrorCode.
Referenced by ProcessDB.
void DBServer::ProcessDB_DeletePlayerData(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharLoginLoad(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwPlayerID, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SDQT_CHAR_LOGIN_LOAD, SendBW_DBQueryRet, SeDBStream::WriteDword.
Referenced by ProcessDB.
void DBServer::ProcessDB_CharQueryValid(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwPlayerID, SeDBStream::GetCurPos, SeDBStream::GetData, GetDBTime, SeDBStream::InitData, SeDBQuery::kString, SDQT_CHAR_QUERY_VALID, SeLogError, SendBW_DBQueryRet, SeDBStream::WriteDword.
Referenced by ProcessDB.
void DBServer::ProcessDB_CharAdd(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References CCR_CREATE_CHAR_OK, CCR_DB_ERROR, CCR_NAME_EXIST, SeDBPlayerMgr::DelCreateQueryName, SeDBQuery::dwPlayerID, g_kDBPlayerMgr, kName, SBBR_CHAR_ADD, SeLogError, SendBW_DataInsertRet.
Referenced by ProcessDB.
void DBServer::ProcessDB_CharRenameBegin(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::acSql, SeDBQuery::apkVoid, SeDBResult_IsPlayerExist::bExist, SeDBResult::bReturn, SeDBResult::bSuccess, SeDBQuery::dwParam1, SeDBQuery::dwPlayerID, SeDBResult_IsPlayerExist::dwPlayerID, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBQuery::iDBIndex, SeDBStream::InitData, SeDBQuery::kString, SAFE_ARRAY_DELETE, SDQT_CHAR_RENAME, SeLogError, SendBW_DBQueryRet, SendDB_CharRenameEnd, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by ProcessDB.
void DBServer::ProcessDB_CharRenameEnd(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::acSql, SeDBPlayerMgr::AddCharNameRecord, SeDBPlayerMgr::DelCharNameRecord, SeDBQuery::dwParam2, SeDBQuery::dwParam3, SeDBQuery::dwParam4, SeDBQuery::dwPlayerID, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBPlayerMgr::GetDBPlayer, SeDBPlayer::HasLoadFlag, SeDBStream::InitData, SeDBQuery::kString, SeDBPlayer::pkCharInfo, PLF_ALL_FLAG, SDQT_CHAR_RENAME, SeLogError, SendBW_DBQueryRet, SendDB_CharRenameEndQuery, StrCpy, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by ProcessDB.
bool DBServer::SendDB_CharRenameEndQuery(DWord dwPlayerID, const char *pcName)
References SeDBQuery::acSql, SeDBQuery::dwPlayerID, SeDBQuery::dwTime, GetDBIndex, SeDBQuery::iDBIndex, SeDBQuery::kString, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, SDTI_CharInfo, SPrintf, SQT_CHAR_RENAME_END_QUERY.
Referenced by ProcessDB_CharRenameEnd.
void DBServer::ProcessDB_ChraRenameEndQuery(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::acSql, SeDBPlayerMgr::AddCharNameRecord, SeDBPlayerMgr::DelCharNameRecord, SeDBQuery::dwPlayerID, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBPlayerMgr::GetDBPlayer, SeDBStream::InitData, SeDBQuery::kString, PLF_ALL_FLAG, SDQT_CHAR_RENAME, SeLogError, SendBW_DBQueryRet, SPrintf, SSD_MAX_CHAR_NAME, StrCpy, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by ProcessDB.
void DBServer::ProcessDB_IsPlayerExistByID(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwPlayerID, SeDBQuery::pkVoid, SeLogError, SendBW_IsPlayerExistRet, SSD_MAX_CHAR_NAME, StrCpy.
Referenced by ProcessDB.
void DBServer::ProcessDB_IsPlayerExistByAccountOrName(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBResult_IsPlayerExist::acName, SeDBQuery::acSql, SeDBQuery::apkVoid, SeDBStream::Attach, SeDBResult_IsPlayerExist::bExist, SeDBResult::bReturn, SeDBResult::bSuccess, CCR_NAME_EXIST, SeDBPlayerMgr::DelCreateQueryName, SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwParam3, SeDBQuery::dwParam4, SeDBResult_IsPlayerExist::dwPlayerID, g_kDBPlayerMgr, SeDBQuery::iDBIndex, SeDBQuery::pkVoid, SeDBStream::ReadDword, SeDBStream::ReadString, SAFE_ARRAY_DELETE, SBBR_CHAR_ADD, SeLogError, SendBW_DataInsertRet, SendBW_IsPlayerExistRet, SendDB_CharInfoAdd, SSD_MAX_ACCOUNT, SSD_MAX_CHAR_NAME, StrCpy.
Referenced by ProcessDB.
void DBServer::ProcessDB_CharTaskLoad(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharNexusFriendLoad(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBPlayer::akNexusFriend, SeDBQuery::dwPlayerID, g_kDBPlayerMgr, SeDBPlayerMgr::GetDBPlayer, GetDBTime, SeDBPlayer::HasLoadFlag, PLF_CHAR_NEXUSFRIEND, SeDBPlayerMgr::SeLoadingFlag, SeLogError, StrCpy.
Referenced by ProcessDB.
void DBServer::ProcessDB_CharNexusFriendOperation(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError.
Referenced by ProcessDB.
void DBServer::ProcessDB_CharHeroOperation(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError.
void DBServer::ProcessDB_CharFriendLadderLoad(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::dwParam1, SeDBQuery::dwParam2, SeDBQuery::dwPlayerID, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBPlayerMgr::GetDBPlayer, SeDBStream::InitData, SeLogError, SendBBL_SelectFriendDataRet, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by ProcessDB.
void DBServer::ProcessDB_OperPlayerItem(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError.
Referenced by ProcessDB.
bool DBServer::SendBW_RegisterRet(bool bRegisterRet, void *pkReceiver=NULL)
Referenced by ProcessWB_Register.
bool DBServer::SendBW_InitGenIDRet(const SeInitGenIDType &eType, const SeDBTableIndex &eTableIndex, bool bSuccess, DWord dwGenID, void *pkReceiver=NULL)
Referenced by onInitGenID.
bool DBServer::SendBW_DBServerError(int iErrorID, void *pkReceiver=NULL)
Referenced by SetServerErrorCode.
bool DBServer::SendBW_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessWB_HeartPackage.
bool DBServer::SendBW_DataInsertRet(DWord dwID, const SeBBReceipt &eReceipt, DWord dwPara1, void *pkReceiver=NULL)
Referenced by ProcessDB_CharAdd, ProcessDB_IsPlayerExistByAccountOrName, ProcessWS_CharAdd.
bool DBServer::SendBW_DBQueryRet(const SeDBQueryType &eType, int iNowSendNum, bool bSendOver, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by ProcessDB_CharLoginLoad, ProcessDB_CharQueryValid, ProcessDB_CharRenameBegin, ProcessDB_CharRenameEnd, ProcessDB_ChraRenameEndQuery, SendDB_CharLoginLoad, SendDB_CharQueryValid.
bool DBServer::SendBW_DBQueryRet(const SeDBQueryType &eType, int iNowSendNum, bool bSendOver, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBW_IsPlayerExistRet(const SePlayerExistQueryType &eType, bool bExist, DWord dwPlayerID, const char *acName, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by ProcessDB_IsPlayerExistByAccountOrName, ProcessDB_IsPlayerExistByID, ProcessWB_IsPlayerExist.
bool DBServer::SendBW_IsPlayerExistRet(const SePlayerExistQueryType &eType, bool bExist, DWord dwPlayerID, const char *acName, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBW_TabSelectRet(DWord dwQueryID, Byte bySendOver, int iRows, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by onTabSelect.
bool DBServer::SendBW_TabSelectRet(DWord dwQueryID, Byte bySendOver, int iRows, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBWData(void *pkData, int iSize, void *pkReceiver)
References SeServerData::bRegistered, CMD_BW_DBQUERYRET, SeServerData::kSock, m_kNetMgr, m_kWSData, SeLogError, SeCMD::wCmd.
Referenced by Excu_SelectData, SendBBLData.
bool DBServer::ProcessWBData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool DBServer::PreProcessWB(void *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_Register(SeWB_Register *pkData, int iSize, void *pkSender)
References SeServerData::bRegistered, SeServerData::dwRegisterTime, SeWB_Register::dwWorldMagic, SeServerData::kSock, m_dwCurTime, m_kNetMgr, m_kWSData, SendBW_RegisterRet, SSD_MSANGO_MAGIC.
void DBServer::ProcessWB_HeartPackage(SeWB_HeartPackage *pkData, int iSize, void *pkSender)
References SendBW_HeartPackageRet.
void DBServer::ProcessWB_InitGenID(SeWB_InitGenID *pkData, int iSize, void *pkSender)
References SeWB_InitGenID::eTableIndex, SeWB_InitGenID::eType, SendDB_InitGenID.
void DBServer::ProcessWB_DataInsert(SeWB_DataInsert *pkData, int iSize, void *pkSender)
References SeWB_DataInsert::acData, SeWB_DataInsert::dwID, SeWB_DataInsert::dwParam1, SeWB_DataInsert::dwPlayerID, SeWB_DataInsert::eReceipt, SeWB_DataInsert::eTable, g_kDBPlayerMgr, SeDBPlayerMgr::GetDBPlayer, SeWB_DataInsert::iSize, ProcessWS_CharAdd, ProcessWS_Insert_NoReceipt, ProcessWS_Insert_NoReceipt_Offline, SBBR_CHAR_ADD, SBBR_NONE, SeLogError, SSD_ENDSTR_LEN.
void DBServer::ProcessWB_DataUpdate(SeWB_DataUpdate *pkData, int iSize, void *pkSender)
References SeWB_DataUpdate::acData, SeWB_DataUpdate::dwID, SeWB_DataUpdate::dwParam1, SeWB_DataUpdate::dwPlayerID, SeWB_DataUpdate::eReceipt, SeWB_DataUpdate::eTable, SeWB_DataUpdate::iSize, ProcessWS_Update_NoReceipt, SBBR_NONE, SeLogError, SSD_ENDSTR_LEN.
void DBServer::ProcessWB_DataDiscard(SeWB_DataDiscard *pkData, int iSize, void *pkSender)
References SeWB_DataDiscard::dwID, SeWB_DataDiscard::dwPlayerID, SeWB_DataDiscard::eTable, g_kDBPlayerMgr, SeWB_DataDiscard::iDeleteReason, SeWB_DataDiscard::kDeleteTime, SeDBPlayerMgr::OnDataDiscard.
void DBServer::ProcessWB_DataDelete(SeWB_DataDelete *pkData, int iSize, void *pkSender)
References SeWB_DataDelete::dwID, SeWB_DataDelete::dwPlayerID, SeWB_DataDelete::eTable, g_kDBPlayerMgr, SeDBPlayerMgr::OnDataDelete.
void DBServer::ProcessWB_PlayerLoad(SeWB_PlayerLoad *pkData, int iSize, void *pkSender)
References SeDBPlayerMgr::DBPlayerLoad, SeWB_PlayerLoad::dwPlayerID, g_kDBPlayerMgr, SeDBPlayerMgr::SetDBPlayerOnline.
void DBServer::ProcessWB_SelectData(SeWB_SelectData *pkData, int iSize, void *pkSender)
References SeWB_SelectData::aiIndex, SeWB_SelectData::dwID, SeWB_SelectData::eReceipt, SeWB_SelectData::eTable, Excu_SelectData, SeWB_SelectData::iNum, SeLogError, SSD_MAX_SEND_SIZE.
void DBServer::ProcessWB_PlayerOffLine(SeWB_PlayerOffLine *pkData, int iSize, void *pkSender)
References SeWB_PlayerOffLine::dwPlayerID, g_kDBPlayerMgr, SeDBPlayerMgr::SetDBPlayerOnline.
void DBServer::ProcessWB_DBQuery(SeWB_DBQuery *pkData, int iSize, void *pkSender)
References SeWB_DBQuery::acData, SeDBStream::Attach, SeWB_DBQuery::eType, SeWB_DBQuery::iSize, SDQT_CHAR_LOGIN_LOAD, SDQT_CHAR_MEMORY_UPDATE, SDQT_CHAR_QUERY_VALID, SDQT_CHAR_RENAME, SeLogError, SendDB_CharLoginLoad, SendDB_CharMemoryUpdate, SendDB_CharQueryValid, SendDB_CharRenameBegin, SSD_ENDSTR_LEN, SSD_MAX_SEND_SIZE.
void DBServer::ProcessWB_IsPlayerExist(SeWB_IsPlayerExist *pkData, int iSize, void *pkSender)
References SeWB_IsPlayerExist::acAccount, SeWB_IsPlayerExist::acData, SeDBStream::Attach, SeWB_IsPlayerExist::eType, g_kDBPlayerMgr, SeDBPlayerMgr::GetDBPlayer, SeDBPlayerMgr::GetDBPlayerByName, SeWB_IsPlayerExist::iSize, SeDBPlayerMgr::IsPlayerLoadComplete, SeDBPlayer::pkCharInfo, SeDBStream::ReadDword, SeDBStream::ReadString, SeLogError, SendBW_IsPlayerExistRet, SendDB_IsPlayerExistByID, SendDB_IsPlayerExistByName, SPEQ_CHAR_CHECK_NAME, SPEQ_CHAR_QUERY_NAME_BY_NAME, SPEQ_CHAR_QUERY_NAME_BY_USERID, SSD_ENDSTR_LEN, SSD_MAX_CHAR_NAME, SSD_MAX_SEND_SIZE, StrCpy.
void DBServer::ProcessWB_LoadPlayerInfoAgain(SeWB_LoadPlayerInfoAgain *pkData, int iSize, void *pkSender)
References SeWB_LoadPlayerInfoAgain::akPlayerInfo, SeDBPlayerMgr::DBPlayerLoad, g_kDBPlayerMgr, SeDBPlayerMgr::GetDBPlayer, SeWB_LoadPlayerInfoAgain::iBegin, SeWB_LoadPlayerInfoAgain::iNum, SeDBPlayerMgr::IsPlayerLoadComplete, SeWB_LoadPlayerInfoAgain::iTotalNum, SeLogError, SeLogInfo, SeDBPlayerMgr::SetDBPlayerOnline.
void DBServer::ProcessWB_TabSelect(SeWB_TabSelect *pkData, int iSize, void *pkSender)
References SeWB_TabSelect::acData, SeDBQuery::acSql, appendWhereClause, SeDBStream::Attach, SeDBQuery::callback, SeWB_TabSelect::dwQueryID, SeDBQuery::dwTime, SeWB_TabSelect::eTable, g_kDBServer, GetDBIndex, GetFieldFormat, GetTableFieldName, GetTableName, SeDBQuery::iDBIndex, SeWB_TabSelect::iSize, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, onTabSelect, SeDBStream::ReadDword, SeLogError, SPrintf, SQT_NULL.
void DBServer::ProcessWB_TabUpdate(SeWB_TabUpdate *pkData, int iSize, void *pkSender)
References SeWB_TabUpdate::acData, SeDBQuery::acSql, appendWhereClause, SeDBStream::Attach, SeDBQuery::callback, SeDBQuery::dwTime, SeWB_TabUpdate::eTable, g_kDBServer, GetDBIndex, GetFieldFormat, GetTableFieldName, GetTableName, SeDBQuery::iDBIndex, SeWB_TabUpdate::iSize, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, onTabModify, SeDBStream::ReadDword, SeDBStream::ReadVariant, SeLogError, SFF_NULL, SPrintf, SQT_NULL.
void DBServer::ProcessWB_TabInsert(SeWB_TabInsert *pkData, int iSize, void *pkSender)
References SeWB_TabInsert::acData, SeDBQuery::acSql, SeDBStream::Attach, SeDBQuery::callback, SeDBQuery::dwTime, SeWB_TabInsert::eTable, g_kDBServer, GetDBIndex, GetFieldFormat, GetTableFieldName, GetTableName, SeDBQuery::iDBIndex, SeWB_TabInsert::iSize, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, onTabModify, SeDBStream::ReadDword, SeDBStream::ReadVariant, SeLogError, SFF_NULL, SPrintf, SQT_NULL.
void DBServer::ProcessWB_TabDelete(SeWB_TabDelete *pkData, int iSize, void *pkSender)
References SeWB_TabDelete::acData, SeDBQuery::acSql, appendWhereClause, SeDBStream::Attach, SeDBQuery::callback, SeDBQuery::dwTime, SeWB_TabDelete::eTable, g_kDBServer, GetDBIndex, GetTableName, SeDBQuery::iDBIndex, SeWB_TabDelete::iSize, m_dwCurTime, m_kAllDBQuery, m_kDBMgr, onTabModify, SeLogError, SPrintf, SQT_NULL.
void DBServer::ProcessWB_SelectFriendData(SeWB_SelectFriendData *pkData, int iSize, void *pkSender)
References SeWB_SelectFriendData::dwID, SeWB_SelectFriendData::dwIDList, SeWB_SelectFriendData::eType, SeWB_SelectFriendData::iSize, SBBR_LOAD_FRIEND_LADDER, SBBR_LOAD_ONE_FRIEND_LADDER, SeLogError, SendDB_FriendLadderInfoLoad, SSD_MAX_SEND_SIZE.
void DBServer::ProcessWS_Insert_NoReceipt(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iSize, char *pkData)
References SeDBStream::Attach, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBPlayerMgr::GetDBPlayer, GetFieldFormat, SeDBPlayerMgr::IsPlayerLoadComplete, SeDBPlayerMgr::OnDataInsert, SeDBStream::ReadDBTime, SeDBStream::ReadDoubleDword, SeDBStream::ReadDword, SeDBStream::ReadString, SeLogError, SFF_DATETIME, SFF_NUM, SFF_NUM64, SFF_STRING.
Referenced by ProcessWB_DataInsert.
void DBServer::ProcessWS_Update_NoReceipt(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iSize, char *pkData, DWord dwPara1)
References SeDBStream::Attach, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBPlayerMgr::GetDBPlayer, GetFieldFormat, SeDBPlayerMgr::IsPlayerLoadComplete, SeDBPlayerMgr::OnDataUpdateNum, SeDBPlayerMgr::OnDataUpdateNum64, SeDBPlayerMgr::OnDataUpdateString, SeDBPlayerMgr::OnDataUpdateTime, SeDBStream::ReadDBTime, SeDBStream::ReadDoubleDword, SeDBStream::ReadDword, SeDBStream::ReadString, SeLogError, SFF_DATETIME, SFF_NUM, SFF_NUM64, SFF_STRING.
Referenced by ProcessWB_DataUpdate.
void DBServer::Excu_SelectData(DWord dwPlayerID, SeDBTableIndex eTable, SeBBReceipt eReceipt, int iNum, int *piIndex)
References SeBBL_SelectDataRet::acData, SeBBL_SelectDataRet::bySendOver, SeBBL_SelectDataRet::dwPlayerID, SeBBL_SelectDataRet::eReceipt, SeBBL_SelectDataRet::eTable, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBPlayerMgr::GetDBPlayer, GetFieldFormat, GetPlayerFieldDate, GetPlayerFieldNum, GetPlayerFieldNum64, GetPlayerFieldStr, GetPlayerRecordCount, SeDBStream::InitData, SeBBL_SelectDataRet::iSendNum, SeBBL_SelectDataRet::iSize, SeDBPlayerMgr::IsPlayerLoadComplete, m_acSend, MemCpy, MNew, RECORDCOUNT_OFFSET, SeLogError, SendBWData, SFF_DATETIME, SFF_NUM, SFF_NUM64, SFF_STRING, SSD_ENDSTR_LEN, SSD_MAX_SEND_SIZE, SeDBStream::WriteDBTime, SeDBStream::WriteDoubleDword, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by ProcessWB_SelectData.
void DBServer::ProcessWS_CharAdd(DWord dwPlayerID, SeDBTableIndex eTable, DWord dwlID, SeBBReceipt eReceipt, int iSize, char *pkData)
References SeDBPlayerMgr::AddCreateQueryName, SeDBStream::Attach, CCR_NAME_EXIST, g_kDBPlayerMgr, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SeDBPlayerMgr::IsRepeatName, SeDBStream::ReadDword, SeDBStream::ReadString, SBBR_CHAR_ADD, SeLogError, SendBW_DataInsertRet, SendDB_IsPlayerExistByName, SPEQ_NULL, SSD_MAX_ACCOUNT, SSD_MAX_CHAR_NAME, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by ProcessWB_DataInsert.
void DBServer::ProcessWS_Insert_NoReceipt_Offline(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iSize, char *pkData)
References ProcessWS_Insert_NoReceipt_Offline_NexusFriend, SDTI_CharNexusFriend.
Referenced by ProcessWB_DataInsert.
void DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iSize, char *pkData)
References SeDBStream::Attach, SeDBPlayerMgr::CreateDBPlayer_Offline, g_kDBPlayerMgr, g_kDBServer, SeDBStream::GetCurPos, GetDBConnectNums, GetDBIndex, GetFieldFormat, SeDBStream::ReadDBTime, SeDBStream::ReadDoubleDword, SeDBStream::ReadDword, SeDBStream::ReadString, SCT_INSERT, SDTI_CharNexusFriend, SeLogError, SFF_DATETIME, SFF_NUM, SFF_NUM64, SFF_STRING.
Referenced by ProcessWS_Insert_NoReceipt_Offline.
bool DBServer::SendBBL_PlayerLoadRet(DWord dwPlayerID, bool bLoadSuc, void *pkReceiver=NULL)
Referenced by SeDBPlayerMgr::DBPlayerLoad, SeDBPlayerMgr::onLoadingComplete.
bool DBServer::SendBBL_SelectDataRet(DWord dwPlayerID, const SeDBTableIndex &eTable, const SeBBReceipt &eReceipt, Byte bySendOver, int iSendNum, int iSize, const char *acData, void *pkReceiver=NULL)
bool DBServer::SendBBL_SelectDataRet(DWord dwPlayerID, const SeDBTableIndex &eTable, const SeBBReceipt &eReceipt, Byte bySendOver, int iSendNum, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBBL_SelectFriendDataRet(DWord dwPlayerID, DWord dwFriendID, const SeBBReceipt &eReceipt, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by ProcessDB_CharFriendLadderLoad, SendDB_FriendLadderInfoLoad.
bool DBServer::SendBBL_SelectFriendDataRet(DWord dwPlayerID, DWord dwFriendID, const SeBBReceipt &eReceipt, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBBLData(void *pkData, int iSize, void *pkReceiver)
References SendBWData.
bool DBServer::ProcessBLBData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool DBServer::PreProcessBLB(void *pkData, int iSize, void *pkSender)
DBServer::DBServer(void)
DBServer::~DBServer(void)
bool DBServer::Initialize(void)
void DBServer::Update(void)
void DBServer::Finialize(void)
void DBServer::ShowConsoleTitle(int iDTime)
SeServerActionResult DBServer::ExecuteAction(SeServerActionIndex eActionIndex)
virtual void DBServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
virtual void DBServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
virtual void DBServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
virtual void DBServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
virtual void DBServer::OnDBResponse(int iDB, TeDBResSet &rkResSet)
DWord DBServer::GetServerTime(void)
void DBServer::SetMaxCacheNums(int iNums)
int DBServer::GetMaxCacheNums()
DWord DBServer::GetSaveSpaceTime()
void DBServer::SetServerErrorCode(int iErrorCode)
bool DBServer::GetServerDBError(void)
int DBServer::GetDBQueryNums()
void DBServer::SetMaxDBQueryNums(int iNums)
int DBServer::GetMaxDBQueryNums()
void DBServer::SetLoginLogInfo(DWord dwCount, DWord dwCousumeTime)
int DBServer::GetLogShowType(void)
void DBServer::WriteLogUpdate(void)
bool DBServer::SendDBLog_SqlLog(int iDBIndex, const char *pcSql)
SeDBTableIndex DBServer::GetTableIndex(const char *pcTableName)
const char* DBServer::GetTableName(SeDBTableIndex eTable)
const char* DBServer::GetTableFieldName(SeDBTableIndex eTable, int fieldIndex)
int DBServer::GetTableFieldCount(SeDBTableIndex eTable)
int DBServer::GetDBConnectNums(int iDBIndex)
int DBServer::GetGMDBConnect(SeDBTableIndex eTableIndex)
int DBServer::GetDBIndex(DWord dwID, SeDBTableIndex eTableIndex)
int DBServer::GetDBNums(SeDBTableIndex eTableIndex)
void DBServer::PushDBQuery(DWord dwKey, SeDBQuery *pkQuery)
DWord DBServer::PostExecutSQL(int iDB, const char *pcSql, UInt uiHash=0, int iExeFlag=0)
SeFieldFormat DBServer::GetFieldFormat(SeDBTableIndex eTable, int iIndex)
DWord DBServer::GetPlayerFieldNum(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, int iIndex, int iCount, uint64_t dwlID=0, DWord dwPara1=0)
uint64_t DBServer::GetPlayerFieldNum64(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, int iIndex, int iCount, uint64_t dwlID=0, DWord dwPara1=0)
SeDBTime DBServer::GetPlayerFieldDate(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, int iIndex, DWord iCount)
const char* DBServer::GetPlayerFieldStr(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, int iIndex, DWord iCount)
bool DBServer::SendDB_LoadInfo(DWord dwID)
bool DBServer::SendDB_InitGenID(SeInitGenIDType eType, SeDBTableIndex eTableIndex)
bool DBServer::SendDB_CharLoginLoad(SeDBStream &rkDBStream, int iSize)
bool DBServer::SendDB_CharQueryValid(SeDBStream &rkDBStream, int iSize)
bool DBServer::SendDB_CharInfoAdd(DWord dwPlayerID, const char *pcAccount, const char *pcName)
bool DBServer::SendDB_IsPlayerExistByID(DWord dwPlayerID, SePlayerExistQueryType eType, int iSize, char *pcData)
bool DBServer::SendDB_IsPlayerExistByName(char *pcStr, SePlayerExistQueryType eType, int iSize, char *pcData, bool bDBServerQuery=false)
bool DBServer::SendDB_CharRenameBegin(SeDBStream &rkDBStream, int iSize)
bool DBServer::SendDB_CharRenameEnd(DWord dwPlayerID, const char *pcName)
bool DBServer::SendDB_CharTaskLoad(DWord dwPlayerID)
bool DBServer::SendDB_CharMemoryUpdate(SeDBStream &rkDBStream, int iSize)
bool DBServer::SendDB_CharNexusFriendLoad(DWord dwPlayerID)
bool DBServer::SendDB_CharData(SeDBTableIndex eTable, DWord dwPlayerID)
bool DBServer::SendDB_FriendLadderInfoLoad(DWord dwPlayerID, DWord dwFriendID, const SeBBReceipt &eType)
void DBServer::ProcessDB(int iDB, TeDBResSet &rkResSet)
void DBServer::ProcessDB_Common(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_DeletePlayerData(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharLoginLoad(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharQueryValid(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharAdd(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharRenameBegin(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharRenameEnd(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
bool DBServer::SendDB_CharRenameEndQuery(DWord dwPlayerID, const char *pcName)
void DBServer::ProcessDB_ChraRenameEndQuery(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_IsPlayerExistByID(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_IsPlayerExistByAccountOrName(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharTaskLoad(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharNexusFriendLoad(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharNexusFriendOperation(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharHeroOperation(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_CharFriendLadderLoad(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void DBServer::ProcessDB_OperPlayerItem(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
bool DBServer::SendBW_RegisterRet(bool bRegisterRet, void *pkReceiver=NULL)
bool DBServer::SendBW_InitGenIDRet(const SeInitGenIDType &eType, const SeDBTableIndex &eTableIndex, bool bSuccess, DWord dwGenID, void *pkReceiver=NULL)
bool DBServer::SendBW_DBServerError(int iErrorID, void *pkReceiver=NULL)
bool DBServer::SendBW_HeartPackageRet(void *pkReceiver=NULL)
bool DBServer::SendBW_DataInsertRet(DWord dwID, const SeBBReceipt &eReceipt, DWord dwPara1, void *pkReceiver=NULL)
bool DBServer::SendBW_DBQueryRet(const SeDBQueryType &eType, int iNowSendNum, bool bSendOver, int iSize, const char *acData, void *pkReceiver=NULL)
bool DBServer::SendBW_DBQueryRet(const SeDBQueryType &eType, int iNowSendNum, bool bSendOver, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBW_IsPlayerExistRet(const SePlayerExistQueryType &eType, bool bExist, DWord dwPlayerID, const char *acName, int iSize, const char *acData, void *pkReceiver=NULL)
bool DBServer::SendBW_IsPlayerExistRet(const SePlayerExistQueryType &eType, bool bExist, DWord dwPlayerID, const char *acName, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBW_TabSelectRet(DWord dwQueryID, Byte bySendOver, int iRows, int iSize, const char *acData, void *pkReceiver=NULL)
bool DBServer::SendBW_TabSelectRet(DWord dwQueryID, Byte bySendOver, int iRows, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBWData(void *pkData, int iSize, void *pkReceiver)
bool DBServer::ProcessWBData(void *pkData, int iSize, void *pkSender=NULL)
bool DBServer::PreProcessWB(void *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_Register(SeWB_Register *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_HeartPackage(SeWB_HeartPackage *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_InitGenID(SeWB_InitGenID *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_DataInsert(SeWB_DataInsert *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_DataUpdate(SeWB_DataUpdate *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_DataDiscard(SeWB_DataDiscard *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_DataDelete(SeWB_DataDelete *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_PlayerLoad(SeWB_PlayerLoad *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_SelectData(SeWB_SelectData *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_PlayerOffLine(SeWB_PlayerOffLine *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_DBQuery(SeWB_DBQuery *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_IsPlayerExist(SeWB_IsPlayerExist *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_LoadPlayerInfoAgain(SeWB_LoadPlayerInfoAgain *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_TabSelect(SeWB_TabSelect *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_TabUpdate(SeWB_TabUpdate *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_TabInsert(SeWB_TabInsert *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_TabDelete(SeWB_TabDelete *pkData, int iSize, void *pkSender)
void DBServer::ProcessWB_SelectFriendData(SeWB_SelectFriendData *pkData, int iSize, void *pkSender)
void DBServer::ProcessWS_Insert_NoReceipt(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iSize, char *pkData)
void DBServer::ProcessWS_Update_NoReceipt(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iSize, char *pkData, DWord dwPara1)
void DBServer::Excu_SelectData(DWord dwPlayerID, SeDBTableIndex eTable, SeBBReceipt eReceipt, int iNum, int *piIndex)
void DBServer::ProcessWS_CharAdd(DWord dwPlayerID, SeDBTableIndex eTable, DWord dwlID, SeBBReceipt eReceipt, int iSize, char *pkData)
void DBServer::ProcessWS_Insert_NoReceipt_Offline(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iSize, char *pkData)
void DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iSize, char *pkData)
bool DBServer::SendBBL_PlayerLoadRet(DWord dwPlayerID, bool bLoadSuc, void *pkReceiver=NULL)
bool DBServer::SendBBL_SelectDataRet(DWord dwPlayerID, const SeDBTableIndex &eTable, const SeBBReceipt &eReceipt, Byte bySendOver, int iSendNum, int iSize, const char *acData, void *pkReceiver=NULL)
bool DBServer::SendBBL_SelectDataRet(DWord dwPlayerID, const SeDBTableIndex &eTable, const SeBBReceipt &eReceipt, Byte bySendOver, int iSendNum, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBBL_SelectFriendDataRet(DWord dwPlayerID, DWord dwFriendID, const SeBBReceipt &eReceipt, int iSize, const char *acData, void *pkReceiver=NULL)
bool DBServer::SendBBL_SelectFriendDataRet(DWord dwPlayerID, DWord dwFriendID, const SeBBReceipt &eReceipt, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool DBServer::SendBBLData(void *pkData, int iSize, void *pkReceiver)
bool DBServer::ProcessBLBData(void *pkData, int iSize, void *pkSender=NULL)
bool DBServer::PreProcessBLB(void *pkData, int iSize, void *pkSender)
bool DBServer::LoadConfig(const char *pcFile)
References SeDBTableInfo::acDBTableName, DBPLAYER_CACHE_MAX_NUMS, SeDBServerConfig::dwServerID, g_kDBPlayerMgr, GetAString, SeConfig::GetDBTableAddrFromStr, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeDBTableInfo::iDBNums, SeDBServerConfig::iMaxCacheNums, SeDBServerConfig::iMaxDBQueryNum, SeDBServerConfig::kLocalServer, SeDBTableInfo::kVDBAddr, SeDBServerConfig::kVDBInfo, SeConfig::Load, LoadDynamicConfig, m_acSqlLogPath, m_dwSaveSpaceTime, m_kConfig, MkDir, SeLogError, SeLogInfo, SeDBPlayerMgr::SetCycleNums, SeDBPlayerMgr::SetCyclePlayerNums, StrCpy.
Referenced by Initialize.
void DBServer::LoadDynamicConfig(void)
References SeDBPlayerMgr::AddClearPlayerID, g_kDBPlayerMgr, SeConfig::GetValue, SeDBServerConfig::iLogShowType, SeConfig::Load, m_kConfig, SeLogError.
Referenced by ExecuteAction, LoadConfig.
bool DBServer::InitializeDB(void)
References SeDBTableAddr::acDBName, SeDBTableAddr::acDBPassword, SeDBTableInfo::acDBTableName, SeDBTableAddr::acDBUser, SeDBTableAddr::acIP, GetGMDBConnect, GetTableIndex, SeDBTableAddr::iPort, SeDBTableAddr::iThreadNums, SeDBTableInfo::kVDBAddr, SeDBServerConfig::kVDBInfo, m_kConfig, m_kDBMgr, m_kMID2DBConnectNums, m_kMID2DBIndex, m_kMID2DBName, SDTI_NONE, SeLogError, SeLogInfo.
Referenced by Initialize.
bool DBServer::InitializeNet(void)
References SeNetAddr::acIP, SeNetAddr::iPort, SeDBServerConfig::kLocalServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo, SERVER_BUFFER_SIZE.
Referenced by Initialize.
bool DBServer::InitDBMem(void)
References g_kPlayerDataMgr, IniMemCheckOut, PlayerDataMgr::initialize, RebuildMem, SeLogError.
Referenced by Initialize.
bool DBServer::IniMemCheckOut()
Referenced by InitDBMem.
bool DBServer::RebuildMem(void)
References SeDBMemMgr::AddAllocSize, SeEleMass::dwEleNum, SeEleMass::dwEleSize, SeEleMass::dwMagic, SeEleMass::dwSize, SeEleMass::dwTag, g_kDBMemMgr, g_kDBPlayerMgr, g_kPlayerDataMgr, SeDBMemMgr::GetAllocSize, SeDBMemMgr::GetEleMassAddr, GetID2Str, SeDBMemMgr::GetMemTag, SeDBMemMgr::GetMinMemSize, SeDBMemMgr::GetTotalSize, SeDBPlayerMgr::RebuildDBCharMemory, SeDBPlayerMgr::RebuildDBCharNexusFriend, SeDBPlayerMgr::RebuildDBCharTask, PlayerDataMgr::rebuildMem, SeLogError, SeLogInfo.
Referenced by InitDBMem.
void DBServer::UpdateDissconectDB(void)
References GetServerDBError, GetServerTime, m_aiDissconectDBIndex, m_kDBMgr, SeLogInfo, SetServerErrorCode.
Referenced by Update.
void DBServer::UpdateLogShow(void)
References GetServerTime, SeDBServerConfig::iLogShowType, m_dwLoadCount, m_dwLoadSumTime, m_kConfig, SeLogInfo.
Referenced by Update.
std::vector< int > DBServer::GetPlayerRecordCount(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable)
References SeDBPlayer::akNexusFriend, SeDBPlayer::akTask, g_kDBPlayerMgr, g_kPlayerDataMgr, SeDBPlayerMgr::GetCharMemoryCount, PlayerDataMgr::getRecordCount, SeDBPlayerMgr::IsPlayerLoadComplete, SeDBPlayer::pkCharInfo, SDTI_CharMemory, SDTI_CharNexusFriend, SDTI_CharTask, SeLogError.
Referenced by Excu_SelectData.
const void * DBServer::GetPlayerFieldData(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1)
References SeDBPlayer::akNexusFriend, SeDBPlayer::akTask, g_kDBPlayerMgr, g_kPlayerDataMgr, SeDBPlayerMgr::GetCharMemoryByIndex, PlayerDataMgr::getFieldData, SeDBPlayerMgr::IsPlayerLoadComplete, SeDBPlayer::pkCharInfo, RECORDCOUNT_OFFSET, SDTI_CharMemory, SDTI_CharNexusFriend, SDTI_CharTask, SeLogError, SFF_DATETIME, SFF_NUM, SFF_NUM64, SFF_STRING.
Referenced by GetPlayerFieldDate, GetPlayerFieldNum, GetPlayerFieldNum64, GetPlayerFieldStr.
void DBServer::PrintUpdateTime(DWord *pdwDecTime, int iNums)
References CharToFileFun, GetLocalTime, SPrintf.
Referenced by Update.
void DBServer::OnPrintfNetState(void)
References SeFlux::aiWSConsumeTime, SeFlux::aiWSCountProcess, SeFlux::aiWSProcess, CharToFileFun, GetLocalTime, m_kFlux, SPrintf.
Referenced by Update.
void DBServer::SaveSqlLog2File(const char *pcSql, SeDBTime &rkLogTime, const char *pcDBName)
References SeSqlLogCache::acLogBuffer, AddDBTime, SeDBTime::iDay, SeDBTime::iHour, SeSqlLogCache::iLogRecvCount, SeSqlLogCache::iLogSize, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear, m_acSqlLogPath, m_kSqlLog, MAX_LOG_SIZE, MAX_SQL_SIZE, MkDir, SeLogError, SPrintf.
Referenced by WriteLogUpdate.
void DBServer::UpdateSqlLog2File(void)
References SeSqlLogCache::acLogBuffer, AddDBTime, SeDBTime::iDay, SeDBTime::iHour, SeSqlLogCache::iLogSize, SeDBTime::iMonth, SeDBTime::iYear, m_acSqlLogPath, m_kHourDBTime, m_kSqlLog, MkDir, NowTime, SPrintf.
Referenced by WriteLogUpdate.
bool DBServer::LoadConfig(const char *pcFile)
void DBServer::LoadDynamicConfig(void)
bool DBServer::InitializeDB(void)
bool DBServer::InitializeNet(void)
bool DBServer::InitDBMem(void)
bool DBServer::IniMemCheckOut()
bool DBServer::RebuildMem(void)
void DBServer::UpdateDissconectDB(void)
void DBServer::UpdateLogShow(void)
std::vector<int> DBServer::GetPlayerRecordCount(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable)
const void* DBServer::GetPlayerFieldData(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTalbe, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1)
void DBServer::PrintUpdateTime(DWord *pdwDecTime, int iNums)
void DBServer::OnPrintfNetState(void)
void DBServer::SaveSqlLog2File(const char *pcSql, SeDBTime &rkLogTime, const char *pcDBName)
void DBServer::UpdateSqlLog2File(void)