TcpServer
DWord TcpServer::m_dwCurTime
Referenced by GetServerTime, TcpServer, Update.
DWord TcpServer::m_dwTickCount
Referenced by Initialize, TcpServer, Update.
SeSvrConfig TcpServer::m_kConfig
Referenced by ConnectToParent, DisconnectPlayerSock, InitializeNet, LoadConfig, LoadDynamicConfig, OnNetAccept, OnNetConnected, SendParent_Register, ShowConsoleTitle, UpdateClientHeart, UpdateConnect, UpdateParentHeart.
DWord TcpServer::m_dwClientGenID
Referenced by GenClientID, TcpServer.
DWord TcpServer::m_dwCheckConnectTime
Referenced by TcpServer, UpdateClientHeart, UpdateConnect.
TeNetMgr TcpServer::m_kNetMgr
Referenced by ConnectToParent, DisconnectPlayerSock, Finialize, InitializeNet, OnNetAccept, OnNetRecv, ProcessParent_SendData, SendTTData, Update, UpdateParentHeart.
SeServerData TcpServer::m_kParentData
Referenced by ConnectToParent, OnNetAccept, OnNetConnected, OnNetDisconnect, OnNetRecv, ProcessParent, ProcessParent_RegisterRet, RegisterToParent, SendTTData, UpdateParentHeart, UpdateState.
MapAllConnect TcpServer::m_kMapSock
Referenced by AddConnect, DelConnect, FindConnect, ProcessParent_RegisterRet, ShowConsoleTitle, UpdateClientHeart, UpdateConnect.
MapAllConnectByID TcpServer::m_kMapID
Referenced by AddConnect, DelConnect, FindConnect, ShowConsoleTitle.
MapIPCount TcpServer::m_kIPCount
Referenced by OnNetAccept, OnNetDisconnect.
TcpServer::TcpServer(void)
References m_dwCheckConnectTime, m_dwClientGenID, m_dwCurTime, m_dwTickCount.
TcpServer::~TcpServer(void)
References Finialize.
bool TcpServer::Initialize()
References InitializeNet, LoadConfig, LoadDynamicConfig, m_dwTickCount.
void TcpServer::Update(void)
References m_dwCurTime, m_dwTickCount, m_kNetMgr, UpdateClientHeart, UpdateParentHeart, UpdateState.
void TcpServer::Finialize(void)
References m_kNetMgr.
Referenced by ~TcpServer.
void TcpServer::ShowConsoleTitle(int iDTime)
References SeSvrConfig::dwServerID, GetID2Str, m_kConfig, m_kMapID, m_kMapSock, SPrintf.
SeServerActionResult TcpServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F5, LoadDynamicConfig, SeLogHideTime, SeLogInfo.
void TcpServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeServerData::bConnecting, SeNetAddr::iPort, SeSvrConfig::kParentServer, SeServerData::kSock, m_kConfig, m_kParentData, SeLogError, SeLogInfo.
void TcpServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, AddConnect, SeServerData::bRegistered, SeConnect::dwAccountID, SeConnect::dwClientID, SeConnect::dwLastRecvTime, SeConnect::dwStateTime, SeConnect::eState, GenClientID, GetServerTime, SeNetAddr::iPort, SeSvrConfig::iSameIPConnect, SeConnect::kNetAddr, SeConnect::kSock, m_kConfig, m_kIPCount, m_kNetMgr, m_kParentData, SCS_UNKOWN, SeLogInfo, SendParent_ClientConnect, StrCpy.
void TcpServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References SeConnect::dwClientID, SeConnect::dwLastRecvTime, SeConnect::dwPackCount, SeConnect::dwPackSize, FindConnect, GetServerTime, SeServerData::kSock, m_kNetMgr, m_kParentData, ProcessParent, SendParent_RecvData.
void TcpServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, SeServerData::bRegistered, DelConnect, SeConnect::dwClientID, SeServerData::dwRegisterTime, FindConnect, GetServerTime, SeConnect::kNetAddr, SeServerData::kSock, m_kIPCount, m_kParentData, SeLogInfo, SendParent_ClientDisconnect.
bool TcpServer::SendTTData(void *pkData, int iSize)
References SeServerData::kSock, m_kNetMgr, m_kParentData, SeLogError, SeCMD::wCmd.
Referenced by SendParent_ClientConnect, SendParent_ClientDisconnect, SendParent_HeartPackage, SendParent_RecvData, SendParent_Register, SendParent_ReLoadReadyID.
bool TcpServer::SendParent_Register()
References SeSvrConfig::dwServerID, SeTT_Register::dwServerID, SeSvrConfig::kLocalServer, SeTT_Register::kTCPAddr, m_kConfig, SendTTData.
Referenced by RegisterToParent.
bool TcpServer::SendParent_ReLoadReadyID(bool bOver, int iDataLen, const char *acData)
References SeTT_ReLoadReadyID::acData, SeTT_ReLoadReadyID::bOver, SeTT_ReLoadReadyID::iDataLen, MemCpy, MNew, SendTTData, SSD_ENDSTR_LEN, SSD_MAX_SEND_SIZE, SSD_SEND_SIZE.
Referenced by ProcessParent_RegisterRet.
bool TcpServer::SendParent_ClientConnect(DWord dwClientID, const char *acIP, int iPort)
References SeTT_ClientConnect::acIP, SeTT_ClientConnect::dwClientID, SeTT_ClientConnect::iPort, SendTTData, StrCpy.
Referenced by OnNetAccept.
bool TcpServer::SendParent_ClientDisconnect(DWord dwClientID)
References SeTT_ClientDisconnect::dwClientID, SendTTData.
Referenced by OnNetDisconnect.
bool TcpServer::SendParent_RecvData(DWord dwClientID, int iSize, void *pkData)
References SeTT_RecvData::acData, SeTT_RecvData::dwClientID, SeTT_RecvData::iDataLen, MemCpy, MNew, SendTTData, SSD_ENDSTR_LEN, SSD_MAX_SEND_SIZE, SSD_SEND_SIZE.
Referenced by OnNetRecv.
bool TcpServer::SendParent_HeartPackage(void)
References SendTTData.
Referenced by UpdateParentHeart.
bool TcpServer::LoadConfig(const char *pcFile)
References SeSvrConfig::dwServerID, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeSvrConfig::kLocalServer, SeSvrConfig::kParentServer, SeConfig::Load, m_kConfig, SeLogError.
Referenced by Initialize.
void TcpServer::LoadDynamicConfig(void)
References SeSvrConfig::bAllFileLog, SeSvrConfig::bAutoExpireLog, SeSvrConfig::bConnectHeartCheck, SeSvrConfig::bDayFile, SeSvrConfig::bOldHeartPackRet, SeSvrConfig::bShowDisconnectLog, SeSvrConfig::dwConnectHeartTime, SeSvrConfig::dwHeartPackageTime, SeSvrConfig::dwHeartPackReplyTime, SeSvrConfig::dwMaxConnectNum, SeConfig::GetValue, SeSvrConfig::iExpireLogDays, SeSvrConfig::iSameIPConnect, SeConfig::Load, m_kConfig, SeLogError, SeLogInfo.
Referenced by ExecuteAction, Initialize.
bool TcpServer::InitializeNet(void)
References SeNetAddr::acIP, CLIENT_BUFFER_SIZE, SeNetAddr::iPort, SeSvrConfig::kLocalServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo.
Referenced by Initialize.
void TcpServer::UpdateState()
References SeServerData::bRegistered, ConnectToParent, SeServerData::kSock, m_kParentData, RegisterToParent.
Referenced by Update.
void TcpServer::UpdateConnect(void)
References SeSvrConfig::bConnectHeartCheck, SeConnect::dwAccountID, SeSvrConfig::dwConnectHeartTime, SeConnect::dwLastRecvTime, SeConnect::dwPackCount, SeConnect::dwPackSize, SeConnect::dwStateTime, SeConnect::eState, GetServerTime, m_dwCheckConnectTime, m_kConfig, m_kMapSock, SCS_UNKOWN, SCS_VALID_FAILED, SeLogInfo, VALID_CONNECT_TIMEOUT.
void TcpServer::UpdateClientHeart(void)
References SeConnect::dwAccountID, SeSvrConfig::dwConnectHeartTime, SeConnect::dwLastRecvTime, GetServerTime, m_dwCheckConnectTime, m_kConfig, m_kMapSock, SeLogInfo.
Referenced by Update.
void TcpServer::UpdateParentHeart(void)
References SeServerData::bRegistered, SeServerData::dwHeartPackageTime, SeSvrConfig::dwHeartPackageTime, GetServerTime, SeServerData::kSock, m_kConfig, m_kNetMgr, m_kParentData, SeLogError, SendParent_HeartPackage.
Referenced by Update.
void TcpServer::ConnectToParent(void)
References SeNetAddr::acIP, SeServerData::bConnecting, SeServerData::dwRegisterTime, SeNetAddr::iPort, SeSvrConfig::kParentServer, m_kConfig, m_kNetMgr, m_kParentData, SeLogError, SERVER_BUFFER_SIZE.
Referenced by UpdateState.
void TcpServer::RegisterToParent(void)
References SeServerData::dwRegisterTime, GetServerTime, m_kParentData, SeLogError, SendParent_Register.
Referenced by UpdateState.
void TcpServer::AddConnect(SeConnect *pkConn)
References SeConnect::dwClientID, SeConnect::kSock, m_kMapID, m_kMapSock, SeLogError.
Referenced by OnNetAccept.
void TcpServer::DelConnect(SeConnect *pkConn)
References SeConnect::dwClientID, SeConnect::kSock, m_kMapID, m_kMapSock, SeLogError.
Referenced by OnNetDisconnect.
SeConnect * TcpServer::FindConnect(DWord dwConnID)
References m_kMapID.
Referenced by OnNetDisconnect, OnNetRecv, ProcessParent_ConnectState, ProcessParent_SendData, ProcessParent_SeverDisconnect.
SeConnect * TcpServer::FindConnect(const HSock &rkSock)
References m_kMapSock.
DWord TcpServer::GenClientID()
References m_dwClientGenID.
Referenced by OnNetAccept.
void TcpServer::DisconnectPlayerSock(SeConnect *pkConnect, const char *pcFun, int iLine)
References SeConnect::dwAccountID, SeConnect::kSock, SeLogError.
Referenced by DisconnectPlayerSock.
void TcpServer::DisconnectPlayerSock(const HSock &rkSock, DWord dwAccountID, const char *pcFun, int iLine)
References DisconnectPlayerSock, SPrintf.
void TcpServer::DisconnectPlayerSock(const HSock &rkSock, const char *acAccount, const char *pcFun, int iLine)
References SeSvrConfig::bShowDisconnectLog, GetLocalTime, m_kConfig, m_kNetMgr, SeLogInfo, SPrintf.
DWord TcpServer::GetServerTime(void)
References m_dwCurTime.
Referenced by OnNetAccept, OnNetDisconnect, OnNetRecv, RegisterToParent, UpdateClientHeart, UpdateConnect, UpdateParentHeart.
void TcpServer::ProcessParent(void *pkData, int iSize)
References CMD_TT_CONNECT_STATE, CMD_TT_REGISTERRET, CMD_TT_SENDDATA, CMD_TT_SEVERDISCONNECT, SeServerData::dwHeartPackageTime, m_kParentData, ProcessParent_ConnectState, ProcessParent_RegisterRet, ProcessParent_SendData, ProcessParent_SeverDisconnect, SeCMD::wCmd.
Referenced by OnNetRecv.
void TcpServer::ProcessParent_RegisterRet(void *pkData, int iSize)
References SeNetAddr::acIP, SeServerData::bRegistered, SeConnect::dwAccountID, SeConnect::dwClientID, SeTT_RegisterRet::eRegisterRet, SeConnect::eState, SeNetStream::GetCurPos, SeNetStream::GetData, GetIPString2DWord, SeNetStream::InitData, SeConnect::kNetAddr, m_kMapSock, m_kParentData, SCS_VALID_OK, SeLogError, SeLogInfo, SendParent_ReLoadReadyID, SRR_SUCCESS, SeNetStream::WriteDword.
Referenced by ProcessParent.
void TcpServer::ProcessParent_SeverDisconnect(void *pkData, int iSize)
References SeTT_SeverDisconnect::dwClientID, FindConnect.
Referenced by ProcessParent.
void TcpServer::ProcessParent_SendData(void *pkData, int iSize)
References SeTT_SendData::acData, SeTT_SendData::dwClientID, FindConnect, SeTT_SendData::iDataLen, SeConnect::kSock, m_kNetMgr, SeLogError.
Referenced by ProcessParent.
void TcpServer::ProcessParent_ConnectState(void *pkData, int iSize)
References SeConnect::dwAccountID, SeTT_ConnectState::dwClientID, SeTT_ConnectState::dwParam1, SeConnect::eState, FindConnect, SeTT_ConnectState::iReturn.
Referenced by ProcessParent.