RenJiTableMgr
std::map<unsigned int,RenJiTable*> RenJiTableMgr::m_kRenJiTableMap
Referenced by FillData, GetRenJiTable, GetRenJiTableMap, GetRenJiTableVec, ~RenJiTableMgr.
RenJiTableMgr * RenJiTableMgr::m_pkRenJiTableMgr
Referenced by Get, ReLoad.
RenJiTableMgr * RenJiTableMgr::Get()
References m_pkRenJiTableMgr, RenJiTableMgr.
Referenced by ReLoad.
RenJiTableMgr * RenJiTableMgr::ReLoad()
References Get, m_pkRenJiTableMgr.
RenJiTableMgr::RenJiTableMgr()
References Load.
Referenced by Get.
RenJiTableMgr::~RenJiTableMgr()
References m_kRenJiTableMap.
const RenJiTable * RenJiTableMgr::GetRenJiTable(unsigned int iTypeID)
References m_kRenJiTableMap.
const std::map< unsigned int, RenJiTable * > & RenJiTableMgr::GetRenJiTableMap()
References m_kRenJiTableMap.
TableResArray RenJiTableMgr::GetRenJiTableVec()
References m_kRenJiTableMap, TableResArray::pushBack.
bool RenJiTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RenJiTableMgr.
void RenJiTableMgr::FillData(RenJiTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RenJiTable::iConditions, RenJiTable::iMapSelect, RenJiTable::kDiscription, m_kRenJiTableMap, RenJiTable::uiAction, RenJiTable::uiCharacter, RenJiTable::uiID.
Referenced by Load.