AppendGroupTableMgr
std::map<unsigned int,AppendGroupTable*> AppendGroupTableMgr::m_kAppendGroupTableMap
Referenced by FillData, GetAppendGroupTable, GetAppendGroupTableMap, GetAppendGroupTableVec, ~AppendGroupTableMgr.
AppendGroupTableMgr * AppendGroupTableMgr::m_pkAppendGroupTableMgr
Referenced by Get, ReLoad.
AppendGroupTableMgr * AppendGroupTableMgr::Get()
References AppendGroupTableMgr, m_pkAppendGroupTableMgr.
Referenced by FreshSkill, ReLoad.
AppendGroupTableMgr * AppendGroupTableMgr::ReLoad()
References Get, m_pkAppendGroupTableMgr.
AppendGroupTableMgr::AppendGroupTableMgr()
References Load.
Referenced by Get.
AppendGroupTableMgr::~AppendGroupTableMgr()
References m_kAppendGroupTableMap.
const AppendGroupTable * AppendGroupTableMgr::GetAppendGroupTable(unsigned int iTypeID)
References m_kAppendGroupTableMap.
const std::map< unsigned int, AppendGroupTable * > & AppendGroupTableMgr::GetAppendGroupTableMap()
References m_kAppendGroupTableMap.
TableResArray AppendGroupTableMgr::GetAppendGroupTableVec()
References m_kAppendGroupTableMap, TableResArray::pushBack.
Referenced by FreshSkill.
bool AppendGroupTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AppendGroupTableMgr.
void AppendGroupTableMgr::FillData(AppendGroupTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AppendGroupTable::iProbability, AppendGroupTable::kName, m_kAppendGroupTableMap, AppendGroupTable::uiID, AppendGroupTable::uiOrgTypeID, AppendGroupTable::uiTypeID.
Referenced by Load.