SeLogThread
SeThreadMsgMgr SeLogThread::m_kLogDataCache
Referenced by DoWork, Initialize, PushLog.
bool SeLogThread::m_bRun
Referenced by DoWork, Finialize, Initialize, SeLogThread.
SeFileLog* SeLogThread::m_pkFileLog
Referenced by DoWork, SeLogThread.
SeLogThread::SeLogThread(SeFileLog *pkFileLog)
References m_bRun, m_pkFileLog.
SeLogThread::~SeLogThread(void)
bool SeLogThread::Initialize(void)
References SeThreadMsgMgr::Initialize, m_bRun, m_kLogDataCache.
Referenced by SeFileLog::Initialize.
void SeLogThread::Finialize(void)
References m_bRun.
Referenced by SeFileLog::~SeFileLog.
void SeLogThread::DoWork(void)
References SeFileLog::FlushLog, SeFileLog::Log, m_bRun, m_kLogDataCache, m_pkFileLog, SeThreadMsgMgr::PopMsg.
bool SeLogThread::PushLog(char *pcData, size_t szSize)
References m_kLogDataCache, SeThreadMsgMgr::PushMsg.
Referenced by SeFileLog::Flush, SeFileLog::LogAsLevel.