TabMgr
typedef std::map<DWord, SelectItem *> TabMgr::SELECTMAP
typedef std::map<DWord, SelectItem *> TabMgr::SELECTMAP
Es::NormalLock TabMgr::m_mutex
Ëø.
Referenced by getNextSelectID, onTabSelectRet, tabSelect.
SELECTMAP TabMgr::m_selectItems
Referenced by getNextSelectID, onTabSelectRet, tabSelect.
DWord TabMgr::m_nextSelectID
Referenced by getNextSelectID.
void TabMgr::tabSelect(SeDBTableIndex eTable, const std::list< int > &fields, const std::list< SeDBPair > &conds, SelectCallback &callback)
References TabMgr::SelectItem::callback, TabMgr::SelectItem::formats, g_kWorldServer, SeDBStream::GetCurPos, SeDBStream::GetData, GetFieldFormat, getNextSelectID, SeDBStream::InitData, m_mutex, m_selectItems, WorldServer::SendWB_TabSelect, SFF_NULL, SeDBStream::WriteDword, SeDBStream::WriteVariant.
Referenced by LadderLevelMgr::loadDBData, LadderRankMgr::loadLadderRankInfoDBData.
void TabMgr::tabInsert(SeDBTableIndex eTable, const std::list< SeDBPair > &values)
References g_kWorldServer, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, WorldServer::SendWB_TabInsert, SeDBStream::WriteDword, SeDBStream::WriteVariant.
Referenced by LadderRankItem::DBInsert, LadderLevelMgr::joinTop.
void TabMgr::tabUpdate(SeDBTableIndex eTable, const std::list< SeDBPair > &values, const std::list< SeDBPair > &conds)
References g_kWorldServer, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, WorldServer::SendWB_TabUpdate, SeDBStream::WriteDword, SeDBStream::WriteVariant.
Referenced by LadderRankItem::DBUpdate, LadderLevelMgr::updateScore.
void TabMgr::tabDelete(SeDBTableIndex eTable, const std::list< SeDBPair > &conds)
References g_kWorldServer, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, WorldServer::SendWB_TabDelete, SeDBStream::WriteDword, SeDBStream::WriteVariant.
Referenced by LadderRankItem::DBDelete, LadderLevelMgr::TopItem::dbDelete.
void TabMgr::onTabSelectRet(SeBW_TabSelectRet *pkData)
References SeBW_TabSelectRet::acData, SeDBStream::Attach, SeBW_TabSelectRet::bySendOver, TabMgr::SelectItem::callback, SeBW_TabSelectRet::dwQueryID, SelectCallback::execute, TabMgr::SelectItem::formats, SeBW_TabSelectRet::iRows, SeBW_TabSelectRet::iSize, m_mutex, m_selectItems, SeDBStream::ReadVariant, TabMgr::SelectItem::recordset, SeLogError.
Referenced by WorldServer::ProcessBW_TabSelectRet.
void TabMgr::tabSelect(SeDBTableIndex eTable, const std::list< int > &fields, const std::list< SeDBPair > &conds, SelectCallback &callback)
void TabMgr::tabInsert(SeDBTableIndex eTable, const std::list< SeDBPair > &values)
void TabMgr::tabUpdate(SeDBTableIndex eTable, const std::list< SeDBPair > &values, const std::list< SeDBPair > &conds)
void TabMgr::tabDelete(SeDBTableIndex eTable, const std::list< SeDBPair > &conds)
void TabMgr::onTabSelectRet(SeBW_TabSelectRet *pkData)
SeFieldFormat TabMgr::GetFieldFormat(SeDBTableIndex eTable, int iIndex)
References SeLogError, SFF_NULL.
Referenced by tabSelect.
DWord TabMgr::getNextSelectID()
References m_mutex, m_nextSelectID, m_selectItems.
Referenced by tabSelect.
SeFieldFormat TabMgr::GetFieldFormat(SeDBTableIndex eTable, int iIndex)
DWord TabMgr::getNextSelectID()