ItemExchangeTableMgr
std::map<unsigned int,ItemExchangeTable*> ItemExchangeTableMgr::m_kItemExchangeTableMap
Referenced by FillData, GetItemExchangeTable, GetItemExchangeTableMap, GetItemExchangeTableVec, ~ItemExchangeTableMgr.
ItemExchangeTableMgr * ItemExchangeTableMgr::m_pkItemExchangeTableMgr
Referenced by Get, ReLoad.
ItemExchangeTableMgr * ItemExchangeTableMgr::Get()
References ItemExchangeTableMgr, m_pkItemExchangeTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
ItemExchangeTableMgr * ItemExchangeTableMgr::ReLoad()
References Get, m_pkItemExchangeTableMgr.
Referenced by TableMgr::ReloadTable.
ItemExchangeTableMgr::ItemExchangeTableMgr()
References Load.
Referenced by Get.
ItemExchangeTableMgr::~ItemExchangeTableMgr()
References m_kItemExchangeTableMap.
const ItemExchangeTable * ItemExchangeTableMgr::GetItemExchangeTable(unsigned int iTypeID)
References m_kItemExchangeTableMap.
const std::map< unsigned int, ItemExchangeTable * > & ItemExchangeTableMgr::GetItemExchangeTableMap()
References m_kItemExchangeTableMap.
TableResArray ItemExchangeTableMgr::GetItemExchangeTableVec()
References m_kItemExchangeTableMap, TableResArray::pushBack.
bool ItemExchangeTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by ItemExchangeTableMgr.
void ItemExchangeTableMgr::FillData(ItemExchangeTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, ItemExchangeTable::iConsume, ItemExchangeTable::iDesc, ItemExchangeTable::iExChangeItemNum, ItemExchangeTable::iOpen, ItemExchangeTable::kName_China, m_kItemExchangeTableMap, ItemExchangeTable::uiExChangeItemID, ItemExchangeTable::uiExChangeType, ItemExchangeTable::uiExchangeTypeID, ItemExchangeTable::uiNeed, ItemExchangeTable::uiNeedItemID, ItemExchangeTable::uiNeedNum, ItemExchangeTable::uiOrgTypeID, ItemExchangeTable::uiRepeatType, ItemExchangeTable::uiResultType, ItemExchangeTable::uiSubTask.
Referenced by Load.