LanguageTableMgr
std::map<std::string,LanguageTable*> LanguageTableMgr::m_kLanguageTableMap
Referenced by FillData, GetLanguageTable, GetLanguageTableMap, GetLanguageTableVec, ~LanguageTableMgr.
LanguageTableMgr * LanguageTableMgr::m_pkLanguageTableMgr
Referenced by Get, ReLoad.
LanguageTableMgr * LanguageTableMgr::Get()
References LanguageTableMgr, m_pkLanguageTableMgr.
Referenced by TableMgr::GetText, TableMgr::LoadTable, ReLoad.
LanguageTableMgr * LanguageTableMgr::ReLoad()
References Get, m_pkLanguageTableMgr.
Referenced by TableMgr::ReloadTable.
LanguageTableMgr::LanguageTableMgr()
References Load.
Referenced by Get.
LanguageTableMgr::~LanguageTableMgr()
References m_kLanguageTableMap.
const LanguageTable * LanguageTableMgr::GetLanguageTable(const std::string sKey)
References m_kLanguageTableMap.
Referenced by TableMgr::GetText.
const std::map< std::string, LanguageTable * > & LanguageTableMgr::GetLanguageTableMap()
References m_kLanguageTableMap.
TableResArray LanguageTableMgr::GetLanguageTableVec()
References m_kLanguageTableMap, TableResArray::pushBack.
bool LanguageTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by LanguageTableMgr.
void LanguageTableMgr::FillData(LanguageTable *row, TiXmlElement *element)
References LanguageTable::akLanguage, TiXmlElement::Attribute, LanguageTable::kKey, m_kLanguageTableMap, SGL_EN_US, SGL_ZH_CN.
Referenced by Load.