DressTableMgr
std::map<unsigned int,DressTable*> DressTableMgr::m_kDressTableMap
Referenced by FillData, GetDressTable, GetDressTableMap, GetDressTableVec, ~DressTableMgr.
DressTableMgr * DressTableMgr::m_pkDressTableMgr
Referenced by Get, ReLoad.
DressTableMgr * DressTableMgr::Get()
References DressTableMgr, m_pkDressTableMgr.
Referenced by ReLoad.
DressTableMgr * DressTableMgr::ReLoad()
References Get, m_pkDressTableMgr.
DressTableMgr::DressTableMgr()
References Load.
Referenced by Get.
DressTableMgr::~DressTableMgr()
References m_kDressTableMap.
const DressTable * DressTableMgr::GetDressTable(unsigned int iTypeID)
References m_kDressTableMap.
const std::map< unsigned int, DressTable * > & DressTableMgr::GetDressTableMap()
References m_kDressTableMap.
TableResArray DressTableMgr::GetDressTableVec()
References m_kDressTableMap, TableResArray::pushBack.
bool DressTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by DressTableMgr.
void DressTableMgr::FillData(DressTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, DressTable::iBasicDressPower, DressTable::iModelFile, DressTable::iName, DressTable::iPos, DressTable::kIcon, DressTable::kName_China, m_kDressTableMap, DressTable::uiDressID, DressTable::uiOwnerID.
Referenced by Load.