RankStageTableMgr
std::map<unsigned int,RankStageTable*> RankStageTableMgr::m_kRankStageTableMap
Referenced by FillData, GetRankStageTable, GetRankStageTableMap, GetRankStageTableVec, UpdateLanguadgeContent, ~RankStageTableMgr.
RankStageTableMgr * RankStageTableMgr::m_pkRankStageTableMgr
Referenced by Get, ReLoad.
RankStageTableMgr * RankStageTableMgr::Get()
References m_pkRankStageTableMgr, RankStageTableMgr.
Referenced by LadderLevelMgr::getNewLadderScore, GlobalTableMgr::GetRankStageTable, GlobalTableMgr::GetRankStageTableMap, LadderLevelMgr::Initialize, TableMgr::LoadTable, SeRaceMgr::OnRaceEndGradeDetail, ReLoad, TableMgr::UpdateLanguageContent.
RankStageTableMgr * RankStageTableMgr::ReLoad()
References Get, m_pkRankStageTableMgr.
RankStageTableMgr::RankStageTableMgr()
References Load.
Referenced by Get.
RankStageTableMgr::~RankStageTableMgr()
References m_kRankStageTableMap.
const RankStageTable * RankStageTableMgr::GetRankStageTable(unsigned int iTypeID)
References m_kRankStageTableMap.
Referenced by LadderLevelMgr::getNewLadderScore, GlobalTableMgr::GetRankStageTable, SeRaceMgr::OnRaceEndGradeDetail.
const std::map< unsigned int, RankStageTable * > & RankStageTableMgr::GetRankStageTableMap()
References m_kRankStageTableMap.
Referenced by GlobalTableMgr::GetRankStageTableMap, LadderLevelMgr::Initialize.
TableResArray RankStageTableMgr::GetRankStageTableVec()
References m_kRankStageTableMap, TableResArray::pushBack.
void RankStageTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, RankStageTable::kStageLevelName, RankStageTable::kStageLevelNameK, RankStageTable::kStageName, RankStageTable::kStageNameK, m_kRankStageTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool RankStageTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by RankStageTableMgr.
void RankStageTableMgr::FillData(RankStageTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RankStageTable::fReduceProportion, RankStageTable::iActivityTaskId, RankStageTable::iRankStage, RankStageTable::iRankStageId, RankStageTable::iRankStageLevel, RankStageTable::iStageRanking, RankStageTable::iStageScore, RankStageTable::iStageScoreNextSeason, RankStageTable::kBeizhu, RankStageTable::kGradientBottom, RankStageTable::kGradientTop, RankStageTable::kStageImg, RankStageTable::kStageLevelNameK, RankStageTable::kStageNameK, m_kRankStageTableMap.
Referenced by Load.