LadderLevelMgr
typedef std::map<int, RankStageTable *,std::greater<int> > LadderLevelMgr::SCOREMAP
typedef std::map<DWord, TopItem *> LadderLevelMgr::PLAYERTOPMAP
typedef std::set<TopItem *, TopItemScoreCmp> LadderLevelMgr::SCORETOPSET
typedef std::map<int, RankStageTable *,std::greater<int> > LadderLevelMgr::SCOREMAP
typedef std::map<DWord, TopItem *> LadderLevelMgr::PLAYERTOPMAP
typedef std::set<TopItem *, TopItemScoreCmp> LadderLevelMgr::SCORETOPSET
Es::NormalLock LadderLevelMgr::m_mutex
Ëø.
Referenced by joinTop, quitTop.
int LadderLevelMgr::m_topLevel
Referenced by getLevel, getTopLevel, Initialize, LadderLevelMgr.
int LadderLevelMgr::m_topPlayerMaxNum
Referenced by Initialize, joinTop, LadderLevelMgr.
SCOREMAP LadderLevelMgr::m_scoreMap
Referenced by getLevelByScore, Initialize.
PLAYERTOPMAP LadderLevelMgr::m_playerTopMap
Referenced by joinTop, quitTop, setInitData.
SCORETOPSET LadderLevelMgr::m_scoreTopSet
Referenced by insertTopSet, joinTop, quitTop, updateScore.
LadderLevelMgr::LadderLevelMgr(void)
References m_topLevel, m_topPlayerMaxNum, MIN_LEVEL.
LadderLevelMgr::~LadderLevelMgr(void)
bool LadderLevelMgr::Initialize(void)
References RankStageTableMgr::Get, RankStageTableMgr::GetRankStageTableMap, m_scoreMap, m_topLevel, m_topPlayerMaxNum, MIN_LEVEL, SeLogError.
Referenced by WorldServer::Initialize.
int LadderLevelMgr::getLevel(DWord dwPlayerID, int score)
References getLevelByScore, joinTop, m_topLevel.
Referenced by SePlayer::adjustLadderNo, SePlayer::GetLadder, BlockServer::ProcessRBL_UpdateScore.
int LadderLevelMgr::getNewLadderScore(int newNo, int oldNo, int oldLevel)
References RankStageTableMgr::Get, getLevelByScore, RankStageTableMgr::GetRankStageTable, RankStageTable::iStageScoreNextSeason, MIN_SCORE.
Referenced by SePlayer::adjustLadderNo.
void LadderLevelMgr::loadDBData()
References g_kTabMgr, onLadderLoad, SDTI_CharLadder, TabMgr::tabSelect.
Referenced by WorldServer::ProcessBW_RegisterRet.
void LadderLevelMgr::setInitData(DWord dwPlayerID, time_t time, int score)
References LadderLevelMgr::TopItem::dwPlayerID, insertTopSet, m_playerTopMap, LadderLevelMgr::TopItem::score, LadderLevelMgr::TopItem::time.
Referenced by onLadderLoad.
void LadderLevelMgr::quitTop(DWord dwPlayerID)
References LadderLevelMgr::TopItem::dbDelete, m_mutex, m_playerTopMap, m_scoreTopSet.
Referenced by BlockServer::ProcessRBL_UpdateScore.
int LadderLevelMgr::getTopLevel()
References m_topLevel.
Referenced by BlockServer::ProcessRBL_UpdateScore.
LadderLevelMgr::LadderLevelMgr(void)
LadderLevelMgr::~LadderLevelMgr(void)
bool LadderLevelMgr::Initialize(void)
int LadderLevelMgr::getLevel(DWord dwPlayerID, int score)
int LadderLevelMgr::getNewLadderScore(int newNo, int oldNo, int oldLevel)
void LadderLevelMgr::loadDBData()
void LadderLevelMgr::setInitData(DWord dwPlayerID, time_t time, int score)
void LadderLevelMgr::quitTop(DWord dwPlayerID)
int LadderLevelMgr::getTopLevel()
int LadderLevelMgr::getLevelByScore(int score)
References m_scoreMap, MIN_LEVEL.
Referenced by getLevel, getNewLadderScore.
bool LadderLevelMgr::joinTop(DWord dwPlayerID, int score)
References LadderLevelMgr::TopItem::dbDelete, LadderLevelMgr::TopItem::dwPlayerID, g_kTabMgr, GetDBTime, insertTopSet, m_mutex, m_playerTopMap, m_scoreTopSet, m_topPlayerMaxNum, LadderLevelMgr::TopItem::score, SDTI_CharLadder, TabMgr::tabInsert, LadderLevelMgr::TopItem::time, updateScore.
Referenced by getLevel.
void LadderLevelMgr::updateScore(TopItem *item, int score)
References LadderLevelMgr::TopItem::dwPlayerID, g_kTabMgr, GetDBTime, insertTopSet, m_scoreTopSet, LadderLevelMgr::TopItem::score, SDTI_CharLadder, TabMgr::tabUpdate, LadderLevelMgr::TopItem::time.
Referenced by joinTop.
void LadderLevelMgr::insertTopSet(TopItem *item)
References m_scoreTopSet, LadderLevelMgr::TopItem::time.
Referenced by joinTop, setInitData, updateScore.
int LadderLevelMgr::getLevelByScore(int score)
bool LadderLevelMgr::joinTop(DWord dwPlayerID, int score)
void LadderLevelMgr::updateScore(TopItem *item, int score)
void LadderLevelMgr::insertTopSet(TopItem *item)