ChoiceItemTableMgr
std::map<unsigned int,ChoiceItemTable*> ChoiceItemTableMgr::m_kChoiceItemTableMap
Referenced by FillData, GetChoiceItemTable, GetChoiceItemTableMap, GetChoiceItemTableVec, ~ChoiceItemTableMgr.
ChoiceItemTableMgr * ChoiceItemTableMgr::m_pkChoiceItemTableMgr
Referenced by Get, ReLoad.
ChoiceItemTableMgr * ChoiceItemTableMgr::Get()
References ChoiceItemTableMgr, m_pkChoiceItemTableMgr.
Referenced by GlobalTableMgr::GetChoiceItemMap, GlobalTableMgr::GetChoiceItemTable, GlobalTableMgr::GetLastChoiceItemTable, TableMgr::InitWishBuyOrder, TableMgr::LoadTable, ReLoad.
ChoiceItemTableMgr * ChoiceItemTableMgr::ReLoad()
References Get, m_pkChoiceItemTableMgr.
Referenced by TableMgr::ReloadTable.
ChoiceItemTableMgr::ChoiceItemTableMgr()
References Load.
Referenced by Get.
ChoiceItemTableMgr::~ChoiceItemTableMgr()
References m_kChoiceItemTableMap.
const ChoiceItemTable * ChoiceItemTableMgr::GetChoiceItemTable(unsigned int iTypeID)
References m_kChoiceItemTableMap.
Referenced by GlobalTableMgr::GetChoiceItemTable.
const std::map< unsigned int, ChoiceItemTable * > & ChoiceItemTableMgr::GetChoiceItemTableMap()
References m_kChoiceItemTableMap.
Referenced by GlobalTableMgr::GetChoiceItemMap, GlobalTableMgr::GetLastChoiceItemTable, TableMgr::InitWishBuyOrder.
TableResArray ChoiceItemTableMgr::GetChoiceItemTableVec()
References m_kChoiceItemTableMap, TableResArray::pushBack.
bool ChoiceItemTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by ChoiceItemTableMgr.
void ChoiceItemTableMgr::FillData(ChoiceItemTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, ChoiceItemTable::kName, m_kChoiceItemTableMap, ChoiceItemTable::uiBuyItemID, ChoiceItemTable::uiSkillItem.
Referenced by Load.