LadderRankMgr
typedef std::multimap<LadderRankIndex, LadderRankItem *, LadderRankCompare > LadderRankMgr::LADDERRANKMMAP
typedef std::multimap<LadderRankIndex, LadderRankItem *, LadderRankCompare >::iterator LadderRankMgr::LADDERRANKITER
typedef std::map<DWord, LADDERRANKITER> LadderRankMgr::PLAYERID2ITEMITER
typedef std::multimap<LadderRankIndex, LadderRankItem *, LadderRankCompare > LadderRankMgr::LADDERRANKMMAP
typedef std::multimap<LadderRankIndex, LadderRankItem *, LadderRankCompare >::iterator LadderRankMgr::LADDERRANKITER
typedef std::map<DWord, LADDERRANKITER> LadderRankMgr::PLAYERID2ITEMITER
LADDERRANKMMAP LadderRankMgr::m_LadderRankMMap
Referenced by AdjustRankSize, JoinNewPlayerLadderInfo, QueryLadderRank, UpdateRank.
PLAYERID2ITEMITER LadderRankMgr::m_playerIterMap
Referenced by AdjustRankSize, JoinNewPlayerLadderInfo.
Es::NormalLock LadderRankMgr::m_mutex
Ëø.
Referenced by JoinNewPlayerLadderInfo, QueryLadderRank.
int LadderRankMgr::m_MaxRankNum
Referenced by AdjustRankSize, Initialize, JoinNewPlayerLadderInfo, LadderRankMgr.
bool LadderRankMgr::m_bSaveDbFlag
Referenced by JoinNewPlayerLadderInfo, LadderRankMgr, RankDBDelete, RankDBInsert, RankDBUpdate.
LadderRankCompare LadderRankMgr::m_compare
Referenced by CompareRankIndex.
LadderRankMgr::LadderRankMgr(void)
References m_bSaveDbFlag, m_MaxRankNum.
LadderRankMgr::~LadderRankMgr(void)
bool LadderRankMgr::Initialize(void)
References m_MaxRankNum.
void LadderRankMgr::loadLadderRankInfoDBData()
References g_kTabMgr, onLadderRankLoad, SDTI_CharLadderRank, TabMgr::tabSelect.
Referenced by WorldServer::ProcessBW_RegisterRet.
bool LadderRankMgr::GetPlayerRankInfo(DWord dwPlayerId, LadderRankItem &ItemInfo)
int LadderRankMgr::JoinNewPlayerLadderInfo(DWord dwPlayerID, int level, int score, int playerLevel, Word wIconID, const char *acName, bool bSaveDbFlag=true)
References AdjustRankSize, CompareRankIndex, LadderRankItem::GetRank, LadderRankItem::Index, LadderRankItem::LoadInfo, m_bSaveDbFlag, m_LadderRankMMap, m_MaxRankNum, m_mutex, m_playerIterMap, RankDBInsert, RankDBUpdate, LadderRankItem::SetRank, UpdateRank.
Referenced by onLadderRankLoad, BlockServer::ProcessRBL_UpdateScore.
bool LadderRankMgr::CompareRankIndex(const LadderRankIndex &a, const LadderRankIndex &b)
References m_compare.
Referenced by JoinNewPlayerLadderInfo.
void LadderRankMgr::QueryLadderRank(std::vector< SeLadderRankInfo > &vRankList)
References m_LadderRankMMap, m_mutex.
Referenced by BlockServer::ProcessTBL_LadderRankQueryReq.
void LadderRankMgr::UpdateRank(LADDERRANKITER &currIter, int rank)
References m_LadderRankMMap, LadderRankItem::SetRank.
Referenced by JoinNewPlayerLadderInfo.
void LadderRankMgr::AdjustRankSize()
References SeLadderRankInfo::dwPlayerID, m_LadderRankMMap, m_MaxRankNum, m_playerIterMap, RankDBDelete.
Referenced by JoinNewPlayerLadderInfo.
void LadderRankMgr::RankDBDelete(LadderRankItem *item)
References LadderRankItem::DBDelete, m_bSaveDbFlag.
Referenced by AdjustRankSize.
void LadderRankMgr::RankDBUpdate(LadderRankItem *item)
References LadderRankItem::DBUpdate, m_bSaveDbFlag.
Referenced by JoinNewPlayerLadderInfo.
void LadderRankMgr::RankDBInsert(LadderRankItem *item)
References LadderRankItem::DBInsert, m_bSaveDbFlag.
Referenced by JoinNewPlayerLadderInfo.
LadderRankMgr::LadderRankMgr(void)
LadderRankMgr::~LadderRankMgr(void)
bool LadderRankMgr::Initialize(void)
void LadderRankMgr::loadLadderRankInfoDBData()
bool LadderRankMgr::GetPlayerRankInfo(DWord dwPlayerId, LadderRankItem &ItemInfo)
int LadderRankMgr::JoinNewPlayerLadderInfo(DWord dwPlayerID, int level, int score, int playerLevel, Word wIconID, const char *acName, bool bSaveDbFlag=true)
bool LadderRankMgr::CompareRankIndex(const LadderRankIndex &a, const LadderRankIndex &b)
void LadderRankMgr::QueryLadderRank(std::vector< SeLadderRankInfo > &vRankList)
void LadderRankMgr::UpdateRank(LADDERRANKITER &currIter, int rank)
void LadderRankMgr::AdjustRankSize()
void LadderRankMgr::RankDBDelete(LadderRankItem *item)
void LadderRankMgr::RankDBUpdate(LadderRankItem *item)
void LadderRankMgr::RankDBInsert(LadderRankItem *item)