SeTownMgr
MapAllTS SeTownMgr::m_kAllTS
Referenced by Finialize, GetAllTS, GetTown, GetTownNum, GetTownSockByArea, OnTSDisconnect, OnTSRegister, OnTSUpdateLoadNum, RefreshAreaNum.
int SeTownMgr::m_iTownArea
Referenced by GetTownArea, RefreshAreaNum, SeTownMgr.
SAreaID SeTownMgr::m_kAreaID
Referenced by GetAreaID, RefreshAreaNum.
SeTownMgr::SeTownMgr()
References m_iTownArea.
SeTownMgr::~SeTownMgr()
References Finialize.
bool SeTownMgr::Initialize(void)
Referenced by MatchServer::Initialize.
void SeTownMgr::Update(void)
Referenced by MatchServer::Update.
void SeTownMgr::Finialize(void)
References m_kAllTS, SAFE_DELETE.
Referenced by ~SeTownMgr.
bool SeTownMgr::OnTSRegister(SeTown kTown)
References SeTown::dwAreaID, SeTown::dwServerID, SeTown::iRegisterCount, m_kAllTS, RefreshAreaNum.
Referenced by MatchServer::ProcessTM_Register.
bool SeTownMgr::OnTSDisconnect(HTownSign &rkTownSign)
References m_kAllTS, RefreshAreaNum, SAFE_DELETE.
Referenced by MatchServer::OnNetDisconnect.
void SeTownMgr::OnTSUpdateLoadNum(HTownSign &rkTownSign, int iPlayerConn, int iRaceConn)
References SeTown::dwLastRecvTime, g_kMatchServer, MatchServer::GetServerTime, SeTown::iPlayerNum, SeTown::iRaceConnNum, m_kAllTS.
Referenced by MatchServer::ProcessTM_HeartPackage.
int SeTownMgr::GetTownNum(void)
References m_kAllTS.
Referenced by MatchServer::ShowConsoleTitle.
int SeTownMgr::GetTownArea(void)
References m_iTownArea.
Referenced by MatchServer::ShowConsoleTitle.
const SeTown * SeTownMgr::GetTown(const HTownSign &kTownSign)
References m_kAllTS.
Referenced by SeRaceMgr::GetTownSock, GetTownSockBySign, SeMatchMgr::OnMatchReq, MatchServer::ProcessRM_ReconQueryFail, MatchServer::ProcessRM_ViewQueryFail, MatchServer::ProcessTM_CommMatchMsg, MatchServer::ProcessTM_Register.
SAreaID & SeTownMgr::GetAreaID()
References m_kAreaID.
HSock SeTownMgr::GetTownSockBySign(const HTownSign &rkTownSign)
References GetTown, SeConnect::kSock, SeTown::pkConnect.
Referenced by SeMatchMgr::addWaitRoom, SeOpenRoomMgr::CreateRaceInfo, SeMatchMgr::OnConfirm, SeOpenRoomMgr::OnCreateRoom, MatchPrepareMgr::onDataResult, SeMatchMgr::OnMatchCancel, SeOpenRoomMgr::OnQueryRoomList, SeOpenRoomMgr::OnRoomKickSomeone, SeOpenRoomMgr::OnRoomLeave, SeOpenRoomMgr::OnRoomSwitchSeat, SeOpenRoomMgr::SendRoomJoinRet, SeOpenRoomMgr::SendRoomNotify, SeMatchMgr::UpdateRoom.
HSock SeTownMgr::GetTownSockByArea(DWord dwAreaID)
References SeTown::dwAreaID, SeConnect::kSock, m_kAllTS, SeTown::pkConnect.
Referenced by SeRaceMgr::OnProcessMatchRaceLoad, SeRaceMgr::OnProcessRaceBuy, SeRaceMgr::OnProcessRaceEndGuanqia, SeRaceMgr::OnProcessRaceEndReport.
MapAllTS & SeTownMgr::GetAllTS()
References m_kAllTS.
Referenced by MatchServer::UpdateTSTOMSTime.
SeTownMgr::SeTownMgr()
SeTownMgr::~SeTownMgr()
bool SeTownMgr::Initialize(void)
void SeTownMgr::Update(void)
void SeTownMgr::Finialize(void)
bool SeTownMgr::OnTSRegister(SeTown kTown)
bool SeTownMgr::OnTSDisconnect(HTownSign &rkTownSign)
void SeTownMgr::OnTSUpdateLoadNum(HTownSign &rkTownSign, int iPlayerConn, int iRaceConn)
int SeTownMgr::GetTownNum(void)
int SeTownMgr::GetTownArea(void)
const SeTown* SeTownMgr::GetTown(const HTownSign &kTownSign)
SAreaID& SeTownMgr::GetAreaID()
HSock SeTownMgr::GetTownSockBySign(const HTownSign &rkTownSign)
HSock SeTownMgr::GetTownSockByArea(DWord dwAreaID)
MapAllTS& SeTownMgr::GetAllTS()
void SeTownMgr::RefreshAreaNum(void)
References SeTown::dwAreaID, m_iTownArea, m_kAllTS, m_kAreaID.
Referenced by OnTSDisconnect, OnTSRegister.
void SeTownMgr::RefreshAreaNum(void)