IInterval
virtual void IInterval::Start()=0
Referenced by CIntervalScope::CIntervalScope.
virtual void IInterval::End()=0
Referenced by CIntervalScope::~CIntervalScope.
virtual IInterval::~IInterval()
virtual IInterval* IInterval::SetFolderName(const char *szFolderName)=0
Referenced by CPerformanceTiming::CreateOrLookupInterval, CPerformanceTiming::TickNotify.