EquipSchemaMgr
SePlayer & EquipSchemaMgr::m_owner
Referenced by getOwner.
SeDBCharEquipSchema * EquipSchemaMgr::m_data[SSD_QUICK_EQUIP_MAX_NUM]
Referenced by EquipSchemaMgr, fixData, getEquips, loadData, putOnEquip, sendInitData, takeOffEquip, ~EquipSchemaMgr.
EquipSchemaMgr::EquipSchemaMgr(SePlayer &owner)
References m_data.
EquipSchemaMgr::~EquipSchemaMgr()
References m_data, SSD_QUICK_EQUIP_MAX_NUM.
void EquipSchemaMgr::loadData(const SeDBCharEquipSchema &item)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete, g_kCharEquipSchemaStrategy, getOwner, m_data, SSD_QUICK_EQUIP_MAX_NUM.
void EquipSchemaMgr::fixData()
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, g_kCharEquipSchemaStrategy, CItemMgr::getItem, SePlayer::GetItemMgr, getOwner, isValidEquip, m_data, partBegin, partEnd, s_dbParts, s_varZero, SSD_QUICK_EQUIP_MAX_NUM.
SeItemResult EquipSchemaMgr::putOnEquip(Word srcpos, Word ucDst, DWord &dwItemID)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, g_kCharEquipSchemaStrategy, getEquipClass, PlayerDataStrategy::getGenID, SePlayer::GetID, CItemMgr::getItem, SePlayer::GetItemMgr, getOwner, isValidEquip, ITEM_DST_INDEX_ERROR, ITEM_RESULT_SUCCESS, ITEM_TAKEON_POS_SUBTYPE_ERROR, m_data, partBegin, s_dbParts, CItem::uiID.
Referenced by BlockServer::ProcessTBL_PutOnEquip.
SeItemResult EquipSchemaMgr::takeOffEquip(Word srcpos)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, g_kCharEquipSchemaStrategy, getEquipClass, getOwner, ITEM_DST_INDEX_ERROR, ITEM_RESULT_SUCCESS, m_data, partBegin, partEnd, s_dbParts, s_varZero.
Referenced by BlockServer::ProcessTBL_TakeOffEquip.
void EquipSchemaMgr::sendInitData()
References SeWT_EquipSchema::akEquips, SeEquipSchemaInfo::byIndex, g_kWorldServer, GetID, getOwner, GetTownSock, SeWT_EquipSchema::iNum, m_data, partBegin, partEnd, s_dbParts, s_proParts, WorldServer::SendWT_EquipSchema, SSD_QUICK_EQUIP_MAX_NUM.
Referenced by SePlayer::OperateLoading.
void EquipSchemaMgr::getEquips(int equipmentType, VVPtlEquipItem &equips)
References CItem::CopyToEquipItem, CItemMgr::getItem, SePlayer::GetItemMgr, getOwner, m_data, partBegin, partEnd, s_dbParts, SSD_QUICK_EQUIP_MAX_NUM.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail.
EquipSchemaMgr::EquipSchemaMgr(SePlayer &owner)
EquipSchemaMgr::~EquipSchemaMgr()
void EquipSchemaMgr::loadData(const SeDBCharEquipSchema &item)
void EquipSchemaMgr::fixData()
SeItemResult EquipSchemaMgr::putOnEquip(Word srcpos, Word ucDst, DWord &dwItemID)
SeItemResult EquipSchemaMgr::takeOffEquip(Word srcpos)
void EquipSchemaMgr::sendInitData()
void EquipSchemaMgr::getEquips(int equipmentType, VVPtlEquipItem &equips)
SePlayer & EquipSchemaMgr::getOwner()
References m_owner.
Referenced by fixData, getEquips, loadData, putOnEquip, sendInitData, takeOffEquip.
SePlayer& EquipSchemaMgr::getOwner()
bool EquipSchemaMgr::isValidEquip(int partIndex, CItem *pItem)
References TownItemTableMgr::Get, TownItemTableMgr::GetTownItemTable, TOWNITEM_CLASS_ZHUANGBEI, TownItemTable::uiClass, CItem::uiItemID, TownItemTable::uiSubClass.
Referenced by fixData, putOnEquip.
static bool EquipSchemaMgr::isValidEquip(int partIndex, CItem *pItem)