SeDBPlayerMgr
CharInfoStrategy
MID2DBPlayerLink SeDBPlayerMgr::m_kMapDBPlayerLink
Referenced by AttachLink, CreateDBPlayer, CreateDBPlayer_Offline, DBPlayerLinkItrJoin, DBPlayerLinkItrLeave, Finialize, GenCacheInitID, GetDBPlayer, GetDBPlayerNums, handleEachPlayer, IsRepeatName, CharInfoStrategy::rebuildMem, SafeDeleteDBPlayer, SaveAllPlayerToDB, SeDBPlayerMgr, Update.
int SeDBPlayerMgr::m_iMaxCycleNums
Referenced by GetCycleNums, SeDBPlayerMgr, SetCycleNums.
int SeDBPlayerMgr::m_iMaxCyclePlayerNums
Referenced by GetCyclePlayerNums, SeDBPlayerMgr, SetCyclePlayerNums.
MID2DBPlayerLink::iterator SeDBPlayerMgr::m_kItrDBPlayerLink
Referenced by DBPlayerLinkItrJoin, DBPlayerLinkItrLeave, SeDBPlayerMgr, Update.
SeDBPlayerLink * SeDBPlayerMgr::m_pkFirst
Referenced by AttachLink, ClearDBPlayer, DetachLink, SeDBPlayerMgr.
SeDBPlayerLink * SeDBPlayerMgr::m_pkLast
Referenced by AttachLink, ClearDBPlayer, DetachLink, SeDBPlayerMgr.
bool SeDBPlayerMgr::m_bSaveAllPlayerToDB
Referenced by SaveAllPlayerToDB, SeDBPlayerMgr, Update.
MID2DBPlayerLink::iterator SeDBPlayerMgr::m_kPlayerLinkItr
Referenced by SaveAllPlayerToDB, Update.
int SeDBPlayerMgr::m_iResCount
Referenced by GetResCount, incResCount, OnDataDelete, OnDataDiscard, OnDataInsert, OnDataUpdateNum, OnDataUpdateNum64, OnDataUpdateString, OnDataUpdateTime, RebuildDBCharNexusFriend, RebuildDBCharTask, SaveToDB, SeDBPlayerMgr.
DWord SeDBPlayerMgr::m_dwClearPlayerID
Referenced by AddClearPlayerID, SeDBPlayerMgr, Update.
std::vector< DWord > SeDBPlayerMgr::m_VecClearPlayerID
Referenced by AddClearPlayerID, GetNextClearPlayerID.
MNAME2Player SeDBPlayerMgr::m_kMapCharName2Player
Referenced by AddCharNameRecord, DelCharNameRecord, GetDBPlayerByName, GetNameRecordCount.
MID2CharName SeDBPlayerMgr::m_kMCreateQueryName
Referenced by AddCreateQueryName, DelCreateQueryName, IsRepeatName.
MID2CharMemory SeDBPlayerMgr::m_kMCharMemory
Referenced by GetCharMemoryByIndex, GetCharMemoryCount, RebuildDBCharMemory, UpdateCharMemoryData.
SeDBTime SeDBPlayerMgr::m_kServerTime
Referenced by SeDBPlayerMgr.
SeDBPlayerMgr::SeDBPlayerMgr(void)
References m_bSaveAllPlayerToDB, m_dwClearPlayerID, m_iMaxCycleNums, m_iMaxCyclePlayerNums, m_iResCount, m_kItrDBPlayerLink, m_kMapDBPlayerLink, m_kServerTime, m_pkFirst, m_pkLast, NowTime.
SeDBPlayerMgr::~SeDBPlayerMgr(void)
bool SeDBPlayerMgr::Initialize(void)
void SeDBPlayerMgr::Update(void)
References SeDBPlayer::bOnline, ClearDBPlayer, SeDBPlayer::dwLastSaveTime, g_kDBServer, GetCycleNums, GetCyclePlayerNums, GetDBPlayer, DBServer::GetDBQueryNums, DBServer::GetMaxDBQueryNums, GetNextClearPlayerID, DBServer::GetSaveSpaceTime, DBServer::GetServerDBError, DBServer::GetServerTime, IsPlayerLoadComplete, m_bSaveAllPlayerToDB, m_dwClearPlayerID, m_kItrDBPlayerLink, m_kMapDBPlayerLink, m_kPlayerLinkItr, SaveToDB, SeLogError, SeLogInfo.
Referenced by DBServer::Finialize, DBServer::Update.
void SeDBPlayerMgr::Finialize(void)
References SeDBPlayer::dwPlayerID, m_kMapDBPlayerLink, SafeDeleteDBPlayer.
void SeDBPlayerMgr::RebuildDBCharTask(VDBCharTask &rkVCharTask)
References SeDBPlayer::akTask, SeDBPlayer::bIsInSaving, GetDBPlayer, m_iResCount, SCT_NULL.
Referenced by DBServer::RebuildMem.
void SeDBPlayerMgr::RebuildDBCharMemory(VDBCharMemory &rkVCharMemory)
References m_kMCharMemory.
Referenced by DBServer::RebuildMem.
void SeDBPlayerMgr::RebuildDBCharNexusFriend(VDBCharNexusFriend &rkNexusFriend)
References SeDBPlayer::akNexusFriend, SeDBPlayer::bIsInSaving, GetDBPlayer, m_iResCount, SCT_NULL.
Referenced by DBServer::RebuildMem.
DWord SeDBPlayerMgr::GetNextClearPlayerID()
References m_VecClearPlayerID.
Referenced by AddClearPlayerID, Update.
void SeDBPlayerMgr::AddClearPlayerID(DWord dwPlayerID)
References GetNextClearPlayerID, m_dwClearPlayerID, m_VecClearPlayerID.
Referenced by DBServer::LoadDynamicConfig.
int SeDBPlayerMgr::GetResCount()
References m_iResCount.
int SeDBPlayerMgr::GetNameRecordCount()
References m_kMapCharName2Player.
Referenced by DBServer::ShowConsoleTitle.
int SeDBPlayerMgr::GetDBPlayerNums()
References m_kMapDBPlayerLink.
Referenced by DBServer::ShowConsoleTitle.
void SeDBPlayerMgr::SetCycleNums(int iNums)
References m_iMaxCycleNums.
Referenced by DBServer::LoadConfig.
int SeDBPlayerMgr::GetCycleNums()
References m_iMaxCycleNums.
Referenced by DBServer::ShowConsoleTitle, Update.
void SeDBPlayerMgr::SetCyclePlayerNums(int iNums)
References m_iMaxCyclePlayerNums.
Referenced by DBServer::LoadConfig.
int SeDBPlayerMgr::GetCyclePlayerNums()
References m_iMaxCyclePlayerNums.
Referenced by Update.
int SeDBPlayerMgr::GetCharMemoryCount(DWord dwPlayerID)
References m_kMCharMemory.
Referenced by DBServer::GetPlayerRecordCount.
SeDBCharMemory * SeDBPlayerMgr::GetCharMemoryByIndex(DWord dwPlayerID, int iIndex)
References DiffDBTime, m_kMCharMemory, NowTime.
Referenced by DBServer::GetPlayerFieldData.
void SeDBPlayerMgr::UpdateCharMemoryData(DWord dwPlayerID, DWord dwType, DWord dwParam, DWord dwValue, SeDBTime &rkEndTime)
References m_kMCharMemory.
Referenced by DBServer::SendDB_CharMemoryUpdate.
SeDBPlayer * SeDBPlayerMgr::GetDBPlayer(DWord dwPlayerID)
References m_kMapDBPlayerLink.
Referenced by AttachLink, ClearDBPlayer, CreateDBPlayer, CreateDBPlayer_Offline, DBPlayerLoad, DetachLink, DBServer::Excu_SelectData, GetDBPlayerByName, OnDataDelete, OnDataDiscard, OnDataInsert, OnDataUpdateNum, OnDataUpdateNum64, OnDataUpdateString, OnDataUpdateTime, onLoadCharData, DBServer::ProcessDB_CharFriendLadderLoad, DBServer::ProcessDB_CharNexusFriendLoad, DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery, DBServer::ProcessWB_DataInsert, DBServer::ProcessWB_IsPlayerExist, DBServer::ProcessWB_LoadPlayerInfoAgain, DBServer::ProcessWS_Insert_NoReceipt, DBServer::ProcessWS_Update_NoReceipt, RebuildDBCharNexusFriend, RebuildDBCharTask, PlayerDataStrategy::rebuildMem, SafeDeleteDBPlayer, SeLoadingFlag, DBServer::SendDB_CharLoginLoad, DBServer::SendDB_CharQueryValid, DBServer::SendDB_FriendLadderInfoLoad, DBServer::SendDB_LoadInfo, SetDBPlayerOnline, Update.
SeDBPlayer * SeDBPlayerMgr::GetDBPlayerByName(const char *pcName)
References GetDBPlayer, m_kMapCharName2Player, SeDBPlayer::pkCharInfo, SSD_MAX_CHAR_NAME.
Referenced by DBServer::ProcessWB_IsPlayerExist.
bool SeDBPlayerMgr::DBPlayerLoad(DWord dwPlayerID)
References AttachLink, SeDBPlayer::bOnline, CreateDBPlayer, DetachLink, SeDBPlayer::dwLoadStartTime, g_kDBServer, GetDBPlayer, DBServer::GetLogShowType, DBServer::GetServerTime, IsPlayerLoadComplete, SeLogError, SeLogInfo, DBServer::SendBBL_PlayerLoadRet, DBServer::SendDB_LoadInfo, SetDBPlayerOnline, DBServer::SetLoginLogInfo, UpdatePlayerLastLoginTime.
Referenced by DBServer::ProcessWB_LoadPlayerInfoAgain, DBServer::ProcessWB_PlayerLoad.
void SeDBPlayerMgr::SeLoadingFlag(DWord dwPlayerID, int iFlag)
References GetDBPlayer, IsPlayerLoadComplete, onLoadingComplete, SeDBPlayer::SetLoadFlag.
Referenced by CharInfoStrategy::onLoadData, PlayerDataStrategy::onLoadData, DBServer::ProcessDB_CharNexusFriendLoad, DBServer::SendDB_LoadInfo.
void SeDBPlayerMgr::SeLoadingFlag(DWord dwPlayerID, SeDBTableIndex eTable)
References GetDBPlayer, IsPlayerLoadComplete, onLoadingComplete, SeDBPlayer::setLoadFlag.
void SeDBPlayerMgr::SetDBPlayerOnline(DWord dwPlayerID, bool bOnline)
References AttachLink, SeDBPlayer::bOnline, DetachLink, GetDBPlayer, SaveToDB.
Referenced by DBPlayerLoad, DBServer::ProcessWB_LoadPlayerInfoAgain, DBServer::ProcessWB_PlayerLoad, DBServer::ProcessWB_PlayerOffLine.
void SeDBPlayerMgr::SaveAllPlayerToDB(void)
References m_bSaveAllPlayerToDB, m_kMapDBPlayerLink, m_kPlayerLinkItr.
bool SeDBPlayerMgr::IsPlayerLoadComplete(SeDBPlayer *pkPlayer)
References SeDBPlayer::HasLoadFlag, SeDBPlayer::pkCharInfo, PLF_ALL_FLAG, SeDBPlayer::setLoadFlag.
Referenced by ClearDBPlayer, DBPlayerLoad, DBServer::Excu_SelectData, GenCacheInitID, DBServer::GetPlayerFieldData, DBServer::GetPlayerFieldDate, DBServer::GetPlayerFieldNum, DBServer::GetPlayerFieldNum64, DBServer::GetPlayerFieldStr, DBServer::GetPlayerRecordCount, handleEachPlayer, OnDataDelete, OnDataDiscard, OnDataUpdateNum, OnDataUpdateNum64, OnDataUpdateString, OnDataUpdateTime, DBServer::ProcessWB_IsPlayerExist, DBServer::ProcessWB_LoadPlayerInfoAgain, DBServer::ProcessWS_Insert_NoReceipt, DBServer::ProcessWS_Update_NoReceipt, SaveToDB, SeLoadingFlag, DBServer::SendDB_CharLoginLoad, DBServer::SendDB_CharQueryValid, DBServer::SendDB_FriendLadderInfoLoad, Update, UpdatePlayerLastLoginTime.
void SeDBPlayerMgr::AddCharNameRecord(const char *pcName, DWord dwPlayerID)
References m_kMapCharName2Player.
Referenced by CharInfoStrategy::onLoadData, DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery, CharInfoStrategy::rebuildMem.
void SeDBPlayerMgr::DelCharNameRecord(const char *pcName)
References m_kMapCharName2Player.
Referenced by DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery.
bool SeDBPlayerMgr::IsRepeatName(const char *pkName)
References m_kMapDBPlayerLink, m_kMCreateQueryName, SeDBPlayer::pkCharInfo.
Referenced by DBServer::ProcessWS_CharAdd.
void SeDBPlayerMgr::AddCreateQueryName(DWord dwPlayerID, const char *pkName)
References m_kMCreateQueryName.
Referenced by DBServer::ProcessWS_CharAdd, DBServer::SendDB_CharRenameBegin.
std::string SeDBPlayerMgr::DelCreateQueryName(DWord dwPlayerID)
References kName, m_kMCreateQueryName.
Referenced by DBServer::ProcessDB_CharAdd, DBServer::ProcessDB_IsPlayerExistByAccountOrName.
DWord SeDBPlayerMgr::GenCacheInitID(SeInitGenIDType eType)
References SeDBPlayer::akNexusFriend, IsPlayerLoadComplete, m_kMapDBPlayerLink, SIGT_NEXUSFRIEND.
Referenced by DBServer::SendDB_InitGenID.
void SeDBPlayerMgr::OnDataInsert(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
References SeDBPlayer::bIsInSaving, DataInsert, GetDBPlayer, m_iResCount.
Referenced by DBServer::ProcessWS_Insert_NoReceipt.
void SeDBPlayerMgr::OnDataUpdateNum(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, DWord dwValue, bool bAdd=false, bool bRefresh=false, DWord dwPara1=0)
References SeDBPlayer::bIsInSaving, DataUpdate, g_kDBServer, GetDBPlayer, DBServer::GetPlayerFieldNum, IsPlayerLoadComplete, m_iResCount, SeLogError.
Referenced by DBServer::ProcessWS_Update_NoReceipt.
void SeDBPlayerMgr::OnDataUpdateString(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, const char *pcString, DWord dwPara1=0)
References SeDBPlayer::bIsInSaving, DataUpdate, GetDBPlayer, IsPlayerLoadComplete, m_iResCount, SeLogError.
Referenced by DBServer::ProcessWS_Update_NoReceipt.
void SeDBPlayerMgr::OnDataUpdateTime(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, const SeDBTime &rkTime, DWord dwPara1=0)
References SeDBPlayer::bIsInSaving, DataUpdate, GetDBPlayer, IsPlayerLoadComplete, m_iResCount, SeLogError.
Referenced by DBServer::ProcessWS_Update_NoReceipt.
void SeDBPlayerMgr::OnDataDiscard(DWord dwPlayerID, SeDBTableIndex eTable, DWord dwlID, int iDeleteReason, const SeDBTime &rkDeleteTime)
References SeDBPlayer::bIsInSaving, DataDiscard, GetDBPlayer, IsPlayerLoadComplete, m_iResCount, SeLogError.
Referenced by DBServer::ProcessWB_DataDiscard.
void SeDBPlayerMgr::OnDataDelete(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID)
References SeDBPlayer::bIsInSaving, DataDelete, GetDBPlayer, IsPlayerLoadComplete, m_iResCount, SeLogError.
Referenced by DBServer::ProcessWB_DataDelete.
void SeDBPlayerMgr::OnDataUpdateNum64(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, uint64_t uivalue, bool bAdd=false, bool bRefresh=false, DWord dwPara1=0)
References SeDBPlayer::bIsInSaving, DataUpdate, g_kDBServer, GetDBPlayer, DBServer::GetPlayerFieldNum64, IsPlayerLoadComplete, m_iResCount, SeLogError.
Referenced by DBServer::ProcessWS_Update_NoReceipt.
void SeDBPlayerMgr::handleEachPlayer(PlayerHandler &handler)
References PlayerHandler::execute, IsPlayerLoadComplete, m_kMapDBPlayerLink.
Referenced by PlayerDataStrategy::getCacheInitID.
void SeDBPlayerMgr::incResCount()
References m_iResCount.
Referenced by CharInfoStrategy::rebuildMem, PlayerDataStrategy::rebuildMem.
SeDBPlayer * SeDBPlayerMgr::CreateDBPlayer_Offline(DWord dwPlayerID)
References SeDBPlayer::dwPlayerID, GetDBPlayer, m_kMapDBPlayerLink, SeDBPlayer::pkCharInfo.
Referenced by DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend.
SeDBPlayerMgr::SeDBPlayerMgr(void)
SeDBPlayerMgr::~SeDBPlayerMgr(void)
bool SeDBPlayerMgr::Initialize(void)
void SeDBPlayerMgr::Update(void)
void SeDBPlayerMgr::Finialize(void)
void SeDBPlayerMgr::RebuildDBCharTask(VDBCharTask &rkVCharTask)
void SeDBPlayerMgr::RebuildDBCharMemory(VDBCharMemory &rkVCharMemory)
void SeDBPlayerMgr::RebuildDBCharNexusFriend(VDBCharNexusFriend &rkNexusFriend)
DWord SeDBPlayerMgr::GetNextClearPlayerID()
void SeDBPlayerMgr::AddClearPlayerID(DWord dwPlayerID)
int SeDBPlayerMgr::GetResCount()
int SeDBPlayerMgr::GetNameRecordCount()
int SeDBPlayerMgr::GetDBPlayerNums()
void SeDBPlayerMgr::SetCycleNums(int iNums)
int SeDBPlayerMgr::GetCycleNums()
void SeDBPlayerMgr::SetCyclePlayerNums(int iNums)
int SeDBPlayerMgr::GetCyclePlayerNums()
int SeDBPlayerMgr::GetCharMemoryCount(DWord dwPlayerID)
SeDBCharMemory* SeDBPlayerMgr::GetCharMemoryByIndex(DWord dwPlayerID, int iIndex)
void SeDBPlayerMgr::UpdateCharMemoryData(DWord dwPlayerID, DWord dwType, DWord dwParam, DWord dwValue, SeDBTime &rkEndTime)
SeDBPlayer* SeDBPlayerMgr::GetDBPlayer(DWord dwPlayerID)
SeDBPlayer* SeDBPlayerMgr::GetDBPlayerByName(const char *pcName)
bool SeDBPlayerMgr::DBPlayerLoad(DWord dwPlayerID)
void SeDBPlayerMgr::SeLoadingFlag(DWord dwPlayerID, int iFlag)
void SeDBPlayerMgr::SeLoadingFlag(DWord dwPlayerID, SeDBTableIndex eTable)
void SeDBPlayerMgr::SetDBPlayerOnline(DWord dwPlayerID, bool bOnline)
void SeDBPlayerMgr::SaveAllPlayerToDB(void)
bool SeDBPlayerMgr::IsPlayerLoadComplete(SeDBPlayer *pkPlayer)
void SeDBPlayerMgr::AddCharNameRecord(const char *pcName, DWord dwPlayerID)
void SeDBPlayerMgr::DelCharNameRecord(const char *pcName)
bool SeDBPlayerMgr::IsRepeatName(const char *pkName)
void SeDBPlayerMgr::AddCreateQueryName(DWord dwPlayerID, const char *pkName)
std::string SeDBPlayerMgr::DelCreateQueryName(DWord dwPlayerID)
DWord SeDBPlayerMgr::GenCacheInitID(SeInitGenIDType eType)
void SeDBPlayerMgr::OnDataInsert(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
void SeDBPlayerMgr::OnDataUpdateNum(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, DWord dwValue, bool bAdd=false, bool bRefresh=false, DWord dwPara1=0)
void SeDBPlayerMgr::OnDataUpdateString(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, const char *pcString, DWord dwPara1=0)
void SeDBPlayerMgr::OnDataUpdateTime(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, const SeDBTime &rkTime, DWord dwPara1=0)
void SeDBPlayerMgr::OnDataDiscard(DWord dwPlayerID, SeDBTableIndex eTable, DWord dwlID, int iDeleteReason, const SeDBTime &rkDeleteTime)
void SeDBPlayerMgr::OnDataDelete(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID)
void SeDBPlayerMgr::OnDataUpdateNum64(DWord dwPlayerID, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, uint64_t uivalue, bool bAdd=false, bool bRefresh=false, DWord dwPara1=0)
void SeDBPlayerMgr::handleEachPlayer(PlayerHandler &handler)
void SeDBPlayerMgr::incResCount()
SeDBPlayer* SeDBPlayerMgr::CreateDBPlayer_Offline(DWord dwPlayerID)
SeDBPlayer * SeDBPlayerMgr::CreateDBPlayer(DWord dwPlayerID)
References DBPlayerLinkItrJoin, SeDBPlayer::dwPlayerID, GetDBPlayer, m_kMapDBPlayerLink, SeDBPlayer::pkCharInfo.
Referenced by DBPlayerLoad.
int SeDBPlayerMgr::ClearDBPlayer(DWord dwPlayerID, DWord dwMagic=0)
References SeDBPlayer::bOnline, DetachLink, DetachList, GetDBPlayer, IsPlayerLoadComplete, m_pkFirst, m_pkLast, SafeDeleteDBPlayer, SaveToDB, SeLogError.
Referenced by AttachLink, Update.
int SeDBPlayerMgr::SafeDeleteDBPlayer(DWord dwPlayerID, DWord dwMagic=0)
References SeDBPlayer::akNexusFriend, SeDBPlayer::akTask, DBPlayerLinkItrLeave, g_kPlayerDataMgr, GetDBPlayer, m_kMapDBPlayerLink, PlayerDataMgr::safeDeleteDBPlayer.
Referenced by ClearDBPlayer, Finialize.
int SeDBPlayerMgr::SaveToDB(SeDBPlayer *pkDBPlayer, bool bOffLine=false)
References SeDBPlayer::akNexusFriend, SeDBPlayer::bIsInSaving, SeDBPlayer::dwPlayerID, g_kDBServer, g_kPlayerDataMgr, DBServer::GetDBConnectNums, DBServer::GetDBIndex, IsPlayerLoadComplete, m_iResCount, PlayerDataMgr::saveToDB, SCT_NULL, SDTI_CharNexusFriend.
Referenced by ClearDBPlayer, SetDBPlayerOnline, Update.
void SeDBPlayerMgr::DetachLink(DWord dwPlayerID)
References DetachList, GetDBPlayer, m_pkFirst, m_pkLast.
Referenced by ClearDBPlayer, DBPlayerLoad, SetDBPlayerOnline.
void SeDBPlayerMgr::AttachLink(DWord dwPlayerID)
References AttachList, ClearDBPlayer, DetachList, SeDBPlayer::dwPlayerID, g_kDBServer, GetDBPlayer, DBServer::GetMaxCacheNums, SeDBPlayer::iLoadFlag, m_kMapDBPlayerLink, m_pkFirst, m_pkLast, SeLogError.
Referenced by DBPlayerLoad, onLoadingComplete, CharInfoStrategy::rebuildMem, SetDBPlayerOnline.
void SeDBPlayerMgr::DBPlayerLinkItrJoin(DWord dwID)
References m_kItrDBPlayerLink, m_kMapDBPlayerLink.
Referenced by CreateDBPlayer, CharInfoStrategy::rebuildMem.
void SeDBPlayerMgr::DBPlayerLinkItrLeave(DWord dwID)
References m_kItrDBPlayerLink, m_kMapDBPlayerLink.
Referenced by SafeDeleteDBPlayer.
void SeDBPlayerMgr::DataInsert(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
References SeDBPlayer::akNexusFriend, SeDBPlayer::akTask, PlayerDataMgr::dataInsert, SeDBPlayer::dwPlayerID, g_kPlayerDataMgr, SCT_DELETE, SCT_INSERT, SCT_UPDATE, SDTI_CharNexusFriend, SDTI_CharTask, SeLogError.
Referenced by OnDataInsert.
void SeDBPlayerMgr::DataUpdate(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, void *pkData, DWord dwParam1=0)
References SeDBPlayer::akNexusFriend, SeDBPlayer::akTask, PlayerDataMgr::dataUpdate, SeDBPlayer::dwPlayerID, g_kPlayerDataMgr, SCT_UPDATE, SDTI_CharNexusFriend, SDTI_CharTask, SeLogError.
Referenced by OnDataUpdateNum, OnDataUpdateNum64, OnDataUpdateString, OnDataUpdateTime.
void SeDBPlayerMgr::DataDiscard(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable, DWord dwlID, int iDeleteReason, const SeDBTime &rkDeleteTime)
Referenced by OnDataDiscard.
void SeDBPlayerMgr::DataDelete(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable, uint64_t dwlID)
References SeDBPlayer::akNexusFriend, SeDBPlayer::akTask, PlayerDataMgr::dataDelete, SeDBPlayer::dwPlayerID, g_kPlayerDataMgr, SCT_DELETE, SDTI_CharNexusFriend, SDTI_CharTask, SeLogError.
Referenced by OnDataDelete.
void SeDBPlayerMgr::UpdatePlayerLastLoginTime(SeDBPlayer *pkDBPlayer)
References IsPlayerLoadComplete, NowTime.
Referenced by DBPlayerLoad, onLoadingComplete.
SeDBPlayer* SeDBPlayerMgr::CreateDBPlayer(DWord dwPlayerID)
int SeDBPlayerMgr::ClearDBPlayer(DWord dwPlayerID, DWord dwMagic=0)
int SeDBPlayerMgr::SafeDeleteDBPlayer(DWord dwPlayerID, DWord dwMagic=0)
int SeDBPlayerMgr::SaveToDB(SeDBPlayer *pkDBPlayer, bool bOffLine=false)
void SeDBPlayerMgr::DetachLink(DWord dwPlayerID)
void SeDBPlayerMgr::AttachLink(DWord dwPlayerID)
void SeDBPlayerMgr::DBPlayerLinkItrJoin(DWord dwID)
void SeDBPlayerMgr::DBPlayerLinkItrLeave(DWord dwID)
void SeDBPlayerMgr::DataInsert(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
void SeDBPlayerMgr::DataUpdate(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable, uint64_t dwlID, int iIndex, void *pkData, DWord dwParam1=0)
void SeDBPlayerMgr::DataDiscard(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable, DWord dwlID, int iDeleteReason, const SeDBTime &rkDeleteTime)
void SeDBPlayerMgr::DataDelete(SeDBPlayer *pkDBPlayer, SeDBTableIndex eTable, uint64_t dwlID)
void SeDBPlayerMgr::UpdatePlayerLastLoginTime(SeDBPlayer *pkDBPlayer)
void SeDBPlayerMgr::onLoadingComplete(SeDBPlayer &player)
References AttachLink, SeDBPlayer::bOnline, SeDBPlayer::dwLoadStartTime, SeDBPlayer::dwPlayerID, g_kDBServer, DBServer::GetLogShowType, DBServer::GetServerTime, SeLogInfo, DBServer::SendBBL_PlayerLoadRet, DBServer::SetLoginLogInfo, UpdatePlayerLastLoginTime.
Referenced by SeLoadingFlag.
void SeDBPlayerMgr::onLoadingComplete(SeDBPlayer &player)