AppendSkillTableMgr
std::map<unsigned int,AppendSkillTable*> AppendSkillTableMgr::m_kAppendSkillTableMap
Referenced by FillData, GetAppendSkillTable, GetAppendSkillTableMap, GetAppendSkillTableVec, ~AppendSkillTableMgr.
AppendSkillTableMgr * AppendSkillTableMgr::m_pkAppendSkillTableMgr
Referenced by Get, ReLoad.
AppendSkillTableMgr * AppendSkillTableMgr::Get()
References AppendSkillTableMgr, m_pkAppendSkillTableMgr.
Referenced by FreshSkill, GlobalTableMgr::GetAppendSkillTable, TableMgr::LoadTable, ReLoad.
AppendSkillTableMgr * AppendSkillTableMgr::ReLoad()
References Get, m_pkAppendSkillTableMgr.
Referenced by TableMgr::ReloadTable.
AppendSkillTableMgr::AppendSkillTableMgr()
References Load.
Referenced by Get.
AppendSkillTableMgr::~AppendSkillTableMgr()
References m_kAppendSkillTableMap.
const AppendSkillTable * AppendSkillTableMgr::GetAppendSkillTable(unsigned int iTypeID)
References m_kAppendSkillTableMap.
Referenced by FreshSkill, GlobalTableMgr::GetAppendSkillTable.
const std::map< unsigned int, AppendSkillTable * > & AppendSkillTableMgr::GetAppendSkillTableMap()
References m_kAppendSkillTableMap.
TableResArray AppendSkillTableMgr::GetAppendSkillTableVec()
References m_kAppendSkillTableMap, TableResArray::pushBack.
bool AppendSkillTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AppendSkillTableMgr.
void AppendSkillTableMgr::FillData(AppendSkillTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AppendSkillTable::iMaxDataA, AppendSkillTable::iMaxDataB, AppendSkillTable::iMaxDataC, AppendSkillTable::iMinDataA, AppendSkillTable::iMinDataB, AppendSkillTable::iMinDataC, AppendSkillTable::kAppendName, AppendSkillTable::kDesc, AppendSkillTable::kRandomPR, m_kAppendSkillTableMap, AppendSkillTable::uiAppendID, AppendSkillTable::uiitemValue, AppendSkillTable::uiProperty, AppendSkillTable::uiSkillID, AppendSkillTable::uiSkillType.
Referenced by Load.