HorseTableMgr
std::map<unsigned int,HorseTable*> HorseTableMgr::m_kHorseTableMap
Referenced by FillData, GetHorseTable, GetHorseTableMap, GetHorseTableVec, ~HorseTableMgr.
HorseTableMgr * HorseTableMgr::m_pkHorseTableMgr
Referenced by Get, ReLoad.
HorseTableMgr * HorseTableMgr::Get()
References HorseTableMgr, m_pkHorseTableMgr.
Referenced by TableMgr::InitHorsePosIndex, ReLoad.
HorseTableMgr * HorseTableMgr::ReLoad()
References Get, m_pkHorseTableMgr.
HorseTableMgr::HorseTableMgr()
References Load.
Referenced by Get.
HorseTableMgr::~HorseTableMgr()
References m_kHorseTableMap.
const HorseTable * HorseTableMgr::GetHorseTable(unsigned int iTypeID)
References m_kHorseTableMap.
const std::map< unsigned int, HorseTable * > & HorseTableMgr::GetHorseTableMap()
References m_kHorseTableMap.
Referenced by TableMgr::InitHorsePosIndex.
TableResArray HorseTableMgr::GetHorseTableVec()
References m_kHorseTableMap, TableResArray::pushBack.
bool HorseTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by HorseTableMgr.
void HorseTableMgr::FillData(HorseTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, HorseTable::iAssistPowerValue, HorseTable::iAttackPowerValue, HorseTable::iBasicHorsePower, HorseTable::iDefensePowerValue, HorseTable::iLevelAddHorsePower, HorseTable::iMagicPowerValue, HorseTable::iModelFile, HorseTable::iName, HorseTable::kIcon, HorseTable::kName_China, m_kHorseTableMap, HorseTable::uiHorseID.
Referenced by Load.