AITableMgr
std::map<unsigned int,AITable*> AITableMgr::m_kAITableMap
Referenced by FillData, GetAITable, GetAITableMap, GetAITableVec, ~AITableMgr.
AITableMgr * AITableMgr::m_pkAITableMgr
Referenced by Get, ReLoad.
AITableMgr * AITableMgr::Get()
References AITableMgr, m_pkAITableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
AITableMgr * AITableMgr::ReLoad()
References Get, m_pkAITableMgr.
Referenced by TableMgr::ReloadTable.
AITableMgr::AITableMgr()
References Load.
Referenced by Get.
AITableMgr::~AITableMgr()
References m_kAITableMap.
const AITable * AITableMgr::GetAITable(unsigned int iTypeID)
References m_kAITableMap.
const std::map< unsigned int, AITable * > & AITableMgr::GetAITableMap()
References m_kAITableMap.
TableResArray AITableMgr::GetAITableVec()
References m_kAITableMap, TableResArray::pushBack.
bool AITableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AITableMgr.
void AITableMgr::FillData(AITable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AITable::fEPBuilding, AITable::fEPClass, AITable::fEPDemlisher, AITable::fEPDistance, AITable::fEPHero, AITable::fEPHp, AITable::fEPMonster, AITable::fEPSoldier, AITable::kDesc, m_kAITableMap, AITable::uiAITypeID.
Referenced by Load.