MapsInfoTableMgr
std::map<unsigned int,MapsInfoTable*> MapsInfoTableMgr::m_kMapsInfoTableMap
Referenced by FillData, GetMapsInfoTable, GetMapsInfoTableMap, GetMapsInfoTableVec, ~MapsInfoTableMgr.
MapsInfoTableMgr * MapsInfoTableMgr::m_pkMapsInfoTableMgr
Referenced by Get, ReLoad.
MapsInfoTableMgr * MapsInfoTableMgr::Get()
References m_pkMapsInfoTableMgr, MapsInfoTableMgr.
Referenced by RaceDetailMgr::CreateRaceDetail, GlobalTableMgr::GetMapsInfoTable, ReLoad.
MapsInfoTableMgr * MapsInfoTableMgr::ReLoad()
References Get, m_pkMapsInfoTableMgr.
MapsInfoTableMgr::MapsInfoTableMgr()
References Load.
Referenced by Get.
MapsInfoTableMgr::~MapsInfoTableMgr()
References m_kMapsInfoTableMap.
const MapsInfoTable * MapsInfoTableMgr::GetMapsInfoTable(unsigned int iTypeID)
References m_kMapsInfoTableMap.
Referenced by GlobalTableMgr::GetMapsInfoTable.
const std::map< unsigned int, MapsInfoTable * > & MapsInfoTableMgr::GetMapsInfoTableMap()
References m_kMapsInfoTableMap.
Referenced by RaceDetailMgr::CreateRaceDetail.
TableResArray MapsInfoTableMgr::GetMapsInfoTableVec()
References m_kMapsInfoTableMap, TableResArray::pushBack.
bool MapsInfoTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by MapsInfoTableMgr.
void MapsInfoTableMgr::FillData(MapsInfoTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, MapsInfoTable::iAreaRange, MapsInfoTable::iBelongsTowerName, MapsInfoTable::iborntime, MapsInfoTable::iCreepGroupN, MapsInfoTable::iExpandX, MapsInfoTable::iExpandY, MapsInfoTable::iLinkUnitType, MapsInfoTable::iMapHomeRot, MapsInfoTable::iNextAreaID, MapsInfoTable::ireborntime, MapsInfoTable::iUnionAreaID, MapsInfoTable::iUnitPosX, MapsInfoTable::iUnitPosY, MapsInfoTable::iUnitPosZ, MapsInfoTable::kDestoryedSoundID, MapsInfoTable::kUnderAttackSoundID, MapsInfoTable::kUnitTips, m_kMapsInfoTableMap, MapsInfoTable::uiLinkMaps, MapsInfoTable::uiMapUnitID, MapsInfoTable::uiMapUnitType.
Referenced by Load.