TaskRecomTableMgr
std::map<unsigned int,TaskRecomTable*> TaskRecomTableMgr::m_kTaskRecomTableMap
Referenced by FillData, GetTaskRecomTable, GetTaskRecomTableMap, GetTaskRecomTableVec, ~TaskRecomTableMgr.
TaskRecomTableMgr * TaskRecomTableMgr::m_pkTaskRecomTableMgr
Referenced by Get, ReLoad.
TaskRecomTableMgr * TaskRecomTableMgr::Get()
References m_pkTaskRecomTableMgr, TaskRecomTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
TaskRecomTableMgr * TaskRecomTableMgr::ReLoad()
References Get, m_pkTaskRecomTableMgr.
Referenced by TableMgr::ReloadTable.
TaskRecomTableMgr::TaskRecomTableMgr()
References Load.
Referenced by Get.
TaskRecomTableMgr::~TaskRecomTableMgr()
References m_kTaskRecomTableMap.
const TaskRecomTable * TaskRecomTableMgr::GetTaskRecomTable(unsigned int iTypeID)
References m_kTaskRecomTableMap.
const std::map< unsigned int, TaskRecomTable * > & TaskRecomTableMgr::GetTaskRecomTableMap()
References m_kTaskRecomTableMap.
TableResArray TaskRecomTableMgr::GetTaskRecomTableVec()
References m_kTaskRecomTableMap, TableResArray::pushBack.
bool TaskRecomTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by TaskRecomTableMgr.
void TaskRecomTableMgr::FillData(TaskRecomTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, TaskRecomTable::iPlayerLevel, TaskRecomTable::iTaskList, m_kTaskRecomTableMap, TaskRecomTable::uiID.
Referenced by Load.