WatchServer::SeRaceRecordSaveThread
bool WatchServer::SeRaceRecordSaveThread::m_bRun
Referenced by DoWork, Finialize, Initialize, SeRaceRecordSaveThread.
CWatchServer* WatchServer::SeRaceRecordSaveThread::m_pkOwner
unsigned int WatchServer::SeRaceRecordSaveThread::m_uLogicVersion
Referenced by saveRecord.
TRaceTaskQueue WatchServer::SeRaceRecordSaveThread::m_qSaveQueue
Referenced by DoWork, Finialize, PushTask.
TRaceTaskQueue WatchServer::SeRaceRecordSaveThread::m_qFinishQueue
Referenced by DoWork, Update.
Es::NormalLock* WatchServer::SeRaceRecordSaveThread::m_pkQueueLock
Referenced by DoWork, Initialize, PushTask, Update.
SeRaceRecordSaveThread::SeRaceRecordSaveThread(CWatchServer *owner, unsigned int logciVersion)
References m_bRun.
SeRaceRecordSaveThread::~SeRaceRecordSaveThread(void)
void SeRaceRecordSaveThread::PushTask(class SeRace *pTask)
References m_pkQueueLock, m_qSaveQueue.
Referenced by WatchServer::CSeRaceMgr::Update.
bool SeRaceRecordSaveThread::Initialize(void)
References m_bRun, m_pkQueueLock.
Referenced by WatchServer::CSeRaceMgr::CSeRaceMgr.
void SeRaceRecordSaveThread::Finialize(void)
References m_bRun, m_qSaveQueue, saveRecord.
Referenced by WatchServer::CSeRaceMgr::~CSeRaceMgr.
void SeRaceRecordSaveThread::Update()
References m_pkQueueLock, m_qFinishQueue.
Referenced by WatchServer::CSeRaceMgr::Update.
void SeRaceRecordSaveThread::DoWork(void)
References m_bRun, m_pkQueueLock, m_qFinishQueue, m_qSaveQueue, saveRecord.
void SeRaceRecordSaveThread::saveRecord(class SeRace *pTask)
References TeMD5::abyMD5, WatchServer::SeWatchConfig::acGameRecordFilePath, g_kWatchServer, GetMD52Str, WatchServer::CWatchServer::GetWatchConfig, WatchServer::SeRace::kRaceID, WatchServer::SeRace::kSvrModeRecord, m_uLogicVersion, SeRaceRecord::SaveToFile, SPrintf.
Referenced by DoWork, Finialize.