ItemComposeTableMgr
std::map<unsigned int,ItemComposeTable*> ItemComposeTableMgr::m_kItemComposeTableMap
Referenced by FillData, GetItemComposeTable, GetItemComposeTableMap, GetItemComposeTableVec, ~ItemComposeTableMgr.
ItemComposeTableMgr * ItemComposeTableMgr::m_pkItemComposeTableMgr
Referenced by Get, ReLoad.
ItemComposeTableMgr * ItemComposeTableMgr::Get()
References ItemComposeTableMgr, m_pkItemComposeTableMgr.
Referenced by GlobalTableMgr::GetComposeeRecursively, TableMgr::GetItemComposee, GlobalTableMgr::GetItemComposeTable, TableMgr::InitReelMap, TableMgr::LoadTable, ReLoad.
ItemComposeTableMgr * ItemComposeTableMgr::ReLoad()
References Get, m_pkItemComposeTableMgr.
Referenced by TableMgr::ReloadTable.
ItemComposeTableMgr::ItemComposeTableMgr()
References Load.
Referenced by Get.
ItemComposeTableMgr::~ItemComposeTableMgr()
References m_kItemComposeTableMap.
const ItemComposeTable * ItemComposeTableMgr::GetItemComposeTable(unsigned int iTypeID)
References m_kItemComposeTableMap.
Referenced by TableMgr::GetItemComposee, GlobalTableMgr::GetItemComposeTable.
const std::map< unsigned int, ItemComposeTable * > & ItemComposeTableMgr::GetItemComposeTableMap()
References m_kItemComposeTableMap.
Referenced by TableMgr::InitReelMap.
TableResArray ItemComposeTableMgr::GetItemComposeTableVec()
References m_kItemComposeTableMap, TableResArray::pushBack.
bool ItemComposeTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by ItemComposeTableMgr.
void ItemComposeTableMgr::FillData(ItemComposeTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, ItemComposeTable::kMeaterialA, ItemComposeTable::kMeaterialB, ItemComposeTable::kMeaterialC, ItemComposeTable::kMeaterialD, ItemComposeTable::kSpecialDesc, m_kItemComposeTableMap, ItemComposeTable::uiItemIDA, ItemComposeTable::uiItemIDB, ItemComposeTable::uiItemIDC, ItemComposeTable::uiItemIDD, ItemComposeTable::uiNeedMatTNum, ItemComposeTable::uiProperty, ItemComposeTable::uiReelID, ItemComposeTable::uiTypeID.
Referenced by Load.