MissionInfoTableMgr
std::map<unsigned int,MissionInfoTable*> MissionInfoTableMgr::m_kMissionInfoTableMap
Referenced by FillData, GetMissionInfoTable, GetMissionInfoTableMap, GetMissionInfoTableVec, UpdateLanguadgeContent, ~MissionInfoTableMgr.
MissionInfoTableMgr * MissionInfoTableMgr::m_pkMissionInfoTableMgr
Referenced by Get, ReLoad.
MissionInfoTableMgr * MissionInfoTableMgr::Get()
References m_pkMissionInfoTableMgr, MissionInfoTableMgr.
Referenced by GlobalTableMgr::GetMissionInfoTable, GlobalTableMgr::GetMissionInfoTableMap, ReLoad, TableMgr::UpdateLanguageContent.
MissionInfoTableMgr * MissionInfoTableMgr::ReLoad()
References Get, m_pkMissionInfoTableMgr.
MissionInfoTableMgr::MissionInfoTableMgr()
References Load.
Referenced by Get.
MissionInfoTableMgr::~MissionInfoTableMgr()
References m_kMissionInfoTableMap.
const MissionInfoTable * MissionInfoTableMgr::GetMissionInfoTable(unsigned int iTypeID)
References m_kMissionInfoTableMap.
Referenced by GlobalTableMgr::GetMissionInfoTable.
const std::map< unsigned int, MissionInfoTable * > & MissionInfoTableMgr::GetMissionInfoTableMap()
References m_kMissionInfoTableMap.
Referenced by GlobalTableMgr::GetMissionInfoTableMap.
TableResArray MissionInfoTableMgr::GetMissionInfoTableVec()
References m_kMissionInfoTableMap, TableResArray::pushBack.
void MissionInfoTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, MissionInfoTable::kMissionBeginTip, MissionInfoTable::kMissionBeginTipK, MissionInfoTable::kMissionDescTip, MissionInfoTable::kMissionDescTipK, MissionInfoTable::kMissionName, MissionInfoTable::kMissionNameK, MissionInfoTable::kMissionTimeTip, MissionInfoTable::kMissionTimeTipK, m_kMissionInfoTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool MissionInfoTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by MissionInfoTableMgr.
void MissionInfoTableMgr::FillData(MissionInfoTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, MissionInfoTable::iAddExp, MissionInfoTable::iAddMoney, MissionInfoTable::iAddPoint, MissionInfoTable::iItemCount, MissionInfoTable::iNextMission, MissionInfoTable::iRuleIDS, MissionInfoTable::iTimeDelay, MissionInfoTable::kDesc, MissionInfoTable::kMissionBeginTipK, MissionInfoTable::kMissionDescTipK, MissionInfoTable::kMissionNameK, MissionInfoTable::kMissionTimeTipK, m_kMissionInfoTableMap, MissionInfoTable::uiDifficulty, MissionInfoTable::uiMissionID, MissionInfoTable::uiMissionTarget, MissionInfoTable::uiMissionType.
Referenced by Load.