SeCacheMgr
MapAccountByID SeCacheMgr::m_kMapAccountByID
Referenced by AddAccount, Clear, DelAccount, GetAccountByID, GetCacheState, OnAccountLogout, SaveAllCacheToDB, SeCacheMgr, Update.
MapAccount SeCacheMgr::m_kMapAccount
Referenced by AddAccount, GetAccountByAccount.
MapOnlinePlayer SeCacheMgr::m_kOnlinePlayer
Referenced by GetCacheState, OnAccountLogin, OnAccountLogout.
SeCacheAccount * SeCacheMgr::m_pkOfflineHead
Referenced by AddAccount, Clear, DelAccount, OnAccountLogin, OnAccountLogout, SeCacheMgr.
SeCacheAccount * SeCacheMgr::m_pkOfflineEnd
Referenced by AddAccount, Clear, DelAccount, OnAccountLogin, OnAccountLogout, SeCacheMgr.
MapAccountByID::iterator SeCacheMgr::m_kCacheLinkItr
Referenced by DelAccount, SaveAllCacheToDB, SeCacheMgr, Update.
char SeCacheMgr::m_acClearAccount[64]
Referenced by SeCacheMgr, SetClearAccount, Update.
int SeCacheMgr::m_iMaxCycleNum
Referenced by GetMaxCycleNum, SeCacheMgr, SetMaxCycleNum.
bool SeCacheMgr::m_bSaveAllPlayerToDB
Referenced by SaveAllCacheToDB, SeCacheMgr, Update.
SeCacheMgr::SeCacheMgr(void)
References m_acClearAccount, m_bSaveAllPlayerToDB, m_iMaxCycleNum, m_kCacheLinkItr, m_kMapAccountByID, m_pkOfflineEnd, m_pkOfflineHead.
SeCacheMgr::~SeCacheMgr(void)
References Clear.
void SeCacheMgr::Update(void)
References SeFlagBase::ClrFlag, DelAccount, SeAccount::dwLastSaveTime, g_kGlobalServer, GlobalServer::GetDBQueryNums, GetMaxCycleNum, GlobalServer::GetServerTime, SeFlagBase::HasFlag, m_acClearAccount, m_bSaveAllPlayerToDB, m_kCacheLinkItr, m_kMapAccountByID, SAF_NEED_UPDATE, SeLogError, SeLogInfo, GlobalServer::SendDB_AccountUpdateData.
Referenced by GlobalServer::Update.
void SeCacheMgr::OnAccountLogin(SeAccount *pkAccount)
References DetachList, SeAccount::dwPlayerID, m_kOnlinePlayer, m_pkOfflineEnd, m_pkOfflineHead, SAF_LOGINED, SeFlagBase::SetFlag.
Referenced by GlobalServer::OnLoginQueryRet.
void SeCacheMgr::OnAccountLogout(DWord dwPlayerID)
References AttachList, SeFlagBase::ClrFlag, DetachList, m_kMapAccountByID, m_kOnlinePlayer, m_pkOfflineEnd, m_pkOfflineHead, SAF_LOGINED, SAF_NEED_UPDATE, SeFlagBase::SetFlag.
Referenced by GlobalServer::ProcessLG_PlayerLogout.
void SeCacheMgr::OnUpdateAccountDynamic(SeAccount *pkAccount, const char *pcIP, DWord dwAreaID)
References SeAccount::acLastLoginIP, SeAccount::acTemLoginIP, SeAccount::dwLastLoginAreaID, SeAccount::dwTotalLoginCount, SeAccount::kLastLoginTime, SeAccount::kTemLoginTime, NowTime, SAF_NEED_UPDATE, SeFlagBase::SetFlag.
Referenced by GlobalServer::OnLoginQueryRet.
SeAccount * SeCacheMgr::AddAccount(const SeAccount &rkAccount)
References SeAccount::acAccount, DelAccount, SeAccount::dwPlayerID, g_kGlobalServer, GlobalServer::GetMaxCacheNum, m_kMapAccount, m_kMapAccountByID, m_pkOfflineEnd, m_pkOfflineHead, MemCpy.
Referenced by GlobalServer::ProcessDB_AccountQuery.
SeAccount * SeCacheMgr::GetAccountByID(DWord dwPlayerID)
References m_kMapAccountByID.
Referenced by GlobalServer::ProcessLG_PlayerTownIndex.
SeAccount * SeCacheMgr::GetAccountByAccount(std::string acc)
References m_kMapAccount.
Referenced by GlobalServer::ProcessLG_AccountLogin.
void SeCacheMgr::SetClearAccount(const char *pcAccount)
References m_acClearAccount, StrCpy.
void SeCacheMgr::SetMaxCycleNum(int iNum)
References m_iMaxCycleNum.
int SeCacheMgr::GetMaxCycleNum(void)
References m_iMaxCycleNum.
Referenced by Update.
void SeCacheMgr::GetCacheState(int &iOnlineNum, int &iCacheNum, int &iSelTownNum, int &iUnUpdateCount)
References SeFlagBase::HasFlag, SeAccount::iTownIndex, m_kMapAccountByID, m_kOnlinePlayer, SAF_NEED_UPDATE.
Referenced by GlobalServer::ShowConsoleTitle.
SeCacheMgr::SeCacheMgr(void)
SeCacheMgr::~SeCacheMgr(void)
void SeCacheMgr::Update(void)
void SeCacheMgr::OnAccountLogin(SeAccount *pkAccount)
void SeCacheMgr::OnAccountLogout(DWord dwPlayerID)
void SeCacheMgr::OnUpdateAccountDynamic(SeAccount *pkAccount, const char *pcIP, DWord dwAreaID)
SeAccount* SeCacheMgr::AddAccount(const SeAccount &rkAccount)
SeAccount* SeCacheMgr::GetAccountByID(DWord dwPlayerID)
SeAccount* SeCacheMgr::GetAccountByAccount(std::string acc)
void SeCacheMgr::SetClearAccount(const char *pcAccount)
void SeCacheMgr::SetMaxCycleNum(int iNum)
int SeCacheMgr::GetMaxCycleNum(void)
void SeCacheMgr::GetCacheState(int &iOnlineNum, int &iCacheNum, int &iSelTownNum, int &iUnUpdateCount)
void SeCacheMgr::Clear(void)
References m_kMapAccountByID, m_pkOfflineEnd, m_pkOfflineHead.
Referenced by ~SeCacheMgr.
void SeCacheMgr::SaveAllCacheToDB(void)
References m_bSaveAllPlayerToDB, m_kCacheLinkItr, m_kMapAccountByID.
void SeCacheMgr::DelAccount(SeCacheAccount *pkAccount)
References DetachList, SeAccount::dwPlayerID, m_kCacheLinkItr, m_kMapAccountByID, m_pkOfflineEnd, m_pkOfflineHead.
Referenced by AddAccount, Update.
void SeCacheMgr::Clear(void)
void SeCacheMgr::SaveAllCacheToDB(void)
void SeCacheMgr::DelAccount(SeCacheAccount *pkAccount)