RacehelpTableMgr
std::map<unsigned int,RacehelpTable*> RacehelpTableMgr::m_kRacehelpTableMap
Referenced by FillData, GetRacehelpTable, GetRacehelpTableMap, GetRacehelpTableVec, ~RacehelpTableMgr.
RacehelpTableMgr * RacehelpTableMgr::m_pkRacehelpTableMgr
Referenced by Get, ReLoad.
RacehelpTableMgr * RacehelpTableMgr::Get()
References m_pkRacehelpTableMgr, RacehelpTableMgr.
Referenced by TableMgr::InitRaceHelperRes, TableMgr::LoadTable, ReLoad.
RacehelpTableMgr * RacehelpTableMgr::ReLoad()
References Get, m_pkRacehelpTableMgr.
Referenced by TableMgr::ReloadTable.
RacehelpTableMgr::RacehelpTableMgr()
References Load.
Referenced by Get.
RacehelpTableMgr::~RacehelpTableMgr()
References m_kRacehelpTableMap.
const RacehelpTable * RacehelpTableMgr::GetRacehelpTable(unsigned int iTypeID)
References m_kRacehelpTableMap.
const std::map< unsigned int, RacehelpTable * > & RacehelpTableMgr::GetRacehelpTableMap()
References m_kRacehelpTableMap.
Referenced by TableMgr::InitRaceHelperRes.
TableResArray RacehelpTableMgr::GetRacehelpTableVec()
References m_kRacehelpTableMap, TableResArray::pushBack.
bool RacehelpTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RacehelpTableMgr.
void RacehelpTableMgr::FillData(RacehelpTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RacehelpTable::iUnitName, RacehelpTable::kArcherRecom, RacehelpTable::kHeroHelp, RacehelpTable::kMageRecom, RacehelpTable::kMasteryRecom, RacehelpTable::kName_China, RacehelpTable::kSkillRecom, RacehelpTable::kTankRecom, RacehelpTable::kWarriarRecom, m_kRacehelpTableMap, RacehelpTable::uiUnitTypeID.
Referenced by Load.