SeDBMemMgr
char SeDBMemMgr::m_acName[64][64]
Referenced by Initialize, LoadConfig, SeDBMemMgr.
DWord SeDBMemMgr::m_dwTag
Referenced by GetMemTag, LoadConfig, SeDBMemMgr.
void* SeDBMemMgr::m_pkBaseMemAddr
Referenced by AllocEleMass, GetEleMassAddr, InitializeMem, MemCheckOutFunc, SeDBMemMgr.
SIZE_T SeDBMemMgr::m_stTotalMemSize
Referenced by AllocEleMass, GetTotalSize, InitializeMem, SeDBMemMgr.
SIZE_T SeDBMemMgr::m_stAllocMemSize
Referenced by AddAllocSize, AllocEleMass, GetAllocSize, InitializeMem, MemCheckOutFunc, SeDBMemMgr.
SIZE_T SeDBMemMgr::m_stMinMemSize
Referenced by AllocEleMass, GetMinMemSize, Initialize, LoadConfig, SeDBMemMgr.
SeDBMemMgr::SeDBMemMgr(void)
References m_acName, m_dwTag, m_pkBaseMemAddr, m_stAllocMemSize, m_stMinMemSize, m_stTotalMemSize.
SeDBMemMgr::~SeDBMemMgr(void)
bool SeDBMemMgr::Initialize(void)
References InitializeMem, LoadConfig, m_acName, m_stMinMemSize, SeLogError.
Referenced by DBServer::Initialize.
SIZE_T SeDBMemMgr::GetMinMemSize()
References m_stMinMemSize.
Referenced by DBServer::RebuildMem.
DWord SeDBMemMgr::GetMemTag()
References m_dwTag.
Referenced by DBServer::RebuildMem.
SIZE_T SeDBMemMgr::GetTotalSize()
References m_stTotalMemSize.
Referenced by DBServer::RebuildMem.
void * SeDBMemMgr::GetEleMassAddr()
References m_pkBaseMemAddr.
Referenced by DBServer::RebuildMem.
SIZE_T SeDBMemMgr::GetAllocSize()
References m_stAllocMemSize.
Referenced by DBServer::RebuildMem, DBServer::ShowConsoleTitle.
void SeDBMemMgr::AddAllocSize(SIZE_T stSize)
References m_stAllocMemSize.
Referenced by DBServer::RebuildMem.
bool SeDBMemMgr::MemCheckOutFunc(DWord dwMagic, DWord dwVersion)
References AllocEleMass, SeEleMass::dwMagic, SeEleMass::dwTag, GetID2Str, m_pkBaseMemAddr, m_stAllocMemSize, MemCpy, SeLogError.
void * SeDBMemMgr::AllocEleMass(DWord dwMagic, int iEleSize, int iEleNum)
References SeEleMass::dwEleNum, SeEleMass::dwEleSize, SeEleMass::dwMagic, SeEleMass::dwSize, SeEleMass::dwTag, GetID2Str, m_pkBaseMemAddr, m_stAllocMemSize, m_stMinMemSize, m_stTotalMemSize, SeLogError, SeLogInfo.
Referenced by SeDBMemPool::ExtendPool, MemCheckOutFunc.
bool SeDBMemMgr::LoadConfig(void)
References GetStr2ID, SeConfig::GetValue, SeConfig::Load, m_acName, m_dwTag, m_stMinMemSize, SeLogError, StrCpy.
Referenced by Initialize.
bool SeDBMemMgr::InitializeMem(const char *pcName, DWord dwMinSize)
References m_pkBaseMemAddr, m_stAllocMemSize, m_stTotalMemSize, SeLogError, SeLogInfo.
Referenced by Initialize.