SeMatchReconMgr
MID2ReconPPtr SeMatchReconMgr::m_kMID2ReconPPtr
Referenced by AddPlayer, DelPlayer, GetReconPlayer, IsReservedSeat, Update, ~SeMatchReconMgr.
MRoom2MSeat2ID SeMatchReconMgr::m_kMRoom2MSeat2ID
Referenced by FinishAllow, GetAllowPlayerID, InitAllow, IsAllowPlayer, IsAllowRoom, UpdatePlayerReservedSeat.
MID2PlayerName SeMatchReconMgr::m_kMID2PlayerName
Referenced by AddReconPlayerName, DelReconPlayerName, GetReconPlayerName, Update.
MRoomID2SeOldConInfo SeMatchReconMgr::m_mOldRaceConInfo
Referenced by AddRaceSeat, CheckCon2OldRace, RemoveRace, RemoveRaceSeat, Update.
SeMatchReconMgr::SeMatchReconMgr()
SeMatchReconMgr::~SeMatchReconMgr()
References m_kMID2ReconPPtr.
bool SeMatchReconMgr::Initialize(void)
void SeMatchReconMgr::Update(void)
References AddRaceSeat, SeReconPlayer::dwDisconTime, g_kRaceMgr, g_kRaceServer, RaceServer::GetMaxReconTime, SeRaceMgr::GetRaceByRoomIndex, RaceServer::GetServerTime, SeReconPlayer::iRoomIndex, SeReconPlayer::iSeatIndex, SeRace::iThreadIndex, SeRace::kRaceID, m_kMID2PlayerName, m_kMID2ReconPPtr, m_mOldRaceConInfo, RaceServer::PushRSC_SetRaceIncmpState, RaceServer::SendRM_AddIncompleteRace, UpdatePlayerReservedSeat.
Referenced by RaceServer::Update.
bool SeMatchReconMgr::Finalize(void)
void SeMatchReconMgr::AddPlayer(SeMatchPlayer *pkPlayer, const TeMD5 &rkRaceID)
References SeReconPlayer::acName, SeReconPlayer::dwAreaID, SeReconPlayer::dwDisconTime, SeReconPlayer::dwServerID, SeReconPlayer::eCamp, g_kRaceServer, SeMatchPlayer::GetAreaID, SeMatchPlayer::GetID, SeMatchPlayer::GetName, SeMatchPlayer::GetPlayerSeat, SeMatchPlayer::GetRoomPlayerCamp, SeMatchPlayer::GetRoomSessionID, SeMatchPlayer::GetServerID, RaceServer::GetServerTime, SeReconPlayer::iRoomIndex, SeReconPlayer::iSeatIndex, SeReconPlayer::kRaceID, m_kMID2ReconPPtr, StrCpy, UpdatePlayerReservedSeat.
Referenced by SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnRaceModeEnd.
void SeMatchReconMgr::UpdatePlayerReservedSeat(int iRoomIndex, int iSeat, DWord dwPlayerID)
References m_kMRoom2MSeat2ID.
Referenced by AddPlayer, Update.
void SeMatchReconMgr::DelPlayer(DWord dwPlayerID)
References m_kMID2ReconPPtr.
Referenced by SeRaceRoomMgr::OnReconValidOK, RaceServer::ProcessCR_RaceValidate.
const SeReconPlayer * SeMatchReconMgr::GetReconPlayer(DWord dwPlayerID)
References SeRace::eState, g_kRaceMgr, SeRaceMgr::GetRaceByRoomIndex, SeReconPlayer::iRoomIndex, SeReconPlayer::kRaceID, SeRace::kRaceID, m_kMID2ReconPPtr, RAS_VERIFY, RAS_VERIFY_END.
Referenced by SeRaceRoomMgr::OnPlayerReconQuery, RaceServer::ProcessCR_RaceValidate, SeRaceMgr::UpdateCheckOvertimeRace.
bool SeMatchReconMgr::IsReservedSeat(int iRoomIndex, int iSeat)
References GetAllowPlayerID, SeReconPlayer::iRoomIndex, SeReconPlayer::iSeatIndex, m_kMID2ReconPPtr.
Referenced by SeRaceRoomMgr::GetReloadRoomInfo, SeRaceRoomMgr::OnPlayerReconQuery.
void SeMatchReconMgr::InitAllow(int iRoomIndex)
References g_kRaceRoomMgr, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, SeRaceRoomMgr::GetRoom, m_kMRoom2MSeat2ID.
Referenced by SeRaceMgr::UpdateLoadEnd.
bool SeMatchReconMgr::IsAllowPlayer(int iRoomIndex, int iSeat, DWord dwPlayerID)
References m_kMRoom2MSeat2ID.
Referenced by SeRaceRoomMgr::OnPlayerReconQuery.
bool SeMatchReconMgr::IsAllowRoom(int iRoomIndex)
References m_kMRoom2MSeat2ID.
void SeMatchReconMgr::FinishAllow(int iRoomIndex)
References m_kMRoom2MSeat2ID.
Referenced by SeRaceMgr::UpdateRaceEnd.
const SeReconPlayerName * SeMatchReconMgr::GetReconPlayerName(DWord dwPlayerID) const
References m_kMID2PlayerName.
Referenced by RaceServer::ProcessCR_RaceValidate.
void SeMatchReconMgr::DelReconPlayerName(DWord dwPlayerID)
References m_kMID2PlayerName.
Referenced by SeRaceRoomMgr::OnReconValidOK.
void SeMatchReconMgr::AddReconPlayerName(DWord dwPlayerID, const char cName[])
References SeReconPlayerName::acName, SeReconPlayerName::dwTimeout, g_kRaceServer, RaceServer::GetServerTime, m_kMID2PlayerName, StrCpy.
Referenced by RaceServer::ProcessMR_ReconPLayerName.
DWord SeMatchReconMgr::GetAllowPlayerID(int iRoomIndex, int iSeat)
References m_kMRoom2MSeat2ID.
Referenced by IsReservedSeat.
void SeMatchReconMgr::AddRaceSeat(DWord iRoomSession, int iSeat)
References g_kRaceServer, m_mOldRaceConInfo, RaceServer::SendRM_UpdateIncompleteRace, SeOldRaceConInfo::setSeat.
Referenced by Update.
void SeMatchReconMgr::RemoveRaceSeat(int iRoomSession, int iSeat)
References SeOldRaceConInfo::checkSeat, g_kRaceServer, SeOldRaceConInfo::hasEmptySeat, m_mOldRaceConInfo, RemoveRace, RaceServer::SendRM_UpdateIncompleteRace, SeOldRaceConInfo::setSeat.
Referenced by SeRaceRoomMgr::OnReconValidOK.
void SeMatchReconMgr::RemoveRace(int iRoomSession)
References g_kRaceMgr, g_kRaceServer, SeRaceMgr::GetRaceByRoomIndex, SeRace::iThreadIndex, SeRace::kRaceID, m_mOldRaceConInfo, RaceServer::PushRSC_SetRaceIncmpState.
Referenced by RemoveRaceSeat.
bool SeMatchReconMgr::CheckCon2OldRace(int iRoomSession, int iSeat) const
References SeOldRaceConInfo::checkSeat, m_mOldRaceConInfo.
Referenced by SeRaceMgr::OnRaceKDA, RaceServer::ProcessCR_RaceValidate.
SeMatchReconMgr::SeMatchReconMgr()
SeMatchReconMgr::~SeMatchReconMgr()
bool SeMatchReconMgr::Initialize(void)
void SeMatchReconMgr::Update(void)
bool SeMatchReconMgr::Finalize(void)
void SeMatchReconMgr::AddPlayer(SeMatchPlayer *pkPlayer, const TeMD5 &rkRaceID)
void SeMatchReconMgr::UpdatePlayerReservedSeat(int iRoomIndex, int iSeat, DWord dwPlayerID)
void SeMatchReconMgr::DelPlayer(DWord dwPlayerID)
const SeReconPlayer* SeMatchReconMgr::GetReconPlayer(DWord dwPlayerID)
bool SeMatchReconMgr::IsReservedSeat(int iRoomIndex, int iSeat)
void SeMatchReconMgr::InitAllow(int iRoomIndex)
bool SeMatchReconMgr::IsAllowPlayer(int iRoomIndex, int iSeat, DWord dwPlayerID)
bool SeMatchReconMgr::IsAllowRoom(int iRoomIndex)
void SeMatchReconMgr::FinishAllow(int iRoomIndex)
const SeReconPlayerName* SeMatchReconMgr::GetReconPlayerName(DWord dwPlayerID) const
void SeMatchReconMgr::DelReconPlayerName(DWord dwPlayerID)
void SeMatchReconMgr::AddReconPlayerName(DWord dwPlayerID, const char cName[])
DWord SeMatchReconMgr::GetAllowPlayerID(int iRoomIndex, int iSeat)
void SeMatchReconMgr::AddRaceSeat(DWord iRoomSession, int iSeat)
void SeMatchReconMgr::RemoveRaceSeat(int iRoomSession, int iSeat)
void SeMatchReconMgr::RemoveRace(int iRoomSession)
bool SeMatchReconMgr::CheckCon2OldRace(int iRoomSession, int iSeat) const