HeroMgr
SePlayer & HeroMgr::m_owner
Referenced by getOwner.
std::map< DWord, SeDBCharHero * > HeroMgr::m_data
Referenced by fixData, getAllUnlockHeroInfo, getHeroInfo, loadData, sendInitData, setAvatar, unlockHero, ~HeroMgr.
HeroMgr::HeroMgr(SePlayer &owner)
HeroMgr::~HeroMgr()
References m_data.
void HeroMgr::loadData(const SeDBCharHero &item)
References m_data.
void HeroMgr::fixData()
References AVATAR_BEGIN, AVATAR_END, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, g_kCharHeroStrategy, CItemMgr::getItem, SePlayer::GetItemMgr, getOwner, isValidAvatar, m_data, s_avatars, s_varZero.
void HeroMgr::sendInitData()
References m_data, notifyChanged.
Referenced by SePlayer::OperateLoading.
void HeroMgr::unlockHero(int num, SeUnlockHeroBaseInfo *items)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, EUHS_SHOP, EUHS_WEEK, g_kCharHeroStrategy, FreeHeroesTableMgr::Get, HeroInfoTableMgr::Get, PlayerDataStrategy::getGenID, SePlayer::GetID, getOwner, SePlayer::getTaskMgr, SeUnlockHeroBaseInfo::heroID, m_data, SeUnlockHeroBaseInfo::mark, notifyChanged, NowTime, processAddHeroBindItem, TaskMgr::SettleTask, TASKINFO_CONDITON_JIESUOYINGXIONG.
Referenced by createFreeHeroes, CShop::ProcessHeroItem.
void HeroMgr::notifyChanged(const std::list< SeDBCharHero * > &items)
References SeWT_UserHeroSync::akHeroSyncInfo, SeUserHeroSyncInfo::dwSkin, SeUserHeroSyncInfo::dwWeapon, SeUserHeroSyncInfo::dwWing, g_kWorldServer, GetID, getOwner, GetTownSock, SeUserHeroSyncInfo::heroID, isValidHero, SeUserHeroSyncInfo::mark, SeWT_UserHeroSync::num, WorldServer::SendWT_UserHeroSync.
Referenced by sendInitData, unlockHero.
void HeroMgr::createFreeHeroes()
References FreeHeroesTableMgr::Get, FreeHeroesTableMgr::GetFreeHeroesTableMap, SeUnlockHeroBaseInfo::heroID, SeUnlockHeroBaseInfo::mark, FreeHeroesTable::uifeature, FreeHeroesTable::uiHeroID, unlockHero.
Referenced by SePlayer::OperateLoading.
void HeroMgr::getAllUnlockHeroInfo(VecSelHeroInfo &akUnlockHero)
References SeSelHeroInfo::dwActiveSkin, SeSelHeroInfo::dwActiveWeapon, SeSelHeroInfo::dwActiveWing, SeSelHeroInfo::dwHeroTypeID, m_data.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail.
bool HeroMgr::getHeroInfo(DWord dwHeroID, SeSelHeroInfo &hero)
References SeSelHeroInfo::dwActiveSkin, SeSelHeroInfo::dwActiveWeapon, SeSelHeroInfo::dwActiveWing, SeSelHeroInfo::dwHeroTypeID, m_data.
Referenced by BlockServer::ProcessRBL_SelectHeroReq.
void HeroMgr::setAvatar(DWord dwHeroID, DWord dwItemID)
References AVATAR_BEGIN, AVATAR_END, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, g_kCharHeroStrategy, CItemMgr::getItem, SePlayer::GetItemMgr, getOwner, isValidAvatar, m_data, s_avatars.
Referenced by BlockServer::ProcessRBL_SetAvatarNtf.
HeroMgr::HeroMgr(SePlayer &owner)
HeroMgr::~HeroMgr()
void HeroMgr::loadData(const SeDBCharHero &item)
void HeroMgr::fixData()
void HeroMgr::sendInitData()
void HeroMgr::unlockHero(int num, SeUnlockHeroBaseInfo *items)
void HeroMgr::notifyChanged(const std::list< SeDBCharHero * > &items)
void HeroMgr::createFreeHeroes()
void HeroMgr::getAllUnlockHeroInfo(VecSelHeroInfo &akUnlockHero)
bool HeroMgr::getHeroInfo(DWord dwHeroID, SeSelHeroInfo &hero)
void HeroMgr::setAvatar(DWord dwHeroID, DWord dwItemID)
bool HeroMgr::isValidAvatar(CItem *pItem, DWord dwHeroID, int avatarBegin, int avatarEnd, int &avatarType)
References AvatarTableMgr::Get, TownItemTableMgr::Get, AvatarTableMgr::GetAvatarTable, TownItemTableMgr::GetTownItemTable, TOWNITEM_CLASS_ZHUANGBAN, AvatarTable::uiAvatarType, TownItemTable::uiClass, AvatarTable::uiHeroID, CItem::uiItemID.
Referenced by ActiveAvatarMgr::fixData, fixData, ActiveAvatarMgr::setActiveAvatar, setAvatar.
static bool HeroMgr::isValidAvatar(CItem *pItem, DWord dwHeroID, int avatarBegin, int avatarEnd, int &avatarType)
SePlayer & HeroMgr::getOwner()
References m_owner.
Referenced by fixData, notifyChanged, processAddHeroBindItem, setAvatar, unlockHero.
void HeroMgr::processAddHeroBindItem(DWord dwHeroID)
References CItemMgr::AddItem, g_kWorldServer, SePlayer::GetItemMgr, getOwner, WorldServer::UserHeroBindItem.
Referenced by unlockHero.
SePlayer& HeroMgr::getOwner()
void HeroMgr::processAddHeroBindItem(DWord dwHeroID)
bool HeroMgr::isValidHero(const SeDBCharHero &item)
References EUHS_WEEK, FreeHeroesTableMgr::Get, FreeHeroesTableMgr::GetFreeHeroesTable.
Referenced by notifyChanged.
static bool HeroMgr::isValidHero(const SeDBCharHero &item)