TaskInfoTableMgr
std::map<unsigned int,TaskInfoTable*> TaskInfoTableMgr::m_kTaskInfoTableMap
Referenced by FillData, GetTaskInfoTable, GetTaskInfoTableMap, GetTaskInfoTableVec, ~TaskInfoTableMgr.
TaskInfoTableMgr * TaskInfoTableMgr::m_pkTaskInfoTableMgr
Referenced by Get, ReLoad.
TaskInfoTableMgr * TaskInfoTableMgr::Get()
References m_pkTaskInfoTableMgr, TaskInfoTableMgr.
Referenced by TaskMgr::GetDailyTaskNextTask, TaskMgr::GetTaskConditionNum, TableMgr::GetTaskInfo, TaskMgr::GetWinTaskNextTask, TableMgr::InitTaskList, TaskMgr::loadData, TableMgr::LoadTable, ReLoad.
TaskInfoTableMgr * TaskInfoTableMgr::ReLoad()
References Get, m_pkTaskInfoTableMgr.
Referenced by TableMgr::ReloadTable.
TaskInfoTableMgr::TaskInfoTableMgr()
References Load.
Referenced by Get.
TaskInfoTableMgr::~TaskInfoTableMgr()
References m_kTaskInfoTableMap.
const TaskInfoTable * TaskInfoTableMgr::GetTaskInfoTable(unsigned int iTypeID)
References m_kTaskInfoTableMap.
Referenced by TaskMgr::GetDailyTaskNextTask, TaskMgr::GetTaskConditionNum, TableMgr::GetTaskInfo, TaskMgr::GetWinTaskNextTask, TaskMgr::loadData.
const std::map< unsigned int, TaskInfoTable * > & TaskInfoTableMgr::GetTaskInfoTableMap()
References m_kTaskInfoTableMap.
Referenced by TableMgr::InitTaskList.
TableResArray TaskInfoTableMgr::GetTaskInfoTableVec()
References m_kTaskInfoTableMap, TableResArray::pushBack.
bool TaskInfoTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by TaskInfoTableMgr.
void TaskInfoTableMgr::FillData(TaskInfoTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, TaskInfoTable::fValue, TaskInfoTable::iAwardExp, TaskInfoTable::iAwardGold, TaskInfoTable::iAwardItem, TaskInfoTable::iCondValue1, TaskInfoTable::iCondValue2, TaskInfoTable::iLimit, TaskInfoTable::iMapList, TaskInfoTable::kDescID, TaskInfoTable::kName_China, TaskInfoTable::kNameID, TaskInfoTable::kTargetDesc, TaskInfoTable::kTaskDesc, m_kTaskInfoTableMap, TaskInfoTable::uiChange, TaskInfoTable::uiConditionParam, TaskInfoTable::uiConditon, TaskInfoTable::uiPreconditionTaskID, TaskInfoTable::uiReceiveCondition, TaskInfoTable::uiSpecialConditon, TaskInfoTable::uiTaskID, TaskInfoTable::uiTriggerType, TaskInfoTable::uiType.
Referenced by Load.