StrengthenTableMgr
std::map<unsigned int,StrengthenTable*> StrengthenTableMgr::m_kStrengthenTableMap
Referenced by FillData, GetStrengthenTable, GetStrengthenTableMap, GetStrengthenTableVec, ~StrengthenTableMgr.
std::map<int, unsigned int> StrengthenTableMgr::m_strentghenMap
Referenced by FillData, GetStrengthenTable.
StrengthenTableMgr * StrengthenTableMgr::m_pkStrengthenTableMgr
Referenced by Get, ReLoad.
StrengthenTableMgr * StrengthenTableMgr::Get()
References m_pkStrengthenTableMgr, StrengthenTableMgr.
Referenced by GenerateAddedAttr, GlobalTableMgr::GetStrengthenTable, TableMgr::LoadTable, ReLoad, CItemMgr::StrenthEquip.
StrengthenTableMgr * StrengthenTableMgr::ReLoad()
References Get, m_pkStrengthenTableMgr.
Referenced by TableMgr::ReloadTable.
StrengthenTableMgr::StrengthenTableMgr()
References Load.
Referenced by Get.
StrengthenTableMgr::~StrengthenTableMgr()
References m_kStrengthenTableMap.
const StrengthenTable * StrengthenTableMgr::GetStrengthenTable(unsigned int iTypeID)
References m_kStrengthenTableMap.
Referenced by GenerateAddedAttr, GlobalTableMgr::GetStrengthenTable, CItemMgr::StrenthEquip.
const std::map< unsigned int, StrengthenTable * > & StrengthenTableMgr::GetStrengthenTableMap()
References m_kStrengthenTableMap.
TableResArray StrengthenTableMgr::GetStrengthenTableVec()
References m_kStrengthenTableMap, TableResArray::pushBack.
const StrengthenTable * StrengthenTableMgr::GetStrengthenTable(int iStrengthenLevel, int iColorLevel, int iType)
References GetKey, m_kStrengthenTableMap, m_strentghenMap.
bool StrengthenTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by StrengthenTableMgr.
void StrengthenTableMgr::FillData(StrengthenTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, StrengthenTable::fStrResult1, StrengthenTable::fStrResult2, StrengthenTable::fStrResult3, StrengthenTable::fStrResult4, StrengthenTable::fStrResult5, StrengthenTable::fStrResult6, StrengthenTable::fStrResult7, StrengthenTable::fStrResult8, GetKey, StrengthenTable::iCostMoney, StrengthenTable::iLevel, StrengthenTable::iStrStoneNum1, StrengthenTable::iStrStoneNum2, StrengthenTable::iSuccessRate, StrengthenTable::kStrStoneName1, StrengthenTable::kStrStoneName2, m_kStrengthenTableMap, m_strentghenMap, StrengthenTable::uiApplyClass, StrengthenTable::uiColorLevel, StrengthenTable::uiStrengID, StrengthenTable::uiStrengthenID, StrengthenTable::uiStrProperty1, StrengthenTable::uiStrProperty2, StrengthenTable::uiStrProperty3, StrengthenTable::uiStrProperty4, StrengthenTable::uiStrProperty5, StrengthenTable::uiStrProperty6, StrengthenTable::uiStrProperty7, StrengthenTable::uiStrProperty8, StrengthenTable::uiStrStoneID1, StrengthenTable::uiStrStoneID2.
Referenced by Load.
int StrengthenTableMgr::GetKey(int StrengthenLevel, int ColorLevel, int EquipType)
Referenced by FillData, GetStrengthenTable.