SeRaceSvrMgr
MapAllRS SeRaceSvrMgr::m_kAllRS
Referenced by Finialize, GetAllRS, GetBestNormalRaceSvr, GetRaceSvr, GetRaceSvrByPlayer, GetRaceSvrNum, HasRaceSvr, OnRSDisconnect, OnRSRefreshConfig, OnRSRegister, OnRSUpdateLoadNum.
MIDPair SeRaceSvrMgr::m_kMPlayerRaceSvr
Referenced by GetRaceSvrByPlayer, InitPlayerRaceSvr.
SeRaceSvrMgr::SeRaceSvrMgr()
SeRaceSvrMgr::~SeRaceSvrMgr()
References Finialize.
bool SeRaceSvrMgr::Initialize(void)
References InitPlayerRaceSvr.
Referenced by MatchServer::Initialize.
void SeRaceSvrMgr::Update(void)
void SeRaceSvrMgr::Finialize(void)
References m_kAllRS, SAFE_DELETE.
Referenced by ~SeRaceSvrMgr.
bool SeRaceSvrMgr::OnRSRegister(SeRaceSvr kSvr)
References SeRaceSvr::dwAreaID, SeRaceSvr::dwServerID, g_kRaceMgr, SeRaceSvr::iRegisterCount, m_kAllRS, SeRaceMgr::OnProcessRSRegister.
Referenced by MatchServer::ProcessRM_Register.
bool SeRaceSvrMgr::OnRSDisconnect(HTownSign &rkTownSign)
References m_kAllRS, SAFE_DELETE.
Referenced by MatchServer::OnNetDisconnect.
void SeRaceSvrMgr::OnRSUpdateLoadNum(HTownSign &rkTownSign, int iSvrRaceNum, int iNormalRaceNum)
References SeRaceSvr::dwLastRecvTime, g_kMatchServer, MatchServer::GetServerTime, SeRaceSvr::iNormalRaceNum, SeRaceSvr::iSvrModeCanRunNum, m_kAllRS.
Referenced by MatchServer::ProcessRM_HeartPackage.
void SeRaceSvrMgr::OnRSRefreshConfig(HTownSign &rkTownSign, bool bSvrMode, bool bOpen)
References SeRaceSvr::bOpen, m_kAllRS.
int SeRaceSvrMgr::GetRaceSvrNum(void)
References m_kAllRS.
Referenced by MatchServer::ShowConsoleTitle.
bool SeRaceSvrMgr::HasRaceSvr(void)
References SeRaceSvr::bOpen, m_kAllRS.
SeRaceSvr * SeRaceSvrMgr::GetRaceSvr(HTownSign &rkTownSign)
References m_kAllRS.
Referenced by SeRaceMgr::GetRaceSvrSock, SeRaceMgr::OnBiVoiceCreateRoom, SeRaceMgr::OnProcessReconQuerySuccess, SeRaceMgr::OnProcessViewQuerySuccess, MatchServer::ProcessRM_Register, SeRaceMgr::SendMatchAddrMsg.
SeRaceSvr * SeRaceSvrMgr::GetBestNormalRaceSvr(DWord dwAreaID, DWord dwPlayerID)
References SeRaceSvr::bOpen, SeRaceSvr::dwAreaID, SeMatchConfig::dwMasterRS, g_kMatchServer, MatchServer::GetConfig, SeRaceSvr::GetNormalRaceNum, GetRaceSvrByPlayer, m_kAllRS.
Referenced by SeRaceMgr::GetRacingSvr.
MapAllRS & SeRaceSvrMgr::GetAllRS()
References m_kAllRS.
Referenced by MatchServer::UpdateRSTOMSTime.
SeRaceSvrMgr::SeRaceSvrMgr()
SeRaceSvrMgr::~SeRaceSvrMgr()
bool SeRaceSvrMgr::Initialize(void)
void SeRaceSvrMgr::Update(void)
void SeRaceSvrMgr::Finialize(void)
bool SeRaceSvrMgr::OnRSRegister(SeRaceSvr kSvr)
bool SeRaceSvrMgr::OnRSDisconnect(HTownSign &rkTownSign)
void SeRaceSvrMgr::OnRSUpdateLoadNum(HTownSign &rkTownSign, int iSvrRaceNum, int iNormalRaceNum)
void SeRaceSvrMgr::OnRSRefreshConfig(HTownSign &rkTownSign, bool bSvrMode, bool bOpen)
int SeRaceSvrMgr::GetRaceSvrNum(void)
bool SeRaceSvrMgr::HasRaceSvr(void)
SeRaceSvr* SeRaceSvrMgr::GetRaceSvr(HTownSign &rkTownSign)
SeRaceSvr* SeRaceSvrMgr::GetBestNormalRaceSvr(DWord dwAreaID, DWord dwPlayerID)
MapAllRS& SeRaceSvrMgr::GetAllRS()
void SeRaceSvrMgr::InitPlayerRaceSvr()
References GetAString, GetStr2ID, m_kMPlayerRaceSvr.
Referenced by Initialize.
SeRaceSvr * SeRaceSvrMgr::GetRaceSvrByPlayer(DWord dwPlayerID)
References HTownSign::dwAreaID, HTownSign::dwServerID, m_kAllRS, m_kMPlayerRaceSvr.
Referenced by GetBestNormalRaceSvr.
void SeRaceSvrMgr::InitPlayerRaceSvr()
SeRaceSvr* SeRaceSvrMgr::GetRaceSvrByPlayer(DWord dwPlayerID)