CPerformanceIntervalFileDump
const Config CPerformanceIntervalFileDump::m_Config
Referenced by CPerformanceIntervalFileDump, DumpIntervals, ResetNextWriteTime, Tick.
Float32 CPerformanceIntervalFileDump::m_fNextWriteTime
Referenced by BeginTrack, ResetNextWriteTime, Tick.
Float32 CPerformanceIntervalFileDump::m_fLastDumpDeltaTime
Referenced by DumpIntervals, Tick.
std::string CPerformanceIntervalFileDump::m_sStatsFolder
Referenced by CPerformanceIntervalFileDump.
Float64 CPerformanceIntervalFileDump::m_dMaxDumpTimeSec
Referenced by DumpIntervals, Tick.
Float64 CPerformanceIntervalFileDump::m_dLastDumpTimeSec
Referenced by Tick.
bool CPerformanceIntervalFileDump::m_bTracking
Referenced by BeginTrack, EndTrack, Tick.
UInt32 CPerformanceIntervalFileDump::m_tmBeginTrack
Referenced by BeginTrack, DumpIntervals, EndTrack.
CPerformanceTiming * CPerformanceIntervalFileDump::m_pOwner
Referenced by GetOwnerInst, SetOwner.
CPerformanceIntervalFileDump::CPerformanceIntervalFileDump(const Config &rConfig)
References m_Config, m_sStatsFolder, ResetNextWriteTime, CPerformanceIntervalFileDump::Config::sLogDir.
CPerformanceIntervalFileDump::~CPerformanceIntervalFileDump()
void CPerformanceIntervalFileDump::Tick(Float32 fDeltaTime)
References SeRaceConfig::bRealTickTime, DumpIntervals, makeCallback.f, SeRaceConfig::fWriteInterval, g_kRaceServer, CPerformanceTiming::GetLastDumpTotalTime, PerformanceTiming::CInterval::GetLastFrameNegIntervalTimeSec, CPerformanceTiming::GetLastRealTimeDeltaSec, PerformanceTiming::CPackCounter::getMaxTotalSize, CPerformanceTiming::getPacketCounter, RaceServer::GetRaceConfig, CPerformanceTiming::Instance, CPerformanceTiming::InstanceQuick, SeRaceConfig::iRacePrintTime, m_bTracking, m_Config, m_dLastDumpTimeSec, m_dMaxDumpTimeSec, M_DoFunctionMutiInterval_FN, m_fLastDumpDeltaTime, m_fNextWriteTime, CPerformanceIntervalFileDump::Config::uMaxPacketSize.
void CPerformanceIntervalFileDump::BeginTrack()
References CPerformanceTiming::Instance, m_bTracking, m_fNextWriteTime, m_tmBeginTrack, CPerformanceTiming::ResetAll.
void CPerformanceIntervalFileDump::EndTrack()
References DumpIntervals, m_bTracking, m_tmBeginTrack.
void CPerformanceIntervalFileDump::ForceDump()
References DumpIntervals.
virtual void CPerformanceIntervalFileDump::SetOwner(IPerformaceTiming *pOwner)
References m_pOwner.
CPerformanceIntervalFileDump::CPerformanceIntervalFileDump(const Config &rConfig)
virtual CPerformanceIntervalFileDump::~CPerformanceIntervalFileDump()
virtual void CPerformanceIntervalFileDump::Tick(Float32 fDeltaTime)
virtual void CPerformanceIntervalFileDump::BeginTrack()
virtual void CPerformanceIntervalFileDump::EndTrack()
virtual void CPerformanceIntervalFileDump::ForceDump()
virtual void CPerformanceIntervalFileDump::SetOwner(IPerformaceTiming *pOwner)
References m_pOwner.
CPerformanceIntervalFileDump::CPerformanceIntervalFileDump(const CPerformanceIntervalFileDump &)
CPerformanceIntervalFileDump& CPerformanceIntervalFileDump::operator=(const CPerformanceIntervalFileDump &)
CPerformanceTiming* CPerformanceIntervalFileDump::GetOwnerInst()
References m_pOwner.
void CPerformanceIntervalFileDump::ResetNextWriteTime()
References CPerformanceIntervalFileDump::Config::fFileWriteIntervalSec, m_Config, m_fNextWriteTime.
Referenced by CPerformanceIntervalFileDump.
void CPerformanceIntervalFileDump::DumpIntervals(bool bThresholdDump)
References CPerformanceTiming::EnumerateAllCounters, CPerformanceTiming::EnumerateIntervals, PerformanceTiming::g_kPerformanceSave, CPerformanceTiming::GetLastDumpTotalTime, CPerformanceTiming::GetLastFps, CPerformanceTiming::GetLastRealTimeDeltaSec, CPerformanceTiming::GetTotalAvgFPS, CPerformanceTiming::Instance, CPerformanceTiming::InstanceQuick, m_Config, m_dMaxDumpTimeSec, M_DoMutiInterval_FN, PerformanceTiming::SePerfocemanceTime::m_fCurDumpTime, PerformanceTiming::SePerfocemanceTime::m_fFrameTime, m_fLastDumpDeltaTime, PerformanceTiming::SePerfocemanceTime::m_fLastDumpTime, PerformanceTiming::SePerfocemanceTime::m_fLastFps, PerformanceTiming::SePerfocemanceTime::m_fMaxDumpTimes, PerformanceTiming::SePerfocemanceTime::m_fRealTickTime, PerformanceTiming::SePerfocemanceTime::m_fTotalAvgFps, m_tmBeginTrack, PerformanceTiming::SePerfocemanceTime::m_uBeginTraceTime, PerformanceTiming::SePerfocemanceTime::m_uSecondsFromStart, PerformanceTiming::SePerfocemanceTime::m_uThreadID, PerformanceTiming::SePerformanceSave::PushTask, CPerformanceIntervalFileDump::Config::sApplicationName.
Referenced by EndTrack, ForceDump, Tick.
void CPerformanceIntervalFileDump::DumpIntervalLine(Es::String &sText, bool bFoldered, bool bFolder, const Es::String &sName, Float64 dTimeMS, UInt32 uEntries, Float64 fPercentage, bool bOddLine, bool bClosed)
References PerformanceTiming::PaddedString.
void CPerformanceIntervalFileDump::DumpCounterLine(Es::String &sText, bool bFoldered, bool bFolder, const Es::String &sName, UInt32 uValue, UInt64 uTotal, bool bHistory, bool bOddLine)
References PerformanceTiming::PaddedString.
void CPerformanceIntervalFileDump::DumpHistoryIntervalLine(Es::String &sText, const Es::String &sName, Float64 dTimeMS, UInt32 uEntries, Float64 dMax, Float64 dMin, bool bOddLine)
References PerformanceTiming::PaddedString.
void CPerformanceIntervalFileDump::DumpPacketCounterLine(Es::String &sText, UInt32 packtID, UInt32 uSize, UInt32 uCount, UInt32 uTotal, UInt32 uRealTotal, bool bOddLine)
References PerformanceTiming::PaddedString.
CPerformanceIntervalFileDump::CPerformanceIntervalFileDump(const CPerformanceIntervalFileDump &)
CPerformanceIntervalFileDump& CPerformanceIntervalFileDump::operator=(const CPerformanceIntervalFileDump &)
CPerformanceTiming* CPerformanceIntervalFileDump::GetOwnerInst()
References m_pOwner.
void CPerformanceIntervalFileDump::ResetNextWriteTime()
void CPerformanceIntervalFileDump::DumpIntervals(bool bThresholdDump)
void CPerformanceIntervalFileDump::DumpIntervalLine(Es::String &sText, bool bFoldered, bool bFolder, const Es::String &sName, Float64 dTimeMS, UInt32 uEntries, Float64 fPercentage, bool bOddLine, bool bClosed)
void CPerformanceIntervalFileDump::DumpCounterLine(Es::String &sText, bool bFoldered, bool bFolder, const Es::String &sName, UInt32 uValue, UInt64 uTotal, bool bHistory, bool bOddLine)
void CPerformanceIntervalFileDump::DumpHistoryIntervalLine(Es::String &sText, const Es::String &sName, Float64 dTimeMS, UInt32 uEntries, Float64 dMax, Float64 dMin, bool bOddLine)
void CPerformanceIntervalFileDump::DumpPacketCounterLine(Es::String &sText, UInt32 packtID, UInt32 uSize, UInt32 uCount, UInt32 uTotal, UInt32 uRealTotal, bool bOddLine)