SearchChoiceTableMgr
std::map<unsigned int,SearchChoiceTable*> SearchChoiceTableMgr::m_kSearchChoiceTableMap
Referenced by FillData, GetSearchChoiceTable, GetSearchChoiceTableMap, GetSearchChoiceTableVec, ~SearchChoiceTableMgr.
SearchChoiceTableMgr * SearchChoiceTableMgr::m_pkSearchChoiceTableMgr
Referenced by Get, ReLoad.
SearchChoiceTableMgr * SearchChoiceTableMgr::Get()
References m_pkSearchChoiceTableMgr, SearchChoiceTableMgr.
Referenced by ReLoad.
SearchChoiceTableMgr * SearchChoiceTableMgr::ReLoad()
References Get, m_pkSearchChoiceTableMgr.
Referenced by TableMgr::ReloadTable.
SearchChoiceTableMgr::SearchChoiceTableMgr()
References Load.
Referenced by Get.
SearchChoiceTableMgr::~SearchChoiceTableMgr()
References m_kSearchChoiceTableMap.
const SearchChoiceTable * SearchChoiceTableMgr::GetSearchChoiceTable(unsigned int iTypeID)
References m_kSearchChoiceTableMap.
const std::map< unsigned int, SearchChoiceTable * > & SearchChoiceTableMgr::GetSearchChoiceTableMap()
References m_kSearchChoiceTableMap.
TableResArray SearchChoiceTableMgr::GetSearchChoiceTableVec()
References m_kSearchChoiceTableMap, TableResArray::pushBack.
bool SearchChoiceTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by SearchChoiceTableMgr.
void SearchChoiceTableMgr::FillData(SearchChoiceTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, SearchChoiceTable::bIgnoreBKB, SearchChoiceTable::fForceHpPer, SearchChoiceTable::fHpPer, SearchChoiceTable::iAnticipation, SearchChoiceTable::iBestDis, SearchChoiceTable::iBestHP, SearchChoiceTable::iBestRange, SearchChoiceTable::iDisRatio, SearchChoiceTable::iHPRatio, SearchChoiceTable::iIsLongRelease, SearchChoiceTable::iMinAngel, SearchChoiceTable::iPrejudgeswitch, SearchChoiceTable::iQTEIntervalTime, SearchChoiceTable::iSearchAngel, SearchChoiceTable::itongshiyouxianji, SearchChoiceTable::iyoushibati, SearchChoiceTable::iyoushilinken, SearchChoiceTable::kDesc, m_kSearchChoiceTableMap, SearchChoiceTable::uiTypeID.
Referenced by Load.