LevelTableMgr
std::map<unsigned int,LevelTable*> LevelTableMgr::m_kLevelTableMap
Referenced by FillData, GetLevelTable, GetLevelTableMap, GetLevelTableVec, ~LevelTableMgr.
LevelTableMgr * LevelTableMgr::m_pkLevelTableMgr
Referenced by Get, ReLoad.
LevelTableMgr * LevelTableMgr::Get()
References LevelTableMgr, m_pkLevelTableMgr.
Referenced by GlobalTableMgr::GetLevelTable, SeFormula::Init, TableMgr::LoadTable, ReLoad.
LevelTableMgr * LevelTableMgr::ReLoad()
References Get, m_pkLevelTableMgr.
Referenced by TableMgr::ReloadTable.
LevelTableMgr::LevelTableMgr()
References Load.
Referenced by Get.
LevelTableMgr::~LevelTableMgr()
References m_kLevelTableMap.
const LevelTable * LevelTableMgr::GetLevelTable(unsigned int iTypeID)
References m_kLevelTableMap.
Referenced by GlobalTableMgr::GetLevelTable, SeFormula::Init.
const std::map< unsigned int, LevelTable * > & LevelTableMgr::GetLevelTableMap()
References m_kLevelTableMap.
TableResArray LevelTableMgr::GetLevelTableVec()
References m_kLevelTableMap, TableResArray::pushBack.
bool LevelTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by LevelTableMgr.
void LevelTableMgr::FillData(LevelTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, m_kLevelTableMap, LevelTable::uiDeadExp, LevelTable::uiKillGold, LevelTable::uiLevel, LevelTable::uiRebornTime, LevelTable::uiTotalExp.
Referenced by Load.