MapInfoTableMgr
std::map<unsigned int,MapInfoTable*> MapInfoTableMgr::m_kMapInfoTableMap
Referenced by FillData, GetMapInfoTable, GetMapInfoTableMap, GetMapInfoTableVec, UpdateLanguadgeContent, ~MapInfoTableMgr.
MapInfoTableMgr * MapInfoTableMgr::m_pkMapInfoTableMgr
Referenced by Get, ReLoad.
MapInfoTableMgr * MapInfoTableMgr::Get()
References m_pkMapInfoTableMgr, MapInfoTableMgr.
Referenced by WorldServer::CheckMapMatchType, WorldServer::CheckMapType, MatchPrepareMgr::collectData, SeOpenRoomMgr::ConvOpenRoomInfo, SeRaceMgr::CreateRobotRace, SeRaceRoomMgr::CreateRoom, GlobalTableMgr::GetMapInfoTable, GlobalTableMgr::GetMapInfoTableMap, TableMgr::GetMaxCampPlayerNumByMapID, SeMatchMgr::getPlayerType, TableMgr::LoadTable, SeMatchMgr::match, SeOpenRoomMgr::OnCreateRoom, SeMatchMgr::OnMatchReq, SeRaceMgr::OnRaceEndArenaDetail, SeRaceMgr::OnRaceEndGradeDetail, SeRaceMgr::OnRaceModeEnd, SeOpenRoomMgr::OnRoomInvite, SeOpenRoomMgr::OnRoomInviteRspOk, SeOpenRoomMgr::OnRoomJoin, SeOpenRoomMgr::OnRoomReady, MatchServer::OnSendRSValidatePlayerInfo, SeMatchMgr::openRoom, MatchServer::ProcessTM_PlayerMatchReq, WorldServer::ProcessTW_RaceEndRace, BlockServer::ProcessWBL_RaceEndGuanka, BlockServer::ProcessWBL_RaceEndRace, ReLoad, TableMgr::UpdateLanguageContent, MatchServer::UpdateRaceBetOddsEnd, RaceServer::UpdateWaitRobot.
MapInfoTableMgr * MapInfoTableMgr::ReLoad()
References Get, m_pkMapInfoTableMgr.
Referenced by TableMgr::ReloadTable.
MapInfoTableMgr::MapInfoTableMgr()
References Load.
Referenced by Get.
MapInfoTableMgr::~MapInfoTableMgr()
References m_kMapInfoTableMap.
const MapInfoTable * MapInfoTableMgr::GetMapInfoTable(unsigned int iTypeID)
References m_kMapInfoTableMap.
Referenced by WorldServer::CheckMapMatchType, WorldServer::CheckMapType, MatchPrepareMgr::collectData, SeOpenRoomMgr::ConvOpenRoomInfo, SeRaceMgr::CreateRobotRace, SeRaceRoomMgr::CreateRoom, GlobalTableMgr::GetMapInfoTable, TableMgr::GetMaxCampPlayerNumByMapID, SeMatchMgr::getPlayerType, SeMatchMgr::match, SeOpenRoomMgr::OnCreateRoom, SeMatchMgr::OnMatchReq, SeRaceMgr::OnRaceEndArenaDetail, SeRaceMgr::OnRaceEndGradeDetail, SeRaceMgr::OnRaceModeEnd, SeOpenRoomMgr::OnRoomInvite, SeOpenRoomMgr::OnRoomInviteRspOk, SeOpenRoomMgr::OnRoomJoin, SeOpenRoomMgr::OnRoomReady, MatchServer::OnSendRSValidatePlayerInfo, SeMatchMgr::openRoom, MatchServer::ProcessTM_PlayerMatchReq, WorldServer::ProcessTW_RaceEndRace, BlockServer::ProcessWBL_RaceEndGuanka, BlockServer::ProcessWBL_RaceEndRace, MatchServer::UpdateRaceBetOddsEnd, RaceServer::UpdateWaitRobot.
const std::map< unsigned int, MapInfoTable * > & MapInfoTableMgr::GetMapInfoTableMap()
References m_kMapInfoTableMap.
Referenced by GlobalTableMgr::GetMapInfoTableMap.
TableResArray MapInfoTableMgr::GetMapInfoTableVec()
References m_kMapInfoTableMap, TableResArray::pushBack.
void MapInfoTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, MapInfoTable::kDesc, MapInfoTable::kDescK, MapInfoTable::kName, MapInfoTable::kNameK, MapInfoTable::kVictoryConditions, MapInfoTable::kVictoryConditionsK, m_kMapInfoTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool MapInfoTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by MapInfoTableMgr.
void MapInfoTableMgr::FillData(MapInfoTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, MapInfoTable::fBaseScore, MapInfoTable::fMapRatio, MapInfoTable::fMonsterRecoveryPer, MapInfoTable::fOneHitKillHPPer, MapInfoTable::iAwardExpPS, MapInfoTable::iAwardGoldPS, MapInfoTable::iBanHeroID, MapInfoTable::iBaseSpeedUpRange, MapInfoTable::iCameraLimitTop, MapInfoTable::iCameraZ, MapInfoTable::iCampNum, MapInfoTable::iCampPos, MapInfoTable::iEnemyTPEff, MapInfoTable::iEvaluateConfig, MapInfoTable::iFlipMap, MapInfoTable::iHeroLevelInit, MapInfoTable::iManualValue, MapInfoTable::iMapCameraType, MapInfoTable::iMapSkill, MapInfoTable::iMapVector, MapInfoTable::iMaxPlayer, MapInfoTable::iMinHeroLevel, MapInfoTable::iMinMapBattleLevel, MapInfoTable::iMissionID, MapInfoTable::iOneHitKillHP, MapInfoTable::iOpen, MapInfoTable::iovermissile, MapInfoTable::iOverMoney, MapInfoTable::iPesurrectionProps, MapInfoTable::iPveReliveCDTime, MapInfoTable::iReLiveInPlace, MapInfoTable::iReLiveTimeForFree, MapInfoTable::iSelfTPEff, MapInfoTable::iStartGold, MapInfoTable::iSurrenderCDTime, MapInfoTable::iSurrenderTime, MapInfoTable::iTimeLimit, MapInfoTable::iWaitTime, MapInfoTable::iWish, MapInfoTable::kAudio, MapInfoTable::kConfigName, MapInfoTable::kDescK, MapInfoTable::kExplain_Name, MapInfoTable::kMapHeightPath, MapInfoTable::kMapIcon, MapInfoTable::kMapInfoPath, MapInfoTable::kMapResName, MapInfoTable::kNameK, MapInfoTable::kPath, MapInfoTable::kVictoryConditionsK, MapInfoTable::kWin, m_kMapInfoTableMap, MapInfoTable::ShenFuFlushTime, MapInfoTable::ShenFuItems, MapInfoTable::ShenFuPos, MapInfoTable::strMegaCreepsSoundID, MapInfoTable::uiBossName, MapInfoTable::uiDefaultKillFlagTypeID, MapInfoTable::uiDifficult, MapInfoTable::uiEquipmentType, MapInfoTable::uiEvaluateType, MapInfoTable::uiFail, MapInfoTable::uiItemID, MapInfoTable::uiMapTypeID, MapInfoTable::uiMatchType, MapInfoTable::uiOpen1, MapInfoTable::uiOpen2, MapInfoTable::uiOpen3, MapInfoTable::uiOpenType1, MapInfoTable::uiOpenType2, MapInfoTable::uiOpenType3, MapInfoTable::uiProperty, MapInfoTable::uiType, MapInfoTable::uiViewUnitTypeID.
Referenced by Load.