PlayerDataStrategy
void * PlayerDataStrategy::m_memData
Referenced by PlayerDataStrategy, CharInfoStrategy::rebuildMem, rebuildMem, setRebuildMemData.
Es::NormalLock PlayerDataStrategy::m_kGenIDLock
Referenced by getGenID.
DWord PlayerDataStrategy::m_genID
Referenced by getGenID, setGenID.
PlayerDataStrategy::PlayerDataStrategy()
References PlayerDataMgr::getInitList, m_memData.
virtual SeDBTableIndex PlayerDataStrategy::getTableIndex()=0
Referenced by dataDelete, dataInsert, dataUpdate, getInitGenIDSql, initGenID, loadData, PlayerDataMgr::onInitGenIDRet, onLoadData, saveToDB.
virtual DWord PlayerDataStrategy::getCacheInitID()=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::getCacheInitID, PlayerDataMgr::getCacheInitID.
virtual void PlayerDataStrategy::rebuildMem()=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::rebuildMem.
virtual int PlayerDataStrategy::saveToDB(SeDBPlayer &player)=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::saveToDB.
virtual void PlayerDataStrategy::dataInsert(SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, PlayerDataMgr::dataInsert.
virtual void PlayerDataStrategy::dataUpdate(SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, PlayerDataMgr::dataUpdate.
virtual void PlayerDataStrategy::dataDelete(SeDBPlayer &player, uint64_t dwlID)=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete, PlayerDataMgr::dataDelete.
virtual void PlayerDataStrategy::onLoadData(SeDBPlayer &player, TeDBResSet &rkResSet)=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::onLoadData, PlayerDataMgr::onLoadData.
virtual void PlayerDataStrategy::getRecordCount(SeDBPlayer &player, int &count)=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::getRecordCount, PlayerDataMgr::getRecordCount.
virtual void PlayerDataStrategy::getFieldData(SeDBPlayer &player, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1, void *&ret)=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::getFieldData, PlayerDataMgr::getFieldData.
virtual int PlayerDataStrategy::safeDeleteDBPlayer(SeDBPlayer &player, DWord dwMagic)=0
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::safeDeleteDBPlayer.
bool PlayerDataStrategy::getInitGenIDSql(char *sql, int size)
References g_kDBServer, getTableIndex, DBServer::GetTableName, SPrintf.
Referenced by PlayerDataMgr::getInitGenIDSql.
void PlayerDataStrategy::setRebuildMemData(void *data)
References m_memData.
Referenced by PlayerDataMgr::setRebuildMemData.
void PlayerDataStrategy::loadData(SeDBPlayer &player)
References SeDBPlayer::dwPlayerID, g_kDBServer, getTableIndex, DBServer::SendDB_CharData, SeDBPlayer::setLoadFlag.
Referenced by onLoadData.
PlayerDataStrategy::PlayerDataStrategy()
virtual SeDBTableIndex PlayerDataStrategy::getTableIndex()=0
virtual DWord PlayerDataStrategy::getCacheInitID()=0
virtual void PlayerDataStrategy::rebuildMem()=0
virtual int PlayerDataStrategy::saveToDB(SeDBPlayer &player)=0
virtual void PlayerDataStrategy::dataInsert(SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)=0
virtual void PlayerDataStrategy::dataUpdate(SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)=0
virtual void PlayerDataStrategy::dataDelete(SeDBPlayer &player, uint64_t dwlID)=0
virtual void PlayerDataStrategy::onLoadData(SeDBPlayer &player, TeDBResSet &rkResSet)=0
virtual void PlayerDataStrategy::getRecordCount(SeDBPlayer &player, int &count)=0
virtual void PlayerDataStrategy::getFieldData(SeDBPlayer &player, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1, void *&ret)=0
virtual int PlayerDataStrategy::safeDeleteDBPlayer(SeDBPlayer &player, DWord dwMagic)=0
virtual bool PlayerDataStrategy::getInitGenIDSql(char *sql, int size)
void PlayerDataStrategy::setRebuildMemData(void *data)
void PlayerDataStrategy::loadData(SeDBPlayer &player)
PlayerDataStrategy::PlayerDataStrategy()
virtual SeDBTableIndex PlayerDataStrategy::getTableIndex()=0
bool PlayerDataStrategy::initGenID()
References g_kWorldServer, getTableIndex, WorldServer::SendWB_InitGenID, SIGT_NULL.
void PlayerDataStrategy::loadData(SePlayer &player)
References g_kWorldServer, SePlayer::GetID, WorldServer::GetTableFieldCount, getTableIndex, SBBR_NONE, WorldServer::SendWB_SelectData, SePlayer::setLoadingFlag.
virtual void PlayerDataStrategy::onLoadData(SePlayer &player, SeBBL_SelectDataRet *pkData)=0
virtual void PlayerDataStrategy::fixData(SePlayer &player)=0
void PlayerDataStrategy::setGenID(DWord id)
References m_genID.
Referenced by PlayerDataMgr::onInitGenIDRet.
void PlayerDataStrategy::dataDelete(SePlayer &player, DWord dwID)
References g_kWorldServer, SePlayer::GetID, getTableIndex, WorldServer::SendWB_DataDelete.
void PlayerDataStrategy::dataUpdate(SePlayer &player, DWord dwID, const std::list< SeDBPair > &values)
References g_kWorldServer, SeDBStream::GetCurPos, SeDBStream::GetData, SePlayer::GetID, getTableIndex, SeDBStream::InitData, SBBR_NONE, WorldServer::SendWB_DataUpdate, SFF_NUM, SFF_NUM64, SeDBStream::WriteDword, SeDBStream::WriteVariant.
void PlayerDataStrategy::dataInsert(SePlayer &player, T &item)
References g_kWorldServer, SeDBStream::GetCurPos, SeDBStream::GetData, SePlayer::GetID, WorldServer::GetTableFieldCount, getTableIndex, SeDBStream::InitData, SBBR_NONE, WorldServer::SendWB_DataInsert, SeDBStream::WriteDword.
void PlayerDataStrategy::dataUpdate(SePlayer &player, T &item)
References g_kWorldServer, SeDBStream::GetCurPos, SeDBStream::GetData, SePlayer::GetID, WorldServer::GetTableFieldCount, getTableIndex, SeDBStream::InitData, SBBR_NONE, WorldServer::SendWB_DataUpdate, SFF_NUM, SFF_NUM64, SeDBStream::WriteDword.
DWord PlayerDataStrategy::getGenID()
References m_genID, m_kGenIDLock.
Referenced by CItemMgr::AddNewMultiItem, AchieveScheduleMgr::ComposeInfo, AchieveFinishMgr::ComposeInfo, RaceHeroMgr::createHero, RaceMapMgr::createMap, EquipSchemaMgr::putOnEquip, HeroMgr::unlockHero.
PlayerDataStrategy::PlayerDataStrategy()
virtual SeDBTableIndex PlayerDataStrategy::getTableIndex()=0
virtual bool PlayerDataStrategy::initGenID()
virtual void PlayerDataStrategy::loadData(SePlayer &player)
virtual void PlayerDataStrategy::onLoadData(SePlayer &player, SeBBL_SelectDataRet *pkData)=0
virtual void PlayerDataStrategy::fixData(SePlayer &player)=0
void PlayerDataStrategy::setGenID(DWord id)
void PlayerDataStrategy::dataDelete(SePlayer &player, DWord dwID)
void PlayerDataStrategy::dataUpdate(SePlayer &player, DWord dwID, const std::list< SeDBPair > &values)
void PlayerDataStrategy::dataInsert(SePlayer &player, T &item)
void PlayerDataStrategy::dataUpdate(SePlayer &player, T &item)
DWord PlayerDataStrategy::getGenID()
DWord PlayerDataStrategy::getCacheInitID(std::vector< T * > SeDBPlayer::*data)
References g_kDBPlayerMgr, GetCacheInitIDHandler< T >::getInitID, SeDBPlayerMgr::handleEachPlayer.
void PlayerDataStrategy::rebuildMem(std::vector< T * > SeDBPlayer::*data)
References SeDBPlayer::bIsInSaving, g_kDBPlayerMgr, SeDBPlayerMgr::GetDBPlayer, SeDBPlayerMgr::incResCount, m_memData, SCT_NULL.
int PlayerDataStrategy::saveToDB(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player)
References SeDBPlayer::dwPlayerID, g_kDBServer, DBServer::GetDBConnectNums, DBServer::GetDBIndex, getTableIndex, SCT_NULL.
void PlayerDataStrategy::dataInsert(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
References SeDBPlayer::dwPlayerID, SCT_INSERT.
void PlayerDataStrategy::dataUpdate(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
References SCT_UPDATE.
void PlayerDataStrategy::dataDelete(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, uint64_t dwlID)
References SCT_DELETE.
void PlayerDataStrategy::onLoadData(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, TeDBResSet &rkResSet)
References SeDBPlayer::dwPlayerID, g_kDBPlayerMgr, getTableIndex, SeDBPlayerMgr::SeLoadingFlag.
void PlayerDataStrategy::getRecordCount(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, int &count)
void PlayerDataStrategy::getFieldData(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1, void *&ret)
References SFF_DATETIME, SFF_NUM, SFF_NUM64, SFF_STRING.
int PlayerDataStrategy::safeDeleteDBPlayer(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, DWord dwMagic)
DWord PlayerDataStrategy::getCacheInitID(std::vector< T * > SeDBPlayer::*data)
void PlayerDataStrategy::rebuildMem(std::vector< T * > SeDBPlayer::*data)
int PlayerDataStrategy::saveToDB(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player)
void PlayerDataStrategy::dataInsert(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
void PlayerDataStrategy::dataUpdate(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
void PlayerDataStrategy::dataDelete(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, uint64_t dwlID)
void PlayerDataStrategy::onLoadData(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, TeDBResSet &rkResSet)
void PlayerDataStrategy::getRecordCount(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, int &count)
void PlayerDataStrategy::getFieldData(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1, void *&ret)
int PlayerDataStrategy::safeDeleteDBPlayer(std::vector< T * > SeDBPlayer::*data, SeDBPlayer &player, DWord dwMagic)
void PlayerDataStrategy::onLoadData(SePlayer &player, SeBBL_SelectDataRet *pkData)
References SeBBL_SelectDataRet::acData, SeDBStream::Attach, SeBBL_SelectDataRet::bySendOver, SePlayer::clearLoadingFlag, g_kWorldServer, SePlayer::getDataMgr, SePlayer::GetID, SePlayer::GetLoadFlagCount, WorldServer::GetTableFieldCount, getTableIndex, SeDBStream::IsEnd, SeBBL_SelectDataRet::iSendNum, SeBBL_SelectDataRet::iSize, loadData, SePlayer::LoadingComplete, SeDBStream::ReadDword, SeLogError, SePlayer::SetLoadFlagCount.
void PlayerDataStrategy::onLoadData(SePlayer &player, SeBBL_SelectDataRet *pkData)
void PlayerDataStrategy::fixData(SePlayer &player)
void PlayerDataStrategy::fixData(SePlayer &player)