UnitTableMgr
std::map<unsigned int,UnitTable*> UnitTableMgr::m_kUnitTableMap
Referenced by FillData, GetUnitTable, GetUnitTableMap, GetUnitTableVec, UpdateLanguadgeContent, ~UnitTableMgr.
UnitTableMgr * UnitTableMgr::m_pkUnitTableMgr
Referenced by Get, ReLoad.
UnitTableMgr * UnitTableMgr::Get()
References m_pkUnitTableMgr, UnitTableMgr.
Referenced by TableMgr::GetRaceHelpSkillTypes, GlobalTableMgr::GetUnitTable, TableMgr::InitCreateSightUnit, TableMgr::LoadTable, ReLoad, TableMgr::UpdateLanguageContent, WorldServer::UserHeroBindItem.
UnitTableMgr * UnitTableMgr::ReLoad()
References Get, m_pkUnitTableMgr.
Referenced by TableMgr::ReloadTable.
UnitTableMgr::UnitTableMgr()
References Load.
Referenced by Get.
UnitTableMgr::~UnitTableMgr()
References m_kUnitTableMap.
const UnitTable * UnitTableMgr::GetUnitTable(unsigned int iTypeID)
References m_kUnitTableMap.
Referenced by TableMgr::GetRaceHelpSkillTypes, GlobalTableMgr::GetUnitTable, WorldServer::UserHeroBindItem.
const std::map< unsigned int, UnitTable * > & UnitTableMgr::GetUnitTableMap()
References m_kUnitTableMap.
Referenced by TableMgr::InitCreateSightUnit.
TableResArray UnitTableMgr::GetUnitTableVec()
References m_kUnitTableMap, TableResArray::pushBack.
void UnitTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, UnitTable::kName_China, UnitTable::kName_ChinaK, m_kUnitTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool UnitTableMgr::Load(std::string path, int iIdx)
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by UnitTableMgr.
void UnitTableMgr::FillData(UnitTable *row, TiXmlElement *element, int iIdx)
References UnitTable::aiAutoAddSkillPt, TiXmlElement::Attribute, UnitTable::fAIAlertRange, UnitTable::fArmorUp, UnitTable::fAttachEffScale, UnitTable::fAttackBackPt, UnitTable::fAttackDamageHold, UnitTable::fAttackDamagePt, UnitTable::fAttackRange, UnitTable::fAttackSpeedUp, UnitTable::fAttackUp, UnitTable::fBaseAttackSpeed, UnitTable::fCollision, UnitTable::fHpRegenUp, UnitTable::fHpUp, UnitTable::fMagicAntiUp, UnitTable::fMissileArc, UnitTable::fMissileSpeed, UnitTable::fModelScale, UnitTable::fMpRegenUp, UnitTable::fMpUp, UnitTable::fOrgAntiMagic, UnitTable::fOrgArmor, UnitTable::fOrgDamage, UnitTable::fOrgDayRegenHP, UnitTable::fOrgMaxHP, UnitTable::fOrgMaxMP, UnitTable::fOrgMoveSpeed, UnitTable::fOrgRegenMP, UnitTable::fSelectScale, UnitTable::fSpellBackPt, UnitTable::fSpellDamagePt, UnitTable::fTimeGrowthArmor, UnitTable::fTimeGrowthAttack, UnitTable::fTimeGrowthExp, UnitTable::fTimeGrowthHp, UnitTable::fTimeGrowthMagicArmor, UnitTable::fTurnSpeed, UnitTable::iBaseID, UnitTable::iBossSkillVec, UnitTable::iDeathExp, UnitTable::iDeathMoney, UnitTable::iDeathMoneyMax, UnitTable::iEnemyMissileModel, UnitTable::iEnemyModelFile, UnitTable::iFlyHeight, UnitTable::iHPUI, UnitTable::iInitSkill, UnitTable::iKillRecoverHP, UnitTable::iKillRecoverMP, UnitTable::iKillRecoverRatio, UnitTable::iLoadDeathModel, UnitTable::iLoadEnemyDeathModel, UnitTable::iLockCircle, UnitTable::iLockEnemyType, UnitTable::iMissileModel, UnitTable::iModelFile, UnitTable::iOrgAttackCD, UnitTable::iShareMoney, UnitTable::iShareMoneyGlobal, UnitTable::iSightLifeTime, UnitTable::iSightTime, UnitTable::iSkillList, UnitTable::iSuperSkillList, UnitTable::iTimeGrowthBeginTime, UnitTable::iTimeGrowthGold, UnitTable::iTimeGrowthInterval, UnitTable::iTimeGrowthMaxLevel, UnitTable::iUnitSight, UnitTable::kAttackVoice, UnitTable::kDeafultEquip, UnitTable::kDeathSound, UnitTable::kEmenyResName, UnitTable::kIcon, UnitTable::kName_ChinaK, UnitTable::kResName, UnitTable::kResPath, UnitTable::kRideResName, UnitTable::kSelectSound, UnitTable::kStandSound, UnitTable::kWalkSound, m_kUnitTableMap, UnitTable::uiAttackType, UnitTable::uiBeDamagedEffect, UnitTable::uiBKBMatID, UnitTable::uibkbysID, UnitTable::uiClassType, UnitTable::uiDeathMatID, UnitTable::uiDefaultLocation, UnitTable::uiDefenseType, UnitTable::uiEnemyBeDamagedEffect, UnitTable::uiIceMatID, UnitTable::uiInvMatID, UnitTable::uiProperty, UnitTable::uiSpecialMatID, UnitTable::uiUnitTypeID.
Referenced by Load.