RaceMapMgr
SePlayer & RaceMapMgr::m_owner
Referenced by getOwner.
MDBCharRaceMap RaceMapMgr::m_race_map
Referenced by createMap, get_race_data, get_race_map, getMap, loadData, ~RaceMapMgr.
RaceMapMgr::RaceMapMgr(SePlayer &owner)
RaceMapMgr::~RaceMapMgr()
References m_race_map.
void RaceMapMgr::loadData(const SeDBCharRaceArena &info)
References checkMap, m_race_map.
void RaceMapMgr::saveData(SeDBCharRaceArena &info)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, g_kCharRaceMapStrategy, getOwner.
Referenced by makeMap.
void RaceMapMgr::updateData(SeDBCharRaceArena &info)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, g_kCharRaceMapStrategy, getOwner.
Referenced by makeMap.
SeDBCharRaceArena * RaceMapMgr::getMap(const DWord dw_map_id)
References m_race_map.
Referenced by checkMap, updateMap.
bool RaceMapMgr::checkMap(const DWord dw_map_id)
References getMap.
Referenced by loadData, makeMap.
void RaceMapMgr::makeMap(SeDBCharRaceArena &info)
References checkMap, createMap, saveData, updateData, updateMap.
Referenced by BlockServer::ProcessRBL_UserRaceMapNtf.
void RaceMapMgr::createMap(SeDBCharRaceArena &info)
References g_kCharRaceMapStrategy, PlayerDataStrategy::getGenID, m_race_map.
Referenced by makeMap.
void RaceMapMgr::updateMap(SeDBCharRaceArena &info)
References getMap.
Referenced by makeMap.
MDBCharRaceMap & RaceMapMgr::get_race_map()
References m_race_map.
void RaceMapMgr::get_race_data(SeRaceEndArenaResult &info, const DWord map_type)
References WorldServer::CheckMapType, g_kWorldServer, SeRaceEndArenaResult::iAssists, SeRaceEndArenaResult::iBest, SeRaceEndArenaResult::iBlood_1, SeRaceEndArenaResult::iDies, SeRaceEndArenaResult::iEnemyEyes, SeRaceEndArenaResult::iKills, SeRaceEndArenaResult::iKills_3, SeRaceEndArenaResult::iKills_4, SeRaceEndArenaResult::iKills_5, SeRaceEndArenaResult::iMvp, SeRaceEndArenaResult::iPlaceEyes, SeRaceEndArenaResult::iRaceFlag, SeRaceEndArenaResult::iRaceNum, SeRaceEndArenaResult::iSuper, SeRaceEndArenaResult::iTitle, SeRaceEndArenaResult::iTotalBeDamage, SeRaceEndArenaResult::iTotalDamage, SeRaceEndArenaResult::iTotalGold, m_race_map.
Referenced by BlockServer::ProcessTBL_LadderDetailInfoReq, BlockServer::ProcessTBL_UserRaceMapDetailReq.
void RaceMapMgr::get_race_data(SeLadderDetailInfo &info)
References WorldServer::CheckMapMatchType, SeLadderDetailInfo::dwMvpNUm, SeLadderDetailInfo::dwRaceNum, SeLadderDetailInfo::dwSuperNUm, SeLadderDetailInfo::dwWinNUm, EMT_LADDER, g_kWorldServer, m_race_map.
RaceMapMgr::RaceMapMgr(SePlayer &owner)
RaceMapMgr::~RaceMapMgr()
void RaceMapMgr::loadData(const SeDBCharRaceArena &info)
void RaceMapMgr::saveData(SeDBCharRaceArena &info)
void RaceMapMgr::updateData(SeDBCharRaceArena &info)
SeDBCharRaceArena* RaceMapMgr::getMap(const DWord dw_map_id)
bool RaceMapMgr::checkMap(const DWord dw_map_id)
void RaceMapMgr::makeMap(SeDBCharRaceArena &info)
void RaceMapMgr::createMap(SeDBCharRaceArena &info)
void RaceMapMgr::updateMap(SeDBCharRaceArena &info)
MDBCharRaceMap& RaceMapMgr::get_race_map()
void RaceMapMgr::get_race_data(SeRaceEndArenaResult &info, const DWord map_type)
void RaceMapMgr::get_race_data(SeLadderDetailInfo &info)
SePlayer & RaceMapMgr::getOwner()
References m_owner.
Referenced by saveData, updateData.
SePlayer& RaceMapMgr::getOwner()