HttpServer
char HttpServer::m_acSend[SSD_SEND_SIZE][SSD_SEND_SIZE]
Referenced by HttpServer.
char HttpServer::m_acPraseBuf[SSD_PRASER_SIZE][SSD_PRASER_SIZE]
Referenced by HttpServer.
SeHttpConfig HttpServer::m_kConfig
Referenced by GetServerID, Initialize, LoadConfig, LoadDynamicConfig, ProcessWH_RegisterRet, ShowConsoleTitle.
DWord HttpServer::m_dwTickCount
Referenced by HttpServer, Initialize, Update.
DWord HttpServer::m_dwCurTime
Referenced by GetServerTime, HttpServer, Update.
TeNetMgr HttpServer::m_kNetMgr
Referenced by Finialize, Initialize, InitializeNet, OnNetRecv, SendHWData, Update.
SeVirtConn* HttpServer::m_pkWSConn
Referenced by HttpServer, LoadConfig, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessWH, ProcessWH_RegisterRet, SendHWData.
Es::NormalLock HttpServer::m_kRequestLock
Referenced by AddRequest, GetDeleteRequest.
MapRequest HttpServer::m_kMapRequest
Referenced by AddRequest, GetDeleteRequest.
Es::NormalLock HttpServer::m_kResponseLock
Referenced by AddResponse, GetDeleteResponse.
MapResponse HttpServer::m_kMapResponse
Referenced by AddResponse, GetDeleteResponse.
HttpServer::HttpServer(void)
References m_acPraseBuf, m_acSend, m_dwCurTime, m_dwTickCount, m_pkWSConn.
HttpServer::~HttpServer(void)
References Finialize.
bool HttpServer::Initialize()
References SeNetAddr::acIP, g_kVirtConnMgr, HttpCloseCallback, HttpRequestCallback, HttpResponseCallback, SeVirtConnMgr::Initialize, InitializeNet, SeNetAddr::iPort, SeHttpConfig::kHttpServer, LoadConfig, m_dwTickCount, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo, sendHeartPack, sendRegPack.
void HttpServer::Update(void)
References g_kVirtConnMgr, m_dwCurTime, m_dwTickCount, m_kNetMgr, SeVirtConnMgr::Update.
void HttpServer::Finialize(void)
References m_kNetMgr.
Referenced by ~HttpServer.
void HttpServer::ShowConsoleTitle(int iDTime)
References SeHttpConfig::dwServerID, GetID2Str, m_kConfig, SeLogInfo, SPrintf.
SeServerActionResult HttpServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F5, SeLogHideTime.
void HttpServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, g_kVirtConnMgr, SeNetAddr::iPort, SeVirtConn::kNetAddr, m_pkWSConn, SeVirtConnMgr::OnServerConnected.
void HttpServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
void HttpServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References SeVirtConn::kSock, m_kNetMgr, m_pkWSConn, ProcessWHData.
void HttpServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References g_kVirtConnMgr, SeVirtConn::kSock, m_pkWSConn, SeVirtConnMgr::OnServerDisconnect.
void HttpServer::OnHttpRequest(unsigned long ulKey, const char *pcUrl, const char *pcContent, int iSize)
Referenced by HttpRequestCallback.
void HttpServer::OnHttpResponse(unsigned long ulKey, const char *pcContent, int iSize)
References GetDeleteResponse, SeResponseContent::iType, ProcessHttp_QueryFreeHeroListRet, SeLogError, SHQT_QUERY_FREE_HERO_LIST.
Referenced by HttpResponseCallback.
void HttpServer::OnHttpClose(unsigned long ulKey)
Referenced by HttpCloseCallback.
DWord HttpServer::GetServerTime(void)
References m_dwCurTime.
Referenced by PreProcessWH.
DWord HttpServer::GetServerID(void)
References SeHttpConfig::dwServerID, m_kConfig.
Referenced by sendRegPack.
bool HttpServer::SendHW_Register(DWord dwMagic, DWord dwServerID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool HttpServer::SendHW_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool HttpServer::SendHW_QueryFreeHeroListRet(int iNum, const DWord *adwHeroID, void *pkReceiver=NULL)
Referenced by ProcessHttp_QueryFreeHeroListRet.
bool HttpServer::SendHW_QueryFreeHeroListRet(int iNum, std::vector< DWord > &adwHeroID, void *pkReceiver=NULL)
bool HttpServer::SendHWData(void *pkData, int iSize, void *pkReceiver)
References CMD_HW_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkWSConn, SVCS_REGISTERED, SeCMD::wCmd.
int HttpServer::HttpRequestCallback(unsigned long ulKey, const char *pcUrl, const char *pcContent, int iSize)
References OnHttpRequest.
Referenced by Initialize.
int HttpServer::HttpResponseCallback(unsigned long ulKey, const char *pcContent, int iSize)
References OnHttpResponse.
Referenced by Initialize.
int HttpServer::HttpCloseCallback(unsigned long ulKey)
References OnHttpClose.
Referenced by Initialize.
bool HttpServer::ProcessWHData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool HttpServer::PreProcessWH(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, GetServerTime, m_pkWSConn.
void HttpServer::ProcessWH_RegisterRet(SeWH_RegisterRet *pkData, int iSize, void *pkSender)
References SeHttpConfig::dwServerID, SeWH_RegisterRet::eRegisterRet, SeVirtConn::eState, GetID2Str, m_kConfig, m_pkWSConn, SeLogError, SeLogInfo, SRR_REPEAT, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void HttpServer::ProcessWH_HeartPackageRet(SeWH_HeartPackageRet *pkData, int iSize, void *pkSender)
void HttpServer::ProcessWH_QueryFreeHeroList(SeWH_QueryFreeHeroList *pkData, int iSize, void *pkSender)
References AddResponse, SeResponseContent::iType, SeLogError, SHQT_QUERY_FREE_HERO_LIST, SPrintf.
bool HttpServer::ProcessHttp_QueryFreeHeroListRet(const char *pcContent, int iSize, SeResponseContent &rkContent)
References Json::Value::asInt, Json::Value::isArray, Json::Value::isObject, Json::Reader::parse, SendHW_QueryFreeHeroListRet, Json::Value::size.
Referenced by OnHttpResponse.
bool HttpServer::LoadConfig(const char *pcFile)
References SeVirtConnMgr::AddServerConn, SeHttpConfig::dwServerID, g_kVirtConnMgr, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeHttpConfig::kHttpServer, SeConfig::Load, LoadDynamicConfig, m_kConfig, m_pkWSConn, SeLogError, SeLogInfo, SSI_WS.
Referenced by Initialize.
bool HttpServer::LoadDynamicConfig(void)
References SeHttpConfig::dwHeartPackageTime, SeConfig::GetValue, SeConfig::Load, m_kConfig, SeLogError.
Referenced by LoadConfig.
bool HttpServer::InitializeNet(void)
References m_kNetMgr, SeLogError, SeLogInfo.
Referenced by Initialize.
void HttpServer::AddRequest(ULONG ulKey, SeRequestContent &rkContent)
References m_kMapRequest, m_kRequestLock.
bool HttpServer::GetDeleteRequest(ULONG ulKey, SeRequestContent &rkContent)
References m_kMapRequest, m_kRequestLock.
void HttpServer::AddResponse(ULONG ulKey, SeResponseContent &rkContent)
References m_kMapResponse, m_kResponseLock.
Referenced by ProcessWH_QueryFreeHeroList.
bool HttpServer::GetDeleteResponse(ULONG ulKey, SeResponseContent &rkContent)
References m_kMapResponse, m_kResponseLock.
Referenced by OnHttpResponse.