NexusServer
TeNetMgr NexusServer::m_kNetMgr
Referenced by InitializeNet, InitializeNetEx, OnNetRecv, ProcessRN_Register, ProcessWCMSN_Register, SendNBKSData, SendNMData, SendNRData, SendNTData, SendNWCMSData, SendNWData, Update, UpdateConnect.
SeVirtConn* NexusServer::m_pkWSConn
Referenced by LoadConfig, NexusServer, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessBLN, PreProcessWN, ProcessWN_RegisterRet, SendNWData.
SeVirtConn* NexusServer::m_pkBKSConn
Referenced by PreProcessBKSN, ProcessBKSN_RegisterRet, SendNBKSData.
SeNexusConfig NexusServer::m_kConfig
Referenced by GetAreaID, GetServerID, InitializeNet, LoadConfig, ProcessMN_Register, ProcessRN_Register, ProcessTN_Register, ProcessWCMSN_Register.
MapAllConnect NexusServer::m_kAllConnect
Referenced by OnNetAccept, OnNetDisconnect, OnNetRecv, UpdateConnect.
DWord NexusServer::m_dwTickCount
Referenced by NexusServer, Update.
DWord NexusServer::m_dwCurTime
Referenced by GetServerTime, NexusServer, PreProcessBKSN, PreProcessBLN, PreProcessWN, ProcessTN_LeaderKickMemberReq, ProcessTN_NexusLinkUserSync, ProcessTN_UserConfirmInviteReq, ProcessTN_UserInviteReq, ProcessTN_UserLeaveTeamReq, ProcessTN_UserRefuseInviteReq, Update.
NexusServer::NexusServer(void)
References m_dwCurTime, m_dwTickCount, m_pkWSConn.
NexusServer::~NexusServer(void)
bool NexusServer::Initialize(void)
References moba::Clock::getInstance, InitializeNet, InitializeNetEx, LoadConfig, moba::Clock::setTime.
void NexusServer::Update(void)
References g_kVirtConnMgr, moba::Clock::getInstance, m_dwCurTime, m_dwTickCount, m_kNetMgr, moba::Clock::setTime, SeVirtConnMgr::Update, UpdateConnect, UpdateLogicl.
void NexusServer::Finialize(void)
void NexusServer::ShowConsoleTitle(int iDTime)
References SPrintf.
SeServerActionResult NexusServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, SeLogHideTime.
void NexusServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, g_kVirtConnMgr, SeNetAddr::iPort, SeVirtConn::kNetAddr, m_pkWSConn, SeVirtConnMgr::OnServerConnected.
void NexusServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeConnect::dwServerID, moba::Clock::getInstance, moba::Clock::getMilliSeconds, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllConnect, SSD_IP_LEN, SSI_UNKNOWN, StrCpy.
void NexusServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References CMD_MN_REGISTER, CMD_RN_REGISTER, CMD_TN_REGISTER, CMD_WCMSN_REGISTER, moba::Clock::getInstance, moba::Clock::getMilliSeconds, SeVirtConn::kSock, m_kAllConnect, m_kNetMgr, m_pkWSConn, ProcessBLNData, ProcessMNData, ProcessRNData, ProcessTNData, ProcessWCMSNData, ProcessWNData, SSI_MS, SSI_RS, SSI_TS, SSI_UNKNOWN, SSI_WCMS, STCB_BLS_NS, STCB_INTERVAL, SeCMD::wCmd.
void NexusServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, moba::ServerSessionMgr::deleteServer, SeConnect::dwServerID, g_kMatchServerMgr, g_kRaceServerMgr, g_kTownServerMgr, g_kVirtConnMgr, WatchServer::g_kWatchServerMgr, SeNetAddr::iPort, SeConnect::kNetAddr, SeVirtConn::kSock, m_kAllConnect, m_pkWSConn, SeVirtConnMgr::OnServerDisconnect, SeLogError, SSI_MS, SSI_RS, SSI_TS, SSI_WCMS.
void NexusServer::UpdateLogicl()
References g_kNexusTeamMgr, GetServerTime, NS_TEAM_CHECK_TIME, NexusTeamMgr::Update.
Referenced by Update.
bool NexusServer::SendNT_RegisterRet(const SeRegisterRet &eRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessTN_Register.
bool NexusServer::SendNT_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessTN_HeartPackage.
bool NexusServer::SendNT_NexusFriendDetailInfoRes(DWord dwPlayerID, int page_number, int page_max_number, int iNum, const SeNexusPlayerInfo *akNexusFriendInfo, void *pkReceiver=NULL)
Referenced by ProcessTN_NexusFriendDetailInfoReq.
bool NexusServer::SendNT_NexusFriendDetailInfoRes(DWord dwPlayerID, int page_number, int page_max_number, int iNum, std::vector< SeNexusPlayerInfo > &akNexusFriendInfo, void *pkReceiver=NULL)
bool NexusServer::SendNT_NexusUserActionSync(DWord dwPlayerID, const SeNexusUserInfo &sync_info, void *pkReceiver=NULL)
Referenced by ProcessTN_NexusUserActionReq.
bool NexusServer::SendNT_TeamChangeSync(DWord dwPlayerID, DWord dwTeamID, DWord dwLeaderID, const char *acLeaderName, void *pkReceiver=NULL)
Referenced by ProcessTN_UserConfirmInviteReq, ProcessTN_UserInviteReq, ProcessTN_UserLeaveTeamReq.
bool NexusServer::SendNT_TeamLeaderSync(DWord dwPlayerID, DWord dwGuestID, const char *acGuestName, DWord dwMark, void *pkReceiver=NULL)
Referenced by ProcessTN_UserLeaveTeamReq, ProcessTN_UserRefuseInviteReq.
bool NexusServer::SendNT_TeamMemberSync(DWord dwPlayerID, DWord dwTeamID, DWord dwInviterID, const char *acInviterName, DWord dwMark, void *pkReceiver=NULL)
Referenced by ProcessTN_LeaderKickMemberReq, ProcessTN_UserInviteReq.
bool NexusServer::SendNT_TeamUserStateRes(DWord dwPlayerID, DWord dwStateID, void *pkReceiver=NULL)
Referenced by ProcessTN_LeaderKickMemberReq, ProcessTN_NexusLinkUserSync, ProcessTN_UserConfirmInviteReq, ProcessTN_UserInviteReq, ProcessTN_UserLeaveTeamReq, ProcessTN_UserRefuseInviteReq.
bool NexusServer::SendNT_TeamMemberInfoRes(DWord dwPlayerID, DWord dwTeamID, int iNum, const SeTeamMemberBaseInfo *member_info, void *pkReceiver=NULL)
Referenced by ProcessTN_LeaderKickMemberReq, ProcessTN_NexusLinkUserSync, ProcessTN_UserConfirmInviteReq, ProcessTN_UserLeaveTeamReq.
bool NexusServer::SendNT_TeamMemberInfoRes(DWord dwPlayerID, DWord dwTeamID, int iNum, std::vector< SeTeamMemberBaseInfo > &member_info, void *pkReceiver=NULL)
bool NexusServer::SendNT_NexusFriendStatusSync(DWord dwPlayerID, DWord dwFriendID, DWord dwOnlineID, void *pkReceiver=NULL)
Referenced by ProcessTN_NexusLinkUserSync, ProcessTN_NexusUserActionReq.
bool NexusServer::SendNT_NexusFriendLimitRes(DWord dwPlayerID, DWord dwLimitID, void *pkReceiver=NULL)
Referenced by ProcessTN_NexusUserActionReq.
bool NexusServer::SendNT_MatchTeamMemberRes(DWord dwPlayerID, const MatchReqResult &result, DWord MemberNum, const DWord *IDArray, void *pkReceiver=NULL)
Referenced by ProcessTN_MatchTeamMemberReq.
bool NexusServer::SendNT_MatchTeamMemberRes(DWord dwPlayerID, const MatchReqResult &result, DWord MemberNum, std::vector< DWord > &IDArray, void *pkReceiver=NULL)
bool NexusServer::SendNT_NexusFriendCleanRefuseNoticeRes(DWord dwPlayerID, DWord dwGuestID, void *pkReceiver=NULL)
Referenced by ProcessTN_NexusFriendCleanRefuseNoticeReq.
bool NexusServer::SendNT_UserStatusQueryRes(DWord dwPlayerID, int iNum, const SeUserStatusBaseInfo *base_info, void *pkReceiver=NULL)
Referenced by ProcessTN_UserStatusQueryReq.
bool NexusServer::SendNT_UserStatusQueryRes(DWord dwPlayerID, int iNum, std::vector< SeUserStatusBaseInfo > &base_info, void *pkReceiver=NULL)
bool NexusServer::SendNT_RoomInviteNotifyVerifyRsp(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessTN_RoomInviteNotifyVerify.
bool NexusServer::SendNTData(void *pkData, int iSize, void *pkReceiver)
References moba::ServerSessionMgr::broadcast, g_kTownServerMgr, m_kNetMgr.
bool NexusServer::ProcessTNData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool NexusServer::PreProcessTN(void *pkData, int iSize, void *pkSender)
void NexusServer::ProcessTN_Register(SeTN_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, moba::ServerSessionMgr::checkServer, moba::ServerSessionMgr::createServer, SeNexusConfig::dwAreaID, SeTN_Register::dwServerID, SeConnect::dwServerID, g_kTownServerMgr, GetID2Str, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kConfig, SeLogInfo, SendNT_RegisterRet, SRR_SUCCESS, SSI_TS, SSI_UNKNOWN.
void NexusServer::ProcessTN_HeartPackage(SeTN_HeartPackage *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, SeLogError, SendNT_HeartPackageRet.
void NexusServer::ProcessTN_RoomInviteNotifyVerify(SeTN_RoomInviteNotifyVerify *pkData, int iSize, void *pkSender)
References NexusLinkUserMgr::check_matching, NexusLinkUserMgr::check_offline, NexusLinkUserMgr::check_racing, NexusLinkUserMgr::check_watching, SeTN_RoomInviteNotifyVerify::dwInviteeID, SeTN_RoomInviteNotifyVerify::dwPlayerID, SeTN_RoomInviteNotifyVerify::dwRoomID, g_kNexusLinkUserMgr, GET_CUR_CONN, SeLogDebug, SendNT_RoomInviteNotifyVerifyRsp.
void NexusServer::ProcessTN_NexusFriendDetailInfoReq(SeTN_NexusFriendDetailInfoReq *pkData, int iSize, void *pkSender)
References SeTN_NexusFriendDetailInfoReq::dwPlayerID, SeNexusUserBaseInfo::dwPlayerId, ENM_Dismiss, g_kNexusFriendMgr, g_kNexusLinkUserMgr, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_online_state, NexusFriendMgr::get_player_friend_map, SeNexusKeyInfo::key, SeNexusPlayerInfo::mark, SeTN_NexusFriendDetailInfoReq::page_counts, SeTN_NexusFriendDetailInfoReq::page_number, NexusFriend::player_info, SeLogDebug, SendNT_NexusFriendDetailInfoRes, SeNexusPlayerInfo::status, SeNexusPlayerInfo::user_info.
void NexusServer::ProcessTN_NexusUserActionReq(SeTN_NexusUserActionReq *pkData, int iSize, void *pkSender)
References SeNexusUserBaseInfo::acName, NexusFriendMgr::check_apply, NexusFriendMgr::check_confirm, NexusFriendMgr::check_limit, NexusFriendMgr::check_player, SeTN_NexusUserActionReq::dwPlayerID, SeNexusUserBaseInfo::dwPlayerId, SeTN_NexusUserActionReq::dwPlayerOnlineID, ENFL_MemberLimit, ENM_Cancel, ENM_Confirm, ENM_Dismiss, ENM_Reject, ENM_Request, ENState_Offline, ENState_Online, SeNexusUserInfo::friend_info, g_kNexusFriendMgr, g_kNexusLinkUserMgr, NexusFriendMgr::gen_master_nexus_user, NexusFriendMgr::gen_nexus_friend, NexusFriendMgr::gen_nexus_player, NexusFriendMgr::gen_slaver_nexus_user, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_online_state, SeNexusKeyInfo::key, NexusFriendMgr::make, NexusFriendMgr::make_friend, SeNexusUserInfo::mark, SeTN_NexusUserActionReq::nexus_user_actions, NowTime, SendNT_NexusFriendLimitRes, SendNT_NexusFriendStatusSync, SendNT_NexusUserActionSync, SendNW_CreateNexusFriendReq, SendNW_CreateNexusOfflineFriendReq, SendNW_UpdateNexusFriendReq, SeNexusUserInfo::user_info, NexusFriendMgr::verify.
void NexusServer::ProcessTN_NexusLinkUserSync(SeTN_NexusLinkUserSync *pkData, int iSize, void *pkSender)
References SeTeamMemberBaseInfo::acMemberName, NexusTeamMgr::check_disband, NexusTeamMgr::disband, SeTeamMemberBaseInfo::dwBattleScores, SeTeamMemberBaseInfo::dwInviterID, SeTeamMemberBaseInfo::dwLadderScores, SeTN_NexusLinkUserSync::dwLoginTime, SeTeamMemberBaseInfo::dwMatchScores, SeTeamMemberBaseInfo::dwMemberID, SeTeamMemberBaseInfo::dwOrderID, SeTN_NexusLinkUserSync::dwPlayerID, SeNexusUserBaseInfo::dwPlayerId, SeTeamMemberBaseInfo::dwPunishTime, SeTN_NexusLinkUserSync::dwStateID, ENM_Confirm, ENState_Offline, ENState_Online, ETUNS_Confirm, ETUNS_Dismiss, ETUNS_Offline, g_kNexusFriendMgr, g_kNexusLinkUserMgr, g_kNexusTeamMgr, NexusTeamMgr::gen_param, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_battle_scores, NexusLinkUserMgr::get_link_user_ladder_scores, NexusLinkUserMgr::get_link_user_match_scores, NexusLinkUserMgr::get_link_user_punish_time, NexusLinkUserMgr::get_link_user_team, NexusTeamMgr::get_member_map, NexusFriendMgr::get_player_friend_map, NexusTeamMgr::get_team_leader_id, NexusTeamMemberBase::inviter_id, SeNexusKeyInfo::key, m_dwCurTime, NexusLinkUserMgr::make, NexusTeamMgr::make, NexusTeamMemberBase::mark, SeNexusPlayerInfo::mark, NexusTeamMember::member_base, NexusTeamMemberBase::order_id, NexusFriend::player_info, SeLogDebug, SendNBKS_UserStateSync, SendNT_NexusFriendStatusSync, SendNT_TeamMemberInfoRes, SendNT_TeamUserStateRes, NexusTeamMemberBase::user_id, SeNexusPlayerInfo::user_info, NexusTeamMemberBase::user_name.
void NexusServer::ProcessTN_CreateUserSync(SeTN_CreateUserSync *pkData, int iSize, void *pkSender)
References SeTN_CreateUserSync::acRemoteIp, SeTN_CreateUserSync::dwLoginTime, SeTN_CreateUserSync::dwPlayerID, GET_CUR_CONN, SeLogDebug, SendNBKS_CreatUserSync.
void NexusServer::ProcessTN_UserInviteReq(SeTN_UserInviteReq *pkData, int iSize, void *pkSender)
References SeTN_UserInviteReq::acGuestName, SeTN_UserInviteReq::acUserName, NexusTeamMgr::check_invite, NexusLinkUserMgr::check_matching, NexusTeamMgr::check_member, NexusLinkUserMgr::check_offline, NexusLinkUserMgr::check_racing, NexusTeamMgr::check_team, NexusTeamMgr::check_team_state, NexusTeamMgr::check_valid, NexusLinkUserMgr::check_watching, SeTN_UserInviteReq::dwGuestID, SeTN_UserInviteReq::dwPlayerID, ETUNS_IllegalTeam, ETUNS_Invite, ETUNS_Matching, ETUNS_Offline, ETUNS_OterMember, ETUNS_Racing, ETUNS_SelfMember, ETUNS_TeamLimited, ETUNS_Watching, g_kNexusLinkUserMgr, g_kNexusTeamMgr, NexusTeamMgr::gen_param, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_team, NexusTeamMgr::get_team_leader_id, NexusTeamMgr::get_team_member, m_dwCurTime, NexusTeamMgr::make, NexusTeamMember::member_base, SeLogDebug, SendNT_TeamChangeSync, SendNT_TeamMemberSync, SendNT_TeamUserStateRes, NexusTeamMemberBase::user_name.
void NexusServer::ProcessTN_UserConfirmInviteReq(SeTN_UserConfirmInviteReq *pkData, int iSize, void *pkSender)
References SeTeamMemberBaseInfo::acMemberName, NexusLinkUserMgr::check_matching, NexusTeamMgr::check_member, NexusLinkUserMgr::check_racing, NexusTeamMgr::check_team, NexusTeamMgr::check_team_state, NexusTeamMgr::check_valid, NexusLinkUserMgr::check_watching, SeTeamMemberBaseInfo::dwBattleScores, SeTeamMemberBaseInfo::dwInviterID, SeTeamMemberBaseInfo::dwLadderScores, SeTeamMemberBaseInfo::dwMatchScores, SeTeamMemberBaseInfo::dwMemberID, SeTeamMemberBaseInfo::dwOrderID, SeTN_UserConfirmInviteReq::dwPlayerID, SeTeamMemberBaseInfo::dwPunishTime, SeTN_UserConfirmInviteReq::dwTeamID, ETUNS_Confirm, ETUNS_IllegalTeam, ETUNS_Matching, ETUNS_OterMember, ETUNS_Racing, ETUNS_SelfMember, ETUNS_TeamLimited, ETUNS_Watching, g_kNexusLinkUserMgr, g_kNexusTeamMgr, NexusTeamMgr::gen_param, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_battle_scores, NexusLinkUserMgr::get_link_user_ladder_scores, NexusLinkUserMgr::get_link_user_match_scores, NexusLinkUserMgr::get_link_user_punish_time, NexusLinkUserMgr::get_link_user_team, NexusTeamMgr::get_member_map, NexusTeamMgr::get_team_leader_id, NexusTeamMgr::get_team_member, NexusTeamMemberBase::inviter_id, m_dwCurTime, NexusTeamMgr::make, NexusTeamMemberBase::mark, NexusTeamMember::member_base, NexusTeamMemberBase::order_id, SeLogDebug, SendNT_TeamChangeSync, SendNT_TeamMemberInfoRes, SendNT_TeamUserStateRes, NexusTeamMemberBase::user_id, NexusTeamMemberBase::user_name.
void NexusServer::ProcessTN_UserRefuseInviteReq(SeTN_UserRefuseInviteReq *pkData, int iSize, void *pkSender)
References NexusTeamMgr::check_team, SeTN_UserRefuseInviteReq::dwPlayerID, SeTN_UserRefuseInviteReq::dwTeamID, ETUNS_IllegalTeam, ETUNS_Refuse, g_kNexusTeamMgr, NexusTeamMgr::gen_param, GET_CUR_CONN, NexusTeamMgr::get_team_member, NexusTeamMemberBase::inviter_id, m_dwCurTime, NexusTeamMgr::make, NexusTeamMember::member_base, SeLogDebug, SendNT_TeamLeaderSync, SendNT_TeamUserStateRes, NexusTeamMemberBase::user_id, NexusTeamMemberBase::user_name.
void NexusServer::ProcessTN_UserLeaveTeamReq(SeTN_UserLeaveTeamReq *pkData, int iSize, void *pkSender)
References SeTeamMemberBaseInfo::acMemberName, NexusTeamMgr::check_disband, NexusTeamMgr::check_member, NexusTeamMgr::check_team, NexusTeamMgr::check_team_leader, NexusTeamMgr::disband, SeTeamMemberBaseInfo::dwBattleScores, SeTeamMemberBaseInfo::dwInviterID, SeTeamMemberBaseInfo::dwLadderScores, SeTeamMemberBaseInfo::dwMatchScores, SeTeamMemberBaseInfo::dwMemberID, SeTeamMemberBaseInfo::dwOrderID, SeTN_UserLeaveTeamReq::dwPlayerID, SeTeamMemberBaseInfo::dwPunishTime, SeTN_UserLeaveTeamReq::dwTeamID, ETUNS_Confirm, ETUNS_Dismiss, ETUNS_IllegalMember, ETUNS_IllegalTeam, ETUNS_Leave, g_kNexusLinkUserMgr, g_kNexusTeamMgr, NexusTeamMgr::gen_param, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_battle_scores, NexusLinkUserMgr::get_link_user_ladder_scores, NexusLinkUserMgr::get_link_user_match_scores, NexusLinkUserMgr::get_link_user_punish_time, NexusTeamMgr::get_member_inviter_id, NexusTeamMgr::get_member_map, NexusTeamMgr::get_team_leader_id, NexusTeamMgr::get_team_member, NexusTeamMemberBase::inviter_id, m_dwCurTime, NexusTeamMgr::make, NexusTeamMemberBase::mark, NexusTeamMember::member_base, NexusTeamMemberBase::order_id, SeLogDebug, SendNT_TeamChangeSync, SendNT_TeamLeaderSync, SendNT_TeamMemberInfoRes, SendNT_TeamUserStateRes, NexusTeamMemberBase::user_id, NexusTeamMemberBase::user_name.
void NexusServer::ProcessTN_LeaderKickMemberReq(SeTN_LeaderKickMemberReq *pkData, int iSize, void *pkSender)
References SeTeamMemberBaseInfo::acMemberName, NexusTeamMgr::check_disband, NexusTeamMgr::check_member, NexusTeamMgr::check_team, NexusTeamMgr::check_team_leader, NexusTeamMgr::disband, SeTeamMemberBaseInfo::dwBattleScores, SeTeamMemberBaseInfo::dwInviterID, SeTeamMemberBaseInfo::dwLadderScores, SeTeamMemberBaseInfo::dwMatchScores, SeTN_LeaderKickMemberReq::dwMemberID, SeTeamMemberBaseInfo::dwMemberID, SeTeamMemberBaseInfo::dwOrderID, SeTN_LeaderKickMemberReq::dwPlayerID, SeTeamMemberBaseInfo::dwPunishTime, SeTN_LeaderKickMemberReq::dwTeamID, ETUNS_Confirm, ETUNS_Dismiss, ETUNS_IllegalLeader, ETUNS_IllegalMember, ETUNS_IllegalTeam, ETUNS_Kick, g_kNexusLinkUserMgr, g_kNexusTeamMgr, NexusTeamMgr::gen_param, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_battle_scores, NexusLinkUserMgr::get_link_user_ladder_scores, NexusLinkUserMgr::get_link_user_match_scores, NexusLinkUserMgr::get_link_user_punish_time, NexusTeamMgr::get_member_map, NexusTeamMgr::get_team_leader_id, NexusTeamMgr::get_team_member, NexusTeamMemberBase::inviter_id, m_dwCurTime, NexusTeamMgr::make, NexusTeamMemberBase::mark, NexusTeamMember::member_base, NexusTeamMemberBase::order_id, SeLogDebug, SendNT_TeamMemberInfoRes, SendNT_TeamMemberSync, SendNT_TeamUserStateRes, NexusTeamMemberBase::user_id, NexusTeamMemberBase::user_name.
void NexusServer::ProcessTN_LeaderDismissTeamReq(SeTN_LeaderDismissTeamReq *pkData, int iSize, void *pkSender)
References SeTN_LeaderDismissTeamReq::dwPlayerID, GET_CUR_CONN, SeLogDebug.
void NexusServer::ProcessTN_MatchTeamMemberReq(SeTN_MatchTeamMemberReq *pkData, int iSize, void *pkSender)
References NexusTeamMgr::check_valid, SeTN_MatchTeamMemberReq::dwPlayerID, ETUNS_Confirm, g_kNexusLinkUserMgr, g_kNexusTeamMgr, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_team, NexusTeamMgr::get_member_map, NexusTeamMgr::get_team_leader_id, NexusTeamMemberBase::mark, NexusTeamMember::member_base, ReqResultNotTeamLeader, ReqResultSuccess, SeLogDebug, SendNT_MatchTeamMemberRes, NexusTeamMemberBase::user_id.
void NexusServer::ProcessTN_NexusFriendCleanRefuseNoticeReq(SeTN_NexusFriendCleanRefuseNoticeReq *pkData, int iSize, void *pkSender)
References SeTN_NexusFriendCleanRefuseNoticeReq::dwPlayerID, ENM_Dismiss, g_kNexusFriendMgr, GET_CUR_CONN, SeTN_NexusFriendCleanRefuseNoticeReq::guest_id, SeLogDebug, SendNT_NexusFriendCleanRefuseNoticeRes, SendNW_UpdateNexusFriendReq, NexusFriendMgr::verify.
void NexusServer::ProcessTN_UserStatusQueryReq(SeTN_UserStatusQueryReq *pkData, int iSize, void *pkSender)
References SeTN_UserStatusQueryReq::dwPlayerID, SeUserStatusBaseInfo::dwStatusID, SeUserStatusBaseInfo::dwUserID, g_kNexusLinkUserMgr, GET_CUR_CONN, NexusLinkUserMgr::get_link_user_state, SeTN_UserStatusQueryReq::num, SeLogDebug, SendNT_UserStatusQueryRes, SeTN_UserStatusQueryReq::user_ids.
void NexusServer::ProcessTN_UserAttrInfoSync(SeTN_UserAttrInfoSync *pkData, int iSize, void *pkSender)
References SeTN_UserAttrInfoSync::dwPlayerID, g_kNexusLinkUserMgr, GET_CUR_CONN, SeLogDebug, SeTN_UserAttrInfoSync::user_attr, NexusLinkUserMgr::verify_user_attr.
bool NexusServer::SendNW_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool NexusServer::SendNW_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool NexusServer::SendNW_CreateNexusFriendReq(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, const char *acName, const SeDBTime &CreateTime, void *pkReceiver=NULL)
Referenced by ProcessTN_NexusUserActionReq.
bool NexusServer::SendNW_CreateNexusOfflineFriendReq(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, const char *acName, const SeDBTime &CreateTime, void *pkReceiver=NULL)
Referenced by ProcessTN_NexusUserActionReq.
bool NexusServer::SendNW_UpdateNexusFriendReq(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, void *pkReceiver=NULL)
Referenced by ProcessTN_NexusFriendCleanRefuseNoticeReq, ProcessTN_NexusUserActionReq.
bool NexusServer::SendNW_DelNexusFriendReq(DWord dwPlayerID, DWord dwPlayerFriendID, void *pkReceiver=NULL)
bool NexusServer::SendNWData(void *pkData, int iSize, void *pkReceiver)
References CMD_NW_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkWSConn, SVCS_REGISTERED, SeCMD::wCmd.
Referenced by SendNBLData.
bool NexusServer::ProcessWNData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool NexusServer::PreProcessWN(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkWSConn.
void NexusServer::ProcessWN_RegisterRet(SeWN_RegisterRet *pkData, int iSize, void *pkSender)
References SeWN_RegisterRet::dwAreaID, SeVirtConn::dwAreaID, SeWN_RegisterRet::eRegisterRet, SeVirtConn::eState, m_pkWSConn, SeLogError, SeLogInfo, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void NexusServer::ProcessWN_HeartPackageRet(SeWN_HeartPackageRet *pkData, int iSize, void *pkSender)
void NexusServer::ProcessWN_NexusFriendInfoSyn(SeWN_NexusFriendInfoSyn *pkData, int iSize, void *pkSender)
References SeWN_NexusFriendInfoSyn::acName, SeNexusUserBaseInfo::acName, SeNexusFriendSyncInfo::acName, SeWN_NexusFriendInfoSyn::akNexusFriendSync, SeNexusFriendSyncInfo::dwMark, SeNexusFriendSyncInfo::dwPlayerFriendID, SeNexusUserBaseInfo::dwPlayerId, SeNexusFriendSyncInfo::dwPlayerID, SeNexusUserInfo::friend_info, g_kNexusFriendMgr, NexusFriendMgr::gen_nexus_friend, NexusFriendMgr::gen_nexus_player, SeWN_NexusFriendInfoSyn::iNum, SeNexusKeyInfo::key, NexusFriendMgr::make_friend, SeNexusUserInfo::mark, SeNexusUserInfo::user_info.
void NexusServer::ProcessWN_PlayerScoreNtf(SeWN_PlayerScoreNtf *pkData, int iSize, void *pkSender)
References SeWN_PlayerScoreNtf::dwMatchType, SeWN_PlayerScoreNtf::dwPlayerID, SeWN_PlayerScoreNtf::dwScore, g_kNexusLinkUserMgr, NexusLinkUserMgr::verify_scores.
bool NexusServer::SendNWCMS_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessWCMSN_Register.
bool NexusServer::SendNWCMS_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessWCMSN_HeartPackage.
bool NexusServer::SendNWCMSData(void *pkData, int iSize, void *pkReceiver)
References WatchServer::g_kWatchServerMgr, m_kNetMgr.
bool NexusServer::ProcessWCMSNData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool NexusServer::PreProcessWCMSN(void *pkData, int iSize, void *pkSender)
void NexusServer::ProcessWCMSN_Register(SeWCMSN_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeNexusConfig::dwAreaID, SeWCMSN_Register::dwLoginMagic, SeWCMSN_Register::dwServerID, SeConnect::dwServerID, WatchServer::g_kWatchServerMgr, GetID2Str, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kConfig, m_kNetMgr, SeLogInfo, SendNWCMS_RegisterRet, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_UNKNOWN, SSI_WCMS.
void NexusServer::ProcessWCMSN_HeartPackage(SeWCMSN_HeartPackage *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, SeLogError, SendNWCMS_HeartPackageRet.
void NexusServer::ProcessWCMSN_RaceWatchUserSync(SeWCMSN_RaceWatchUserSync *pkData, int iSize, void *pkSender)
References SeWCMSN_RaceWatchUserSync::dwPlayerID, SeWCMSN_RaceWatchUserSync::dwStateID, g_kNexusLinkUserMgr, NexusLinkUserMgr::make, SeLogDebug.
bool NexusServer::SendNR_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessRN_Register.
bool NexusServer::SendNR_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessRN_HeartPackage.
bool NexusServer::SendNRData(void *pkData, int iSize, void *pkReceiver)
References moba::ServerSessionMgr::broadcast, g_kRaceServerMgr, m_kNetMgr.
bool NexusServer::ProcessRNData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool NexusServer::PreProcessRN(void *pkData, int iSize, void *pkSender)
void NexusServer::ProcessRN_Register(SeRN_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, moba::ServerSessionMgr::checkServer, moba::ServerSessionMgr::createServer, SeNexusConfig::dwAreaID, SeRN_Register::dwLoginMagic, SeRN_Register::dwServerID, SeConnect::dwServerID, g_kRaceServerMgr, GetID2Str, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kConfig, m_kNetMgr, SeLogInfo, SendNR_RegisterRet, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_RS, SSI_UNKNOWN.
void NexusServer::ProcessRN_HeartPackage(SeRN_HeartPackage *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, SeLogError, SendNR_HeartPackageRet.
void NexusServer::ProcessRN_RaceLinkUserSync(SeRN_RaceLinkUserSync *pkData, int iSize, void *pkSender)
References SeRN_RaceLinkUserSync::dwPlayerID, SeRN_RaceLinkUserSync::dwStateID, g_kNexusLinkUserMgr, NexusLinkUserMgr::make, SeLogDebug, SendNBKS_UserStateSync.
bool NexusServer::SendNBKS_Register(DWord dwServerID, DWord dwAreaID, void *pkReceiver=NULL)
bool NexusServer::SendNBKS_HeartPackage(void *pkReceiver=NULL)
bool NexusServer::SendNBKS_UserStateSync(DWord dwPlayerID, DWord dwStateID, DWord dwLoginTime, void *pkReceiver=NULL)
Referenced by ProcessRN_RaceLinkUserSync, ProcessTN_NexusLinkUserSync.
bool NexusServer::SendNBKS_CreatUserSync(DWord dwPlayerID, DWord dwLoginTime, const char *acRemoteIp, void *pkReceiver=NULL)
Referenced by ProcessTN_CreateUserSync.
bool NexusServer::SendNBKSData(void *pkData, int iSize, void *pkReceiver)
References CMD_NBKS_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkBKSConn, SVCS_REGISTERED, SeCMD::wCmd.
bool NexusServer::ProcessBKSNData(void *pkData, int iSize, void *pkSender=NULL)
bool NexusServer::PreProcessBKSN(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkBKSConn.
void NexusServer::ProcessBKSN_RegisterRet(SeBKSN_RegisterRet *pkData, int iSize, void *pkSender)
References SeBKSN_RegisterRet::eRet, SeVirtConn::eState, m_pkBKSConn, SeLogError, SeLogInfo, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void NexusServer::ProcessBKSN_HeartPackageRet(SeBKSN_HeartPackageRet *pkData, int iSize, void *pkSender)
bool NexusServer::SendNM_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessMN_Register.
bool NexusServer::SendNM_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessMN_HeartPackage.
bool NexusServer::SendNMData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool NexusServer::ProcessMNData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool NexusServer::PreProcessMN(void *pkData, int iSize, void *pkSender)
void NexusServer::ProcessMN_Register(SeMN_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, moba::ServerSessionMgr::checkServer, moba::ServerSessionMgr::createServer, SeNexusConfig::dwAreaID, SeMN_Register::dwServerID, SeConnect::dwServerID, g_kMatchServerMgr, GetID2Str, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kConfig, SeLogInfo, SendNM_RegisterRet, SRR_SUCCESS, SSI_MS, SSI_UNKNOWN.
void NexusServer::ProcessMN_HeartPackage(SeMN_HeartPackage *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, SeLogError, SendNM_HeartPackageRet.
void NexusServer::ProcessMN_MatchPunishNtf(SeMN_MatchPunishNtf *pkData, int iSize, void *pkSender)
References SeMN_MatchPunishNtf::dwMs, SeMN_MatchPunishNtf::dwPlayerID, g_kNexusLinkUserMgr, SeLogDebug, NexusLinkUserMgr::verify_punish_time.
bool NexusServer::SendNBLData(void *pkData, int iSize, void *pkReceiver)
References SendNWData.
bool NexusServer::ProcessBLNData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool NexusServer::PreProcessBLN(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkWSConn.
DWord NexusServer::GetServerID()
References SeNexusConfig::dwServerID, m_kConfig.
Referenced by sendRegPack.
DWord NexusServer::GetAreaID()
References SeNexusConfig::dwAreaID, m_kConfig.
DWord NexusServer::GetServerTime(void)
References m_dwCurTime.
Referenced by UpdateConnect, UpdateLogicl, NexusLinkUserMgr::verify_punish_time.
string NexusServer::GenGuidString()
References guidkeygen, SSI_NS, SSI_TS.
bool NexusServer::LoadConfig(const char *pcFile)
References SeVirtConnMgr::AddServerConn, SeNexusConfig::dwAreaID, SeNexusConfig::dwServerID, g_kVirtConnMgr, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeNexusConfig::kLocalServer, SeConfig::Load, m_kConfig, m_pkWSConn, SeLogError, SeLogInfo, SSI_WS.
bool NexusServer::LoadConfig(void)
Referenced by Initialize.
bool NexusServer::InitializeNet(void)
References SeNetAddr::acIP, g_kMatchServerMgr, g_kRaceServerMgr, g_kTownServerMgr, WatchServer::g_kWatchServerMgr, moba::ServerSessionMgr::initialize, SeNetAddr::iPort, SeNexusConfig::kLocalServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo, SERVER_BUFFER_SIZE.
Referenced by Initialize.
bool NexusServer::InitializeNetEx(void)
References g_kVirtConnMgr, SeVirtConnMgr::Initialize, m_kNetMgr, SeLogError, sendHeartPack, sendRegPack.
Referenced by Initialize.
void NexusServer::UpdateConnect()
References SeNetAddr::acIP, g_kMatchServerMgr, g_kRaceServerMgr, g_kTownServerMgr, WatchServer::g_kWatchServerMgr, moba::Clock::getInstance, moba::Clock::getMilliSeconds, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllConnect, m_kNetMgr, NS_DELAY_MAX_TIME, SeLogError, SSI_UNKNOWN, moba::ServerSessionMgr::update.
Referenced by Update.