PerformanceTiming::CInterval
UInt32 PerformanceTiming::CInterval::m_uiFlags
Referenced by CheckFlag, ClearFlag, GetVerboseLevel, SetFlag.
UInt64 PerformanceTiming::CInterval::m_EntryTime
Float64 PerformanceTiming::CInterval::m_dMaxIntervalTimeSec
Referenced by GetMaxIntervalTimeSec, HardReset.
Float64 PerformanceTiming::CInterval::m_dMinIntervalTimeSec
Referenced by GetMinIntervalTimeSec, HardReset.
Float64 PerformanceTiming::CInterval::m_dLastIntervalTimeSec
Referenced by GetLastIntervalTimeSec, HardReset.
Float64 PerformanceTiming::CInterval::m_dTotalIntervalTimeSec
Referenced by GetAverageIntervalTimeSec, GetTotalIntervalTimeSec, HardReset.
UInt32 PerformanceTiming::CInterval::m_iTotalIntervalEntries
Referenced by GetAverageIntervalTimeSec, GetTotalIntervalEntries, HardReset.
Float64 PerformanceTiming::CInterval::m_dThisFrameIntervalTimeSec
time spent in the interval this frame/tick - accumulator
Referenced by AdvanceFrame, GetThisFrameIntervalTimeSec, HardReset.
Float64 PerformanceTiming::CInterval::m_dLastFrameIntervalTimeSec
time spent in the interval last frame/tick
Referenced by AdvanceFrame, GetLastFrameIntervalTimeSec, HardReset.
UInt32 PerformanceTiming::CInterval::m_iThisFrameIntervalEntries
number of times the interval was start/ended (entered) this frame/tick - accumulator
Referenced by AdvanceFrame, GetThisFrameIntervalEntries, HardReset.
UInt32 PerformanceTiming::CInterval::m_iLastFrameIntervalEntries
number of times the interval was start/ended (entered) last frame/tick
Referenced by AdvanceFrame, GetLastFrameIntervalEntries, HardReset.
PerformanceTiming::TIntervalArray PerformanceTiming::CInterval::m_vChildren
Referenced by AddChild.
Int32 PerformanceTiming::CInterval::m_iDepth
Referenced by AdvanceFrame.
bool PerformanceTiming::CInterval::m_bLastFrameClosed
Referenced by AdvanceFrame, IsLastFrameClosed.
Float64 PerformanceTiming::CInterval::m_dWarningThresholdMS
Referenced by GetWarningThresholdMS.
Float64 PerformanceTiming::CInterval::m_dCriticalThresholdMS
Referenced by GetCriticalThresholdMS.
static Float64 PerformanceTiming::CInterval::s_dLastFrameNegIntervalTimeSec
Referenced by AdvanceFrameStatic, GetLastFrameNegIntervalTimeSec.
static Float64 PerformanceTiming::CInterval::s_dThisFrameNegIntervalTimeSec
Referenced by AdvanceFrameStatic.
PerformanceTiming::CInterval::CInterval(const std::string &sName, UInt32 uiFlags, Float64 dWarning=0.0, Float64 dCritical=0.0)
virtual void PerformanceTiming::CInterval::HardReset()
References m_dLastFrameIntervalTimeSec, m_dLastIntervalTimeSec, m_dMaxIntervalTimeSec, m_dMinIntervalTimeSec, m_dThisFrameIntervalTimeSec, m_dTotalIntervalTimeSec, m_iLastFrameIntervalEntries, m_iThisFrameIntervalEntries, m_iTotalIntervalEntries, PerformanceTiming::CPerformanceStat::ResetTouch.
Float64 PerformanceTiming::CInterval::GetWarningThresholdMS() const
References m_dWarningThresholdMS.
Float64 PerformanceTiming::CInterval::GetCriticalThresholdMS() const
References m_dCriticalThresholdMS.
Float64 PerformanceTiming::CInterval::GetMinIntervalTimeSec() const
References m_dMinIntervalTimeSec.
Float64 PerformanceTiming::CInterval::GetMaxIntervalTimeSec() const
References m_dMaxIntervalTimeSec.
Float64 PerformanceTiming::CInterval::GetLastIntervalTimeSec() const
References m_dLastIntervalTimeSec.
Float64 PerformanceTiming::CInterval::GetTotalIntervalTimeSec() const
References m_dTotalIntervalTimeSec.
Referenced by PerformanceTiming::Pred_IntervalByOrder::operator().
UInt32 PerformanceTiming::CInterval::GetTotalIntervalEntries() const
References m_iTotalIntervalEntries.
Float64 PerformanceTiming::CInterval::GetAverageIntervalTimeSec() const
References m_dTotalIntervalTimeSec, m_iTotalIntervalEntries.
Float64 PerformanceTiming::CInterval::GetLastFrameIntervalTimeSec() const
References m_dLastFrameIntervalTimeSec.
Referenced by CPerformanceTiming::EnumerateIntervals.
UInt32 PerformanceTiming::CInterval::GetLastFrameIntervalEntries() const
References m_iLastFrameIntervalEntries.
Referenced by CPerformanceTiming::EnumerateIntervals.
Float64 PerformanceTiming::CInterval::GetThisFrameIntervalTimeSec() const
References m_dThisFrameIntervalTimeSec.
UInt32 PerformanceTiming::CInterval::GetThisFrameIntervalEntries() const
References m_iThisFrameIntervalEntries.
bool PerformanceTiming::CInterval::IsLastFrameClosed() const
References m_bLastFrameClosed.
Referenced by CPerformanceTiming::EnumerateIntervals.
float PerformanceTiming::CInterval::GetIntervalPercentage() const
References CPerformanceTiming::GetTotalElapsedTime, CPerformanceTiming::InstanceQuick.
void PerformanceTiming::CInterval::Start()
Starts interval timing. Takes a timestamp of the current time. Only functions if the interval is not already started.
Referenced by PerformanceTiming::CIntervalScope::CIntervalScope, CPerformanceTiming::TickNotify.
void PerformanceTiming::CInterval::End()
Ends interval timing. Takes a timestamp of the current time, and computes interval from start time. Only functions if the interval is started.
References makeCallback.f.
Referenced by CPerformanceTiming::TickNotify, PerformanceTiming::CIntervalScope::~CIntervalScope.
void PerformanceTiming::CInterval::AdvanceFrame()
References m_bLastFrameClosed, m_dLastFrameIntervalTimeSec, m_dThisFrameIntervalTimeSec, m_iDepth, m_iLastFrameIntervalEntries, m_iThisFrameIntervalEntries.
Referenced by CPerformanceTiming::TickNotify.
UInt32 PerformanceTiming::CInterval::CheckFlag(UInt32 uFlag) const
References m_uiFlags.
void PerformanceTiming::CInterval::SetFlag(UInt32 uFlag)
References m_uiFlags.
void PerformanceTiming::CInterval::ClearFlag(UInt32 uFlag)
References m_uiFlags.
UInt32 PerformanceTiming::CInterval::GetVerboseLevel()
References m_uiFlags.
void PerformanceTiming::CInterval::AddChild(CInterval *pChild)
References m_vChildren.
Referenced by CPerformanceTiming::CreateOrLookupChildInterval.
IInterval* PerformanceTiming::CInterval::SetFolderName(const char *szFolderName)
References PerformanceTiming::CPerformanceStat::DoSetFolderName.
PerformanceTiming::CInterval::CInterval(const std::string &sName, UInt32 uiFlags, Float64 dWarning=0.0, Float64 dCritical=0.0)
virtual void PerformanceTiming::CInterval::HardReset()
References m_dLastFrameIntervalTimeSec, m_dLastIntervalTimeSec, m_dMaxIntervalTimeSec, m_dMinIntervalTimeSec, m_dThisFrameIntervalTimeSec, m_dTotalIntervalTimeSec, m_iLastFrameIntervalEntries, m_iThisFrameIntervalEntries, m_iTotalIntervalEntries, PerformanceTiming::CPerformanceStat::ResetTouch.
Float64 PerformanceTiming::CInterval::GetWarningThresholdMS() const
References m_dWarningThresholdMS.
Float64 PerformanceTiming::CInterval::GetCriticalThresholdMS() const
References m_dCriticalThresholdMS.
Float64 PerformanceTiming::CInterval::GetMinIntervalTimeSec() const
References m_dMinIntervalTimeSec.
Float64 PerformanceTiming::CInterval::GetMaxIntervalTimeSec() const
References m_dMaxIntervalTimeSec.
Float64 PerformanceTiming::CInterval::GetLastIntervalTimeSec() const
References m_dLastIntervalTimeSec.
Float64 PerformanceTiming::CInterval::GetTotalIntervalTimeSec() const
References m_dTotalIntervalTimeSec.
UInt32 PerformanceTiming::CInterval::GetTotalIntervalEntries() const
References m_iTotalIntervalEntries.
Float64 PerformanceTiming::CInterval::GetAverageIntervalTimeSec() const
References m_dTotalIntervalTimeSec, m_iTotalIntervalEntries.
Float64 PerformanceTiming::CInterval::GetLastFrameIntervalTimeSec() const
References m_dLastFrameIntervalTimeSec.
UInt32 PerformanceTiming::CInterval::GetLastFrameIntervalEntries() const
References m_iLastFrameIntervalEntries.
Float64 PerformanceTiming::CInterval::GetThisFrameIntervalTimeSec() const
References m_dThisFrameIntervalTimeSec.
UInt32 PerformanceTiming::CInterval::GetThisFrameIntervalEntries() const
References m_iThisFrameIntervalEntries.
bool PerformanceTiming::CInterval::IsLastFrameClosed() const
References m_bLastFrameClosed.
float PerformanceTiming::CInterval::GetIntervalPercentage() const
void PerformanceTiming::CInterval::Start()
void PerformanceTiming::CInterval::End()
void PerformanceTiming::CInterval::AdvanceFrame()
References m_bLastFrameClosed, m_dLastFrameIntervalTimeSec, m_dThisFrameIntervalTimeSec, m_iDepth, m_iLastFrameIntervalEntries, m_iThisFrameIntervalEntries.
UInt32 PerformanceTiming::CInterval::CheckFlag(UInt32 uFlag) const
References m_uiFlags.
void PerformanceTiming::CInterval::SetFlag(UInt32 uFlag)
References m_uiFlags.
void PerformanceTiming::CInterval::ClearFlag(UInt32 uFlag)
References m_uiFlags.
UInt32 PerformanceTiming::CInterval::GetVerboseLevel()
References m_uiFlags.
void PerformanceTiming::CInterval::AddChild(CInterval *pChild)
References m_vChildren.
IInterval* PerformanceTiming::CInterval::SetFolderName(const char *szFolderName)
References PerformanceTiming::CPerformanceStat::DoSetFolderName.
static Float64 PerformanceTiming::CInterval::GetLastFrameNegIntervalTimeSec()
References s_dLastFrameNegIntervalTimeSec.
Referenced by CPerformanceIntervalFileDump::Tick.
static void PerformanceTiming::CInterval::AdvanceFrameStatic()
References s_dLastFrameNegIntervalTimeSec, s_dThisFrameNegIntervalTimeSec.
Referenced by CPerformanceTiming::TickNotify.
static Float64 PerformanceTiming::CInterval::GetLastFrameNegIntervalTimeSec()
References s_dLastFrameNegIntervalTimeSec.
static void PerformanceTiming::CInterval::AdvanceFrameStatic()
References s_dLastFrameNegIntervalTimeSec, s_dThisFrameNegIntervalTimeSec.