PresetShopTableMgr
std::map<unsigned int,PresetShopTable*> PresetShopTableMgr::m_kPresetShopTableMap
Referenced by FillData, GetPresetShopTable, GetPresetShopTableMap, GetPresetShopTableVec, ~PresetShopTableMgr.
PresetShopTableMgr * PresetShopTableMgr::m_pkPresetShopTableMgr
Referenced by Get, ReLoad.
PresetShopTableMgr * PresetShopTableMgr::Get()
References m_pkPresetShopTableMgr, PresetShopTableMgr.
Referenced by GlobalTableMgr::GetPresetShopTable, TableMgr::LoadTable, ReLoad.
PresetShopTableMgr * PresetShopTableMgr::ReLoad()
References Get, m_pkPresetShopTableMgr.
Referenced by TableMgr::ReloadTable.
PresetShopTableMgr::PresetShopTableMgr()
References Load.
Referenced by Get.
PresetShopTableMgr::~PresetShopTableMgr()
References m_kPresetShopTableMap.
const PresetShopTable * PresetShopTableMgr::GetPresetShopTable(unsigned int iTypeID)
References m_kPresetShopTableMap.
Referenced by GlobalTableMgr::GetPresetShopTable.
const std::map< unsigned int, PresetShopTable * > & PresetShopTableMgr::GetPresetShopTableMap()
References m_kPresetShopTableMap.
TableResArray PresetShopTableMgr::GetPresetShopTableVec()
References m_kPresetShopTableMap, TableResArray::pushBack.
bool PresetShopTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by PresetShopTableMgr.
void PresetShopTableMgr::FillData(PresetShopTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, PresetShopTable::kName, m_kPresetShopTableMap, PresetShopTable::uiItemType, PresetShopTable::uiItemTypeID.
Referenced by Load.