SeOpenRoomMgr
DWord SeOpenRoomMgr::m_dwGenID
Referenced by GetGenID, SeOpenRoomMgr.
MPlayerID2RoomID SeOpenRoomMgr::m_kPlayerID2OpenRoomPtr
Referenced by DelRoom, OnCreateRoom, OnPlayerLeave, OnRoomInvite, OnRoomInviteRspOk, OnRoomJoin, OnRoomKickSomeone, OnRoomLeave, OnRoomReady, OnRoomSwitchSeat.
MID2OpenRoomPtr SeOpenRoomMgr::m_kMID2OpenRoomPtr
Referenced by OnCreateRoom, OnQueryRoomList, OnRoomInvite, OnRoomInviteRspOk, OnRoomJoin, OnRoomKickSomeone, OnRoomLeave, OnRoomReady, OnRoomSwitchSeat, StartMatch.
MID2OpenRoomPtr SeOpenRoomMgr::m_kMID2CreateRacePtr
Referenced by OnRoomInvite, OnRoomKickSomeone, OnRoomLeave, StartMatch, Update.
SeOpenRoomMgr::SeOpenRoomMgr()
References m_dwGenID.
void SeOpenRoomMgr::Update(DWord dwTime)
References SeMatchRace::bSendMatchAddr, DelRoom, SeOpenRoom::dwID, SeOpenRoom::dwRaceSession, g_kRaceMgr, SeRaceMgr::GetRace, SeTimer::IsPassed, m_kMID2CreateRacePtr, SeOpenRoom::repeatTimerInterValue, SeLogInfo.
uint32_t SeOpenRoomMgr::GetGenID()
References m_dwGenID.
Referenced by OnCreateRoom.
void SeOpenRoomMgr::OnCreateRoom(const HTownSign &rkTownSign, SeTM_MatchCreateRoom &rkCreateRoom, bool bSysCreate)
References SeTeamPlayer::acName, SeTM_MatchCreateRoom::acName, SeOpenRoom::bPlayBoss, SeTM_MatchCreateRoom::bPlayBoss, SeOpenRoom::bSysCreate, SeOpenRoom::bUseRobot, SeTM_MatchCreateRoom::bUseRobot, SeOpenRoom::campSeat, SeOpenRoom::chPass, SeOpenRoom::chRoomName, ConvOpenRoomInfo, CRR_HAS_ROOM, CRR_SUCCESS, SeTM_MatchCreateRoom::dwCamp, SeOpenRoom::dwGameMode, SeTM_MatchCreateRoom::dwGameMode, SeOpenRoom::dwID, SeTeamPlayer::dwJoinTime, SeOpenRoom::dwLeaderID, SeOpenRoom::dwMapID, SeTM_MatchCreateRoom::dwMapID, SeTeamPlayer::dwPlayerID, SeTM_MatchCreateRoom::dwPlayerID, SeTeamPlayer::dwTeamID, g_kMatchServer, g_kTownMgr, MapInfoTableMgr::Get, GetGenID, MapInfoTableMgr::GetMapInfoTable, MatchServer::GetServerTime, SeTownMgr::GetTownSockBySign, MapInfoTable::iCampNum, SeOpenRoom::iCampPlayerNum, SeOpenRoom::iDifficulty, SeTM_MatchCreateRoom::iDifficulty, MapInfoTable::iMaxPlayer, SeTeamPlayer::kTownSign, m_kMID2OpenRoomPtr, m_kPlayerID2OpenRoomPtr, SeOpenRoom::memberPtr, SeLogError, SeLogInfo, MatchServer::SendMT_MatchCreateRoomRet, SSD_MAX_CHAR_NAME, StartMatch, StrCpy, SeTM_MatchCreateRoom::strPass, SeTM_MatchCreateRoom::strRoomName.
void SeOpenRoomMgr::OnQueryRoomList(const HTownSign &rkTownSign, const SeTM_MatchQueryRoomList &rkRoom)
References ConvOpenRoomInfo, SeOpenRoom::dwID, SeTM_MatchQueryRoomList::dwPlayerID, g_kMatchServer, g_kTownMgr, SeTownMgr::GetTownSockBySign, m_kMID2OpenRoomPtr, MatchServer::SendMT_MatchQueryRoomListRet.
void SeOpenRoomMgr::OnRoomJoin(const HTownSign &rkTownSign, SeTM_MatchRoomJoin &rkJoin)
References SeTeamPlayer::acName, SeTM_MatchRoomJoin::acName, SeRoomMember::acName, SeRoomMember::byCamp, SeRoomMember::bySeat, SeOpenRoom::campSeat, SeOpenRoom::chPass, SeTM_MatchRoomJoin::dwCamp, SeTM_MatchRoomJoin::dwDstRoom, SeOpenRoom::dwID, SeTeamPlayer::dwJoinTime, SeOpenRoom::dwMapID, SeTeamPlayer::dwPlayerID, SeTM_MatchRoomJoin::dwPlayerID, SeRoomMember::dwPlayerID, SeTeamPlayer::dwTeamID, FindRoomEmptySeat, g_kMatchServer, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, MatchServer::GetServerTime, MapInfoTable::iMaxPlayer, SeTeamPlayer::kTownSign, m_kMID2OpenRoomPtr, m_kPlayerID2OpenRoomPtr, SeOpenRoom::memberPtr, ROOM_WAIT_RACE_TIMEOUT, SeLogError, SendRoomJoinRet, SendRoomNotify, SeTimer::SetInterValue, SLRJ_SEAT_BEEN_ACCOUNTED, SLRJ_SUCCESS, SLRJ_WRONG_PASSWORD, SLRN_MEMBER_JOIN, StrCpy, SeTM_MatchRoomJoin::strPass, SeOpenRoom::waitRaceTimer.
void SeOpenRoomMgr::OnRoomLeave(const HTownSign &rkTownSign, const SeTM_MatchRoomLeave &rkleave)
References SeRoomMember::byCamp, SeRoomMember::bySeat, SeOpenRoom::campSeat, SeTM_MatchRoomLeave::dwDstRoom, SeOpenRoom::dwID, SeOpenRoom::dwLeaderID, SeTeamPlayer::dwPlayerID, SeTM_MatchRoomLeave::dwPlayerID, SeRoomMember::dwPlayerID, SeTeamPlayer::dwTeamID, g_kMatchServer, g_kTownMgr, SeTownMgr::GetTownSockBySign, m_kMID2CreateRacePtr, m_kMID2OpenRoomPtr, m_kPlayerID2OpenRoomPtr, SeOpenRoom::memberPtr, SeLogError, MatchServer::SendMT_MatchRoomLeaveRet, SendRoomNotify, SLRN_MEMBER_LEAVE.
Referenced by OnPlayerLeave.
void SeOpenRoomMgr::OnRoomSwitchSeat(const HTownSign &rkTownSign, const SeTM_MatchRoomSwitchSeat &rkswitch)
References SeTeamPlayer::acName, SeRoomMember::acName, SeRoomMember::byCamp, SeRoomMember::bySeat, SeOpenRoom::campSeat, SeTM_MatchRoomSwitchSeat::dwCamp, SeTM_MatchRoomSwitchSeat::dwDstRoom, SeTeamPlayer::dwPlayerID, SeTM_MatchRoomSwitchSeat::dwPlayerID, SeRoomMember::dwPlayerID, SeTeamPlayer::dwTeamID, g_kMatchServer, g_kTownMgr, GetRoomPlayerseat, SeTownMgr::GetTownSockBySign, SeTM_MatchRoomSwitchSeat::iseat, m_kMID2OpenRoomPtr, m_kPlayerID2OpenRoomPtr, SeOpenRoom::memberPtr, SeLogError, MatchServer::SendMT_MatchRoomSwitchSeatRet, SendRoomNotify, SLRJ_SEAT_BEEN_ACCOUNTED, SLRJ_SUCCESS, SLRN_SWITCH_SEAT, StrCpy.
void SeOpenRoomMgr::OnRoomKickSomeone(const HTownSign &rkTownSign, const SeTM_MatchRoomKickSomeone &rkKick)
References SeTeamPlayer::acName, SeRoomMember::acName, SeRoomMember::byCamp, SeRoomMember::bySeat, SeOpenRoom::campSeat, SeOpenRoom::dwID, SeTM_MatchRoomKickSomeone::dwKickedPlayerID, SeOpenRoom::dwLeaderID, SeTM_MatchRoomKickSomeone::dwPlayerID, SeRoomMember::dwPlayerID, SeTM_MatchRoomKickSomeone::dwRoomID, SeTeamPlayer::dwTeamID, g_kMatchServer, g_kTownMgr, SeTownMgr::GetTownSockBySign, SeTM_MatchRoomKickSomeone::iseat, m_kMID2CreateRacePtr, m_kMID2OpenRoomPtr, m_kPlayerID2OpenRoomPtr, SeOpenRoom::memberPtr, SeLogError, MatchServer::SendMT_MatchRoomKickSomeoneRet, SendRoomNotify, SLRN_MEMBER_KICKED, SRK_INFO_EXPIRED, SRK_KICK_SUCESS, StrCpy.
void SeOpenRoomMgr::OnRoomInvite(const HTownSign &rkTownSign, const SeTM_MatchRoomInvite &rkInvite)
References SeTeamPlayer::acName, SeTM_MatchRoomInvite::dwInviteeID, SeOpenRoom::dwMapID, SeTM_MatchRoomInvite::dwPlayerID, SeTM_MatchRoomInvite::dwRoomID, g_kMatchServer, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, MapInfoTable::iMaxPlayer, m_kMID2CreateRacePtr, m_kMID2OpenRoomPtr, m_kPlayerID2OpenRoomPtr, SeOpenRoom::memberPtr, SeLogError, MatchServer::SendMBL_BlockRoomInvite.
void SeOpenRoomMgr::OnRoomInviteRspOk(const HTownSign &rkTownSign, const SeTM_MatchRoomInviteRsp &rkinviteOk)
References SeTeamPlayer::acName, SeTM_MatchRoomInviteRsp::acName, SeRoomMember::acName, SeRoomMember::byCamp, SeRoomMember::bySeat, SeOpenRoom::campSeat, SeOpenRoom::dwID, SeTeamPlayer::dwJoinTime, SeOpenRoom::dwMapID, SeTeamPlayer::dwPlayerID, SeTM_MatchRoomInviteRsp::dwPlayerID, SeRoomMember::dwPlayerID, SeTM_MatchRoomInviteRsp::dwRoomID, SeTeamPlayer::dwTeamID, FindRoomEmptySeat, g_kMatchServer, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, MatchServer::GetServerTime, MapInfoTable::iMaxPlayer, SeTeamPlayer::kTownSign, m_kMID2OpenRoomPtr, m_kPlayerID2OpenRoomPtr, SeOpenRoom::memberPtr, ROOM_WAIT_RACE_TIMEOUT, SeLogError, SendRoomJoinRet, SendRoomNotify, SeTimer::SetInterValue, SLRJ_SEAT_BEEN_ACCOUNTED, SLRJ_SUCCESS, SLRN_MEMBER_JOIN, StrCpy, SeOpenRoom::waitRaceTimer.
void SeOpenRoomMgr::OnRoomReady(const HTownSign &rkTownSign, const SeTM_MatchRoomReady &rkReady)
References SeOpenRoom::dwLeaderID, SeOpenRoom::dwMapID, SeTM_MatchRoomReady::dwPlayerID, SeTM_MatchRoomReady::dwRoomID, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, m_kMID2OpenRoomPtr, m_kPlayerID2OpenRoomPtr, SeLogError, StartMatch.
void SeOpenRoomMgr::OnPlayerLeave(const HTownSign &rkTownSign, DWord dwPlayerID, DWord dwDelID)
References SeTM_MatchRoomLeave::dwDstRoom, SeTM_MatchRoomLeave::dwPlayerID, m_kPlayerID2OpenRoomPtr, OnRoomLeave.
int SeOpenRoomMgr::GetCampMemberNum(DWord dwCamp, SeOpenRoom *pRoom)
References SeOpenRoom::campSeat, SeOpenRoom::memberPtr.
Referenced by CreateRaceInfo.
DWord SeOpenRoomMgr::CreateRaceInfo(SeOpenRoom *pRoom, const MapInfoTable *pkMapInfo)
References SeRaceMgr::AddRace, SeMatchRace::akMRacePlayer, CAMP_A, SeRaceMgr::CreatEmptyRace, HTownSign::dwAreaID, SeMatchRace::dwMapID, SeMatchRace::dwMatchAreaID, SeMatchRace::dwMatchSession, SeRacePlayer::dwPlayerID, SeTeamPlayer::dwPlayerID, SeTeamPlayer::dwTeamID, SeRacePlayer::dwTeamID, SeRacePlayer::eCamp, g_kMatchServer, g_kRaceMgr, g_kTownMgr, GetCampMemberNum, GetID2Str, SeMatchRace::GetRacePlayerByID, GetRoomPlayerseat, SeTownMgr::GetTownSockBySign, SeOpenRoom::groupA, SeMatchRace::groupA, SeOpenRoom::groupB, SeMatchRace::groupB, SeMatchFightInfo::iLeagueMMR, SeMatchFightInfo::iLeagueScore, SeMatchFightInfo::iOtherLeagueScore, SeRacePlayer::iSeatIndex, SeRacePlayer::iTeamMemberNum, SeRacePlayer::kFightInfo, SeRacePlayer::kTownSign, SeTeamPlayer::kTownSign, MatchServer::loadMatchDetail, SeOpenRoom::memberPtr, SCMM_NOTIFY_LOAD_FAILED, SeLogError, SeLogInfo, SeRaceMgr::SendMatchCommMsg, MapInfoTable::uiEquipmentType, MapInfoTable::uiMapTypeID, MapInfoTable::uiMatchType.
Referenced by StartMatch.
void SeOpenRoomMgr::StartMatch(SeOpenRoom *pRoom, const MapInfoTable *pkMapInfo)
References CreateRaceInfo, SeOpenRoom::dwID, SeOpenRoom::dwRaceSession, SeOpenRoom::eState, g_kMatchServer, MatchServer::GetServerTime, m_kMID2CreateRacePtr, m_kMID2OpenRoomPtr, REPEAT_TIMER_INTERVALUE, SeOpenRoom::repeatTimerInterValue, SeTimer::SetInterValue, SMOS_CREATE_RACE.
Referenced by OnCreateRoom, OnRoomReady.
DWord SeOpenRoomMgr::GetRoomPlayerseat(SeOpenRoom *pRoom, DWord camp, const DWord playerId)
References SeOpenRoom::campSeat.
Referenced by ConvOpenRoomInfo, CreateRaceInfo, OnRoomSwitchSeat.
void SeOpenRoomMgr::ConvOpenRoomInfo(SeOpenRoomInfo &info, SeOpenRoom *pRoom)
References SeRoomMember::acName, SeOpenRoomInfo::acRoomName, SeOpenRoomInfo::akMember, SeOpenRoomInfo::bPass, SeRoomMember::byCamp, SeRoomMember::bySeat, SeOpenRoom::chPass, SeOpenRoom::chRoomName, SeOpenRoom::dwGameMode, SeOpenRoomInfo::dwGameMode, SeOpenRoom::dwID, SeOpenRoom::dwLeaderID, SeOpenRoomInfo::dwLeaderID, SeOpenRoom::dwMapID, SeOpenRoomInfo::dwMapID, SeRoomMember::dwPlayerID, SeOpenRoomInfo::dwRoomID, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, GetRoomPlayerseat, SeOpenRoomInfo::iCurrPlayerNum, MapInfoTable::iMaxPlayer, SeOpenRoomInfo::iMaxPlayerNum, SeOpenRoomInfo::iNum, SeOpenRoom::memberPtr, SeLogError, StrCpy.
Referenced by OnCreateRoom, OnQueryRoomList, SendRoomJoinRet.
void SeOpenRoomMgr::FindRoomEmptySeat(SeOpenRoom *pRoom, const MapInfoTable *pkMapInfo, DWord &camp, DWord &seat)
References SeOpenRoom::campSeat, SeOpenRoom::iCampPlayerNum, SRPC_CAMPA.
Referenced by OnRoomInviteRspOk, OnRoomJoin.
void SeOpenRoomMgr::SendRoomJoinRet(const HTownSign &rkTownSign, const DWord playerID, SeOpenRoom *pRoom, const SeRoomJoinRetType etype)
References ConvOpenRoomInfo, g_kMatchServer, g_kTownMgr, SeTownMgr::GetTownSockBySign, MatchServer::SendMT_MatchRoomJoinRet.
Referenced by OnRoomInviteRspOk, OnRoomJoin.
void SeOpenRoomMgr::SendRoomNotify(const DWord selfPlayerID, SeOpenRoom *pRoom, const SeRoomNtfCode etype, SeRoomMember &memberInfo, bool bAllSync=false)
References SeOpenRoom::dwID, SeOpenRoom::dwLeaderID, g_kMatchServer, g_kTownMgr, SeTownMgr::GetTownSockBySign, SeOpenRoom::memberPtr, MatchServer::SendMT_MatchRoomMemberNotifyRet.
Referenced by OnRoomInviteRspOk, OnRoomJoin, OnRoomKickSomeone, OnRoomLeave, OnRoomSwitchSeat.
int SeOpenRoomMgr::GetValidateSeat(SeOpenRoom *pRoom, const MapInfoTable *pkMapInfo, DWord &camp, DWord &seat)
References SeOpenRoom::iCampPlayerNum, MapInfoTable::iMaxPlayer, SRPC_CAMPA.
void SeOpenRoomMgr::DelRoom(SeOpenRoom *pRoom)
References m_kPlayerID2OpenRoomPtr, SeOpenRoom::memberPtr, SeLogInfo.
Referenced by Update.
SeOpenRoomMgr::SeOpenRoomMgr()
void SeOpenRoomMgr::Update(DWord dwTime)
uint32_t SeOpenRoomMgr::GetGenID()
void SeOpenRoomMgr::OnCreateRoom(const HTownSign &rkTownSign, SeTM_MatchCreateRoom &rkCreateRoom, bool bSysCreate)
void SeOpenRoomMgr::OnQueryRoomList(const HTownSign &rkTownSign, const SeTM_MatchQueryRoomList &rkRoom)
void SeOpenRoomMgr::OnRoomJoin(const HTownSign &rkTownSign, SeTM_MatchRoomJoin &rkJoin)
void SeOpenRoomMgr::OnRoomLeave(const HTownSign &rkTownSign, const SeTM_MatchRoomLeave &rkleave)
void SeOpenRoomMgr::OnRoomSwitchSeat(const HTownSign &rkTownSign, const SeTM_MatchRoomSwitchSeat &rkswitch)
void SeOpenRoomMgr::OnRoomKickSomeone(const HTownSign &rkTownSign, const SeTM_MatchRoomKickSomeone &rkKick)
void SeOpenRoomMgr::OnRoomInvite(const HTownSign &rkTownSign, const SeTM_MatchRoomInvite &rkInvite)
void SeOpenRoomMgr::OnRoomInviteRspOk(const HTownSign &rkTownSign, const SeTM_MatchRoomInviteRsp &rkinviteOk)
void SeOpenRoomMgr::OnRoomReady(const HTownSign &rkTownSign, const SeTM_MatchRoomReady &rkReady)
void SeOpenRoomMgr::OnPlayerLeave(const HTownSign &rkTownSign, DWord dwPlayerID, DWord dwDelID)
int SeOpenRoomMgr::GetCampMemberNum(DWord dwCamp, SeOpenRoom *pRoom)
DWord SeOpenRoomMgr::CreateRaceInfo(SeOpenRoom *pRoom, const MapInfoTable *pkMapInfo)
void SeOpenRoomMgr::StartMatch(SeOpenRoom *pRoom, const MapInfoTable *pkMapInfo)
DWord SeOpenRoomMgr::GetRoomPlayerseat(SeOpenRoom *pRoom, DWord camp, const DWord playerId)
void SeOpenRoomMgr::ConvOpenRoomInfo(SeOpenRoomInfo &info, SeOpenRoom *pRoom)
void SeOpenRoomMgr::FindRoomEmptySeat(SeOpenRoom *pRoom, const MapInfoTable *pkMapInfo, DWord &camp, DWord &seat)
void SeOpenRoomMgr::SendRoomJoinRet(const HTownSign &rkTownSign, const DWord playerID, SeOpenRoom *pRoom, const SeRoomJoinRetType etype)
void SeOpenRoomMgr::SendRoomNotify(const DWord selfPlayerID, SeOpenRoom *pRoom, const SeRoomNtfCode etype, SeRoomMember &memberInfo, bool bAllSync=false)
int SeOpenRoomMgr::GetValidateSeat(SeOpenRoom *pRoom, const MapInfoTable *pkMapInfo, DWord &camp, DWord &seat)
void SeOpenRoomMgr::DelRoom(SeOpenRoom *pRoom)