SeMatchMgr
PlayerType
PlayerType
typedef std::multimap<moba::TimeType, MatchItem *> SeMatchMgr::TIMEMAP
以时间为key.
typedef std::multimap<double, MatchItem *> SeMatchMgr::LEVELMAP
以等级为key.
typedef std::map<uint32_t, MatchItem *> SeMatchMgr::USERMAP
以用户ID为key.
typedef std::map<MatchIndex, LEVELMAP > SeMatchMgr::TYPEMAP
typedef std::map<uint32_t, WaitItem *> SeMatchMgr::WAITMAP
typedef std::multimap<moba::TimeType, MatchItem *> SeMatchMgr::TIMEMAP
以时间为key.
typedef std::multimap<double, MatchItem *> SeMatchMgr::LEVELMAP
以等级为key.
typedef std::map<uint32_t, MatchItem *> SeMatchMgr::USERMAP
以用户ID为key.
typedef std::map<MatchIndex, LEVELMAP > SeMatchMgr::TYPEMAP
typedef std::map<uint32_t, WaitItem *> SeMatchMgr::WAITMAP
TIMEMAP SeMatchMgr::m_timeMap
Referenced by match, OnMatchReq, rejoinMatch, removeMatch, Update.
TYPEMAP SeMatchMgr::m_typeMap
Referenced by match, OnMatchReq, rejoinMatch, removeMatch.
USERMAP SeMatchMgr::m_userMap
Referenced by clearMatch, OnMatchCancel, OnMatchReq, OnPlayerLeave.
WAITMAP SeMatchMgr::m_waitMap
Referenced by addWaitRoom, OnConfirm, UpdateRoom.
SeMatchMgr::SeMatchMgr()
SeMatchMgr::~SeMatchMgr()
void SeMatchMgr::Update()
References moba::Clock::getInstance, moba::Clock::getMilliSeconds, m_timeMap, match, UpdateRoom.
Referenced by MatchServer::Update.
MatchReqResult SeMatchMgr::OnMatchReq(DWord mapid, Byte seats, const std::list< MatchValueStru > &matchValues, const std::list< HTownSign > &towns)
References SeMatchMgr::PlayerInfo::acName, SeMatchMgr::PlayerInfo::BoolConfirmed, SeMatchMgr::MatchItem::calForce, SeMatchMgr::PlayerInfo::defeat, SeMatchMgr::PlayerInfo::dwPlayerID, EMT_LADDER, MatchIndex::entertainment, SeMatchMgr::MatchItem::entertainment, SeMatchMgr::MatchItem::ePlayerType, SeMatchMgr::MatchItem::force, g_kTownMgr, MapInfoTableMgr::Get, moba::Clock::getInstance, MapInfoTableMgr::GetMapInfoTable, getMatchRules, moba::Clock::getMilliSeconds, getPlayerType, SeTownMgr::GetTown, SeMatchMgr::MatchItem::itLevel, SeMatchMgr::MatchItem::itTime, SeMatchMgr::PlayerInfo::kTownSign, SeMatchMgr::PlayerInfo::level, SeMatchMgr::MatchItem::level, m_timeMap, m_typeMap, m_userMap, SeMatchMgr::MatchItem::mapID, MATCH_STATUS_MATCHING, SeMatchMgr::PlayerInfo::matchNum, SeMatchMgr::MatchItem::matchstatus, SeMatchMgr::MatchItem::matchTime, SeMatchMgr::MatchItem::matchTimes, SeMatchMgr::MatchItem::matchType, MatchRule::maxFunc, SeMatchMgr::MatchItem::maxLevel, MatchRule::minFunc, SeMatchMgr::MatchItem::minLevel, MatchRule::param, SeMatchMgr::MatchItem::players, PT_NEW, ReqResultInnerError, ReqResultOffline, ReqResultSuccess, ReqResultWrongNum, ReqResultWrongStatus, SeMatchMgr::PlayerInfo::score, SeMatchMgr::MatchItem::seats, SeLogDebug, StrCpy, MatchIndex::uiMapID, MapInfoTable::uiMatchType.
Referenced by MatchPrepareMgr::onDataResult.
MatchCancelResult SeMatchMgr::OnMatchCancel(DWord dwPlayerID)
References CancelResultInBattle, CancelResultNotQueue, CancelResultSuccess, clearMatch, g_kMatchServer, g_kTownMgr, SeTownMgr::GetTownSockBySign, m_userMap, MATCH_STATUS_MATCHING, SeMatchMgr::MatchItem::matchstatus, SeMatchMgr::MatchItem::players, removeMatch, MatchServer::SendMT_MatchCancelRep.
Referenced by OnPlayerLeave, MatchServer::ProcessTM_PlayerMatchCancel.
void SeMatchMgr::OnBattleOver(SeRacePlayer &player)
Referenced by SeRaceMgr::DoRaceOver.
void SeMatchMgr::OnConfirm(uint32_t uiPlayerID, uint32_t uiWaiID, bool bolConfirm)
References MatchBanMgr::banPlayer, clearMatch, g_kMatchBanMgr, g_kMatchServer, g_kTownMgr, SeMatchMgr::WaitItem::getConfirm, SeTownMgr::GetTownSockBySign, m_waitMap, openRoom, rejoinMatch, MatchServer::SendMT_NotiMatcherResult, MatchServer::SendMT_SingleMatchConfirm, SeMatchMgr::WaitItem::setConfirm, SeMatchMgr::WaitItem::teams.
Referenced by OnPlayerLeave, MatchServer::ProcessTM_MatchConfirm.
void SeMatchMgr::OnPlayerLeave(DWord dwPlayerID)
References SeMatchMgr::MatchItem::dwWaitID, m_userMap, MATCH_STATUS_MATCHING, SeMatchMgr::MatchItem::matchstatus, OnConfirm, OnMatchCancel.
Referenced by MatchServer::ProcessTM_PlayerLeave.
SeMatchMgr::SeMatchMgr()
SeMatchMgr::~SeMatchMgr()
void SeMatchMgr::Update()
MatchReqResult SeMatchMgr::OnMatchReq(DWord mapid, Byte seats, const std::list< MatchValueStru > &matchValues, const std::list< HTownSign > &towns)
MatchCancelResult SeMatchMgr::OnMatchCancel(DWord dwPlayerID)
void SeMatchMgr::OnBattleOver(SeRacePlayer &player)
void SeMatchMgr::OnConfirm(uint32_t uiPlayerID, uint32_t uiWaiID, bool bolConfirm)
void SeMatchMgr::OnPlayerLeave(DWord dwPlayerID)
void SeMatchMgr::UpdateRoom()
References MatchBanMgr::banPlayer, clearMatch, g_kMatchBanMgr, g_kMatchServer, g_kTownMgr, moba::Clock::getInstance, moba::Clock::getMilliSeconds, SeTownMgr::GetTownSockBySign, m_waitMap, rejoinMatch, MatchServer::SendMT_NotiMatcherResult, SeMatchMgr::WaitItem::startTime, SeMatchMgr::WaitItem::teams.
Referenced by Update.
void SeMatchMgr::match(MatchItem *item)
匹配
References addWaitRoom, SeMatchConfig::bMatchTimeoutRobot, MatchIndex::entertainment, SeMatchMgr::MatchItem::entertainment, SeMatchMgr::MatchItem::ePlayerType, g_kMatchServer, MapInfoTableMgr::Get, MatchServer::GetConfig, MapInfoTableMgr::GetMapInfoTable, getMatchRules, SeMatchMgr::MatchItem::itLevel, SeMatchMgr::MatchItem::itTime, SeMatchMgr::MatchItem::level, m_timeMap, m_typeMap, SeMatchMgr::MatchItem::mapID, SeMatchMgr::MatchItem::matchTime, SeMatchMgr::MatchItem::matchTimes, SeMatchMgr::MatchItem::matchType, MatchRule::maxFunc, SeMatchMgr::MatchItem::maxLevel, MatchRule::minFunc, SeMatchMgr::MatchItem::minLevel, MatchRule::ms, MatchRule::param, SeMatchMgr::MatchItem::players, PT_NOVICE, SeMatchMgr::MatchItem::seats, SeLogDebug, MatchIndex::uiMapID.
Referenced by Update.
bool SeMatchMgr::match(MatchItem *item, std::multimap< double, MatchItem * > *matchArray, std::list< MatchItem * > &groupA, std::list< MatchItem * > &groupB)
References CombinationItem::combination, SeMatchMgr::MatchItem::entertainment, getMatchItems, SeMatchMgr::MatchItem::matchTimes, SeMatchMgr::MatchItem::onlyMatchFriend, SeMatchMgr::MatchItem::players, SeMatchMgr::MatchItem::seats, CombinationItem::size, TURN_FALSE_FORCE_GAME.
bool SeMatchMgr::getMatchItems(int *counts, std::multimap< double, MatchItem * > *matchArray, std::list< MatchItem * > &group)
从数组中获得指定数量的条目
References SeLogDebug.
Referenced by match.
void SeMatchMgr::addWaitRoom(const std::list< MatchItem * > &groupA, const std::list< MatchItem * > &groupB)
加入到等待房间
References g_kMatchServer, g_kTownMgr, moba::Clock::getInstance, moba::Clock::getMilliSeconds, SeTownMgr::GetTownSockBySign, SeMatchMgr::WaitItem::groupA, SeMatchMgr::WaitItem::groupB, m_waitMap, MATCH_STATUS_INRACE, removeMatch, SeLogDebug, MatchServer::SendMT_NotiMatcherPre, SeMatchMgr::WaitItem::startTime, SeMatchMgr::WaitItem::teams, SeMatchMgr::WaitItem::uiMapID, SeMatchMgr::WaitItem::uiWaitID, WAITSTATUSWAIT, SeMatchMgr::WaitItem::ws.
Referenced by match.
void SeMatchMgr::removeMatch(MatchItem *item)
References MatchIndex::entertainment, SeMatchMgr::MatchItem::entertainment, SeMatchMgr::MatchItem::itLevel, SeMatchMgr::MatchItem::itTime, m_timeMap, m_typeMap, SeMatchMgr::MatchItem::mapID, MatchIndex::uiMapID.
Referenced by addWaitRoom, OnMatchCancel.
void SeMatchMgr::clearMatch(MatchItem *item)
References m_userMap, SeMatchMgr::MatchItem::players.
Referenced by OnConfirm, OnMatchCancel, UpdateRoom.
void SeMatchMgr::rejoinMatch(MatchItem *item)
References MatchIndex::entertainment, SeMatchMgr::MatchItem::entertainment, moba::Clock::getInstance, getMatchRules, moba::Clock::getMilliSeconds, SeMatchMgr::MatchItem::itLevel, SeMatchMgr::MatchItem::itTime, SeMatchMgr::MatchItem::level, m_timeMap, m_typeMap, SeMatchMgr::MatchItem::mapID, MATCH_STATUS_MATCHING, SeMatchMgr::MatchItem::matchstatus, SeMatchMgr::MatchItem::matchTime, SeMatchMgr::MatchItem::matchTimes, SeMatchMgr::MatchItem::matchType, MatchRule::maxFunc, SeMatchMgr::MatchItem::maxLevel, MatchRule::minFunc, SeMatchMgr::MatchItem::minLevel, MatchRule::ms, MatchRule::param, SeMatchMgr::MatchItem::players, MatchIndex::uiMapID.
Referenced by OnConfirm, UpdateRoom.
void SeMatchMgr::openRoom(WaitItem *item)
References SeTeamPlayer::acName, SeOpenRoom::bPlayBoss, SeOpenRoom::bSysCreate, SeOpenRoom::bUseRobot, CAMP_A, CAMP_B, CAMP_SIZE, SeOpenRoom::campSeat, SeOpenRoom::dwID, SeTeamPlayer::dwJoinTime, SeOpenRoom::dwLeaderID, SeOpenRoom::dwMapID, SeTeamPlayer::dwPlayerID, SeTeamPlayer::dwTeamID, g_kMatchServer, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, MatchServer::GetServerTime, SeOpenRoom::groupA, SeMatchMgr::WaitItem::groupA, SeOpenRoom::groupB, SeMatchMgr::WaitItem::groupB, MapInfoTable::iCampNum, SeOpenRoom::iCampPlayerNum, SeOpenRoom::iDifficulty, MapInfoTable::iMaxPlayer, SeTeamPlayer::kTownSign, SeOpenRoom::memberPtr, SeLogDebug, SeOpenRoomMgrInst, StrCpy, SeMatchMgr::WaitItem::uiMapID, SeMatchMgr::WaitItem::uiWaitID.
Referenced by OnConfirm.
void SeMatchMgr::UpdateRoom()
void SeMatchMgr::match(MatchItem *item)
匹配
bool SeMatchMgr::match(MatchItem *item, std::multimap< double, MatchItem * > *matchArray, std::list< MatchItem * > &groupA, std::list< MatchItem * > &groupB)
bool SeMatchMgr::getMatchItems(int *counts, std::multimap< double, MatchItem * > *matchArray, std::list< MatchItem * > &group)
从数组中获得指定数量的条目
void SeMatchMgr::addWaitRoom(const std::list< MatchItem * > &groupA, const std::list< MatchItem * > &groupB)
加入到等待房间
void SeMatchMgr::removeMatch(MatchItem *item)
void SeMatchMgr::clearMatch(MatchItem *item)
void SeMatchMgr::rejoinMatch(MatchItem *item)
void SeMatchMgr::openRoom(WaitItem *item)
SeMatchMgr::PlayerType SeMatchMgr::getPlayerType(MatchType eMatchType, const PlayerInfo &info)
References PT_NORMAL.
Referenced by getPlayerType, OnMatchReq.
SeMatchMgr::PlayerType SeMatchMgr::getPlayerType(const MatchItem &item)
References MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, getPlayerType, SeMatchMgr::MatchItem::mapID, SeMatchMgr::MatchItem::players, PT_NEW, MapInfoTable::uiMatchType.
static PlayerType SeMatchMgr::getPlayerType(MatchType eMatchType, const PlayerInfo &info)
static PlayerType SeMatchMgr::getPlayerType(const MatchItem &item)