PlayerDataMgr
PlayerDataStrategy
std::map< SeDBTableIndex, PlayerDataStrategy * > PlayerDataMgr::m_strategies
Referenced by fixData, getStrategy, initGenID, initialize, loadData, rebuildMem, safeDeleteDBPlayer, saveToDB.
std::set< SeDBTableIndex > PlayerDataMgr::m_initGenIDTables
Referenced by initGenID, isGenIDFinished, onInitGenIDRet.
void PlayerDataMgr::initialize()
References getInitList, m_strategies.
Referenced by DBServer::InitDBMem, WorldServer::Initialize.
DWord PlayerDataMgr::getCacheInitID(SeDBTableIndex eTableIndex)
References PlayerDataStrategy::getCacheInitID, getStrategy.
Referenced by DBServer::SendDB_InitGenID.
bool PlayerDataMgr::getInitGenIDSql(SeDBTableIndex eTableIndex, char *sql, int size)
References PlayerDataStrategy::getInitGenIDSql, getStrategy.
Referenced by DBServer::SendDB_InitGenID.
void PlayerDataMgr::setRebuildMemData(SeDBTableIndex eTableIndex, void *data)
References getStrategy, PlayerDataStrategy::setRebuildMemData.
void PlayerDataMgr::rebuildMem()
References m_strategies.
Referenced by DBServer::RebuildMem.
int PlayerDataMgr::saveToDB(SeDBPlayer &player)
References m_strategies.
Referenced by SeDBPlayerMgr::SaveToDB.
bool PlayerDataMgr::dataInsert(SeDBTableIndex eTableIndex, SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
References PlayerDataStrategy::dataInsert, getStrategy.
Referenced by SeDBPlayerMgr::DataInsert.
bool PlayerDataMgr::dataUpdate(SeDBTableIndex eTableIndex, SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
References PlayerDataStrategy::dataUpdate, getStrategy.
Referenced by SeDBPlayerMgr::DataUpdate.
bool PlayerDataMgr::dataDelete(SeDBTableIndex eTableIndex, SeDBPlayer &player, uint64_t dwlID)
References PlayerDataStrategy::dataDelete, getStrategy.
Referenced by SeDBPlayerMgr::DataDelete.
void PlayerDataMgr::loadData(SeDBPlayer &player)
References m_strategies.
Referenced by BlockServer::ProcessBBL_PlayerLoadRet, DBServer::SendDB_LoadInfo.
void PlayerDataMgr::onLoadData(SeDBTableIndex eTableIndex, SeDBPlayer &player, TeDBResSet &rkResSet)
References getStrategy, PlayerDataStrategy::onLoadData.
Referenced by onLoadCharData, BlockServer::ProcessBBL_SelectDataRet.
bool PlayerDataMgr::getRecordCount(SeDBTableIndex eTableIndex, SeDBPlayer &player, int &count)
References PlayerDataStrategy::getRecordCount, getStrategy.
Referenced by DBServer::GetPlayerRecordCount.
bool PlayerDataMgr::getFieldData(SeDBTableIndex eTableIndex, SeDBPlayer &player, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1, void *&ret)
References PlayerDataStrategy::getFieldData, getStrategy.
Referenced by DBServer::GetPlayerFieldData.
int PlayerDataMgr::safeDeleteDBPlayer(SeDBPlayer &player, DWord dwMagic)
References m_strategies.
Referenced by SeDBPlayerMgr::SafeDeleteDBPlayer.
void PlayerDataMgr::initialize()
DWord PlayerDataMgr::getCacheInitID(SeDBTableIndex eTableIndex)
bool PlayerDataMgr::getInitGenIDSql(SeDBTableIndex eTableIndex, char *sql, int size)
void PlayerDataMgr::setRebuildMemData(SeDBTableIndex eTableIndex, void *data)
void PlayerDataMgr::rebuildMem()
int PlayerDataMgr::saveToDB(SeDBPlayer &player)
bool PlayerDataMgr::dataInsert(SeDBTableIndex eTableIndex, SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
bool PlayerDataMgr::dataUpdate(SeDBTableIndex eTableIndex, SeDBPlayer &player, uint64_t dwlID, DWord dwParam1, int iIndex, void *pkData)
bool PlayerDataMgr::dataDelete(SeDBTableIndex eTableIndex, SeDBPlayer &player, uint64_t dwlID)
void PlayerDataMgr::loadData(SeDBPlayer &player)
void PlayerDataMgr::onLoadData(SeDBTableIndex eTableIndex, SeDBPlayer &player, TeDBResSet &rkResSet)
bool PlayerDataMgr::getRecordCount(SeDBTableIndex eTableIndex, SeDBPlayer &player, int &count)
bool PlayerDataMgr::getFieldData(SeDBTableIndex eTableIndex, SeDBPlayer &player, SeFieldFormat eFormat, int iIndex, int iCount, uint64_t dwlID, DWord dwPara1, void *&ret)
int PlayerDataMgr::safeDeleteDBPlayer(SeDBPlayer &player, DWord dwMagic)
void PlayerDataMgr::initialize()
void PlayerDataMgr::initGenID()
References m_initGenIDTables, m_strategies.
Referenced by WorldServer::ProcessBW_RegisterRet.
void PlayerDataMgr::onInitGenIDRet(SeDBTableIndex eTableIndex, DWord dwGenID)
References getStrategy, PlayerDataStrategy::getTableIndex, m_initGenIDTables, PlayerDataStrategy::setGenID.
Referenced by WorldServer::ProcessBW_InitGenIDRet.
bool PlayerDataMgr::isGenIDFinished()
References m_initGenIDTables.
Referenced by WorldServer::Update.
void PlayerDataMgr::loadData(SePlayer &player)
References m_strategies.
void PlayerDataMgr::onLoadData(SeDBTableIndex eTableIndex, SePlayer &player, SeBBL_SelectDataRet *pkData)
References getStrategy, PlayerDataStrategy::onLoadData.
void PlayerDataMgr::fixData(SePlayer &player)
References m_strategies.
Referenced by SePlayer::LoadingComplete.
void PlayerDataMgr::initialize()
void PlayerDataMgr::initGenID()
void PlayerDataMgr::onInitGenIDRet(SeDBTableIndex eTableIndex, DWord dwGenID)
bool PlayerDataMgr::isGenIDFinished()
void PlayerDataMgr::loadData(SePlayer &player)
void PlayerDataMgr::onLoadData(SeDBTableIndex eTableIndex, SePlayer &player, SeBBL_SelectDataRet *pkData)
void PlayerDataMgr::fixData(SePlayer &player)
PlayerDataStrategy * PlayerDataMgr::getStrategy(SeDBTableIndex eTableIndex)
References m_strategies.
Referenced by dataDelete, dataInsert, dataUpdate, getCacheInitID, getFieldData, getInitGenIDSql, getRecordCount, onInitGenIDRet, onLoadData, setRebuildMemData.
PlayerDataStrategy* PlayerDataMgr::getStrategy(SeDBTableIndex eTableIndex)
PlayerDataStrategy* PlayerDataMgr::getStrategy(SeDBTableIndex eTableIndex)
PlayerDataStrategy* PlayerDataMgr::getStrategy(SeDBTableIndex eTableIndex)
std::list< PlayerDataStrategy * > & PlayerDataMgr::getInitList()
Referenced by initialize, PlayerDataStrategy::PlayerDataStrategy.
static std::list<PlayerDataStrategy *>& PlayerDataMgr::getInitList()
static std::list<PlayerDataStrategy *>& PlayerDataMgr::getInitList()
static std::list<PlayerDataStrategy *>& PlayerDataMgr::getInitList()