CItemMgr
typedef std::map<uint16_t, CItem*> CItemMgr::ITEMMAP
typedef ITEMMAP::iterator CItemMgr::ITEMIT
typedef std::map<uint16_t, CItem*> CItemMgr::ITEMMAP
typedef ITEMMAP::iterator CItemMgr::ITEMIT
ITEMMAP CItemMgr::m_BagMap
Referenced by AddItem, AddNewMultiItem, ChangeCiTiao, clearItemNewFlag, CountNeedSlotNumByItemID, decRespawnItem, DeleteItem, doItemMergeCharge, eraseItem, GetEmpySlotIndex, GetExistItemIndex, getItem, GetItemCountByID, getRespawnItemCount, getSelectableAvatars, insertItem, ItemDepart, loadData, openRandBox, PackAllItem, StrenthEquip, ~CItemMgr.
std::map< DWord, CItem * > CItemMgr::m_idMap
Referenced by eraseItem, getItem, insertItem.
SePlayer * CItemMgr::m_pOwner
Referenced by CItemMgr, GetOwner, SetOwner.
uint32_t CItemMgr::m_uiTimer
Referenced by CItemMgr, Update.
CItemMgr::CItemMgr()
References m_pOwner, m_uiTimer.
CItemMgr::~CItemMgr()
References m_BagMap.
void CItemMgr::loadData(const SeDBCharItem &obj)
References TownItemTableMgr::Get, TownItemTableMgr::GetTownItemTable, insertItem, CItem::load, m_BagMap, SeLogWarning, CItem::ucIndex, CItem::uiID, CItem::uiItemID.
void CItemMgr::PackAllItem()
References g_kWorldServer, GetID, GetOwner, GetTownSock, SeWT_PlayerNewItem::iNum, m_BagMap, SeWT_PlayerNewItem::SeItemArray, WorldServer::SendWT_PlayerNewItem.
Referenced by SePlayer::OperateLoading.
void CItemMgr::Update(DWord dwCurTime)
References GetOwner, m_uiTimer.
Referenced by SePlayer::Update.
uint32_t CItemMgr::GetItemCountByID(uint32_t uiItemID)
References m_BagMap.
Referenced by CShop::BuyItem, CheckOwnerItem, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold.
void CItemMgr::SetOwner(SePlayer *pOwner)
References m_pOwner.
Referenced by SePlayer::SePlayer.
SePlayer* CItemMgr::GetOwner()
References m_pOwner.
Referenced by AddItem, ChangeCiTiao, DeleteItem, doExchangeItem, doItemMergeCharge, doMoveItem, ItemDepart, notiChangeItem, openRandBox, PackAllItem, StrenthEquip, Update.
SeItemResult CItemMgr::StrenthEquip(Word SrcPos, int32_t iNum, Word DstPos[])
References CItem::addedLevel, AddStrenAttr, CheckEnough, doItemMergeCharge, StrengthenTable::fStrResult1, StrengthenTable::fStrResult2, StrengthenTable::fStrResult3, StrengthenTable::fStrResult4, StrengthenTable::fStrResult5, StrengthenTable::fStrResult6, StrengthenTable::fStrResult7, StrengthenTable::fStrResult8, StrengthenTableMgr::Get, TownItemTableMgr::Get, GetGold, GetOwner, StrengthenTableMgr::GetStrengthenTable, TownItemTableMgr::GetTownItemTable, StrengthenTable::iCostMoney, TownItemTable::iitemlevelmax, StrengthenTable::iStrStoneNum1, StrengthenTable::iStrStoneNum2, StrengthenTable::iSuccessRate, ITEM_DST_INDEX_ERROR, ITEM_DST_ITEM_NOT_FOUND, ITEM_NOT_ENOUGH_MONEY, ITEM_OPER_MOD, ITEM_RESULT_SUCCESS, ITEM_SERVER_INNER_ERROR, ITEM_SRC_DST_ISSAME, ITEM_SRC_INDEX_ERROR, ITEM_SRC_ITEM_NOT_FOUND, ITEM_SRC_NOT_EQUIP, ITEM_SRC_WRONG_NUM, ITEM_STRENTH_HIGH_LEVEL, ITEM_STRENTH_NO_STRENTHID, ITEM_STRENTH_NOT_ENOUGH_SRC, ITEM_STRENTH_PROBABLITY_FAIL, ITEM_STRENTH_SRC_REPEATED, m_BagMap, SeLogInfo, CItem::SetOper, TOWNITEM_CLASS_ZHUANGBEI, TownItemTable::uiClass, CItem::uiItemID, TownItemTable::uiLevel, StrengthenTable::uiStrProperty1, StrengthenTable::uiStrProperty2, StrengthenTable::uiStrProperty3, StrengthenTable::uiStrProperty4, StrengthenTable::uiStrProperty5, StrengthenTable::uiStrProperty6, StrengthenTable::uiStrProperty7, StrengthenTable::uiStrProperty8, StrengthenTable::uiStrStoneID1, StrengthenTable::uiStrStoneID2, TownItemTable::uiSubClass.
Referenced by BlockServer::ProcessTBL_ReqItemStrenth.
SeItemResult CItemMgr::ChangeCiTiao(Word SrcPos, uint32_t iCiTiaoIndex, uint32_t uiNum, bool bLock, Word SrcPosArray[])
References CheckEnough, doItemMergeCharge, FreshSkill, AppendCostTableMgr::Get, TownItemTableMgr::Get, AppendCostTableMgr::GetAppendCostTableVec, SePlayer::GetGold, TableResArray::getObjectAt, GetOwner, TableResArray::getSize, TownItemTableMgr::GetTownItemTable, ITEM_DST_INDEX_ERROR, ITEM_DST_ITEM_NOT_FOUND, ITEM_FRESHITEM_NOTEXIST, ITEM_FRESHITEM_WRONG_INDEX, ITEM_NOT_ENOUGH_MONEY, ITEM_OPER_MOD, ITEM_RESULT_FRESH_SRC_NOTENOUGH, ITEM_RESULT_SUCCESS, ITEM_RESULT_TABLE_ERROR, ITEM_SERVER_INNER_ERROR, ITEM_SRC_DST_ISSAME, ITEM_SRC_INDEX_ERROR, ITEM_SRC_ITEM_NOT_FOUND, ITEM_SRC_NOT_EQUIP, ITEM_SRC_WRONG_NUM, ITEM_STRENTH_SRC_REPEATED, m_BagMap, SeLogInfo, SSD_MAX_ATTR_NUM, TOWNITEM_CLASS_ZHUANGBEI, TownItemTable::uiClass, TownItemTable::uiLevel.
Referenced by BlockServer::ProcessTBL_ReqItemCiTiaoChange.
SeItemResult CItemMgr::AddNewMultiItem(const std::list< DeposeStru > &itemlist, std::list< CItem * > &items)
References CItem::addedLevel, CItem::dwNewFlag, g_kCharItemStrategy, GenerateAddedAttr, GenerateAddedSkill, TownItemTableMgr::Get, GetEmpySlotIndex, PlayerDataStrategy::getGenID, TownItemTableMgr::GetTownItemTable, insertItem, TownItemTable::iPileCount, ITEM_BAG_SLOT_ISNOT_ENOUGH, ITEM_DST_ITEM_NOT_FOUND, ITEM_OPER_INSERT, ITEM_OPER_MOD, ITEM_RESULT_SUCCESS, CItem::LostTime, m_BagMap, SeLogInfo, CItem::SetOper, SSD_BAG_ITEM_NUM, TOWNITEM_CLASS_ZHUANGBEI, CItem::ucIndex, TownItemTable::uiClass, CItem::uiID, CItem::uiItemID, CItem::uiOverLap.
Referenced by AddItem, ItemDepart, openRandBox.
SeItemResult CItemMgr::ItemDepart(Word DstPos)
References AddNewMultiItem, CountNeedSlotNumByItemID, DeposeStru::dwItemID, DeposeStru::dwNum, eraseItem, DecomposeTableMgr::Get, TownItemTableMgr::Get, DecomposeTableMgr::GetDecomposeTableVec, TableResArray::getObjectAt, GetOwner, TableResArray::getSize, TownItemTableMgr::GetTownItemTable, DecomposeTable::iItemCount1, DecomposeTable::iItemCount2, DecomposeTable::iItemCount3, DecomposeTable::iItemCount4, DecomposeTable::iItemCount5, ITEM_BAG_SLOT_ISNOT_ENOUGH, ITEM_OPER_DEL, ITEM_RESULT_SUCCESS, ITEM_RESULT_TABLE_ERROR, ITEM_SERVER_INNER_ERROR, ITEM_SRC_INDEX_ERROR, ITEM_SRC_ITEM_NOT_FOUND, ITEM_SRC_NOT_EQUIP, m_BagMap, notiChangeItem, SeLogInfo, SSD_BAG_ITEM_NUM, TOWNITEM_CLASS_ZHUANGBEI, TownItemTable::uiClass, DecomposeTable::uiDecomposeItem1, DecomposeTable::uiDecomposeItem2, DecomposeTable::uiDecomposeItem3, DecomposeTable::uiDecomposeItem4, DecomposeTable::uiDecomposeItem5, TownItemTable::uiLevel, DecomposeTable::uiQualityType.
Referenced by BlockServer::ProcessTBL_ReqItemDepart.
uint16_t CItemMgr::GetExistItemIndex(uint32_t ItemID, uint32_t &itemcount)
References TownItemTableMgr::Get, TownItemTableMgr::GetTownItemTable, TownItemTable::iPileCount, m_BagMap, SeLogInfo, SSD_BAG_ITEM_NUM.
uint16_t CItemMgr::CountNeedSlotNumByItemID(DeposeStru &item)
References DeposeStru::dwItemID, DeposeStru::dwNum, TownItemTableMgr::Get, TownItemTableMgr::GetTownItemTable, TownItemTable::iPileCount, m_BagMap, SSD_BAG_ITEM_NUM.
Referenced by AddItem, ItemDepart, openRandBox.
SeItemResult CItemMgr::AddItem(uint32_t ItemID, int32_t num)
References AddNewMultiItem, CountNeedSlotNumByItemID, DeposeStru::dwItemID, DeposeStru::dwNum, TownItemTableMgr::Get, GetOwner, SePlayer::getTaskMgr, TownItemTableMgr::GetTownItemTable, TownItemTable::iPileCount, ITEM_BAG_SLOT_ISNOT_ENOUGH, ITEM_DST_ITEM_NOT_FOUND, ITEM_RESULT_SUCCESS, ITEM_RESULT_TABLE_ERROR, m_BagMap, notiChangeItem, TaskMgr::SettleTask, SSD_BAG_ITEM_NUM, TASKINFO_CONDITON_JIESUOPIFU, TOWNITEM_CLASS_PIFU, TownItemTable::uiClass.
Referenced by CShop::BuyItem, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold, TaskMgr::GetTaskReward, HeroMgr::processAddHeroBindItem, BlockServer::ProcessRBL_AwardItemNtf, BlockServer::ProcessTBL_GMAddItem.
SeItemResult CItemMgr::DeleteItem(Word dstpos)
References eraseItem, GetOwner, ITEM_DST_INDEX_ERROR, ITEM_OPER_DEL, ITEM_RESULT_SUCCESS, ITEM_SERVER_INNER_ERROR, m_BagMap, notiChangeItem.
Referenced by BlockServer::ProcessTBL_DelelteItem.
SeItemResult CItemMgr::openRandBox(Word wPos, std::vector< SeRandBoxItem > &boxItems)
References AddNewMultiItem, CountNeedSlotNumByItemID, SeRandBoxItem::dwItemID, SeRandBoxItem::dwNum, eraseItem, g_kResMgr, TownItemTableMgr::Get, GetOwner, TownItemTableMgr::GetTownItemTable, ITEM_BAG_SLOT_ISNOT_ENOUGH, ITEM_NOT_RANDBOX, ITEM_OPER_DEL, ITEM_OPER_MOD, ITEM_RESULT_SUCCESS, ITEM_RESULT_TABLE_ERROR, ITEM_SERVER_INNER_ERROR, ITEM_SRC_INDEX_ERROR, ITEM_SRC_ITEM_NOT_FOUND, m_BagMap, notiChangeItem, SeLogInfo, CItem::SetOper, SSD_BAG_ITEM_NUM, TOWNITEM_CLASS_BAOXIANG, TownItemTable::uiClass, CItem::uiItemID, CItem::uiOverLap.
Referenced by BlockServer::ProcessTBL_OpenRandBox.
SeItemResult CItemMgr::clearItemNewFlag(int iNum, Word PosArray[])
References CItem::dwNewFlag, ITEM_OPER_MOD, ITEM_RESULT_SUCCESS, ITEM_SRC_INDEX_ERROR, m_BagMap, notiChangeItem.
Referenced by BlockServer::ProcessTBL_ClearItemNewFlag.
CItem * CItemMgr::getItem(DWord dwID)
References m_idMap.
Referenced by ActiveAvatarMgr::fixData, EquipSchemaMgr::fixData, HeroMgr::fixData, ActiveAvatarMgr::getAvatars, EquipSchemaMgr::getEquips, EquipSchemaMgr::putOnEquip, ActiveAvatarMgr::setActiveAvatar, HeroMgr::setAvatar.
CItem * CItemMgr::getItem(Word wPos)
References m_BagMap.
DWord CItemMgr::getRespawnItemCount()
References TownItemTableMgr::Get, TownItemTableMgr::GetTownItemTable, m_BagMap, TOWNITEM_CLASS_FUHUODAN, TownItemTable::uiClass, CItem::uiItemID, CItem::uiOverLap.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail.
void CItemMgr::decRespawnItem()
References eraseItem, TownItemTableMgr::Get, TownItemTableMgr::GetTownItemTable, ITEM_OPER_DEL, ITEM_OPER_MOD, m_BagMap, notiChangeItem, CItem::SetOper, TOWNITEM_CLASS_FUHUODAN, TownItemTable::uiClass, CItem::uiItemID, CItem::uiOverLap.
Referenced by BlockServer::ProcessRBL_DecRespawnItemNtf.
void CItemMgr::getSelectableAvatars(const VecSelHeroInfo &akHeroList, VPtlAvatar &akAvatars)
References SePtlAvatar::dwItemID, SePtlAvatar::dwItemTypeID, AvatarTableMgr::Get, TownItemTableMgr::Get, AvatarTableMgr::GetAvatarTable, TownItemTableMgr::GetTownItemTable, m_BagMap, TOWNITEM_CLASS_ZHUANGBAN, TownItemTable::uiClass, AvatarTable::uiHeroID, CItem::uiID, CItem::uiItemID.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail.
bool CItemMgr::CheckOwnerItem(uint32_t ItemID)
References GetItemCountByID.
Referenced by CShop::CheckSoleItem, BlockServer::ProcessWBL_UserAlterNickNameReq.
CItemMgr::CItemMgr()
CItemMgr::~CItemMgr()
void CItemMgr::loadData(const SeDBCharItem &obj)
void CItemMgr::PackAllItem()
void CItemMgr::Update(DWord dwCurTime)
uint32_t CItemMgr::GetItemCountByID(uint32_t uiItemID)
void CItemMgr::SetOwner(SePlayer *pOwner)
References m_pOwner.
SePlayer* CItemMgr::GetOwner()
References m_pOwner.
SeItemResult CItemMgr::StrenthEquip(Word SrcPos, int32_t iNum, Word DstPos[])
SeItemResult CItemMgr::ChangeCiTiao(Word SrcPos, uint32_t iCiTiaoIndex, uint32_t uiNum, bool bLock, Word SrcPosArray[])
SeItemResult CItemMgr::AddNewMultiItem(const std::list< DeposeStru > &itemlist, std::list< CItem * > &items)
SeItemResult CItemMgr::ItemDepart(Word DstPos)
uint16_t CItemMgr::GetExistItemIndex(uint32_t ItemID, uint32_t &itemcount)
uint16_t CItemMgr::CountNeedSlotNumByItemID(DeposeStru &item)
SeItemResult CItemMgr::AddItem(uint32_t ItemID, int32_t num)
SeItemResult CItemMgr::DeleteItem(Word dstpos)
SeItemResult CItemMgr::openRandBox(Word wPos, std::vector< SeRandBoxItem > &boxItems)
SeItemResult CItemMgr::clearItemNewFlag(int iNum, Word PosArray[])
CItem* CItemMgr::getItem(DWord dwID)
CItem* CItemMgr::getItem(Word wPos)
DWord CItemMgr::getRespawnItemCount()
void CItemMgr::decRespawnItem()
void CItemMgr::getSelectableAvatars(const VecSelHeroInfo &akHeroList, VPtlAvatar &akAvatars)
bool CItemMgr::CheckOwnerItem(uint32_t ItemID)
uint16_t CItemMgr::GetEmpySlotIndex()
References m_BagMap, SSD_BAG_ITEM_NUM.
Referenced by AddNewMultiItem.
void CItemMgr::doMoveItem(CItem &item, Word dstPos)
References CItem::CopyToProtoItem, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, SeWT_PlayerNewItem::dwPlayerID, eraseItem, g_kCharItemStrategy, g_kWorldServer, GetID, SePlayer::GetID, GetOwner, GetTownSock, insertItem, SeWT_PlayerNewItem::iNum, ITEM_OPER_DEL, ITEM_OPER_INSERT, SeItemNoti::ItemOper, CItem::save, SeWT_PlayerNewItem::SeItemArray, WorldServer::SendWT_PlayerNewItem, CItem::ucIndex.
void CItemMgr::doExchangeItem(CItem &itemA, CItem &itemB)
References CItem::CopyToProtoItem, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, SeWT_PlayerNewItem::dwPlayerID, eraseItem, g_kCharItemStrategy, g_kWorldServer, GetID, SePlayer::GetID, GetOwner, GetTownSock, insertItem, SeWT_PlayerNewItem::iNum, ITEM_OPER_DEL, ITEM_OPER_INSERT, SeItemNoti::ItemOper, CItem::save, SeWT_PlayerNewItem::SeItemArray, WorldServer::SendWT_PlayerNewItem, CItem::ucIndex.
void CItemMgr::eraseItem(CItem &item)
References m_BagMap, m_idMap, CItem::ucIndex, CItem::uiID.
Referenced by decRespawnItem, DeleteItem, doExchangeItem, doItemMergeCharge, doMoveItem, ItemDepart, openRandBox.
void CItemMgr::insertItem(CItem &item)
References m_BagMap, m_idMap, CItem::ucIndex, CItem::uiID.
Referenced by AddNewMultiItem, doExchangeItem, doMoveItem, loadData.
void CItemMgr::notiChangeItem(std::list< CItem * > &items)
References CItem::CopyToProtoItem, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, SeWT_PlayerNewItem::dwPlayerID, g_kCharItemStrategy, g_kWorldServer, GetID, SePlayer::GetID, CItem::GetOper, GetOwner, GetTownSock, SeWT_PlayerNewItem::iNum, ITEM_OPER_DEL, ITEM_OPER_INSERT, ITEM_OPER_MOD, ITEM_OPER_NONE, CItem::save, SeWT_PlayerNewItem::SeItemArray, WorldServer::SendWT_PlayerNewItem, CItem::SetOper, CItem::uiID.
Referenced by AddItem, clearItemNewFlag, decRespawnItem, DeleteItem, doItemMergeCharge, ItemDepart, openRandBox.
void CItemMgr::doItemMergeCharge(CItem &item, DWord gold, const std::list< ItemAddedStru > &costItems)
References CMT_GOLD, eraseItem, GetGold, GetOwner, ITEM_OPER_DEL, ITEM_OPER_MOD, m_BagMap, notiChangeItem, SePlayer::NotifyOwnMoney, SePlayer::UpdateCharMisc.
Referenced by ChangeCiTiao, StrenthEquip.
uint16_t CItemMgr::GetEmpySlotIndex()
void CItemMgr::doMoveItem(CItem &item, Word dstPos)
void CItemMgr::doExchangeItem(CItem &itemA, CItem &itemB)
void CItemMgr::eraseItem(CItem &item)
void CItemMgr::insertItem(CItem &item)
void CItemMgr::notiChangeItem(std::list< CItem * > &items)
void CItemMgr::doItemMergeCharge(CItem &item, DWord gold, const std::list< ItemAddedStru > &costItems)