SeNexusMgr
MNexus SeNexusMgr::m_NexusMap
Referenced by CheckNexus, CreateNexus, DeleteNexus, GetNexus, GetNexusMap.
SeNexusMgr::SeNexusMgr()
SeNexusMgr::~SeNexusMgr()
void SeNexusMgr::CreateNexus(SeConnect *pkConnect)
References SeNexus::dwServerID, SeConnect::dwServerID, SeConnect::kSock, m_NexusMap, SeNexus::pkConnect.
Referenced by BackendServer::ProcessNBKS_Register.
void SeNexusMgr::DeleteNexus(HSock kSock)
References m_NexusMap.
Referenced by BackendServer::OnNetDisconnect.
bool SeNexusMgr::CheckNexus(HSock kSock)
References m_NexusMap.
Referenced by BackendServer::ProcessNBKS_Register.
MNexus & SeNexusMgr::GetNexusMap()
References m_NexusMap.
SeNexus * SeNexusMgr::GetNexus(HSock kSock)
References m_NexusMap.