SeLogicRaceData
int SeLogicRaceData::m_iBufSize
Referenced by ExpandBuffer, SeLogicRaceData.
Byte * SeLogicRaceData::m_pbyBuffer
Referenced by ExpandBuffer, GetRacePack, PushData, SeLogicRaceData, ~SeLogicRaceData.
int SeLogicRaceData::m_iCurPos
Referenced by ExpandBuffer, GetRacePack, PushData, ResetDataPos, SeLogicRaceData.
DWord SeLogicRaceData::m_dwFrame
Referenced by PushData.
char SeLogicRaceData::m_pHeroInfoBuff[4 *1024]
Referenced by PushHeroInfo, SeLogicRaceData, SendHeroInfo.
int SeLogicRaceData::m_iHeroInfoSize
Referenced by PushHeroInfo, SeLogicRaceData, SendHeroInfo.
SeLogicRaceData::SeLogicRaceData(void)
References m_iBufSize, m_iCurPos, m_iHeroInfoSize, m_pbyBuffer, m_pHeroInfoBuff.
SeLogicRaceData::~SeLogicRaceData(void)
References m_pbyBuffer.
bool SeLogicRaceData::PushData(DWord dwFrame, char *pkData, int iSize)
References ExpandBuffer, m_dwFrame, m_iCurPos, m_pbyBuffer.
Referenced by SeRaceDataMgr::PushRaceData.
void SeLogicRaceData::ResetDataPos()
References m_iCurPos.
Referenced by SeRaceDataMgr::Clear.
Byte * SeLogicRaceData::GetRacePack(int &riSize)
References m_iCurPos, m_pbyBuffer.
Referenced by SeRaceDataMgr::GetRaceData.
bool SeLogicRaceData::PushHeroInfo(int iSeat, char *pkData, int iSize)
References m_iHeroInfoSize, m_pHeroInfoBuff, SeLogError.
Referenced by SeRaceDataMgr::PushHeroInfo.
void SeLogicRaceData::SendHeroInfo(HSock &rkSock)
References g_kRaceServer, SeUDPSender::kSock, m_iHeroInfoSize, m_pHeroInfoBuff, RaceServer::SendRC_GetHeroInfoRet.
Referenced by SeRaceDataMgr::UpdateRaceData.
SeLogicRaceData::SeLogicRaceData(void)
SeLogicRaceData::~SeLogicRaceData(void)
bool SeLogicRaceData::PushData(DWord dwFrame, char *pkData, int iSize)
void SeLogicRaceData::ResetDataPos()
Byte* SeLogicRaceData::GetRacePack(int &riSize)
bool SeLogicRaceData::PushHeroInfo(int iSeat, char *pkData, int iSize)
void SeLogicRaceData::SendHeroInfo(HSock &rkSock)
bool SeLogicRaceData::ExpandBuffer(int iSize)
References m_iBufSize, m_iCurPos, m_pbyBuffer.
Referenced by PushData.
bool SeLogicRaceData::ExpandBuffer(int iSize)