PerformanceTiming::CPerformanceStat
std::string PerformanceTiming::CPerformanceStat::m_sName
std::string PerformanceTiming::CPerformanceStat::m_sFolderName
folder name for the stat - for display/organization purposes
Referenced by GetFolderName.
CRC_ID PerformanceTiming::CPerformanceStat::m_FolderNameCRC
Referenced by CPerformanceStat, GetFolderNameCRC.
bool PerformanceTiming::CPerformanceStat::m_bTouched
Referenced by IsTouched, ResetTouch, Touch.
PerformanceTiming::CPerformanceStat::CPerformanceStat(const std::string &sName)
References m_FolderNameCRC.
virtual PerformanceTiming::CPerformanceStat::~CPerformanceStat()
const std::string & PerformanceTiming::CPerformanceStat::Name() const
Referenced by CPerformanceTiming::EnumerateAllCounters, CPerformanceTiming::EnumerateIntervals, PerformanceTiming::Pred_StatByName::operator().
const char* PerformanceTiming::CPerformanceStat::GetFolderName() const
References m_sFolderName.
Referenced by CIntervalFolderSet::BuildFolderSets, CCounterFolderSet::BuildFolderSets, CPerformanceTiming::EnumerateAllCounters, CPerformanceTiming::EnumerateIntervals.
CRC_ID PerformanceTiming::CPerformanceStat::GetFolderNameCRC() const
References m_FolderNameCRC.
Referenced by CIntervalFolderSet::BuildFolderSets, CCounterFolderSet::BuildFolderSets, CPerformanceTiming::EnumerateAllCounters, CPerformanceTiming::EnumerateIntervals.
bool PerformanceTiming::CPerformanceStat::IsTouched() const
References m_bTouched.
Referenced by CPerformanceTiming::LookupInterval.
virtual void PerformanceTiming::CPerformanceStat::HardReset()=0
PerformanceTiming::CPerformanceStat::CPerformanceStat(const std::string &sName)
virtual PerformanceTiming::CPerformanceStat::~CPerformanceStat()
const std::string& PerformanceTiming::CPerformanceStat::Name() const
const char* PerformanceTiming::CPerformanceStat::GetFolderName() const
References m_sFolderName.
CRC_ID PerformanceTiming::CPerformanceStat::GetFolderNameCRC() const
References m_FolderNameCRC.
bool PerformanceTiming::CPerformanceStat::IsTouched() const
References m_bTouched.
virtual void PerformanceTiming::CPerformanceStat::HardReset()=0
void PerformanceTiming::CPerformanceStat::Touch()
References m_bTouched.
Referenced by PerformanceTiming::CCounter::Add, PerformanceTiming::CCounter::Decrement, PerformanceTiming::CCounter::Increment, PerformanceTiming::CCounter::SetValue.
void PerformanceTiming::CPerformanceStat::ResetTouch()
References m_bTouched.
Referenced by PerformanceTiming::CCounter::HardReset, PerformanceTiming::CInterval::HardReset.
void PerformanceTiming::CPerformanceStat::DoSetFolderName(const char *szFolderName)
References PerformanceTiming::CRCString.
Referenced by CPerformanceTiming::CPerformanceTiming, PerformanceTiming::CCounter::SetFolderName, PerformanceTiming::CInterval::SetFolderName.
void PerformanceTiming::CPerformanceStat::DoSetFolderFlag(int iFlag)
References PerformanceTiming::CRCString.
Referenced by PerformanceTiming::CCounter::SetFolderName.
void PerformanceTiming::CPerformanceStat::Touch()
References m_bTouched.
void PerformanceTiming::CPerformanceStat::ResetTouch()
References m_bTouched.
void PerformanceTiming::CPerformanceStat::DoSetFolderName(const char *szFolderName)
void PerformanceTiming::CPerformanceStat::DoSetFolderFlag(int iFlag)