WorldServer
char WorldServer::m_acSend[SSD_SEND_SIZE]
Referenced by WorldServer.
DWord WorldServer::m_dwTickCount
Referenced by Initialize, Update, WorldServer.
DWord WorldServer::m_dwCurTime
Referenced by GetServerTime, Update, WorldServer.
SeWorldConfig WorldServer::m_kConfig
Referenced by GetAcvmtPerPage, GetConfig, GetReconnTime, InitializeNet, LoadConfig, LoadDynamicConfig, OnNetConnected, OnNetDisconnect, ProcessLW_Register, ProcessMW_Register, ProcessNW_Register, ProcessRW_Register, ProcessTW_RaceEndRace, ProcessTW_Register, SendHS_QueryNearestRaceInfo, UpdateDisconnectTS, UpdateLogShow, UpdateTSTOWSTime.
int WorldServer::m_iInitFlag
Referenced by HasInitFlag, SetInitFlag, WorldServer.
SeDBError WorldServer::m_eDBServerErrorCode
Referenced by GetHasDBError, SetHasDBError, WorldServer.
SeRandNum WorldServer::m_kRandNum
Referenced by RandFloat, RandInt, WorldServer.
int WorldServer::m_iMaxPlayerNum
Referenced by WorldServer.
SeDBTime WorldServer::m_dwMaxPlayerTime
Referenced by WorldServer.
TeNetMgr WorldServer::m_kNetMgr
Referenced by Finialize, Initialize, InitializeNet, OnNetRecv, ProcessHS_Register, ProcessLW_Register, ProcessMW_Register, ProcessNW_Register, ProcessRW_Register, ProcessTW_Register, SendHSData, SendWBData, SendWLData, SendWMData, SendWNData, SendWRData, SendWTData, Update, UpdateHSToWSTime, UpdateLSToWSTime, UpdateTSTOWSTime, UpdateUnknownState.
MapAllConnect WorldServer::m_kAllConnect
Referenced by Finialize, OnNetAccept, OnNetDisconnect, OnNetRecv, UpdateUnknownState.
MapAllConnect WorldServer::m_kAllLS
Referenced by GetLS, GetLSByServerID, GetLSBySock, OnLSDisconnect, ProcessLW_Register, UpdateLSToWSTime.
MapAllConnect WorldServer::m_kAllHS
Referenced by GetHS, GetHSByServerID, GetHSBySock, OnHSDisconnect, ProcessHS_Register, SendHS_QueryNearestRaceInfo, UpdateHSToWSTime.
MapAllTS WorldServer::m_kAllTS
Referenced by Finialize, GetTSByID, GetTSByIndex, GetTSBySock, GetTSNum, HasTownIndex, IsAllTownLoadComplete, KickPlayerByID, OnTSDisconnect, ProcessLW_AccountLogin, ProcessTW_Register, SeDBSerProcess_CharLoginLoad, SetWSReady, UpdateTSTOWSTime.
MapServerID2Time WorldServer::m_kAllDisconnectTS
Referenced by OnTSDisconnect, ProcessTW_Register, UpdateDisconnectTS.
SeVirtConn * WorldServer::m_pkDBSConn
Referenced by LoadConfig, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessBW, ProcessBW_RegisterRet, ProcessHS_Register, ProcessLW_Register, ProcessMW_Register, ProcessNW_Register, ProcessRW_Register, ProcessTW_Register, SendWBData, WorldServer.
SeServerData WorldServer::m_kGlobalServer
Referenced by OnNetConnected, OnNetDisconnect.
Es::NormalLock WorldServer::m_kGenIDLock
Referenced by GenCharRaceArenaID, GenNexusFriendID, GenNexusPromotionID, GenNexusTeamID, GenNexusTeamMemberID.
DWord WorldServer::m_dwGenNexuseFriendID
Referenced by GenNexusFriendID, ProcessBW_InitGenIDRet, WorldServer.
DWord WorldServer::m_dwGenNexusPromotionID
Referenced by GenNexusPromotionID, WorldServer.
DWord WorldServer::m_dwGenCharRaceArenaID
Referenced by GenCharRaceArenaID, WorldServer.
DWord WorldServer::m_dwGenNexusTeamID
Referenced by GenNexusTeamID, WorldServer.
DWord WorldServer::m_dwGenNexusTeamMemberID
Referenced by GenNexusTeamMemberID, WorldServer.
MapLoadFlag2Count WorldServer::m_kLoadFlag2Count
MapOnlinePlayer WorldServer::m_kOnlinePlayer
Referenced by AddOnlinePlayer, DelOnlinePlayer, GetOnlinePlayer, GetPlayerNum, GetPlayerTownSock, OnSendDBSLoadPlayerInfoAgain, ProcessBW_RegisterRet.
MapID2ServerID WorldServer::m_kPlayerID2LS
Referenced by DelLSPlayer, GetLSByPlayerID.
SeDBTime WorldServer::m_kUpdateFreeHeroTime
Referenced by UpdateQueryFreeHeroList.
SeLeagueInfo WorldServer::m_kLeagueInfo
Referenced by GenLeagueTime, InitLeagueInfo, SaveLeagueInfo, UpdateLeagueInfo.
MapHeroSta WorldServer::m_kMHeroStat
Referenced by OnHeroEndStat, UpdateLogHeroEndStat.
int WorldServer::m_iBlockServerNum
Referenced by Finialize, GetBlockServerNum, Initialize, LoadConfig, PushThreadMsg, WorldServer.
BlockServer * WorldServer::m_pakBlockServer
Referenced by Finialize, Initialize, LoadDynamicConfig, PushThreadMsg, PushThreadMsgByNum, WorldServer.
SeThreadMsgMgr WorldServer::m_kThreadMsgMgr
Referenced by Initialize, PushWSMsg, UpdateWSMsg.
DWord WorldServer::m_dwGenThreadMsgID
Referenced by WorldServer.
MapThreadQuery WorldServer::m_kAllThreadQuery
MapID2ReconInfo WorldServer::m_kMID2ReconInfo
Referenced by DelReconPlayer, GetReconPlayer, ProcessTW_SavePlayerReconInfo, UpdatePlayerReconInfo.
SeFlux WorldServer::m_kFlux
Referenced by SendWTData, WorldServer.
DWord WorldServer::m_adwCmdTime[512]
Referenced by Update, WorldServer.
DWord WorldServer::m_dwLoadCount
Referenced by ProcessBLW_PlayerLoadComplete, UpdateLogShow, WorldServer.
DWord WorldServer::m_dwLoadSumTime
Referenced by ProcessBLW_PlayerLoadComplete, UpdateLogShow, WorldServer.
bool WorldServer::m_bSysDBDataInit
Referenced by ProcessBW_RegisterRet, WorldServer.
bool WorldServer::m_bSysDSDataInit
Referenced by WorldServer.
bool WorldServer::m_bBSReady
Referenced by IsDBReady, SetDBReady, WorldServer.
bool WorldServer::m_bWSReady
Referenced by IsWSReady, SetWSReady, SwitchWSReady, WorldServer.
bool WorldServer::m_bForceWSStop
Referenced by SwitchWSReady, Update, WorldServer.
bool WorldServer::m_bPrintMemory
Referenced by Update, WorldServer.
bool WorldServer::m_bPrintUpdateTime
Referenced by WorldServer.
bool WorldServer::m_bPrintProcessCMDTime
Referenced by Update, WorldServer.
bool WorldServer::m_bPrintFlux
Referenced by SendWTData, WorldServer.
bool WorldServer::m_bPrintBlockServerTime
Referenced by WorldServer.
bool WorldServer::m_bException
Referenced by IsException, SetException, WorldServer.
CShop WorldServer::m_Shop
Referenced by GetShop, LoadConfig, Update.
WorldServer::WorldServer(void)
References SeRandNum::Initialize, m_acSend, m_adwCmdTime, m_bBSReady, m_bException, m_bForceWSStop, m_bPrintBlockServerTime, m_bPrintFlux, m_bPrintMemory, m_bPrintProcessCMDTime, m_bPrintUpdateTime, m_bSysDBDataInit, m_bSysDSDataInit, m_bWSReady, m_dwCurTime, m_dwGenCharRaceArenaID, m_dwGenNexuseFriendID, m_dwGenNexusPromotionID, m_dwGenNexusTeamID, m_dwGenNexusTeamMemberID, m_dwGenThreadMsgID, m_dwLoadCount, m_dwLoadSumTime, m_dwMaxPlayerTime, m_dwTickCount, m_eDBServerErrorCode, m_iBlockServerNum, m_iInitFlag, m_iMaxPlayerNum, m_kFlux, m_kRandNum, m_pakBlockServer, m_pkDBSConn, NowTime, SDER_NONE.
WorldServer::~WorldServer(void)
References Finialize.
bool WorldServer::Initialize(void)
References g_kLadderLevelMgr, g_kPlayerDataMgr, g_kResMgr, g_kVirtConnMgr, moba::Clock::getInstance, InitDBTable, InitialFileData, SeReMgr::Initialize, PlayerDataMgr::initialize, LadderLevelMgr::Initialize, BlockServer::Initialize, SeThreadMsgMgr::Initialize, SeVirtConnMgr::Initialize, InitializeNet, InitializeSysManager, LoadConfig, LoadDynamicConfig, m_dwTickCount, m_iBlockServerNum, m_kNetMgr, m_kThreadMsgMgr, m_pakBlockServer, SeLogError, SeLogInfo, sendHeartPack, sendRegPack, moba::Clock::setTime.
void WorldServer::Update(void)
References CharToFileFun, g_kMatchServerMgr, g_kNexusServerMgr, g_kPlayerDataMgr, g_kRaceServerMgr, g_kTownServerMgr, g_kVirtConnMgr, moba::Clock::getInstance, GetLocalTime, HasInitFlag, IsDBReady, IsException, PlayerDataMgr::isGenIDFinished, IsWSReady, m_adwCmdTime, m_bForceWSStop, m_bPrintMemory, m_bPrintProcessCMDTime, m_dwCurTime, m_dwTickCount, m_kNetMgr, m_Shop, SeLogInfo, moba::Clock::setTime, SetWSReady, SPrintf, SWIF_INIT_ALL, TIMEOUT_EXEC, TIMER_KIND_SHOP, moba::ServerSessionMgr::update, CShop::Update, SeVirtConnMgr::Update, UpdateDisconnectTS, UpdateHSToWSTime, UpdateLeagueInfo, UpdateLogHeroEndStat, UpdateLogShow, UpdateLSToWSTime, UpdateQueryFreeHeroList, UpdateTSTOWSTime, UpdateUnknownState, UpdateWSMsg.
void WorldServer::Finialize(void)
References BlockServer::Finialize, m_iBlockServerNum, m_kAllConnect, m_kAllTS, m_kNetMgr, m_pakBlockServer, SaveUpdateWorldSetup.
Referenced by ~WorldServer.
void WorldServer::ShowConsoleTitle(int iDTime)
References GetPlayerNum, GetTSNum, SPrintf.
DWord WorldServer::GetReconnTime() const
References SeWorldConfig::dwMaxReconTime, m_kConfig.
Referenced by ProcessBLW_PlayerLoadComplete, UpdatePlayerReconInfo.
int WorldServer::GetAcvmtPerPage() const
References SeWorldConfig::iAcvmtNumPerPage, m_kConfig.
SeServerActionResult WorldServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F5, LoadDynamicConfig, SeLogHideTime, SeLogInfo.
CShop* WorldServer::GetShop()
References m_Shop.
Referenced by BlockServer::ProcessWBL_BuyShopItem, BlockServer::ProcessWBL_GetItemGM, BlockServer::ProcessWBL_ShopItemGM.
void WorldServer::UserInfoSync(SePlayer *pPlayer)
References UserInfoSync_LoadFriendLadderRank, UserInfoSync_NexusFriend, UserInfoSync_PlayerScore.
Referenced by SePlayer::OperateLoading.
void WorldServer::UserInfoSync_NexusFriend(SePlayer *pPlayer)
References SeNexusFriendSyncInfo::acName, SeCharNexusFriendData::char_friend_id, SeCharNexusFriendData::char_id, SeNexusFriendSyncInfo::dwMark, SeNexusFriendSyncInfo::dwPlayerFriendID, SeNexusFriendSyncInfo::dwPlayerID, SePlayer::GetID, SePlayer::GetMCharNexusFriendData, SePlayer::GetName, SeCharNexusFriendData::mark, SeCharNexusFriendData::name, SendWN_NexusFriendInfoSyn.
Referenced by UserInfoSync.
void WorldServer::UserInfoSync_PlayerScore(SePlayer *pPlayer)
References EMT_BATTLEFIELD, EMT_LADDER, EMT_MATCH, SePlayer::GetBattleField, SePlayer::GetID, SePlayer::GetLadder, SePlayer::GetMatch, SendWN_PlayerScoreNtf.
Referenced by UserInfoSync.
void WorldServer::UserInfoSync_LoadFriendLadderRank(SePlayer *pPlayer)
References SePlayer::GetID, SePlayer::GetMCharNexusFriendData, SBBR_LOAD_FRIEND_LADDER, SendWB_SelectFriendData, SePlayer::SetCurrFriendNumForAck.
Referenced by UserInfoSync.
void WorldServer::UserHeroBindItem(DWord dwHeroID, std::vector< DWord > &rInfoVec)
References UnitTableMgr::Get, UnitTableMgr::GetUnitTable, UnitTable::iBaseID, SeLogError.
Referenced by HeroMgr::processAddHeroBindItem.
bool WorldServer::CheckMapType(const DWord dw_map_id, const DWord dw_map_type)
References MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, MapInfoTable::uiType.
Referenced by RaceMapMgr::get_race_data, RaceHeroMgr::makeHero_Arena.
bool WorldServer::CheckMapMatchType(const DWord dw_map_id, const DWord dw_map_type)
References MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, MapInfoTable::uiMatchType.
Referenced by RaceMapMgr::get_race_data.
void WorldServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeServerData::bConnecting, g_kVirtConnMgr, SeNetAddr::iPort, SeWorldConfig::kGlobalServer, SeVirtConn::kNetAddr, SeServerData::kSock, m_kConfig, m_kGlobalServer, m_pkDBSConn, SeVirtConnMgr::OnServerConnected, SeLogError, SeLogInfo.
void WorldServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeConnect::dwServerID, moba::Clock::getInstance, moba::Clock::getMilliSeconds, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllConnect, SSD_IP_LEN, SSI_UNKNOWN, StrCpy.
void WorldServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References CMD_HS_REGISTER, CMD_LW_REGISTER, CMD_MW_REGISTER, CMD_NW_REGISTER, CMD_RW_REGISTER, CMD_TW_REGISTER, SeBlockCMD::connectID, SeVirtConn::dwLastRecvTime, SeBlockCMD::dwPlayerID, SeConnect::dwServerID, moba::Clock::getInstance, moba::Clock::getMilliSeconds, GetServerTime, SeVirtConn::kSock, m_kAllConnect, m_kNetMgr, m_pkDBSConn, ProcessBWData, ProcessHSData, ProcessLWData, ProcessMWData, ProcessNWData, ProcessRWData, ProcessTWData, PushThreadMsg, SeLogError, SSD_SEND_SIZE, SSI_HS, SSI_LS, SSI_MS, SSI_NS, SSI_RS, SSI_TS, SSI_UNKNOWN, STCB_BS_BLS, STCB_INTERVAL, STCB_MS_BLS, STCB_NS_BLS, STCB_RS_BLS, STCB_TS_BLS, SeCMD::wCmd, SeBlockCMD::wCmd, SeCMD::wFlag.
void WorldServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, SeServerData::bConnecting, SeServerData::bRegistered, moba::ServerSessionMgr::deleteServer, SeServerData::dwRegisterTime, SeConnect::dwServerID, g_kMatchServerMgr, g_kNexusServerMgr, g_kRaceServerMgr, g_kTownServerMgr, g_kVirtConnMgr, GetID2Str, SeNetAddr::iPort, SeWorldConfig::kGlobalServer, SeConnect::kNetAddr, SeServerData::kSock, SeVirtConn::kSock, m_kAllConnect, m_kConfig, m_kGlobalServer, m_pkDBSConn, OnHSDisconnect, OnLSDisconnect, SeVirtConnMgr::OnServerDisconnect, OnTSDisconnect, SDER_DB_DISCONNECT, SeLogError, SetHasDBError, SSI_HS, SSI_LS, SSI_MS, SSI_NS, SSI_RS, SSI_TS.
SeWorldConfig& WorldServer::GetConfig()
References m_kConfig.
Referenced by SePlayer::adjustLadderNo, SePlayer::GetLadder, CShop::LoadGmItems, BlockServer::ProcessMBL_GetPlayerMatchValue, ItemSaveThread::SaveGmItem.
const char * WorldServer::GetTableName(SeDBTableIndex eTable)
References SeLogError.
Referenced by ProcessBW_InitGenIDRet.
int WorldServer::GetTableFieldCount(SeDBTableIndex eTable)
Referenced by PlayerDataStrategy::dataInsert, PlayerDataStrategy::dataUpdate, PlayerDataStrategy::loadData, PlayerDataStrategy::onLoadData.
bool WorldServer::SendWL_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessLW_Register.
bool WorldServer::SendWL_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessLW_HeartPackage.
bool WorldServer::SendWL_LoginSuccess(DWord dwPackKey, DWord dwPlayerID, DWord dwSessionID, int iNum, const SeNetAddr *akGateList, void *pkReceiver=NULL)
Referenced by ProcessLW_AccountLogin, SeDBSerProcess_CharLoginLoad.
bool WorldServer::SendWL_LoginSuccess(DWord dwPackKey, DWord dwPlayerID, DWord dwSessionID, int iNum, std::vector< SeNetAddr > &akGateList, void *pkReceiver=NULL)
bool WorldServer::SendWL_LoginFailed(DWord dwPackKey, DWord dwPlayerID, const SeLoginReason &eReason, int iParam1, void *pkReceiver=NULL)
Referenced by ProcessLW_AccountLogin.
bool WorldServer::SendWL_PlayerTownIndex(DWord dwPlayerID, int iTownIndex, void *pkReceiver=NULL)
Referenced by OnSendLSPlayerTownIndex.
bool WorldServer::SendWL_PlayerLogout(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by OnSendLSPlayerLogout.
bool WorldServer::SendWL_PlayerUpdateOnlineTime(DWord dwPlayerID, DWord dwOnlineTime, void *pkReceiver=NULL)
bool WorldServer::SendWLData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool WorldServer::SendWT_RegisterRet(const SeRegisterRet &eRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessTW_Register.
bool WorldServer::SendWT_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessTW_HeartPackage.
bool WorldServer::SendWT_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, DWord dwParam, int iSize, const char *acMessage, void *pkReceiver=NULL)
Referenced by OnSendShowNoticeWithoutString, BlockServer::ProcessWBL_ShowNotice.
bool WorldServer::SendWT_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, DWord dwParam, int iSize, std::vector< char > &acMessage, void *pkReceiver=NULL)
bool WorldServer::SendWT_IsReady(bool bReady, void *pkReceiver=NULL)
Referenced by ProcessTW_LoadPlayerInfoAgain, SetWSReady.
bool WorldServer::SendWT_LoadPlayerInfoAgainRet(bool bSuc, void *pkReceiver=NULL)
Referenced by SeTown::DelLoadPlayerID, ProcessTW_LoadPlayerInfoAgain, SeTown::UpdateLoadData.
bool WorldServer::SendWT_PlayerValidateRet(DWord dwClientID, DWord dwPlayerID, const SeValidateType &eValidateType, void *pkReceiver=NULL)
Referenced by BlockServer::ProcessWBL_PlayerValidate, BlockServer::ProcessWBL_PlayerValidateEnd.
bool WorldServer::SendWT_QueryNameRet(DWord dwPlayerID, bool bHasExist, void *pkReceiver=NULL)
Referenced by ProcessTW_QueryName.
bool WorldServer::SendWT_CreateCharRet(DWord dwPlayerID, const SeCreateCharRet &eState, void *pkReceiver=NULL)
Referenced by BlockServer::ProcessWBL_CharAddRet.
bool WorldServer::SendWT_KickPlayer(DWord dwPlayerID, bool bIsSysKick, void *pkReceiver=NULL)
Referenced by BlockServer::KickPlayerByID, KickPlayerByID.
bool WorldServer::SendWT_PlayerLeave(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessBLW_PlayerLeave.
bool WorldServer::SendWT_InitPlayerInfo(DWord dwPlayerID, const char *acName, DWord iGold, DWord iDiamond, DWord dwLevel, DWord dwExp, const SeLadderInfo &kLadder, Byte byEquipSetIndex, DWord dwServerTime, DWord dwOnlineTime, void *pkReceiver=NULL)
Referenced by SePlayer::OperateLoading.
bool WorldServer::SendWT_ExchangeInit(DWord dwPlayerID, int iNum, const SePtlExchange *akPtlExchange, void *pkReceiver=NULL)
Referenced by SePlayer::OperateLoading.
bool WorldServer::SendWT_ExchangeInit(DWord dwPlayerID, int iNum, std::vector< SePtlExchange > &akPtlExchange, void *pkReceiver=NULL)
bool WorldServer::SendWT_ItemExchangeRet(DWord dwPlayerID, int iTypeID, int iReturn, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryPlayerReconInfo(DWord dwPlayerID, DWord dwRoomID, int iSeatIndex, int iReconTime, void *pkReceiver=NULL)
Referenced by ProcessBLW_PlayerLoadComplete.
bool WorldServer::SendWT_UpdateMisc(DWord dwPlayerID, const SeMiscType &eType, int iValue, int iValue2, void *pkReceiver=NULL)
bool WorldServer::SendWT_TaskQueryListRet(DWord dwPlayerID, int iNum, const SePtlTask *akList, void *pkReceiver=NULL)
bool WorldServer::SendWT_TaskQueryListRet(DWord dwPlayerID, int iNum, std::vector< SePtlTask > &akList, void *pkReceiver=NULL)
bool WorldServer::SendWT_TaskReselRet(DWord dwPlayerID, DWord dwSrcTaskID, const SePtlTask &kNewTask, void *pkReceiver=NULL)
bool WorldServer::SendWT_ItemDel(DWord dwPlayerID, DWord dwItemID, const SeItemDelType &eType, void *pkReceiver=NULL)
bool WorldServer::SendWT_ReceiveMail(DWord dwPlayerID, int iNum, const SePtlMail *akMail, void *pkReceiver=NULL)
bool WorldServer::SendWT_ReceiveMail(DWord dwPlayerID, int iNum, std::vector< SePtlMail > &akMail, void *pkReceiver=NULL)
bool WorldServer::SendWT_UpdateMail(DWord dwPlayerID, int iNum, const SeMailUpdate *akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_UpdateMail(DWord dwPlayerID, int iNum, std::vector< SeMailUpdate > &akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_MailOprRet(DWord dwPlayerID, int iType, DWord dwMailID, int iRet, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerRename(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
Referenced by SePlayer::OnRenameEnd.
bool WorldServer::SendWT_RaceBuyRet(DWord dwSession, bool bSuccess, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryMapTaskListRet(DWord dwPlayerID, DWord dwMapID, int iNum, const SePtlMapTask *akPtlMapTask, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryMapTaskListRet(DWord dwPlayerID, DWord dwMapID, int iNum, std::vector< SePtlMapTask > &akPtlMapTask, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryNearestRaceInfoRet(DWord dwPlayerID, DWord dwQueriedID, int iNum, const SePtlRaceHistory *akRaceInfo, void *pkReceiver=NULL)
Referenced by ProcessHS_QueryNearestRaceInfoRet.
bool WorldServer::SendWT_QueryNearestRaceInfoRet(DWord dwPlayerID, DWord dwQueriedID, int iNum, std::vector< SePtlRaceHistory > &akRaceInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_GetRaceHistoryRet(DWord dwPlayerID, int iType, int iPage, int iMaxPage, int iNum, const SePtlRaceHistory *akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_GetRaceHistoryRet(DWord dwPlayerID, int iType, int iPage, int iMaxPage, int iNum, std::vector< SePtlRaceHistory > &akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerNewItem(DWord dwPlayerID, int iNum, const SeItemNoti *SeItemArray, void *pkReceiver=NULL)
Referenced by CItemMgr::doExchangeItem, CItemMgr::doMoveItem, CItemMgr::notiChangeItem, CItemMgr::PackAllItem.
bool WorldServer::SendWT_PlayerNewItem(DWord dwPlayerID, int iNum, std::vector< SeItemNoti > &SeItemArray, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerOperRep(DWord dwPlayerID, int iResult, void *pkReceiver=NULL)
Referenced by ProcessBLW_PlayerOperRep.
bool WorldServer::SendWT_PlayerMoneyAndDiamond(DWord dwPlayerID, DWord dwGold, DWord dwDiamond, void *pkReceiver=NULL)
Referenced by SePlayer::NotifyOwnMoney.
bool WorldServer::SendWT_ShopItemGmRep(DWord dwPlayerID, int iResult, const ShopItem &GmItem, void *pkReceiver=NULL)
Referenced by ProcessBLW_ShopItemGmRep.
bool WorldServer::SendWT_SearchUserArchivesInfoRes(DWord dwPlayerID, const SeUserArchivesInfo &user_archives_info, void *pkReceiver=NULL)
Referenced by ProcessBW_IsPlayerExistRet.
bool WorldServer::SendWT_SearchUserArchivesDetailInfoRes(DWord dwPlayerID, const SeUserArchivesInfo &user_archives_info, void *pkReceiver=NULL)
Referenced by ProcessBW_IsPlayerExistRet.
bool WorldServer::SendWT_PlayerLadder(DWord dwPlayerID, const SeLadderInfo &kLadder, void *pkReceiver=NULL)
Referenced by BlockServer::ProcessRBL_UpdateScore.
bool WorldServer::SendWT_EquipSchema(DWord dwPlayerID, int iNum, const SeEquipSchemaInfo *akEquips, void *pkReceiver=NULL)
Referenced by EquipSchemaMgr::sendInitData.
bool WorldServer::SendWT_EquipSchema(DWord dwPlayerID, int iNum, std::vector< SeEquipSchemaInfo > &akEquips, void *pkReceiver=NULL)
bool WorldServer::SendWT_RoomInviteNotify(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
Referenced by BlockServer::ProcessMBL_BlockRoomInvite.
bool WorldServer::SendWT_FriendLadderInfoNtf(DWord dwPlayerID, int iNum, const SeLadderRankInfo *RankList, void *pkReceiver=NULL)
Referenced by BlockServer::ProcessBBL_SelectFriendDataRet.
bool WorldServer::SendWT_FriendLadderInfoNtf(DWord dwPlayerID, int iNum, std::vector< SeLadderRankInfo > &RankList, void *pkReceiver=NULL)
bool WorldServer::SendWT_ActiveAvatarNtf(DWord dwPlayerID, int iNum, const DWord *avartars, void *pkReceiver=NULL)
Referenced by ActiveAvatarMgr::sendInitData.
bool WorldServer::SendWT_ActiveAvatarNtf(DWord dwPlayerID, int iNum, std::vector< DWord > &avartars, void *pkReceiver=NULL)
bool WorldServer::SendWT_UserHeroSync(DWord dwPlayerID, int num, const SeUserHeroSyncInfo *akHeroSyncInfo, void *pkReceiver=NULL)
Referenced by HeroMgr::notifyChanged.
bool WorldServer::SendWT_UserHeroSync(DWord dwPlayerID, int num, std::vector< SeUserHeroSyncInfo > &akHeroSyncInfo, void *pkReceiver=NULL)
bool WorldServer::SendWTData(void *pkData, int iSize, void *pkReceiver)
References SeFlux::aiFluxCountSend, SeFlux::aiFluxSend, CMD_WT_BEGIN, m_bPrintFlux, m_kFlux, m_kNetMgr, SeLogError, SeCMD::wCmd.
Referenced by BlockServer::SendBLTData.
bool WorldServer::SendHSData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
Referenced by SendHS_HeartPackageRet, SendHS_QueryNearestRaceInfo, SendHS_RegisterRet.
bool WorldServer::SendHS_RegisterRet(const HSock &rkSock, int iRet)
References SeHS_RegisterRet::iRet, SendHSData.
Referenced by ProcessHS_Register.
bool WorldServer::SendHS_HeartPackageRet(const HSock &rkSock)
References SendHSData.
Referenced by ProcessHS_HeartPackage.
bool WorldServer::SendHS_QueryNearestRaceInfo(DWord dwPlayerID, DWord dwQueryID, DWord dwMapID)
References SeWorldConfig::dwAreaID, SeHS_UPSQueryNearestRaceInfo::dwAreaID, SeHS_UPSQueryNearestRaceInfo::dwMapID, SeHS_UPSQueryNearestRaceInfo::dwPlayerID, SeHS_UPSQueryNearestRaceInfo::dwQueryID, m_kAllHS, m_kConfig, SendHSData.
Referenced by ProcessTW_QueryNearestRaceInfo.
bool WorldServer::SendWB_Register(DWord dwWorldMagic, DWord dwVersion, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool WorldServer::SendWB_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool WorldServer::SendWB_InitGenID(const SeInitGenIDType &eType, const SeDBTableIndex &eTableIndex, void *pkReceiver=NULL)
Referenced by PlayerDataStrategy::initGenID, ProcessBW_RegisterRet.
bool WorldServer::SendWB_DataInsert(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, DWord dwParam1, const SeBBReceipt &eReceipt, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by PlayerDataStrategy::dataInsert, SendDBServer_CharInfoADD, SendDBServer_CharTaskAdd, SendDBServer_NexusFriendCreate.
bool WorldServer::SendWB_DataInsert(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, DWord dwParam1, const SeBBReceipt &eReceipt, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataUpdate(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, DWord dwParam1, const SeBBReceipt &eReceipt, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by PlayerDataStrategy::dataUpdate, SendDBServer_CharAddMisc, SendDBServer_CharTaskUpdate, SendDBServer_CharUpdateBattleField, SendDBServer_CharUpdateLadder, SendDBServer_CharUpdateLoginTime, SendDBServer_CharUpdateMatch, SendDBServer_CharUpdateMisc, SendDBServer_CharUpdateTaskResetCount, SendDBServer_CharUpdateTaskResetTime, SendDBServer_NexusFriendUpdate.
bool WorldServer::SendWB_DataUpdate(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, DWord dwParam1, const SeBBReceipt &eReceipt, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataDiscard(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, int iDeleteReason, const SeDBTime &kDeleteTime, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataDelete(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, void *pkReceiver=NULL)
Referenced by PlayerDataStrategy::dataDelete, SendDBServer_CharTaskDel, SendDBServer_NexusFriendDelete.
bool WorldServer::SendWB_PlayerLoad(DWord dwPlayerID, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by OnSendDBPlayerLoad.
bool WorldServer::SendWB_PlayerLoad(DWord dwPlayerID, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_SelectData(DWord dwID, const SeDBTableIndex &eTable, const SeBBReceipt &eReceipt, int iNum, const int *aiIndex, void *pkReceiver=NULL)
Referenced by PlayerDataStrategy::loadData, SendDBServer_CharMemoryLoad, SendDBServer_CharTaskLoad, SendDBServer_NexusFriendLoad.
bool WorldServer::SendWB_SelectData(DWord dwID, const SeDBTableIndex &eTable, const SeBBReceipt &eReceipt, int iNum, std::vector< int > &aiIndex, void *pkReceiver=NULL)
bool WorldServer::SendWB_PlayerOffLine(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by BlockServer::KickPlayerByID.
bool WorldServer::SendWB_DBQuery(const SeDBQueryType &eType, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by SendDBServer_CharInfoRename, SendDBServer_CharLoginLoad, SendDBServer_CharMemoryUpdate, SendDBServer_CharQueryValid.
bool WorldServer::SendWB_DBQuery(const SeDBQueryType &eType, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_IsPlayerExist(const SePlayerExistQueryType &eType, const char *acAccount, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by BlockServer::ProcessTBL_UserAlterNickNameReq, ProcessTW_QueryName, ProcessTW_SearchUserArchivesDetailInfoReq, ProcessTW_SearchUserArchivesInfoReq.
bool WorldServer::SendWB_IsPlayerExist(const SePlayerExistQueryType &eType, const char *acAccount, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_LoadPlayerInfoAgain(int iTotalNum, int iBegin, int iNum, const DWord *akPlayerInfo, void *pkReceiver=NULL)
Referenced by OnSendDBSLoadPlayerInfoAgain.
bool WorldServer::SendWB_LoadPlayerInfoAgain(int iTotalNum, int iBegin, int iNum, std::vector< DWord > &akPlayerInfo, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabSelect(const SeDBTableIndex &eTable, DWord dwQueryID, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by TabMgr::tabSelect.
bool WorldServer::SendWB_TabSelect(const SeDBTableIndex &eTable, DWord dwQueryID, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabUpdate(const SeDBTableIndex &eTable, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by TabMgr::tabUpdate.
bool WorldServer::SendWB_TabUpdate(const SeDBTableIndex &eTable, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabInsert(const SeDBTableIndex &eTable, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by TabMgr::tabInsert.
bool WorldServer::SendWB_TabInsert(const SeDBTableIndex &eTable, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabDelete(const SeDBTableIndex &eTable, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by TabMgr::tabDelete.
bool WorldServer::SendWB_TabDelete(const SeDBTableIndex &eTable, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_SelectFriendData(DWord dwID, const SeBBReceipt &eType, int iSize, const DWord *dwIDList, void *pkReceiver=NULL)
Referenced by BlockServer::ProcessTBL_FriendLadderInfoReq, UserInfoSync_LoadFriendLadderRank.
bool WorldServer::SendWB_SelectFriendData(DWord dwID, const SeBBReceipt &eType, int iSize, std::vector< DWord > &dwIDList, void *pkReceiver=NULL)
bool WorldServer::SendWBData(void *pkData, int iSize, void *pkReceiver)
References CMD_WB_REGISTER, SeVirtConn::eState, IsDBReady, SeVirtConn::kSock, m_kNetMgr, m_pkDBSConn, SeLogError, SVCS_REGISTERED, SeCMD::wCmd.
Referenced by BlockServer::SendBLBData.
bool WorldServer::SendDBServer_CharLoginLoad(DWord dwID, DWord dwPackKey, DWord dwSessionID)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SDQT_CHAR_LOGIN_LOAD, SendWB_DBQuery, SeDBStream::WriteDword.
bool WorldServer::SendDBServer_CharInfoADD(DWord dwPlayerID, const char *pcAccount, const char *pcName, int iSex, int iPlatFlag)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_CHAR_ADD, SDTI_CharInfo, SendWB_DataInsert, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by BlockServer::ProcessWBL_CreateChar.
bool WorldServer::SendDBServer_CharUpdateMisc(DWord dwPlayerID, SeCharMiscType eType, UInt uiValue)
References CMT_AVATAR, CMT_AVATARFRAME, CMT_DIAMOND, CMT_EQUIPSETINDEX, CMT_EXP, CMT_GOLD, CMT_LEVEL, CMT_ONLINE_TIME, CMT_RACECUMUGOLDS, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SeLogError, SendWB_DataUpdate, SeDBStream::WriteDword.
Referenced by SePlayer::UpdateCharMisc, SePlayer::UpdateOnlineTime.
bool WorldServer::SendDBServer_CharAddMisc(DWord dwPlayerID, SeCharMiscType eType, UInt uiValue)
References CMT_DIAMOND, CMT_GOLD, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SeLogError, SendWB_DataUpdate, SeDBStream::WriteDword.
bool WorldServer::SendDBServer_CharInfoUpdateScore(DWord dwPlayerID, UInt uiScore, UInt uiFood, UInt uiSoldiers, SeCharMiscType eType, UInt uiValue=0)
bool WorldServer::SendDBServer_CharInfoAddScore(DWord dwPlayerID, UInt uiAddScore, UInt uiAddFood, UInt uiAddSoldiers, SeCharMiscType eType, UInt uiAddValue=0)
bool WorldServer::SendDBServer_CharQueryValid(DWord dwPlayerID, DWord dwClientID, int iTownIndex)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, NowTime, SDQT_CHAR_QUERY_VALID, SendWB_DBQuery, SeDBStream::WriteDBTime, SeDBStream::WriteDword.
Referenced by BlockServer::ProcessWBL_PlayerValidate.
bool WorldServer::SendDBServer_CharInfoRename(DWord dwPlayerID, const char *pcName)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SDQT_CHAR_RENAME, SeLogError, SendWB_DBQuery, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by SePlayer::OnRenameBegin.
bool WorldServer::SendDBServer_CharUpdateChestInfo(DWord dwPlayerID, int iChestKey, const SeDBTime &rkChestKeyTime)
bool WorldServer::SendDBServer_CharUpdateAcvmtCounts(DWord dwPlayerID, int iVal)
bool WorldServer::SendDBServer_CharInfoUpdateConfig(DWord dwPlayerID, const char *pConfig, int iLen)
bool WorldServer::SendDBServer_CharUpdateLoginTime(DWord dwPlayerID, const SeDBTime &loginTime)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SendWB_DataUpdate, SeDBStream::WriteDBTime, SeDBStream::WriteDword.
Referenced by SePlayer::LoadingComplete.
bool WorldServer::SendDBServer_CharUpdateLadder(DWord dwPlayerID, const SeDBTime &time, int defeat, int score, int no, int level)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SendWB_DataUpdate, SeDBStream::WriteDBTime, SeDBStream::WriteDword.
Referenced by BlockServer::ProcessRBL_UpdateScore.
bool WorldServer::SendDBServer_CharUpdateMatch(DWord dwPlayerID, const SeDBTime &time, int defeat, int score, int num)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SendWB_DataUpdate, SeDBStream::WriteDBTime, SeDBStream::WriteDword.
Referenced by BlockServer::ProcessRBL_UpdateScore.
bool WorldServer::SendDBServer_CharUpdateBattleField(DWord dwPlayerID, const SeDBTime &time, int defeat, int score)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SendWB_DataUpdate, SeDBStream::WriteDBTime, SeDBStream::WriteDword.
Referenced by BlockServer::ProcessRBL_UpdateScore.
bool WorldServer::SendDBServer_CharUpdateTaskResetCount(DWord dwPlayerID, DWord dwResetCount)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SendWB_DataUpdate, SeDBStream::WriteDword.
Referenced by TaskMgr::ResetTask.
bool WorldServer::SendDBServer_CharUpdateTaskResetTime(DWord dwPlayerID, DWord dwResetCount, const SeDBTime &time)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SendWB_DataUpdate, SeDBStream::WriteDBTime, SeDBStream::WriteDword.
Referenced by TaskMgr::RefreshTask.
bool WorldServer::SendDBServer_CharTaskLoad(DWord dwPlayerID)
References SBBR_LOAD_CHAR_TASK, SDTI_CharTask, SendWB_SelectData.
bool WorldServer::SendDBServer_CharTaskAdd(DWord dwPlayerID, const SeTaskInfo *pkTask)
References SeTaskInfo::dwTaskID, SeTaskInfo::eState, SeTaskInfo::eTaskType, SeDBStream::GetCurPos, SeDBStream::GetData, SeTaskInfo::iConditionNum, SeTaskInfo::ifinishCount, SeDBStream::InitData, SeTaskInfo::iSchedule, SBBR_NONE, SDTI_CharTask, SendWB_DataInsert, SeDBStream::WriteDword.
bool WorldServer::SendDBServer_CharTaskDel(DWord dwPlayerID, DWord dwTaskID)
References SDTI_CharTask, SendWB_DataDelete.
bool WorldServer::SendDBServer_CharTaskUpdate(DWord dwPlayerID, const SeTaskInfo *pkTask)
References SeTaskInfo::dwTaskID, SeTaskInfo::eState, SeTaskInfo::eTaskType, SeDBStream::GetCurPos, SeDBStream::GetData, SeTaskInfo::iConditionNum, SeTaskInfo::ifinishCount, SeDBStream::InitData, SeTaskInfo::iSchedule, SBBR_NONE, SDTI_CharTask, SendWB_DataUpdate, SeDBStream::WriteDword.
bool WorldServer::SendDBServer_CharMemoryLoad(DWord dwPlayerID)
References SBBR_LOAD_CHAR_MEMORY, SDTI_CharMemory, SendWB_SelectData.
Referenced by BlockServer::ProcessBBL_PlayerLoadRet.
bool WorldServer::SendDBServer_CharMemoryUpdate(DWord dwPlayerID, DWord dwType, const SeCharMemory &rkData)
References SeCharMemory::dwParam, SeCharMemory::dwValue, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SeCharMemory::kEndTime, SDQT_CHAR_MEMORY_UPDATE, SendWB_DBQuery, SeDBStream::WriteDBTime, SeDBStream::WriteDword.
Referenced by SePlayer::UpdateMemoryData.
bool WorldServer::SendDBServer_NexusFriendLoad(DWord dwPlayerID)
References SBBR_LOAD_CHAR_NEXUSFRIEND, SDTI_CharNexusFriend, SendWB_SelectData.
Referenced by BlockServer::ProcessBBL_PlayerLoadRet.
bool WorldServer::SendDBServer_NexusFriendCreate(DWord dwPlayerID, const SeCharNexusFriendData &rkData)
References SeCharNexusFriendData::char_friend_id, SeCharNexusFriendData::char_id, SeCharNexusFriendData::create_time, SeDBStream::GetCurPos, SeDBStream::GetData, SeCharNexusFriendData::id, SeDBStream::InitData, SeCharNexusFriendData::mark, SeCharNexusFriendData::name, SBBR_NONE, SDTI_CharNexusFriend, SendWB_DataInsert, SeDBStream::WriteDBTime, SeDBStream::WriteDoubleDword, SeDBStream::WriteDword, SeDBStream::WriteString.
Referenced by BlockServer::ProcessWBL_CreateNexusFriend, BlockServer::ProcessWBL_CreateNexusOfflineFriend.
bool WorldServer::SendDBServer_NexusFriendUpdate(DWord dwPlayerID, const SeCharNexusFriendData &rkData)
References SeCharNexusFriendData::char_friend_id, SeCharNexusFriendData::char_id, SeDBStream::GetCurPos, SeDBStream::GetData, SeCharNexusFriendData::id, SeDBStream::InitData, SeCharNexusFriendData::mark, SBBR_NONE, SDTI_CharNexusFriend, SendWB_DataUpdate, SeDBStream::WriteDoubleDword, SeDBStream::WriteDword.
Referenced by BlockServer::ProcessWBL_UpdateNexusFriend.
bool WorldServer::SendDBServer_NexusFriendDelete(DWord dwPlayerID, DWord dwID)
References SDTI_CharNexusFriend, SendWB_DataDelete.
Referenced by BlockServer::ProcessWBL_DelNexusFriend.
bool WorldServer::SendDBServer_CharUpdateMisc(DWord dwPlayerID, SeCharMiscType eType, const SeDBTime &time)
References CMT_BATTLETIME, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SeLogError, SendWB_DataUpdate, SeDBStream::WriteDBTime, SeDBStream::WriteDword.
bool WorldServer::SendDBServer_CharUpdateMisc(DWord dwPlayerID, SeCharMiscType eType, const char *str)
References CMT_NAME, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SBBR_NONE, SDTI_CharInfo, SeLogError, SendWB_DataUpdate, SeDBStream::WriteDword, SeDBStream::WriteString.
bool WorldServer::ProcessLWData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WorldServer::PreProcessLW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessLW_Register(SeLW_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeWorldConfig::dwAreaID, SeLW_Register::dwLoginMagic, SeLW_Register::dwServerID, SeConnect::dwServerID, SeVirtConn::eState, GetID2Str, moba::Clock::getInstance, GetLSByServerID, moba::Clock::getMilliSeconds, SeNetAddr::iPort, IsAllTownLoadComplete, IsDBReady, IsWSReady, SeConnect::kNetAddr, SeConnect::kSock, m_kAllLS, m_kConfig, m_kNetMgr, m_pkDBSConn, SeLogError, SeLogInfo, SendWL_RegisterRet, SRR_FAILED, SRR_REPEAT, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_LS, SSI_UNKNOWN, SVCS_REGISTERED.
void WorldServer::ProcessLW_HeartPackage(SeLW_HeartPackage *pkData, int iSize, void *pkSender)
References SeConnect::kSock, SendWL_HeartPackageRet.
void WorldServer::ProcessLW_KickAccount(SeLW_KickAccount *pkData, int iSize, void *pkSender)
References SeLW_KickAccount::dwPlayerID, KickPlayerByID, SeLogDebug.
void WorldServer::ProcessLW_AccountLogin(SeLW_AccountLogin *pkData, int iSize, void *pkSender)
References SeLW_AccountLogin::dwPackKey, SeLW_AccountLogin::dwPlayerID, g_kWorldServer, SeTown::GetAddrToPlayer, GetHasDBError, SeLW_AccountLogin::kAccountInfo, KickPlayerByID, SeConnect::kSock, LFR_WS_DB_ERROR, m_kAllTS, RandInt, SDER_NONE, SeLogError, SendWBL_AccountLogin, SendWL_LoginFailed, SendWL_LoginSuccess.
void WorldServer::ProcessLW_AccountWillLogin(SeLW_AccountWillLogin *pkData, int iSize, void *pkSender)
References SeLW_AccountWillLogin::dwPlayerID, GetPlayerTownSock, OnSendShowNoticeWithoutString, SNC_ACCOUNT_WILL_LOGIN.
bool WorldServer::ProcessTWData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WorldServer::PreProcessTW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_Register(SeTW_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, moba::ServerSessionMgr::checkServer, moba::ServerSessionMgr::createServer, SeWorldConfig::dwAreaID, SeConnect::dwServerID, SeTW_Register::dwServerID, SeTW_Register::dwTownMagic, SeVirtConn::eState, g_kTownServerMgr, SeTown::GetConnect, GetID2Str, SeTown::GetServerID, SeTown::GetTownIndex, GetTSByID, SeTown::Initialize, SeNetAddr::iPort, SeTown::IsClosed, IsWSReady, SeTW_Register::kInfo, SeConnect::kNetAddr, SeConnect::kSock, m_kAllDisconnectTS, m_kAllTS, m_kConfig, m_kNetMgr, m_pkDBSConn, SeLogError, SeLogInfo, SendWT_RegisterRet, SeTown::SetClosed, SeTown::SetConnect, SRR_REPEAT, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_TS, SSI_UNKNOWN, SVCS_REGISTERED.
void WorldServer::ProcessTW_HeartPackage(SeTW_HeartPackage *pkData, int iSize, void *pkSender)
References GetServerTime, GetTSBySock, SeConnect::kSock, SendWT_HeartPackageRet, SeTown::SetLastRecvTime.
void WorldServer::ProcessTW_LoadPlayerInfoAgain(SeTW_LoadPlayerInfoAgain *pkData, int iSize, void *pkSender)
References SeTW_LoadPlayerInfoAgain::akPlayerInfo, SeLoadPlayerInfoAgain::dwPlayerID, g_kWorldServer, GetBlockServerNum, SeTown::GetHSock, GetID2Str, SeTown::GetLoadAgainPlayer, SeTown::GetServerID, GetServerTime, SeTown::GetTownIndex, GetTSBySock, SeTW_LoadPlayerInfoAgain::iBegin, SeTW_LoadPlayerInfoAgain::iNum, IsWSReady, SeTW_LoadPlayerInfoAgain::iTotalNum, SeConnect::kSock, SeTown::PushLoadPlayerID, SeLogInfo, SendWBL_LoadPlayerInfoAgain, SendWT_IsReady, SendWT_LoadPlayerInfoAgainRet, SeTown::SetPlayerNum.
void WorldServer::ProcessTW_PlayerValidate(SeTW_PlayerValidate *pkData, int iSize, void *pkSender)
References SeTW_PlayerValidate::dwClientID, SeTW_PlayerValidate::dwMaxMailID, SeTW_PlayerValidate::dwPlayerID, SeTW_PlayerValidate::dwPlayerIP, SeTW_PlayerValidate::dwSessionID, GET_CUR_CONN_AND_TOWN, SeTW_PlayerValidate::kMobileInfo, SendWBL_PlayerValidate.
void WorldServer::ProcessTW_QueryName(SeTW_QueryName *pkData, int iSize, void *pkSender)
References SeTW_QueryName::acName, SeTW_QueryName::dwPlayerID, GET_CUR_CONN_AND_TOWN, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, MemCpy, SeLogError, SendWB_IsPlayerExist, SendWT_QueryNameRet, SPEQ_CHAR_QUERY_NAME_BY_NAME, SSD_MAX_CHAR_NAME, SSD_MIN_CHAR_NAME, SeDBStream::WriteDword.
void WorldServer::ProcessTW_CreateChar(SeTW_CreateChar *pkData, int iSize, void *pkSender)
References SeTW_CreateChar::acName, SeTW_CreateChar::dwPlayerID, SeTW_CreateChar::iSex, MemCpy, SeLogInfo, SendWBL_CreateChar, SSD_MAX_CHAR_NAME, SSD_MIN_CHAR_NAME.
void WorldServer::ProcessTW_PlayerLeave(SeTW_PlayerLeave *pkData, int iSize, void *pkSender)
References SeTW_PlayerLeave::bExitGame, SeTW_PlayerLeave::dwPlayerID, SeTown::GetTownIndex, GetTSBySock, SeConnect::kSock, OnPlayerLeave.
void WorldServer::ProcessTW_RaceEndRace(SeTW_RaceEndRace *pkData, int iSize, void *pkSender)
References SeTW_RaceEndRace::akInfo, DelReconPlayer, SeWorldConfig::dwAreaID, SeWSRaceSendInfo::dwAreaID, SeTW_RaceEndRace::dwMapID, SeWSRaceSendInfo::dwPlayerID, SeTW_RaceEndRace::dwRoomSession, SeTW_RaceEndRace::dwTime, SeWSRaceSendInfo::eCmp, SeTW_RaceEndRace::eMatchType, MapInfoTableMgr::Get, GetBlockServerNum, GetID2Str, MapInfoTableMgr::GetMapInfoTable, GetPlayerTownSock, GetRaceAreaInfo, SeTown::GetTownIndex, GetTSBySock, SeTW_RaceEndRace::iNum, SeRaceSendInfo::iRaceEndFlag, SeWSRaceSendInfo::kInfo, SeConnect::kSock, m_kConfig, OnHeroEndStat, OnSendBSRaceEndRace, SeLogInfo, SROT_RRESULT_INVILAD.
void WorldServer::ProcessTW_RaceEndGuanka(SeTW_RaceEndGuanka *pkData, int iSize, void *pkSender)
References SeTW_RaceEndGuanka::akInfo, DelReconPlayer, SeTW_RaceEndGuanka::dwMapID, SeWSGuanqiaSendInfo::dwPlayerID, SeTW_RaceEndGuanka::dwTime, GetBlockServerNum, SeTW_RaceEndGuanka::iNum, OnSendBSRaceEndGuanQia.
void WorldServer::ProcessTW_ItemExchange(SeTW_ItemExchange *pkData, int iSize, void *pkSender)
References SeTW_ItemExchange::dwPlayerID, SeTW_ItemExchange::iTypeID, SendWBL_ItemExchange.
void WorldServer::ProcessTW_SavePlayerReconInfo(SeTW_SavePlayerReconInfo *pkData, int iSize, void *pkSender)
References SePlayerReconInfo::dwDisconTime, SeTW_SavePlayerReconInfo::dwPlayerID, SePlayerReconInfo::dwRoomID, SeTW_SavePlayerReconInfo::dwRoomID, g_kWorldServer, GetServerTime, SePlayerReconInfo::iSeatIndex, SeTW_SavePlayerReconInfo::iSeatIndex, m_kMID2ReconInfo, SeLogInfo.
void WorldServer::ProcessTW_TaskQueryList(SeTW_TaskQueryList *pkData, int iSize, void *pkSender)
References SeTW_TaskQueryList::dwPlayerID, SendWBL_TaskQueryList.
void WorldServer::ProcessTW_TaskResel(SeTW_TaskResel *pkData, int iSize, void *pkSender)
References SeTW_TaskResel::dwPlayerID, SeTW_TaskResel::dwTaskID, SendWBL_TaskResel.
void WorldServer::ProcessTW_GetTaskReward(SeTW_GetTaskReward *pkData, int iSize, void *pkSender)
References SeTW_GetTaskReward::dwPlayerID, SeTW_GetTaskReward::dwTaskID, SendWBL_TaskGetAward.
void WorldServer::ProcessTW_MatchRaceLoad(SeTW_MatchRaceLoad *pkData, int iSize, void *pkSender)
References SeTW_MatchRaceLoad::dwMapID, SeTW_MatchRaceLoad::dwPlayerID, SeTW_MatchRaceLoad::dwRoomSession, SendWBL_MatchRaceLoad.
void WorldServer::ProcessTW_DelReconInfo(SeTW_DelReconInfo *pkData, int iSize, void *pkSender)
References DelReconPlayer, SeTW_DelReconInfo::dwPlayerID.
void WorldServer::ProcessTW_PlayerRename(SeTW_PlayerRename *pkData, int iSize, void *pkSender)
References SeTW_PlayerRename::acName, SeTW_PlayerRename::dwPlayerID, SendWBL_PlayerRenameBegin.
void WorldServer::ProcessTW_RaceBuy(SeTW_RaceBuy *pkData, int iSize, void *pkSender)
References SeTW_RaceBuy::dwParam1, SeTW_RaceBuy::dwParam2, SeTW_RaceBuy::dwPlayerID, SeTW_RaceBuy::dwSession, SeTW_RaceBuy::iType, SendWBL_RaceBuy.
void WorldServer::ProcessTW_MapTaskOpr(SeTW_MapTaskOpr *pkData, int iSize, void *pkSender)
References SeTW_MapTaskOpr::dwParam, SeTW_MapTaskOpr::dwPlayerID, SeTW_MapTaskOpr::iOprType, SendWBL_MapTaskOpr.
void WorldServer::ProcessTW_QueryNearestRaceInfo(SeTW_QueryNearestRaceInfo *pkData, int iSize, void *pkSender)
References SeTW_QueryNearestRaceInfo::dwMapID, SeTW_QueryNearestRaceInfo::dwPlayerID, SeTW_QueryNearestRaceInfo::dwQueriedID, SendHS_QueryNearestRaceInfo.
void WorldServer::ProcessTW_PlayerLeaveRace(SeTW_PlayerLeaveRace *pkData, int iSize, void *pkSender)
References DelReconPlayer, SeTW_PlayerLeaveRace::dwPlayerID, GetBlockServerNum, SeTown::GetTownIndex, GetTSBySock, SeConnect::kSock, SeLogDebug.
void WorldServer::ProcessTW_BuyShopItem(SeTW_BuyShopItem *pkData, int iSize, void *pkSender)
References SeTW_BuyShopItem::dwPlayerID, SeTW_BuyShopItem::Num, SendWBL_BuyShopItem, SeTW_BuyShopItem::ShopID, SeTW_BuyShopItem::types.
void WorldServer::ProcessTW_ShopItemGM(SeTW_ShopItemGM *pkData, int iSize, void *pkSender)
References SeTW_ShopItemGM::dwPlayerID, SeTW_ShopItemGM::GmItems, SeTW_ShopItemGM::iNum, SendWBL_ShopItemGM.
void WorldServer::ProcessTW_GetItemGM(SeTW_GetItemGM *pkData, int iSize, void *pkSender)
References SeTW_GetItemGM::dwPlayerID, SendWBL_GetItemGM, SeTW_GetItemGM::ShopID.
void WorldServer::ProcessTW_SearchUserArchivesInfoReq(SeTW_SearchUserArchivesInfoReq *pkData, int iSize, void *pkSender)
References SeUserArchivesNameInfo::acName, SeTW_SearchUserArchivesInfoReq::dwPlayerID, GET_CUR_CONN_AND_TOWN, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, MemCpy, SeLogError, SendWB_IsPlayerExist, SPEQ_CHAR_QUERY_NAME_BY_NAME, SSD_MAX_CHAR_NAME, SSD_MIN_CHAR_NAME, SeTW_SearchUserArchivesInfoReq::username, SeDBStream::WriteDword.
void WorldServer::ProcessTW_SearchUserArchivesDetailInfoReq(SeTW_SearchUserArchivesDetailInfoReq *pkData, int iSize, void *pkSender)
References SeTW_SearchUserArchivesDetailInfoReq::dwPlayerID, GET_CUR_CONN_AND_TOWN, SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SendWB_IsPlayerExist, SPEQ_CHAR_QUERY_NAME_BY_USERID, SeTW_SearchUserArchivesDetailInfoReq::userid, SeDBStream::WriteDword.
void WorldServer::ProcessHSData(void *pkData, int iSize, void *pkSender=NULL)
References CMD_HS_HEARTPACKAGE, CMD_HS_REGISTER, CMD_HS_UPS_QUERY_NEAREST_RACE_INFO_RET, ProcessHS_HeartPackage, ProcessHS_QueryNearestRaceInfoRet, ProcessHS_Register, SeCMD::wCmd.
Referenced by OnNetRecv.
void WorldServer::ProcessHS_Register(void *pkData, int iSize, void *pkSender=NULL)
References SeNetAddr::acIP, SeConnect::dwServerID, SeVirtConn::eState, GetHSByServerID, GetID2Str, moba::Clock::getInstance, moba::Clock::getMilliSeconds, SeHS_Register::iMagic, SeNetAddr::iPort, IsAllTownLoadComplete, IsDBReady, SeHS_Register::iServerID, IsWSReady, SeConnect::kNetAddr, SeConnect::kSock, m_kAllHS, m_kNetMgr, m_pkDBSConn, SeLogError, SeLogInfo, SendHS_RegisterRet, SRR_FAILED, SRR_REPEAT, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_HS, SSI_UNKNOWN, SVCS_REGISTERED.
Referenced by ProcessHSData.
void WorldServer::ProcessHS_HeartPackage(void *pkData, int iSize, void *pkSender=NULL)
References SeConnect::kSock, SendHS_HeartPackageRet.
Referenced by ProcessHSData.
void WorldServer::ProcessHS_QueryNearestRaceInfoRet(void *pkData, int iSize, void *pkSender=NULL)
References SePtlRaceHistory::acCreateTime, SePtlRaceHistory::acRaceID, SeHS_UPSQueryNearestRaceInfoRet::akJson, Json::Value::asCString, SePtlRaceHistory::dwHeroID, SePtlRaceHistory::dwMapID, SeHS_UPSQueryNearestRaceInfoRet::dwPlayerID, SeHS_UPSQueryNearestRaceInfoRet::dwQueryID, GetMD5Str2MD5, GetPlayerTownSock, SePtlRaceHistory::iDeath, SePtlRaceHistory::iKill, SeHS_UPSQueryNearestRaceInfoRet::iNum, SePtlRaceHistory::iResult, Json::Value::isObject, Json::Value::isString, MemCpy, SendWT_QueryNearestRaceInfoRet, Json::Value::size, StrCpy.
Referenced by ProcessHSData.
bool WorldServer::ProcessBWData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WorldServer::PreProcessBW(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, GetServerTime, m_pkDBSConn.
void WorldServer::ProcessBW_RegisterRet(SeBW_RegisterRet *pkData, int iSize, void *pkSender)
References SeBW_RegisterRet::bRegisterRet, SeOnlinePlayer::dwPlayerID, SeVirtConn::eState, g_kLadderLevelMgr, g_kLadderRankMgr, g_kPlayerDataMgr, GetHasDBError, PlayerDataMgr::initGenID, LadderLevelMgr::loadDBData, LadderRankMgr::loadLadderRankInfoDBData, m_bSysDBDataInit, m_kOnlinePlayer, m_pkDBSConn, OnSendDBSLoadPlayerInfoAgain, SDER_DB_DISCONNECT, SDER_NONE, SDTI_NONE, SeLogInfo, SendWB_InitGenID, SetDBReady, SetHasDBError, SIGT_NEXUSFRIEND, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void WorldServer::ProcessBW_InitGenIDRet(SeBW_InitGenIDRet *pkData, int iSize, void *pkSender)
References SeBW_InitGenIDRet::bSuccess, SeBW_InitGenIDRet::dwGenID, SeBW_InitGenIDRet::eTableIndex, SeBW_InitGenIDRet::eType, g_kPlayerDataMgr, g_kWorldServer, GetTableName, m_dwGenNexuseFriendID, PlayerDataMgr::onInitGenIDRet, SeLogError, SeLogInfo, SetInitFlag, SIGT_NEXUSFRIEND, SIGT_NULL, SPrintf, StrCpy, SWIF_GENERATEID_NEXUSFRIEND.
void WorldServer::ProcessBW_DBServerError(SeBW_DBServerError *pkData, int iSize, void *pkSender)
References SeBW_DBServerError::iErrorID, SetHasDBError.
void WorldServer::ProcessBW_HeartPackageRet(SeBW_HeartPackageRet *pkData, int iSize, void *pkSender)
References GetHasDBError, SDER_DB_DISCONNECT, SDER_NONE, SetHasDBError.
void WorldServer::ProcessBW_DataInsertRet(SeBW_DataInsertRet *pkData, int iSize, void *pkSender)
References SeBW_DataInsertRet::dwID, SeBW_DataInsertRet::dwPara1, SeBW_DataInsertRet::eReceipt, SBBR_CHAR_ADD, SeDBSerProcess_CharAdd.
void WorldServer::ProcessBW_DBQueryRet(SeBW_DBQueryRet *pkData, int iSize, void *pkSender)
References SeBW_DBQueryRet::acData, SeDBStream::Attach, SeBW_DBQueryRet::bSendOver, SeBW_DBQueryRet::eType, SeBW_DBQueryRet::iNowSendNum, SeBW_DBQueryRet::iSize, SDQT_CHAR_LOGIN_LOAD, SDQT_CHAR_QUERY_VALID, SDQT_CHAR_RENAME, SeDBSerProcess_CharLoginLoad, SeDBSerProcess_CharQueryValid, SeDBSerProcess_CharRename, SeLogError, SSD_ENDSTR_LEN.
void WorldServer::ProcessBW_IsPlayerExistRet(SeBW_IsPlayerExistRet *pkData, int iSize, void *pkSender)
References SeBW_IsPlayerExistRet::acData, SeBW_IsPlayerExistRet::acName, SeUserArchivesInfo::acName, SeDBStream::Attach, SeBW_IsPlayerExistRet::bExist, SeBW_IsPlayerExistRet::dwPlayerID, SeUserArchivesInfo::dwPlayerId, SeBW_IsPlayerExistRet::eType, EUAS_NAME_REPEAT, EUAS_SUCCESS, SeTown::GetHSock, GetTSByIndex, SeBW_IsPlayerExistRet::iSize, SeDBStream::ReadDword, SeLogError, SendWBL_UserAlterNickNameReq, SendWT_SearchUserArchivesDetailInfoRes, SendWT_SearchUserArchivesInfoRes, SPEQ_CHAR_CHECK_NAME, SPEQ_CHAR_QUERY_NAME_BY_NAME, SPEQ_CHAR_QUERY_NAME_BY_USERID, SSD_ENDSTR_LEN.
void WorldServer::ProcessBW_TabSelectRet(SeBW_TabSelectRet *pkData, int iSize, void *pkSender)
References g_kTabMgr, TabMgr::onTabSelectRet.
void WorldServer::SeDBSerProcess_CharLoginLoad(int iNowSendNum, bool bSendOver, SeDBStream &rkDBStream)
References DelLSPlayer, SeTown::GetAddrToPlayer, GetLSByPlayerID, SeConnect::kSock, m_kAllTS, SeDBStream::ReadDword, SendWL_LoginSuccess.
Referenced by ProcessBW_DBQueryRet.
void WorldServer::SeDBSerProcess_CharQueryValid(int iNowSendNum, bool bSendOver, SeDBStream &rkDBStream)
References GetTSByIndex, SeDBStream::ReadDword, SeLogError, SendWBL_PlayerValidateEnd, SVT_CHAR_NOT_EXIST, SVT_GAME_DB_ERROR, SVT_VALIDATE_OK.
Referenced by ProcessBW_DBQueryRet.
void WorldServer::SeDBSerProcess_CharAdd(DWord dwPlayerID, SeCreateCharRet eRet)
References g_kWorldServer, SendWBL_CharAddRet.
Referenced by ProcessBW_DataInsertRet.
void WorldServer::SeDBSerProcess_CharRename(int iNowSendNum, bool bSendOver, SeDBStream &rkDBStream)
References SeDBStream::IsEnd, SeDBStream::ReadDword, SeDBStream::ReadString, SeLogError, SendWBL_PlayerRenameEnd, SSD_MAX_CHAR_NAME, StrCpy.
Referenced by ProcessBW_DBQueryRet.
bool WorldServer::ProcessBLWData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by UpdateWSMsg.
bool WorldServer::PreProcessBLW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBLW_TSIncNum(SeBLW_TSIncNum *pkData, int iSize, void *pkSender)
References SeTown::GetPlayerNum, GetTSByIndex, SeBLW_TSIncNum::iNum, SeBLW_TSIncNum::iTownIndex, SeTown::SetPlayerNum.
void WorldServer::ProcessBLW_ShowNotice(SeBLW_ShowNotice *pkData, int iSize, void *pkSender)
References SeBLW_ShowNotice::acMessage, SeBLW_ShowNotice::dwPlayerID, GetPlayerTownSock, SeBLW_ShowNotice::iSize, MemCpy.
void WorldServer::ProcessBLW_LoadPlayerInfoAgainRet(SeBLW_LoadPlayerInfoAgainRet *pkData, int iSize, void *pkSender)
References SeBLW_LoadPlayerInfoAgainRet::adwPlayerID, SeTown::DelLoadPlayerID, GetTSByIndex, SeBLW_LoadPlayerInfoAgainRet::iNum, SeBLW_LoadPlayerInfoAgainRet::iTownIndex.
void WorldServer::ProcessBLW_PlayerLeave(SeBLW_PlayerLeave *pkData, int iSize, void *pkSender)
References SeBLW_PlayerLeave::byPlayerLeaveRet, SeTown::DecPlayerNum, DelOnlinePlayer, SeBLW_PlayerLeave::dwPlayerID, g_kWorldServer, SeTown::GetHSock, GetTSByIndex, SeBLW_PlayerLeave::iTownIndex, SendWT_PlayerLeave.
void WorldServer::ProcessBLW_PlayerLoadComplete(SeBLW_PlayerLoadComplete *pkData, int iSize, void *pkSender)
References SeBLW_PlayerLoadComplete::acPlayerName, SeOnlinePlayer::acPlayerName, AddOnlinePlayer, SePlayerReconInfo::dwDisconTime, SeBLW_PlayerLoadComplete::dwLoadConsumeTime, SeBLW_PlayerLoadComplete::dwPlayerID, SeOnlinePlayer::dwPlayerID, SePlayerReconInfo::dwRoomID, g_kWorldServer, GetPlayerTownSock, GetReconnTime, GetReconPlayer, GetServerTime, SePlayerReconInfo::iSeatIndex, SeBLW_PlayerLoadComplete::iTownIndex, SeOnlinePlayer::iTownIndex, m_dwLoadCount, m_dwLoadSumTime, SendWT_QueryPlayerReconInfo, StrCpy.
void WorldServer::ProcessBLW_PlayerOperRep(SeBLW_PlayerOperRep *pkData, int iSize, void *pkSender)
References SeBLW_PlayerOperRep::dwPlayerID, g_kWorldServer, SeTown::GetHSock, GetOnlinePlayer, GetTSByIndex, SeBLW_PlayerOperRep::iResult, SeOnlinePlayer::iTownIndex, SeLogInfo, SendWT_PlayerOperRep.
void WorldServer::ProcessBLW_ShopItemGmRep(SeBLW_ShopItemGmRep *pkData, int iSize, void *pkSender)
References SeBLW_ShopItemGmRep::dwPlayerID, g_kWorldServer, SeTown::GetHSock, GetOnlinePlayer, GetTSByIndex, SeBLW_ShopItemGmRep::GmItem, SeBLW_ShopItemGmRep::iResult, SeOnlinePlayer::iTownIndex, SeLogInfo, SendWT_ShopItemGmRep.
DWord WorldServer::GenNexusFriendID()
References m_dwGenNexuseFriendID, m_kGenIDLock, SeLogError.
Referenced by BlockServer::ProcessWBL_CreateNexusFriend, BlockServer::ProcessWBL_CreateNexusOfflineFriend.
DWord WorldServer::GenNexusPromotionID()
References m_dwGenNexusPromotionID, m_kGenIDLock, SeLogError.
DWord WorldServer::GenCharRaceArenaID()
References m_dwGenCharRaceArenaID, m_kGenIDLock, SeLogError.
DWord WorldServer::GenNexusTeamID()
References m_dwGenNexusTeamID, m_kGenIDLock, SeLogError.
DWord WorldServer::GenNexusTeamMemberID()
References m_dwGenNexusTeamMemberID, m_kGenIDLock, SeLogError.
DWord WorldServer::GetServerTime(void)
References m_dwCurTime.
Referenced by OnNetRecv, OnTSDisconnect, PreProcessBW, ProcessBLW_PlayerLoadComplete, ProcessTW_HeartPackage, ProcessTW_LoadPlayerInfoAgain, ProcessTW_SavePlayerReconInfo, UpdateDisconnectTS, UpdateHSToWSTime, UpdateLeagueInfo, SeTown::UpdateLoadData, UpdateLogHeroEndStat, UpdateLogShow, UpdateLSToWSTime, UpdatePlayerReconInfo, UpdateQueryFreeHeroList, UpdateTSTOWSTime, UpdateUnknownState.
int WorldServer::GetPlayerNum(void)
References m_kOnlinePlayer.
Referenced by ShowConsoleTitle.
int WorldServer::RandInt(void)
References m_kRandNum, SeRandNum::RandInt.
Referenced by TaskMgr::GetDailyTaskNextTask, TaskMgr::GetTaskConditionNum, TaskMgr::GetWinTaskNextTask, SeResMgr::openRandBox, ProcessLW_AccountLogin, SeResMgr::randomItem.
int WorldServer::RandInt(int iMin, int iMax)
References m_kRandNum, SeRandNum::RandInt.
float WorldServer::RandFloat(float fMin, float fMax)
References m_kRandNum, SeRandNum::RandFloat.
void WorldServer::AddOnlinePlayer(DWord dwPlayerID, const SeOnlinePlayer &rkOnlinePlayer)
References m_kOnlinePlayer.
Referenced by ProcessBLW_PlayerLoadComplete.
void WorldServer::DelOnlinePlayer(DWord dwPlayerID)
References m_kOnlinePlayer.
Referenced by ProcessBLW_PlayerLeave.
const SeOnlinePlayer * WorldServer::GetOnlinePlayer(DWord dwPlayerID)
References m_kOnlinePlayer.
Referenced by ProcessBLW_PlayerOperRep, ProcessBLW_ShopItemGmRep.
HSock WorldServer::GetPlayerTownSock(DWord dwPlayerID)
References g_kWorldServer, SeTown::GetHSock, GetTSByIndex, SeOnlinePlayer::iTownIndex, m_kOnlinePlayer.
Referenced by ProcessBLW_PlayerLoadComplete, ProcessBLW_ShowNotice, ProcessHS_QueryNearestRaceInfoRet, ProcessLW_AccountWillLogin, ProcessTW_RaceEndRace.
void WorldServer::OnSendDBPlayerLoad(DWord dwPlayerID)
References SeDBStream::GetCurPos, SeDBStream::GetData, SeDBStream::InitData, SendWB_PlayerLoad, SeDBStream::WriteDword.
Referenced by BlockServer::ProcessWBL_CharAddRet, BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerValidateEnd.
void WorldServer::OnSendDBSLoadPlayerInfoAgain(void)
References SeOnlinePlayer::dwPlayerID, m_kOnlinePlayer, SeLogInfo, SendWB_LoadPlayerInfoAgain.
Referenced by ProcessBW_RegisterRet.
const SePlayerReconInfo * WorldServer::GetReconPlayer(DWord dwPlayerID)
References m_kMID2ReconInfo.
Referenced by ProcessBLW_PlayerLoadComplete.
void WorldServer::DelReconPlayer(DWord dwPlayerID)
References m_kMID2ReconInfo.
Referenced by ProcessTW_DelReconInfo, ProcessTW_PlayerLeaveRace, ProcessTW_RaceEndGuanka, ProcessTW_RaceEndRace.
void WorldServer::UpdatePlayerReconInfo(void)
References SePlayerReconInfo::dwDisconTime, g_kWorldServer, GetReconnTime, GetServerTime, m_kMID2ReconInfo.
void WorldServer::OnSendBSRaceEndRace(DWord dwThreadNum, DWord dwMapID, DWord dwRoomSession, int iTownIndex, DWord dwTime, int iNum, bool bAutoMatchRace, const VWSRaceSendInfo &akRaceSendInfo, const char *pcAreaInfo, SeMatchRaceType eMatchType)
References SeWBL_RaceEndRace::acAreaInfo, SeWBL_RaceEndRace::akInfo, SeWBL_RaceEndRace::bAutoMatchRace, SeWBL_RaceEndRace::dwMapID, SeWBL_RaceEndRace::dwRoomSession, SeWBL_RaceEndRace::dwTime, SeWBL_RaceEndRace::eMatchType, g_kWorldServer, SeWBL_RaceEndRace::iNum, SeWBL_RaceEndRace::iTownIndex, MNew, PushThreadMsgByNum, SSD_SEND_SIZE, StrCpy.
Referenced by ProcessTW_RaceEndRace.
void WorldServer::OnSendBSRaceEndGuanQia(DWord dwThreadNum, DWord dwMapID, DWord dwTime, int iNum, const VWSGuanqiaSendInfo &akRaceSendInfo, bool bAutoMatchRace)
References SeWBL_RaceEndGuanka::akInfo, SeWBL_RaceEndGuanka::dwMapID, SeWBL_RaceEndGuanka::dwTime, g_kWorldServer, SeWBL_RaceEndGuanka::iNum, MNew, PushThreadMsgByNum, SSD_SEND_SIZE.
Referenced by ProcessTW_RaceEndGuanka.
bool WorldServer::IsException(void)
References m_bException.
Referenced by Update, BlockServer::Update.
void WorldServer::SetException(void)
References m_bException.
Referenced by BlockServer::Update.
bool WorldServer::IsAllTownLoadComplete(void)
References SeTown::LoadComplete, m_kAllTS.
Referenced by ProcessHS_Register, ProcessLW_Register.
bool WorldServer::SwitchWSReady(void)
References m_bForceWSStop, m_bWSReady, SeLogError, SeLogInfo, SetWSReady.
void WorldServer::SetWSReady(bool bReady)
References SeTown::GetHSock, m_bWSReady, m_kAllTS, SendWT_IsReady.
Referenced by SetHasDBError, SwitchWSReady, Update.
bool WorldServer::IsWSReady()
References m_bWSReady.
Referenced by ProcessHS_Register, ProcessLW_Register, ProcessTW_LoadPlayerInfoAgain, ProcessTW_Register, Update, UpdateDisconnectTS.
void WorldServer::SetDBReady(bool bReady)
References m_bBSReady.
Referenced by ProcessBW_RegisterRet, SetHasDBError.
bool WorldServer::IsDBReady()
References m_bBSReady.
Referenced by ProcessHS_Register, ProcessLW_Register, SendWBData, Update.
void WorldServer::SetInitFlag(int iFlag)
References m_iInitFlag.
Referenced by ProcessBW_InitGenIDRet.
bool WorldServer::HasInitFlag(int iFlag)
References m_iInitFlag.
Referenced by Update.
SeConnect * WorldServer::GetLS()
References m_kAllLS.
Referenced by OnSendLSPlayerLogout, OnSendLSPlayerTownIndex.
SeConnect * WorldServer::GetLSBySock(HSock kSock)
References m_kAllLS.
SeConnect * WorldServer::GetLSByPlayerID(DWord dwPlayerID)
References GetLSByServerID, m_kPlayerID2LS.
Referenced by SeDBSerProcess_CharLoginLoad.
SeConnect * WorldServer::GetLSByServerID(DWord dwServerID)
References SeConnect::dwServerID, m_kAllLS.
Referenced by GetLSByPlayerID, ProcessLW_Register.
void WorldServer::DelLSPlayer(DWord dwPlayerID)
References m_kPlayerID2LS.
Referenced by SeDBSerProcess_CharLoginLoad.
void WorldServer::OnLSDisconnect(DWord dwServerID)
References SeConnect::dwServerID, m_kAllLS.
Referenced by OnNetDisconnect.
void WorldServer::OnSendLSPlayerLogout(DWord dwPlayerID)
References GetLS, SeConnect::kSock, SendWL_PlayerLogout.
Referenced by BlockServer::UpdateWaitPlayer.
void WorldServer::OnSendLSPlayerTownIndex(DWord dwPlayerID, int iTownIndex)
References GetLS, SeConnect::kSock, SendWL_PlayerTownIndex.
Referenced by BlockServer::ProcessWBL_CharAddRet, BlockServer::ProcessWBL_PlayerValidateEnd.
SeConnect * WorldServer::GetHS()
References m_kAllHS.
Referenced by UpdateQueryFreeHeroList.
SeConnect * WorldServer::GetHSBySock(HSock kSock)
References m_kAllHS.
SeConnect * WorldServer::GetHSByServerID(DWord dwServerID)
References SeConnect::dwServerID, m_kAllHS.
Referenced by ProcessHS_Register.
void WorldServer::OnHSDisconnect(DWord dwServerID)
References SeConnect::dwServerID, m_kAllHS.
Referenced by OnNetDisconnect.
SeTown * WorldServer::GetTSByID(DWord dwServerID)
References SeTown::GetServerID, m_kAllTS.
Referenced by ProcessTW_Register, UpdateDisconnectTS.
SeTown * WorldServer::GetTSByIndex(int iTownIndex)
References SeTown::GetTownIndex, m_kAllTS.
Referenced by GetPlayerTownSock, ProcessBLW_LoadPlayerInfoAgainRet, ProcessBLW_PlayerLeave, ProcessBLW_PlayerOperRep, ProcessBLW_ShopItemGmRep, ProcessBLW_TSIncNum, ProcessBW_IsPlayerExistRet, SeDBSerProcess_CharQueryValid.
SeTown * WorldServer::GetTSBySock(HSock kSock)
References m_kAllTS.
Referenced by ProcessTW_HeartPackage, ProcessTW_LoadPlayerInfoAgain, ProcessTW_PlayerLeave, ProcessTW_PlayerLeaveRace, ProcessTW_RaceEndRace.
bool WorldServer::HasTownIndex(int iTownIndex)
References SeTown::GetTownIndex, m_kAllTS.
void WorldServer::OnTSDisconnect(DWord dwServerID)
References SeDisconnectTSInfo::dwDisconnectTime, SeTown::GetServerID, GetServerTime, SeTown::GetTownIndex, SeDisconnectTSInfo::iTownIndex, m_kAllDisconnectTS, m_kAllTS.
Referenced by OnNetDisconnect.
int WorldServer::GetTSNum(void)
References m_kAllTS.
Referenced by ShowConsoleTitle.
void WorldServer::DisconnectAllTown(void)
void WorldServer::SetHasDBError(SeDBError eErrorCode)
References g_kWorldServer, GetBlockServerNum, m_eDBServerErrorCode, SDER_DB_DISCONNECT, SDER_DB_ERROR_RET, SDER_NONE, SeLogError, SeLogInfo, SendWBL_HasDBError, SetDBReady, SetWSReady.
Referenced by OnNetDisconnect, ProcessBW_DBServerError, ProcessBW_HeartPackageRet, ProcessBW_RegisterRet.
SeDBError WorldServer::GetHasDBError(void)
References m_eDBServerErrorCode.
Referenced by ProcessBW_HeartPackageRet, ProcessBW_RegisterRet, ProcessLW_AccountLogin.
int WorldServer::GetBlockServerNum(void)
References m_iBlockServerNum.
Referenced by LoadDynamicConfig, ProcessTW_LoadPlayerInfoAgain, ProcessTW_PlayerLeaveRace, ProcessTW_RaceEndGuanka, ProcessTW_RaceEndRace, PushThreadMsgByNum, SetHasDBError, UpdateDisconnectTS, UpdateLeagueInfo.
bool WorldServer::PushThreadMsg(DWord dwPlayerID, void *pkData, int iSize)
References m_iBlockServerNum, m_pakBlockServer, BlockServer::PushMsg, SeLogError.
Referenced by OnNetRecv, SendWBLData.
bool WorldServer::PushThreadMsgByNum(int iBlockServer, void *pkData, int iSize)
References GetBlockServerNum, m_pakBlockServer, BlockServer::PushMsg, SeLogError.
Referenced by OnSendBSRaceEndGuanQia, OnSendBSRaceEndRace.
bool WorldServer::PushWSMsg(void *pkData, int iSize)
References m_kThreadMsgMgr, SeThreadMsgMgr::PushMsg.
Referenced by BlockServer::SendBLWData.
bool WorldServer::KickPlayerByID(DWord dwPlayerID, bool bLoginKick, bool bSysKick=false)
References SeTown::GetHSock, m_kAllTS, SeLogDebug, SendWBL_KickPlayerByID, SendWT_KickPlayer.
Referenced by ProcessLW_AccountLogin, ProcessLW_KickAccount.
void WorldServer::OnPlayerLeave(DWord dwPlayerID, bool bExitGame, int iTownIndex=-1)
References SendWBL_PlayerLeave.
Referenced by ProcessTW_PlayerLeave.
void WorldServer::UpdateQueryFreeHeroList()
References GetHS, GetServerTime, IsDiffWeek, m_kUpdateFreeHeroTime, NowTime.
Referenced by Update.
void WorldServer::InitLeagueInfo()
References GetAString, GetDBTime, SeLeagueInfo::kBeginTime, SeLeagueInfo::kEndTime, m_kLeagueInfo, SPrintf.
void WorldServer::SaveLeagueInfo()
References GetDBTime2Str, SeLeagueInfo::kBeginTime, SeLeagueInfo::kEndTime, m_kLeagueInfo, SPrintf.
Referenced by UpdateLeagueInfo.
void WorldServer::UpdateLeagueInfo()
References SeLeagueInfo::bSendBlockServer, g_kWorldServer, GenLeagueTime, GetBlockServerNum, GetServerTime, SeLeagueInfo::kBeginTime, SeLeagueInfo::kEndTime, m_kLeagueInfo, SaveLeagueInfo, SendWBL_UpdateLeagueInfo.
Referenced by Update.
bool WorldServer::GenLeagueTime()
References SeLeagueInfo::bSendBlockServer, SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeLeagueInfo::IsValidTime, SeDBTime::iYear, SeLeagueInfo::kBeginTime, SeLeagueInfo::kEndTime, m_kLeagueInfo, NowTime.
Referenced by UpdateLeagueInfo.
void WorldServer::OnHeroEndStat(const SeWSRaceSendInfo &rkInfo)
References SeHeroEndStat::dwHeroID, SeRaceSendInfo::dwHeroTypeID, SeHeroEndStat::dwMapID, SeWSRaceSendInfo::dwMapID, SeHeroEndStat::iLose, SeRaceSendInfo::iRaceEndFlag, SeHeroEndStat::iRecordCount, SeHeroEndStat::iWin, SeWSRaceSendInfo::kInfo, m_kMHeroStat, SROT_RRESULT_FINISHED_SUCCES.
Referenced by ProcessTW_RaceEndRace.
void WorldServer::UpdateLogHeroEndStat()
References GetServerTime, m_kMHeroStat.
Referenced by Update.
void WorldServer::OnSendShowNoticeWithoutString(HSock &rkTownSock, DWord dwPlayerID, const SeNoticeCode eCode, DWord dwParam)
References SendWT_ShowNotice, SSD_ENDSTR_LEN.
Referenced by ProcessLW_AccountWillLogin, BlockServer::ProcessWBL_PlayerRenameEnd.
std::string WorldServer::GetRaceAreaInfo(int iNum, const SeWSRaceSendInfo *pkInfo)
References SPrintf.
Referenced by ProcessTW_RaceEndRace.
void WorldServer::OnSendRaceEndInfoLog(SeMatchRaceType eMatchType, const char *pcAreaInfo, const SeWSRaceSendInfo &rkSendInfo)
Referenced by BlockServer::ProcessWBL_RaceEndRace.
bool WorldServer::SendWBL_HasDBError(const SeDBError &eErrorCode, void *pkReceiver=NULL)
Referenced by SetHasDBError.
bool WorldServer::SendWBL_BlockSetup(const SeBlockSetupType &eType, int iParam, void *pkReceiver=NULL)
Referenced by LoadDynamicConfig.
bool WorldServer::SendWBL_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, int iSize, const char *acMessage, void *pkReceiver=NULL)
bool WorldServer::SendWBL_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, int iSize, std::vector< char > &acMessage, void *pkReceiver=NULL)
bool WorldServer::SendWBL_LoadPlayerInfoAgain(int iTownIndex, const HSock &kTownSock, int iNum, const SeLoadPlayerInfoAgain *akPlayerInfo, void *pkReceiver=NULL)
Referenced by ProcessTW_LoadPlayerInfoAgain, UpdateDisconnectTS.
bool WorldServer::SendWBL_LoadPlayerInfoAgain(int iTownIndex, const HSock &kTownSock, int iNum, std::vector< SeLoadPlayerInfoAgain > &akPlayerInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_AccountLogin(DWord dwPlayerID, DWord dwSessionID, const SePtlAccountInfo &kAccountInfo, void *pkReceiver=NULL)
Referenced by ProcessLW_AccountLogin.
bool WorldServer::SendWBL_PlayerValidate(DWord dwPlayerID, const HSock &kTSSock, DWord dwClientID, DWord dwSessionID, DWord dwPlayerIP, DWord dwMaxMailID, int iTownIndex, DWord dwTownServerID, const SeMobileInfo &kMobileInfo, void *pkReceiver=NULL)
Referenced by ProcessTW_PlayerValidate.
bool WorldServer::SendWBL_PlayerValidateEnd(DWord dwPlayerID, DWord dwClientID, const SeValidateType &eValidateType, int iSize, const char *acNotice, void *pkReceiver=NULL)
Referenced by SeDBSerProcess_CharQueryValid.
bool WorldServer::SendWBL_PlayerValidateEnd(DWord dwPlayerID, DWord dwClientID, const SeValidateType &eValidateType, int iSize, std::vector< char > &acNotice, void *pkReceiver=NULL)
bool WorldServer::SendWBL_KickPlayerByID(DWord dwPlayerID, bool bLoginKick, bool bSysKick, void *pkReceiver=NULL)
Referenced by KickPlayerByID.
bool WorldServer::SendWBL_PlayerLeave(DWord dwPlayerID, int iTownIndex, bool bExitGame, void *pkReceiver=NULL)
Referenced by OnPlayerLeave.
bool WorldServer::SendWBL_CreateChar(DWord dwPlayerID, const char *acName, int iSex, void *pkReceiver=NULL)
Referenced by ProcessTW_CreateChar.
bool WorldServer::SendWBL_CharAddRet(DWord dwPlayerID, const SeCreateCharRet &eRet, void *pkReceiver=NULL)
Referenced by SeDBSerProcess_CharAdd.
bool WorldServer::SendWBL_RaceEndRace(DWord dwTime, DWord dwMapID, int iTownIndex, bool bAutoMatchRace, DWord dwRoomSession, const SeMatchRaceType &eMatchType, const char *acAreaInfo, int iNum, const SeWSRaceSendInfo *akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_RaceEndRace(DWord dwTime, DWord dwMapID, int iTownIndex, bool bAutoMatchRace, DWord dwRoomSession, const SeMatchRaceType &eMatchType, const char *acAreaInfo, int iNum, std::vector< SeWSRaceSendInfo > &akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_RaceEndGuanka(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, const SeWSGuanqiaSendInfo *akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_RaceEndGuanka(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, std::vector< SeWSGuanqiaSendInfo > &akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_ItemExchange(DWord dwPlayerID, int iTypeID, void *pkReceiver=NULL)
Referenced by ProcessTW_ItemExchange.
bool WorldServer::SendWBL_TaskQueryList(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessTW_TaskQueryList.
bool WorldServer::SendWBL_TaskResel(DWord dwPlayerID, DWord dwTaskID, void *pkReceiver=NULL)
Referenced by ProcessTW_TaskResel.
bool WorldServer::SendWBL_TaskGetAward(DWord dwPlayerID, DWord dwTaskID, void *pkReceiver=NULL)
Referenced by ProcessTW_GetTaskReward.
bool WorldServer::SendWBL_MatchRaceLoad(DWord dwRoomSession, DWord dwPlayerID, DWord dwMapID, void *pkReceiver=NULL)
Referenced by ProcessTW_MatchRaceLoad.
bool WorldServer::SendWBL_UpdateLeagueInfo(const SeDBTime &kBeginTime, const SeDBTime &kEndTime, void *pkReceiver=NULL)
Referenced by UpdateLeagueInfo.
bool WorldServer::SendWBL_PlayerRenameBegin(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
Referenced by ProcessTW_PlayerRename.
bool WorldServer::SendWBL_PlayerRenameEnd(DWord dwPlayerID, bool bSuccess, const char *acName, void *pkReceiver=NULL)
Referenced by SeDBSerProcess_CharRename.
bool WorldServer::SendWBL_RaceBuy(DWord dwSession, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
Referenced by ProcessTW_RaceBuy.
bool WorldServer::SendWBL_MapTaskOpr(DWord dwPlayerID, int iOprType, DWord dwParam, void *pkReceiver=NULL)
Referenced by ProcessTW_MapTaskOpr.
bool WorldServer::SendWBL_BuyShopItem(DWord dwPlayerID, int types, DWord ShopID, DWord Num, void *pkReceiver=NULL)
Referenced by ProcessTW_BuyShopItem.
bool WorldServer::SendWBL_ShopItemGM(DWord dwPlayerID, int iNum, const ShopItem *GmItems, void *pkReceiver=NULL)
Referenced by ProcessTW_ShopItemGM.
bool WorldServer::SendWBL_ShopItemGM(DWord dwPlayerID, int iNum, std::vector< ShopItem > &GmItems, void *pkReceiver=NULL)
bool WorldServer::SendWBL_GetItemGM(DWord dwPlayerID, DWord ShopID, void *pkReceiver=NULL)
Referenced by ProcessTW_GetItemGM.
bool WorldServer::SendWBL_CreateNexusFriend(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, const char *acName, const SeDBTime &CreateTime, void *pkReceiver=NULL)
Referenced by ProcessNW_CreateNexusFriendReq.
bool WorldServer::SendWBL_CreateNexusOfflineFriend(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, const char *acName, const SeDBTime &CreateTime, void *pkReceiver=NULL)
Referenced by ProcessNW_CreateNexusOfflineFriendReq.
bool WorldServer::SendWBL_UpdateNexusFriend(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, void *pkReceiver=NULL)
Referenced by ProcessNW_UpdateNexusFriendReq.
bool WorldServer::SendWBL_DelNexusFriend(DWord dwPlayerID, DWord dwPlayerFriendID, void *pkReceiver=NULL)
Referenced by ProcessNW_DelNexusFriendReq.
bool WorldServer::SendWBL_UserAlterNickNameReq(DWord dwPlayerID, const char *acNickName, int iResult, void *pkReceiver=NULL)
Referenced by ProcessBW_IsPlayerExistRet.
bool WorldServer::SendWBLData(void *pkData, int iSize, void *pkReceiver)
References g_kWorldServer, PushThreadMsg.
bool WorldServer::SendWN_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessNW_Register.
bool WorldServer::SendWN_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessNW_HeartPackage.
bool WorldServer::SendWN_NexusFriendInfoSyn(DWord dwPlayerID, const char *acName, int iNum, const SeNexusFriendSyncInfo *akNexusFriendSync, void *pkReceiver=NULL)
Referenced by UserInfoSync_NexusFriend.
bool WorldServer::SendWN_NexusFriendInfoSyn(DWord dwPlayerID, const char *acName, int iNum, std::vector< SeNexusFriendSyncInfo > &akNexusFriendSync, void *pkReceiver=NULL)
bool WorldServer::SendWN_PlayerScoreNtf(DWord dwPlayerID, const MatchType &dwMatchType, DWord dwScore, void *pkReceiver=NULL)
Referenced by BlockServer::ProcessRBL_UpdateScore, UserInfoSync_PlayerScore.
bool WorldServer::SendWNData(void *pkData, int iSize, void *pkReceiver)
References g_kNexusServerMgr, moba::ServerSessionMgr::getServerHSock, m_kNetMgr, SeLogError, SeCMD::wCmd.
Referenced by BlockServer::SendBLNData.
bool WorldServer::ProcessNWData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WorldServer::PreProcessNW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessNW_Register(SeNW_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, moba::ServerSessionMgr::checkServer, moba::ServerSessionMgr::createServer, SeWorldConfig::dwAreaID, SeNW_Register::dwLoginMagic, SeNW_Register::dwServerID, SeConnect::dwServerID, SeVirtConn::eState, g_kNexusServerMgr, GetID2Str, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kConfig, m_kNetMgr, m_pkDBSConn, SeLogInfo, SendWN_RegisterRet, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_NS, SSI_UNKNOWN, SVCS_REGISTERED.
void WorldServer::ProcessNW_HeartPackage(SeNW_HeartPackage *pkData, int iSize, void *pkSender)
References SeConnect::kSock, SendWN_HeartPackageRet.
void WorldServer::ProcessNW_CreateNexusFriendReq(SeNW_CreateNexusFriendReq *pkData, int iSize, void *pkSender)
References SeNW_CreateNexusFriendReq::acName, SeNW_CreateNexusFriendReq::CreateTime, SeNW_CreateNexusFriendReq::dwMark, SeNW_CreateNexusFriendReq::dwPlayerFriendID, SeNW_CreateNexusFriendReq::dwPlayerID, SendWBL_CreateNexusFriend.
void WorldServer::ProcessNW_CreateNexusOfflineFriendReq(SeNW_CreateNexusOfflineFriendReq *pkData, int iSize, void *pkSender)
References SeNW_CreateNexusOfflineFriendReq::acName, SeNW_CreateNexusOfflineFriendReq::CreateTime, SeNW_CreateNexusOfflineFriendReq::dwMark, SeNW_CreateNexusOfflineFriendReq::dwPlayerFriendID, SeNW_CreateNexusOfflineFriendReq::dwPlayerID, SendWBL_CreateNexusOfflineFriend.
void WorldServer::ProcessNW_UpdateNexusFriendReq(SeNW_UpdateNexusFriendReq *pkData, int iSize, void *pkSender)
References SeNW_UpdateNexusFriendReq::dwMark, SeNW_UpdateNexusFriendReq::dwPlayerFriendID, SeNW_UpdateNexusFriendReq::dwPlayerID, SendWBL_UpdateNexusFriend.
void WorldServer::ProcessNW_DelNexusFriendReq(SeNW_DelNexusFriendReq *pkData, int iSize, void *pkSender)
References SeNW_DelNexusFriendReq::dwPlayerFriendID, SeNW_DelNexusFriendReq::dwPlayerID, SendWBL_DelNexusFriend.
bool WorldServer::SendWR_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessRW_Register.
bool WorldServer::SendWR_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessRW_HeartPackage.
bool WorldServer::SendWRData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr, SeLogError, SeCMD::wCmd.
Referenced by BlockServer::SendBLRData.
bool WorldServer::ProcessRWData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WorldServer::PreProcessRW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessRW_Register(SeRW_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, moba::ServerSessionMgr::checkServer, moba::ServerSessionMgr::createServer, SeWorldConfig::dwAreaID, SeRW_Register::dwLoginMagic, SeRW_Register::dwServerID, SeConnect::dwServerID, SeVirtConn::eState, g_kRaceServerMgr, GetID2Str, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kConfig, m_kNetMgr, m_pkDBSConn, SeLogInfo, SendWR_RegisterRet, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_RS, SSI_UNKNOWN, SVCS_REGISTERED.
void WorldServer::ProcessRW_HeartPackage(SeRW_HeartPackage *pkData, int iSize, void *pkSender)
References SeConnect::kSock, SendWR_HeartPackageRet.
bool WorldServer::SendWM_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessMW_Register.
bool WorldServer::SendWM_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessMW_HeartPackage.
bool WorldServer::SendWMData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr, SeLogError, SeCMD::wCmd.
Referenced by BlockServer::SendBLMData.
bool WorldServer::ProcessMWData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WorldServer::PreProcessMW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessMW_Register(SeMW_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, moba::ServerSessionMgr::checkServer, moba::ServerSessionMgr::createServer, SeWorldConfig::dwAreaID, SeMW_Register::dwLoginMagic, SeMW_Register::dwServerID, SeConnect::dwServerID, SeVirtConn::eState, g_kMatchServerMgr, GetID2Str, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kConfig, m_kNetMgr, m_pkDBSConn, SeLogInfo, SendWM_RegisterRet, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_MS, SSI_UNKNOWN, SVCS_REGISTERED.
void WorldServer::ProcessMW_HeartPackage(SeMW_HeartPackage *pkData, int iSize, void *pkSender)
References SeConnect::kSock, SendWM_HeartPackageRet.
WorldServer::WorldServer(void)
WorldServer::~WorldServer(void)
bool WorldServer::Initialize(void)
void WorldServer::Update(void)
void WorldServer::Finialize(void)
void WorldServer::ShowConsoleTitle(int iDTime)
DWord WorldServer::GetReconnTime() const
int WorldServer::GetAcvmtPerPage() const
SeServerActionResult WorldServer::ExecuteAction(SeServerActionIndex eActionIndex)
CShop* WorldServer::GetShop()
References m_Shop.
void WorldServer::UserInfoSync(SePlayer *pPlayer)
void WorldServer::UserInfoSync_NexusFriend(SePlayer *pPlayer)
void WorldServer::UserInfoSync_PlayerScore(SePlayer *pPlayer)
void WorldServer::UserInfoSync_LoadFriendLadderRank(SePlayer *pPlayer)
void WorldServer::UserHeroBindItem(DWord dwHeroID, std::vector< DWord > &rInfoVec)
bool WorldServer::CheckMapType(const DWord dw_map_id, const DWord dw_map_type)
bool WorldServer::CheckMapMatchType(const DWord dw_map_id, const DWord dw_map_type)
virtual void WorldServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
virtual void WorldServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
virtual void WorldServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
virtual void WorldServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
SeWorldConfig& WorldServer::GetConfig()
References m_kConfig.
const char* WorldServer::GetTableName(SeDBTableIndex eTable)
int WorldServer::GetTableFieldCount(SeDBTableIndex eTable)
bool WorldServer::SendWL_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
bool WorldServer::SendWL_HeartPackageRet(void *pkReceiver=NULL)
bool WorldServer::SendWL_LoginSuccess(DWord dwPackKey, DWord dwPlayerID, DWord dwSessionID, int iNum, const SeNetAddr *akGateList, void *pkReceiver=NULL)
bool WorldServer::SendWL_LoginSuccess(DWord dwPackKey, DWord dwPlayerID, DWord dwSessionID, int iNum, std::vector< SeNetAddr > &akGateList, void *pkReceiver=NULL)
bool WorldServer::SendWL_LoginFailed(DWord dwPackKey, DWord dwPlayerID, const SeLoginReason &eReason, int iParam1, void *pkReceiver=NULL)
bool WorldServer::SendWL_PlayerTownIndex(DWord dwPlayerID, int iTownIndex, void *pkReceiver=NULL)
bool WorldServer::SendWL_PlayerLogout(DWord dwPlayerID, void *pkReceiver=NULL)
bool WorldServer::SendWL_PlayerUpdateOnlineTime(DWord dwPlayerID, DWord dwOnlineTime, void *pkReceiver=NULL)
bool WorldServer::SendWLData(void *pkData, int iSize, void *pkReceiver)
bool WorldServer::SendWT_RegisterRet(const SeRegisterRet &eRet, DWord dwAreaID, void *pkReceiver=NULL)
bool WorldServer::SendWT_HeartPackageRet(void *pkReceiver=NULL)
bool WorldServer::SendWT_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, DWord dwParam, int iSize, const char *acMessage, void *pkReceiver=NULL)
bool WorldServer::SendWT_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, DWord dwParam, int iSize, std::vector< char > &acMessage, void *pkReceiver=NULL)
bool WorldServer::SendWT_IsReady(bool bReady, void *pkReceiver=NULL)
bool WorldServer::SendWT_LoadPlayerInfoAgainRet(bool bSuc, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerValidateRet(DWord dwClientID, DWord dwPlayerID, const SeValidateType &eValidateType, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryNameRet(DWord dwPlayerID, bool bHasExist, void *pkReceiver=NULL)
bool WorldServer::SendWT_CreateCharRet(DWord dwPlayerID, const SeCreateCharRet &eState, void *pkReceiver=NULL)
bool WorldServer::SendWT_KickPlayer(DWord dwPlayerID, bool bIsSysKick, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerLeave(DWord dwPlayerID, void *pkReceiver=NULL)
bool WorldServer::SendWT_InitPlayerInfo(DWord dwPlayerID, const char *acName, DWord iGold, DWord iDiamond, DWord dwLevel, DWord dwExp, const SeLadderInfo &kLadder, Byte byEquipSetIndex, DWord dwServerTime, DWord dwOnlineTime, void *pkReceiver=NULL)
bool WorldServer::SendWT_ExchangeInit(DWord dwPlayerID, int iNum, const SePtlExchange *akPtlExchange, void *pkReceiver=NULL)
bool WorldServer::SendWT_ExchangeInit(DWord dwPlayerID, int iNum, std::vector< SePtlExchange > &akPtlExchange, void *pkReceiver=NULL)
bool WorldServer::SendWT_ItemExchangeRet(DWord dwPlayerID, int iTypeID, int iReturn, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryPlayerReconInfo(DWord dwPlayerID, DWord dwRoomID, int iSeatIndex, int iReconTime, void *pkReceiver=NULL)
bool WorldServer::SendWT_UpdateMisc(DWord dwPlayerID, const SeMiscType &eType, int iValue, int iValue2, void *pkReceiver=NULL)
bool WorldServer::SendWT_TaskQueryListRet(DWord dwPlayerID, int iNum, const SePtlTask *akList, void *pkReceiver=NULL)
bool WorldServer::SendWT_TaskQueryListRet(DWord dwPlayerID, int iNum, std::vector< SePtlTask > &akList, void *pkReceiver=NULL)
bool WorldServer::SendWT_TaskReselRet(DWord dwPlayerID, DWord dwSrcTaskID, const SePtlTask &kNewTask, void *pkReceiver=NULL)
bool WorldServer::SendWT_ItemDel(DWord dwPlayerID, DWord dwItemID, const SeItemDelType &eType, void *pkReceiver=NULL)
bool WorldServer::SendWT_ReceiveMail(DWord dwPlayerID, int iNum, const SePtlMail *akMail, void *pkReceiver=NULL)
bool WorldServer::SendWT_ReceiveMail(DWord dwPlayerID, int iNum, std::vector< SePtlMail > &akMail, void *pkReceiver=NULL)
bool WorldServer::SendWT_UpdateMail(DWord dwPlayerID, int iNum, const SeMailUpdate *akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_UpdateMail(DWord dwPlayerID, int iNum, std::vector< SeMailUpdate > &akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_MailOprRet(DWord dwPlayerID, int iType, DWord dwMailID, int iRet, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerRename(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
bool WorldServer::SendWT_RaceBuyRet(DWord dwSession, bool bSuccess, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryMapTaskListRet(DWord dwPlayerID, DWord dwMapID, int iNum, const SePtlMapTask *akPtlMapTask, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryMapTaskListRet(DWord dwPlayerID, DWord dwMapID, int iNum, std::vector< SePtlMapTask > &akPtlMapTask, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryNearestRaceInfoRet(DWord dwPlayerID, DWord dwQueriedID, int iNum, const SePtlRaceHistory *akRaceInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_QueryNearestRaceInfoRet(DWord dwPlayerID, DWord dwQueriedID, int iNum, std::vector< SePtlRaceHistory > &akRaceInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_GetRaceHistoryRet(DWord dwPlayerID, int iType, int iPage, int iMaxPage, int iNum, const SePtlRaceHistory *akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_GetRaceHistoryRet(DWord dwPlayerID, int iType, int iPage, int iMaxPage, int iNum, std::vector< SePtlRaceHistory > &akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerNewItem(DWord dwPlayerID, int iNum, const SeItemNoti *SeItemArray, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerNewItem(DWord dwPlayerID, int iNum, std::vector< SeItemNoti > &SeItemArray, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerOperRep(DWord dwPlayerID, int iResult, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerMoneyAndDiamond(DWord dwPlayerID, DWord dwGold, DWord dwDiamond, void *pkReceiver=NULL)
bool WorldServer::SendWT_ShopItemGmRep(DWord dwPlayerID, int iResult, const ShopItem &GmItem, void *pkReceiver=NULL)
bool WorldServer::SendWT_SearchUserArchivesInfoRes(DWord dwPlayerID, const SeUserArchivesInfo &user_archives_info, void *pkReceiver=NULL)
bool WorldServer::SendWT_SearchUserArchivesDetailInfoRes(DWord dwPlayerID, const SeUserArchivesInfo &user_archives_info, void *pkReceiver=NULL)
bool WorldServer::SendWT_PlayerLadder(DWord dwPlayerID, const SeLadderInfo &kLadder, void *pkReceiver=NULL)
bool WorldServer::SendWT_EquipSchema(DWord dwPlayerID, int iNum, const SeEquipSchemaInfo *akEquips, void *pkReceiver=NULL)
bool WorldServer::SendWT_EquipSchema(DWord dwPlayerID, int iNum, std::vector< SeEquipSchemaInfo > &akEquips, void *pkReceiver=NULL)
bool WorldServer::SendWT_RoomInviteNotify(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
bool WorldServer::SendWT_FriendLadderInfoNtf(DWord dwPlayerID, int iNum, const SeLadderRankInfo *RankList, void *pkReceiver=NULL)
bool WorldServer::SendWT_FriendLadderInfoNtf(DWord dwPlayerID, int iNum, std::vector< SeLadderRankInfo > &RankList, void *pkReceiver=NULL)
bool WorldServer::SendWT_ActiveAvatarNtf(DWord dwPlayerID, int iNum, const DWord *avartars, void *pkReceiver=NULL)
bool WorldServer::SendWT_ActiveAvatarNtf(DWord dwPlayerID, int iNum, std::vector< DWord > &avartars, void *pkReceiver=NULL)
bool WorldServer::SendWT_UserHeroSync(DWord dwPlayerID, int num, const SeUserHeroSyncInfo *akHeroSyncInfo, void *pkReceiver=NULL)
bool WorldServer::SendWT_UserHeroSync(DWord dwPlayerID, int num, std::vector< SeUserHeroSyncInfo > &akHeroSyncInfo, void *pkReceiver=NULL)
bool WorldServer::SendWTData(void *pkData, int iSize, void *pkReceiver)
bool WorldServer::SendHSData(void *pkData, int iSize, void *pkReceiver)
bool WorldServer::SendHS_RegisterRet(const HSock &rkSock, int iRet)
bool WorldServer::SendHS_HeartPackageRet(const HSock &rkSock)
bool WorldServer::SendHS_QueryNearestRaceInfo(DWord dwPlayerID, DWord dwQueryID, DWord dwMapID)
bool WorldServer::SendWB_Register(DWord dwWorldMagic, DWord dwVersion, void *pkReceiver=NULL)
bool WorldServer::SendWB_HeartPackage(void *pkReceiver=NULL)
bool WorldServer::SendWB_InitGenID(const SeInitGenIDType &eType, const SeDBTableIndex &eTableIndex, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataInsert(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, DWord dwParam1, const SeBBReceipt &eReceipt, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataInsert(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, DWord dwParam1, const SeBBReceipt &eReceipt, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataUpdate(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, DWord dwParam1, const SeBBReceipt &eReceipt, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataUpdate(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, DWord dwParam1, const SeBBReceipt &eReceipt, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataDiscard(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, int iDeleteReason, const SeDBTime &kDeleteTime, void *pkReceiver=NULL)
bool WorldServer::SendWB_DataDelete(DWord dwPlayerID, const SeDBTableIndex &eTable, DWord dwID, void *pkReceiver=NULL)
bool WorldServer::SendWB_PlayerLoad(DWord dwPlayerID, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_PlayerLoad(DWord dwPlayerID, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_SelectData(DWord dwID, const SeDBTableIndex &eTable, const SeBBReceipt &eReceipt, int iNum, const int *aiIndex, void *pkReceiver=NULL)
bool WorldServer::SendWB_SelectData(DWord dwID, const SeDBTableIndex &eTable, const SeBBReceipt &eReceipt, int iNum, std::vector< int > &aiIndex, void *pkReceiver=NULL)
bool WorldServer::SendWB_PlayerOffLine(DWord dwPlayerID, void *pkReceiver=NULL)
bool WorldServer::SendWB_DBQuery(const SeDBQueryType &eType, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_DBQuery(const SeDBQueryType &eType, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_IsPlayerExist(const SePlayerExistQueryType &eType, const char *acAccount, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_IsPlayerExist(const SePlayerExistQueryType &eType, const char *acAccount, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_LoadPlayerInfoAgain(int iTotalNum, int iBegin, int iNum, const DWord *akPlayerInfo, void *pkReceiver=NULL)
bool WorldServer::SendWB_LoadPlayerInfoAgain(int iTotalNum, int iBegin, int iNum, std::vector< DWord > &akPlayerInfo, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabSelect(const SeDBTableIndex &eTable, DWord dwQueryID, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabSelect(const SeDBTableIndex &eTable, DWord dwQueryID, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabUpdate(const SeDBTableIndex &eTable, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabUpdate(const SeDBTableIndex &eTable, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabInsert(const SeDBTableIndex &eTable, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabInsert(const SeDBTableIndex &eTable, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabDelete(const SeDBTableIndex &eTable, int iSize, const char *acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_TabDelete(const SeDBTableIndex &eTable, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WorldServer::SendWB_SelectFriendData(DWord dwID, const SeBBReceipt &eType, int iSize, const DWord *dwIDList, void *pkReceiver=NULL)
bool WorldServer::SendWB_SelectFriendData(DWord dwID, const SeBBReceipt &eType, int iSize, std::vector< DWord > &dwIDList, void *pkReceiver=NULL)
bool WorldServer::SendWBData(void *pkData, int iSize, void *pkReceiver)
bool WorldServer::SendDBServer_CharLoginLoad(DWord dwID, DWord dwPackKey, DWord dwSessionID)
bool WorldServer::SendDBServer_CharInfoADD(DWord dwPlayerID, const char *pcAccount, const char *pcName, int iSex, int iPlatFlag)
bool WorldServer::SendDBServer_CharUpdateMisc(DWord dwPlayerID, SeCharMiscType eType, UInt uiValue)
bool WorldServer::SendDBServer_CharAddMisc(DWord dwPlayerID, SeCharMiscType eType, UInt uiValue)
bool WorldServer::SendDBServer_CharInfoUpdateScore(DWord dwPlayerID, UInt uiScore, UInt uiFood, UInt uiSoldiers, SeCharMiscType eType, UInt uiValue=0)
bool WorldServer::SendDBServer_CharInfoAddScore(DWord dwPlayerID, UInt uiAddScore, UInt uiAddFood, UInt uiAddSoldiers, SeCharMiscType eType, UInt uiAddValue=0)
bool WorldServer::SendDBServer_CharQueryValid(DWord dwPlayerID, DWord dwClientID, int iTownIndex)
bool WorldServer::SendDBServer_CharInfoRename(DWord dwPlayerID, const char *pcName)
bool WorldServer::SendDBServer_CharUpdateChestInfo(DWord dwPlayerID, int iChestKey, const SeDBTime &rkChestKeyTime)
bool WorldServer::SendDBServer_CharUpdateAcvmtCounts(DWord dwPlayerID, int iVal)
bool WorldServer::SendDBServer_CharInfoUpdateConfig(DWord dwPlayerID, const char *pConfig, int iLen)
bool WorldServer::SendDBServer_CharUpdateLoginTime(DWord dwPlayerID, const SeDBTime &loginTime)
bool WorldServer::SendDBServer_CharUpdateLadder(DWord dwPlayerID, const SeDBTime &time, int defeat, int score, int no, int level)
bool WorldServer::SendDBServer_CharUpdateMatch(DWord dwPlayerID, const SeDBTime &time, int defeat, int score, int num)
bool WorldServer::SendDBServer_CharUpdateBattleField(DWord dwPlayerID, const SeDBTime &time, int defeat, int score)
bool WorldServer::SendDBServer_CharUpdateTaskResetCount(DWord dwPlayerID, DWord dwResetCount)
bool WorldServer::SendDBServer_CharUpdateTaskResetTime(DWord dwPlayerID, DWord dwResetCount, const SeDBTime &time)
bool WorldServer::SendDBServer_CharTaskLoad(DWord dwPlayerID)
bool WorldServer::SendDBServer_CharTaskAdd(DWord dwPlayerID, const SeTaskInfo *pkTask)
bool WorldServer::SendDBServer_CharTaskDel(DWord dwPlayerID, DWord dwTaskID)
bool WorldServer::SendDBServer_CharTaskUpdate(DWord dwPlayerID, const SeTaskInfo *pkTask)
bool WorldServer::SendDBServer_CharMemoryLoad(DWord dwPlayerID)
bool WorldServer::SendDBServer_CharMemoryUpdate(DWord dwPlayerID, DWord dwType, const SeCharMemory &rkData)
bool WorldServer::SendDBServer_NexusFriendLoad(DWord dwPlayerID)
bool WorldServer::SendDBServer_NexusFriendCreate(DWord dwPlayerID, const SeCharNexusFriendData &rkData)
bool WorldServer::SendDBServer_NexusFriendUpdate(DWord dwPlayerID, const SeCharNexusFriendData &rkData)
bool WorldServer::SendDBServer_NexusFriendDelete(DWord dwPlayerID, DWord dwID)
bool WorldServer::SendDBServer_CharUpdateMisc(DWord dwPlayerID, SeCharMiscType eType, const SeDBTime &time)
bool WorldServer::SendDBServer_CharUpdateMisc(DWord dwPlayerID, SeCharMiscType eType, const char *str)
bool WorldServer::ProcessLWData(void *pkData, int iSize, void *pkSender=NULL)
bool WorldServer::PreProcessLW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessLW_Register(SeLW_Register *pkData, int iSize, void *pkSender)
void WorldServer::ProcessLW_HeartPackage(SeLW_HeartPackage *pkData, int iSize, void *pkSender)
void WorldServer::ProcessLW_KickAccount(SeLW_KickAccount *pkData, int iSize, void *pkSender)
void WorldServer::ProcessLW_AccountLogin(SeLW_AccountLogin *pkData, int iSize, void *pkSender)
void WorldServer::ProcessLW_AccountWillLogin(SeLW_AccountWillLogin *pkData, int iSize, void *pkSender)
bool WorldServer::ProcessTWData(void *pkData, int iSize, void *pkSender=NULL)
bool WorldServer::PreProcessTW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_Register(SeTW_Register *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_HeartPackage(SeTW_HeartPackage *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_LoadPlayerInfoAgain(SeTW_LoadPlayerInfoAgain *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_PlayerValidate(SeTW_PlayerValidate *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_QueryName(SeTW_QueryName *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_CreateChar(SeTW_CreateChar *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_PlayerLeave(SeTW_PlayerLeave *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_RaceEndRace(SeTW_RaceEndRace *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_RaceEndGuanka(SeTW_RaceEndGuanka *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_ItemExchange(SeTW_ItemExchange *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_SavePlayerReconInfo(SeTW_SavePlayerReconInfo *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_TaskQueryList(SeTW_TaskQueryList *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_TaskResel(SeTW_TaskResel *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_GetTaskReward(SeTW_GetTaskReward *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_MatchRaceLoad(SeTW_MatchRaceLoad *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_DelReconInfo(SeTW_DelReconInfo *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_PlayerRename(SeTW_PlayerRename *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_RaceBuy(SeTW_RaceBuy *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_MapTaskOpr(SeTW_MapTaskOpr *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_QueryNearestRaceInfo(SeTW_QueryNearestRaceInfo *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_PlayerLeaveRace(SeTW_PlayerLeaveRace *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_BuyShopItem(SeTW_BuyShopItem *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_ShopItemGM(SeTW_ShopItemGM *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_GetItemGM(SeTW_GetItemGM *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_SearchUserArchivesInfoReq(SeTW_SearchUserArchivesInfoReq *pkData, int iSize, void *pkSender)
void WorldServer::ProcessTW_SearchUserArchivesDetailInfoReq(SeTW_SearchUserArchivesDetailInfoReq *pkData, int iSize, void *pkSender)
void WorldServer::ProcessHSData(void *pkData, int iSize, void *pkSender=NULL)
void WorldServer::ProcessHS_Register(void *pkData, int iSize, void *pkSender=NULL)
void WorldServer::ProcessHS_HeartPackage(void *pkData, int iSize, void *pkSender=NULL)
void WorldServer::ProcessHS_QueryNearestRaceInfoRet(void *pkData, int iSize, void *pkSender=NULL)
bool WorldServer::ProcessBWData(void *pkData, int iSize, void *pkSender=NULL)
bool WorldServer::PreProcessBW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBW_RegisterRet(SeBW_RegisterRet *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBW_InitGenIDRet(SeBW_InitGenIDRet *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBW_DBServerError(SeBW_DBServerError *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBW_HeartPackageRet(SeBW_HeartPackageRet *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBW_DataInsertRet(SeBW_DataInsertRet *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBW_DBQueryRet(SeBW_DBQueryRet *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBW_IsPlayerExistRet(SeBW_IsPlayerExistRet *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBW_TabSelectRet(SeBW_TabSelectRet *pkData, int iSize, void *pkSender)
void WorldServer::SeDBSerProcess_CharLoginLoad(int iNowSendNum, bool bSendOver, SeDBStream &rkDBStream)
void WorldServer::SeDBSerProcess_CharQueryValid(int iNowSendNum, bool bSendOver, SeDBStream &rkDBStream)
void WorldServer::SeDBSerProcess_CharAdd(DWord dwPlayerID, SeCreateCharRet eRet)
void WorldServer::SeDBSerProcess_CharRename(int iNowSendNum, bool bSendOver, SeDBStream &rkDBStream)
bool WorldServer::ProcessBLWData(void *pkData, int iSize, void *pkSender=NULL)
bool WorldServer::PreProcessBLW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBLW_TSIncNum(SeBLW_TSIncNum *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBLW_ShowNotice(SeBLW_ShowNotice *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBLW_LoadPlayerInfoAgainRet(SeBLW_LoadPlayerInfoAgainRet *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBLW_PlayerLeave(SeBLW_PlayerLeave *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBLW_PlayerLoadComplete(SeBLW_PlayerLoadComplete *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBLW_PlayerOperRep(SeBLW_PlayerOperRep *pkData, int iSize, void *pkSender)
void WorldServer::ProcessBLW_ShopItemGmRep(SeBLW_ShopItemGmRep *pkData, int iSize, void *pkSender)
DWord WorldServer::GenNexusFriendID()
DWord WorldServer::GenNexusPromotionID()
DWord WorldServer::GenCharRaceArenaID()
DWord WorldServer::GenNexusTeamID()
DWord WorldServer::GenNexusTeamMemberID()
DWord WorldServer::GetServerTime(void)
int WorldServer::GetPlayerNum(void)
int WorldServer::RandInt(void)
int WorldServer::RandInt(int iMin, int iMax)
float WorldServer::RandFloat(float fMin, float fMax)
void WorldServer::AddOnlinePlayer(DWord dwPlayerID, const SeOnlinePlayer &rkOnlinePlayer)
void WorldServer::DelOnlinePlayer(DWord dwPlayerID)
const SeOnlinePlayer* WorldServer::GetOnlinePlayer(DWord dwPlayerID)
HSock WorldServer::GetPlayerTownSock(DWord dwPlayerID)
void WorldServer::OnSendDBPlayerLoad(DWord dwPlayerID)
void WorldServer::OnSendDBSLoadPlayerInfoAgain(void)
const SePlayerReconInfo* WorldServer::GetReconPlayer(DWord dwPlayerID)
void WorldServer::DelReconPlayer(DWord dwPlayerID)
void WorldServer::UpdatePlayerReconInfo(void)
void WorldServer::OnSendBSRaceEndRace(DWord dwThreadNum, DWord dwMapID, DWord dwRoomSession, int iTownIndex, DWord dwTime, int iNum, bool bAutoMatchRace, const VWSRaceSendInfo &akRaceSendInfo, const char *pcAreaInfo, SeMatchRaceType eMatchType)
void WorldServer::OnSendBSRaceEndGuanQia(DWord dwThreadNum, DWord dwMapID, DWord dwTime, int iNum, const VWSGuanqiaSendInfo &akRaceSendInfo, bool bAutoMatchRace)
bool WorldServer::IsException(void)
void WorldServer::SetException(void)
bool WorldServer::IsAllTownLoadComplete(void)
bool WorldServer::SwitchWSReady(void)
void WorldServer::SetWSReady(bool bReady)
bool WorldServer::IsWSReady()
void WorldServer::SetDBReady(bool bReady)
bool WorldServer::IsDBReady()
void WorldServer::SetInitFlag(int iFlag)
bool WorldServer::HasInitFlag(int iFlag)
SeConnect* WorldServer::GetLS()
SeConnect* WorldServer::GetLSBySock(HSock kSock)
SeConnect* WorldServer::GetLSByPlayerID(DWord dwPlayerID)
SeConnect* WorldServer::GetLSByServerID(DWord dwServerID)
void WorldServer::DelLSPlayer(DWord dwPlayerID)
void WorldServer::OnLSDisconnect(DWord dwServerID)
void WorldServer::OnSendLSPlayerLogout(DWord dwPlayerID)
void WorldServer::OnSendLSPlayerTownIndex(DWord dwPlayerID, int iTownIndex)
SeConnect* WorldServer::GetHS()
SeConnect* WorldServer::GetHSBySock(HSock kSock)
SeConnect* WorldServer::GetHSByServerID(DWord dwServerID)
void WorldServer::OnHSDisconnect(DWord dwServerID)
SeTown* WorldServer::GetTSByID(DWord dwServerID)
SeTown* WorldServer::GetTSByIndex(int iTownIndex)
SeTown* WorldServer::GetTSBySock(HSock kSock)
bool WorldServer::HasTownIndex(int iTownIndex)
void WorldServer::OnTSDisconnect(DWord dwServerID)
int WorldServer::GetTSNum(void)
void WorldServer::DisconnectAllTown(void)
void WorldServer::SetHasDBError(SeDBError eErrorCode)
SeDBError WorldServer::GetHasDBError(void)
int WorldServer::GetBlockServerNum(void)
bool WorldServer::PushThreadMsg(DWord dwPlayerID, void *pkData, int iSize)
bool WorldServer::PushThreadMsgByNum(int iBlockServer, void *pkData, int iSize)
bool WorldServer::PushWSMsg(void *pkData, int iSize)
bool WorldServer::KickPlayerByID(DWord dwPlayerID, bool bLoginKick, bool bSysKick=false)
void WorldServer::OnPlayerLeave(DWord dwPlayerID, bool bExitGame, int iTownIndex=-1)
void WorldServer::UpdateQueryFreeHeroList()
void WorldServer::InitLeagueInfo()
void WorldServer::SaveLeagueInfo()
void WorldServer::UpdateLeagueInfo()
bool WorldServer::GenLeagueTime()
void WorldServer::OnHeroEndStat(const SeWSRaceSendInfo &rkInfo)
void WorldServer::UpdateLogHeroEndStat()
void WorldServer::OnSendShowNoticeWithoutString(HSock &rkTownSock, DWord dwPlayerID, const SeNoticeCode eCode, DWord dwParam)
std::string WorldServer::GetRaceAreaInfo(int iNum, const SeWSRaceSendInfo *pkInfo)
void WorldServer::OnSendRaceEndInfoLog(SeMatchRaceType eMatchType, const char *pcAreaInfo, const SeWSRaceSendInfo &rkSendInfo)
bool WorldServer::SendWBL_HasDBError(const SeDBError &eErrorCode, void *pkReceiver=NULL)
bool WorldServer::SendWBL_BlockSetup(const SeBlockSetupType &eType, int iParam, void *pkReceiver=NULL)
bool WorldServer::SendWBL_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, int iSize, const char *acMessage, void *pkReceiver=NULL)
bool WorldServer::SendWBL_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, int iSize, std::vector< char > &acMessage, void *pkReceiver=NULL)
bool WorldServer::SendWBL_LoadPlayerInfoAgain(int iTownIndex, const HSock &kTownSock, int iNum, const SeLoadPlayerInfoAgain *akPlayerInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_LoadPlayerInfoAgain(int iTownIndex, const HSock &kTownSock, int iNum, std::vector< SeLoadPlayerInfoAgain > &akPlayerInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_AccountLogin(DWord dwPlayerID, DWord dwSessionID, const SePtlAccountInfo &kAccountInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_PlayerValidate(DWord dwPlayerID, const HSock &kTSSock, DWord dwClientID, DWord dwSessionID, DWord dwPlayerIP, DWord dwMaxMailID, int iTownIndex, DWord dwTownServerID, const SeMobileInfo &kMobileInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_PlayerValidateEnd(DWord dwPlayerID, DWord dwClientID, const SeValidateType &eValidateType, int iSize, const char *acNotice, void *pkReceiver=NULL)
bool WorldServer::SendWBL_PlayerValidateEnd(DWord dwPlayerID, DWord dwClientID, const SeValidateType &eValidateType, int iSize, std::vector< char > &acNotice, void *pkReceiver=NULL)
bool WorldServer::SendWBL_KickPlayerByID(DWord dwPlayerID, bool bLoginKick, bool bSysKick, void *pkReceiver=NULL)
bool WorldServer::SendWBL_PlayerLeave(DWord dwPlayerID, int iTownIndex, bool bExitGame, void *pkReceiver=NULL)
bool WorldServer::SendWBL_CreateChar(DWord dwPlayerID, const char *acName, int iSex, void *pkReceiver=NULL)
bool WorldServer::SendWBL_CharAddRet(DWord dwPlayerID, const SeCreateCharRet &eRet, void *pkReceiver=NULL)
bool WorldServer::SendWBL_RaceEndRace(DWord dwTime, DWord dwMapID, int iTownIndex, bool bAutoMatchRace, DWord dwRoomSession, const SeMatchRaceType &eMatchType, const char *acAreaInfo, int iNum, const SeWSRaceSendInfo *akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_RaceEndRace(DWord dwTime, DWord dwMapID, int iTownIndex, bool bAutoMatchRace, DWord dwRoomSession, const SeMatchRaceType &eMatchType, const char *acAreaInfo, int iNum, std::vector< SeWSRaceSendInfo > &akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_RaceEndGuanka(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, const SeWSGuanqiaSendInfo *akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_RaceEndGuanka(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, std::vector< SeWSGuanqiaSendInfo > &akInfo, void *pkReceiver=NULL)
bool WorldServer::SendWBL_ItemExchange(DWord dwPlayerID, int iTypeID, void *pkReceiver=NULL)
bool WorldServer::SendWBL_TaskQueryList(DWord dwPlayerID, void *pkReceiver=NULL)
bool WorldServer::SendWBL_TaskResel(DWord dwPlayerID, DWord dwTaskID, void *pkReceiver=NULL)
bool WorldServer::SendWBL_TaskGetAward(DWord dwPlayerID, DWord dwTaskID, void *pkReceiver=NULL)
bool WorldServer::SendWBL_MatchRaceLoad(DWord dwRoomSession, DWord dwPlayerID, DWord dwMapID, void *pkReceiver=NULL)
bool WorldServer::SendWBL_UpdateLeagueInfo(const SeDBTime &kBeginTime, const SeDBTime &kEndTime, void *pkReceiver=NULL)
bool WorldServer::SendWBL_PlayerRenameBegin(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
bool WorldServer::SendWBL_PlayerRenameEnd(DWord dwPlayerID, bool bSuccess, const char *acName, void *pkReceiver=NULL)
bool WorldServer::SendWBL_RaceBuy(DWord dwSession, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool WorldServer::SendWBL_MapTaskOpr(DWord dwPlayerID, int iOprType, DWord dwParam, void *pkReceiver=NULL)
bool WorldServer::SendWBL_BuyShopItem(DWord dwPlayerID, int types, DWord ShopID, DWord Num, void *pkReceiver=NULL)
bool WorldServer::SendWBL_ShopItemGM(DWord dwPlayerID, int iNum, const ShopItem *GmItems, void *pkReceiver=NULL)
bool WorldServer::SendWBL_ShopItemGM(DWord dwPlayerID, int iNum, std::vector< ShopItem > &GmItems, void *pkReceiver=NULL)
bool WorldServer::SendWBL_GetItemGM(DWord dwPlayerID, DWord ShopID, void *pkReceiver=NULL)
bool WorldServer::SendWBL_CreateNexusFriend(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, const char *acName, const SeDBTime &CreateTime, void *pkReceiver=NULL)
bool WorldServer::SendWBL_CreateNexusOfflineFriend(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, const char *acName, const SeDBTime &CreateTime, void *pkReceiver=NULL)
bool WorldServer::SendWBL_UpdateNexusFriend(DWord dwPlayerID, DWord dwPlayerFriendID, DWord dwMark, void *pkReceiver=NULL)
bool WorldServer::SendWBL_DelNexusFriend(DWord dwPlayerID, DWord dwPlayerFriendID, void *pkReceiver=NULL)
bool WorldServer::SendWBL_UserAlterNickNameReq(DWord dwPlayerID, const char *acNickName, int iResult, void *pkReceiver=NULL)
bool WorldServer::SendWBLData(void *pkData, int iSize, void *pkReceiver)
bool WorldServer::SendWN_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
bool WorldServer::SendWN_HeartPackageRet(void *pkReceiver=NULL)
bool WorldServer::SendWN_NexusFriendInfoSyn(DWord dwPlayerID, const char *acName, int iNum, const SeNexusFriendSyncInfo *akNexusFriendSync, void *pkReceiver=NULL)
bool WorldServer::SendWN_NexusFriendInfoSyn(DWord dwPlayerID, const char *acName, int iNum, std::vector< SeNexusFriendSyncInfo > &akNexusFriendSync, void *pkReceiver=NULL)
bool WorldServer::SendWN_PlayerScoreNtf(DWord dwPlayerID, const MatchType &dwMatchType, DWord dwScore, void *pkReceiver=NULL)
bool WorldServer::SendWNData(void *pkData, int iSize, void *pkReceiver)
bool WorldServer::ProcessNWData(void *pkData, int iSize, void *pkSender=NULL)
bool WorldServer::PreProcessNW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessNW_Register(SeNW_Register *pkData, int iSize, void *pkSender)
void WorldServer::ProcessNW_HeartPackage(SeNW_HeartPackage *pkData, int iSize, void *pkSender)
void WorldServer::ProcessNW_CreateNexusFriendReq(SeNW_CreateNexusFriendReq *pkData, int iSize, void *pkSender)
void WorldServer::ProcessNW_CreateNexusOfflineFriendReq(SeNW_CreateNexusOfflineFriendReq *pkData, int iSize, void *pkSender)
void WorldServer::ProcessNW_UpdateNexusFriendReq(SeNW_UpdateNexusFriendReq *pkData, int iSize, void *pkSender)
void WorldServer::ProcessNW_DelNexusFriendReq(SeNW_DelNexusFriendReq *pkData, int iSize, void *pkSender)
bool WorldServer::SendWR_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
bool WorldServer::SendWR_HeartPackageRet(void *pkReceiver=NULL)
bool WorldServer::SendWRData(void *pkData, int iSize, void *pkReceiver)
bool WorldServer::ProcessRWData(void *pkData, int iSize, void *pkSender=NULL)
bool WorldServer::PreProcessRW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessRW_Register(SeRW_Register *pkData, int iSize, void *pkSender)
void WorldServer::ProcessRW_HeartPackage(SeRW_HeartPackage *pkData, int iSize, void *pkSender)
bool WorldServer::SendWM_RegisterRet(const SeRegisterRet &eRegisterRet, DWord dwAreaID, void *pkReceiver=NULL)
bool WorldServer::SendWM_HeartPackageRet(void *pkReceiver=NULL)
bool WorldServer::SendWMData(void *pkData, int iSize, void *pkReceiver)
bool WorldServer::ProcessMWData(void *pkData, int iSize, void *pkSender=NULL)
bool WorldServer::PreProcessMW(void *pkData, int iSize, void *pkSender)
void WorldServer::ProcessMW_Register(SeMW_Register *pkData, int iSize, void *pkSender)
void WorldServer::ProcessMW_HeartPackage(SeMW_HeartPackage *pkData, int iSize, void *pkSender)
bool WorldServer::LoadConfig(const char *pcFile)
References SeVirtConnMgr::AddServerConn, SeWorldConfig::dwAreaID, SeWorldConfig::dwMaxReconTime, SeWorldConfig::dwServerID, g_kVirtConnMgr, SeConfig::GetDBTime, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeWorldConfig::iAcvmtNumPerPage, SeWorldConfig::iLadderNo, SeWorldConfig::ItemSaveName, SeWorldConfig::kGlobalServer, SeWorldConfig::kLadderEndTime, SeWorldConfig::kLadderStartTime, SeWorldConfig::kLocalServer, SeConfig::Load, CShop::LoadGmItems, m_iBlockServerNum, m_kConfig, m_pkDBSConn, m_Shop, SeLogError, SeLogInfo, SeLogWarning, SSI_BS, StrCpy.
Referenced by Initialize.
void WorldServer::LoadDynamicConfig(bool bIsReLoad=false)
References SeWorldConfig::dwTSHeartPackageTime, GetBlockServerNum, SeConfig::GetValue, SeWorldConfig::iLogShowType, SeWorldConfig::iTSDisconnectOverTime, SeConfig::Load, m_kConfig, m_pakBlockServer, SBST_LOG_SHOW_TYPE, SeLogError, SendWBL_BlockSetup, WS_DELAY_MAX_TIME.
Referenced by ExecuteAction, Initialize.
void WorldServer::SaveUpdateWorldSetup(void)
References SeConfig::Load, SeLogError.
Referenced by Finialize.
bool WorldServer::InitializeNet(void)
References SeNetAddr::acIP, g_kMatchServerMgr, g_kNexusServerMgr, g_kRaceServerMgr, g_kTownServerMgr, moba::ServerSessionMgr::initialize, SeNetAddr::iPort, SeWorldConfig::kLocalServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo, SERVER_BUFFER_SIZE.
Referenced by Initialize.
void WorldServer::InitDBTable()
Referenced by Initialize.
bool WorldServer::InitializeSysManager(void)
Referenced by Initialize.
void WorldServer::InitialFileData(void)
Referenced by Initialize.
void WorldServer::UpdateTSTOWSTime(void)
References SeNetAddr::acIP, SeWorldConfig::dwTSHeartPackageTime, SeTown::GetConnect, SeTown::GetHSock, GetID2Str, SeTown::GetLastRecvTime, SeTown::GetServerID, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeTown::LoadComplete, m_kAllTS, m_kConfig, m_kNetMgr, SeLogError.
Referenced by Update.
void WorldServer::UpdateUnknownState(void)
References SeNetAddr::acIP, moba::Clock::getInstance, moba::Clock::getMilliSeconds, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllConnect, m_kNetMgr, SeLogError, SSI_UNKNOWN, WS_DELAY_MAX_TIME.
Referenced by Update.
void WorldServer::UpdateLSToWSTime(void)
References SeNetAddr::acIP, SeConnect::dwServerID, GetID2Str, moba::Clock::getInstance, moba::Clock::getMilliSeconds, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllLS, m_kNetMgr, SeLogError, WS_DELAY_MAX_TIME.
Referenced by Update.
void WorldServer::UpdateHSToWSTime(void)
References SeNetAddr::acIP, SeConnect::dwServerID, GetID2Str, moba::Clock::getInstance, moba::Clock::getMilliSeconds, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllHS, m_kNetMgr, SeLogError, WS_DELAY_MAX_TIME.
Referenced by Update.
void WorldServer::UpdateLogShow(void)
References GetServerTime, SeWorldConfig::iLogShowType, m_dwLoadCount, m_dwLoadSumTime, m_kConfig, SeLogInfo.
Referenced by Update.
void WorldServer::UpdateWSMsg(void)
References SeMsgData::abyData, SeMsgData::iSize, m_kThreadMsgMgr, SeThreadMsgMgr::PopMsg, ProcessBLWData.
Referenced by Update.
void WorldServer::UpdateDisconnectTS(void)
References SeDisconnectTSInfo::dwDisconnectTime, GetBlockServerNum, GetID2Str, GetServerTime, GetTSByID, IsWSReady, SeDisconnectTSInfo::iTownIndex, SeWorldConfig::iTSDisconnectOverTime, m_kAllDisconnectTS, m_kConfig, SeLogError, SendWBL_LoadPlayerInfoAgain.
Referenced by Update.
void WorldServer::ConnectToGlobal(void)
void WorldServer::RegisterToGlobal(void)
bool WorldServer::LoadConfig(const char *pcFile)
void WorldServer::LoadDynamicConfig(bool bIsReLoad=false)
void WorldServer::SaveUpdateWorldSetup(void)
bool WorldServer::InitializeNet(void)
void WorldServer::InitDBTable()
bool WorldServer::InitializeSysManager(void)
void WorldServer::InitialFileData(void)
void WorldServer::UpdateTSTOWSTime(void)
void WorldServer::UpdateUnknownState(void)
void WorldServer::UpdateLSToWSTime(void)
void WorldServer::UpdateHSToWSTime(void)
void WorldServer::UpdateLogShow(void)
void WorldServer::UpdateWSMsg(void)
void WorldServer::UpdateDisconnectTS(void)
void WorldServer::ConnectToGlobal(void)
void WorldServer::RegisterToGlobal(void)