SeBaseServer
SeBaseServer::SeBaseServer()
virtual SeBaseServer::~SeBaseServer()
virtual bool SeBaseServer::Initialize()=0
Referenced by ServerMain.
virtual void SeBaseServer::Update(void)=0
Referenced by ServerMain.
virtual void SeBaseServer::Finialize(void)=0
Referenced by ServerMain.
virtual void SeBaseServer::ShowConsoleTitle(int iDTime)=0
Referenced by ServerMain.
virtual SeServerActionResult SeBaseServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK.