AIPrioTableMgr
std::map<unsigned int,AIPrioTable*> AIPrioTableMgr::m_kAIPrioTableMap
Referenced by FillData, GetAIPrioTable, GetAIPrioTableMap, GetAIPrioTableVec, ~AIPrioTableMgr.
AIPrioTableMgr * AIPrioTableMgr::m_pkAIPrioTableMgr
Referenced by Get, ReLoad.
AIPrioTableMgr * AIPrioTableMgr::Get()
References AIPrioTableMgr, m_pkAIPrioTableMgr.
Referenced by ReLoad.
AIPrioTableMgr * AIPrioTableMgr::ReLoad()
References Get, m_pkAIPrioTableMgr.
AIPrioTableMgr::AIPrioTableMgr()
References Load.
Referenced by Get.
AIPrioTableMgr::~AIPrioTableMgr()
References m_kAIPrioTableMap.
const AIPrioTable * AIPrioTableMgr::GetAIPrioTable(unsigned int iTypeID)
References m_kAIPrioTableMap.
const std::map< unsigned int, AIPrioTable * > & AIPrioTableMgr::GetAIPrioTableMap()
References m_kAIPrioTableMap.
TableResArray AIPrioTableMgr::GetAIPrioTableVec()
References m_kAIPrioTableMap, TableResArray::pushBack.
bool AIPrioTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AIPrioTableMgr.
void AIPrioTableMgr::FillData(AIPrioTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AIPrioTable::fBasePrio, AIPrioTable::fValueA, AIPrioTable::fValueB, AIPrioTable::fValueC, AIPrioTable::fValueD, AIPrioTable::fValueE, AIPrioTable::fValueF, AIPrioTable::fValueG, AIPrioTable::fValueH, AIPrioTable::fValueI, AIPrioTable::kDesc_China, AIPrioTable::kName_China, m_kAIPrioTableMap, AIPrioTable::uiTypeID.
Referenced by Load.