WatchServer::CWatchServer
typedef std::map<HSock, DWord> WatchServer::CWatchServer::TSockServerDataMap
char WatchServer::CWatchServer::m_acSend[RACERECORD_SEND_SIZE][RACERECORD_SEND_SIZE]
Referenced by CWatchServer.
char WatchServer::CWatchServer::m_acPraseBuf[SSD_PRASER_SIZE][SSD_PRASER_SIZE]
Referenced by CWatchServer.
DWord WatchServer::CWatchServer::m_dwTickCount
Referenced by CWatchServer, Update.
DWord WatchServer::CWatchServer::m_dwCurTime
Referenced by CheckConnect, CWatchServer, GetServerTime, OnPlayerConnected, PreProcessNWCMS, Register2RS, Register2WCMS, Update.
bool WatchServer::CWatchServer::m_bWCMSReady
Referenced by CWatchServer, SetWatchMgrServerReady.
SeWatchConfig WatchServer::CWatchServer::m_kConfig
Referenced by Connect2WCMS, GetServerID, GetWatchConfig, Initialize, InitializeNet, IsWatchMgrServerReady, LoadConfig, onDelRace, onHandleNewRace, OnNetAccept, OnNetConnected, OnNetDisconnect, ProcessRWCS_RegisterRet, ProcessWCMSWCS_RegisterRet, Register2RS, Register2WCMS, ShowConsoleTitle, UpdateHeartPkg, UpdateRsState, UpdateWCMSState.
int WatchServer::CWatchServer::m_iRegisterCount
Referenced by CWatchServer, ProcessWCMSWCS_RegisterRet, Register2WCMS.
MapAllConnect WatchServer::CWatchServer::m_kAllConnect
Referenced by CheckConnect, OnNetAccept, OnNetDisconnect, OnNetRecv, OnPlayerDisconnect, SetPlayerConnect, ShowConsoleTitle.
MapAllInnerConnect WatchServer::CWatchServer::m_kAllInnerConnect
Referenced by OnNetAccept, OnNetDisconnect, OnNetRecv.
TeNetMgr WatchServer::CWatchServer::m_kNetMgr
Referenced by Connect2WCMS, DisconnectPlayer, InitializeNet, OnNetAccept, OnNetRecv, SendWCMSNData, SendWCMSTData, SendWCMSWCSData, SendWCSCData, SendWCSRData, SendWCSSWCSData, SendWCSWCMSData, SendWCSWCSSData, Update, UpdateHeartPkg, UpdateRsState.
SeServerData WatchServer::CWatchServer::m_vWcsMgrServerData
Referenced by Connect2WCMS, IsWatchMgrServerReady, OnNetConnected, OnNetDisconnect, OnNetRecv, ProcessWCMSWCS_RegisterRet, Register2WCMS, UpdateHeartPkg, UpdateWCMSState.
VecServerData WatchServer::CWatchServer::m_vRsServerData
Referenced by OnNetConnected, OnNetDisconnect, OnNetRecv, ProcessRWCS_HeartPackageRet, ProcessRWCS_RegisterRet, UpdateHeartPkg, UpdateRsState.
TSockServerDataMap WatchServer::CWatchServer::m_mSockRsServerData
Referenced by OnNetConnected, OnNetDisconnect, OnNetRecv, ProcessRWCS_HeartPackageRet, ProcessRWCS_RegisterRet.
SeServerData WatchServer::CWatchServer::m_vWCSMasterServerData
Referenced by OnNetConnected, OnNetDisconnect, OnNetRecv, UpdateHeartPkg.
SeVirtConn* WatchServer::CWatchServer::m_pkNSConn
Referenced by CWatchServer, InitializeNet, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessNWCMS, ProcessNWCMS_RegisterRet, SendWCMSNData.
WatchServer::CWatchServer::CWatchServer(void)
References m_acPraseBuf, m_acSend, m_bWCMSReady, m_dwCurTime, m_dwTickCount, m_iRegisterCount, m_pkNSConn.
WatchServer::CWatchServer::~CWatchServer(void)
bool WatchServer::CWatchServer::Initialize(void)
References WatchServer::SeWatchConfig::bMgr, WatchServer::g_kWatchServerMgr, GetServerID, InitializeNet, SeNetAddr::IsEmpty, WatchServer::SeWatchConfig::kAddrToPlayer, LoadConfig, m_kConfig, WatchServer::CWatchServerMgr::registerWCS, WatchServer::SeWatchServerInfo::setAddr2Player, WatchServer::SeWatchServerInfo::setConnect, WatchServer::SeWatchServerInfo::setServerID.
void WatchServer::CWatchServer::Update(void)
References WatchServer::g_kRaceMgr, g_kVirtConnMgr, m_dwCurTime, m_dwTickCount, m_kNetMgr, WatchServer::CSeRaceMgr::Update, SeVirtConnMgr::Update, UpdateHeartPkg, UpdateWCMSState.
void WatchServer::CWatchServer::Finialize(void)
void WatchServer::CWatchServer::ShowConsoleTitle(int iDTime)
References WatchServer::SeWatchConfig::bMgr, WatchServer::g_kRaceMgr, WatchServer::g_kWatchServerMgr, WatchServer::CWatchServerMgr::getAllRaceCounts, WatchServer::CSeRaceMgr::getAllRaceCounts, GetID2Str, GetServerID, m_kAllConnect, m_kConfig, SPrintf.
SeServerActionResult WatchServer::CWatchServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, SeLogHideTime.
void WatchServer::CWatchServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeServerData::bConnecting, g_kVirtConnMgr, SeNetAddr::iPort, WatchServer::SeWatchConfig::kMasterServer, SeVirtConn::kNetAddr, SeServerData::kSock, WatchServer::SeWatchConfig::kWatchMgrServer, m_kConfig, m_mSockRsServerData, m_pkNSConn, m_vRsServerData, m_vWCSMasterServerData, m_vWcsMgrServerData, SeVirtConnMgr::OnServerConnected, SeLogError, SeLogInfo, WatchServer::SeWatchConfig::vAddrRS.
void WatchServer::CWatchServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, WatchServer::SeInnerConnect::eState, SeNetAddr::iPort, IsWatchMgrServerReady, WatchServer::SeWatchConfig::kAddrToPlayer, WatchServer::SeWatchConfig::kLocalServer, WatchServer::SeInnerConnect::kNetAddr, WatchServer::SeConnect::kSock, WatchServer::SeInnerConnect::kSock, m_kAllConnect, m_kAllInnerConnect, m_kConfig, m_kNetMgr, OnPlayerConnected, WatchServer::SCS_UNKOWN, SSD_IP_LEN, StrCpy.
void WatchServer::CWatchServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References CMD_TWCMS_REGISTER, CMD_WCSSWCS_REGISTER, CMD_WCSWCMS_REGISTER, WatchServer::SeConnect::dwLastRecvTime, WatchServer::SeInnerConnect::dwLastRecvTime, WatchServer::SeConnect::dwPackCount, WatchServer::SeInnerConnect::eState, GetServerTime, SeServerData::kSock, SeVirtConn::kSock, m_kAllConnect, m_kAllInnerConnect, m_kNetMgr, m_mSockRsServerData, m_pkNSConn, m_vRsServerData, m_vWCSMasterServerData, m_vWcsMgrServerData, ProcessCWCSData, ProcessNWCMSData, ProcessRWCSData, ProcessTWCMSData, ProcessWCMSWCSData, ProcessWCSSWCSData, ProcessWCSWCMSData, ProcessWCSWCSSData, WatchServer::SCS_TOWN_OK, WatchServer::SCS_UNKOWN, WatchServer::SCS_WATCHSERVER_OK, WatchServer::SCS_WATCHSLAVESERVER_OK, SeCMD::wCmd.
void WatchServer::CWatchServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, SeServerData::bConnecting, SeServerData::bRegistered, SeServerData::dwRegisterTime, WatchServer::SeInnerConnect::eState, WatchServer::g_kTownMgr, g_kVirtConnMgr, SeNetAddr::iPort, WatchServer::SeWatchConfig::kMasterServer, WatchServer::SeInnerConnect::kNetAddr, SeServerData::kSock, SeVirtConn::kSock, WatchServer::SeInnerConnect::kTownSign, WatchServer::SeWatchConfig::kWatchMgrServer, m_kAllConnect, m_kAllInnerConnect, m_kConfig, m_mSockRsServerData, m_pkNSConn, m_vRsServerData, m_vWCSMasterServerData, m_vWcsMgrServerData, OnPlayerDisconnect, SeVirtConnMgr::OnServerDisconnect, WatchServer::SeTownMgr::OnTSDisconnect, WatchServer::SCS_TOWN_OK, SeLogError, WatchServer::SeWatchConfig::vAddrRS.
bool WatchServer::CWatchServer::ProcessRWCSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WatchServer::CWatchServer::PreProcessRWCS(void *pkData, int iSize, void *pkSender)
void WatchServer::CWatchServer::ProcessRWCS_RegisterRet(SeRWCS_RegisterRet *pkData, int iSize, void *pkSender)
References SeRWCS_RegisterRet::eRet, m_kConfig, m_mSockRsServerData, m_vRsServerData, SeLogError, SeLogInfo, SRR_SUCCESS, WatchServer::SeWatchConfig::vAddrRS.
void WatchServer::CWatchServer::ProcessRWCS_HeartPackageRet(SeRWCS_HeartPackageRet *pkData, int iSize, void *pkSender)
References m_mSockRsServerData, m_vRsServerData.
void WatchServer::CWatchServer::ProcessRWCS_RaceRecord(SeRWCS_RaceRecord *pkData, int iSize, void *pkSender)
References TeMD5::abyMD5, WatchServer::g_kRaceMgr, SeRWCS_RaceRecord::iNum, WatchServer::CSeRaceMgr::pushRaceData, SeRWCS_RaceRecord::raceDat, SeRWCS_RaceRecord::rID.
void WatchServer::CWatchServer::ProcessRWCS_RaceEnd(SeRWCS_RaceEnd *pkData, int iSize, void *pkSender)
References TeMD5::abyMD5, WatchServer::g_kRaceMgr, GetMD52Str, WatchServer::CSeRaceMgr::onRaceEnd, SeRWCS_RaceEnd::rID, SeLogInfo.
void WatchServer::CWatchServer::ProcessRWCS_RaceStart(SeRWCS_RaceStart *pkData, int iSize, void *pkSender)
References WatchServer::g_kRaceMgr, GetMD52Str, SeRWCS_RaceStart::iNum, WatchServer::CSeRaceMgr::onRaceStart, SeRWCS_RaceStart::racePlayerSeatInfo, SeRWCS_RaceStart::rID, SeLogInfo, TeMD5FromArray.
void WatchServer::CWatchServer::ProcessRWCS_RaceDetailInfoSync(SeRWCS_RaceDetailInfoSync *pkData, int iSize, void *pkSender)
References SeRWCS_RaceDetailInfoSync::akRaceDetailInfo, WatchServer::g_kRaceMgr, SeRWCS_RaceDetailInfoSync::num, WatchServer::CSeRaceMgr::onRaceDetailSync.
bool WatchServer::CWatchServer::SendWCSR_Register(DWord dwServerID, int iSize, const SeWCSViewInfo *acViewInfo, void *pkReceiver=NULL)
Referenced by Register2RS.
bool WatchServer::CWatchServer::SendWCSR_Register(DWord dwServerID, int iSize, std::vector< SeWCSViewInfo > &acViewInfo, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCSR_HeartPackage(void *pkReceiver=NULL)
Referenced by UpdateHeartPkg.
bool WatchServer::CWatchServer::SendWCSRData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool WatchServer::CWatchServer::ProcessWCSWCMSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WatchServer::CWatchServer::PreProcessWCSWCMS(void *pkData, int iSize, void *pkSender)
void WatchServer::CWatchServer::ProcessWCSWCMS_Register(SeWCSWCMS_Register *pkData, int iSize, void *pkSender)
References WatchServer::SeInnerConnect::eState, WatchServer::SCS_UNKOWN, WatchServer::SCS_WATCHSERVER_OK.
bool WatchServer::CWatchServer::SendWCSWCMS_Register(DWord dwServerID, const SeNetAddr &kAddrToPlayer, int iRegisterCount, bool bOpen, void *pkReceiver=NULL)
Referenced by Register2WCMS.
bool WatchServer::CWatchServer::SendWCSWCMSData(void *pkData, int iSize, void *pkReceiver)
References WatchServer::SeInnerConnect::kSock, m_kNetMgr.
bool WatchServer::CWatchServer::ProcessWCMSWCSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WatchServer::CWatchServer::PreProcessWCMSWCS(void *pkData, int iSize, void *pkSender)
void WatchServer::CWatchServer::ProcessWCMSWCS_RegisterRet(SeWCMSWCS_RegisterRet *pkData, int iSize, void *pkSender)
References SeServerData::bRegistered, SeServerData::dwHeartPackageTime, WatchServer::SeWatchConfig::dwServerID, SeWCMSWCS_RegisterRet::eRet, GetID2Str, m_iRegisterCount, m_kConfig, m_vWcsMgrServerData, SeLogError, SeLogInfo, SetWatchMgrServerReady, SRR_REPEAT, SRR_SUCCESS.
bool WatchServer::CWatchServer::SendWCMSWCS_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCMSWCSData(void *pkData, int iSize, void *pkReceiver)
References WatchServer::SeInnerConnect::kSock, m_kNetMgr.
bool WatchServer::CWatchServer::ProcessWCSSWCSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WatchServer::CWatchServer::PreProcessWCSSWCS(void *pkData, int iSize, void *pkSender)
void WatchServer::CWatchServer::ProcessWCSSWCS_Register(SeWCSSWCS_Register *pkData, int iSize, void *pkSender)
bool WatchServer::CWatchServer::SendWCSSWCS_Register(DWord dwServerID, DWord dwAreaID, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCSSWCSData(void *pkData, int iSize, void *pkReceiver)
References WatchServer::SeInnerConnect::kSock, m_kNetMgr.
bool WatchServer::CWatchServer::ProcessWCSWCSSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WatchServer::CWatchServer::PreProcessWCSWCSS(void *pkData, int iSize, void *pkSender)
void WatchServer::CWatchServer::ProcessWCSWCSS_RegisterRet(SeWCSWCSS_RegisterRet *pkData, int iSize, void *pkSender)
bool WatchServer::CWatchServer::SendWCSWCSS_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCSWCSSData(void *pkData, int iSize, void *pkReceiver)
References WatchServer::SeInnerConnect::kSock, m_kNetMgr.
bool WatchServer::CWatchServer::ProcessCWCSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WatchServer::CWatchServer::PreProcessCWCS(void *pkData, int iSize, void *pkSender)
void WatchServer::CWatchServer::ProcessCWCS_ViewValidate(SeCWCS_ViewValidate *pkData, int iSize, void *pkSender)
References SeCWCS_ViewValidate::dwPlayerID, SeCWCS_ViewValidate::eValidType, WatchServer::g_kRaceMgr, WatchServer::SeConnect::kSock, WatchServer::CSeRaceMgr::onViewValidate, SeCWCS_ViewValidate::raceID, SRVT_VIEW, TeMD5FromArray.
bool WatchServer::CWatchServer::ProcessTWCMSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WatchServer::CWatchServer::PreProcessTWCMS(void *pkData, int iSize, void *pkSender)
void WatchServer::CWatchServer::ProcessTWCMS_Register(SeTWCMS_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, WatchServer::SeTown::dwAreaID, SeTWCMS_Register::dwAreaID, WatchServer::SeTown::dwLastRecvTime, WatchServer::SeTown::dwServerID, SeTWCMS_Register::dwServerID, WatchServer::SeInnerConnect::eState, WatchServer::g_kTownMgr, GetID2Str, GetServerTime, WatchServer::SeTownMgr::GetTown, SeNetAddr::iPort, WatchServer::SeInnerConnect::kNetAddr, WatchServer::SeInnerConnect::kSock, WatchServer::SeInnerConnect::kTownSign, WatchServer::SeTownMgr::OnTSRegister, WatchServer::SeTown::pkConnect, WatchServer::SCS_TOWN_OK, WatchServer::SCS_UNKOWN, SeLogError, SeLogInfo, SendWCMST_RegisterRet, SRR_REPEAT, SRR_SUCCESS.
void WatchServer::CWatchServer::ProcessTWCMS_HeartPackage(SeTWCMS_HeartPackage *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeNetAddr::iPort, WatchServer::SeInnerConnect::kNetAddr, WatchServer::SeInnerConnect::kSock, SeLogError, SendWCMST_HeartPackageRet.
void WatchServer::CWatchServer::ProcessTWCMS_ReqView(SeTWCMS_ReqView *pkData, int iSize, void *pkSender)
References SeTWCMS_ReqView::dwPlayerID, WatchServer::g_kWatchServerMgr, GET_CUR_CONN_AND_TOWN, WatchServer::CWatchServerMgr::onReqView, SeTWCMS_ReqView::rID, TeMD5FromArray.
void WatchServer::CWatchServer::ProcessTWCMS_ReqViewList(SeTWCMS_ReqViewList *pkData, int iSize, void *pkSender)
References SeTWCMS_ReqViewList::dwPlayerID, WatchServer::g_kWatchServerMgr, GET_CUR_CONN_AND_TOWN, SeTWCMS_ReqViewList::iPage, WatchServer::CWatchServerMgr::onReqViewList.
void WatchServer::CWatchServer::ProcessTWCMS_RaceDetailInfoReq(SeTWCMS_RaceDetailInfoReq *pkData, int iSize, void *pkSender)
References SeTWCMS_RaceDetailInfoReq::dwPlayerID, WatchServer::g_kWatchServerMgr, GET_CUR_CONN_AND_TOWN, WatchServer::CWatchServerMgr::onRaceDetailInfoReq, SeTWCMS_RaceDetailInfoReq::page_counts, SeTWCMS_RaceDetailInfoReq::page_number, SeLogError.
bool WatchServer::CWatchServer::SendWCMST_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
Referenced by ProcessTWCMS_Register.
bool WatchServer::CWatchServer::SendWCMST_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessTWCMS_HeartPackage.
bool WatchServer::CWatchServer::SendWCMST_ResView(DWord dwPlayerID, const Byte *rID, const SePtlNetAddr &kViewAddr, void *pkReceiver=NULL)
Referenced by WatchServer::CWatchServerMgr::onReqView.
bool WatchServer::CWatchServer::SendWCMST_ResView(DWord dwPlayerID, std::vector< Byte > &rID, const SePtlNetAddr &kViewAddr, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCMST_ResViewList(DWord dwPlayerID, int iPage, int iMaxPage, int iNum, const SeViewList *akSeViewList, void *pkReceiver=NULL)
Referenced by WatchServer::CWatchServerMgr::onReqViewList.
bool WatchServer::CWatchServer::SendWCMST_ResViewList(DWord dwPlayerID, int iPage, int iMaxPage, int iNum, std::vector< SeViewList > &akSeViewList, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCMST_ResRaceDetailInfo(DWord dwPlayerID, int page_number, int page_max_number, int iNum, const SeRaceDetailInfo *akRaceDetailInfo, void *pkReceiver=NULL)
Referenced by WatchServer::CWatchServerMgr::onRaceDetailInfoReq.
bool WatchServer::CWatchServer::SendWCMST_ResRaceDetailInfo(DWord dwPlayerID, int page_number, int page_max_number, int iNum, std::vector< SeRaceDetailInfo > &akRaceDetailInfo, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCMSTData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool WatchServer::CWatchServer::SendWCSC_EncryptKey(const char *abyEncryptKey, DWord dwVersion, void *pkReceiver=NULL)
Referenced by OnPlayerConnected.
bool WatchServer::CWatchServer::SendWCSC_ViewValidateRet(SeWCSValidateCode res, void *pkReceiver=NULL)
Referenced by WatchServer::CSeRaceMgr::onViewValidate.
bool WatchServer::CWatchServer::SendWCSC_ViewPack(int iOffset, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by WatchServer::CSeRaceMgr::updateView.
bool WatchServer::CWatchServer::SendWCSC_ViewPack(int iOffset, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCSC_ViewPlayerInfo(int iNum, const SePlayerInfoSeat *akSeat, void *pkReceiver=NULL)
Referenced by WatchServer::CSeRaceMgr::BeginView.
bool WatchServer::CWatchServer::SendWCSC_ViewPlayerInfo(int iNum, std::vector< SePlayerInfoSeat > &akSeat, void *pkReceiver=NULL)
bool WatchServer::CWatchServer::SendWCSCData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool WatchServer::CWatchServer::ProcessNWCMSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool WatchServer::CWatchServer::PreProcessNWCMS(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkNSConn.
void WatchServer::CWatchServer::ProcessNWCMS_RegisterRet(SeNWCMS_RegisterRet *pkData, int iSize, void *pkSender)
References SeNWCMS_RegisterRet::dwAreaID, SeVirtConn::dwAreaID, SeNWCMS_RegisterRet::eRegisterRet, SeVirtConn::eState, m_pkNSConn, SeLogError, SeLogInfo, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void WatchServer::CWatchServer::ProcessNWCMS_HeartPackageRet(SeNWCMS_HeartPackageRet *pkData, int iSize, void *pkSender)
bool WatchServer::CWatchServer::SendWCMSN_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool WatchServer::CWatchServer::SendWCMSN_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool WatchServer::CWatchServer::SendWCMSN_RaceWatchUserSync(DWord dwPlayerID, DWord dwStateID, void *pkReceiver=NULL)
Referenced by WatchServer::CWatchServerMgr::onRaceWatchUserSync.
bool WatchServer::CWatchServer::SendWCMSNData(void *pkData, int iSize, void *pkReceiver)
References CMD_WCMSN_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkNSConn, SVCS_REGISTERED, SeCMD::wCmd.
void WatchServer::CWatchServer::OnPlayerConnected(SeConnect *pkConnect, const char *pcIP, int iPort)
References WatchServer::SeConnect::acEncryptKey, SeNetAddr::acIP, WatchServer::SeConnect::dwLastRecvTime, WatchServer::SeConnect::dwPlayerID, WatchServer::SeConnect::dwStateTime, WatchServer::SeConnect::eState, GenEncryptKey, SeNetAddr::iPort, WatchServer::SeConnect::kNetAddr, WatchServer::SeConnect::kSock, LOGIC_VERSION, m_dwCurTime, WatchServer::SCS_UNKOWN, SeLogInfo, SendWCSC_EncryptKey, SSD_EN_KEY_LEN, StrCpy.
Referenced by OnNetAccept.
void WatchServer::CWatchServer::OnPlayerDisconnect(HSock rkSock, TeDisconnectCode eCode)
References DisconnectPlayer, WatchServer::SeConnect::dwPlayerID, WatchServer::g_kRaceMgr, m_kAllConnect, WatchServer::CSeRaceMgr::removeViewPlayer.
Referenced by OnNetDisconnect.
bool WatchServer::CWatchServer::LoadConfig(const char *pcFile)
References WatchServer::SeWatchConfig::acGameRecordFilePath, WatchServer::SeWatchConfig::bMgr, WatchServer::SeWatchConfig::bSlave, WatchServer::SeWatchConfig::dwServerID, WatchServer::SeWatchConfig::dwViewListNum, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, WatchServer::SeWatchConfig::iDebugLevel, WatchServer::SeWatchConfig::kAddrToPlayer, WatchServer::SeWatchConfig::kLocalServer, WatchServer::SeWatchConfig::kMasterServer, WatchServer::SeWatchConfig::kWatchMgrServer, SeConfig::Load, m_kConfig, SeLogError, StrCpy, WatchServer::SeWatchConfig::vAddrRS.
Referenced by Initialize.
void WatchServer::CWatchServer::ReLoadConfig()
SeWatchConfig WatchServer::CWatchServer::GetWatchConfig()
References m_kConfig.
Referenced by WatchServer::CWatchServerMgr::onReqViewList, WatchServer::SeRaceRecordSaveThread::saveRecord.
bool WatchServer::CWatchServer::IsWatchMgrServerReady()
References WatchServer::SeWatchConfig::bMgr, SeServerData::bRegistered, SeServerData::kSock, m_kConfig, m_vWcsMgrServerData.
Referenced by OnNetAccept.
DWord WatchServer::CWatchServer::GetServerID()
References WatchServer::SeWatchConfig::dwServerID, m_kConfig.
Referenced by Initialize, onHandleNewRace, sendRegPack, ShowConsoleTitle.
DWord WatchServer::CWatchServer::GetServerTime(void)
References m_dwCurTime.
Referenced by OnNetRecv, ProcessTWCMS_Register, WatchServer::CSeRaceMgr::Update, UpdateHeartPkg, UpdateWCMSState.
void WatchServer::CWatchServer::onHandleNewRace(const TeMD5 &rRaceID)
References WatchServer::CWatchServerMgr::addViewRace, WatchServer::SeWatchConfig::bMgr, WatchServer::g_kWatchServerMgr, GetServerID, m_kConfig.
Referenced by WatchServer::CSeRaceMgr::updateView.
void WatchServer::CWatchServer::onDelRace(const TeMD5 &rRaceID)
References WatchServer::SeWatchConfig::bMgr, WatchServer::CWatchServerMgr::delViewRace, WatchServer::g_kWatchServerMgr, m_kConfig.
Referenced by WatchServer::CSeRaceMgr::onRaceEnd.
void WatchServer::CWatchServer::DisconnectPlayer(HSock &rSock)
References m_kNetMgr.
Referenced by CheckConnect, OnPlayerDisconnect, WatchServer::CSeRaceMgr::updateView.
void WatchServer::CWatchServer::SetPlayerConnect(HSock kSock, DWord dwPlayerID)
References WatchServer::SeConnect::dwPlayerID, m_kAllConnect.
Referenced by WatchServer::CSeRaceMgr::addViewPlayer.
void WatchServer::CWatchServer::RaceWatchUserSync(DWord dwPlayerID, DWord dwStateID)
References WatchServer::g_kWatchServerMgr, WatchServer::CWatchServerMgr::onRaceWatchUserSync.
Referenced by WatchServer::CSeRaceMgr::onViewValidate.
bool WatchServer::CWatchServer::InitializeNet(void)
References SeNetAddr::acIP, SeVirtConnMgr::AddServerConn, CLIENT_BUFFER_SIZE, g_kVirtConnMgr, SeConfig::GetNetAddr, SeVirtConnMgr::Initialize, SeNetAddr::iPort, WatchServer::SeWatchConfig::kAddrToPlayer, WatchServer::SeWatchConfig::kLocalServer, SeConfig::Load, m_kConfig, m_kNetMgr, m_pkNSConn, SeLogError, SeLogInfo, sendHeartPack, sendRegPack, SERVER_BUFFER_SIZE, SSI_NS.
Referenced by Initialize.
void WatchServer::CWatchServer::SetWatchMgrServerReady(bool bReady)
References m_bWCMSReady.
Referenced by ProcessWCMSWCS_RegisterRet.
void WatchServer::CWatchServer::DisconnectPlayer(SeConnect *pkConn)
References WatchServer::SeConnect::kSock, m_kNetMgr.
void WatchServer::CWatchServer::CheckConnect()
References DisconnectPlayer, WatchServer::SeConnect::dwStateTime, WatchServer::SeConnect::eState, m_dwCurTime, m_kAllConnect, WatchServer::SCS_UNKOWN.
void WatchServer::CWatchServer::UpdateRsState()
References SeNetAddr::acIP, SeNetAddr::iPort, m_kConfig, m_kNetMgr, m_vRsServerData, Register2RS, SeLogError, SERVER_BUFFER_SIZE, WatchServer::SeWatchConfig::vAddrRS.
Referenced by UpdateWCMSState.
void WatchServer::CWatchServer::UpdateWCMSState()
References WatchServer::SeWatchConfig::bMgr, SeServerData::bRegistered, Connect2WCMS, GetServerTime, SeServerData::kSock, m_kConfig, m_vWcsMgrServerData, Register2WCMS, UpdateRsState.
Referenced by Update.
void WatchServer::CWatchServer::Connect2WCMS()
References SeNetAddr::acIP, SeServerData::bConnecting, SeNetAddr::iPort, WatchServer::SeWatchConfig::kWatchMgrServer, m_kConfig, m_kNetMgr, m_vWcsMgrServerData, SeLogError, SERVER_BUFFER_SIZE.
Referenced by UpdateWCMSState.
void WatchServer::CWatchServer::Register2WCMS()
References SeServerData::dwRegisterTime, WatchServer::SeWatchConfig::dwServerID, WatchServer::SeWatchConfig::kAddrToPlayer, SeServerData::kSock, m_dwCurTime, m_iRegisterCount, m_kConfig, m_vWcsMgrServerData, WatchServer::RECONNECT_TIME, SeLogError, SendWCSWCMS_Register.
Referenced by UpdateWCMSState.
void WatchServer::CWatchServer::Register2RS(SeServerData &rServerDat)
References SeServerData::dwRegisterTime, WatchServer::SeWatchConfig::dwServerID, WatchServer::g_kRaceMgr, WatchServer::CSeRaceMgr::getRaceViewInfos, SeServerData::kSock, m_dwCurTime, m_kConfig, WatchServer::RECONNECT_TIME, SeLogError, SendWCSR_Register.
Referenced by UpdateRsState.
DWord WatchServer::CWatchServer::GetServerID() const
References WatchServer::SeWatchConfig::dwServerID, m_kConfig.
void WatchServer::CWatchServer::UpdateHeartPkg()
References WatchServer::SeWatchConfig::bMgr, WatchServer::SeWatchConfig::bSlave, GetServerTime, m_kConfig, m_vRsServerData, m_vWCSMasterServerData, m_vWcsMgrServerData, WatchServer::SHS_RS, WatchServer::SHS_WCMS, WatchServer::SHS_WCS.
Referenced by Update.
void WatchServer::CWatchServer::UpdateHeartPkg(SeServerData &rSrvDat, SeHeartState eHeart)
References SeServerData::dwHeartPackageTime, SeServerData::dwID, GetID2Str, GetServerTime, SeServerData::kSock, m_kNetMgr, SeLogError, SendWCSR_HeartPackage, WatchServer::SHS_RS.