AvatarEffectTableMgr
std::map<unsigned int,AvatarEffectTable*> AvatarEffectTableMgr::m_kAvatarEffectTableMap
Referenced by FillData, GetAvatarEffectTable, GetAvatarEffectTableMap, GetAvatarEffectTableVec, ~AvatarEffectTableMgr.
AvatarEffectTableMgr * AvatarEffectTableMgr::m_pkAvatarEffectTableMgr
Referenced by Get, ReLoad.
AvatarEffectTableMgr * AvatarEffectTableMgr::Get()
References AvatarEffectTableMgr, m_pkAvatarEffectTableMgr.
Referenced by GlobalTableMgr::GetAvatarEffectTable, GlobalTableMgr::GetAvatarEffectTableMap, ReLoad.
AvatarEffectTableMgr * AvatarEffectTableMgr::ReLoad()
References Get, m_pkAvatarEffectTableMgr.
Referenced by TableMgr::ReloadTable.
AvatarEffectTableMgr::AvatarEffectTableMgr()
References Load.
Referenced by Get.
AvatarEffectTableMgr::~AvatarEffectTableMgr()
References m_kAvatarEffectTableMap.
const AvatarEffectTable * AvatarEffectTableMgr::GetAvatarEffectTable(unsigned int iTypeID)
References m_kAvatarEffectTableMap.
Referenced by GlobalTableMgr::GetAvatarEffectTable.
const std::map< unsigned int, AvatarEffectTable * > & AvatarEffectTableMgr::GetAvatarEffectTableMap()
References m_kAvatarEffectTableMap.
Referenced by GlobalTableMgr::GetAvatarEffectTableMap.
TableResArray AvatarEffectTableMgr::GetAvatarEffectTableVec()
References m_kAvatarEffectTableMap, TableResArray::pushBack.
bool AvatarEffectTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AvatarEffectTableMgr.
void AvatarEffectTableMgr::FillData(AvatarEffectTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AvatarEffectTable::kDelDelay, AvatarEffectTable::kHookName, AvatarEffectTable::kName_China, AvatarEffectTable::kResPath, m_kAvatarEffectTableMap, AvatarEffectTable::uiAvatarEffID, AvatarEffectTable::uiAvatarType, AvatarEffectTable::uiReplaceOrgEffID.
Referenced by Load.