ModelResTableMgr
std::map<unsigned int,ModelResTable*> ModelResTableMgr::m_kModelResTableMap
Referenced by FillData, GetModelResTable, GetModelResTableMap, GetModelResTableVec, ~ModelResTableMgr.
ModelResTableMgr * ModelResTableMgr::m_pkModelResTableMgr
Referenced by Get, ReLoad.
ModelResTableMgr * ModelResTableMgr::Get()
References m_pkModelResTableMgr, ModelResTableMgr.
Referenced by TableMgr::GetActionResVec, TableMgr::GetActionResVecAll, GlobalTableMgr::GetModelResTable, GlobalTableMgr::GetModelResTableMap, TableMgr::GetModleIndex, TableMgr::GetPreLoadRes, TableMgr::InitModelRes, TableMgr::LoadTable, ReLoad.
ModelResTableMgr * ModelResTableMgr::ReLoad()
References Get, m_pkModelResTableMgr.
Referenced by TableMgr::ReloadTable.
ModelResTableMgr::ModelResTableMgr()
References Load.
Referenced by Get.
ModelResTableMgr::~ModelResTableMgr()
References m_kModelResTableMap.
const ModelResTable * ModelResTableMgr::GetModelResTable(unsigned int iTypeID)
References m_kModelResTableMap.
Referenced by GlobalTableMgr::GetModelResTable.
const std::map< unsigned int, ModelResTable * > & ModelResTableMgr::GetModelResTableMap()
References m_kModelResTableMap.
Referenced by TableMgr::GetActionResVec, TableMgr::GetActionResVecAll, GlobalTableMgr::GetModelResTableMap, TableMgr::GetModleIndex, TableMgr::GetPreLoadRes, TableMgr::InitModelRes.
TableResArray ModelResTableMgr::GetModelResTableVec()
References m_kModelResTableMap, TableResArray::pushBack.
bool ModelResTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by ModelResTableMgr.
void ModelResTableMgr::FillData(ModelResTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, ModelResTable::bActionRes, ModelResTable::bNeedScaleWithUnit, ModelResTable::DelDelay, ModelResTable::iEffectRange, ModelResTable::iPreLoad, ModelResTable::kAttachPos, ModelResTable::kDesc, ModelResTable::kHitSound, ModelResTable::kPath, ModelResTable::kPreLoadPath, m_kModelResTableMap, ModelResTable::uiID, ModelResTable::uiOwner.
Referenced by Load.