SeConfig
char SeConfig::m_acString[512][512]
Referenced by GetValue, SeConfig.
SeNetAddr SeConfig::m_kNetAddr
Referenced by GetNetAddr.
SeDBAddr SeConfig::m_kDBAddr
Referenced by GetDBAddr, GetDBTableAddrFromStr, GetLogDBAddr.
SeDBTableAddr SeConfig::m_kDBTableAddr
Referenced by GetDBTableAddrFromStr.
SeRedisAddr SeConfig::m_kRedisAddr
Referenced by GetRedisAddrFromStr.
SeLogDBAddr SeConfig::m_kLogDBAddr
Referenced by GetLogDBAddr.
SeDBTime SeConfig::m_kDBTime
Referenced by GetDBTime.
std::string SeConfig::m_kFileName
Referenced by GetValue, Load, SetValue.
SeConfig::SeConfig(void)
References m_acString.
SeConfig::~SeConfig(void)
bool SeConfig::Load(const char *pcFile)
References m_kFileName.
Referenced by WatchServer::CWatchServer::InitializeNet, RaceServer::InitializeNetEx, SeDBMemMgr::LoadConfig, TcpServer::LoadConfig, LoginServer::LoadConfig, GlobalServer::LoadConfig, BackendServer::LoadConfig, HttpServer::LoadConfig, TownServer::LoadConfig, WatchServer::CWatchServer::LoadConfig, MatchServer::LoadConfig, NexusServer::LoadConfig, WorldServer::LoadConfig, DBServer::LoadConfig, TcpServer::LoadDynamicConfig, LoginServer::LoadDynamicConfig, GlobalServer::LoadDynamicConfig, HttpServer::LoadDynamicConfig, MatchServer::LoadDynamicConfig, WorldServer::LoadDynamicConfig, DBServer::LoadDynamicConfig, TownServer::LoadGameSetup, RaceServer::LoadRSTempConfig, TownServer::LoadServerAddr, RaceServer::ReLoadServerAddr, WorldServer::SaveUpdateWorldSetup.
const char * SeConfig::GetValue(const char *pcKey, const char *pcName=NULL)
References m_acString, m_kFileName.
Referenced by GetDBAddr, GetDBTime, GetLogDBAddr, GetNetAddr, SeDBMemMgr::LoadConfig, TcpServer::LoadConfig, LoginServer::LoadConfig, GlobalServer::LoadConfig, BackendServer::LoadConfig, HttpServer::LoadConfig, TownServer::LoadConfig, WatchServer::CWatchServer::LoadConfig, MatchServer::LoadConfig, NexusServer::LoadConfig, WorldServer::LoadConfig, DBServer::LoadConfig, TcpServer::LoadDynamicConfig, LoginServer::LoadDynamicConfig, GlobalServer::LoadDynamicConfig, HttpServer::LoadDynamicConfig, MatchServer::LoadDynamicConfig, WorldServer::LoadDynamicConfig, DBServer::LoadDynamicConfig, TownServer::LoadGameSetup, RaceServer::LoadRSTempConfig.
bool SeConfig::SetValue(const char *pcKey, const char *pcValue, const char *pcName=NULL)
References m_kFileName.
SeNetAddr * SeConfig::GetNetAddr(const char *pcKey)
References SeNetAddr::acIP, GetAString, GetValue, SeNetAddr::iPort, m_kNetAddr.
Referenced by WatchServer::CWatchServer::InitializeNet, RaceServer::InitializeNetEx, TcpServer::LoadConfig, LoginServer::LoadConfig, GlobalServer::LoadConfig, BackendServer::LoadConfig, HttpServer::LoadConfig, TownServer::LoadConfig, WatchServer::CWatchServer::LoadConfig, MatchServer::LoadConfig, NexusServer::LoadConfig, WorldServer::LoadConfig, DBServer::LoadConfig, RaceServer::LoadRSTempConfig, TownServer::LoadServerAddr, RaceServer::ReLoadServerAddr.
SeLogDBAddr * SeConfig::GetLogDBAddr(const char *pcKey)
References SeLogDBAddr::acDBName, SeLogDBAddr::acDBPassword, SeLogDBAddr::acDBUser, SeDBAddr::acIP, SeLogDBAddr::acIP, SeLogDBAddr::acTable, SeLogDBAddr::bSaveLog2File, GetAString, GetValue, SeLogDBAddr::iEveryMonths, SeLogDBAddr::iPort, m_kDBAddr, m_kLogDBAddr.
SeDBAddr * SeConfig::GetDBAddr(const char *pcKey, const char *pcName=NULL)
References SeDBAddr::acDBName, SeDBAddr::acDBPassword, SeDBAddr::acDBUser, SeDBAddr::acIP, GetAString, GetValue, SeDBAddr::iPort, m_kDBAddr.
Referenced by GlobalServer::LoadConfig, BackendServer::LoadConfig.
SeDBTableAddr * SeConfig::GetDBTableAddrFromStr(const char *pcStr)
References SeDBTableAddr::acDBName, SeDBTableAddr::acDBPassword, SeDBTableAddr::acDBUser, SeDBAddr::acIP, SeDBTableAddr::acIP, GetAString, SeDBTableAddr::iPort, SeDBTableAddr::iThreadNums, m_kDBAddr, m_kDBTableAddr.
Referenced by DBServer::LoadConfig.
SeRedisAddr * SeConfig::GetRedisAddrFromStr(const char *pcStr)
References SeRedisAddr::acCacheTypeName, SeRedisAddr::acIP, SeRedisAddr::acPassword, GetAString, SeRedisAddr::iCacheType, SeRedisAddr::iPort, SeRedisAddr::iThreadNums, m_kRedisAddr.
SeDBTime * SeConfig::GetDBTime(const char *pcKey)
References GetValue, m_kDBTime.
Referenced by WorldServer::LoadConfig.
bool SeConfig::IsValidIpV4(const char *pcIp)