BufferTableMgr
std::map<unsigned int,BufferTable*> BufferTableMgr::m_kBufferTableMap
Referenced by FillData, GetBufferTable, GetBufferTableMap, GetBufferTableVec, ~BufferTableMgr.
BufferTableMgr * BufferTableMgr::m_pkBufferTableMgr
Referenced by Get, ReLoad.
BufferTableMgr * BufferTableMgr::Get()
References BufferTableMgr, m_pkBufferTableMgr.
Referenced by GlobalTableMgr::GetBufferTable, TableMgr::LoadTable, ReLoad.
BufferTableMgr * BufferTableMgr::ReLoad()
References Get, m_pkBufferTableMgr.
Referenced by TableMgr::ReloadTable.
BufferTableMgr::BufferTableMgr()
References Load.
Referenced by Get.
BufferTableMgr::~BufferTableMgr()
References m_kBufferTableMap.
const BufferTable * BufferTableMgr::GetBufferTable(unsigned int iTypeID)
References m_kBufferTableMap.
Referenced by GlobalTableMgr::GetBufferTable.
const std::map< unsigned int, BufferTable * > & BufferTableMgr::GetBufferTableMap()
References m_kBufferTableMap.
TableResArray BufferTableMgr::GetBufferTableVec()
References m_kBufferTableMap, TableResArray::pushBack.
bool BufferTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by BufferTableMgr.
void BufferTableMgr::FillData(BufferTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, BufferTable::ibuffcolour, BufferTable::iEffectID, BufferTable::iMultiSpliceNum, BufferTable::iSingleSpliceNum, BufferTable::kbufficon, BufferTable::kDesc, BufferTable::kIcon, BufferTable::kName, BufferTable::kVoice, BufferTable::kVoiceCycle, m_kBufferTableMap, BufferTable::uiBufferTypeID, BufferTable::uiProperty.
Referenced by Load.