SeThreadRaceMgr
MSvrRace SeThreadRaceMgr::m_kMapRace
Referenced by AddRace, AddRacePlayer, DelRace, PlayerLeave, PlayerRelink, PrintCmdData, PushGetHeroInfo, PushRaceData, UpdateRace, ~SeThreadRaceMgr.
int SeThreadRaceMgr::m_iThreadIndex
Referenced by AddRace, DelRace, SeThreadRaceMgr, SetThreadIndex.
int SeThreadRaceMgr::m_iPrintDataSize
Referenced by PrintCmdData, SeThreadRaceMgr.
SeThreadRaceMgr::SeThreadRaceMgr(void)
References m_iPrintDataSize, m_iThreadIndex.
SeThreadRaceMgr::~SeThreadRaceMgr(void)
References m_kMapRace.
void SeThreadRaceMgr::SetThreadIndex(int iThreadIndex)
References m_iThreadIndex.
Referenced by RaceService::SetThreadIndex.
void SeThreadRaceMgr::AddRace(const TeMD5 &rkRaceID)
References g_kRaceServer, SeRCR_RaceOpr::iOprType, SeRCR_RaceOpr::iThreadIndex, m_iThreadIndex, m_kMapRace, RaceServer::PushRSMsg.
Referenced by RaceService::ProcessRRC_RaceInit.
void SeThreadRaceMgr::AddRacePlayer(const TeMD5 &rkRaceID, int iNum, SeRaceStartInfo *pkInfo)
References SeRaceStartInfo::bLeave, SeRaceStartInfo::iSeatIndex, SeSvrRace::kRacePlayer, SeRaceStartInfo::kSock, m_kMapRace, SeLogInfo.
Referenced by RaceService::ProcessRRC_RaceInit, RaceService::ProcessRRC_RaceStart.
void SeThreadRaceMgr::DelRace(const TeMD5 &rkRaceID)
References g_kRaceServer, RaceServer::GetServerTime, SeRCR_RaceOpr::iOprType, SeRCR_RaceOpr::iThreadIndex, SeSvrRace::kRaceDataMgr, SeSvrRace::kRacePlayer, m_iThreadIndex, m_kMapRace, RaceServer::PushRSMsg, SeLogInfo, SeRaceDataMgr::UpdateRaceData.
Referenced by RaceService::OnRaceErrorRet, RaceService::OnRaceEvent, RaceService::ProcessRRC_RaceOver.
void SeThreadRaceMgr::PushGetHeroInfo(const TeMD5 &rkRaceID, int iSeat, void *pkData, int iSize)
References SeSvrRace::kRaceDataMgr, m_kMapRace, SeRaceDataMgr::PushHeroInfo.
Referenced by RaceService::OnRaceHeroInfo.
void SeThreadRaceMgr::PushRaceData(const TeMD5 &rkRaceID, int iSeat, DWord dwFrame, char *pkData, int iSize, bool bMustSend)
References SeSvrRace::bNeedSendData, SeRaceCmd::dwCmd, SeSvrRace::dwLastSendCmdDataTime, eCounterFlags_ResetEachFrame, StatisticSendCommandPacket::iCount, StatisticSendCommandPacket::iSize, SeSvrRace::kRaceDataMgr, SeSvrRace::kSendCmdDataSize, M_addCounterF_FN, m_kMapRace, SeRaceDataMgr::PushRaceData.
Referenced by RaceService::OnRaceStream.
void SeThreadRaceMgr::PlayerLeave(const TeMD5 &rkRaceID, int iSeatIndex)
References SeSvrRace::kRacePlayer, m_kMapRace.
Referenced by RaceService::ProcessRRC_PlayerLeave.
void SeThreadRaceMgr::PlayerRelink(const TeMD5 &rkRaceID, int iSeatIndex, HSock kPlayerSock)
References SeRaceDataMgr::Clear, SeSvrRace::kRaceDataMgr, SeSvrRace::kRacePlayer, m_kMapRace.
Referenced by RaceService::ProcessRRC_PlayerRelink.
void SeThreadRaceMgr::UpdateRace()
References SeSvrRace::bNeedSendData, SeSvrRace::dwLastSendCmdDataTime, SeSvrRace::dwLastSendTime, g_kRaceServer, RaceServer::GetServerModePackTime, RaceServer::GetServerTime, SeSvrRace::kRaceDataMgr, SeSvrRace::kRacePlayer, M_BeforeStartInverval, m_kMapRace, M_QDoMutiInterval_FN, PrintCmdData, SeLogError, SeLogInfo, SeRaceDataMgr::UpdateRaceData.
Referenced by RaceService::Update.
void SeThreadRaceMgr::PushGetKDA(const TeMD5 &rkRaceID, void *pkData)
SeThreadRaceMgr::SeThreadRaceMgr(void)
SeThreadRaceMgr::~SeThreadRaceMgr(void)
void SeThreadRaceMgr::SetThreadIndex(int iThreadIndex)
void SeThreadRaceMgr::AddRace(const TeMD5 &rkRaceID)
void SeThreadRaceMgr::AddRacePlayer(const TeMD5 &rkRaceID, int iNum, SeRaceStartInfo *pkInfo)
void SeThreadRaceMgr::DelRace(const TeMD5 &rkRaceID)
void SeThreadRaceMgr::PushGetHeroInfo(const TeMD5 &rkRaceID, int iSeat, void *pkData, int iSize)
void SeThreadRaceMgr::PushRaceData(const TeMD5 &rkRaceID, int iSeat, DWord dwFrame, char *pkData, int iSize, bool bMustSend)
void SeThreadRaceMgr::PlayerLeave(const TeMD5 &rkRaceID, int iSeatIndex)
void SeThreadRaceMgr::PlayerRelink(const TeMD5 &rkRaceID, int iSeatIndex, HSock kPlayerSock)
void SeThreadRaceMgr::UpdateRace()
void SeThreadRaceMgr::PushGetKDA(const TeMD5 &rkRaceID, void *pkData)
void SeThreadRaceMgr::PrintCmdData()
References ConvCmdName, SeSvrRace::dwLastSendCmdDataTime, g_kRaceServer, GetMD52Str, RaceServer::GetRaceConfig, SeRaceConfig::iStatisticPacketSizeTime, SeSvrRace::kSendCmdDataSize, m_iPrintDataSize, m_kMapRace.
Referenced by UpdateRace.
char * SeThreadRaceMgr::ConvCmdName(char *ch, DWord cmd)
References SPRCT_ATTACHDATA, SPRCT_BEGIN, SPRCT_BUFFERDATA, SPRCT_CHAINEFFECTDATA, SPRCT_DAMAGEDATA, SPRCT_EFFECTDATA, SPRCT_EFFECTDEL, SPRCT_GLOBALDATA, SPRCT_HERODATA, SPRCT_KILLHERODATA, SPRCT_MAPITEMDATA, SPRCT_MAPPOINTDATA, SPRCT_PING, SPRCT_UIWINDOWDATA, SPRCT_UNITDISAPPEAR, SPRCT_UNITSHOWDATA, SPRCT_USERDATA, SRC_ADJUSTFRAME, SRC_END, SRC_FRAME, SRC_HERO_ATTACK_CANCEL, SRC_HERO_ATTACK_POS, SRC_HERO_ATTACK_UNIT, SRC_HERO_DIRECT_MOVE, SRC_HERO_HOLD, SRC_HERO_MOVE, SRC_HERO_SELECT, SRC_HERO_STOP, SRC_LOAD, SRC_LOCKUNIT, SRC_PAUSE_BEGIN, SRC_PAUSE_CANCEL, SRC_PAUSE_END, SRC_PING, SRC_PLAYER_GUANQIA_CMD, SRC_PLAYER_INFO, SRC_PLAYER_LEAVE, SRC_PLAYER_RECON_END, SRC_PLAYER_RELIVEHERO, SRC_PLAYER_TOWNITEM, SRC_RACE_PAUSE, SRC_RELINKBEGIN, SRC_RELINKEND, SRC_REPLAYVERSION, SRC_SAVE_RECONDATA_BEGIN, SRC_SAVE_RECONDATA_END, SRC_SHOP_LIST, SRC_START, SRC_SWITCH_HEROFOCUS, SRC_SWITCH_MODE, SRC_SYSTEM_CHEAT, SRC_SYSTEM_SURRENDER, SRC_SYSTEM_SUSPEND, SRC_TRAN_LOADEND, SRC_UNIT_ACTIVE_SKILL, SRC_UNIT_ATTACK, SRC_UNIT_ATTACK_POS, SRC_UNIT_ATTACK_UNIT, SRC_UNIT_BUY_ITEM, SRC_UNIT_DIRECTBUY_ITEM, SRC_UNIT_DIRECTSELL_ITEM, SRC_UNIT_DISPLACE_ITEM, SRC_UNIT_DROP_ITEM, SRC_UNIT_FOLLOW, SRC_UNIT_GIVEUP_DISPLACE_ITEM, SRC_UNIT_HOLD, SRC_UNIT_LEARN_SKILL, SRC_UNIT_MOVE, SRC_UNIT_PATROL, SRC_UNIT_PICK_ITEM, SRC_UNIT_PICK_ITEM_AUTO, SRC_UNIT_SPELL, SRC_UNIT_SPELLXULI, SRC_UNIT_STOP, SRC_UNIT_SWAP_ITEM, SRC_UNIT_USE_ITEM, SRC_VIEW_SELHERO, SRC_WATCH_POINT.
Referenced by PrintCmdData.
void SeThreadRaceMgr::PrintCmdData()
char* SeThreadRaceMgr::ConvCmdName(char *ch, DWord cmd)