ItemSaveThread
SHOPITEMMAP ItemSaveThread::m_ThreadItemMap
Referenced by SaveGmItem, SetMap.
ItemSaveThread::ItemSaveThread()
ItemSaveThread::~ItemSaveThread()
void ItemSaveThread::DoWork()
void ItemSaveThread::SaveGmItem()
References g_kWorldServer, WorldServer::GetConfig, SeWorldConfig::ItemSaveName, m_ThreadItemMap, SeLogError.
Referenced by CShop::Update, CShop::~CShop.
void ItemSaveThread::SetMap(SHOPITEMMAP &tmpMap)
References m_ThreadItemMap.
Referenced by CShop::Update.
ItemSaveThread::ItemSaveThread()
ItemSaveThread::~ItemSaveThread()
void ItemSaveThread::DoWork()
void ItemSaveThread::SaveGmItem()
void ItemSaveThread::SetMap(SHOPITEMMAP &tmpMap)
References m_ThreadItemMap.