moba::Clock
moba::timeval moba::Clock::m_current
当前时间
Referenced by getTime, getTimeVal, setTime.
unsigned int moba::Clock::m_second
逝去的秒数
Referenced by getSeconds, setTime.
TimeType moba::Clock::m_millisecond
逝去的毫秒数
Referenced by Clock, getMilliSeconds, setTime.
TimeType moba::Clock::m_currentMS
以毫秒计数的当前时间
Referenced by getTimeMS, setTime.
Es::NormalLock moba::Clock::m_mutex
锁.
Referenced by getMilliSeconds, getSeconds, getTime, getTimeMS, getTimeVal, setTime.
unsigned int moba::Clock::m_tailMillisecond
Referenced by Clock, setTime.
time_t moba::Clock::getTime()
获取时间
UNIX时间戳
References m_current, m_mutex, moba::timeval::tv_sec.
const TimeType moba::Clock::getTimeMS()
获取时间
以毫秒为精度的UNIX时间戳
References m_currentMS, m_mutex.
const moba::timeval moba::Clock::getTimeVal()
获取时间
timeval结构
References m_current, m_mutex.
unsigned int moba::Clock::getSeconds()
取得逝去的秒数
References m_mutex, m_second.
const TimeType moba::Clock::getMilliSeconds()
取得逝去的毫秒数
References m_millisecond, m_mutex.
Referenced by SeMatchMgr::addWaitRoom, SeMatchMgr::OnMatchReq, NexusServer::OnNetAccept, WorldServer::OnNetAccept, NexusServer::OnNetRecv, WorldServer::OnNetRecv, WorldServer::ProcessHS_Register, WorldServer::ProcessLW_Register, SeMatchMgr::rejoinMatch, MatchBanMgr::update, MatchPrepareMgr::update, moba::ServerSessionMgr::update, SeMatchMgr::Update, NexusServer::UpdateConnect, WorldServer::UpdateHSToWSTime, WorldServer::UpdateLSToWSTime, SeMatchMgr::UpdateRoom, WorldServer::UpdateUnknownState.
void moba::Clock::setTime()
设置时间,更新时钟状态
References gettimeofday, m_current, m_currentMS, m_millisecond, m_mutex, m_second, m_tailMillisecond, moba::timeval::tv_sec, moba::timeval::tv_usec.
Referenced by Clock, NexusServer::Initialize, WorldServer::Initialize, NexusServer::Update, WorldServer::Update, MatchServer::Update.
Clock & moba::Clock::getInstance()
Referenced by SeMatchMgr::addWaitRoom, MatchPrepareMgr::collectData, NexusServer::Initialize, WorldServer::Initialize, SeMatchMgr::OnMatchReq, NexusServer::OnNetAccept, WorldServer::OnNetAccept, NexusServer::OnNetRecv, WorldServer::OnNetRecv, WorldServer::ProcessHS_Register, WorldServer::ProcessLW_Register, SeMatchMgr::rejoinMatch, NexusServer::Update, MatchBanMgr::update, MatchPrepareMgr::update, WorldServer::Update, MatchServer::Update, moba::ServerSessionMgr::update, SeMatchMgr::Update, NexusServer::UpdateConnect, WorldServer::UpdateHSToWSTime, WorldServer::UpdateLSToWSTime, SeMatchMgr::UpdateRoom, WorldServer::UpdateUnknownState.
int moba::Clock::gettimeofday(struct moba::timeval *tp, struct timezone *tzp)
References moba::systime, moba::timeval::tv_sec, moba::timeval::tv_usec.
Referenced by setTime.
moba::Clock::Clock()
References m_millisecond, m_tailMillisecond, setTime.