BackendServer
TeNetMgr BackendServer::m_kNetMgr
Referenced by Finialize, InitializeNet, OnNetRecv, SendBKSNData, Update.
SeBackendConfig BackendServer::m_kConfig
Referenced by GetAreaID, GetServerID, InitializeDB, InitializeNet, LoadConfig.
MapAllConnect BackendServer::m_kAllConnect
Referenced by OnNetAccept, OnNetDisconnect, OnNetRecv.
TeDataBaseMgr BackendServer::m_kDBMgr
Referenced by Finialize, InitializeDB, SendDB_ExecuteSQL, Update.
int BackendServer::m_iUnitStatisticDB
Referenced by BackendServer, InitializeDB, SendDB_Online_Num, SendDB_Race_Num, SendDB_User_Create, SendDB_User_Race, SendDB_User_Town, SendDB_User_Watch, SendDB_Watch_Num.
MapDBQuery BackendServer::m_kAllDBQuery
Referenced by ProcessDB, SendDB_ExecuteSQL.
DWord BackendServer::m_dwTickCount
Referenced by BackendServer, Update.
DWord BackendServer::m_dwCurTime
Referenced by BackendServer, GetServerTime, SendDB_ExecuteSQL, Update.
BackendServer::BackendServer(void)
References m_dwCurTime, m_dwTickCount, m_iUnitStatisticDB.
BackendServer::~BackendServer(void)
bool BackendServer::Initialize(void)
References InitializeDB, InitializeNet, InitializeNetEx, LoadConfig.
void BackendServer::Update(void)
References g_kVirtConnMgr, m_dwCurTime, m_dwTickCount, m_kDBMgr, m_kNetMgr, SeVirtConnMgr::Update, UpdateConnect, UpdateStatistic.
void BackendServer::Finialize(void)
References m_kDBMgr, m_kNetMgr.
void BackendServer::ShowConsoleTitle(int iDTime)
References SPrintf.
SeServerActionResult BackendServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, SeLogHideTime.
void BackendServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
void BackendServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeConnect::eState, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllConnect, SCS_UNKOWN, SSD_IP_LEN, StrCpy.
void BackendServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References CMD_NBKS_REGISTER, SeConnect::dwRecvTime, SeConnect::eState, GetServerTime, m_kAllConnect, m_kNetMgr, ProcessNBKSData, SCS_NEXUS_OK, SCS_UNKOWN, SeCMD::wCmd.
void BackendServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, SeNexusMgr::DeleteNexus, SeConnect::dwServerID, SeConnect::eState, g_kNexusMgr, GetID2Str, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllConnect, SCS_NEXUS_OK, SeLogError.
void BackendServer::OnDBResponse(int iDB, TeDBResSet &rkResSet)
References ProcessDB.
bool BackendServer::SendBKSN_RegisterRet(const SeRegisterRet &eRet, void *pkReceiver=NULL)
Referenced by ProcessNBKS_Register.
bool BackendServer::SendBKSN_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessNBKS_HeartPackage.
bool BackendServer::SendBKSNData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr, SeLogError, SeCMD::wCmd.
bool BackendServer::ProcessNBKSData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool BackendServer::PreProcessNBKS(void *pkData, int iSize, void *pkSender)
void BackendServer::ProcessNBKS_Register(SeNBKS_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeNexusMgr::CheckNexus, SeNexusMgr::CreateNexus, SeNBKS_Register::dwServerID, SeConnect::dwServerID, SeConnect::dwStateTime, SeConnect::eState, g_kNexusMgr, GetID2Str, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, SCS_NEXUS_OK, SCS_UNKOWN, SeLogInfo, SendBKSN_RegisterRet, SRR_SUCCESS.
void BackendServer::ProcessNBKS_HeartPackage(SeNBKS_HeartPackage *pkData, int iSize, void *pkSender)
References SeConnect::kSock, SendBKSN_HeartPackageRet.
void BackendServer::ProcessNBKS_UserStateSync(SeNBKS_UserStateSync *pkData, int iSize, void *pkSender)
References SeNBKS_UserStateSync::dwLoginTime, SeNBKS_UserStateSync::dwPlayerID, SeNBKS_UserStateSync::dwStateID, g_kLinkUserMgr, LinkUserSync, LinkUserMgr::make.
void BackendServer::ProcessNBKS_CreatUserSync(SeNBKS_CreatUserSync *pkData, int iSize, void *pkSender)
References SeNBKS_CreatUserSync::acRemoteIp, CreatUserSync, SeNBKS_CreatUserSync::dwLoginTime, SeNBKS_CreatUserSync::dwPlayerID.
bool BackendServer::SendDB_ExecuteSQL(int db_type, int query_type, const char *pcSql)
References SeDBQuery::dwTime, m_dwCurTime, m_kAllDBQuery, m_kDBMgr.
Referenced by SendDB_Online_Num, SendDB_Race_Num, SendDB_User_Create, SendDB_User_Race, SendDB_User_Town, SendDB_User_Watch, SendDB_Watch_Num.
bool BackendServer::SendDB_User_Create(DWord dw_player_id, const char *pIp)
References m_iUnitStatisticDB, SendDB_ExecuteSQL, SPrintf, SQT_USER_CREATE_ID.
Referenced by CreatUserSync.
bool BackendServer::SendDB_User_Town(DWord dw_player_id)
References m_iUnitStatisticDB, SendDB_ExecuteSQL, SPrintf, SQT_USER_TOWN_ID.
Referenced by LinkUserTownSync.
bool BackendServer::SendDB_User_Race(DWord dw_player_id)
References m_iUnitStatisticDB, SendDB_ExecuteSQL, SPrintf, SQT_USER_RACE_ID.
Referenced by LinkUserRaceSync.
bool BackendServer::SendDB_User_Watch(DWord dw_player_id)
References m_iUnitStatisticDB, SendDB_ExecuteSQL, SPrintf, SQT_USER_WATCH_ID.
Referenced by LinkUserWatchSync.
bool BackendServer::SendDB_Online_Num(DWord dw_online_users)
References m_iUnitStatisticDB, SendDB_ExecuteSQL, SPrintf, SQT_ONLINE_NUM_ID.
Referenced by UpdateStatistic_OnlineNum.
bool BackendServer::SendDB_Race_Num(DWord dw_race_users)
References m_iUnitStatisticDB, SendDB_ExecuteSQL, SPrintf, SQT_RACE_NUM_ID.
Referenced by UpdateStatistic_RaceNum.
bool BackendServer::SendDB_Watch_Num(DWord dw_watch_users)
References m_iUnitStatisticDB, SendDB_ExecuteSQL, SPrintf, SQT_WATCH_NUM_ID.
Referenced by UpdateStatistic_WatchNum.
void BackendServer::ProcessDB(int iDB, TeDBResSet &rkResSet)
References SeDBQuery::eType, m_kAllDBQuery, ProcessDB_Online_Num, ProcessDB_Race_Num, ProcessDB_User_Create, ProcessDB_User_Race, ProcessDB_User_Town, ProcessDB_User_Watch, ProcessDB_Watch_Num, SQT_ONLINE_NUM_ID, SQT_RACE_NUM_ID, SQT_USER_CREATE_ID, SQT_USER_RACE_ID, SQT_USER_TOWN_ID, SQT_USER_WATCH_ID, SQT_WATCH_NUM_ID.
Referenced by OnDBResponse.
void BackendServer::ProcessDB_User_Create(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError, SeLogInfo.
Referenced by ProcessDB.
void BackendServer::ProcessDB_User_Town(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError, SeLogInfo.
Referenced by ProcessDB.
void BackendServer::ProcessDB_User_Race(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError, SeLogInfo.
Referenced by ProcessDB.
void BackendServer::ProcessDB_User_Watch(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError, SeLogInfo.
Referenced by ProcessDB.
void BackendServer::ProcessDB_Online_Num(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError, SeLogInfo.
Referenced by ProcessDB.
void BackendServer::ProcessDB_Race_Num(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError, SeLogInfo.
Referenced by ProcessDB.
void BackendServer::ProcessDB_Watch_Num(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError, SeLogInfo.
Referenced by ProcessDB.
DWord BackendServer::GetServerID()
References SeBackendConfig::dwServerID, m_kConfig.
DWord BackendServer::GetAreaID()
References SeBackendConfig::dwAreaID, m_kConfig.
DWord BackendServer::GetServerTime(void)
References m_dwCurTime.
Referenced by OnNetRecv, ProcessNBKS_Register, UpdateConnect, UpdateStatistic.
bool BackendServer::LoadConfig(const char *pcFile)
References SeBackendConfig::dwAreaID, SeBackendConfig::dwServerID, SeConfig::GetDBAddr, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeBackendConfig::kLocalServer, SeBackendConfig::kUnitStatisticsDB, SeConfig::Load, m_kConfig, SeLogError, SeLogInfo.
bool BackendServer::LoadConfig(void)
Referenced by Initialize.
bool BackendServer::InitializeNet(void)
References SeNetAddr::acIP, SeNetAddr::iPort, SeBackendConfig::kLocalServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo, SERVER_BUFFER_SIZE.
Referenced by Initialize.
bool BackendServer::InitializeNetEx(void)
Referenced by Initialize.
bool BackendServer::InitializeDB(void)
References SeDBAddr::acDBName, SeDBAddr::acDBPassword, SeDBAddr::acDBUser, SeDBAddr::acIP, SeDBAddr::iPort, SeBackendConfig::kUnitStatisticsDB, m_iUnitStatisticDB, m_kConfig, m_kDBMgr, SAD_DB_LOGIC, SeLogError, SeLogInfo.
Referenced by Initialize.
void BackendServer::UpdateConnect()
References GetServerTime.
Referenced by Update.
void BackendServer::UpdateStatistic()
References BKS_ONLINE_STATIC_TIME, GetServerTime, UpdateStatistic_OnlineNum.
Referenced by Update.
void BackendServer::UpdateStatistic_OnlineNum()
References g_kBackendStatisticsMgr, BackendStatisticsMgr::get_online_users, SeLogInfo, SendDB_Online_Num.
Referenced by UpdateStatistic.
void BackendServer::UpdateStatistic_RaceNum()
References g_kBackendStatisticsMgr, BackendStatisticsMgr::get_race_users, SeLogInfo, SendDB_Race_Num.
void BackendServer::UpdateStatistic_WatchNum()
References g_kBackendStatisticsMgr, BackendStatisticsMgr::get_watch_users, SeLogInfo, SendDB_Watch_Num.
void BackendServer::LinkUserSync(DWord dwPlayerID, DWord dwStateID, DWord dwLoginTime)
References ENState_Online, ENState_Racing, ENState_Watching, LinkUserRaceSync, LinkUserTownSync, LinkUserWatchSync.
Referenced by ProcessNBKS_UserStateSync.
void BackendServer::LinkUserTownSync(DWord dwPlayerID)
References SeLogInfo, SendDB_User_Town.
Referenced by LinkUserSync.
void BackendServer::LinkUserRaceSync(DWord dwPlayerID)
References SeLogInfo, SendDB_User_Race.
Referenced by LinkUserSync.
void BackendServer::LinkUserWatchSync(DWord dwPlayerID)
References SeLogInfo, SendDB_User_Watch.
Referenced by LinkUserSync.
void BackendServer::CreatUserSync(DWord dwPlayerID, DWord dwLoginTime, const char *pIp)
References SeLogInfo, SendDB_User_Create.
Referenced by ProcessNBKS_CreatUserSync.