SeXmlUnknown
SeXmlUnknown::SeXmlUnknown()
Referenced by Clone.
virtual SeXmlUnknown::~SeXmlUnknown()
SeXmlUnknown::SeXmlUnknown(const SeXmlUnknown &copy)
References CopyTo.
SeXmlUnknown& SeXmlUnknown::operator=(const SeXmlUnknown &copy)
References CopyTo.
SeXmlNode * SeXmlUnknown::Clone() const
Creates a copy of this Unknown and returns it.
References CopyTo, SeXmlUnknown.
void SeXmlUnknown::Print(FILE *cfile, int depth) const
All SeXml classes can print themselves to a filestream or the string class (SeXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.This is a formatted print, and will insert tabs and newlines.(For an unformatted stream, use the << operator.)
References SeXmlNode::value.
const char * SeXmlUnknown::Parse(const char *p, SeXmlParsingData *data, SeXmlEncoding encoding)
References SeXmlParsingData::Cursor, SeXmlNode::GetDocument, SeXmlBase::location, SeXmlDocument::SetError, SeXmlBase::SeXml_ERROR_PARSING_UNKNOWN, SeXmlBase::SkipWhiteSpace, SeXmlParsingData::Stamp, SeXmlNode::value.
virtual const SeXmlUnknown* SeXmlUnknown::ToUnknown() const
Cast to a more defined type. Will return null not of the requested type.
virtual SeXmlUnknown* SeXmlUnknown::ToUnknown()
Cast to a more defined type. Will return null not of the requested type.
bool SeXmlUnknown::Accept(SeXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
References SeXmlVisitor::Visit.
void SeXmlUnknown::CopyTo(SeXmlUnknown *target) const
References SeXmlNode::CopyTo.
Referenced by Clone, operator=, SeXmlUnknown.
void SeXmlUnknown::StreamIn(std::istream *in, SeXml_STRING *tag)
References SeXmlNode::GetDocument, SeXmlDocument::SetError, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_EMBEDDED_NULL.