GlobalServer
char GlobalServer::m_acSend[SSD_SEND_SIZE]
Referenced by GlobalServer.
DWord GlobalServer::m_dwCurTime
Referenced by GetServerTime, GlobalServer, Initialize, ProcessLG_Register, ProcessWG_Register, SendDB_AccountInitGenID, SendDB_AccountInsertData, SendDB_AccountQuery, SendDB_AccountUpdateData, Update.
SeGlobalConfig GlobalServer::m_kConfig
Referenced by GetMaxCacheNum, InitializeDB, InitializeNet, LoadConfig, LoadDynamicConfig, OnLoginQueryRet, UpdateLogShow.
std::string GlobalServer::m_kAreaInfo
MAPID2AreaName GlobalServer::m_kID2AreaName
Referenced by GetAreaName, LoadDynamicConfig.
TeNetMgr GlobalServer::m_kNetMgr
Referenced by Finialize, Initialize, InitializeNet, OnNetRecv, PreProcessLG, PreProcessWG, ProcessLG_Register, ProcessWG_Register, SendGLData, SendGWData, SendHSData, Update, UpdateGS2WSTime.
MapAllWS GlobalServer::m_kAllWS
Referenced by Finialize, GetWSByAreaID, GetWSByID, UpdateGS2WSTime.
DWord GlobalServer::m_dwHeartPackageTime
Referenced by GlobalServer.
TeDataBaseMgr GlobalServer::m_kDBMgr
Referenced by Finialize, InitializeDB, SendDB_AccountInitGenID, SendDB_AccountInsertData, SendDB_AccountQuery, SendDB_AccountUpdateData, Update.
int GlobalServer::m_iUnitAccountDB
Referenced by GlobalServer, InitializeDB, SendDB_AccountInitGenID, SendDB_AccountInsertData, SendDB_AccountQuery, SendDB_AccountUpdateData.
MapDBQuery GlobalServer::m_kAllDBQuery
Referenced by GetDBQueryNums, ProcessDB, SendDB_AccountInitGenID, SendDB_AccountInsertData, SendDB_AccountQuery, SendDB_AccountUpdateData.
DWord GlobalServer::m_dwGenPlayerID
Referenced by GenPlayerID, GlobalServer, ProcessDB_AccountGenID.
MapOnlinePlayerNum GlobalServer::m_kOlinePlayerNum
DWord GlobalServer::m_dwLoadCount
Referenced by GlobalServer, SetLoginLogInfo, UpdateLogShow.
DWord GlobalServer::m_dwLoadSumTime
Referenced by GlobalServer, SetLoginLogInfo, UpdateLogShow.
GlobalServer::GlobalServer(void)
References m_acSend, m_dwCurTime, m_dwGenPlayerID, m_dwHeartPackageTime, m_dwLoadCount, m_dwLoadSumTime, m_iUnitAccountDB.
GlobalServer::~GlobalServer(void)
bool GlobalServer::Initialize(void)
References g_kVirtConnMgr, SeVirtConnMgr::Initialize, InitializeDB, InitializeNet, LoadConfig, m_dwCurTime, m_kNetMgr, SeLogError, SendDB_AccountInitGenID, sendHeartPack, sendRegPack.
void GlobalServer::Update(void)
References g_kCacheMgr, g_kVirtConnMgr, m_dwCurTime, m_kDBMgr, m_kNetMgr, SeCacheMgr::Update, SeVirtConnMgr::Update, UpdateLogShow, UpdateState.
void GlobalServer::Finialize(void)
References m_kAllWS, m_kDBMgr, m_kNetMgr.
void GlobalServer::ShowConsoleTitle(int iDTime)
References g_kCacheMgr, SeCacheMgr::GetCacheState, SPrintf.
SeServerActionResult GlobalServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F5, g_kGlobalServer, LoadDynamicConfig, SeLogHideTime, SeLogInfo.
void GlobalServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
void GlobalServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeVirtConnMgr::AddClientConn, g_kVirtConnMgr.
void GlobalServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References CMD_HS_REGISTER, CMD_LG_REGISTER, CMD_WG_REGISTER, SeVirtConn::dwLastRecvTime, SeVirtConn::eIndex, SeVirtConn::eState, g_kVirtConnMgr, SeVirtConnMgr::GetClientConnBySock, GetServerTime, m_kNetMgr, ProcessHSData, ProcessLGData, ProcessWGData, SSI_HS, SSI_LS, SSI_WS, SVCS_NULL, SVCS_REGISTERED, SeCMD::wCmd.
void GlobalServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References g_kVirtConnMgr, SeVirtConnMgr::OnClientDisconnect.
void GlobalServer::OnDBResponse(int iDB, TeDBResSet &rkResSet)
References ProcessDB.
int GlobalServer::GetMaxCacheNum(void)
References SeGlobalConfig::iMaxCacheNum, m_kConfig.
Referenced by SeCacheMgr::AddAccount.
int GlobalServer::GetDBQueryNums(void)
References m_kAllDBQuery.
Referenced by SeCacheMgr::Update.
DWord GlobalServer::GetServerTime(void)
References m_dwCurTime.
Referenced by OnLoginQueryRet, OnNetRecv, ProcessDB_AccountQuery, ProcessLG_AccountLogin, ProcessLG_PlayerLogin, SeCacheMgr::Update, UpdateGS2WSTime, UpdateLogShow.
bool GlobalServer::SendGW_RegisterRet(const SeRegisterRet &eRegisterRet, void *pkReceiver=NULL)
bool GlobalServer::SendGW_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessWG_HeartPackage.
bool GlobalServer::SendGWData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool GlobalServer::SendGL_RegisterRet(const SeRegisterRet &eRegisterRet, void *pkReceiver=NULL)
Referenced by ProcessLG_Register.
bool GlobalServer::SendGL_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessLG_HeartPackage.
bool GlobalServer::SendGL_KickAccount(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by OnLoginQueryRet.
bool GlobalServer::SendGL_AccountLoginSuccess(DWord dwPackKey, DWord dwPlayerID, const SePtlAccountInfo &kAccountInfo, void *pkReceiver=NULL)
Referenced by OnLoginQueryRet.
bool GlobalServer::SendGL_AccountLoginFailed(DWord dwPackKey, const SeLoginReason &eReason, int iParam1, int iParam2, void *pkReceiver=NULL)
Referenced by OnLoginQueryRet, ProcessDB_AccountQuery, ProcessHS_DHAccountLoginRet, ProcessLG_PlayerLogin.
bool GlobalServer::SendGL_AccountWillLogin(DWord dwPlayerID, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by OnLoginQueryRet.
bool GlobalServer::SendGLData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool GlobalServer::SendHSData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
Referenced by SendHS_DHAccountLogin, SendHS_HeartPackageRet, SendHS_RegisterRet.
bool GlobalServer::SendHS_RegisterRet(const HSock &rkSock, int iRet)
References SeHS_RegisterRet::iRet, SendHSData.
Referenced by ProcessHS_Register.
bool GlobalServer::SendHS_HeartPackageRet(const HSock &rkSock)
References SendHSData.
Referenced by ProcessHS_HeartPackage.
bool GlobalServer::SendHS_DHAccountLogin(const HSock &rkSock, int iPackKey, const SeLG_PlayerLogin *pkInfo, const char *pcGuestID, const char *pcSign)
References SeLG_PlayerLogin::acAccount, SeHS_DHAccountLogin::acAccount, SeHS_DHAccountLogin::acAppID, SeHS_DHAccountLogin::acGuestID, SeLG_PlayerLogin::acLoginType, SeHS_DHAccountLogin::acLoginType, SeLG_PlayerLogin::acMobileInfo, SeHS_DHAccountLogin::acMobileInfo, SeHS_DHAccountLogin::acSign, SeLG_PlayerLogin::acToken, SeHS_DHAccountLogin::acToken, APPID_DIANHUN, SeLG_PlayerLogin::dwAccountID, SeHS_DHAccountLogin::dwAccountID, SeHS_DHAccountLogin::iPackKey, SendHSData, StrCpy.
Referenced by ProcessLG_PlayerLogin.
bool GlobalServer::SendDB_AccountInitGenID(void)
References SeDBQuery::dwTime, m_dwCurTime, m_iUnitAccountDB, m_kAllDBQuery, m_kDBMgr, SPrintf, SQT_ACCOUNT_INIT_GEN_ID.
Referenced by Initialize.
bool GlobalServer::SendDB_AccountQuery(SeWaitLoginAccount *pkWaitLoginAccount)
References SeWaitLoginAccount::acGameAccount, SeDBQuery::dwTime, GetAccountHash, m_dwCurTime, m_iUnitAccountDB, m_kAllDBQuery, m_kDBMgr, SeDBQuery::pkVoid, SAD_DB_LOGIC, SPrintf, SQT_ACCOUNT_QUERY.
Referenced by ProcessHS_DHAccountLoginRet, ProcessLG_AccountLogin.
bool GlobalServer::SendDB_AccountInsertData(const SeAccount *pkAccount)
References SeAccount::acAccount, SeAccount::acMobileInfo, SeAccount::acRegIP, SeAccount::chName, SeDBQuery::dwParam1, SeAccount::dwPlayerID, SeAccount::dwRegVersion, SeDBQuery::dwTime, SeAccount::ePlatFlag, GetDBTime2Str, SeAccount::kCreateTime, m_dwCurTime, m_iUnitAccountDB, m_kAllDBQuery, m_kDBMgr, SAD_DB_LOGIC, SPrintf, SQT_ACCOUNT_INSERT_DATA.
Referenced by ProcessDB_AccountQuery.
bool GlobalServer::SendDB_AccountUpdateData(const SeAccount *pkAccount)
References SeAccount::acLastLoginIP, SeAccount::dwLastLoginAreaID, SeAccount::dwOfflineTime, SeAccount::dwOnlineTime, SeAccount::dwPlayerID, SeDBQuery::dwTime, SeAccount::dwTotalGameTime, SeAccount::dwTotalLoginCount, GetDBTime2Str, SeAccount::kLastLoginTime, SeAccount::kLastLogoutTime, m_dwCurTime, m_iUnitAccountDB, m_kAllDBQuery, m_kDBMgr, SAD_DB_LOGIC, SPrintf, SQT_ACCOUNT_UPDATE_DATA.
Referenced by SeCacheMgr::Update.
bool GlobalServer::ProcessWGData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool GlobalServer::PreProcessWG(void *pkData, int iSize, void *pkSender)
References CMD_WG_REGISTER, SeWSData::eState, SeWSData::kSock, m_kNetMgr, SeCMD::wCmd, WSS_UNKOWN.
void GlobalServer::ProcessWG_Register(SeWG_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeWG_Register::dwAreaID, SeWSData::dwAreaID, SeWG_Register::dwLoginMagic, SeWSData::dwRecvTime, SeWG_Register::dwServerID, SeWSData::dwServerID, SeWSData::eState, GetID2Str, GetWSByAreaID, GetWSByID, SeNetAddr::iPort, SeWSData::kNetAddr, SeWSData::kSock, m_dwCurTime, m_kNetMgr, SeLogError, SeLogInfo, SSD_MSANGO_MAGIC, WSS_LOGIN_OK, WSS_UNKOWN.
void GlobalServer::ProcessWG_HeartPackage(SeWG_HeartPackage *pkData, int iSize, void *pkSender)
References SeWSData::kSock, SendGW_HeartPackageRet.
bool GlobalServer::ProcessLGData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool GlobalServer::PreProcessLG(void *pkData, int iSize, void *pkSender)
References CMD_LG_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, SVCS_NULL, SeCMD::wCmd.
void GlobalServer::ProcessLG_Register(SeLG_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeLG_Register::dwAreaID, SeVirtConn::dwLastRecvTime, SeLG_Register::dwLoginMagic, SeLG_Register::dwServerID, SeVirtConn::eState, g_kVirtConnMgr, GetAreaName, SeVirtConnMgr::GetClientConnByID, GetID2Str, SeNetAddr::iPort, SeVirtConn::kNetAddr, SeVirtConn::kSock, m_dwCurTime, m_kNetMgr, SeVirtConnMgr::OnClientRegister, SeLogError, SeLogInfo, SendGL_RegisterRet, SRR_FAILED, SRR_REPEAT, SRR_SUCCESS, SSD_MSANGO_MAGIC, SSI_LS, SVCS_NULL.
void GlobalServer::ProcessLG_HeartPackage(SeLG_HeartPackage *pkData, int iSize, void *pkSender)
References SeVirtConn::kSock, SendGL_HeartPackageRet.
void GlobalServer::ProcessLG_AccountLogin(SeLG_AccountLogin *pkData, int iSize, void *pkSender)
References SeLG_AccountLogin::acAccount, SeWaitLoginAccount::acGameAccount, SeWaitLoginAccount::acGamePassword, SeLG_AccountLogin::acPassword, SeSynMgr::AddSynOpr, SeLG_AccountLogin::bForceKick, SeWaitLoginAccount::bForceKick, SeWaitLoginAccount::dwBeginTime, SeLG_AccountLogin::dwIP, SeWaitLoginAccount::dwIP, SeLG_AccountLogin::dwPackKey, SeWaitLoginAccount::dwPackKey, SeLG_AccountLogin::dwVersion, SeWaitLoginAccount::dwVersion, g_kCacheMgr, g_kSynMgr, SeCacheMgr::GetAccountByAccount, GetServerTime, SeWaitLoginAccount::kLSSock, SeVirtConn::kSock, OnLoginQueryRet, SeSynOpr::pkVoid, SeLogDebug, SendDB_AccountQuery, StrCpy.
void GlobalServer::ProcessLG_PlayerLogin(SeLG_PlayerLogin *pkData, int iSize, void *pkSender)
References TeMD5::abyMD5, SeLG_PlayerLogin::acAccount, SeWaitLoginAccount::acGameAccount, SeLG_PlayerLogin::acLoginType, SeLG_PlayerLogin::acMobileInfo, SeWaitLoginAccount::acMobileInfo, SeLG_PlayerLogin::acToken, SeSynMgr::AddSynOpr, APPID_DIANHUN, SeLG_PlayerLogin::bForceKick, SeWaitLoginAccount::bForceKick, SeLG_PlayerLogin::dwAccountID, SeWaitLoginAccount::dwBeginTime, SeLG_PlayerLogin::dwIP, SeWaitLoginAccount::dwIP, SeLG_PlayerLogin::dwPackKey, SeWaitLoginAccount::dwPackKey, SeLG_PlayerLogin::dwVersion, SeWaitLoginAccount::dwVersion, SeWaitLoginAccount::ePlatFlag, g_kSynMgr, g_kVirtConnMgr, GenGameAccount, SeVirtConnMgr::GetClientConnByIndex, GetMD5, GetMD52Str, SeSynMgr::GetOutSynOpr, GetServerTime, SeLG_PlayerLogin::iPlatFlag, SeWaitLoginAccount::kLSSock, SeVirtConn::kSock, LFR_ACCOUNT_VERITYFY, LFR_INVALID_PLAT, LFR_SERVER_DISCONNECT, PFG_DIANHUN, PFG_GUEST, SeSynOpr::pkVoid, SAFE_DELETE, SeLogError, SendGL_AccountLoginFailed, SendHS_DHAccountLogin, SPrintf, SSD_MAX_ACCOUNT, SSI_HS, StrCpy.
void GlobalServer::ProcessLG_PlayerTownIndex(SeLG_PlayerTownIndex *pkData, int iSize, void *pkSender)
References SeLG_PlayerTownIndex::dwPlayerID, g_kCacheMgr, SeCacheMgr::GetAccountByID, SeAccount::iTownIndex, SeLG_PlayerTownIndex::iTownIndex, NowTime.
void GlobalServer::ProcessLG_PlayerLogout(SeLG_PlayerLogout *pkData, int iSize, void *pkSender)
References SeLG_PlayerLogout::dwPlayerID, g_kCacheMgr, SeCacheMgr::OnAccountLogout.
void GlobalServer::ProcessHSData(void *pkData, int iSize, void *pkSender=NULL)
References CMD_HS_DIANHUN_ACCOUNT_LOGIN_RET, CMD_HS_HEARTPACKAGE, CMD_HS_REGISTER, ProcessHS_DHAccountLoginRet, ProcessHS_HeartPackage, ProcessHS_Register, SeCMD::wCmd.
Referenced by OnNetRecv.
void GlobalServer::ProcessHS_Register(void *pkData, int iSize, void *pkSender=NULL)
References SeNetAddr::acIP, SeVirtConn::eIndex, SeVirtConn::eState, g_kVirtConnMgr, SeNetAddr::iPort, SeVirtConn::kNetAddr, SeVirtConn::kSock, SeVirtConnMgr::OnClientRegister, SeLogError, SeLogInfo, SendHS_RegisterRet, SSI_HS, SVCS_REGISTERED.
Referenced by ProcessHSData.
void GlobalServer::ProcessHS_HeartPackage(void *pkData, int iSize, void *pkSender=NULL)
References SeVirtConn::kSock, SendHS_HeartPackageRet.
Referenced by ProcessHSData.
void GlobalServer::ProcessHS_DHAccountLoginRet(void *pkData, int iSize, void *pkSender=NULL)
References SeWaitLoginAccount::acGameAccount, SeWaitLoginAccount::dwPackKey, g_kSynMgr, g_kVirtConnMgr, SeVirtConnMgr::GetClientConnBySock, SeSynMgr::GetOutSynOpr, SeHS_DHAccountLoginRet::iPackKey, SeHS_DHAccountLoginRet::iResult, SeWaitLoginAccount::kLSSock, LFR_ACCOUNT_ERROR, SeSynOpr::pkVoid, SAFE_DELETE, SeLogError, SendDB_AccountQuery, SendGL_AccountLoginFailed.
Referenced by ProcessHSData.
void GlobalServer::ProcessDB(int iDB, TeDBResSet &rkResSet)
References SeDBQuery::eType, m_kAllDBQuery, ProcessDB_AccountGenID, ProcessDB_AccountInsertData, ProcessDB_AccountQuery, ProcessDB_AccountUpdateData, SQT_ACCOUNT_INIT_GEN_ID, SQT_ACCOUNT_INSERT_DATA, SQT_ACCOUNT_QUERY, SQT_ACCOUNT_UPDATE_DATA.
Referenced by OnDBResponse.
void GlobalServer::ProcessDB_AccountGenID(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References m_dwGenPlayerID, SeLogError, SeLogInfo.
Referenced by ProcessDB.
void GlobalServer::ProcessDB_AccountQuery(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeAccount::acAccount, SeAccount::acLastLoginIP, SeAccount::acMobileInfo, SeAccount::acRegIP, SeCacheMgr::AddAccount, SeAccount::chName, SeAccount::dwLastLoginAreaID, SeAccount::dwLastSaveTime, SeAccount::dwOfflineTime, SeAccount::dwOnlineTime, SeAccount::dwPlayerID, SeAccount::dwRegVersion, SeAccount::dwTotalGameTime, SeAccount::dwTotalLoginCount, SeAccount::eLockReason, SeAccount::ePlatFlag, g_kCacheMgr, g_kGlobalServer, g_kVirtConnMgr, GenPlayerID, SeVirtConnMgr::GetClientConnBySock, GetDBTime, GetServerTime, SeAccount::iLockNum, SeAccount::iPriorityLevel, SeAccount::kCreateTime, SeAccount::kLastLoginTime, SeAccount::kLastLogoutTime, SeAccount::kLockFinishTime, SeVirtConn::kSock, LFR_DB_ERROR, NowTime, OnLoginQueryRet, SeDBQuery::pkVoid, SeLogError, SendDB_AccountInsertData, SendGL_AccountLoginFailed, StrCpy.
Referenced by ProcessDB.
void GlobalServer::ProcessDB_AccountInsertData(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeLogError.
Referenced by ProcessDB.
void GlobalServer::ProcessDB_AccountUpdateData(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
References SeDBQuery::pkVoid.
Referenced by ProcessDB.
GlobalServer::GlobalServer(void)
GlobalServer::~GlobalServer(void)
bool GlobalServer::Initialize(void)
void GlobalServer::Update(void)
void GlobalServer::Finialize(void)
void GlobalServer::ShowConsoleTitle(int iDTime)
SeServerActionResult GlobalServer::ExecuteAction(SeServerActionIndex eActionIndex)
virtual void GlobalServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
virtual void GlobalServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
virtual void GlobalServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
virtual void GlobalServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
virtual void GlobalServer::OnDBResponse(int iDB, TeDBResSet &rkResSet)
int GlobalServer::GetMaxCacheNum(void)
int GlobalServer::GetDBQueryNums(void)
DWord GlobalServer::GetServerTime(void)
bool GlobalServer::SendGW_RegisterRet(const SeRegisterRet &eRegisterRet, void *pkReceiver=NULL)
bool GlobalServer::SendGW_HeartPackageRet(void *pkReceiver=NULL)
bool GlobalServer::SendGWData(void *pkData, int iSize, void *pkReceiver)
bool GlobalServer::SendGL_RegisterRet(const SeRegisterRet &eRegisterRet, void *pkReceiver=NULL)
bool GlobalServer::SendGL_HeartPackageRet(void *pkReceiver=NULL)
bool GlobalServer::SendGL_KickAccount(DWord dwPlayerID, void *pkReceiver=NULL)
bool GlobalServer::SendGL_AccountLoginSuccess(DWord dwPackKey, DWord dwPlayerID, const SePtlAccountInfo &kAccountInfo, void *pkReceiver=NULL)
bool GlobalServer::SendGL_AccountLoginFailed(DWord dwPackKey, const SeLoginReason &eReason, int iParam1, int iParam2, void *pkReceiver=NULL)
bool GlobalServer::SendGL_AccountWillLogin(DWord dwPlayerID, DWord dwAreaID, void *pkReceiver=NULL)
bool GlobalServer::SendGLData(void *pkData, int iSize, void *pkReceiver)
bool GlobalServer::SendHSData(void *pkData, int iSize, void *pkReceiver)
bool GlobalServer::SendHS_RegisterRet(const HSock &rkSock, int iRet)
bool GlobalServer::SendHS_HeartPackageRet(const HSock &rkSock)
bool GlobalServer::SendHS_DHAccountLogin(const HSock &rkSock, int iPackKey, const SeLG_PlayerLogin *pkInfo, const char *pcGuestID, const char *pcSign)
bool GlobalServer::SendDB_AccountInitGenID(void)
bool GlobalServer::SendDB_AccountQuery(SeWaitLoginAccount *pkWaitLoginAccount)
bool GlobalServer::SendDB_AccountInsertData(const SeAccount *pkAccount)
bool GlobalServer::SendDB_AccountUpdateData(const SeAccount *pkAccount)
bool GlobalServer::ProcessWGData(void *pkData, int iSize, void *pkSender=NULL)
bool GlobalServer::PreProcessWG(void *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessWG_Register(SeWG_Register *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessWG_HeartPackage(SeWG_HeartPackage *pkData, int iSize, void *pkSender)
bool GlobalServer::ProcessLGData(void *pkData, int iSize, void *pkSender=NULL)
bool GlobalServer::PreProcessLG(void *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessLG_Register(SeLG_Register *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessLG_HeartPackage(SeLG_HeartPackage *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessLG_AccountLogin(SeLG_AccountLogin *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessLG_PlayerLogin(SeLG_PlayerLogin *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessLG_PlayerTownIndex(SeLG_PlayerTownIndex *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessLG_PlayerLogout(SeLG_PlayerLogout *pkData, int iSize, void *pkSender)
void GlobalServer::ProcessHSData(void *pkData, int iSize, void *pkSender=NULL)
void GlobalServer::ProcessHS_Register(void *pkData, int iSize, void *pkSender=NULL)
void GlobalServer::ProcessHS_HeartPackage(void *pkData, int iSize, void *pkSender=NULL)
void GlobalServer::ProcessHS_DHAccountLoginRet(void *pkData, int iSize, void *pkSender=NULL)
void GlobalServer::ProcessDB(int iDB, TeDBResSet &rkResSet)
void GlobalServer::ProcessDB_AccountGenID(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void GlobalServer::ProcessDB_AccountQuery(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void GlobalServer::ProcessDB_AccountInsertData(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
void GlobalServer::ProcessDB_AccountUpdateData(SeDBQuery *pkDBQuery, TeDBResSet &rkResSet)
bool GlobalServer::LoadConfig(const char *pcFile)
References SeGlobalConfig::dwServerID, SeConfig::GetDBAddr, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeGlobalConfig::kAddrToServer, SeGlobalConfig::kUnitAccountDB, SeConfig::Load, LoadDynamicConfig, m_kConfig, SeLogError, SeLogInfo.
Referenced by Initialize.
void GlobalServer::LoadDynamicConfig(void)
References SeGlobalConfig::dwHeartPackageTime, SeConfig::GetValue, SeGlobalConfig::iLogShowType, SeGlobalConfig::iMaxCacheNum, SeConfig::Load, m_kConfig, m_kID2AreaName, SPrintf.
Referenced by ExecuteAction, LoadConfig.
bool GlobalServer::InitializeDB(void)
References SeDBAddr::acDBName, SeDBAddr::acDBPassword, SeDBAddr::acDBUser, SeDBAddr::acIP, SeDBAddr::iPort, SeGlobalConfig::kUnitAccountDB, m_iUnitAccountDB, m_kConfig, m_kDBMgr, SAD_DB_LOGIC, SeLogError, SeLogInfo.
Referenced by Initialize.
bool GlobalServer::InitializeNet(void)
References SeNetAddr::acIP, SeNetAddr::iPort, SeGlobalConfig::kAddrToServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo, SERVER_BUFFER_SIZE.
Referenced by Initialize.
void GlobalServer::ConnectToDS(void)
void GlobalServer::RegisterToDS(void)
void GlobalServer::UpdateState(void)
Referenced by Update.
void GlobalServer::UpdateLogShow(void)
References GetServerTime, SeGlobalConfig::iLogShowType, m_dwLoadCount, m_dwLoadSumTime, m_kConfig, SeLogInfo.
Referenced by Update.
void GlobalServer::UpdateGS2WSTime(void)
References SeNetAddr::acIP, SeWSData::dwRecvTime, SeWSData::dwServerID, SeWSData::eState, GetID2Str, GetServerTime, SeNetAddr::iPort, SeWSData::kNetAddr, SeWSData::kSock, m_kAllWS, m_kNetMgr, SeLogInfo, WSS_LOGIN_OK.
SeWSData * GlobalServer::GetWSByID(DWord dwServerID)
References SeWSData::dwServerID, SeWSData::eState, m_kAllWS, WSS_LOGIN_OK.
Referenced by ProcessWG_Register.
SeWSData * GlobalServer::GetWSByAreaID(DWord dwAreaID)
References SeWSData::dwAreaID, SeWSData::eState, m_kAllWS, WSS_LOGIN_OK.
Referenced by ProcessWG_Register.
std::string GlobalServer::GetAreaName(DWord dwID)
References m_kID2AreaName.
Referenced by ProcessLG_Register.
void GlobalServer::SetLoginLogInfo(DWord dwCount, DWord dwCousumeTime)
References m_dwLoadCount, m_dwLoadSumTime.
Referenced by OnLoginQueryRet.
void GlobalServer::OnLoginQueryRet(SeWaitLoginAccount *pkWaitAccount, SeAccount *pkAccount)
References SeAccount::acAccount, SePtlAccountInfo::acAccount, SeWaitLoginAccount::acGameAccount, SePtlAccountInfo::acNickName, SeAccount::acRegIP, SePtlAccountInfo::acRegIP, SeWaitLoginAccount::bForceKick, SeAccount::chName, SeVirtConn::dwAreaID, SeWaitLoginAccount::dwBeginTime, SeWaitLoginAccount::dwIP, SeAccount::dwLastLoginAreaID, SeWaitLoginAccount::dwPackKey, SeAccount::dwPlayerID, SeAccount::dwRegVersion, SePtlAccountInfo::dwRegVersion, SeAccount::ePlatFlag, g_kCacheMgr, g_kVirtConnMgr, SeVirtConnMgr::GetClientConnByAreaID, SeVirtConnMgr::GetClientConnBySock, GetDWord2IPString, GetServerTime, SeFlagBase::HasFlag, SeGlobalConfig::iLogShowType, SePtlAccountInfo::iPlatFlag, SeAccount::iTownIndex, SeWaitLoginAccount::kLSSock, SeVirtConn::kSock, LFR_OTHER_LOGGED, m_kConfig, SeCacheMgr::OnAccountLogin, SeCacheMgr::OnUpdateAccountDynamic, SAF_LOGINED, SeLogInfo, SendGL_AccountLoginFailed, SendGL_AccountLoginSuccess, SendGL_AccountWillLogin, SendGL_KickAccount, SetLoginLogInfo, SPrintf, SSI_LS, StrCpy.
Referenced by ProcessDB_AccountQuery, ProcessLG_AccountLogin.
DWord GlobalServer::GenPlayerID(void)
References m_dwGenPlayerID, SeLogError.
Referenced by ProcessDB_AccountQuery.
bool GlobalServer::GenGameAccount(SePlatFlag ePlatFlag, DWord dwPlatAccountID, const char *pcPlatAccount, char *pcGameAccount)
References PFG_DIANHUN, PFG_GUEST, SPrintf, SSD_MAX_ACCOUNT.
Referenced by ProcessLG_PlayerLogin.
int GlobalServer::GetAccountHash(const char *pcAccount, int iMaxDB)
References uiCount.
Referenced by SendDB_AccountQuery.
bool GlobalServer::LoadConfig(const char *pcFile)
void GlobalServer::LoadDynamicConfig(void)
bool GlobalServer::InitializeDB(void)
bool GlobalServer::InitializeNet(void)
void GlobalServer::ConnectToDS(void)
void GlobalServer::RegisterToDS(void)
void GlobalServer::UpdateState(void)
void GlobalServer::UpdateLogShow(void)
void GlobalServer::UpdateGS2WSTime(void)
SeWSData* GlobalServer::GetWSByID(DWord dwServerID)
SeWSData* GlobalServer::GetWSByAreaID(DWord dwAreaID)
std::string GlobalServer::GetAreaName(DWord dwID)
void GlobalServer::SetLoginLogInfo(DWord dwCount, DWord dwCousumeTime)
void GlobalServer::OnLoginQueryRet(SeWaitLoginAccount *pkWaitAccount, SeAccount *pkAccount)
DWord GlobalServer::GenPlayerID(void)
bool GlobalServer::GenGameAccount(SePlatFlag ePlatFlag, DWord dwPlatAccountID, const char *pcPlatAccount, char *pcGameAccount)
int GlobalServer::GetAccountHash(const char *pcAccount, int iMaxDB)