PerformanceTiming::CCounterClone
const char * PerformanceTiming::CCounterClone::m_strName
Referenced by CPerformanceTiming::EnumerateAllCounters, Name.
const char * PerformanceTiming::CCounterClone::m_strFolderName
Referenced by CPerformanceTiming::EnumerateAllCounters, GetFolderName.
Int32 PerformanceTiming::CCounterClone::m_uValue
Referenced by CPerformanceTiming::EnumerateAllCounters, GetValue.
Int32 PerformanceTiming::CCounterClone::m_LastValueAdded
Referenced by CPerformanceTiming::EnumerateAllCounters, GetLastValue.
UInt64 PerformanceTiming::CCounterClone::m_RunningTotal
Referenced by CPerformanceTiming::EnumerateAllCounters, GetRunningTotal.
bool PerformanceTiming::CCounterClone::m_bHistory
Referenced by CPerformanceTiming::EnumerateAllCounters, IsHistoryCounter.
CRC_ID PerformanceTiming::CCounterClone::m_crcID
Referenced by CPerformanceTiming::EnumerateAllCounters, GetFolderNameCRC.
PerformanceTiming::CCounterClone::DECLARE_POOL(CCounterClone)
PerformanceTiming::CCounterClone::CCounterClone()
PerformanceTiming::CCounterClone::CCounterClone(const char *strName, const char *pFolderName, Int32 iVal, UInt64 iTotalVal, bool bHistory, CRC_ID crc)
Int32 PerformanceTiming::CCounterClone::GetValue() const
References m_uValue.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
Int32 PerformanceTiming::CCounterClone::GetLastValue() const
References m_LastValueAdded.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
UInt64 PerformanceTiming::CCounterClone::GetRunningTotal() const
References m_RunningTotal.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
bool PerformanceTiming::CCounterClone::IsHistoryCounter() const
References m_bHistory.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
CRC_ID PerformanceTiming::CCounterClone::GetFolderNameCRC() const
References m_crcID.
Referenced by CCounterCloneFolderSet::BuildFolderSets.
const char* PerformanceTiming::CCounterClone::GetFolderName() const
References m_strFolderName.
Referenced by CCounterCloneFolderSet::BuildFolderSets.
const char* PerformanceTiming::CCounterClone::Name() const
References m_strName.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
PerformanceTiming::CCounterClone::DECLARE_POOL(CCounterClone)
PerformanceTiming::CCounterClone::CCounterClone()
PerformanceTiming::CCounterClone::CCounterClone(const char *strName, const char *pFolderName, Int32 iVal, UInt64 iTotalVal, bool bHistory, CRC_ID crc)
Int32 PerformanceTiming::CCounterClone::GetValue() const
References m_uValue.
Int32 PerformanceTiming::CCounterClone::GetLastValue() const
References m_LastValueAdded.
UInt64 PerformanceTiming::CCounterClone::GetRunningTotal() const
References m_RunningTotal.
bool PerformanceTiming::CCounterClone::IsHistoryCounter() const
References m_bHistory.
CRC_ID PerformanceTiming::CCounterClone::GetFolderNameCRC() const
References m_crcID.
const char* PerformanceTiming::CCounterClone::GetFolderName() const
References m_strFolderName.
const char* PerformanceTiming::CCounterClone::Name() const
References m_strName.