RaceServer
char RaceServer::m_acSend[RACE_SEND_SIZE]
Referenced by RaceServer.
char RaceServer::m_acPraseBuf[SSD_PRASER_SIZE]
Referenced by RaceServer.
DWord RaceServer::m_dwTickCount
Referenced by RaceServer, Update.
DWord RaceServer::m_dwCurTime
Referenced by CheckConnect, CheckFreq, GetServerTime, OnNetAccept, OnPlayerConnected, PreProcessNR, PreProcessWR, ProcessCR_RaceRobotLogin, ProcessCR_RaceValidate, RaceServer, RegisterToMS, Update.
bool RaceServer::m_bMSReady
Referenced by IsMSReady, RaceServer, SetMSReady.
SeRaceConfig RaceServer::m_kConfig
Referenced by CheckConnect, ConnectToMS, DelConnectByID, DisconnectPlayer, GetAreaID, GetDebugLevel, GetGameLogFilePath, GetMaxPacketSize, GetMaxReconTime, GetRaceConfig, GetRacePackTime, GetRacePrintTime, GetServerID, GetServerModePackTime, InitializeNet, IsTestRobotMode, LoadConfig, OnNetAccept, OnNetConnected, OnNetUdpAccept, OnPlayerConnected, ProcessMR_RegisterRet, RegisterToMS, ReLoadServerAddr, SendRCData, SetDebugLevel.
SeRandNum RaceServer::m_kRandNum
Referenced by RandInt, Update.
int RaceServer::m_iRegisterCount
Referenced by ProcessMR_RegisterRet, RaceServer, RegisterToMS.
TeNetMgr RaceServer::m_kNetMgr
Referenced by ConnectToMS, DelConnectByID, DisconnectPlayer, Finialize, InitializeNet, InitializeNetEx, OnNetAccept, OnNetRecv, ReLoadServerAddr, SendRCData, SendRMData, SendRNData, SendRWCSData, SendRWData, Update, UpdateMSHeartPackage.
TeUdpMgr RaceServer::m_kUdpMgr
Referenced by DelConnectByID, DisconnectPlayer, Finialize, InitializeNet, OnNetUdpAccept, SendRCData, Update.
SeServerData RaceServer::m_kMSData
Referenced by ConnectToMS, GetMSID, IsMSReady, OnNetConnected, OnNetRecv, ProcessMR_HeartPackageRet, ProcessMR_RegisterRet, RegisterToMS, ReLoadServerAddr, SendRMData, UpdateMSHeartPackage, UpdateMSState.
MapWCSConnect RaceServer::m_kWCSConnect
Referenced by GetWCSConnectMap, OnNetAccept, OnNetDisconnect, OnNetRecv.
SeVirtConn * RaceServer::m_pkWSConn
Referenced by InitializeNetEx, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessWR, ProcessWR_RegisterRet, RaceServer, SendRWData.
SeVirtConn * RaceServer::m_pkNSConn
Referenced by InitializeNetEx, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessNR, ProcessNR_RegisterRet, RaceServer, SendRNData.
MapAllConnect RaceServer::m_kAllConnect
Referenced by CheckConnect, CheckFreq, ClearAllPlayerConn, DelConnectByID, GetConnectByID, GetConnectBySock, GetConnectNum, OnNetAccept, OnNetDisconnect, OnNetRecv, OnNetUdpAccept, OnNetUdpDisconnect, OnNetUdpRecv, OnPlayerDisconnect.
DWord RaceServer::m_dwFreqTime
Referenced by CheckFreq, RaceServer.
Map2WaitRobot RaceServer::m_kWaitRobot
Referenced by DelWaitRobot, ProcessCR_RaceRobotLogin, UpdateWaitRobot.
QInt RaceServer::m_akThreadTime[Stat_TIME_THREAD_NUM]
Referenced by ProcessRC_ThreadOverTime, UpdateSaveThreadUpdateTime.
int RaceServer::m_iRaceServiceNum
Referenced by Finialize, GetRaceServiceNum, InitializeRaceService, LoadRSTempConfig, PushRaceServiceMsg, RaceServer.
RaceService * RaceServer::m_pakRaceService
Referenced by Finialize, InitializeRaceService, PushRaceServiceMsg, RaceServer.
SeThreadMsgMgr RaceServer::m_kThreadMsgMgr
Referenced by InitializeRaceService, PushRSMsg, UpdateRSMsg.
int RaceServer::m_iRobotRaceNum
Referenced by Initialize, LoadRSTempConfig.
SeRaceRecordSaveThread * RaceServer::m_pkSaveRecordThread
Referenced by RaceServer, RaceThreadFinialize, RaceThreadInitialize, RaceThreadUpdate, SaveRecord.
TWCSViewArray RaceServer::m_vWCSView
Referenced by GetWCSView, OnWCSDisconnect, ProcessWCSR_Register.
RaceServer::RaceServer(void)
References m_acPraseBuf, m_acSend, m_bMSReady, m_dwCurTime, m_dwFreqTime, m_dwTickCount, m_iRaceServiceNum, m_iRegisterCount, m_pakRaceService, m_pkNSConn, m_pkSaveRecordThread, m_pkWSConn.
RaceServer::~RaceServer(void)
bool RaceServer::Initialize(void)
References SeRaceMgr::CreateRobotRace, g_kFileLog, g_kRaceMgr, SeRaceMgr::Initialize, InitializeNet, InitializeNetEx, InitializeRaceService, LoadConfig, TableMgr::LoadTable, m_iRobotRaceNum, RaceThreadInitialize, SeLogHideTime, SeFileLog::SetLogConsole, SeRaceMgr::StartRobotRace.
void RaceServer::Update(void)
References CheckConnect, CheckFreq, g_kMatchReconMgr, g_kRaceMgr, g_kRaceRoomMgr, g_kVirtConnMgr, m_dwCurTime, m_dwTickCount, m_kNetMgr, m_kRandNum, m_kUdpMgr, RaceThreadUpdate, SeRandNum::RandInt, SeRaceRoomMgr::Update, SeMatchReconMgr::Update, SeRaceMgr::Update, SeVirtConnMgr::Update, UpdateHeartPackage, UpdateMSState, UpdateRSConfig, UpdateRSMsg, UpdateSaveThreadUpdateTime, UpdateWaitRobot.
void RaceServer::Finialize(void)
References RaceService::Finialize, m_iRaceServiceNum, m_kNetMgr, m_kUdpMgr, m_pakRaceService, RaceThreadFinialize.
void RaceServer::ShowConsoleTitle(int iDTime)
References GetConnectNum, GetID2Str, GetServerID, GetServerRunState, SPrintf.
SeServerActionResult RaceServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F3, AI_F5, AI_F6, SeRaceMgr::EnableCheating, g_kFileLog, g_kRaceMgr, SeFileLog::GetLogConsole, SeRaceMgr::IsCheating, ReLoadConfig, SeLogHideTime, SeLogInfo, SeFileLog::SetLogConsole.
void RaceServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeServerData::bConnecting, g_kVirtConnMgr, SeNetAddr::iPort, SeRaceConfig::kMSServer, SeVirtConn::kNetAddr, SeServerData::kSock, m_kConfig, m_kMSData, m_pkNSConn, m_pkWSConn, SeVirtConnMgr::OnServerConnected, SeLogError, SeLogInfo.
void RaceServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeWatchServerConnect::bRegister, SeWatchServerConnect::dwStateTime, SeNetAddr::iPort, IsMSReady, SeRaceConfig::kAddrToPlayer, SeRaceConfig::kAddrToWCS, SeWatchServerConnect::kNetAddr, SeConnect::kSock, SeWatchServerConnect::kSock, m_dwCurTime, m_kAllConnect, m_kConfig, m_kNetMgr, m_kWCSConnect, OnPlayerConnected, StrCpy.
void RaceServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References SeWatchServerConnect::bRegister, CMD_CR_RACEVALIDATE, CMD_WCSR_REGISTER, SeConnect::dwLastRecvTime, SeConnect::dwPackCount, GetServerTime, SeServerData::kSock, SeVirtConn::kSock, m_kAllConnect, m_kMSData, m_kNetMgr, m_kWCSConnect, m_pkNSConn, m_pkWSConn, ProcessBLRData, ProcessCRData, ProcessMRData, ProcessNRData, ProcessWCSRData, ProcessWRData, SeLogInfo, STCB_BLS_RS, STCB_INTERVAL, SeCMD::wCmd.
void RaceServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, SeRaceRoomMgr::DelPlayer, DelWaitRobot, SeConnect::dwPlayerID, SeWatchServerConnect::dwServerID, ENState_Online, SeConnect::eState, g_kRaceMgr, g_kRaceRoomMgr, g_kVirtConnMgr, SeMatchPlayer::GetAreaID, SeMatchPlayer::GetID, GetID2Str, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeMatchPlayer::GetRoomSessionID, SeMatchPlayer::GetServerID, SeNetAddr::iPort, SeWatchServerConnect::kNetAddr, SeVirtConn::kSock, SeConnect::kSock, SeRaceRoomMgr::LeaveRaceView, m_kAllConnect, m_kWCSConnect, m_pkNSConn, m_pkWSConn, MM_VIEW_STATE, SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnPlayerViewQuit, SeRaceRoomMgr::OnRaceLeave, SeVirtConnMgr::OnServerDisconnect, OnWCSDisconnect, RaceLinkUserSync, SeLogError, SeLogInfo, SendRM_UpdateMisc, SMPS_RACEVIEW.
void RaceServer::OnNetUdpAccept(int iID, int iListtenPort, const char *pcIP, int iPort)
References SeNetAddr::iPort, IsMSReady, IsTestRobotMode, SeRaceConfig::kAddrToPlayerUdp, SeConnect::kSock, m_kAllConnect, m_kConfig, m_kUdpMgr, OnPlayerConnected.
void RaceServer::OnNetUdpRecv(int iID, void *pkData, int iSize)
References CMD_CR_RACEVALIDATE, SeConnect::dwLastRecvTime, SeConnect::dwPackCount, GetServerTime, m_kAllConnect, ProcessCRData, SeLogInfo, SeCMD::wCmd.
void RaceServer::OnNetUdpDisconnect(int iID)
References SeRaceRoomMgr::DelPlayer, SeConnect::dwPlayerID, g_kRaceMgr, g_kRaceRoomMgr, SeMatchPlayer::GetAreaID, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeMatchPlayer::GetRoomSessionID, SeMatchPlayer::GetServerID, SeRaceRoomMgr::LeaveRaceView, m_kAllConnect, MM_VIEW_STATE, SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnPlayerViewQuit, SeRaceRoomMgr::OnRaceLeave, SeLogInfo, SendRM_UpdateMisc, SMPS_RACEVIEW.
bool RaceServer::SendRC_EncryptKey(const char *abyEncryptKey, DWord dwVersion, void *pkReceiver=NULL)
Referenced by OnPlayerConnected.
bool RaceServer::SendRC_HeartBeat(void *pkReceiver=NULL)
Referenced by ProcessCR_HeartPackage.
bool RaceServer::SendRC_ValidateRet(bool bReturn, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::OnReconValidOK, SeRaceRoomMgr::OnViewValidOKRet, ProcessCR_RaceValidate.
bool RaceServer::SendRC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, int iSize, const char *acMessage, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnRaceEndArenaDetail, ProcessBLR_SelectHeroAck, SeRaceRoomMgr::SelHero, SeRaceRoomMgr::SelHeroFight, SendPlayer_ReconNoticePlayerJoin.
bool RaceServer::SendRC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, int iSize, std::vector< char > &acMessage, void *pkReceiver=NULL)
bool RaceServer::SendRC_RoomPlayerBaseInfo(DWord dwMapID, SeRaceModel eRaceModel, int iNum, const SeMatchSelPlayerInfo *akPlayerInfo, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::SendRacePlayerBaseInfo.
bool RaceServer::SendRC_RoomPlayerBaseInfo(DWord dwMapID, SeRaceModel eRaceModel, int iNum, std::vector< SeMatchSelPlayerInfo > &akPlayerInfo, void *pkReceiver=NULL)
bool RaceServer::SendRC_RacePack(DWord dwPackIndex, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnPlayerReconBegin, SeRaceMgr::OnRaceModeEnd, SeRaceMgr::UpdateLoadEnd, SeRaceMgr::UpdateRace.
bool RaceServer::SendRC_RacePack(DWord dwPackIndex, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_RaceStream(int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by OnSendPlayerRaceStream.
bool RaceServer::SendRC_RaceStream(int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_RacePlayerLoadEnd(int iSeat, DWord dwRate, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnPlayerRaceLoadEnd.
bool RaceServer::SendRC_BeginSelectHero(DWord dwCamp, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::IntoSelHero.
bool RaceServer::SendRC_SelHeroMessage(SeSelHeroMsgType eMessageType, DWord dwHeroID, bool bDreamHero, int iDecMoney, DWord dwOrgPlayerID, DWord dwDstPlayerID, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::CancelHero, SeRaceRoomMgr::SelHeroFight, SeRaceRoomMgr::SelHeroReady.
bool RaceServer::SendRC_ReconResult(SeReconResultType eResult, int iData, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnPlayerReconBegin, SeRaceMgr::UpdateReconBegin, SeRaceMgr::UpdateReconEnd.
bool RaceServer::SendRC_ReconPack(int iOffset, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by SeRaceMgr::UpdateReconBegin.
bool RaceServer::SendRC_ReconPack(int iOffset, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_ViewPack(int iOffset, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by SeRaceMgr::UpdateView.
bool RaceServer::SendRC_ViewPack(int iOffset, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_ViewResult(SeViewResultType eResult, int iData, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnPlayerRaceViewBegin, SeRaceMgr::OnPlayerViewQuit, SeRaceMgr::UpdateView.
bool RaceServer::SendRC_ViewPlayerInfo(int iNum, const SePlayerInfoSeat *akSeat, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnPlayerRaceViewBegin.
bool RaceServer::SendRC_ViewPlayerInfo(int iNum, std::vector< SePlayerInfoSeat > &akSeat, void *pkReceiver=NULL)
bool RaceServer::SendRC_Talk(SeTalkType eType, DWord dwSrcID, int iSize, const char *acMsg, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::OnPlayerTalk.
bool RaceServer::SendRC_SelPetList(int iNum, const int *akPetID, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelPetList(int iNum, std::vector< int > &akPetID, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelHeroList(int iNum, const SeSelHeroInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::IntoSelHero.
bool RaceServer::SendRC_SelHeroList(int iNum, std::vector< SeSelHeroInfo > &akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelHorseList(int iNum, const int *akHorseID, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelHorseList(int iNum, std::vector< int > &akHorseID, void *pkReceiver=NULL)
bool RaceServer::SendRC_PingRet(DWord dwPackIndex, void *pkReceiver=NULL)
Referenced by ProcessCR_Ping.
bool RaceServer::SendRC_GetHeroInfoRet(int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by SeLogicRaceData::SendHeroInfo.
bool RaceServer::SendRC_GetHeroInfoRet(int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_RaceEndNotifyDown(const char *acURLBase, const char *acRaceID, void *pkReceiver=NULL)
Referenced by SeRaceMgr::UpdateView.
bool RaceServer::SendRC_RaceGoldExpPlus(int RaceGold, int RaceExp, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnRaceEndArenaDetail.
bool RaceServer::SendRC_SetEquipSetAck(int iResult, void *pkReceiver=NULL)
Referenced by ProcessCR_SetEquipSetReq.
bool RaceServer::SendRC_SetAvatarAck(int iResult, void *pkReceiver=NULL)
Referenced by ProcessCR_SetAvatarReq.
bool RaceServer::SendRC_SeatScoreNtf(const SeSeatScore *scores, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnRaceEndGradeDetail.
bool RaceServer::SendRC_SeatScoreNtf(std::vector< SeSeatScore > &scores, void *pkReceiver=NULL)
bool RaceServer::SendRCData(void *pkData, int iSize, void *pkReceiver)
References SeRaceConfig::bRCPacketToFile, SeRaceConfig::bTcpClient, SeUDPSender::iFlag, SeUDPSender::iProtocolFlag, SeUDPSender::kSock, m_kConfig, m_kNetMgr, m_kUdpMgr, SeLogError, SeCMD::wFlag, WriteToLogFile.
bool RaceServer::ProcessCRData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv, OnNetUdpRecv.
bool RaceServer::PreProcessCR(void *pkData, int iSize, void *pkSender)
References CMD_CR_HEARTPACKAGE, CMD_CR_PING, CMD_CR_RACECMD, getCRCmdNameMap, SeLogDebug, SeCMD::wCmd.
void RaceServer::ProcessCR_HeartPackage(SeCR_HeartPackage *pkData, int iSize, void *pkSender)
References SeConnect::kSock, SeUDPSender::kSock, SendRC_HeartBeat.
void RaceServer::ProcessCR_RaceValidate(SeCR_RaceValidate *pkData, int iSize, void *pkSender)
References SeReconPlayer::acName, SeReconPlayerName::acName, SeReconInitInfo::acName, SeMatchReconMgr::CheckCon2OldRace, SeMatchReconMgr::DelPlayer, SeReconPlayer::dwAreaID, SeReconInitInfo::dwAreaID, SeCR_RaceValidate::dwFrame, SeReconInitInfo::dwFrame, SeCR_RaceValidate::dwKey, SeRaceRoom::dwKey, SeCR_RaceValidate::dwPlayerID, SeConnect::dwPlayerID, SeReconInitInfo::dwPlayerID, SeReconPlayer::dwServerID, SeReconInitInfo::dwServerID, SeCR_RaceValidate::dwSessionId, SeConnect::dwStateTime, SeReconPlayer::eCamp, SeReconInitInfo::eCamp, ENState_Racing, SeConnect::eState, SeCR_RaceValidate::eValidType, g_kMatchReconMgr, g_kRaceRoomMgr, g_kRaceServer, SeMatchPlayer::GetAreaID, GetConnectByID, SeRaceRoom::GetDroppedPlayer, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchReconMgr::GetReconPlayer, SeMatchReconMgr::GetReconPlayerName, SeRaceRoomMgr::GetRoom, SeMatchPlayer::GetRoomPlayerCamp, SeMatchPlayer::GetServerID, SeCR_RaceValidate::iOffset, SeReconInitInfo::iOffset, SeCR_RaceValidate::iSeat, SeReconInitInfo::iSeat, SeConnect::kSock, SeUDPSender::kSock, m_dwCurTime, SeRaceRoomMgr::OnPlayerReconQuery, SeRaceRoomMgr::OnReconValidOK, RaceLinkUserSync, SCS_VALID_OK, SeLogDebug, SeLogError, SeLogInfo, SendRC_ValidateRet, SendRM_ReconViewValid, SeMatchPlayer::SetHSock, SeMatchPlayer::SetPlayerState, SeMatchPlayer::SetValidate, SMPS_CONNECT, SRQF_NULL, SRVT_RACE, SRVT_RECON, SRVT_VIEW, StrCpy.
Referenced by StartRobotGame.
void RaceServer::ProcessCR_RaceLoadEnd(SeCR_RaceLoadEnd *pkData, int iSize, void *pkSender)
References SeConnect::dwPlayerID, SeCR_RaceLoadEnd::dwRate, SeCR_RaceLoadEnd::eLoadType, g_kRaceMgr, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetRoomSessionID, SeRaceMgr::OnPlayerRaceLoadEnd, SeLogInfo.
void RaceServer::ProcessCR_RaceCmd(SeCR_RaceCmd *pkData, int iSize, void *pkSender)
References SeCR_RaceCmd::acData, SeRaceCmd::dwCmd, SeConnect::dwPlayerID, g_kRaceMgr, g_kRaceRoomMgr, SeRaceRoomMgr::GetPlayer, SeCR_RaceCmd::iSize, SeRaceMgr::OnPlayerRaceCmd, SRC_HERO_DIRECT_MOVE.
void RaceServer::ProcessCR_RaceLeave(SeCR_RaceLeave *pkData, int iSize, void *pkSender)
References SeConnect::dwPlayerID, g_kRaceMgr, g_kRaceRoomMgr, SeRaceRoomMgr::GetPlayer, SeRaceMgr::OnPlayerRaceLeave, SeRaceRoomMgr::OnRaceLeave.
void RaceServer::ProcessCR_RaceEndRace(SeCR_RaceEndRace *pkData, int iSize, void *pkSender)
References SeCR_RaceEndRace::akPlayerInfo, SeCR_RaceEndRace::bValid, DISCONNECR_PLAYER, SeConnect::dwPlayerID, SeCR_RaceEndRace::dwRaceTime, g_kRaceMgr, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeMatchPlayer::GetName, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeCR_RaceEndRace::iNums, SeRaceMgr::OnPlayerRaceEnd, SeLogDebug, SMPS_RACING, SSD_MAX_ROOM_PLAYER.
void RaceServer::ProcessCR_RaceEndGuanqia(SeCR_RaceEndGuanqia *pkData, int iSize, void *pkSender)
References SeCR_RaceEndGuanqia::akPlayerInfo, SeCR_RaceEndGuanqia::bValid, DISCONNECR_PLAYER, SeConnect::dwPlayerID, SeCR_RaceEndGuanqia::dwRaceTime, g_kRaceMgr, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeMatchPlayer::GetName, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeCR_RaceEndGuanqia::iNums, SeRaceMgr::OnPlayerGuanqiaEnd, SeLogDebug, SMPS_RACING, SSD_MAX_ROOM_PLAYER.
void RaceServer::ProcessCR_SelHeroChoiceHero(SeCR_SelHeroChoiceHero *pkData, int iSize, void *pkSender)
References SeCR_SelHeroChoiceHero::bDreamHero, SeCR_SelHeroChoiceHero::dwHeroCardID, SeConnect::dwPlayerID, SeRaceRoom::eRoomState, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeRaceRoomMgr::GetRoom, SeMatchPlayer::GetRoomSessionID, SeMatchPlayer::HasHero, SeRaceRoomMgr::OnPlayerChoiceHero, SeLogInfo, SendRBL_SelectHeroReq, SMPS_SELECT_HERO, SRRS_SELHERO.
void RaceServer::ProcessCR_SelHeroCancelHero(SeCR_SelHeroCancelHero *pkData, int iSize, void *pkSender)
References SeConnect::dwPlayerID, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetRoomSessionID, SeRaceRoomMgr::OnPlayerCancelHero, SeLogInfo.
void RaceServer::ProcessCR_SelHeroPrapared(SeCR_SelHeroPrapared *pkData, int iSize, void *pkSender)
References SeConnect::dwPlayerID, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetRoomSessionID, SeRaceRoomMgr::OnPlayerSelectHeroReady, SeLogInfo.
void RaceServer::ProcessCR_RaceReportSyn(SeCR_RaceReportSyn *pkData, int iSize, void *pkSender)
References SeConnect::dwPlayerID, g_kRaceMgr, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetRoomSessionID, SeRaceMgr::OnPlayerReportSyn, SeLogInfo.
void RaceServer::ProcessCR_Talk(SeCR_Talk *pkData, int iSize, void *pkSender)
References SeCR_Talk::acMessage, SeConnect::dwPlayerID, SeCR_Talk::eType, g_kRaceRoomMgr, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeRaceRoomMgr::GetRoom, SeMatchPlayer::GetRoomSessionID, SeRaceRoomMgr::OnPlayerTalk, SDD_MAIL_MSG_LEN, SMPS_RACING, SMPS_SELECT_HERO, StrCpy, STT_NORMAL_TALK.
void RaceServer::ProcessCR_RaceRobotLogin(SeCR_RaceRobotLogin *pkData, int iSize, void *pkSender)
References DISCONNECR_PLAYER, SeCR_RaceRobotLogin::dwMapID, SeConnect::dwPlayerID, SeTestRobot::dwPlayerID, SeCR_RaceRobotLogin::dwPlayerID, SeConnect::dwStateTime, SeConnect::eState, GetConnectByID, SeConnect::kSock, SeTestRobot::kSock, m_dwCurTime, m_kWaitRobot, SCS_VALID_OK, SeLogDebug, SeLogError.
void RaceServer::ProcessCR_Ping(SeCR_Ping *pkData, int iSize, void *pkSender)
References SeCR_Ping::dwPackIndex, SeConnect::kSock, SeUDPSender::kSock, SendRC_PingRet.
void RaceServer::ProcessCR_BuyRaceItem(SeCR_BuyRaceItem *pkData, int iSize, void *pkSender)
References SeRaceCmd_TownItem::bSuccess, SeCR_BuyRaceItem::dwItemTypeID, SeConnect::dwPlayerID, SeRaceCmd_TownItem::dwTargetUnitID, SeCR_BuyRaceItem::dwTarUnitID, SeRaceCmd_TownItem::dwTownItemTypeID, g_kRaceMgr, g_kRaceRoomMgr, SeRaceRoomMgr::GetPlayer, SeRaceMgr::OnPlayerBuyRaceItem, SeRaceMgr::OnPlayerRaceCmd.
void RaceServer::ProcessCR_GetHeroInfo(SeCR_GetHeroInfo *pkData, int iSize, void *pkSender)
References SeConnect::dwPlayerID, g_kRaceMgr, g_kRaceRoomMgr, SeRaceRoomMgr::GetPlayer, SeRaceMgr::OnGetHeroInfo.
void RaceServer::ProcessCR_ReplayReport(SeCR_ReplayReport *pkData, int iSize, void *pkSender)
References SeConnect::dwPlayerID, g_kRaceMgr, g_kRaceRoomMgr, SeRaceRoomMgr::GetPlayer, SeRaceMgr::OnPlayerRaceReplayReport.
void RaceServer::ProcessCR_SetEquipSetReq(SeCR_SetEquipSetReq *pkData, int iSize, void *pkSender)
References SeCR_SetEquipSetReq::byIndex, SeConnect::dwPlayerID, SeRaceRoom::eRoomState, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeRaceRoomMgr::GetRoom, SeMatchPlayer::GetRoomSessionID, SeConnect::kSock, SeUDPSender::kSock, SendRBL_SetEquipSetNtf, SendRC_SetEquipSetAck, SeMatchPlayer::setEquipSetIndex, SMPS_SELECT_HERO, SRRS_SELHERO.
void RaceServer::ProcessCR_SetAvatarReq(SeCR_SetAvatarReq *pkData, int iSize, void *pkSender)
References AVATAR_AVATARTYPE_SKIN, AVATAR_AVATARTYPE_TRAILING, SeCR_SetAvatarReq::dwItemID, SeConnect::dwPlayerID, SeRaceRoom::eRoomState, g_kRaceRoomMgr, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeRaceRoomMgr::GetRoom, SeMatchPlayer::GetRoomSessionID, SeMatchPlayer::GetSelHeroID, SeConnect::kSock, SeUDPSender::kSock, SendRBL_SetAvatarNtf, SendRC_SetAvatarAck, SeMatchPlayer::setAvatar, SMPS_SELECT_HERO, SRRS_SELHERO.
bool RaceServer::SendRM_Register(DWord dwServerID, DWord dwAreaID, const SeNetAddr &kAddrToMatch, const SeNetAddr &kAddrToMatchUdp, int iRegisterCount, bool bOpen, void *pkReceiver=NULL)
Referenced by RegisterToMS.
bool RaceServer::SendRM_HeartPackage(DWord dwCurrRaceNum, void *pkReceiver=NULL)
Referenced by UpdateMSHeartPackage.
bool RaceServer::SendRM_ValidatePlayerInfoRet(DWord dwSessionID, const SeMatchValidateResult &eResult, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::OnProcessRepeatPlayer, SeRaceRoomMgr::OnRaceLeave, SeRaceRoomMgr::UpdateWaitRoom.
bool RaceServer::SendRM_CommRaceMsg(DWord dwMatchSession, const SeRaceSvrCommMsg &eMsg, DWord dwParam, int iParam, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::OnProcessRepeatPlayer, SeRaceRoomMgr::OnRaceLeave, SeRaceRoomMgr::StartLoad, SeRaceRoomMgr::UpdateRaceEndTime.
bool RaceServer::SendRM_RaceGetCardInfo(DWord dwSession, DWord dwPlayerID, DWord dwHeroTypeID, DWord dwMapTypeID, void *pkReceiver=NULL)
bool RaceServer::SendRM_UpdateMisc(DWord dwPlayerID, DWord dwSession, const SeMMMiscType &eType, int iValue, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::BeginRaceView, SeRaceRoomMgr::JoinRoomRecon, OnNetDisconnect, OnNetUdpDisconnect, SeRaceRoomMgr::OnRaceLeave.
bool RaceServer::SendRM_RaceEndReport(DWord dwMatchSession, DWord dwTime, DWord dwMapID, const SeMatchRaceType &eMatchType, int iNum, const SeWSRaceSendInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnCheckRaceEnd.
bool RaceServer::SendRM_RaceEndReport(DWord dwMatchSession, DWord dwTime, DWord dwMapID, const SeMatchRaceType &eMatchType, int iNum, std::vector< SeWSRaceSendInfo > &akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_RaceEndGuanqia(DWord dwMatchSession, DWord dwTime, DWord dwMapID, int iNum, const SeWSGuanqiaSendInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnCheckGuanqiaEnd.
bool RaceServer::SendRM_RaceEndGuanqia(DWord dwMatchSession, DWord dwTime, DWord dwMapID, int iNum, std::vector< SeWSGuanqiaSendInfo > &akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_MatchRoomLoadInfo(DWord dwSession, int iNum, const SeMatchRoomLoadInfo *akLoadInfo, void *pkReceiver=NULL)
Referenced by OnSendMatchRoomLoadInfo.
bool RaceServer::SendRM_MatchRoomLoadInfo(DWord dwSession, int iNum, std::vector< SeMatchRoomLoadInfo > &akLoadInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_RefreshConfigInfo(bool bOpen, void *pkReceiver=NULL)
Referenced by LoadConfig.
bool RaceServer::SendRM_ReconQuerySuccess(DWord dwRoomID, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iSeat, int iOffset, DWord dwFrame, void *pkReceiver=NULL)
Referenced by ProcessMR_ReconQuery.
bool RaceServer::SendRM_ReconQueryFail(const SeReconQueryFailReason &eReason, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessMR_ReconQuery.
bool RaceServer::SendRM_ViewQuerySuccess(DWord dwSession, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iViewDelay, void *pkReceiver=NULL)
Referenced by ProcessMR_ViewQuery.
bool RaceServer::SendRM_ViewQueryFail(const SeViewQueryFailReason &eReason, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessMR_ViewQuery.
bool RaceServer::SendRM_ReconViewValid(DWord dwSession, DWord dwPlayerID, DWord dwKey, const SeRaceValidType &eValidType, void *pkReceiver=NULL)
Referenced by ProcessCR_RaceValidate.
bool RaceServer::SendRM_ReLoadRoomInfoList(int iNum, const SeReLoadRoomInfo *akRoomInfo, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::UpdateReSendRoomList.
bool RaceServer::SendRM_ReLoadRoomInfoList(int iNum, std::vector< SeReLoadRoomInfo > &akRoomInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_MatchRaceLoad(DWord dwRoomSession, DWord dwMapID, void *pkReceiver=NULL)
Referenced by SeRaceRoomMgr::UpdateReady.
bool RaceServer::SendRM_RaceBuy(DWord dwSession, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnPlayerBuyRaceItem.
bool RaceServer::SendRM_AddIncompleteRace(DWord dwRoomSession, int iSeat, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by SeMatchReconMgr::Update.
bool RaceServer::SendRM_RemoveIncompleteRace(DWord dwRoomSession, void *pkReceiver=NULL)
bool RaceServer::SendRM_UpdateIncompleteRace(DWord dwRoomSession, int iSeat, bool bSeat, void *pkReceiver=NULL)
Referenced by SeMatchReconMgr::AddRaceSeat, SeMatchReconMgr::RemoveRaceSeat.
bool RaceServer::SendRM_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, const SeSeatBaseInfo *oIncmpRaceBaseInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnRaceKDA.
bool RaceServer::SendRM_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, std::vector< SeSeatBaseInfo > &oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool RaceServer::SendRMData(void *pkData, int iSize, void *pkReceiver)
References CMD_RM_HEARTPACKAGE, CMD_RM_REGISTER, IsMSReady, SeServerData::kSock, m_kMSData, m_kNetMgr, SeCMD::wCmd.
bool RaceServer::ProcessMRData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool RaceServer::PreProcessMR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_RegisterRet(SeMR_RegisterRet *pkData, int iSize, void *pkSender)
References SeServerData::bRegistered, SeMR_RegisterRet::bRunning, SeServerData::dwHeartPackageTime, SeRaceConfig::dwServerID, SeMR_RegisterRet::eRet, g_kRaceRoomMgr, GetID2Str, m_iRegisterCount, m_kConfig, m_kMSData, SeRaceRoomMgr::OnReSendRoomInfo, SeLogError, SeLogInfo, SetMSReady, SRR_REPEAT, SRR_SUCCESS.
void RaceServer::ProcessMR_HeartPackageRet(SeMR_HeartPackageRet *pkData, int iSize, void *pkSender)
References SeServerData::dwHeartPackageTime, m_kMSData.
void RaceServer::ProcessMR_ValidatePlayerInfo(SeMR_ValidatePlayerInfo *pkData, int iSize, void *pkSender)
References SeMR_ValidatePlayerInfo::acData, SeNetStream::Attach, SeRaceRoomMgr::CreateRoom, g_kRaceRoomMgr, SeMR_ValidatePlayerInfo::iSize, Read.
void RaceServer::ProcessMR_PlayerModifyInfo(SeMR_PlayerModifyInfo *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_UpdateMiscInfo(SeMR_UpdateMiscInfo *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_ReconQuery(SeMR_ReconQuery *pkData, int iSize, void *pkSender)
References SeMR_ReconQuery::dwAreaID, SeMR_ReconQuery::dwFrame, SeMR_ReconQuery::dwPlayerID, SeMR_ReconQuery::dwRoomID, SeMR_ReconQuery::dwServerID, g_kRaceRoomMgr, SeMR_ReconQuery::iOffset, SeMR_ReconQuery::iSeat, SeRaceRoomMgr::OnPlayerReconQuery, SAFECHECK_INDEX, SendRM_ReconQueryFail, SendRM_ReconQuerySuccess, SRQF_NULL, SSD_MAX_ROOM_PLAYER.
void RaceServer::ProcessMR_ViewQuery(SeMR_ViewQuery *pkData, int iSize, void *pkSender)
References SeMR_ViewQuery::dwAreaID, SeMR_ViewQuery::dwPlayerID, SeMR_ViewQuery::dwServerID, SeMR_ViewQuery::dwSession, g_kRaceRoomMgr, SeMR_ViewQuery::iViewDelay, SeRaceRoomMgr::OnPlayerViewQuery, SendRM_ViewQueryFail, SendRM_ViewQuerySuccess, SVQF_NULL.
void RaceServer::ProcessMR_ViewValidOKRet(SeMR_ViewValidOKRet *pkData, int iSize, void *pkSender)
References SeViewInitInfo::dwPlayerID, g_kRaceRoomMgr, GetConnectByID, SeMR_ViewValidOKRet::kInitInfo, SeRaceRoomMgr::OnViewValidOKRet.
void RaceServer::ProcessMR_ValidFailRet(SeMR_ValidFailRet *pkData, int iSize, void *pkSender)
References DisconnectPlayer, SeConnect::dwPlayerID, SeMR_ValidFailRet::dwPlayerID, SeMR_ValidFailRet::dwSession, GetConnectByID, SeLogError.
void RaceServer::ProcessMR_RaceBuyRet(SeMR_RaceBuyRet *pkData, int iSize, void *pkSender)
References SeMR_RaceBuyRet::bSuccess, SeRaceCmd_TownItem::bSuccess, SeMR_RaceBuyRet::dwParam1, SeMR_RaceBuyRet::dwParam2, SeMR_RaceBuyRet::dwPlayerID, SeMR_RaceBuyRet::dwSession, SeRaceCmd_TownItem::dwTargetUnitID, SeRaceCmd_TownItem::dwTownItemTypeID, SeRaceRoom::eRoomState, g_kRaceMgr, g_kRaceRoomMgr, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeRaceRoomMgr::GetRoom, SeMR_RaceBuyRet::iType, SeRaceMgr::OnPlayerRaceCmd, SMPS_RACING, SRBT_RACE_ITEM, SRRS_RACING.
void RaceServer::ProcessMR_ReconPLayerName(SeMR_ReconPLayerName *pkData, int iSize, void *pkSender)
References SeMR_ReconPLayerName::acName, SeMatchReconMgr::AddReconPlayerName, SeMR_ReconPLayerName::dwPlayerID, g_kMatchReconMgr, SeLogDebug.
bool RaceServer::SendRWCS_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
Referenced by ProcessWCSR_Register.
bool RaceServer::SendRWCS_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessWCSR_HeartPackage.
bool RaceServer::SendRWCS_RaceRecord(const Byte *rID, int iNum, const char *raceDat, void *pkReceiver=NULL)
Referenced by SeRaceMgr::UpdateView.
bool RaceServer::SendRWCS_RaceRecord(std::vector< Byte > &rID, int iNum, std::vector< char > &raceDat, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceEnd(const Byte *rID, void *pkReceiver=NULL)
Referenced by SeRaceMgr::UpdateView, SeRaceMgr::UpdateViewEnd.
bool RaceServer::SendRWCS_RaceEnd(std::vector< Byte > &rID, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceStart(const Byte *rID, int iNum, const SePlayerInfoSeat *racePlayerSeatInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::UpdateView.
bool RaceServer::SendRWCS_RaceStart(std::vector< Byte > &rID, int iNum, std::vector< SePlayerInfoSeat > &racePlayerSeatInfo, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceDetailInfoSync(int num, const SeRaceDetailInfo *akRaceDetailInfo, void *pkReceiver=NULL)
Referenced by RaceDetailMgr::SyncRaceDetail.
bool RaceServer::SendRWCS_RaceDetailInfoSync(int num, std::vector< SeRaceDetailInfo > &akRaceDetailInfo, void *pkReceiver=NULL)
bool RaceServer::SendRWCSData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool RaceServer::ProcessWCSRData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool RaceServer::PreProcessWCSR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessWCSR_Register(SeWCSR_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeWCSR_Register::acViewInfo, SeWatchServerConnect::bRegister, SeWCSR_Register::dwServerID, SeWatchServerConnect::dwServerID, SeWCSView::dwWCSID, g_kRaceMgr, GetID2Str, SeNetAddr::iPort, SeWCSR_Register::iSize, SeWatchServerConnect::kNetAddr, SeWatchServerConnect::kSock, SeWCSView::kWCSSock, m_vWCSView, SeRaceMgr::ReflashWCSViewInfo, SeLogInfo, SendRWCS_RegisterRet, SRR_REPEAT, SRR_SUCCESS.
void RaceServer::ProcessWCSR_HeartPackage(SeWCSR_HeartPackage *pkData, int iSize, void *pkSender)
References SendRWCS_HeartPackageRet.
bool RaceServer::PushRSC_RaceInit(DWord dwRaceIndex, TeMD5 &rkRaceID, int iMapID, int iSeatInfo, VRacePlayer &rkVRacePlayer)
References SeRSC_RaceInit::akInfo, SeRaceStartInfo::bLeave, SeRSC_RaceInit::iMapID, SeRSC_RaceInit::iNum, SeRaceStartInfo::iSeatIndex, SeRSC_RaceInit::iSeatInfo, SeRSC_RaceInit::kRaceID, SeRaceStartInfo::kSock, MNew, PushRaceServiceMsg, SSD_SEND_SIZE.
Referenced by SeRaceMgr::CreateRobotRace, SeRaceMgr::OnRaceModeEnd.
bool RaceServer::PushRSC_RaceStream(DWord dwRaceIndex, TeMD5 &rkRaceID, char *pcData, int iDataSize)
References SeRSC_RaceStream::acData, SeRSC_RaceStream::iDataSize, SeRSC_RaceStream::kRaceID, MemCpy, MNew, PushRaceServiceMsg, SSD_ENDSTR_LEN, SSD_SEND_SIZE.
Referenced by SeRaceMgr::CreateRobotRace, SeRaceMgr::OnPlayerGuanqiaEnd, SeRaceMgr::OnPlayerRaceCmd, SeRaceMgr::OnPlayerRaceEnd, SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnPlayerReconBegin, SeRaceMgr::OnRaceModeEnd, SeRaceMgr::UpdateLoadEnd, SeRaceMgr::UpdateReconEnd.
bool RaceServer::PushRSC_PlayerLeave(DWord dwRaceIndex, TeMD5 &rkRaceID, int iSeat)
References SeRSC_PlayerLeave::iSeat, SeRSC_PlayerLeave::kRaceID, PushRaceServiceMsg.
Referenced by SeRaceMgr::OnPlayerGuanqiaEnd, SeRaceMgr::OnPlayerRaceEnd, SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::UpdateLoadEnd.
bool RaceServer::PushRSC_PlayerRelink(DWord dwRaceIndex, TeMD5 &rkRaceID, int iSeat, HSock &rkSock)
References SeRSC_PlayerRelink::iSeat, SeRSC_PlayerRelink::kRaceID, SeRSC_PlayerRelink::kSock, PushRaceServiceMsg.
Referenced by SeRaceMgr::OnPlayerReconBegin, SeRaceMgr::UpdateReconEnd.
bool RaceServer::PushRSC_RaceOver(DWord dwRaceIndex, TeMD5 &rkRaceID)
References SeRSC_RaceOver::kRaceID, PushRaceServiceMsg.
Referenced by SeRaceMgr::UpdateCheckOvertimeRace.
bool RaceServer::PushRSC_RaceStart(DWord dwRaceIndex, TeMD5 &rkRaceID, VRacePlayer &rkVRacePlayer)
References SeRSC_RaceStart::akInfo, SeRaceStartInfo::bLeave, SeRSC_RaceStart::iNum, SeRaceStartInfo::iSeatIndex, SeRSC_RaceStart::kRaceID, SeRaceStartInfo::kSock, MNew, PushRaceServiceMsg, SSD_SEND_SIZE.
Referenced by SeRaceMgr::UpdateLoadEnd.
bool RaceServer::PushRSC_GetHeroInfo(DWord dwRaceIndex, TeMD5 &rkRaceID, int iSeat)
References SeRSC_GetHeroInfo::iSeat, SeRSC_GetHeroInfo::kRaceID, PushRaceServiceMsg.
Referenced by SeRaceMgr::OnGetHeroInfo.
bool RaceServer::PushRSC_SetRaceIncmpState(DWord dwRaceIndex, TeMD5 &rkRaceID, bool bIncmp)
References SeRSC_SetRaceIncmpState::bIncmp, SeRSC_SetRaceIncmpState::kRaceID, PushRaceServiceMsg.
Referenced by SeMatchReconMgr::RemoveRace, SeMatchReconMgr::Update.
void RaceServer::ProcessRCR(void *pkData, int iSize)
References CMD_RCR_ACHIEVEMENT_COUNTS, CMD_RCR_COMMAND, CMD_RCR_GET_ACHIEVEMENT, CMD_RCR_RACE_END, CMD_RCR_RACE_ERROR, CMD_RCR_RACE_INIT_FAIL, CMD_RCR_RACE_OPR, CMD_RCR_RACE_SVR_MODEL_PACK, CMD_RCR_THREAD_OVERTIME, ProcessRC_AchievementCounts, ProcessRC_Command, ProcessRC_GetAchievement, ProcessRC_RaceEnd, ProcessRC_RaceError, ProcessRC_RaceInitFail, ProcessRC_RaceOpr, ProcessRC_RaceSvrModelPack, ProcessRC_ThreadOverTime, SeThreadCmd::wCmd.
Referenced by UpdateRSMsg.
void RaceServer::ProcessRC_RaceStream(void *pkData, int iSize)
void RaceServer::ProcessRC_RaceEnd(void *pkData, int iSize)
References SeRCR_RaceEnd::acData, g_kRaceMgr, SeRCR_RaceEnd::kRaceID, SeRaceMgr::OnSvrRaceResult, SSD_ENDSTR_LEN.
Referenced by ProcessRCR.
void RaceServer::ProcessRC_RaceError(void *pkData, int iSize)
References g_kRaceMgr, SeRCR_RaceError::kRaceID, SeRaceMgr::OnSvrRaceError.
Referenced by ProcessRCR.
void RaceServer::ProcessRC_RaceInitFail(void *pkData, int iSize)
Referenced by ProcessRCR.
void RaceServer::ProcessRC_RaceOpr(void *pkData, int iSize)
References g_kRaceMgr, SeRCR_RaceOpr::iOprType, SeRCR_RaceOpr::iThreadIndex, SeRaceMgr::OprSvrRaceNum.
Referenced by ProcessRCR.
void RaceServer::ProcessRC_RaceSvrModelPack(void *pkData, int iSize)
References SeRCR_RaceSvrModelPack::acData, g_kRaceMgr, SeRCR_RaceSvrModelPack::iSize, SeRCR_RaceSvrModelPack::kRaceID, SeRaceMgr::OnSvrRaceSvrModelPack, SSD_ENDSTR_LEN.
Referenced by ProcessRCR.
void RaceServer::ProcessRC_ThreadOverTime(void *pkData, int iSize)
References SeRCR_ThreadOverTime::iDTime, SeRCR_ThreadOverTime::iThreadIndex, m_akThreadTime, SeLogInfo, Stat_TIME_THREAD_NUM.
Referenced by ProcessRCR.
void RaceServer::ProcessRC_GetAchievement(void *pkData, int iSize)
References SeRCR_GetAchievement::dwAID, SeRCR_GetAchievement::dwLvl, g_kRaceMgr, SeRCR_GetAchievement::iSeat, SeRCR_GetAchievement::kRaceID, SeRaceMgr::OnGetAchievement.
Referenced by ProcessRCR.
void RaceServer::ProcessRC_AchievementCounts(void *pkData, int iSize)
References TeMD5::abyMD5, g_kRaceMgr, GetMD52Str, SeRaceMgr::GetRace, SeRaceMgr::GetRacePlayerBySeat, SeRCR_AchievementCounts::iSeat, SeRCR_AchievementCounts::iSize, SeRCR_AchievementCounts::kRaceID, SeLogError.
Referenced by ProcessRCR.
void RaceServer::ProcessRC_Command(void *pkData, int iSize)
References SeRCR_Command::command, moba::Command::execute.
Referenced by ProcessRCR.
int RaceServer::GetDebugLevel(void)
References SeRaceConfig::iDebugLevel, m_kConfig.
Referenced by SeRaceMgr::UpdateLoadingRace.
void RaceServer::SetDebugLevel(int iLevel)
References SeRaceConfig::iDebugLevel, m_kConfig.
int RaceServer::GetRacePackTime(void)
References SeRaceConfig::iRacePackTime, m_kConfig.
Referenced by SeRaceMgr::UpdateRace.
char * RaceServer::GetGameLogFilePath()
References SeRaceConfig::acGameLogFilePath, m_kConfig.
int RaceServer::GetRaceServiceNum(void)
References m_iRaceServiceNum.
Referenced by SeRaceMgr::GetFreeThreadIndex.
int RaceServer::GetRacePrintTime(void)
References SeRaceConfig::iRacePrintTime, m_kConfig.
Referenced by RaceService::DoWork, RaceService::Update.
int RaceServer::GetMaxPacketSize(void)
References SeRaceConfig::iRacePacketMaxSize, m_kConfig.
Referenced by RaceService::DoWork.
int RaceServer::GetServerModePackTime(void)
References SeRaceConfig::iServerModePackTime, m_kConfig.
Referenced by SeThreadRaceMgr::UpdateRace.
int RaceServer::GetMaxReconTime(void)
References SeRaceConfig::iMaxReconTime, m_kConfig.
Referenced by SeMatchReconMgr::Update.
bool RaceServer::IsTestRobotMode()
References SeRaceConfig::bTestRobotMode, m_kConfig.
Referenced by SeRaceRoomMgr::CreateRoom, OnNetUdpAccept, OnPlayerConnected.
int RaceServer::GetServerID(void)
References SeRaceConfig::dwServerID, m_kConfig.
Referenced by CheckConnect, SeRaceMgr::CreateRobotRace, SeRaceMgr::GenRaceID, SeRaceMgr::OnRaceModeEnd, sendRegPack, ShowConsoleTitle.
int RaceServer::GetAreaID(void)
References SeRaceConfig::dwAreaID, m_kConfig.
DWord RaceServer::GetServerTime(void)
References m_dwCurTime.
Referenced by SeMatchReconMgr::AddPlayer, SeMatchReconMgr::AddReconPlayerName, SeRaceRoomMgr::BeginRaceView, SeRaceRoomMgr::ChangeRoomState, RaceDetailMgr::CheckRace_UserAttr_Bound, RaceDetailMgr::CreateRaceDetail, SeRaceMgr::CreateRobotRace, SeRaceRoomMgr::CreateRoom, SeThreadRaceMgr::DelRace, SeRaceMgr::GenRaceID, SeRaceMgr::GetRaceTime, SeRaceRoomMgr::IntoSelHero, OnNetRecv, OnNetUdpRecv, SeRaceMgr::OnPlayerRaceCmd, SeRaceMgr::OnRaceModeEnd, SeRaceMgr::OnRealTimeRaceKDA, SeRaceRoomMgr::SelHeroReady, SeMatchReconMgr::Update, SeRaceMgr::UpdateCheckOvertimeRace, UpdateHeartPackage, SeRaceMgr::UpdateLoadEnd, SeRaceMgr::UpdateLoadingRace, UpdateMSHeartPackage, UpdateMSState, SeThreadRaceMgr::UpdateRace, SeRaceMgr::UpdateRaceEnd, SeRaceRoomMgr::UpdateRaceEndTime, SeRaceRoomMgr::UpdateReady, SeRaceRoomMgr::UpdateReSendRoomList, UpdateRSConfig, UpdateSaveThreadUpdateTime, SeRaceRoomMgr::UpdateSelHero, UpdateWaitRobot, SeRaceRoomMgr::UpdateWaitRoom.
int RaceServer::RandInt(void)
References m_kRandNum, SeRandNum::RandInt.
Referenced by SeRaceMgr::GetRandHeroID, SeRaceRoomMgr::GetRandID, SeRaceMgr::OnPlayerReportSyn, SeMatchPlayer::setRandomAvatar.
void RaceServer::OnSendMatchRoomLoadInfo(DWord dwSession, VRacePlayer &rkVRacePlayer)
References SeRacePlayer::acName, SeMatchRoomLoadInfo::acName, SeMatchRoomLoadInfo::bEscape, SeRacePlayer::bLeaveRace, SeMatchRoomLoadInfo::dwHeroID, SeRacePlayer::dwHeroTypeID, SeMatchRoomLoadInfo::dwSkinTypeID, SeMatchRoomLoadInfo::iSeat, SeRacePlayer::iSeatIndex, MemCpy, SendRM_MatchRoomLoadInfo, SSD_MAX_CHAR_NAME.
Referenced by SeRaceMgr::OnRaceModeEnd.
void RaceServer::OnSendPlayerRaceStream(HSock &rkPlayerSock, bool bMustSend, const char *pkData, int iDataSize)
References g_kRaceServer, SeUDPSender::iFlag, SeUDPSender::iProtocolFlag, SeUDPSender::kSock, OnPlayerDisconnect, SCF_UDP_UNRELIABLE, SeLogError, SendRC_RaceStream.
Referenced by SeRaceDataMgr::UpdateRaceData.
void RaceServer::SendPlayer_ReconNoticePlayerJoin(HSock &rkPlayerSock, int iSeat, int iSize, const char *sName)
References SeUDPSender::kSock, SendRC_ShowNotice, SNC_PLAYER_RECON.
Referenced by SeRaceMgr::UpdateReconEnd.
void RaceServer::DelWaitRobot(DWord dwPlayerID)
References m_kWaitRobot.
Referenced by OnNetDisconnect.
void RaceServer::UpdateWaitRobot()
References SeTestRobot::dwPlayerID, g_kRaceServer, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, GetServerTime, MapInfoTable::iMaxPlayer, m_kWaitRobot, StartRobotGame.
Referenced by Update.
void RaceServer::StartRobotGame(const MapInfoTable *pkMapRes, VTestRobot &rakRobot)
References SeRaceRoomMgr::CreateRoom, SeCR_RaceValidate::dwKey, SeMR_ValidatePlayerInfo::dwKey, SeMR_ValidatePlayerInfo::dwMapID, SeCR_RaceValidate::dwPlayerID, SeConnect::dwPlayerID, SeTestRobot::dwPlayerID, SePtlMatchRaceInfo::dwPlayerID, SeMR_ValidatePlayerInfo::dwSessionID, SeCR_RaceValidate::dwSessionId, SePtlMatchRaceInfo::eCamp, SeCR_RaceValidate::eValidType, g_kRaceRoomMgr, GetConnectBySock, MapInfoTable::iCampNum, MapInfoTable::iMaxPlayer, SeCR_RaceValidate::iSeat, SePtlMatchRaceInfo::iSeatIndex, SeTestRobot::kSock, ProcessCR_RaceValidate, SeLogError, SRPC_INVALID, SRVT_RACE, MapInfoTable::uiMapTypeID.
Referenced by UpdateWaitRobot.
bool RaceServer::PushRaceServiceMsg(DWord dwThreadIndex, void *pkData, int iSize)
References m_iRaceServiceNum, m_pakRaceService, RaceService::PushMsg, SeLogError.
Referenced by PushRSC_GetHeroInfo, PushRSC_PlayerLeave, PushRSC_PlayerRelink, PushRSC_RaceInit, PushRSC_RaceOver, PushRSC_RaceStart, PushRSC_RaceStream, PushRSC_SetRaceIncmpState.
bool RaceServer::PushRSMsg(void *pkData, int iSize)
References m_kThreadMsgMgr, SeThreadMsgMgr::PushMsg.
Referenced by SeThreadRaceMgr::AddRace, SeThreadRaceMgr::DelRace, RaceService::OnAchievementCounts, RaceService::OnAddRaceRet, RaceService::OnDecRespawnItem, RaceService::OnGetAchievement, RaceService::OnPlayerItemChange, RaceService::OnRaceEndArenaDetail, RaceService::OnRaceEndGradeDetail, RaceService::OnRaceErrorRet, RaceService::OnRaceEvent, RaceService::OnRaceKDA, RaceService::OnRaceSvrModelPack, RaceService::OnRealTimeRaceKDA, RaceService::OnRealTimeRaceMapDetail, RaceService::Update.
bool RaceServer::SendRN_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool RaceServer::SendRN_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool RaceServer::SendRN_RaceLinkUserSync(DWord dwPlayerID, DWord dwStateID, void *pkReceiver=NULL)
Referenced by RaceLinkUserSync.
bool RaceServer::SendRNData(void *pkData, int iSize, void *pkReceiver)
References CMD_RN_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkNSConn, SVCS_REGISTERED, SeCMD::wCmd.
bool RaceServer::ProcessNRData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool RaceServer::PreProcessNR(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkNSConn.
void RaceServer::ProcessNR_RegisterRet(SeNR_RegisterRet *pkData, int iSize, void *pkSender)
References SeNR_RegisterRet::dwAreaID, SeVirtConn::dwAreaID, SeNR_RegisterRet::eRegisterRet, SeVirtConn::eState, m_pkNSConn, SeLogError, SeLogInfo, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void RaceServer::ProcessNR_HeartPackageRet(SeNR_HeartPackageRet *pkData, int iSize, void *pkSender)
bool RaceServer::SendRW_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool RaceServer::SendRW_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool RaceServer::SendRWData(void *pkData, int iSize, void *pkReceiver)
References CMD_RW_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkWSConn, SVCS_REGISTERED, SeCMD::wCmd.
Referenced by SendRBLData.
bool RaceServer::ProcessWRData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool RaceServer::PreProcessWR(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkWSConn.
void RaceServer::ProcessWR_RegisterRet(SeWR_RegisterRet *pkData, int iSize, void *pkSender)
References SeWR_RegisterRet::dwAreaID, SeVirtConn::dwAreaID, SeWR_RegisterRet::eRegisterRet, SeVirtConn::eState, m_pkWSConn, SeLogError, SeLogInfo, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void RaceServer::ProcessWR_HeartPackageRet(SeWR_HeartPackageRet *pkData, int iSize, void *pkSender)
bool RaceServer::SendRBL_UpdateScore(DWord dwPlayerID, const MatchType &eMatchType, int score, bool win, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnRaceEndGradeDetail.
bool RaceServer::SendRBL_AwardItemNtf(DWord dwPlayerID, int iNum, const SeAwardItem *awards, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnPlayerItemChange.
bool RaceServer::SendRBL_AwardItemNtf(DWord dwPlayerID, int iNum, std::vector< SeAwardItem > &awards, void *pkReceiver=NULL)
bool RaceServer::SendRBL_DecRespawnItemNtf(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnDecRespawnItem.
bool RaceServer::SendRBL_SetEquipSetNtf(DWord dwPlayerID, Byte byIndex, void *pkReceiver=NULL)
Referenced by ProcessCR_SetEquipSetReq.
bool RaceServer::SendRBL_SetRaceMapHeroNtf(DWord dwPlayerID, DWord dwMapID, DWord dwHeroID, DWord dwWinCounts, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnRaceEndArenaDetail.
bool RaceServer::SendRBL_SetAvatarNtf(DWord dwPlayerID, DWord dwHeroID, DWord dwItemID, void *pkReceiver=NULL)
Referenced by ProcessCR_SetAvatarReq.
bool RaceServer::SendRBL_SelectHeroReq(DWord dwPlayerID, DWord dwHeroID, void *pkReceiver=NULL)
Referenced by ProcessCR_SelHeroChoiceHero.
bool RaceServer::SendRBL_UserRaceMapNtf(DWord dwPlayerID, const SeRaceEndArenaDetailInfo &akRaceMaplInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnRaceEndArenaDetail.
bool RaceServer::SendRBL_RaceEndArenaBaseInfoSync(DWord dwPlayerID, const SeRaceEndArenaBaseInfo &akRaceBaselInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnRaceEndArenaDetail.
bool RaceServer::SendRBLData(void *pkData, int iSize, void *pkReceiver)
References SendRWData.
bool RaceServer::ProcessBLRData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool RaceServer::PreProcessBLR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessBLR_SelectHeroAck(SeBLR_SelectHeroAck *pkData, int iSize, void *pkSender)
References SeSelHeroInfo::dwHeroTypeID, SeBLR_SelectHeroAck::dwPlayerID, SeRaceRoom::eRoomState, g_kRaceRoomMgr, g_kRaceServer, SeMatchPlayer::GetHSock, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerState, SeRaceRoomMgr::GetRoom, SeMatchPlayer::GetRoomSessionID, SeBLR_SelectHeroAck::hero, SeBLR_SelectHeroAck::iResult, SeUDPSender::kSock, SeRaceRoomMgr::OnPlayerChoiceHero, SeMatchPlayer::pushHero, SendRC_ShowNotice, SMPS_SELECT_HERO, SNC_MATCH_SELHERO_FAIL, SRRS_SELHERO.
void RaceServer::OnPlayerConnected(SeConnect *pkConnect, const char *pcIP, int iPort)
References SeConnect::acEncryptKey, SeNetAddr::acIP, SeRaceConfig::dwGenRobotID, SeConnect::dwLastRecvTime, SeConnect::dwPlayerID, SeConnect::dwStateTime, SeConnect::eState, GenEncryptKey, SeNetAddr::iPort, IsTestRobotMode, SeConnect::kNetAddr, SeConnect::kSock, SeUDPSender::kSock, LOGIC_VERSION, m_dwCurTime, m_kConfig, SCS_UNKOWN, SeLogInfo, SendRC_EncryptKey, SSD_EN_KEY_LEN, StrCpy.
Referenced by OnNetAccept, OnNetUdpAccept.
void RaceServer::OnPlayerDisconnect(HSock rkSock)
References DisconnectPlayer, m_kAllConnect.
Referenced by SeRaceRoomMgr::OnRaceLeave, OnSendPlayerRaceStream, SeRaceRoomMgr::RecycleRoomPlayer.
void RaceServer::ClearAllPlayerConn()
References DisconnectPlayer, m_kAllConnect.
SeConnect * RaceServer::GetConnectByID(DWord dwPlayerID)
References SeConnect::dwPlayerID, m_kAllConnect.
Referenced by ProcessCR_RaceRobotLogin, ProcessCR_RaceValidate, ProcessMR_ValidFailRet, ProcessMR_ViewValidOKRet.
void RaceServer::GetServerRunState(int &riSvrModeNum, int &riNormalNum)
References g_kRaceMgr, SeRaceMgr::GetNormalRaceNum, SeRaceMgr::GetSvrModeRaceNum.
Referenced by ShowConsoleTitle.
int RaceServer::GetConnectNum()
References m_kAllConnect.
Referenced by ShowConsoleTitle.
void RaceServer::DelConnectByID(DWord dwPlayerID)
References SeRaceConfig::bTcpClient, SeConnect::dwPlayerID, SeConnect::kSock, m_kAllConnect, m_kConfig, m_kNetMgr, m_kUdpMgr, SeLogError.
Referenced by SeRaceRoomMgr::CreateRoom.
SeConnect * RaceServer::GetConnectBySock(const HSock &rkSock)
References m_kAllConnect.
Referenced by StartRobotGame.
bool RaceServer::ReLoadServerAddr(const char *pcFile)
References SeConfig::GetNetAddr, SeNetAddr::IsEmpty, SeRaceConfig::kMSServer, SeServerData::kSock, SeConfig::Load, m_kConfig, m_kMSData, m_kNetMgr, SeLogError, SeLogInfo.
Referenced by UpdateRSConfig.
bool RaceServer::LoadConfig(const char *pcFile)
References SeRaceConfig::bCanLoad, SeRaceConfig::bOpen, LoadRSTempConfig, m_kConfig, MemCpy, SeLogInfo, SendRM_RefreshConfigInfo.
Referenced by Initialize, ReLoadConfig.
void RaceServer::ReLoadConfig()
References LoadConfig.
Referenced by ExecuteAction, UpdateRSConfig.
bool RaceServer::LoadRSTempConfig(const char *pcFile, SeRaceConfig &rkRSConfig)
References SeRaceConfig::acDumpPath, SeRaceConfig::acGameLogFilePath, SeRaceConfig::acRaceRecordSavePath, SeRaceConfig::acRaceRecordURLBase, SeRaceConfig::acRandSelHeroQuality, SeRaceConfig::acRecordSaveBat, SeRaceConfig::bCanLoad, SeRaceConfig::bOpen, SeRaceConfig::bRCPacketToFile, SeRaceConfig::bRealTickTime, SeRaceConfig::bTcpClient, SeRaceConfig::bTestRobotMode, SeRaceConfig::dwAreaID, SeRaceConfig::dwServerID, SeRaceConfig::fWriteInterval, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeRaceConfig::iClientHeartBeatTime, SeRaceConfig::iDebugLevel, SeRaceConfig::iLogicDllRaceNum, SeRaceConfig::iMaxReconTime, SeRaceConfig::iRaceJustify, SeRaceConfig::iRacePacketMaxSize, SeRaceConfig::iRacePackTime, SeRaceConfig::iRacePrintTime, SeRaceConfig::iServerModePackTime, SeRaceConfig::iStatisticPacketSize, SeRaceConfig::iStatisticPacketSizeTime, SeRaceConfig::iTestRaceNum, SeRaceConfig::kAddrToPlayer, SeRaceConfig::kAddrToPlayerUdp, SeRaceConfig::kAddrToWCS, SeRaceConfig::kMSServer, SeConfig::Load, m_iRaceServiceNum, m_iRobotRaceNum, SeLogError, SeLogInfo, StrCpy.
Referenced by LoadConfig.
bool RaceServer::IsMSReady(void)
References SeServerData::bRegistered, SeServerData::kSock, m_bMSReady, m_kMSData.
Referenced by SeRaceMgr::OnCheckGuanqiaEnd, SeRaceMgr::OnCheckRaceEnd, OnNetAccept, OnNetUdpAccept, SendRMData.
DWord RaceServer::GetMSID()
References SeServerData::dwID, m_kMSData.
SeRaceConfig RaceServer::GetRaceConfig()
References m_kConfig.
Referenced by SeRaceMgr::GetFreeThreadIndex, SeRaceMgr::GetFreeThreadIndexByNum, RaceService::Initialize, SeRaceMgr::OnPlayerRaceLeave, SeThreadRaceMgr::PrintCmdData, SeRaceRecordSaveThread::saveRecord, CPerformanceIntervalFileDump::Tick, SeRaceMgr::UpdateView.
void RaceServer::SaveRecord(SeRace *pRace)
References m_pkSaveRecordThread, SeRaceRecordSaveThread::PushTask.
const TWCSViewArray& RaceServer::GetWCSView() const
References m_vWCSView.
Referenced by SeRaceMgr::UpdateView.
MapWCSConnect& RaceServer::GetWCSConnectMap()
References m_kWCSConnect.
Referenced by RaceDetailMgr::SyncRaceDetail.
void RaceServer::RaceThreadInitialize()
References SeRaceRecordSaveThread::Initialize, m_pkSaveRecordThread.
Referenced by Initialize.
void RaceServer::RaceThreadFinialize()
References SeRaceRecordSaveThread::Finialize, m_pkSaveRecordThread, SeRaceRecordSaveThread::Update.
Referenced by Finialize.
void RaceServer::RaceThreadUpdate()
References m_pkSaveRecordThread, SeRaceRecordSaveThread::Update.
Referenced by Update.
void RaceServer::RaceLinkUserSync(DWord dwPlayerID, DWord dwStateID)
References SendRN_RaceLinkUserSync.
Referenced by OnNetDisconnect, ProcessCR_RaceValidate.
RaceServer::RaceServer(void)
RaceServer::~RaceServer(void)
bool RaceServer::Initialize(void)
void RaceServer::Update(void)
void RaceServer::Finialize(void)
void RaceServer::ShowConsoleTitle(int iDTime)
SeServerActionResult RaceServer::ExecuteAction(SeServerActionIndex eActionIndex)
virtual void RaceServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
virtual void RaceServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
virtual void RaceServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
virtual void RaceServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
virtual void RaceServer::OnNetUdpAccept(int iID, int iListtenPort, const char *pcIP, int iPort)
virtual void RaceServer::OnNetUdpRecv(int iID, void *pkData, int iSize)
virtual void RaceServer::OnNetUdpDisconnect(int iID)
bool RaceServer::SendRC_EncryptKey(const char *abyEncryptKey, DWord dwVersion, void *pkReceiver=NULL)
bool RaceServer::SendRC_HeartBeat(void *pkReceiver=NULL)
bool RaceServer::SendRC_ValidateRet(bool bReturn, void *pkReceiver=NULL)
bool RaceServer::SendRC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, int iSize, const char *acMessage, void *pkReceiver=NULL)
bool RaceServer::SendRC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, int iSize, std::vector< char > &acMessage, void *pkReceiver=NULL)
bool RaceServer::SendRC_RoomPlayerBaseInfo(DWord dwMapID, SeRaceModel eRaceModel, int iNum, const SeMatchSelPlayerInfo *akPlayerInfo, void *pkReceiver=NULL)
bool RaceServer::SendRC_RoomPlayerBaseInfo(DWord dwMapID, SeRaceModel eRaceModel, int iNum, std::vector< SeMatchSelPlayerInfo > &akPlayerInfo, void *pkReceiver=NULL)
bool RaceServer::SendRC_RacePack(DWord dwPackIndex, int iSize, const char *acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_RacePack(DWord dwPackIndex, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_RaceStream(int iSize, const char *acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_RaceStream(int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_RacePlayerLoadEnd(int iSeat, DWord dwRate, void *pkReceiver=NULL)
bool RaceServer::SendRC_BeginSelectHero(DWord dwCamp, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelHeroMessage(SeSelHeroMsgType eMessageType, DWord dwHeroID, bool bDreamHero, int iDecMoney, DWord dwOrgPlayerID, DWord dwDstPlayerID, void *pkReceiver=NULL)
bool RaceServer::SendRC_ReconResult(SeReconResultType eResult, int iData, void *pkReceiver=NULL)
bool RaceServer::SendRC_ReconPack(int iOffset, int iSize, const char *acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_ReconPack(int iOffset, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_ViewPack(int iOffset, int iSize, const char *acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_ViewPack(int iOffset, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_ViewResult(SeViewResultType eResult, int iData, void *pkReceiver=NULL)
bool RaceServer::SendRC_ViewPlayerInfo(int iNum, const SePlayerInfoSeat *akSeat, void *pkReceiver=NULL)
bool RaceServer::SendRC_ViewPlayerInfo(int iNum, std::vector< SePlayerInfoSeat > &akSeat, void *pkReceiver=NULL)
bool RaceServer::SendRC_Talk(SeTalkType eType, DWord dwSrcID, int iSize, const char *acMsg, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelPetList(int iNum, const int *akPetID, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelPetList(int iNum, std::vector< int > &akPetID, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelHeroList(int iNum, const SeSelHeroInfo *akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelHeroList(int iNum, std::vector< SeSelHeroInfo > &akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelHorseList(int iNum, const int *akHorseID, void *pkReceiver=NULL)
bool RaceServer::SendRC_SelHorseList(int iNum, std::vector< int > &akHorseID, void *pkReceiver=NULL)
bool RaceServer::SendRC_PingRet(DWord dwPackIndex, void *pkReceiver=NULL)
bool RaceServer::SendRC_GetHeroInfoRet(int iSize, const char *acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_GetHeroInfoRet(int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool RaceServer::SendRC_RaceEndNotifyDown(const char *acURLBase, const char *acRaceID, void *pkReceiver=NULL)
bool RaceServer::SendRC_RaceGoldExpPlus(int RaceGold, int RaceExp, void *pkReceiver=NULL)
bool RaceServer::SendRC_SetEquipSetAck(int iResult, void *pkReceiver=NULL)
bool RaceServer::SendRC_SetAvatarAck(int iResult, void *pkReceiver=NULL)
bool RaceServer::SendRC_SeatScoreNtf(const SeSeatScore *scores, void *pkReceiver=NULL)
bool RaceServer::SendRC_SeatScoreNtf(std::vector< SeSeatScore > &scores, void *pkReceiver=NULL)
bool RaceServer::SendRCData(void *pkData, int iSize, void *pkReceiver)
bool RaceServer::ProcessCRData(void *pkData, int iSize, void *pkSender=NULL)
bool RaceServer::PreProcessCR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_HeartPackage(SeCR_HeartPackage *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_RaceValidate(SeCR_RaceValidate *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_RaceLoadEnd(SeCR_RaceLoadEnd *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_RaceCmd(SeCR_RaceCmd *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_RaceLeave(SeCR_RaceLeave *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_RaceEndRace(SeCR_RaceEndRace *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_RaceEndGuanqia(SeCR_RaceEndGuanqia *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_SelHeroChoiceHero(SeCR_SelHeroChoiceHero *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_SelHeroCancelHero(SeCR_SelHeroCancelHero *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_SelHeroPrapared(SeCR_SelHeroPrapared *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_RaceReportSyn(SeCR_RaceReportSyn *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_Talk(SeCR_Talk *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_RaceRobotLogin(SeCR_RaceRobotLogin *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_Ping(SeCR_Ping *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_BuyRaceItem(SeCR_BuyRaceItem *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_GetHeroInfo(SeCR_GetHeroInfo *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_ReplayReport(SeCR_ReplayReport *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_SetEquipSetReq(SeCR_SetEquipSetReq *pkData, int iSize, void *pkSender)
void RaceServer::ProcessCR_SetAvatarReq(SeCR_SetAvatarReq *pkData, int iSize, void *pkSender)
bool RaceServer::SendRM_Register(DWord dwServerID, DWord dwAreaID, const SeNetAddr &kAddrToMatch, const SeNetAddr &kAddrToMatchUdp, int iRegisterCount, bool bOpen, void *pkReceiver=NULL)
bool RaceServer::SendRM_HeartPackage(DWord dwCurrRaceNum, void *pkReceiver=NULL)
bool RaceServer::SendRM_ValidatePlayerInfoRet(DWord dwSessionID, const SeMatchValidateResult &eResult, void *pkReceiver=NULL)
bool RaceServer::SendRM_CommRaceMsg(DWord dwMatchSession, const SeRaceSvrCommMsg &eMsg, DWord dwParam, int iParam, void *pkReceiver=NULL)
bool RaceServer::SendRM_RaceGetCardInfo(DWord dwSession, DWord dwPlayerID, DWord dwHeroTypeID, DWord dwMapTypeID, void *pkReceiver=NULL)
bool RaceServer::SendRM_UpdateMisc(DWord dwPlayerID, DWord dwSession, const SeMMMiscType &eType, int iValue, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool RaceServer::SendRM_RaceEndReport(DWord dwMatchSession, DWord dwTime, DWord dwMapID, const SeMatchRaceType &eMatchType, int iNum, const SeWSRaceSendInfo *akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_RaceEndReport(DWord dwMatchSession, DWord dwTime, DWord dwMapID, const SeMatchRaceType &eMatchType, int iNum, std::vector< SeWSRaceSendInfo > &akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_RaceEndGuanqia(DWord dwMatchSession, DWord dwTime, DWord dwMapID, int iNum, const SeWSGuanqiaSendInfo *akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_RaceEndGuanqia(DWord dwMatchSession, DWord dwTime, DWord dwMapID, int iNum, std::vector< SeWSGuanqiaSendInfo > &akInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_MatchRoomLoadInfo(DWord dwSession, int iNum, const SeMatchRoomLoadInfo *akLoadInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_MatchRoomLoadInfo(DWord dwSession, int iNum, std::vector< SeMatchRoomLoadInfo > &akLoadInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_RefreshConfigInfo(bool bOpen, void *pkReceiver=NULL)
bool RaceServer::SendRM_ReconQuerySuccess(DWord dwRoomID, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iSeat, int iOffset, DWord dwFrame, void *pkReceiver=NULL)
bool RaceServer::SendRM_ReconQueryFail(const SeReconQueryFailReason &eReason, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, void *pkReceiver=NULL)
bool RaceServer::SendRM_ViewQuerySuccess(DWord dwSession, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iViewDelay, void *pkReceiver=NULL)
bool RaceServer::SendRM_ViewQueryFail(const SeViewQueryFailReason &eReason, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, void *pkReceiver=NULL)
bool RaceServer::SendRM_ReconViewValid(DWord dwSession, DWord dwPlayerID, DWord dwKey, const SeRaceValidType &eValidType, void *pkReceiver=NULL)
bool RaceServer::SendRM_ReLoadRoomInfoList(int iNum, const SeReLoadRoomInfo *akRoomInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_ReLoadRoomInfoList(int iNum, std::vector< SeReLoadRoomInfo > &akRoomInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_MatchRaceLoad(DWord dwRoomSession, DWord dwMapID, void *pkReceiver=NULL)
bool RaceServer::SendRM_RaceBuy(DWord dwSession, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool RaceServer::SendRM_AddIncompleteRace(DWord dwRoomSession, int iSeat, DWord dwPlayerID, void *pkReceiver=NULL)
bool RaceServer::SendRM_RemoveIncompleteRace(DWord dwRoomSession, void *pkReceiver=NULL)
bool RaceServer::SendRM_UpdateIncompleteRace(DWord dwRoomSession, int iSeat, bool bSeat, void *pkReceiver=NULL)
bool RaceServer::SendRM_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, const SeSeatBaseInfo *oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool RaceServer::SendRM_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, std::vector< SeSeatBaseInfo > &oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool RaceServer::SendRMData(void *pkData, int iSize, void *pkReceiver)
bool RaceServer::ProcessMRData(void *pkData, int iSize, void *pkSender=NULL)
bool RaceServer::PreProcessMR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_RegisterRet(SeMR_RegisterRet *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_HeartPackageRet(SeMR_HeartPackageRet *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_ValidatePlayerInfo(SeMR_ValidatePlayerInfo *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_PlayerModifyInfo(SeMR_PlayerModifyInfo *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_UpdateMiscInfo(SeMR_UpdateMiscInfo *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_ReconQuery(SeMR_ReconQuery *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_ViewQuery(SeMR_ViewQuery *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_ViewValidOKRet(SeMR_ViewValidOKRet *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_ValidFailRet(SeMR_ValidFailRet *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_RaceBuyRet(SeMR_RaceBuyRet *pkData, int iSize, void *pkSender)
void RaceServer::ProcessMR_ReconPLayerName(SeMR_ReconPLayerName *pkData, int iSize, void *pkSender)
bool RaceServer::SendRWCS_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_HeartPackageRet(void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceRecord(const Byte *rID, int iNum, const char *raceDat, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceRecord(std::vector< Byte > &rID, int iNum, std::vector< char > &raceDat, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceEnd(const Byte *rID, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceEnd(std::vector< Byte > &rID, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceStart(const Byte *rID, int iNum, const SePlayerInfoSeat *racePlayerSeatInfo, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceStart(std::vector< Byte > &rID, int iNum, std::vector< SePlayerInfoSeat > &racePlayerSeatInfo, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceDetailInfoSync(int num, const SeRaceDetailInfo *akRaceDetailInfo, void *pkReceiver=NULL)
bool RaceServer::SendRWCS_RaceDetailInfoSync(int num, std::vector< SeRaceDetailInfo > &akRaceDetailInfo, void *pkReceiver=NULL)
bool RaceServer::SendRWCSData(void *pkData, int iSize, void *pkReceiver)
bool RaceServer::ProcessWCSRData(void *pkData, int iSize, void *pkSender=NULL)
bool RaceServer::PreProcessWCSR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessWCSR_Register(SeWCSR_Register *pkData, int iSize, void *pkSender)
void RaceServer::ProcessWCSR_HeartPackage(SeWCSR_HeartPackage *pkData, int iSize, void *pkSender)
bool RaceServer::PushRSC_RaceInit(DWord dwRaceIndex, TeMD5 &rkRaceID, int iMapID, int iSeatInfo, VRacePlayer &rkVRacePlayer)
bool RaceServer::PushRSC_RaceStream(DWord dwRaceIndex, TeMD5 &rkRaceID, char *pcData, int iDataSize)
bool RaceServer::PushRSC_PlayerLeave(DWord dwRaceIndex, TeMD5 &rkRaceID, int iSeat)
bool RaceServer::PushRSC_PlayerRelink(DWord dwRaceIndex, TeMD5 &rkRaceID, int iSeat, HSock &rkSock)
bool RaceServer::PushRSC_RaceOver(DWord dwRaceIndex, TeMD5 &rkRaceID)
bool RaceServer::PushRSC_RaceStart(DWord dwRaceIndex, TeMD5 &rkRaceID, VRacePlayer &rkVRacePlayer)
bool RaceServer::PushRSC_GetHeroInfo(DWord dwRaceIndex, TeMD5 &rkRaceID, int iSeat)
bool RaceServer::PushRSC_SetRaceIncmpState(DWord dwRaceIndex, TeMD5 &rkRaceID, bool bIncmp)
void RaceServer::ProcessRCR(void *pkData, int iSize)
void RaceServer::ProcessRC_RaceStream(void *pkData, int iSize)
void RaceServer::ProcessRC_RaceEnd(void *pkData, int iSize)
void RaceServer::ProcessRC_RaceError(void *pkData, int iSize)
void RaceServer::ProcessRC_RaceInitFail(void *pkData, int iSize)
void RaceServer::ProcessRC_RaceOpr(void *pkData, int iSize)
void RaceServer::ProcessRC_RaceSvrModelPack(void *pkData, int iSize)
void RaceServer::ProcessRC_ThreadOverTime(void *pkData, int iSize)
void RaceServer::ProcessRC_GetAchievement(void *pkData, int iSize)
void RaceServer::ProcessRC_AchievementCounts(void *pkData, int iSize)
void RaceServer::ProcessRC_Command(void *pkData, int iSize)
int RaceServer::GetDebugLevel(void)
void RaceServer::SetDebugLevel(int iLevel)
int RaceServer::GetRacePackTime(void)
char* RaceServer::GetGameLogFilePath()
int RaceServer::GetRaceServiceNum(void)
int RaceServer::GetRacePrintTime(void)
int RaceServer::GetMaxPacketSize(void)
int RaceServer::GetServerModePackTime(void)
int RaceServer::GetMaxReconTime(void)
bool RaceServer::IsTestRobotMode()
int RaceServer::GetServerID(void)
int RaceServer::GetAreaID(void)
DWord RaceServer::GetServerTime(void)
int RaceServer::RandInt(void)
void RaceServer::OnSendMatchRoomLoadInfo(DWord dwSession, VRacePlayer &rkVRacePlayer)
void RaceServer::OnSendPlayerRaceStream(HSock &rkPlayerSock, bool bMustSend, const char *pkData, int iDataSize)
void RaceServer::SendPlayer_ReconNoticePlayerJoin(HSock &rkPlayerSock, int iSeat, int iSize, const char *sName)
void RaceServer::DelWaitRobot(DWord dwPlayerID)
void RaceServer::UpdateWaitRobot()
void RaceServer::StartRobotGame(const MapInfoTable *pkMapRes, VTestRobot &rakRobot)
bool RaceServer::PushRaceServiceMsg(DWord dwThreadIndex, void *pkData, int iSize)
bool RaceServer::PushRSMsg(void *pkData, int iSize)
bool RaceServer::SendRN_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
bool RaceServer::SendRN_HeartPackage(void *pkReceiver=NULL)
bool RaceServer::SendRN_RaceLinkUserSync(DWord dwPlayerID, DWord dwStateID, void *pkReceiver=NULL)
bool RaceServer::SendRNData(void *pkData, int iSize, void *pkReceiver)
bool RaceServer::ProcessNRData(void *pkData, int iSize, void *pkSender=NULL)
bool RaceServer::PreProcessNR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessNR_RegisterRet(SeNR_RegisterRet *pkData, int iSize, void *pkSender)
void RaceServer::ProcessNR_HeartPackageRet(SeNR_HeartPackageRet *pkData, int iSize, void *pkSender)
bool RaceServer::SendRW_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
bool RaceServer::SendRW_HeartPackage(void *pkReceiver=NULL)
bool RaceServer::SendRWData(void *pkData, int iSize, void *pkReceiver)
bool RaceServer::ProcessWRData(void *pkData, int iSize, void *pkSender=NULL)
bool RaceServer::PreProcessWR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessWR_RegisterRet(SeWR_RegisterRet *pkData, int iSize, void *pkSender)
void RaceServer::ProcessWR_HeartPackageRet(SeWR_HeartPackageRet *pkData, int iSize, void *pkSender)
bool RaceServer::SendRBL_UpdateScore(DWord dwPlayerID, const MatchType &eMatchType, int score, bool win, void *pkReceiver=NULL)
bool RaceServer::SendRBL_AwardItemNtf(DWord dwPlayerID, int iNum, const SeAwardItem *awards, void *pkReceiver=NULL)
bool RaceServer::SendRBL_AwardItemNtf(DWord dwPlayerID, int iNum, std::vector< SeAwardItem > &awards, void *pkReceiver=NULL)
bool RaceServer::SendRBL_DecRespawnItemNtf(DWord dwPlayerID, void *pkReceiver=NULL)
bool RaceServer::SendRBL_SetEquipSetNtf(DWord dwPlayerID, Byte byIndex, void *pkReceiver=NULL)
bool RaceServer::SendRBL_SetRaceMapHeroNtf(DWord dwPlayerID, DWord dwMapID, DWord dwHeroID, DWord dwWinCounts, void *pkReceiver=NULL)
bool RaceServer::SendRBL_SetAvatarNtf(DWord dwPlayerID, DWord dwHeroID, DWord dwItemID, void *pkReceiver=NULL)
bool RaceServer::SendRBL_SelectHeroReq(DWord dwPlayerID, DWord dwHeroID, void *pkReceiver=NULL)
bool RaceServer::SendRBL_UserRaceMapNtf(DWord dwPlayerID, const SeRaceEndArenaDetailInfo &akRaceMaplInfo, void *pkReceiver=NULL)
bool RaceServer::SendRBL_RaceEndArenaBaseInfoSync(DWord dwPlayerID, const SeRaceEndArenaBaseInfo &akRaceBaselInfo, void *pkReceiver=NULL)
bool RaceServer::SendRBLData(void *pkData, int iSize, void *pkReceiver)
bool RaceServer::ProcessBLRData(void *pkData, int iSize, void *pkSender=NULL)
bool RaceServer::PreProcessBLR(void *pkData, int iSize, void *pkSender)
void RaceServer::ProcessBLR_SelectHeroAck(SeBLR_SelectHeroAck *pkData, int iSize, void *pkSender)
void RaceServer::OnPlayerConnected(SeConnect *pkConnect, const char *pcIP, int iPort)
void RaceServer::OnPlayerDisconnect(HSock rkSock)
void RaceServer::ClearAllPlayerConn()
SeConnect* RaceServer::GetConnectByID(DWord dwPlayerID)
void RaceServer::GetServerRunState(int &riSvrModeNum, int &riNormalNum)
int RaceServer::GetConnectNum()
void RaceServer::DelConnectByID(DWord dwPlayerID)
SeConnect* RaceServer::GetConnectBySock(const HSock &rkSock)
bool RaceServer::ReLoadServerAddr(const char *pcFile)
bool RaceServer::LoadConfig(const char *pcFile)
void RaceServer::ReLoadConfig()
bool RaceServer::LoadRSTempConfig(const char *pcFile, SeRaceConfig &rkRSConfig)
bool RaceServer::IsMSReady(void)
DWord RaceServer::GetMSID()
SeRaceConfig RaceServer::GetRaceConfig()
void RaceServer::SaveRecord(SeRace *pRace)
const TWCSViewArray& RaceServer::GetWCSView() const
References m_vWCSView.
MapWCSConnect& RaceServer::GetWCSConnectMap()
References m_kWCSConnect.
void RaceServer::RaceThreadInitialize()
void RaceServer::RaceThreadFinialize()
void RaceServer::RaceThreadUpdate()
void RaceServer::RaceLinkUserSync(DWord dwPlayerID, DWord dwStateID)
bool RaceServer::InitializeNet(void)
References SeNetAddr::acIP, SeRaceConfig::bTcpClient, CLIENT_BUFFER_SIZE, SeNetAddr::iPort, SeRaceConfig::kAddrToPlayer, SeRaceConfig::kAddrToPlayerUdp, SeRaceConfig::kAddrToWCS, m_kConfig, m_kNetMgr, m_kUdpMgr, SeLogError, SeLogInfo, SERVER_BUFFER_SIZE.
Referenced by Initialize.
bool RaceServer::InitializeNetEx(void)
References SeVirtConnMgr::AddServerConn, g_kVirtConnMgr, SeConfig::GetNetAddr, SeVirtConnMgr::Initialize, SeConfig::Load, m_kNetMgr, m_pkNSConn, m_pkWSConn, SeLogError, sendHeartPack, sendRegPack, SSI_NS, SSI_WS.
Referenced by Initialize.
bool RaceServer::InitializeRaceService(void)
References RaceService::Initialize, SeThreadMsgMgr::Initialize, m_iRaceServiceNum, m_kThreadMsgMgr, m_pakRaceService, SeLogInfo, CPerformanceTimingMgr::SetInstance, RaceService::SetPerformaceMgr, RaceService::SetThreadIndex.
Referenced by Initialize.
void RaceServer::ParseSetupVal(VIntVec &rkVec, const char *pcValue, bool bNum=false)
References GetStr2ID, MemCpy, StrCpy.
void RaceServer::UpdateMSState(void)
References SeServerData::bRegistered, ConnectToMS, GetServerTime, SeServerData::kSock, m_kMSData, RegisterToMS.
Referenced by Update.
void RaceServer::CheckFreq(void)
References CHECK_FREQ_TIME, SeConnect::dwPackCount, SeConnect::dwPlayerID, m_dwCurTime, m_dwFreqTime, m_kAllConnect, SeLogInfo.
Referenced by Update.
void RaceServer::ConnectToMS(void)
References SeNetAddr::acIP, SeServerData::bConnecting, SeNetAddr::iPort, SeRaceConfig::kMSServer, m_kConfig, m_kMSData, m_kNetMgr, SeLogError, SERVER_BUFFER_SIZE.
Referenced by UpdateMSState.
void RaceServer::RegisterToMS(void)
References SeRaceConfig::bOpen, SeRaceConfig::dwAreaID, SeServerData::dwRegisterTime, SeRaceConfig::dwServerID, SeRaceConfig::kAddrToPlayer, SeRaceConfig::kAddrToPlayerUdp, m_dwCurTime, m_iRegisterCount, m_kConfig, m_kMSData, RECONNECT_TIME, SeLogError, SendRM_Register.
Referenced by UpdateMSState.
void RaceServer::SetMSReady(bool bReady)
References m_bMSReady.
Referenced by ProcessMR_RegisterRet.
void RaceServer::DisconnectPlayer(SeConnect *pkConn)
References SeRaceConfig::bTcpClient, SeConnect::kSock, m_kConfig, m_kNetMgr, m_kUdpMgr.
Referenced by CheckConnect, ClearAllPlayerConn, OnPlayerDisconnect, ProcessMR_ValidFailRet.
void RaceServer::CheckConnect()
References DisconnectPlayer, SeConnect::dwLastRecvTime, SeConnect::dwPlayerID, SeConnect::dwStateTime, SeConnect::eState, GetID2Str, GetServerID, SeRaceConfig::iClientHeartBeatTime, m_dwCurTime, m_kAllConnect, m_kConfig, SCS_UNKOWN, SeLogError.
Referenced by Update.
void RaceServer::UpdateRSMsg(void)
References SeMsgData::abyData, SeMsgData::iSize, m_kThreadMsgMgr, SeThreadMsgMgr::PopMsg, ProcessRCR.
Referenced by Update.
void RaceServer::UpdateHeartPackage(void)
References GetServerTime, UpdateMSHeartPackage.
Referenced by Update.
void RaceServer::UpdateMSHeartPackage(void)
References SeServerData::dwHeartPackageTime, g_kRaceMgr, SeRaceMgr::GetCurrentRaceNum, GetServerTime, SeServerData::kSock, m_kMSData, m_kNetMgr, SeLogError, SendRM_HeartPackage.
Referenced by UpdateHeartPackage.
void RaceServer::UpdateRSConfig(void)
References GetServerTime, ReLoadConfig, ReLoadServerAddr.
Referenced by Update.
void RaceServer::UpdateSaveThreadUpdateTime(void)
References GetServerTime, m_akThreadTime, SPrintf, Stat_TIME_THREAD_NUM.
Referenced by Update.
void RaceServer::OnWCSDisconnect(const HSock &rkSock)
References g_kRaceMgr, SeWCSView::kWCSSock, m_vWCSView, SeRaceMgr::RemoveWCSView.
Referenced by OnNetDisconnect.
void RaceServer::WriteToLogFile(const char *pcLogName, const char *pcInfo, int size)
Referenced by SendRCData.
bool RaceServer::InitializeNet(void)
bool RaceServer::InitializeNetEx(void)
bool RaceServer::InitializeRaceService(void)
void RaceServer::ParseSetupVal(VIntVec &rkVec, const char *pcValue, bool bNum=false)
void RaceServer::UpdateMSState(void)
void RaceServer::CheckFreq(void)
void RaceServer::ConnectToMS(void)
void RaceServer::RegisterToMS(void)
void RaceServer::SetMSReady(bool bReady)
void RaceServer::DisconnectPlayer(SeConnect *pkConn)
void RaceServer::CheckConnect()
void RaceServer::UpdateRSMsg(void)
void RaceServer::UpdateHeartPackage(void)
void RaceServer::UpdateMSHeartPackage(void)
void RaceServer::UpdateRSConfig(void)
void RaceServer::UpdateSaveThreadUpdateTime(void)
void RaceServer::OnWCSDisconnect(const HSock &rkSock)
void RaceServer::WriteToLogFile(const char *pcLogName, const char *pcInfo, int size)