SeMemPool
char SeMemPool::m_acName[64][64]
Referenced by ExtendPool, SeMemPool.
int SeMemPool::m_iEleSize
Referenced by ExtendPool, GetAllocSize, IsValid, NewEle, SeMemPool.
int SeMemPool::m_iBaseEles
Referenced by ExtendPool, SeMemPool.
int SeMemPool::m_iAddEles
Referenced by ExtendPool, SeMemPool.
int SeMemPool::m_iTotalSize
Referenced by ExtendPool, GetTotalSize, SeMemPool.
int SeMemPool::m_iAllocEles
Referenced by DelEle, GetAllocSize, NewEle, Reset.
int SeMemPool::m_iAllocMaxEles
Referenced by GetAllocMaxEles, NewEle, Reset.
void* SeMemPool::m_pkFreeFirst
Referenced by DelEle, ExtendPool, NewEle, Reset.
SeHeadList SeMemPool::m_kHeadList
Referenced by Clear, ExtendPool, Reset.
SIZE_T SeMemPool::m_stMagicBegin
Referenced by IsValid, NewEle, SeMemPool.
SIZE_T SeMemPool::m_stMagicEnd
Referenced by IsValid, NewEle, SeMemPool.
Es::NormalLock SeMemPool::m_kLock
Referenced by Clear, DelEle, ExtendPool, IsValid, NewEle, Reset, SeMemPool, ~SeMemPool.
NotifyMempoolAlloc SeMemPool::m_fAllocCallBack
Referenced by ExtendPool, RegisterAllocCallBack.
SeMemPool::SeMemPool(int iEleSize, int iBaseEles, int iAddEles, const char *acName)
References ExtendPool, m_acName, m_iAddEles, m_iBaseEles, m_iEleSize, m_iTotalSize, m_kLock, m_stMagicBegin, m_stMagicEnd, Reset.
SeMemPool::~SeMemPool(void)
References Clear, m_kLock.
void * SeMemPool::NewEle(void)
References ExtendPool, m_iAllocEles, m_iAllocMaxEles, m_iEleSize, m_kLock, m_pkFreeFirst, m_stMagicBegin, m_stMagicEnd.
void SeMemPool::DelEle(void *pkEle)
References m_iAllocEles, m_kLock, m_pkFreeFirst.
bool SeMemPool::IsValid(void *pkEle)
References m_iEleSize, m_kLock, m_stMagicBegin, m_stMagicEnd.
int SeMemPool::GetAllocSize(void)
References m_iAllocEles, m_iEleSize.
int SeMemPool::GetTotalSize(void)
References m_iTotalSize.
int SeMemPool::GetAllocMaxEles(void)
References m_iAllocMaxEles.
void SeMemPool::Clear(void)
References m_kHeadList, m_kLock, SeMemPool::SeHeadList::pkNext, Reset.
Referenced by ~SeMemPool.
void SeMemPool::RegisterAllocCallBack(NotifyMempoolAlloc fCallBack)
References m_fAllocCallBack.
bool SeMemPool::ExtendPool(void)
References SeMemPool::SeHeadList::acData, SeMemPool::SeHeadList::iSize, m_acName, m_fAllocCallBack, m_iAddEles, m_iBaseEles, m_iEleSize, m_iTotalSize, m_kHeadList, m_kLock, m_pkFreeFirst, SeMemPool::SeHeadList::pkNext, SeMemPool::SeHeadList::pkPrev.
Referenced by NewEle, SeMemPool.
void SeMemPool::Reset(void)
References m_iAllocEles, m_iAllocMaxEles, m_kHeadList, m_kLock, m_pkFreeFirst, SeMemPool::SeHeadList::pkNext, SeMemPool::SeHeadList::pkPrev.
Referenced by Clear, SeMemPool.