CShop
SHOPITEMMAP CShop::m_ShopItemMap
Referenced by BuyItem, CurrencyBuyItem_Diamond, CurrencyBuyItem_Gold, GetGMItem, GMModiItem, ParasLineItem, Update, ~CShop.
ItemSaveThread * CShop::pSaveThread
Referenced by CShop, GetSaveThread, ~CShop.
bool CShop::bolOper
Referenced by CShop, GMModiItem, Update.
Es::NormalLock * CShop::m_pSaveLock
Referenced by BuyItem, CShop, CurrencyBuyItem_Diamond, CurrencyBuyItem_Gold, GetGMItem, GMModiItem, LoadGmItems, Update, ~CShop.
CShop::CShop()
References bolOper, m_pSaveLock, pSaveThread.
CShop::~CShop()
References m_pSaveLock, m_ShopItemMap, pSaveThread, ItemSaveThread::SaveGmItem.
void CShop::Update(DWord dwCurTime)
References bolOper, GetSaveThread, m_pSaveLock, m_ShopItemMap, ItemSaveThread::SaveGmItem, ItemSaveThread::SetMap.
Referenced by WorldServer::Update.
SeItemResult CShop::BuyItem(SePlayer *pPlayer, uint32_t uiShopID, uint32_t ItemCount=1)
References CItemMgr::AddItem, CMT_GOLD, RackTableMgr::Get, TownItemTableMgr::Get, SePlayer::GetGold, CItemMgr::GetItemCountByID, SePlayer::GetItemMgr, RackTableMgr::GetRackTable, TownItemTableMgr::GetTownItemTable, ITEM_RESULT_SUCCESS, ITEM_RESULT_TABLE_ERROR, ITEM_SERVER_INNER_ERROR, ITEM_SHOP_HAVE_NOSTOCK, ITEM_SHOP_HAVE_TOOMORE, ITEM_SHOP_HAVE_UNLOAD, ITEM_SHOP_NOT_ENOUGH_MONEY, ITEM_SHOP_NOTEXISTITEM, ITEM_SHOP_NUMBER_ERROR, m_pSaveLock, m_ShopItemMap, SePlayer::NotifyOwnMoney, RACK_FEATURE_XIAJIA, SePlayer::SetGold, RackTable::uiItemID, RackTable::uiPrice1, SePlayer::UpdateCharMisc.
SeItemResult CShop::GMModiItem(SePlayer *pPlayer, uint32_t ItemCount, ShopItem gmitems[])
References bolOper, ShopItem::dwFeature, ShopItem::dwItemID, ShopItem::dwPrice, ShopItem::dwResetCount, ShopItem::dwShopID, ShopItem::dwSingleCount, ShopItem::dwStockCount, ShopItem::fDisco, RackTableMgr::Get, TownItemTableMgr::Get, RackTableMgr::GetRackTable, TownItemTableMgr::GetTownItemTable, ITEM_RESULT_SUCCESS, ITEM_RESULT_TABLE_ERROR, ITEM_SERVER_INNER_ERROR, ITEM_SHOP_NOTEXISTITEM, ITEM_SHOP_NUMBER_ERROR, m_pSaveLock, m_ShopItemMap.
Referenced by BlockServer::ProcessWBL_ShopItemGM.
int32_t CShop::GetGMItem(SePlayer *pPlayer, uint32_t ShopID, ShopItem &item)
References ShopItem::dwFeature, ShopItem::dwItemID, ShopItem::dwPrice, ShopItem::dwResetCount, ShopItem::dwShopID, ShopItem::dwSingleCount, ShopItem::dwStockCount, ShopItem::fDisco, m_pSaveLock, m_ShopItemMap.
Referenced by BlockServer::ProcessWBL_GetItemGM.
ItemSaveThread* CShop::GetSaveThread()
References pSaveThread.
Referenced by Update.
void CShop::ParasItemString(char *pSring, std::string strResult[], char *pToken, int32_t iNum)
Referenced by ParasLineItem.
void CShop::ParasLineItem(char *pData)
References CShopItem::fDiscope, m_ShopItemMap, ParasItemString, CShopItem::uiFeature, CShopItem::uiID, CShopItem::uiItemID, CShopItem::uiPrice, CShopItem::uiResetCount, CShopItem::uiRestrictionsCount, CShopItem::uiStockCount.
Referenced by LoadGmItems.
bool CShop::LoadGmItems()
References g_kWorldServer, WorldServer::GetConfig, SeWorldConfig::ItemSaveName, m_pSaveLock, ParasLineItem.
Referenced by WorldServer::LoadConfig.
SeItemResult CShop::CurrencyBuyItem(SePlayer *pPlayer, uint32_t types, uint32_t uiShopID, uint32_t ItemCount)
References CurrencyBuyItem_Diamond, CurrencyBuyItem_Gold, ECurrencyType_Diamond, ECurrencyType_Gold, ITEM_RESULT_SUCCESS.
Referenced by BlockServer::ProcessWBL_BuyShopItem.
SeItemResult CShop::CurrencyBuyItem_Gold(SePlayer *pPlayer, uint32_t types, uint32_t uiShopID, uint32_t ItemCount)
References CItemMgr::AddItem, CheckSoleItem, CMT_GOLD, RackTableMgr::Get, TownItemTableMgr::Get, SePlayer::GetGold, CItemMgr::GetItemCountByID, SePlayer::GetItemMgr, RackTableMgr::GetRackTable, TownItemTableMgr::GetTownItemTable, ITEM_ALREADY_HAVE, ITEM_RESULT_SUCCESS, ITEM_RESULT_TABLE_ERROR, ITEM_SERVER_INNER_ERROR, ITEM_SHOP_HAVE_NOSTOCK, ITEM_SHOP_HAVE_TOOMORE, ITEM_SHOP_HAVE_UNLOAD, ITEM_SHOP_NOT_ENOUGH_MONEY, ITEM_SHOP_NOTEXISTITEM, ITEM_SHOP_NUMBER_ERROR, m_pSaveLock, m_ShopItemMap, SePlayer::NotifyOwnMoney, ProcessHeroItem, RACK_FEATURE_XIAJIA, SePlayer::SetGold, TownItemTable::uiClass, RackTable::uiItemID, RackTable::uiPrice2, SePlayer::UpdateCharMisc.
Referenced by CurrencyBuyItem.
SeItemResult CShop::CurrencyBuyItem_Diamond(SePlayer *pPlayer, uint32_t types, uint32_t uiShopID, uint32_t ItemCount)
References CItemMgr::AddItem, CheckSoleItem, CMT_DIAMOND, RackTable::fDiscount, RackTableMgr::Get, TownItemTableMgr::Get, SePlayer::GetDiamond, CItemMgr::GetItemCountByID, SePlayer::GetItemMgr, RackTableMgr::GetRackTable, TownItemTableMgr::GetTownItemTable, ITEM_ALREADY_HAVE, ITEM_RESULT_SUCCESS, ITEM_RESULT_TABLE_ERROR, ITEM_SERVER_INNER_ERROR, ITEM_SHOP_HAVE_NOSTOCK, ITEM_SHOP_HAVE_TOOMORE, ITEM_SHOP_HAVE_UNLOAD, ITEM_SHOP_NOT_ENOUGH_MONEY, ITEM_SHOP_NOTEXISTITEM, ITEM_SHOP_NUMBER_ERROR, m_pSaveLock, m_ShopItemMap, SePlayer::NotifyOwnMoney, ProcessHeroItem, RACK_FEATURE_XIAJIA, SePlayer::SetDiamond, TownItemTable::uiClass, RackTable::uiItemID, RackTable::uiPrice1, SePlayer::UpdateCharMisc.
Referenced by CurrencyBuyItem.
void CShop::ProcessHeroItem(SePlayer *pPlayer, uint32_t uiItemID)
References EUHS_SHOP, GetHeroID, SePlayer::getHeroMgr, SeUnlockHeroBaseInfo::heroID, SeUnlockHeroBaseInfo::mark, HeroMgr::unlockHero.
Referenced by CurrencyBuyItem_Diamond, CurrencyBuyItem_Gold.
DWord CShop::GetHeroID(uint32_t uiItemID)
References AvatarTableMgr::Get, AvatarTableMgr::GetAvatarTable, AvatarTable::uiHeroID.
Referenced by ProcessHeroItem.
bool CShop::CheckSoleItemType(int32_t iclass)
References ESoleItemType_Hero, ESoleItemType_Skin, ESoleItemType_Weapon.
Referenced by CheckSoleItem.
bool CShop::CheckSoleItem(SePlayer *pPlayer, int32_t iclass, uint32_t uiItemID)
References CItemMgr::CheckOwnerItem, CheckSoleItemType, SePlayer::GetItemMgr.
Referenced by CurrencyBuyItem_Diamond, CurrencyBuyItem_Gold.
CShop::CShop()
CShop::~CShop()
void CShop::Update(DWord dwCurTime)
SeItemResult CShop::BuyItem(SePlayer *pPlayer, uint32_t uiShopID, uint32_t ItemCount=1)
SeItemResult CShop::GMModiItem(SePlayer *pPlayer, uint32_t ItemCount, ShopItem gmitems[])
int32_t CShop::GetGMItem(SePlayer *pPlayer, uint32_t ShopID, ShopItem &item)
ItemSaveThread* CShop::GetSaveThread()
References pSaveThread.
void CShop::ParasItemString(char *pSring, std::string strResult[], char *pToken, int32_t iNum)
void CShop::ParasLineItem(char *pData)
bool CShop::LoadGmItems()
SeItemResult CShop::CurrencyBuyItem(SePlayer *pPlayer, uint32_t types, uint32_t uiShopID, uint32_t ItemCount)
SeItemResult CShop::CurrencyBuyItem_Gold(SePlayer *pPlayer, uint32_t types, uint32_t uiShopID, uint32_t ItemCount)
SeItemResult CShop::CurrencyBuyItem_Diamond(SePlayer *pPlayer, uint32_t types, uint32_t uiShopID, uint32_t ItemCount)
void CShop::ProcessHeroItem(SePlayer *pPlayer, uint32_t uiItemID)
DWord CShop::GetHeroID(uint32_t uiItemID)
bool CShop::CheckSoleItemType(int32_t iclass)
bool CShop::CheckSoleItem(SePlayer *pPlayer, int32_t iclass, uint32_t uiItemID)