CPerformanceTiming
CRSPerformanceTimingMgr
static PerformanceTiming::CInterval * CPerformanceTiming::s_maxFramePktHandlerInterval
PerformanceTiming::TIntervalMap CPerformanceTiming::m_mAllIntervals
map of the profiling interval objects registered with us
Referenced by CreateOrLookupInterval, EnumerateIntervals, LookupInterval, ResetAll, TickNotify.
PerformanceTiming::THistoryCounterArray CPerformanceTiming::m_vHistoryCounters
Referenced by CreateOrLookupCounter, EnumerateAllCounters, TickNotify.
PerformanceTiming::TCounterArray CPerformanceTiming::m_vCounters
Referenced by CreateOrLookupCounter, EnumerateAllCounters.
PerformanceTiming::TCounterMap CPerformanceTiming::m_mAllCounters
Referenced by CreateOrLookupCounter, LookupCounter, ResetCounters.
PerformanceTiming::CPackCounter * CPerformanceTiming::m_pPackCounter
Referenced by addPacketRealTotalSize, CPerformanceTiming, getPacketCounter.
IInterval * CPerformanceTiming::_InnerArray[EPERF_MAX_NODE]
Referenced by GetAllInterval, Init.
UInt64 CPerformanceTiming::m_DeltaTime
Referenced by GetLastRealTimeDeltaSec, TickNotify.
UInt64 CPerformanceTiming::m_LastTime
Referenced by BeginTrack, TickNotify.
UInt64 CPerformanceTiming::m_LastFrameTime
Referenced by Start, TickNotify.
float CPerformanceTiming::m_fLastDumpTotalTime
Referenced by GetLastDumpTotalTime, TickNotify.
UInt64 CPerformanceTiming::m_TotalElapsedTime
total elapsed time
Referenced by GetTotalElapsedTime, TickNotify.
UInt64 CPerformanceTiming::m_uTotalCounts
Referenced by TickNotify.
std::vector< CPerformanceTimingSink * > CPerformanceTiming::m_vSinks
Referenced by AddSink, BeginTrack, EndTrack, ForceDump, TickNotify.
UInt32 CPerformanceTiming::m_uLastCounts
Referenced by TickNotify.
float CPerformanceTiming::m_fLastFps
Referenced by GetLastFps, TickNotify.
float CPerformanceTiming::m_fFpsTime
Referenced by TickNotify.
float CPerformanceTiming::m_fTotalAvgFps
Referenced by GetTotalAvgFPS, TickNotify.
static bool CPerformanceTiming::m_sbIntervalsActive
dynamic enabling/disabling of intervals processing based on visibility/usage
Referenced by GetIntervalsActive, SetIntervalsActive.
static UInt32 CPerformanceTiming::m_suiIntervalsVerboseLevel
current interval verbose level
Referenced by GetIntervalsVerboseLevel, SetIntervalsVerboseLevel.
static UInt32 CPerformanceTiming::m_suiIntervalDispWidth
Referenced by GetIntervalsDispWidth, SetIntervalsDispWidth.
static CPerformanceTiming* CPerformanceTiming::Instance()
References CPerformanceTimingMgr::GetInstacne, CPerformanceTimingMgr::MutiInstance.
Referenced by CPerformanceIntervalFileDump::BeginTrack, CPerformanceIntervalFileDump::DumpIntervals, MutiInstance, CPerformanceIntervalFileDump::Tick, TickNotify, RaceService::Update.
static CPerformanceTiming* CPerformanceTiming::InstanceQuick()
References CPerformanceTimingMgr::GetInstacne, CPerformanceTimingMgr::MutiInstanceQuick.
Referenced by CPerformanceIntervalFileDump::DumpIntervals, PerformanceTiming::CInterval::GetIntervalPercentage, MutiInstanceQuick, CPerformanceIntervalFileDump::Tick.
static CPerformanceTiming* CPerformanceTiming::MutiInstance()
References Instance.
Referenced by RaceService::DoWork.
static CPerformanceTiming* CPerformanceTiming::MutiInstanceQuick()
References InstanceQuick.
static bool CPerformanceTiming::GetIntervalsActive()
References m_sbIntervalsActive.
static void CPerformanceTiming::SetIntervalsActive(bool bActive)
References m_sbIntervalsActive.
static UInt32 CPerformanceTiming::GetIntervalsVerboseLevel()
References m_suiIntervalsVerboseLevel.
static void CPerformanceTiming::SetIntervalsVerboseLevel(UInt32 uLvl)
References m_suiIntervalsVerboseLevel.
static UInt32 CPerformanceTiming::GetIntervalsDispWidth()
References m_suiIntervalDispWidth.
static void CPerformanceTiming::SetIntervalsDispWidth(UInt32 uWidth)
References m_suiIntervalDispWidth.
static CPerformanceTiming* CPerformanceTiming::Instance()
References CPerformanceTimingMgr::GetInstacne, CPerformanceTimingMgr::MutiInstance.
static CPerformanceTiming* CPerformanceTiming::InstanceQuick()
References CPerformanceTimingMgr::GetInstacne, CPerformanceTimingMgr::MutiInstanceQuick.
static CPerformanceTiming* CPerformanceTiming::MutiInstance()
References Instance.
static CPerformanceTiming* CPerformanceTiming::MutiInstanceQuick()
References InstanceQuick.
static bool CPerformanceTiming::GetIntervalsActive()
References m_sbIntervalsActive.
static void CPerformanceTiming::SetIntervalsActive(bool bActive)
References m_sbIntervalsActive.
static UInt32 CPerformanceTiming::GetIntervalsVerboseLevel()
References m_suiIntervalsVerboseLevel.
static void CPerformanceTiming::SetIntervalsVerboseLevel(UInt32 uLvl)
References m_suiIntervalsVerboseLevel.
static UInt32 CPerformanceTiming::GetIntervalsDispWidth()
References m_suiIntervalDispWidth.
static void CPerformanceTiming::SetIntervalsDispWidth(UInt32 uWidth)
References m_suiIntervalDispWidth.
void CPerformanceTiming::Init()
References _InnerArray.
Referenced by RaceService::DoWork.
void CPerformanceTiming::ResetAll()
References m_mAllIntervals.
Referenced by CPerformanceIntervalFileDump::BeginTrack.
void CPerformanceTiming::AddSink(CPerformanceTimingSink *pSink)
References m_vSinks, CPerformanceTimingSink::SetOwner.
Referenced by RaceService::DoWork.
void CPerformanceTiming::BeginTrack()
References m_LastTime, m_vSinks.
Referenced by RaceService::DoWork.
void CPerformanceTiming::EndTrack()
References m_vSinks.
PerformanceTiming::CInterval * CPerformanceTiming::LookupInterval(const char *szName, bool bOnlyIncludeTouched)
References PerformanceTiming::CRCString, PerformanceTiming::CPerformanceStat::IsTouched.
PerformanceTiming::CCounter * CPerformanceTiming::LookupCounter(CRC_ID id, bool bOnlyIncludeTouched=false)
References m_mAllCounters.
Referenced by CreateOrLookupCounter.
IInterval * CPerformanceTiming::CreateOrLookupInterval(const char *szName, UInt32 uiFlags=0, double dWarning=0.0, double dCritical=0.0)
References PerformanceTiming::CRCString, m_mAllIntervals.
Referenced by CreateOrLookupChildInterval, CreateOrLookupInterval, TickNotify.
IInterval * CPerformanceTiming::CreateOrLookupInterval(CRC_ID id, char *szName, unsigned int uiFlags=0, double dWarning=0.0, double dCritical=0.0)
References m_mAllIntervals.
ICounter * CPerformanceTiming::CreateOrLookupCounter(CRC_ID id, char *szName, unsigned int uiFlags=0, double dWarning=0.0, double dCritical=0.0)
References eCounterFlags_ResetEachFrame, LookupCounter, m_mAllCounters, m_vCounters, m_vHistoryCounters.
Referenced by CreateOrLookupCounter.
IInterval * CPerformanceTiming::CreateOrLookupInterval(CRC_ID id, char *szName, char *szFolderName, unsigned int uiFlags=0, double dWarning=0.0, double dCritical=0.0)
References CreateOrLookupInterval, m_mAllIntervals, IInterval::SetFolderName.
ICounter * CPerformanceTiming::CreateOrLookupCounter(CRC_ID id, char *szName, char *szFolderName, unsigned int uiFlags=0, double dWarning=0.0, double dCritical=0.0)
References CreateOrLookupCounter, m_mAllCounters, ICounter::SetFolderName.
virtual IIntervalArray& CPerformanceTiming::GetAllInterval()
References _InnerArray.
void CPerformanceTiming::addPacketStatu(const TeMD5 &rRaceID, UInt32 iPacketID, UInt32 iSize)
void CPerformanceTiming::addPacketRealTotalSize(const TeMD5 &rRaceID, UInt32 iSize)
References PerformanceTiming::CPackCounter::m_mMaxPackTotalSize, PerformanceTiming::CPackCounter::m_mRaceRealPackTotalSize, m_pPackCounter.
void CPerformanceTiming::ResetCounters()
References m_mAllCounters, PerformanceTiming::CCounter::Reset.
PerformanceTiming::CInterval * CPerformanceTiming::CreateOrLookupChildInterval(const char *szName, const char *szChild, UInt32 uiFlags=0)
References PerformanceTiming::CInterval::AddChild, CreateOrLookupInterval.
void CPerformanceTiming::TickNotify()
References PerformanceTiming::CInterval::AdvanceFrame, PerformanceTiming::CInterval::AdvanceFrameStatic, PerformanceTiming::CRCString, CreateOrLookupInterval, PerformanceTiming::CInterval::End, makeCallback.f, Instance, m_DeltaTime, M_DoMutiInterval_FN, m_fFpsTime, m_fLastDumpTotalTime, m_fLastFps, m_fTotalAvgFps, m_LastFrameTime, m_LastTime, m_mAllIntervals, m_TotalElapsedTime, m_uLastCounts, m_uTotalCounts, m_vHistoryCounters, m_vSinks, IInterval::SetFolderName, PerformanceTiming::CInterval::Start.
Referenced by RaceService::Update.
void CPerformanceTiming::Start()
References m_LastFrameTime.
Referenced by RaceService::Update.
Float64 CPerformanceTiming::GetTotalElapsedTime() const
References m_TotalElapsedTime.
Referenced by PerformanceTiming::CInterval::GetIntervalPercentage.
Float64 CPerformanceTiming::GetLastRealTimeDeltaSec() const
References m_DeltaTime.
Referenced by CPerformanceIntervalFileDump::DumpIntervals, CPerformanceIntervalFileDump::Tick.
float CPerformanceTiming::GetTotalAvgFPS() const
References m_fTotalAvgFps.
Referenced by CPerformanceIntervalFileDump::DumpIntervals.
float CPerformanceTiming::GetLastFps() const
References m_fLastFps.
Referenced by CPerformanceIntervalFileDump::DumpIntervals.
float CPerformanceTiming::GetLastDumpTotalTime() const
References m_fLastDumpTotalTime.
Referenced by CPerformanceIntervalFileDump::DumpIntervals, CPerformanceIntervalFileDump::Tick.
void CPerformanceTiming::EnumerateIntervals(PerformanceTiming::TConstIntervalArray &vIntervals, bool bOnlyIncludeTouched=true)
References m_mAllIntervals.
Referenced by CPerformanceIntervalFileDump::DumpIntervals.
void CPerformanceTiming::EnumerateAllCounters(PerformanceTiming::TConstCounterArray &vAllCounters, bool bOnlyIncludeTouched=true)
References m_vCounters, m_vHistoryCounters.
Referenced by CPerformanceIntervalFileDump::DumpIntervals.
void CPerformanceTiming::EnumerateIntervals(PerformanceTiming::TIntervalCloneArray &vIntervals, bool bOnlyIncludeTouched=true)
References PerformanceTiming::CPerformanceStat::GetFolderName, PerformanceTiming::CPerformanceStat::GetFolderNameCRC, PerformanceTiming::CInterval::GetLastFrameIntervalEntries, PerformanceTiming::CInterval::GetLastFrameIntervalTimeSec, PerformanceTiming::CInterval::IsLastFrameClosed, PerformanceTiming::CIntervalClone::m_bLastFrameClosed, PerformanceTiming::CIntervalClone::m_crcID, PerformanceTiming::CIntervalClone::m_dLastFrameIntervalTimeSec, PerformanceTiming::CIntervalClone::m_iKey, PerformanceTiming::CIntervalClone::m_iLastFrameIntervalEntries, m_mAllIntervals, PerformanceTiming::CIntervalClone::m_strFolderName, PerformanceTiming::CIntervalClone::m_StrName, PerformanceTiming::CPerformanceStat::Name.
void CPerformanceTiming::EnumerateAllCounters(PerformanceTiming::TCounterCloneArray &vAllCounters, bool bOnlyIncludeTouched=true)
References PerformanceTiming::CPerformanceStat::GetFolderName, PerformanceTiming::CPerformanceStat::GetFolderNameCRC, PerformanceTiming::CHistoryCounter::GetHistory, PerformanceTiming::CCounterHistory< TValueType, TSumType >::GetLastValue, PerformanceTiming::CCounter::GetValue, PerformanceTiming::CCounterClone::m_bHistory, PerformanceTiming::CCounterClone::m_crcID, PerformanceTiming::CCounterClone::m_LastValueAdded, PerformanceTiming::CCounterClone::m_RunningTotal, PerformanceTiming::CCounterClone::m_strFolderName, PerformanceTiming::CCounterClone::m_strName, PerformanceTiming::CCounterClone::m_uValue, m_vCounters, m_vHistoryCounters, PerformanceTiming::CPerformanceStat::Name.
void CPerformanceTiming::ForceDump()
References m_vSinks.
PerformanceTiming::CInterval * CPerformanceTiming::LookupInterval(CRC_ID nameID)
References m_mAllIntervals.
PerformanceTiming::CPackCounter* CPerformanceTiming::getPacketCounter()
References m_pPackCounter.
Referenced by CPerformanceIntervalFileDump::Tick.
void CPerformanceTiming::Init()
void CPerformanceTiming::ResetAll()
void CPerformanceTiming::AddSink(CPerformanceTimingSink *pSink)
void CPerformanceTiming::BeginTrack()
void CPerformanceTiming::EndTrack()
PerformanceTiming::CInterval* CPerformanceTiming::LookupInterval(const char *szName, bool bOnlyIncludeTouched)
PerformanceTiming::CCounter* CPerformanceTiming::LookupCounter(CRC_ID id, bool bOnlyIncludeTouched=false)
IInterval* CPerformanceTiming::CreateOrLookupInterval(const char *szName, UInt32 uiFlags=0, double dWarning=0.0, double dCritical=0.0)
IInterval* CPerformanceTiming::CreateOrLookupInterval(CRC_ID id, char *szName, unsigned int uiFlags=0, double dWarning=0.0, double dCritical=0.0)
ICounter* CPerformanceTiming::CreateOrLookupCounter(CRC_ID id, char *szName, unsigned int uiFlags=0, double dWarning=0.0, double dCritical=0.0)
virtual IInterval* CPerformanceTiming::CreateOrLookupInterval(CRC_ID id, char *szName, char *szFolderName, unsigned int uiFlags=0, double dWarning=0.0, double dCritical=0.0)
virtual ICounter* CPerformanceTiming::CreateOrLookupCounter(CRC_ID id, char *szName, char *szFolderName, unsigned int uiFlags=0, double dWarning=0.0, double dCritical=0.0)
virtual IIntervalArray& CPerformanceTiming::GetAllInterval()
References _InnerArray.
void CPerformanceTiming::addPacketStatu(const TeMD5 &rRaceID, UInt32 iPacketID, UInt32 iSize)
void CPerformanceTiming::addPacketRealTotalSize(const TeMD5 &rRaceID, UInt32 iSize)
void CPerformanceTiming::ResetCounters()
PerformanceTiming::CInterval* CPerformanceTiming::CreateOrLookupChildInterval(const char *szName, const char *szChild, UInt32 uiFlags=0)
void CPerformanceTiming::TickNotify()
void CPerformanceTiming::Start()
Float64 CPerformanceTiming::GetTotalElapsedTime() const
References m_TotalElapsedTime.
Float64 CPerformanceTiming::GetLastRealTimeDeltaSec() const
References m_DeltaTime.
float CPerformanceTiming::GetTotalAvgFPS() const
References m_fTotalAvgFps.
float CPerformanceTiming::GetLastFps() const
References m_fLastFps.
float CPerformanceTiming::GetLastDumpTotalTime() const
References m_fLastDumpTotalTime.
void CPerformanceTiming::EnumerateIntervals(PerformanceTiming::TConstIntervalArray &vIntervals, bool bOnlyIncludeTouched=true)
void CPerformanceTiming::EnumerateAllCounters(PerformanceTiming::TConstCounterArray &vAllCounters, bool bOnlyIncludeTouched=true)
void CPerformanceTiming::EnumerateIntervals(PerformanceTiming::TIntervalCloneArray &vIntervals, bool bOnlyIncludeTouched=true)
void CPerformanceTiming::EnumerateAllCounters(PerformanceTiming::TCounterCloneArray &vAllCounters, bool bOnlyIncludeTouched=true)
void CPerformanceTiming::ForceDump()
PerformanceTiming::CInterval* CPerformanceTiming::LookupInterval(CRC_ID nameID)
PerformanceTiming::CPackCounter* CPerformanceTiming::getPacketCounter()
References m_pPackCounter.
CPerformanceTiming::CPerformanceTiming()
References PerformanceTiming::CPerformanceStat::DoSetFolderName, m_pPackCounter.
CPerformanceTiming::~CPerformanceTiming()
CPerformanceTiming destructor
CPerformanceTiming::CPerformanceTiming()
CPerformanceTiming::~CPerformanceTiming()