TiXmlVisitor
virtual TiXmlVisitor::~TiXmlVisitor()
virtual bool TiXmlVisitor::VisitEnter(const TiXmlDocument &doc)
Visit a document.
Referenced by TiXmlElement::Accept, TiXmlDocument::Accept.
virtual bool TiXmlVisitor::VisitExit(const TiXmlDocument &doc)
Visit a document.
Referenced by TiXmlElement::Accept, TiXmlDocument::Accept.
virtual bool TiXmlVisitor::VisitEnter(const TiXmlElement &element, const TiXmlAttribute *firstAttribute)
Visit an element.
virtual bool TiXmlVisitor::VisitExit(const TiXmlElement &element)
Visit an element.
virtual bool TiXmlVisitor::Visit(const TiXmlDeclaration &declaration)
Visit a declaration.
Referenced by TiXmlComment::Accept, TiXmlText::Accept, TiXmlDeclaration::Accept, TiXmlUnknown::Accept.
virtual bool TiXmlVisitor::Visit(const TiXmlText &text)
Visit a text node.
virtual bool TiXmlVisitor::Visit(const TiXmlComment &comment)
Visit a comment node.
virtual bool TiXmlVisitor::Visit(const TiXmlUnknown &unknown)
Visit an unknow node.