MatchBanMgr
typedef std::map<DWord, BanItem *> MatchBanMgr::PLAYERMAP
typedef std::multimap<moba::TimeType, BanItem *> MatchBanMgr::TIMEMAP
typedef std::map<DWord, BanItem *> MatchBanMgr::PLAYERMAP
typedef std::multimap<moba::TimeType, BanItem *> MatchBanMgr::TIMEMAP
PLAYERMAP MatchBanMgr::m_players
Referenced by clearItem, isPlayerBanned.
TIMEMAP MatchBanMgr::m_timeMap
Referenced by clearItem, update.
MatchBanMgr::MatchBanMgr()
MatchBanMgr::~MatchBanMgr()
bool MatchBanMgr::isPlayerBanned(DWord dwPlayerID)
References m_players.
Referenced by MatchPrepareMgr::collectData.
void MatchBanMgr::banPlayer(DWord dwPlayerID)
References g_kMatchServer, MatchServer::SendMN_MatchPunishNtf, TIMEOUT.
Referenced by SeMatchMgr::OnConfirm, SeMatchMgr::UpdateRoom.
void MatchBanMgr::update()
References clearItem, moba::Clock::getInstance, moba::Clock::getMilliSeconds, m_timeMap.
Referenced by MatchServer::Update.
MatchBanMgr::MatchBanMgr()
MatchBanMgr::~MatchBanMgr()
bool MatchBanMgr::isPlayerBanned(DWord dwPlayerID)
void MatchBanMgr::banPlayer(DWord dwPlayerID)
void MatchBanMgr::update()
void MatchBanMgr::clearItem(BanItem *item)
References MatchBanMgr::BanItem::dwPlayerID, MatchBanMgr::BanItem::itTime, m_players, m_timeMap.
Referenced by update.
void MatchBanMgr::clearItem(BanItem *item)