SeRaceRecordSaveThread
bool SeRaceRecordSaveThread::m_bRun
Referenced by DoWork, Finialize, Initialize, SeRaceRecordSaveThread.
RaceServer * SeRaceRecordSaveThread::m_pkOwner
unsigned int SeRaceRecordSaveThread::m_uLogicVersion
Referenced by saveRecord.
TRaceTaskQueue SeRaceRecordSaveThread::m_qSaveQueue
Referenced by DoWork, Finialize, PushTask.
TRaceTaskQueue SeRaceRecordSaveThread::m_qFinishQueue
Referenced by DoWork, Update.
Es::NormalLock * SeRaceRecordSaveThread::m_pkQueueLock
Referenced by DoWork, Initialize, PushTask, Update.
SeRaceRecordSaveThread::SeRaceRecordSaveThread(RaceServer *owner, unsigned int logciVersion)
References m_bRun.
SeRaceRecordSaveThread::~SeRaceRecordSaveThread(void)
void SeRaceRecordSaveThread::PushTask(class SeRace *pTask)
References m_pkQueueLock, m_qSaveQueue.
Referenced by RaceServer::SaveRecord.
bool SeRaceRecordSaveThread::Initialize(void)
References m_bRun, m_pkQueueLock.
Referenced by RaceServer::RaceThreadInitialize.
void SeRaceRecordSaveThread::Finialize(void)
References m_bRun, m_qSaveQueue, saveRecord.
Referenced by RaceServer::RaceThreadFinialize.
void SeRaceRecordSaveThread::Update()
References m_pkQueueLock, m_qFinishQueue.
Referenced by RaceServer::RaceThreadFinialize, RaceServer::RaceThreadUpdate.
void SeRaceRecordSaveThread::DoWork(void)
References m_bRun, m_pkQueueLock, m_qFinishQueue, m_qSaveQueue, saveRecord.
SeRaceRecordSaveThread::SeRaceRecordSaveThread(RaceServer *owner, unsigned int logciVersion)
virtual SeRaceRecordSaveThread::~SeRaceRecordSaveThread(void)
void SeRaceRecordSaveThread::PushTask(class SeRace *pTask)
bool SeRaceRecordSaveThread::Initialize(void)
void SeRaceRecordSaveThread::Finialize(void)
void SeRaceRecordSaveThread::Update()
virtual void SeRaceRecordSaveThread::DoWork(void)
void SeRaceRecordSaveThread::saveRecord(class SeRace *pTask)
References TeMD5::abyMD5, SeRaceConfig::acRaceRecordSavePath, g_kRaceServer, GetMD52Str, RaceServer::GetRaceConfig, SeRace::kRaceID, SeRace::kRecord, SeRace::kSvrModeRecord, m_uLogicVersion, SeRaceRecord::SaveReplayReportToFile, SeRaceRecord::SaveToFile, SeLogInfo, SPrintf.
Referenced by DoWork, Finialize.
void SeRaceRecordSaveThread::saveRecord(class SeRace *pTask)