TableLoader
virtual const char* TableLoader::LoadTable(const char *pkPath, int &iSize)=0
Referenced by KillBountyTableMgr::Load, AppendGroupTableMgr::Load, AvatarShopTableMgr::Load, TaskRecomTableMgr::Load, MapShopResTableMgr::Load, ChoiceItemTableMgr::Load, AddtionalTableMgr::Load, AvatarModelTableMgr::Load, RaceTextTableMgr::Load, RandomNameTableMgr::Load, SystemPromptTableMgr::Load, UnitHeadAreaTableMgr::Load, LevelTableMgr::Load, AttackArmorRatioTableMgr::Load, EffectSwitchTableMgr::Load, LanguageTableMgr::Load, DressTableMgr::Load, RacehelpTableMgr::Load, AITableMgr::Load, AchievementTableMgr::Load, AIPrioTableMgr::Load, AvatarAnimationTableMgr::Load, HorseTableMgr::Load, VoiceTableMgr::Load, PresetShopTableMgr::Load, IndexofferTableMgr::Load, AvatarEffectTableMgr::Load, AcSystemTableMgr::Load, AccountLevelTableMgr::Load, UpgradeCostTableMgr::Load, ChanceTableMgr::Load, AppendCostTableMgr::Load, PetTableMgr::Load, SearchChoiceTableMgr::Load, RenJiTableMgr::Load, ItemComposeTableMgr::Load, CreepTowerGrowthTableMgr::Load, RankStageTableMgr::Load, FreeHeroesTableMgr::Load, LeagueRankTableMgr::Load, ShopTableMgr::Load, PropagandaTableMgr::Load, DecomposeTableMgr::Load, MapMiscTableMgr::Load, ModelResTableMgr::Load, RenJiActionsTableMgr::Load, RenJiCustomDataTableMgr::Load, HeroInfoTableMgr::Load, StarWheelTableMgr::Load, RacedropTableMgr::Load, RackTableMgr::Load, BufferTableMgr::Load, BattleTipsTableMgr::Load, MissionInfoTableMgr::Load, PVERuleTableMgr::Load, VideoTagTableMgr::Load, AppendSkillPRTableMgr::Load, RaceStaMissionTableMgr::Load, RenJiConditionsTableMgr::Load, AvatarTableMgr::Load, MapsInfoTableMgr::Load, AppendSkillTableMgr::Load, SelHeroTableMgr::Load, ItemExchangeTableMgr::Load, TaskInfoTableMgr::Load, AchievementTaskTableMgr::Load, MapInfoTableMgr::Load, StrengthenTableMgr::Load, UnitTableMgr::Load, ItemTableMgr::Load, TownItemTableMgr::Load, SkillTableMgr::LoadSkillFile.