KillBountyTableMgr
std::map<int,KillBountyTable*> KillBountyTableMgr::m_kKillBountyTableMap
Referenced by FillData, GetKillBountyTable, GetKillBountyTableMap, GetKillBountyTableVec, ~KillBountyTableMgr.
KillBountyTableMgr * KillBountyTableMgr::m_pkKillBountyTableMgr
Referenced by Get, ReLoad.
KillBountyTableMgr * KillBountyTableMgr::Get()
References KillBountyTableMgr, m_pkKillBountyTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
KillBountyTableMgr * KillBountyTableMgr::ReLoad()
References Get, m_pkKillBountyTableMgr.
Referenced by TableMgr::ReloadTable.
KillBountyTableMgr::KillBountyTableMgr()
References Load.
Referenced by Get.
KillBountyTableMgr::~KillBountyTableMgr()
References m_kKillBountyTableMap.
const KillBountyTable * KillBountyTableMgr::GetKillBountyTable(int iTypeID)
References m_kKillBountyTableMap.
const std::map< int, KillBountyTable * > & KillBountyTableMgr::GetKillBountyTableMap()
References m_kKillBountyTableMap.
TableResArray KillBountyTableMgr::GetKillBountyTableVec()
References m_kKillBountyTableMap, TableResArray::pushBack.
bool KillBountyTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by KillBountyTableMgr.
void KillBountyTableMgr::FillData(KillBountyTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, KillBountyTable::fAssistsShareMoney, KillBountyTable::fKillMoney, KillBountyTable::iComboKillDeath, m_kKillBountyTableMap.
Referenced by Load.