UnitHeadAreaTableMgr
std::map<unsigned int,UnitHeadAreaTable*> UnitHeadAreaTableMgr::m_kUnitHeadAreaTableMap
Referenced by FillData, GetUnitHeadAreaTable, GetUnitHeadAreaTableMap, GetUnitHeadAreaTableVec, ~UnitHeadAreaTableMgr.
UnitHeadAreaTableMgr * UnitHeadAreaTableMgr::m_pkUnitHeadAreaTableMgr
Referenced by Get, ReLoad.
UnitHeadAreaTableMgr * UnitHeadAreaTableMgr::Get()
References m_pkUnitHeadAreaTableMgr, UnitHeadAreaTableMgr.
Referenced by ReLoad.
UnitHeadAreaTableMgr * UnitHeadAreaTableMgr::ReLoad()
References Get, m_pkUnitHeadAreaTableMgr.
UnitHeadAreaTableMgr::UnitHeadAreaTableMgr()
References Load.
Referenced by Get.
UnitHeadAreaTableMgr::~UnitHeadAreaTableMgr()
References m_kUnitHeadAreaTableMap.
const UnitHeadAreaTable * UnitHeadAreaTableMgr::GetUnitHeadAreaTable(unsigned int iTypeID)
References m_kUnitHeadAreaTableMap.
const std::map< unsigned int, UnitHeadAreaTable * > & UnitHeadAreaTableMgr::GetUnitHeadAreaTableMap()
References m_kUnitHeadAreaTableMap.
TableResArray UnitHeadAreaTableMgr::GetUnitHeadAreaTableVec()
References m_kUnitHeadAreaTableMap, TableResArray::pushBack.
bool UnitHeadAreaTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by UnitHeadAreaTableMgr.
void UnitHeadAreaTableMgr::FillData(UnitHeadAreaTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, UnitHeadAreaTable::kIcon1, UnitHeadAreaTable::kIcon2, UnitHeadAreaTable::kIcon3, UnitHeadAreaTable::kIcon4, m_kUnitHeadAreaTableMap, UnitHeadAreaTable::uiUnitTypeID.
Referenced by Load.