EffectSwitchTableMgr
std::map<unsigned int, EffectSwitchTable*> EffectSwitchTableMgr::m_kEffectSwitchTableMap
Referenced by FillData, GetEffectSwitchTable, GetEffectSwitchTableMap, GetEffectSwitchTableVec, GetEffectSwitchTableVecByID, ~EffectSwitchTableMgr.
std::vector<EffectSwitchTable*> EffectSwitchTableMgr::m_kEffectSwitchTempVector
Referenced by GetEffectSwitchTableVecByID.
EffectSwitchTableMgr * EffectSwitchTableMgr::m_pkEffectSwitchTableMgr
Referenced by Get, ReLoad.
EffectSwitchTableMgr * EffectSwitchTableMgr::Get()
References EffectSwitchTableMgr, m_pkEffectSwitchTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
EffectSwitchTableMgr * EffectSwitchTableMgr::ReLoad()
References Get, m_pkEffectSwitchTableMgr.
Referenced by TableMgr::ReloadTable.
EffectSwitchTableMgr::EffectSwitchTableMgr()
References Load.
Referenced by Get.
EffectSwitchTableMgr::~EffectSwitchTableMgr()
References m_kEffectSwitchTableMap.
const EffectSwitchTable * EffectSwitchTableMgr::GetEffectSwitchTable(unsigned int iTypeID)
References m_kEffectSwitchTableMap.
const std::map< unsigned int, EffectSwitchTable * > & EffectSwitchTableMgr::GetEffectSwitchTableMap()
References m_kEffectSwitchTableMap.
const std::vector< EffectSwitchTable * > & EffectSwitchTableMgr::GetEffectSwitchTableVecByID(unsigned int iTypeID)
References m_kEffectSwitchTableMap, m_kEffectSwitchTempVector.
TableResArray EffectSwitchTableMgr::GetEffectSwitchTableVec()
References m_kEffectSwitchTableMap, TableResArray::pushBack.
bool EffectSwitchTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by EffectSwitchTableMgr.
void EffectSwitchTableMgr::FillData(EffectSwitchTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, m_kEffectSwitchTableMap, EffectSwitchTable::strAttachPos, EffectSwitchTable::uiAttachCondition, EffectSwitchTable::uiID, EffectSwitchTable::uiOwner, EffectSwitchTable::uiResID.
Referenced by Load.