RaceTextTableMgr
std::map<unsigned int,RaceTextTable*> RaceTextTableMgr::m_kRaceTextTableMap
Referenced by FillData, GetRaceTextTable, GetRaceTextTableMap, GetRaceTextTableVec, ~RaceTextTableMgr.
RaceTextTableMgr * RaceTextTableMgr::m_pkRaceTextTableMgr
Referenced by Get, ReLoad.
RaceTextTableMgr * RaceTextTableMgr::Get()
References m_pkRaceTextTableMgr, RaceTextTableMgr.
Referenced by ReLoad.
RaceTextTableMgr * RaceTextTableMgr::ReLoad()
References Get, m_pkRaceTextTableMgr.
RaceTextTableMgr::RaceTextTableMgr()
References Load.
Referenced by Get.
RaceTextTableMgr::~RaceTextTableMgr()
References m_kRaceTextTableMap.
const RaceTextTable * RaceTextTableMgr::GetRaceTextTable(unsigned int iTypeID)
References m_kRaceTextTableMap.
const std::map< unsigned int, RaceTextTable * > & RaceTextTableMgr::GetRaceTextTableMap()
References m_kRaceTextTableMap.
TableResArray RaceTextTableMgr::GetRaceTextTableVec()
References m_kRaceTextTableMap, TableResArray::pushBack.
bool RaceTextTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RaceTextTableMgr.
void RaceTextTableMgr::FillData(RaceTextTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RaceTextTable::kName_China, RaceTextTable::kTextDesc, m_kRaceTextTableMap, RaceTextTable::uiContent, RaceTextTable::uiTextID.
Referenced by Load.