AvatarTableMgr
std::map<unsigned int,AvatarTable*> AvatarTableMgr::m_kAvatarTableMap
Referenced by FillData, GetAvatarTable, GetAvatarTableMap, GetAvatarTableVec, ~AvatarTableMgr.
AvatarTableMgr * AvatarTableMgr::m_pkAvatarTableMgr
Referenced by Get, ReLoad.
AvatarTableMgr * AvatarTableMgr::Get()
References AvatarTableMgr, m_pkAvatarTableMgr.
Referenced by GlobalTableMgr::GetAvatarTable, GlobalTableMgr::GetAvatarTableMap, CShop::GetHeroID, CItemMgr::getSelectableAvatars, HeroMgr::isValidAvatar, TableMgr::LoadTable, ReLoad, SeMatchPlayer::setAvatar, SeMatchPlayer::setRandomAvatar.
AvatarTableMgr * AvatarTableMgr::ReLoad()
References Get, m_pkAvatarTableMgr.
Referenced by TableMgr::ReloadTable.
AvatarTableMgr::AvatarTableMgr()
References Load.
Referenced by Get.
AvatarTableMgr::~AvatarTableMgr()
References m_kAvatarTableMap.
const AvatarTable * AvatarTableMgr::GetAvatarTable(unsigned int iTypeID)
References m_kAvatarTableMap.
Referenced by GlobalTableMgr::GetAvatarTable, CShop::GetHeroID, CItemMgr::getSelectableAvatars, HeroMgr::isValidAvatar, SeMatchPlayer::setAvatar, SeMatchPlayer::setRandomAvatar.
const std::map< unsigned int, AvatarTable * > & AvatarTableMgr::GetAvatarTableMap()
References m_kAvatarTableMap.
Referenced by GlobalTableMgr::GetAvatarTableMap.
TableResArray AvatarTableMgr::GetAvatarTableVec()
References m_kAvatarTableMap, TableResArray::pushBack.
bool AvatarTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AvatarTableMgr.
void AvatarTableMgr::FillData(AvatarTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AvatarTable::iAniResID, AvatarTable::iAttack1StateEffID, AvatarTable::iAttack2StateEffID, AvatarTable::iAttackStateEffID, AvatarTable::iCommonEffID, AvatarTable::iDeadStateEffID, AvatarTable::iModelResID, AvatarTable::iShowModelID, AvatarTable::iSillEffID, AvatarTable::iSkillIconID, AvatarTable::kAvatarFolderName, AvatarTable::kBtainTips, AvatarTable::kdescribe, AvatarTable::kName_China, m_kAvatarTableMap, AvatarTable::uiAvatarID, AvatarTable::uiAvatarQuality, AvatarTable::uiAvatarType, AvatarTable::uiBtain, AvatarTable::uiCardIconID, AvatarTable::uiHeadIconID, AvatarTable::uiHeroID, AvatarTable::uiLanguageID, AvatarTable::uiLoadingIconID, AvatarTable::uiMorphID, AvatarTable::uiRackID, AvatarTable::uiSkinPos.
Referenced by Load.