SeXmlParsingData
friend class SeXmlDocument
SeXmlCursor SeXmlParsingData::cursor
Referenced by Cursor, SeXmlDocument::Parse, SeXmlParsingData, Stamp.
const char* SeXmlParsingData::stamp
Referenced by SeXmlParsingData, Stamp.
int SeXmlParsingData::tabsize
Referenced by SeXmlParsingData, Stamp.
void SeXmlParsingData::Stamp(const char *now, SeXmlEncoding encoding)
References SeXmlCursor::col, cursor, SeXmlCursor::row, SeXml_ENCODING_UTF8, SeXml_UTF_LEAD_0, SeXml_UTF_LEAD_1, SeXml_UTF_LEAD_2, stamp, tabsize, SeXmlBase::utf8ByteTable.
Referenced by SeXmlAttribute::Parse, SeXmlElement::Parse, SeXmlComment::Parse, SeXmlText::Parse, SeXmlDeclaration::Parse, SeXmlUnknown::Parse, SeXmlDocument::SetError.
const SeXmlCursor& SeXmlParsingData::Cursor() const
References cursor.
Referenced by SeXmlAttribute::Parse, SeXmlElement::Parse, SeXmlComment::Parse, SeXmlText::Parse, SeXmlDeclaration::Parse, SeXmlUnknown::Parse, SeXmlDocument::Parse, SeXmlDocument::SetError.
SeXmlParsingData::SeXmlParsingData(const char *start, int _tabsize, int row, int col)
References SeXmlCursor::col, cursor, SeXmlCursor::row, stamp, tabsize.