AcSystemTableMgr
std::map<unsigned int,AcSystemTable*> AcSystemTableMgr::m_kAcSystemTableMap
Referenced by FillData, GetAcSystemTable, GetAcSystemTableMap, GetAcSystemTableVec, ~AcSystemTableMgr.
AcSystemTableMgr * AcSystemTableMgr::m_pkAcSystemTableMgr
Referenced by Get, ReLoad.
AcSystemTableMgr * AcSystemTableMgr::Get()
References AcSystemTableMgr, m_pkAcSystemTableMgr.
Referenced by GlobalTableMgr::GetAcSystemTable, GlobalTableMgr::GetAcSystemTableMap, TableMgr::LoadTable, ReLoad.
AcSystemTableMgr * AcSystemTableMgr::ReLoad()
References Get, m_pkAcSystemTableMgr.
Referenced by TableMgr::ReloadTable.
AcSystemTableMgr::AcSystemTableMgr()
References Load.
Referenced by Get.
AcSystemTableMgr::~AcSystemTableMgr()
References m_kAcSystemTableMap.
const AcSystemTable * AcSystemTableMgr::GetAcSystemTable(unsigned int iTypeID)
References m_kAcSystemTableMap.
Referenced by GlobalTableMgr::GetAcSystemTable.
const std::map< unsigned int, AcSystemTable * > & AcSystemTableMgr::GetAcSystemTableMap()
References m_kAcSystemTableMap.
Referenced by GlobalTableMgr::GetAcSystemTableMap.
TableResArray AcSystemTableMgr::GetAcSystemTableVec()
References m_kAcSystemTableMap, TableResArray::pushBack.
bool AcSystemTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AcSystemTableMgr.
void AcSystemTableMgr::FillData(AcSystemTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AcSystemTable::iMapID, AcSystemTable::kACIcon, AcSystemTable::kACName, AcSystemTable::kBattleStory, m_kAcSystemTableMap, AcSystemTable::uidifficultChoose, AcSystemTable::uiPreconditionBattle, AcSystemTable::uiTypeID.
Referenced by Load.