WatchServer::CSeRaceMgr
typedef std::map<DWord, TeMD5> WatchServer::CSeRaceMgr::MPlayerID2RaceID
MRace WatchServer::CSeRaceMgr::m_mAllRace
Referenced by addViewPlayer, BeginView, CheckWatchRace, getAllRaceCounts, getRaceViewInfos, onRaceEnd, onRaceStart, onViewValidate, pushRaceData, removeViewPlayer, Update.
MPlayerID2RaceID WatchServer::CSeRaceMgr::m_mPlayerRaceID
Referenced by addViewPlayer, removeViewPlayer, updateView.
SeRaceRecordSaveThread* WatchServer::CSeRaceMgr::m_pkSaveRecordThread
Referenced by CSeRaceMgr, Update, ~CSeRaceMgr.
MRaceDetail WatchServer::CSeRaceMgr::m_race_detail_map
Referenced by CreateRaceDetail, DecViewUserCount, GetRaceDetail, GetRaceDetailMap, IncViewUserCount, MakeRaceDetail, onRaceDetailEnd, UpdateRaceDetail.
WatchServer::CSeRaceMgr::CSeRaceMgr()
References g_kWatchServer, WatchServer::SeRaceRecordSaveThread::Initialize, LOGIC_VERSION, m_pkSaveRecordThread.
WatchServer::CSeRaceMgr::~CSeRaceMgr()
References WatchServer::SeRaceRecordSaveThread::Finialize, m_pkSaveRecordThread.
bool WatchServer::CSeRaceMgr::addViewPlayer(const TeMD5 &rID, const SeViewPlayer &rView)
References WatchServer::SeViewPlayer::dwPlayerID, g_kWatchServer, IncViewUserCount, WatchServer::SeViewPlayer::kPlayerSock, m_mAllRace, m_mPlayerRaceID, removeViewPlayer, WatchServer::CWatchServer::SetPlayerConnect.
Referenced by onViewValidate.
void WatchServer::CSeRaceMgr::removeViewPlayer(DWord dwPlayerID)
References DecViewUserCount, WatchServer::g_kRaceMgr, m_mAllRace, m_mPlayerRaceID, SeLogInfo.
Referenced by addViewPlayer, WatchServer::CWatchServer::OnPlayerDisconnect.
void WatchServer::CSeRaceMgr::pushRaceData(const TeMD5 &rID, const char *pDat, DWord iSize)
References WatchServer::SeRace::kSvrModeRecord, m_mAllRace, SeRaceRecord::PushRaceData.
Referenced by WatchServer::CWatchServer::ProcessRWCS_RaceRecord.
void WatchServer::CSeRaceMgr::onRaceEnd(const TeMD5 &rID)
References WatchServer::SeRace::bRaceEnd, g_kWatchServer, m_mAllRace, WatchServer::CWatchServer::onDelRace, onRaceDetailEnd.
Referenced by WatchServer::CWatchServer::ProcessRWCS_RaceEnd.
void WatchServer::CSeRaceMgr::onRaceStart(const TeMD5 &rID, const SePlayerInfoSeat *pInfo, int iNum)
References WatchServer::SeRace::kRaceID, WatchServer::SeRace::kSvrModeRecord, m_mAllRace, SeRaceRecord::SetPlayerInfo, SeRaceRecord::SetServerMode.
Referenced by WatchServer::CWatchServer::ProcessRWCS_RaceStart.
void WatchServer::CSeRaceMgr::getRaceViewInfos(TWCSViewInfoArray &rViewList)
References TeMD5::abyMD5, SeRaceRecord::GetDataSize, SeRaceRecord::GetLastFrame, WatchServer::SeRace::kRaceID, WatchServer::SeRace::kSvrModeRecord, m_mAllRace.
Referenced by WatchServer::CWatchServer::Register2RS.
void WatchServer::CSeRaceMgr::Update()
References WatchServer::SeRace::bRaceEnd, g_kWatchServer, WatchServer::CWatchServer::GetServerTime, WatchServer::SeRace::kRaceID, m_mAllRace, m_pkSaveRecordThread, WatchServer::SeRace::mViewPlayer, onRaceDetailEnd, WatchServer::SeRaceRecordSaveThread::PushTask, WatchServer::SeRaceRecordSaveThread::Update, updateView.
Referenced by WatchServer::CWatchServer::Update.
DWord WatchServer::CSeRaceMgr::getAllRaceCounts() const
References m_mAllRace.
Referenced by WatchServer::CWatchServer::ShowConsoleTitle.
void WatchServer::CSeRaceMgr::onViewValidate(const TeMD5 &rID, DWord dwPlayerID, void *pSender)
References TeMD5::abyMD5, addViewPlayer, BeginView, WatchServer::SeViewPlayer::dwPlayerID, ENState_Watching, g_kWatchServer, GetMD52Str, WatchServer::SeViewPlayer::kPlayerSock, m_mAllRace, WatchServer::CWatchServer::RaceWatchUserSync, SeLogInfo, WatchServer::CWatchServer::SendWCSC_ViewValidateRet, SWCSVLD_RACENOTSTART, SWCSVLD_RACEOVER.
Referenced by WatchServer::CWatchServer::ProcessCWCS_ViewValidate.
MRaceDetail & WatchServer::CSeRaceMgr::GetRaceDetailMap()
References m_race_detail_map.
Referenced by WatchServer::CWatchServerMgr::onRaceDetailInfoReq.
void WatchServer::CSeRaceMgr::onRaceDetailSync(SeRaceDetailInfo *pInfo, int num)
References MakeRaceDetail.
Referenced by WatchServer::CWatchServer::ProcessRWCS_RaceDetailInfoSync.
void WatchServer::CSeRaceMgr::onRaceDetailEnd(const TeMD5 &rID)
References m_race_detail_map.
Referenced by onRaceEnd, Update.
void WatchServer::CSeRaceMgr::MakeRaceDetail(SeRaceDetailInfo Info)
References TeMD5::abyMD5, CheckWatchRace, CreateRaceDetail, m_race_detail_map, SeRaceDetailInfo::rase_id, UpdateRaceDetail.
Referenced by onRaceDetailSync.
void WatchServer::CSeRaceMgr::CreateRaceDetail(SeRaceDetailInfo Info, const TeMD5 &rID)
References m_race_detail_map, SRaceDetail::race_info, SeRaceDetailInfo::race_info, SRaceDetail::rase_id.
Referenced by MakeRaceDetail.
void WatchServer::CSeRaceMgr::UpdateRaceDetail(SeRaceDetailInfo Info, SRaceDetail *pRaceDetail)
References SeRaceGameInfo::game_mode, SeRaceGameInfo::game_time, m_race_detail_map, SeRaceInfo::race_game, SRaceDetail::race_info, SeRaceDetailInfo::race_info, SeRaceInfo::race_map, SeRaceGameInfo::race_mmr, SeRaceInfo::race_user, SRaceDetail::rase_id.
Referenced by MakeRaceDetail.
SRaceDetail * WatchServer::CSeRaceMgr::GetRaceDetail(const TeMD5 &rID)
References m_race_detail_map.
Referenced by DecViewUserCount, IncViewUserCount.
void WatchServer::CSeRaceMgr::IncViewUserCount(const TeMD5 &rID)
References GetRaceDetail, m_race_detail_map, SeRaceInfo::race_game, SRaceDetail::race_info, SRaceDetail::rase_id, SeRaceGameInfo::watch_user_num.
Referenced by addViewPlayer.
void WatchServer::CSeRaceMgr::DecViewUserCount(const TeMD5 &rID)
References GetRaceDetail, m_race_detail_map, SeRaceInfo::race_game, SRaceDetail::race_info, SRaceDetail::rase_id, SeRaceGameInfo::watch_user_num.
Referenced by removeViewPlayer.
bool WatchServer::CSeRaceMgr::CheckWatchRace(const TeMD5 &rID)
References SeRaceRecord::GetLastFrame, WatchServer::SeRace::kSvrModeRecord, m_mAllRace, MIN_DELAY_FRAME.
Referenced by MakeRaceDetail.
void WatchServer::CSeRaceMgr::BeginView(const SeViewPlayer &rView, const TeMD5 &rID)
References WatchServer::SeViewPlayer::dwPlayerID, g_kWatchServer, SeRaceRecord::GetPlayerInfo, SeWCSC_ViewPlayerInfo::iNum, WatchServer::SeViewPlayer::kPlayerSock, WatchServer::SeRace::kSvrModeRecord, m_mAllRace, MNew, SeLogDebug, WatchServer::CWatchServer::SendWCSC_ViewPlayerInfo.
Referenced by onViewValidate.
void WatchServer::CSeRaceMgr::updateView(SeRace &rRace)
References WatchServer::SeViewPlayer::bDel, WatchServer::SeRace::bRaceEnd, WatchServer::SeRace::bRaceViewStart, WatchServer::CWatchServer::DisconnectPlayer, WatchServer::SeViewPlayer::dwFrame, SeRaceCmd::dwFrame, WatchServer::SeViewPlayer::dwPlayerID, g_kWatchServer, SeRaceRecord::GetDataSize, SeRaceRecord::GetLastFrame, SeRaceRecord::GetLastPos, SeRaceRecord::GetRaceCmd, WatchServer::SeViewPlayer::iOffset, WatchServer::SeViewPlayer::kPlayerSock, WatchServer::SeRace::kRaceID, WatchServer::SeRace::kSvrModeRecord, m_mPlayerRaceID, MIN_DELAY_FRAME, WatchServer::SeRace::mViewPlayer, WatchServer::CWatchServer::onHandleNewRace, WatchServer::CWatchServer::SendWCSC_ViewPack.
Referenced by Update.