LinkUserMgr
MLinkUser LinkUserMgr::map_link_user_
Referenced by check, create, get_link_user, get_link_user_map, get_online_users, get_race_users, get_watch_users, update.
LinkUserMgr::LinkUserMgr()
LinkUserMgr::~LinkUserMgr()
void LinkUserMgr::create(const DWord dw_player_id, const DWord dw_state_id, const DWord dw_login_time)
References LinkUser::login_time, map_link_user_, LinkUser::state_id, LinkUser::user_id.
Referenced by make.
void LinkUserMgr::update(const DWord dw_player_id, const DWord dw_state_id, const DWord dw_login_time)
References get_link_user, LinkUser::login_time, map_link_user_, LinkUser::state_id, LinkUser::user_id.
Referenced by make.
void LinkUserMgr::make(const DWord dw_player_id, const DWord dw_state_id, const DWord dw_login_time)
References check, create, update.
Referenced by BackendServer::ProcessNBKS_UserStateSync.
bool LinkUserMgr::check(const DWord dw_player_id)
References map_link_user_.
Referenced by make.
bool LinkUserMgr::check_online(const DWord dw_player_id)
References check_state, ENState_Online.
Referenced by get_watch_users.
bool LinkUserMgr::check_watching(const DWord dw_player_id)
References check_state, ENState_Watching.
bool LinkUserMgr::check_racing(const DWord dw_player_id)
References check_state, ENState_Racing.
Referenced by get_watch_users.
bool LinkUserMgr::check_state(const DWord dw_player_id, const DWord dw_state_id)
References get_link_user, LinkUser::state_id.
Referenced by check_online, check_racing, check_watching.
LinkUser * LinkUserMgr::get_link_user(const DWord dw_player_id)
References map_link_user_.
Referenced by check_state, update.
MLinkUser & LinkUserMgr::get_link_user_map()
References map_link_user_.
DWord LinkUserMgr::get_online_users()
References map_link_user_.
Referenced by BackendStatisticsMgr::get_online_users.
DWord LinkUserMgr::get_race_users()
References map_link_user_.
Referenced by BackendStatisticsMgr::get_race_users.
DWord LinkUserMgr::get_watch_users()
References check_online, check_racing, map_link_user_, LinkUser::user_id.
Referenced by BackendStatisticsMgr::get_watch_users.