AchievementTaskTableMgr
std::map<unsigned int,AchievementTaskTable*> AchievementTaskTableMgr::m_kAchievementTaskTableMap
Referenced by FillData, GetAchievementTaskTable, GetAchievementTaskTableMap, GetAchievementTaskTableVec, ~AchievementTaskTableMgr.
AchievementTaskTableMgr * AchievementTaskTableMgr::m_pkAchievementTaskTableMgr
Referenced by Get, ReLoad.
AchievementTaskTableMgr * AchievementTaskTableMgr::Get()
References AchievementTaskTableMgr, m_pkAchievementTaskTableMgr.
Referenced by TableMgr::LoadAchieveInfo, AchieveFinishMgr::loadData, ReLoad.
AchievementTaskTableMgr * AchievementTaskTableMgr::ReLoad()
References Get, m_pkAchievementTaskTableMgr.
AchievementTaskTableMgr::AchievementTaskTableMgr()
References Load.
Referenced by Get.
AchievementTaskTableMgr::~AchievementTaskTableMgr()
References m_kAchievementTaskTableMap.
const AchievementTaskTable * AchievementTaskTableMgr::GetAchievementTaskTable(unsigned int iTypeID)
References m_kAchievementTaskTableMap.
Referenced by AchieveFinishMgr::loadData.
const std::map< unsigned int, AchievementTaskTable * > & AchievementTaskTableMgr::GetAchievementTaskTableMap()
References m_kAchievementTaskTableMap.
Referenced by TableMgr::LoadAchieveInfo.
TableResArray AchievementTaskTableMgr::GetAchievementTaskTableVec()
References m_kAchievementTaskTableMap, TableResArray::pushBack.
bool AchievementTaskTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AchievementTaskTableMgr.
void AchievementTaskTableMgr::FillData(AchievementTaskTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AchievementTaskTable::iAchievement_Point, AchievementTaskTable::iMapList, AchievementTaskTable::iOpen, AchievementTaskTable::iReward_Icon, AchievementTaskTable::iSummoners_Level, AchievementTaskTable::iTaskSequence, AchievementTaskTable::iTravel_to, AchievementTaskTable::iValue_Number, AchievementTaskTable::kAchievement_Describe, AchievementTaskTable::kAchievement_Describe1, AchievementTaskTable::kAchievement_Icon, AchievementTaskTable::kAchievement_Name, AchievementTaskTable::kAchievement_Name1, m_kAchievementTaskTableMap, AchievementTaskTable::uiAchievement_fenlei, AchievementTaskTable::uiCondition, AchievementTaskTable::uiGameType, AchievementTaskTable::uiTask_ID, AchievementTaskTable::uiTaskgroups.
Referenced by Load.