ItemTableMgr
std::map<unsigned int, ItemTable*> ItemTableMgr::m_kItemTableMap
Referenced by FillData, GetItemTable, GetItemTableMap, GetItemTableVec, UpdateLanguadgeContent, ~ItemTableMgr.
std::set<unsigned int> ItemTableMgr::m_kDescFormatFlag
Referenced by GetItemTable.
ItemTableMgr * ItemTableMgr::m_pkItemTableMgr
Referenced by Get, ReLoad.
ItemTableMgr * ItemTableMgr::Get()
References ItemTableMgr, m_pkItemTableMgr.
Referenced by GlobalTableMgr::GetItemTable, TableMgr::LoadTable, ReLoad, TableMgr::UpdateLanguageContent.
ItemTableMgr * ItemTableMgr::ReLoad()
References Get, m_pkItemTableMgr.
Referenced by TableMgr::ReloadTable.
ItemTableMgr::ItemTableMgr()
References Load.
Referenced by Get.
ItemTableMgr::~ItemTableMgr()
References m_kItemTableMap.
const ItemTable * ItemTableMgr::GetItemTable(unsigned int iTypeID)
References EvalFormatElement, ItemFormatElement::Format, ItemTable::kBuyDesc, m_kDescFormatFlag, m_kItemTableMap, ItemFormatElement::Parse, ItemTable::uiItemTypeID.
Referenced by GlobalTableMgr::GetItemTable.
const std::map< unsigned int, ItemTable * > & ItemTableMgr::GetItemTableMap()
References m_kItemTableMap.
TableResArray ItemTableMgr::GetItemTableVec()
References m_kItemTableMap, TableResArray::pushBack.
void ItemTableMgr::EvalFormatElement(ItemFormatElement &ele)
References ItemFormatElement::cFiled, ItemFormatElement::cParentFiled, SkillTable::fAAdj, SkillTable::fBAdj, SkillTable::fCAdj, SkillTable::fDAdj, SkillTable::fEAdj, SkillTable::fFAdj, SkillTable::fValueA, SkillTable::fValueB, SkillTable::fValueC, SkillTable::fValueD, SkillTable::fValueE, SkillTable::fValueF, SkillTableMgr::Get, SkillTableMgr::GetSkillTable, SkillTable::iCoolDown, ItemFormatElement::iID, ItemFormatElement::iValue.
Referenced by GetItemTable.
void ItemTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, ItemTable::kBuyDesc, ItemTable::kBuyDescKey, ItemTable::kName, ItemTable::kNameKey, m_kItemTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool ItemTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by ItemTableMgr.
void ItemTableMgr::FillData(ItemTable *row, TiXmlElement *element)
References ItemTable::aiSkillID, TiXmlElement::Attribute, ItemTable::eClass, ItemTable::fPriceOfSell, ItemTable::fScale, ItemTable::iAutobuyOnlyOneItem, ItemTable::iItemLv, ItemTable::iItemType, ItemTable::iItemUIShowPos, ItemTable::iMaxPileCount, ItemTable::iOnlyOneItemG, ItemTable::iOrgPileCount, ItemTable::iOrgUseCount, ItemTable::iPriceOfBuy, ItemTable::iRecycleCD, ItemTable::iShareCDItem, ItemTable::iShowModelType, ItemTable::iStockCD, ItemTable::iUpgradeID, ItemTable::kBuyDescKey, ItemTable::kBuySimpleDesc, ItemTable::kIcon, ItemTable::kModelFile, ItemTable::kNameKey, ItemTable::kShopDetail, m_kItemTableMap, ItemTable::uiItemProperty, ItemTable::uiItemType, ItemTable::uiItemTypeID, ItemTable::uiShareItemID.
Referenced by Load.