WatchServer::SeTownMgr
MapAllTS WatchServer::SeTownMgr::m_kAllTS
Referenced by Finialize, GetAllTS, GetTown, GetTownNum, GetTownSockByArea, OnTSDisconnect, OnTSRegister, RefreshAreaNum.
int WatchServer::SeTownMgr::m_iTownArea
Referenced by GetTownArea, RefreshAreaNum, SeTownMgr.
SAreaID WatchServer::SeTownMgr::m_kAreaID
Referenced by GetAreaID, RefreshAreaNum.
SeTownMgr::SeTownMgr()
References m_iTownArea.
SeTownMgr::~SeTownMgr()
References Finialize.
bool SeTownMgr::Initialize(void)
void SeTownMgr::Update(void)
void SeTownMgr::Finialize(void)
References m_kAllTS, SAFE_DELETE.
Referenced by ~SeTownMgr.
bool SeTownMgr::OnTSRegister(const SeTown &kTown)
References WatchServer::SeTown::dwAreaID, WatchServer::SeTown::dwServerID, WatchServer::SeTown::iRegisterCount, m_kAllTS, RefreshAreaNum.
Referenced by WatchServer::CWatchServer::ProcessTWCMS_Register.
bool SeTownMgr::OnTSDisconnect(HTownSign &rkTownSign)
References m_kAllTS, RefreshAreaNum, SAFE_DELETE.
Referenced by WatchServer::CWatchServer::OnNetDisconnect.
int SeTownMgr::GetTownNum(void)
References m_kAllTS.
int SeTownMgr::GetTownArea(void)
References m_iTownArea.
const SeTown * SeTownMgr::GetTown(HTownSign &kTownSign)
References m_kAllTS.
Referenced by GetTownSockBySign, WatchServer::CWatchServer::ProcessTWCMS_Register.
SAreaID & SeTownMgr::GetAreaID()
References m_kAreaID.
HSock SeTownMgr::GetTownSockBySign(HTownSign &rkTownSign)
References GetTown, WatchServer::SeInnerConnect::kSock, WatchServer::SeTown::pkConnect.
HSock SeTownMgr::GetTownSockByArea(DWord dwAreaID)
References WatchServer::SeTown::dwAreaID, WatchServer::SeInnerConnect::kSock, m_kAllTS, WatchServer::SeTown::pkConnect.
MapAllTS & SeTownMgr::GetAllTS()
References m_kAllTS.
void SeTownMgr::RefreshAreaNum(void)
References WatchServer::SeTown::dwAreaID, m_iTownArea, m_kAllTS, m_kAreaID.
Referenced by OnTSDisconnect, OnTSRegister.