moba::ServerSessionMgr
Es::NormalLock moba::ServerSessionMgr::m_mutex
Ëø.
Referenced by broadcast, checkServer, createServer, deleteServer, getServerHSock, update.
TeNetMgr* moba::ServerSessionMgr::m_netMgr
Referenced by broadcast, initialize, ServerSessionMgr, update.
std::map<DWord, SeConnect*> moba::ServerSessionMgr::m_servers
Referenced by broadcast, checkServer, createServer, deleteServer, getServerHSock, update.
moba::ServerSessionMgr::ServerSessionMgr()
References m_netMgr.
moba::ServerSessionMgr::~ServerSessionMgr()
void moba::ServerSessionMgr::initialize(TeNetMgr &netMgr)
References m_netMgr.
Referenced by NexusServer::InitializeNet, WorldServer::InitializeNet.
void moba::ServerSessionMgr::createServer(SeConnect &pkConnect)
References moba::SeConnect::dwServerID, m_mutex, m_servers.
Referenced by NexusServer::ProcessMN_Register, WorldServer::ProcessMW_Register, WorldServer::ProcessNW_Register, NexusServer::ProcessRN_Register, WorldServer::ProcessRW_Register, NexusServer::ProcessTN_Register, WorldServer::ProcessTW_Register.
void moba::ServerSessionMgr::deleteServer(DWord dwServerID)
References m_mutex, m_servers.
Referenced by NexusServer::OnNetDisconnect, WorldServer::OnNetDisconnect.
bool moba::ServerSessionMgr::checkServer(DWord dwServerID)
References m_mutex, m_servers.
Referenced by NexusServer::ProcessMN_Register, WorldServer::ProcessMW_Register, WorldServer::ProcessNW_Register, NexusServer::ProcessRN_Register, WorldServer::ProcessRW_Register, NexusServer::ProcessTN_Register, WorldServer::ProcessTW_Register.
bool moba::ServerSessionMgr::getServerHSock(DWord dwServerID, HSock &kSock)
References m_mutex, m_servers.
Referenced by BlockServer::SendBLMData, BlockServer::SendBLRData, BlockServer::SendBLTData, WorldServer::SendWNData.
bool moba::ServerSessionMgr::getServerHSock(HSock &kSock)
References m_mutex, m_servers.
void moba::ServerSessionMgr::update()
References SeNetAddr::acIP, moba::DELAY_MAX_TIME, moba::SeConnect::dwServerID, moba::SeConnect::eIndex, GetID2Str, moba::Clock::getInstance, moba::Clock::getMilliSeconds, GetServerNameByIndex, SeNetAddr::iPort, moba::SeConnect::kNetAddr, moba::SeConnect::kSock, m_mutex, m_netMgr, m_servers, moba::SeConnect::recvTime, SeLogError.
Referenced by WorldServer::Update, NexusServer::UpdateConnect.
void moba::ServerSessionMgr::broadcast(void *pkData, int iSize)
References moba::SeConnect::kSock, m_mutex, m_netMgr, m_servers.
Referenced by NexusServer::SendNRData, NexusServer::SendNTData.