Json::Value::CZString
DuplicationPolicy
char const* Json::Value::CZString::cstr_
Referenced by CZString, operator<, operator==, swap.
union Json::Value::CZString::@2 Json::Value::CZString::@3
ArrayIndex Json::Value::CZString::index_
Referenced by operator<, operator==, swap.
StringStorage Json::Value::CZString::storage_
Referenced by CZString, operator<, operator==.
Json::Value::CZString::CZString(ArrayIndex index)
Json::Value::CZString::CZString(char const *str, unsigned length, DuplicationPolicy allocate)
References Json::Value::CZString::StringStorage::length_, Json::Value::CZString::StringStorage::policy_, storage_.
Json::Value::CZString::CZString(CZString const &other)
References cstr_, duplicate, Json::Value::CZString::StringStorage::length_, noDuplication, Json::Value::CZString::StringStorage::policy_, storage_.
Json::Value::CZString::~CZString()
References Json::releaseStringValue.
Value::CZString & Json::Value::CZString::operator=(CZString other)
References Json::Value::swap.
bool Json::Value::CZString::operator<(CZString const &other) const
References cstr_, index_, Json::Value::CZString::StringStorage::length_, storage_.
bool Json::Value::CZString::operator==(CZString const &other) const
References cstr_, index_, Json::Value::CZString::StringStorage::length_, storage_.
ArrayIndex Json::Value::CZString::index() const
Referenced by Json::ValueIteratorBase::index, Json::ValueIteratorBase::key.
const char * Json::Value::CZString::data() const
Referenced by Json::ValueIteratorBase::index, Json::ValueIteratorBase::key.
unsigned Json::Value::CZString::length() const
Referenced by Json::ValueIteratorBase::key.
bool Json::Value::CZString::isStaticString() const
Referenced by Json::ValueIteratorBase::key.
void Json::Value::CZString::swap(CZString &other)
References cstr_, index_.