SeRaceMgr
SeRaceQueryMgr
SeRaceRoomMgr
DWord SeRaceMgr::m_dwGenID
Referenced by GenSession, GetSession, ResetSession, SeRaceMgr.
SeTimer SeRaceMgr::m_kRaceTimer
Referenced by Initialize, Update.
SeTimer SeRaceMgr::m_kValidTimer
Referenced by Initialize, Update.
MRace SeRaceMgr::m_kMRace
Referenced by AddRace, DelRace, Finalize, GetRace, GetRaceByPlayerID, GetRaceNum, IsSessionExist, OnProcessReloadRoomList, OnProcessRSRegister, RaceUpdate.
int SeRaceMgr::m_iSvrAddFailCount
Referenced by SeRaceMgr, UpdateSvrStaCount.
DWord SeRaceMgr::m_dwLastRecordTime
Referenced by SeRaceMgr, UpdateSvrStaCount.
MWaitValidPlayer SeRaceMgr::m_kMWaitValidPlayer
Referenced by OnProcessReconViewValid, OnProcessViewQuerySuccess, ValidWaitUpdate.
DWord SeRaceMgr::m_dwGenRaceID
Referenced by CreateRobotRace, GenRaceID, GenRobotRaceID, OnRaceModeEnd.
MRace SeRaceMgr::m_kAllRace
Referenced by CreateRobotRace, GetCurrentRaceNum, GetNormalRaceNum, GetRace, GetRaceByID, OnRaceModeEnd, OnSvrRaceError, OnSvrRaceResult, OnSvrRaceSvrModelPack, ReflashWCSViewInfo, SaveAllRaceRecord, StartRobotRace.
bool SeRaceMgr::m_bCheating
Referenced by EnableCheating, IsCheating.
MRaceID2Result SeRaceMgr::m_kSvrModeResult
Referenced by OnSvrRaceResult, UpdateSvrRaceVerify.
VSeWSRaceSendInfo SeRaceMgr::m_kVVRaceSendInfo
Referenced by OnCheckRaceEnd.
VSeWSGuanqiaSendInfo SeRaceMgr::m_kVVGuanqiaSendInfo
MID2Count SeRaceMgr::m_kMSvrIndex2Count
Referenced by GetFreeThreadIndex, GetSvrModeRaceNum, OprSvrRaceNum.
std::map< int, int > SeRaceMgr::m_recvCMDCountMap
Referenced by CheckFreq, OnPlayerRaceCmd.
std::vector< DWord > SeRaceMgr::m_selHeroList
Referenced by GetRandHeroID, InitSelHeroList.
std::vector< DWord > SeRaceMgr::m_vRemovedWCSIDList
Referenced by ReflashWCSViewInfo, RemoveWCSView, UpdateView.
VSeWSGuanqiaSendInfo SeRaceMgr::m_kVVGuanqiaSendInfo
Referenced by OnCheckGuankaEnd, OnCheckGuanqiaEnd, UpdateSendRaceEndInfo.
VIncmpRaceArray SeRaceMgr::m_kVIncmpRaceArray
Referenced by AddIncmpRace, OnReqGetIncmpRaceList, RemoveIncmpRace.
MRoomID2SeatKDA SeRaceMgr::m_mRoomSeatKDA
Referenced by OnIncmpRaceKDA, RemoveIncmpRace.
SeRaceMgr::SeRaceMgr()
References m_dwGenID, m_dwLastRecordTime, m_iSvrAddFailCount.
SeRaceMgr::~SeRaceMgr()
bool SeRaceMgr::Initialize()
References m_kRaceTimer, m_kValidTimer, SeTimer::SetInterValue.
Referenced by RaceServer::Initialize.
void SeRaceMgr::Update(DWord dwServerTime)
References SeTimer::IsPassed, m_kRaceTimer, m_kValidTimer, RaceUpdate, SeTimer::Update, UpdateSvrStaCount, ValidWaitUpdate.
Referenced by MatchServer::Update, RaceServer::Update.
void SeRaceMgr::Finalize()
References m_kMRace.
Referenced by MatchServer::Finialize.
SeMatchRace * SeRaceMgr::CreatEmptyRace(DWord dwMapID)
References SeMatchRace::dwKey, SeMatchRace::dwLastRecvTime, SeMatchRace::dwMapID, SeMatchRace::dwMatchSession, SeMatchRace::eRaceState, g_kMatchServer, GenSession, GetEnterKey, MatchServer::GetServerTime, SMRS_LOAD.
Referenced by SeOpenRoomMgr::CreateRaceInfo.
void SeRaceMgr::AddRace(SeMatchRace *pkRace)
References SeMatchRace::dwMatchSession, m_kMRace.
Referenced by SeOpenRoomMgr::CreateRaceInfo.
bool SeRaceMgr::SendMatchCommMsg(SeMatchRace *pkRace, SeCommMatchMsg eMsg, DWord dwParam=0)
References SeMatchRace::akMRacePlayer, SeMatchRace::dwMatchSession, SeRacePlayer::dwPlayerID, g_kMatchServer, GetTownSock, SeRacePlayer::iRoomIndex, SeRacePlayer::kTownSign, MatchServer::SendMT_CommMatchMsg.
Referenced by SeOpenRoomMgr::CreateRaceInfo, OnProcessCommMsg, OnProcessCommRaceMsg, OnProcessValidateInfoRet, RaceUpdate.
void SeRaceMgr::OnProcessDetailInfoReturn(DWord dwSession, DWord dwPlayerID, SePtlMatchPlayer &rakMatchPlayer)
References SeRacePlayer::akPlayerInfo, SeMatchRace::bAllLoad, SeRacePlayer::bLoadEnd, GetRace, SeMatchRace::GetRacePlayerByID, SeMatchRace::IsAllPlayerLoad, SeLogError.
Referenced by MatchServer::ProcessBLM_RaceMatchLoadDetailRet.
void SeRaceMgr::OnProcessCommMsg(DWord dwSession, SeCommMatchMsg eMsg, DWord dwParam, int iParam)
References DelRace, GetRace, SCMM_NOTIFY_LOAD_FAILED, SCMM_REPORT_LOAD_FAILED, SeLogError, SendMatchCommMsg.
Referenced by MatchServer::ProcessTM_CommMatchMsg.
void SeRaceMgr::OnProcessReconQuery(SeTM_ReconQuery *pkQuery)
References SeTM_ReconQuery::dwAreaID, SeTM_ReconQuery::dwFrame, SeTM_ReconQuery::dwPlayerID, SeTM_ReconQuery::dwRoomID, SeTM_ReconQuery::dwServerID, g_kMatchServer, GetRace, GetRaceSvrSock, SeTM_ReconQuery::iOffset, SeTM_ReconQuery::iSeat, SeMatchRace::kRaceTownSign, MatchServer::SendMR_ReconQuery.
Referenced by MatchServer::ProcessTM_ReconQuery.
void SeRaceMgr::OnProcessViewQuery(SeTM_ViewQuery *pkQuery, HSock rkTownSock)
References SeTM_ViewQuery::dwAreaID, SeTM_ViewQuery::dwDstPlayerID, SeMatchRace::dwMatchSession, SeTM_ViewQuery::dwPlayerID, SeTM_ViewQuery::dwServerID, SeTM_ViewQuery::dwSession, g_kMatchServer, GetRace, GetRaceByPlayerID, GetRaceSvrSock, SeTM_ViewQuery::iViewDelay, SeMatchRace::kRaceTownSign, MatchServer::SendMR_ViewQuery, MatchServer::SendMT_ViewQueryFail, SVQF_NOT_RACING.
Referenced by MatchServer::ProcessTM_ViewQuery.
void SeRaceMgr::OnProcessValidateInfoRet(DWord dwSessionID, SeMatchValidateResult eResult)
References DelRace, SeMatchRace::dwLastRecvTime, SeMatchRace::eRaceState, g_kMatchServer, GetRace, MatchServer::GetServerTime, SCMM_ENTER_SEL_HERO, SCMM_NOTIFY_VALIDATE_FAILED, SeLogError, SendMatchAddrMsg, SendMatchCommMsg, SMRS_SEL_HERO, SMVR_LEAVE, SMVR_OK, SMVR_RECEIVE_OK, SMVR_REPEAT, SMVR_TIMEOUT.
Referenced by MatchServer::ProcessRM_ValidatePlayerInfoRet.
void SeRaceMgr::OnProcessUpdateMisc(SeRM_UpdateMisc *pkMisc, int iSize)
References HTownSign::dwAreaID, SeRM_UpdateMisc::dwParam1, SeRM_UpdateMisc::dwParam2, SeRM_UpdateMisc::dwPlayerID, HTownSign::dwServerID, SeRM_UpdateMisc::dwSession, SeRM_UpdateMisc::eType, g_kMatchServer, GetRace, SeMatchRace::GetRacePlayerByID, GetTownSock, SeRM_UpdateMisc::iValue, SeRacePlayer::kTownSign, MM_GAME_STATE, MM_VIEW_STATE, OnProcessReconPlayerInfo, MatchServer::SendMT_UpdateMisc.
Referenced by MatchServer::ProcessRM_UpdateMisc.
void SeRaceMgr::OnProcessRaceEndReport(SeRM_RaceEndReport *pkRaceEnd, int iSize)
References SeRM_RaceEndReport::akInfo, SeMatchRace::akMRacePlayer, HTownSign::dwAreaID, SeWSRaceSendInfo::dwAreaID, SeRM_RaceEndReport::dwMapID, SeRM_RaceEndReport::dwMatchSession, SeRM_RaceEndReport::dwTime, SeRM_RaceEndReport::eMatchType, g_kMatchServer, g_kTownMgr, GetRace, GetTownSignByAreaID, GetTownSock, SeTownMgr::GetTownSockByArea, SeRM_RaceEndReport::iNum, MatchServer::SendMT_RaceEndSend.
Referenced by MatchServer::ProcessRM_RaceEndReport.
void SeRaceMgr::OnProcessRaceEndGuanqia(SeRM_RaceEndGuanqia *pkRaceEnd, int iSize)
References SeRM_RaceEndGuanqia::akInfo, SeMatchRace::akMRacePlayer, HTownSign::dwAreaID, SeWSGuanqiaSendInfo::dwAreaID, SeRM_RaceEndGuanqia::dwMapID, SeRM_RaceEndGuanqia::dwMatchSession, SeRM_RaceEndGuanqia::dwTime, g_kMatchServer, g_kTownMgr, GetRace, GetTownSignByAreaID, GetTownSock, SeTownMgr::GetTownSockByArea, SeRM_RaceEndGuanqia::iNum, MatchServer::SendMT_GuanqiaEndSend.
Referenced by MatchServer::ProcessRM_RaceEndGuanqia.
void SeRaceMgr::OnProcessCommRaceMsg(DWord dwSession, SeRaceSvrCommMsg eMsg, DWord dwParam, int iParam)
References SeRacePlayer::bLeaveRace, DelRace, DoRaceOver, SeMatchRace::dwLastRecvTime, SeMatchRace::dwMatchSession, SeRacePlayer::dwTeamID, SeMatchRace::eRaceState, g_kMatchServer, g_kRaceQueryMgr, GetRace, SeMatchRace::GetRacePlayerByID, MatchServer::GetServerTime, GetTownSock, SeRacePlayer::iRoomIndex, SeMatchRace::iRoomIndex, SeRacePlayer::iSeatIndex, SeRacePlayer::kTownSign, SeRaceQueryMgr::OnCreateRoom, SeRaceQueryMgr::OnRaceSeatUpdateReverse, SeRaceQueryMgr::OnRaceSeatUpdateState, SCMM_NOTIFY_LEAVE_RACE, SCMM_NOTIFY_RACE_ESCAPE, SendMatchCommMsg, MatchServer::SendMT_CommMatchMsg, SMRS_RACING, SRCM_BEGIN_RACE, SRCM_BREAK_RACE, SRCM_END_RACE, SRCM_LEAVE_RACE, SRCM_UPDATE_REVERSE.
Referenced by MatchServer::ProcessRM_CommRaceMsg.
void SeRaceMgr::OnProcessReconQuerySuccess(SeRM_ReconQuerySuccess *pkQuery)
References SeRM_ReconQuerySuccess::dwAreaID, SeMatchRace::dwKey, SeMatchRace::dwMatchSession, SeRM_ReconQuerySuccess::dwPlayerID, SeRM_ReconQuerySuccess::dwRoomID, SeRM_ReconQuerySuccess::dwServerID, g_kMatchServer, g_kRaceSvrMgr, GetRace, SeRaceSvrMgr::GetRaceSvr, GetTownSock, SeRM_ReconQuerySuccess::iSeat, SeRaceSvr::kAddrToMatch, SeRaceSvr::kAddrToMatchUdp, SeMatchRace::kRaceTownSign, MatchServer::SendMT_NotifyAddrToMatch, SRVT_RECON.
Referenced by MatchServer::ProcessRM_ReconQuerySuccess.
void SeRaceMgr::OnProcessViewQuerySuccess(SeRM_ViewQuerySuccess *pkQuery)
References HTownSign::dwAreaID, SeRM_ViewQuerySuccess::dwAreaID, SeWaitValidPlayer::dwCreateTime, SeWaitValidPlayer::dwKey, SeRM_ViewQuerySuccess::dwPlayerID, HTownSign::dwServerID, SeRM_ViewQuerySuccess::dwServerID, SeWaitValidPlayer::dwSession, SeRM_ViewQuerySuccess::dwSession, SeWaitValidPlayer::eValidType, g_kMatchServer, g_kRaceSvrMgr, GetEnterKey, GetRace, SeRaceSvrMgr::GetRaceSvr, MatchServer::GetServerTime, GetTownSock, SeWaitValidPlayer::iViewDelay, SeRM_ViewQuerySuccess::iViewDelay, SeRaceSvr::kAddrToMatch, SeRaceSvr::kAddrToMatchUdp, SeMatchRace::kRaceTownSign, SeWaitValidPlayer::kTownSign, m_kMWaitValidPlayer, MatchServer::SendMT_NotifyAddrToMatch, MatchServer::SendMT_ViewQueryFail, SRVT_VIEW, SVQF_COMMON.
Referenced by MatchServer::ProcessRM_ViewQuerySuccess.
void SeRaceMgr::OnProcessReconViewValid(SeRM_ReconViewValid *pkValid)
References HTownSign::dwAreaID, SeViewInitInfo::dwAreaID, SeWaitValidPlayer::dwKey, SeRM_ReconViewValid::dwKey, SeRM_ReconViewValid::dwPlayerID, SeViewInitInfo::dwPlayerID, HTownSign::dwServerID, SeViewInitInfo::dwServerID, SeRM_ReconViewValid::dwSession, SeRM_ReconViewValid::eValidType, g_kMatchServer, GetRace, GetRaceSvrSock, SeWaitValidPlayer::iViewDelay, SeViewInitInfo::iViewDelay, SeMatchRace::kRaceTownSign, SeWaitValidPlayer::kTownSign, m_kMWaitValidPlayer, MatchServer::SendMR_ValidFailRet, MatchServer::SendMR_ViewValidOKRet, SRVT_RECON.
Referenced by MatchServer::ProcessRM_ReconViewValid.
void SeRaceMgr::OnProcessReloadRoomList(HTownSign kRaceSign, int iNum, SeReLoadRoomInfo *pkRoomInfo)
References SeMatchRace::akMRacePlayer, SeReLoadRoomInfo::akPlayerInfo, SeRacePlayer::bLeaveRace, SeReLoadPlayerInfo::bLeaveRace, SeRacePlayer::bOwner, HTownSign::dwAreaID, SeReLoadPlayerInfo::dwAreaID, SeMatchRace::dwLastRecvTime, SeMatchRace::dwMapID, SeReLoadRoomInfo::dwMapID, SeMatchRace::dwMatchSession, SeRacePlayer::dwPlayerID, SeReLoadPlayerInfo::dwPlayerID, SeReLoadRoomInfo::dwRaceBeginTime, HTownSign::dwServerID, SeReLoadPlayerInfo::dwServerID, SeReLoadRoomInfo::dwSession, SeRacePlayer::eCamp, SeReLoadPlayerInfo::eCamp, SeMatchRace::eRaceState, g_kMatchServer, g_kRaceQueryMgr, MatchServer::GetServerTime, GetSession, SeRacePlayer::iRoomIndex, SeMatchRace::iRoomIndex, SeRacePlayer::iSeatIndex, SeReLoadPlayerInfo::iSeatIndex, IsSessionExist, SeReLoadPlayerInfo::iTownRoomIndex, SeMatchRace::kRaceTownSign, SeRacePlayer::kTownSign, m_kMRace, SeRaceQueryMgr::OnCreateRoom, SeRaceQueryMgr::OnReloadPlayerInfo, ResetSession, SMRS_RACING, SMRS_SEL_HERO, SSD_MAX_ROOM_PLAYER.
Referenced by MatchServer::ProcessRM_ReLoadRoomInfoList.
void SeRaceMgr::OnProcessMatchRaceLoad(SeRM_MatchRaceLoad *pkLoad)
References SeMatchRace::akMRacePlayer, HTownSign::dwAreaID, SeRM_MatchRaceLoad::dwMapID, SeRacePlayer::dwPlayerID, SeRM_MatchRaceLoad::dwRoomSession, g_kMatchServer, g_kTownMgr, GetRace, GetTownSock, SeTownMgr::GetTownSockByArea, SeRacePlayer::kTownSign, MatchServer::SendMT_MatchRaceLoad.
Referenced by MatchServer::ProcessRM_MatchRaceLoad.
bool SeRaceMgr::OnProcessRaceBuy(SeRM_RaceBuy *pkBuy)
References HTownSign::dwAreaID, SeRM_RaceBuy::dwParam1, SeRM_RaceBuy::dwParam2, SeRacePlayer::dwPlayerID, SeRM_RaceBuy::dwPlayerID, SeRM_RaceBuy::dwSession, g_kMatchServer, g_kTownMgr, GetRace, SeMatchRace::GetRacePlayerByID, GetTownSock, SeTownMgr::GetTownSockByArea, SeRM_RaceBuy::iType, SeRacePlayer::kTownSign, MatchServer::SendMT_RaceBuy.
Referenced by MatchServer::ProcessRM_RaceBuy.
void SeRaceMgr::OnProcessRaceBuyRet(SeTM_RaceBuyRet *pkBuy)
References SeTM_RaceBuyRet::bSuccess, SeTM_RaceBuyRet::dwParam1, SeTM_RaceBuyRet::dwParam2, SeTM_RaceBuyRet::dwPlayerID, SeTM_RaceBuyRet::dwSession, g_kMatchServer, GetRace, GetRaceSvrSock, SeTM_RaceBuyRet::iType, SeMatchRace::kRaceTownSign, MatchServer::SendMR_RaceBuyRet.
Referenced by MatchServer::ProcessTM_RaceBuyRet.
void SeRaceMgr::OnProcessAddIncompleteRace(DWord dwSession, DWord dwPlayerID, int iSeat)
References SeMatchRace::dwMapID, g_kMatchServer, g_kRaceQueryMgr, GetRace, SeMatchRace::GetRacePlayerByID, GetRoomIndexBySession, GetTownSock, SeRacePlayer::kTownSign, SeRaceQueryMgr::OnProcessAddIncompleteRace, SCMM_NOTIFY_LEAVE_RACE_WITHOUTREON, SeLogDebug, SeLogError, MatchServer::SendMT_CommMatchMsg.
Referenced by MatchServer::ProcessRM_AddIncompleteRace.
void SeRaceMgr::OnProcessRemoveIncompleteRace(DWord dwSession)
References g_kRaceQueryMgr, SeRaceQueryMgr::OnProcessRemoveIncompleteRace.
Referenced by MatchServer::ProcessRM_RemoveIncompleteRace.
void SeRaceMgr::OnProcessIncmpRaceKDA(DWord dwSession, SeRM_ResIncmpRaceSeatBaseInfo *pInfo)
References g_kRaceQueryMgr, GetRace, SeMatchRace::iRoomIndex, SeRaceQueryMgr::OnProcessIncmpRaceKDA, SeLogError.
Referenced by MatchServer::ProcessRM_ResIncmpRaceSeatBaseInfo.
void SeRaceMgr::OnProcessReconPlayerInfo(DWord dwSession, DWord dwPlayerID, int iSeat)
References SeMatchRace::akMRacePlayer, g_kRaceQueryMgr, GetRace, GetRoomIndexBySession, SeRaceQueryMgr::OnReconUpdatePlayerInfo.
Referenced by OnProcessUpdateMisc.
void SeRaceMgr::OnProcessReconPlayerName(DWord dwSession, DWord dwPlayerID, const char cName[])
References g_kMatchServer, GetRace, GetRaceSvrSock, SeMatchRace::kRaceTownSign, MatchServer::SendMR_ReconPLayerName.
Referenced by MatchServer::ProcessTM_ReconPLayerName.
SeMatchRace * SeRaceMgr::GetRace(DWord dwSession)
References m_kMRace.
Referenced by GetRoomIndexBySession, SeRaceQueryMgr::GetRoomList, OnBiVoiceCreateRoom, OnDecRespawnItem, OnPlayerItemChange, OnProcessAddIncompleteRace, OnProcessCommMsg, OnProcessCommRaceMsg, OnProcessDetailInfoReturn, OnProcessIncmpRaceKDA, OnProcessMatchRaceLoad, OnProcessRaceBuy, OnProcessRaceBuyRet, OnProcessRaceEndGuanqia, OnProcessRaceEndReport, OnProcessReconPlayerInfo, OnProcessReconPlayerName, OnProcessReconQuery, OnProcessReconQuerySuccess, OnProcessReconViewValid, OnProcessUpdateMisc, OnProcessValidateInfoRet, OnProcessViewQuery, OnProcessViewQuerySuccess, OnRaceEndArenaDetail, OnRaceEndGradeDetail, RaceServer::ProcessRC_AchievementCounts, SeOpenRoomMgr::Update.
void SeRaceMgr::OnProcessRSRegister(HTownSign kTownSign)
References SeMatchRace::dwMatchSession, HTownSign::dwServerID, g_kRaceQueryMgr, GetID2Str, SeMatchRace::iRoomIndex, SeMatchRace::kRaceTownSign, m_kMRace, SeRaceQueryMgr::OnDestroyRoom, SeLogInfo.
Referenced by SeRaceSvrMgr::OnRSRegister.
int SeRaceMgr::GetRaceNum()
References m_kMRace.
Referenced by MatchServer::ShowConsoleTitle.
int SeRaceMgr::GetRoomIndexBySession(DWord dwSession)
References GetRace, SeMatchRace::iRoomIndex.
Referenced by OnProcessAddIncompleteRace, OnProcessReconPlayerInfo, MatchServer::ProcessRM_MatchRoomLoadInfo.
void SeRaceMgr::OnBiVoiceCreateRoom(DWord dwSession, int iRoomID)
References SeMatchRace::akMRacePlayer, SeRacePlayer::dwPlayerID, g_kMatchServer, g_kRaceSvrMgr, GetRace, SeRaceSvrMgr::GetRaceSvr, GetTownSock, SeMatchRace::iBiVoiceRoomID, SeMatchRace::kRaceTownSign, SeRacePlayer::kTownSign, SeLogInfo, MatchServer::SendMT_BiVoiceEnterInfo.
Referenced by MatchServer::ProcessHS_BiVoiceCreateChatRoomRet.
SeRaceMgr::SeRaceMgr()
SeRaceMgr::~SeRaceMgr()
bool SeRaceMgr::Initialize()
void SeRaceMgr::Update(DWord dwServerTime)
void SeRaceMgr::Finalize()
SeMatchRace* SeRaceMgr::CreatEmptyRace(DWord dwMapID)
void SeRaceMgr::AddRace(SeMatchRace *pkRace)
bool SeRaceMgr::SendMatchCommMsg(SeMatchRace *pkRace, SeCommMatchMsg eMsg, DWord dwParam=0)
void SeRaceMgr::OnProcessDetailInfoReturn(DWord dwSession, DWord dwPlayerID, SePtlMatchPlayer &rakMatchPlayer)
void SeRaceMgr::OnProcessCommMsg(DWord dwSession, SeCommMatchMsg eMsg, DWord dwParam, int iParam)
void SeRaceMgr::OnProcessReconQuery(SeTM_ReconQuery *pkQuery)
void SeRaceMgr::OnProcessViewQuery(SeTM_ViewQuery *pkQuery, HSock rkTownSock)
void SeRaceMgr::OnProcessValidateInfoRet(DWord dwSessionID, SeMatchValidateResult eResult)
void SeRaceMgr::OnProcessUpdateMisc(SeRM_UpdateMisc *pkMisc, int iSize)
void SeRaceMgr::OnProcessRaceEndReport(SeRM_RaceEndReport *pkRaceEnd, int iSize)
void SeRaceMgr::OnProcessRaceEndGuanqia(SeRM_RaceEndGuanqia *pkRaceEnd, int iSize)
void SeRaceMgr::OnProcessCommRaceMsg(DWord dwSession, SeRaceSvrCommMsg eMsg, DWord dwParam, int iParam)
void SeRaceMgr::OnProcessReconQuerySuccess(SeRM_ReconQuerySuccess *pkQuery)
void SeRaceMgr::OnProcessViewQuerySuccess(SeRM_ViewQuerySuccess *pkQuery)
void SeRaceMgr::OnProcessReconViewValid(SeRM_ReconViewValid *pkValid)
void SeRaceMgr::OnProcessReloadRoomList(HTownSign kRaceSign, int iNum, SeReLoadRoomInfo *pkRoomInfo)
void SeRaceMgr::OnProcessMatchRaceLoad(SeRM_MatchRaceLoad *pkLoad)
bool SeRaceMgr::OnProcessRaceBuy(SeRM_RaceBuy *pkBuy)
void SeRaceMgr::OnProcessRaceBuyRet(SeTM_RaceBuyRet *pkBuy)
void SeRaceMgr::OnProcessAddIncompleteRace(DWord dwSession, DWord dwPlayerID, int iSeat)
void SeRaceMgr::OnProcessRemoveIncompleteRace(DWord dwSession)
void SeRaceMgr::OnProcessIncmpRaceKDA(DWord dwSession, SeRM_ResIncmpRaceSeatBaseInfo *pInfo)
void SeRaceMgr::OnProcessReconPlayerInfo(DWord dwSession, DWord dwPlayerID, int iSeat)
void SeRaceMgr::OnProcessReconPlayerName(DWord dwSession, DWord dwPlayerID, const char cName[])
SeMatchRace* SeRaceMgr::GetRace(DWord dwSession)
void SeRaceMgr::OnProcessRSRegister(HTownSign kTownSign)
int SeRaceMgr::GetRaceNum()
int SeRaceMgr::GetRoomIndexBySession(DWord dwSession)
void SeRaceMgr::OnBiVoiceCreateRoom(DWord dwSession, int iRoomID)
SeRaceMgr::SeRaceMgr(void)
SeRaceMgr::~SeRaceMgr(void)
bool SeRaceMgr::Initialize(void)
void SeRaceMgr::Update(void)
References UpdateSendRaceEndInfo.
void SeRaceMgr::Finialize(void)
void SeRaceMgr::OnPlayerGuankaEnd(SePlayer *pkPlayer, DWord dwMapID, DWord dwRaceTime, bool bValied, int iNum, SeGuanqiaSendInfo *akInfo)
References SeGuankaEndCheck::akInfo, SeGuankaEndCheck::bValid, SeGuankaEndCheck::dwMapID, SeGuankaEndCheck::dwPlayerID, SePlayer::GetID, OnCheckGuankaEnd.
Referenced by TownServer::ProcessCT_RaceEndGuanka.
void SeRaceMgr::OnCheckGuankaEnd(SeGuankaEndCheck &kGuankaCheck)
References SeGuankaEndCheck::akInfo, SeGuankaEndCheck::bValid, SeGuankaEndCheck::dwGameTime, SeGuankaEndCheck::dwMapID, SeGuankaEndCheck::dwPlayerID, SeWSGuanqiaSendInfo::dwPlayerID, g_kTownServer, TownServer::IsWSReady, SeWSGuanqiaSendInfo::kInfo, m_kVVGuanqiaSendInfo, TownServer::SendTW_RaceEndGuanka.
Referenced by OnPlayerGuankaEnd.
void SeRaceMgr::AddIncmpRace(const SeIncompleteRaceBaseInfo &rData)
References SeIncompleteRaceBaseInfo::dwRoomID, m_kVIncmpRaceArray, SeLogError.
Referenced by TownServer::ProcessMT_AddIncompleteRace.
void SeRaceMgr::RemoveIncmpRace(DWord dwRoomSession)
References m_kVIncmpRaceArray, m_mRoomSeatKDA.
Referenced by TownServer::ProcessMT_RemoveIncompleteRace.
void SeRaceMgr::OnIncmpRaceKDA(DWord iRoomSession, SeSeatBaseInfo vSeatData[], int iNum)
References m_mRoomSeatKDA.
void SeRaceMgr::OnReqGetIncmpRaceList(const SePlayer &rkPlayer)
References g_kTownServer, SePlayer::GetClientID, SePlayer::GetID, m_kVIncmpRaceArray, SeLogDebug, TownServer::SendTC_ResIncompleteRaceList.
SeRaceMgr::SeRaceMgr(void)
SeRaceMgr::~SeRaceMgr(void)
bool SeRaceMgr::Initialize(void)
void SeRaceMgr::Update(void)
void SeRaceMgr::Finialize(void)
void SeRaceMgr::OnPlayerGuankaEnd(SePlayer *pkPlayer, DWord dwMapID, DWord dwRaceTime, bool bValied, int iNum, SeGuanqiaSendInfo *akInfo)
void SeRaceMgr::OnCheckGuankaEnd(SeGuankaEndCheck &kGuankaCheck)
void SeRaceMgr::AddIncmpRace(const SeIncompleteRaceBaseInfo &rData)
void SeRaceMgr::RemoveIncmpRace(DWord dwRoomSession)
void SeRaceMgr::OnIncmpRaceKDA(DWord iRoomSession, SeSeatBaseInfo vSeatData[], int iNum)
void SeRaceMgr::OnReqGetIncmpRaceList(const SePlayer &rkPlayer)
SeRaceMgr::SeRaceMgr(void)
SeRaceMgr::~SeRaceMgr(void)
bool SeRaceMgr::Initialize()
void SeRaceMgr::Update(void)
void SeRaceMgr::Finialize(void)
TeMD5 SeRaceMgr::OnRaceModeEnd(SeRaceRoom *pkRoom, SeMatchRaceSelTask *pkTask)
References SeRace::abyEnKey, SeRaceLoad::acData, SeRacePlayer::acName, SePlayerInfoSeat::acName, SeMatchReconMgr::AddPlayer, SeRacePlayer::akAchievementCounts, SeLoadSeat::akAchievementCounts, SeRacePlayer::akAllGetedAchievementIDs, SeLoadSeat::akAllGetedAchievementIDs, SeRacePlayer::akEquipItem, SeLoadSeat::akEquipItem, SeMatchRaceSelTask::akPlayerSelResult, SeRace::akRaceLoadData, SeRace::akRacePlayer, SeMatchRaceSelTask::akRebotSel, SeRacePlayerInfo::akSeat, SeNetStream::Attach, SeRace::bAutoMatchRace, SeRacePlayerInfo::bIsServerMode, SeRaceLoad::bIsServerMode, SeRacePlayer::bLeaveRace, SeRace::bRecordSendOver, SeRaceRoom::bRobot, SeRace::bSvrModeRace, SeRaceRoom::bSvrRace, SeRaceRoomMgr::ChangeRoomState, SeRaceRoom::DelDroppedPlayer, SeRacePlayer::dwAreaID, SeRace::dwBeginTime, SeRebotSelHero::dwHeroCardID, SeRacePlayer::dwHeroTypeID, SeLoadSeat::dwHeroTypeID, SeSelectResult::dwHeroTypeID, SeRaceRoom::dwID, SeRaceRoom::dwMapID, SeRace::dwMapID, SeRacePlayer::dwOrgPlayerID, SeRace::dwPackIndex, SeRacePlayer::dwPlayerID, SeSelectResult::dwPlayerID, SePlayerInfoSeat::dwPlayerID, SeRacePlayer::dwRespawnItemCount, SeLoadSeat::dwRespawnItemCount, SeRaceRoom::dwScoreCampA, SeRace::dwScoreCampA, SeRaceRoom::dwScoreCampB, SeRace::dwScoreCampB, SeRaceRoom::dwScoreRobot, SeRace::dwScoreRobot, SeRacePlayer::dwTeamID, SePlayerInfoSeat::dwTeamID, SeRacePlayer::eCamp, SeLoadSeat::eCamp, SeRebotSelHero::eCamp, SeSelectResult::eCamp, SeRaceRoom::eMatchType, SeRace::eMatchType, SeRace::eServerRaceResult, SeRace::eState, SePtlRaceBetInfo::fAddtionA, SePtlRaceBetInfo::fAddtionB, SeRaceLoad::fBetOddsA, SeRaceLoad::fBetOddsB, SeRace::fillSeatPlayers, SePtlRaceBetInfo::fOddsA, SePtlRaceBetInfo::fOddsB, g_kMatchReconMgr, g_kRaceRoomMgr, g_kRaceServer, GenEncryptKey, GenRaceID, MapInfoTableMgr::Get, SeMatchPlayer::GetAchievementCounts, SeMatchPlayer::GetAchievementCountsIDs, SeMatchPlayer::GetAreaID, SeNetStream::GetCurPos, SeMatchPlayer::GetDiamond, SeRaceRoom::GetDroppedPlayer, SeMatchPlayer::GetEquipItem, SeMatchPlayer::GetExp, GetFreeThreadIndex, SeMatchPlayer::GetGold, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, GetID2Str, MapInfoTableMgr::GetMapInfoTable, SeMatchPlayer::GetMatchFightInfo, SeMatchPlayer::GetName, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetRaceArenaTime, SeMatchPlayer::GetRaceCumuGolds, SeRaceRoomMgr::GetRandID, SeMatchPlayer::GetRespawnItemCount, SeMatchPlayer::GetScoreInfo, SeMatchPlayer::GetSelHeroAvatar, RaceServer::GetServerID, RaceServer::GetServerTime, SeMatchPlayer::GetTeamID, SeMatchPlayer::GetTeamMemberNum, SeRaceLoad::iBetAdditionA, SeRaceLoad::iBetAdditionB, MapInfoTable::iCampNum, SeRaceLoad::iConstellIDA, SePtlRaceBetInfo::iConstellIDA, SeRaceLoad::iConstellIDB, SePtlRaceBetInfo::iConstellIDB, SeRaceLoad::iDataSize, SeRacePlayer::iDecMoney, SeSelectResult::iDecMoney, SeRacePlayer::iDiamond, SeRaceRoom::iDifficulty, SeRace::iDifficulty, SeRaceLoad::iDifficulty, SeRacePlayer::iExp, SeRacePlayer::iGold, SeMatchFightInfo::iLeagueScore, SeRaceLoad::iMapID, MapInfoTable::iMaxPlayer, SeRacePlayerInfo::iNum, SeRacePlayer::iRaceArenaTime, SeRacePlayer::iRaceCumuGolds, SeRace::iRoomIndex, SeRacePlayer::iSeatIndex, SeLoadSeat::iSeatIndex, SePlayerInfoSeat::iSeatIndex, SeRace::iSeed, SeRacePlayer::iTeamMemberNum, SeRace::iThreadIndex, SeRacePlayer::kFightInfo, SeRacePlayer::kHeroAvatar, SeLoadSeat::kHeroAvatar, SeRace::kInfo, SeRacePlayer::kPlayerSock, SeRaceRoom::kRaceBet, SeRace::kRaceBet, SeRaceRoom::kRaceID, SeRace::kRaceID, SeRaceLoad::kRaceID, SeRace::kRecord, SeRacePlayer::kScoreInfo, SeUDPSender::kSock, SeRace::kSvrModeRecord, m_dwGenRaceID, m_kAllRace, MNew, SeRaceRecord::OnHostStart, RaceServer::OnSendMatchRoomLoadInfo, SeRaceRoom::pkMapInfoRes, SeRace::pkMapRes, SeRaceRecord::PushRaceCmd, SeRaceRecord::PushRacePack, RaceServer::PushRSC_RaceInit, RaceServer::PushRSC_RaceStream, RAS_LOADING, SeLogError, SeLogInfo, RaceServer::SendRC_RacePack, SeLoadSeat::SetSeatFlag, SLSF_PLAYER, SLSF_ROBOT, SPrintf, SRPC_CAMPA, SRRS_LOADING, SSD_EN_KEY_LEN, SSD_ENDSTR_LEN, SSD_MAX_ROOM_PLAYER, SSRR_NORMAL, StrCpy, SePlayerInfoSeat::uiScore, Write.
Referenced by SeRaceRoomMgr::StartLoad.
void SeRaceMgr::OnCheckRaceEnd(SeRace *pkRace, SeRaceEndCheck &kRaceCheck)
References TeMD5::abyMD5, SeWSRaceSendInfo::abyRaceID, SeRaceEndCheck::akInfo, SeVWSRaceSendInfo::akInfo, SeRace::bAutoMatchRace, SeWSRaceSendInfo::bAutoMatchRace, SeRacePlayer::dwAreaID, SeWSRaceSendInfo::dwAreaID, SeRaceEndCheck::dwGameTime, SeRace::dwMapID, SeWSRaceSendInfo::dwMapID, SeVWSRaceSendInfo::dwMatchSession, SeRacePlayer::dwOrgPlayerID, SeWSRaceSendInfo::dwOrgPlayerID, SeRacePlayer::dwPlayerID, SeWSRaceSendInfo::dwPlayerID, SeWSRaceSendInfo::dwRaceTime, SeRacePlayer::eCamp, SeWSRaceSendInfo::eCmp, SeRace::eMatchType, SeWSRaceSendInfo::eRaceModel, g_kRaceServer, GetMD52Str, GetRacePlayerBySeat, SeRaceSendInfo::iGold, SeWSRaceSendInfo::iLeagueMMR, SeMatchFightInfo::iLeagueMMR, SeWSRaceSendInfo::iLeagueScore, SeMatchFightInfo::iLeagueScore, SeWSRaceSendInfo::iOtherLeagueScore, SeMatchFightInfo::iOtherLeagueScore, SeRace::iRoomIndex, SeRaceSendInfo::iScore, SeRaceSendInfo::iSeatIndex, RaceServer::IsMSReady, SeRacePlayer::iTeamMemberNum, SeWSRaceSendInfo::iTeamMemberNum, SeRacePlayer::kFightInfo, SeWSRaceSendInfo::kInfo, SeRace::kRaceID, m_kVVRaceSendInfo, SeLogInfo, RaceServer::SendRM_RaceEndReport, SRM_ALLRANDOM, SSD_RACEBET_MAP.
Referenced by LocalCheckEnd_Race, UpdateSvrRaceVerify.
void SeRaceMgr::OnCheckGuanqiaEnd(SeRace *pkRace, SeGuankaEndCheck &kGuankaCheck)
References TeMD5::abyMD5, SeWSGuanqiaSendInfo::abyRaceID, SeGuankaEndCheck::akInfo, SeVWGuanqiaSendInfo::akInfo, SeRace::bAutoMatchRace, SeWSGuanqiaSendInfo::bAutoMatchRace, SeGuankaEndCheck::bValid, SeRacePlayer::dwAreaID, SeWSGuanqiaSendInfo::dwAreaID, SeGuankaEndCheck::dwGameTime, SeRace::dwMapID, SeWSGuanqiaSendInfo::dwMapID, SeVWGuanqiaSendInfo::dwMatchSession, SeRacePlayer::dwPlayerID, SeWSGuanqiaSendInfo::dwPlayerID, SeWSGuanqiaSendInfo::dwRaceTime, g_kRaceServer, GetMD52Str, GetRacePlayerBySeat, SeRace::iRoomIndex, SeGuanqiaSendInfo::iSeatIndex, RaceServer::IsMSReady, SeWSGuanqiaSendInfo::kInfo, SeRace::kRaceID, m_kVVGuanqiaSendInfo, RaceServer::SendRM_RaceEndGuanqia.
Referenced by LocalCheckEnd_Guanqia, UpdateSvrRaceVerify.
void SeRaceMgr::OnPlayerRaceLoadEnd(SeMatchPlayer *pkPlayer, DWord dwRate)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRacePlayer::dwLoadRate, SeRace::eState, g_kRaceServer, SeMatchPlayer::GetID, GetRaceByRoomIndex, GetRacePlayer, SeMatchPlayer::GetRoomSessionID, SeRacePlayer::iSeatIndex, SeRacePlayer::kPlayerSock, SeUDPSender::kSock, RAS_LOADING, RaceServer::SendRC_RacePlayerLoadEnd, SeMatchPlayer::SetPlayerState, SMPS_RACING, UpdateLoadEnd.
Referenced by RaceServer::ProcessCR_RaceLoadEnd.
bool SeRaceMgr::OnPlayerBuyRaceItem(SeMatchPlayer *pkPlayer, DWord dwItemTypeID, DWord dwTarUnitID)
References SeRace::eState, g_kRaceServer, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, GetRacePlayer, SeMatchPlayer::GetRoomSessionID, SeRacePlayer::iSeatIndex, RAS_RACING, RaceServer::SendRM_RaceBuy, SRBT_RACE_ITEM.
Referenced by RaceServer::ProcessCR_BuyRaceItem.
void SeRaceMgr::CheckFreq(void)
References CHECK_FREQ_TIME, m_recvCMDCountMap, SeLogInfo.
Referenced by OnPlayerRaceCmd.
void SeRaceMgr::OnPlayerRaceCmd(SeMatchPlayer *pkPlayer, void *pkData, int iSize)
References SeRace::bSvrModeRace, CheckFreq, SeRaceCmd::dwCmd, SeRaceCmd::dwFrame, SeRace::dwLastRecvCmdTime, SeRaceCmd::dwSeat, SeRace::eState, g_kRaceServer, SeRaceRecord::GetCurrentFrame, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, GetRacePlayer, SeMatchPlayer::GetRoomSessionID, RaceServer::GetServerTime, SeRacePlayer::iSeatIndex, SeRace::iThreadIndex, SeRace::kRaceID, SeRace::kRecord, m_recvCMDCountMap, SeRaceRecord::PushRaceCmd, RaceServer::PushRSC_RaceStream, RAS_RACING, SRC_PLAYER_GUANQIA_CMD.
Referenced by RaceServer::ProcessCR_BuyRaceItem, RaceServer::ProcessCR_RaceCmd, RaceServer::ProcessMR_RaceBuyRet.
void SeRaceMgr::OnPlayerRaceReplayReport(SeMatchPlayer *pkPlayer, void *pkData, int iSize)
References SeCR_ReplayReport::acMessage, SeCR_ReplayReport::Camera_x, SeCR_ReplayReport::Camera_y, SeRace::eState, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, GetRacePlayer, SeMatchPlayer::GetRoomSessionID, SeCR_ReplayReport::iReportFrame, SeRacePlayer::iSeatIndex, SeRace::kRecord, SeRaceRecord::PushRecordReport, RAS_RACING.
Referenced by RaceServer::ProcessCR_ReplayReport.
void SeRaceMgr::OnPlayerRaceLeave(SeMatchPlayer *pkPlayer, DWord dwKickFlag=0)
References SeMatchReconMgr::AddPlayer, SeRacePlayer::bLeaveRace, CheckValidRace, SeRacePlayer::dwPlayerID, SeRaceCmd::dwSeat, g_kMatchReconMgr, g_kRaceServer, SeMatchPlayer::GetID, SeMatchPlayer::GetName, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, RaceServer::GetRaceConfig, GetRacePlayer, SeMatchPlayer::GetRoomSessionID, SeRaceCmd_PlayerLeave::iConnectTime, SeRaceConfig::iMaxReconTime, SeMatchPlayer::IsRaceEndReport, SeRacePlayer::kPlayerSock, SeUDPSender::kSock, OnPlayerReconQuit, RaceServer::PushRSC_PlayerLeave, RaceServer::PushRSC_RaceStream, RAS_LOADING, RAS_RACING, SeLogDebug, SeLogInfo, RaceServer::SendRC_RacePack, UpdateLoadEnd, UpdateRaceEnd.
Referenced by RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, SeRaceRoomMgr::OnProcessRepeatPlayer, RaceServer::ProcessCR_RaceLeave, UpdateLoadingRace, UpdateReconEnd.
void SeRaceMgr::OnPlayerRaceEnd(SeMatchPlayer *pkPlayer, DWord dwRaceTime, bool bValied, int iNum, SeRaceSendInfo *akInfo)
References SeRacePlayer::akRaceEndInfo, SeRacePlayer::bLeaveRace, SeRacePlayer::bRaceEndReport, SeRace::bRaceEndReport, SeRace::bSvrModeRace, SeRacePlayer::bValied, SeRacePlayer::dwGameTime, SeRaceCmd::dwSeat, g_kRaceServer, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, GetRacePlayer, SeMatchPlayer::GetRoomSessionID, SeRace::iThreadIndex, SeRace::kRaceID, SeRace::kRecord, MAPINFO_TYPE_RACE, SeRace::pkMapRes, SeRaceRecord::PushRaceCmd, RaceServer::PushRSC_PlayerLeave, RaceServer::PushRSC_RaceStream, SeMatchPlayer::SetRaceEndReport, MapInfoTable::uiType, UpdateRaceEnd.
Referenced by RaceServer::ProcessCR_RaceEndRace.
void SeRaceMgr::OnPlayerGuanqiaEnd(SeMatchPlayer *pkPlayer, DWord dwRaceTime, bool bValied, int iNum, SeGuanqiaSendInfo *akInfo)
References SeRacePlayer::akGuanqiaEndInfo, SeRacePlayer::bLeaveRace, SeRacePlayer::bRaceEndReport, SeRace::bRaceEndReport, SeRace::bSvrModeRace, SeRacePlayer::bValied, SeRacePlayer::dwGameTime, SeRaceCmd::dwSeat, g_kRaceServer, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, GetRacePlayer, SeMatchPlayer::GetRoomSessionID, SeRace::iThreadIndex, SeRace::kRaceID, SeRace::kRecord, MAPINFO_TYPE_GUANQIA, SeRace::pkMapRes, SeRaceRecord::PushRaceCmd, RaceServer::PushRSC_PlayerLeave, RaceServer::PushRSC_RaceStream, SeMatchPlayer::SetRaceEndReport, MapInfoTable::uiType, UpdateRaceEnd.
Referenced by RaceServer::ProcessCR_RaceEndGuanqia.
void SeRaceMgr::OnPlayerReportSyn(SeMatchPlayer *pkPlayer, void *pkData, int iSize)
References SeRace::akRacePlayer, SeRacePlayer::akSynRand, SeRacePlayer::bLeaveRace, SeCR_RaceReportSyn::dwFrame, SeRacePlayer::dwPlayerID, SeRace::eState, g_kRaceRoomMgr, g_kRaceServer, SeMatchPlayer::GetID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, GetRacePlayer, SeMatchPlayer::GetRoomSessionID, SeSynInfo::iCount, SeCR_RaceReportSyn::iFrameRand, SeRacePlayer::iSeatIndex, SeSynInfo::iSynRand, MapInfoTable::kName, OnPlayerGameSynCheck, SeRace::pkMapRes, RaceServer::RandInt, RAS_RACING, RAS_RACING_PAUSE, SeLogError, SeLogInfo, SSD_MAX_ROOM_PLAYER, SSD_PRE_UPDATE_FRAME, SSD_SYN_FRAME.
Referenced by RaceServer::ProcessCR_RaceReportSyn.
bool SeRaceMgr::OnPlayerGameSynCheck(const SeRacePlayer *pkRacePlayer, const SeRace *pkRace, int iIndex, SeSynInfo *akSynInfo, int iSynInfo, int &riCount)
References SeRace::akRacePlayer, SeRacePlayer::akSynRand, SeRacePlayer::bLeaveRace, SeSynInfo::iCount, SeSynInfo::iSynRand.
Referenced by OnPlayerReportSyn.
void SeRaceMgr::OnPlayerReconBegin(int iRoomIndex, SeMatchPlayer *pkPlayer, bool bView, int iOffset, DWord dwFrame)
References SeRacePlayer::acName, SePlayerInfoSeat::acName, SePalyerReconBegin::acName, SeRace::akRaceLoadData, SeRace::akRacePlayer, SeRace::akRJoinPlayer, SeRacePlayerInfo::akSeat, SeRacePlayer::akSynRand, SeRace::akViewPlayer, SeReconJoinPlayer::bComplete, SeReconJoinPlayer::bDel, SeRacePlayerInfo::bIsServerMode, SeRacePlayer::bLeaveRace, SeRacePlayer::bRecon, SeRacePlayer::bReconRand, SeRace::bSvrModeRace, SeViewPlayer::dwFrame, SeReconJoinPlayer::dwFrame, SeRacePlayer::dwPlayerID, SeViewPlayer::dwPlayerID, SeReconJoinPlayer::dwPlayerID, SePlayerInfoSeat::dwPlayerID, SePalyerReconBegin::dwPlayerID, SeRacePlayer::dwTeamID, SePlayerInfoSeat::dwTeamID, SeRace::eServerRaceResult, g_kRaceRoomMgr, g_kRaceServer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, SeMatchPlayer::GetName, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, GetRacePlayerBySeat, SeMatchFightInfo::iLeagueScore, SeRacePlayerInfo::iNum, SeViewPlayer::iOffset, SeReconJoinPlayer::iOffset, SeReconJoinPlayer::iSeat, SeRacePlayer::iSeatIndex, SePlayerInfoSeat::iSeatIndex, SePalyerReconBegin::iSeatIndex, SeRace::iThreadIndex, SeRacePlayer::kFightInfo, MapInfoTable::kName, SeRacePlayer::kPlayerSock, SeReconJoinPlayer::kPlayerSock, SeRace::kRaceID, SeUDPSender::kSock, MNew, OnPlayerView2Recon, SeRace::pkMapRes, RaceServer::PushRSC_PlayerRelink, RaceServer::PushRSC_RaceStream, SeLogInfo, RaceServer::SendRC_RacePack, RaceServer::SendRC_ReconResult, SRRT_BEGIN, StrCpy, SePlayerInfoSeat::uiScore, UpdateReconEnd.
Referenced by SeRaceRoomMgr::JoinRoomRecon.
void SeRaceMgr::OnPlayerRaceViewBegin(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, int iRoomSession)
References SePlayerInfoSeat::acName, SeRace::akRacePlayer, SeRC_ViewPlayerInfo::akSeat, SeRace::akViewPlayer, SeViewPlayer::dwPlayerID, SePlayerInfoSeat::dwPlayerID, g_kRaceServer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, GetRaceByRoomIndex, SeViewPlayer::iDelay, SeRC_ViewPlayerInfo::iNum, SePlayerInfoSeat::iSeatIndex, SeViewPlayer::kPlayerSock, SeRaceRoom::kRaceID, SeUDPSender::kSock, MNew, RaceServer::SendRC_ViewPlayerInfo, RaceServer::SendRC_ViewResult, SeMatchPlayer::SetRaceID, StrCpy, SVRT_BEGIN.
Referenced by SeRaceRoomMgr::BeginRaceView.
void SeRaceMgr::OnPlayerView2Recon(SeMatchPlayer *pkPlayer)
References SeRace::akViewPlayer, g_kRaceRoomMgr, SeMatchPlayer::GetHSock, GetRaceByID, SeMatchPlayer::GetRaceID, SeMatchPlayer::GetRoomSessionID, SeRaceRoomMgr::LeaveRaceView.
Referenced by OnPlayerReconBegin.
void SeRaceMgr::OnPlayerViewQuit(SeMatchPlayer *pkPlayer)
References SeRace::akViewPlayer, g_kRaceServer, SeMatchPlayer::GetHSock, GetRaceByID, SeMatchPlayer::GetRaceID, SeUDPSender::kSock, RaceServer::SendRC_ViewResult, SVRT_END.
Referenced by RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect.
bool SeRaceMgr::IsReconValidSeat(int iRoomIndex, int iSeat)
References SeRacePlayer::bLeaveRace, SeRace::eState, GetRaceByRoomIndex, GetRacePlayerBySeat, RAS_RACING, RAS_RACING_PAUSE.
Referenced by SeRaceRoomMgr::OnPlayerReconQuery.
bool SeRaceMgr::IsReconValidPlayer(int iRoomIndex, DWord dwPlayerID, int iSeat)
References SeRace::akRacePlayer, SeRace::akRJoinPlayer, SeRacePlayer::dwPlayerID, SeReconJoinPlayer::dwPlayerID, g_kRaceRoomMgr, GetRaceByID, SeRaceRoomMgr::GetRoom, SeRacePlayer::iSeatIndex, SeRaceRoom::kRaceID.
Referenced by SeRaceRoomMgr::OnPlayerReconQuery.
void SeRaceMgr::OnPlayerReconQuit(DWord dwPlayerID, TeMD5 &rkRaceID)
References SeRace::akRJoinPlayer, SeReconJoinPlayer::dwPlayerID, GetRaceByID.
Referenced by OnPlayerRaceLeave.
void SeRaceMgr::OnSvrRaceSvrModelPack(const TeMD5 &rkRaceID, const char *pcData, int iSize)
References SeRace::kSvrModeRecord, m_kAllRace, SeRaceRecord::PushRaceData.
Referenced by RaceServer::ProcessRC_RaceSvrModelPack.
void SeRaceMgr::OnSvrRaceResult(const TeMD5 &rkRaceID, const char *pcData, int iSize)
References SeRace::bRaceEndReport, m_kAllRace, m_kSvrModeResult, UpdateRaceEnd.
Referenced by RaceServer::ProcessRC_RaceEnd.
void SeRaceMgr::OnSvrRaceError(const TeMD5 &rkRaceID)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRace::bSvrRaceError, m_kAllRace.
Referenced by RaceServer::ProcessRC_RaceError.
void SeRaceMgr::UpdateSvrRaceVerify(SeRace *pkRace)
References SeGuankaEndCheck::akInfo, SeRaceEndCheck::akInfo, SeCR_RaceEndRace::akPlayerInfo, SeCR_RaceEndGuanqia::akPlayerInfo, SeRace::bRecordSendOver, SeRace::bSvrRaceError, SeGuankaEndCheck::bValid, SeRaceEndCheck::bValid, SeCR_RaceEndRace::bValid, SeCR_RaceEndGuanqia::bValid, SeGuankaEndCheck::dwGameTime, SeRaceEndCheck::dwGameTime, SeCR_RaceEndRace::dwRaceTime, SeCR_RaceEndGuanqia::dwRaceTime, SeRace::eState, SeRaceEndCheck::iCount, SeGuankaEndCheck::iCount, SeCR_RaceEndRace::iNums, SeCR_RaceEndGuanqia::iNums, SeRace::kRaceID, m_kSvrModeResult, MAPINFO_TYPE_GUANQIA, MAPINFO_TYPE_RACE, OnCheckGuanqiaEnd, OnCheckRaceEnd, SeRace::pkMapRes, RAS_VERIFY, RAS_VERIFY_END, SeLogInfo, MapInfoTable::uiType.
void SeRaceMgr::OnGetAchievement(const TeMD5 &rkRaceID, int iSeat, DWord aID, DWord aLvl)
References GetRaceByID, GetRacePlayerBySeat, SeLogDebug, SeLogError.
Referenced by RaceServer::ProcessRC_GetAchievement.
DWord SeRaceMgr::GetRaceTime(const TeMD5 &rkRaceID)
References SeRace::dwBeginTime, g_kRaceServer, GetRaceByID, RaceServer::GetServerTime.
Referenced by SeRaceRoomMgr::GetReloadRoomInfo.
void SeRaceMgr::OprSvrRaceNum(int iThreadIndex, int iOpr)
References m_kMSvrIndex2Count.
Referenced by RaceServer::ProcessRC_RaceOpr.
int SeRaceMgr::GetSvrModeRaceNum()
References m_kMSvrIndex2Count.
Referenced by GetNormalRaceNum, RaceServer::GetServerRunState.
int SeRaceMgr::GetNormalRaceNum()
References GetSvrModeRaceNum, m_kAllRace.
Referenced by RaceServer::GetServerRunState.
int SeRaceMgr::GetCurrentRaceNum()
References m_kAllRace.
Referenced by RaceServer::UpdateMSHeartPackage.
void SeRaceMgr::SaveAllRaceRecord(void)
References TeMD5::abyMD5, GetMD52Str, SeRace::kRaceID, SeRace::kRecord, SeRace::kSvrModeRecord, m_kAllRace, SeRaceRecord::SaveToFile, SPrintf.
SeRace * SeRaceMgr::GetRaceByRoomIndex(int iRoomSession, bool bRacing=true)
References g_kRaceRoomMgr, GetRaceByID, SeRaceRoomMgr::GetRoom, SeRaceRoom::kRaceID.
Referenced by SeMatchReconMgr::GetReconPlayer, IsReconValidSeat, OnGetHeroInfo, OnPlayerBuyRaceItem, OnPlayerGuanqiaEnd, OnPlayerRaceCmd, OnPlayerRaceEnd, OnPlayerRaceLeave, OnPlayerRaceLoadEnd, OnPlayerRaceReplayReport, OnPlayerRaceViewBegin, OnPlayerReconBegin, OnPlayerReportSyn, SeMatchReconMgr::RemoveRace, SeMatchReconMgr::Update.
void SeRaceMgr::OnGetHeroInfo(SeMatchPlayer *pkPlayer)
References g_kRaceServer, SeMatchPlayer::GetPlayerSeat, GetRaceByRoomIndex, SeMatchPlayer::GetRoomSessionID, SeRace::iThreadIndex, SeRace::kRaceID, RaceServer::PushRSC_GetHeroInfo.
Referenced by RaceServer::ProcessCR_GetHeroInfo.
SeRacePlayer * SeRaceMgr::GetRacePlayerBySeat(SeRace *pkRace, int iSeat)
References SeRace::akRacePlayer, SeRacePlayer::iSeatIndex.
Referenced by SeRaceRoomMgr::GetReloadRoomInfo, IsReconValidSeat, OnCheckGuanqiaEnd, OnCheckRaceEnd, OnGetAchievement, OnPlayerReconBegin, RaceServer::ProcessRC_AchievementCounts, UpdateLoadEnd.
void SeRaceMgr::EnableCheating(bool bEnable)
References m_bCheating.
Referenced by RaceServer::ExecuteAction.
bool SeRaceMgr::IsCheating(void) const
References m_bCheating.
Referenced by RaceServer::ExecuteAction.
bool SeRaceMgr::IsValidRace(const SeRace *pkRace)
References SeRace::bVaildRace.
bool SeRaceMgr::CheckValidRace(SeRace *pkRace)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRace::bVaildRace, SeRacePlayer::eCamp, SRPC_INVALID, SRPC_NUMS.
Referenced by OnPlayerRaceLeave.
SeRace * SeRaceMgr::GetRaceByID(const TeMD5 &rkRaceID, bool bRacing=true)
References SeRace::eState, m_kAllRace, RAS_RACING.
Referenced by RaceDetailMgr::CheckRaceRuler, RaceDetailMgr::CreateRaceDetail, GetRaceByRoomIndex, GetRaceTime, SeRaceRoomMgr::GetReloadRoomInfo, IsReconValidPlayer, SeRaceRoomMgr::IsValidRace, OnGetAchievement, OnPlayerReconQuit, OnPlayerView2Recon, SeRaceRoomMgr::OnPlayerViewQuery, OnPlayerViewQuit, OnRaceKDA, OnRealTimeRaceKDA, OnRealTimeRaceMapDetail, SeRaceRoomMgr::UpdateRaceEndTime, UpdateView.
SeRace * SeRaceMgr::GetRace(const TeMD5 &rkRaceID)
References m_kAllRace.
void SeRaceMgr::CreateRobotRace(int n)
References SeRace::abyEnKey, SeRaceLoad::acData, SeRace::akRaceLoadData, SeRace::akRacePlayer, SeNetStream::Attach, SeRace::bAutoMatchRace, SeRacePlayerInfo::bIsServerMode, SeRaceLoad::bIsServerMode, SeRace::bRecordSendOver, SeRace::bSvrModeRace, SeRace::dwBeginTime, SeLoadSeat::dwHeroTypeID, SeRace::dwMapID, SeRace::dwPackIndex, SeLoadSeat::eCamp, SeRace::eServerRaceResult, SeRace::eState, SePtlRaceBetInfo::fAddtionA, SePtlRaceBetInfo::fAddtionB, SeRaceLoad::fBetOddsA, SeRaceLoad::fBetOddsB, SePtlRaceBetInfo::fOddsA, SePtlRaceBetInfo::fOddsB, g_kRaceServer, GenEncryptKey, GenRaceID, GenRobotRaceID, MapInfoTableMgr::Get, SeNetStream::GetCurPos, GetFreeThreadIndexByNum, GetID2Str, MapInfoTableMgr::GetMapInfoTable, GetRandHeroID, RaceServer::GetServerID, RaceServer::GetServerTime, GetStr2ID, SeRaceLoad::iBetAdditionA, SeRaceLoad::iBetAdditionB, MapInfoTable::iCampNum, SeRaceLoad::iConstellIDA, SePtlRaceBetInfo::iConstellIDA, SeRaceLoad::iConstellIDB, SePtlRaceBetInfo::iConstellIDB, SeRaceLoad::iDataSize, SeRace::iDifficulty, SeRaceLoad::iDifficulty, SeRaceLoad::iMapID, MapInfoTable::iMaxPlayer, SeRacePlayerInfo::iNum, SeRace::iRoomIndex, SeLoadSeat::iSeatIndex, SeRace::iSeed, SeRace::isRobotRace, SeRace::iThreadIndex, SeRace::kInfo, SeRace::kRaceBet, SeRace::kRaceID, SeRaceLoad::kRaceID, SeRace::kRecord, SeRace::kSvrModeRecord, m_dwGenRaceID, m_kAllRace, MNew, SeRaceRecord::OnHostStart, SeRace::pkMapRes, SeRaceRecord::PushRaceCmd, SeRaceRecord::PushRacePack, RaceServer::PushRSC_RaceInit, RaceServer::PushRSC_RaceStream, RAS_LOADING, SeLogError, SeLogInfo, SeLoadSeat::SetSeatFlag, SLSF_ROBOT, SPrintf, SRPC_CAMPA, SSD_EN_KEY_LEN, SSD_ENDSTR_LEN, SSRR_NORMAL, Write.
Referenced by RaceServer::Initialize.
void SeRaceMgr::StartRobotRace(void)
References SeRace::isRobotRace, m_kAllRace, UpdateLoadEnd.
Referenced by RaceServer::Initialize.
void SeRaceMgr::ReflashWCSViewInfo(DWord dwWCSID, int Counts, const SeWCSViewInfo *pViewInfo)
References SeWCSViewInfo::dwFrame, SeWCSViewInfo::dwOffset, m_kAllRace, m_vRemovedWCSIDList, SeRace::m_WCSViewMap, RAS_VERIFY_END, SeLogInfo, TeMD5FromArray.
Referenced by RaceServer::ProcessWCSR_Register.
void SeRaceMgr::RemoveWCSView(DWord dwWCSID)
References m_vRemovedWCSIDList, SeLogInfo.
Referenced by RaceServer::OnWCSDisconnect.
void SeRaceMgr::OnPlayerItemChange(const TeMD5 &rkRaceID, const BePlayerItemChange &rInfo)
References TeMD5::abyMD5, SeRacePlayer::dwPlayerID, g_kRaceServer, GetMD52Str, GetRace, SeRace::getSeatPlayer, SeLogError, RaceServer::SendRBL_AwardItemNtf.
Referenced by RaceService::OnPlayerItemChange.
void SeRaceMgr::OnRaceEndGradeDetail(const TeMD5 &rkRaceID, const BeRaceGradeDetail &rInfo)
References TeMD5::abyMD5, calOdds, calRaceScore_Lose, calRaceScore_Win, calTimeCoef, SeRace::dwMapID, SeRacePlayer::dwPlayerID, SeRace::dwScoreCampA, SeRace::dwScoreCampB, SeRace::dwScoreRobot, EMT_LADDER, EMT_PVE, RankStageTable::fReduceProportion, g_kRaceServer, RankStageTableMgr::Get, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, GetMD52Str, GetRace, RankStageTableMgr::GetRankStageTable, SeRace::getSeatPlayer, SeSeatScore::iChanged, SeSeatScore::iOld, SeRacePlayer::kPlayerSock, SeRacePlayer::kScoreInfo, SeUDPSender::kSock, SeScoreInfo::level, SeScoreInfo::score, SeRC_SeatScoreNtf::scores, SeLogError, RaceServer::SendRBL_UpdateScore, RaceServer::SendRC_SeatScoreNtf, SSD_MAX_ROOM_PLAYER, MapInfoTable::uiMatchType.
Referenced by RaceService::OnRaceEndGradeDetail.
void SeRaceMgr::OnDecRespawnItem(const TeMD5 &rkRaceID, const BeDecRespawnItem &rInfo)
References TeMD5::abyMD5, SeRacePlayer::dwPlayerID, g_kRaceServer, GetMD52Str, GetRace, SeRace::getSeatPlayer, SeLogError, RaceServer::SendRBL_DecRespawnItemNtf.
Referenced by RaceService::OnDecRespawnItem.
void SeRaceMgr::OnRaceEndArenaDetail(const TeMD5 &rkRaceID, const BeRaceArenaDetail &rInfo)
References RaceDetailMgr::CheckRace_UserAttr_Bound, SeRacePlayer::dwHeroTypeID, SeRace::dwMapID, SeRaceEndArenaDetailInfo::dwMapID, SeRacePlayer::dwPlayerID, SeRaceEndArenaDetailInfo::dwPlayerID, SeRaceEndArenaBaseInfo::dwPlayerID, g_kRaceDetailMgr, g_kRaceServer, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, GetRace, SeRace::getSeatPlayer, SeRaceEndArenaDetailInfo::iAssists, SeRaceEndArenaDetailInfo::iBest, SeRaceEndArenaDetailInfo::iBlood_1, SeRaceEndArenaBaseInfo::iCumuGold, SeRaceEndArenaDetailInfo::iDies, SeRaceEndArenaDetailInfo::iEnemyEyes, SeRacePlayer::iExp, SeRaceEndArenaBaseInfo::iExp, SeRacePlayer::iGold, SeRaceEndArenaBaseInfo::iGold, SeRaceEndArenaDetailInfo::iKills, SeRaceEndArenaDetailInfo::iKills_3, SeRaceEndArenaDetailInfo::iKills_4, SeRaceEndArenaDetailInfo::iKills_5, SeRaceEndArenaDetailInfo::iMvp, SeRaceEndArenaDetailInfo::iPlaceEyes, SeRacePlayer::iRaceArenaTime, SeRacePlayer::iRaceCumuGolds, SeRaceEndArenaDetailInfo::iRaceFlag, SeRaceEndArenaDetailInfo::iRaceNum, SeRaceEndArenaDetailInfo::iSuper, SeRaceEndArenaDetailInfo::iTitle, SeRaceEndArenaDetailInfo::iTotalBeDamage, SeRaceEndArenaDetailInfo::iTotalDamage, SeRaceEndArenaDetailInfo::iTotalGold, SeRacePlayer::kPlayerSock, SeUDPSender::kSock, RaceDetailMgr::RaceUserAttr_Loss, RaceDetailMgr::RaceUserAttr_Win, SeLogDebug, SeLogError, RaceServer::SendRBL_RaceEndArenaBaseInfoSync, RaceServer::SendRBL_SetRaceMapHeroNtf, RaceServer::SendRBL_UserRaceMapNtf, RaceServer::SendRC_RaceGoldExpPlus, RaceServer::SendRC_ShowNotice, SNC_USER_WEEK_GOLD_LIMIT, SSD_MAX_ROOM_PLAYER.
Referenced by RaceService::OnRaceEndArenaDetail.
void SeRaceMgr::OnRealTimeRaceMapDetail(const TeMD5 &rkRaceID, const BeRaceBuildingStatus &rInfo)
References g_kRaceDetailMgr, GetRaceByID, RaceDetailMgr::GetRaceDetailMap, RaceDetailMgr::PushRaceDetail, SRaceDetail::race_info, SeRaceInfo::race_map, SeRaceMapInfo::race_map_building, RaceDetailMgr::SyncRaceDetail.
Referenced by RaceService::OnRealTimeRaceMapDetail.
void SeRaceMgr::OnRealTimeRaceKDA(const TeMD5 &rkRaceID, const BeAllHeroKDA &rInfo)
References SeRace::dwBeginTime, SeRaceUserHeroInfo::dwHeroID, g_kRaceDetailMgr, g_kRaceServer, SeRaceGameInfo::game_time, GetRaceByID, RaceDetailMgr::GetRaceDetailMap, SeRace::getSeatPlayer, RaceServer::GetServerTime, RaceDetailMgr::PushRaceDetail, SeRaceUserHeroInfo::race_assist, SeRaceUserHeroInfo::race_death, SeRaceInfo::race_game, SRaceDetail::race_info, SeRaceUserHeroInfo::race_kill, SeRaceGameInfo::race_mmr, SeRaceInfo::race_user, SeRaceUserInfo::race_user_hero, SeLogDebug, SSD_MAX_ROOM_PLAYER, RaceDetailMgr::SyncRaceDetail.
Referenced by RaceService::OnRealTimeRaceKDA.
void SeRaceMgr::OnRaceKDA(const TeMD5 &rkRaceID, const BeAllHeroKDA &rInfo)
References SeMatchReconMgr::CheckCon2OldRace, g_kMatchReconMgr, g_kRaceServer, GetRaceByID, SeRace::iRoomIndex, SeLogDebug, RaceServer::SendRM_ResIncmpRaceSeatBaseInfo.
Referenced by RaceService::OnRaceKDA.
SeRaceMgr::SeRaceMgr(void)
SeRaceMgr::~SeRaceMgr(void)
bool SeRaceMgr::Initialize()
void SeRaceMgr::Update(void)
void SeRaceMgr::Finialize(void)
TeMD5 SeRaceMgr::OnRaceModeEnd(SeRaceRoom *pkRoom, SeMatchRaceSelTask *pkTask)
void SeRaceMgr::OnCheckRaceEnd(SeRace *pkRace, SeRaceEndCheck &kRaceCheck)
void SeRaceMgr::OnCheckGuanqiaEnd(SeRace *pkRace, SeGuankaEndCheck &kGuankaCheck)
void SeRaceMgr::OnPlayerRaceLoadEnd(SeMatchPlayer *pkPlayer, DWord dwRate)
bool SeRaceMgr::OnPlayerBuyRaceItem(SeMatchPlayer *pkPlayer, DWord dwItemTypeID, DWord dwTarUnitID)
void SeRaceMgr::CheckFreq(void)
void SeRaceMgr::OnPlayerRaceCmd(SeMatchPlayer *pkPlayer, void *pkData, int iSize)
void SeRaceMgr::OnPlayerRaceReplayReport(SeMatchPlayer *pkPlayer, void *pkData, int iSize)
void SeRaceMgr::OnPlayerRaceLeave(SeMatchPlayer *pkPlayer, DWord dwKickFlag=0)
void SeRaceMgr::OnPlayerRaceEnd(SeMatchPlayer *pkPlayer, DWord dwRaceTime, bool bValied, int iNum, SeRaceSendInfo *akInfo)
void SeRaceMgr::OnPlayerGuanqiaEnd(SeMatchPlayer *pkPlayer, DWord dwRaceTime, bool bValied, int iNum, SeGuanqiaSendInfo *akInfo)
void SeRaceMgr::OnPlayerReportSyn(SeMatchPlayer *pkPlayer, void *pkData, int iSize)
bool SeRaceMgr::OnPlayerGameSynCheck(const SeRacePlayer *pkRacePlayer, const SeRace *pkRace, int iIndex, SeSynInfo *akSynInfo, int iSynInfo, int &riCount)
void SeRaceMgr::OnPlayerReconBegin(int iRoomIndex, SeMatchPlayer *pkPlayer, bool bView, int iOffset, DWord dwFrame)
void SeRaceMgr::OnPlayerRaceViewBegin(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, int iRoomSession)
void SeRaceMgr::OnPlayerView2Recon(SeMatchPlayer *pkPlayer)
void SeRaceMgr::OnPlayerViewQuit(SeMatchPlayer *pkPlayer)
bool SeRaceMgr::IsReconValidSeat(int iRoomIndex, int iSeat)
bool SeRaceMgr::IsReconValidPlayer(int iRoomIndex, DWord dwPlayerID, int iSeat)
void SeRaceMgr::OnPlayerReconQuit(DWord dwPlayerID, TeMD5 &rkRaceID)
void SeRaceMgr::OnSvrRaceSvrModelPack(const TeMD5 &rkRaceID, const char *pcData, int iSize)
void SeRaceMgr::OnSvrRaceResult(const TeMD5 &rkRaceID, const char *pcData, int iSize)
void SeRaceMgr::OnSvrRaceError(const TeMD5 &rkRaceID)
void SeRaceMgr::UpdateSvrRaceVerify(SeRace *pkRace)
void SeRaceMgr::OnGetAchievement(const TeMD5 &rkRaceID, int iSeat, DWord aID, DWord aLvl)
DWord SeRaceMgr::GetRaceTime(const TeMD5 &rkRaceID)
void SeRaceMgr::OprSvrRaceNum(int iThreadIndex, int iOpr)
int SeRaceMgr::GetSvrModeRaceNum()
int SeRaceMgr::GetNormalRaceNum()
int SeRaceMgr::GetCurrentRaceNum()
void SeRaceMgr::SaveAllRaceRecord(void)
SeRace* SeRaceMgr::GetRaceByRoomIndex(int iRoomSession, bool bRacing=true)
void SeRaceMgr::OnGetHeroInfo(SeMatchPlayer *pkPlayer)
SeRacePlayer* SeRaceMgr::GetRacePlayerBySeat(SeRace *pkRace, int iSeat)
void SeRaceMgr::EnableCheating(bool bEnable)
bool SeRaceMgr::IsCheating(void) const
bool SeRaceMgr::IsValidRace(const SeRace *pkRace)
bool SeRaceMgr::CheckValidRace(SeRace *pkRace)
SeRace* SeRaceMgr::GetRaceByID(const TeMD5 &rkRaceID, bool bRacing=true)
SeRace* SeRaceMgr::GetRace(const TeMD5 &rkRaceID)
void SeRaceMgr::CreateRobotRace(int n)
void SeRaceMgr::StartRobotRace(void)
void SeRaceMgr::ReflashWCSViewInfo(DWord dwWCSID, int Counts, const SeWCSViewInfo *pViewInfo)
void SeRaceMgr::RemoveWCSView(DWord dwWCSID)
void SeRaceMgr::OnPlayerItemChange(const TeMD5 &rkRaceID, const BePlayerItemChange &rInfo)
void SeRaceMgr::OnRaceEndGradeDetail(const TeMD5 &rkRaceID, const BeRaceGradeDetail &rInfo)
void SeRaceMgr::OnDecRespawnItem(const TeMD5 &rkRaceID, const BeDecRespawnItem &rInfo)
void SeRaceMgr::OnRaceEndArenaDetail(const TeMD5 &rkRaceID, const BeRaceArenaDetail &rInfo)
void SeRaceMgr::OnRealTimeRaceMapDetail(const TeMD5 &rkRaceID, const BeRaceBuildingStatus &rInfo)
void SeRaceMgr::OnRealTimeRaceKDA(const TeMD5 &rkRaceID, const BeAllHeroKDA &rInfo)
void SeRaceMgr::OnRaceKDA(const TeMD5 &rkRaceID, const BeAllHeroKDA &rInfo)
bool SeRaceMgr::SendMatchAddrMsg(SeMatchRace *pkRace)
References SeMatchBaseInfo::acName, SeNoticeMatchPlayerInfo::acName, SeSynMgr::AddSynOpr, SeMatchRace::akMRacePlayer, SeRacePlayer::akPlayerInfo, SeMatchRace::bSendMatchAddr, SeNoticeMatchPlayerInfo::byCamp, SeMatchRace::dwKey, SeMatchRace::dwMatchSession, SeRacePlayer::dwPlayerID, SeNoticeMatchPlayerInfo::dwPlayerID, SeRacePlayer::eCamp, g_kMatchServer, g_kRaceSvrMgr, g_kSynMgr, SeRaceSvrMgr::GetRaceSvr, MatchServer::GetRandHttpSock, GetTownSock, SeSynOpr::iID, SeRacePlayer::iSeatIndex, SeNoticeMatchPlayerInfo::iSeatIndex, SeRaceSvr::kAddrToMatch, SeRaceSvr::kAddrToMatchUdp, SePtlMatchPlayer::kBaseInfo, SeMatchRace::kRaceTownSign, SeRacePlayer::kTownSign, SeLogError, SeLogInfo, MatchServer::SendHS_BiVoiceCreateChatRoom, MatchServer::SendMT_NotifyAddrToMatch, SPrintf, SRVT_RACE, StrCpy.
Referenced by OnProcessValidateInfoRet.
void SeRaceMgr::DoRaceOver(SeMatchRace *pkRace)
References SeMatchRace::akMRacePlayer, SeMatchRace::dwLastRecvTime, SeMatchRace::dwMapID, SeMatchRace::dwMatchSession, SeRacePlayer::dwPlayerID, HTownSign::dwServerID, SeRacePlayer::eCamp, SeMatchRace::eRaceState, g_kMatchMgr, g_kMatchServer, g_kRaceQueryMgr, GetID2Str, MatchServer::GetServerTime, GetTownSock, SeMatchRace::iRoomIndex, SeRacePlayer::kTownSign, SeMatchMgr::OnBattleOver, SeRaceQueryMgr::OnDestroyRoom, SCMM_RACE_OVER, SeLogInfo, MatchServer::SendMT_CommMatchMsg, SMRS_RACE_OVER.
Referenced by OnProcessCommRaceMsg.
void SeRaceMgr::RaceUpdate(DWord dwServerTime)
References SeMatchRace::akMRacePlayer, SeMatchRace::bAllLoad, HTownSign::dwAreaID, SeMatchRace::dwLastRecvTime, SeMatchRace::dwMapID, SeMatchRace::dwMatchSession, HTownSign::dwServerID, SeMatchRace::eRaceState, g_kMatchServer, g_kRaceQueryMgr, GetID2Str, SeMatchRace::GetMatchRaceInfo, MatchServer::GetRaceBetInfo, GetRaceSvrSock, GetRacingSvr, SeMatchRace::iRoomIndex, SeMatchRace::kRaceTownSign, m_kMRace, SeRaceQueryMgr::OnDestroyRoom, MatchServer::OnSendRSValidatePlayerInfo, SCMM_NOTIFY_LOAD_FAILED, SeLogError, SeLogInfo, SendMatchCommMsg, SMRS_LOAD, SMRS_RACE_OVER, SMRS_VALIDATE.
Referenced by Update.
void SeRaceMgr::ValidWaitUpdate(DWord dwServerTime)
References SeWaitValidPlayer::dwCreateTime, m_kMWaitValidPlayer.
Referenced by Update.
SeMatchRace * SeRaceMgr::GetRaceByPlayerID(DWord dwPlayerID)
References SeMatchRace::akMRacePlayer, SeRacePlayer::dwPlayerID, m_kMRace.
Referenced by OnProcessViewQuery.
void SeRaceMgr::DelRace(DWord dwSession)
References SeMatchRace::dwMatchSession, g_kRaceQueryMgr, SeMatchRace::iRoomIndex, m_kMRace, SeRaceQueryMgr::OnDestroyRoom.
Referenced by OnProcessCommMsg, OnProcessCommRaceMsg, OnProcessValidateInfoRet.
bool SeRaceMgr::CheckMatchedRoomNum(const MapInfoTable *pkMapInfo, int iRoomNum, int iCampNum)
References MAPINFO_PROPERTY_BOSSPLAY, SSD_LUANDOU_MAP, MapInfoTable::uiMapTypeID, MapInfoTable::uiProperty.
bool SeRaceMgr::CheckMatchedPlayerNum(const MapInfoTable *pkMapInfo, int iRacePlayers, int iCampPlayers, int iCamp)
References MAPINFO_PROPERTY_BOSSPLAY, SSD_LUANDOU_MAP, MapInfoTable::uiMapTypeID, MapInfoTable::uiProperty.
DWord SeRaceMgr::GenSession()
References m_dwGenID.
Referenced by CreatEmptyRace.
DWord SeRaceMgr::GetSession()
References m_dwGenID.
Referenced by OnProcessReloadRoomList.
void SeRaceMgr::ResetSession(DWord dwSession)
References m_dwGenID.
Referenced by OnProcessReloadRoomList.
bool SeRaceMgr::IsSessionExist(DWord dwSession)
References m_kMRace.
Referenced by OnProcessReloadRoomList.
DWord SeRaceMgr::GetEnterKey()
Referenced by CreatEmptyRace, OnProcessViewQuerySuccess.
bool SeRaceMgr::GetRacingSvr(SeMatchRace *pkRace)
References SeRaceSvr::dwAreaID, HTownSign::dwAreaID, SeMatchRace::dwMatchAreaID, SeRaceSvr::dwServerID, HTownSign::dwServerID, g_kRaceSvrMgr, SeRaceSvrMgr::GetBestNormalRaceSvr, SeMatchRace::GetFirstPlayerID, SeMatchRace::kRaceTownSign.
Referenced by RaceUpdate.
HSock SeRaceMgr::GetTownSock(HTownSign &rkSign)
References g_kTownMgr, SeTownMgr::GetTown, SeConnect::kSock, SeTown::pkConnect.
Referenced by DoRaceOver, OnBiVoiceCreateRoom, OnProcessAddIncompleteRace, OnProcessCommRaceMsg, OnProcessMatchRaceLoad, OnProcessRaceBuy, OnProcessRaceEndGuanqia, OnProcessRaceEndReport, OnProcessReconQuerySuccess, OnProcessUpdateMisc, OnProcessViewQuerySuccess, SendMatchAddrMsg, SendMatchCommMsg.
HTownSign SeRaceMgr::GetTownSignByAreaID(MRacePlayer &rkMRacePlayer, DWord dwAreaID)
References HTownSign::dwAreaID, SeRacePlayer::kTownSign.
Referenced by OnProcessRaceEndGuanqia, OnProcessRaceEndReport.
HSock SeRaceMgr::GetRaceSvrSock(HTownSign &rkSign)
References g_kRaceSvrMgr, SeRaceSvrMgr::GetRaceSvr, SeConnect::kSock, SeRaceSvr::pkConnect.
Referenced by OnProcessRaceBuyRet, OnProcessReconPlayerName, OnProcessReconQuery, OnProcessReconViewValid, OnProcessViewQuery, RaceUpdate.
void SeRaceMgr::UpdateSvrStaCount()
References g_kMatchServer, MatchServer::GetServerTime, m_dwLastRecordTime, m_iSvrAddFailCount.
Referenced by Update.
bool SeRaceMgr::SendMatchAddrMsg(SeMatchRace *pkRace)
void SeRaceMgr::DoRaceOver(SeMatchRace *pkRace)
void SeRaceMgr::RaceUpdate(DWord dwServerTime)
void SeRaceMgr::ValidWaitUpdate(DWord dwServerTime)
SeMatchRace* SeRaceMgr::GetRaceByPlayerID(DWord dwPlayerID)
void SeRaceMgr::DelRace(DWord dwSession)
bool SeRaceMgr::CheckMatchedRoomNum(const MapInfoTable *pkMapInfo, int iRoomNum, int iCampNum)
bool SeRaceMgr::CheckMatchedPlayerNum(const MapInfoTable *pkMapInfo, int iRacePlayers, int iCampPlayers, int iCamp)
DWord SeRaceMgr::GenSession()
DWord SeRaceMgr::GetSession()
void SeRaceMgr::ResetSession(DWord dwSession)
bool SeRaceMgr::IsSessionExist(DWord dwSession)
DWord SeRaceMgr::GetEnterKey()
bool SeRaceMgr::GetRacingSvr(SeMatchRace *pkRace)
HSock SeRaceMgr::GetTownSock(HTownSign &rkSign)
HTownSign SeRaceMgr::GetTownSignByAreaID(MRacePlayer &rkMRacePlayer, DWord dwAreaID)
HSock SeRaceMgr::GetRaceSvrSock(HTownSign &rkSign)
void SeRaceMgr::UpdateSvrStaCount()
void SeRaceMgr::UpdateSendRaceEndInfo(void)
References g_kTownServer, GetID2Str, TownServer::IsWSReady, TownServer::IsWSRegistered, m_kVVGuanqiaSendInfo, SeLogInfo, TownServer::SendTW_RaceEndGuanka.
Referenced by Update.
void SeRaceMgr::UpdateSendRaceEndInfo(void)
void SeRaceMgr::UpdateRace(SeRace *pkRace, DWord dwServerTime)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRace::bSvrModeRace, SeRace::dwLastSendTime, SeRacePack::dwPackIndex, SeRacePlayer::dwPlayerID, g_kRaceServer, SeRaceRecord::GenRacePack, RaceServer::GetRacePackTime, SeRacePack::iSize, SeRace::kInfo, SeRacePlayer::kPlayerSock, SeRace::kRecord, SeUDPSender::kSock, SeRacePack::pkData, SeLogInfo, RaceServer::SendRC_RacePack, SRPS_NORMAL, SeRaceRecord::Update.
void SeRaceMgr::UpdateView(std::vector< SeViewPlayer > &rakViewPlayer, SeRaceState eRaceState, SeRaceRecord &rkRecord, DWord dwServerTime)
References SeViewPlayer::bDel, SeViewPlayer::bSyn, SeRaceCmd::dwFrame, SeViewPlayer::dwFrame, SeViewPlayer::dwLastSendTime, g_kRaceServer, GAME_FRAME_TIME, SeRaceRecord::GetDataSize, SeRaceRecord::GetLastFrame, SeRaceRecord::GetLastPos, SeRaceRecord::GetRaceCmd, SeViewPlayer::iDelay, SeViewPlayer::iOffset, SeViewPlayer::iSpeed, SeViewPlayer::kPlayerSock, SeUDPSender::kSock, RAS_LOADING, RAS_RACING, RAS_RACING_PAUSE, RAS_VERIFY, RAS_VERIFY_END, RaceServer::SendRC_ViewPack, RaceServer::SendRC_ViewResult, SVRT_END, SVRT_RACE_FRAME, SVRT_RACE_TIME, SVRT_SYN, VIEW_PACK_TIME.
void SeRaceMgr::UpdateView(TWCSViewMap &rViewMap, SeRaceState eRaceState, const TeMD5 &rRaceID, SeRaceRecord &rkRecord, DWord dwServerTime)
References TeMD5::abyMD5, SeRaceConfig::acRaceRecordURLBase, SeRace::akRacePlayer, SeWCSView::bDel, SeRaceCmd::dwFrame, SeWCSView::dwFrame, SeWCSView::dwLastSendTime, g_kRaceServer, SeRaceRecord::GetDataSize, SeRaceRecord::GetLastFrame, SeRaceRecord::GetLastPos, GetMD52Str, SeRaceRecord::GetPlayerInfo, GetRaceByID, SeRaceRecord::GetRaceCmd, RaceServer::GetRaceConfig, RaceServer::GetWCSView, SeWCSView::iOffset, SeRace::isNotifyed, SeRacePlayer::kPlayerSock, SeRace::kRaceID, SeUDPSender::kSock, m_vRemovedWCSIDList, RAS_RACING, RAS_VERIFY_END, SeLogDebug, SeLogError, RaceServer::SendRC_RaceEndNotifyDown, RaceServer::SendRWCS_RaceEnd, RaceServer::SendRWCS_RaceRecord, RaceServer::SendRWCS_RaceStart.
void SeRaceMgr::UpdateViewEnd(TWCSViewMap &rViewMap, const TeMD5 &rRaceID, SeRaceRecord &rkRecord)
References TeMD5::abyMD5, g_kRaceServer, GetMD52Str, SeWCSView::kWCSSock, SeLogDebug, RaceServer::SendRWCS_RaceEnd.
void SeRaceMgr::UpdateLoadingRace(SeRace *pkRace)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRace::dwBeginTime, SeRacePlayer::dwLoadRate, SeRace::dwMapID, SeRacePlayer::dwPlayerID, g_kRaceRoomMgr, g_kRaceServer, RaceServer::GetDebugLevel, GetID2Str, SeRaceRoomMgr::GetPlayer, RaceServer::GetServerTime, SeRace::iRoomIndex, OnPlayerRaceLeave, SeRaceRoomMgr::OnRaceLeave, SeLogError, UpdateLoadEnd.
void SeRaceMgr::UpdateLoadEnd(SeRace *pkRace)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRace::bSvrModeRace, SeRaceRoomMgr::ChangeRoomState, SeRaceCmd::dwFrame, SeRace::dwLastRecvCmdTime, SeRacePlayer::dwLoadRate, SeRace::dwPackIndex, SeRacePlayer::dwPlayerID, SeRaceCmd::dwSeat, SeRace::eState, g_kMatchReconMgr, g_kRaceRoomMgr, g_kRaceServer, SeRaceRecord::GetCurrentFrame, GetRacePlayerBySeat, RaceServer::GetServerTime, SeMatchReconMgr::InitAllow, SeRace::iRoomIndex, SeRacePlayer::iSeatIndex, SeRace::iThreadIndex, SeRacePlayer::kPlayerSock, SeRace::kRaceID, SeRace::kRecord, SeUDPSender::kSock, SeRaceRecord::OnHostStart, SeRaceRecord::PushRaceCmd, RaceServer::PushRSC_PlayerLeave, RaceServer::PushRSC_RaceStart, RaceServer::PushRSC_RaceStream, RAS_LOADING, RAS_RACING, SeLogInfo, SeLogWarning, RaceServer::SendRC_RacePack, SRRS_RACING, SSD_MAX_ROOM_PLAYER.
Referenced by OnPlayerRaceLeave, OnPlayerRaceLoadEnd, StartRobotRace, UpdateLoadingRace.
void SeRaceMgr::UpdateRaceEnd(SeRace *pkRace)
References SeRace::bSvrModeRace, SeRace::dwRaceEndTime, SeRace::eState, SeMatchReconMgr::FinishAllow, g_kMatchReconMgr, g_kRaceRoomMgr, g_kRaceServer, RaceServer::GetServerTime, SeRace::iRoomIndex, SeRace::kInfo, LocalCheckEnd, SeRaceRoomMgr::OnRaceEnd, RAS_VERIFY, RAS_VERIFY_END, SeLogInfo, WillRaceEnd.
Referenced by OnPlayerGuanqiaEnd, OnPlayerRaceEnd, OnPlayerRaceLeave, OnSvrRaceResult.
void SeRaceMgr::UpdateReconBegin(SeRace *pkRace, DWord dwServerTime)
References SeRace::akRJoinPlayer, SeReconJoinPlayer::bComplete, SeReconJoinPlayer::bDel, SeReconJoinPlayer::bRaceOver, SeRaceCmd::dwCmd, SeRaceCmd::dwFrame, SeReconJoinPlayer::dwFrame, SeReconJoinPlayer::dwLastSendTime, SeReconJoinPlayer::dwPlayerID, SeRace::eState, g_kRaceServer, GAME_FRAME_TIME, SeRaceRecord::GetDataSize, SeRaceRecord::GetLastFrame, SeRaceRecord::GetLastPos, SeRaceRecord::GetRaceCmd, SeReconJoinPlayer::iOffset, SeReconJoinPlayer::iSpeed, SeRace::kInfo, SeReconJoinPlayer::kPlayerSock, SeRace::kRecord, SeUDPSender::kSock, RAS_VERIFY, RAS_VERIFY_END, RECON_PACK_TIME, SeLogError, RaceServer::SendRC_ReconPack, RaceServer::SendRC_ReconResult, SPrintf, SRRT_RACE_OVER, SRRT_RACE_TIME, UpdateReconEnd.
void SeRaceMgr::UpdateReconEnd(SeRace *pkRace)
References SeRacePlayer::acName, SeRace::akRacePlayer, SeRace::akRJoinPlayer, SeReconJoinPlayer::bComplete, SeReconJoinPlayer::bDel, SeRacePlayer::bLeaveRace, SeReconJoinPlayer::bRaceOver, SeRacePlayer::bRecon, SeRace::bSvrModeRace, SeRacePlayer::dwPlayerID, SeReconJoinPlayer::dwPlayerID, g_kRaceRoomMgr, g_kRaceServer, SeRaceRoomMgr::GetPlayer, GetRacePlayer, SeReconJoinPlayer::iSeat, SeRacePlayer::iSeatIndex, SePlayerReconEnd::iSeatIndex, SeRace::iThreadIndex, SeRacePlayer::kPlayerSock, SeReconJoinPlayer::kPlayerSock, SeRace::kRaceID, SeRace::kRecord, SeUDPSender::kSock, OnPlayerRaceLeave, SeRaceRoomMgr::OnRaceLeave, SeRaceRecord::PushRaceCmd, RaceServer::PushRSC_PlayerRelink, RaceServer::PushRSC_RaceStream, RaceServer::SendPlayer_ReconNoticePlayerJoin, RaceServer::SendRC_ReconResult, SRRT_END.
Referenced by OnPlayerReconBegin, UpdateReconBegin.
void SeRaceMgr::UpdateSendRaceEndInfo(void)
bool SeRaceMgr::UpdateCheckOvertimeRace(SeRace *pkRace)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRacePlayer::bRecon, SeRace::bSvrModeRace, SeRace::dwBeginTime, SeRacePlayer::dwPlayerID, SeRace::eState, g_kMatchReconMgr, g_kRaceServer, SeMatchReconMgr::GetReconPlayer, RaceServer::GetServerTime, SeRace::isRobotRace, SeRace::iThreadIndex, SeRace::kInfo, SeRace::kRaceID, LocalCheckEnd, MAX_RACE_TIME, PLAYER_DISCONNECT, RaceServer::PushRSC_RaceOver, RACE_OVER_TIME, RAS_RACING, RAS_VERIFY, RAS_VERIFY_END, SeLogError.
const TeMD5 & SeRaceMgr::GenRaceID(void)
References g_kRaceServer, GetMD5, RaceServer::GetServerID, RaceServer::GetServerTime, m_dwGenRaceID, MemCpy.
Referenced by CreateRobotRace, OnRaceModeEnd.
const int SeRaceMgr::GenRobotRaceID(void)
References m_dwGenRaceID.
Referenced by CreateRobotRace.
SeRacePlayer * SeRaceMgr::GetRacePlayer(SeRace *pkRace, DWord dwPlayerID)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRacePlayer::dwPlayerID.
Referenced by OnPlayerBuyRaceItem, OnPlayerGuanqiaEnd, OnPlayerRaceCmd, OnPlayerRaceEnd, OnPlayerRaceLeave, OnPlayerRaceLoadEnd, OnPlayerRaceReplayReport, OnPlayerReportSyn, UpdateReconEnd.
bool SeRaceMgr::WillRaceEnd(SeRace *pkRace)
References SeRace::akRacePlayer, SeRacePlayer::bLeaveRace, SeRace::bRaceEndReport, SeRacePlayer::bRecon, SeRace::eState, RAS_RACING, RAS_VERIFY, RAS_VERIFY_END.
Referenced by UpdateRaceEnd.
void SeRaceMgr::LocalCheckEnd(SeRace *pkRace)
References LocalCheckEnd_Guanqia, LocalCheckEnd_Race, MAPINFO_TYPE_GUANQIA, MAPINFO_TYPE_RACE, SeRace::pkMapRes, MapInfoTable::uiType.
Referenced by UpdateCheckOvertimeRace, UpdateRaceEnd.
void SeRaceMgr::LocalCheckEnd_Race(SeRace *pkRace)
References SeRacePlayer::acName, SeRaceEndCheck::akInfo, SeRacePlayer::akRaceEndInfo, SeRace::akRacePlayer, SeRaceEndCheck::bValid, SeRacePlayer::bValied, CharToFileFun, SeRaceEndCheck::dwGameTime, SeRacePlayer::dwGameTime, SeRacePlayer::dwHeroTypeID, SeRacePlayer::dwPlayerID, GetID2Str, GetLocalTime, GetMD5String, SeRaceEndCheck::iCount, SeRacePlayer::iSeatIndex, SeRace::kInfo, MapInfoTable::kName, OnCheckRaceEnd, SeRace::pkMapRes, SeLogInfo, SPrintf.
Referenced by LocalCheckEnd.
void SeRaceMgr::LocalCheckEnd_Guanqia(SeRace *pkRace)
References SeRacePlayer::acName, SeRacePlayer::akGuanqiaEndInfo, SeGuankaEndCheck::akInfo, SeRace::akRacePlayer, SeGuankaEndCheck::bValid, SeRacePlayer::bValied, CharToFileFun, SeGuankaEndCheck::dwGameTime, SeRacePlayer::dwGameTime, SeRacePlayer::dwHeroTypeID, SeRacePlayer::dwPlayerID, GetID2Str, GetLocalTime, GetMD5String, SeGuankaEndCheck::iCount, SeRacePlayer::iSeatIndex, SeRace::kInfo, MapInfoTable::kName, OnCheckGuanqiaEnd, SeRace::pkMapRes, SeLogInfo, SPrintf.
Referenced by LocalCheckEnd.
void SeRaceMgr::InitSelHeroList(void)
References SelHeroTableMgr::Get, SelHeroTableMgr::GetSelHeroTableMap, SelHeroTable::iOpen, m_selHeroList.
DWord SeRaceMgr::GetRandHeroID()
References g_kRaceServer, m_selHeroList, RaceServer::RandInt.
Referenced by CreateRobotRace.
DWord SeRaceMgr::GetFreeThreadIndex()
References g_kRaceServer, RaceServer::GetRaceConfig, RaceServer::GetRaceServiceNum, SeRaceConfig::iLogicDllRaceNum, m_kMSvrIndex2Count.
Referenced by OnRaceModeEnd.
DWord SeRaceMgr::GetFreeThreadIndexByNum(int n)
References g_kRaceServer, RaceServer::GetRaceConfig, SeRaceConfig::iLogicDllRaceNum.
Referenced by CreateRobotRace.
void SeRaceMgr::UpdateRace(SeRace *pkRace, DWord dwServerTime)
void SeRaceMgr::UpdateView(std::vector< SeViewPlayer > &rakViewPlayer, SeRaceState eRaceState, SeRaceRecord &rkRecord, DWord dwServerTime)
void SeRaceMgr::UpdateView(TWCSViewMap &rViewMap, SeRaceState eRaceState, const TeMD5 &rRaceID, SeRaceRecord &rkRecord, DWord dwServerTime)
void SeRaceMgr::UpdateViewEnd(TWCSViewMap &rViewMap, const TeMD5 &rRaceID, SeRaceRecord &rkRecord)
void SeRaceMgr::UpdateLoadingRace(SeRace *pkRace)
void SeRaceMgr::UpdateLoadEnd(SeRace *pkRace)
void SeRaceMgr::UpdateRaceEnd(SeRace *pkRace)
void SeRaceMgr::UpdateReconBegin(SeRace *pkRace, DWord dwServerTime)
void SeRaceMgr::UpdateReconEnd(SeRace *pkRace)
void SeRaceMgr::UpdateSendRaceEndInfo(void)
bool SeRaceMgr::UpdateCheckOvertimeRace(SeRace *pkRace)
const TeMD5& SeRaceMgr::GenRaceID(void)
const int SeRaceMgr::GenRobotRaceID(void)
SeRacePlayer* SeRaceMgr::GetRacePlayer(SeRace *pkRace, DWord dwPlayerID)
bool SeRaceMgr::WillRaceEnd(SeRace *pkRace)
void SeRaceMgr::LocalCheckEnd(SeRace *pkRace)
void SeRaceMgr::LocalCheckEnd_Race(SeRace *pkRace)
void SeRaceMgr::LocalCheckEnd_Guanqia(SeRace *pkRace)
void SeRaceMgr::InitSelHeroList(void)
DWord SeRaceMgr::GetRandHeroID()
DWord SeRaceMgr::GetFreeThreadIndex()
DWord SeRaceMgr::GetFreeThreadIndexByNum(int n)