PVERuleTableMgr
std::map<unsigned int,PVERuleTable*> PVERuleTableMgr::m_kPVERuleTableMap
Referenced by FillData, GetPVERuleTable, GetPVERuleTableMap, GetPVERuleTableVec, ~PVERuleTableMgr.
PVERuleTableMgr * PVERuleTableMgr::m_pkPVERuleTableMgr
Referenced by Get, ReLoad.
PVERuleTableMgr * PVERuleTableMgr::Get()
References m_pkPVERuleTableMgr, PVERuleTableMgr.
Referenced by ReLoad.
PVERuleTableMgr * PVERuleTableMgr::ReLoad()
References Get, m_pkPVERuleTableMgr.
PVERuleTableMgr::PVERuleTableMgr()
References Load.
Referenced by Get.
PVERuleTableMgr::~PVERuleTableMgr()
References m_kPVERuleTableMap.
const PVERuleTable * PVERuleTableMgr::GetPVERuleTable(unsigned int iTypeID)
References m_kPVERuleTableMap.
const std::map< unsigned int, PVERuleTable * > & PVERuleTableMgr::GetPVERuleTableMap()
References m_kPVERuleTableMap.
TableResArray PVERuleTableMgr::GetPVERuleTableVec()
References m_kPVERuleTableMap, TableResArray::pushBack.
bool PVERuleTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by PVERuleTableMgr.
void PVERuleTableMgr::FillData(PVERuleTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, PVERuleTable::fUnitDirection, PVERuleTable::fUnitPosX, PVERuleTable::fUnitPosY, PVERuleTable::iAreaRange, PVERuleTable::iBlockAreaPoints, PVERuleTable::iCount, PVERuleTable::iIsDelay, PVERuleTable::iIsGameEnd, PVERuleTable::iRateOfRefresh, PVERuleTable::iTimesOfRefresh, PVERuleTable::iUnitDPosX, PVERuleTable::iUnitDPosY, PVERuleTable::iWalkLineIndex, PVERuleTable::kTips, m_kPVERuleTableMap, PVERuleTable::uiCamp, PVERuleTable::uiLinkMaps, PVERuleTable::uiMapUnitID, PVERuleTable::uiRuleOfCreate, PVERuleTable::uiUnitId, PVERuleTable::uiUnitType.
Referenced by Load.