SeXmlText
friend class SeXmlElement
bool SeXmlText::cdata
Referenced by CDATA, CopyTo, Parse, Print, SetCDATA, SeXmlText, StreamIn.
SeXmlText::SeXmlText(const char *initValue)
Constructor for text element. By default, it is treated as normal, encoded text. If you want it be output as a CDATA text element, set the parameter _cdata to 'true'
References cdata, SeXmlNode::SetValue.
Referenced by Clone.
virtual SeXmlText::~SeXmlText()
SeXmlText::SeXmlText(const std::string &initValue)
Constructor.
References cdata, SeXmlNode::SetValue.
SeXmlText::SeXmlText(const SeXmlText &copy)
References CopyTo.
SeXmlText& SeXmlText::operator=(const SeXmlText &base)
References CopyTo.
void SeXmlText::Print(FILE *cfile, int depth) const
All SeXml classes can print themselves to a filestream or the string class (SeXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.This is a formatted print, and will insert tabs and newlines.(For an unformatted stream, use the << operator.)
References cdata, SeXmlBase::EncodeString, SeXml_STRING, SeXmlNode::value.
bool SeXmlText::CDATA() const
Queries whether this represents text using a CDATA section.
References cdata.
Referenced by SeXmlPrinter::Visit, SeXmlPrinter::VisitEnter.
void SeXmlText::SetCDATA(bool _cdata)
Turns on or off a CDATA representation of text.
References cdata.
Referenced by SeXmlNode::Identify.
const char * SeXmlText::Parse(const char *p, SeXmlParsingData *data, SeXmlEncoding encoding)
References cdata, SeXmlParsingData::Cursor, SeXmlNode::GetDocument, SeXmlBase::location, SeXmlBase::ReadText, SeXmlDocument::SetError, SeXmlBase::SeXml_ERROR_PARSING_CDATA, SeXml_STRING, SeXmlParsingData::Stamp, SeXmlBase::StringEqual, SeXmlNode::value.
Referenced by SeXmlElement::ReadValue.
virtual const SeXmlText* SeXmlText::ToText() const
Cast to a more defined type. Will return null not of the requested type.
virtual SeXmlText* SeXmlText::ToText()
Cast to a more defined type. Will return null not of the requested type.
bool SeXmlText::Accept(SeXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
References SeXmlVisitor::Visit.
SeXmlNode * SeXmlText::Clone() const
[internal use] Creates a new Element and returns it.
References CopyTo, SeXmlText.
void SeXmlText::CopyTo(SeXmlText *target) const
References cdata, SeXmlNode::CopyTo.
Referenced by Clone, operator=, SeXmlText.
bool SeXmlText::Blank() const
References SeXmlBase::IsWhiteSpace, SeXmlNode::value.
Referenced by SeXmlElement::ReadValue.
void SeXmlText::StreamIn(std::istream *in, SeXml_STRING *tag)
References cdata, SeXmlNode::GetDocument, SeXmlDocument::SetError, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_EMBEDDED_NULL.
Referenced by SeXmlElement::StreamIn.