SeXmlNode
NodeType
friend class SeXmlDocument
friend class SeXmlElement
Referenced by SeXmlHandle::CreatePath, Identify.
std::istream& operator>>(std::istream &in, SeXmlNode &base)
An input stream operator, for every class. Tolerant of newlines and formatting, but doesn't expect them.
std::ostream& operator<<(std::ostream &out, const SeXmlNode &base)
An output stream operator, for every class. Note that this outputs without any newlines or formatting, as opposed to Print(), which includes tabs and new lines.The operator<< and operator>> are not completely symmetric. Writing a node to a stream is very well defined. You'll get a nice stream of output, without any extra whitespace or newlines.But reading is not as well defined. (As it always is.) If you create a SeXmlElement (for example) and read that from an input stream, the text needs to define an element or junk will result. This is true of all input streams, but it's worth keeping in mind.A SeXmlDocument will read nodes until it reads a root element, and all the children of that root element.
std::string& operator<<(std::string &out, const SeXmlNode &base)
Appends the XML node or attribute to a std::string.
SeXmlNode* SeXmlNode::parent
Referenced by GetDocument, Identify, InsertAfterChild, InsertBeforeChild, IterateChildren, LinkEndChild, Parent, RemoveChild, ReplaceChild, SeXmlNode.
NodeType SeXmlNode::type
Referenced by SeXmlNode, Type.
SeXmlNode* SeXmlNode::firstChild
Referenced by Clear, SeXmlElement::CopyTo, SeXmlDocument::CopyTo, FirstChild, InsertBeforeChild, LinkEndChild, NoChildren, SeXmlDocument::Parse, SeXmlElement::Print, RemoveChild, ReplaceChild, SeXmlElement::SeXmlElement, SeXmlNode, ~SeXmlNode.
SeXmlNode* SeXmlNode::lastChild
Referenced by Clear, InsertAfterChild, LastChild, LinkEndChild, SeXmlElement::Print, RemoveChild, ReplaceChild, SeXmlElement::SeXmlElement, SeXmlNode.
SeXml_STRING SeXmlNode::value
Referenced by SeXmlText::Blank, CopyTo, SeXmlDocument::LoadFile, SeXmlElement::Parse, SeXmlComment::Parse, SeXmlText::Parse, SeXmlUnknown::Parse, SeXmlElement::Print, SeXmlComment::Print, SeXmlText::Print, SeXmlUnknown::Print, SetValue, SeXmlDocument::SeXmlDocument, SeXmlElement::SeXmlElement, Value, ValueStr, ValueTStr.
SeXmlNode* SeXmlNode::prev
Referenced by InsertAfterChild, InsertBeforeChild, LastChild, LinkEndChild, PreviousSibling, RemoveChild, ReplaceChild, SeXmlNode.
SeXmlNode* SeXmlNode::next
Referenced by Clear, FirstChild, InsertAfterChild, InsertBeforeChild, LinkEndChild, NextSibling, RemoveChild, ReplaceChild, SeXmlNode, ~SeXmlNode.
SeXmlNode::~SeXmlNode()
References firstChild, next.
const char* SeXmlNode::Value() const
The meaning of 'value' changes for the specific type of SeXmlNode. Document: filename of the xml file Element: name of the element Comment: the comment text Unknown: the tag contents Text: the text string The subclasses will wrap this function.
References value.
Referenced by SeXmlElement::Clone, SeXmlHandle::CreatePath, FirstChild, SeXmlHandle::GetPath, SeXmlElement::GetText, LastChild, SeXmlDocument::LoadFile, NextSibling, PreviousSibling, SeXmlDocument::SaveFile, SeXmlPrinter::Visit, SeXmlPrinter::VisitEnter, SeXmlPrinter::VisitExit.
const std::string& SeXmlNode::ValueStr() const
Return Value() as a std::string. If you only use STL, this is more efficient than calling Value(). Only available in STL mode.
References value.
const SeXml_STRING& SeXmlNode::ValueTStr() const
References value.
Referenced by SeXmlPrinter::Visit.
void SeXmlNode::SetValue(const char *_value)
Changes the value of the node. Defined as: Document: filename of the xml file Element: name of the element Comment: the comment text Unknown: the tag contents Text: the text string
References value.
Referenced by CopyTo, SeXmlComment::SeXmlComment, SeXmlText::SeXmlText.
void SeXmlNode::SetValue(const std::string &_value)
STL std::string form.
References value.
void SeXmlNode::Clear()
Delete all the children of this node. Does not affect 'this'.
References firstChild, lastChild, next.
Referenced by SeXmlElement::ClearThis, SeXmlDocument::LoadFile, SeXmlComment::operator=, SeXmlDeclaration::operator=, SeXmlDocument::operator=.
SeXmlNode* SeXmlNode::Parent()
One step up the DOM.
References parent.
const SeXmlNode* SeXmlNode::Parent() const
References parent.
const SeXmlNode* SeXmlNode::FirstChild() const
The first child of this node. Will be null if there are no children.
References firstChild.
Referenced by SeXmlElement::Accept, SeXmlDocument::Accept, SeXmlHandle::Child, SeXmlHandle::FirstChild, FirstChildElement, SeXmlElement::GetText, IterateChildren, SeXmlDocument::Print, SeXmlPrinter::VisitEnter, SeXmlPrinter::VisitExit.
SeXmlNode* SeXmlNode::FirstChild()
References firstChild.
const SeXmlNode * SeXmlNode::FirstChild(const char *value) const
The first child of this node with the matching 'value'. Will be null if none found.
References firstChild, next, Value.
SeXmlNode* SeXmlNode::FirstChild(const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const SeXmlNode* SeXmlNode::LastChild() const
References lastChild.
Referenced by SeXmlPrinter::VisitEnter.
SeXmlNode* SeXmlNode::LastChild()
The last child of this node. Will be null if there are no children.
References lastChild.
const SeXmlNode * SeXmlNode::LastChild(const char *value) const
References lastChild, prev, Value.
SeXmlNode* SeXmlNode::LastChild(const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const SeXmlNode* SeXmlNode::FirstChild(const std::string &_value) const
STL std::string form.
References FirstChild.
Referenced by FirstChild.
SeXmlNode* SeXmlNode::FirstChild(const std::string &_value)
STL std::string form.
References FirstChild.
Referenced by FirstChild.
const SeXmlNode* SeXmlNode::LastChild(const std::string &_value) const
STL std::string form.
References LastChild.
Referenced by LastChild.
SeXmlNode* SeXmlNode::LastChild(const std::string &_value)
STL std::string form.
References LastChild.
Referenced by LastChild.
const SeXmlNode * SeXmlNode::IterateChildren(const SeXmlNode *previous) const
An alternate way to walk the children of a node. One way to iterate over nodes is: for( child = parent->FirstChild(); child; child = child->NextSibling() ) IterateChildren does the same thing with the syntax: child = 0; while( child = parent->IterateChildren( child ) ) IterateChildren takes the previous child as input and finds the next one. If the previous child is null, it returns the first. IterateChildren will return null when done.
References FirstChild, NextSibling, parent.
SeXmlNode* SeXmlNode::IterateChildren(const SeXmlNode *previous)
const SeXmlNode * SeXmlNode::IterateChildren(const char *value, const SeXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
References FirstChild, NextSibling, parent.
SeXmlNode* SeXmlNode::IterateChildren(const char *_value, const SeXmlNode *previous)
const SeXmlNode* SeXmlNode::IterateChildren(const std::string &_value, const SeXmlNode *previous) const
STL std::string form.
References IterateChildren.
Referenced by IterateChildren.
SeXmlNode* SeXmlNode::IterateChildren(const std::string &_value, const SeXmlNode *previous)
STL std::string form.
References IterateChildren.
Referenced by IterateChildren.
SeXmlNode * SeXmlNode::InsertEndChild(const SeXmlNode &addThis)
Add a new node related to this. Adds a child past the LastChild. Returns a pointer to the new object or NULL if an error occured.
References Clone, GetDocument, LinkEndChild, SeXmlDocument::SetError, SeXml_DOCUMENT, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_DOCUMENT_TOP_ONLY, Type.
SeXmlNode * SeXmlNode::LinkEndChild(SeXmlNode *addThis)
Add a new node related to this. Adds a child past the LastChild.NOTE: the node to be added is passed by pointer, and will be henceforth owned (and deleted) by SeXml. This method is efficient and avoids an extra copy, but should be used with care as it uses a different memory model than the other insert functions.InsertEndChild
References firstChild, GetDocument, lastChild, next, parent, prev, SeXmlDocument::SetError, SeXml_DOCUMENT, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_DOCUMENT_TOP_ONLY, Type.
Referenced by SeXmlElement::CopyTo, SeXmlDocument::CopyTo, SeXmlHandle::CreatePath, InsertEndChild, SeXmlDocument::Parse, SeXmlElement::ReadValue.
SeXmlNode * SeXmlNode::InsertBeforeChild(SeXmlNode *beforeThis, const SeXmlNode &addThis)
Add a new node related to this. Adds a child before the specified child. Returns a pointer to the new object or NULL if an error occured.
References Clone, firstChild, GetDocument, next, parent, prev, SeXmlDocument::SetError, SeXml_DOCUMENT, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_DOCUMENT_TOP_ONLY, Type.
SeXmlNode * SeXmlNode::InsertAfterChild(SeXmlNode *afterThis, const SeXmlNode &addThis)
Add a new node related to this. Adds a child after the specified child. Returns a pointer to the new object or NULL if an error occured.
References Clone, GetDocument, lastChild, next, parent, prev, SeXmlDocument::SetError, SeXml_DOCUMENT, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_DOCUMENT_TOP_ONLY, Type.
SeXmlNode * SeXmlNode::ReplaceChild(SeXmlNode *replaceThis, const SeXmlNode &withThis)
Replace a child of this node. Returns a pointer to the new object or NULL if an error occured.
References Clone, firstChild, GetDocument, lastChild, next, parent, prev, SeXmlDocument::SetError, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_DOCUMENT_TOP_ONLY, ToDocument.
bool SeXmlNode::RemoveChild(SeXmlNode *removeThis)
Delete a child of this node.
References firstChild, lastChild, next, parent, prev.
const SeXmlNode* SeXmlNode::PreviousSibling() const
Navigate to a sibling node.
References prev.
SeXmlNode* SeXmlNode::PreviousSibling()
References prev.
const SeXmlNode * SeXmlNode::PreviousSibling(const char *) const
Navigate to a sibling node.
References prev, Value.
SeXmlNode* SeXmlNode::PreviousSibling(const char *_prev)
const SeXmlNode* SeXmlNode::PreviousSibling(const std::string &_value) const
STL std::string form.
References PreviousSibling.
Referenced by PreviousSibling.
SeXmlNode* SeXmlNode::PreviousSibling(const std::string &_value)
STL std::string form.
References PreviousSibling.
Referenced by PreviousSibling.
const SeXmlNode* SeXmlNode::NextSibling(const std::string &_value) const
STL std::string form.
References NextSibling.
Referenced by SeXmlElement::Accept, SeXmlDocument::Accept, SeXmlHandle::Child, SeXmlElement::CopyTo, SeXmlDocument::CopyTo, SeXmlHandle::CreatePath, FirstChildElement, SeXmlHandle::GetPath, IterateChildren, NextSibling, NextSiblingElement, SeXmlElement::Print, SeXmlDocument::Print.
SeXmlNode* SeXmlNode::NextSibling(const std::string &_value)
STL std::string form.
References NextSibling.
Referenced by NextSibling.
const SeXmlNode* SeXmlNode::NextSibling() const
Navigate to a sibling node.
References next.
Referenced by NextSiblingElement.
SeXmlNode* SeXmlNode::NextSibling()
References next.
const SeXmlNode * SeXmlNode::NextSibling(const char *) const
Navigate to a sibling node with the given 'value'.
References next, Value.
SeXmlNode* SeXmlNode::NextSibling(const char *_next)
const SeXmlElement * SeXmlNode::NextSiblingElement() const
Convenience function to get through elements. Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
References NextSibling, ToElement.
Referenced by SeXmlHandle::ChildElement.
SeXmlElement* SeXmlNode::NextSiblingElement()
const SeXmlElement * SeXmlNode::NextSiblingElement(const char *) const
Convenience function to get through elements. Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
References NextSibling, ToElement.
SeXmlElement* SeXmlNode::NextSiblingElement(const char *_next)
const SeXmlElement* SeXmlNode::NextSiblingElement(const std::string &_value) const
STL std::string form.
References NextSiblingElement.
Referenced by NextSiblingElement.
SeXmlElement* SeXmlNode::NextSiblingElement(const std::string &_value)
STL std::string form.
References NextSiblingElement.
Referenced by NextSiblingElement.
const SeXmlElement * SeXmlNode::FirstChildElement() const
Convenience function to get through elements.
References FirstChild, NextSibling, ToElement.
Referenced by SeXmlHandle::ChildElement, SeXmlHandle::CreatePath, SeXmlHandle::FirstChildElement, SeXmlHandle::GetPath, SeXmlDocument::RootElement.
SeXmlElement* SeXmlNode::FirstChildElement()
const SeXmlElement * SeXmlNode::FirstChildElement(const char *_value) const
Convenience function to get through elements.
References FirstChild, NextSibling, ToElement.
SeXmlElement* SeXmlNode::FirstChildElement(const char *_value)
const SeXmlElement* SeXmlNode::FirstChildElement(const std::string &_value) const
STL std::string form.
References FirstChildElement.
Referenced by FirstChildElement.
SeXmlElement* SeXmlNode::FirstChildElement(const std::string &_value)
STL std::string form.
References FirstChildElement.
Referenced by FirstChildElement.
int SeXmlNode::Type() const
Query the type (as an enumerated value, above) of this node. The possible types are: SeXml_DOCUMENT, SeXml_ELEMENT, SeXml_COMMENT, SeXml_UNKNOWN, SeXml_TEXT, and SeXml_DECLARATION.
References type.
Referenced by InsertAfterChild, InsertBeforeChild, InsertEndChild, LinkEndChild.
const SeXmlDocument * SeXmlNode::GetDocument() const
Return a pointer to the Document this node lives in. Returns null if not in a document.
References parent, ToDocument.
Referenced by InsertAfterChild, InsertBeforeChild, InsertEndChild, LinkEndChild, SeXmlElement::Parse, SeXmlComment::Parse, SeXmlText::Parse, SeXmlDeclaration::Parse, SeXmlUnknown::Parse, SeXmlElement::ReadValue, ReplaceChild, SeXmlElement::StreamIn, SeXmlComment::StreamIn, SeXmlText::StreamIn, SeXmlDeclaration::StreamIn, SeXmlUnknown::StreamIn.
SeXmlDocument* SeXmlNode::GetDocument()
bool SeXmlNode::NoChildren() const
Returns true if this node has no children.
References firstChild.
virtual const SeXmlDocument* SeXmlNode::ToDocument() const
Cast to a more defined type. Will return null if not of the requested type.
Referenced by GetDocument, ReplaceChild.
virtual const SeXmlElement* SeXmlNode::ToElement() const
Cast to a more defined type. Will return null if not of the requested type.
Referenced by SeXmlHandle::CreatePath, FirstChildElement, SeXmlHandle::GetPath, NextSiblingElement, SeXmlDocument::StreamIn, SeXmlHandle::ToElement.
virtual const SeXmlComment* SeXmlNode::ToComment() const
Cast to a more defined type. Will return null if not of the requested type.
virtual const SeXmlUnknown* SeXmlNode::ToUnknown() const
Cast to a more defined type. Will return null if not of the requested type.
Referenced by SeXmlHandle::ToUnknown.
virtual const SeXmlText* SeXmlNode::ToText() const
Cast to a more defined type. Will return null if not of the requested type.
Referenced by SeXmlElement::GetText, SeXmlElement::Print, SeXmlHandle::ToText, SeXmlPrinter::VisitEnter.
virtual const SeXmlDeclaration* SeXmlNode::ToDeclaration() const
Cast to a more defined type. Will return null if not of the requested type.
Referenced by SeXmlDocument::Parse.
virtual SeXmlDocument* SeXmlNode::ToDocument()
Cast to a more defined type. Will return null if not of the requested type.
virtual SeXmlElement* SeXmlNode::ToElement()
Cast to a more defined type. Will return null if not of the requested type.
virtual SeXmlComment* SeXmlNode::ToComment()
Cast to a more defined type. Will return null if not of the requested type.
virtual SeXmlUnknown* SeXmlNode::ToUnknown()
Cast to a more defined type. Will return null if not of the requested type.
virtual SeXmlText* SeXmlNode::ToText()
Cast to a more defined type. Will return null if not of the requested type.
virtual SeXmlDeclaration* SeXmlNode::ToDeclaration()
Cast to a more defined type. Will return null if not of the requested type.
virtual SeXmlNode* SeXmlNode::Clone() const =0
Create an exact duplicate of this node and return it. The memory must be deleted by the caller.
Referenced by SeXmlElement::CopyTo, SeXmlDocument::CopyTo, InsertAfterChild, InsertBeforeChild, InsertEndChild, ReplaceChild.
virtual bool SeXmlNode::Accept(SeXmlVisitor *visitor) const =0
Accept a hierchical visit the nodes in the SeXml DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the SeXmlVisitor interface.This is essentially a SAX interface for SeXml. (Note however it doesn't re-parse the XML for the callbacks, so the performance of SeXml is unchanged by using this interface versus any other.)The interface has been based on ideas from: http://www.saxproject.org/http://c2.com/cgi/wiki?HierarchicalVisitorPattern Which are both good references for "visiting".An example of using Accept(): SeXmlPrinter printer; SeXmlDoc.Accept( &printer ); const char* xmlcstr = printer.CStr();
Referenced by operator<<.
SeXmlNode::SeXmlNode(NodeType _type)
References firstChild, lastChild, next, parent, prev, type.
void SeXmlNode::CopyTo(SeXmlNode *target) const
References SeXmlBase::location, SetValue, SeXmlBase::userData, value.
Referenced by SeXmlElement::CopyTo, SeXmlComment::CopyTo, SeXmlText::CopyTo, SeXmlDeclaration::CopyTo, SeXmlUnknown::CopyTo, SeXmlDocument::CopyTo.
virtual void SeXmlNode::StreamIn(std::istream *in, SeXml_STRING *tag)=0
Referenced by operator>>, SeXmlElement::StreamIn, SeXmlDocument::StreamIn.
SeXmlNode * SeXmlNode::Identify(const char *start, SeXmlEncoding encoding)
References SeXmlBase::IsAlpha, parent, SeXmlText::SetCDATA, SeXmlElement, SeXmlBase::SkipWhiteSpace, SeXmlBase::StringEqual.
Referenced by SeXmlDocument::Parse, SeXmlElement::ReadValue, SeXmlElement::StreamIn, SeXmlDocument::StreamIn.
SeXmlNode::SeXmlNode(const SeXmlNode &)
void SeXmlNode::operator=(const SeXmlNode &base)