SeSharedPtr
T* SeSharedPtr< T >::m_pkRep
Referenced by SeSharedPtr< T >::Bind, SeSharedPtr< T >::Destroy, SeSharedPtr< T >::Get, SeSharedPtr< T >::GetPointer, SeSharedPtr< T >::IsNull, SeSharedPtr< T >::SeSharedPtr, SeSharedPtr< T >::SetNull, SeSharedPtr< T >::Swap.
ShareUseCount* SeSharedPtr< T >::m_pkUserPtr
Referenced by SeSharedPtr< T >::Bind, SeSharedPtr< T >::Destroy, SeSharedPtr< T >::Get, SeSharedPtr< T >::GetPointer, SeSharedPtr< T >::GetUseCount, SeSharedPtr< T >::GetUseCountPointer, SeSharedPtr< T >::IsNull, SeSharedPtr< T >::Release, SeSharedPtr< T >::SeSharedPtr, SeSharedPtr< T >::SetNull, SeSharedPtr< T >::SetOutDestroy, SeSharedPtr< T >::Swap, SeSharedPtr< T >::Unique.
SeSharedPtr< T >::SeSharedPtr()
SeSharedPtr< T >::SeSharedPtr(const SeSharedPtr &rkSeSharedPtr)
References SeSharedPtr< T >::ShareUseCount::iUseCount, SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr.
SeSharedPtr& SeSharedPtr< T >::operator=(const SeSharedPtr &rkSeSharedPtr)
References SeSharedPtr< T >::Swap.
SeSharedPtr< T >::SeSharedPtr(const SeSharedPtr< Y > &rkSeSharedPtr)
References SeSharedPtr< T >::ShareUseCount::iUseCount, SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr.
SeSharedPtr& SeSharedPtr< T >::operator=(const SeSharedPtr< Y > &rkSeSharedPtr)
References SeSharedPtr< T >::Swap.
virtual SeSharedPtr< T >::~SeSharedPtr()
References SeSharedPtr< T >::Release.
T& SeSharedPtr< T >::operator*() const
References SeSharedPtr< T >::Get.
T* SeSharedPtr< T >::operator->() const
References SeSharedPtr< T >::Get.
T* SeSharedPtr< T >::Get() const
References SeSharedPtr< T >::ShareUseCount::bSetNull, SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr.
Referenced by SeSharedPtr< T >::operator*, SeSharedPtr< T >::operator->.
void SeSharedPtr< T >::SetOutDestroy(bool bOut)
References SeSharedPtr< T >::ShareUseCount::bOutDestroy, SeSharedPtr< T >::m_pkUserPtr.
void SeSharedPtr< T >::Bind(T *pkPtr)
References SeSharedPtr< T >::ShareUseCount::iUseCount, SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr.
bool SeSharedPtr< T >::Unique() const
References SeSharedPtr< T >::ShareUseCount::iUseCount, SeSharedPtr< T >::m_pkUserPtr.
unsigned int SeSharedPtr< T >::GetUseCount() const
References SeSharedPtr< T >::ShareUseCount::iUseCount, SeSharedPtr< T >::m_pkUserPtr.
unsigned int* SeSharedPtr< T >::GetUseCountPointer() const
References SeSharedPtr< T >::ShareUseCount::iUseCount, SeSharedPtr< T >::m_pkUserPtr.
T* SeSharedPtr< T >::GetPointer() const
References SeSharedPtr< T >::ShareUseCount::bSetNull, SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr.
Referenced by operator!=, operator==.
bool SeSharedPtr< T >::IsNull() const
References SeSharedPtr< T >::ShareUseCount::bSetNull, SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr.
void SeSharedPtr< T >::SetNull()
References SeSharedPtr< T >::ShareUseCount::bSetNull, SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr.
void SeSharedPtr< T >::Release()
References SeSharedPtr< T >::Destroy, SeSharedPtr< T >::ShareUseCount::iUseCount, SeSharedPtr< T >::m_pkUserPtr.
Referenced by SeSharedPtr< T >::~SeSharedPtr.
void SeSharedPtr< T >::Destroy()
References SeSharedPtr< T >::ShareUseCount::bOutDestroy, SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr, SAFE_DELETE.
Referenced by SeSharedPtr< T >::Release.
void SeSharedPtr< T >::Swap(SeSharedPtr< T > &rkOther)
References SeSharedPtr< T >::m_pkRep, SeSharedPtr< T >::m_pkUserPtr.
Referenced by SeSharedPtr< T >::operator=.