SeRandNumFomula
MID2Pool SeRandNumFomula::m_kMID2RandPool
Referenced by AddRandResult, Clear, InsertRandPool, IsMaxSucRand, RandFloatInRate, SetRandResult, UpdateRandPool.
bool SeRandNumFomula::m_bFomula
Referenced by Clear, RandFloatInRate, SeRandNumFomula, SetFomula.
SeRandNumFomula::SeRandNumFomula()
References m_bFomula.
SeRandNumFomula::~SeRandNumFomula()
References Clear.
void SeRandNumFomula::Clear(void)
References m_bFomula, m_kMID2RandPool.
Referenced by ~SeRandNumFomula.
bool SeRandNumFomula::RandFloatInRate(unsigned int dwID, float fRate, bool bResult)
References makeCallback.f, BeRandPool::fHiRate, BeRandPool::iHitFail, BeRandPool::iHitSuc, InsertRandPool, BeRandPool::iSucLimit, BeRandPool::iTotalLimit, m_bFomula, m_kMID2RandPool, UpdateRandPool.
void SeRandNumFomula::SetRandResult(unsigned int dwID, bool bResult)
References BeRandPool::iHitFail, BeRandPool::iHitSuc, BeRandPool::iTotalHit, BeRandPool::iTotalLimit, m_kMID2RandPool.
bool SeRandNumFomula::IsMaxSucRand(int iRandID)
References BeRandPool::iHitSuc, BeRandPool::iSucLimit, m_kMID2RandPool.
void SeRandNumFomula::AddRandResult(int iRandID, bool bResult)
References BeRandPool::iHitFail, BeRandPool::iHitSuc, m_kMID2RandPool.
void SeRandNumFomula::SetFomula(bool bFomula)
References m_bFomula.
void SeRandNumFomula::InsertRandPool(unsigned int dwID, float fRate)
References CALCUTE_RANDRATE, makeCallback.f, BeRandPool::fHiRate, BeRandPool::fLowRate, GetMCD, BeRandPool::iSucLimit, BeRandPool::iTotalLimit, m_kMID2RandPool, MAX_TOTAL_LIMIT, MAXDPER.
Referenced by RandFloatInRate.
void SeRandNumFomula::UpdateRandPool(unsigned int dwID, bool bHitSuc)
References BeRandPool::iHitFail, BeRandPool::iHitSuc, BeRandPool::iTotalHit, BeRandPool::iTotalLimit, m_kMID2RandPool.
Referenced by RandFloatInRate.