TiXmlAttribute
friend class TiXmlAttributeSet
TiXmlDocument* TiXmlAttribute::document
Referenced by SetDocument, TiXmlAttribute.
TIXML_STRING TiXmlAttribute::name
Referenced by TiXmlAttributeSet::Find, Name, NameTStr, Next, operator<, operator==, operator>, Parse, Previous, SetName, TiXmlAttribute.
TIXML_STRING TiXmlAttribute::value
Referenced by DoubleValue, IntValue, Next, Parse, Previous, Print, QueryDoubleValue, QueryIntValue, SetValue, TiXmlAttribute, Value.
TiXmlAttribute* TiXmlAttribute::prev
Referenced by TiXmlAttributeSet::Add, TiXmlAttributeSet::Last, Previous, TiXmlAttributeSet::Remove, TiXmlAttribute, TiXmlAttributeSet::TiXmlAttributeSet, TiXmlAttributeSet::~TiXmlAttributeSet.
TiXmlAttribute* TiXmlAttribute::next
Referenced by TiXmlAttributeSet::Add, TiXmlAttributeSet::Find, TiXmlAttributeSet::First, Next, TiXmlAttributeSet::Remove, TiXmlAttribute, TiXmlAttributeSet::TiXmlAttributeSet, TiXmlAttributeSet::~TiXmlAttributeSet.
TiXmlAttribute::TiXmlAttribute()
Construct an empty attribute.
References document, next, prev.
TiXmlAttribute::TiXmlAttribute(const char *_name, const char *_value)
Construct an attribute with a name and value.
References document, name, next, prev, value.
const char* TiXmlAttribute::Name() const
Return the name of this attribute.
References name.
Referenced by TiXmlAttributeSet::Add, TiXmlElement::CopyTo, TiXmlElement::Parse.
const char* TiXmlAttribute::Value() const
Return the value of this attribute.
References value.
Referenced by TiXmlElement::Attribute, TiXmlElement::CopyTo, TiXmlElement::Parse, TiXmlDeclaration::Parse.
int TiXmlAttribute::IntValue() const
Return the value of this attribute, converted to an integer.
References value.
double TiXmlAttribute::DoubleValue() const
Return the value of this attribute, converted to a double.
References value.
const TIXML_STRING& TiXmlAttribute::NameTStr() const
References name.
Referenced by TiXmlElement::Parse.
int TiXmlAttribute::QueryIntValue(int *_value) const
QueryIntValue examines the value string. It is an alternative to the IntValue() method with richer error checking. If the value is an integer, it is stored in 'value' and the call returns TIXML_SUCCESS. If it is not an integer, it returns TIXML_WRONG_TYPE.A specialized but useful call. Note that for success it returns 0, which is the opposite of almost all other TinyXml calls.
References TIXML_SUCCESS, TIXML_WRONG_TYPE, value.
Referenced by TiXmlElement::QueryIntAttribute.
int TiXmlAttribute::QueryDoubleValue(double *_value) const
QueryDoubleValue examines the value string. See QueryIntValue().
References TIXML_SUCCESS, TIXML_WRONG_TYPE, value.
Referenced by TiXmlElement::QueryDoubleAttribute.
void TiXmlAttribute::SetName(const char *_name)
Set the name of this attribute.
References name.
void TiXmlAttribute::SetValue(const char *_value)
Set the value.
References value.
Referenced by TiXmlElement::Parse, TiXmlElement::SetAttribute, SetDoubleValue, SetIntValue.
void TiXmlAttribute::SetIntValue(int _value)
Set the value from an integer.
References SetValue.
void TiXmlAttribute::SetDoubleValue(double _value)
Set the value from a double.
References SetValue.
const TiXmlAttribute * TiXmlAttribute::Next() const
Get the next sibling attribute in the DOM. Returns null at end.
References name, next, value.
Referenced by TiXmlElement::CopyTo, TiXmlElement::Print, TiXmlPrinter::VisitEnter.
TiXmlAttribute* TiXmlAttribute::Next()
const TiXmlAttribute * TiXmlAttribute::Previous() const
Get the previous sibling attribute in the DOM. Returns null at beginning.
References name, prev, value.
TiXmlAttribute* TiXmlAttribute::Previous()
bool TiXmlAttribute::operator==(const TiXmlAttribute &rhs) const
References name.
bool TiXmlAttribute::operator<(const TiXmlAttribute &rhs) const
References name.
bool TiXmlAttribute::operator>(const TiXmlAttribute &rhs) const
References name.
const char * TiXmlAttribute::Parse(const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
References TiXmlParsingData::Cursor, TiXmlBase::IsWhiteSpace, TiXmlBase::location, name, TiXmlBase::ReadName, TiXmlBase::ReadText, TiXmlDocument::SetError, TiXmlBase::SkipWhiteSpace, TiXmlParsingData::Stamp, TiXmlBase::TIXML_ERROR_READING_ATTRIBUTES, value.
Referenced by TiXmlElement::Parse, TiXmlDeclaration::Parse.
virtual void TiXmlAttribute::Print(FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.This is a formatted print, and will insert tabs and newlines.(For an unformatted stream, use the << operator.)
Referenced by TiXmlDocument::Print, TiXmlPrinter::VisitEnter.
void TiXmlAttribute::Print(FILE *cfile, int depth, TIXML_STRING *str) const
References TiXmlBase::PutString, TIXML_STRING, value.
void TiXmlAttribute::SetDocument(TiXmlDocument *doc)
References document.
Referenced by TiXmlElement::Parse.
TiXmlAttribute::TiXmlAttribute(const TiXmlAttribute &)
void TiXmlAttribute::operator=(const TiXmlAttribute &base)