SeDBStream
char* SeDBStream::m_pcData
Referenced by Attach, GetData, InitData, Read, SeDBStream, Write.
char SeDBStream::m_acData[SSD_SEND_SIZE][SSD_SEND_SIZE]
Referenced by InitData, SeDBStream.
int SeDBStream::m_iSize
Referenced by Attach, InitData, IsEnd, Read, SeDBStream, Write.
int SeDBStream::m_iPos
Referenced by Attach, GetCurPos, InitData, IsEnd, Read, SeDBStream, Write.
bool SeDBStream::m_bLimitData
Referenced by Attach, InitData, SeDBStream, Write.
SeDBStream::SeDBStream()
References m_acData, m_bLimitData, m_iPos, m_iSize, m_pcData.
SeDBStream::~SeDBStream()
bool SeDBStream::Attach(void *pkData, int iSize)
References m_bLimitData, m_iPos, m_iSize, m_pcData.
Referenced by PlayerDataStrategy::onLoadData, TabMgr::onTabSelectRet, BlockServer::ProcessBBL_SelectFriendDataRet, WorldServer::ProcessBW_DBQueryRet, WorldServer::ProcessBW_IsPlayerExistRet, DBServer::ProcessDB_IsPlayerExistByAccountOrName, DBServer::ProcessWB_DBQuery, DBServer::ProcessWB_IsPlayerExist, DBServer::ProcessWB_TabDelete, DBServer::ProcessWB_TabInsert, DBServer::ProcessWB_TabSelect, DBServer::ProcessWB_TabUpdate, DBServer::ProcessWS_CharAdd, DBServer::ProcessWS_Insert_NoReceipt, DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend, DBServer::ProcessWS_Update_NoReceipt, BlockServer::SeBSProcess_CharMemoryLoad, BlockServer::SeBSProcess_CharNexusFriend, BlockServer::SeBSProcess_LoadFriendLadderInfo.
void SeDBStream::InitData()
References m_acData, m_bLimitData, m_iPos, m_iSize, m_pcData.
Referenced by PlayerDataStrategy::dataInsert, PlayerDataStrategy::dataUpdate, DBServer::Excu_SelectData, WorldServer::OnSendDBPlayerLoad, onTabSelect, DBServer::ProcessDB_CharFriendLadderLoad, DBServer::ProcessDB_CharLoginLoad, DBServer::ProcessDB_CharQueryValid, DBServer::ProcessDB_CharRenameBegin, DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery, BlockServer::ProcessTBL_UserAlterNickNameReq, WorldServer::ProcessTW_QueryName, WorldServer::ProcessTW_SearchUserArchivesDetailInfoReq, WorldServer::ProcessTW_SearchUserArchivesInfoReq, DBServer::ProcessWS_CharAdd, DBServer::SendDB_CharLoginLoad, DBServer::SendDB_CharQueryValid, DBServer::SendDB_FriendLadderInfoLoad, WorldServer::SendDBServer_CharAddMisc, WorldServer::SendDBServer_CharInfoADD, WorldServer::SendDBServer_CharInfoRename, WorldServer::SendDBServer_CharLoginLoad, WorldServer::SendDBServer_CharMemoryUpdate, WorldServer::SendDBServer_CharQueryValid, WorldServer::SendDBServer_CharTaskAdd, WorldServer::SendDBServer_CharTaskUpdate, WorldServer::SendDBServer_CharUpdateBattleField, WorldServer::SendDBServer_CharUpdateLadder, WorldServer::SendDBServer_CharUpdateLoginTime, WorldServer::SendDBServer_CharUpdateMatch, WorldServer::SendDBServer_CharUpdateMisc, WorldServer::SendDBServer_CharUpdateTaskResetCount, WorldServer::SendDBServer_CharUpdateTaskResetTime, WorldServer::SendDBServer_NexusFriendCreate, WorldServer::SendDBServer_NexusFriendUpdate, TabMgr::tabDelete, TabMgr::tabInsert, TabMgr::tabSelect, TabMgr::tabUpdate.
bool SeDBStream::IsEnd(int iSize)
References m_iPos, m_iSize.
Referenced by PlayerDataStrategy::onLoadData, BlockServer::SeBSProcess_CharMemoryLoad, BlockServer::SeBSProcess_CharNexusFriend, WorldServer::SeDBSerProcess_CharRename.
char * SeDBStream::GetData()
References m_pcData.
Referenced by PlayerDataStrategy::dataInsert, PlayerDataStrategy::dataUpdate, DBServer::Excu_SelectData, WorldServer::OnSendDBPlayerLoad, onTabSelect, DBServer::ProcessDB_CharFriendLadderLoad, DBServer::ProcessDB_CharLoginLoad, DBServer::ProcessDB_CharQueryValid, DBServer::ProcessDB_CharRenameBegin, DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery, BlockServer::ProcessTBL_UserAlterNickNameReq, WorldServer::ProcessTW_QueryName, WorldServer::ProcessTW_SearchUserArchivesDetailInfoReq, WorldServer::ProcessTW_SearchUserArchivesInfoReq, DBServer::ProcessWS_CharAdd, DBServer::SendDB_CharLoginLoad, DBServer::SendDB_CharQueryValid, DBServer::SendDB_FriendLadderInfoLoad, WorldServer::SendDBServer_CharAddMisc, WorldServer::SendDBServer_CharInfoADD, WorldServer::SendDBServer_CharInfoRename, WorldServer::SendDBServer_CharLoginLoad, WorldServer::SendDBServer_CharMemoryUpdate, WorldServer::SendDBServer_CharQueryValid, WorldServer::SendDBServer_CharTaskAdd, WorldServer::SendDBServer_CharTaskUpdate, WorldServer::SendDBServer_CharUpdateBattleField, WorldServer::SendDBServer_CharUpdateLadder, WorldServer::SendDBServer_CharUpdateLoginTime, WorldServer::SendDBServer_CharUpdateMatch, WorldServer::SendDBServer_CharUpdateMisc, WorldServer::SendDBServer_CharUpdateTaskResetCount, WorldServer::SendDBServer_CharUpdateTaskResetTime, WorldServer::SendDBServer_NexusFriendCreate, WorldServer::SendDBServer_NexusFriendUpdate, TabMgr::tabDelete, TabMgr::tabInsert, TabMgr::tabSelect, TabMgr::tabUpdate.
int SeDBStream::GetCurPos(void)
References m_iPos.
Referenced by PlayerDataStrategy::dataInsert, PlayerDataStrategy::dataUpdate, DBServer::Excu_SelectData, WorldServer::OnSendDBPlayerLoad, onTabSelect, DBServer::ProcessDB_CharFriendLadderLoad, DBServer::ProcessDB_CharLoginLoad, DBServer::ProcessDB_CharQueryValid, DBServer::ProcessDB_CharRenameBegin, DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery, BlockServer::ProcessTBL_UserAlterNickNameReq, WorldServer::ProcessTW_QueryName, WorldServer::ProcessTW_SearchUserArchivesDetailInfoReq, WorldServer::ProcessTW_SearchUserArchivesInfoReq, DBServer::ProcessWS_CharAdd, DBServer::ProcessWS_Insert_NoReceipt, DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend, DBServer::ProcessWS_Update_NoReceipt, DBServer::SendDB_CharLoginLoad, DBServer::SendDB_CharMemoryUpdate, DBServer::SendDB_CharQueryValid, DBServer::SendDB_CharRenameBegin, DBServer::SendDB_FriendLadderInfoLoad, WorldServer::SendDBServer_CharAddMisc, WorldServer::SendDBServer_CharInfoADD, WorldServer::SendDBServer_CharInfoRename, WorldServer::SendDBServer_CharLoginLoad, WorldServer::SendDBServer_CharMemoryUpdate, WorldServer::SendDBServer_CharQueryValid, WorldServer::SendDBServer_CharTaskAdd, WorldServer::SendDBServer_CharTaskUpdate, WorldServer::SendDBServer_CharUpdateBattleField, WorldServer::SendDBServer_CharUpdateLadder, WorldServer::SendDBServer_CharUpdateLoginTime, WorldServer::SendDBServer_CharUpdateMatch, WorldServer::SendDBServer_CharUpdateMisc, WorldServer::SendDBServer_CharUpdateTaskResetCount, WorldServer::SendDBServer_CharUpdateTaskResetTime, WorldServer::SendDBServer_NexusFriendCreate, WorldServer::SendDBServer_NexusFriendUpdate, TabMgr::tabDelete, TabMgr::tabInsert, TabMgr::tabSelect, TabMgr::tabUpdate.
Byte SeDBStream::ReadByte(void)
References Read.
DWord SeDBStream::ReadDword(void)
References Read.
Referenced by appendWhereClause, PlayerDataStrategy::onLoadData, BlockServer::ProcessBBL_SelectFriendDataRet, WorldServer::ProcessBW_IsPlayerExistRet, DBServer::ProcessDB_IsPlayerExistByAccountOrName, DBServer::ProcessWB_IsPlayerExist, DBServer::ProcessWB_TabInsert, DBServer::ProcessWB_TabSelect, DBServer::ProcessWB_TabUpdate, DBServer::ProcessWS_CharAdd, DBServer::ProcessWS_Insert_NoReceipt, DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend, DBServer::ProcessWS_Update_NoReceipt, ReadVariant, BlockServer::SeBSProcess_CharMemoryLoad, BlockServer::SeBSProcess_CharNexusFriend, BlockServer::SeBSProcess_LoadFriendLadderInfo, WorldServer::SeDBSerProcess_CharLoginLoad, WorldServer::SeDBSerProcess_CharQueryValid, WorldServer::SeDBSerProcess_CharRename, DBServer::SendDB_CharLoginLoad, DBServer::SendDB_CharMemoryUpdate, DBServer::SendDB_CharQueryValid, DBServer::SendDB_CharRenameBegin.
bool SeDBStream::ReadString(char *pcValue)
References Read, ReadWord, TOOL_MAX_STRING.
Referenced by BlockServer::ProcessBBL_SelectFriendDataRet, DBServer::ProcessDB_IsPlayerExistByAccountOrName, DBServer::ProcessWB_IsPlayerExist, DBServer::ProcessWS_CharAdd, DBServer::ProcessWS_Insert_NoReceipt, DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend, DBServer::ProcessWS_Update_NoReceipt, ReadVariant, BlockServer::SeBSProcess_CharNexusFriend, BlockServer::SeBSProcess_LoadFriendLadderInfo, WorldServer::SeDBSerProcess_CharRename, DBServer::SendDB_CharRenameBegin.
bool SeDBStream::ReadDBTime(SeDBTime &rkTime)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear, ReadChar, ReadShort.
Referenced by DBServer::ProcessWS_Insert_NoReceipt, DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend, DBServer::ProcessWS_Update_NoReceipt, ReadVariant, BlockServer::SeBSProcess_CharMemoryLoad, BlockServer::SeBSProcess_CharNexusFriend, DBServer::SendDB_CharMemoryUpdate, DBServer::SendDB_CharQueryValid.
float SeDBStream::ReadFloat(void)
References Read.
bool SeDBStream::ReadMD5(TeMD5 &rkMD5)
References TeMD5::abyMD5, Read.
bool SeDBStream::ReadPtlHSock(SePtlHSock &rkSock)
References Read.
uint64_t SeDBStream::ReadDoubleDword(void)
References Read.
Referenced by DBServer::ProcessWS_Insert_NoReceipt, DBServer::ProcessWS_Insert_NoReceipt_Offline_NexusFriend, DBServer::ProcessWS_Update_NoReceipt, ReadVariant, BlockServer::SeBSProcess_CharNexusFriend.
bool SeDBStream::ReadVariant(SeDBVariant &var)
References SeDBVariant::getFormat, ReadDBTime, ReadDoubleDword, ReadDword, ReadString, SFF_DATETIME, SFF_NUM, SFF_NUM64, SFF_STRING.
Referenced by appendWhereClause, TabMgr::onTabSelectRet, DBServer::ProcessWB_TabInsert, DBServer::ProcessWB_TabUpdate.
bool SeDBStream::WriteByte(Byte byValue)
References Write.
bool SeDBStream::WriteDword(DWord dwValue)
References Write.
Referenced by PlayerDataStrategy::dataInsert, PlayerDataStrategy::dataUpdate, DBServer::Excu_SelectData, WorldServer::OnSendDBPlayerLoad, onTabSelect, DBServer::ProcessDB_CharFriendLadderLoad, DBServer::ProcessDB_CharLoginLoad, DBServer::ProcessDB_CharQueryValid, DBServer::ProcessDB_CharRenameBegin, DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery, BlockServer::ProcessTBL_UserAlterNickNameReq, WorldServer::ProcessTW_QueryName, WorldServer::ProcessTW_SearchUserArchivesDetailInfoReq, WorldServer::ProcessTW_SearchUserArchivesInfoReq, DBServer::ProcessWS_CharAdd, DBServer::SendDB_CharLoginLoad, DBServer::SendDB_CharQueryValid, DBServer::SendDB_FriendLadderInfoLoad, WorldServer::SendDBServer_CharAddMisc, WorldServer::SendDBServer_CharInfoADD, WorldServer::SendDBServer_CharInfoRename, WorldServer::SendDBServer_CharLoginLoad, WorldServer::SendDBServer_CharMemoryUpdate, WorldServer::SendDBServer_CharQueryValid, WorldServer::SendDBServer_CharTaskAdd, WorldServer::SendDBServer_CharTaskUpdate, WorldServer::SendDBServer_CharUpdateBattleField, WorldServer::SendDBServer_CharUpdateLadder, WorldServer::SendDBServer_CharUpdateLoginTime, WorldServer::SendDBServer_CharUpdateMatch, WorldServer::SendDBServer_CharUpdateMisc, WorldServer::SendDBServer_CharUpdateTaskResetCount, WorldServer::SendDBServer_CharUpdateTaskResetTime, WorldServer::SendDBServer_NexusFriendCreate, WorldServer::SendDBServer_NexusFriendUpdate, TabMgr::tabDelete, TabMgr::tabInsert, TabMgr::tabSelect, TabMgr::tabUpdate, WriteVariant.
bool SeDBStream::WriteString(const char *pcValue)
References Write, WriteWord.
Referenced by DBServer::Excu_SelectData, onTabSelect, DBServer::ProcessDB_CharFriendLadderLoad, DBServer::ProcessDB_CharRenameBegin, DBServer::ProcessDB_CharRenameEnd, DBServer::ProcessDB_ChraRenameEndQuery, BlockServer::ProcessTBL_UserAlterNickNameReq, DBServer::ProcessWS_CharAdd, DBServer::SendDB_FriendLadderInfoLoad, WorldServer::SendDBServer_CharInfoADD, WorldServer::SendDBServer_CharInfoRename, WorldServer::SendDBServer_CharUpdateMisc, WorldServer::SendDBServer_NexusFriendCreate, WriteVariant.
bool SeDBStream::WriteDBTime(const SeDBTime &rkTime)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear, WriteChar, WriteShort.
Referenced by DBServer::Excu_SelectData, onTabSelect, WorldServer::SendDBServer_CharMemoryUpdate, WorldServer::SendDBServer_CharQueryValid, WorldServer::SendDBServer_CharUpdateBattleField, WorldServer::SendDBServer_CharUpdateLadder, WorldServer::SendDBServer_CharUpdateLoginTime, WorldServer::SendDBServer_CharUpdateMatch, WorldServer::SendDBServer_CharUpdateMisc, WorldServer::SendDBServer_CharUpdateTaskResetTime, WorldServer::SendDBServer_NexusFriendCreate, WriteVariant.
bool SeDBStream::WriteFloat(float fValue)
References Write.
bool SeDBStream::WriteMD5(const TeMD5 &rkMD5)
References TeMD5::abyMD5, Write.
bool SeDBStream::WritePtlHSock(const SePtlHSock &rkSock)
References Write.
bool SeDBStream::WriteDoubleDword(uint64_t uiValue)
References Write.
Referenced by DBServer::Excu_SelectData, onTabSelect, WorldServer::SendDBServer_NexusFriendCreate, WorldServer::SendDBServer_NexusFriendUpdate, WriteVariant.
bool SeDBStream::WriteVariant(const SeDBVariant &var)
References SeDBVariant::getFormat, SFF_DATETIME, SFF_NUM, SFF_NUM64, SFF_STRING, WriteDBTime, WriteDoubleDword, WriteDword, WriteString.
Referenced by PlayerDataStrategy::dataUpdate, TabMgr::tabDelete, TabMgr::tabInsert, TabMgr::tabSelect, TabMgr::tabUpdate.
bool SeDBStream::Read(void *pkVoid, int iSize)
References m_iPos, m_iSize, m_pcData.
Referenced by ReadByte, ReadChar, ReadDoubleDword, ReadDword, ReadFloat, ReadMD5, ReadPtlHSock, ReadShort, ReadString, ReadWord.
char SeDBStream::ReadChar(void)
References Read.
Referenced by ReadDBTime.
short SeDBStream::ReadShort(void)
References Read.
Referenced by ReadDBTime.
Word SeDBStream::ReadWord(void)
References Read.
Referenced by ReadString.
bool SeDBStream::Write(void *pkVoid, int iSize)
References m_bLimitData, m_iPos, m_iSize, m_pcData, SSD_SEND_SIZE.
Referenced by WriteByte, WriteChar, WriteDoubleDword, WriteDword, WriteFloat, WriteMD5, WritePtlHSock, WriteShort, WriteString, WriteWord.
bool SeDBStream::WriteChar(char cValue)
References Write.
Referenced by WriteDBTime.
bool SeDBStream::WriteShort(short sValue)
References Write.
Referenced by WriteDBTime.
bool SeDBStream::WriteWord(Word wValue)
References Write.
Referenced by WriteString.