ShopTableMgr
std::map<unsigned int,ShopTable*> ShopTableMgr::m_kShopTableMap
Referenced by FillData, GetShopTable, GetShopTableMap, GetShopTableVec, ~ShopTableMgr.
ShopTableMgr * ShopTableMgr::m_pkShopTableMgr
Referenced by Get, ReLoad.
ShopTableMgr * ShopTableMgr::Get()
References m_pkShopTableMgr, ShopTableMgr.
Referenced by GlobalTableMgr::GetShopTable, TableMgr::LoadTable, ReLoad.
ShopTableMgr * ShopTableMgr::ReLoad()
References Get, m_pkShopTableMgr.
Referenced by TableMgr::ReloadTable.
ShopTableMgr::ShopTableMgr()
References Load.
Referenced by Get.
ShopTableMgr::~ShopTableMgr()
References m_kShopTableMap.
const ShopTable * ShopTableMgr::GetShopTable(unsigned int iTypeID)
References m_kShopTableMap.
Referenced by GlobalTableMgr::GetShopTable.
const std::map< unsigned int, ShopTable * > & ShopTableMgr::GetShopTableMap()
References m_kShopTableMap.
TableResArray ShopTableMgr::GetShopTableVec()
References m_kShopTableMap, TableResArray::pushBack.
bool ShopTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by ShopTableMgr.
void ShopTableMgr::FillData(ShopTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, ShopTable::ktips1, ShopTable::ktips10, ShopTable::ktips2, ShopTable::ktips3, ShopTable::ktips4, ShopTable::ktips5, ShopTable::ktips6, ShopTable::ktips7, ShopTable::ktips8, ShopTable::ktips9, m_kShopTableMap, ShopTable::uiitem1, ShopTable::uiitem10, ShopTable::uiitem2, ShopTable::uiitem3, ShopTable::uiitem4, ShopTable::uiitem5, ShopTable::uiitem6, ShopTable::uiitem7, ShopTable::uiitem8, ShopTable::uiitem9, ShopTable::uiItemTypeID.
Referenced by Load.