AvatarShopTableMgr
std::map<unsigned int,AvatarShopTable*> AvatarShopTableMgr::m_kAvatarShopTableMap
Referenced by FillData, GetAvatarShopTable, GetAvatarShopTableMap, GetAvatarShopTableVec, ~AvatarShopTableMgr.
AvatarShopTableMgr * AvatarShopTableMgr::m_pkAvatarShopTableMgr
Referenced by Get, ReLoad.
AvatarShopTableMgr * AvatarShopTableMgr::Get()
References AvatarShopTableMgr, m_pkAvatarShopTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
AvatarShopTableMgr * AvatarShopTableMgr::ReLoad()
References Get, m_pkAvatarShopTableMgr.
Referenced by TableMgr::ReloadTable.
AvatarShopTableMgr::AvatarShopTableMgr()
References Load.
Referenced by Get.
AvatarShopTableMgr::~AvatarShopTableMgr()
References m_kAvatarShopTableMap.
const AvatarShopTable * AvatarShopTableMgr::GetAvatarShopTable(unsigned int iTypeID)
References m_kAvatarShopTableMap.
const std::map< unsigned int, AvatarShopTable * > & AvatarShopTableMgr::GetAvatarShopTableMap()
References m_kAvatarShopTableMap.
TableResArray AvatarShopTableMgr::GetAvatarShopTableVec()
References m_kAvatarShopTableMap, TableResArray::pushBack.
bool AvatarShopTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AvatarShopTableMgr.
void AvatarShopTableMgr::FillData(AvatarShopTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AvatarShopTable::iGroupID, AvatarShopTable::kWeaponSkinName, m_kAvatarShopTableMap, AvatarShopTable::uiAvatarShopID.
Referenced by Load.