WatchServer::SeWatchServerInfo
typedef std::list<SeWatchServerInfo*> WatchServer::SeWatchServerInfo::TWatchServerList
SeInnerConnect* WatchServer::SeWatchServerInfo::m_pkConnect
Referenced by getConnect, setConnect, ~SeWatchServerInfo.
SeNetAddr WatchServer::SeWatchServerInfo::m_addr2Player
Referenced by getAddr2Player, setAddr2Player.
DWord WatchServer::SeWatchServerInfo::m_dwServerID
Referenced by getServertID, setServerID.
TWatchServerList WatchServer::SeWatchServerInfo::m_SlaveWatchSrv
Referenced by addSlaveWCS, ~SeWatchServerInfo.
WatchServer::SeWatchServerInfo::DECLARE_POOL(SeWatchServerInfo)
WatchServer::SeWatchServerInfo::SeWatchServerInfo()
WatchServer::SeWatchServerInfo::~SeWatchServerInfo(void)
References m_pkConnect, m_SlaveWatchSrv.
const SeInnerConnect& WatchServer::SeWatchServerInfo::getConnect() const
References m_pkConnect.
DWord WatchServer::SeWatchServerInfo::getServertID() const
References m_dwServerID.
Referenced by WatchServer::CWatchServerMgr::registerWCS.
void WatchServer::SeWatchServerInfo::setConnect(SeInnerConnect *pConnect)
References m_pkConnect.
Referenced by WatchServer::CWatchServer::Initialize.
void WatchServer::SeWatchServerInfo::setServerID(DWord svrID)
References m_dwServerID.
Referenced by WatchServer::CWatchServer::Initialize.
void WatchServer::SeWatchServerInfo::setAddr2Player(const SeNetAddr &rAddr)
References m_addr2Player.
Referenced by WatchServer::CWatchServer::Initialize.
const SeNetAddr& WatchServer::SeWatchServerInfo::getAddr2Player() const
References m_addr2Player.
void WatchServer::SeWatchServerInfo::addSlaveWCS(SeWatchServerInfo *pSlave)
References m_SlaveWatchSrv.