StarWheelTableMgr
std::map<unsigned int,StarWheelTable*> StarWheelTableMgr::m_kStarWheelTableMap
Referenced by FillData, GetStarWheelTable, GetStarWheelTableMap, GetStarWheelTableVec, ~StarWheelTableMgr.
StarWheelTableMgr * StarWheelTableMgr::m_pkStarWheelTableMgr
Referenced by Get, ReLoad.
StarWheelTableMgr * StarWheelTableMgr::Get()
References m_pkStarWheelTableMgr, StarWheelTableMgr.
Referenced by SeReMgr::InitStarWheelRes, ReLoad, MatchServer::UpdateRaceBetInfo.
StarWheelTableMgr * StarWheelTableMgr::ReLoad()
References Get, m_pkStarWheelTableMgr.
StarWheelTableMgr::StarWheelTableMgr()
References Load.
Referenced by Get.
StarWheelTableMgr::~StarWheelTableMgr()
References m_kStarWheelTableMap.
const StarWheelTable * StarWheelTableMgr::GetStarWheelTable(unsigned int iTypeID)
References m_kStarWheelTableMap.
Referenced by MatchServer::UpdateRaceBetInfo.
const std::map< unsigned int, StarWheelTable * > & StarWheelTableMgr::GetStarWheelTableMap()
References m_kStarWheelTableMap.
Referenced by SeReMgr::InitStarWheelRes.
TableResArray StarWheelTableMgr::GetStarWheelTableVec()
References m_kStarWheelTableMap, TableResArray::pushBack.
bool StarWheelTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by StarWheelTableMgr.
void StarWheelTableMgr::FillData(StarWheelTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, StarWheelTable::fValue, StarWheelTable::iOdds, StarWheelTable::kAbility, StarWheelTable::kConstell, StarWheelTable::kIcon, m_kStarWheelTableMap, StarWheelTable::uiAbilityType, StarWheelTable::uiBufferID, StarWheelTable::uiID, StarWheelTable::uiLevel.
Referenced by Load.