SeRandNum
const unsigned int SeRandNum::RAND_INT_MAX
Referenced by RandFloat.
const unsigned int SeRandNum::RAND_CONST
Referenced by RandInt, RandInteger.
const unsigned int SeRandNum::RAND_Q
Referenced by RandInt, RandInteger.
const unsigned int SeRandNum::RAND_R
Referenced by RandInt, RandInteger.
int SeRandNum::m_iSeed
Referenced by GetSeed, Initialize, SeRandNum.
unsigned int SeRandNum::m_uiPoolNum
Referenced by GetPoolNum, Initialize, RandInt, RandInteger, SeRandNum.
unsigned int SeRandNum::m_uiCount
Referenced by GetCount, Initialize, RandFloat, RandInt, RandInteger, SeRandNum.
int SeRandNum::m_iSize
Referenced by Initialize, SeRandNum, SetRecordFrameSize.
bool SeRandNum::m_bHaveRecord
Referenced by RandFloat, RandInt, RandInteger, SeRandNum.
bool SeRandNum::m_bCheckMode
Referenced by InitCurFrame, Initialize, RandFloat, RandInt, RandInteger, SeRandNum.
std::string SeRandNum::m_kFileName
unsigned int SeRandNum::m_dwFrame
Referenced by InitCurFrame, Initialize, SeRandNum.
std::vector<std::string> SeRandNum::m_kRandInfo[MAXBUFSIZE][MAXBUFSIZE]
Referenced by InitCurFrame, RandFloat, RandInt, RandInteger.
int SeRandNum::m_iCurPos
Referenced by InitCurFrame, Initialize, RandFloat, RandInt, RandInteger, SeRandNum.
SeRandomCallBack SeRandNum::m_pkCallback
Referenced by RandFloat, RandInt, RandInteger, RegisterCallBack, SeRandNum, UnRegisterCallBack.
void* SeRandNum::m_pkCallBackUserData
Referenced by RandFloat, RandInt, RandInteger, RegisterCallBack, SeRandNum.
SeRandNum::SeRandNum(void)
References m_bCheckMode, m_bHaveRecord, m_dwFrame, m_iCurPos, m_iSeed, m_iSize, m_pkCallback, m_pkCallBackUserData, m_uiCount, m_uiPoolNum, MSANGO_DEFAULT_SEED.
SeRandNum::~SeRandNum(void)
void SeRandNum::Initialize(int iSeed=0)
References m_bCheckMode, m_dwFrame, m_iCurPos, m_iSeed, m_iSize, m_uiCount, m_uiPoolNum, MSANGO_DEFAULT_SEED.
Referenced by WorldServer::WorldServer.
int SeRandNum::GetSeed(void)
References m_iSeed.
int SeRandNum::GetCount(void)
References m_uiCount.
int SeRandNum::GetPoolNum(void)
References m_uiPoolNum.
int SeRandNum::RandInt(void)
References makeCallback.f, m_pkCallback, m_pkCallBackUserData, m_uiCount, m_uiPoolNum, MSANGO_DEFAULT_SEED, RAND_CONST, RAND_Q, RAND_R.
Referenced by RandFloat, WorldServer::RandInt, MatchServer::RandInt, RaceServer::RandInt, RandInt, RaceServer::Update.
int SeRandNum::RandInt(int iMin, int iMax)
References makeCallback.f, m_pkCallback, m_pkCallBackUserData, RandInt.
float SeRandNum::RandFloat(float fMin, float fMax)
References m_pkCallback, m_pkCallBackUserData, RAND_INT_MAX, RandInt.
Referenced by WorldServer::RandFloat.
int SeRandNum::RandInteger(const char *pFuncInfo, const int iLine)
References makeCallback.f, m_bCheckMode, m_bHaveRecord, m_iCurPos, m_kRandInfo, m_pkCallback, m_pkCallBackUserData, m_uiCount, m_uiPoolNum, MAXBUFSIZE, MSANGO_DEFAULT_SEED, RAND_CONST, RAND_Q, RAND_R.
Referenced by RandFloat, RandInt.
int SeRandNum::RandInt(const char *pFuncInfo, const int iLine, int iMin, int iMax)
References makeCallback.f, m_bCheckMode, m_bHaveRecord, m_iCurPos, m_kRandInfo, m_pkCallback, m_pkCallBackUserData, m_uiCount, MAXBUFSIZE, RandInteger.
float SeRandNum::RandFloat(const char *pFuncInfo, const int iLine, float fMin, float fMax)
References m_bCheckMode, m_bHaveRecord, m_iCurPos, m_kRandInfo, m_pkCallback, m_pkCallBackUserData, m_uiCount, MAXBUFSIZE, RAND_INT_MAX, RandInteger.
void SeRandNum::InitCurFrame(unsigned int dwFrame)
References m_bCheckMode, m_dwFrame, m_iCurPos, m_kRandInfo, MAXBUFSIZE.
void SeRandNum::RegisterCallBack(SeRandomCallBack fCallBack, void *pkUserData)
References m_pkCallback, m_pkCallBackUserData.
void SeRandNum::UnRegisterCallBack()
References m_pkCallback.
void SeRandNum::SetRecordFrameSize(int iSize)
References m_iSize.