RaceHeroMgr
SePlayer & RaceHeroMgr::m_owner
Referenced by getOwner.
MMDBCharRaceHeros RaceHeroMgr::map_race_heros
Referenced by createHero, getHero, getRaceHeroMap, getRaceHerosMap, loadData, ~RaceHeroMgr.
MUserRaceMapHeroBase RaceHeroMgr::map_arena_race_heros
Referenced by checkHero_Arena, createHero_Arena, get_race_hero_data, getHero_Arena, ~RaceHeroMgr.
RaceHeroMgr::RaceHeroMgr(SePlayer &owner)
RaceHeroMgr::~RaceHeroMgr()
References map_arena_race_heros, map_race_heros.
void RaceHeroMgr::loadData(const SeDBCharRaceHero &info)
References checkHero, createHero_Arena, map_race_heros.
void RaceHeroMgr::saveData(SeDBCharRaceHero &info)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, g_kCharRaceHeroStrategy, getOwner.
Referenced by makeHero.
void RaceHeroMgr::updateData(SeDBCharRaceHero &info)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, g_kCharRaceHeroStrategy, getOwner.
Referenced by makeHero.
SeDBCharRaceHero RaceHeroMgr::genHeroParam(const DWord char_id, const DWord map_id, const DWord hero_id, const DWord win_counts)
Referenced by BlockServer::ProcessRBL_SetRaceMapHeroNtf.
SeDBCharRaceHero * RaceHeroMgr::getHero(const DWord dw_map_id, const DWord dw_hero_id)
References map_race_heros.
Referenced by checkHero, updateHero.
SeUserRaceMapHeroBase RaceHeroMgr::getHero_Arena(const DWord dw_hero_id)
References map_arena_race_heros.
Referenced by updateHero_Arena.
bool RaceHeroMgr::checkHero(const DWord dw_map_id, const DWord dw_hero_id)
References getHero.
Referenced by loadData, makeHero.
bool RaceHeroMgr::checkHero_Arena(const DWord dw_hero_id)
References map_arena_race_heros.
Referenced by makeHero_Arena.
void RaceHeroMgr::makeHero(SeDBCharRaceHero &info)
References checkHero, createHero, saveData, updateData, updateHero.
Referenced by BlockServer::ProcessRBL_SetRaceMapHeroNtf.
void RaceHeroMgr::makeHero_Arena(SeDBCharRaceHero &info)
References checkHero_Arena, WorldServer::CheckMapType, createHero_Arena, EPVPMapType_Race, g_kWorldServer, updateHero_Arena.
Referenced by BlockServer::ProcessRBL_SetRaceMapHeroNtf.
void RaceHeroMgr::createHero(SeDBCharRaceHero &info)
References g_kCharRaceHeroStrategy, PlayerDataStrategy::getGenID, map_race_heros.
Referenced by makeHero.
void RaceHeroMgr::createHero_Arena(const SeDBCharRaceHero &info)
References SeUserRaceMapHeroBase::dwHeroID, SeUserRaceMapHeroBase::dwUseCounts, SeUserRaceMapHeroBase::dwWinCounts, map_arena_race_heros.
Referenced by loadData, makeHero_Arena.
void RaceHeroMgr::updateHero(SeDBCharRaceHero &info)
References getHero.
Referenced by makeHero.
void RaceHeroMgr::updateHero_Arena(SeDBCharRaceHero &info)
References SeUserRaceMapHeroBase::dwUseCounts, SeUserRaceMapHeroBase::dwWinCounts, getHero_Arena.
Referenced by makeHero_Arena.
MDBCharRaceHero & RaceHeroMgr::getRaceHeroMap(const DWord dw_map_id)
References map_race_heros.
MMDBCharRaceHeros & RaceHeroMgr::getRaceHerosMap()
References map_race_heros.
void RaceHeroMgr::get_race_hero_data(std::vector< SeUserRaceMapHeroBase > &vDat, const DWord map_type)
References SeUserRaceMapHeroBase::dwHeroID, SeUserRaceMapHeroBase::dwUseCounts, SeUserRaceMapHeroBase::dwWinCounts, EPVPMapType_Race, map_arena_race_heros.
Referenced by BlockServer::ProcessTBL_UserMapRaceHeroReq.
RaceHeroMgr::RaceHeroMgr(SePlayer &owner)
RaceHeroMgr::~RaceHeroMgr()
void RaceHeroMgr::loadData(const SeDBCharRaceHero &info)
void RaceHeroMgr::saveData(SeDBCharRaceHero &info)
void RaceHeroMgr::updateData(SeDBCharRaceHero &info)
SeDBCharRaceHero RaceHeroMgr::genHeroParam(const DWord char_id, const DWord map_id, const DWord hero_id, const DWord win_counts)
SeDBCharRaceHero* RaceHeroMgr::getHero(const DWord dw_map_id, const DWord dw_hero_id)
SeUserRaceMapHeroBase RaceHeroMgr::getHero_Arena(const DWord dw_hero_id)
bool RaceHeroMgr::checkHero(const DWord dw_map_id, const DWord dw_hero_id)
bool RaceHeroMgr::checkHero_Arena(const DWord dw_hero_id)
void RaceHeroMgr::makeHero(SeDBCharRaceHero &info)
void RaceHeroMgr::makeHero_Arena(SeDBCharRaceHero &info)
void RaceHeroMgr::createHero(SeDBCharRaceHero &info)
void RaceHeroMgr::createHero_Arena(const SeDBCharRaceHero &info)
void RaceHeroMgr::updateHero(SeDBCharRaceHero &info)
void RaceHeroMgr::updateHero_Arena(SeDBCharRaceHero &info)
MDBCharRaceHero& RaceHeroMgr::getRaceHeroMap(const DWord dw_map_id)
MMDBCharRaceHeros& RaceHeroMgr::getRaceHerosMap()
void RaceHeroMgr::get_race_hero_data(std::vector< SeUserRaceMapHeroBase > &vDat, const DWord map_type)
SePlayer & RaceHeroMgr::getOwner()
References m_owner.
Referenced by saveData, updateData.
SePlayer& RaceHeroMgr::getOwner()