NexusFriendMgr
MNexusPlayer NexusFriendMgr::map_nexus_player_
Referenced by check_player, create, get_player.
NexusFriendMgr::NexusFriendMgr()
NexusFriendMgr::~NexusFriendMgr()
NexusPlayer NexusFriendMgr::gen_nexus_player(SeNexusUserInfo nexus_user_info, const DWord dw_online_id)
References SeNexusKeyInfo::key, SeNexusUserInfo::mark, SeNexusPlayerInfo::mark, NexusPlayer::player_info, SeNexusPlayerInfo::status, SeNexusUserInfo::user_info, SeNexusPlayerInfo::user_info.
Referenced by NexusServer::ProcessTN_NexusUserActionReq, NexusServer::ProcessWN_NexusFriendInfoSyn.
NexusFriend NexusFriendMgr::gen_nexus_friend(SeNexusUserInfo nexus_user_info, const DWord dw_online_id)
References SeNexusUserInfo::friend_info, SeNexusKeyInfo::key, SeNexusUserInfo::mark, SeNexusPlayerInfo::mark, NexusFriend::player_info, SeNexusPlayerInfo::status, SeNexusPlayerInfo::user_info.
Referenced by NexusServer::ProcessTN_NexusUserActionReq, NexusServer::ProcessWN_NexusFriendInfoSyn.
NexusPlayer NexusFriendMgr::gen_master_nexus_user(SeNexusUserInfo nexus_user_info, const DWord dw_online_id)
References SeNexusUserInfo::friend_info, SeNexusKeyInfo::key, SeNexusUserInfo::mark, SeNexusPlayerInfo::mark, NexusPlayer::player_info, SeNexusPlayerInfo::status, SeNexusPlayerInfo::user_info.
Referenced by NexusServer::ProcessTN_NexusUserActionReq.
NexusFriend NexusFriendMgr::gen_slaver_nexus_user(SeNexusUserInfo nexus_user_info, const DWord dw_online_id)
References SeNexusKeyInfo::key, SeNexusUserInfo::mark, SeNexusPlayerInfo::mark, NexusFriend::player_info, SeNexusPlayerInfo::status, SeNexusUserInfo::user_info, SeNexusPlayerInfo::user_info.
Referenced by NexusServer::ProcessTN_NexusUserActionReq.
void NexusFriendMgr::make(const NexusPlayer nexus_player, const NexusFriend nexus_friend)
References apply, cancel, confirm, ENM_Cancel, ENM_Confirm, ENM_Reject, ENM_Request, SeNexusKeyInfo::key, SeNexusPlayerInfo::mark, NexusFriend::player_info, reject.
Referenced by NexusServer::ProcessTN_NexusUserActionReq.
void NexusFriendMgr::create(NexusPlayer *p_player, NexusFriend nexus_friend)
References SeNexusUserBaseInfo::dwPlayerId, NexusPlayer::map_friends, map_nexus_player_, NexusFriend::player_info, NexusPlayer::player_info, SeNexusPlayerInfo::user_info.
Referenced by add_friend, create_friend, verify.
void NexusFriendMgr::del(NexusPlayer *p_player, const NexusFriend nexus_friend)
References SeNexusUserBaseInfo::dwPlayerId, NexusPlayer::map_friends, NexusFriend::player_info, SeNexusPlayerInfo::user_info.
Referenced by del_friend.
void NexusFriendMgr::create_friend(const NexusPlayer nexus_player, const NexusFriend nexus_friend)
References SeNexusUserBaseInfo::acName, create, SeNexusUserBaseInfo::dwPlayerId, get_player, NexusPlayer::player_info, SeNexusPlayerInfo::user_info.
Referenced by make_friend.
void NexusFriendMgr::add_friend(const NexusPlayer nexus_player, const NexusFriend nexus_friend)
References SeNexusUserBaseInfo::acName, create, SeNexusUserBaseInfo::dwPlayerId, get_player, NexusPlayer::player_info, SeNexusPlayerInfo::user_info.
Referenced by make_friend.
void NexusFriendMgr::del_friend(const NexusPlayer nexus_player, const NexusFriend nexus_friend)
References del, SeNexusUserBaseInfo::dwPlayerId, get_player, NexusPlayer::player_info, SeNexusPlayerInfo::user_info.
Referenced by cancel.
void NexusFriendMgr::make_friend(const NexusPlayer nexus_player, const NexusFriend nexus_friend)
References add_friend, check_player, create_friend, SeNexusUserBaseInfo::dwPlayerId, NexusPlayer::player_info, SeNexusPlayerInfo::user_info.
Referenced by apply, NexusServer::ProcessTN_NexusUserActionReq, NexusServer::ProcessWN_NexusFriendInfoSyn.
void NexusFriendMgr::apply(const NexusPlayer nexus_player, NexusFriend nexus_friend)
References ENM_Request, SeNexusKeyInfo::key, make_friend, SeNexusPlayerInfo::mark, NexusFriend::player_info.
Referenced by make.
void NexusFriendMgr::confirm(const NexusPlayer nexus_player, NexusFriend nexus_friend)
References ENM_Confirm, verify.
Referenced by make.
void NexusFriendMgr::reject(const NexusPlayer nexus_player, NexusFriend nexus_friend)
References ENM_Reject, verify.
Referenced by make.
void NexusFriendMgr::cancel(const NexusPlayer nexus_player, NexusFriend nexus_friend)
References del_friend.
Referenced by make.
void NexusFriendMgr::verify(const NexusPlayer nexus_player, NexusFriend nexus_friend, const DWord dw_mark)
References create, SeNexusUserBaseInfo::dwPlayerId, get_player, SeNexusKeyInfo::key, SeNexusPlayerInfo::mark, NexusFriend::player_info, NexusPlayer::player_info, SeNexusPlayerInfo::user_info.
Referenced by confirm, NexusServer::ProcessTN_NexusFriendCleanRefuseNoticeReq, NexusServer::ProcessTN_NexusUserActionReq, reject.
void NexusFriendMgr::verify(const DWord dw_player_id, const DWord dw_friend_player_id, const DWord dw_mark)
References create, SeNexusUserBaseInfo::dwPlayerId, get_player, SeNexusKeyInfo::key, SeNexusPlayerInfo::mark, NexusFriend::player_info, SeNexusPlayerInfo::user_info.
NexusPlayer * NexusFriendMgr::get_player(const DWord dw_player_id)
References map_nexus_player_.
Referenced by add_friend, create_friend, del_friend, get_player_friend, get_player_friend_map, verify.
NexusFriend * NexusFriendMgr::get_player_friend(const DWord dw_player_id, const DWord dw_friend_player_id)
References get_player, NexusPlayer::map_friends.
Referenced by get_mark.
int NexusFriendMgr::get_mark(const DWord dw_player_id, const DWord dw_friend_player_id)
References ENM_Unknow, get_player_friend, SeNexusKeyInfo::key, SeNexusPlayerInfo::mark, NexusFriend::player_info.
Referenced by check_apply, check_confirm, check_reject.
bool NexusFriendMgr::check_player(const DWord dw_player_id)
References map_nexus_player_.
Referenced by make_friend, NexusServer::ProcessTN_NexusUserActionReq.
bool NexusFriendMgr::check_apply(const DWord dw_player_id, const DWord dw_friend_player_id)
References ENM_Request, get_mark.
Referenced by NexusServer::ProcessTN_NexusUserActionReq.
bool NexusFriendMgr::check_confirm(const DWord dw_player_id, const DWord dw_friend_player_id)
References ENM_Confirm, get_mark.
Referenced by NexusServer::ProcessTN_NexusUserActionReq.
bool NexusFriendMgr::check_reject(const DWord dw_player_id, const DWord dw_friend_player_id)
References ENM_Reject, get_mark.
bool NexusFriendMgr::check_limit(const DWord dw_player_id)
References ENM_Confirm, friend_member_num_max, get_player_friend_map, SeNexusKeyInfo::key, SeNexusPlayerInfo::mark, NexusFriend::player_info.
Referenced by NexusServer::ProcessTN_NexusUserActionReq.
MNexusFriend NexusFriendMgr::get_player_friend_map(const DWord dw_player_id)
References get_player, NexusPlayer::map_friends.
Referenced by check_limit, NexusServer::ProcessTN_NexusFriendDetailInfoReq, NexusServer::ProcessTN_NexusLinkUserSync.