RaceService
int RaceService::m_iThreadIndex
Referenced by RaceService, SetThreadIndex, Update.
class CPerformanceTimingMgr * RaceService::m_pPerforceMgr
Referenced by GetPerformaceMgr, SetPerformaceMgr.
DWord RaceService::m_dwTickCount
Referenced by RaceService.
DWord RaceService::m_dwCurTime
Referenced by RaceService.
SeThreadMsgMgr RaceService::m_kThreadMsgMgr
Referenced by Initialize, PushMsg, UpdateRSCMsg.
bool RaceService::m_bStop
Referenced by DoWork, Finialize, RaceService, Update.
IRaceLogic * RaceService::m_pkRaceLogic
Referenced by Finialize, Initialize, ProcessRRC_GetHeroInfo, ProcessRRC_PlayerLeave, ProcessRRC_PlayerRelink, ProcessRRC_RaceInit, ProcessRRC_RaceOver, ProcessRRC_RaceStream, ProcessRRC_SetRaceIncmpState, RaceService, Update.
SeThreadRaceMgr RaceService::m_kRaceMgr
Referenced by OnRaceErrorRet, OnRaceEvent, OnRaceHeroInfo, OnRaceStream, ProcessRRC_PlayerLeave, ProcessRRC_PlayerRelink, ProcessRRC_RaceInit, ProcessRRC_RaceOver, ProcessRRC_RaceStart, SetThreadIndex, Update.
RaceService::RaceService(void)
References m_bStop, m_dwCurTime, m_dwTickCount, m_iThreadIndex, m_pkRaceLogic.
RaceService::~RaceService(void)
References Finialize.
bool RaceService::Initialize(int iBaseBuffSize=4 *1024 *1024)
References g_kRaceServer, RaceServer::GetRaceConfig, SeRaceConfig::iLogicDllRaceNum, SeThreadMsgMgr::Initialize, m_kThreadMsgMgr, m_pkRaceLogic, SeLogError.
Referenced by RaceServer::InitializeRaceService.
void RaceService::Update(void)
References g_kRaceServer, RaceServer::GetRacePrintTime, SeRCR_ThreadOverTime::iDTime, CPerformanceTiming::Instance, SeRCR_ThreadOverTime::iThreadIndex, M_BeforeStartInverval, m_bStop, m_iThreadIndex, m_kRaceMgr, m_pkRaceLogic, M_QbeginMutiInterval, M_QendMutiInterval, MyExceptionFilter, RaceServer::PushRSMsg, SeLogError, CPerformanceTiming::Start, CPerformanceTiming::TickNotify, SeThreadRaceMgr::UpdateRace, UpdateRSCMsg.
Referenced by DoWork.
void RaceService::Finialize(void)
References m_bStop, m_pkRaceLogic.
Referenced by RaceServer::Finialize, ~RaceService.
void RaceService::SetPerformaceMgr(class CPerformanceTimingMgr *pMgr)
References m_pPerforceMgr.
Referenced by RaceServer::InitializeRaceService.
void * RaceService::GetPerformaceMgr()
References m_pPerforceMgr.
void RaceService::Dislpay(int iFlag, char *format,...)
References SeLogInfo.
char * RaceService::GetDumpPath(void)
void RaceService::OnJustifyResult(const TeMD5 &rkRaceID, void *pkData, int iSize)
void RaceService::OnRaceStream(const TeMD5 &rkRaceID, int iSeat, DWord dwFrame, void *pkData, int iSize, bool bMustSend)
References m_kRaceMgr, SeThreadRaceMgr::PushRaceData.
virtual void RaceService::OnRaceRecordPack(const TeMD5 &rkRaceID, void *pkData, int iSize)
void RaceService::OnRaceErrorRet(const TeMD5 &rkRaceID)
References SeThreadRaceMgr::DelRace, g_kRaceServer, SeRCR_RaceError::kRaceID, m_kRaceMgr, RaceServer::PushRSMsg.
void RaceService::OnRaceEvent(const TeMD5 &rkRaceID, const BeLogicEventInfo &rkEvent)
References SeRCR_RaceEnd::acData, SeThreadRaceMgr::DelRace, g_kRaceServer, SeRCR_RaceEnd::kRaceID, m_kRaceMgr, MemCpy, MNew, RaceServer::PushRSMsg, SSD_ENDSTR_LEN, SSD_SEND_SIZE.
void RaceService::OnRaceSvrModelPack(const TeMD5 &rkRaceID, void *pkData, int iSize)
References SeRCR_RaceSvrModelPack::acData, g_kRaceServer, SeRCR_RaceSvrModelPack::iSize, SeRCR_RaceSvrModelPack::kRaceID, MemCpy, MNew, RaceServer::PushRSMsg, SSD_ENDSTR_LEN, SSD_SEND_SIZE.
void RaceService::OnAddRaceRet(const TeMD5 &rkRaceID, bool bAddSuc, int iType, DWord dwSrcServerID)
References g_kRaceServer, SeRCR_RaceInitFail::iRet, SeRCR_RaceInitFail::kRaceID, RaceServer::PushRSMsg.
void RaceService::OnPushStreamRet(const TeMD5 &rkRaceID, DWord dwSrcServerID, bool bPushRet, int iSize)
void RaceService::OnRaceNumsRet(int iType, void *pkUserData, int iNums)
void RaceService::OnRaceOffsetRet(const TeMD5 &rkRaceID, int iOffset)
virtual void RaceService::OnShowPerInfo(int iX, int iY, const char *pcInfo)
virtual void RaceService::OnThreadUpdateTime(DWord dwUpdateTime)
void RaceService::OnRaceHeroInfo(const TeMD5 &rkRaceID, int iSeat, void *pkData, int iSize)
References m_kRaceMgr, SeThreadRaceMgr::PushGetHeroInfo.
void RaceService::OnRaceKDA(const TeMD5 &rkRaceID, const BeAllHeroKDA &rInfo)
References SeRCR_Command::command, g_kRaceMgr, g_kRaceServer, SeRaceMgr::OnRaceKDA, RaceServer::PushRSMsg.
void RaceService::OnRealTimeRaceKDA(const TeMD5 &rkRaceID, const BeAllHeroKDA &rInfo)
References SeRCR_Command::command, g_kRaceMgr, g_kRaceServer, SeRaceMgr::OnRealTimeRaceKDA, RaceServer::PushRSMsg.
void RaceService::OnRealTimeRaceMapDetail(const TeMD5 &rkRaceID, const BeRaceBuildingStatus &rInfo)
References SeRCR_Command::command, g_kRaceMgr, g_kRaceServer, SeRaceMgr::OnRealTimeRaceMapDetail, RaceServer::PushRSMsg.
void RaceService::OnGetAchievement(const TeMD5 &rkRaceID, int iSeat, DWord aID, DWord aLvl)
References SeRCR_GetAchievement::dwAID, SeRCR_GetAchievement::dwLvl, g_kRaceServer, SeRCR_GetAchievement::iSeat, SeRCR_GetAchievement::kRaceID, RaceServer::PushRSMsg.
void RaceService::OnAchievementCounts(const TeMD5 &rkRaceID, int iSeat, void *pkData, int iSize)
References SeRCR_AchievementCounts::acData, g_kRaceServer, SeRCR_AchievementCounts::iSeat, SeRCR_AchievementCounts::iSize, SeRCR_AchievementCounts::kRaceID, MemCpy, MNew, RaceServer::PushRSMsg, SSD_ENDSTR_LEN, SSD_SEND_SIZE.
void RaceService::OnPlayerItemChange(const TeMD5 &rkRaceID, const BePlayerItemChange &rInfo)
References SeRCR_Command::command, g_kRaceMgr, g_kRaceServer, SeRaceMgr::OnPlayerItemChange, RaceServer::PushRSMsg.
void RaceService::OnRaceEndArenaDetail(const TeMD5 &rkRaceID, const BeRaceArenaDetail &rInfo)
References SeRCR_Command::command, g_kRaceMgr, g_kRaceServer, SeRaceMgr::OnRaceEndArenaDetail, RaceServer::PushRSMsg.
void RaceService::OnRaceEndGradeDetail(const TeMD5 &rkRaceID, const BeRaceGradeDetail &rInfo)
References SeRCR_Command::command, g_kRaceMgr, g_kRaceServer, SeRaceMgr::OnRaceEndGradeDetail, RaceServer::PushRSMsg.
void RaceService::OnDecRespawnItem(const TeMD5 &rkRaceID, const BeDecRespawnItem &rInfo)
References SeRCR_Command::command, g_kRaceMgr, g_kRaceServer, SeRaceMgr::OnDecRespawnItem, RaceServer::PushRSMsg.
void RaceService::ProcessRRC(void *pkData, int iSize)
References CMD_RSC_END_RACE, CMD_RSC_GET_HERO_INFO, CMD_RSC_PLAYER_LEAVE, CMD_RSC_PLAYER_RELINK, CMD_RSC_RACE_INIT, CMD_RSC_RACE_START, CMD_RSC_RACE_STREAM, CMD_RSC_SET_RACE_INCMP_STATE, ProcessRRC_GetHeroInfo, ProcessRRC_PlayerLeave, ProcessRRC_PlayerRelink, ProcessRRC_RaceInit, ProcessRRC_RaceOver, ProcessRRC_RaceStart, ProcessRRC_RaceStream, ProcessRRC_SetRaceIncmpState, SeThreadCmd::wCmd.
Referenced by UpdateRSCMsg.
void RaceService::ProcessRRC_RaceInit(void *pkData, int iSize)
References SeThreadRaceMgr::AddRace, SeThreadRaceMgr::AddRacePlayer, SeRSC_RaceInit::akInfo, SeRSC_RaceInit::iMapID, SeRSC_RaceInit::iNum, SeRSC_RaceInit::iSeatInfo, SeRSC_RaceInit::kRaceID, m_kRaceMgr, m_pkRaceLogic.
Referenced by ProcessRRC.
void RaceService::ProcessRRC_RaceStream(void *pkData, int iSize)
References SeRSC_RaceStream::acData, SeRSC_RaceStream::iDataSize, SeRSC_RaceStream::kRaceID, m_pkRaceLogic, SSD_ENDSTR_LEN.
Referenced by ProcessRRC.
void RaceService::ProcessRRC_PlayerLeave(void *pkData, int iSize)
References SeRSC_PlayerLeave::iSeat, SeRSC_PlayerLeave::kRaceID, m_kRaceMgr, m_pkRaceLogic, SeThreadRaceMgr::PlayerLeave.
Referenced by ProcessRRC.
void RaceService::ProcessRRC_PlayerRelink(void *pkData, int iSize)
References SeRSC_PlayerRelink::iSeat, SeRSC_PlayerRelink::kRaceID, SeRSC_PlayerRelink::kSock, m_kRaceMgr, m_pkRaceLogic, SeThreadRaceMgr::PlayerRelink.
Referenced by ProcessRRC.
void RaceService::ProcessRRC_RaceOver(void *pkData, int iSize)
References SeThreadRaceMgr::DelRace, SeRSC_RaceOver::kRaceID, m_kRaceMgr, m_pkRaceLogic.
Referenced by ProcessRRC.
void RaceService::ProcessRRC_RaceStart(void *pkData, int iSize)
References SeThreadRaceMgr::AddRacePlayer, SeRSC_RaceStart::akInfo, SeRSC_RaceStart::iNum, SeRSC_RaceStart::kRaceID, m_kRaceMgr.
Referenced by ProcessRRC.
void RaceService::ProcessRRC_GetHeroInfo(void *pkData, int iSize)
References SeRSC_GetHeroInfo::iSeat, SeRSC_GetHeroInfo::kRaceID, m_pkRaceLogic.
Referenced by ProcessRRC.
void RaceService::ProcessRRC_SetRaceIncmpState(void *pkData, int iSize)
References SeRSC_SetRaceIncmpState::bIncmp, SeRSC_SetRaceIncmpState::kRaceID, m_pkRaceLogic.
Referenced by ProcessRRC.
bool RaceService::PushMsg(void *pkData, int iSize)
References m_kThreadMsgMgr, SeThreadMsgMgr::PushMsg.
Referenced by RaceServer::PushRaceServiceMsg.
void RaceService::SetThreadIndex(int iThreadIndex)
References m_iThreadIndex, m_kRaceMgr, SeThreadRaceMgr::SetThreadIndex.
Referenced by RaceServer::InitializeRaceService.
RaceService::RaceService(void)
RaceService::~RaceService(void)
bool RaceService::Initialize(int iBaseBuffSize=4 *1024 *1024)
void RaceService::Update(void)
void RaceService::Finialize(void)
void RaceService::SetPerformaceMgr(class CPerformanceTimingMgr *pMgr)
virtual void* RaceService::GetPerformaceMgr()
virtual void RaceService::Dislpay(int iFlag, char *format,...)
virtual char* RaceService::GetDumpPath(void)
virtual void RaceService::OnJustifyResult(const TeMD5 &rkRaceID, void *pkData, int iSize)
virtual void RaceService::OnRaceStream(const TeMD5 &rkRaceID, int iSeat, DWord dwFrame, void *pkData, int iSize, bool bMustSend)
virtual void RaceService::OnRaceRecordPack(const TeMD5 &rkRaceID, void *pkData, int iSize)
virtual void RaceService::OnRaceErrorRet(const TeMD5 &rkRaceID)
virtual void RaceService::OnRaceEvent(const TeMD5 &rkRaceID, const BeLogicEventInfo &rkEvent)
virtual void RaceService::OnRaceSvrModelPack(const TeMD5 &rkRaceID, void *pkData, int iSize)
virtual void RaceService::OnAddRaceRet(const TeMD5 &rkRaceID, bool bAddSuc, int iType, DWord dwSrcServerID)
virtual void RaceService::OnPushStreamRet(const TeMD5 &rkRaceID, DWord dwSrcServerID, bool bPushRet, int iSize)
virtual void RaceService::OnRaceNumsRet(int iType, void *pkUserData, int iNums)
virtual void RaceService::OnRaceOffsetRet(const TeMD5 &rkRaceID, int iOffset)
virtual void RaceService::OnShowPerInfo(int iX, int iY, const char *pcInfo)
virtual void RaceService::OnThreadUpdateTime(DWord dwUpdateTime)
virtual void RaceService::OnRaceHeroInfo(const TeMD5 &rkRaceID, int iSeat, void *pkData, int iSize)
virtual void RaceService::OnRaceKDA(const TeMD5 &rkRaceID, const BeAllHeroKDA &rInfo)
virtual void RaceService::OnRealTimeRaceKDA(const TeMD5 &rkRaceID, const BeAllHeroKDA &rInfo)
virtual void RaceService::OnRealTimeRaceMapDetail(const TeMD5 &rkRaceID, const BeRaceBuildingStatus &rInfo)
virtual void RaceService::OnGetAchievement(const TeMD5 &rkRaceID, int iSeat, DWord aID, DWord aLvl)
virtual void RaceService::OnAchievementCounts(const TeMD5 &rkRaceID, int iSeat, void *pkData, int iSize)
virtual void RaceService::OnPlayerItemChange(const TeMD5 &rkRaceID, const BePlayerItemChange &rInfo)
virtual void RaceService::OnRaceEndArenaDetail(const TeMD5 &rkRaceID, const BeRaceArenaDetail &rInfo)
virtual void RaceService::OnRaceEndGradeDetail(const TeMD5 &rkRaceID, const BeRaceGradeDetail &rInfo)
virtual void RaceService::OnDecRespawnItem(const TeMD5 &rkRaceID, const BeDecRespawnItem &rInfo)
void RaceService::ProcessRRC(void *pkData, int iSize)
void RaceService::ProcessRRC_RaceInit(void *pkData, int iSize)
void RaceService::ProcessRRC_RaceStream(void *pkData, int iSize)
void RaceService::ProcessRRC_PlayerLeave(void *pkData, int iSize)
void RaceService::ProcessRRC_PlayerRelink(void *pkData, int iSize)
void RaceService::ProcessRRC_RaceOver(void *pkData, int iSize)
void RaceService::ProcessRRC_RaceStart(void *pkData, int iSize)
void RaceService::ProcessRRC_GetHeroInfo(void *pkData, int iSize)
void RaceService::ProcessRRC_SetRaceIncmpState(void *pkData, int iSize)
bool RaceService::PushMsg(void *pkData, int iSize)
void RaceService::SetThreadIndex(int iThreadIndex)
void RaceService::UpdateRSCMsg(void)
References SeMsgData::abyData, SeMsgData::iSize, M_BeforeStartInverval, m_kThreadMsgMgr, M_QDoMutiInterval_FN, SeThreadMsgMgr::PopMsg, ProcessRRC.
Referenced by Update.
void RaceService::DoWork()
References CPerformanceTiming::AddSink, CPerformanceTiming::BeginTrack, makeCallback.f, g_kRaceServer, RaceServer::GetMaxPacketSize, RaceServer::GetRacePrintTime, CPerformanceTiming::Init, m_bStop, CPerformanceTiming::MutiInstance, Update.
void RaceService::UpdateRSCMsg(void)
virtual void RaceService::DoWork()