TownServer
char TownServer::m_acSend[TOWN_SEND_SIZE]
Referenced by TownServer.
char TownServer::m_acPraseBuf[SSD_PRASER_SIZE]
Referenced by TownServer.
DWord TownServer::m_dwTickCount
Referenced by Initialize, TownServer, Update.
DWord TownServer::m_dwCurTime
Referenced by GetServerTime, OnNetAccept, ProcessCT_CreateChar, ProcessCT_PlayerValidate, ProcessTCPSvr_ClientConnect, ProcessTCPSvr_ReLoadReadyID, ProcessWT_CreateCharRet, ProcessWT_InitPlayerInfo, ProcessWT_PlayerValidateRet, RegisterToMS, RegisterToNS, RegisterToWCS, RegisterToWS, TownServer, Update.
SeTownConfig TownServer::m_kConfig
Referenced by ConnectToMS, ConnectToNS, ConnectToWS, ConnectWCS, GetServerID, GetTownIndex, InitializeNet, LoadConfig, LoadGameSetup, LoadServerAddr, OnNetAccept, OnNetConnected, OnNetDisconnect, ProcessCT_ReconQuery, ProcessCT_ViewBegin, ProcessNT_RegisterRet, ProcessWT_GetRaceHistoryRet, ProcessWT_QueryPlayerReconInfo, ProcessWT_RegisterRet, RegisterToMS, RegisterToNS, RegisterToWCS, RegisterToWS, Update, UpdateMSHeartPackage, UpdateNSHeartPackage, UpdateState, UpdateWCSHeartPackage, UpdateWSHeartPackage.
TeNetMgr TownServer::m_kNetMgr
Referenced by ConnectToMS, ConnectToNS, ConnectToWS, ConnectWCS, DisconnectWS, Finialize, InitializeNet, LoadServerAddr, OnNetAccept, OnNetRecv, OnTCPSvrDisconnect, ProcessTCPSvr_ReLoadReadyID, SendTCPSvr, SendTMData, SendTNData, SendTWCMSData, SendTWData, Update, UpdateMSHeartPackage, UpdateNSHeartPackage, UpdateWCSHeartPackage.
SeServerData TownServer::m_kWSData
Referenced by ConnectToWS, DisconnectWS, IsWSReady, IsWSRegistered, LoadServerAddr, OnNetConnected, OnNetDisconnect, OnNetRecv, OnTCPSvrDisconnect, ProcessCT_ReconQuery, ProcessCT_ViewBegin, ProcessWT_HeartPackageRet, ProcessWT_QueryPlayerReconInfo, ProcessWT_RegisterRet, RegisterToWS, SendTWData, UpdateState, UpdateWSHeartPackage.
DWord TownServer::m_dwWSRecvSize
Referenced by GetWSRecvSize, OnNetRecv, TownServer.
SeDBTime TownServer::m_kWSTime
Referenced by GetWSTime, TownServer.
SeServerData TownServer::m_kMSData
Referenced by ConnectToMS, IsMSReady, LoadServerAddr, OnNetConnected, OnNetDisconnect, OnNetRecv, OnTCPSvrDisconnect, ProcessMT_HeartPackageRet, ProcessMT_RegisterRet, RegisterToMS, SendTMData, UpdateMSHeartPackage, UpdateState.
SeServerData TownServer::m_kWCSData
Referenced by ConnectWCS, LoadServerAddr, OnNetConnected, OnNetDisconnect, OnNetRecv, OnTCPSvrDisconnect, ProcessWCMST_HeartPackageRet, ProcessWCMST_RegisterRet, RegisterToWCS, SendTWCMSData, UpdateState, UpdateWCSHeartPackage.
int TownServer::m_iRegisterCount
Referenced by RegisterToMS, TownServer.
SeTCPSvrData TownServer::m_kTCPSvrData
Referenced by OnNetAccept, OnNetDisconnect, OnNetRecv, ProcessTCPSvr_Register, ProcessTCPSvr_ReLoadReadyID, RegisterToWS, SendTCData, SendTCPSvr, UpdateState.
bool TownServer::m_bTCPSvrReady
Referenced by OnNetDisconnect, ProcessTCPSvr_ReLoadReadyID, TownServer.
MapAllTcpUser TownServer::m_kAllTcpUser
Referenced by GetTcpUser, GetTcpUserByID, GetTcpUserNum, OnTCPSvrDisconnect, ProcessTCPSvr_ClientConnect, ProcessTCPSvr_ClientDisconnect, ProcessTCPSvr_ReLoadReadyID.
DWord TownServer::m_dwReloadPlayerTime
Referenced by ProcessWT_LoadPlayerInfoAgainRet, SetReloadPlayerTime, TownServer.
bool TownServer::m_bWSLoadTSReady
Referenced by IsWSReady, ProcessWT_LoadPlayerInfoAgainRet, SetWSLoadTSReady, TownServer.
bool TownServer::m_bShowFullCheckInfo
Referenced by LoadConfig, TownServer.
bool TownServer::m_bShowDisconnectLog
Referenced by DisconnectTcpUser, TownServer.
bool TownServer::m_bWSReady
Referenced by IsWSReady, SetWSReady, TownServer.
bool TownServer::m_bPrintfFlux
Referenced by TownServer, Update.
DWord TownServer::m_dwPrintfFluxTime
Referenced by TownServer.
SeFlux TownServer::m_kFlux
Referenced by SendTWData, Update.
SeServerData TownServer::m_kNSData
Referenced by ConnectToNS, LoadServerAddr, OnNetConnected, OnNetDisconnect, OnNetRecv, OnTCPSvrDisconnect, ProcessNT_HeartPackageRet, ProcessNT_RegisterRet, RegisterToNS, SendTNData, UpdateNSHeartPackage, UpdateState.
TownServer::TownServer(void)
References m_acPraseBuf, m_acSend, m_bPrintfFlux, m_bShowDisconnectLog, m_bShowFullCheckInfo, m_bTCPSvrReady, m_bWSLoadTSReady, m_bWSReady, m_dwCurTime, m_dwPrintfFluxTime, m_dwReloadPlayerTime, m_dwTickCount, m_dwWSRecvSize, m_iRegisterCount, m_kWSTime, NowTime.
TownServer::~TownServer(void)
References Finialize.
bool TownServer::Initialize()
References InitializeNet, LoadConfig, LoadGameSetup, LoadServerAddr, m_dwTickCount.
void TownServer::Update(void)
References SeTownConfig::dwPrintUpdateTime, g_kPlayerMgr, m_bPrintfFlux, m_dwCurTime, m_dwTickCount, m_kConfig, m_kFlux, m_kNetMgr, SeLogError, SePlayerMgr::Update, UpdateHeartPackage, UpdateState.
void TownServer::Finialize(void)
References SePlayerMgr::Finialize, g_kPlayerMgr, m_kNetMgr.
Referenced by ~TownServer.
void TownServer::ShowConsoleTitle(int iDTime)
References g_kPlayerMgr, GetID2Str, GetServerID, GetTcpUserNum, SePlayerMgr::GetTotalPlayerNum, GetWSRecvSize, SPrintf.
SeServerActionResult TownServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F5, ReLoadTownSetup, SeLogHideTime.
void TownServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeServerData::bConnecting, SeNetAddr::iPort, SeTownConfig::kAddrWCMSServer, SeTownConfig::kMatchServer, SeTownConfig::kNexusServer, SeServerData::kSock, SeTownConfig::kWorldServer, m_kConfig, m_kMSData, m_kNSData, m_kWCSData, m_kWSData, SeLogError, SeLogInfo.
void TownServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeTCPSvrData::bRegister, SeTCPSvrData::dwConnectTime, SeNetAddr::iPort, SeTownConfig::kAddrToPlayer, SeTCPSvrData::kNetAddr, SeTCPSvrData::kSock, m_dwCurTime, m_kConfig, m_kNetMgr, m_kTCPSvrData, SeLogError, SeLogInfo.
void TownServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References SeServerData::kSock, SeTCPSvrData::kSock, m_dwWSRecvSize, m_kMSData, m_kNetMgr, m_kNSData, m_kTCPSvrData, m_kWCSData, m_kWSData, ProcessBLTData, ProcessMTData, ProcessNTData, ProcessTCPSvr, ProcessWCMSTData, ProcessWTData, STCB_BLS_TS, STCB_INTERVAL, SeCMD::wCmd.
void TownServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, SeServerData::bConnecting, SeTCPSvrData::bRegister, SeServerData::bRegistered, SeServerData::dwRegisterTime, SeNetAddr::iPort, SeTownConfig::kAddrWCMSServer, SeTownConfig::kMatchServer, SeTCPSvrData::kNetAddr, SeTownConfig::kNexusServer, SeServerData::kSock, SeTCPSvrData::kSock, SeTownConfig::kWorldServer, m_bTCPSvrReady, m_kConfig, m_kMSData, m_kNSData, m_kTCPSvrData, m_kWCSData, m_kWSData, OnTCPSvrDisconnect, SeLogError, SetWSReady.
bool TownServer::SendTW_Register(DWord dwTownMagic, DWord dwServerID, const SeTownInfo &kInfo, void *pkReceiver=NULL)
Referenced by RegisterToWS.
bool TownServer::SendTW_HeartPackage(void *pkReceiver=NULL)
Referenced by UpdateWSHeartPackage.
bool TownServer::SendTW_LoadPlayerInfoAgain(int iTotalNum, int iBegin, int iNum, const SeLoadPlayerInfoAgain *akPlayerInfo, void *pkReceiver=NULL)
Referenced by SePlayerMgr::OnLoadPlayerInfoAgain.
bool TownServer::SendTW_LoadPlayerInfoAgain(int iTotalNum, int iBegin, int iNum, std::vector< SeLoadPlayerInfoAgain > &akPlayerInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_PlayerValidate(DWord dwClientID, DWord dwPlayerID, DWord dwSessionID, DWord dwPlayerIP, DWord dwMaxMailID, const SeMobileInfo &kMobileInfo, void *pkReceiver=NULL)
Referenced by ProcessCT_PlayerValidate.
bool TownServer::SendTW_QueryName(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
Referenced by ProcessCT_QueryName.
bool TownServer::SendTW_CreateChar(DWord dwPlayerID, const char *acName, int iSex, DWord dwCardTypeID, void *pkReceiver=NULL)
Referenced by ProcessCT_CreateChar.
bool TownServer::SendTW_PlayerLeave(DWord dwPlayerID, bool bExitGame, void *pkReceiver=NULL)
Referenced by OnTCPSvrDisconnect, ProcessTCPSvr_ClientDisconnect.
bool TownServer::SendTW_RaceEndRace(DWord dwTime, DWord dwMapID, DWord dwRoomSession, const SeMatchRaceType &eMatchType, int iNum, const SeWSRaceSendInfo *akInfo, void *pkReceiver=NULL)
Referenced by ProcessMT_RaceEndSend.
bool TownServer::SendTW_RaceEndRace(DWord dwTime, DWord dwMapID, DWord dwRoomSession, const SeMatchRaceType &eMatchType, int iNum, std::vector< SeWSRaceSendInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_RaceEndGuanka(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, const SeWSGuanqiaSendInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnCheckGuankaEnd, ProcessMT_GuanqiaEndSend, SeRaceMgr::UpdateSendRaceEndInfo.
bool TownServer::SendTW_RaceEndGuanka(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, std::vector< SeWSGuanqiaSendInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_ItemExchange(DWord dwPlayerID, int iTypeID, void *pkReceiver=NULL)
Referenced by ProcessCT_ItemExchange.
bool TownServer::SendTW_SavePlayerReconInfo(DWord dwPlayerID, DWord dwRoomID, int iSeatIndex, void *pkReceiver=NULL)
Referenced by OnProcessCommMatchMsg.
bool TownServer::SendTW_TaskQueryList(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_TaskQueryList.
bool TownServer::SendTW_TaskResel(DWord dwPlayerID, DWord dwTaskID, void *pkReceiver=NULL)
Referenced by ProcessCT_TaskResel.
bool TownServer::SendTW_GetTaskReward(DWord dwPlayerID, DWord dwTaskID, void *pkReceiver=NULL)
Referenced by ProcessCT_GetTaskReward.
bool TownServer::SendTW_MatchRaceLoad(DWord dwRoomSession, DWord dwPlayerID, DWord dwMapID, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchRaceLoad.
bool TownServer::SendTW_DelReconInfo(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_DelReconInfo.
bool TownServer::SendTW_PlayerRename(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
Referenced by ProcessCT_PlayerRename.
bool TownServer::SendTW_RaceBuy(DWord dwSession, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
Referenced by ProcessMT_RaceBuy.
bool TownServer::SendTW_MapTaskOpr(DWord dwPlayerID, int iOprType, DWord dwParam, void *pkReceiver=NULL)
Referenced by ProcessCT_MapTaskOpr.
bool TownServer::SendTW_QueryNearestRaceInfo(DWord dwPlayerID, DWord dwMapID, DWord dwQueriedID, void *pkReceiver=NULL)
Referenced by ProcessCT_QueryNearestRaceInfo.
bool TownServer::SendTW_PlayerLeaveRace(DWord dwPlayerID, DWord dwRoomID, int iSeatIndex, void *pkReceiver=NULL)
Referenced by OnProcessCommMatchMsg.
bool TownServer::SendTW_BuyShopItem(DWord dwPlayerID, int types, DWord ShopID, DWord Num, void *pkReceiver=NULL)
Referenced by ProcessCT_BuyShopItem.
bool TownServer::SendTW_ShopItemGM(DWord dwPlayerID, int iNum, const ShopItem *GmItems, void *pkReceiver=NULL)
Referenced by ProcessCT_ShopItemGM.
bool TownServer::SendTW_ShopItemGM(DWord dwPlayerID, int iNum, std::vector< ShopItem > &GmItems, void *pkReceiver=NULL)
bool TownServer::SendTW_GetItemGM(DWord dwPlayerID, DWord ShopID, void *pkReceiver=NULL)
Referenced by ProcessCT_GetItemGM.
bool TownServer::SendTW_SearchUserArchivesInfoReq(DWord dwPlayerID, const SeUserArchivesNameInfo &username, void *pkReceiver=NULL)
Referenced by ProcessCT_SearchUserArchivesInfoReq.
bool TownServer::SendTW_SearchUserArchivesDetailInfoReq(DWord dwPlayerID, DWord userid, void *pkReceiver=NULL)
Referenced by ProcessCT_SearchUserArchivesDetailInfoReq.
bool TownServer::SendTWData(void *pkData, int iSize, void *pkReceiver)
References SeFlux::aiWSCountSend, SeFlux::aiWSSend, CMD_TW_BEGIN, CMD_TW_HEARTPACKAGE, CMD_TW_LOADPLAYERINFOAGAIN, CMD_TW_REGISTER, IsWSReady, SeServerData::kSock, m_kFlux, m_kNetMgr, m_kWSData, SeCMD::wCmd.
Referenced by SendTBLData.
bool TownServer::SendTC_EncryptKey(const char *abyEncryptKey, DWord dwVersion, void *pkReceiver=NULL)
Referenced by ProcessTCPSvr_ClientConnect.
bool TownServer::SendTC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, const char *acMessage, void *pkReceiver=NULL)
Referenced by OnSendShowNoticeWithoutString, ProcessMT_ReconQueryFail, ProcessWT_ShowNotice.
bool TownServer::SendTC_PlayerValidateRet(SeValidateType eValidateType, void *pkReceiver=NULL)
Referenced by ProcessWT_PlayerValidateRet.
bool TownServer::SendTC_QueryNameRet(bool bHasExist, void *pkReceiver=NULL)
Referenced by ProcessWT_QueryNameRet.
bool TownServer::SendTC_CreateCharRet(SeCreateCharRet eResult, void *pkReceiver=NULL)
Referenced by ProcessWT_CreateCharRet.
bool TownServer::SendTC_PlayerLeaveRet(void *pkReceiver=NULL)
Referenced by ProcessWT_PlayerLeave.
bool TownServer::SendTC_InitPlayerInfo(DWord dwPlayerID, const char *acName, DWord iGold, DWord iDiamond, DWord dwLevel, DWord dwExp, const SeLadderInfo &kLadder, Byte byEquipSetIndex, DWord dwServerTime, DWord dwOnlineTime, void *pkReceiver=NULL)
Referenced by ProcessWT_InitPlayerInfo.
bool TownServer::SendTC_MatchRaceAddr(DWord dwSessionID, int dwKey, SeRaceValidType eValidType, const SePtlNetAddr &kRaceAddr, const SePtlNetAddr &kRaceAddrUdp, int iSeat, int iNum, const SeNoticeMatchPlayerInfo *akPlayerInfo, void *pkReceiver=NULL)
Referenced by ProcessMT_NotifyAddrToMatch.
bool TownServer::SendTC_MatchRaceAddr(DWord dwSessionID, int dwKey, SeRaceValidType eValidType, const SePtlNetAddr &kRaceAddr, const SePtlNetAddr &kRaceAddrUdp, int iSeat, int iNum, std::vector< SeNoticeMatchPlayerInfo > &akPlayerInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerAppear(int iNum, const SePlayerAppear *akPlayerList, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerAppear(int iNum, std::vector< SePlayerAppear > &akPlayerList, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerDisappear(int iNum, const SePlayerDisappear *adwID, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerDisappear(int iNum, std::vector< SePlayerDisappear > &adwID, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerGoPos(DWord dwPlayerID, float fDirect, void *pkReceiver=NULL)
bool TownServer::SendTC_ExchangeInit(int iNum, const SePtlExchange *akPtlExchange, void *pkReceiver=NULL)
Referenced by ProcessWT_ExchangeInit.
bool TownServer::SendTC_ExchangeInit(int iNum, std::vector< SePtlExchange > &akPtlExchange, void *pkReceiver=NULL)
bool TownServer::SendTC_ViewResult(SeViewResultType eResult, int iData, void *pkReceiver=NULL)
Referenced by ProcessMT_ViewQueryFail.
bool TownServer::SendTC_QueryRaceRoomListRet(int iCurPage, int iMaxPage, int iRoomNums, const SeMatchRoomListInfo *akRoomInfo, void *pkReceiver=NULL)
Referenced by ProcessMT_QueryRaceRoomListRet.
bool TownServer::SendTC_QueryRaceRoomListRet(int iCurPage, int iMaxPage, int iRoomNums, std::vector< SeMatchRoomListInfo > &akRoomInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_ItemExchangeRet(int iTypeID, int iReturn, void *pkReceiver=NULL)
Referenced by ProcessWT_ItemExchangeRet.
bool TownServer::SendTC_UpdateMisc(SeMiscType eType, int iValue, int iValue2, void *pkReceiver=NULL)
Referenced by ProcessWT_UpdateMisc.
bool TownServer::SendTC_DelayCheckRet(void *pkReceiver=NULL)
Referenced by ProcessCT_DelayCheck.
bool TownServer::SendTC_BiVoiceEnterInfo(int roomid, const char *acLoginSession, const char *acRoomSession, void *pkReceiver=NULL)
Referenced by ProcessMT_BiVoiceEnterInfo.
bool TownServer::SendTC_TaskQueryListRet(int iNum, const SePtlTask *akList, void *pkReceiver=NULL)
Referenced by ProcessWT_TaskQueryListRet.
bool TownServer::SendTC_TaskQueryListRet(int iNum, std::vector< SePtlTask > &akList, void *pkReceiver=NULL)
bool TownServer::SendTC_TaskReselRet(DWord dwSrcTaskID, const SePtlTask &kNewTask, void *pkReceiver=NULL)
Referenced by ProcessWT_TaskReselRet.
bool TownServer::SendTC_AskEnterWaitRace(DWord dwMapID, int iNum, const SeRaceWaitPlayer *akPlayerList, void *pkReceiver=NULL)
Referenced by ProcessMT_AskEnterWaitRace.
bool TownServer::SendTC_AskEnterWaitRace(DWord dwMapID, int iNum, std::vector< SeRaceWaitPlayer > &akPlayerList, void *pkReceiver=NULL)
bool TownServer::SendTC_CardUpdate(void *pkReceiver=NULL)
bool TownServer::SendTC_StartMatchRet(int iResult, DWord dwMapID, void *pkReceiver=NULL)
Referenced by ProcessMT_StartMatchRet.
bool TownServer::SendTC_FriendRequestInit(int iNum, const SePtlFriendRequest *akRequest, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendRequestInit(int iNum, std::vector< SePtlFriendRequest > &akRequest, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendRequestAdd(const SePtlFriendRequest &kInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendInit(int iNum, const SePtlFriend *akFriend, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendInit(int iNum, std::vector< SePtlFriend > &akFriend, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendAdd(const SePtlFriend &kFriend, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendDel(DWord dwFriendID, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendUpdateStatus(DWord dwFriendID, SeOnlineStatus eStatus, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendRemarkRet(DWord dwFriendID, const char *acRemarks, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryRaceBetInfoRet(DWord dwdwConstellIDA, DWord dwdwConstellIDB, float fOddsA, float fOddsB, void *pkReceiver=NULL)
Referenced by ProcessMT_QueryRaceBetInfoRet.
bool TownServer::SendTC_ItemDel(DWord dwItemID, SeItemDelType eType, void *pkReceiver=NULL)
Referenced by ProcessWT_ItemDel.
bool TownServer::SendTC_KickPlayer(void *pkReceiver=NULL)
Referenced by ProcessWT_KickPlayer.
bool TownServer::SendTC_ReceiveMail(int iNum, const SePtlMail *akMail, void *pkReceiver=NULL)
Referenced by ProcessWT_ReceiveMail.
bool TownServer::SendTC_ReceiveMail(int iNum, std::vector< SePtlMail > &akMail, void *pkReceiver=NULL)
bool TownServer::SendTC_UpdateMail(int iNum, const SeMailUpdate *akInfo, void *pkReceiver=NULL)
Referenced by ProcessWT_UpdateMail.
bool TownServer::SendTC_UpdateMail(int iNum, std::vector< SeMailUpdate > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_MailOprRet(int iType, DWord dwMailID, int iRet, void *pkReceiver=NULL)
Referenced by ProcessWT_MailOprRet.
bool TownServer::SendTC_PlayerRename(const char *acName, void *pkReceiver=NULL)
Referenced by ProcessWT_PlayerRename.
bool TownServer::SendTC_HeartBeat(void *pkReceiver=NULL)
Referenced by ProcessCT_HeartBeat.
bool TownServer::SendTC_QueryMapTaskListRet(DWord dwMapID, int iNum, const SePtlMapTask *akPtlMapTask, void *pkReceiver=NULL)
Referenced by ProcessWT_QueryMapTaskListRet.
bool TownServer::SendTC_QueryMapTaskListRet(DWord dwMapID, int iNum, std::vector< SePtlMapTask > &akPtlMapTask, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryNearestRaceInfoRet(DWord dwQueriedID, int iNum, const SePtlRaceHistory *akRaceInfo, void *pkReceiver=NULL)
Referenced by ProcessWT_QueryNearestRaceInfoRet.
bool TownServer::SendTC_QueryNearestRaceInfoRet(DWord dwQueriedID, int iNum, std::vector< SePtlRaceHistory > &akRaceInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_ResIncompleteRaceList(int iNum, const SeIncompleteRaceBaseInfo *akIncmpRaceList, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnReqGetIncmpRaceList, ProcessMT_ResIncompleteRaceList.
bool TownServer::SendTC_ResIncompleteRaceList(int iNum, std::vector< SeIncompleteRaceBaseInfo > &akIncmpRaceList, void *pkReceiver=NULL)
bool TownServer::SendTC_AddIncompleteRace(const SeIncompleteRaceBaseInfo &akIncmpRace, void *pkReceiver=NULL)
Referenced by SePlayerMgr::OnAddIncmpRace.
bool TownServer::SendTC_RemoveIncompleteRace(DWord iRoomID, void *pkReceiver=NULL)
Referenced by SePlayerMgr::OnRemoveIncmpRace.
bool TownServer::SendTC_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, const SeSeatBaseInfo *oIncmpRaceBaseInfo, void *pkReceiver=NULL)
Referenced by SePlayerMgr::OnIncmpRaceKDA, ProcessMT_ResIncmpRaceSeatBaseInfo.
bool TownServer::SendTC_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, std::vector< SeSeatBaseInfo > &oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_InGameDisconn(DWord dwRoomID, int iSeat, int iReconTime, void *pkReceiver=NULL)
Referenced by ProcessMT_NotifyAddrToMatch.
bool TownServer::SendTC_CreateRoomRet(SeCreateRoomRetType eType, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchCreateRoomRet.
bool TownServer::SendTC_CreateRoomRet(SeCreateRoomRetType eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryRoomListRet(int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchQueryRoomListRet.
bool TownServer::SendTC_QueryRoomListRet(int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomJoinRet(SeRoomJoinRetType eType, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchRoomJoinRet.
bool TownServer::SendTC_RoomJoinRet(SeRoomJoinRetType eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomSwitchSeatRet(SeRoomJoinRetType eType, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchRoomSwitchSeatRet.
bool TownServer::SendTC_RoomMemberNotify(SeRoomNtfCode eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, const SeRoomMember *akInfo, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchRoomMemberNotifyRet.
bool TownServer::SendTC_RoomMemberNotify(SeRoomNtfCode eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, std::vector< SeRoomMember > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomLeaveRet(DWord dwRoomID, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchRoomLeaveRet.
bool TownServer::SendTC_RoomStartRet(DWord dwRoomID, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomKickSomeoneRet(DWord dwRoomID, int iseat, SeRoomKickCode eType, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchRoomKickSomeoneRet.
bool TownServer::SendTC_RoomInviteNotify(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
Referenced by ProcessWT_RoomInviteNotify.
bool TownServer::SendTC_GetRaceHistoryRet(int iType, int iPage, int iMaxPage, const char *acURLBase, int iNum, const SePtlRaceHistory *akInfo, void *pkReceiver=NULL)
Referenced by ProcessWT_GetRaceHistoryRet.
bool TownServer::SendTC_GetRaceHistoryRet(int iType, int iPage, int iMaxPage, const char *acURLBase, int iNum, std::vector< SePtlRaceHistory > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_ResAchievementDat(DWord dwPlayerID, int iPage, int iMaxPage, int iNum, const SeAchievementPtlDat *akAchevementDat, void *pkReceiver=NULL)
bool TownServer::SendTC_ResAchievementDat(DWord dwPlayerID, int iPage, int iMaxPage, int iNum, std::vector< SeAchievementPtlDat > &akAchevementDat, void *pkReceiver=NULL)
bool TownServer::SendTC_ResAchievementCounts(DWord dwPlayerID, int iNum, const SeAchievementCounts *akAchevementCounts, void *pkReceiver=NULL)
bool TownServer::SendTC_ResAchievementCounts(DWord dwPlayerID, int iNum, std::vector< SeAchievementCounts > &akAchevementCounts, void *pkReceiver=NULL)
bool TownServer::SendTC_GetAchievement(DWord dwPlayerID, DWord a_ID, int GetTime, void *pkReceiver=NULL)
bool TownServer::SendTC_ResView(const Byte *rID, const SePtlNetAddr &kViewAddr, void *pkReceiver=NULL)
Referenced by ProcessWCMST_ResView.
bool TownServer::SendTC_ResView(std::vector< Byte > &rID, const SePtlNetAddr &kViewAddr, void *pkReceiver=NULL)
bool TownServer::SendTC_ResViewList(int iPage, int iMaxPage, int iNum, const SeViewList *akSeViewList, void *pkReceiver=NULL)
Referenced by ProcessWCMST_ResViewList.
bool TownServer::SendTC_ResViewList(int iPage, int iMaxPage, int iNum, std::vector< SeViewList > &akSeViewList, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerNewItem(int iNum, const SeItemNoti *SeItemArray, void *pkReceiver=NULL)
Referenced by ProcessWT_PlayerNewItem.
bool TownServer::SendTC_PlayerNewItem(int iNum, std::vector< SeItemNoti > &SeItemArray, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerOperRep(int iResult, void *pkReceiver=NULL)
Referenced by ProcessBLT_PlayerOperRep, ProcessWT_PlayerOperRep.
bool TownServer::SendTC_OpenRandBoxRet(int iResult, int iNum, const SeRandBoxItem *ItemArray, void *pkReceiver=NULL)
Referenced by ProcessBLT_OpenRandBoxRet.
bool TownServer::SendTC_OpenRandBoxRet(int iResult, int iNum, std::vector< SeRandBoxItem > &ItemArray, void *pkReceiver=NULL)
bool TownServer::SendTC_PutOnEquipRet(int iResult, Word wEquipPos, DWord dwItemID, void *pkReceiver=NULL)
Referenced by ProcessBLT_PutOnEquipRet.
bool TownServer::SendTC_TakeOffEquipRet(int iResult, Word wEquipPos, void *pkReceiver=NULL)
Referenced by ProcessBLT_TakeOffEquipRet.
bool TownServer::SendTC_ResRaceDetailInfo(int page_number, int page_max_number, int iNum, const SeRaceDetailInfo *akRaceDetailInfo, void *pkReceiver=NULL)
Referenced by ProcessWCMST_ResRaceDetailInfo.
bool TownServer::SendTC_ResRaceDetailInfo(int page_number, int page_max_number, int iNum, std::vector< SeRaceDetailInfo > &akRaceDetailInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerMoneyAndDiamond(DWord dwPlayerID, DWord dwGold, DWord dwDiamond, void *pkReceiver=NULL)
Referenced by ProcessWT_PlayerMoneyAndDiamond.
bool TownServer::SendTC_ShopItemGmRep(DWord dwPlayerID, int iResult, const ShopItem &GmItem, void *pkReceiver=NULL)
Referenced by ProcessWT_ShopItemGmRep.
bool TownServer::SendTC_NexusFriendDetailInfoRes(int page_number, int page_max_number, int iNum, const SeNexusPlayerInfo *akNexusFriendInfo, void *pkReceiver=NULL)
Referenced by ProcessNT_NexusFriendDetailInfoRes.
bool TownServer::SendTC_NexusFriendDetailInfoRes(int page_number, int page_max_number, int iNum, std::vector< SeNexusPlayerInfo > &akNexusFriendInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusUserPromotionDetailInfoRes(const SeNexusUserPromotionInfo &nexus_user_promotion, void *pkReceiver=NULL)
bool TownServer::SendTC_SearchUserArchivesInfoRes(const SeUserArchivesInfo &user_archives_info, void *pkReceiver=NULL)
Referenced by ProcessWT_SearchUserArchivesInfoRes.
bool TownServer::SendTC_SearchUserArchivesDetailInfoRes(const SeUserArchivesInfo &user_archives_info, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusUserActionSync(const SeNexusUserInfo &sync_info, void *pkReceiver=NULL)
Referenced by ProcessNT_NexusUserActionSync.
bool TownServer::SendTC_ReqMatchRep(MatchReqResult ReqResult, void *pkReceiver=NULL)
Referenced by ProcessCT_PlayerMatchReq, ProcessMT_ReqMatchRep, ProcessNT_MatchTeamMemberRes.
bool TownServer::SendTC_CancelMatchRep(MatchCancelResult CancelResult, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchCancelRep.
bool TownServer::SendTC_NotiMatcherPre(DWord WaitID, DWord dwPlayerNum, void *pkReceiver=NULL)
Referenced by ProcessMT_NotiMatcherPre.
bool TownServer::SendTC_NotiMatcherResult(DWord ResultKind, void *pkReceiver=NULL)
Referenced by ProcessMT_NotiMatcherResult.
bool TownServer::SendTC_SingleMatchConfirm(DWord PlayerID, bool BolConfirm, DWord PlayerIndex, DWord MaxPlayerNum, void *pkReceiver=NULL)
Referenced by ProcessMT_SingleMatchConfirm.
bool TownServer::SendTC_SeUserRaceArenaDetailInfoRes(const SeRaceEndArenaResult &race_arena_info, void *pkReceiver=NULL)
Referenced by ProcessBLT_UserRaceArenaDetailAck.
bool TownServer::SendTC_TeamChangeSync(DWord dwTeamID, DWord dwLeaderID, const char *acLeaderName, void *pkReceiver=NULL)
Referenced by ProcessNT_TeamChangeSync.
bool TownServer::SendTC_TeamLeaderSync(DWord dwGuestID, const char *acGuestName, DWord dwMark, void *pkReceiver=NULL)
Referenced by ProcessNT_TeamLeaderSync.
bool TownServer::SendTC_TeamMemberSync(DWord dwTeamID, DWord dwInviterID, const char *acInviterName, DWord dwMark, void *pkReceiver=NULL)
Referenced by ProcessNT_TeamMemberSync.
bool TownServer::SendTC_TeamUserStateRes(DWord dwStateID, void *pkReceiver=NULL)
Referenced by ProcessNT_TeamUserStateRes.
bool TownServer::SendTC_TeamMemberInfoRes(DWord dwTeamID, int iNum, const SeTeamMemberBaseInfo *member_info, void *pkReceiver=NULL)
Referenced by ProcessNT_TeamMemberInfoRes.
bool TownServer::SendTC_TeamMemberInfoRes(DWord dwTeamID, int iNum, std::vector< SeTeamMemberBaseInfo > &member_info, void *pkReceiver=NULL)
bool TownServer::SendTC_UserHeroSync(DWord dwPlayerID, int num, const SeUserHeroSyncInfo *akHeroSyncInfo, void *pkReceiver=NULL)
Referenced by ProcessWT_UserHeroSync.
bool TownServer::SendTC_UserHeroSync(DWord dwPlayerID, int num, std::vector< SeUserHeroSyncInfo > &akHeroSyncInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusFriendStatusSync(DWord dwFriendID, DWord dwOnlineID, void *pkReceiver=NULL)
Referenced by ProcessNT_NexusFriendStatusSync.
bool TownServer::SendTC_PlayerLadder(const SeLadderInfo &kLadder, void *pkReceiver=NULL)
Referenced by ProcessWT_PlayerLadder.
bool TownServer::SendTC_NexusFriendLimitRes(DWord dwLimitID, void *pkReceiver=NULL)
Referenced by ProcessNT_NexusFriendLimitRes.
bool TownServer::SendTC_NexusFriendCleanRefuseNoticeRes(DWord dwGuestID, void *pkReceiver=NULL)
Referenced by ProcessNT_NexusFriendCleanRefuseNoticeRes.
bool TownServer::SendTC_UserStatusQueryReqRes(int iNum, const SeUserStatusBaseInfo *base_info, void *pkReceiver=NULL)
Referenced by ProcessNT_UserStatusQueryRes.
bool TownServer::SendTC_UserStatusQueryReqRes(int iNum, std::vector< SeUserStatusBaseInfo > &base_info, void *pkReceiver=NULL)
bool TownServer::SendTC_EquipSchema(int iNum, const SeEquipSchemaInfo *akEquips, void *pkReceiver=NULL)
Referenced by ProcessWT_EquipSchema.
bool TownServer::SendTC_EquipSchema(int iNum, std::vector< SeEquipSchemaInfo > &akEquips, void *pkReceiver=NULL)
bool TownServer::SendTC_LadderRankQueryAck(int iNum, const SeLadderRankInfo *RankList, void *pkReceiver=NULL)
Referenced by ProcessBLT_LadderRankQueryAck.
bool TownServer::SendTC_LadderRankQueryAck(int iNum, std::vector< SeLadderRankInfo > &RankList, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendLadderInfoNtf(int iNum, const SeLadderRankInfo *RankList, void *pkReceiver=NULL)
Referenced by ProcessWT_FriendLadderInfoNtf.
bool TownServer::SendTC_FriendLadderInfoNtf(int iNum, std::vector< SeLadderRankInfo > &RankList, void *pkReceiver=NULL)
bool TownServer::SendTC_UserRaceMapHeroAck(int iNum, const SeUserRaceMapHeroBase *hero_info, void *pkReceiver=NULL)
Referenced by ProcessBLT_UserRaceHeroAck.
bool TownServer::SendTC_UserRaceMapHeroAck(int iNum, std::vector< SeUserRaceMapHeroBase > &hero_info, void *pkReceiver=NULL)
bool TownServer::SendTC_SetActiveAvatarAck(int iResult, DWord dwItemID, void *pkReceiver=NULL)
Referenced by ProcessBLT_SetActiveAvatarAck.
bool TownServer::SendTC_ActiveAvatarNtf(int iNum, const DWord *avartars, void *pkReceiver=NULL)
Referenced by ProcessWT_ActiveAvatarNtf.
bool TownServer::SendTC_ActiveAvatarNtf(int iNum, std::vector< DWord > &avartars, void *pkReceiver=NULL)
bool TownServer::SendTC_UserAlterNickNameAck(int iResult, void *pkReceiver=NULL)
Referenced by ProcessBLT_UserAlterNickNameAck.
bool TownServer::SendTC_UserAlterAvatarAndFrameNtf(DWord dwAvatarID, DWord dwAvatarFrameID, void *pkReceiver=NULL)
Referenced by ProcessBLT_UserAlterAvatarAndFrameNtf.
bool TownServer::SendTC_LadderDetailInfoAck(const SeLadderDetailInfo &info, void *pkReceiver=NULL)
Referenced by ProcessBLT_LadderDetailInfoAck.
bool TownServer::SendTC_AchieveInfoAck(int iNum1, const SeAchieveFinish *finishInfo, int iNum2, const SeAchieveSchedule *scheduleInfo, void *pkReceiver=NULL)
Referenced by ProcessBLT_AchieveInfoAck.
bool TownServer::SendTC_AchieveInfoAck(int iNum1, std::vector< SeAchieveFinish > &finishInfo, int iNum2, std::vector< SeAchieveSchedule > &scheduleInfo, void *pkReceiver=NULL)
bool TownServer::SendTCData(void *pkData, int iSize, void *pkReceiver)
References SeTCPSvrData::kSock, m_kTCPSvrData, SendTCPSvr_SendData.
bool TownServer::SendTM_Register(DWord dwTownMagic, DWord dwServerID, DWord dwAreaID, int iTownIndex, DWord dwDefaultMapID, int iMaxPlayerNum, int iRegisterCount, void *pkReceiver=NULL)
Referenced by RegisterToMS.
bool TownServer::SendTM_HeartPackage(int iPlayerConn, int iRaceConn, void *pkReceiver=NULL)
Referenced by UpdateMSHeartPackage.
bool TownServer::SendTM_CommMatchMsg(DWord dwMatchSession, const SeCommMatchMsg &eMsg, DWord dwParam, int iParam, DWord dwParam2, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchSessionNotify, ProcessMT_NotifyAddrToMatch.
bool TownServer::SendTM_ReconQuery(DWord dwRoomID, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iSeat, int iOffset, DWord dwFrame, void *pkReceiver=NULL)
Referenced by ProcessCT_ReconQuery, ProcessWT_QueryPlayerReconInfo.
bool TownServer::SendTM_ViewQuery(DWord dwSession, DWord dwDstPlayerID, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iViewDelay, void *pkReceiver=NULL)
Referenced by ProcessCT_ViewBegin.
bool TownServer::SendTM_QueryRaceRoomList(DWord dwPlayerID, DWord dwRoomSession, int iPage, DWord dwMapID, void *pkReceiver=NULL)
Referenced by ProcessCT_QueryRaceRoomList.
bool TownServer::SendTM_QueryRaceBetInfo(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_QueryRaceBetInfo.
bool TownServer::SendTM_RaceBuyRet(DWord dwSession, bool bSuccess, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
Referenced by ProcessWT_RaceBuyRet.
bool TownServer::SendTM_PlayerLeave(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by SePlayerMgr::DelPlayer.
bool TownServer::SendTM_MatchCreateRoom(DWord dwPlayerID, const char *acName, DWord dwMapID, DWord dwCamp, int iDifficulty, bool bPlayBoss, bool bUseRobot, DWord dwGameMode, const char *strRoomName, const char *strPass, void *pkReceiver=NULL)
Referenced by ProcessCT_CreateRoom.
bool TownServer::SendTM_MatchQueryRoomList(DWord dwPlayerID, int iCurPage, DWord dwMapID, void *pkReceiver=NULL)
Referenced by ProcessCT_QueryRoomList.
bool TownServer::SendTM_MatchRoomJoin(DWord dwPlayerID, const char *acName, DWord dwDstRoom, DWord dwCamp, int iseat, const char *strPass, void *pkReceiver=NULL)
Referenced by ProcessCT_RoomJoin.
bool TownServer::SendTM_MatchRoomLeave(DWord dwPlayerID, DWord dwDstRoom, void *pkReceiver=NULL)
Referenced by ProcessCT_RoomLeave.
bool TownServer::SendTM_MatchRoomReady(DWord dwPlayerID, DWord dwRoomID, void *pkReceiver=NULL)
Referenced by ProcessCT_RoomStart.
bool TownServer::SendTM_MatchRoomSwitchSeat(DWord dwPlayerID, DWord dwDstRoom, DWord dwCamp, int iseat, void *pkReceiver=NULL)
Referenced by ProcessCT_RoomSwitchSeat.
bool TownServer::SendTM_MatchRoomKickSomeone(DWord dwPlayerID, DWord dwRoomID, DWord dwKickedPlayerID, int iseat, void *pkReceiver=NULL)
Referenced by ProcessCT_RoomKickSomeone.
bool TownServer::SendTM_MatchRoomInvite(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessNT_RoomInviteNotifyVerifyRsp.
bool TownServer::SendTM_MatchRoomInviteRsp(DWord dwPlayerID, DWord dwRoomID, DWord dwInvitorID, const char *acName, void *pkReceiver=NULL)
Referenced by ProcessCT_RoomInviteRsp.
bool TownServer::SendTM_ReqIncompleteRaceKDA(DWord dwRoomSession, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_ReqIncompleteRaceKDA.
bool TownServer::SendTM_ReqIncompleteRaceList(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_ReqIncompleteRaceList.
bool TownServer::SendTM_ReconPLayerName(DWord dwPlayerID, DWord dwRoomSession, const char *acName, void *pkReceiver=NULL)
Referenced by ProcessCT_ReconQuery.
bool TownServer::SendTM_PlayerMatchCancel(DWord playerID, void *pkReceiver=NULL)
Referenced by ProcessCT_PlayerMatchCancel.
bool TownServer::SendTM_MatchConfirm(DWord PlayerID, DWord WaitID, bool BoolConfirm, void *pkReceiver=NULL)
Referenced by ProcessCT_MatchConfirm.
bool TownServer::SendTM_PlayerMatchReq(DWord dwPlayerID, DWord MapID, Byte bySeats, DWord MemberNum, const DWord *IDArray, void *pkReceiver=NULL)
Referenced by ProcessNT_MatchTeamMemberRes.
bool TownServer::SendTM_PlayerMatchReq(DWord dwPlayerID, DWord MapID, Byte bySeats, DWord MemberNum, std::vector< DWord > &IDArray, void *pkReceiver=NULL)
bool TownServer::SendTMData(void *pkData, int iSize, void *pkReceiver)
References SeServerData::bRegistered, CMD_TM_REGISTER, SeServerData::kSock, m_kMSData, m_kNetMgr, SeCMD::wCmd.
bool TownServer::SendTCPSvr(void *pkData, int iSize)
References SeTCPSvrData::kSock, m_kNetMgr, m_kTCPSvrData, SeLogError, SeCMD::wCmd.
Referenced by SendTCPSvr_ConnectState, SendTCPSvr_HeartPackageRet, SendTCPSvr_RegisterRet, SendTCPSvr_SendData, SendTCPSvr_SeverDisconnect.
bool TownServer::SendTCPSvr_RegisterRet(SeRegisterRet eRet)
References SeTT_RegisterRet::eRegisterRet, SendTCPSvr.
Referenced by ProcessTCPSvr_Register.
bool TownServer::SendTCPSvr_SeverDisconnect(DWord dwClientID)
References SeTT_SeverDisconnect::dwClientID, SendTCPSvr.
Referenced by DisconnectTcpUser.
bool TownServer::SendTCPSvr_SendData(DWord dwClientID, void *pkData, int iSize)
References SeTT_SendData::acData, SeTT_SendData::dwClientID, SeTT_SendData::iDataLen, MemCpy, MNew, SendTCPSvr, SSD_ENDSTR_LEN, SSD_MAX_SEND_SIZE, SSD_SEND_SIZE.
Referenced by SendTCData.
bool TownServer::SendTCPSvr_ConnectState(DWord dwClientID, DWord dwAccountID, int iReturn)
References SeTT_ConnectState::dwClientID, SeTT_ConnectState::dwParam1, SeTT_ConnectState::iReturn, SendTCPSvr.
Referenced by ProcessWT_PlayerValidateRet.
bool TownServer::SendTCPSvr_HeartPackageRet(void)
References SendTCPSvr.
Referenced by ProcessTCPSvr_HeartPackage.
DWord TownServer::GetServerTime(void)
References m_dwCurTime.
Referenced by SePlayerMgr::OnLoadPlayerInfoAgain, ProcessWT_PlayerLeave, UpdateHeartPackage, UpdateMSHeartPackage, UpdateNSHeartPackage, UpdateState, UpdateWCSHeartPackage, UpdateWSHeartPackage.
const SeDBTime & TownServer::GetWSTime()
References SeDBTime::IsValid, m_kWSTime, NowTime.
DWord TownServer::GetServerID(void)
References SeTownConfig::dwServerID, m_kConfig.
Referenced by ShowConsoleTitle.
int TownServer::GetTownIndex(void)
References SeTownConfig::iTownIndex, m_kConfig.
DWord TownServer::GetWSRecvSize(void)
References m_dwWSRecvSize.
Referenced by ShowConsoleTitle.
bool TownServer::IsWSRegistered(void)
References SeServerData::bRegistered, m_kWSData.
Referenced by SeRaceMgr::UpdateSendRaceEndInfo.
void TownServer::SetWSReady(bool bReady)
References m_bWSReady, SeLogError, SeLogInfo.
Referenced by OnNetDisconnect, ProcessWT_IsReady, ProcessWT_RegisterRet.
bool TownServer::IsWSReady(void)
References SeServerData::bRegistered, SeServerData::kSock, m_bWSLoadTSReady, m_bWSReady, m_kWSData.
Referenced by SeRaceMgr::OnCheckGuankaEnd, SendTWData, SeRaceMgr::UpdateSendRaceEndInfo.
bool TownServer::IsMSReady(void)
References SeServerData::bRegistered, SeServerData::kSock, m_kMSData.
void TownServer::SetReloadPlayerTime(DWord dwTime)
References m_dwReloadPlayerTime.
Referenced by SePlayerMgr::OnLoadPlayerInfoAgain.
void TownServer::SetWSLoadTSReady(bool bReady)
References m_bWSLoadTSReady.
Referenced by SePlayerMgr::OnLoadPlayerInfoAgain.
void TownServer::DisconnectWS(void)
References SeServerData::kSock, m_kNetMgr, m_kWSData.
Referenced by UpdateWSHeartPackage.
SeTCPUser * TownServer::GetTcpUserByID(DWord dwAccountID)
References SeTCPUser::dwPlayerID, m_kAllTcpUser, SeLogError.
Referenced by SePlayerMgr::GetPlayerIP, ProcessCT_PlayerValidate, ProcessMT_QueryRaceRoomListRet, ProcessMT_ViewQueryFail, ProcessWT_CreateCharRet, ProcessWT_InitPlayerInfo, ProcessWT_KickPlayer, ProcessWT_PlayerLeave, ProcessWT_QueryNameRet, ProcessWT_ShowNotice.
SeTCPUser * TownServer::GetTcpUser(DWord dwClientID)
References m_kAllTcpUser.
Referenced by ProcessTCPSvr_ClientConnect, ProcessTCPSvr_RecvData, ProcessTCPSvr_ReLoadReadyID, ProcessWT_PlayerValidateRet.
int TownServer::GetTcpUserNum(void)
References m_kAllTcpUser.
Referenced by ShowConsoleTitle, UpdateMSHeartPackage.
void TownServer::DisconnectTcpUser(SeTCPUser *pkUser, const char *pcFun, int iLine)
References SeTCPUser::dwClientID, SeTCPUser::dwPlayerID.
Referenced by DisconnectTcpUser.
void TownServer::DisconnectTcpUser(DWord dwClientID, DWord dwAccountID, const char *pcFun, int iLine)
References DisconnectTcpUser, SPrintf.
void TownServer::DisconnectTcpUser(DWord dwClientID, const char *acAccount, const char *pcFun, int iLine)
References GetLocalTime, m_bShowDisconnectLog, SeLogInfo, SendTCPSvr_SeverDisconnect, SPrintf.
void TownServer::OnSendShowNoticeWithoutString(const SeNoticeCode eCode, DWord dwParam1, DWord dwClientID)
References SendTC_ShowNotice, SSD_ENDSTR_LEN.
Referenced by SePlayerMgr::OnProcessCommMatchMsg, ProcessCT_CreateChar, ProcessMT_CancelMatchRet, ProcessMT_StartMatchRet.
void TownServer::OnProcessCommMatchMsg(DWord dwSession, SeCommMatchMsg eMsg, DWord dwParam, int iParam, DWord dwParam2)
References eSSRSTATE_END_RACE, g_kPlayerMgr, g_kTownServer, SePlayerMgr::GetPlayerByID, SePlayerMgr::OnProcessCommMatchMsg, SCMM_NOTIFY_LEAVE_RACE, SCMM_NOTIFY_LEAVE_RACE_WITHOUTREON, SCMM_RACE_OVER, SeLogDebug, SeLogInfo, SendTW_PlayerLeaveRace, SendTW_SavePlayerReconInfo.
Referenced by ProcessMT_CommMatchMsg.
bool TownServer::ProcessWTData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool TownServer::PreProcessWT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_RegisterRet(SeWT_RegisterRet *pkData, int iSize, void *pkSender)
References SeServerData::bRegistered, SeWT_RegisterRet::dwAreaID, SeServerData::dwID, SeTownConfig::dwServerID, SeWT_RegisterRet::eRet, g_kPlayerMgr, GetID2Str, m_kConfig, m_kWSData, SePlayerMgr::OnLoadPlayerInfoAgain, SeLogError, SeLogInfo, SetWSReady, SRR_REPEAT, SRR_SUCCESS.
void TownServer::ProcessWT_HeartPackageRet(SeWT_HeartPackageRet *pkData, int iSize, void *pkSender)
References SeServerData::dwHeartPackageTime, m_kWSData.
void TownServer::ProcessWT_ShowNotice(SeWT_ShowNotice *pkData, int iSize, void *pkSender)
References SeWT_ShowNotice::acMessage, SeTCPUser::dwClientID, SeWT_ShowNotice::dwParam, SeWT_ShowNotice::dwPlayerID, SeWT_ShowNotice::eNoticeCode, GetTcpUserByID, SeWT_ShowNotice::iSize, MemCpy, SDD_SHOW_NOTICE_LEN, SendTC_ShowNotice.
void TownServer::ProcessWT_IsReady(SeWT_IsReady *pkData, int iSize, void *pkSender)
References SeWT_IsReady::bReady, SetWSReady.
void TownServer::ProcessWT_LoadPlayerInfoAgainRet(SeWT_LoadPlayerInfoAgainRet *pkData, int iSize, void *pkSender)
References m_bWSLoadTSReady, m_dwReloadPlayerTime, SeLogInfo.
void TownServer::ProcessWT_PlayerValidateRet(SeWT_PlayerValidateRet *pkData, int iSize, void *pkSender)
References SeTCPUser::dwClientID, SeWT_PlayerValidateRet::dwClientID, SeTCPUser::dwPlayerID, SeWT_PlayerValidateRet::dwPlayerID, SeTCPUser::dwStateTime, SeTCPUser::eState, SeWT_PlayerValidateRet::eValidateType, GetTcpUser, m_dwCurTime, SCS_CREATE_CHAR, SCS_VALID_FAILED, SCS_VALID_OK, SCS_WAIT_WS, SeLogError, SeLogInfo, SendTC_PlayerValidateRet, SendTCPSvr_ConnectState, SVT_CHAR_NOT_EXIST, SVT_GAME_DB_ERROR, SVT_SESSION_ID_ERROR, SVT_VALIDATE_OK.
void TownServer::ProcessWT_QueryNameRet(SeWT_QueryNameRet *pkData, int iSize, void *pkSender)
References SeWT_QueryNameRet::bHasExist, SeTCPUser::dwClientID, SeWT_QueryNameRet::dwPlayerID, GetTcpUserByID, SendTC_QueryNameRet.
void TownServer::ProcessWT_CreateCharRet(SeWT_CreateCharRet *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, CCR_CREATE_CHAR_OK, SeTCPUser::dwClientID, SeWT_CreateCharRet::dwPlayerID, SeTCPUser::dwStateTime, SeTCPUser::eState, SeWT_CreateCharRet::eState, GetTcpUserByID, SeTCPUser::kNetAddr, m_dwCurTime, SCS_CREATE_CHAR, SCS_CREATEING_CHAR, SCS_VALID_OK, SeLogError, SendTC_CreateCharRet, SendTN_CreateUserSync.
void TownServer::ProcessWT_KickPlayer(SeWT_KickPlayer *pkData, int iSize, void *pkSender)
References DISCONNECT_USER, SeTCPUser::dwClientID, SeTCPUser::dwPlayerID, SeWT_KickPlayer::dwPlayerID, GetTcpUserByID, SeLogInfo, SendTC_KickPlayer.
void TownServer::ProcessWT_PlayerLeave(SeWT_PlayerLeave *pkData, int iSize, void *pkSender)
References SeTCPUser::dwClientID, SeWT_PlayerLeave::dwPlayerID, SeTCPUser::dwStateTime, SeTCPUser::eState, GetServerTime, GetTcpUserByID, SCS_VALID_FAILED, SendTC_PlayerLeaveRet, SSD_ENDSTR_LEN.
void TownServer::ProcessWT_InitPlayerInfo(SeWT_InitPlayerInfo *pkData, int iSize, void *pkSender)
References SeWT_InitPlayerInfo::acName, SeUserBaseAttrInfo::acUserNickName, SePlayerMgr::AddPlayer, SeWT_InitPlayerInfo::byEquipSetIndex, SeTCPUser::dwClientID, SeWT_InitPlayerInfo::dwExp, SeWT_InitPlayerInfo::dwLevel, SeWT_InitPlayerInfo::dwOnlineTime, SeWT_InitPlayerInfo::dwPlayerID, SeWT_InitPlayerInfo::dwServerTime, SeUserBaseAttrInfo::dwUserLevel, SeTCPUser::eDeviceOS, ENState_Online, SeTCPUser::eState, g_kPlayerMgr, SePlayerMgr::GetPlayerByID, GetTcpUserByID, SeWT_InitPlayerInfo::iDiamond, SeWT_InitPlayerInfo::iGold, SeWT_InitPlayerInfo::kLadder, m_dwCurTime, SCS_VALID_OK, SeLogInfo, SendTC_InitPlayerInfo, SendTN_NexusLinkUserSync, SendTN_UserAttrInfoSync, SePlayer::SetDeviceOS, SePlayer::SetName, StrCpy.
void TownServer::ProcessWT_ExchangeInit(SeWT_ExchangeInit *pkData, int iSize, void *pkSender)
References SeWT_ExchangeInit::akPtlExchange, SeWT_ExchangeInit::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_ExchangeInit::iNum, SendTC_ExchangeInit.
void TownServer::ProcessWT_ItemExchangeRet(SeWT_ItemExchangeRet *pkData, int iSize, void *pkSender)
References SeWT_ItemExchangeRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_ItemExchangeRet::iReturn, SeWT_ItemExchangeRet::iTypeID, SendTC_ItemExchangeRet.
void TownServer::ProcessWT_QueryPlayerReconInfo(SeWT_QueryPlayerReconInfo *pkData, int iSize, void *pkSender)
References SeServerData::dwID, SeWT_QueryPlayerReconInfo::dwPlayerID, SeWT_QueryPlayerReconInfo::dwRoomID, SeTownConfig::dwServerID, g_kPlayerMgr, SePlayer::GetID, SePlayerMgr::GetPlayerByID, SeWT_QueryPlayerReconInfo::iReconTime, SeWT_QueryPlayerReconInfo::iSeatIndex, m_kConfig, m_kWSData, SeLogInfo, SendTM_ReconQuery, SePlayer::SetFlag, SePlayer::SetReconTime, SPF_QueryRecon.
void TownServer::ProcessWT_UpdateMisc(SeWT_UpdateMisc *pkData, int iSize, void *pkSender)
References SeWT_UpdateMisc::dwPlayerID, SeWT_UpdateMisc::eType, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_UpdateMisc::iValue, SeWT_UpdateMisc::iValue2, SendTC_UpdateMisc, SePlayer::SetLeagueMMR, SePlayer::SetLeagueScore, SMT_LEAGUE_INFO.
void TownServer::ProcessWT_TaskQueryListRet(SeWT_TaskQueryListRet *pkData, int iSize, void *pkSender)
References SeWT_TaskQueryListRet::akList, SeWT_TaskQueryListRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_TaskQueryListRet::iNum, SendTC_TaskQueryListRet.
void TownServer::ProcessWT_TaskReselRet(SeWT_TaskReselRet *pkData, int iSize, void *pkSender)
References SeWT_TaskReselRet::dwPlayerID, SeWT_TaskReselRet::dwSrcTaskID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_TaskReselRet::kNewTask, SendTC_TaskReselRet.
void TownServer::ProcessWT_ItemDel(SeWT_ItemDel *pkData, int iSize, void *pkSender)
References SeWT_ItemDel::dwItemID, SeWT_ItemDel::dwPlayerID, SeWT_ItemDel::eType, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SendTC_ItemDel.
void TownServer::ProcessWT_ReceiveMail(SeWT_ReceiveMail *pkData, int iSize, void *pkSender)
References SeWT_ReceiveMail::akMail, SeWT_ReceiveMail::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_ReceiveMail::iNum, SendTC_ReceiveMail.
void TownServer::ProcessWT_UpdateMail(SeWT_UpdateMail *pkData, int iSize, void *pkSender)
References SeWT_UpdateMail::akInfo, SeWT_UpdateMail::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_UpdateMail::iNum, SendTC_UpdateMail.
void TownServer::ProcessWT_MailOprRet(SeWT_MailOprRet *pkData, int iSize, void *pkSender)
References SeWT_MailOprRet::dwMailID, SeWT_MailOprRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_MailOprRet::iRet, SeWT_MailOprRet::iType, SendTC_MailOprRet.
void TownServer::ProcessWT_PlayerRename(SeWT_PlayerRename *pkData, int iSize, void *pkSender)
References SeWT_PlayerRename::acName, SeWT_PlayerRename::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SendTC_PlayerRename, SePlayer::SetName.
void TownServer::ProcessWT_RaceBuyRet(SeWT_RaceBuyRet *pkData, int iSize, void *pkSender)
References SeWT_RaceBuyRet::bSuccess, SeWT_RaceBuyRet::dwParam1, SeWT_RaceBuyRet::dwParam2, SeWT_RaceBuyRet::dwPlayerID, SeWT_RaceBuyRet::dwSession, SeWT_RaceBuyRet::iType, SendTM_RaceBuyRet.
void TownServer::ProcessWT_QueryMapTaskListRet(SeWT_QueryMapTaskListRet *pkData, int iSize, void *pkSender)
References SeWT_QueryMapTaskListRet::akPtlMapTask, SeWT_QueryMapTaskListRet::dwMapID, SeWT_QueryMapTaskListRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_QueryMapTaskListRet::iNum, SendTC_QueryMapTaskListRet.
void TownServer::ProcessWT_QueryNearestRaceInfoRet(SeWT_QueryNearestRaceInfoRet *pkData, int iSize, void *pkSender)
References SeWT_QueryNearestRaceInfoRet::akRaceInfo, SeWT_QueryNearestRaceInfoRet::dwPlayerID, SeWT_QueryNearestRaceInfoRet::dwQueriedID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_QueryNearestRaceInfoRet::iNum, SendTC_QueryNearestRaceInfoRet.
void TownServer::ProcessWT_GetRaceHistoryRet(SeWT_GetRaceHistoryRet *pkData, int iSize, void *pkSender)
References SeTownConfig::acRaceRecordURLBase, SeWT_GetRaceHistoryRet::akInfo, SeWT_GetRaceHistoryRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_GetRaceHistoryRet::iMaxPage, SeWT_GetRaceHistoryRet::iNum, SeWT_GetRaceHistoryRet::iPage, SeWT_GetRaceHistoryRet::iType, m_kConfig, SendTC_GetRaceHistoryRet.
void TownServer::ProcessWT_PlayerNewItem(SeWT_PlayerNewItem *pkData, int iSize, void *pkSender)
References SeWT_PlayerNewItem::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_PlayerNewItem::iNum, SeWT_PlayerNewItem::SeItemArray, SendTC_PlayerNewItem.
void TownServer::ProcessWT_PlayerOperRep(SeWT_PlayerOperRep *pkData, int iSize, void *pkSender)
References SeWT_PlayerOperRep::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_PlayerOperRep::iResult, SendTC_PlayerOperRep.
void TownServer::ProcessWT_PlayerMoneyAndDiamond(SeWT_PlayerMoneyAndDiamond *pkData, int iSize, void *pkSender)
References SeWT_PlayerMoneyAndDiamond::dwDiamond, SeWT_PlayerMoneyAndDiamond::dwGold, SeWT_PlayerMoneyAndDiamond::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SendTC_PlayerMoneyAndDiamond.
void TownServer::ProcessWT_ShopItemGmRep(SeWT_ShopItemGmRep *pkData, int iSize, void *pkSender)
References SeWT_ShopItemGmRep::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_ShopItemGmRep::GmItem, SeWT_ShopItemGmRep::iResult, SendTC_ShopItemGmRep.
void TownServer::ProcessWT_SearchUserArchivesInfoRes(SeWT_SearchUserArchivesInfoRes *pkData, int iSize, void *pkSender)
References SeWT_SearchUserArchivesInfoRes::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SendTC_SearchUserArchivesInfoRes, SeWT_SearchUserArchivesInfoRes::user_archives_info.
void TownServer::ProcessWT_SearchUserArchivesDetailInfoRes(SeWT_SearchUserArchivesDetailInfoRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_PlayerLadder(SeWT_PlayerLadder *pkData, int iSize, void *pkSender)
References SeWT_PlayerLadder::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_PlayerLadder::kLadder, SendTC_PlayerLadder.
void TownServer::ProcessWT_EquipSchema(SeWT_EquipSchema *pkData, int iSize, void *pkSender)
References SeWT_EquipSchema::akEquips, SeWT_EquipSchema::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_EquipSchema::iNum, SendTC_EquipSchema.
void TownServer::ProcessWT_RoomInviteNotify(SeWT_RoomInviteNotify *pkData, int iSize, void *pkSender)
References SeWT_RoomInviteNotify::acName, SeWT_RoomInviteNotify::dwInviteeID, SeWT_RoomInviteNotify::dwPlayerID, SeWT_RoomInviteNotify::dwRoomID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SendTC_RoomInviteNotify.
void TownServer::ProcessWT_FriendLadderInfoNtf(SeWT_FriendLadderInfoNtf *pkData, int iSize, void *pkSender)
References SeWT_FriendLadderInfoNtf::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_FriendLadderInfoNtf::iNum, SeWT_FriendLadderInfoNtf::RankList, SendTC_FriendLadderInfoNtf.
void TownServer::ProcessWT_ActiveAvatarNtf(SeWT_ActiveAvatarNtf *pkData, int iSize, void *pkSender)
References SeWT_ActiveAvatarNtf::avartars, SeWT_ActiveAvatarNtf::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_ActiveAvatarNtf::iNum, SendTC_ActiveAvatarNtf.
void TownServer::ProcessWT_UserHeroSync(SeWT_UserHeroSync *pkData, int iSize, void *pkSender)
References SeWT_UserHeroSync::akHeroSyncInfo, SeWT_UserHeroSync::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWT_UserHeroSync::num, SeLogDebug, SendTC_UserHeroSync.
bool TownServer::ProcessCTData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by ProcessTCPSvr_RecvData.
bool TownServer::PreProcessCT(void *pkData, int iSize, void *pkSender)
References CMD_CT_HEARTBEAT, getCTCmdNameMap, SeLogDebug, SeCMD::wCmd.
void TownServer::ProcessCT_PlayerValidate(SeCT_PlayerValidate *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, DISCONNECT_USER, SeTCPUser::dwClientID, SeMobileInfo::dwDeviceOS, SeCT_PlayerValidate::dwMaxMailID, SeCT_PlayerValidate::dwMSangoMagic, SeTCPUser::dwPlayerID, SeCT_PlayerValidate::dwPlayerID, SeCT_PlayerValidate::dwSessionId, SeTCPUser::dwStateTime, SeCT_PlayerValidate::dwVersion, SeTCPUser::eDeviceOS, SeTCPUser::eState, GetIPString2DWord, GetTcpUserByID, SeCT_PlayerValidate::kMobileInfo, SeTCPUser::kNetAddr, m_dwCurTime, SCS_UNKOWN, SCS_WAIT_WS, SeLogError, SeLogInfo, SendTW_PlayerValidate, SSD_MSANGO_MAGIC.
void TownServer::ProcessCT_QueryName(SeCT_QueryName *pkData, int iSize, void *pkSender)
References SeCT_QueryName::acName, SeTCPUser::dwPlayerID, MemCpy, SeLogInfo, SendTW_QueryName, SSD_MAX_CHAR_NAME, SSD_MIN_CHAR_NAME.
void TownServer::ProcessCT_CreateChar(SeCT_CreateChar *pkData, int iSize, void *pkSender)
References SeCT_CreateChar::acName, SeCT_CreateChar::dwCardID, SeTCPUser::dwClientID, SeTCPUser::dwPlayerID, SeTCPUser::dwStateTime, SeTCPUser::eState, SeCT_CreateChar::iSex, m_dwCurTime, MemCpy, OnSendShowNoticeWithoutString, SCS_CREATE_CHAR, SCS_CREATEING_CHAR, SeLogInfo, SendTW_CreateChar, SNC_CHAR_NAME_INVALID, SSD_MAX_CHAR_NAME, SSD_MIN_CHAR_NAME.
void TownServer::ProcessCT_LeaveTown(SeCT_LeaveTown *pkData, int iSize, void *pkSender)
References DISCONNECT_USER, SeTCPUser::dwPlayerID, SeLogInfo.
void TownServer::ProcessCT_PlayerGoDirect(SeCT_PlayerGoDirect *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RaceEndGuanka(SeCT_RaceEndGuanka *pkData, int iSize, void *pkSender)
References SeCT_RaceEndGuanka::akPlayerInfo, SeCT_RaceEndGuanka::bValid, DISCONNECT_USER, SeTCPUser::dwPlayerID, SeCT_RaceEndGuanka::dwRaceTime, g_kPlayerMgr, g_kRaceMgr, SePlayerMgr::GetPlayerByID, SeCT_RaceEndGuanka::iMapID, SeCT_RaceEndGuanka::iNums, SeCT_RaceEndGuanka::iType, SeRaceMgr::OnPlayerGuankaEnd, SeLogError, SeLogInfo, SSD_MAX_ROOM_PLAYER.
void TownServer::ProcessCT_ViewBegin(SeCT_ViewBegin *pkData, int iSize, void *pkSender)
References SeCT_ViewBegin::dwDstPlayerID, SeServerData::dwID, SeTCPUser::dwPlayerID, SeCT_ViewBegin::dwRoomSession, SeTownConfig::dwServerID, g_kPlayerMgr, SePlayer::GetID, SePlayerMgr::GetPlayerByID, m_kConfig, m_kWSData, SeLogInfo, SendTM_ViewQuery.
void TownServer::ProcessCT_QueryRaceRoomList(SeCT_QueryRaceRoomList *pkData, int iSize, void *pkSender)
References SeCT_QueryRaceRoomList::dwMapID, SeTCPUser::dwPlayerID, SeCT_QueryRaceRoomList::dwRoomSession, g_kPlayerMgr, SePlayer::GetID, SePlayerMgr::GetPlayerByID, SeCT_QueryRaceRoomList::iPage, SeLogInfo, SendTM_QueryRaceRoomList.
void TownServer::ProcessCT_ItemExchange(SeCT_ItemExchange *pkData, int iSize, void *pkSender)
References SeTCPUser::dwPlayerID, g_kPlayerMgr, SePlayer::GetID, SePlayerMgr::GetPlayerByID, SeCT_ItemExchange::iTypeID, SeLogInfo, SendTW_ItemExchange.
void TownServer::ProcessCT_ReconQuery(SeCT_ReconQuery *pkData, int iSize, void *pkSender)
References SeCT_ReconQuery::dwFrame, SeServerData::dwID, SeTCPUser::dwPlayerID, SeCT_ReconQuery::dwRoomID, SeTownConfig::dwServerID, g_kPlayerMgr, SePlayer::GetID, SePlayer::GetName, SePlayerMgr::GetPlayerByID, SeCT_ReconQuery::iOffset, SeCT_ReconQuery::iSeat, m_kConfig, m_kWSData, SeLogInfo, SendTM_ReconPLayerName, SendTM_ReconQuery.
void TownServer::ProcessCT_DelayCheck(SeCT_DelayCheck *pkData, int iSize, void *pkSender)
References SeTCPUser::dwClientID, SeTCPUser::dwPlayerID, SeLogInfo, SendTC_DelayCheckRet.
void TownServer::ProcessCT_TaskQueryList(SeCT_TaskQueryList *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_TaskQueryList.
void TownServer::ProcessCT_TaskResel(SeCT_TaskResel *pkData, int iSize, void *pkSender)
References SeCT_TaskResel::dwTaskID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_TaskResel.
void TownServer::ProcessCT_GetTaskReward(SeCT_GetTaskReward *pkData, int iSize, void *pkSender)
References SeCT_GetTaskReward::dwTaskID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_GetTaskReward.
void TownServer::ProcessCT_QueryRaceBetInfo(SeCT_QueryRaceBetInfo *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTM_QueryRaceBetInfo.
void TownServer::ProcessCT_DelReconInfo(SeCT_DelReconInfo *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_DelReconInfo.
void TownServer::ProcessCT_MailOpr(SeCT_MailOpr *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_PlayerRename(SeCT_PlayerRename *pkData, int iSize, void *pkSender)
References SeCT_PlayerRename::acName, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_PlayerRename.
void TownServer::ProcessCT_HeartBeat(SeCT_HeartBeat *pkData, int iSize, void *pkSender)
References SeTCPUser::dwClientID, SendTC_HeartBeat.
void TownServer::ProcessCT_MapTaskOpr(SeCT_MapTaskOpr *pkData, int iSize, void *pkSender)
References SeCT_MapTaskOpr::dwParam, GET_CUR_CONN_AND_PLAYER, SeCT_MapTaskOpr::iOprType, SeLogInfo, SendTW_MapTaskOpr.
void TownServer::ProcessCT_QueryNearestRaceInfo(SeCT_QueryNearestRaceInfo *pkData, int iSize, void *pkSender)
References SeCT_QueryNearestRaceInfo::dwMapID, SeCT_QueryNearestRaceInfo::dwQueriedID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_QueryNearestRaceInfo.
void TownServer::ProcessCT_ReqIncompleteRaceList(SeCT_ReqIncompleteRaceList *pkData, int iSize, void *pkSender)
References SeTCPUser::dwPlayerID, g_kPlayerMgr, SePlayerMgr::GetPlayerByID, SeLogDebug, SendTM_ReqIncompleteRaceList.
void TownServer::ProcessCT_CloseIncompleteRaceList(SeCT_CloseIncompleteRaceList *pkData, int iSize, void *pkSender)
References SeTCPUser::dwPlayerID, g_kPlayerMgr, SePlayer::GetID, SePlayerMgr::GetPlayerByID, SePlayerMgr::OnProcessCloseIncmpRaceList, SeLogDebug.
void TownServer::ProcessCT_ReqIncompleteRaceKDA(SeCT_ReqIncompleteRaceKDA *pkData, int iSize, void *pkSender)
References SeTCPUser::dwPlayerID, SeCT_ReqIncompleteRaceKDA::dwRoomSession, g_kPlayerMgr, SePlayerMgr::GetPlayerByID, SeLogDebug, SendTM_ReqIncompleteRaceKDA.
void TownServer::ProcessCT_CreateRoom(SeCT_CreateRoom *pkData, int iSize, void *pkSender)
References SeCT_CreateRoom::bPlayBoss, SeCT_CreateRoom::bUseRobot, SeCT_CreateRoom::dwCamp, SeCT_CreateRoom::dwGameMode, SeCT_CreateRoom::dwMapID, GET_CUR_CONN_AND_PLAYER, SeCT_CreateRoom::iDifficulty, SeLogInfo, SendTM_MatchCreateRoom, SeCT_CreateRoom::strPass, SeCT_CreateRoom::strRoomName.
void TownServer::ProcessCT_QueryRoomList(SeCT_QueryRoomList *pkData, int iSize, void *pkSender)
References SeCT_QueryRoomList::dwMapID, GET_CUR_CONN_AND_PLAYER, SeCT_QueryRoomList::iCurPage, SeLogInfo, SendTM_MatchQueryRoomList.
void TownServer::ProcessCT_RoomJoin(SeCT_RoomJoin *pkData, int iSize, void *pkSender)
References SeCT_RoomJoin::dwCamp, SeCT_RoomJoin::dwDstRoom, GET_CUR_CONN_AND_PLAYER, SeCT_RoomJoin::iseat, SeLogInfo, SendTM_MatchRoomJoin, SeCT_RoomJoin::strPass.
void TownServer::ProcessCT_RoomLeave(SeCT_RoomLeave *pkData, int iSize, void *pkSender)
References SeCT_RoomLeave::dwDstRoom, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTM_MatchRoomLeave.
void TownServer::ProcessCT_RoomSwitchSeat(SeCT_RoomSwitchSeat *pkData, int iSize, void *pkSender)
References SeCT_RoomSwitchSeat::dwCamp, SeCT_RoomSwitchSeat::dwDstRoom, GET_CUR_CONN_AND_PLAYER, SeCT_RoomSwitchSeat::iseat, SeLogInfo, SendTM_MatchRoomSwitchSeat.
void TownServer::ProcessCT_RoomStart(SeCT_RoomStart *pkData, int iSize, void *pkSender)
References SeCT_RoomStart::dwRoomID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTM_MatchRoomReady.
void TownServer::ProcessCT_RoomKickSomeone(SeCT_RoomKickSomeone *pkData, int iSize, void *pkSender)
References SeCT_RoomKickSomeone::dwKickedPlayerID, SeCT_RoomKickSomeone::dwRoomID, GET_CUR_CONN_AND_PLAYER, SeCT_RoomKickSomeone::iseat, SeLogInfo, SendTM_MatchRoomKickSomeone.
void TownServer::ProcessCT_RoomInvite(SeCT_RoomInvite *pkData, int iSize, void *pkSender)
References SeCT_RoomInvite::dwInviteeID, SeCT_RoomInvite::dwRoomID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTN_RoomInviteNotifyVerify.
void TownServer::ProcessCT_RoomInviteRsp(SeCT_RoomInviteRsp *pkData, int iSize, void *pkSender)
References SeCT_RoomInviteRsp::dwInvitorID, SeCT_RoomInviteRsp::dwRoomID, GET_CUR_CONN_AND_PLAYER, SeCT_RoomInviteRsp::option, SeLogInfo, SendTM_MatchRoomInviteRsp.
void TownServer::ProcessCT_GetRaceHistory(SeCT_GetRaceHistory *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqAchievement(SeCT_ReqAchievement *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqView(SeCT_ReqView *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_ReqView::rID, SeLogInfo, SendTWCMS_ReqView.
void TownServer::ProcessCT_ReqAchievementCounts(SeCT_ReqAchievementCounts *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqViewList(SeCT_ReqViewList *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_ReqViewList::iPage, SeLogInfo, SendTWCMS_ReqViewList.
void TownServer::ProcessCT_ReqItemStrenth(SeCT_ReqItemStrenth *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_ReqItemStrenth::iNum, SeLogInfo, SendTBL_ReqItemStrenth, SeCT_ReqItemStrenth::SrcPosArray, SeCT_ReqItemStrenth::wPos.
void TownServer::ProcessCT_RaceDetailInfoReq(SeCT_RaceDetailInfoReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_RaceDetailInfoReq::page_counts, SeCT_RaceDetailInfoReq::page_number, SeLogInfo, SendTWCMS_RaceDetailInfoReq.
void TownServer::ProcessCT_ReqItemCiTiaoChange(SeCT_ReqItemCiTiaoChange *pkData, int iSize, void *pkSender)
References SeCT_ReqItemCiTiaoChange::BolLock, GET_CUR_CONN_AND_PLAYER, SeCT_ReqItemCiTiaoChange::iIndex, SeCT_ReqItemCiTiaoChange::iNum, SeLogInfo, SendTBL_ReqItemCiTiaoChange, SeCT_ReqItemCiTiaoChange::SrcPosArray, SeCT_ReqItemCiTiaoChange::wPos.
void TownServer::ProcessCT_ReqItemDepart(SeCT_ReqItemDepart *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTBL_ReqItemDepart, SeCT_ReqItemDepart::wPos.
void TownServer::ProcessCT_GMAddItem(SeCT_GMAddItem *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_GMAddItem::ItemID, SeCT_GMAddItem::Level, SeCT_GMAddItem::Num, SeLogInfo, SendTBL_GMAddItem.
void TownServer::ProcessCT_DelelteItem(SeCT_DelelteItem *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTBL_DelelteItem, SeCT_DelelteItem::wPos.
void TownServer::ProcessCT_PutOnEquip(SeCT_PutOnEquip *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_PutOnEquip::PutPos, SeLogInfo, SendTBL_PutOnEquip, SeCT_PutOnEquip::wPos.
void TownServer::ProcessCT_TakeOffEquip(SeCT_TakeOffEquip *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTBL_TakeOffEquip, SeCT_TakeOffEquip::wPos.
void TownServer::ProcessCT_OpenRandBox(SeCT_OpenRandBox *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SendTBL_OpenRandBox, SeCT_OpenRandBox::wPos.
void TownServer::ProcessCT_ClearItemNewFlag(SeCT_ClearItemNewFlag *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_ClearItemNewFlag::iNum, SeCT_ClearItemNewFlag::PosArray, SendTBL_ClearItemNewFlag.
void TownServer::ProcessCT_BuyShopItem(SeCT_BuyShopItem *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_BuyShopItem::Num, SeLogInfo, SendTW_BuyShopItem, SeCT_BuyShopItem::ShopID, SeCT_BuyShopItem::types.
void TownServer::ProcessCT_ShopItemGM(SeCT_ShopItemGM *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_ShopItemGM::GmItems, SeCT_ShopItemGM::iNum, SeLogInfo, SendTW_ShopItemGM.
void TownServer::ProcessCT_GetItemGM(SeCT_GetItemGM *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_GetItemGM, SeCT_GetItemGM::ShopID.
void TownServer::ProcessCT_NexusFriendDetailInfoReq(SeCT_NexusFriendDetailInfoReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_NexusFriendDetailInfoReq::page_counts, SeCT_NexusFriendDetailInfoReq::page_number, SeLogInfo, SendTN_NexusFriendDetailInfoReq.
void TownServer::ProcessCT_NexusUserActionReq(SeCT_NexusUserActionReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_NexusUserActionReq::nexus_user_actions, SeLogInfo, SendTN_NexusUserActionReq.
void TownServer::ProcessCT_NexusUserPromotionReq(SeCT_NexusUserPromotionReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER.
void TownServer::ProcessCT_SearchUserArchivesInfoReq(SeCT_SearchUserArchivesInfoReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_SearchUserArchivesInfoReq, SeCT_SearchUserArchivesInfoReq::username.
void TownServer::ProcessCT_SearchUserArchivesDetailInfoReq(SeCT_SearchUserArchivesDetailInfoReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTW_SearchUserArchivesDetailInfoReq, SeCT_SearchUserArchivesDetailInfoReq::userid.
void TownServer::ProcessCT_NexusUserPromotionDetailInfoReq(SeCT_NexusUserPromotionDetailInfoReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER.
void TownServer::ProcessCT_PlayerMatchReq(SeCT_PlayerMatchReq *pkData, int iSize, void *pkSender)
References SeCT_PlayerMatchReq::bySeats, GET_CUR_CONN_AND_PLAYER, SeCT_PlayerMatchReq::MapID, ReqResultWrongStatus, SendTC_ReqMatchRep, SendTN_MatchTeamMemberReq.
void TownServer::ProcessCT_PlayerMatchCancel(SeCT_PlayerMatchCancel *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTM_PlayerMatchCancel.
void TownServer::ProcessCT_MatchConfirm(SeCT_MatchConfirm *pkData, int iSize, void *pkSender)
References SeCT_MatchConfirm::BoolConfirm, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTM_MatchConfirm, SeCT_MatchConfirm::WaitID.
void TownServer::ProcessCT_SeUserRaceArenaDetailInfoReq(SeCT_SeUserRaceArenaDetailInfoReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTBL_UserRaceMapDetailReq.
void TownServer::ProcessCT_UserInviteReq(SeCT_UserInviteReq *pkData, int iSize, void *pkSender)
References SeCT_UserInviteReq::acGuestName, SeCT_UserInviteReq::acUserName, SeCT_UserInviteReq::dwGuestID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTN_UserInviteReq.
void TownServer::ProcessCT_UserConfirmInviteReq(SeCT_UserConfirmInviteReq *pkData, int iSize, void *pkSender)
References SeCT_UserConfirmInviteReq::dwTeamID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTN_UserConfirmInviteReq.
void TownServer::ProcessCT_UserRefuseInviteReq(SeCT_UserRefuseInviteReq *pkData, int iSize, void *pkSender)
References SeCT_UserRefuseInviteReq::dwTeamID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTN_UserRefuseInviteReq.
void TownServer::ProcessCT_UserLeaveTeamReq(SeCT_UserLeaveTeamReq *pkData, int iSize, void *pkSender)
References SeCT_UserLeaveTeamReq::dwTeamID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTN_UserLeaveTeamReq.
void TownServer::ProcessCT_LeaderKickMemberReq(SeCT_LeaderKickMemberReq *pkData, int iSize, void *pkSender)
References SeCT_LeaderKickMemberReq::dwMemberID, SeCT_LeaderKickMemberReq::dwTeamID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTN_LeaderKickMemberReq.
void TownServer::ProcessCT_LeaderDismissTeamReq(SeCT_LeaderDismissTeamReq *pkData, int iSize, void *pkSender)
References SeCT_LeaderDismissTeamReq::dwTeamID, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTN_LeaderDismissTeamReq.
void TownServer::ProcessCT_GMSetGold(SeCT_GMSetGold *pkData, int iSize, void *pkSender)
References SeCT_GMSetGold::dwGold, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTBL_GMSetGold.
void TownServer::ProcessCT_GMSetDiamond(SeCT_GMSetDiamond *pkData, int iSize, void *pkSender)
References SeCT_GMSetDiamond::dwDiamond, GET_CUR_CONN_AND_PLAYER, SeLogInfo, SendTBL_GMSetDiamond.
void TownServer::ProcessCT_NexusFriendCleanRefuseNoticeReq(SeCT_NexusFriendCleanRefuseNoticeReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_NexusFriendCleanRefuseNoticeReq::guest_id, SeLogInfo, SendTN_NexusFriendCleanRefuseNoticeReq.
void TownServer::ProcessCT_UserStatusQueryReq(SeCT_UserStatusQueryReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SeCT_UserStatusQueryReq::num, SeLogInfo, SendTN_UserStatusQueryReq, SeCT_UserStatusQueryReq::user_ids.
void TownServer::ProcessCT_LadderRankQueryReq(SeCT_LadderRankQueryReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SendTBL_LadderRankQueryReq.
void TownServer::ProcessCT_FriendLadderInfoReq(SeCT_FriendLadderInfoReq *pkData, int iSize, void *pkSender)
References SeCT_FriendLadderInfoReq::dwFriendID, GET_CUR_CONN_AND_PLAYER, SendTBL_FriendLadderInfoReq.
void TownServer::ProcessCT_UserMapRaceHeroReq(SeCT_UserMapRaceHeroReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SendTBL_UserMapRaceHeroReq.
void TownServer::ProcessCT_SetActiveAvatarReq(SeCT_SetActiveAvatarReq *pkData, int iSize, void *pkSender)
References SeCT_SetActiveAvatarReq::bActive, SeCT_SetActiveAvatarReq::dwItemID, GET_CUR_CONN_AND_PLAYER, SendTBL_SetActiveAvatarReq.
void TownServer::ProcessCT_UserAlterNickNameReq(SeCT_UserAlterNickNameReq *pkData, int iSize, void *pkSender)
References SeCT_UserAlterNickNameReq::acNickName, GET_CUR_CONN_AND_PLAYER, SendTBL_UserAlterNickNameReq.
void TownServer::ProcessCT_UserAlterAvatarReq(SeCT_UserAlterAvatarReq *pkData, int iSize, void *pkSender)
References SeCT_UserAlterAvatarReq::dwAvatarID, GET_CUR_CONN_AND_PLAYER, SendTBL_UserAlterAvatarReq.
void TownServer::ProcessCT_UserAlterAvatarFrameReq(SeCT_UserAlterAvatarFrameReq *pkData, int iSize, void *pkSender)
References SeCT_UserAlterAvatarFrameReq::dwAvatarFrameID, GET_CUR_CONN_AND_PLAYER, SendTBL_UserAlterAvatarFrameReq.
void TownServer::ProcessCT_UserPurchaseAvatarReq(SeCT_UserPurchaseAvatarReq *pkData, int iSize, void *pkSender)
References SeCT_UserPurchaseAvatarReq::dwAvatarID, GET_CUR_CONN_AND_PLAYER, SendTBL_UserPurchaseAvatarReq.
void TownServer::ProcessCT_LadderDetailInfoReq(SeCT_LadderDetailInfoReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SendTBL_LadderDetailInfoReq.
void TownServer::ProcessCT_AchieveInfoReq(SeCT_AchieveInfoReq *pkData, int iSize, void *pkSender)
References GET_CUR_CONN_AND_PLAYER, SendTBL_AchieveInfoReq.
bool TownServer::ProcessMTData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool TownServer::PreProcessMT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_RegisterRet(SeMT_RegisterRet *pkData, int iSize, void *pkSender)
References SeServerData::bRegistered, SeMT_RegisterRet::eRet, g_kPlayerMgr, m_kMSData, SePlayerMgr::OnClearMatchServerData, SeLogError, SeLogInfo, SRR_SUCCESS.
void TownServer::ProcessMT_HeartPackageRet(SeMT_HeartPackageRet *pkData, int iSize, void *pkSender)
References SeServerData::dwHeartPackageTime, m_kMSData.
void TownServer::ProcessMT_StartMatchRet(SeMT_StartMatchRet *pkData, int iSize, void *pkSender)
References SeMT_StartMatchRet::dwMapID, SeMT_StartMatchRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_StartMatchRet::iResult, OnSendShowNoticeWithoutString, SeLogError, SeLogInfo, SendTC_StartMatchRet, SNC_START_MATCH_RET.
void TownServer::ProcessMT_CancelMatchRet(SeMT_CancelMatchRet *pkData, int iSize, void *pkSender)
References SeMT_CancelMatchRet::bRet, SeMT_CancelMatchRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, OnSendShowNoticeWithoutString, SeLogError, SeLogInfo, SNC_CANCEL_MATCH_RET.
void TownServer::ProcessMT_MatchSessionNotify(SeMT_MatchSessionNotify *pkData, int iSize, void *pkSender)
References SeMT_MatchSessionNotify::dwMatchSession, SeMT_MatchSessionNotify::dwPlayerID, g_kPlayerMgr, SePlayerMgr::GetPlayerByID, SCMM_REPORT_LOAD_FAILED, SeLogError, SendTM_CommMatchMsg, SePlayer::SetMatchSession.
void TownServer::ProcessMT_CommMatchMsg(SeMT_CommMatchMsg *pkData, int iSize, void *pkSender)
References SeMT_CommMatchMsg::dwMatchSession, SeMT_CommMatchMsg::dwParam, SeMT_CommMatchMsg::dwParam2, SeMT_CommMatchMsg::eMsg, SeMT_CommMatchMsg::iParam, OnProcessCommMatchMsg, SeLogInfo.
void TownServer::ProcessMT_NotifyAddrToMatch(SeMT_NotifyAddrToMatch *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SePtlNetAddr::acIP, SeMT_NotifyAddrToMatch::akPlayerInfo, SePlayer::ClearFlag, SeMT_NotifyAddrToMatch::dwEnterKey, SeMT_NotifyAddrToMatch::dwMatchSession, SeMT_NotifyAddrToMatch::dwPlayerID, SeMT_NotifyAddrToMatch::eValidType, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SePlayer::GetPlayerState, SePlayer::GetReconTime, SePlayer::HasFlag, SeMT_NotifyAddrToMatch::iNum, SeNetAddr::iPort, SePtlNetAddr::iPort, SeMT_NotifyAddrToMatch::iSeat, SeMT_NotifyAddrToMatch::kAddrToMatch, SeMT_NotifyAddrToMatch::kAddrToMatchUdp, SCMM_REPORT_LOAD_FAILED, SeLogError, SeLogInfo, SendTC_InGameDisconn, SendTC_MatchRaceAddr, SendTM_CommMatchMsg, SPF_QueryRecon, SPS_IN_TOWN, SRVT_RECON.
void TownServer::ProcessMT_UpdateMisc(SeMT_UpdateMisc *pkData, int iSize, void *pkSender)
References SeMT_UpdateMisc::dwParam1, SeMT_UpdateMisc::dwParam2, SeMT_UpdateMisc::dwPlayerID, SeMT_UpdateMisc::eType, g_kPlayerMgr, SePlayerMgr::GetPlayerByID, SeMT_UpdateMisc::iValue, MM_GAME_STATE, SeLogInfo.
void TownServer::ProcessMT_RaceEndSend(SeMT_RaceEndSend *pkData, int iSize, void *pkSender)
References SeMT_RaceEndSend::akInfo, SeMT_RaceEndSend::dwMapID, SeMT_RaceEndSend::dwRoomSession, SeMT_RaceEndSend::dwTime, SeMT_RaceEndSend::eMatchType, g_kTownServer, GetID2Str, SeMT_RaceEndSend::iNum, SeLogInfo, SendTW_RaceEndRace.
void TownServer::ProcessMT_GuanqiaEndSend(SeMT_GuanqiaEndSend *pkData, int iSize, void *pkSender)
References SeMT_GuanqiaEndSend::akInfo, SeMT_GuanqiaEndSend::dwMapID, SeMT_GuanqiaEndSend::dwRoomSession, SeMT_GuanqiaEndSend::dwTime, g_kTownServer, GetID2Str, SeMT_GuanqiaEndSend::iNum, SeLogError, SendTW_RaceEndGuanka.
void TownServer::ProcessMT_ReconQueryFail(SeMT_ReconQueryFail *pkData, int iSize, void *pkSender)
References SePlayer::ClearFlag, SeMT_ReconQueryFail::dwPlayerID, SeMT_ReconQueryFail::eReason, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SePlayer::HasFlag, SendTC_ShowNotice, SNC_RECON_FAILED, SPF_QueryRecon.
void TownServer::ProcessMT_ViewQueryFail(SeMT_ViewQueryFail *pkData, int iSize, void *pkSender)
References SeTCPUser::dwClientID, SeMT_ViewQueryFail::dwPlayerID, SeMT_ViewQueryFail::eReason, GetTcpUserByID, SendTC_ViewResult, SVQF_COMMON, SVQF_EXIST, SVQF_MAX_VIEW, SVQF_NOT_RACING, SVQF_WAIT, SVRT_PLAYER_EXSIST, SVRT_RACE_ERROR, SVRT_REACH_MAX, SVRT_WAIT.
void TownServer::ProcessMT_QueryRaceRoomListRet(SeMT_QueryRaceRoomListRet *pkData, int iSize, void *pkSender)
References SeMT_QueryRaceRoomListRet::akRoomInfo, SeTCPUser::dwClientID, SeMT_QueryRaceRoomListRet::dwPlayerID, GetTcpUserByID, SeMT_QueryRaceRoomListRet::iCurPage, SeMT_QueryRaceRoomListRet::iMaxPage, SeMT_QueryRaceRoomListRet::iRoomNums, SeLogInfo, SendTC_QueryRaceRoomListRet.
void TownServer::ProcessMT_BiVoiceEnterInfo(SeMT_BiVoiceEnterInfo *pkData, int iSize, void *pkSender)
References SeMT_BiVoiceEnterInfo::acLoginSession, SeMT_BiVoiceEnterInfo::acRoomSession, SeMT_BiVoiceEnterInfo::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_BiVoiceEnterInfo::roomid, SeLogInfo, SendTC_BiVoiceEnterInfo.
void TownServer::ProcessMT_AskEnterWaitRace(SeMT_AskEnterWaitRace *pkData, int iSize, void *pkSender)
References SeMT_AskEnterWaitRace::akPlayerList, SeMT_AskEnterWaitRace::dwMapID, SeMT_AskEnterWaitRace::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_AskEnterWaitRace::iNum, SeLogInfo, SendTC_AskEnterWaitRace.
void TownServer::ProcessMT_GetRaceCardInfo(SeMT_GetRaceCardInfo *pkData, int iSize, void *pkSender)
References SeMT_GetRaceCardInfo::dwPlayerID, g_kPlayerMgr, SePlayerMgr::GetPlayerByID.
void TownServer::ProcessMT_MatchRaceLoad(SeMT_MatchRaceLoad *pkData, int iSize, void *pkSender)
References SeMT_MatchRaceLoad::dwMapID, SeMT_MatchRaceLoad::dwPlayerID, SeMT_MatchRaceLoad::dwRoomSession, SeLogInfo, SendTW_MatchRaceLoad.
void TownServer::ProcessMT_QueryRaceBetInfoRet(SeMT_QueryRaceBetInfoRet *pkData, int iSize, void *pkSender)
References SeMT_QueryRaceBetInfoRet::dwConstellIDA, SeMT_QueryRaceBetInfoRet::dwConstellIDB, SeMT_QueryRaceBetInfoRet::dwPlayerID, SeMT_QueryRaceBetInfoRet::fOddsA, SeMT_QueryRaceBetInfoRet::fOddsB, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogInfo, SendTC_QueryRaceBetInfoRet.
void TownServer::ProcessMT_RaceBuy(SeMT_RaceBuy *pkData, int iSize, void *pkSender)
References SeMT_RaceBuy::dwParam1, SeMT_RaceBuy::dwParam2, SeMT_RaceBuy::dwPlayerID, SeMT_RaceBuy::dwSession, SeMT_RaceBuy::iType, SeLogInfo, SendTW_RaceBuy.
void TownServer::ProcessMT_MatchCreateRoomRet(SeMT_MatchCreateRoomRet *pkData, int iSize, void *pkSender)
References SeRoomMember::acName, SeMT_MatchCreateRoomRet::akInfo, SeOpenRoomInfo::akMember, SeRoomMember::bySeat, SeMT_MatchCreateRoomRet::dwPlayerID, SeMT_MatchCreateRoomRet::eType, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_MatchCreateRoomRet::iNum, SeOpenRoomInfo::iNum, SeLogInfo, SendTC_CreateRoomRet.
void TownServer::ProcessMT_MatchQueryRoomListRet(SeMT_MatchQueryRoomListRet *pkData, int iSize, void *pkSender)
References SeMT_MatchQueryRoomListRet::akInfo, SeMT_MatchQueryRoomListRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_MatchQueryRoomListRet::iNum, SeLogInfo, SendTC_QueryRoomListRet.
void TownServer::ProcessMT_MatchRoomJoinRet(SeMT_MatchRoomJoinRet *pkData, int iSize, void *pkSender)
References SeRoomMember::acName, SeMT_MatchRoomJoinRet::akInfo, SeOpenRoomInfo::akMember, SeRoomMember::bySeat, SeMT_MatchRoomJoinRet::dwPlayerID, SeMT_MatchRoomJoinRet::eType, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_MatchRoomJoinRet::iNum, SeOpenRoomInfo::iNum, SeLogInfo, SendTC_RoomJoinRet.
void TownServer::ProcessMT_MatchRoomMemberNotifyRet(SeMT_MatchRoomMemberNotifyRet *pkData, int iSize, void *pkSender)
References SeRoomMember::acName, SeMT_MatchRoomMemberNotifyRet::akInfo, SeRoomMember::bySeat, SeMT_MatchRoomMemberNotifyRet::dwPlayerID, SeMT_MatchRoomMemberNotifyRet::dwRoomID, SeMT_MatchRoomMemberNotifyRet::dwRoomLeaderID, SeMT_MatchRoomMemberNotifyRet::eNoticeCode, g_kPlayerMgr, SePlayer::GetClientID, SePlayer::GetID, SePlayerMgr::GetPlayerByID, SeMT_MatchRoomMemberNotifyRet::iNum, SePlayer::m_bRoomCreater, SeLogInfo, SendTC_RoomMemberNotify.
void TownServer::ProcessMT_MatchRoomLeaveRet(SeMT_MatchRoomLeaveRet *pkData, int iSize, void *pkSender)
References SeMT_MatchRoomLeaveRet::dwPlayerID, SeMT_MatchRoomLeaveRet::dwRoomID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SePlayer::m_bRoomCreater, SeLogInfo, SendTC_RoomLeaveRet.
void TownServer::ProcessMT_MatchRoomReadyRet(SeMT_MatchRoomReadyRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchRoomSwitchSeatRet(SeMT_MatchRoomSwitchSeatRet *pkData, int iSize, void *pkSender)
References SeMT_MatchRoomSwitchSeatRet::dwPlayerID, SeMT_MatchRoomSwitchSeatRet::eType, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogInfo, SendTC_RoomSwitchSeatRet.
void TownServer::ProcessMT_MatchRoomKickSomeoneRet(SeMT_MatchRoomKickSomeoneRet *pkData, int iSize, void *pkSender)
References SeMT_MatchRoomKickSomeoneRet::dwPlayerID, SeMT_MatchRoomKickSomeoneRet::dwRoomID, SeMT_MatchRoomKickSomeoneRet::eType, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_MatchRoomKickSomeoneRet::iseat, SeLogInfo, SendTC_RoomKickSomeoneRet.
void TownServer::ProcessMT_AddIncompleteRace(SeMT_AddIncompleteRace *pkData, int iSize, void *pkSender)
References SeRaceMgr::AddIncmpRace, SeIncompleteRaceBaseInfo::dwRoomID, g_kPlayerMgr, g_kRaceMgr, SeMT_AddIncompleteRace::oIncompleteRaceBaseInfo, SePlayerMgr::OnAddIncmpRace, SeLogDebug.
void TownServer::ProcessMT_RemoveIncompleteRace(SeMT_RemoveIncompleteRace *pkData, int iSize, void *pkSender)
References SeMT_RemoveIncompleteRace::dwRoomID, g_kPlayerMgr, g_kRaceMgr, SePlayerMgr::OnRemoveIncmpRace, SeRaceMgr::RemoveIncmpRace, SeLogDebug.
void TownServer::ProcessMT_ResIncmpRaceSeatBaseInfo(SeMT_ResIncmpRaceSeatBaseInfo *pkData, int iSize, void *pkSender)
References SeMT_ResIncmpRaceSeatBaseInfo::dwPlayerID, SeMT_ResIncmpRaceSeatBaseInfo::dwRoomID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_ResIncmpRaceSeatBaseInfo::iNum, SeMT_ResIncmpRaceSeatBaseInfo::oIncmpRaceBaseInfo, SeLogDebug, SendTC_ResIncmpRaceSeatBaseInfo.
void TownServer::ProcessMT_ResIncompleteRaceList(SeMT_ResIncompleteRaceList *pkData, int iSize, void *pkSender)
References SeMT_ResIncompleteRaceList::akIncmpRaceList, SeMT_ResIncompleteRaceList::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_ResIncompleteRaceList::iNum, SeLogDebug, SendTC_ResIncompleteRaceList.
void TownServer::ProcessMT_ReqMatchRep(SeMT_ReqMatchRep *pkData, int iSize, void *pkSender)
References SeMT_ReqMatchRep::dwPlayerID, ENState_Matching, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_ReqMatchRep::ReqResult, ReqResultSuccess, SendTC_ReqMatchRep, SendTN_NexusLinkUserSync.
void TownServer::ProcessMT_MatchCancelRep(SeMT_MatchCancelRep *pkData, int iSize, void *pkSender)
References SeMT_MatchCancelRep::CancelMatchResult, CancelResultSuccess, SeMT_MatchCancelRep::dwPlayerID, SeMT_MatchCancelRep::dwReceiver, ENState_Online, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SendTC_CancelMatchRep, SendTN_NexusLinkUserSync.
void TownServer::ProcessMT_NotiMatcherPre(SeMT_NotiMatcherPre *pkData, int iSize, void *pkSender)
References SeMT_NotiMatcherPre::dwPlayerID, SeMT_NotiMatcherPre::dwPlayerNum, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SendTC_NotiMatcherPre, SeMT_NotiMatcherPre::WaitID.
void TownServer::ProcessMT_NotiMatcherResult(SeMT_NotiMatcherResult *pkData, int iSize, void *pkSender)
References SeMT_NotiMatcherResult::dwPlayerID, ENState_Online, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_NotiMatcherResult::ResultKind, SeLogDebug, SendTC_NotiMatcherResult, SendTN_NexusLinkUserSync.
void TownServer::ProcessMT_SingleMatchConfirm(SeMT_SingleMatchConfirm *pkData, int iSize, void *pkSender)
References SeMT_SingleMatchConfirm::BolConfirm, SeMT_SingleMatchConfirm::dwReceiver, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeMT_SingleMatchConfirm::MaxPlayerNum, SeMT_SingleMatchConfirm::PlayerID, SeMT_SingleMatchConfirm::PlayerIndex, SendTC_SingleMatchConfirm.
void TownServer::ProcessTCPSvr(void *pkData, int iSize)
References CMD_TT_CLIENTCONNECT, CMD_TT_CLIENTDISCONNECT, CMD_TT_HEARTPACKAGE, CMD_TT_RECVDATA, CMD_TT_REGISTER, CMD_TT_RELOAD_READY_ID, ProcessTCPSvr_ClientConnect, ProcessTCPSvr_ClientDisconnect, ProcessTCPSvr_HeartPackage, ProcessTCPSvr_RecvData, ProcessTCPSvr_Register, ProcessTCPSvr_ReLoadReadyID, SeCMD::wCmd.
Referenced by OnNetRecv.
void TownServer::ProcessTCPSvr_Register(void *pkData, int iSize)
References SeNetAddr::acIP, SeTCPSvrData::bRegister, SeNetAddr::iPort, SeTT_Register::kTCPAddr, SeTCPSvrData::kTCPAddr, m_kTCPSvrData, SeLogInfo, SendTCPSvr_RegisterRet, SRR_FAILED, SRR_SUCCESS.
Referenced by ProcessTCPSvr.
void TownServer::ProcessTCPSvr_ClientConnect(void *pkData, int iSize)
References SeTCPUser::acAccount, SeTCPUser::acEncryptKey, SeNetAddr::acIP, SeTT_ClientConnect::acIP, SeTT_ClientConnect::dwClientID, SeTCPUser::dwClientID, SeTCPUser::dwPlayerID, SeTCPUser::dwStateTime, SeTCPUser::eState, GenEncryptKey, GetTcpUser, SeTCPUser::kNetAddr, m_dwCurTime, m_kAllTcpUser, SCS_UNKOWN, SeLogError, SeLogInfo, SendTC_EncryptKey, SSD_EN_KEY_LEN, StrCpy.
Referenced by ProcessTCPSvr.
void TownServer::ProcessTCPSvr_ClientDisconnect(void *pkData, int iSize)
References SePlayerMgr::DelPlayer, SeTT_ClientDisconnect::dwClientID, SeTCPUser::dwPlayerID, ENState_Offline, g_kPlayerMgr, SePlayerMgr::GetPlayerByID, m_kAllTcpUser, SeLogInfo, SendTN_NexusLinkUserSync, SendTW_PlayerLeave.
Referenced by ProcessTCPSvr.
void TownServer::ProcessTCPSvr_RecvData(void *pkData, int iSize)
References SeTT_RecvData::acData, SeTT_RecvData::dwClientID, GetTcpUser, SeTT_RecvData::iDataLen, ProcessCTData.
Referenced by ProcessTCPSvr.
void TownServer::ProcessTCPSvr_HeartPackage(void *pkData, int iSize)
References SendTCPSvr_HeartPackageRet.
Referenced by ProcessTCPSvr.
void TownServer::ProcessTCPSvr_ReLoadReadyID(void *pkData, int iSize)
References SeTT_ReLoadReadyID::acData, SeNetAddr::acIP, SePlayerMgr::AddPlayer, SeNetStream::Attach, SeTT_ReLoadReadyID::bOver, SeTCPUser::dwClientID, SeTCPUser::dwPlayerID, SeTCPUser::dwStateTime, SeTCPUser::eState, g_kPlayerMgr, GetDWord2IPString, GetTcpUser, SeTT_ReLoadReadyID::iDataLen, SeNetStream::IsEnd, SeTCPUser::kNetAddr, SeTCPSvrData::kSock, m_bTCPSvrReady, m_dwCurTime, m_kAllTcpUser, m_kNetMgr, m_kTCPSvrData, SeNetStream::ReadDword, SCS_VALID_OK, SeLogError, SeLogInfo, SSD_ENDSTR_LEN, StrCpy.
Referenced by ProcessTCPSvr.
bool TownServer::ProcessWCMSTData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool TownServer::PreProcessWCMST(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessWCMST_RegisterRet(SeWCMST_RegisterRet *pkData, int iSize, void *pkSender)
References SeServerData::bRegistered, SeWCMST_RegisterRet::eRet, m_kWCSData, SeLogError, SeLogInfo, SRR_SUCCESS.
void TownServer::ProcessWCMST_HeartPackageRet(SeWCMST_HeartPackageRet *pkData, int iSize, void *pkSender)
References SeServerData::dwHeartPackageTime, m_kWCSData.
void TownServer::ProcessWCMST_ResView(SeWCMST_ResView *pkData, int iSize, void *pkSender)
References SeWCMST_ResView::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWCMST_ResView::kViewAddr, SeWCMST_ResView::rID, SeLogDebug, SeLogError, SendTC_ResView.
void TownServer::ProcessWCMST_ResViewList(SeWCMST_ResViewList *pkData, int iSize, void *pkSender)
References SeWCMST_ResViewList::akSeViewList, SeWCMST_ResViewList::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWCMST_ResViewList::iMaxPage, SeWCMST_ResViewList::iNum, SeWCMST_ResViewList::iPage, SeLogDebug, SeLogError, SendTC_ResViewList.
void TownServer::ProcessWCMST_ResRaceDetailInfo(SeWCMST_ResRaceDetailInfo *pkData, int iSize, void *pkSender)
References SeWCMST_ResRaceDetailInfo::akRaceDetailInfo, SeWCMST_ResRaceDetailInfo::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeWCMST_ResRaceDetailInfo::iNum, SeWCMST_ResRaceDetailInfo::page_max_number, SeWCMST_ResRaceDetailInfo::page_number, SeLogDebug, SeLogError, SendTC_ResRaceDetailInfo.
bool TownServer::SendTWCMS_Register(DWord dwServerID, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by RegisterToWCS.
bool TownServer::SendTWCMS_HeartPackage(void *pkReceiver=NULL)
Referenced by UpdateWCSHeartPackage.
bool TownServer::SendTWCMS_ReqView(DWord dwPlayerID, const Byte *rID, void *pkReceiver=NULL)
Referenced by ProcessCT_ReqView.
bool TownServer::SendTWCMS_ReqView(DWord dwPlayerID, std::vector< Byte > &rID, void *pkReceiver=NULL)
bool TownServer::SendTWCMS_ReqViewList(DWord dwPlayerID, int iPage, void *pkReceiver=NULL)
Referenced by ProcessCT_ReqViewList.
bool TownServer::SendTWCMS_RaceDetailInfoReq(DWord dwPlayerID, int page_number, int page_counts, void *pkReceiver=NULL)
Referenced by ProcessCT_RaceDetailInfoReq.
bool TownServer::SendTWCMSData(void *pkData, int iSize, void *pkReceiver)
References SeServerData::bRegistered, CMD_TWCMS_REGISTER, SeServerData::kSock, m_kNetMgr, m_kWCSData, SeCMD::wCmd.
bool TownServer::SendTN_Register(DWord dwServerID, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by RegisterToNS.
bool TownServer::SendTN_HeartPackage(void *pkReceiver=NULL)
Referenced by UpdateNSHeartPackage.
bool TownServer::SendTN_RoomInviteNotifyVerify(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_RoomInvite.
bool TownServer::SendTN_NexusFriendDetailInfoReq(DWord dwPlayerID, int page_number, int page_counts, void *pkReceiver=NULL)
Referenced by ProcessCT_NexusFriendDetailInfoReq.
bool TownServer::SendTN_NexusUserActionReq(DWord dwPlayerID, DWord dwPlayerOnlineID, const SeNexusUserInfo &nexus_user_actions, void *pkReceiver=NULL)
Referenced by ProcessCT_NexusUserActionReq.
bool TownServer::SendTN_NexusLinkUserSync(DWord dwPlayerID, DWord dwStateID, DWord dwLoginTime, void *pkReceiver=NULL)
Referenced by ProcessMT_MatchCancelRep, ProcessMT_NotiMatcherResult, ProcessMT_ReqMatchRep, ProcessTCPSvr_ClientDisconnect, ProcessWT_InitPlayerInfo.
bool TownServer::SendTN_CreateUserSync(DWord dwPlayerID, DWord dwLoginTime, const char *acRemoteIp, void *pkReceiver=NULL)
Referenced by ProcessWT_CreateCharRet.
bool TownServer::SendTN_UserInviteReq(DWord dwPlayerID, const char *acUserName, DWord dwGuestID, const char *acGuestName, void *pkReceiver=NULL)
Referenced by ProcessCT_UserInviteReq.
bool TownServer::SendTN_UserConfirmInviteReq(DWord dwPlayerID, DWord dwTeamID, void *pkReceiver=NULL)
Referenced by ProcessCT_UserConfirmInviteReq.
bool TownServer::SendTN_UserRefuseInviteReq(DWord dwPlayerID, DWord dwTeamID, void *pkReceiver=NULL)
Referenced by ProcessCT_UserRefuseInviteReq.
bool TownServer::SendTN_UserLeaveTeamReq(DWord dwPlayerID, DWord dwTeamID, void *pkReceiver=NULL)
Referenced by ProcessCT_UserLeaveTeamReq.
bool TownServer::SendTN_LeaderKickMemberReq(DWord dwPlayerID, DWord dwTeamID, DWord dwMemberID, void *pkReceiver=NULL)
Referenced by ProcessCT_LeaderKickMemberReq.
bool TownServer::SendTN_LeaderDismissTeamReq(DWord dwPlayerID, DWord dwTeamID, void *pkReceiver=NULL)
Referenced by ProcessCT_LeaderDismissTeamReq.
bool TownServer::SendTN_MatchTeamMemberReq(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_PlayerMatchReq.
bool TownServer::SendTN_NexusFriendCleanRefuseNoticeReq(DWord dwPlayerID, DWord guest_id, void *pkReceiver=NULL)
Referenced by ProcessCT_NexusFriendCleanRefuseNoticeReq.
bool TownServer::SendTN_UserStatusQueryReq(DWord dwPlayerID, DWord num, const DWord *user_ids, void *pkReceiver=NULL)
Referenced by ProcessCT_UserStatusQueryReq.
bool TownServer::SendTN_UserStatusQueryReq(DWord dwPlayerID, DWord num, std::vector< DWord > &user_ids, void *pkReceiver=NULL)
bool TownServer::SendTN_UserAttrInfoSync(DWord dwPlayerID, const SeUserBaseAttrInfo &user_attr, void *pkReceiver=NULL)
Referenced by ProcessWT_InitPlayerInfo.
bool TownServer::SendTNData(void *pkData, int iSize, void *pkReceiver)
References SeServerData::bRegistered, CMD_TN_REGISTER, SeServerData::kSock, m_kNetMgr, m_kNSData, SeCMD::wCmd.
bool TownServer::ProcessNTData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool TownServer::PreProcessNT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_RegisterRet(SeNT_RegisterRet *pkData, int iSize, void *pkSender)
References SeServerData::bRegistered, SeNT_RegisterRet::dwAreaID, SeServerData::dwID, SeTownConfig::dwServerID, SeNT_RegisterRet::eRet, GetID2Str, m_kConfig, m_kNSData, SeLogError, SeLogInfo, SRR_SUCCESS.
void TownServer::ProcessNT_HeartPackageRet(SeNT_HeartPackageRet *pkData, int iSize, void *pkSender)
References SeServerData::dwHeartPackageTime, m_kNSData.
void TownServer::ProcessNT_NexusFriendDetailInfoRes(SeNT_NexusFriendDetailInfoRes *pkData, int iSize, void *pkSender)
References SeNT_NexusFriendDetailInfoRes::akNexusFriendInfo, SeNT_NexusFriendDetailInfoRes::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeNT_NexusFriendDetailInfoRes::iNum, SeNT_NexusFriendDetailInfoRes::page_max_number, SeNT_NexusFriendDetailInfoRes::page_number, SeLogDebug, SeLogError, SendTC_NexusFriendDetailInfoRes.
void TownServer::ProcessNT_NexusUserActionSync(SeNT_NexusUserActionSync *pkData, int iSize, void *pkSender)
References SeNT_NexusUserActionSync::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogDebug, SeLogError, SendTC_NexusUserActionSync, SeNT_NexusUserActionSync::sync_info.
void TownServer::ProcessNT_TeamChangeSync(SeNT_TeamChangeSync *pkData, int iSize, void *pkSender)
References SeNT_TeamChangeSync::acLeaderName, SeNT_TeamChangeSync::dwLeaderID, SeNT_TeamChangeSync::dwPlayerID, SeNT_TeamChangeSync::dwTeamID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogDebug, SeLogError, SendTC_TeamChangeSync.
void TownServer::ProcessNT_TeamLeaderSync(SeNT_TeamLeaderSync *pkData, int iSize, void *pkSender)
References SeNT_TeamLeaderSync::acGuestName, SeNT_TeamLeaderSync::dwGuestID, SeNT_TeamLeaderSync::dwMark, SeNT_TeamLeaderSync::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogDebug, SeLogError, SendTC_TeamLeaderSync.
void TownServer::ProcessNT_TeamMemberSync(SeNT_TeamMemberSync *pkData, int iSize, void *pkSender)
References SeNT_TeamMemberSync::acInviterName, SeNT_TeamMemberSync::dwInviterID, SeNT_TeamMemberSync::dwMark, SeNT_TeamMemberSync::dwPlayerID, SeNT_TeamMemberSync::dwTeamID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogDebug, SeLogError, SendTC_TeamMemberSync.
void TownServer::ProcessNT_TeamUserStateRes(SeNT_TeamUserStateRes *pkData, int iSize, void *pkSender)
References SeNT_TeamUserStateRes::dwPlayerID, SeNT_TeamUserStateRes::dwStateID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogDebug, SeLogError, SendTC_TeamUserStateRes.
void TownServer::ProcessNT_TeamMemberInfoRes(SeNT_TeamMemberInfoRes *pkData, int iSize, void *pkSender)
References SeNT_TeamMemberInfoRes::dwPlayerID, SeNT_TeamMemberInfoRes::dwTeamID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeNT_TeamMemberInfoRes::iNum, SeNT_TeamMemberInfoRes::member_info, SeLogDebug, SeLogError, SendTC_TeamMemberInfoRes.
void TownServer::ProcessNT_NexusFriendStatusSync(SeNT_NexusFriendStatusSync *pkData, int iSize, void *pkSender)
References SeNT_NexusFriendStatusSync::dwFriendID, SeNT_NexusFriendStatusSync::dwOnlineID, SeNT_NexusFriendStatusSync::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogDebug, SeLogError, SendTC_NexusFriendStatusSync.
void TownServer::ProcessNT_NexusFriendLimitRes(SeNT_NexusFriendLimitRes *pkData, int iSize, void *pkSender)
References SeNT_NexusFriendLimitRes::dwLimitID, SeNT_NexusFriendLimitRes::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogDebug, SeLogError, SendTC_NexusFriendLimitRes.
void TownServer::ProcessNT_MatchTeamMemberRes(SeNT_MatchTeamMemberRes *pkData, int iSize, void *pkSender)
References SePlayer::bySeats, SePlayer::dwMapID, SeNT_MatchTeamMemberRes::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayer::GetID, SePlayerMgr::GetPlayerByID, SeNT_MatchTeamMemberRes::IDArray, SePlayer::m_matchData, SeNT_MatchTeamMemberRes::MemberNum, ReqResultSuccess, SeNT_MatchTeamMemberRes::result, SeLogError, SendTC_ReqMatchRep, SendTM_PlayerMatchReq.
void TownServer::ProcessNT_NexusFriendCleanRefuseNoticeRes(SeNT_NexusFriendCleanRefuseNoticeRes *pkData, int iSize, void *pkSender)
References SeNT_NexusFriendCleanRefuseNoticeRes::dwGuestID, SeNT_NexusFriendCleanRefuseNoticeRes::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeLogDebug, SeLogError, SendTC_NexusFriendCleanRefuseNoticeRes.
void TownServer::ProcessNT_UserStatusQueryRes(SeNT_UserStatusQueryRes *pkData, int iSize, void *pkSender)
References SeNT_UserStatusQueryRes::base_info, SeNT_UserStatusQueryRes::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeNT_UserStatusQueryRes::iNum, SeLogDebug, SeLogError, SendTC_UserStatusQueryReqRes.
void TownServer::ProcessNT_RoomInviteNotifyVerifyRsp(SeNT_RoomInviteNotifyVerifyRsp *pkData, int iSize, void *pkSender)
References SeNT_RoomInviteNotifyVerifyRsp::dwInviteeID, SeNT_RoomInviteNotifyVerifyRsp::dwPlayerID, SeNT_RoomInviteNotifyVerifyRsp::dwRoomID, g_kPlayerMgr, SePlayer::GetID, SePlayerMgr::GetPlayerByID, SeLogError, SendTM_MatchRoomInvite.
bool TownServer::SendTBL_GMSetGold(DWord dwPlayerID, DWord dwGold, void *pkReceiver=NULL)
Referenced by ProcessCT_GMSetGold.
bool TownServer::SendTBL_GMSetDiamond(DWord dwPlayerID, DWord dwDiamond, void *pkReceiver=NULL)
Referenced by ProcessCT_GMSetDiamond.
bool TownServer::SendTBL_ReqItemStrenth(DWord dwPlayerID, Word wPos, int iNum, const Word *SrcPosArray, void *pkReceiver=NULL)
Referenced by ProcessCT_ReqItemStrenth.
bool TownServer::SendTBL_ReqItemStrenth(DWord dwPlayerID, Word wPos, int iNum, std::vector< Word > &SrcPosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_ReqItemCiTiaoChange(DWord dwPlayerID, Word wPos, Word wIndex, Byte BolLock, int iNum, const Word *SrcPosArray, void *pkReceiver=NULL)
Referenced by ProcessCT_ReqItemCiTiaoChange.
bool TownServer::SendTBL_ReqItemCiTiaoChange(DWord dwPlayerID, Word wPos, Word wIndex, Byte BolLock, int iNum, std::vector< Word > &SrcPosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_ReqItemDepart(DWord dwPlayerID, Word wPos, void *pkReceiver=NULL)
Referenced by ProcessCT_ReqItemDepart.
bool TownServer::SendTBL_GMAddItem(DWord dwPlayerID, DWord ItemID, int Num, int Level, void *pkReceiver=NULL)
Referenced by ProcessCT_GMAddItem.
bool TownServer::SendTBL_DelelteItem(DWord dwPlayerID, Word wPos, void *pkReceiver=NULL)
Referenced by ProcessCT_DelelteItem.
bool TownServer::SendTBL_PutOnEquip(DWord dwPlayerID, Word wPos, Word PutPos, void *pkReceiver=NULL)
Referenced by ProcessCT_PutOnEquip.
bool TownServer::SendTBL_TakeOffEquip(DWord dwPlayerID, Word wPos, void *pkReceiver=NULL)
Referenced by ProcessCT_TakeOffEquip.
bool TownServer::SendTBL_OpenRandBox(DWord dwPlayerID, Word wPos, void *pkReceiver=NULL)
Referenced by ProcessCT_OpenRandBox.
bool TownServer::SendTBL_ClearItemNewFlag(DWord dwPlayerID, int iNum, const Word *PosArray, void *pkReceiver=NULL)
Referenced by ProcessCT_ClearItemNewFlag.
bool TownServer::SendTBL_ClearItemNewFlag(DWord dwPlayerID, int iNum, std::vector< Word > &PosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_LadderRankQueryReq(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_LadderRankQueryReq.
bool TownServer::SendTBL_FriendLadderInfoReq(DWord dwPlayerID, DWord dwFriendID, void *pkReceiver=NULL)
Referenced by ProcessCT_FriendLadderInfoReq.
bool TownServer::SendTBL_UserMapRaceHeroReq(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_UserMapRaceHeroReq.
bool TownServer::SendTBL_SetActiveAvatarReq(DWord dwPlayerID, bool bActive, DWord dwItemID, void *pkReceiver=NULL)
Referenced by ProcessCT_SetActiveAvatarReq.
bool TownServer::SendTBL_UserAlterNickNameReq(DWord dwPlayerID, const char *acNickName, void *pkReceiver=NULL)
Referenced by ProcessCT_UserAlterNickNameReq.
bool TownServer::SendTBL_UserAlterAvatarReq(DWord dwPlayerID, DWord dwAvatarID, void *pkReceiver=NULL)
Referenced by ProcessCT_UserAlterAvatarReq.
bool TownServer::SendTBL_UserAlterAvatarFrameReq(DWord dwPlayerID, DWord dwAvatarFrameID, void *pkReceiver=NULL)
Referenced by ProcessCT_UserAlterAvatarFrameReq.
bool TownServer::SendTBL_UserPurchaseAvatarReq(DWord dwPlayerID, DWord dwAvatarID, void *pkReceiver=NULL)
Referenced by ProcessCT_UserPurchaseAvatarReq.
bool TownServer::SendTBL_UserRaceMapDetailReq(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_SeUserRaceArenaDetailInfoReq.
bool TownServer::SendTBL_LadderDetailInfoReq(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_LadderDetailInfoReq.
bool TownServer::SendTBL_AchieveInfoReq(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessCT_AchieveInfoReq.
bool TownServer::SendTBLData(void *pkData, int iSize, void *pkReceiver)
References SendTWData.
bool TownServer::ProcessBLTData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool TownServer::PreProcessBLT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_PlayerOperRep(SeBLT_PlayerOperRep *pkData, int iSize, void *pkSender)
References SeBLT_PlayerOperRep::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_PlayerOperRep::iResult, SendTC_PlayerOperRep.
void TownServer::ProcessBLT_OpenRandBoxRet(SeBLT_OpenRandBoxRet *pkData, int iSize, void *pkSender)
References SeBLT_OpenRandBoxRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_OpenRandBoxRet::iNum, SeBLT_OpenRandBoxRet::iResult, SeBLT_OpenRandBoxRet::ItemArray, SendTC_OpenRandBoxRet.
void TownServer::ProcessBLT_PutOnEquipRet(SeBLT_PutOnEquipRet *pkData, int iSize, void *pkSender)
References SeBLT_PutOnEquipRet::dwItemID, SeBLT_PutOnEquipRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_PutOnEquipRet::iResult, SendTC_PutOnEquipRet, SeBLT_PutOnEquipRet::wEquipPos.
void TownServer::ProcessBLT_TakeOffEquipRet(SeBLT_TakeOffEquipRet *pkData, int iSize, void *pkSender)
References SeBLT_TakeOffEquipRet::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_TakeOffEquipRet::iResult, SendTC_TakeOffEquipRet, SeBLT_TakeOffEquipRet::wEquipPos.
void TownServer::ProcessBLT_LadderRankQueryAck(SeBLT_LadderRankQueryAck *pkData, int iSize, void *pkSender)
References SeBLT_LadderRankQueryAck::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_LadderRankQueryAck::iNum, SeBLT_LadderRankQueryAck::RankList, SendTC_LadderRankQueryAck.
void TownServer::ProcessBLT_UserRaceHeroAck(SeBLT_UserRaceHeroAck *pkData, int iSize, void *pkSender)
References SeBLT_UserRaceHeroAck::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_UserRaceHeroAck::hero_info, SeBLT_UserRaceHeroAck::iNum, SendTC_UserRaceMapHeroAck.
void TownServer::ProcessBLT_SetActiveAvatarAck(SeBLT_SetActiveAvatarAck *pkData, int iSize, void *pkSender)
References SeBLT_SetActiveAvatarAck::dwItemID, SeBLT_SetActiveAvatarAck::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_SetActiveAvatarAck::iResult, SendTC_SetActiveAvatarAck.
void TownServer::ProcessBLT_UserAlterNickNameAck(SeBLT_UserAlterNickNameAck *pkData, int iSize, void *pkSender)
References SeBLT_UserAlterNickNameAck::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_UserAlterNickNameAck::iResult, SendTC_UserAlterNickNameAck.
void TownServer::ProcessBLT_UserAlterAvatarAndFrameNtf(SeBLT_UserAlterAvatarAndFrameNtf *pkData, int iSize, void *pkSender)
References SeBLT_UserAlterAvatarAndFrameNtf::dwAvatarFrameID, SeBLT_UserAlterAvatarAndFrameNtf::dwAvatarID, SeBLT_UserAlterAvatarAndFrameNtf::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SendTC_UserAlterAvatarAndFrameNtf.
void TownServer::ProcessBLT_UserRaceArenaDetailAck(SeBLT_UserRaceArenaDetailAck *pkData, int iSize, void *pkSender)
References SeBLT_UserRaceArenaDetailAck::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_UserRaceArenaDetailAck::race_arena_info, SendTC_SeUserRaceArenaDetailInfoRes.
void TownServer::ProcessBLT_LadderDetailInfoAck(SeBLT_LadderDetailInfoAck *pkData, int iSize, void *pkSender)
References SeBLT_LadderDetailInfoAck::dwPlayerID, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_LadderDetailInfoAck::info, SendTC_LadderDetailInfoAck.
void TownServer::ProcessBLT_AchieveInfoAck(SeBLT_AchieveInfoAck *pkData, int iSize, void *pkSender)
References SeBLT_AchieveInfoAck::dwPlayerID, SeBLT_AchieveInfoAck::finishInfo, g_kPlayerMgr, SePlayer::GetClientID, SePlayerMgr::GetPlayerByID, SeBLT_AchieveInfoAck::iNum1, SeBLT_AchieveInfoAck::iNum2, SeBLT_AchieveInfoAck::scheduleInfo, SendTC_AchieveInfoAck.
TownServer::TownServer(void)
TownServer::~TownServer(void)
bool TownServer::Initialize()
void TownServer::Update(void)
void TownServer::Finialize(void)
void TownServer::ShowConsoleTitle(int iDTime)
SeServerActionResult TownServer::ExecuteAction(SeServerActionIndex eActionIndex)
virtual void TownServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
virtual void TownServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
virtual void TownServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
virtual void TownServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
bool TownServer::SendTW_Register(DWord dwTownMagic, DWord dwServerID, const SeTownInfo &kInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_HeartPackage(void *pkReceiver=NULL)
bool TownServer::SendTW_LoadPlayerInfoAgain(int iTotalNum, int iBegin, int iNum, const SeLoadPlayerInfoAgain *akPlayerInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_LoadPlayerInfoAgain(int iTotalNum, int iBegin, int iNum, std::vector< SeLoadPlayerInfoAgain > &akPlayerInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_PlayerValidate(DWord dwClientID, DWord dwPlayerID, DWord dwSessionID, DWord dwPlayerIP, DWord dwMaxMailID, const SeMobileInfo &kMobileInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_QueryName(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
bool TownServer::SendTW_CreateChar(DWord dwPlayerID, const char *acName, int iSex, DWord dwCardTypeID, void *pkReceiver=NULL)
bool TownServer::SendTW_PlayerLeave(DWord dwPlayerID, bool bExitGame, void *pkReceiver=NULL)
bool TownServer::SendTW_RaceEndRace(DWord dwTime, DWord dwMapID, DWord dwRoomSession, const SeMatchRaceType &eMatchType, int iNum, const SeWSRaceSendInfo *akInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_RaceEndRace(DWord dwTime, DWord dwMapID, DWord dwRoomSession, const SeMatchRaceType &eMatchType, int iNum, std::vector< SeWSRaceSendInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_RaceEndGuanka(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, const SeWSGuanqiaSendInfo *akInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_RaceEndGuanka(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, std::vector< SeWSGuanqiaSendInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTW_ItemExchange(DWord dwPlayerID, int iTypeID, void *pkReceiver=NULL)
bool TownServer::SendTW_SavePlayerReconInfo(DWord dwPlayerID, DWord dwRoomID, int iSeatIndex, void *pkReceiver=NULL)
bool TownServer::SendTW_TaskQueryList(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTW_TaskResel(DWord dwPlayerID, DWord dwTaskID, void *pkReceiver=NULL)
bool TownServer::SendTW_GetTaskReward(DWord dwPlayerID, DWord dwTaskID, void *pkReceiver=NULL)
bool TownServer::SendTW_MatchRaceLoad(DWord dwRoomSession, DWord dwPlayerID, DWord dwMapID, void *pkReceiver=NULL)
bool TownServer::SendTW_DelReconInfo(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTW_PlayerRename(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
bool TownServer::SendTW_RaceBuy(DWord dwSession, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool TownServer::SendTW_MapTaskOpr(DWord dwPlayerID, int iOprType, DWord dwParam, void *pkReceiver=NULL)
bool TownServer::SendTW_QueryNearestRaceInfo(DWord dwPlayerID, DWord dwMapID, DWord dwQueriedID, void *pkReceiver=NULL)
bool TownServer::SendTW_PlayerLeaveRace(DWord dwPlayerID, DWord dwRoomID, int iSeatIndex, void *pkReceiver=NULL)
bool TownServer::SendTW_BuyShopItem(DWord dwPlayerID, int types, DWord ShopID, DWord Num, void *pkReceiver=NULL)
bool TownServer::SendTW_ShopItemGM(DWord dwPlayerID, int iNum, const ShopItem *GmItems, void *pkReceiver=NULL)
bool TownServer::SendTW_ShopItemGM(DWord dwPlayerID, int iNum, std::vector< ShopItem > &GmItems, void *pkReceiver=NULL)
bool TownServer::SendTW_GetItemGM(DWord dwPlayerID, DWord ShopID, void *pkReceiver=NULL)
bool TownServer::SendTW_SearchUserArchivesInfoReq(DWord dwPlayerID, const SeUserArchivesNameInfo &username, void *pkReceiver=NULL)
bool TownServer::SendTW_SearchUserArchivesDetailInfoReq(DWord dwPlayerID, DWord userid, void *pkReceiver=NULL)
bool TownServer::SendTWData(void *pkData, int iSize, void *pkReceiver)
bool TownServer::SendTC_EncryptKey(const char *abyEncryptKey, DWord dwVersion, void *pkReceiver=NULL)
bool TownServer::SendTC_ShowNotice(SeNoticeCode eNoticeCode, DWord dwParam, const char *acMessage, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerValidateRet(SeValidateType eValidateType, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryNameRet(bool bHasExist, void *pkReceiver=NULL)
bool TownServer::SendTC_CreateCharRet(SeCreateCharRet eResult, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerLeaveRet(void *pkReceiver=NULL)
bool TownServer::SendTC_InitPlayerInfo(DWord dwPlayerID, const char *acName, DWord iGold, DWord iDiamond, DWord dwLevel, DWord dwExp, const SeLadderInfo &kLadder, Byte byEquipSetIndex, DWord dwServerTime, DWord dwOnlineTime, void *pkReceiver=NULL)
bool TownServer::SendTC_MatchRaceAddr(DWord dwSessionID, int dwKey, SeRaceValidType eValidType, const SePtlNetAddr &kRaceAddr, const SePtlNetAddr &kRaceAddrUdp, int iSeat, int iNum, const SeNoticeMatchPlayerInfo *akPlayerInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_MatchRaceAddr(DWord dwSessionID, int dwKey, SeRaceValidType eValidType, const SePtlNetAddr &kRaceAddr, const SePtlNetAddr &kRaceAddrUdp, int iSeat, int iNum, std::vector< SeNoticeMatchPlayerInfo > &akPlayerInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerAppear(int iNum, const SePlayerAppear *akPlayerList, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerAppear(int iNum, std::vector< SePlayerAppear > &akPlayerList, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerDisappear(int iNum, const SePlayerDisappear *adwID, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerDisappear(int iNum, std::vector< SePlayerDisappear > &adwID, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerGoPos(DWord dwPlayerID, float fDirect, void *pkReceiver=NULL)
bool TownServer::SendTC_ExchangeInit(int iNum, const SePtlExchange *akPtlExchange, void *pkReceiver=NULL)
bool TownServer::SendTC_ExchangeInit(int iNum, std::vector< SePtlExchange > &akPtlExchange, void *pkReceiver=NULL)
bool TownServer::SendTC_ViewResult(SeViewResultType eResult, int iData, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryRaceRoomListRet(int iCurPage, int iMaxPage, int iRoomNums, const SeMatchRoomListInfo *akRoomInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryRaceRoomListRet(int iCurPage, int iMaxPage, int iRoomNums, std::vector< SeMatchRoomListInfo > &akRoomInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_ItemExchangeRet(int iTypeID, int iReturn, void *pkReceiver=NULL)
bool TownServer::SendTC_UpdateMisc(SeMiscType eType, int iValue, int iValue2, void *pkReceiver=NULL)
bool TownServer::SendTC_DelayCheckRet(void *pkReceiver=NULL)
bool TownServer::SendTC_BiVoiceEnterInfo(int roomid, const char *acLoginSession, const char *acRoomSession, void *pkReceiver=NULL)
bool TownServer::SendTC_TaskQueryListRet(int iNum, const SePtlTask *akList, void *pkReceiver=NULL)
bool TownServer::SendTC_TaskQueryListRet(int iNum, std::vector< SePtlTask > &akList, void *pkReceiver=NULL)
bool TownServer::SendTC_TaskReselRet(DWord dwSrcTaskID, const SePtlTask &kNewTask, void *pkReceiver=NULL)
bool TownServer::SendTC_AskEnterWaitRace(DWord dwMapID, int iNum, const SeRaceWaitPlayer *akPlayerList, void *pkReceiver=NULL)
bool TownServer::SendTC_AskEnterWaitRace(DWord dwMapID, int iNum, std::vector< SeRaceWaitPlayer > &akPlayerList, void *pkReceiver=NULL)
bool TownServer::SendTC_CardUpdate(void *pkReceiver=NULL)
bool TownServer::SendTC_StartMatchRet(int iResult, DWord dwMapID, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendRequestInit(int iNum, const SePtlFriendRequest *akRequest, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendRequestInit(int iNum, std::vector< SePtlFriendRequest > &akRequest, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendRequestAdd(const SePtlFriendRequest &kInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendInit(int iNum, const SePtlFriend *akFriend, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendInit(int iNum, std::vector< SePtlFriend > &akFriend, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendAdd(const SePtlFriend &kFriend, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendDel(DWord dwFriendID, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendUpdateStatus(DWord dwFriendID, SeOnlineStatus eStatus, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendRemarkRet(DWord dwFriendID, const char *acRemarks, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryRaceBetInfoRet(DWord dwdwConstellIDA, DWord dwdwConstellIDB, float fOddsA, float fOddsB, void *pkReceiver=NULL)
bool TownServer::SendTC_ItemDel(DWord dwItemID, SeItemDelType eType, void *pkReceiver=NULL)
bool TownServer::SendTC_KickPlayer(void *pkReceiver=NULL)
bool TownServer::SendTC_ReceiveMail(int iNum, const SePtlMail *akMail, void *pkReceiver=NULL)
bool TownServer::SendTC_ReceiveMail(int iNum, std::vector< SePtlMail > &akMail, void *pkReceiver=NULL)
bool TownServer::SendTC_UpdateMail(int iNum, const SeMailUpdate *akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_UpdateMail(int iNum, std::vector< SeMailUpdate > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_MailOprRet(int iType, DWord dwMailID, int iRet, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerRename(const char *acName, void *pkReceiver=NULL)
bool TownServer::SendTC_HeartBeat(void *pkReceiver=NULL)
bool TownServer::SendTC_QueryMapTaskListRet(DWord dwMapID, int iNum, const SePtlMapTask *akPtlMapTask, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryMapTaskListRet(DWord dwMapID, int iNum, std::vector< SePtlMapTask > &akPtlMapTask, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryNearestRaceInfoRet(DWord dwQueriedID, int iNum, const SePtlRaceHistory *akRaceInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryNearestRaceInfoRet(DWord dwQueriedID, int iNum, std::vector< SePtlRaceHistory > &akRaceInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_ResIncompleteRaceList(int iNum, const SeIncompleteRaceBaseInfo *akIncmpRaceList, void *pkReceiver=NULL)
bool TownServer::SendTC_ResIncompleteRaceList(int iNum, std::vector< SeIncompleteRaceBaseInfo > &akIncmpRaceList, void *pkReceiver=NULL)
bool TownServer::SendTC_AddIncompleteRace(const SeIncompleteRaceBaseInfo &akIncmpRace, void *pkReceiver=NULL)
bool TownServer::SendTC_RemoveIncompleteRace(DWord iRoomID, void *pkReceiver=NULL)
bool TownServer::SendTC_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, const SeSeatBaseInfo *oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_ResIncmpRaceSeatBaseInfo(DWord dwRoomID, int iNum, std::vector< SeSeatBaseInfo > &oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_InGameDisconn(DWord dwRoomID, int iSeat, int iReconTime, void *pkReceiver=NULL)
bool TownServer::SendTC_CreateRoomRet(SeCreateRoomRetType eType, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_CreateRoomRet(SeCreateRoomRetType eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryRoomListRet(int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_QueryRoomListRet(int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomJoinRet(SeRoomJoinRetType eType, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomJoinRet(SeRoomJoinRetType eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomSwitchSeatRet(SeRoomJoinRetType eType, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomMemberNotify(SeRoomNtfCode eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, const SeRoomMember *akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomMemberNotify(SeRoomNtfCode eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, std::vector< SeRoomMember > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomLeaveRet(DWord dwRoomID, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomStartRet(DWord dwRoomID, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomKickSomeoneRet(DWord dwRoomID, int iseat, SeRoomKickCode eType, void *pkReceiver=NULL)
bool TownServer::SendTC_RoomInviteNotify(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
bool TownServer::SendTC_GetRaceHistoryRet(int iType, int iPage, int iMaxPage, const char *acURLBase, int iNum, const SePtlRaceHistory *akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_GetRaceHistoryRet(int iType, int iPage, int iMaxPage, const char *acURLBase, int iNum, std::vector< SePtlRaceHistory > &akInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_ResAchievementDat(DWord dwPlayerID, int iPage, int iMaxPage, int iNum, const SeAchievementPtlDat *akAchevementDat, void *pkReceiver=NULL)
bool TownServer::SendTC_ResAchievementDat(DWord dwPlayerID, int iPage, int iMaxPage, int iNum, std::vector< SeAchievementPtlDat > &akAchevementDat, void *pkReceiver=NULL)
bool TownServer::SendTC_ResAchievementCounts(DWord dwPlayerID, int iNum, const SeAchievementCounts *akAchevementCounts, void *pkReceiver=NULL)
bool TownServer::SendTC_ResAchievementCounts(DWord dwPlayerID, int iNum, std::vector< SeAchievementCounts > &akAchevementCounts, void *pkReceiver=NULL)
bool TownServer::SendTC_GetAchievement(DWord dwPlayerID, DWord a_ID, int GetTime, void *pkReceiver=NULL)
bool TownServer::SendTC_ResView(const Byte *rID, const SePtlNetAddr &kViewAddr, void *pkReceiver=NULL)
bool TownServer::SendTC_ResView(std::vector< Byte > &rID, const SePtlNetAddr &kViewAddr, void *pkReceiver=NULL)
bool TownServer::SendTC_ResViewList(int iPage, int iMaxPage, int iNum, const SeViewList *akSeViewList, void *pkReceiver=NULL)
bool TownServer::SendTC_ResViewList(int iPage, int iMaxPage, int iNum, std::vector< SeViewList > &akSeViewList, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerNewItem(int iNum, const SeItemNoti *SeItemArray, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerNewItem(int iNum, std::vector< SeItemNoti > &SeItemArray, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerOperRep(int iResult, void *pkReceiver=NULL)
bool TownServer::SendTC_OpenRandBoxRet(int iResult, int iNum, const SeRandBoxItem *ItemArray, void *pkReceiver=NULL)
bool TownServer::SendTC_OpenRandBoxRet(int iResult, int iNum, std::vector< SeRandBoxItem > &ItemArray, void *pkReceiver=NULL)
bool TownServer::SendTC_PutOnEquipRet(int iResult, Word wEquipPos, DWord dwItemID, void *pkReceiver=NULL)
bool TownServer::SendTC_TakeOffEquipRet(int iResult, Word wEquipPos, void *pkReceiver=NULL)
bool TownServer::SendTC_ResRaceDetailInfo(int page_number, int page_max_number, int iNum, const SeRaceDetailInfo *akRaceDetailInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_ResRaceDetailInfo(int page_number, int page_max_number, int iNum, std::vector< SeRaceDetailInfo > &akRaceDetailInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerMoneyAndDiamond(DWord dwPlayerID, DWord dwGold, DWord dwDiamond, void *pkReceiver=NULL)
bool TownServer::SendTC_ShopItemGmRep(DWord dwPlayerID, int iResult, const ShopItem &GmItem, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusFriendDetailInfoRes(int page_number, int page_max_number, int iNum, const SeNexusPlayerInfo *akNexusFriendInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusFriendDetailInfoRes(int page_number, int page_max_number, int iNum, std::vector< SeNexusPlayerInfo > &akNexusFriendInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusUserPromotionDetailInfoRes(const SeNexusUserPromotionInfo &nexus_user_promotion, void *pkReceiver=NULL)
bool TownServer::SendTC_SearchUserArchivesInfoRes(const SeUserArchivesInfo &user_archives_info, void *pkReceiver=NULL)
bool TownServer::SendTC_SearchUserArchivesDetailInfoRes(const SeUserArchivesInfo &user_archives_info, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusUserActionSync(const SeNexusUserInfo &sync_info, void *pkReceiver=NULL)
bool TownServer::SendTC_ReqMatchRep(MatchReqResult ReqResult, void *pkReceiver=NULL)
bool TownServer::SendTC_CancelMatchRep(MatchCancelResult CancelResult, DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTC_NotiMatcherPre(DWord WaitID, DWord dwPlayerNum, void *pkReceiver=NULL)
bool TownServer::SendTC_NotiMatcherResult(DWord ResultKind, void *pkReceiver=NULL)
bool TownServer::SendTC_SingleMatchConfirm(DWord PlayerID, bool BolConfirm, DWord PlayerIndex, DWord MaxPlayerNum, void *pkReceiver=NULL)
bool TownServer::SendTC_SeUserRaceArenaDetailInfoRes(const SeRaceEndArenaResult &race_arena_info, void *pkReceiver=NULL)
bool TownServer::SendTC_TeamChangeSync(DWord dwTeamID, DWord dwLeaderID, const char *acLeaderName, void *pkReceiver=NULL)
bool TownServer::SendTC_TeamLeaderSync(DWord dwGuestID, const char *acGuestName, DWord dwMark, void *pkReceiver=NULL)
bool TownServer::SendTC_TeamMemberSync(DWord dwTeamID, DWord dwInviterID, const char *acInviterName, DWord dwMark, void *pkReceiver=NULL)
bool TownServer::SendTC_TeamUserStateRes(DWord dwStateID, void *pkReceiver=NULL)
bool TownServer::SendTC_TeamMemberInfoRes(DWord dwTeamID, int iNum, const SeTeamMemberBaseInfo *member_info, void *pkReceiver=NULL)
bool TownServer::SendTC_TeamMemberInfoRes(DWord dwTeamID, int iNum, std::vector< SeTeamMemberBaseInfo > &member_info, void *pkReceiver=NULL)
bool TownServer::SendTC_UserHeroSync(DWord dwPlayerID, int num, const SeUserHeroSyncInfo *akHeroSyncInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_UserHeroSync(DWord dwPlayerID, int num, std::vector< SeUserHeroSyncInfo > &akHeroSyncInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusFriendStatusSync(DWord dwFriendID, DWord dwOnlineID, void *pkReceiver=NULL)
bool TownServer::SendTC_PlayerLadder(const SeLadderInfo &kLadder, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusFriendLimitRes(DWord dwLimitID, void *pkReceiver=NULL)
bool TownServer::SendTC_NexusFriendCleanRefuseNoticeRes(DWord dwGuestID, void *pkReceiver=NULL)
bool TownServer::SendTC_UserStatusQueryReqRes(int iNum, const SeUserStatusBaseInfo *base_info, void *pkReceiver=NULL)
bool TownServer::SendTC_UserStatusQueryReqRes(int iNum, std::vector< SeUserStatusBaseInfo > &base_info, void *pkReceiver=NULL)
bool TownServer::SendTC_EquipSchema(int iNum, const SeEquipSchemaInfo *akEquips, void *pkReceiver=NULL)
bool TownServer::SendTC_EquipSchema(int iNum, std::vector< SeEquipSchemaInfo > &akEquips, void *pkReceiver=NULL)
bool TownServer::SendTC_LadderRankQueryAck(int iNum, const SeLadderRankInfo *RankList, void *pkReceiver=NULL)
bool TownServer::SendTC_LadderRankQueryAck(int iNum, std::vector< SeLadderRankInfo > &RankList, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendLadderInfoNtf(int iNum, const SeLadderRankInfo *RankList, void *pkReceiver=NULL)
bool TownServer::SendTC_FriendLadderInfoNtf(int iNum, std::vector< SeLadderRankInfo > &RankList, void *pkReceiver=NULL)
bool TownServer::SendTC_UserRaceMapHeroAck(int iNum, const SeUserRaceMapHeroBase *hero_info, void *pkReceiver=NULL)
bool TownServer::SendTC_UserRaceMapHeroAck(int iNum, std::vector< SeUserRaceMapHeroBase > &hero_info, void *pkReceiver=NULL)
bool TownServer::SendTC_SetActiveAvatarAck(int iResult, DWord dwItemID, void *pkReceiver=NULL)
bool TownServer::SendTC_ActiveAvatarNtf(int iNum, const DWord *avartars, void *pkReceiver=NULL)
bool TownServer::SendTC_ActiveAvatarNtf(int iNum, std::vector< DWord > &avartars, void *pkReceiver=NULL)
bool TownServer::SendTC_UserAlterNickNameAck(int iResult, void *pkReceiver=NULL)
bool TownServer::SendTC_UserAlterAvatarAndFrameNtf(DWord dwAvatarID, DWord dwAvatarFrameID, void *pkReceiver=NULL)
bool TownServer::SendTC_LadderDetailInfoAck(const SeLadderDetailInfo &info, void *pkReceiver=NULL)
bool TownServer::SendTC_AchieveInfoAck(int iNum1, const SeAchieveFinish *finishInfo, int iNum2, const SeAchieveSchedule *scheduleInfo, void *pkReceiver=NULL)
bool TownServer::SendTC_AchieveInfoAck(int iNum1, std::vector< SeAchieveFinish > &finishInfo, int iNum2, std::vector< SeAchieveSchedule > &scheduleInfo, void *pkReceiver=NULL)
bool TownServer::SendTCData(void *pkData, int iSize, void *pkReceiver)
bool TownServer::SendTM_Register(DWord dwTownMagic, DWord dwServerID, DWord dwAreaID, int iTownIndex, DWord dwDefaultMapID, int iMaxPlayerNum, int iRegisterCount, void *pkReceiver=NULL)
bool TownServer::SendTM_HeartPackage(int iPlayerConn, int iRaceConn, void *pkReceiver=NULL)
bool TownServer::SendTM_CommMatchMsg(DWord dwMatchSession, const SeCommMatchMsg &eMsg, DWord dwParam, int iParam, DWord dwParam2, void *pkReceiver=NULL)
bool TownServer::SendTM_ReconQuery(DWord dwRoomID, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iSeat, int iOffset, DWord dwFrame, void *pkReceiver=NULL)
bool TownServer::SendTM_ViewQuery(DWord dwSession, DWord dwDstPlayerID, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iViewDelay, void *pkReceiver=NULL)
bool TownServer::SendTM_QueryRaceRoomList(DWord dwPlayerID, DWord dwRoomSession, int iPage, DWord dwMapID, void *pkReceiver=NULL)
bool TownServer::SendTM_QueryRaceBetInfo(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTM_RaceBuyRet(DWord dwSession, bool bSuccess, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool TownServer::SendTM_PlayerLeave(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchCreateRoom(DWord dwPlayerID, const char *acName, DWord dwMapID, DWord dwCamp, int iDifficulty, bool bPlayBoss, bool bUseRobot, DWord dwGameMode, const char *strRoomName, const char *strPass, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchQueryRoomList(DWord dwPlayerID, int iCurPage, DWord dwMapID, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchRoomJoin(DWord dwPlayerID, const char *acName, DWord dwDstRoom, DWord dwCamp, int iseat, const char *strPass, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchRoomLeave(DWord dwPlayerID, DWord dwDstRoom, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchRoomReady(DWord dwPlayerID, DWord dwRoomID, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchRoomSwitchSeat(DWord dwPlayerID, DWord dwDstRoom, DWord dwCamp, int iseat, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchRoomKickSomeone(DWord dwPlayerID, DWord dwRoomID, DWord dwKickedPlayerID, int iseat, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchRoomInvite(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchRoomInviteRsp(DWord dwPlayerID, DWord dwRoomID, DWord dwInvitorID, const char *acName, void *pkReceiver=NULL)
bool TownServer::SendTM_ReqIncompleteRaceKDA(DWord dwRoomSession, DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTM_ReqIncompleteRaceList(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTM_ReconPLayerName(DWord dwPlayerID, DWord dwRoomSession, const char *acName, void *pkReceiver=NULL)
bool TownServer::SendTM_PlayerMatchCancel(DWord playerID, void *pkReceiver=NULL)
bool TownServer::SendTM_MatchConfirm(DWord PlayerID, DWord WaitID, bool BoolConfirm, void *pkReceiver=NULL)
bool TownServer::SendTM_PlayerMatchReq(DWord dwPlayerID, DWord MapID, Byte bySeats, DWord MemberNum, const DWord *IDArray, void *pkReceiver=NULL)
bool TownServer::SendTM_PlayerMatchReq(DWord dwPlayerID, DWord MapID, Byte bySeats, DWord MemberNum, std::vector< DWord > &IDArray, void *pkReceiver=NULL)
bool TownServer::SendTMData(void *pkData, int iSize, void *pkReceiver)
bool TownServer::SendTCPSvr(void *pkData, int iSize)
bool TownServer::SendTCPSvr_RegisterRet(SeRegisterRet eRet)
bool TownServer::SendTCPSvr_SeverDisconnect(DWord dwClientID)
bool TownServer::SendTCPSvr_SendData(DWord dwClientID, void *pkData, int iSize)
bool TownServer::SendTCPSvr_ConnectState(DWord dwClientID, DWord dwAccountID, int iReturn)
bool TownServer::SendTCPSvr_HeartPackageRet(void)
DWord TownServer::GetServerTime(void)
const SeDBTime& TownServer::GetWSTime()
DWord TownServer::GetServerID(void)
int TownServer::GetTownIndex(void)
DWord TownServer::GetWSRecvSize(void)
bool TownServer::IsWSRegistered(void)
void TownServer::SetWSReady(bool bReady)
bool TownServer::IsWSReady(void)
bool TownServer::IsMSReady(void)
void TownServer::SetReloadPlayerTime(DWord dwTime)
void TownServer::SetWSLoadTSReady(bool bReady)
void TownServer::DisconnectWS(void)
SeTCPUser* TownServer::GetTcpUserByID(DWord dwAccountID)
SeTCPUser* TownServer::GetTcpUser(DWord dwClientID)
int TownServer::GetTcpUserNum(void)
void TownServer::DisconnectTcpUser(SeTCPUser *pkUser, const char *pcFun, int iLine)
void TownServer::DisconnectTcpUser(DWord dwClientID, DWord dwAccountID, const char *pcFun, int iLine)
void TownServer::DisconnectTcpUser(DWord dwClientID, const char *acAccount, const char *pcFun, int iLine)
void TownServer::OnSendShowNoticeWithoutString(const SeNoticeCode eCode, DWord dwParam1, DWord dwClientID)
void TownServer::OnProcessCommMatchMsg(DWord dwSession, SeCommMatchMsg eMsg, DWord dwParam, int iParam, DWord dwParam2)
bool TownServer::ProcessWTData(void *pkData, int iSize, void *pkSender=NULL)
bool TownServer::PreProcessWT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_RegisterRet(SeWT_RegisterRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_HeartPackageRet(SeWT_HeartPackageRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_ShowNotice(SeWT_ShowNotice *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_IsReady(SeWT_IsReady *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_LoadPlayerInfoAgainRet(SeWT_LoadPlayerInfoAgainRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_PlayerValidateRet(SeWT_PlayerValidateRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_QueryNameRet(SeWT_QueryNameRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_CreateCharRet(SeWT_CreateCharRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_KickPlayer(SeWT_KickPlayer *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_PlayerLeave(SeWT_PlayerLeave *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_InitPlayerInfo(SeWT_InitPlayerInfo *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_ExchangeInit(SeWT_ExchangeInit *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_ItemExchangeRet(SeWT_ItemExchangeRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_QueryPlayerReconInfo(SeWT_QueryPlayerReconInfo *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_UpdateMisc(SeWT_UpdateMisc *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_TaskQueryListRet(SeWT_TaskQueryListRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_TaskReselRet(SeWT_TaskReselRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_ItemDel(SeWT_ItemDel *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_ReceiveMail(SeWT_ReceiveMail *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_UpdateMail(SeWT_UpdateMail *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_MailOprRet(SeWT_MailOprRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_PlayerRename(SeWT_PlayerRename *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_RaceBuyRet(SeWT_RaceBuyRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_QueryMapTaskListRet(SeWT_QueryMapTaskListRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_QueryNearestRaceInfoRet(SeWT_QueryNearestRaceInfoRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_GetRaceHistoryRet(SeWT_GetRaceHistoryRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_PlayerNewItem(SeWT_PlayerNewItem *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_PlayerOperRep(SeWT_PlayerOperRep *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_PlayerMoneyAndDiamond(SeWT_PlayerMoneyAndDiamond *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_ShopItemGmRep(SeWT_ShopItemGmRep *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_SearchUserArchivesInfoRes(SeWT_SearchUserArchivesInfoRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_SearchUserArchivesDetailInfoRes(SeWT_SearchUserArchivesDetailInfoRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_PlayerLadder(SeWT_PlayerLadder *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_EquipSchema(SeWT_EquipSchema *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_RoomInviteNotify(SeWT_RoomInviteNotify *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_FriendLadderInfoNtf(SeWT_FriendLadderInfoNtf *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_ActiveAvatarNtf(SeWT_ActiveAvatarNtf *pkData, int iSize, void *pkSender)
void TownServer::ProcessWT_UserHeroSync(SeWT_UserHeroSync *pkData, int iSize, void *pkSender)
bool TownServer::ProcessCTData(void *pkData, int iSize, void *pkSender=NULL)
bool TownServer::PreProcessCT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_PlayerValidate(SeCT_PlayerValidate *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_QueryName(SeCT_QueryName *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_CreateChar(SeCT_CreateChar *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_LeaveTown(SeCT_LeaveTown *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_PlayerGoDirect(SeCT_PlayerGoDirect *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RaceEndGuanka(SeCT_RaceEndGuanka *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ViewBegin(SeCT_ViewBegin *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_QueryRaceRoomList(SeCT_QueryRaceRoomList *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ItemExchange(SeCT_ItemExchange *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReconQuery(SeCT_ReconQuery *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_DelayCheck(SeCT_DelayCheck *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_TaskQueryList(SeCT_TaskQueryList *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_TaskResel(SeCT_TaskResel *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_GetTaskReward(SeCT_GetTaskReward *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_QueryRaceBetInfo(SeCT_QueryRaceBetInfo *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_DelReconInfo(SeCT_DelReconInfo *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_MailOpr(SeCT_MailOpr *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_PlayerRename(SeCT_PlayerRename *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_HeartBeat(SeCT_HeartBeat *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_MapTaskOpr(SeCT_MapTaskOpr *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_QueryNearestRaceInfo(SeCT_QueryNearestRaceInfo *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqIncompleteRaceList(SeCT_ReqIncompleteRaceList *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_CloseIncompleteRaceList(SeCT_CloseIncompleteRaceList *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqIncompleteRaceKDA(SeCT_ReqIncompleteRaceKDA *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_CreateRoom(SeCT_CreateRoom *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_QueryRoomList(SeCT_QueryRoomList *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RoomJoin(SeCT_RoomJoin *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RoomLeave(SeCT_RoomLeave *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RoomSwitchSeat(SeCT_RoomSwitchSeat *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RoomStart(SeCT_RoomStart *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RoomKickSomeone(SeCT_RoomKickSomeone *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RoomInvite(SeCT_RoomInvite *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RoomInviteRsp(SeCT_RoomInviteRsp *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_GetRaceHistory(SeCT_GetRaceHistory *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqAchievement(SeCT_ReqAchievement *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqView(SeCT_ReqView *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqAchievementCounts(SeCT_ReqAchievementCounts *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqViewList(SeCT_ReqViewList *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqItemStrenth(SeCT_ReqItemStrenth *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_RaceDetailInfoReq(SeCT_RaceDetailInfoReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqItemCiTiaoChange(SeCT_ReqItemCiTiaoChange *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ReqItemDepart(SeCT_ReqItemDepart *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_GMAddItem(SeCT_GMAddItem *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_DelelteItem(SeCT_DelelteItem *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_PutOnEquip(SeCT_PutOnEquip *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_TakeOffEquip(SeCT_TakeOffEquip *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_OpenRandBox(SeCT_OpenRandBox *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ClearItemNewFlag(SeCT_ClearItemNewFlag *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_BuyShopItem(SeCT_BuyShopItem *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_ShopItemGM(SeCT_ShopItemGM *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_GetItemGM(SeCT_GetItemGM *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_NexusFriendDetailInfoReq(SeCT_NexusFriendDetailInfoReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_NexusUserActionReq(SeCT_NexusUserActionReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_NexusUserPromotionReq(SeCT_NexusUserPromotionReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_SearchUserArchivesInfoReq(SeCT_SearchUserArchivesInfoReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_SearchUserArchivesDetailInfoReq(SeCT_SearchUserArchivesDetailInfoReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_NexusUserPromotionDetailInfoReq(SeCT_NexusUserPromotionDetailInfoReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_PlayerMatchReq(SeCT_PlayerMatchReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_PlayerMatchCancel(SeCT_PlayerMatchCancel *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_MatchConfirm(SeCT_MatchConfirm *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_SeUserRaceArenaDetailInfoReq(SeCT_SeUserRaceArenaDetailInfoReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserInviteReq(SeCT_UserInviteReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserConfirmInviteReq(SeCT_UserConfirmInviteReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserRefuseInviteReq(SeCT_UserRefuseInviteReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserLeaveTeamReq(SeCT_UserLeaveTeamReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_LeaderKickMemberReq(SeCT_LeaderKickMemberReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_LeaderDismissTeamReq(SeCT_LeaderDismissTeamReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_GMSetGold(SeCT_GMSetGold *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_GMSetDiamond(SeCT_GMSetDiamond *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_NexusFriendCleanRefuseNoticeReq(SeCT_NexusFriendCleanRefuseNoticeReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserStatusQueryReq(SeCT_UserStatusQueryReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_LadderRankQueryReq(SeCT_LadderRankQueryReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_FriendLadderInfoReq(SeCT_FriendLadderInfoReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserMapRaceHeroReq(SeCT_UserMapRaceHeroReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_SetActiveAvatarReq(SeCT_SetActiveAvatarReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserAlterNickNameReq(SeCT_UserAlterNickNameReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserAlterAvatarReq(SeCT_UserAlterAvatarReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserAlterAvatarFrameReq(SeCT_UserAlterAvatarFrameReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_UserPurchaseAvatarReq(SeCT_UserPurchaseAvatarReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_LadderDetailInfoReq(SeCT_LadderDetailInfoReq *pkData, int iSize, void *pkSender)
void TownServer::ProcessCT_AchieveInfoReq(SeCT_AchieveInfoReq *pkData, int iSize, void *pkSender)
bool TownServer::ProcessMTData(void *pkData, int iSize, void *pkSender=NULL)
bool TownServer::PreProcessMT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_RegisterRet(SeMT_RegisterRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_HeartPackageRet(SeMT_HeartPackageRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_StartMatchRet(SeMT_StartMatchRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_CancelMatchRet(SeMT_CancelMatchRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchSessionNotify(SeMT_MatchSessionNotify *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_CommMatchMsg(SeMT_CommMatchMsg *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_NotifyAddrToMatch(SeMT_NotifyAddrToMatch *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_UpdateMisc(SeMT_UpdateMisc *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_RaceEndSend(SeMT_RaceEndSend *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_GuanqiaEndSend(SeMT_GuanqiaEndSend *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_ReconQueryFail(SeMT_ReconQueryFail *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_ViewQueryFail(SeMT_ViewQueryFail *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_QueryRaceRoomListRet(SeMT_QueryRaceRoomListRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_BiVoiceEnterInfo(SeMT_BiVoiceEnterInfo *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_AskEnterWaitRace(SeMT_AskEnterWaitRace *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_GetRaceCardInfo(SeMT_GetRaceCardInfo *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchRaceLoad(SeMT_MatchRaceLoad *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_QueryRaceBetInfoRet(SeMT_QueryRaceBetInfoRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_RaceBuy(SeMT_RaceBuy *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchCreateRoomRet(SeMT_MatchCreateRoomRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchQueryRoomListRet(SeMT_MatchQueryRoomListRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchRoomJoinRet(SeMT_MatchRoomJoinRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchRoomMemberNotifyRet(SeMT_MatchRoomMemberNotifyRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchRoomLeaveRet(SeMT_MatchRoomLeaveRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchRoomReadyRet(SeMT_MatchRoomReadyRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchRoomSwitchSeatRet(SeMT_MatchRoomSwitchSeatRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchRoomKickSomeoneRet(SeMT_MatchRoomKickSomeoneRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_AddIncompleteRace(SeMT_AddIncompleteRace *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_RemoveIncompleteRace(SeMT_RemoveIncompleteRace *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_ResIncmpRaceSeatBaseInfo(SeMT_ResIncmpRaceSeatBaseInfo *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_ResIncompleteRaceList(SeMT_ResIncompleteRaceList *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_ReqMatchRep(SeMT_ReqMatchRep *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_MatchCancelRep(SeMT_MatchCancelRep *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_NotiMatcherPre(SeMT_NotiMatcherPre *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_NotiMatcherResult(SeMT_NotiMatcherResult *pkData, int iSize, void *pkSender)
void TownServer::ProcessMT_SingleMatchConfirm(SeMT_SingleMatchConfirm *pkData, int iSize, void *pkSender)
void TownServer::ProcessTCPSvr(void *pkData, int iSize)
void TownServer::ProcessTCPSvr_Register(void *pkData, int iSize)
void TownServer::ProcessTCPSvr_ClientConnect(void *pkData, int iSize)
void TownServer::ProcessTCPSvr_ClientDisconnect(void *pkData, int iSize)
void TownServer::ProcessTCPSvr_RecvData(void *pkData, int iSize)
void TownServer::ProcessTCPSvr_HeartPackage(void *pkData, int iSize)
void TownServer::ProcessTCPSvr_ReLoadReadyID(void *pkData, int iSize)
bool TownServer::ProcessWCMSTData(void *pkData, int iSize, void *pkSender=NULL)
bool TownServer::PreProcessWCMST(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessWCMST_RegisterRet(SeWCMST_RegisterRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWCMST_HeartPackageRet(SeWCMST_HeartPackageRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessWCMST_ResView(SeWCMST_ResView *pkData, int iSize, void *pkSender)
void TownServer::ProcessWCMST_ResViewList(SeWCMST_ResViewList *pkData, int iSize, void *pkSender)
void TownServer::ProcessWCMST_ResRaceDetailInfo(SeWCMST_ResRaceDetailInfo *pkData, int iSize, void *pkSender)
bool TownServer::SendTWCMS_Register(DWord dwServerID, DWord dwAreaID, void *pkReceiver=NULL)
bool TownServer::SendTWCMS_HeartPackage(void *pkReceiver=NULL)
bool TownServer::SendTWCMS_ReqView(DWord dwPlayerID, const Byte *rID, void *pkReceiver=NULL)
bool TownServer::SendTWCMS_ReqView(DWord dwPlayerID, std::vector< Byte > &rID, void *pkReceiver=NULL)
bool TownServer::SendTWCMS_ReqViewList(DWord dwPlayerID, int iPage, void *pkReceiver=NULL)
bool TownServer::SendTWCMS_RaceDetailInfoReq(DWord dwPlayerID, int page_number, int page_counts, void *pkReceiver=NULL)
bool TownServer::SendTWCMSData(void *pkData, int iSize, void *pkReceiver)
bool TownServer::SendTN_Register(DWord dwServerID, DWord dwAreaID, void *pkReceiver=NULL)
bool TownServer::SendTN_HeartPackage(void *pkReceiver=NULL)
bool TownServer::SendTN_RoomInviteNotifyVerify(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTN_NexusFriendDetailInfoReq(DWord dwPlayerID, int page_number, int page_counts, void *pkReceiver=NULL)
bool TownServer::SendTN_NexusUserActionReq(DWord dwPlayerID, DWord dwPlayerOnlineID, const SeNexusUserInfo &nexus_user_actions, void *pkReceiver=NULL)
bool TownServer::SendTN_NexusLinkUserSync(DWord dwPlayerID, DWord dwStateID, DWord dwLoginTime, void *pkReceiver=NULL)
bool TownServer::SendTN_CreateUserSync(DWord dwPlayerID, DWord dwLoginTime, const char *acRemoteIp, void *pkReceiver=NULL)
bool TownServer::SendTN_UserInviteReq(DWord dwPlayerID, const char *acUserName, DWord dwGuestID, const char *acGuestName, void *pkReceiver=NULL)
bool TownServer::SendTN_UserConfirmInviteReq(DWord dwPlayerID, DWord dwTeamID, void *pkReceiver=NULL)
bool TownServer::SendTN_UserRefuseInviteReq(DWord dwPlayerID, DWord dwTeamID, void *pkReceiver=NULL)
bool TownServer::SendTN_UserLeaveTeamReq(DWord dwPlayerID, DWord dwTeamID, void *pkReceiver=NULL)
bool TownServer::SendTN_LeaderKickMemberReq(DWord dwPlayerID, DWord dwTeamID, DWord dwMemberID, void *pkReceiver=NULL)
bool TownServer::SendTN_LeaderDismissTeamReq(DWord dwPlayerID, DWord dwTeamID, void *pkReceiver=NULL)
bool TownServer::SendTN_MatchTeamMemberReq(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTN_NexusFriendCleanRefuseNoticeReq(DWord dwPlayerID, DWord guest_id, void *pkReceiver=NULL)
bool TownServer::SendTN_UserStatusQueryReq(DWord dwPlayerID, DWord num, const DWord *user_ids, void *pkReceiver=NULL)
bool TownServer::SendTN_UserStatusQueryReq(DWord dwPlayerID, DWord num, std::vector< DWord > &user_ids, void *pkReceiver=NULL)
bool TownServer::SendTN_UserAttrInfoSync(DWord dwPlayerID, const SeUserBaseAttrInfo &user_attr, void *pkReceiver=NULL)
bool TownServer::SendTNData(void *pkData, int iSize, void *pkReceiver)
bool TownServer::ProcessNTData(void *pkData, int iSize, void *pkSender=NULL)
bool TownServer::PreProcessNT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_RegisterRet(SeNT_RegisterRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_HeartPackageRet(SeNT_HeartPackageRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_NexusFriendDetailInfoRes(SeNT_NexusFriendDetailInfoRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_NexusUserActionSync(SeNT_NexusUserActionSync *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_TeamChangeSync(SeNT_TeamChangeSync *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_TeamLeaderSync(SeNT_TeamLeaderSync *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_TeamMemberSync(SeNT_TeamMemberSync *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_TeamUserStateRes(SeNT_TeamUserStateRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_TeamMemberInfoRes(SeNT_TeamMemberInfoRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_NexusFriendStatusSync(SeNT_NexusFriendStatusSync *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_NexusFriendLimitRes(SeNT_NexusFriendLimitRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_MatchTeamMemberRes(SeNT_MatchTeamMemberRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_NexusFriendCleanRefuseNoticeRes(SeNT_NexusFriendCleanRefuseNoticeRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_UserStatusQueryRes(SeNT_UserStatusQueryRes *pkData, int iSize, void *pkSender)
void TownServer::ProcessNT_RoomInviteNotifyVerifyRsp(SeNT_RoomInviteNotifyVerifyRsp *pkData, int iSize, void *pkSender)
bool TownServer::SendTBL_GMSetGold(DWord dwPlayerID, DWord dwGold, void *pkReceiver=NULL)
bool TownServer::SendTBL_GMSetDiamond(DWord dwPlayerID, DWord dwDiamond, void *pkReceiver=NULL)
bool TownServer::SendTBL_ReqItemStrenth(DWord dwPlayerID, Word wPos, int iNum, const Word *SrcPosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_ReqItemStrenth(DWord dwPlayerID, Word wPos, int iNum, std::vector< Word > &SrcPosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_ReqItemCiTiaoChange(DWord dwPlayerID, Word wPos, Word wIndex, Byte BolLock, int iNum, const Word *SrcPosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_ReqItemCiTiaoChange(DWord dwPlayerID, Word wPos, Word wIndex, Byte BolLock, int iNum, std::vector< Word > &SrcPosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_ReqItemDepart(DWord dwPlayerID, Word wPos, void *pkReceiver=NULL)
bool TownServer::SendTBL_GMAddItem(DWord dwPlayerID, DWord ItemID, int Num, int Level, void *pkReceiver=NULL)
bool TownServer::SendTBL_DelelteItem(DWord dwPlayerID, Word wPos, void *pkReceiver=NULL)
bool TownServer::SendTBL_PutOnEquip(DWord dwPlayerID, Word wPos, Word PutPos, void *pkReceiver=NULL)
bool TownServer::SendTBL_TakeOffEquip(DWord dwPlayerID, Word wPos, void *pkReceiver=NULL)
bool TownServer::SendTBL_OpenRandBox(DWord dwPlayerID, Word wPos, void *pkReceiver=NULL)
bool TownServer::SendTBL_ClearItemNewFlag(DWord dwPlayerID, int iNum, const Word *PosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_ClearItemNewFlag(DWord dwPlayerID, int iNum, std::vector< Word > &PosArray, void *pkReceiver=NULL)
bool TownServer::SendTBL_LadderRankQueryReq(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTBL_FriendLadderInfoReq(DWord dwPlayerID, DWord dwFriendID, void *pkReceiver=NULL)
bool TownServer::SendTBL_UserMapRaceHeroReq(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTBL_SetActiveAvatarReq(DWord dwPlayerID, bool bActive, DWord dwItemID, void *pkReceiver=NULL)
bool TownServer::SendTBL_UserAlterNickNameReq(DWord dwPlayerID, const char *acNickName, void *pkReceiver=NULL)
bool TownServer::SendTBL_UserAlterAvatarReq(DWord dwPlayerID, DWord dwAvatarID, void *pkReceiver=NULL)
bool TownServer::SendTBL_UserAlterAvatarFrameReq(DWord dwPlayerID, DWord dwAvatarFrameID, void *pkReceiver=NULL)
bool TownServer::SendTBL_UserPurchaseAvatarReq(DWord dwPlayerID, DWord dwAvatarID, void *pkReceiver=NULL)
bool TownServer::SendTBL_UserRaceMapDetailReq(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTBL_LadderDetailInfoReq(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTBL_AchieveInfoReq(DWord dwPlayerID, void *pkReceiver=NULL)
bool TownServer::SendTBLData(void *pkData, int iSize, void *pkReceiver)
bool TownServer::ProcessBLTData(void *pkData, int iSize, void *pkSender=NULL)
bool TownServer::PreProcessBLT(void *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_PlayerOperRep(SeBLT_PlayerOperRep *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_OpenRandBoxRet(SeBLT_OpenRandBoxRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_PutOnEquipRet(SeBLT_PutOnEquipRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_TakeOffEquipRet(SeBLT_TakeOffEquipRet *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_LadderRankQueryAck(SeBLT_LadderRankQueryAck *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_UserRaceHeroAck(SeBLT_UserRaceHeroAck *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_SetActiveAvatarAck(SeBLT_SetActiveAvatarAck *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_UserAlterNickNameAck(SeBLT_UserAlterNickNameAck *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_UserAlterAvatarAndFrameNtf(SeBLT_UserAlterAvatarAndFrameNtf *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_UserRaceArenaDetailAck(SeBLT_UserRaceArenaDetailAck *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_LadderDetailInfoAck(SeBLT_LadderDetailInfoAck *pkData, int iSize, void *pkSender)
void TownServer::ProcessBLT_AchieveInfoAck(SeBLT_AchieveInfoAck *pkData, int iSize, void *pkSender)
bool TownServer::LoadConfig(const char *pcFile)
References SeTownConfig::acRaceRecordURLBase, SeTownConfig::dwServerID, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeTownConfig::iDebugLevel, SeTownConfig::iTownIndex, SeTownConfig::kAddrToPlayer, SeTownConfig::kAddrToServer, SeConfig::Load, m_bShowFullCheckInfo, m_kConfig, MAX_DEBUG_LEVEL, SeLogError, SeLogInfo, StrCpy.
Referenced by Initialize.
bool TownServer::LoadServerAddr(const char *pcFile)
References SeConfig::GetNetAddr, SeNetAddr::IsEmpty, SeTownConfig::kAddrWCMSServer, SeTownConfig::kMatchServer, SeTownConfig::kNexusServer, SeServerData::kSock, SeTownConfig::kWorldServer, SeConfig::Load, m_kConfig, m_kMSData, m_kNetMgr, m_kNSData, m_kWCSData, m_kWSData, SeLogError, SeLogInfo.
Referenced by Initialize.
bool TownServer::LoadGameSetup(const char *pcFile)
References SeTownConfig::bShowDisconnectLog, SeTownConfig::dwHeartPackageTime, SeTownConfig::dwPrintUpdateTime, SeConfig::GetValue, SeTownConfig::iDebugLevel, SeTownConfig::iSameIPConnect, SeConfig::Load, m_kConfig, SeLogError, SeLogInfo, SSD_MAX_HEART_PACKAGE_TIME.
Referenced by Initialize, ReLoadTownSetup.
bool TownServer::ReLoadTownSetup(void)
References LoadGameSetup.
Referenced by ExecuteAction.
bool TownServer::InitializeNet(void)
References SeNetAddr::acIP, SeNetAddr::iPort, SeTownConfig::kAddrToPlayer, SeTownConfig::kAddrToServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo, SERVER_BUFFER_SIZE.
Referenced by Initialize.
void TownServer::UpdateHeartPackage(void)
References GetServerTime, UpdateMSHeartPackage, UpdateNSHeartPackage, UpdateWCSHeartPackage, UpdateWSHeartPackage.
Referenced by Update.
void TownServer::UpdateWSHeartPackage(void)
References DisconnectWS, SeServerData::dwHeartPackageTime, SeTownConfig::dwHeartPackageTime, GetServerTime, SeServerData::kSock, m_kConfig, m_kWSData, SeLogError, SendTW_HeartPackage.
Referenced by UpdateHeartPackage.
void TownServer::UpdateMSHeartPackage(void)
References SeServerData::bRegistered, SeServerData::dwHeartPackageTime, SeTownConfig::dwHeartPackageTime, GetServerTime, GetTcpUserNum, SeServerData::kSock, m_kConfig, m_kMSData, m_kNetMgr, SeLogError, SendTM_HeartPackage.
Referenced by UpdateHeartPackage.
void TownServer::UpdateNSHeartPackage(void)
References SeServerData::bRegistered, SeServerData::dwHeartPackageTime, SeTownConfig::dwHeartPackageTime, GetServerTime, SeServerData::kSock, m_kConfig, m_kNetMgr, m_kNSData, SeLogError, SendTN_HeartPackage.
Referenced by UpdateHeartPackage.
void TownServer::UpdatePrintfNetState(void)
void TownServer::UpdateWCSHeartPackage(void)
References SeServerData::bRegistered, SeServerData::dwHeartPackageTime, SeTownConfig::dwHeartPackageTime, GetServerTime, SeServerData::kSock, m_kConfig, m_kNetMgr, m_kWCSData, SeLogError, SendTWCMS_HeartPackage.
Referenced by UpdateHeartPackage.
void TownServer::UpdateState(void)
References SeTCPSvrData::bRegister, SeServerData::bRegistered, ConnectToMS, ConnectToNS, ConnectToWS, ConnectWCS, GetServerTime, SeNetAddr::iPort, SeTownConfig::kAddrWCMSServer, SeTownConfig::kMatchServer, SeTownConfig::kNexusServer, SeServerData::kSock, m_kConfig, m_kMSData, m_kNSData, m_kTCPSvrData, m_kWCSData, m_kWSData, RegisterToMS, RegisterToNS, RegisterToWCS, RegisterToWS.
Referenced by Update.
void TownServer::UpdateLogSta(void)
void TownServer::ConnectToWS(void)
References SeNetAddr::acIP, SeServerData::bConnecting, SeNetAddr::iPort, SeTownConfig::kWorldServer, m_kConfig, m_kNetMgr, m_kWSData, SeLogError, SERVER_BUFFER_SIZE.
Referenced by UpdateState.
void TownServer::RegisterToWS(void)
References SeNetAddr::acIP, SeServerData::dwRegisterTime, SeTownConfig::dwServerID, SeNetAddr::iPort, SeTownInfo::kAddrToPlayer, SeTCPSvrData::kTCPAddr, m_dwCurTime, m_kConfig, m_kTCPSvrData, m_kWSData, RECONNECT_TIME, SeLogError, SeLogInfo, SendTW_Register, SSD_MSANGO_MAGIC.
Referenced by UpdateState.
void TownServer::ConnectToMS(void)
References SeNetAddr::acIP, SeServerData::bConnecting, SeNetAddr::iPort, SeTownConfig::kMatchServer, m_kConfig, m_kMSData, m_kNetMgr, SeLogError, SERVER_BUFFER_SIZE.
Referenced by UpdateState.
void TownServer::RegisterToMS(void)
References SeServerData::dwRegisterTime, SeTownConfig::dwServerID, SeTownConfig::iMaxNormalPlayerNum, SeTownConfig::iTownIndex, m_dwCurTime, m_iRegisterCount, m_kConfig, m_kMSData, SeLogInfo, SendTM_Register, SSD_MSANGO_MAGIC.
Referenced by UpdateState.
void TownServer::ConnectToCS(void)
void TownServer::ConnectToNS(void)
References SeNetAddr::acIP, SeServerData::bConnecting, SeNetAddr::iPort, SeTownConfig::kNexusServer, m_kConfig, m_kNetMgr, m_kNSData, SeLogError, SERVER_BUFFER_SIZE.
Referenced by UpdateState.
void TownServer::RegisterToNS(void)
References SeServerData::dwRegisterTime, SeTownConfig::dwServerID, m_dwCurTime, m_kConfig, m_kNSData, SeLogInfo, SendTN_Register.
Referenced by UpdateState.
void TownServer::ConnectWCS()
References SeNetAddr::acIP, SeServerData::bConnecting, SeNetAddr::iPort, SeTownConfig::kAddrWCMSServer, m_kConfig, m_kNetMgr, m_kWCSData, SeLogError, SERVER_BUFFER_SIZE.
Referenced by UpdateState.
void TownServer::RegisterToWCS()
References SeServerData::dwRegisterTime, SeTownConfig::dwServerID, m_dwCurTime, m_kConfig, m_kWCSData, SeLogInfo, SendTWCMS_Register.
Referenced by UpdateState.
void TownServer::OnTCPSvrDisconnect()
References SePlayerMgr::DelPlayer, SeTCPUser::dwPlayerID, g_kPlayerMgr, SePlayerMgr::GetPlayerByID, SeServerData::kSock, m_kAllTcpUser, m_kMSData, m_kNetMgr, m_kNSData, m_kWCSData, m_kWSData, SeLogError, SeLogInfo, SendTW_PlayerLeave.
Referenced by OnNetDisconnect.
bool TownServer::LoadConfig(const char *pcFile)
bool TownServer::LoadServerAddr(const char *pcFile)
bool TownServer::LoadGameSetup(const char *pcFile)
bool TownServer::ReLoadTownSetup(void)
bool TownServer::InitializeNet(void)
void TownServer::UpdateHeartPackage(void)
void TownServer::UpdateWSHeartPackage(void)
void TownServer::UpdateMSHeartPackage(void)
void TownServer::UpdateNSHeartPackage(void)
void TownServer::UpdatePrintfNetState(void)
void TownServer::UpdateWCSHeartPackage(void)
void TownServer::UpdateState(void)
void TownServer::UpdateLogSta(void)
void TownServer::ConnectToWS(void)
void TownServer::RegisterToWS(void)
void TownServer::ConnectToMS(void)
void TownServer::RegisterToMS(void)
void TownServer::ConnectToCS(void)
void TownServer::ConnectToNS(void)
void TownServer::RegisterToNS(void)
void TownServer::ConnectWCS()
void TownServer::RegisterToWCS()
void TownServer::OnTCPSvrDisconnect()