MapShopResTableMgr
std::map<unsigned int,MapShopResTable*> MapShopResTableMgr::m_kMapShopResTableMap
Referenced by FillData, GetMapShopResTable, GetMapShopResTableMap, GetMapShopResTableVec, ~MapShopResTableMgr.
MapShopResTableMgr * MapShopResTableMgr::m_pkMapShopResTableMgr
Referenced by Get, ReLoad.
MapShopResTableMgr * MapShopResTableMgr::Get()
References m_pkMapShopResTableMgr, MapShopResTableMgr.
Referenced by GlobalTableMgr::GetMapShopResTable, TableMgr::LoadTable, ReLoad.
MapShopResTableMgr * MapShopResTableMgr::ReLoad()
References Get, m_pkMapShopResTableMgr.
Referenced by TableMgr::ReloadTable.
MapShopResTableMgr::MapShopResTableMgr()
References Load.
Referenced by Get.
MapShopResTableMgr::~MapShopResTableMgr()
References m_kMapShopResTableMap.
const MapShopResTable * MapShopResTableMgr::GetMapShopResTable(unsigned int iTypeID)
References m_kMapShopResTableMap.
Referenced by GlobalTableMgr::GetMapShopResTable.
const std::map< unsigned int, MapShopResTable * > & MapShopResTableMgr::GetMapShopResTableMap()
References m_kMapShopResTableMap.
TableResArray MapShopResTableMgr::GetMapShopResTableVec()
References m_kMapShopResTableMap, TableResArray::pushBack.
bool MapShopResTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by MapShopResTableMgr.
void MapShopResTableMgr::FillData(MapShopResTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, m_kMapShopResTableMap, MapShopResTable::uiPos, MapShopResTable::uiSH01, MapShopResTable::uiSH02.
Referenced by Load.