TownItemTableMgr
std::map<unsigned int,TownItemTable*> TownItemTableMgr::m_kTownItemTableMap
Referenced by FillData, GetTownItemTable, GetTownItemTableMap, GetTownItemTableVec, ~TownItemTableMgr.
TownItemTableMgr * TownItemTableMgr::m_pkTownItemTableMgr
Referenced by Get, ReLoad.
TownItemTableMgr * TownItemTableMgr::Get()
References m_pkTownItemTableMgr, TownItemTableMgr.
Referenced by CItemMgr::AddItem, CItemMgr::AddNewMultiItem, CShop::BuyItem, CItemMgr::ChangeCiTiao, CItemMgr::CountNeedSlotNumByItemID, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold, CItemMgr::decRespawnItem, GenerateAddedAttr, GenerateAddedSkill, CItemMgr::GetExistItemIndex, CItemMgr::getRespawnItemCount, CItemMgr::getSelectableAvatars, GlobalTableMgr::GetTownItemTable, CShop::GMModiItem, HeroMgr::isValidAvatar, EquipSchemaMgr::isValidEquip, CItemMgr::ItemDepart, CItem::loadData, CItemMgr::loadData, TableMgr::LoadTable, SePlayer::OnUseItem, CItemMgr::openRandBox, BlockServer::ProcessWBL_UserAlterNickNameReq, ReLoad, CItem::saveData, CItemMgr::StrenthEquip.
TownItemTableMgr * TownItemTableMgr::ReLoad()
References Get, m_pkTownItemTableMgr.
Referenced by TableMgr::ReloadTable.
TownItemTableMgr::TownItemTableMgr()
References Load.
Referenced by Get.
TownItemTableMgr::~TownItemTableMgr()
References m_kTownItemTableMap.
const TownItemTable * TownItemTableMgr::GetTownItemTable(unsigned int iTypeID)
References m_kTownItemTableMap.
Referenced by CItemMgr::AddItem, CItemMgr::AddNewMultiItem, CShop::BuyItem, CItemMgr::ChangeCiTiao, CItemMgr::CountNeedSlotNumByItemID, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold, CItemMgr::decRespawnItem, GenerateAddedAttr, GenerateAddedSkill, CItemMgr::GetExistItemIndex, CItemMgr::getRespawnItemCount, CItemMgr::getSelectableAvatars, GlobalTableMgr::GetTownItemTable, CShop::GMModiItem, HeroMgr::isValidAvatar, EquipSchemaMgr::isValidEquip, CItemMgr::ItemDepart, CItem::loadData, CItemMgr::loadData, SePlayer::OnUseItem, CItemMgr::openRandBox, BlockServer::ProcessWBL_UserAlterNickNameReq, CItem::saveData, CItemMgr::StrenthEquip.
const std::map< unsigned int, TownItemTable * > & TownItemTableMgr::GetTownItemTableMap()
References m_kTownItemTableMap.
TableResArray TownItemTableMgr::GetTownItemTableVec()
References m_kTownItemTableMap, TableResArray::pushBack.
bool TownItemTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by TownItemTableMgr.
void TownItemTableMgr::FillData(TownItemTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, TownItemTable::fEquipmentlevel, TownItemTable::fRemarks, TownItemTable::iBaseDissolveValue, TownItemTable::iCanUseDay, TownItemTable::iitemlevel, TownItemTable::iitemlevelmax, TownItemTable::iitemlevelmin, TownItemTable::iitemMaxLevel, TownItemTable::iMagnification, TownItemTable::iNeedLevel, TownItemTable::iPackage, TownItemTable::iPileCount, TownItemTable::iPower, TownItemTable::kAttachModel1, TownItemTable::kAttachModel2, TownItemTable::kBigIcon, TownItemTable::kchapter, TownItemTable::kDesc, TownItemTable::kDescID, TownItemTable::kIcon, TownItemTable::kItemModel, TownItemTable::kName, TownItemTable::kNameID, TownItemTable::kPVEValueA, TownItemTable::kPVEValueB, TownItemTable::kPVEValueC, TownItemTable::kPVEValueD, TownItemTable::kPVEValueE, TownItemTable::kPVEValueF, TownItemTable::kPVEValueG, TownItemTable::kPVEValueH, TownItemTable::kPVPValueA, TownItemTable::kPVPValueB, TownItemTable::kPVPValueC, TownItemTable::kPVPValueD, TownItemTable::kPVPValueE, TownItemTable::kPVPValueF, TownItemTable::kPVPValueG, TownItemTable::kPVPValueH, TownItemTable::ktaozhuangID, m_kTownItemTableMap, TownItemTable::uicitiao1, TownItemTable::uicitiao2, TownItemTable::uicitiao3, TownItemTable::uicitiao4, TownItemTable::uicitiao5, TownItemTable::uiClass, TownItemTable::uiItemID, TownItemTable::uiLevel, TownItemTable::uiProperty, TownItemTable::uiPVEDataA, TownItemTable::uiPVEDataB, TownItemTable::uiPVEDataC, TownItemTable::uiPVEDataD, TownItemTable::uiPVEDataE, TownItemTable::uiPVEDataF, TownItemTable::uiPVEDataG, TownItemTable::uiPVEDataH, TownItemTable::uiPVPDataA, TownItemTable::uiPVPDataB, TownItemTable::uiPVPDataC, TownItemTable::uiPVPDataD, TownItemTable::uiPVPDataE, TownItemTable::uiPVPDataF, TownItemTable::uiPVPDataG, TownItemTable::uiPVPDataH, TownItemTable::uiSubClass, TownItemTable::uiTypeID, TownItemTable::uiWeaponClass.
Referenced by Load.