MatchPrepareMgr
typedef std::map<DWord, PrepareItem *> MatchPrepareMgr::PLAYERMAP
typedef std::multimap<moba::TimeType, PrepareItem *> MatchPrepareMgr::TIMEMAP
typedef std::map<DWord, PrepareItem *> MatchPrepareMgr::PLAYERMAP
typedef std::multimap<moba::TimeType, PrepareItem *> MatchPrepareMgr::TIMEMAP
PLAYERMAP MatchPrepareMgr::m_players
Referenced by clearItem, collectData, onDataResult, OnPlayerLeave.
TIMEMAP MatchPrepareMgr::m_timeMap
Referenced by clearItem, collectData, update.
MatchPrepareMgr::MatchPrepareMgr()
MatchPrepareMgr::~MatchPrepareMgr()
MatchReqResult MatchPrepareMgr::collectData(DWord dwMapID, DWord dwPlayerID, int num, DWord *players, Byte bySeats, const HSock &townSock)
References MatchPrepareMgr::PrepareItem::bySeats, MatchPrepareMgr::PrepareItem::dwMapID, MatchPrepareMgr::PrepareItem::dwPlayreID, EMT_PVE, g_kMatchBanMgr, MapInfoTableMgr::Get, moba::Clock::getInstance, MapInfoTableMgr::GetMapInfoTable, MatchBanMgr::isPlayerBanned, MatchPrepareMgr::PrepareItem::itTime, m_players, m_timeMap, MatchPrepareMgr::PrepareItem::players, ReqResultBanned, ReqResultInnerError, ReqResultLoading, ReqResultSuccess, ReqResultWrongNum, TIMEOUT, MatchPrepareMgr::PrepareItem::townSock, MapInfoTable::uiMatchType.
Referenced by MatchServer::ProcessTM_PlayerMatchReq.
void MatchPrepareMgr::onDataResult(SeBLM_GetPlayerMatchValueRet *pkData)
References MatchPrepareMgr::PrepareItem::bySeats, clearItem, MatchPrepareMgr::PrepareItem::dwMapID, MatchValueStru::dwPlayerID, MatchPrepareMgr::PrepareItem::dwPlayreID, g_kMatchMgr, g_kMatchServer, g_kTownMgr, SeTownMgr::GetTownSockBySign, m_players, SeBLM_GetPlayerMatchValueRet::matchValue, MatchPrepareMgr::PrepareItem::matchValues, SeMatchMgr::OnMatchReq, MatchPrepareMgr::PrepareItem::players, ReqResultSuccess, ReqResultTimeout, SeBLM_GetPlayerMatchValueRet::result, MatchServer::SendMT_ReqMatchRep, SeBLM_GetPlayerMatchValueRet::town, MatchPrepareMgr::PrepareItem::towns.
Referenced by MatchServer::ProcessBLM_GetPlayerMatchValueRet.
void MatchPrepareMgr::update()
References clearItem, MatchPrepareMgr::PrepareItem::dwPlayreID, g_kMatchServer, moba::Clock::getInstance, moba::Clock::getMilliSeconds, m_timeMap, ReqResultTimeout, MatchServer::SendMT_ReqMatchRep.
Referenced by MatchServer::Update.
void MatchPrepareMgr::OnPlayerLeave(DWord dwPlayerID)
References clearItem, MatchPrepareMgr::PrepareItem::dwPlayreID, g_kMatchServer, m_players, ReqResultOffline, MatchServer::SendMT_ReqMatchRep.
Referenced by MatchServer::ProcessTM_PlayerLeave.
MatchPrepareMgr::MatchPrepareMgr()
MatchPrepareMgr::~MatchPrepareMgr()
MatchReqResult MatchPrepareMgr::collectData(DWord dwMapID, DWord dwPlayerID, int num, DWord *players, Byte bySeats, const HSock &townSock)
void MatchPrepareMgr::onDataResult(SeBLM_GetPlayerMatchValueRet *pkData)
void MatchPrepareMgr::update()
void MatchPrepareMgr::OnPlayerLeave(DWord dwPlayerID)
void MatchPrepareMgr::clearItem(PrepareItem *item)
References MatchPrepareMgr::PrepareItem::itTime, m_players, m_timeMap, MatchPrepareMgr::PrepareItem::players.
Referenced by onDataResult, OnPlayerLeave, update.
void MatchPrepareMgr::clearItem(PrepareItem *item)