SeXmlAttribute
friend class SeXmlAttributeSet
SeXmlDocument* SeXmlAttribute::document
Referenced by Parse, SetDocument, SeXmlAttribute.
SeXml_STRING SeXmlAttribute::name
Referenced by Name, NameTStr, Next, operator<, operator==, operator>, Parse, Previous, Print, SetName, SeXmlAttribute.
SeXml_STRING SeXmlAttribute::value
Referenced by DoubleValue, IntValue, Next, Parse, Previous, Print, QueryDoubleValue, QueryIntValue, SetValue, SeXmlAttribute, Value, ValueStr.
SeXmlAttribute* SeXmlAttribute::prev
Referenced by SeXmlAttributeSet::Add, SeXmlAttributeSet::Last, Previous, SeXmlAttributeSet::Remove, SeXmlAttribute, SeXmlAttributeSet::SeXmlAttributeSet, SeXmlAttributeSet::~SeXmlAttributeSet.
SeXmlAttribute* SeXmlAttribute::next
Referenced by SeXmlAttributeSet::Add, SeXmlAttributeSet::Find, SeXmlAttributeSet::First, Next, SeXmlAttributeSet::Remove, SeXmlAttribute, SeXmlAttributeSet::SeXmlAttributeSet, SeXmlAttributeSet::~SeXmlAttributeSet.
SeXmlAttribute::SeXmlAttribute()
Construct an empty attribute.
References document, next, prev.
SeXmlAttribute::SeXmlAttribute(const std::string &_name, const std::string &_value)
std::string constructor.
References document, name, next, prev, value.
SeXmlAttribute::SeXmlAttribute(const char *_name, const char *_value)
Construct an attribute with a name and value.
References document, name, next, prev, value.
const char* SeXmlAttribute::Name() const
Return the name of this attribute.
References name.
Referenced by SeXmlAttributeSet::Add, SeXmlElement::CopyTo, SeXmlHandle::CreatePath, SeXmlHandle::GetPath.
const char* SeXmlAttribute::Value() const
Return the value of this attribute.
References value.
Referenced by SeXmlElement::Attribute, SeXmlElement::CopyTo, SeXmlHandle::CreatePath, SeXmlHandle::GetPath, SeXmlDeclaration::Parse, SeXmlElement::QueryBoolAttribute.
const std::string& SeXmlAttribute::ValueStr() const
Return the value of this attribute.
References value.
Referenced by SeXmlElement::Attribute, SeXmlElement::QueryValueAttribute.
int SeXmlAttribute::IntValue() const
Return the value of this attribute, converted to an integer.
References value.
double SeXmlAttribute::DoubleValue() const
Return the value of this attribute, converted to a double.
References value.
const SeXml_STRING& SeXmlAttribute::NameTStr() const
References name.
Referenced by SeXmlElement::Parse.
int SeXmlAttribute::QueryIntValue(int *_value) const
QueryIntValue examines the value string. It is an alternative to the IntValue() method with richer error checking. If the value is an integer, it is stored in 'value' and the call returns SeXml_SUCCESS. If it is not an integer, it returns SeXml_WRONG_TYPE.A specialized but useful call. Note that for success it returns 0, which is the opposite of almost all other SeXml calls.
References SeXml_SSCANF, SeXml_SUCCESS, SeXml_WRONG_TYPE, value.
Referenced by SeXmlElement::Attribute, SeXmlElement::QueryIntAttribute, SeXmlElement::QueryUnsignedAttribute.
int SeXmlAttribute::QueryDoubleValue(double *_value) const
QueryDoubleValue examines the value string. See QueryIntValue().
References SeXml_SSCANF, SeXml_SUCCESS, SeXml_WRONG_TYPE, value.
Referenced by SeXmlElement::Attribute, SeXmlElement::QueryDoubleAttribute.
void SeXmlAttribute::SetName(const char *_name)
Set the name of this attribute.
References name.
Referenced by SeXmlAttributeSet::FindOrCreate.
void SeXmlAttribute::SetValue(const char *_value)
Set the value.
References value.
Referenced by SeXmlElement::SetAttribute, SetDoubleValue, SetIntValue.
void SeXmlAttribute::SetIntValue(int _value)
Set the value from an integer.
References SetValue, SeXml_SNPRINTF.
Referenced by SeXmlElement::SetAttribute.
void SeXmlAttribute::SetDoubleValue(double _value)
Set the value from a double.
References SetValue, SeXml_SNPRINTF.
Referenced by SeXmlElement::SetDoubleAttribute.
void SeXmlAttribute::SetName(const std::string &_name)
STL std::string form.
References name.
void SeXmlAttribute::SetValue(const std::string &_value)
STL std::string form.
References value.
const SeXmlAttribute * SeXmlAttribute::Next() const
Get the next sibling attribute in the DOM. Returns null at end.
References name, next, value.
Referenced by SeXmlElement::CopyTo, SeXmlHandle::CreatePath, SeXmlHandle::GetPath, SeXmlElement::Print, SeXmlPrinter::VisitEnter.
SeXmlAttribute* SeXmlAttribute::Next()
const SeXmlAttribute * SeXmlAttribute::Previous() const
Get the previous sibling attribute in the DOM. Returns null at beginning.
References name, prev, value.
SeXmlAttribute* SeXmlAttribute::Previous()
bool SeXmlAttribute::operator==(const SeXmlAttribute &rhs) const
References name.
bool SeXmlAttribute::operator<(const SeXmlAttribute &rhs) const
References name.
bool SeXmlAttribute::operator>(const SeXmlAttribute &rhs) const
References name.
const char * SeXmlAttribute::Parse(const char *p, SeXmlParsingData *data, SeXmlEncoding encoding)
References SeXmlParsingData::Cursor, document, SeXmlBase::IsWhiteSpace, SeXmlBase::location, name, SeXmlBase::ReadName, SeXmlBase::ReadText, SeXmlDocument::SetError, SeXmlBase::SeXml_ERROR_READING_ATTRIBUTES, SeXmlBase::SkipWhiteSpace, SeXmlParsingData::Stamp, value.
Referenced by SeXmlElement::Parse, SeXmlDeclaration::Parse.
virtual void SeXmlAttribute::Print(FILE *cfile, int depth) const
All SeXml classes can print themselves to a filestream or the string class (SeXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.This is a formatted print, and will insert tabs and newlines.(For an unformatted stream, use the << operator.)
void SeXmlAttribute::Print(FILE *cfile, int depth, SeXml_STRING *str) const
References SeXmlBase::EncodeString, name, SeXml_STRING, value.
void SeXmlAttribute::SetDocument(SeXmlDocument *doc)
References document.
Referenced by SeXmlElement::Parse.
SeXmlAttribute::SeXmlAttribute(const SeXmlAttribute &)
void SeXmlAttribute::operator=(const SeXmlAttribute &base)