HeroInfoTableMgr
std::map<unsigned int,HeroInfoTable*> HeroInfoTableMgr::m_kHeroInfoTableMap
Referenced by FillData, GetHeroInfoTable, GetHeroInfoTableMap, GetHeroInfoTableVec, UpdateLanguadgeContent, ~HeroInfoTableMgr.
HeroInfoTableMgr * HeroInfoTableMgr::m_pkHeroInfoTableMgr
Referenced by Get, ReLoad.
HeroInfoTableMgr * HeroInfoTableMgr::Get()
References HeroInfoTableMgr, m_pkHeroInfoTableMgr.
Referenced by BlockServer::CheckTaskGuanqia, BlockServer::CheckTaskRace, GlobalTableMgr::GetHeroInfoTable, GlobalTableMgr::GetHeroInfoTableMap, TableMgr::LoadTable, ReLoad, HeroMgr::unlockHero, TableMgr::UpdateLanguageContent.
HeroInfoTableMgr * HeroInfoTableMgr::ReLoad()
References Get, m_pkHeroInfoTableMgr.
Referenced by TableMgr::ReloadTable.
HeroInfoTableMgr::HeroInfoTableMgr()
References Load.
Referenced by Get.
HeroInfoTableMgr::~HeroInfoTableMgr()
References m_kHeroInfoTableMap.
const HeroInfoTable * HeroInfoTableMgr::GetHeroInfoTable(unsigned int iTypeID)
References m_kHeroInfoTableMap.
Referenced by BlockServer::CheckTaskGuanqia, BlockServer::CheckTaskRace, GlobalTableMgr::GetHeroInfoTable.
const std::map< unsigned int, HeroInfoTable * > & HeroInfoTableMgr::GetHeroInfoTableMap()
References m_kHeroInfoTableMap.
Referenced by GlobalTableMgr::GetHeroInfoTableMap.
TableResArray HeroInfoTableMgr::GetHeroInfoTableVec()
References m_kHeroInfoTableMap, TableResArray::pushBack.
void HeroInfoTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, HeroInfoTable::kattack, HeroInfoTable::kattackKey, HeroInfoTable::kchenghao, HeroInfoTable::kchenghaoKey, HeroInfoTable::kdingwei, HeroInfoTable::kdingweiKey, HeroInfoTable::kfenlei, HeroInfoTable::kfenleiKey, HeroInfoTable::kHeroName, HeroInfoTable::kHeroNameKey, HeroInfoTable::kjianjie, HeroInfoTable::kjianjieKey, HeroInfoTable::kjiqiaoK, HeroInfoTable::kjiqiaoKKey, HeroInfoTable::kzhenying, HeroInfoTable::kzhenyingKey, m_kHeroInfoTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool HeroInfoTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by HeroInfoTableMgr.
void HeroInfoTableMgr::FillData(HeroInfoTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, HeroInfoTable::fDifficulty, HeroInfoTable::kattackKey, HeroInfoTable::kchenghaoKey, HeroInfoTable::kdingweiKey, HeroInfoTable::kfenleiKey, HeroInfoTable::kHeroNameKey, HeroInfoTable::kHeroStoryK, HeroInfoTable::kjianjieKey, HeroInfoTable::kjiqiaoKKey, HeroInfoTable::kzhenyingKey, m_kHeroInfoTableMap, HeroInfoTable::uifenlei, HeroInfoTable::uiUnitID.
Referenced by Load.