PerformanceTiming::CCounter
UInt32 PerformanceTiming::CCounter::m_uValue
Referenced by Add, PerformanceTiming::CHistoryCounter::AdvanceFrame, Decrement, GetValue, Increment, Reset, SetValue.
UInt32 PerformanceTiming::CCounter::m_uiFlags
Referenced by CheckFlag, HasFlagsSet.
UInt32 PerformanceTiming::CCounter::m_uWarningThreshold
Referenced by GetWarningThresholdMS.
UInt32 PerformanceTiming::CCounter::m_uCriticalThreshold
Referenced by GetCriticalThresholdMS.
PerformanceTiming::CCounter::CCounter(const std::string &sName, UInt32 uiFlags, UInt32 uWarning=0, UInt32 uCritical=0)
virtual void PerformanceTiming::CCounter::HardReset()
References Reset, PerformanceTiming::CPerformanceStat::ResetTouch.
UInt32 PerformanceTiming::CCounter::CheckFlag(UInt32 uFlag) const
References m_uiFlags.
void PerformanceTiming::CCounter::SetValue(UInt32 uiNewValue)
References m_uValue, PerformanceTiming::CPerformanceStat::Touch.
void PerformanceTiming::CCounter::Add(Int32 uiIncrement)
References m_uValue, PerformanceTiming::CPerformanceStat::Touch.
void PerformanceTiming::CCounter::Increment()
References m_uValue, PerformanceTiming::CPerformanceStat::Touch.
void PerformanceTiming::CCounter::Decrement()
References m_uValue, PerformanceTiming::CPerformanceStat::Touch.
void PerformanceTiming::CCounter::Reset()
References m_uValue.
Referenced by HardReset, CPerformanceTiming::ResetCounters.
Int32 PerformanceTiming::CCounter::GetValue() const
References m_uValue.
Referenced by CPerformanceTiming::EnumerateAllCounters.
Int32 PerformanceTiming::CCounter::GetWarningThresholdMS() const
References m_uWarningThreshold.
Int32 PerformanceTiming::CCounter::GetCriticalThresholdMS() const
References m_uCriticalThreshold.
ICounter* PerformanceTiming::CCounter::SetFolderName(const char *szFolderName)
References PerformanceTiming::CPerformanceStat::DoSetFolderName.
virtual ICounter* PerformanceTiming::CCounter::SetFolderName(int iFolderFlag)
References PerformanceTiming::CPerformanceStat::DoSetFolderFlag.
bool PerformanceTiming::CCounter::HasFlagsSet(UInt32 uiFlags) const
References m_uiFlags.
Referenced by PerformanceTiming::CHistoryCounter::AdvanceFrame.
virtual bool PerformanceTiming::CCounter::IsHistoryCounter() const
PerformanceTiming::CCounter::CCounter(const std::string &sName, UInt32 uiFlags, UInt32 uWarning=0, UInt32 uCritical=0)
virtual void PerformanceTiming::CCounter::HardReset()
References Reset, PerformanceTiming::CPerformanceStat::ResetTouch.
UInt32 PerformanceTiming::CCounter::CheckFlag(UInt32 uFlag) const
References m_uiFlags.
void PerformanceTiming::CCounter::SetValue(UInt32 uiNewValue)
References m_uValue, PerformanceTiming::CPerformanceStat::Touch.
void PerformanceTiming::CCounter::Add(Int32 uiIncrement)
References m_uValue, PerformanceTiming::CPerformanceStat::Touch.
void PerformanceTiming::CCounter::Increment()
References m_uValue, PerformanceTiming::CPerformanceStat::Touch.
void PerformanceTiming::CCounter::Decrement()
References m_uValue, PerformanceTiming::CPerformanceStat::Touch.
void PerformanceTiming::CCounter::Reset()
References m_uValue.
Int32 PerformanceTiming::CCounter::GetValue() const
References m_uValue.
Int32 PerformanceTiming::CCounter::GetWarningThresholdMS() const
References m_uWarningThreshold.
Int32 PerformanceTiming::CCounter::GetCriticalThresholdMS() const
References m_uCriticalThreshold.
ICounter* PerformanceTiming::CCounter::SetFolderName(const char *szFolderName)
References PerformanceTiming::CPerformanceStat::DoSetFolderName.
virtual ICounter* PerformanceTiming::CCounter::SetFolderName(int iFolderFlag)
References PerformanceTiming::CPerformanceStat::DoSetFolderFlag.
bool PerformanceTiming::CCounter::HasFlagsSet(UInt32 uiFlags) const
References m_uiFlags.
virtual bool PerformanceTiming::CCounter::IsHistoryCounter() const