SeRaceRoomMgr
MapMatchPlayer SeRaceRoomMgr::m_kAllPlayer
Referenced by CreateRoom, DelPlayer, Finialize, GetPlayer, OnReconValidOK, OnViewValidOKRet, RecycleRoomPlayer.
MapRaceRoom SeRaceRoomMgr::m_kAllRoom
Referenced by CreateRoom, DelRoom, Finialize, GetRoom, OnReSendRoomInfo, UpdateRaceEndTime, UpdateReady, UpdateWaitRoom.
MapMatchRaceSelTask SeRaceRoomMgr::m_kMapMatchSelTask
Referenced by ClearModeTask, IntoSelHero, OnPlayerCancelHero, SelHero, SelHeroReady, StartLoad, UpdateSelHero.
DWord SeRaceRoomMgr::m_dwGenRaceModeID
Referenced by GenRaceModeID, SeRaceRoomMgr.
MRoom2ViewPlayerID SeRaceRoomMgr::m_kMRoom2ViewPlayerID
Referenced by BeginRaceView, DelRoomViewPlayVec, LeaveRaceView.
VReLoadRoomInfo SeRaceRoomMgr::m_kVReLoadRoomInfo
Referenced by OnReSendRoomInfo, UpdateReSendRoomList.
SeRaceRoomMgr::SeRaceRoomMgr(void)
References m_dwGenRaceModeID.
SeRaceRoomMgr::~SeRaceRoomMgr(void)
bool SeRaceRoomMgr::Initialize(void)
void SeRaceRoomMgr::Update(void)
References UpdateRaceEndTime, UpdateReady, UpdateReSendRoomList, UpdateSelHero, UpdateWaitRoom.
Referenced by RaceServer::Update.
void SeRaceRoomMgr::Finialize(void)
References DestroyRoom, m_kAllPlayer, m_kAllRoom.
void SeRaceRoomMgr::OnReSendRoomInfo(void)
References SeRaceRoom::eRoomState, GetReloadRoomInfo, m_kAllRoom, m_kVReLoadRoomInfo, SRRS_RACEWAIT, SRRS_WAIT.
Referenced by RaceServer::ProcessMR_RegisterRet.
void SeRaceRoomMgr::GetReloadRoomInfo(SeRaceRoom *pkRoom, SeReLoadRoomInfo &rkReLoadRoomInfo)
References SeRacePlayer::acName, SeReLoadPlayerInfo::acName, SeReLoadRoomInfo::akPlayerInfo, SeReLoadRoomInfo::bIsSvrRace, SeRacePlayer::bLeaveRace, SeReLoadPlayerInfo::bLeaveRace, SeReLoadRoomInfo::bRacing, SeReLoadPlayerInfo::bReverse, SeRaceRoom::bSvrRace, SeReLoadPlayerInfo::dwAreaID, SeReLoadPlayerInfo::dwHeroID, SeReLoadPlayerInfo::dwHeroSkin, SeRacePlayer::dwHeroTypeID, SeRaceRoom::dwID, SeRaceRoom::dwMapID, SeReLoadRoomInfo::dwMapID, SeRacePlayer::dwPlayerID, SeReLoadPlayerInfo::dwPlayerID, SeReLoadRoomInfo::dwRaceBeginTime, SeReLoadPlayerInfo::dwServerID, SeReLoadRoomInfo::dwSession, SeHeroAvatar::dwSkin, SeRacePlayer::eCamp, SeReLoadPlayerInfo::eCamp, SeRaceRoom::eMatchType, SeReLoadRoomInfo::eMatchType, SeRaceRoom::eRoomState, g_kMatchReconMgr, g_kRaceMgr, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetAreaID, SeMatchPlayer::GetID, GetPlayer, SeMatchPlayer::GetPlayerSeat, SeRaceMgr::GetRaceByID, SeRaceMgr::GetRacePlayerBySeat, SeRaceMgr::GetRaceTime, SeMatchPlayer::GetRoomPlayerCamp, SeMatchPlayer::GetServerID, SeMatchPlayer::GetTownRoomIndex, MapInfoTable::iMaxPlayer, SeRacePlayer::iSeatIndex, SeReLoadPlayerInfo::iSeatIndex, SeMatchReconMgr::IsReservedSeat, SeReLoadPlayerInfo::iTownRoomIndex, SeRacePlayer::kHeroAvatar, SeRaceRoom::kRaceID, SeRaceRoom::pkMapInfoRes, SRRS_SELHERO, SSD_MAX_CHAR_NAME, SSD_MAX_ROOM_PLAYER, StrCpy.
Referenced by OnReSendRoomInfo.
void SeRaceRoomMgr::CreateRoom(SeMR_ValidatePlayerInfo *pkData, VMatchRaceInfo &rakRaceInfo)
References SeMatchPlayer::AddPlayerInfo, SeRaceRoom::akRoomSeat, SeMR_ValidatePlayerInfo::bRobot, SeRaceRoom::bRobot, SeRaceRoom::bSvrRace, SeMR_ValidatePlayerInfo::bSvrRace, RaceServer::DelConnectByID, DelPlayer, SeRaceRoomSeat::dwAreaID, SeMR_ValidatePlayerInfo::dwKey, SeRaceRoom::dwKey, SeRaceRoom::dwMapID, SeMR_ValidatePlayerInfo::dwMapID, SeRaceRoomSeat::dwPlayerID, SeMR_ValidatePlayerInfo::dwScoreCampA, SeRaceRoom::dwScoreCampA, SeMR_ValidatePlayerInfo::dwScoreCampB, SeRaceRoom::dwScoreCampB, SeMR_ValidatePlayerInfo::dwScoreRobot, SeRaceRoom::dwScoreRobot, SeMR_ValidatePlayerInfo::dwSessionID, SeRaceRoom::dwStateTime, SeRaceRoom::eRaceModel, g_kRaceServer, MapInfoTableMgr::Get, SeMatchPlayer::GetAreaID, SeMatchPlayer::GetID, MapInfoTableMgr::GetMapInfoTable, GetPlayer, SeMatchPlayer::GetPlayerSeat, RaceServer::GetServerTime, SeMR_ValidatePlayerInfo::iDifficulty, SeRaceRoom::iDifficulty, RaceServer::IsTestRobotMode, SeMR_ValidatePlayerInfo::kRaceBet, SeRaceRoom::kRaceBet, m_kAllPlayer, m_kAllRoom, OnProcessRepeatPlayer, SeRaceRoom::pkMapInfoRes, SeLogError, RaceServer::SendRM_ValidatePlayerInfoRet, SeMatchPlayer::SetSessionID, SMVR_RECEIVE_OK, SMVR_REPEAT, SRM_NORMAL, SSD_MAX_ROOM_PLAYER.
Referenced by RaceServer::ProcessMR_ValidatePlayerInfo, RaceServer::StartRobotGame.
void SeRaceRoomMgr::DelRoom(DWord dwSessionID)
References DestroyRoom, m_kAllRoom, SeLogInfo.
Referenced by OnProcessRepeatPlayer, OnRaceLeave.
SeMatchPlayer * SeRaceRoomMgr::GetPlayer(DWord dwPlayerID)
References m_kAllPlayer.
Referenced by CreateRoom, SeRaceRoom::GetAllSeatPlayer, SeRaceRoom::GetOneMatchPlayer, GetReloadRoomInfo, RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, SeRaceMgr::OnPlayerReconBegin, SeRaceMgr::OnPlayerReportSyn, SeRaceMgr::OnRaceModeEnd, RaceServer::ProcessBLR_SelectHeroAck, RaceServer::ProcessCR_BuyRaceItem, RaceServer::ProcessCR_GetHeroInfo, RaceServer::ProcessCR_RaceCmd, RaceServer::ProcessCR_RaceEndGuanqia, RaceServer::ProcessCR_RaceEndRace, RaceServer::ProcessCR_RaceLeave, RaceServer::ProcessCR_RaceLoadEnd, RaceServer::ProcessCR_RaceReportSyn, RaceServer::ProcessCR_RaceValidate, RaceServer::ProcessCR_ReplayReport, RaceServer::ProcessCR_SelHeroCancelHero, RaceServer::ProcessCR_SelHeroChoiceHero, RaceServer::ProcessCR_SelHeroPrapared, RaceServer::ProcessCR_SetAvatarReq, RaceServer::ProcessCR_SetEquipSetReq, RaceServer::ProcessCR_Talk, RaceServer::ProcessMR_RaceBuyRet, SeRaceMgr::UpdateLoadingRace, SeRaceMgr::UpdateReconEnd.
void SeRaceRoomMgr::DelPlayer(DWord dwID, bool bRealDel=true)
References m_kAllPlayer.
Referenced by CreateRoom, RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, OnRaceLeave.
void SeRaceRoomMgr::ChangeRoomState(int iRoomSession, SeRaceRoomState eState)
References SeRaceRoom::dwRaceEndTime, SeRaceRoom::dwStateTime, SeRaceRoom::eRoomState, g_kRaceServer, GetRoom, RaceServer::GetServerTime, SRRS_RACEWAIT.
Referenced by IntoSelHero, OnRaceEnd, SeRaceMgr::OnRaceModeEnd, SeRaceMgr::UpdateLoadEnd.
SeRaceRoom * SeRaceRoomMgr::GetRoom(DWord dwID)
References m_kAllRoom.
Referenced by BeginRaceView, ChangeRoomState, SeRaceMgr::GetRaceByRoomIndex, SeMatchReconMgr::InitAllow, SeRaceMgr::IsReconValidPlayer, JoinRoomRecon, OnPlayerCancelHero, OnPlayerChoiceHero, OnPlayerReconQuery, OnPlayerSelectHeroReady, OnPlayerTalk, OnPlayerViewQuery, OnProcessRepeatPlayer, OnRaceEnd, OnRaceLeave, OnViewValidOKRet, RaceServer::ProcessBLR_SelectHeroAck, RaceServer::ProcessCR_RaceValidate, RaceServer::ProcessCR_SelHeroChoiceHero, RaceServer::ProcessCR_SetAvatarReq, RaceServer::ProcessCR_SetEquipSetReq, RaceServer::ProcessCR_Talk, RaceServer::ProcessMR_RaceBuyRet, UpdateSelHero.
void SeRaceRoomMgr::OnRaceEnd(int iRoomIndex)
References ChangeRoomState, SeRaceRoom::dwID, SeRaceRoom::eRoomState, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetPlayerState, GetRoom, SeMatchPlayer::SetPlayerState, SMPS_RACEWAIT, SMPS_RACING, SRRS_RACEWAIT, SRRS_RACING.
Referenced by SeRaceMgr::UpdateRaceEnd.
void SeRaceRoomMgr::OnRaceLeave(SeMatchPlayer *pkPlayer, bool bClientDisconnect=false, bool bSynLeave=false)
References DelPlayer, DelRoom, eSSRSTATE_END_RACE, eSSRSTATE_RACING, g_kRaceServer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, SeMatchPlayer::GetName, SeMatchPlayer::GetPlayerSeat, SeMatchPlayer::GetPlayerState, GetRoom, SeMatchPlayer::GetRoomSessionID, SeMatchPlayer::IsRaceEndReport, SeMatchPlayer::IsSendReturnWait, IsValidRace, MM_GAME_STATE, RaceServer::OnPlayerDisconnect, RecycleRoomPlayer, SelHeroReady, SeLogDebug, SeLogInfo, RaceServer::SendRM_CommRaceMsg, RaceServer::SendRM_UpdateMisc, RaceServer::SendRM_ValidatePlayerInfoRet, SeMatchPlayer::SetPlayerState, SeMatchPlayer::SetReturnWait, SMPS_RACEOVER, SMPS_RACEWAIT, SMVR_LEAVE, SRCM_LEAVE_RACE, SRRS_LOADING, SRRS_RACING, SRRS_SELHERO, SRRS_WAIT, SSD_MAX_ROOM_PLAYER.
Referenced by RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, OnProcessRepeatPlayer, RaceServer::ProcessCR_RaceLeave, SeRaceMgr::UpdateLoadingRace, UpdateRaceEndTime, SeRaceMgr::UpdateReconEnd.
void SeRaceRoomMgr::OnProcessRepeatPlayer(SeMatchPlayer *pkPlayer)
References DelRoom, SeRaceRoom::dwID, SeRaceRoom::eRoomState, g_kRaceMgr, g_kRaceServer, SeMatchPlayer::GetID, GetRoom, SeMatchPlayer::GetRoomSessionID, SeRaceMgr::OnPlayerRaceLeave, OnRaceLeave, RecycleRoomPlayer, RaceServer::SendRM_CommRaceMsg, RaceServer::SendRM_ValidatePlayerInfoRet, SMVR_LEAVE, SRCM_BREAK_RACE, SRRS_LOADING, SRRS_RACING, SRRS_SELHERO, SRRS_WAIT.
Referenced by CreateRoom.
void SeRaceRoomMgr::OnPlayerChoiceHero(SeMatchPlayer *pkPlayer, DWord dwHeroCardID, bool bDreamHero)
References SeRaceRoom::eRoomState, SeMatchPlayer::GetPlayerState, GetRoom, SeMatchPlayer::GetRoomSessionID, SelHero, SMPS_SELECT_HERO, SRRS_SELHERO.
Referenced by RaceServer::ProcessBLR_SelectHeroAck, RaceServer::ProcessCR_SelHeroChoiceHero.
void SeRaceRoomMgr::OnPlayerCancelHero(SeMatchPlayer *pkPlayer)
References SeMatchRaceSelTask::akPlayerSelResult, SeSelectResult::bReady, SeSelectResult::bSelected, CancelHero, SeRaceRoom::dwModeTaskID, SeSelectResult::dwPlayerID, SeRaceRoom::eRoomState, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, SeMatchPlayer::GetPlayerState, GetRoom, SeMatchPlayer::GetRoomSessionID, SeMatchRaceSelTask::HasFlag, m_kMapMatchSelTask, SMPS_SELECT_HERO, SRRS_SELHERO, SSD_MAX_ROOM_PLAYER, SSMF_HAS_OPR.
Referenced by RaceServer::ProcessCR_SelHeroCancelHero.
void SeRaceRoomMgr::OnPlayerSelectHeroReady(SeMatchPlayer *pkPlayer)
References SeRaceRoom::eRoomState, SeMatchPlayer::GetPlayerState, GetRoom, SeMatchPlayer::GetRoomSessionID, SelHeroReady, SMPS_SELECT_HERO, SRRS_SELHERO.
Referenced by RaceServer::ProcessCR_SelHeroPrapared.
DWord SeRaceRoomMgr::GetRandID(SeRaceRoom *pkRoom, SeMatchRaceSelTask *pkTask, SeRoomPlayerCamp eCamp, SeMatchPlayer *pkPlayer)
References g_kRaceServer, IsValidHeroID, SeMatchRaceSelTask::kMHeroTypeID2VPlayer, RaceServer::RandInt, SeLogError.
Referenced by SeRaceMgr::OnRaceModeEnd, SelHeroFight.
SeReconQueryFailReason SeRaceRoomMgr::OnPlayerReconQuery(DWord dwRoomSession, DWord dwPlayerID, int iSeat, DWord dwAreaID)
References SeRaceRoom::akRoomSeat, SeRaceRoomSeat::dwAreaID, SeRaceRoom::dwID, SeRaceRoom::eRoomState, g_kMatchReconMgr, g_kRaceMgr, SeMatchReconMgr::GetReconPlayer, GetRoom, SeReconPlayer::iRoomIndex, SeMatchReconMgr::IsAllowPlayer, SeReconPlayer::iSeatIndex, SeRaceMgr::IsReconValidPlayer, SeRaceMgr::IsReconValidSeat, SeMatchReconMgr::IsReservedSeat, SRQF_COMMON, SRQF_NOT_RACING, SRQF_NOT_SAMEAREA, SRQF_NULL, SRQF_RESERVED, SRRS_RACING, SSD_MAX_ROOM_PLAYER.
Referenced by RaceServer::ProcessCR_RaceValidate, RaceServer::ProcessMR_ReconQuery.
void SeRaceRoomMgr::OnReconValidOK(SeConnect *pkConnect, SeRaceRoom *pkRoom, SeReconInitInfo &rkInitInfo)
References SeRaceRoom::akRoomSeat, SeRaceRoom::DelDroppedPlayer, SeMatchReconMgr::DelPlayer, SeMatchReconMgr::DelReconPlayerName, SeReconInitInfo::dwFrame, SeRaceRoom::dwID, SeRaceRoomSeat::dwPlayerID, SeReconInitInfo::dwPlayerID, SeConnect::eState, g_kMatchReconMgr, g_kRaceServer, SeMatchPlayer::GetID, SeReconInitInfo::iOffset, SeReconInitInfo::iSeat, JoinRoomRecon, SeConnect::kSock, SeUDPSender::kSock, m_kAllPlayer, SeMatchPlayer::ReconResetPlayerInfo, SeMatchReconMgr::RemoveRaceSeat, SAFECHECK_INDEX, SCS_VALID_OK, RaceServer::SendRC_ValidateRet, SeMatchPlayer::SetHSock, SeMatchPlayer::SetPlayerState, SeMatchPlayer::SetSessionID, SeMatchPlayer::SetValidate, SMPS_RACING, SSD_MAX_ROOM_PLAYER.
Referenced by RaceServer::ProcessCR_RaceValidate.
void SeRaceRoomMgr::JoinRoomRecon(SeMatchPlayer *pkPlayer, DWord dwSession, int iSeat, bool bView, int iOffset=0, DWord dwFrame=0)
References SeRaceRoom::dwID, SeRaceRoom::dwMapID, g_kRaceMgr, g_kRaceServer, SeMatchPlayer::GetID, GetRoom, MM_GAME_STATE, SeRaceMgr::OnPlayerReconBegin, RaceServer::SendRM_UpdateMisc.
Referenced by OnReconValidOK.
SeViewQueryFailReason SeRaceRoomMgr::OnPlayerViewQuery(SeMR_ViewQuery *pkQuery, DWord &rdwParam)
References SeRace::akViewPlayer, SeMR_ViewQuery::dwPlayerID, SeViewPlayer::dwPlayerID, SeMR_ViewQuery::dwSession, SeRaceRoom::eRoomState, g_kRaceMgr, SeRaceMgr::GetRaceByID, GetRoom, SeRaceRoom::kRaceID, SRRS_RACING, SVQF_EXIST, SVQF_NOT_RACING, SVQF_NULL.
Referenced by RaceServer::ProcessMR_ViewQuery.
void SeRaceRoomMgr::OnViewValidOKRet(SeConnect *pkConnect, SeMR_ViewValidOKRet *pkRet)
References BeginRaceView, SeViewInitInfo::dwPlayerID, SeMR_ViewValidOKRet::dwSession, SeConnect::eState, g_kRaceServer, GetRoom, SeMR_ViewValidOKRet::kInitInfo, SeConnect::kSock, SeUDPSender::kSock, m_kAllPlayer, SeRaceRoom::pkMapInfoRes, SCS_VALID_OK, RaceServer::SendRC_ValidateRet, SeMatchPlayer::SetHSock, SeMatchPlayer::SetPlayerState, SeMatchPlayer::SetSessionID, SeMatchPlayer::SetValidate, SMPS_RACEVIEW, SeMatchPlayer::ViewSetPlayerInfo.
Referenced by RaceServer::ProcessMR_ViewValidOKRet.
void SeRaceRoomMgr::LeaveRaceView(SeMatchPlayer *pkPlayer, DWord dwSession)
References SeViewPlayerData::dwPlayerID, SeMatchPlayer::GetID, m_kMRoom2ViewPlayerID, SeMatchPlayer::SetRaceID.
Referenced by RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, SeRaceMgr::OnPlayerView2Recon.
void SeRaceRoomMgr::OnPlayerTalk(SeMatchPlayer *pkPlayer, const char *pcMsg)
References g_kRaceServer, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, GetRoom, SeMatchPlayer::GetRoomSessionID, SeUDPSender::kSock, RaceServer::SendRC_Talk, STT_NORMAL_TALK.
Referenced by RaceServer::ProcessCR_Talk.
SeRaceRoomMgr::SeRaceRoomMgr(void)
SeRaceRoomMgr::~SeRaceRoomMgr(void)
bool SeRaceRoomMgr::Initialize(void)
void SeRaceRoomMgr::Update(void)
void SeRaceRoomMgr::Finialize(void)
void SeRaceRoomMgr::OnReSendRoomInfo(void)
void SeRaceRoomMgr::GetReloadRoomInfo(SeRaceRoom *pkRoom, SeReLoadRoomInfo &rkReLoadRoomInfo)
void SeRaceRoomMgr::CreateRoom(SeMR_ValidatePlayerInfo *pkData, VMatchRaceInfo &rakRaceInfo)
void SeRaceRoomMgr::DelRoom(DWord dwSessionID)
SeMatchPlayer* SeRaceRoomMgr::GetPlayer(DWord dwPlayerID)
void SeRaceRoomMgr::DelPlayer(DWord dwID, bool bRealDel=true)
void SeRaceRoomMgr::ChangeRoomState(int iRoomSession, SeRaceRoomState eState)
SeRaceRoom* SeRaceRoomMgr::GetRoom(DWord dwID)
void SeRaceRoomMgr::OnRaceEnd(int iRoomIndex)
void SeRaceRoomMgr::OnRaceLeave(SeMatchPlayer *pkPlayer, bool bClientDisconnect=false, bool bSynLeave=false)
void SeRaceRoomMgr::OnProcessRepeatPlayer(SeMatchPlayer *pkPlayer)
void SeRaceRoomMgr::OnPlayerChoiceHero(SeMatchPlayer *pkPlayer, DWord dwHeroCardID, bool bDreamHero)
void SeRaceRoomMgr::OnPlayerCancelHero(SeMatchPlayer *pkPlayer)
void SeRaceRoomMgr::OnPlayerSelectHeroReady(SeMatchPlayer *pkPlayer)
DWord SeRaceRoomMgr::GetRandID(SeRaceRoom *pkRoom, SeMatchRaceSelTask *pkTask, SeRoomPlayerCamp eCamp, SeMatchPlayer *pkPlayer)
SeReconQueryFailReason SeRaceRoomMgr::OnPlayerReconQuery(DWord dwRoomSession, DWord dwPlayerID, int iSeat, DWord dwAreaID)
void SeRaceRoomMgr::OnReconValidOK(SeConnect *pkConnect, SeRaceRoom *pkRoom, SeReconInitInfo &rkInitInfo)
void SeRaceRoomMgr::JoinRoomRecon(SeMatchPlayer *pkPlayer, DWord dwSession, int iSeat, bool bView, int iOffset=0, DWord dwFrame=0)
SeViewQueryFailReason SeRaceRoomMgr::OnPlayerViewQuery(SeMR_ViewQuery *pkQuery, DWord &rdwParam)
void SeRaceRoomMgr::OnViewValidOKRet(SeConnect *pkConnect, SeMR_ViewValidOKRet *pkRet)
void SeRaceRoomMgr::LeaveRaceView(SeMatchPlayer *pkPlayer, DWord dwSession)
void SeRaceRoomMgr::OnPlayerTalk(SeMatchPlayer *pkPlayer, const char *pcMsg)
void SeRaceRoomMgr::UpdateReSendRoomList()
References g_kRaceServer, RaceServer::GetServerTime, m_kVReLoadRoomInfo, SeLogError, RaceServer::SendRM_ReLoadRoomInfoList.
Referenced by Update.
void SeRaceRoomMgr::UpdateWaitRoom()
References DestroyRoom, SeRaceRoom::dwID, SeRaceRoom::dwStateTime, SeRaceRoom::eRoomState, g_kRaceServer, RaceServer::GetServerTime, IntoSelHero, IsPlayerValidateEnd, m_kAllRoom, RecycleRoomPlayer, SeLogError, SendRacePlayerBaseInfo, RaceServer::SendRM_ValidatePlayerInfoRet, SMVR_OK, SMVR_TIMEOUT, SRRS_WAIT.
Referenced by Update.
void SeRaceRoomMgr::UpdateSelHero()
References SeMatchRaceSelTask::bDeleted, SeMatchRaceSelTask::dwBeginTime, SeMatchRaceSelTask::dwSessionID, SeRaceRoom::eRaceModel, SeRaceRoom::eRoomState, g_kRaceServer, SeRaceRoom::GetAllSeatPlayer, GetRoom, RaceServer::GetServerTime, m_kMapMatchSelTask, SAFE_DELETE, SelHeroReady, SRM_ALLRANDOM, SRM_NORMAL, SRRS_SELHERO.
Referenced by Update.
void SeRaceRoomMgr::UpdateReady()
References SeRaceRoom::dwID, SeRaceRoom::dwMapID, SeRaceRoom::dwReadyTime, SeRaceRoom::eRoomState, g_kRaceServer, RaceServer::GetServerTime, m_kAllRoom, RaceServer::SendRM_MatchRaceLoad, SRRS_SELHERO, SSD_RACEBET_MAP, StartLoad.
Referenced by Update.
void SeRaceRoomMgr::UpdateRaceEndTime()
References DelRoomViewPlayVec, DestroyRoom, SeRaceRoom::dwID, SeRaceRoom::dwMapID, SeRaceRoom::dwRaceEndTime, SeRaceRoom::eRoomState, SeRace::eState, g_kRaceMgr, g_kRaceServer, SeRaceRoom::GetAllSeatPlayer, GetID2Str, SeMatchPlayer::GetPlayerState, SeRaceMgr::GetRaceByID, RaceServer::GetServerTime, IsAllRoomPlayerLeave, IsValidRace, SeRaceRoom::kRaceID, m_kAllRoom, OnRaceLeave, RAS_VERIFY_END, RecycleRoomPlayer, SeLogInfo, RaceServer::SendRM_CommRaceMsg, SMPS_RACEWAIT, SRCM_END_RACE, SRRS_RACEWAIT, SRRS_RACING.
Referenced by Update.
void SeRaceRoomMgr::StartLoad(SeRaceRoom *pkRoom)
References ClearModeTask, SeRaceRoom::dwID, SeRaceRoom::dwModeTaskID, SeRaceRoom::eRoomState, g_kRaceMgr, g_kRaceServer, SeRaceRoom::GetAllSeatPlayer, m_kMapMatchSelTask, SeRaceMgr::OnRaceModeEnd, RaceServer::SendRM_CommRaceMsg, SeMatchPlayer::SetPlayerState, SMPS_LOADING, SRCM_BEGIN_RACE, SRRS_SELHERO.
Referenced by UpdateReady.
bool SeRaceRoomMgr::IsPlayerValidateEnd(SeRaceRoom *pkRoom)
References SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::IsValidate.
Referenced by UpdateWaitRoom.
bool SeRaceRoomMgr::IsAllRoomPlayerLeave(SeRaceRoom *pkRoom)
References SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetPlayerState, SMPS_RACEOVER.
Referenced by UpdateRaceEndTime.
void SeRaceRoomMgr::RecycleRoomPlayer(SeRaceRoom *pkRoom, DWord dwSpecialID=0)
References SeRaceRoom::akRoomSeat, SeRaceRoom::dwID, SeRaceRoomSeat::dwPlayerID, g_kRaceServer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetRoomSessionID, m_kAllPlayer, RaceServer::OnPlayerDisconnect, SSD_MAX_ROOM_PLAYER.
Referenced by OnProcessRepeatPlayer, OnRaceLeave, UpdateRaceEndTime, UpdateWaitRoom.
bool SeRaceRoomMgr::IsValidRace(SeRaceRoom *pkRoom)
References SeRace::bVaildRace, g_kRaceMgr, SeRaceMgr::GetRaceByID, SeRaceRoom::kRaceID.
Referenced by OnRaceLeave, UpdateRaceEndTime.
DWord SeRaceRoomMgr::GenRaceModeID(void)
References m_dwGenRaceModeID.
Referenced by IntoSelHero.
void SeRaceRoomMgr::ClearModeTask(SeRaceRoom *pkRoom)
References SeMatchRaceSelTask::bDeleted, SeRaceRoom::dwModeTaskID, m_kMapMatchSelTask.
Referenced by StartLoad.
void SeRaceRoomMgr::SendRacePlayerBaseInfo(SeRaceRoom *pkRoom)
References SeMatchSelPlayerInfo::acName, SeMatchSelPlayerInfo::dwAreaID, SeRaceRoom::dwMapID, SeMatchSelPlayerInfo::dwPlayerID, SeMatchSelPlayerInfo::eCamp, SeRaceRoom::eRaceModel, g_kRaceServer, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetAreaID, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, SeMatchPlayer::GetName, SeMatchPlayer::GetPlayerSeat, SeMatchPlayer::GetRoomPlayerCamp, SeMatchSelPlayerInfo::iSeat, SeUDPSender::kSock, MemCpy, RaceServer::SendRC_RoomPlayerBaseInfo, SSD_MAX_CHAR_NAME.
Referenced by UpdateWaitRoom.
void SeRaceRoomMgr::IntoSelHero(SeRaceRoom *pkRoom)
References ChangeRoomState, SeMatchRaceSelTask::dwBeginTime, SeSelHeroInfo::dwHeroTypeID, SeRaceRoom::dwID, SeMatchRaceSelTask::dwModeID, SeRaceRoom::dwModeTaskID, SeMatchRaceSelTask::dwSessionID, SeRaceRoom::eRaceModel, g_kRaceServer, GenRaceModeID, SelHeroTableMgr::Get, SeMatchPlayer::GetAllHeroInfo, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetRoomPlayerCamp, SelHeroTableMgr::GetSelHeroTableMap, GetSelHeroTypeID, RaceServer::GetServerTime, SelHeroTable::iOpen, SeMatchRaceSelTask::kMHeroTypeID2VPlayer, SeUDPSender::kSock, m_kMapMatchSelTask, SelHero, RaceServer::SendRC_BeginSelectHero, RaceServer::SendRC_SelHeroList, SeMatchPlayer::SetPlayerState, SMPS_SELECT_HERO, SRM_ALLRANDOM, SRRS_SELHERO, SelHeroTable::uiUnitID.
Referenced by UpdateWaitRoom.
void SeRaceRoomMgr::SelHeroReady(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer)
References SeMatchRaceSelTask::akPlayerSelResult, SeSelectResult::bReady, SeSelectResult::dwHeroTypeID, SeRaceRoom::dwID, SeRaceRoom::dwModeTaskID, SeSelectResult::dwPlayerID, SeRaceRoom::dwReadyTime, SeSelectResult::eCamp, g_kRaceServer, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, SeMatchPlayer::GetRoomPlayerCamp, SeMatchPlayer::GetRoomSessionID, SeMatchPlayer::GetSelHeroID, RaceServer::GetServerTime, SeUDPSender::kSock, SeMatchRaceSelTask::kVSelectOpr, m_kMapMatchSelTask, SelHero, SeLogInfo, RaceServer::SendRC_SelHeroMessage, SeMatchPlayer::setRandomAvatar, SMT_SELHERO_HASPREPARED, SSD_MAX_ROOM_PLAYER.
Referenced by OnPlayerSelectHeroReady, OnRaceLeave, UpdateSelHero.
void SeRaceRoomMgr::GetSelHeroTypeID(SeRaceRoom *pkRoom, MTypeID2VMatchPlayer &rkTypeID)
References SeRaceRoom::eRaceModel, SelHeroTableMgr::Get, SelHeroTableMgr::GetSelHeroTableMap, SelHeroTable::iOpen, SRM_ALLRANDOM, SRM_NORMAL.
Referenced by IntoSelHero.
void SeRaceRoomMgr::SelHero(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, DWord dwHeroID, bool bDreamHero=false)
References SeMatchRaceSelTask::akPlayerSelResult, SeSelectResult::bDreamHero, SeSelectResult::dwHeroTypeID, SeRaceRoom::dwID, SeRaceRoom::dwModeTaskID, SeSelectResult::dwPlayerID, SeSelectResult::eCamp, g_kRaceServer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, SeMatchPlayer::GetPlayerSeat, SeMatchPlayer::GetRoomPlayerCamp, SeMatchPlayer::HasHero, SeUDPSender::kSock, m_kMapMatchSelTask, SelHeroFight, SeLogError, RaceServer::SendRC_ShowNotice, SNC_USER_HERO_UNLOCK, SSD_MAX_ROOM_PLAYER.
Referenced by CancelHero, IntoSelHero, OnPlayerChoiceHero, SelHeroReady.
void SeRaceRoomMgr::CancelHero(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, SeMatchRaceSelTask *pkTask, SeSelectResult &rkResult, bool bNeedDecMoney)
References SeSelectResult::bDreamHero, ClrSelectedHeroID, SeSelectResult::dwHeroTypeID, SeRaceRoom::eRaceModel, g_kRaceServer, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, SeMatchPlayer::GetRoomPlayerCamp, SeSelectResult::iDecMoney, SeSelectResult::iReselCount, SeUDPSender::kSock, SelHero, RaceServer::SendRC_SelHeroMessage, SMT_SELHERO_CANCEL_HERO, SRM_ALLRANDOM.
Referenced by OnPlayerCancelHero.
void SeRaceRoomMgr::SelHeroFight(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, SeMatchRaceSelTask *pkTask, SeSelectResult &rkResult, DWord &dwHeroID, bool bDreamHero)
References AddSelectedHeroID, SeSelectResult::bDreamHero, SeSelectResult::bSelected, SeSelectResult::dwHeroTypeID, SeRaceRoom::dwID, g_kRaceServer, SeRaceRoom::GetAllSeatPlayer, SeMatchPlayer::GetHSock, SeMatchPlayer::GetID, GetID2Str, SeMatchPlayer::GetPlayerSeat, GetRandID, SeMatchPlayer::GetRoomPlayerCamp, SeMatchPlayer::GetSelHeroID, IsValidHeroID, SeUDPSender::kSock, SeLogError, SeLogInfo, RaceServer::SendRC_SelHeroMessage, RaceServer::SendRC_ShowNotice, SeMatchPlayer::SetSelHeroID, SMT_SELHERO_RAND, SMT_SELHERO_SELF, SNC_MATCH_SELHERO_FAIL.
Referenced by SelHero.
bool SeRaceRoomMgr::IsValidHeroID(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, SeRoomPlayerCamp eCamp, SeMatchRaceSelTask *pkTask, DWord dwHeroID)
References SeMatchRaceSelTask::akPlayerSelResult, SeSelectResult::dwHeroTypeID, SeSelectResult::eCamp, SeMatchPlayer::GetRoomPlayerCamp, SeMatchPlayer::HasHero, SeMatchRaceSelTask::kMHeroTypeID2VPlayer, SSD_MAX_ROOM_PLAYER.
Referenced by GetRandID, SelHeroFight.
void SeRaceRoomMgr::AddSelectedHeroID(SeMatchPlayer *pkPlayer, SeMatchRaceSelTask *pkTask, DWord dwHeroID)
References SeMatchRaceSelTask::kMHeroTypeID2VPlayer.
Referenced by SelHeroFight.
void SeRaceRoomMgr::ClrSelectedHeroID(SeMatchPlayer *pkPlayer, SeMatchRaceSelTask *pkTask, DWord dwHeroID)
References SeMatchPlayer::GetID, SeMatchRaceSelTask::kMHeroTypeID2VPlayer.
Referenced by CancelHero.
void SeRaceRoomMgr::DelRoomViewPlayVec(int iRoomSession)
References m_kMRoom2ViewPlayerID.
Referenced by UpdateRaceEndTime.
void SeRaceRoomMgr::BeginRaceView(SeMatchPlayer *pkPlayer, DWord dwSession)
References SeViewPlayerData::dwPlayerID, SeViewPlayerData::dwStartTime, g_kRaceMgr, g_kRaceServer, SeMatchPlayer::GetAreaID, SeMatchPlayer::GetID, GetRoom, SeMatchPlayer::GetServerID, RaceServer::GetServerTime, m_kMRoom2ViewPlayerID, MM_VIEW_STATE, SeRaceMgr::OnPlayerRaceViewBegin, RaceServer::SendRM_UpdateMisc.
Referenced by OnViewValidOKRet.
void SeRaceRoomMgr::DestroyRoom(SeRaceRoom *pkRoom)
References SeRaceRoom::akDroppedPlayer, SSD_MAX_ROOM_PLAYER.
Referenced by DelRoom, Finialize, UpdateRaceEndTime, UpdateWaitRoom.
void SeRaceRoomMgr::UpdateReSendRoomList()
void SeRaceRoomMgr::UpdateWaitRoom()
void SeRaceRoomMgr::UpdateSelHero()
void SeRaceRoomMgr::UpdateReady()
void SeRaceRoomMgr::UpdateRaceEndTime()
void SeRaceRoomMgr::StartLoad(SeRaceRoom *pkRoom)
bool SeRaceRoomMgr::IsPlayerValidateEnd(SeRaceRoom *pkRoom)
bool SeRaceRoomMgr::IsAllRoomPlayerLeave(SeRaceRoom *pkRoom)
void SeRaceRoomMgr::RecycleRoomPlayer(SeRaceRoom *pkRoom, DWord dwSpecialID=0)
bool SeRaceRoomMgr::IsValidRace(SeRaceRoom *pkRoom)
DWord SeRaceRoomMgr::GenRaceModeID(void)
void SeRaceRoomMgr::ClearModeTask(SeRaceRoom *pkRoom)
void SeRaceRoomMgr::SendRacePlayerBaseInfo(SeRaceRoom *pkRoom)
void SeRaceRoomMgr::IntoSelHero(SeRaceRoom *pkRoom)
void SeRaceRoomMgr::SelHeroReady(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer)
void SeRaceRoomMgr::GetSelHeroTypeID(SeRaceRoom *pkRoom, MTypeID2VMatchPlayer &rkTypeID)
void SeRaceRoomMgr::SelHero(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, DWord dwHeroID, bool bDreamHero=false)
void SeRaceRoomMgr::CancelHero(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, SeMatchRaceSelTask *pkTask, SeSelectResult &rkResult, bool bNeedDecMoney)
void SeRaceRoomMgr::SelHeroFight(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, SeMatchRaceSelTask *pkTask, SeSelectResult &rkResult, DWord &dwHeroID, bool bDreamHero)
bool SeRaceRoomMgr::IsValidHeroID(SeRaceRoom *pkRoom, SeMatchPlayer *pkPlayer, SeRoomPlayerCamp eCamp, SeMatchRaceSelTask *pkTask, DWord dwHeroID)
void SeRaceRoomMgr::AddSelectedHeroID(SeMatchPlayer *pkPlayer, SeMatchRaceSelTask *pkTask, DWord dwHeroID)
void SeRaceRoomMgr::ClrSelectedHeroID(SeMatchPlayer *pkPlayer, SeMatchRaceSelTask *pkTask, DWord dwHeroID)
void SeRaceRoomMgr::DelRoomViewPlayVec(int iRoomSession)
void SeRaceRoomMgr::BeginRaceView(SeMatchPlayer *pkPlayer, DWord dwSession)
void SeRaceRoomMgr::DestroyRoom(SeRaceRoom *pkRoom)