RaceDetailMgr
MRaceDetails RaceDetailMgr::m_kRaceDetails
Referenced by CheckRaceDetail, CreateRaceDetail, DelRaceDetail, GetRaceDetail, GetRaceDetailMap, PushRaceDetail.
RaceDetailMgr::RaceDetailMgr()
RaceDetailMgr::~RaceDetailMgr()
bool RaceDetailMgr::CheckRaceRuler(const TeMD5 &rkRaceID)
References g_kRaceMgr, SeRaceMgr::GetRaceByID, SeLogInfo.
Referenced by MakeRaceDetail.
bool RaceDetailMgr::CheckRaceDetail(const TeMD5 &rkRaceID)
References m_kRaceDetails, SeLogInfo.
Referenced by MakeRaceDetail.
void RaceDetailMgr::CreateRaceDetail(const TeMD5 &rkRaceID)
References SeRacePlayer::acName, SeRaceUserInfo::acName, SeRaceCampBuildingInfo::alive_num, SeRaceMapPosInfo::barrack_pos, SeRaceCampBuildingInfo::base_building, SeRaceMapPosInfo::base_pos, SeRaceMapBuildingInfo::camp_building, SeRaceMapPosInfo::camp_id, SeRaceCampBuildingInfo::camp_id, SeRaceMapPosInfo::defense_town_pos, SeRace::dwBeginTime, SeRaceUserHeroInfo::dwHeroID, SeRaceUserHeroInfo::dwHeroSkinID, SeRacePlayer::dwHeroTypeID, SeRaceBaseBuildingInfo::dwMapBuildingType, SeRace::dwMapID, SeRaceMapInfo::dwMapID, SeRacePlayer::dwPlayerID, SeRaceUserInfo::dwPlayerID, SeHeroAvatar::dwSkin, SeRacePlayer::dwTeamID, SeRaceUserInfo::dwTeamID, SeRacePlayer::eCamp, SeRaceUserInfo::eCamp, SeRace::eServerRaceResult, g_kRaceMgr, g_kRaceServer, SeRaceGameInfo::game_mode, SeRaceGameInfo::game_time, MapsInfoTableMgr::Get, MapsInfoTableMgr::GetMapsInfoTableMap, SeRaceMgr::GetRaceByID, SeRace::getSeatPlayer, RaceServer::GetServerTime, SeRacePlayer::iSeatIndex, SeRaceUserInfo::iSeatIndex, SeRacePlayer::kHeroAvatar, m_kRaceDetails, MAPSINFO_MAPUNITTYPE_PROTOSSBARRACKS, MAPSINFO_MAPUNITTYPE_PROTOSSCENTER, MAPSINFO_MAPUNITTYPE_PROTOSSTOWER, MAPSINFO_MAPUNITTYPE_TERRANBARRACKS, MAPSINFO_MAPUNITTYPE_TERRANCENTER, MAPSINFO_MAPUNITTYPE_TERRANTOWER, SeRaceBaseBuildingInfo::pos_x, SeRaceBaseBuildingInfo::pos_y, SeRaceUserHeroInfo::race_assist, SeRaceUserHeroInfo::race_death, SeRaceInfo::race_game, SRaceDetail::race_info, SeRaceUserHeroInfo::race_kill, SeRaceInfo::race_map, SeRaceMapInfo::race_map_building, race_map_camp_god, race_map_camp_human, SeRaceMapInfo::race_map_pos, SeRaceGameInfo::race_mmr, SeRaceInfo::race_user, SeRaceUserInfo::race_user_hero, SRaceDetail::rase_id, SeLogDebug, SSD_MAX_ROOM_PLAYER, StrCpy, SyncRaceDetail.
Referenced by MakeRaceDetail.
void RaceDetailMgr::MakeRaceDetail(const TeMD5 &rkRaceID)
References CheckRaceDetail, CheckRaceRuler, CreateRaceDetail, SeLogInfo.
void RaceDetailMgr::DelRaceDetail(const TeMD5 &rkRaceID)
References m_kRaceDetails.
void RaceDetailMgr::SyncRaceDetail(SRaceDetail objRaceDetail)
References TeMD5::abyMD5, g_kRaceServer, RaceServer::GetWCSConnectMap, SRaceDetail::race_info, SeRaceDetailInfo::race_info, SRaceDetail::rase_id, SeRaceDetailInfo::rase_id, RaceServer::SendRWCS_RaceDetailInfoSync.
Referenced by CreateRaceDetail, SeRaceMgr::OnRealTimeRaceKDA, SeRaceMgr::OnRealTimeRaceMapDetail.
SRaceDetail & RaceDetailMgr::GetRaceDetail(const TeMD5 &rkRaceID)
References m_kRaceDetails.
void RaceDetailMgr::RaceUserAttr_Win(const DWord dw_race_time, DWord &dw_gold_plus, DWord &dw_exp_plus, const DWord dw_plus=1)
References beyond_win_exp_ratio, beyond_win_gold_ratio, inner_win_exp_ratio, inner_win_gold_ratio, min_convert_ratio, plus_limit_interval.
Referenced by SeRaceMgr::OnRaceEndArenaDetail.
void RaceDetailMgr::RaceUserAttr_Loss(const DWord dw_race_time, DWord &dw_gold_plus, DWord &dw_exp_plus, const DWord dw_plus=1)
References beyond_loss_exp_ratio, beyond_loss_gold_ratio, inner_loss_exp_ratio, inner_loss_gold_ratio, min_convert_ratio, plus_limit_interval.
Referenced by SeRaceMgr::OnRaceEndArenaDetail.
bool RaceDetailMgr::CheckRace_UserAttr_Bound(const DWord dw_pre_time, const DWord dw_cumu_golds, const DWord dw_gold_plus)
References g_kRaceServer, RaceServer::GetServerTime, moba::isSameWeek, ms_convert_second, race_user_cumu_golds_limit.
Referenced by SeRaceMgr::OnRaceEndArenaDetail.
MRaceDetails & RaceDetailMgr::GetRaceDetailMap()
References m_kRaceDetails.
Referenced by SeRaceMgr::OnRealTimeRaceKDA, SeRaceMgr::OnRealTimeRaceMapDetail.
void RaceDetailMgr::PushRaceDetail(SRaceDetail &detail)
References m_kRaceDetails, SRaceDetail::rase_id.
Referenced by SeRaceMgr::OnRealTimeRaceKDA, SeRaceMgr::OnRealTimeRaceMapDetail.
RaceDetailMgr::RaceDetailMgr()
RaceDetailMgr::~RaceDetailMgr()
bool RaceDetailMgr::CheckRaceRuler(const TeMD5 &rkRaceID)
bool RaceDetailMgr::CheckRaceDetail(const TeMD5 &rkRaceID)
void RaceDetailMgr::CreateRaceDetail(const TeMD5 &rkRaceID)
void RaceDetailMgr::MakeRaceDetail(const TeMD5 &rkRaceID)
void RaceDetailMgr::DelRaceDetail(const TeMD5 &rkRaceID)
void RaceDetailMgr::SyncRaceDetail(SRaceDetail objRaceDetail)
SRaceDetail& RaceDetailMgr::GetRaceDetail(const TeMD5 &rkRaceID)
void RaceDetailMgr::RaceUserAttr_Win(const DWord dw_race_time, DWord &dw_gold_plus, DWord &dw_exp_plus, const DWord dw_plus=1)
void RaceDetailMgr::RaceUserAttr_Loss(const DWord dw_race_time, DWord &dw_gold_plus, DWord &dw_exp_plus, const DWord dw_plus=1)
bool RaceDetailMgr::CheckRace_UserAttr_Bound(const DWord dw_pre_time, const DWord dw_cumu_golds, const DWord dw_gold_plus)
MRaceDetails& RaceDetailMgr::GetRaceDetailMap()
void RaceDetailMgr::PushRaceDetail(SRaceDetail &detail)