CCounterCloneFolderSet
const char * CCounterCloneFolderSet::m_szFolderName
Referenced by FolderName.
CRC_ID CCounterCloneFolderSet::m_FolderNameCRC
Referenced by FolderNameCRC.
PerformanceTiming::TConstCounterCloneArray CCounterCloneFolderSet::m_vCounters
Referenced by AddCounter, Counters.
CCounterCloneFolderSet::CCounterCloneFolderSet(const char *szName, CRC_ID folderNameCRC)
const char* CCounterCloneFolderSet::FolderName() const
References m_szFolderName.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
CRC_ID CCounterCloneFolderSet::FolderNameCRC() const
References m_FolderNameCRC.
void CCounterCloneFolderSet::AddCounter(const PerformanceTiming::CCounterClone *pCounter)
References m_vCounters.
Referenced by BuildFolderSets.
const PerformanceTiming::TConstCounterCloneArray& CCounterCloneFolderSet::Counters() const
References m_vCounters.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
CCounterCloneFolderSet::CCounterCloneFolderSet(const char *szName, CRC_ID folderNameCRC)
const char* CCounterCloneFolderSet::FolderName() const
References m_szFolderName.
CRC_ID CCounterCloneFolderSet::FolderNameCRC() const
References m_FolderNameCRC.
void CCounterCloneFolderSet::AddCounter(const PerformanceTiming::CCounterClone *pCounter)
References m_vCounters.
const PerformanceTiming::TConstCounterCloneArray& CCounterCloneFolderSet::Counters() const
References m_vCounters.
void CCounterCloneFolderSet::BuildFolderSets(std::vector< CCounterCloneFolderSet > &vFolderSets, PerformanceTiming::TCounterCloneArray &vAllCounters)
References AddCounter, PerformanceTiming::CCounterClone::GetFolderName, PerformanceTiming::CCounterClone::GetFolderNameCRC.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
static void CCounterCloneFolderSet::BuildFolderSets(std::vector< CCounterCloneFolderSet > &vFolderSets, PerformanceTiming::TCounterCloneArray &vAllCounters)