SystemPromptTableMgr
std::map<unsigned int,SystemPromptTable*> SystemPromptTableMgr::m_kSystemPromptTableMap
Referenced by FillData, GetSystemPromptTable, GetSystemPromptTableMap, GetSystemPromptTableVec, UpdateLanguadgeContent, ~SystemPromptTableMgr.
SystemPromptTableMgr * SystemPromptTableMgr::m_pkSystemPromptTableMgr
Referenced by Get, ReLoad.
SystemPromptTableMgr * SystemPromptTableMgr::Get()
References m_pkSystemPromptTableMgr, SystemPromptTableMgr.
Referenced by GlobalTableMgr::GerSystemPromptTable, TableMgr::LoadTable, ReLoad, TableMgr::UpdateLanguageContent.
SystemPromptTableMgr * SystemPromptTableMgr::ReLoad()
References Get, m_pkSystemPromptTableMgr.
Referenced by TableMgr::ReloadTable.
SystemPromptTableMgr::SystemPromptTableMgr()
References Load.
Referenced by Get.
SystemPromptTableMgr::~SystemPromptTableMgr()
References m_kSystemPromptTableMap.
const SystemPromptTable * SystemPromptTableMgr::GetSystemPromptTable(unsigned int iTypeID)
References m_kSystemPromptTableMap.
Referenced by GlobalTableMgr::GerSystemPromptTable.
const std::map< unsigned int, SystemPromptTable * > & SystemPromptTableMgr::GetSystemPromptTableMap()
References m_kSystemPromptTableMap.
TableResArray SystemPromptTableMgr::GetSystemPromptTableVec()
References m_kSystemPromptTableMap, TableResArray::pushBack.
void SystemPromptTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, SystemPromptTable::kTips1, SystemPromptTable::kTips1Key, m_kSystemPromptTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool SystemPromptTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by SystemPromptTableMgr.
void SystemPromptTableMgr::FillData(SystemPromptTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, SystemPromptTable::kDesc, SystemPromptTable::kTips1Key, m_kSystemPromptTableMap, SystemPromptTable::uiID.
Referenced by Load.