AttackArmorRatioTableMgr
std::map<unsigned int,AttackArmorRatioTable*> AttackArmorRatioTableMgr::m_kAttackArmorRatioTableMap
Referenced by FillData, GetAttackArmorRatioTable, GetAttackArmorRatioTableMap, GetAttackArmorRatioTableVec, ~AttackArmorRatioTableMgr.
AttackArmorRatioTableMgr * AttackArmorRatioTableMgr::m_pkAttackArmorRatioTableMgr
Referenced by Get, ReLoad.
AttackArmorRatioTableMgr * AttackArmorRatioTableMgr::Get()
References AttackArmorRatioTableMgr, m_pkAttackArmorRatioTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
AttackArmorRatioTableMgr * AttackArmorRatioTableMgr::ReLoad()
References Get, m_pkAttackArmorRatioTableMgr.
Referenced by TableMgr::ReloadTable.
AttackArmorRatioTableMgr::AttackArmorRatioTableMgr()
References Load.
Referenced by Get.
AttackArmorRatioTableMgr::~AttackArmorRatioTableMgr()
References m_kAttackArmorRatioTableMap.
const AttackArmorRatioTable * AttackArmorRatioTableMgr::GetAttackArmorRatioTable(unsigned int iTypeID)
References m_kAttackArmorRatioTableMap.
const std::map< unsigned int, AttackArmorRatioTable * > & AttackArmorRatioTableMgr::GetAttackArmorRatioTableMap()
References m_kAttackArmorRatioTableMap.
TableResArray AttackArmorRatioTableMgr::GetAttackArmorRatioTableVec()
References m_kAttackArmorRatioTableMap, TableResArray::pushBack.
bool AttackArmorRatioTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AttackArmorRatioTableMgr.
void AttackArmorRatioTableMgr::FillData(AttackArmorRatioTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AttackArmorRatioTable::fBuildingArmor, AttackArmorRatioTable::fHArmor, AttackArmorRatioTable::fHeroArmor, AttackArmorRatioTable::fLArmor, AttackArmorRatioTable::fMArmor, AttackArmorRatioTable::kName, m_kAttackArmorRatioTableMap, AttackArmorRatioTable::uiAttackTypeID.
Referenced by Load.