AchieveFinishMgr
AchieveMgr
std::map< DWord, std::map< DWord, SeAchieveFinishInfo * > > AchieveFinishMgr::m_FinishMap
Referenced by AddFinishAchieve, Finalize, GetLastTaskID, loadData, TryGetTaskReward.
SePlayer & AchieveFinishMgr::m_SePlayer
Referenced by getOwner.
SeDBCharAchieveFinish AchieveFinishMgr::m_TemData
Referenced by AddFinishAchieve.
AchieveFinishMgr::AchieveFinishMgr(SePlayer &m_Player)
AchieveFinishMgr::~AchieveFinishMgr()
DWord AchieveFinishMgr::GetLastTaskID(DWord dwGroupID)
References m_FinishMap.
SeAchieveAckCode AchieveFinishMgr::TryGetTaskReward(DWord dwGroupID, DWord dwAchieveID)
References ACHIEVE_REWARD_ALREADY_GET, ACHIEVE_REWARD_NOT_GET, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, SeAchieveFinishInfo::dwID, SeAchieveFinishInfo::dwStatus, g_kAchieveFinishStrategy, getOwner, m_FinishMap, SAAC_ALREADY_GET, SAAC_NOT_FINISH, SAAC_SUCCESS.
void AchieveFinishMgr::loadData(const SeDBCharAchieveFinish &data)
References AchievementTaskTableMgr::Get, AchievementTaskTableMgr::GetAchievementTaskTable, SeAchieveFinishInfo::loadData, m_FinishMap, AchievementTaskTable::uiTaskgroups.
SePlayer & AchieveFinishMgr::getOwner()
References m_SePlayer.
Referenced by AddFinishAchieve, TryGetTaskReward.
void AchieveFinishMgr::Finalize()
References m_FinishMap.
AchieveFinishMgr::AchieveFinishMgr(SePlayer &m_Player)
AchieveFinishMgr::~AchieveFinishMgr()
DWord AchieveFinishMgr::GetLastTaskID(DWord dwGroupID)
SeAchieveAckCode AchieveFinishMgr::TryGetTaskReward(DWord dwGroupID, DWord dwAchieveID)
void AchieveFinishMgr::loadData(const SeDBCharAchieveFinish &data)
SePlayer& AchieveFinishMgr::getOwner()
void AchieveFinishMgr::Finalize()
bool AchieveFinishMgr::AddFinishAchieve(DWord dwGroupID, DWord dwAchieveID)
References ComposeInfo, SeAchieveFinishInfo::DataInfo, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, g_kAchieveFinishStrategy, getOwner, m_FinishMap, m_TemData.
SeAchieveFinishInfo * AchieveFinishMgr::ComposeInfo(DWord dwID)
References ACHIEVE_REWARD_NOT_GET, SeAchieveFinishInfo::dwAchieveID, SeAchieveFinishInfo::dwID, SeAchieveFinishInfo::dwStatus, g_kAchieveFinishStrategy, PlayerDataStrategy::getGenID, NowTime, SeAchieveFinishInfo::skTime.
Referenced by AddFinishAchieve.
bool AchieveFinishMgr::AddFinishAchieve(DWord dwGroupID, DWord dwAchieveID)
SeAchieveFinishInfo* AchieveFinishMgr::ComposeInfo(DWord dwID)