AppendSkillPRTableMgr
std::map<std::string,AppendSkillPRTable*> AppendSkillPRTableMgr::m_kAppendSkillPRTableMap
Referenced by FillData, GetAppendSkillPRTable, GetAppendSkillPRTableMap, GetAppendSkillPRTableVec, ~AppendSkillPRTableMgr.
AppendSkillPRTableMgr * AppendSkillPRTableMgr::m_pkAppendSkillPRTableMgr
Referenced by Get, ReLoad.
AppendSkillPRTableMgr * AppendSkillPRTableMgr::Get()
References AppendSkillPRTableMgr, m_pkAppendSkillPRTableMgr.
Referenced by ReLoad.
AppendSkillPRTableMgr * AppendSkillPRTableMgr::ReLoad()
References Get, m_pkAppendSkillPRTableMgr.
AppendSkillPRTableMgr::AppendSkillPRTableMgr()
References Load.
Referenced by Get.
AppendSkillPRTableMgr::~AppendSkillPRTableMgr()
References m_kAppendSkillPRTableMap.
const AppendSkillPRTable * AppendSkillPRTableMgr::GetAppendSkillPRTable(const std::string &strTypeID)
References m_kAppendSkillPRTableMap.
const std::map< std::string, AppendSkillPRTable * > & AppendSkillPRTableMgr::GetAppendSkillPRTableMap()
References m_kAppendSkillPRTableMap.
TableResArray AppendSkillPRTableMgr::GetAppendSkillPRTableVec()
References m_kAppendSkillPRTableMap, TableResArray::pushBack.
bool AppendSkillPRTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AppendSkillPRTableMgr.
void AppendSkillPRTableMgr::FillData(AppendSkillPRTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AppendSkillPRTable::iRandomInterval1, AppendSkillPRTable::iRandomInterval10, AppendSkillPRTable::iRandomInterval2, AppendSkillPRTable::iRandomInterval3, AppendSkillPRTable::iRandomInterval4, AppendSkillPRTable::iRandomInterval5, AppendSkillPRTable::iRandomInterval6, AppendSkillPRTable::iRandomInterval7, AppendSkillPRTable::iRandomInterval8, AppendSkillPRTable::iRandomInterval9, AppendSkillPRTable::kAppendID, AppendSkillPRTable::kAppendName, AppendSkillPRTable::kDesc, m_kAppendSkillPRTableMap, AppendSkillPRTable::uiitemValue, AppendSkillPRTable::uiProperty.
Referenced by Load.