ActiveAvatarMgr
SePlayer & ActiveAvatarMgr::m_owner
Referenced by getOwner.
std::set< DWord > ActiveAvatarMgr::m_data
Referenced by fixData, getAvatars, loadData, sendInitData, setActiveAvatar, ~ActiveAvatarMgr.
ActiveAvatarMgr::ActiveAvatarMgr(SePlayer &owner)
ActiveAvatarMgr::~ActiveAvatarMgr()
References m_data.
void ActiveAvatarMgr::loadData(const SeDBCharActiveAvatar &item)
References m_data.
void ActiveAvatarMgr::fixData()
References ACTIVE_AVATAR_BEGIN, ACTIVE_AVATAR_END, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete, g_kCharActiveAvatarStrategy, CItemMgr::getItem, SePlayer::GetItemMgr, getOwner, HeroMgr::isValidAvatar, m_data.
void ActiveAvatarMgr::sendInitData()
References SeWT_ActiveAvatarNtf::avartars, g_kWorldServer, GetID, getOwner, GetTownSock, SeWT_ActiveAvatarNtf::iNum, m_data, WorldServer::SendWT_ActiveAvatarNtf.
Referenced by SePlayer::OperateLoading.
bool ActiveAvatarMgr::setActiveAvatar(bool active, DWord dwItemID)
References ACTIVE_AVATAR_BEGIN, ACTIVE_AVATAR_END, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataDelete, DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, g_kCharActiveAvatarStrategy, SePlayer::GetID, CItemMgr::getItem, SePlayer::GetItemMgr, getOwner, HeroMgr::isValidAvatar, m_data.
Referenced by BlockServer::ProcessTBL_SetActiveAvatarReq.
void ActiveAvatarMgr::getAvatars(VPtlAvatar &akAvatars)
References SePtlAvatar::dwItemID, SePtlAvatar::dwItemTypeID, CItemMgr::getItem, SePlayer::GetItemMgr, getOwner, m_data, CItem::uiID, CItem::uiItemID.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail.
ActiveAvatarMgr::ActiveAvatarMgr(SePlayer &owner)
ActiveAvatarMgr::~ActiveAvatarMgr()
void ActiveAvatarMgr::loadData(const SeDBCharActiveAvatar &item)
void ActiveAvatarMgr::fixData()
void ActiveAvatarMgr::sendInitData()
bool ActiveAvatarMgr::setActiveAvatar(bool active, DWord dwItemID)
void ActiveAvatarMgr::getAvatars(VPtlAvatar &akAvatars)
SePlayer & ActiveAvatarMgr::getOwner()
References m_owner.
Referenced by fixData, getAvatars, sendInitData, setActiveAvatar.
SePlayer& ActiveAvatarMgr::getOwner()