AppendCostTableMgr
std::map<unsigned int,AppendCostTable*> AppendCostTableMgr::m_kAppendCostTableMap
Referenced by FillData, GetAppendCostTable, GetAppendCostTableMap, GetAppendCostTableVec, ~AppendCostTableMgr.
std::map<int, AppendCostTable*> AppendCostTableMgr::m_kColorCostMap
Referenced by FillData, GetAppendCostTable.
AppendCostTableMgr * AppendCostTableMgr::m_pkAppendCostTableMgr
Referenced by Get, ReLoad.
AppendCostTableMgr * AppendCostTableMgr::Get()
References AppendCostTableMgr, m_pkAppendCostTableMgr.
Referenced by CItemMgr::ChangeCiTiao, GlobalTableMgr::GetAppendCostTable, TableMgr::LoadTable, ReLoad.
AppendCostTableMgr * AppendCostTableMgr::ReLoad()
References Get, m_pkAppendCostTableMgr.
Referenced by TableMgr::ReloadTable.
AppendCostTableMgr::AppendCostTableMgr()
References Load.
Referenced by Get.
AppendCostTableMgr::~AppendCostTableMgr()
References m_kAppendCostTableMap.
const AppendCostTable * AppendCostTableMgr::GetAppendCostTable(unsigned int iTypeID)
References m_kAppendCostTableMap.
Referenced by GlobalTableMgr::GetAppendCostTable.
const std::map< unsigned int, AppendCostTable * > & AppendCostTableMgr::GetAppendCostTableMap()
References m_kAppendCostTableMap.
TableResArray AppendCostTableMgr::GetAppendCostTableVec()
References m_kAppendCostTableMap, TableResArray::pushBack.
Referenced by CItemMgr::ChangeCiTiao.
const AppendCostTable * AppendCostTableMgr::GetAppendCostTable(int iColorLevel)
References m_kColorCostMap.
bool AppendCostTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AppendCostTableMgr.
void AppendCostTableMgr::FillData(AppendCostTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AppendCostTable::iLockCount, AppendCostTable::iMoneyCount, AppendCostTable::iRecastCount, m_kAppendCostTableMap, m_kColorCostMap, AppendCostTable::uiLocktItem, AppendCostTable::uiQualityType, AppendCostTable::uiRecastItem, AppendCostTable::uiTypeID.
Referenced by Load.