SeRaceRecord
int SeRaceRecord::m_iBufSize
Referenced by EraseSRCFrameCmd, ExpandBuffer, SeRaceRecord.
Byte* SeRaceRecord::m_pbyBuffer
Referenced by EraseSRCFrameCmd, ExpandBuffer, GenRacePack, GenRecordPack, GetRaceBigData, GetRaceCmd, GetRaceData, GetRacePack, PopRaceCmd, PrintCmdLog, PushRaceCmd, PushRaceData, PushRacePack, SaveToFile, SeRaceRecord, ~SeRaceRecord.
int SeRaceRecord::m_iCurPos
Referenced by Clear, EraseSRCFrameCmd, ExpandBuffer, GenRacePack, GenRecordPack, GetDataSize, GetRaceCmd, GetRacePack, OnHostStop, PopRaceCmd, PushRaceCmd, PushRaceData, PushRacePack, ResetSM, SeRaceRecord.
int SeRaceRecord::m_iLastPos
Referenced by Clear, DragToTime, EraseSRCFrameCmd, ExpandBuffer, GenRacePack, GenRecordPack, GetLastPos, GetReconOffPosByTime, OnHostStop, ProcessCmdInfo, PushRaceData, PushRacePack, ResetSM, SeRaceRecord, SetLastPos.
unsigned int SeRaceRecord::m_dwPackIndex
Referenced by Clear, GenRacePack, GenRecordPack, GetLastPackIndex, GetRacePack, OnHostStart, OnHostStop, PushRacePack, ResetSM, SeRaceRecord.
SePackInfo SeRaceRecord::m_akPackInfo[HOLD_MAX_PACK][HOLD_MAX_PACK]
Referenced by Clear, GenRacePack, GenRecordPack, GetRacePack, OnHostStop, PushRacePack, SeRaceRecord.
bool SeRaceRecord::m_bHostSvr
Referenced by Clear, GenRacePack, GenRecordPack, IsHostSvr, OnHostStart, OnHostStop, PushRaceCmd, PushRacePack, ResetSM, SeRaceRecord, SetHostSvr, Update.
unsigned int SeRaceRecord::m_dwFrame
Referenced by Clear, DragToTime, GenRacePack, GetCurrentFrame, GetLastFrame, GetRacePack, IncreaseLastFrame, JumpToSpecialFrame, OnHostStart, OnHostStop, PushRaceCmd, PushRaceData, PushRacePack, ResetSM, SaveToFile, SeRaceRecord, SetLastFrame, Update, UpdateTimer.
unsigned int SeRaceRecord::m_dwLastTime
Referenced by Clear, OnHostStart, OnHostStop, ResetSM, SeRaceRecord, Update.
unsigned int SeRaceRecord::m_dwLeaveTime
Referenced by Clear, OnHostStart, ResetSM, SeRaceRecord, Update.
SeRaceFrame SeRaceRecord::m_kTmpRaceHead
Referenced by GenRacePack, GetRacePack.
SeRacePack SeRaceRecord::m_kTmpRacePack
Referenced by GenRacePack, GenRecordPack, GetRacePack.
int SeRaceRecord::m_iCurCmd
Referenced by Clear, DragToTime, EraseSRCFrameCmd, ExpandBuffer, GetRaceCmd, JumpToSpecialFrame, OnHostStop, PopRaceCmd, ResetSM, SeRaceRecord.
int SeRaceRecord::m_iCurSize
Referenced by Clear, DragToTime, EraseSRCFrameCmd, GetRaceCmd, JumpToSpecialFrame, PopRaceCmd, ResetSM, SeRaceRecord.
std::vector<SePlayerInfoSeat> SeRaceRecord::m_kPlayerInfo
Referenced by GetPlayerInfo, GetReplayInfo, LoadFromFile, ProcessCmdInfo, PushRacePack, SaveToFile, SetPlayerInfo.
float SeRaceRecord::m_fTimeScale
Referenced by Clear, GetTimeScale, ResetSM, SeRaceRecord, SetTimeScale, UpdateTimer.
float SeRaceRecord::m_fTimer
Referenced by Clear, DragToTime, GetCurrentFrame, JumpToSpecialFrame, ResetSM, SeRaceRecord, UpdateTimer.
bool SeRaceRecord::m_bWatch
Referenced by Clear, GetCurrentFrame, IsWatching, ResetSM, SeRaceRecord, SetWatch, UpdateTimer.
unsigned int SeRaceRecord::m_dwLastUpdateTime
Referenced by Clear, DragToTime, GetCurrentFrame, JumpToSpecialFrame, ResetSM, SeRaceRecord.
bool SeRaceRecord::m_bRaceEnd
Referenced by Clear, IsRaceEnd, ResetSM, SeRaceRecord, SetRaceEnd.
bool SeRaceRecord::m_bRecon
Referenced by Clear, IsRecon, ResetSM, SeRaceRecord, SetRecon.
bool SeRaceRecord::m_bCanCancelRecon
Referenced by CanCancelRecon, Clear, ResetSM, SeRaceRecord, SetCanCancelRecon.
bool SeRaceRecord::m_bIsServerMode
Referenced by IsServerMode, PushRaceData, SeRaceRecord, SetServerMode.
unsigned int SeRaceRecord::m_dwPlayerID
Referenced by SeRaceRecord.
bool SeRaceRecord::m_bExpandBufNoLimit
Referenced by ExpandBuffer, SeRaceRecord, SetExpandBufNoLimit.
std::vector<int> SeRaceRecord::m_aiReconDataOffPos
Referenced by Clear, DragToTime, GetReconOffPosByTime, SetReconOffPos.
SeReplayInfo SeRaceRecord::m_kReplayInfo
Referenced by GetReplayInfo.
DWord SeRaceRecord::m_dwMapID
Referenced by Clear, SaveToFile, SeRaceRecord, SetMapID.
std::ofstream SeRaceRecord::m_ClientWatchLogFile
Referenced by LoadFromFile, PushRaceData.
bool SeRaceRecord::m_bJump
Referenced by JumpToSpecialFrame, UpdateTimer.
unsigned int SeRaceRecord::m_dwJumpFrame
Referenced by JumpToSpecialFrame, UpdateTimer.
std::vector<RecordLabel> SeRaceRecord::m_vecRecordLabel
Referenced by Clear, LoadFromFile, ProcessRecordLabel, PushRecordLable.
std::vector<RecordReport> SeRaceRecord::m_vecRecordReport
Referenced by GetRecordReport, LoadReplayReportFromFile, PushRecordReport, ResetSM, SaveReplayReportToFile.
SeRaceRecord::SeRaceRecord(void)
References HOLD_MAX_PACK, m_akPackInfo, m_bCanCancelRecon, m_bExpandBufNoLimit, m_bHostSvr, m_bIsServerMode, m_bRaceEnd, m_bRecon, m_bWatch, m_dwFrame, m_dwLastTime, m_dwLastUpdateTime, m_dwLeaveTime, m_dwMapID, m_dwPackIndex, m_dwPlayerID, m_fTimer, m_fTimeScale, m_iBufSize, m_iCurCmd, m_iCurPos, m_iCurSize, m_iLastPos, m_pbyBuffer.
SeRaceRecord::~SeRaceRecord(void)
References m_pbyBuffer.
void SeRaceRecord::Update(unsigned int dwCurTime, unsigned int dwLimitTime=-1)
References GAME_FRAME_TIME, m_bHostSvr, m_dwFrame, m_dwLastTime, m_dwLeaveTime.
Referenced by SeRaceMgr::UpdateRace.
bool SeRaceRecord::OnHostStart(unsigned int dwCurTime, unsigned int dwPackIndex, unsigned int dwFrame)
References m_bHostSvr, m_dwFrame, m_dwLastTime, m_dwLeaveTime, m_dwPackIndex.
Referenced by SeRaceMgr::CreateRobotRace, SeRaceMgr::OnRaceModeEnd, SeRaceMgr::UpdateLoadEnd.
bool SeRaceRecord::OnHostStop(bool bClearStream)
References HOLD_MAX_PACK, m_akPackInfo, m_bHostSvr, m_dwFrame, m_dwLastTime, m_dwPackIndex, m_iCurCmd, m_iCurPos, m_iLastPos.
void SeRaceRecord::PushRecordLable(RecordLabel &label)
References m_vecRecordLabel.
void SeRaceRecord::PushRecordReport(RecordReport &report)
References m_vecRecordReport.
Referenced by SeRaceMgr::OnPlayerRaceReplayReport.
bool SeRaceRecord::PushRaceCmd(const void *pkData, int iSize)
References SeRaceCmd::dwCmd, SeRaceCmd::dwFrame, ExpandBuffer, GetRaceCmdSize, m_bHostSvr, m_dwFrame, m_iCurPos, m_pbyBuffer, ProcessCmdInfo, SRC_FRAME.
Referenced by SeRaceMgr::CreateRobotRace, SeRaceMgr::OnPlayerGuanqiaEnd, SeRaceMgr::OnPlayerRaceCmd, SeRaceMgr::OnPlayerRaceEnd, SeRaceMgr::OnRaceModeEnd, SeRaceMgr::UpdateLoadEnd, SeRaceMgr::UpdateReconEnd.
SeRacePack * SeRaceRecord::GenRacePack(SeRacePauseState ePauseState, bool &bSynFrame)
References SeRaceCmd::dwCmd, SeRaceCmd::dwFrame, SeRacePack::dwPackIndex, SePackInfo::dwPackIndex, SeRaceCmd::dwQueue, SeRaceCmd::dwSeat, HOLD_MAX_PACK, SePackInfo::iParam, SeRacePack::iSize, SePackInfo::iSize, m_akPackInfo, m_bHostSvr, m_dwFrame, m_dwPackIndex, m_iCurPos, m_iLastPos, m_kTmpRaceHead, m_kTmpRacePack, m_pbyBuffer, SeRacePack::pkData, SRC_FRAME.
Referenced by SeRaceMgr::UpdateRace.
bool SeRaceRecord::PushRaceData(const void *pkData, int iSize, int iCount=0, bool bRecordMode=false)
References ConvCmdName, SeRaceCmd::dwCmd, SeRaceCmd::dwFrame, ExpandBuffer, GetRaceCmdSize, m_bIsServerMode, m_ClientWatchLogFile, m_dwFrame, m_iCurPos, m_iLastPos, m_pbyBuffer, ProcessCmdInfo, ProcessRecordLabel.
Referenced by LoadFromFile, SeRaceMgr::OnSvrRaceSvrModelPack, WatchServer::CSeRaceMgr::pushRaceData.
bool SeRaceRecord::PushRacePack(unsigned int dwPackIndex, void *pkData, int iSize)
References SeRacePlayerInfo::akSeat, CanCancelRecon, SeRaceCmd::dwCmd, SeRaceCmd::dwFrame, SePackInfo::dwPackIndex, ExpandBuffer, GetRaceCmdSize, HOLD_MAX_PACK, SeRacePlayerInfo::iNum, SePackInfo::iParam, SePackInfo::iSize, IsRecon, m_akPackInfo, m_bHostSvr, m_dwFrame, m_dwPackIndex, m_iCurPos, m_iLastPos, m_kPlayerInfo, m_pbyBuffer, ProcessCmdInfo, SetRecon, SRC_PLAYER_INFO.
Referenced by SeRaceMgr::CreateRobotRace, SeRaceMgr::OnRaceModeEnd.
SeRacePack * SeRaceRecord::GetRacePack(unsigned int dwPackIndex)
References SeRaceCmd::dwCmd, SeRaceCmd::dwFrame, SeRacePack::dwPackIndex, SePackInfo::dwPackIndex, SeRaceCmd::dwQueue, SeRaceCmd::dwSeat, HOLD_MAX_PACK, SePackInfo::iParam, SeRacePack::iSize, SePackInfo::iSize, m_akPackInfo, m_dwFrame, m_dwPackIndex, m_iCurPos, m_kTmpRaceHead, m_kTmpRacePack, m_pbyBuffer, SeRacePack::pkData, SRC_FRAME.
unsigned int SeRaceRecord::GetLastPackIndex(void)
References m_dwPackIndex.
unsigned int SeRaceRecord::GetCurrentFrame(void)
References GAME_FRAME_TIME, m_bWatch, m_dwFrame, m_dwLastUpdateTime, m_fTimer, UpdateTimer.
Referenced by JumpToSpecialFrame, SeRaceMgr::OnPlayerRaceCmd, SeRaceMgr::UpdateLoadEnd.
unsigned int SeRaceRecord::GetLastFrame(void)
References m_dwFrame.
Referenced by WatchServer::CSeRaceMgr::CheckWatchRace, WatchServer::CSeRaceMgr::getRaceViewInfos, SeRaceMgr::UpdateReconBegin, WatchServer::CSeRaceMgr::updateView, SeRaceMgr::UpdateView.
void SeRaceRecord::IncreaseLastFrame(void)
References m_dwFrame.
bool SeRaceRecord::IsHostSvr(void)
References m_bHostSvr.
SeRaceCmd * SeRaceRecord::GetRaceCmd(void) const
References GetRaceCmdSize, m_iCurCmd, m_iCurPos, m_iCurSize, m_pbyBuffer.
Referenced by EraseSRCFrameCmd, JumpToSpecialFrame, SeRaceMgr::UpdateReconBegin, WatchServer::CSeRaceMgr::updateView, SeRaceMgr::UpdateView.
void SeRaceRecord::PopRaceCmd(void)
References GetRaceCmdSize, m_iCurCmd, m_iCurPos, m_iCurSize, m_pbyBuffer.
Referenced by EraseSRCFrameCmd, JumpToSpecialFrame.
int SeRaceRecord::GetDataSize(int iOffset) const
References m_iCurPos.
Referenced by GetRaceBigData, GetRaceCmd, GetRaceData, WatchServer::CSeRaceMgr::getRaceViewInfos, PrintCmdLog, SaveToFile, SeRaceMgr::UpdateReconBegin, WatchServer::CSeRaceMgr::updateView, SeRaceMgr::UpdateView.
int SeRaceRecord::GetRaceBigData(int iOffset, void *pkBuf, int iBufSize)
References GetDataSize, m_pbyBuffer, MemCpy.
int SeRaceRecord::GetRaceData(int iOffset, void *pkBuf, int iBufSize)
References GetDataSize, m_pbyBuffer, MemCpy.
SeRaceCmd * SeRaceRecord::GetRaceCmd(int iOffset, int &iCmdSize) const
References GetDataSize, GetRaceCmdSize, m_pbyBuffer.
void SeRaceRecord::EraseSRCFrameCmd()
References SeRaceCmd::dwCmd, GetRaceCmd, GetRaceCmdSize, m_iBufSize, m_iCurCmd, m_iCurPos, m_iCurSize, m_iLastPos, m_pbyBuffer, PopRaceCmd, SAFE_ARRAY_DELETE, SRC_FRAME.
void SeRaceRecord::Clear(void)
References HOLD_MAX_PACK, m_aiReconDataOffPos, m_akPackInfo, m_bCanCancelRecon, m_bHostSvr, m_bRaceEnd, m_bRecon, m_bWatch, m_dwFrame, m_dwLastTime, m_dwLastUpdateTime, m_dwLeaveTime, m_dwMapID, m_dwPackIndex, m_fTimer, m_fTimeScale, m_iCurCmd, m_iCurPos, m_iCurSize, m_iLastPos, m_vecRecordLabel.
Referenced by LoadFromFile, WatchServer::SeRace::~SeRace.
void SeRaceRecord::ResetSM()
References m_bCanCancelRecon, m_bHostSvr, m_bRaceEnd, m_bRecon, m_bWatch, m_dwFrame, m_dwLastTime, m_dwLastUpdateTime, m_dwLeaveTime, m_dwPackIndex, m_fTimer, m_fTimeScale, m_iCurCmd, m_iCurPos, m_iCurSize, m_iLastPos, m_vecRecordReport.
const std::vector< SePlayerInfoSeat > & SeRaceRecord::GetPlayerInfo(void) const
References m_kPlayerInfo.
Referenced by WatchServer::CSeRaceMgr::BeginView, SeRaceMgr::UpdateView.
void SeRaceRecord::SetPlayerInfo(const std::vector< SePlayerInfoSeat > &rkPlayerInfo)
References m_kPlayerInfo.
Referenced by WatchServer::CSeRaceMgr::onRaceStart.
void SeRaceRecord::SetTimeScale(float fScale)
References fScale, m_fTimeScale.
float SeRaceRecord::GetTimeScale()
References m_fTimeScale.
void SeRaceRecord::UpdateTimer(int iDeltTime)
References GAME_FRAME_TIME, m_bJump, m_bWatch, m_dwFrame, m_dwJumpFrame, m_fTimer, m_fTimeScale.
Referenced by GetCurrentFrame.
void SeRaceRecord::SetWatch(bool bWatch=true)
References m_bWatch.
bool SeRaceRecord::SaveToFile(const char *pcFileName, unsigned int dwLogicVer, const char *pcLogFileName=NULL) const
References SeRecorderHead::acSaveTime, SeRecorderHead::dwFileSize, SeRecorderHead::dwGameTime, SeRecorderHead::dwLogicVer, SeRecorderHead::dwMapID, GAME_FRAME_TIME, GetDataSize, SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iYear, m_dwFrame, m_dwMapID, m_kPlayerInfo, m_pbyBuffer, NowTime, PrintCmdLog.
Referenced by SeRaceMgr::SaveAllRaceRecord, SeRaceRecordSaveThread::saveRecord, WatchServer::SeRaceRecordSaveThread::saveRecord.
void SeRaceRecord::PrintCmdLog(const char *pcFileName) const
References ConvCmdName, SeRaceCmd::dwCmd, SeRaceCmd::dwFrame, GetDataSize, GetRaceCmdSize, m_pbyBuffer.
Referenced by SaveToFile.
bool SeRaceRecord::SaveReplayReportToFile(const char *pcFileName, unsigned int dwLogicVer) const
References m_vecRecordReport.
Referenced by SeRaceRecordSaveThread::saveRecord.
bool SeRaceRecord::LoadReplayReportFromFile(const char *pcFileName, unsigned int dwLogicVer)
References makeCallback.f, RecordReport::fCameraX, RecordReport::fCameraY, RecordReport::iReportFrame, RecordReport::iSeat, m_vecRecordReport, RecordReport::strMsg.
void SeRaceRecord::SetRaceEnd(bool bRaceEnd)
References m_bRaceEnd.
Referenced by LoadFromFile.
bool SeRaceRecord::LoadFromFile(const char *pcFileName, unsigned int dwLogicVer)
References Clear, m_ClientWatchLogFile, m_kPlayerInfo, m_vecRecordLabel, PushRaceData, SetRaceEnd.
void SeRaceRecord::SetLastFrame(unsigned int dwFrame)
References m_dwFrame.
bool SeRaceRecord::IsRaceEnd(void) const
References m_bRaceEnd.
void SeRaceRecord::SetRecon(bool bRecon)
References m_bRecon.
Referenced by PushRacePack.
bool SeRaceRecord::IsRecon()
References m_bRecon.
Referenced by PushRacePack.
void SeRaceRecord::SetCanCancelRecon(bool bCanCancel)
References m_bCanCancelRecon.
bool SeRaceRecord::CanCancelRecon()
References m_bCanCancelRecon.
Referenced by PushRacePack.
int SeRaceRecord::GetLastPos() const
References m_iLastPos.
Referenced by SeRaceMgr::UpdateReconBegin, WatchServer::CSeRaceMgr::updateView, SeRaceMgr::UpdateView.
void SeRaceRecord::SetHostSvr(bool bHostSvr)
References m_bHostSvr.
void SeRaceRecord::SetServerMode(bool bServerMode)
References m_bIsServerMode.
Referenced by WatchServer::CSeRaceMgr::onRaceStart, ProcessCmdInfo.
bool SeRaceRecord::IsServerMode()
References m_bIsServerMode.
SeRacePack * SeRaceRecord::GenRecordPack(void)
References SeRacePack::dwPackIndex, SePackInfo::dwPackIndex, HOLD_MAX_PACK, SePackInfo::iParam, SeRacePack::iSize, SePackInfo::iSize, m_akPackInfo, m_bHostSvr, m_dwPackIndex, m_iCurPos, m_iLastPos, m_kTmpRacePack, m_pbyBuffer, SeRacePack::pkData.
void SeRaceRecord::SetExpandBufNoLimit(bool bNoLimit)
References m_bExpandBufNoLimit.
void SeRaceRecord::SetReconOffPos(int iOffPos)
References m_aiReconDataOffPos.
Referenced by ProcessCmdInfo.
void SeRaceRecord::SetLastPos(int iLastPos)
References m_iLastPos.
int SeRaceRecord::GetReconOffPosByTime(DWord dwGameTime)
References m_aiReconDataOffPos, m_iLastPos, SAVE_RECON_DATA_TIME.
int SeRaceRecord::DragToTime(DWord dwGameTime)
References GAME_FRAME_TIME, m_aiReconDataOffPos, m_dwFrame, m_dwLastUpdateTime, m_fTimer, m_iCurCmd, m_iCurSize, m_iLastPos, SAVE_RECON_DATA_TIME.
bool SeRaceRecord::IsWatching()
References m_bWatch.
const SeReplayInfo & SeRaceRecord::GetReplayInfo(const char *acReplayFile)
References SeReplayInfo::acName, SePlayerInfoSeat::acName, SeReplayInfo::acSaveTime, SeRecorderHead::acSaveTime, SeReplayInfo::dwGameTime, SeRecorderHead::dwGameTime, SeRecorderHead::dwLogicVer, SeReplayInfo::dwMapID, SeRecorderHead::dwMapID, SeReplayInfo::dwPlayerID, SePlayerInfoSeat::dwPlayerID, SeReplayInfo::iPlayerNum, SeReplayInfo::iRead, SeReplayInfo::iSeatIndex, SePlayerInfoSeat::iSeatIndex, LOGIC_VERSION, m_kPlayerInfo, m_kReplayInfo, StrCpy, SeReplayInfo::uiScore, SePlayerInfoSeat::uiScore.
const std::vector< RecordReport > & SeRaceRecord::GetRecordReport() const
References m_vecRecordReport.
void SeRaceRecord::ProcessCmdInfo(const SeRaceCmd *pkCmd)
References SeRacePlayerInfo::akSeat, SeRacePlayerInfo::bIsServerMode, SeRaceLoad::bIsServerMode, SeRaceCmd::dwCmd, SeRaceLoad::iMapID, SeRacePlayerInfo::iNum, m_iLastPos, m_kPlayerInfo, SetMapID, SetReconOffPos, SetServerMode, SRC_LOAD, SRC_PLAYER_INFO, SRC_SAVE_RECONDATA_BEGIN.
Referenced by PushRaceCmd, PushRaceData, PushRacePack.
void SeRaceRecord::SetMapID(DWord dwMapID)
References m_dwMapID.
Referenced by ProcessCmdInfo.
bool SeRaceRecord::JumpToSpecialFrame(unsigned int dwFrame)
References SeRaceCmd::dwFrame, GAME_FRAME_TIME, GetCurrentFrame, GetRaceCmd, m_bJump, m_dwFrame, m_dwJumpFrame, m_dwLastUpdateTime, m_fTimer, m_iCurCmd, m_iCurSize, PopRaceCmd.
void SeRaceRecord::ProcessRecordLabel(SeRaceCmd *pkRaceCmd, int iCmdSize)
References SePureRaceCmd::acData, SeNetStream::Attach, SeRaceCmd::dwCmd, SePureRaceCmd::iDataSize, m_vecRecordLabel, Read, SPRCT_RECORD_LABEL.
Referenced by PushRaceData.
bool SeRaceRecord::ReadRecordHead(const char *pcFileName, unsigned int dwLogicVer, SeRecorderHead &OutRecordHead)
bool SeRaceRecord::VerifyRecordFile(const unsigned char *pContent, int iSize)
References SeRecorderHead::acFileType, SeRecorderHead::dwFileSize.
bool SeRaceRecord::VerifyRecordReportFile(const unsigned char *pContent, int iSize)
bool SeRaceRecord::ExpandBuffer(int iSize)
References m_bExpandBufNoLimit, m_iBufSize, m_iCurCmd, m_iCurPos, m_iLastPos, m_pbyBuffer.
Referenced by PushRaceCmd, PushRaceData, PushRacePack.