BlockServer
char BlockServer::m_acSend[SSD_SEND_SIZE]
Referenced by BlockServer.
DWord BlockServer::m_dwTickCount
Referenced by BlockServer, Update.
DWord BlockServer::m_dwCurTime
Referenced by BlockServer, GetServerTime, Update.
SeThreadMsgMgr BlockServer::m_kThreadMsgMgr
Referenced by Initialize, PushMsg, Update.
bool BlockServer::m_bStop
Referenced by BlockServer, DoWork, Finialize, Update.
MapAllWaitPlayer BlockServer::m_kWaitPlayer
Referenced by DelWaitPlayer, Finialize, GetWaitPlayer, ProcessWBL_AccountLogin, ProcessWBL_PlayerValidate, UpdateWaitPlayer, WaitPlayerInfoAssign.
MapAllPlayer BlockServer::m_kAllPlayer
Referenced by Finialize, GetAllPlayer, GetPlayer, KickPlayerByID, ProcessWBL_HasDBError, ProcessWBL_LoadPlayerInfoAgain, ProcessWBL_PlayerValidate, UpdatePlayer.
DWord BlockServer::m_dwCheckPlayerTime
Referenced by BlockServer, UpdatePlayer.
DWord BlockServer::m_dwCheckTime
Referenced by BlockServer, UpdateWaitPlayer.
SeLeagueInfo BlockServer::m_kLeagueInfo
Referenced by ProcessWBL_UpdateLeagueInfo.
int BlockServer::m_iLogShowType
Referenced by BlockServer, GetLogShowType, SetLogShowType.
BlockServer::BlockServer(void)
References m_acSend, m_bStop, m_dwCheckPlayerTime, m_dwCheckTime, m_dwCurTime, m_dwTickCount, m_iLogShowType.
BlockServer::~BlockServer(void)
References Finialize.
bool BlockServer::Initialize(int iBaseBuffSize=4 *1024 *1024)
References SeThreadMsgMgr::Initialize, m_kThreadMsgMgr.
Referenced by WorldServer::Initialize.
void BlockServer::Update(void)
References SeMsgData::abyData, SeBlockCMD::connectID, g_kWorldServer, WorldServer::IsException, SeMsgData::iSize, m_bStop, m_dwCurTime, m_dwTickCount, m_kThreadMsgMgr, MyExceptionFilter, SeThreadMsgMgr::PopMsg, ProcessBBLData, ProcessMBLData, ProcessNBLData, ProcessRBLData, ProcessTBLData, ProcessWBLData, SeLogError, WorldServer::SetException, STCB_BS_BLS, STCB_INTERVAL, STCB_MS_BLS, STCB_NS_BLS, STCB_RS_BLS, STCB_TS_BLS, STCB_WS_BLS, UpdatePlayer, UpdateWaitPlayer, SeBlockCMD::wCmd.
Referenced by DoWork.
void BlockServer::Finialize(void)
References SePlayer::Finalize, m_bStop, m_kAllPlayer, m_kWaitPlayer.
Referenced by WorldServer::Finialize, ~BlockServer.
SePlayer * BlockServer::GetPlayer(DWord dwPlayerID, bool bNeedComplete=true)
References SePlayer::IsLoadComplete, m_kAllPlayer.
Referenced by ProcessBBL_PlayerLoadRet, ProcessBBL_SelectDataRet, ProcessBBL_SelectFriendDataRet, ProcessMBL_BlockRoomInvite, ProcessMBL_GetPlayerMatchValue, ProcessMBL_RaceMatchLoadDetail, ProcessRBL_AwardItemNtf, ProcessRBL_DecRespawnItemNtf, ProcessRBL_RaceEndArenaBaseInfoSync, ProcessRBL_SelectHeroReq, ProcessRBL_SetAvatarNtf, ProcessRBL_SetEquipSetNtf, ProcessRBL_SetRaceMapHeroNtf, ProcessRBL_UpdateScore, ProcessRBL_UserRaceMapNtf, ProcessTBL_ClearItemNewFlag, ProcessTBL_DelelteItem, ProcessTBL_FriendLadderInfoReq, ProcessTBL_GMAddItem, ProcessTBL_GMSetDiamond, ProcessTBL_GMSetGold, ProcessTBL_LadderDetailInfoReq, ProcessTBL_LadderRankQueryReq, ProcessTBL_OpenRandBox, ProcessTBL_PutOnEquip, ProcessTBL_ReqItemCiTiaoChange, ProcessTBL_ReqItemDepart, ProcessTBL_ReqItemStrenth, ProcessTBL_SetActiveAvatarReq, ProcessTBL_TakeOffEquip, ProcessTBL_UserAlterAvatarFrameReq, ProcessTBL_UserAlterAvatarReq, ProcessTBL_UserAlterNickNameReq, ProcessTBL_UserMapRaceHeroReq, ProcessTBL_UserPurchaseAvatarReq, ProcessTBL_UserRaceMapDetailReq, ProcessWBL_BuyShopItem, ProcessWBL_CharAddRet, ProcessWBL_CreateChar, ProcessWBL_CreateNexusFriend, ProcessWBL_DelNexusFriend, ProcessWBL_GetItemGM, ProcessWBL_ItemExchange, ProcessWBL_LoadPlayerInfoAgain, ProcessWBL_MatchRaceLoad, ProcessWBL_PlayerLeave, ProcessWBL_PlayerRenameBegin, ProcessWBL_PlayerRenameEnd, ProcessWBL_PlayerValidate, ProcessWBL_PlayerValidateEnd, ProcessWBL_RaceEndGuanka, ProcessWBL_RaceEndRace, ProcessWBL_ShopItemGM, ProcessWBL_ShowNotice, ProcessWBL_UpdateNexusFriend, ProcessWBL_UserAlterNickNameReq, SeBSProcess_CharMemoryLoad, SeBSProcess_CharNexusFriend, SeBSProcess_LoadFriendLadderInfo.
bool BlockServer::PushMsg(void *pkData, int iSize)
References m_kThreadMsgMgr, SeThreadMsgMgr::PushMsg.
Referenced by WorldServer::PushThreadMsg, WorldServer::PushThreadMsgByNum.
DWord BlockServer::GetServerTime(void)
References m_dwCurTime.
Referenced by SePlayer::DisplayLoadConsumeTime, ProcessWBL_AccountLogin, ProcessWBL_LoadPlayerInfoAgain, ProcessWBL_PlayerValidateEnd, UpdatePlayer, UpdateWaitPlayer, WaitPlayerInfoAssign.
MapAllPlayer & BlockServer::GetAllPlayer(void)
References m_kAllPlayer.
SeWaitPlayer * BlockServer::GetWaitPlayer(DWord dwPlayerID)
References m_kWaitPlayer.
Referenced by ProcessWBL_AccountLogin.
void BlockServer::DelWaitPlayer(DWord dwPlayerID)
References m_kWaitPlayer.
Referenced by KickPlayerByID, ProcessWBL_LoadPlayerInfoAgain.
void BlockServer::OnPlayerLeave(DWord dwPlayerID, bool bExitGame, bool bSendLeave=true)
Referenced by ProcessWBL_LoadPlayerInfoAgain, ProcessWBL_PlayerLeave, ProcessWBL_PlayerValidateEnd.
void BlockServer::KickPlayerByID(DWord dwPlayerID, bool bLoginKick, bool bSysKick=false)
References DelWaitPlayer, SePlayer::Finalize, g_kWorldServer, SePlayer::GetID, SePlayer::GetName, SePlayer::GetTownIndex, SePlayer::GetTownSock, SePlayer::IsLoadComplete, m_kAllPlayer, SAFE_DELETE, SendBLW_PlayerLeave, WorldServer::SendWB_PlayerOffLine, WorldServer::SendWT_KickPlayer, SNT_NULL, SSD_MAX_CHAR_NAME, StrCpy, SePlayer::UpdateOnlineTime, WaitPlayerInfoAssign.
Referenced by ProcessWBL_KickPlayerByID.
void BlockServer::WaitPlayerInfoAssign(SePlayer *pkPlayer, SeWaitPlayer *pkWaitPlayer, bool bKicked)
References SeWaitPlayer::dwPlayerID, SeWaitPlayer::dwSessionID, SeWaitPlayer::dwWaitTime, SePlayer::GetAccountInfo, SePlayer::GetID, GetServerTime, SePlayer::GetSessionID, SeWaitPlayer::kAccountInfo, m_kWaitPlayer.
Referenced by KickPlayerByID.
void BlockServer::SetLogShowType(int iLogShowType)
References m_iLogShowType.
Referenced by ProcessWBL_BlockSetup.
int BlockServer::GetLogShowType(void)
References m_iLogShowType.
Referenced by SePlayer::DisplayLoadConsumeTime.
void BlockServer::GetRaceDropChanceID(DWord dwMapID, int iRaceEndFlag, int iDifficulty, VecDWord &rkVChanceID)
References RacedropTableMgr::Get, RacedropTableMgr::GetRacedropTableMap, RACEDROP_PRIZECOND_LOSE, RACEDROP_PRIZECOND_WIN, SROT_RRESULT_FINISHED_FAILED, SROT_RRESULT_FINISHED_SUCCES, RacedropTable::uiChanceID, RacedropTable::uiDifficulty, RacedropTable::uiMapID, RacedropTable::uiPrizeCond.
void BlockServer::CheckTaskRace(SePlayer *pkPlayer, const SeWSRaceSendInfo &rkInfo)
References SeRaceSendInfo::bAssist, SeRaceSendInfo::bBear, SeRaceSendInfo::bBestHero, SeRaceSendInfo::bDamage, SeRaceSendInfo::bKill, SeRaceSendInfo::bOutput, SeRaceSendInfo::bRich, SeRaceSendInfo::bSoul, SeRaceSendInfo::bTeamwork, SeRaceSendInfo::dwHeroTypeID, SeWSRaceSendInfo::dwMapID, SeWSRaceSendInfo::dwRaceTime, HeroInfoTableMgr::Get, SePlayer::GetCharLevel, HeroInfoTableMgr::GetHeroInfoTable, SePlayer::getTaskMgr, HEROINFO_FENLEI_ARCHER, HEROINFO_FENLEI_ASSASIN, HEROINFO_FENLEI_FUZHU, HEROINFO_FENLEI_MAGE, HEROINFO_FENLEI_TANK, HEROINFO_FENLEI_ZHANSHI, SeRaceSendInfo::iAssistanceNums, SeRaceSendInfo::iComboMaxKills, SeRaceSendInfo::iDeathNums, SeRaceSendInfo::iGold, SeRaceSendInfo::iKilledBuild, SeRaceSendInfo::iKillHeroNums, SeRaceSendInfo::iRaceEndFlag, SePlayer::IsLoadComplete, SeRaceSendInfo::iTeamBeKill, SeWSRaceSendInfo::iTeamMemberNum, SeWSRaceSendInfo::kInfo, TaskMgr::SettleTask, SROT_RRESULT_FINISHED_SUCCES, SROT_RRESULT_GIVEUP, SROT_RRESULT_INVILAD, TASKINFO_CONDITON_CANTUAN, TASKINFO_CONDITON_CANYUYOUXI, TASKINFO_CONDITON_CHENGSHANG, TASKINFO_CONDITON_CUIHUIFANGYUTA, TASKINFO_CONDITON_DUIWUWUSIWANGTONGGUAN, TASKINFO_CONDITON_FUJIA, TASKINFO_CONDITON_GETGOLD, TASKINFO_CONDITON_GUDAN, TASKINFO_CONDITON_JISHA, TASKINFO_CONDITON_LIANSHA, TASKINFO_CONDITON_LIANXUSHENGLI, TASKINFO_CONDITON_MVP, TASKINFO_CONDITON_POFANG, TASKINFO_CONDITON_SHENZHU, TASKINFO_CONDITON_SHIYONGA, TASKINFO_CONDITON_SHIYONGB, TASKINFO_CONDITON_SHIYONGC, TASKINFO_CONDITON_SHIYONGD, TASKINFO_CONDITON_SHIYONGE, TASKINFO_CONDITON_SHOUSHENG, TASKINFO_CONDITON_SHUCHU, TASKINFO_CONDITON_TEAMJOIN, TASKINFO_CONDITON_TEAMMATCHINGWIN, TASKINFO_CONDITON_TIANTILIANXUSHENGLI, TASKINFO_CONDITON_TIANTISHENGLI, TASKINFO_CONDITON_TONGGUANDITU, TASKINFO_CONDITON_WANCHENGZHANGJIE, TASKINFO_CONDITON_WINA, TASKINFO_CONDITON_WINB, TASKINFO_CONDITON_WINC, TASKINFO_CONDITON_WIND, TASKINFO_CONDITON_WINE, TASKINFO_CONDITON_ZHANGHAODENGJI, TASKINFO_CONDITON_ZHANJIANG, TASKINFO_CONDITON_ZHIDINGSHIJIANTONGGUAN, TASKINFO_CONDITON_ZHUGONG, TASKINFO_CONDITON_ZIJIWUSIWANGTONGGUAN, TASKINFO_CONDITON_ZUDUITIANTISHENGLI, HeroInfoTable::uifenlei.
Referenced by ProcessWBL_RaceEndRace.
void BlockServer::CheckTaskGuanqia(SePlayer *pkPlayer, const SeWSGuanqiaSendInfo &rkInfo)
References SeGuanqiaSendInfo::adwBossID, SeGuanqiaSendInfo::dwHeroTypeID, SeWSGuanqiaSendInfo::dwMapID, SeWSGuanqiaSendInfo::dwRaceTime, HeroInfoTableMgr::Get, SePlayer::GetCharLevel, HeroInfoTableMgr::GetHeroInfoTable, SePlayer::getTaskMgr, HEROINFO_FENLEI_ARCHER, HEROINFO_FENLEI_ASSASIN, HEROINFO_FENLEI_FUZHU, HEROINFO_FENLEI_MAGE, HEROINFO_FENLEI_TANK, HEROINFO_FENLEI_ZHANSHI, SeGuanqiaSendInfo::iAddGold, SeGuanqiaSendInfo::iDeathNums, SeGuanqiaSendInfo::iKillBossNums, SeGuanqiaSendInfo::iRaceEndFlag, SePlayer::IsLoadComplete, SeWSGuanqiaSendInfo::kInfo, TaskMgr::SettleTask, SROT_RRESULT_FINISHED_SUCCES, SROT_RRESULT_GIVEUP, SROT_RRESULT_INVILAD, TASKINFO_CONDITON_CANYUYOUXI, TASKINFO_CONDITON_GETGOLD, TASKINFO_CONDITON_KILLNPC, TASKINFO_CONDITON_LIANXUSHENGLI, TASKINFO_CONDITON_SHIYONGA, TASKINFO_CONDITON_SHIYONGB, TASKINFO_CONDITON_SHIYONGC, TASKINFO_CONDITON_SHIYONGD, TASKINFO_CONDITON_SHIYONGE, TASKINFO_CONDITON_TONGGUANDITU, TASKINFO_CONDITON_WANCHENGZHANGJIE, TASKINFO_CONDITON_WINA, TASKINFO_CONDITON_WINB, TASKINFO_CONDITON_WINC, TASKINFO_CONDITON_WIND, TASKINFO_CONDITON_WINE, TASKINFO_CONDITON_ZHANGHAODENGJI, TASKINFO_CONDITON_ZHIDINGSHIJIANTONGGUAN, TASKINFO_CONDITON_ZIJIWUSIWANGTONGGUAN, HeroInfoTable::uifenlei.
Referenced by ProcessWBL_RaceEndGuanka.
void BlockServer::BuyCardItem(SePlayer *pkPlayer, SeMoneyType eMoneyType, const TownItemTable *pkItemRes, int iAllPrice)
void BlockServer::UpdatePlayerLeagueInfo(SePlayer *pkPlayer, const SeWSRaceSendInfo &rkInfo)
Referenced by ProcessWBL_RaceEndRace.
int BlockServer::CalcChangedLeagueScore(int iPlayerLeagueScore, int iOtherCampScore, bool bWin)
References makeCallback.f.
int BlockServer::CalcChangedLeagueMMR(int iLeagueMMR, bool bWin)
References g_kFormula, SeFormula::GetLeagueMMRLevelByScore.
void BlockServer::GetLeagueWinLose(bool bWin, int &iWinLose)
bool BlockServer::SendBLW_TSIncNum(int iTownIndex, int iNum, void *pkReceiver=NULL)
Referenced by ProcessWBL_LoadPlayerInfoAgain, ProcessWBL_PlayerValidate.
bool BlockServer::SendBLW_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, int iSize, const char *acMessage, void *pkReceiver=NULL)
bool BlockServer::SendBLW_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, int iSize, std::vector< char > &acMessage, void *pkReceiver=NULL)
bool BlockServer::SendBLW_LoadPlayerInfoAgainRet(int iTownIndex, int iNum, const DWord *adwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessWBL_LoadPlayerInfoAgain.
bool BlockServer::SendBLW_LoadPlayerInfoAgainRet(int iTownIndex, int iNum, std::vector< DWord > &adwPlayerID, void *pkReceiver=NULL)
bool BlockServer::SendBLW_PlayerLeave(DWord dwPlayerID, const char *acPlayerName, const SeNationType &eNation, int iTownIndex, Byte byPlayerLeaveRet, void *pkReceiver=NULL)
Referenced by KickPlayerByID.
bool BlockServer::SendBLW_PlayerLoadComplete(DWord dwPlayerID, const char *acPlayerName, int iTownIndex, DWord dwLoadConsumeTime, void *pkReceiver=NULL)
Referenced by SePlayer::LoadingComplete.
bool BlockServer::SendBLW_PlayerOperRep(DWord dwPlayerID, int iResult, void *pkReceiver=NULL)
Referenced by ProcessWBL_BuyShopItem, ProcessWBL_ShopItemGM.
bool BlockServer::SendBLW_ShopItemGmRep(DWord dwPlayerID, int iResult, const ShopItem &GmItem, void *pkReceiver=NULL)
Referenced by ProcessWBL_GetItemGM.
bool BlockServer::SendBLWData(void *pkData, int iSize, void *pkReceiver)
References g_kWorldServer, WorldServer::PushWSMsg.
bool BlockServer::ProcessWBLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by Update.
bool BlockServer::PreProcessWBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_HasDBError(SeWBL_HasDBError *pkData, int iSize, void *pkSender)
References SeWBL_HasDBError::eErrorCode, SePlayer::isLoadingComplete, m_kAllPlayer, SDER_NONE, SePlayer::SetLoadComplete.
void BlockServer::ProcessWBL_BlockSetup(SeWBL_BlockSetup *pkData, int iSize, void *pkSender)
References SeWBL_BlockSetup::eType, SeWBL_BlockSetup::iParam, SBST_LOG_SHOW_TYPE, SetLogShowType.
void BlockServer::ProcessWBL_ShowNotice(SeWBL_ShowNotice *pkData, int iSize, void *pkSender)
References SeWBL_ShowNotice::acMessage, SeWBL_ShowNotice::dwPlayerID, SeWBL_ShowNotice::eNoticeCode, g_kWorldServer, SePlayer::GetID, GetPlayer, SePlayer::GetTownSock, WorldServer::SendWT_ShowNotice.
void BlockServer::ProcessWBL_LoadPlayerInfoAgain(SeWBL_LoadPlayerInfoAgain *pkData, int iSize, void *pkSender)
References SeWBL_LoadPlayerInfoAgain::akPlayerInfo, SeLoadPlayerInfoAgain::bRacing, DelWaitPlayer, SeLoadPlayerInfoAgain::dwPlayerID, SeLoadPlayerInfoAgain::dwSessionID, g_kWorldServer, SePlayer::GetID, GetPlayer, GetServerTime, SePlayer::GetTownIndex, SeWBL_LoadPlayerInfoAgain::iNum, SeWBL_LoadPlayerInfoAgain::iTownIndex, SeWBL_LoadPlayerInfoAgain::kTownSock, m_kAllPlayer, OnPlayerLeave, WorldServer::OnSendDBPlayerLoad, SendBLW_LoadPlayerInfoAgainRet, SendBLW_TSIncNum, SePlayer::SetBeginLoadAgainTime, SePlayer::SetBlockServer, SePlayer::SetLoadInfoAgain, SePlayer::SetSessionID, SePlayer::SetState, SePlayer::SetTemState, SePlayer::SetTownIndex, SePlayer::SetTownSock, SPS_LOADING_DATA, SPS_READY_IN_GAME.
void BlockServer::ProcessWBL_AccountLogin(SeWBL_AccountLogin *pkData, int iSize, void *pkSender)
References SeWaitPlayer::dwPlayerID, SeWBL_AccountLogin::dwPlayerID, SeWaitPlayer::dwSessionID, SeWBL_AccountLogin::dwSessionID, SeWaitPlayer::dwWaitTime, GetServerTime, GetWaitPlayer, SeWaitPlayer::kAccountInfo, SeWBL_AccountLogin::kAccountInfo, m_kWaitPlayer, SeLogInfo.
void BlockServer::ProcessWBL_PlayerValidate(SeWBL_PlayerValidate *pkData, int iSize, void *pkSender)
References SeWBL_PlayerValidate::dwClientID, SeWBL_PlayerValidate::dwMaxMailID, SeWBL_PlayerValidate::dwPlayerID, SeWBL_PlayerValidate::dwPlayerIP, SeWaitPlayer::dwSessionID, SeWBL_PlayerValidate::dwSessionID, SeWBL_PlayerValidate::dwTownServerID, g_kWorldServer, SePlayer::GetID, GetPlayer, SeWBL_PlayerValidate::iTownIndex, SeWaitPlayer::kAccountInfo, SeWBL_PlayerValidate::kTSSock, m_kAllPlayer, m_kWaitPlayer, SeLogError, SeLogInfo, SendBLW_TSIncNum, WorldServer::SendDBServer_CharQueryValid, WorldServer::SendWT_PlayerValidateRet, SePlayer::SetAccountInfo, SePlayer::SetBlockServer, SePlayer::SetLoadInfoAgain, SePlayer::SetMaxMailID, SePlayer::SetPlayerIP, SePlayer::SetSessionID, SePlayer::SetState, SePlayer::SetTownIndex, SePlayer::SetTownServerID, SePlayer::SetTownSock, SePlayer::SetUserAvatar, SePlayer::SetUserAvatarFrame, SPS_QUERY_CHAR_INFO, SVT_REPEAT_IN_TOWN, SVT_SESSION_ID_ERROR.
void BlockServer::ProcessWBL_PlayerValidateEnd(SeWBL_PlayerValidateEnd *pkData, int iSize, void *pkSender)
References SeWBL_PlayerValidateEnd::acNotice, SeWBL_PlayerValidateEnd::dwClientID, SeWBL_PlayerValidateEnd::dwPlayerID, SeWBL_PlayerValidateEnd::eValidateType, g_kWorldServer, SePlayer::GetID, GetPlayer, GetServerTime, SePlayer::GetState, SePlayer::GetTownIndex, SePlayer::GetTownSock, SePlayer::IsLoadComplete, OnPlayerLeave, WorldServer::OnSendDBPlayerLoad, WorldServer::OnSendLSPlayerTownIndex, SeLogError, WorldServer::SendWT_PlayerValidateRet, SePlayer::SetBeginLoadTime, SePlayer::SetState, SPS_CREATE_CHAR, SPS_LOADING_DATA, SPS_QUERY_CHAR_INFO, SVT_CHAR_NOT_EXIST, SVT_VALIDATE_OK.
void BlockServer::ProcessWBL_KickPlayerByID(SeWBL_KickPlayerByID *pkData, int iSize, void *pkSender)
References SeWBL_KickPlayerByID::bLoginKick, SeWBL_KickPlayerByID::bSysKick, SeWBL_KickPlayerByID::dwPlayerID, KickPlayerByID.
void BlockServer::ProcessWBL_PlayerLeave(SeWBL_PlayerLeave *pkData, int iSize, void *pkSender)
References SeWBL_PlayerLeave::bExitGame, SeWBL_PlayerLeave::dwPlayerID, GetPlayer, SePlayer::GetTownIndex, SeWBL_PlayerLeave::iTownIndex, OnPlayerLeave, SePlayer::SetFlag, SPF_LEFT_BY_TOWM.
void BlockServer::ProcessWBL_CreateChar(SeWBL_CreateChar *pkData, int iSize, void *pkSender)
References SeWBL_CreateChar::acName, SeWBL_CreateChar::dwPlayerID, g_kWorldServer, SePlayer::GetAccount, SePlayer::GetID, SePlayer::GetPlatFlag, GetPlayer, SePlayer::GetState, SeWBL_CreateChar::iSex, SeLogError, WorldServer::SendDBServer_CharInfoADD, SePlayer::SetState, SPS_CREATE_CHAR, SPS_CREATEING_CHAR.
void BlockServer::ProcessWBL_CharAddRet(SeWBL_CharAddRet *pkData, int iSize, void *pkSender)
References CCR_CREATE_CHAR_OK, CCR_DB_ERROR, CCR_NAME_EXIST, SeWBL_CharAddRet::dwPlayerID, SeWBL_CharAddRet::eRet, g_kWorldServer, SePlayer::GetID, GetPlayer, SePlayer::GetTownIndex, SePlayer::GetTownSock, WorldServer::OnSendDBPlayerLoad, WorldServer::OnSendLSPlayerTownIndex, SeLogError, WorldServer::SendWT_CreateCharRet, SePlayer::SetState, SPS_CREATE_CHAR, SPS_LOADING_DATA.
void BlockServer::ProcessWBL_RaceEndRace(SeWBL_RaceEndRace *pkData, int iSize, void *pkSender)
References SeWBL_RaceEndRace::acAreaInfo, SeWBL_RaceEndRace::akInfo, CheckTaskRace, SeWBL_RaceEndRace::dwMapID, SeWSRaceSendInfo::dwPlayerID, SeWBL_RaceEndRace::eMatchType, g_kWorldServer, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, GetPlayer, SeWBL_RaceEndRace::iNum, SeWSRaceSendInfo::kInfo, WorldServer::OnSendRaceEndInfoLog, UpdatePlayerLeagueInfo.
void BlockServer::ProcessWBL_RaceEndGuanka(SeWBL_RaceEndGuanka *pkData, int iSize, void *pkSender)
References SeWBL_RaceEndGuanka::akInfo, CheckTaskGuanqia, SeWBL_RaceEndGuanka::dwMapID, SeWSGuanqiaSendInfo::dwPlayerID, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, GetPlayer, SeWBL_RaceEndGuanka::iNum, SeGuanqiaSendInfo::iRaceEndFlag, SeWSGuanqiaSendInfo::kInfo, SROT_RRESULT_INVILAD.
void BlockServer::ProcessWBL_ItemExchange(SeWBL_ItemExchange *pkData, int iSize, void *pkSender)
References SeWBL_ItemExchange::dwPlayerID, GetPlayer, SeWBL_ItemExchange::iTypeID, SePlayer::OnItemExchangeCheck.
void BlockServer::ProcessWBL_TaskQueryList(SeWBL_TaskQueryList *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_TaskResel(SeWBL_TaskResel *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_TaskGetAward(SeWBL_TaskGetAward *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_MatchRaceLoad(SeWBL_MatchRaceLoad *pkData, int iSize, void *pkSender)
References SeWBL_MatchRaceLoad::dwMapID, SeWBL_MatchRaceLoad::dwPlayerID, GetDayEndTime, GetID2Str, GetPlayer, SCMT_RACE_MAP_COUNT, SeLogError, SSD_RACEBET_MAP, SePlayer::UpdateMemoryData.
void BlockServer::ProcessWBL_UpdateLeagueInfo(SeWBL_UpdateLeagueInfo *pkData, int iSize, void *pkSender)
References SeDBTime::IsValid, SeLeagueInfo::kBeginTime, SeWBL_UpdateLeagueInfo::kBeginTime, SeLeagueInfo::kEndTime, SeWBL_UpdateLeagueInfo::kEndTime, m_kLeagueInfo.
void BlockServer::ProcessWBL_PlayerRenameBegin(SeWBL_PlayerRenameBegin *pkData, int iSize, void *pkSender)
References SeWBL_PlayerRenameBegin::acName, SeWBL_PlayerRenameBegin::dwPlayerID, GetPlayer, SePlayer::OnRenameBegin.
void BlockServer::ProcessWBL_PlayerRenameEnd(SeWBL_PlayerRenameEnd *pkData, int iSize, void *pkSender)
References SeWBL_PlayerRenameEnd::acName, SeWBL_PlayerRenameEnd::bSuccess, SePlayer::ClrFlag, SeWBL_PlayerRenameEnd::dwPlayerID, g_kWorldServer, GetPlayer, SePlayer::GetTownSock, SePlayer::OnRenameEnd, WorldServer::OnSendShowNoticeWithoutString, SNC_RENAME_FAIL, SPF_RENAME.
void BlockServer::ProcessWBL_RaceBuy(SeWBL_RaceBuy *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_MapTaskOpr(SeWBL_MapTaskOpr *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_BuyShopItem(SeWBL_BuyShopItem *pkData, int iSize, void *pkSender)
References CShop::CurrencyBuyItem, SeWBL_BuyShopItem::dwPlayerID, g_kWorldServer, GetPlayer, WorldServer::GetShop, SeWBL_BuyShopItem::Num, SeLogError, SendBLW_PlayerOperRep, SeWBL_BuyShopItem::ShopID, SeWBL_BuyShopItem::types.
void BlockServer::ProcessWBL_ShopItemGM(SeWBL_ShopItemGM *pkData, int iSize, void *pkSender)
References SeWBL_ShopItemGM::dwPlayerID, g_kWorldServer, GetPlayer, WorldServer::GetShop, SeWBL_ShopItemGM::GmItems, CShop::GMModiItem, SeWBL_ShopItemGM::iNum, SeLogError, SendBLW_PlayerOperRep.
void BlockServer::ProcessWBL_GetItemGM(SeWBL_GetItemGM *pkData, int iSize, void *pkSender)
References SeWBL_GetItemGM::dwPlayerID, g_kWorldServer, CShop::GetGMItem, GetPlayer, WorldServer::GetShop, SeLogError, SendBLW_ShopItemGmRep, SeWBL_GetItemGM::ShopID.
void BlockServer::ProcessWBL_CreateNexusFriend(SeWBL_CreateNexusFriend *pkData, int iSize, void *pkSender)
References SeWBL_CreateNexusFriend::acName, SeCharNexusFriendData::char_friend_id, SeCharNexusFriendData::char_id, SeCharNexusFriendData::create_time, SeWBL_CreateNexusFriend::CreateTime, SeWBL_CreateNexusFriend::dwMark, SeWBL_CreateNexusFriend::dwPlayerFriendID, SeWBL_CreateNexusFriend::dwPlayerID, g_kWorldServer, WorldServer::GenNexusFriendID, SePlayer::GetCharNexusFriendData, GetPlayer, SeCharNexusFriendData::id, SePlayer::m_mapNexusFriendData, SeCharNexusFriendData::mark, SeCharNexusFriendData::name, SeLogError, WorldServer::SendDBServer_NexusFriendCreate.
void BlockServer::ProcessWBL_CreateNexusOfflineFriend(SeWBL_CreateNexusOfflineFriend *pkData, int iSize, void *pkSender)
References SeWBL_CreateNexusOfflineFriend::acName, SeCharNexusFriendData::char_friend_id, SeCharNexusFriendData::char_id, SeCharNexusFriendData::create_time, SeWBL_CreateNexusOfflineFriend::CreateTime, SeWBL_CreateNexusOfflineFriend::dwMark, SeWBL_CreateNexusOfflineFriend::dwPlayerFriendID, SeWBL_CreateNexusOfflineFriend::dwPlayerID, g_kWorldServer, WorldServer::GenNexusFriendID, SeCharNexusFriendData::id, SeCharNexusFriendData::mark, SeCharNexusFriendData::name, SeLogError, WorldServer::SendDBServer_NexusFriendCreate.
void BlockServer::ProcessWBL_UpdateNexusFriend(SeWBL_UpdateNexusFriend *pkData, int iSize, void *pkSender)
References SeCharNexusFriendData::char_friend_id, SeCharNexusFriendData::char_id, SeWBL_UpdateNexusFriend::dwMark, SeWBL_UpdateNexusFriend::dwPlayerFriendID, SeWBL_UpdateNexusFriend::dwPlayerID, g_kWorldServer, SePlayer::GetNexusFriendGenID, GetPlayer, SeCharNexusFriendData::id, SeCharNexusFriendData::mark, SeLogError, WorldServer::SendDBServer_NexusFriendUpdate.
void BlockServer::ProcessWBL_DelNexusFriend(SeWBL_DelNexusFriend *pkData, int iSize, void *pkSender)
References SeWBL_DelNexusFriend::dwPlayerFriendID, SeWBL_DelNexusFriend::dwPlayerID, g_kWorldServer, SePlayer::GetNexusFriendGenID, GetPlayer, SeLogError, WorldServer::SendDBServer_NexusFriendDelete.
void BlockServer::ProcessWBL_UserAlterNickNameReq(SeWBL_UserAlterNickNameReq *pkData, int iSize, void *pkSender)
References SeWBL_UserAlterNickNameReq::acNickName, CItemMgr::CheckOwnerItem, CMT_NAME, SeWBL_UserAlterNickNameReq::dwPlayerID, EUAS_NAME_REPEAT, EUAS_SUCCESS, TownItemTableMgr::Get, SePlayer::GetItemMgr, GetPlayer, TownItemTableMgr::GetTownItemTable, SePlayer::GetTownSock, SeWBL_UserAlterNickNameReq::iResult, ITEM_PROMOTE_MAINASSIST_NOTSAMETYPE, ITEM_RESULT_TABLE_ERROR, SeLogError, SendBLT_PlayerOperRep, SendBLT_UserAlterNickNameAck, SePlayer::UpdateCharMisc, USER_ALTER_NAME_ITEM_ID.
void BlockServer::SeBSProcess_CharMemoryLoad(SeBBL_SelectDataRet *pkRet)
References SeBBL_SelectDataRet::acData, SeDBStream::Attach, SeBBL_SelectDataRet::bySendOver, SeCharMemory::dwParam, SeBBL_SelectDataRet::dwPlayerID, SeCharMemory::dwValue, SePlayer::GetLoadFlagCount, GetPlayer, SeDBStream::IsEnd, SeBBL_SelectDataRet::iSendNum, SeBBL_SelectDataRet::iSize, SeCharMemory::kEndTime, SePlayer::LoadingComplete, SePlayer::LoadMemoryData, PLF_CHAR_MEMORY, SeDBStream::ReadDBTime, SeDBStream::ReadDword, SeLogError, SePlayer::SetLoadFlag, SePlayer::SetLoadFlagCount.
Referenced by ProcessBBL_SelectDataRet.
void BlockServer::SeBSProcess_CharNexusFriend(SeBBL_SelectDataRet *pkRet)
References SeBBL_SelectDataRet::acData, SeDBStream::Attach, SeBBL_SelectDataRet::bySendOver, SeCharNexusFriendData::char_friend_id, SeCharNexusFriendData::char_id, SeCharNexusFriendData::create_time, SeBBL_SelectDataRet::dwPlayerID, SePlayer::GetLoadFlagCount, GetPlayer, SeCharNexusFriendData::id, SeDBStream::IsEnd, SeBBL_SelectDataRet::iSendNum, SeBBL_SelectDataRet::iSize, SePlayer::LoadingComplete, SePlayer::LoadNexusFriend, SeCharNexusFriendData::mark, SeCharNexusFriendData::name, PLF_CHAR_NEXUSFRIEND, SeDBStream::ReadDBTime, SeDBStream::ReadDoubleDword, SeDBStream::ReadDword, SeDBStream::ReadString, SeLogError, SePlayer::SetLoadFlag, SePlayer::SetLoadFlagCount, SSD_MAX_CHAR_NAME, StrCpy.
Referenced by ProcessBBL_SelectDataRet.
bool BlockServer::SeBSProcess_LoadFriendLadderInfo(SeBBL_SelectFriendDataRet *pkRet)
References SeBBL_SelectFriendDataRet::acData, SeDBStream::Attach, SeBBL_SelectFriendDataRet::dwFriendID, SeBBL_SelectFriendDataRet::dwPlayerID, GetPlayer, SeBBL_SelectFriendDataRet::iSize, SePlayer::LoadFriendLadderInfo, SeDBStream::ReadDword, SeDBStream::ReadString, SeLogError.
Referenced by ProcessBBL_SelectFriendDataRet.
bool BlockServer::ProcessRBLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by Update.
bool BlockServer::PreProcessRBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_UpdateScore(SeRBL_UpdateScore *pkData, int iSize, void *pkSender)
References SeLadderInfo::byLadderDefeat, SeLadderInfo::dwLadderScore, SeLadderInfo::dwLadderTime, SeRBL_UpdateScore::dwPlayerID, SeRBL_UpdateScore::eMatchType, EMT_BATTLEFIELD, EMT_LADDER, EMT_MATCH, EMT_PVE, g_kLadderLevelMgr, g_kLadderRankMgr, g_kWorldServer, SePlayer::GetBattleField, SePlayer::GetCharLevel, getDefeat, SePlayer::GetID, SePlayer::GetLadder, LadderLevelMgr::getLevel, SePlayer::GetMatch, SePlayer::GetName, GetPlayer, SePlayer::getTaskMgr, GetTDBTime, LadderLevelMgr::getTopLevel, SePlayer::GetTownSock, SePlayer::GetUserAvatar, LadderRankMgr::JoinNewPlayerLadderInfo, NowTime, LadderLevelMgr::quitTop, SeRBL_UpdateScore::score, SeLogError, WorldServer::SendDBServer_CharUpdateBattleField, WorldServer::SendDBServer_CharUpdateLadder, WorldServer::SendDBServer_CharUpdateMatch, WorldServer::SendWN_PlayerScoreNtf, WorldServer::SendWT_PlayerLadder, SePlayer::SetBattleField, SePlayer::SetLadder, SePlayer::SetMatch, TaskMgr::SettleTask, TASKINFO_CONDITON_TIANTIJIFEN, SeRBL_UpdateScore::win, SeLadderInfo::wLadderLevel.
void BlockServer::ProcessRBL_AwardItemNtf(SeRBL_AwardItemNtf *pkData, int iSize, void *pkSender)
References CItemMgr::AddItem, SeRBL_AwardItemNtf::awards, SeAwardItem::dwItemID, SeAwardItem::dwNum, SeRBL_AwardItemNtf::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, SeRBL_AwardItemNtf::iNum, SeLogError.
void BlockServer::ProcessRBL_DecRespawnItemNtf(SeRBL_DecRespawnItemNtf *pkData, int iSize, void *pkSender)
References CItemMgr::decRespawnItem, SeRBL_DecRespawnItemNtf::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, SeLogError.
void BlockServer::ProcessRBL_SetEquipSetNtf(SeRBL_SetEquipSetNtf *pkData, int iSize, void *pkSender)
References SeRBL_SetEquipSetNtf::byIndex, CMT_EQUIPSETINDEX, SeRBL_SetEquipSetNtf::dwPlayerID, GetPlayer, SeLogError, SSD_QUICK_EQUIP_MAX_NUM, SePlayer::UpdateCharMisc.
void BlockServer::ProcessRBL_SetRaceMapHeroNtf(SeRBL_SetRaceMapHeroNtf *pkData, int iSize, void *pkSender)
References SeRBL_SetRaceMapHeroNtf::dwHeroID, SeRBL_SetRaceMapHeroNtf::dwMapID, SeRBL_SetRaceMapHeroNtf::dwPlayerID, SeRBL_SetRaceMapHeroNtf::dwWinCounts, RaceHeroMgr::genHeroParam, SePlayer::GetID, GetPlayer, SePlayer::getRaceHeroMgr, RaceHeroMgr::makeHero, RaceHeroMgr::makeHero_Arena, SeLogError.
void BlockServer::ProcessRBL_SetAvatarNtf(SeRBL_SetAvatarNtf *pkData, int iSize, void *pkSender)
References SeRBL_SetAvatarNtf::dwHeroID, SeRBL_SetAvatarNtf::dwItemID, SeRBL_SetAvatarNtf::dwPlayerID, SePlayer::getHeroMgr, GetPlayer, SeLogError, HeroMgr::setAvatar.
void BlockServer::ProcessRBL_SelectHeroReq(SeRBL_SelectHeroReq *pkData, int iSize, void *pkSender)
References SeRBL_SelectHeroReq::dwHeroID, SeRBL_SelectHeroReq::dwPlayerID, HeroMgr::getHeroInfo, SePlayer::getHeroMgr, GetPlayer, SendBLR_SelectHeroAck.
void BlockServer::ProcessRBL_UserRaceMapNtf(SeRBL_UserRaceMapNtf *pkData, int iSize, void *pkSender)
References SeRBL_UserRaceMapNtf::akRaceMaplInfo, SeRaceEndArenaDetailInfo::dwMapID, SeRBL_UserRaceMapNtf::dwPlayerID, SeRaceEndArenaDetailInfo::dwPlayerID, GetPlayer, SePlayer::getRaceMapMgr, SeRaceEndArenaDetailInfo::iAssists, SeRaceEndArenaDetailInfo::iBest, SeRaceEndArenaDetailInfo::iBlood_1, SeRaceEndArenaDetailInfo::iDies, SeRaceEndArenaDetailInfo::iEnemyEyes, SeRaceEndArenaDetailInfo::iKills, SeRaceEndArenaDetailInfo::iKills_3, SeRaceEndArenaDetailInfo::iKills_4, SeRaceEndArenaDetailInfo::iKills_5, SeRaceEndArenaDetailInfo::iMvp, SeRaceEndArenaDetailInfo::iPlaceEyes, SeRaceEndArenaDetailInfo::iRaceFlag, SeRaceEndArenaDetailInfo::iRaceNum, SeRaceEndArenaDetailInfo::iSuper, SeRaceEndArenaDetailInfo::iTitle, SeRaceEndArenaDetailInfo::iTotalBeDamage, SeRaceEndArenaDetailInfo::iTotalDamage, SeRaceEndArenaDetailInfo::iTotalGold, RaceMapMgr::makeMap, SeLogError.
void BlockServer::ProcessRBL_RaceEndArenaBaseInfoSync(SeRBL_RaceEndArenaBaseInfoSync *pkData, int iSize, void *pkSender)
References SeRBL_RaceEndArenaBaseInfoSync::akRaceBaselInfo, CMT_BATTLETIME, CMT_EXP, CMT_GOLD, CMT_RACECUMUGOLDS, SeRBL_RaceEndArenaBaseInfoSync::dwPlayerID, GetPlayer, SeRaceEndArenaBaseInfo::iCumuGold, SeRaceEndArenaBaseInfo::iExp, SeRaceEndArenaBaseInfo::iGold, SePlayer::NotifyOwnMoney, NowTime, SeLogError, SePlayer::UpdateCharMisc.
bool BlockServer::SendBLR_SelectHeroAck(int iResult, DWord dwPlayerID, const SeSelHeroInfo &hero, void *pkReceiver=NULL)
Referenced by ProcessRBL_SelectHeroReq.
bool BlockServer::SendBLRData(void *pkData, int iSize, void *pkReceiver)
References g_kRaceServerMgr, g_kWorldServer, moba::ServerSessionMgr::getServerHSock, WorldServer::SendWRData.
bool BlockServer::ProcessMBLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by Update.
bool BlockServer::PreProcessMBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessMBL_RaceMatchLoadDetail(SeMBL_RaceMatchLoadDetail *pkData, int iSize, void *pkSender)
References SeMatchOtherInfo::akEquipItems, SeMatchOtherInfo::akHeroList, SeMatchOtherInfo::akRandomAvatars, SeMatchOtherInfo::akSelectableAvatars, SeMatchOtherInfo::byEquipSetIndex, SeMBL_RaceMatchLoadDetail::dwMatchSession, SeMBL_RaceMatchLoadDetail::dwPlayerID, SeMatchOtherInfo::dwRespawnItemCount, SeMBL_RaceMatchLoadDetail::eMatchType, SePlayer::getActiveAvatarMgr, HeroMgr::getAllUnlockHeroInfo, ActiveAvatarMgr::getAvatars, SeNetStream::GetCurPos, SeNetStream::GetData, EquipSchemaMgr::getEquips, SePlayer::getEquipSchemaMgr, SePlayer::GetEquipSetIndex, SePlayer::getHeroMgr, SePlayer::GetItemMgr, SePlayer::GetMatchBaseInfo, GetPlayer, CItemMgr::getRespawnItemCount, SePlayer::GetScoreInfo, CItemMgr::getSelectableAvatars, SeMBL_RaceMatchLoadDetail::iEquipmentType, SeNetStream::InitData, SePtlMatchPlayer::kBaseInfo, SePtlMatchPlayer::kOtherInfo, SePtlMatchPlayer::kScoreInfo, SeLogError, SendBLM_RaceMatchLoadDetailRet, Write.
void BlockServer::ProcessMBL_GetPlayerMatchValue(SeMBL_GetPlayerMatchValue *pkData, int iSize, void *pkSender)
References SeWorldConfig::dwAreaID, HTownSign::dwAreaID, MatchValueStru::dwMatchNum, SeMBL_GetPlayerMatchValue::dwPlayerID, MatchValueStru::dwPlayerID, HTownSign::dwServerID, SeMBL_GetPlayerMatchValue::eMatchType, g_kWorldServer, WorldServer::GetConfig, SePlayer::GetName, GetPlayer, SePlayer::GetScoreInfo, SePlayer::GetTownServerID, MatchValueStru::NameStr, ReqResultOffline, ReqResultSuccess, MatchValueStru::ScoreInfo, SendBLM_GetPlayerMatchValueRet, StrCpy.
void BlockServer::ProcessMBL_BlockRoomInvite(SeMBL_BlockRoomInvite *pkData, int iSize, void *pkSender)
References SeMBL_BlockRoomInvite::acName, SeMBL_BlockRoomInvite::dwInviteeID, SeMBL_BlockRoomInvite::dwPlayerID, SeMBL_BlockRoomInvite::dwRoomID, g_kWorldServer, GetPlayer, SePlayer::GetTownSock, WorldServer::SendWT_RoomInviteNotify.
bool BlockServer::SendBLM_RaceMatchLoadDetailRet(DWord dwPlayerID, DWord dwMatchSession, int iSize, const char *acData, void *pkReceiver=NULL)
Referenced by ProcessMBL_RaceMatchLoadDetail.
bool BlockServer::SendBLM_RaceMatchLoadDetailRet(DWord dwPlayerID, DWord dwMatchSession, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool BlockServer::SendBLM_GetPlayerMatchValueRet(const MatchReqResult &result, const HTownSign &town, const MatchValueStru &matchValue, void *pkReceiver=NULL)
Referenced by ProcessMBL_GetPlayerMatchValue.
bool BlockServer::SendBLMData(void *pkData, int iSize, void *pkReceiver)
References g_kMatchServerMgr, g_kWorldServer, moba::ServerSessionMgr::getServerHSock, WorldServer::SendWMData.
bool BlockServer::ProcessTBLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by Update.
bool BlockServer::PreProcessTBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_GMSetGold(SeTBL_GMSetGold *pkData, int iSize, void *pkSender)
References CMT_GOLD, SeTBL_GMSetGold::dwGold, SeTBL_GMSetGold::dwPlayerID, GetPlayer, SePlayer::NotifyOwnMoney, SeLogError, SePlayer::UpdateCharMisc.
void BlockServer::ProcessTBL_GMSetDiamond(SeTBL_GMSetDiamond *pkData, int iSize, void *pkSender)
References CMT_DIAMOND, SeTBL_GMSetDiamond::dwDiamond, SeTBL_GMSetDiamond::dwPlayerID, GetPlayer, SePlayer::NotifyOwnMoney, SeLogError, SePlayer::UpdateCharMisc.
void BlockServer::ProcessTBL_ReqItemStrenth(SeTBL_ReqItemStrenth *pkData, int iSize, void *pkSender)
References SeTBL_ReqItemStrenth::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, SeTBL_ReqItemStrenth::iNum, SeLogError, SendBLT_PlayerOperRep, SeTBL_ReqItemStrenth::SrcPosArray, CItemMgr::StrenthEquip, SeTBL_ReqItemStrenth::wPos.
void BlockServer::ProcessTBL_ReqItemCiTiaoChange(SeTBL_ReqItemCiTiaoChange *pkData, int iSize, void *pkSender)
References SeTBL_ReqItemCiTiaoChange::BolLock, CItemMgr::ChangeCiTiao, SeTBL_ReqItemCiTiaoChange::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, SeTBL_ReqItemCiTiaoChange::iNum, SeLogError, SendBLT_PlayerOperRep, SeTBL_ReqItemCiTiaoChange::SrcPosArray, SeTBL_ReqItemCiTiaoChange::wIndex, SeTBL_ReqItemCiTiaoChange::wPos.
void BlockServer::ProcessTBL_ReqItemDepart(SeTBL_ReqItemDepart *pkData, int iSize, void *pkSender)
References SeTBL_ReqItemDepart::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, CItemMgr::ItemDepart, SeLogError, SendBLT_PlayerOperRep, SeTBL_ReqItemDepart::wPos.
void BlockServer::ProcessTBL_GMAddItem(SeTBL_GMAddItem *pkData, int iSize, void *pkSender)
References CItemMgr::AddItem, SeTBL_GMAddItem::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, SeTBL_GMAddItem::ItemID, SeTBL_GMAddItem::Num, SeLogError, SendBLT_PlayerOperRep.
void BlockServer::ProcessTBL_DelelteItem(SeTBL_DelelteItem *pkData, int iSize, void *pkSender)
References CItemMgr::DeleteItem, SeTBL_DelelteItem::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, SeLogError, SendBLT_PlayerOperRep, SeTBL_DelelteItem::wPos.
void BlockServer::ProcessTBL_PutOnEquip(SeTBL_PutOnEquip *pkData, int iSize, void *pkSender)
References SeTBL_PutOnEquip::dwPlayerID, SePlayer::getEquipSchemaMgr, GetPlayer, EquipSchemaMgr::putOnEquip, SeTBL_PutOnEquip::PutPos, SeLogError, SendBLT_PutOnEquipRet, SeTBL_PutOnEquip::wPos.
void BlockServer::ProcessTBL_TakeOffEquip(SeTBL_TakeOffEquip *pkData, int iSize, void *pkSender)
References SeTBL_TakeOffEquip::dwPlayerID, SePlayer::getEquipSchemaMgr, GetPlayer, SeLogError, SendBLT_TakeOffEquipRet, EquipSchemaMgr::takeOffEquip, SeTBL_TakeOffEquip::wPos.
void BlockServer::ProcessTBL_OpenRandBox(SeTBL_OpenRandBox *pkData, int iSize, void *pkSender)
References SeTBL_OpenRandBox::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, CItemMgr::openRandBox, SeLogError, SendBLT_OpenRandBoxRet, SeTBL_OpenRandBox::wPos.
void BlockServer::ProcessTBL_ClearItemNewFlag(SeTBL_ClearItemNewFlag *pkData, int iSize, void *pkSender)
References CItemMgr::clearItemNewFlag, SeTBL_ClearItemNewFlag::dwPlayerID, SePlayer::GetItemMgr, GetPlayer, SeTBL_ClearItemNewFlag::iNum, SeTBL_ClearItemNewFlag::PosArray, SeLogError, SendBLT_PlayerOperRep.
void BlockServer::ProcessTBL_LadderRankQueryReq(SeTBL_LadderRankQueryReq *pkData, int iSize, void *pkSender)
References SeTBL_LadderRankQueryReq::dwPlayerID, g_kLadderRankMgr, GetPlayer, LadderRankMgr::QueryLadderRank, SeLogError, SendBLT_LadderRankQueryAck.
void BlockServer::ProcessTBL_FriendLadderInfoReq(SeTBL_FriendLadderInfoReq *pkData, int iSize, void *pkSender)
References SeTBL_FriendLadderInfoReq::dwFriendID, SeTBL_FriendLadderInfoReq::dwPlayerID, g_kWorldServer, SePlayer::GetCharNexusFriendData, GetPlayer, SBBR_LOAD_ONE_FRIEND_LADDER, SeLogError, WorldServer::SendWB_SelectFriendData.
void BlockServer::ProcessTBL_UserMapRaceHeroReq(SeTBL_UserMapRaceHeroReq *pkData, int iSize, void *pkSender)
References SeTBL_UserMapRaceHeroReq::dwPlayerID, EPVPMapType_Race, RaceHeroMgr::get_race_hero_data, GetPlayer, SePlayer::getRaceHeroMgr, SeLogError, SendBLT_UserRaceHeroAck.
void BlockServer::ProcessTBL_SetActiveAvatarReq(SeTBL_SetActiveAvatarReq *pkData, int iSize, void *pkSender)
References SeTBL_SetActiveAvatarReq::bActive, SeTBL_SetActiveAvatarReq::dwItemID, SeTBL_SetActiveAvatarReq::dwPlayerID, SePlayer::getActiveAvatarMgr, GetPlayer, SeLogError, SendBLT_SetActiveAvatarAck, ActiveAvatarMgr::setActiveAvatar.
void BlockServer::ProcessTBL_UserAlterNickNameReq(SeTBL_UserAlterNickNameReq *pkData, int iSize, void *pkSender)
References SeTBL_UserAlterNickNameReq::acNickName, SeTBL_UserAlterNickNameReq::dwPlayerID, EUAS_ILLEGAL_LEN, g_kWorldServer, SeDBStream::GetCurPos, SeDBStream::GetData, GetPlayer, SePlayer::GetTownIndex, SeDBStream::InitData, SeLogError, SendBLT_UserAlterNickNameAck, WorldServer::SendWB_IsPlayerExist, SPEQ_CHAR_CHECK_NAME, SSD_MAX_CHAR_NAME, SeDBStream::WriteDword, SeDBStream::WriteString.
void BlockServer::ProcessTBL_UserAlterAvatarReq(SeTBL_UserAlterAvatarReq *pkData, int iSize, void *pkSender)
References CMT_AVATAR, SeTBL_UserAlterAvatarReq::dwAvatarID, SeTBL_UserAlterAvatarReq::dwPlayerID, GetPlayer, SePlayer::GetUserAvatar, SePlayer::GetUserAvatarFrame, SeLogError, SendBLT_UserAlterAvatarAndFrameNtf, SePlayer::UpdateCharMisc.
void BlockServer::ProcessTBL_UserAlterAvatarFrameReq(SeTBL_UserAlterAvatarFrameReq *pkData, int iSize, void *pkSender)
References CMT_AVATARFRAME, SeTBL_UserAlterAvatarFrameReq::dwAvatarFrameID, SeTBL_UserAlterAvatarFrameReq::dwPlayerID, GetPlayer, SePlayer::GetUserAvatar, SePlayer::GetUserAvatarFrame, SeLogError, SendBLT_UserAlterAvatarAndFrameNtf, SePlayer::UpdateCharMisc.
void BlockServer::ProcessTBL_UserPurchaseAvatarReq(SeTBL_UserPurchaseAvatarReq *pkData, int iSize, void *pkSender)
References CMT_AVATAR, SeTBL_UserPurchaseAvatarReq::dwAvatarID, SeTBL_UserPurchaseAvatarReq::dwPlayerID, GetPlayer, SePlayer::GetUserAvatar, SePlayer::GetUserAvatarFrame, SeLogError, SendBLT_UserAlterAvatarAndFrameNtf, SePlayer::UpdateCharMisc.
void BlockServer::ProcessTBL_UserRaceMapDetailReq(SeTBL_UserRaceMapDetailReq *pkData, int iSize, void *pkSender)
References SeTBL_UserRaceMapDetailReq::dwPlayerID, EPVPMapType_Race, RaceMapMgr::get_race_data, GetPlayer, SePlayer::getRaceMapMgr, SeLogError, SendBLT_UserRaceArenaDetailAck.
void BlockServer::ProcessTBL_LadderDetailInfoReq(SeTBL_LadderDetailInfoReq *pkData, int iSize, void *pkSender)
References SeTBL_LadderDetailInfoReq::dwPlayerID, RaceMapMgr::get_race_data, GetPlayer, SePlayer::getRaceMapMgr, SeLogError, SendBLT_LadderDetailInfoAck.
void BlockServer::ProcessTBL_AchieveInfoReq(SeTBL_AchieveInfoReq *pkData, int iSize, void *pkSender)
bool BlockServer::SendBLT_PlayerOperRep(DWord dwPlayerID, int iResult, void *pkReceiver=NULL)
Referenced by ProcessTBL_ClearItemNewFlag, ProcessTBL_DelelteItem, ProcessTBL_GMAddItem, ProcessTBL_ReqItemCiTiaoChange, ProcessTBL_ReqItemDepart, ProcessTBL_ReqItemStrenth, ProcessWBL_UserAlterNickNameReq.
bool BlockServer::SendBLT_OpenRandBoxRet(DWord dwPlayerID, int iResult, int iNum, const SeRandBoxItem *ItemArray, void *pkReceiver=NULL)
Referenced by ProcessTBL_OpenRandBox.
bool BlockServer::SendBLT_OpenRandBoxRet(DWord dwPlayerID, int iResult, int iNum, std::vector< SeRandBoxItem > &ItemArray, void *pkReceiver=NULL)
bool BlockServer::SendBLT_PutOnEquipRet(DWord dwPlayerID, int iResult, Word wEquipPos, DWord dwItemID, void *pkReceiver=NULL)
Referenced by ProcessTBL_PutOnEquip.
bool BlockServer::SendBLT_TakeOffEquipRet(DWord dwPlayerID, int iResult, Word wEquipPos, void *pkReceiver=NULL)
Referenced by ProcessTBL_TakeOffEquip.
bool BlockServer::SendBLT_LadderRankQueryAck(DWord dwPlayerID, int iNum, const SeLadderRankInfo *RankList, void *pkReceiver=NULL)
Referenced by ProcessTBL_LadderRankQueryReq.
bool BlockServer::SendBLT_LadderRankQueryAck(DWord dwPlayerID, int iNum, std::vector< SeLadderRankInfo > &RankList, void *pkReceiver=NULL)
bool BlockServer::SendBLT_UserRaceHeroAck(DWord dwPlayerID, int iNum, const SeUserRaceMapHeroBase *hero_info, void *pkReceiver=NULL)
Referenced by ProcessTBL_UserMapRaceHeroReq.
bool BlockServer::SendBLT_UserRaceHeroAck(DWord dwPlayerID, int iNum, std::vector< SeUserRaceMapHeroBase > &hero_info, void *pkReceiver=NULL)
bool BlockServer::SendBLT_SetActiveAvatarAck(DWord dwPlayerID, int iResult, DWord dwItemID, void *pkReceiver=NULL)
Referenced by ProcessTBL_SetActiveAvatarReq.
bool BlockServer::SendBLT_UserAlterNickNameAck(DWord dwPlayerID, int iResult, void *pkReceiver=NULL)
Referenced by ProcessTBL_UserAlterNickNameReq, ProcessWBL_UserAlterNickNameReq.
bool BlockServer::SendBLT_UserAlterAvatarAndFrameNtf(DWord dwPlayerID, DWord dwAvatarID, DWord dwAvatarFrameID, void *pkReceiver=NULL)
Referenced by ProcessTBL_UserAlterAvatarFrameReq, ProcessTBL_UserAlterAvatarReq, ProcessTBL_UserPurchaseAvatarReq.
bool BlockServer::SendBLT_UserRaceArenaDetailAck(DWord dwPlayerID, const SeRaceEndArenaResult &race_arena_info, void *pkReceiver=NULL)
Referenced by ProcessTBL_UserRaceMapDetailReq.
bool BlockServer::SendBLT_LadderDetailInfoAck(DWord dwPlayerID, const SeLadderDetailInfo &info, void *pkReceiver=NULL)
Referenced by ProcessTBL_LadderDetailInfoReq.
bool BlockServer::SendBLT_AchieveInfoAck(DWord dwPlayerID, int iNum1, const SeAchieveFinish *finishInfo, int iNum2, const SeAchieveSchedule *scheduleInfo, void *pkReceiver=NULL)
bool BlockServer::SendBLT_AchieveInfoAck(DWord dwPlayerID, int iNum1, std::vector< SeAchieveFinish > &finishInfo, int iNum2, std::vector< SeAchieveSchedule > &scheduleInfo, void *pkReceiver=NULL)
bool BlockServer::SendBLTData(void *pkData, int iSize, void *pkReceiver)
References g_kTownServerMgr, g_kWorldServer, moba::ServerSessionMgr::getServerHSock, WorldServer::SendWTData.
bool BlockServer::ProcessBBLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by Update.
bool BlockServer::PreProcessBBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessBBL_PlayerLoadRet(SeBBL_PlayerLoadRet *pkData, int iSize, void *pkSender)
References SeBBL_PlayerLoadRet::bLoadSuc, SeBBL_PlayerLoadRet::dwPlayerID, g_kPlayerDataMgr, g_kWorldServer, GetPlayer, PlayerDataMgr::loadData, WorldServer::SendDBServer_CharMemoryLoad, WorldServer::SendDBServer_NexusFriendLoad.
void BlockServer::ProcessBBL_SelectDataRet(SeBBL_SelectDataRet *pkData, int iSize, void *pkSender)
References SeBBL_SelectDataRet::dwPlayerID, SeBBL_SelectDataRet::eReceipt, SeBBL_SelectDataRet::eTable, g_kPlayerDataMgr, GetPlayer, PlayerDataMgr::onLoadData, SBBR_LOAD_CHAR_MEMORY, SBBR_LOAD_CHAR_NEXUSFRIEND, SBBR_NONE, SeBSProcess_CharMemoryLoad, SeBSProcess_CharNexusFriend, SeLogError.
void BlockServer::ProcessBBL_SelectFriendDataRet(SeBBL_SelectFriendDataRet *pkData, int iSize, void *pkSender)
References SeBBL_SelectFriendDataRet::acData, SeLadderRankInfo::acName, SeDBStream::Attach, SeBBL_SelectFriendDataRet::dwPlayerID, SeLadderRankInfo::dwPlayerID, SeBBL_SelectFriendDataRet::eReceipt, g_kWorldServer, GetPlayer, SePlayer::GetTownSock, SeLadderRankInfo::iLadderLevel, SeLadderRankInfo::iLadderScore, SeBBL_SelectFriendDataRet::iSize, SeDBStream::ReadDword, SeDBStream::ReadString, SBBR_LOAD_FRIEND_LADDER, SBBR_LOAD_ONE_FRIEND_LADDER, SeBSProcess_LoadFriendLadderInfo, SeLogError, WorldServer::SendWT_FriendLadderInfoNtf, SePlayer::UploadFriendData, SeLadderRankInfo::wIconID.
bool BlockServer::SendBLBData(void *pkData, int iSize, void *pkReceiver)
References g_kWorldServer, WorldServer::SendWBData.
bool BlockServer::ProcessNBLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by Update.
bool BlockServer::PreProcessNBL(void *pkData, int iSize, void *pkSender)
bool BlockServer::SendBLNData(void *pkData, int iSize, void *pkReceiver)
References g_kWorldServer, WorldServer::SendWNData.
BlockServer::BlockServer(void)
BlockServer::~BlockServer(void)
bool BlockServer::Initialize(int iBaseBuffSize=4 *1024 *1024)
void BlockServer::Update(void)
void BlockServer::Finialize(void)
SePlayer* BlockServer::GetPlayer(DWord dwPlayerID, bool bNeedComplete=true)
bool BlockServer::PushMsg(void *pkData, int iSize)
DWord BlockServer::GetServerTime(void)
MapAllPlayer& BlockServer::GetAllPlayer(void)
SeWaitPlayer* BlockServer::GetWaitPlayer(DWord dwPlayerID)
void BlockServer::DelWaitPlayer(DWord dwPlayerID)
void BlockServer::OnPlayerLeave(DWord dwPlayerID, bool bExitGame, bool bSendLeave=true)
void BlockServer::KickPlayerByID(DWord dwPlayerID, bool bLoginKick, bool bSysKick=false)
void BlockServer::WaitPlayerInfoAssign(SePlayer *pkPlayer, SeWaitPlayer *pkWaitPlayer, bool bKicked)
void BlockServer::SetLogShowType(int iLogShowType)
int BlockServer::GetLogShowType(void)
void BlockServer::GetRaceDropChanceID(DWord dwMapID, int iRaceEndFlag, int iDifficulty, VecDWord &rkVChanceID)
void BlockServer::CheckTaskRace(SePlayer *pkPlayer, const SeWSRaceSendInfo &rkInfo)
void BlockServer::CheckTaskGuanqia(SePlayer *pkPlayer, const SeWSGuanqiaSendInfo &rkInfo)
void BlockServer::BuyCardItem(SePlayer *pkPlayer, SeMoneyType eMoneyType, const TownItemTable *pkItemRes, int iAllPrice)
void BlockServer::UpdatePlayerLeagueInfo(SePlayer *pkPlayer, const SeWSRaceSendInfo &rkInfo)
int BlockServer::CalcChangedLeagueScore(int iPlayerLeagueScore, int iOtherCampScore, bool bWin)
int BlockServer::CalcChangedLeagueMMR(int iLeagueMMR, bool bWin)
void BlockServer::GetLeagueWinLose(bool bWin, int &iWinLose)
bool BlockServer::SendBLW_TSIncNum(int iTownIndex, int iNum, void *pkReceiver=NULL)
bool BlockServer::SendBLW_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, int iSize, const char *acMessage, void *pkReceiver=NULL)
bool BlockServer::SendBLW_ShowNotice(DWord dwPlayerID, const SeNoticeCode &eNoticeCode, int iSize, std::vector< char > &acMessage, void *pkReceiver=NULL)
bool BlockServer::SendBLW_LoadPlayerInfoAgainRet(int iTownIndex, int iNum, const DWord *adwPlayerID, void *pkReceiver=NULL)
bool BlockServer::SendBLW_LoadPlayerInfoAgainRet(int iTownIndex, int iNum, std::vector< DWord > &adwPlayerID, void *pkReceiver=NULL)
bool BlockServer::SendBLW_PlayerLeave(DWord dwPlayerID, const char *acPlayerName, const SeNationType &eNation, int iTownIndex, Byte byPlayerLeaveRet, void *pkReceiver=NULL)
bool BlockServer::SendBLW_PlayerLoadComplete(DWord dwPlayerID, const char *acPlayerName, int iTownIndex, DWord dwLoadConsumeTime, void *pkReceiver=NULL)
bool BlockServer::SendBLW_PlayerOperRep(DWord dwPlayerID, int iResult, void *pkReceiver=NULL)
bool BlockServer::SendBLW_ShopItemGmRep(DWord dwPlayerID, int iResult, const ShopItem &GmItem, void *pkReceiver=NULL)
bool BlockServer::SendBLWData(void *pkData, int iSize, void *pkReceiver)
bool BlockServer::ProcessWBLData(void *pkData, int iSize, void *pkSender=NULL)
bool BlockServer::PreProcessWBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_HasDBError(SeWBL_HasDBError *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_BlockSetup(SeWBL_BlockSetup *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_ShowNotice(SeWBL_ShowNotice *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_LoadPlayerInfoAgain(SeWBL_LoadPlayerInfoAgain *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_AccountLogin(SeWBL_AccountLogin *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_PlayerValidate(SeWBL_PlayerValidate *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_PlayerValidateEnd(SeWBL_PlayerValidateEnd *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_KickPlayerByID(SeWBL_KickPlayerByID *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_PlayerLeave(SeWBL_PlayerLeave *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_CreateChar(SeWBL_CreateChar *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_CharAddRet(SeWBL_CharAddRet *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_RaceEndRace(SeWBL_RaceEndRace *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_RaceEndGuanka(SeWBL_RaceEndGuanka *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_ItemExchange(SeWBL_ItemExchange *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_TaskQueryList(SeWBL_TaskQueryList *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_TaskResel(SeWBL_TaskResel *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_TaskGetAward(SeWBL_TaskGetAward *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_MatchRaceLoad(SeWBL_MatchRaceLoad *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_UpdateLeagueInfo(SeWBL_UpdateLeagueInfo *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_PlayerRenameBegin(SeWBL_PlayerRenameBegin *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_PlayerRenameEnd(SeWBL_PlayerRenameEnd *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_RaceBuy(SeWBL_RaceBuy *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_MapTaskOpr(SeWBL_MapTaskOpr *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_BuyShopItem(SeWBL_BuyShopItem *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_ShopItemGM(SeWBL_ShopItemGM *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_GetItemGM(SeWBL_GetItemGM *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_CreateNexusFriend(SeWBL_CreateNexusFriend *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_CreateNexusOfflineFriend(SeWBL_CreateNexusOfflineFriend *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_UpdateNexusFriend(SeWBL_UpdateNexusFriend *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_DelNexusFriend(SeWBL_DelNexusFriend *pkData, int iSize, void *pkSender)
void BlockServer::ProcessWBL_UserAlterNickNameReq(SeWBL_UserAlterNickNameReq *pkData, int iSize, void *pkSender)
void BlockServer::SeBSProcess_CharMemoryLoad(SeBBL_SelectDataRet *pkRet)
void BlockServer::SeBSProcess_CharNexusFriend(SeBBL_SelectDataRet *pkRet)
bool BlockServer::SeBSProcess_LoadFriendLadderInfo(SeBBL_SelectFriendDataRet *pkRet)
bool BlockServer::ProcessRBLData(void *pkData, int iSize, void *pkSender=NULL)
bool BlockServer::PreProcessRBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_UpdateScore(SeRBL_UpdateScore *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_AwardItemNtf(SeRBL_AwardItemNtf *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_DecRespawnItemNtf(SeRBL_DecRespawnItemNtf *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_SetEquipSetNtf(SeRBL_SetEquipSetNtf *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_SetRaceMapHeroNtf(SeRBL_SetRaceMapHeroNtf *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_SetAvatarNtf(SeRBL_SetAvatarNtf *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_SelectHeroReq(SeRBL_SelectHeroReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_UserRaceMapNtf(SeRBL_UserRaceMapNtf *pkData, int iSize, void *pkSender)
void BlockServer::ProcessRBL_RaceEndArenaBaseInfoSync(SeRBL_RaceEndArenaBaseInfoSync *pkData, int iSize, void *pkSender)
bool BlockServer::SendBLR_SelectHeroAck(int iResult, DWord dwPlayerID, const SeSelHeroInfo &hero, void *pkReceiver=NULL)
bool BlockServer::SendBLRData(void *pkData, int iSize, void *pkReceiver)
bool BlockServer::ProcessMBLData(void *pkData, int iSize, void *pkSender=NULL)
bool BlockServer::PreProcessMBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessMBL_RaceMatchLoadDetail(SeMBL_RaceMatchLoadDetail *pkData, int iSize, void *pkSender)
void BlockServer::ProcessMBL_GetPlayerMatchValue(SeMBL_GetPlayerMatchValue *pkData, int iSize, void *pkSender)
void BlockServer::ProcessMBL_BlockRoomInvite(SeMBL_BlockRoomInvite *pkData, int iSize, void *pkSender)
bool BlockServer::SendBLM_RaceMatchLoadDetailRet(DWord dwPlayerID, DWord dwMatchSession, int iSize, const char *acData, void *pkReceiver=NULL)
bool BlockServer::SendBLM_RaceMatchLoadDetailRet(DWord dwPlayerID, DWord dwMatchSession, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool BlockServer::SendBLM_GetPlayerMatchValueRet(const MatchReqResult &result, const HTownSign &town, const MatchValueStru &matchValue, void *pkReceiver=NULL)
bool BlockServer::SendBLMData(void *pkData, int iSize, void *pkReceiver)
bool BlockServer::ProcessTBLData(void *pkData, int iSize, void *pkSender=NULL)
bool BlockServer::PreProcessTBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_GMSetGold(SeTBL_GMSetGold *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_GMSetDiamond(SeTBL_GMSetDiamond *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_ReqItemStrenth(SeTBL_ReqItemStrenth *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_ReqItemCiTiaoChange(SeTBL_ReqItemCiTiaoChange *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_ReqItemDepart(SeTBL_ReqItemDepart *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_GMAddItem(SeTBL_GMAddItem *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_DelelteItem(SeTBL_DelelteItem *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_PutOnEquip(SeTBL_PutOnEquip *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_TakeOffEquip(SeTBL_TakeOffEquip *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_OpenRandBox(SeTBL_OpenRandBox *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_ClearItemNewFlag(SeTBL_ClearItemNewFlag *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_LadderRankQueryReq(SeTBL_LadderRankQueryReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_FriendLadderInfoReq(SeTBL_FriendLadderInfoReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_UserMapRaceHeroReq(SeTBL_UserMapRaceHeroReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_SetActiveAvatarReq(SeTBL_SetActiveAvatarReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_UserAlterNickNameReq(SeTBL_UserAlterNickNameReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_UserAlterAvatarReq(SeTBL_UserAlterAvatarReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_UserAlterAvatarFrameReq(SeTBL_UserAlterAvatarFrameReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_UserPurchaseAvatarReq(SeTBL_UserPurchaseAvatarReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_UserRaceMapDetailReq(SeTBL_UserRaceMapDetailReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_LadderDetailInfoReq(SeTBL_LadderDetailInfoReq *pkData, int iSize, void *pkSender)
void BlockServer::ProcessTBL_AchieveInfoReq(SeTBL_AchieveInfoReq *pkData, int iSize, void *pkSender)
bool BlockServer::SendBLT_PlayerOperRep(DWord dwPlayerID, int iResult, void *pkReceiver=NULL)
bool BlockServer::SendBLT_OpenRandBoxRet(DWord dwPlayerID, int iResult, int iNum, const SeRandBoxItem *ItemArray, void *pkReceiver=NULL)
bool BlockServer::SendBLT_OpenRandBoxRet(DWord dwPlayerID, int iResult, int iNum, std::vector< SeRandBoxItem > &ItemArray, void *pkReceiver=NULL)
bool BlockServer::SendBLT_PutOnEquipRet(DWord dwPlayerID, int iResult, Word wEquipPos, DWord dwItemID, void *pkReceiver=NULL)
bool BlockServer::SendBLT_TakeOffEquipRet(DWord dwPlayerID, int iResult, Word wEquipPos, void *pkReceiver=NULL)
bool BlockServer::SendBLT_LadderRankQueryAck(DWord dwPlayerID, int iNum, const SeLadderRankInfo *RankList, void *pkReceiver=NULL)
bool BlockServer::SendBLT_LadderRankQueryAck(DWord dwPlayerID, int iNum, std::vector< SeLadderRankInfo > &RankList, void *pkReceiver=NULL)
bool BlockServer::SendBLT_UserRaceHeroAck(DWord dwPlayerID, int iNum, const SeUserRaceMapHeroBase *hero_info, void *pkReceiver=NULL)
bool BlockServer::SendBLT_UserRaceHeroAck(DWord dwPlayerID, int iNum, std::vector< SeUserRaceMapHeroBase > &hero_info, void *pkReceiver=NULL)
bool BlockServer::SendBLT_SetActiveAvatarAck(DWord dwPlayerID, int iResult, DWord dwItemID, void *pkReceiver=NULL)
bool BlockServer::SendBLT_UserAlterNickNameAck(DWord dwPlayerID, int iResult, void *pkReceiver=NULL)
bool BlockServer::SendBLT_UserAlterAvatarAndFrameNtf(DWord dwPlayerID, DWord dwAvatarID, DWord dwAvatarFrameID, void *pkReceiver=NULL)
bool BlockServer::SendBLT_UserRaceArenaDetailAck(DWord dwPlayerID, const SeRaceEndArenaResult &race_arena_info, void *pkReceiver=NULL)
bool BlockServer::SendBLT_LadderDetailInfoAck(DWord dwPlayerID, const SeLadderDetailInfo &info, void *pkReceiver=NULL)
bool BlockServer::SendBLT_AchieveInfoAck(DWord dwPlayerID, int iNum1, const SeAchieveFinish *finishInfo, int iNum2, const SeAchieveSchedule *scheduleInfo, void *pkReceiver=NULL)
bool BlockServer::SendBLT_AchieveInfoAck(DWord dwPlayerID, int iNum1, std::vector< SeAchieveFinish > &finishInfo, int iNum2, std::vector< SeAchieveSchedule > &scheduleInfo, void *pkReceiver=NULL)
bool BlockServer::SendBLTData(void *pkData, int iSize, void *pkReceiver)
bool BlockServer::ProcessBBLData(void *pkData, int iSize, void *pkSender=NULL)
bool BlockServer::PreProcessBBL(void *pkData, int iSize, void *pkSender)
void BlockServer::ProcessBBL_PlayerLoadRet(SeBBL_PlayerLoadRet *pkData, int iSize, void *pkSender)
void BlockServer::ProcessBBL_SelectDataRet(SeBBL_SelectDataRet *pkData, int iSize, void *pkSender)
void BlockServer::ProcessBBL_SelectFriendDataRet(SeBBL_SelectFriendDataRet *pkData, int iSize, void *pkSender)
bool BlockServer::SendBLBData(void *pkData, int iSize, void *pkReceiver)
bool BlockServer::ProcessNBLData(void *pkData, int iSize, void *pkSender=NULL)
bool BlockServer::PreProcessNBL(void *pkData, int iSize, void *pkSender)
bool BlockServer::SendBLNData(void *pkData, int iSize, void *pkReceiver)
void BlockServer::UpdatePlayer(void)
References GetServerTime, m_dwCheckPlayerTime, m_kAllPlayer, SePlayer::Update.
Referenced by Update.
void BlockServer::UpdateWaitPlayer(void)
References SeWaitPlayer::dwPlayerID, SeWaitPlayer::dwWaitTime, g_kWorldServer, GetServerTime, m_dwCheckTime, m_kWaitPlayer, WorldServer::OnSendLSPlayerLogout, RECHECK_TIME, SESSION_TIME.
Referenced by Update.
void BlockServer::DoWork()
References m_bStop, Update.
void BlockServer::UpdatePlayer(void)
void BlockServer::UpdateWaitPlayer(void)
virtual void BlockServer::DoWork()