CreepTowerGrowthTableMgr
std::map<unsigned int,CreepTowerGrowthTable*> CreepTowerGrowthTableMgr::m_kCreepTowerGrowthTableMap
Referenced by FillData, GetCreepTowerGrowthTable, GetCreepTowerGrowthTableMap, GetCreepTowerGrowthTableVec, ~CreepTowerGrowthTableMgr.
CreepTowerGrowthTableMgr * CreepTowerGrowthTableMgr::m_pkCreepTowerGrowthTableMgr
Referenced by Get, ReLoad.
CreepTowerGrowthTableMgr * CreepTowerGrowthTableMgr::Get()
References CreepTowerGrowthTableMgr, m_pkCreepTowerGrowthTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
CreepTowerGrowthTableMgr * CreepTowerGrowthTableMgr::ReLoad()
References Get, m_pkCreepTowerGrowthTableMgr.
Referenced by TableMgr::ReloadTable.
CreepTowerGrowthTableMgr::CreepTowerGrowthTableMgr()
References Load.
Referenced by Get.
CreepTowerGrowthTableMgr::~CreepTowerGrowthTableMgr()
References m_kCreepTowerGrowthTableMap.
const CreepTowerGrowthTable * CreepTowerGrowthTableMgr::GetCreepTowerGrowthTable(unsigned int iTypeID)
References m_kCreepTowerGrowthTableMap.
const std::map< unsigned int, CreepTowerGrowthTable * > & CreepTowerGrowthTableMgr::GetCreepTowerGrowthTableMap()
References m_kCreepTowerGrowthTableMap.
TableResArray CreepTowerGrowthTableMgr::GetCreepTowerGrowthTableVec()
References m_kCreepTowerGrowthTableMap, TableResArray::pushBack.
bool CreepTowerGrowthTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by CreepTowerGrowthTableMgr.
void CreepTowerGrowthTableMgr::FillData(CreepTowerGrowthTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, CreepTowerGrowthTable::fWaveCasterAttack, CreepTowerGrowthTable::fWaveCasterGold, CreepTowerGrowthTable::fWaveCasterHP, CreepTowerGrowthTable::fWaveInnerTurretsAttack, CreepTowerGrowthTable::fWaveInnerTurretsDefence, CreepTowerGrowthTable::fWaveMeleeAttack, CreepTowerGrowthTable::fWaveMeleeGold, CreepTowerGrowthTable::fWaveMeleeHP, CreepTowerGrowthTable::fWaveMiddleTurretsAttack, CreepTowerGrowthTable::fWaveMiddleTurretsDefence, CreepTowerGrowthTable::fWaveNexusTurretsAttack, CreepTowerGrowthTable::fWaveNexusTurretsDefence, CreepTowerGrowthTable::fWaveOuterTurretsAttack, CreepTowerGrowthTable::fWaveOuterTurretsDefence, CreepTowerGrowthTable::fWaveSiegeAttack, CreepTowerGrowthTable::fWaveSiegeGold, CreepTowerGrowthTable::iWaveCasterNum, CreepTowerGrowthTable::iWaveMeleeNum, CreepTowerGrowthTable::iWaveSiegeNum, m_kCreepTowerGrowthTableMap, CreepTowerGrowthTable::uiWaveNumber.
Referenced by Load.