SeFileLog
char SeFileLog::m_acLogBuf[1024 *256][1024 *256]
Referenced by Flush, LogAsLevel, SeFileLog.
char SeFileLog::m_acDir[MAX_PATH_LEN][MAX_PATH_LEN]
Referenced by __CheckLog, Initialize, SeFileLog.
char SeFileLog::m_acName[128][128]
Referenced by SeFileLog.
FILE* SeFileLog::m_pFile
Referenced by __CheckLog, FlushLog, Initialize, Log, ~SeFileLog.
int SeFileLog::m_iSubIndex
Referenced by __CheckLog, Initialize.
unsigned int SeFileLog::m_dwFlag
Referenced by Initialize, SetLogLevel, TestLogLevel.
bool SeFileLog::m_bLogConsole
Referenced by GetLogConsole, Initialize, IsLogConsole, Log, SetLogConsole.
struct tm SeFileLog::m_kTime
Referenced by __CheckLog, Initialize, Log.
SeLogThread* SeFileLog::m_pkLogThread
Referenced by Flush, Initialize, LogAsLevel, ~SeFileLog.
Es::NormalLock* SeFileLog::m_pkLogLock
Referenced by Flush, Initialize, LogAsLevel, ~SeFileLog.
SeFileLog::SeFileLog(void)
References m_acDir, m_acLogBuf, m_acName.
SeFileLog::~SeFileLog(void)
References SeLogThread::Finialize, m_pFile, m_pkLogLock, m_pkLogThread.
bool SeFileLog::Initialize(const char *pcDir)
References __GetLocalTime, ELOGLV_NONE, SeLogThread::Initialize, m_acDir, m_bLogConsole, m_dwFlag, m_iSubIndex, m_kTime, m_pFile, m_pkLogLock, m_pkLogThread, MAX_PATH_LEN, MkDir, SPrintf, StrCpy.
Referenced by EnableFileLog.
void SeFileLog::UnInit(void)
bool SeFileLog::TestLogLevel(ELogLevel eLogLV)
References m_dwFlag.
Referenced by LogAsLevel.
void SeFileLog::SetLogLevel(ELogLevel eLogLV, bool bOpen=true)
References m_dwFlag.
Referenced by EnableFileLog.
bool SeFileLog::GetLogConsole()
References m_bLogConsole.
Referenced by RaceServer::ExecuteAction.
void SeFileLog::SetLogConsole(bool bOpen)
References m_bLogConsole.
Referenced by RaceServer::ExecuteAction, RaceServer::Initialize.
void SeFileLog::Flush(void)
References SLogDataHead::acLog, SLogDataHead::eLogLevel, ELOGLV_NONE, SLogDataHead::eLogOpt, LOG_OPT_FLUSH, m_acLogBuf, m_pkLogLock, m_pkLogThread, SeLogThread::PushLog.
void SeFileLog::LogAsLevel(ELogLevel eLevel, const char *pcFormat,...)
References SLogDataHead::acLog, SLogDataHead::eLogLevel, SLogDataHead::eLogOpt, LOG_OPT_FILE_CONSOLE, m_acLogBuf, m_pkLogLock, m_pkLogThread, SeLogThread::PushLog, TestLogLevel.
bool SeFileLog::IsLogConsole(void)
References m_bLogConsole.
void SeFileLog::Log(SLogDataHead &rkLog)
References __CheckLog, SLogDataHead::acLog, BeginConsoleColor, SLogDataHead::eLogLevel, ELOGLV_DBG, ELOGLV_ERR, ELOGLV_INF, ELOGLV_SYS, ELOGLV_WRN, SLogDataHead::eLogOpt, EndConsoleColor, FlushLog, LOG_OPT_FILE, LOG_OPT_FILE_CONSOLE, LOG_OPT_FLUSH, m_bLogConsole, m_kTime, m_pFile, SPrintf.
Referenced by SeLogThread::DoWork.
void SeFileLog::FlushLog(void)
References m_pFile.
Referenced by SeLogThread::DoWork, Log.
void SeFileLog::__CheckLog(void)
References __GetLocalTime, m_acDir, m_iSubIndex, m_kTime, m_pFile, MAX_LOGFILE_SIZE, MAX_PATH_LEN, SPrintf.
Referenced by Log.
struct tm SeFileLog::__GetLocalTime(time_t kTime=0)
Referenced by __CheckLog, Initialize.