SeSynMgr
DWord SeSynMgr::m_dwKey
Referenced by GenKey, SeSynMgr.
MapID2SynOpr SeSynMgr::m_kMapID2Opr
Referenced by AddSynOpr, CheckOverTime, Finialize, GetNum, GetOutSynOpr.
DWord SeSynMgr::m_dwLastCheckTime
Referenced by CheckOverTime, SeSynMgr.
int SeSynMgr::m_iCheckTime
Referenced by CheckOverTime, Initialize, SeSynMgr.
DWord SeSynMgr::m_dwOverTime
Referenced by CheckOverTime, GetOutSynOpr, Initialize, SeSynMgr.
int SeSynMgr::m_iMaxNum
Referenced by CheckOverTime, Initialize, SeSynMgr.
SeSynMgr::SeSynMgr(void)
References m_dwKey, m_dwLastCheckTime, m_dwOverTime, m_iCheckTime, m_iMaxNum.
SeSynMgr::~SeSynMgr()
References Finialize.
bool SeSynMgr::Initialize(int iCheckTime, DWord dwOverTime, int iMaxNum)
References m_dwOverTime, m_iCheckTime, m_iMaxNum.
void SeSynMgr::Finialize(void)
References m_kMapID2Opr, SeBaseSynOpr::OnOverTime, SAFE_DELETE.
Referenced by ~SeSynMgr.
DWord SeSynMgr::AddSynOpr(SeBaseSynOpr *pkOpr)
References CheckOverTime, SeBaseSynOpr::dwBeginTime, GenKey, m_kMapID2Opr.
Referenced by LoginServer::ProcessCL_PlayerLogin, LoginServer::ProcessCL_PlayerLogin_NEW, LoginServer::ProcessGL_AccountLoginSuccess, GlobalServer::ProcessLG_AccountLogin, GlobalServer::ProcessLG_PlayerLogin, SeRaceMgr::SendMatchAddrMsg.
SeBaseSynOpr * SeSynMgr::GetOutSynOpr(DWord dwKey)
References SeBaseSynOpr::dwBeginTime, m_dwOverTime, m_kMapID2Opr, SeBaseSynOpr::OnOverTime, SAFE_DELETE.
Referenced by LoginServer::ProcessCL_PlayerLogin, LoginServer::ProcessCL_PlayerLogin_NEW, LoginServer::ProcessGL_AccountLoginFailed, LoginServer::ProcessGL_AccountLoginSuccess, MatchServer::ProcessHS_BiVoiceCreateChatRoomRet, GlobalServer::ProcessHS_DHAccountLoginRet, GlobalServer::ProcessLG_PlayerLogin, LoginServer::ProcessWL_LoginFailed, LoginServer::ProcessWL_LoginSuccess.
int SeSynMgr::GetNum(void)
References m_kMapID2Opr.
Referenced by LoginServer::ShowConsoleTitle.
DWord SeSynMgr::GenKey(void)
References m_dwKey.
Referenced by AddSynOpr.
void SeSynMgr::CheckOverTime(void)
References SeBaseSynOpr::dwBeginTime, m_dwLastCheckTime, m_dwOverTime, m_iCheckTime, m_iMaxNum, m_kMapID2Opr, SeBaseSynOpr::OnOverTime, SAFE_DELETE.
Referenced by AddSynOpr.