SePlayerMgr
SePlayer
Referenced by AddPlayer.
MapPlayer SePlayerMgr::m_kAllPlayer
Referenced by AddPlayer, DelPlayer, Finialize, GetPlayerByID, GetPlayerByName, OnClearMatchServerData, OnLoadPlayerInfoAgain.
DWord SePlayerMgr::m_dwCheckDropTime
Referenced by SePlayerMgr.
int SePlayerMgr::m_iPlayerNum
Referenced by GetTotalPlayerNum, SePlayerMgr.
int SePlayerMgr::m_iMaxPageNum
Referenced by SePlayerMgr.
SePlayer * SePlayerMgr::m_apkPlayer[MAX_PLAYER_NUM]
Referenced by SePlayerMgr.
bool SePlayerMgr::m_abPageFlag[MAX_PAGE_NUM]
Referenced by SePlayerMgr.
VPlayerIDArray SePlayerMgr::m_kVPlayerOpenIncmpListArray
Referenced by getPlayerOpenRaceListArray, OnAddIncmpRace, OnIncmpRaceKDA, OnProcessCloseIncmpRaceList, OnProcessOpenIncmpRaceList, OnRemoveIncmpRace.
SePlayerMgr::SePlayerMgr(void)
References m_abPageFlag, m_apkPlayer, m_dwCheckDropTime, m_iMaxPageNum, m_iPlayerNum, MAX_PAGE_NUM, MAX_PLAYER_NUM.
SePlayerMgr::~SePlayerMgr(void)
References Finialize.
void SePlayerMgr::Update(void)
Referenced by TownServer::Update.
void SePlayerMgr::Finialize(void)
References m_kAllPlayer, SAFE_DELETE.
Referenced by TownServer::Finialize, ~SePlayerMgr.
SePlayer * SePlayerMgr::AddPlayer(DWord dwID, DWord dwClientID, int iVipLevel=0, int iZhiZunLevel=0, UInt uiScore=0)
References SePlayer::m_dwPlayerID, m_kAllPlayer, SePlayer.
Referenced by TownServer::ProcessTCPSvr_ReLoadReadyID, TownServer::ProcessWT_InitPlayerInfo.
void SePlayerMgr::DelPlayer(DWord dwID)
References g_kTownServer, m_kAllPlayer, SAFE_DELETE, TownServer::SendTM_PlayerLeave.
Referenced by TownServer::OnTCPSvrDisconnect, TownServer::ProcessTCPSvr_ClientDisconnect.
SePlayer * SePlayerMgr::GetPlayerByID(DWord dwID)
References m_kAllPlayer.
Referenced by OnAddIncmpRace, OnIncmpRaceKDA, OnProcessCommMatchMsg, TownServer::OnProcessCommMatchMsg, OnRemoveIncmpRace, TownServer::OnTCPSvrDisconnect, TownServer::ProcessBLT_AchieveInfoAck, TownServer::ProcessBLT_LadderDetailInfoAck, TownServer::ProcessBLT_LadderRankQueryAck, TownServer::ProcessBLT_OpenRandBoxRet, TownServer::ProcessBLT_PlayerOperRep, TownServer::ProcessBLT_PutOnEquipRet, TownServer::ProcessBLT_SetActiveAvatarAck, TownServer::ProcessBLT_TakeOffEquipRet, TownServer::ProcessBLT_UserAlterAvatarAndFrameNtf, TownServer::ProcessBLT_UserAlterNickNameAck, TownServer::ProcessBLT_UserRaceArenaDetailAck, TownServer::ProcessBLT_UserRaceHeroAck, TownServer::ProcessCT_CloseIncompleteRaceList, TownServer::ProcessCT_ItemExchange, TownServer::ProcessCT_QueryRaceRoomList, TownServer::ProcessCT_RaceEndGuanka, TownServer::ProcessCT_ReconQuery, TownServer::ProcessCT_ReqIncompleteRaceKDA, TownServer::ProcessCT_ReqIncompleteRaceList, TownServer::ProcessCT_ViewBegin, TownServer::ProcessMT_AskEnterWaitRace, TownServer::ProcessMT_BiVoiceEnterInfo, TownServer::ProcessMT_CancelMatchRet, TownServer::ProcessMT_GetRaceCardInfo, TownServer::ProcessMT_MatchCancelRep, TownServer::ProcessMT_MatchCreateRoomRet, TownServer::ProcessMT_MatchQueryRoomListRet, TownServer::ProcessMT_MatchRoomJoinRet, TownServer::ProcessMT_MatchRoomKickSomeoneRet, TownServer::ProcessMT_MatchRoomLeaveRet, TownServer::ProcessMT_MatchRoomMemberNotifyRet, TownServer::ProcessMT_MatchRoomSwitchSeatRet, TownServer::ProcessMT_MatchSessionNotify, TownServer::ProcessMT_NotifyAddrToMatch, TownServer::ProcessMT_NotiMatcherPre, TownServer::ProcessMT_NotiMatcherResult, TownServer::ProcessMT_QueryRaceBetInfoRet, TownServer::ProcessMT_ReconQueryFail, TownServer::ProcessMT_ReqMatchRep, TownServer::ProcessMT_ResIncmpRaceSeatBaseInfo, TownServer::ProcessMT_ResIncompleteRaceList, TownServer::ProcessMT_SingleMatchConfirm, TownServer::ProcessMT_StartMatchRet, TownServer::ProcessMT_UpdateMisc, TownServer::ProcessNT_MatchTeamMemberRes, TownServer::ProcessNT_NexusFriendCleanRefuseNoticeRes, TownServer::ProcessNT_NexusFriendDetailInfoRes, TownServer::ProcessNT_NexusFriendLimitRes, TownServer::ProcessNT_NexusFriendStatusSync, TownServer::ProcessNT_NexusUserActionSync, TownServer::ProcessNT_RoomInviteNotifyVerifyRsp, TownServer::ProcessNT_TeamChangeSync, TownServer::ProcessNT_TeamLeaderSync, TownServer::ProcessNT_TeamMemberInfoRes, TownServer::ProcessNT_TeamMemberSync, TownServer::ProcessNT_TeamUserStateRes, TownServer::ProcessNT_UserStatusQueryRes, TownServer::ProcessTCPSvr_ClientDisconnect, TownServer::ProcessWCMST_ResRaceDetailInfo, TownServer::ProcessWCMST_ResView, TownServer::ProcessWCMST_ResViewList, TownServer::ProcessWT_ActiveAvatarNtf, TownServer::ProcessWT_EquipSchema, TownServer::ProcessWT_ExchangeInit, TownServer::ProcessWT_FriendLadderInfoNtf, TownServer::ProcessWT_GetRaceHistoryRet, TownServer::ProcessWT_InitPlayerInfo, TownServer::ProcessWT_ItemDel, TownServer::ProcessWT_ItemExchangeRet, TownServer::ProcessWT_MailOprRet, TownServer::ProcessWT_PlayerLadder, TownServer::ProcessWT_PlayerMoneyAndDiamond, TownServer::ProcessWT_PlayerNewItem, TownServer::ProcessWT_PlayerOperRep, TownServer::ProcessWT_PlayerRename, TownServer::ProcessWT_QueryMapTaskListRet, TownServer::ProcessWT_QueryNearestRaceInfoRet, TownServer::ProcessWT_QueryPlayerReconInfo, TownServer::ProcessWT_ReceiveMail, TownServer::ProcessWT_RoomInviteNotify, TownServer::ProcessWT_SearchUserArchivesInfoRes, TownServer::ProcessWT_ShopItemGmRep, TownServer::ProcessWT_TaskQueryListRet, TownServer::ProcessWT_TaskReselRet, TownServer::ProcessWT_UpdateMail, TownServer::ProcessWT_UpdateMisc, TownServer::ProcessWT_UserHeroSync.
SePlayer * SePlayerMgr::GetPlayerByName(const char *pcName)
References m_kAllPlayer.
int SePlayerMgr::GetTotalPlayerNum()
References m_iPlayerNum.
Referenced by TownServer::ShowConsoleTitle.
DWord SePlayerMgr::GetPlayerIP(SePlayer *pkPlayer)
References SeNetAddr::acIP, g_kTownServer, SePlayer::GetID, GetIPString2DWord, TownServer::GetTcpUserByID, SeTCPUser::kNetAddr.
void SePlayerMgr::OnProcessCommMatchMsg(DWord dwSession, SeCommMatchMsg eMsg, DWord dwPlayerID, DWord dwOtherParam=0)
References SePlayer::ClearSingleMatchInfo, g_kTownServer, SePlayer::GetClientID, SePlayer::GetMatchSession, GetPlayerByID, TownServer::OnSendShowNoticeWithoutString, SCMM_ENTER_SEL_HERO, SCMM_NOTIFY_LEAVE_RACE, SCMM_NOTIFY_LOAD_FAILED, SCMM_NOTIFY_RACE_ESCAPE, SCMM_NOTIFY_VALIDATE_FAILED, SCMM_RACE_OVER, SeLogInfo, SNC_MATCH_SELHERO_FAIL, SNC_MATCH_STARTRACE_FAIL.
Referenced by TownServer::OnProcessCommMatchMsg.
bool SePlayerMgr::OnLoadPlayerInfoAgain()
References SeLoadPlayerInfoAgain::dwPlayerID, g_kTownServer, SePlayer::GetID, TownServer::GetServerTime, m_kAllPlayer, SeLogInfo, TownServer::SendTW_LoadPlayerInfoAgain, TownServer::SetReloadPlayerTime, TownServer::SetWSLoadTSReady.
Referenced by TownServer::ProcessWT_RegisterRet.
void SePlayerMgr::OnClearMatchServerData()
References SePlayer::GetID, SePlayer::GetPlayerState, SePlayer::GetTeamID, m_kAllPlayer, SeLogInfo, SePlayer::SetTeamID, SePlayer::SetTeamMemberNum, SPS_IN_TOWN.
Referenced by TownServer::ProcessMT_RegisterRet.
void SePlayerMgr::OnProcessOpenIncmpRaceList(DWord dwID)
References m_kVPlayerOpenIncmpListArray, SeLogError.
void SePlayerMgr::OnProcessCloseIncmpRaceList(DWord dwID)
References m_kVPlayerOpenIncmpListArray, SeLogInfo.
Referenced by TownServer::ProcessCT_CloseIncompleteRaceList.
void SePlayerMgr::OnAddIncmpRace(const SeIncompleteRaceBaseInfo &rData)
References g_kTownServer, SePlayer::GetClientID, GetPlayerByID, m_kVPlayerOpenIncmpListArray, TownServer::SendTC_AddIncompleteRace.
Referenced by TownServer::ProcessMT_AddIncompleteRace.
void SePlayerMgr::OnRemoveIncmpRace(DWord iRoomID)
References g_kTownServer, SePlayer::GetClientID, GetPlayerByID, m_kVPlayerOpenIncmpListArray, TownServer::SendTC_RemoveIncompleteRace.
Referenced by TownServer::ProcessMT_RemoveIncompleteRace.
void SePlayerMgr::OnIncmpRaceKDA(DWord iRoomSession, SeSeatBaseInfo vSeatData[], int iNum)
References g_kTownServer, SePlayer::GetClientID, GetPlayerByID, m_kVPlayerOpenIncmpListArray, TownServer::SendTC_ResIncmpRaceSeatBaseInfo.
const VPlayerIDArray& SePlayerMgr::getPlayerOpenRaceListArray() const
References m_kVPlayerOpenIncmpListArray.
SePlayerMgr::SePlayerMgr(void)
SePlayerMgr::~SePlayerMgr(void)
void SePlayerMgr::Update(void)
void SePlayerMgr::Finialize(void)
SePlayer* SePlayerMgr::AddPlayer(DWord dwID, DWord dwClientID, int iVipLevel=0, int iZhiZunLevel=0, UInt uiScore=0)
void SePlayerMgr::DelPlayer(DWord dwID)
SePlayer* SePlayerMgr::GetPlayerByID(DWord dwID)
SePlayer* SePlayerMgr::GetPlayerByName(const char *pcName)
int SePlayerMgr::GetTotalPlayerNum()
DWord SePlayerMgr::GetPlayerIP(SePlayer *pkPlayer)
void SePlayerMgr::OnProcessCommMatchMsg(DWord dwSession, SeCommMatchMsg eMsg, DWord dwPlayerID, DWord dwOtherParam=0)
bool SePlayerMgr::OnLoadPlayerInfoAgain()
void SePlayerMgr::OnClearMatchServerData()
void SePlayerMgr::OnProcessOpenIncmpRaceList(DWord dwID)
void SePlayerMgr::OnProcessCloseIncmpRaceList(DWord dwID)
void SePlayerMgr::OnAddIncmpRace(const SeIncompleteRaceBaseInfo &rData)
void SePlayerMgr::OnRemoveIncmpRace(DWord iRoomID)
void SePlayerMgr::OnIncmpRaceKDA(DWord iRoomSession, SeSeatBaseInfo vSeatData[], int iNum)
const VPlayerIDArray& SePlayerMgr::getPlayerOpenRaceListArray() const
References m_kVPlayerOpenIncmpListArray.