SeRaceQueryMgr
SeRoom * SeRaceQueryMgr::m_apkRoom[SSD_MAX_MATCH_ROOM_NUM]
Referenced by Finalize, GetRoom, Initialize.
VRoomPtr SeRaceQueryMgr::m_kVAllRoomPtr
Referenced by GetCommonRoom, GetRaceRoomNum, Initialize, OnCreateRoom, OnDestroyRoom.
VRoomPtr SeRaceQueryMgr::m_kVNoCreateRoomPtr
Referenced by Initialize, OnCreateRoom, OnDestroyRoom.
MMD52VRoom SeRaceQueryMgr::m_kMMD52VRoom
Referenced by GetFindedRoom, GetRoomFun, UpdateMD5VRoom.
MRoomInCompleteRaceData SeRaceQueryMgr::m_MRoomInComRaceData
Referenced by GetIncmpRaceMap, OnProcessAddIncompleteRace, OnProcessIncmpRaceKDA, OnProcessRemoveIncompleteRace, OnProcessUpdateIncompleteRace.
SeRaceQueryMgr::SeRaceQueryMgr()
SeRaceQueryMgr::~SeRaceQueryMgr()
bool SeRaceQueryMgr::Initialize()
References SeRoom::iIndex, m_apkRoom, m_kVAllRoomPtr, m_kVNoCreateRoomPtr, SSD_MAX_MATCH_ROOM_NUM.
Referenced by MatchServer::Initialize.
void SeRaceQueryMgr::Update(DWord dwServerTime)
References UpdateMD5VRoom.
Referenced by MatchServer::Update.
void SeRaceQueryMgr::Finalize()
References m_apkRoom, SAFE_DELETE, SSD_MAX_MATCH_ROOM_NUM.
int SeRaceQueryMgr::OnCreateRoom(SeMatchRace *pkRace, DWord dwRaceBeginTime)
References SeRoom::Clear, SeRoom::dwMapID, SeMatchRace::dwMapID, SeMatchRace::dwMatchSession, SeRoom::dwRaceBeginTime, SeRoom::dwSession, SeRoom::iIndex, m_kVAllRoomPtr, m_kVNoCreateRoomPtr.
Referenced by SeRaceMgr::OnProcessCommRaceMsg, SeRaceMgr::OnProcessReloadRoomList.
void SeRaceQueryMgr::OnDestroyRoom(int iRoomIndex, DWord dwSession)
References SeRoom::Clear, SeRoom::dwSession, GetRoom, SeRoom::iIndex, m_kVAllRoomPtr, m_kVNoCreateRoomPtr, OnProcessRemoveIncompleteRace.
Referenced by SeRaceMgr::DelRace, SeRaceMgr::DoRaceOver, SeRaceMgr::OnProcessRSRegister, SeRaceMgr::RaceUpdate.
void SeRaceQueryMgr::OnPlayerQueryRoomList(HSock &rkTownSock, DWord dwPlayerID, int iQueryFlag, int iPage, DWord dwMapID=0, int iIndex=-1)
References g_kMatchServer, GetRoomList, MatchServer::OnSendTSQueryRoomListRet.
Referenced by MatchServer::ProcessTM_QueryRaceRoomList.
void SeRaceQueryMgr::OnRaceSvrUpdateRoomLoadInfo(int iRoomIndex, int iNum, SeMatchRoomLoadInfo *pkLoadInfo)
References SeMatchRoomPlayerInfo::acName, SeMatchRoomLoadInfo::acName, SeRoom::akPlayerSeat, SeRoom::bEscape, SeMatchRoomPlayerInfo::bIsPlayer, SeMatchRoomPlayerInfo::bReserved, SeMatchRoomLoadInfo::dwHeroID, SeMatchRoomPlayerInfo::dwHeroTypeID, SeRoom::dwSession, SeMatchRoomPlayerInfo::dwSkinTypeID, SeMatchRoomLoadInfo::dwSkinTypeID, GetRoom, SeMatchRoomLoadInfo::iSeat, SSD_MAX_ROOM_PLAYER, StrCpy.
Referenced by MatchServer::ProcessRM_MatchRoomLoadInfo.
void SeRaceQueryMgr::OnRaceSeatUpdateState(int iRoomIndex, int iSeatIndex, bool bOnLine, UInt uiScore=0, char *pcName=NULL)
References SeMatchRoomPlayerInfo::acName, SeRoom::akPlayerSeat, SeRoom::bEscape, SeMatchRoomPlayerInfo::bIsPlayer, SeMatchRoomPlayerInfo::bReserved, SeMatchRoomPlayerInfo::dwHeroTypeID, SeRoom::dwSession, GetRoom, SSD_MAX_ROOM_PLAYER, StrCpy.
Referenced by SeRaceMgr::OnProcessCommRaceMsg.
void SeRaceQueryMgr::OnRaceSeatUpdateReverse(int iRoomIndex, int iSeatIndex, bool bReserved)
References SeRoom::akPlayerSeat, SeMatchRoomPlayerInfo::bReserved, SeRoom::dwSession, GetRoom, SSD_MAX_ROOM_PLAYER.
Referenced by SeRaceMgr::OnProcessCommRaceMsg.
void SeRaceQueryMgr::OnReloadPlayerInfo(int iRoomIndex, int iNum, SeReLoadPlayerInfo *pkReloadInfo)
References SeMatchRoomPlayerInfo::acName, SeReLoadPlayerInfo::acName, SeRoom::akPlayerSeat, SeRoom::bEscape, SeMatchRoomPlayerInfo::bIsPlayer, SeReLoadPlayerInfo::bLeaveRace, SeMatchRoomPlayerInfo::bReserved, SeReLoadPlayerInfo::bReverse, SeReLoadPlayerInfo::dwHeroID, SeReLoadPlayerInfo::dwHeroSkin, SeMatchRoomPlayerInfo::dwHeroTypeID, SeRoom::dwSession, SeMatchRoomPlayerInfo::dwSkinTypeID, GetRoom, SeReLoadPlayerInfo::iSeatIndex, SSD_MAX_CHAR_NAME, SSD_MAX_ROOM_PLAYER, StrCpy.
Referenced by SeRaceMgr::OnProcessReloadRoomList.
void SeRaceQueryMgr::OnReconUpdatePlayerInfo(int iRoomIndex, DWord dwSession, DWord dwPlayerID, int iSeat)
References SeRoom::akPlayerSeat, SeMatchRoomPlayerInfo::bIsPlayer, SeMatchRoomPlayerInfo::bReserved, GetRoom, OnProcessUpdateIncompleteRace.
Referenced by SeRaceMgr::OnProcessReconPlayerInfo.
const MRoomInCompleteRaceData& SeRaceQueryMgr::GetIncmpRaceMap() const
References m_MRoomInComRaceData.
Referenced by MatchServer::ProcessTM_ReqIncompleteRaceKDA, MatchServer::ProcessTM_ReqIncompleteRaceList.
int SeRaceQueryMgr::GetRaceRoomNum()
References m_kVAllRoomPtr.
Referenced by MatchServer::ShowConsoleTitle.
void SeRaceQueryMgr::OnProcessAddIncompleteRace(DWord iMapid, int iRoomIndex, DWord dwSession, int iSeat)
References SeRoom::akPlayerSeat, SeMatchRoomPlayerInfo::bReserved, GetRoom, m_MRoomInComRaceData.
Referenced by SeRaceMgr::OnProcessAddIncompleteRace.
void SeRaceQueryMgr::OnProcessUpdateIncompleteRace(DWord dwSession, int iSeat, bool bSeat)
References SeInCompleteRoomRaceData::iSeatNums, m_MRoomInComRaceData, SeInCompleteRoomRaceData::setSeat.
Referenced by OnReconUpdatePlayerInfo, MatchServer::ProcessRM_UpdateIncompleteRace.
void SeRaceQueryMgr::OnProcessRemoveIncompleteRace(DWord dwSession)
References m_MRoomInComRaceData.
Referenced by OnDestroyRoom, SeRaceMgr::OnProcessRemoveIncompleteRace.
void SeRaceQueryMgr::OnProcessIncmpRaceKDA(int iRoomIndex, DWord dwSession, SeRM_ResIncmpRaceSeatBaseInfo *pInfo)
References m_MRoomInComRaceData, SeRM_ResIncmpRaceSeatBaseInfo::oIncmpRaceBaseInfo, SeInCompleteRoomRaceData::UpdateSeatBaseInfo.
Referenced by SeRaceMgr::OnProcessIncmpRaceKDA.
SeRaceQueryMgr::SeRaceQueryMgr()
SeRaceQueryMgr::~SeRaceQueryMgr()
bool SeRaceQueryMgr::Initialize()
void SeRaceQueryMgr::Update(DWord dwServerTime)
void SeRaceQueryMgr::Finalize()
int SeRaceQueryMgr::OnCreateRoom(SeMatchRace *pkRace, DWord dwRaceBeginTime)
void SeRaceQueryMgr::OnDestroyRoom(int iRoomIndex, DWord dwSession)
void SeRaceQueryMgr::OnPlayerQueryRoomList(HSock &rkTownSock, DWord dwPlayerID, int iQueryFlag, int iPage, DWord dwMapID=0, int iIndex=-1)
void SeRaceQueryMgr::OnRaceSvrUpdateRoomLoadInfo(int iRoomIndex, int iNum, SeMatchRoomLoadInfo *pkLoadInfo)
void SeRaceQueryMgr::OnRaceSeatUpdateState(int iRoomIndex, int iSeatIndex, bool bOnLine, UInt uiScore=0, char *pcName=NULL)
void SeRaceQueryMgr::OnRaceSeatUpdateReverse(int iRoomIndex, int iSeatIndex, bool bReserved)
void SeRaceQueryMgr::OnReloadPlayerInfo(int iRoomIndex, int iNum, SeReLoadPlayerInfo *pkReloadInfo)
void SeRaceQueryMgr::OnReconUpdatePlayerInfo(int iRoomIndex, DWord dwSession, DWord dwPlayerID, int iSeat)
const MRoomInCompleteRaceData& SeRaceQueryMgr::GetIncmpRaceMap() const
References m_MRoomInComRaceData.
int SeRaceQueryMgr::GetRaceRoomNum()
void SeRaceQueryMgr::OnProcessAddIncompleteRace(DWord iMapid, int iRoomIndex, DWord dwSession, int iSeat)
void SeRaceQueryMgr::OnProcessUpdateIncompleteRace(DWord dwSession, int iSeat, bool bSeat)
void SeRaceQueryMgr::OnProcessRemoveIncompleteRace(DWord dwSession)
void SeRaceQueryMgr::OnProcessIncmpRaceKDA(int iRoomIndex, DWord dwSession, SeRM_ResIncmpRaceSeatBaseInfo *pInfo)
void SeRaceQueryMgr::UpdateMD5VRoom(DWord dwServerTime)
References SeMD5FindVRoom::dwTime, g_kMatchServer, MatchServer::GetServerTime, m_kMMD52VRoom.
Referenced by Update.
SeRoom * SeRaceQueryMgr::GetRoom(int iRoomIndex)
References m_apkRoom, SSD_MAX_MATCH_ROOM_NUM.
Referenced by GetRoomList, OnDestroyRoom, OnProcessAddIncompleteRace, OnRaceSeatUpdateReverse, OnRaceSeatUpdateState, OnRaceSvrUpdateRoomLoadInfo, OnReconUpdatePlayerInfo, OnReloadPlayerInfo.
int SeRaceQueryMgr::GetRoomList(VRoomPtr &rkVRoomPtr, int iPage, int iQueryFlag, DWord dwMapID=0, int iIndex=-1)
References SeRoom::dwSession, g_kRaceMgr, SeRaceMgr::GetRace, GetRoom, GetRoomFun, SeMatchRace::iRoomIndex, SSD_MAX_MATCH_ROOM_NUM, SSD_ROOM_PER_PAGE.
Referenced by OnPlayerQueryRoomList.
int SeRaceQueryMgr::GetRoomFun(VRoomPtr &rkAllRoom, int iQueryFlag, DWord dwMapID, int iBeginPos, int iEndPos)
References SeMD5FindVRoom::dwTime, g_kMatchServer, GetCommonRoom, GetFindedRoom, MatchServer::GetServerTime, SeMD5FindVRoom::iAllRoomNums, m_kMMD52VRoom, SeMD5FindVRoom::rakRoomPtr, SSD_ROOM_PER_PAGE.
Referenced by GetRoomList.
int SeRaceQueryMgr::GetFindedRoom(DWord dwMapID, int iQueryFlag, int iBeginPos, int iEndPos, VRoomPtr &rkAllRoom, TeMD5 &rkMD5)
References GetFindRoomMD5, SeMD5FindVRoom::iAllRoomNums, m_kMMD52VRoom, SeMD5FindVRoom::rakRoomPtr, SSD_ROOM_PER_PAGE.
Referenced by GetRoomFun.
TeMD5 SeRaceQueryMgr::GetFindRoomMD5(int iQueryFlag, DWord dwMapID, int iBeginPos, int iEndPos)
References TeMD5::abyMD5.
Referenced by GetFindedRoom.
int SeRaceQueryMgr::GetCommonRoom(VRoomPtr &rkAllRoom, int iQueryFlag, DWord dwMapID, int iBeginPos, int iEndPos)
References m_kVAllRoomPtr, RoomFilter, SSD_ROOM_PER_PAGE.
Referenced by GetRoomFun.
bool SeRaceQueryMgr::RoomFilter(SeRoom *pkRoom, int iQueryFlag, DWord dwMapID)
References SeRoom::CanShowRace, SeRoom::dwMapID, g_kMatchServer, MatchServer::GetServerTime.
Referenced by GetCommonRoom.
void SeRaceQueryMgr::sendIncompleteInfo2AllTownServer(void *pData, InterMatch::EMatchIncompleteData eType)
void SeRaceQueryMgr::UpdateMD5VRoom(DWord dwServerTime)
SeRoom* SeRaceQueryMgr::GetRoom(int iRoomIndex)
int SeRaceQueryMgr::GetRoomList(VRoomPtr &rkVRoomPtr, int iPage, int iQueryFlag, DWord dwMapID=0, int iIndex=-1)
int SeRaceQueryMgr::GetRoomFun(VRoomPtr &rkAllRoom, int iQueryFlag, DWord dwMapID, int iBeginPos, int iEndPos)
int SeRaceQueryMgr::GetFindedRoom(DWord dwMapID, int iQueryFlag, int iBeginPos, int iEndPos, VRoomPtr &rkAllRoom, TeMD5 &rkMD5)
TeMD5 SeRaceQueryMgr::GetFindRoomMD5(int iQueryFlag, DWord dwMapID, int iBeginPos, int iEndPos)
int SeRaceQueryMgr::GetCommonRoom(VRoomPtr &rkAllRoom, int iQueryFlag, DWord dwMapID, int iBeginPos, int iEndPos)
bool SeRaceQueryMgr::RoomFilter(SeRoom *pkRoom, int iQueryFlag, DWord dwMapID)
void SeRaceQueryMgr::sendIncompleteInfo2AllTownServer(void *pData, InterMatch::EMatchIncompleteData eType)