SePlayer
SePlayerMgr
BlockServer
DWord SePlayer::m_dwClientID
Referenced by SePlayer.
DWord SePlayer::m_dwPlayerID
Referenced by SePlayerMgr::AddPlayer, SePlayer.
char SePlayer::m_acName[SSD_MAX_CHAR_NAME]
Referenced by SePlayer.
DWord SePlayer::m_dwHeroCardTypeID
Referenced by SePlayer.
DWord SePlayer::m_dwSessionID
Referenced by SePlayer.
SePlayerState SePlayer::m_eState
Referenced by SePlayer.
int SePlayer::m_iFlag
Referenced by ClearFlag, HasFlag, SePlayer, SetFlag.
DWord SePlayer::m_dwLastReceiveTime
Referenced by SePlayer.
SePos2 SePlayer::m_kCurPos
Referenced by SePlayer.
DWord SePlayer::m_dwMapEntityID
Referenced by SePlayer.
MapPlayerOrder::iterator SePlayer::m_kOderItr
DWord SePlayer::m_dwTeamID
Referenced by SePlayer.
int SePlayer::m_iTeamMemberNum
Referenced by SePlayer.
SeSingleMatchInfo SePlayer::m_kSingleMatchInfo
DWord SePlayer::m_dwSingleMatchMap
int SePlayer::m_iLeagueScore
Referenced by SePlayer.
int SePlayer::m_iLeagueMMR
Referenced by SePlayer.
SeDeviceOS SePlayer::m_eDeviceOS
Referenced by SePlayer.
int SePlayer::m_iReconTime
Referenced by GetReconTime, SetReconTime.
SePtlAccountInfo SePlayer::m_kAccountInfo
Referenced by SePlayer.
SeMobileInfo SePlayer::m_kMobileInfo
Referenced by SePlayer.
DWord SePlayer::m_dwPlayerIP
Referenced by SePlayer.
DWord SePlayer::m_dwMaxMailID
Referenced by SePlayer.
DWord SePlayer::m_dwBeginLoadTime
Referenced by DisplayLoadConsumeTime, SePlayer.
DWord SePlayer::m_dwBeginLoadAgainTime
Referenced by DisplayLoadConsumeTime, SePlayer.
int SePlayer::m_iTownIndex
Referenced by SePlayer.
DWord SePlayer::m_dwTownServerID
HSock SePlayer::m_kTownSock
Referenced by SePlayer.
SePlayerState SePlayer::m_eTemState
Referenced by SePlayer.
int SePlayer::m_iLoadFlag
Referenced by SePlayer.
bool SePlayer::m_bLoadComplete
Referenced by SePlayer.
MapLoadFlag2Count SePlayer::m_kLoadFlag2Count
std::map< SeDBTableIndex, int > SePlayer::m_kLoadFlagCounts
bool SePlayer::m_bLoadInfoAgain
Referenced by SePlayer.
VExchange SePlayer::m_akExchange
Referenced by Finalize, GetAllExchange, GetExchangeByID, LoadExchangeInfo.
MType2VCharMemory SePlayer::m_kMAllCharMem
Referenced by GetMemoryValue, LoadMemoryData, UpdateMemoryData.
VItem SePlayer::m_akItem[SIC_NUM]
Referenced by Finalize.
DWord SePlayer::m_dwChestKeyCheckTime
Referenced by SePlayer.
VStatMap SePlayer::m_akStatMap[SMC_NUM]
Referenced by Finalize, GetQueryMapList, GetStatMapByID, GetStatMapNum, LoadStatMap.
BlockServer * SePlayer::m_pkBlockServer
Referenced by DisplayLoadConsumeTime, LoadingComplete, SePlayer.
CItemMgr SePlayer::m_PlayerItemMgr
Referenced by getDataMgr, GetItemMgr, OperateLoading, SePlayer, Update.
AchieveMgr SePlayer::m_AchieveMgr
TaskMgr SePlayer::m_TaskMgr
Referenced by getDataMgr, getTaskMgr.
AchieveFinishMgr SePlayer::m_AchieveFinishMgr
Referenced by getDataMgr.
AchieveScheduleMgr SePlayer::m_AchieveScheduleMgr
Referenced by getDataMgr.
MCharNexusFriendData SePlayer::m_mapNexusFriendData
Referenced by Finalize, GetCharNexusFriendData, GetMCharNexusFriendData, GetNexusFriendGenID, LoadNexusFriend, BlockServer::ProcessWBL_CreateNexusFriend.
std::set< SeDBTableIndex > SePlayer::m_loadingFlag
EquipSchemaMgr SePlayer::m_equipSchemaMgr
Referenced by getDataMgr, getEquipSchemaMgr, OperateLoading.
RaceHeroMgr SePlayer::m_raceHeroMgr
Referenced by getDataMgr, getRaceHeroMgr.
HeroMgr SePlayer::m_heroMgr
Referenced by getDataMgr, getHeroMgr, OperateLoading.
ActiveAvatarMgr SePlayer::m_activeAvatarMgr
Referenced by getActiveAvatarMgr, getDataMgr, OperateLoading.
InfoMgr SePlayer::m_infoMgr
Referenced by getDataMgr, getInfoMgr.
RaceMapMgr SePlayer::m_raceMapMgr
Referenced by getDataMgr, getRaceMapMgr.
MFriendLadderData SePlayer::m_FriendLadderData
Referenced by LoadFriendLadderInfo, UploadFriendData.
DWord SePlayer::m_FriendNum
Referenced by LoadFriendLadderInfo, SetCurrFriendNumForAck, UploadFriendData.
SeDBTime SePlayer::m_kEnterTime
Referenced by SePlayer.
bool SePlayer::m_bRoomCreater
Referenced by TownServer::ProcessMT_MatchRoomLeaveRet, TownServer::ProcessMT_MatchRoomMemberNotifyRet, SePlayer.
Byte SePlayer::bySeats
Referenced by ClearSingleMatchInfo, TownServer::ProcessNT_MatchTeamMemberRes.
DWord SePlayer::dwMapID
Referenced by ClearSingleMatchInfo, TownServer::ProcessNT_MatchTeamMemberRes.
struct SePlayer::@0 SePlayer::m_matchData
Referenced by TownServer::ProcessNT_MatchTeamMemberRes, SePlayer.
struct SePlayer::@1 SePlayer::m_matchData
static const int SePlayer::DEFAULT_DEFEAT
Referenced by GetLadder.
static const int SePlayer::DEFAULT_SCORE
Referenced by GetLadder.
static const int SePlayer::DEFEAT_RESTORE2_THRESHOLD
static const int SePlayer::DEFEAT_RESTORE5_THRESHOLD
SePlayer::SePlayer(DWord dwID, DWord dwClientID)
References SePos2::fX, SePos2::fY, InitPlayerPos, m_acName, m_bRoomCreater, m_dwClientID, m_dwHeroCardTypeID, m_dwLastReceiveTime, m_dwMapEntityID, m_dwPlayerID, m_dwSessionID, m_dwTeamID, m_eDeviceOS, m_eState, m_iFlag, m_iLeagueMMR, m_iLeagueScore, m_iTeamMemberNum, m_kCurPos, m_matchData, SDO_WIN32, SPS_IN_TOWN.
Referenced by GetID.
SePlayer::~SePlayer(void)
DWord SePlayer::GetClientID(void) const
Referenced by SePlayerMgr::OnAddIncmpRace, SePlayerMgr::OnIncmpRaceKDA, SePlayerMgr::OnProcessCommMatchMsg, SePlayerMgr::OnRemoveIncmpRace, SeRaceMgr::OnReqGetIncmpRaceList, TownServer::ProcessBLT_AchieveInfoAck, TownServer::ProcessBLT_LadderDetailInfoAck, TownServer::ProcessBLT_LadderRankQueryAck, TownServer::ProcessBLT_OpenRandBoxRet, TownServer::ProcessBLT_PlayerOperRep, TownServer::ProcessBLT_PutOnEquipRet, TownServer::ProcessBLT_SetActiveAvatarAck, TownServer::ProcessBLT_TakeOffEquipRet, TownServer::ProcessBLT_UserAlterAvatarAndFrameNtf, TownServer::ProcessBLT_UserAlterNickNameAck, TownServer::ProcessBLT_UserRaceArenaDetailAck, TownServer::ProcessBLT_UserRaceHeroAck, TownServer::ProcessMT_AskEnterWaitRace, TownServer::ProcessMT_BiVoiceEnterInfo, TownServer::ProcessMT_CancelMatchRet, TownServer::ProcessMT_MatchCancelRep, TownServer::ProcessMT_MatchCreateRoomRet, TownServer::ProcessMT_MatchQueryRoomListRet, TownServer::ProcessMT_MatchRoomJoinRet, TownServer::ProcessMT_MatchRoomKickSomeoneRet, TownServer::ProcessMT_MatchRoomLeaveRet, TownServer::ProcessMT_MatchRoomMemberNotifyRet, TownServer::ProcessMT_MatchRoomSwitchSeatRet, TownServer::ProcessMT_NotifyAddrToMatch, TownServer::ProcessMT_NotiMatcherPre, TownServer::ProcessMT_NotiMatcherResult, TownServer::ProcessMT_QueryRaceBetInfoRet, TownServer::ProcessMT_ReconQueryFail, TownServer::ProcessMT_ReqMatchRep, TownServer::ProcessMT_ResIncmpRaceSeatBaseInfo, TownServer::ProcessMT_ResIncompleteRaceList, TownServer::ProcessMT_SingleMatchConfirm, TownServer::ProcessMT_StartMatchRet, TownServer::ProcessNT_MatchTeamMemberRes, TownServer::ProcessNT_NexusFriendCleanRefuseNoticeRes, TownServer::ProcessNT_NexusFriendDetailInfoRes, TownServer::ProcessNT_NexusFriendLimitRes, TownServer::ProcessNT_NexusFriendStatusSync, TownServer::ProcessNT_NexusUserActionSync, TownServer::ProcessNT_TeamChangeSync, TownServer::ProcessNT_TeamLeaderSync, TownServer::ProcessNT_TeamMemberInfoRes, TownServer::ProcessNT_TeamMemberSync, TownServer::ProcessNT_TeamUserStateRes, TownServer::ProcessNT_UserStatusQueryRes, TownServer::ProcessWCMST_ResRaceDetailInfo, TownServer::ProcessWCMST_ResView, TownServer::ProcessWCMST_ResViewList, TownServer::ProcessWT_ActiveAvatarNtf, TownServer::ProcessWT_EquipSchema, TownServer::ProcessWT_ExchangeInit, TownServer::ProcessWT_FriendLadderInfoNtf, TownServer::ProcessWT_GetRaceHistoryRet, TownServer::ProcessWT_ItemDel, TownServer::ProcessWT_ItemExchangeRet, TownServer::ProcessWT_MailOprRet, TownServer::ProcessWT_PlayerLadder, TownServer::ProcessWT_PlayerMoneyAndDiamond, TownServer::ProcessWT_PlayerNewItem, TownServer::ProcessWT_PlayerOperRep, TownServer::ProcessWT_PlayerRename, TownServer::ProcessWT_QueryMapTaskListRet, TownServer::ProcessWT_QueryNearestRaceInfoRet, TownServer::ProcessWT_ReceiveMail, TownServer::ProcessWT_RoomInviteNotify, TownServer::ProcessWT_SearchUserArchivesInfoRes, TownServer::ProcessWT_ShopItemGmRep, TownServer::ProcessWT_TaskQueryListRet, TownServer::ProcessWT_TaskReselRet, TownServer::ProcessWT_UpdateMail, TownServer::ProcessWT_UpdateMisc, TownServer::ProcessWT_UserHeroSync.
DWord SePlayer::GetID(void) const
Referenced by PlayerDataStrategy::dataDelete, PlayerDataStrategy::dataInsert, PlayerDataStrategy::dataUpdate, DisplayLoadConsumeTime, CItemMgr::doExchangeItem, CItemMgr::doMoveItem, SePlayerMgr::GetPlayerIP, BlockServer::KickPlayerByID, PlayerDataStrategy::loadData, LoadingComplete, CItemMgr::notiChangeItem, NotifyOwnMoney, SePlayerMgr::OnClearMatchServerData, PlayerDataStrategy::onLoadData, SePlayerMgr::OnLoadPlayerInfoAgain, SeRaceMgr::OnPlayerGuankaEnd, OnRenameBegin, OnRenameEnd, SeRaceMgr::OnReqGetIncmpRaceList, OnUseItem, OperateLoading, TownServer::ProcessCT_CloseIncompleteRaceList, TownServer::ProcessCT_ItemExchange, TownServer::ProcessCT_QueryRaceRoomList, TownServer::ProcessCT_ReconQuery, TownServer::ProcessCT_ViewBegin, TownServer::ProcessMT_MatchRoomMemberNotifyRet, TownServer::ProcessNT_MatchTeamMemberRes, TownServer::ProcessNT_RoomInviteNotifyVerifyRsp, BlockServer::ProcessRBL_SetRaceMapHeroNtf, BlockServer::ProcessRBL_UpdateScore, BlockServer::ProcessWBL_CharAddRet, BlockServer::ProcessWBL_CreateChar, BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerValidate, BlockServer::ProcessWBL_PlayerValidateEnd, BlockServer::ProcessWBL_ShowNotice, TownServer::ProcessWT_QueryPlayerReconInfo, EquipSchemaMgr::putOnEquip, TaskMgr::RefreshTask, TaskMgr::ResetTask, ActiveAvatarMgr::setActiveAvatar, HeroMgr::unlockHero, UpdateCharMisc, UpdateMemoryData, UpdateOnlineTime, WorldServer::UserInfoSync_LoadFriendLadderRank, WorldServer::UserInfoSync_NexusFriend, WorldServer::UserInfoSync_PlayerScore, BlockServer::WaitPlayerInfoAssign.
const char* SePlayer::GetName(void) const
Referenced by BlockServer::KickPlayerByID, LoadingComplete, OnRenameEnd, OperateLoading, TownServer::ProcessCT_ReconQuery, BlockServer::ProcessMBL_GetPlayerMatchValue, BlockServer::ProcessRBL_UpdateScore, UpdateCharMisc, WorldServer::UserInfoSync_NexusFriend.
void SePlayer::SetName(const char *pcName)
Referenced by OnRenameEnd, TownServer::ProcessWT_InitPlayerInfo, TownServer::ProcessWT_PlayerRename, UpdateCharMisc.
void SePlayer::SetHeroCardTypeID(DWord dwHeroCardTypeID)
DWord SePlayer::GetHeroCardTypeID(void) const
SePlayerState SePlayer::GetPlayerState(void) const
Referenced by SePlayerMgr::OnClearMatchServerData, TownServer::ProcessMT_NotifyAddrToMatch.
void SePlayer::SetSingleMatching(bool bSingleMatching)
bool SePlayer::IsSingleMatching(void)
void SePlayer::SetMatchLoading(bool bLoading)
bool SePlayer::IsMatchLoading(void)
void SePlayer::SetMatchSession(DWord dwSession)
Referenced by TownServer::ProcessMT_MatchSessionNotify.
DWord SePlayer::GetMatchSession()
Referenced by SePlayerMgr::OnProcessCommMatchMsg.
void SePlayer::ClearSingleMatchInfo()
Referenced by SePlayerMgr::OnProcessCommMatchMsg.
float SePlayer::GetPosX(void)
float SePlayer::GetPosY(void)
void SePlayer::SetPos(float fX, float fY)
void SePlayer::SetMapEntityID(DWord dwID)
DWord SePlayer::GetMapEntityID(void)
void SePlayer::SetTeamID(DWord dwTeamID)
Referenced by SePlayerMgr::OnClearMatchServerData.
DWord SePlayer::GetTeamID(void)
Referenced by SePlayerMgr::OnClearMatchServerData.
void SePlayer::SetTeamMemberNum(int iNum)
Referenced by SePlayerMgr::OnClearMatchServerData.
int SePlayer::GetTeamMemberNum(void)
void SePlayer::SetDeviceOS(SeDeviceOS eOSType)
Referenced by TownServer::ProcessWT_InitPlayerInfo.
SeDeviceOS SePlayer::GetDeviceOS(void)
int SePlayer::GetLeagueScore(void)
void SePlayer::SetLeagueScore(int iLeagueScore)
Referenced by TownServer::ProcessWT_UpdateMisc.
int SePlayer::GetLeagueMMR(void)
void SePlayer::SetLeagueMMR(int iMMR)
Referenced by TownServer::ProcessWT_UpdateMisc.
SeMatchStartInfo SePlayer::GetMatchStartInfo()
void SePlayer::SetLoadFlag(int iFlag)
Referenced by BlockServer::SeBSProcess_CharMemoryLoad, BlockServer::SeBSProcess_CharNexusFriend.
bool SePlayer::HasLoadFlag(int iFlag)
void SePlayer::SetReconTime(int iTime)
References m_iReconTime.
Referenced by TownServer::ProcessWT_QueryPlayerReconInfo.
int SePlayer::GetReconTime() const
References m_iReconTime.
Referenced by TownServer::ProcessMT_NotifyAddrToMatch.
void SePlayer::SetFlag(int iFlag)
References m_iFlag.
Referenced by OnRenameBegin, BlockServer::ProcessWBL_PlayerLeave, TownServer::ProcessWT_QueryPlayerReconInfo.
void SePlayer::ClearFlag(int iFlag)
References m_iFlag.
Referenced by TownServer::ProcessMT_NotifyAddrToMatch, TownServer::ProcessMT_ReconQueryFail.
bool SePlayer::HasFlag(int iFlag)
References m_iFlag.
Referenced by OnRenameBegin, TownServer::ProcessMT_NotifyAddrToMatch, TownServer::ProcessMT_ReconQueryFail.
SePlayer::SePlayer(DWord dwID, DWord dwClientID)
SePlayer::~SePlayer(void)
DWord SePlayer::GetClientID(void) const
DWord SePlayer::GetID(void) const
References SePlayer.
const char* SePlayer::GetName(void) const
void SePlayer::SetName(const char *pcName)
void SePlayer::SetHeroCardTypeID(DWord dwHeroCardTypeID)
DWord SePlayer::GetHeroCardTypeID(void) const
SePlayerState SePlayer::GetPlayerState(void) const
void SePlayer::SetSingleMatching(bool bSingleMatching)
bool SePlayer::IsSingleMatching(void)
void SePlayer::SetMatchLoading(bool bLoading)
bool SePlayer::IsMatchLoading(void)
void SePlayer::SetMatchSession(DWord dwSession)
DWord SePlayer::GetMatchSession()
void SePlayer::ClearSingleMatchInfo()
References bySeats, dwMapID.
float SePlayer::GetPosX(void)
float SePlayer::GetPosY(void)
void SePlayer::SetPos(float fX, float fY)
void SePlayer::SetMapEntityID(DWord dwID)
DWord SePlayer::GetMapEntityID(void)
void SePlayer::SetTeamID(DWord dwTeamID)
DWord SePlayer::GetTeamID(void)
void SePlayer::SetTeamMemberNum(int iNum)
int SePlayer::GetTeamMemberNum(void)
void SePlayer::SetDeviceOS(SeDeviceOS eOSType)
SeDeviceOS SePlayer::GetDeviceOS(void)
int SePlayer::GetLeagueScore(void)
void SePlayer::SetLeagueScore(int iLeagueScore)
int SePlayer::GetLeagueMMR(void)
void SePlayer::SetLeagueMMR(int iMMR)
SeMatchStartInfo SePlayer::GetMatchStartInfo()
void SePlayer::SetLoadFlag(int iFlag)
bool SePlayer::HasLoadFlag(int iFlag)
void SePlayer::SetReconTime(int iTime)
References m_iReconTime.
int SePlayer::GetReconTime() const
References m_iReconTime.
void SePlayer::SetFlag(int iFlag)
void SePlayer::ClearFlag(int iFlag)
bool SePlayer::HasFlag(int iFlag)
SePlayer::SePlayer(DWord dwPlayerID)
References m_bLoadComplete, m_bLoadInfoAgain, m_dwBeginLoadAgainTime, m_dwBeginLoadTime, m_dwChestKeyCheckTime, m_dwMaxMailID, m_dwPlayerID, m_dwPlayerIP, m_dwSessionID, m_eState, m_eTemState, m_iFlag, m_iLoadFlag, m_iTownIndex, m_kAccountInfo, m_kEnterTime, m_kMobileInfo, m_kTownSock, m_pkBlockServer, m_PlayerItemMgr, NowTime, CItemMgr::SetOwner, SPS_QUERY_CHAR_INFO.
SePlayer::~SePlayer(void)
void SePlayer::Finalize()
References m_akExchange, m_akItem, m_akStatMap, m_mapNexusFriendData, SIC_NUM, SMC_NUM.
Referenced by BlockServer::Finialize, BlockServer::KickPlayerByID.
void SePlayer::Update(DWord dwCurTime)
References IsLoadComplete, m_PlayerItemMgr, CItemMgr::Update.
Referenced by BlockServer::UpdatePlayer.
void SePlayer::LoadingComplete()
References DisplayLoadConsumeTime, PlayerDataMgr::fixData, g_kPlayerDataMgr, g_kWorldServer, GetID, GetLoadInfoAgain, GetName, GetTownIndex, isLoadingComplete, m_pkBlockServer, NowTime, OperateLoading, BlockServer::SendBLW_PlayerLoadComplete, WorldServer::SendDBServer_CharUpdateLoginTime, SetLoadComplete, SetLoginTime, SetState, SPS_READY_IN_TOWN.
Referenced by PlayerDataStrategy::onLoadData, BlockServer::SeBSProcess_CharMemoryLoad, BlockServer::SeBSProcess_CharNexusFriend.
DWord SePlayer::GetID(void) const
void SePlayer::SetAccountInfo(SePtlAccountInfo &rkAccountInfo)
Referenced by BlockServer::ProcessWBL_PlayerValidate.
const SePtlAccountInfo& SePlayer::GetAccountInfo(void) const
Referenced by BlockServer::WaitPlayerInfoAssign.
const char* SePlayer::GetAccount(void) const
Referenced by BlockServer::ProcessWBL_CreateChar.
int SePlayer::GetPlatFlag(void) const
Referenced by BlockServer::ProcessWBL_CreateChar.
void SePlayer::SetMobileInfo(SeMobileInfo &rkMobileInfo)
const SeMobileInfo& SePlayer::GetMobileInfo(void) const
void SePlayer::SetSessionID(DWord dwSessionID)
Referenced by BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerValidate.
DWord SePlayer::GetSessionID(void)
Referenced by BlockServer::WaitPlayerInfoAssign.
void SePlayer::SetTownIndex(int iIndex)
Referenced by BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerValidate.
int SePlayer::GetTownIndex(void) const
Referenced by BlockServer::KickPlayerByID, LoadingComplete, BlockServer::ProcessTBL_UserAlterNickNameReq, BlockServer::ProcessWBL_CharAddRet, BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerLeave, BlockServer::ProcessWBL_PlayerValidateEnd.
void SePlayer::SetTownServerID(DWord dwTownServerID)
Referenced by BlockServer::ProcessWBL_PlayerValidate.
DWord SePlayer::GetTownServerID(void) const
Referenced by BlockServer::ProcessMBL_GetPlayerMatchValue.
void SePlayer::SetTownSock(HSock kTownSock)
Referenced by BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerValidate.
HSock& SePlayer::GetTownSock(void)
Referenced by BlockServer::KickPlayerByID, NotifyOwnMoney, OnRenameEnd, OperateLoading, BlockServer::ProcessBBL_SelectFriendDataRet, BlockServer::ProcessMBL_BlockRoomInvite, BlockServer::ProcessRBL_UpdateScore, BlockServer::ProcessWBL_CharAddRet, BlockServer::ProcessWBL_PlayerRenameEnd, BlockServer::ProcessWBL_PlayerValidateEnd, BlockServer::ProcessWBL_ShowNotice, BlockServer::ProcessWBL_UserAlterNickNameReq.
void SePlayer::SetState(SePlayerState eState)
Referenced by LoadingComplete, BlockServer::ProcessWBL_CharAddRet, BlockServer::ProcessWBL_CreateChar, BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerValidate, BlockServer::ProcessWBL_PlayerValidateEnd.
void SePlayer::SetTemState(SePlayerState eState)
Referenced by BlockServer::ProcessWBL_LoadPlayerInfoAgain.
SePlayerState SePlayer::GetState(void)
Referenced by BlockServer::ProcessWBL_CreateChar, BlockServer::ProcessWBL_PlayerValidateEnd.
bool SePlayer::HasFlag(int iFlag) const
void SePlayer::SetFlag(int iFlag)
void SePlayer::setLoadingFlag(SeDBTableIndex eTable)
Referenced by PlayerDataStrategy::loadData.
void SePlayer::clearLoadingFlag(SeDBTableIndex eTable)
Referenced by PlayerDataStrategy::onLoadData.
void SePlayer::ClrFlag(int iFlag)
Referenced by OnRenameBegin, BlockServer::ProcessWBL_PlayerRenameEnd.
void SePlayer::SetLoadComplete(bool bComplete)
Referenced by LoadingComplete, BlockServer::ProcessWBL_HasDBError.
bool SePlayer::IsLoadComplete(void)
Referenced by CanItemUseWhenAdd, BlockServer::CheckTaskGuanqia, BlockServer::CheckTaskRace, BlockServer::GetPlayer, BlockServer::KickPlayerByID, BlockServer::ProcessWBL_PlayerValidateEnd, Update.
void SePlayer::SetLoadInfoAgain(bool bLoadInfoAgain)
Referenced by BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerValidate.
bool SePlayer::GetLoadInfoAgain(void)
Referenced by DisplayLoadConsumeTime, LoadingComplete.
void SePlayer::SetBeginLoadAgainTime(DWord dwTime)
Referenced by BlockServer::ProcessWBL_LoadPlayerInfoAgain.
void SePlayer::SetLoadFlag(int iFlag)
bool SePlayer::isLoadingComplete()
Referenced by LoadingComplete, BlockServer::ProcessWBL_HasDBError.
bool SePlayer::HasLoadFlag(int iFlag)
void SePlayer::SetLoadFlagCount(SeLoadFlag eFlag, int iCount)
Referenced by PlayerDataStrategy::onLoadData, BlockServer::SeBSProcess_CharMemoryLoad, BlockServer::SeBSProcess_CharNexusFriend.
int SePlayer::GetLoadFlagCount(SeLoadFlag eFlag)
Referenced by PlayerDataStrategy::onLoadData, BlockServer::SeBSProcess_CharMemoryLoad, BlockServer::SeBSProcess_CharNexusFriend.
void SePlayer::SetLoadFlagCount(SeDBTableIndex eTable, int iCount)
int SePlayer::GetLoadFlagCount(SeDBTableIndex eTable)
void SePlayer::SetBlockServer(BlockServer *pkBlockServer)
Referenced by BlockServer::ProcessWBL_LoadPlayerInfoAgain, BlockServer::ProcessWBL_PlayerValidate.
void SePlayer::SetPlayerIP(DWord dwPlayerIP)
Referenced by BlockServer::ProcessWBL_PlayerValidate.
DWord SePlayer::GetPlayerIP()
void SePlayer::SetMaxMailID(DWord dwMaxMailID)
Referenced by BlockServer::ProcessWBL_PlayerValidate.
DWord SePlayer::GetMaxMailID()
void SePlayer::SetBeginLoadTime(DWord dwTime)
Referenced by BlockServer::ProcessWBL_PlayerValidateEnd.
void SePlayer::SetName(const char *pcName)
const char* SePlayer::GetName(void) const
void SePlayer::SetGold(int iGold)
Referenced by CShop::BuyItem, CShop::CurrencyBuyItem_Gold, UpdateCharMisc.
int SePlayer::GetGold(void) const
Referenced by CShop::BuyItem, CItemMgr::ChangeCiTiao, CShop::CurrencyBuyItem_Gold, GetMoney, TaskMgr::GetTaskReward, NotifyOwnMoney, OperateLoading, UpdateCharMisc.
void SePlayer::SetDiamond(int iDiamond)
Referenced by CShop::CurrencyBuyItem_Diamond, UpdateCharMisc.
int SePlayer::GetDiamond(void) const
Referenced by CShop::CurrencyBuyItem_Diamond, GetMoney, NotifyOwnMoney, OperateLoading, UpdateCharMisc.
void SePlayer::SetCreateTime(SeDBTime &ctCreateTime)
const SeDBTime& SePlayer::GetCreateTime() const
void SePlayer::SetCharLevel(DWord level)
Referenced by UpdateCharMisc.
const DWord SePlayer::GetCharLevel() const
Referenced by TaskMgr::CheckReceiveCondition, BlockServer::CheckTaskGuanqia, BlockServer::CheckTaskRace, OperateLoading, BlockServer::ProcessRBL_UpdateScore, UpdateCharMisc.
void SePlayer::SetExp(DWord dwExp)
Referenced by UpdateCharMisc.
const DWord SePlayer::GetExp() const
Referenced by TaskMgr::GetTaskReward, OperateLoading, UpdateCharMisc.
void SePlayer::GetMatchBaseInfo(SeMatchBaseInfo &rkBaseInfo)
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail.
void SePlayer::GetScoreInfo(MatchType eMatchType, SeScoreInfo &rkScore, DWord &matchNum)
Referenced by BlockServer::ProcessMBL_GetPlayerMatchValue, BlockServer::ProcessMBL_RaceMatchLoadDetail.
const SeDBTime& SePlayer::GetEnterTime(void) const
Referenced by UpdateOnlineTime.
void SePlayer::SetOnlineTime(UInt uiOnlineTime)
Referenced by UpdateCharMisc, UpdateOnlineTime.
UInt SePlayer::GetOnlineTime(void) const
Referenced by OperateLoading, UpdateCharMisc, UpdateOnlineTime.
void SePlayer::SetBattleTime(SeDBTime &time)
Referenced by UpdateCharMisc.
const SeDBTime& SePlayer::GetBattleTime() const
Referenced by UpdateCharMisc.
void SePlayer::SetLoginTime(SeDBTime &time)
Referenced by LoadingComplete.
const SeDBTime& SePlayer::GetLoginTime() const
void SePlayer::SetBattleField(const SeDBTime &time, int defeat, int score)
Referenced by BlockServer::ProcessRBL_UpdateScore.
void SePlayer::GetBattleField(int &defeat, int &score)
Referenced by BlockServer::ProcessRBL_UpdateScore, WorldServer::UserInfoSync_PlayerScore.
void SePlayer::SetMatch(const SeDBTime &time, int defeat, int score, int num)
Referenced by BlockServer::ProcessRBL_UpdateScore.
void SePlayer::GetMatch(int &defeat, int &score, int &num)
Referenced by BlockServer::ProcessRBL_UpdateScore, WorldServer::UserInfoSync_PlayerScore.
void SePlayer::SetLadder(const SeDBTime &time, int defeat, int score, int no, int level)
Referenced by BlockServer::ProcessRBL_UpdateScore.
void SePlayer::SetEquipSetIndex(Byte index)
Referenced by UpdateCharMisc.
Byte SePlayer::GetEquipSetIndex() const
Referenced by OperateLoading, BlockServer::ProcessMBL_RaceMatchLoadDetail, UpdateCharMisc.
void SePlayer::SetRaceCumuGolds(DWord golds)
Referenced by UpdateCharMisc.
DWord SePlayer::GetRaceCumuGolds() const
Referenced by UpdateCharMisc.
void SePlayer::SetUserAvatar(DWord avatar)
Referenced by BlockServer::ProcessWBL_PlayerValidate, UpdateCharMisc.
DWord SePlayer::GetUserAvatar() const
Referenced by BlockServer::ProcessRBL_UpdateScore, BlockServer::ProcessTBL_UserAlterAvatarFrameReq, BlockServer::ProcessTBL_UserAlterAvatarReq, BlockServer::ProcessTBL_UserPurchaseAvatarReq, UpdateCharMisc.
void SePlayer::SetUserAvatarFrame(DWord avatarFrame)
Referenced by BlockServer::ProcessWBL_PlayerValidate, UpdateCharMisc.
DWord SePlayer::GetUserAvatarFrame() const
Referenced by BlockServer::ProcessTBL_UserAlterAvatarFrameReq, BlockServer::ProcessTBL_UserAlterAvatarReq, BlockServer::ProcessTBL_UserPurchaseAvatarReq, UpdateCharMisc.
const SeDBTime& SePlayer::GetTaskResetTime() const
Referenced by TaskMgr::RefreshTask.
void SePlayer::SetTaskResetTime(const SeDBTime &time)
Referenced by TaskMgr::RefreshTask.
DWord SePlayer::GetTaskResetCount() const
Referenced by TaskMgr::ResetTask.
void SePlayer::SetTaskResetCount(DWord count)
Referenced by TaskMgr::RefreshTask, TaskMgr::ResetTask.
int SePlayer::GetEquipFightScore()
Referenced by TaskMgr::CheckReceiveCondition.
void SePlayer::GetLadder(int &defeat, int &score, int &no, int &level, time_t *time=NULL)
References adjustDefeat, adjustLadderNo, DEFAULT_DEFEAT, DEFAULT_SCORE, g_kLadderLevelMgr, g_kWorldServer, WorldServer::GetConfig, getInfoMgr, LadderLevelMgr::getLevel, GetTDBTime, SeWorldConfig::iLadderNo, NowTime.
Referenced by TaskMgr::CheckReceiveCondition, OperateLoading, BlockServer::ProcessRBL_UpdateScore, WorldServer::UserInfoSync_PlayerScore.
void SePlayer::UpdateCharMisc(SeCharMiscType eType, int iVal)
References CMT_AVATAR, CMT_AVATARFRAME, CMT_DIAMOND, CMT_EQUIPSETINDEX, CMT_EXP, CMT_GOLD, CMT_LEVEL, CMT_ONLINE_TIME, CMT_RACECUMUGOLDS, g_kWorldServer, GetCharLevel, GetDiamond, GetEquipSetIndex, GetExp, GetGold, GetID, GetOnlineTime, GetRaceCumuGolds, GetUserAvatar, GetUserAvatarFrame, WorldServer::SendDBServer_CharUpdateMisc, SetCharLevel, SetDiamond, SetEquipSetIndex, SetExp, SetGold, SetOnlineTime, SetRaceCumuGolds, SetUserAvatar, SetUserAvatarFrame.
Referenced by CShop::BuyItem, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold, CItemMgr::doItemMergeCharge, TaskMgr::GetTaskReward, BlockServer::ProcessRBL_RaceEndArenaBaseInfoSync, BlockServer::ProcessRBL_SetEquipSetNtf, BlockServer::ProcessTBL_GMSetDiamond, BlockServer::ProcessTBL_GMSetGold, BlockServer::ProcessTBL_UserAlterAvatarFrameReq, BlockServer::ProcessTBL_UserAlterAvatarReq, BlockServer::ProcessTBL_UserPurchaseAvatarReq, BlockServer::ProcessWBL_UserAlterNickNameReq.
void SePlayer::UpdateCharMisc(SeCharMiscType eType, const char *str)
References CMT_NAME, g_kWorldServer, GetID, GetName, WorldServer::SendDBServer_CharUpdateMisc, SetName.
void SePlayer::UpdateCharMisc(SeCharMiscType eType, SeDBTime db_time)
References CMT_BATTLETIME, g_kWorldServer, GetBattleTime, GetID, WorldServer::SendDBServer_CharUpdateMisc, SetBattleTime.
int SePlayer::GetMoney(SeMoneyType eType)
References GetDiamond, GetGold, SMNT_DIAMOND, SMNT_GOLD.
DWord SePlayer::UpdateOnlineTime()
References CMT_ONLINE_TIME, DiffDBTime, g_kWorldServer, GetEnterTime, GetID, GetOnlineTime, NowTime, WorldServer::SendDBServer_CharUpdateMisc, SetOnlineTime.
Referenced by BlockServer::KickPlayerByID.
bool SePlayer::OnRenameBegin(const char *pcName)
References ClrFlag, g_kWorldServer, GetID, HasFlag, WorldServer::SendDBServer_CharInfoRename, SetFlag, SPF_RENAME.
Referenced by BlockServer::ProcessWBL_PlayerRenameBegin.
bool SePlayer::OnRenameEnd(const char *pcName)
References g_kWorldServer, GetID, GetName, GetTownSock, WorldServer::SendWT_PlayerRename, SetName, SSD_MAX_CHAR_NAME, StrCpy.
Referenced by BlockServer::ProcessWBL_PlayerRenameEnd.
void SePlayer::LoadExchangeInfo(const SeExChangeInfo &rkExchange)
References SeExChangeInfo::Copy, m_akExchange.
SeExChangeInfo * SePlayer::GetExchangeByID(int iType)
References SeExChangeInfo::dwTypeID, m_akExchange.
void SePlayer::GetAllExchange(VPtlExchange &rkExchange)
References SeExChangeInfo::GetPtlExchange, m_akExchange, NowTime.
Referenced by OperateLoading.
bool SePlayer::OnItemExchangeCheck(int iType)
Referenced by BlockServer::ProcessWBL_ItemExchange.
CItemMgr* SePlayer::GetItemMgr()
References m_PlayerItemMgr.
Referenced by CShop::BuyItem, CShop::CheckSoleItem, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold, ActiveAvatarMgr::fixData, EquipSchemaMgr::fixData, HeroMgr::fixData, ActiveAvatarMgr::getAvatars, EquipSchemaMgr::getEquips, TaskMgr::GetTaskReward, HeroMgr::processAddHeroBindItem, BlockServer::ProcessMBL_RaceMatchLoadDetail, BlockServer::ProcessRBL_AwardItemNtf, BlockServer::ProcessRBL_DecRespawnItemNtf, BlockServer::ProcessTBL_ClearItemNewFlag, BlockServer::ProcessTBL_DelelteItem, BlockServer::ProcessTBL_GMAddItem, BlockServer::ProcessTBL_OpenRandBox, BlockServer::ProcessTBL_ReqItemCiTiaoChange, BlockServer::ProcessTBL_ReqItemDepart, BlockServer::ProcessTBL_ReqItemStrenth, BlockServer::ProcessWBL_UserAlterNickNameReq, EquipSchemaMgr::putOnEquip, ActiveAvatarMgr::setActiveAvatar, HeroMgr::setAvatar.
void SePlayer::LoadNexusFriend(const SeCharNexusFriendData &rDat)
References SeCharNexusFriendData::char_friend_id, SeCharNexusFriendData::Copy, m_mapNexusFriendData.
Referenced by BlockServer::SeBSProcess_CharNexusFriend.
void SePlayer::LoadStatMap(SeMapClass eClass, const SeStatMap &rkStatMap)
References SeStatMap::Copy, eClass, m_akStatMap, SMC_NUM.
void SePlayer::LoadRaceHistory(const SeRaceHistory &rkRaceHistory)
SeStatMap * SePlayer::GetStatMapByID(DWord dwMapID)
References SeStatMap::dwMapID, m_akStatMap, SMC_NUM.
void SePlayer::GetQueryMapList(int iMapClass, VPtlStaMap &rkMapList)
References SeStatMap::GetPtlStaMap, m_akStatMap, SMC_NUM.
void SePlayer::GetStatMapNum(int iMapClass, int &iTotalNum, int &iWinNum)
References SeStatMap::iNums, SeStatMap::iWin, m_akStatMap, SMC_NUM.
void SePlayer::LoadMemoryData(DWord dwType, const SeCharMemory &rkData)
References m_kMAllCharMem.
Referenced by BlockServer::SeBSProcess_CharMemoryLoad.
void SePlayer::UpdateMemoryData(DWord dwType, DWord dwParam, DWord dwValue, SeDBTime &rkEndTime)
References SeCharMemory::dwParam, SeCharMemory::dwValue, g_kWorldServer, GetID, SeCharMemory::IsOverdue, SeCharMemory::kEndTime, m_kMAllCharMem, NowTime, WorldServer::SendDBServer_CharMemoryUpdate.
Referenced by BlockServer::ProcessWBL_MatchRaceLoad.
DWord SePlayer::GetMemoryValue(DWord dwType, DWord dwParam)
References SeCharMemory::dwParam, SeCharMemory::dwValue, SeCharMemory::IsOverdue, m_kMAllCharMem, NowTime.
void SePlayer::NotifyOwnMoney()
References SeWT_PlayerMoneyAndDiamond::dwDiamond, SeWT_PlayerMoneyAndDiamond::dwGold, SeWT_PlayerMoneyAndDiamond::dwPlayerID, g_kWorldServer, GetDiamond, GetGold, GetID, GetTownSock, WorldServer::SendWT_PlayerMoneyAndDiamond.
Referenced by CShop::BuyItem, CShop::CurrencyBuyItem_Diamond, CShop::CurrencyBuyItem_Gold, CItemMgr::doItemMergeCharge, TaskMgr::GetTaskReward, OperateLoading, BlockServer::ProcessRBL_RaceEndArenaBaseInfoSync, BlockServer::ProcessTBL_GMSetDiamond, BlockServer::ProcessTBL_GMSetGold.
bool SePlayer::LoadFriendLadderInfo(DWord dwFriendID, DWord dwLadderLevel, DWord score, DWord dwIconId, DWord dwPlayerLevel, const char *acName)
References SeCharLadderData::Load, m_FriendLadderData, m_FriendNum.
Referenced by BlockServer::SeBSProcess_LoadFriendLadderInfo.
void SePlayer::SetCurrFriendNumForAck(DWord num)
References m_FriendNum.
Referenced by WorldServer::UserInfoSync_LoadFriendLadderRank.
void SePlayer::UploadFriendData(std::vector< SeLadderRankInfo > &vLadderInfo)
References m_FriendLadderData, m_FriendNum.
Referenced by BlockServer::ProcessBBL_SelectFriendDataRet.
TaskMgr & SePlayer::getTaskMgr()
References m_TaskMgr.
Referenced by CItemMgr::AddItem, BlockServer::CheckTaskGuanqia, BlockServer::CheckTaskRace, OperateLoading, BlockServer::ProcessRBL_UpdateScore, HeroMgr::unlockHero.
void SePlayer::AddPlayerMail(std::vector< pair< int, int >> &vReward)
Referenced by TaskMgr::RefreshTask.
bool SePlayer::IsPassChapter(DWord dwChapterID)
Referenced by TaskMgr::SettleTask.
DataMgr<T>& SePlayer::getDataMgr()
Referenced by DefaultPlayerDataStrategy< TABLE, T, DATA >::fixData, PlayerDataStrategy::onLoadData.
EquipSchemaMgr & SePlayer::getEquipSchemaMgr()
References m_equipSchemaMgr.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail, BlockServer::ProcessTBL_PutOnEquip, BlockServer::ProcessTBL_TakeOffEquip.
RaceHeroMgr & SePlayer::getRaceHeroMgr()
References m_raceHeroMgr.
Referenced by BlockServer::ProcessRBL_SetRaceMapHeroNtf, BlockServer::ProcessTBL_UserMapRaceHeroReq.
HeroMgr & SePlayer::getHeroMgr()
References m_heroMgr.
Referenced by CShop::ProcessHeroItem, BlockServer::ProcessMBL_RaceMatchLoadDetail, BlockServer::ProcessRBL_SelectHeroReq, BlockServer::ProcessRBL_SetAvatarNtf.
ActiveAvatarMgr & SePlayer::getActiveAvatarMgr()
References m_activeAvatarMgr.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail, BlockServer::ProcessTBL_SetActiveAvatarReq.
InfoMgr & SePlayer::getInfoMgr()
References m_infoMgr.
Referenced by GetLadder.
const InfoMgr & SePlayer::getInfoMgr() const
References m_infoMgr.
RaceMapMgr & SePlayer::getRaceMapMgr()
References m_raceMapMgr.
Referenced by BlockServer::ProcessRBL_UserRaceMapNtf, BlockServer::ProcessTBL_LadderDetailInfoReq, BlockServer::ProcessTBL_UserRaceMapDetailReq.
MCharNexusFriendData & SePlayer::GetMCharNexusFriendData()
References m_mapNexusFriendData.
Referenced by WorldServer::UserInfoSync_LoadFriendLadderRank, WorldServer::UserInfoSync_NexusFriend.
uint64_t SePlayer::GetNexusFriendGenID(DWORD dwFriendId)
References SeCharNexusFriendData::id, m_mapNexusFriendData.
Referenced by BlockServer::ProcessWBL_DelNexusFriend, BlockServer::ProcessWBL_UpdateNexusFriend.
SeCharNexusFriendData * SePlayer::GetCharNexusFriendData(DWORD dwFriendId)
References m_mapNexusFriendData.
Referenced by BlockServer::ProcessTBL_FriendLadderInfoReq, BlockServer::ProcessWBL_CreateNexusFriend.
SePlayer::SePlayer(DWord dwPlayerID)
SePlayer::~SePlayer(void)
void SePlayer::Finalize()
void SePlayer::Update(DWord dwCurTime)
void SePlayer::LoadingComplete()
DWord SePlayer::GetID(void) const
void SePlayer::SetAccountInfo(SePtlAccountInfo &rkAccountInfo)
const SePtlAccountInfo& SePlayer::GetAccountInfo(void) const
const char* SePlayer::GetAccount(void) const
int SePlayer::GetPlatFlag(void) const
void SePlayer::SetMobileInfo(SeMobileInfo &rkMobileInfo)
const SeMobileInfo& SePlayer::GetMobileInfo(void) const
void SePlayer::SetSessionID(DWord dwSessionID)
DWord SePlayer::GetSessionID(void)
void SePlayer::SetTownIndex(int iIndex)
int SePlayer::GetTownIndex(void) const
void SePlayer::SetTownServerID(DWord dwTownServerID)
DWord SePlayer::GetTownServerID(void) const
void SePlayer::SetTownSock(HSock kTownSock)
HSock& SePlayer::GetTownSock(void)
void SePlayer::SetState(SePlayerState eState)
void SePlayer::SetTemState(SePlayerState eState)
SePlayerState SePlayer::GetState(void)
bool SePlayer::HasFlag(int iFlag) const
void SePlayer::SetFlag(int iFlag)
void SePlayer::setLoadingFlag(SeDBTableIndex eTable)
void SePlayer::clearLoadingFlag(SeDBTableIndex eTable)
void SePlayer::ClrFlag(int iFlag)
void SePlayer::SetLoadComplete(bool bComplete)
bool SePlayer::IsLoadComplete(void)
void SePlayer::SetLoadInfoAgain(bool bLoadInfoAgain)
bool SePlayer::GetLoadInfoAgain(void)
void SePlayer::SetBeginLoadAgainTime(DWord dwTime)
void SePlayer::SetLoadFlag(int iFlag)
bool SePlayer::isLoadingComplete()
bool SePlayer::HasLoadFlag(int iFlag)
void SePlayer::SetLoadFlagCount(SeLoadFlag eFlag, int iCount)
int SePlayer::GetLoadFlagCount(SeLoadFlag eFlag)
void SePlayer::SetLoadFlagCount(SeDBTableIndex eTable, int iCount)
int SePlayer::GetLoadFlagCount(SeDBTableIndex eTable)
void SePlayer::SetBlockServer(BlockServer *pkBlockServer)
void SePlayer::SetPlayerIP(DWord dwPlayerIP)
DWord SePlayer::GetPlayerIP()
void SePlayer::SetMaxMailID(DWord dwMaxMailID)
DWord SePlayer::GetMaxMailID()
void SePlayer::SetBeginLoadTime(DWord dwTime)
void SePlayer::SetName(const char *pcName)
const char* SePlayer::GetName(void) const
void SePlayer::SetGold(int iGold)
int SePlayer::GetGold(void) const
void SePlayer::SetDiamond(int iDiamond)
int SePlayer::GetDiamond(void) const
void SePlayer::SetCreateTime(SeDBTime &ctCreateTime)
const SeDBTime& SePlayer::GetCreateTime() const
void SePlayer::SetCharLevel(DWord level)
const DWord SePlayer::GetCharLevel() const
void SePlayer::SetExp(DWord dwExp)
const DWord SePlayer::GetExp() const
void SePlayer::GetMatchBaseInfo(SeMatchBaseInfo &rkBaseInfo)
void SePlayer::GetScoreInfo(MatchType eMatchType, SeScoreInfo &rkScore, DWord &matchNum)
const SeDBTime& SePlayer::GetEnterTime(void) const
void SePlayer::SetOnlineTime(UInt uiOnlineTime)
UInt SePlayer::GetOnlineTime(void) const
void SePlayer::SetBattleTime(SeDBTime &time)
const SeDBTime& SePlayer::GetBattleTime() const
void SePlayer::SetLoginTime(SeDBTime &time)
const SeDBTime& SePlayer::GetLoginTime() const
void SePlayer::SetBattleField(const SeDBTime &time, int defeat, int score)
void SePlayer::GetBattleField(int &defeat, int &score)
void SePlayer::SetMatch(const SeDBTime &time, int defeat, int score, int num)
void SePlayer::GetMatch(int &defeat, int &score, int &num)
void SePlayer::SetLadder(const SeDBTime &time, int defeat, int score, int no, int level)
void SePlayer::SetEquipSetIndex(Byte index)
Byte SePlayer::GetEquipSetIndex() const
void SePlayer::SetRaceCumuGolds(DWord golds)
DWord SePlayer::GetRaceCumuGolds() const
void SePlayer::SetUserAvatar(DWord avatar)
DWord SePlayer::GetUserAvatar() const
void SePlayer::SetUserAvatarFrame(DWord avatarFrame)
DWord SePlayer::GetUserAvatarFrame() const
const SeDBTime& SePlayer::GetTaskResetTime() const
void SePlayer::SetTaskResetTime(const SeDBTime &time)
DWord SePlayer::GetTaskResetCount() const
void SePlayer::SetTaskResetCount(DWord count)
int SePlayer::GetEquipFightScore()
void SePlayer::GetLadder(int &defeat, int &score, int &no, int &level, time_t *time=NULL)
void SePlayer::UpdateCharMisc(SeCharMiscType eType, int iVal)
void SePlayer::UpdateCharMisc(SeCharMiscType eType, const char *str)
void SePlayer::UpdateCharMisc(SeCharMiscType eType, SeDBTime db_time)
int SePlayer::GetMoney(SeMoneyType eType)
DWord SePlayer::UpdateOnlineTime()
bool SePlayer::OnRenameBegin(const char *pcName)
bool SePlayer::OnRenameEnd(const char *pcName)
void SePlayer::LoadExchangeInfo(const SeExChangeInfo &rkExchange)
SeExChangeInfo* SePlayer::GetExchangeByID(int iType)
void SePlayer::GetAllExchange(VPtlExchange &rkExchange)
bool SePlayer::OnItemExchangeCheck(int iType)
CItemMgr* SePlayer::GetItemMgr()
References m_PlayerItemMgr.
void SePlayer::LoadNexusFriend(const SeCharNexusFriendData &rDat)
void SePlayer::LoadStatMap(SeMapClass eClass, const SeStatMap &rkStatMap)
void SePlayer::LoadRaceHistory(const SeRaceHistory &rkRaceHistory)
SeStatMap* SePlayer::GetStatMapByID(DWord dwMapID)
void SePlayer::GetQueryMapList(int iMapClass, VPtlStaMap &rkMapList)
void SePlayer::GetStatMapNum(int iMapClass, int &iTotalNum, int &iWinNum)
void SePlayer::LoadMemoryData(DWord dwType, const SeCharMemory &rkData)
void SePlayer::UpdateMemoryData(DWord dwType, DWord dwParam, DWord dwValue, SeDBTime &rkEndTime)
DWord SePlayer::GetMemoryValue(DWord dwType, DWord dwParam)
void SePlayer::NotifyOwnMoney()
bool SePlayer::LoadFriendLadderInfo(DWord dwFriendID, DWord dwLadderLevel, DWord score, DWord dwIconId, DWord dwPlayerLevel, const char *acName)
void SePlayer::SetCurrFriendNumForAck(DWord num)
void SePlayer::UploadFriendData(std::vector< SeLadderRankInfo > &vLadderInfo)
TaskMgr& SePlayer::getTaskMgr()
void SePlayer::AddPlayerMail(std::vector< pair< int, int >> &vReward)
bool SePlayer::IsPassChapter(DWord dwChapterID)
DataMgr<T>& SePlayer::getDataMgr()
EquipSchemaMgr& SePlayer::getEquipSchemaMgr()
RaceHeroMgr& SePlayer::getRaceHeroMgr()
HeroMgr& SePlayer::getHeroMgr()
ActiveAvatarMgr& SePlayer::getActiveAvatarMgr()
InfoMgr& SePlayer::getInfoMgr()
const InfoMgr& SePlayer::getInfoMgr() const
RaceMapMgr& SePlayer::getRaceMapMgr()
MCharNexusFriendData& SePlayer::GetMCharNexusFriendData()
uint64_t SePlayer::GetNexusFriendGenID(DWORD dwFriendId)
SeCharNexusFriendData* SePlayer::GetCharNexusFriendData(DWORD dwFriendId)
DataMgr< SeDBCharAchieveFinish > & SePlayer::getDataMgr()
References m_AchieveFinishMgr.
DataMgr< SeDBCharAchieveSchedule > & SePlayer::getDataMgr()
References m_AchieveScheduleMgr.
DataMgr< SeDBCharActiveAvatar > & SePlayer::getDataMgr()
References m_activeAvatarMgr.
DataMgr< SeDBCharEquipSchema > & SePlayer::getDataMgr()
References m_equipSchemaMgr.
DataMgr< SeDBCharHero > & SePlayer::getDataMgr()
References m_heroMgr.
DataMgr< SeDBCharInfo > & SePlayer::getDataMgr()
References m_infoMgr.
DataMgr< SeDBCharItem > & SePlayer::getDataMgr()
References m_PlayerItemMgr.
DataMgr< SeDBCharRaceHero > & SePlayer::getDataMgr()
References m_raceHeroMgr.
DataMgr< SeDBCharRaceArena > & SePlayer::getDataMgr()
References m_raceMapMgr.
DataMgr< SeDBCharTask > & SePlayer::getDataMgr()
References m_TaskMgr.
void SePlayer::InitPlayerPos(float &fX, float &fY)
Referenced by SePlayer.
void SePlayer::InitPlayerPos(float &fX, float &fY)
DWord SePlayer::DisplayLoadConsumeTime(void)
References GetID, GetLoadInfoAgain, BlockServer::GetLogShowType, BlockServer::GetServerTime, m_dwBeginLoadAgainTime, m_dwBeginLoadTime, m_pkBlockServer, SeLogInfo.
Referenced by LoadingComplete.
void SePlayer::OperateLoading(void)
References SeLadderInfo::byLadderDefeat, HeroMgr::createFreeHeroes, SeLadderInfo::dwLadderScore, SeLadderInfo::dwLadderTime, g_kWorldServer, GetAllExchange, GetCharLevel, GetDiamond, GetEquipSetIndex, GetExp, GetGold, GetID, GetLadder, GetName, GetOnlineTime, getTaskMgr, GetTownSock, m_activeAvatarMgr, m_equipSchemaMgr, m_heroMgr, m_PlayerItemMgr, NotifyOwnMoney, OnTownLoginLog, CItemMgr::PackAllItem, TaskMgr::RefreshTask, SeLogError, ActiveAvatarMgr::sendInitData, HeroMgr::sendInitData, EquipSchemaMgr::sendInitData, WorldServer::SendWT_ExchangeInit, WorldServer::SendWT_InitPlayerInfo, WorldServer::UserInfoSync, SeLadderInfo::wLadderLevel.
Referenced by LoadingComplete.
void SePlayer::OnTownLoginLog(void)
Referenced by OperateLoading.
bool SePlayer::ExChangeGive(int iResultType, int iNum)
bool SePlayer::OnUseItem(DWord dwlItemID, DWord dwTypeID, int iPileCount, SeItemReason eOrgReason, DWord dwAddFavor)
References TownItemTableMgr::Get, GetID, GetID2Str, TownItemTableMgr::GetTownItemTable, ParseUseItemByTypeID, SeLogError.
bool SePlayer::ParseUseItemByTypeID(const TownItemTable *pkItemRes, int iPileCount, DWord dwAddFavor)
Referenced by OnUseItem.
bool SePlayer::CanItemUseWhenAdd(const TownItemTable *pkItemRes, int iPileCount)
References IsLoadComplete.
DWord SePlayer::DisplayLoadConsumeTime(void)
void SePlayer::OperateLoading(void)
void SePlayer::OnTownLoginLog(void)
bool SePlayer::ExChangeGive(int iResultType, int iNum)
bool SePlayer::OnUseItem(DWord dwlItemID, DWord dwTypeID, int iPileCount, SeItemReason eOrgReason, DWord dwAddFavor)
bool SePlayer::ParseUseItemByTypeID(const TownItemTable *pkItemRes, int iPileCount, DWord dwAddFavor)
bool SePlayer::CanItemUseWhenAdd(const TownItemTable *pkItemRes, int iPileCount)
static void SePlayer::adjustDefeat(SeDBTime &dbTime, DWord &defeat)
Referenced by GetLadder.
static void SePlayer::adjustDefeat(SeDBTime &dbTime, DWord &defeat)
void SePlayer::adjustLadderNo(DWord &iLadderNo, DWord &iLadderLevel, DWord &iLadderScore)
References g_kLadderLevelMgr, g_kWorldServer, WorldServer::GetConfig, LadderLevelMgr::getLevel, LadderLevelMgr::getNewLadderScore, SeWorldConfig::iLadderNo.
Referenced by GetLadder.
static void SePlayer::adjustLadderNo(DWord &iLadderNo, DWord &iLadderLevel, DWord &iLadderScore)