SkillTableMgr
std::map<unsigned int,SkillTable*> SkillTableMgr::m_kSkillTableMap
Referenced by FillData, GetSkillTable, GetSkillTableMap, GetSkillTableVec, ~SkillTableMgr.
SkillTableMgr * SkillTableMgr::m_pkSkillTableMgr
Referenced by Get, ReLoad.
SkillTableMgr * SkillTableMgr::Get()
References m_pkSkillTableMgr, SkillTableMgr.
Referenced by ItemTableMgr::EvalFormatElement, GlobalTableMgr::GetSkillTable, TableMgr::LoadTable, ReLoad.
SkillTableMgr * SkillTableMgr::ReLoad()
References Get, m_pkSkillTableMgr.
Referenced by TableMgr::ReloadTable.
SkillTableMgr::SkillTableMgr()
References Load.
Referenced by Get.
SkillTableMgr::~SkillTableMgr()
References m_kSkillTableMap.
const SkillTable * SkillTableMgr::GetSkillTable(unsigned int iTypeID)
References m_kSkillTableMap.
Referenced by ItemTableMgr::EvalFormatElement, GlobalTableMgr::GetSkillTable.
const std::map< unsigned int, SkillTable * > & SkillTableMgr::GetSkillTableMap()
References m_kSkillTableMap.
TableResArray SkillTableMgr::GetSkillTableVec()
References m_kSkillTableMap, TableResArray::pushBack.
bool SkillTableMgr::Load()
References LoadSkillFile.
Referenced by SkillTableMgr.
bool SkillTableMgr::LoadSkillFile(std::string path)
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by Load.
void SkillTableMgr::FillData(SkillTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, SkillTable::bAICast, SkillTable::fAAdj, SkillTable::fBAdj, SkillTable::fCAdj, SkillTable::fDAdj, SkillTable::fEAdj, SkillTable::fFAdj, SkillTable::fFightScore, SkillTable::fManaSpend, SkillTable::fMissileArc, SkillTable::fMissileSpeed, SkillTable::fValueA, SkillTable::fValueB, SkillTable::fValueC, SkillTable::fValueD, SkillTable::fValueE, SkillTable::fValueF, SkillTable::iAdditional, SkillTable::iCastTime, SkillTable::iCastVoice, SkillTable::iCoolDown, SkillTable::iDecalType, SkillTable::iDesc, SkillTable::iDstPosEffect, SkillTable::iDstUnitEffect, SkillTable::iEffectScope, SkillTable::iEffectSound, SkillTable::iEffectTime, SkillTable::iHoldTime, SkillTable::iLearnLevel, SkillTable::iMissileModel, SkillTable::iName, SkillTable::iNums, SkillTable::iPrepareSound, SkillTable::iShopPos, SkillTable::iSkillDistance, SkillTable::iSkillEffect, SkillTable::iSkillMaxLevel, SkillTable::iSpecialSound, SkillTable::iSrcEffect, SkillTable::iTower, SkillTable::iUIShowPos, SkillTable::kDesc_China, SkillTable::kLearnIcon, SkillTable::kName_China, SkillTable::kSimpleDesc, m_kSkillTableMap, SkillTable::uiAAdj, SkillTable::uiAttackType, SkillTable::uiBAdj, SkillTable::uiBufferArray, SkillTable::uiBufferID, SkillTable::uiCAdj, SkillTable::uiDAdj, SkillTable::uiDataContentA, SkillTable::uiDataContentB, SkillTable::uiDataContentC, SkillTable::uiDataContentD, SkillTable::uiDataContentE, SkillTable::uiDataContentF, SkillTable::uiEAdj, SkillTable::uiFAdj, SkillTable::uiOperateType, SkillTable::uiOriginTypeID, SkillTable::uiSkillOtherProperty, SkillTable::uiSkillProperty, SkillTable::uiSpecialID, SkillTable::uiSpellAction, SkillTable::uiTalentTips, SkillTable::uiTargetType, SkillTable::uiTypeID.
Referenced by LoadSkillFile.