PetTableMgr
std::map<unsigned int,PetTable*> PetTableMgr::m_kPetTableMap
Referenced by FillData, GetPetTable, GetPetTableMap, GetPetTableVec, ~PetTableMgr.
PetTableMgr * PetTableMgr::m_pkPetTableMgr
Referenced by Get, ReLoad.
PetTableMgr * PetTableMgr::Get()
References m_pkPetTableMgr, PetTableMgr.
Referenced by TableMgr::GetRaceHelpMasterySkillTypes, TableMgr::InitPetPosIndex, ReLoad.
PetTableMgr * PetTableMgr::ReLoad()
References Get, m_pkPetTableMgr.
PetTableMgr::PetTableMgr()
References Load.
Referenced by Get.
PetTableMgr::~PetTableMgr()
References m_kPetTableMap.
const PetTable * PetTableMgr::GetPetTable(unsigned int iTypeID)
References m_kPetTableMap.
Referenced by TableMgr::GetRaceHelpMasterySkillTypes.
const std::map< unsigned int, PetTable * > & PetTableMgr::GetPetTableMap()
References m_kPetTableMap.
Referenced by TableMgr::InitPetPosIndex.
TableResArray PetTableMgr::GetPetTableVec()
References m_kPetTableMap, TableResArray::pushBack.
bool PetTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by PetTableMgr.
void PetTableMgr::FillData(PetTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, PetTable::iAssistPowerValue, PetTable::iAttackPowerValue, PetTable::iBasicPetPower, PetTable::iDefensePowerValue, PetTable::iHeroHonor, PetTable::iLevelAddPetPower, PetTable::iMagicPowerValue, PetTable::iModelFile, PetTable::iName, PetTable::iNameTips, PetTable::iShop_list_4, PetTable::iShop_list_5, PetTable::iShop_list_6, PetTable::kIcon, PetTable::kName_China, PetTable::kName_China1, m_kPetTableMap, PetTable::uiPetID.
Referenced by Load.