SeTimer
DWord SeTimer::m_dwInterValue
Referenced by GetInterValue, GetRemainTime, IsPassed, SeTimer, SetInterValue.
DWord SeTimer::m_dwLastTime
Referenced by GetRemainTime, IsPassed, Reset, SeTimer, SetInterValue.
DWord SeTimer::m_dwNowTime
Referenced by GetRemainTime, IsPassed, SeTimer, SetInterValue, Update.
bool SeTimer::m_bIsVaild
Referenced by IsVaild, SeTimer, SetVaild.
SeTimer::SeTimer()
References m_bIsVaild, m_dwInterValue, m_dwLastTime, m_dwNowTime.
SeTimer::~SeTimer()
void SeTimer::SetInterValue(DWord dwTime, DWord dwCurTime=0)
References m_dwInterValue, m_dwLastTime, m_dwNowTime.
Referenced by SeRaceMgr::Initialize, SeOpenRoomMgr::OnRoomInviteRspOk, SeOpenRoomMgr::OnRoomJoin, SeOpenRoom::SeOpenRoom, SeVirtConnMgr::SeVirtConnMgr, SeOpenRoomMgr::StartMatch.
int SeTimer::GetInterValue()
References m_dwInterValue.
bool SeTimer::IsPassed()
References m_dwInterValue, m_dwLastTime, m_dwNowTime.
Referenced by SeOpenRoomMgr::Update, SeRaceMgr::Update, SeVirtConnMgr::Update.
void SeTimer::SetVaild(bool bVaild)
References m_bIsVaild.
bool SeTimer::IsVaild()
References m_bIsVaild.
void SeTimer::Reset()
References m_dwLastTime.
void SeTimer::Update(DWord dwTime)
References m_dwNowTime.
Referenced by SeRaceMgr::Update, SeVirtConnMgr::Update.
DWord SeTimer::GetRemainTime()
References m_dwInterValue, m_dwLastTime, m_dwNowTime.