RaceStaMissionTableMgr
std::map<unsigned int,RaceStaMissionTable*> RaceStaMissionTableMgr::m_kRaceStaMissionTableMap
Referenced by FillData, GetRaceStaMissionTable, GetRaceStaMissionTableMap, GetRaceStaMissionTableVec, ~RaceStaMissionTableMgr.
RaceStaMissionTableMgr * RaceStaMissionTableMgr::m_pkRaceStaMissionTableMgr
Referenced by Get, ReLoad.
RaceStaMissionTableMgr * RaceStaMissionTableMgr::Get()
References m_pkRaceStaMissionTableMgr, RaceStaMissionTableMgr.
Referenced by ReLoad.
RaceStaMissionTableMgr * RaceStaMissionTableMgr::ReLoad()
References Get, m_pkRaceStaMissionTableMgr.
RaceStaMissionTableMgr::RaceStaMissionTableMgr()
References Load.
Referenced by Get.
RaceStaMissionTableMgr::~RaceStaMissionTableMgr()
References m_kRaceStaMissionTableMap.
const RaceStaMissionTable * RaceStaMissionTableMgr::GetRaceStaMissionTable(unsigned int iTypeID)
References m_kRaceStaMissionTableMap.
const std::map< unsigned int, RaceStaMissionTable * > & RaceStaMissionTableMgr::GetRaceStaMissionTableMap()
References m_kRaceStaMissionTableMap.
TableResArray RaceStaMissionTableMgr::GetRaceStaMissionTableVec()
References m_kRaceStaMissionTableMap, TableResArray::pushBack.
bool RaceStaMissionTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RaceStaMissionTableMgr.
void RaceStaMissionTableMgr::FillData(RaceStaMissionTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RaceStaMissionTable::iItemNums, RaceStaMissionTable::iProbability, RaceStaMissionTable::kComment, RaceStaMissionTable::kDesc, RaceStaMissionTable::kExtraScore, RaceStaMissionTable::kItemDesc, RaceStaMissionTable::kRefValueA, RaceStaMissionTable::kRefValueB, m_kRaceStaMissionTableMap, RaceStaMissionTable::uiACID, RaceStaMissionTable::uiDifficulty, RaceStaMissionTable::uiDropProperty, RaceStaMissionTable::uiItemID, RaceStaMissionTable::uiMainChance, RaceStaMissionTable::uiMapID, RaceStaMissionTable::uiPrize, RaceStaMissionTable::uiPrizeCond, RaceStaMissionTable::uiRefID, RaceStaMissionTable::uiTypeID.
Referenced by Load.