SeMatchPlayer
HSock SeMatchPlayer::m_kSock
Referenced by SeMatchPlayer.
bool SeMatchPlayer::m_bValidateOK
Referenced by SeMatchPlayer.
DWord SeMatchPlayer::m_dwSessionID
Referenced by SeMatchPlayer, ~SeMatchPlayer.
SeMatchPlayerState SeMatchPlayer::m_eState
Referenced by GetPlayerState, SeMatchPlayer, SetPlayerState.
DWord SeMatchPlayer::m_dwPlayerID
Referenced by AddPlayerInfo, ReconResetPlayerInfo, SeMatchPlayer, ViewSetPlayerInfo, ~SeMatchPlayer.
SeRoomPlayerCamp SeMatchPlayer::m_eCamp
Referenced by AddPlayerInfo, ReconResetPlayerInfo, SeMatchPlayer.
DWord SeMatchPlayer::m_dwAreaID
Referenced by AddPlayerInfo, ReconResetPlayerInfo, SeMatchPlayer, ViewSetPlayerInfo.
DWord SeMatchPlayer::m_dwServerID
Referenced by AddPlayerInfo, ReconResetPlayerInfo, SeMatchPlayer, ViewSetPlayerInfo.
int SeMatchPlayer::m_iTownRoomIndex
Referenced by AddPlayerInfo, SeMatchPlayer.
int SeMatchPlayer::m_iSeatIndex
Referenced by AddPlayerInfo, ReconResetPlayerInfo, SeMatchPlayer.
int SeMatchPlayer::m_iTeamMemberNum
Referenced by AddPlayerInfo, SeMatchPlayer.
DWord SeMatchPlayer::m_dwTeamID
Referenced by AddPlayerInfo, SeMatchPlayer.
SeMatchBaseInfo SeMatchPlayer::m_kBaseInfo
Referenced by AddPlayerInfo, ReconResetPlayerInfo.
SeMatchFightInfo SeMatchPlayer::m_kFightInfo
Referenced by AddPlayerInfo.
SeScoreInfo SeMatchPlayer::m_kScoreInfo
Referenced by AddPlayerInfo.
SeMatchOtherInfo SeMatchPlayer::m_kOtherInfo
Referenced by AddPlayerInfo, GetAchievementCountsIDs, getAvatarTypeID, GetEquipItem, GetRespawnItemCount, HasHero, IsValidate, pushHero, setAvatar, setEquipSetIndex, setRandomAvatar, SetSelHeroID.
bool SeMatchPlayer::m_bSendReturnWait
Referenced by SeMatchPlayer.
bool SeMatchPlayer::m_bRaceEndReport
Referenced by SeMatchPlayer.
TeMD5 SeMatchPlayer::m_kRaceID
DWord SeMatchPlayer::m_dwSelHeroID
Referenced by GetSelHeroID, SeMatchPlayer, SetSelHeroID.
SeHeroAvatar SeMatchPlayer::m_kHeroAvatar
Referenced by GetSelHeroAvatar, setAvatar, setRandomAvatar, SetSelHeroID.
SeMatchPlayer::DECLARE_POOL(SeMatchPlayer)
DWord SeMatchPlayer::getAvatarTypeID(DWord dwItemID)
References SeMatchOtherInfo::akSelectableAvatars, m_kOtherInfo.
Referenced by SetSelHeroID.
SeMatchPlayer::DECLARE_POOL(SeMatchPlayer)
DWord SeMatchPlayer::getAvatarTypeID(DWord dwItemID)
SeMatchPlayer::SeMatchPlayer(void)
References m_bRaceEndReport, m_bSendReturnWait, m_bValidateOK, m_dwAreaID, m_dwPlayerID, m_dwSelHeroID, m_dwServerID, m_dwSessionID, m_dwTeamID, m_eCamp, m_eState, m_iSeatIndex, m_iTeamMemberNum, m_iTownRoomIndex, m_kSock, SeLogDebug, SMPS_NULL, SRPC_INVALID.
SeMatchPlayer::~SeMatchPlayer(void)
References m_dwPlayerID, m_dwSessionID, SeLogDebug.
void SeMatchPlayer::SetHSock(HSock kSock)
Referenced by SeRaceRoomMgr::OnReconValidOK, SeRaceRoomMgr::OnViewValidOKRet, RaceServer::ProcessCR_RaceValidate.
HSock SeMatchPlayer::GetHSock(void) const
Referenced by SeRaceRoomMgr::CancelHero, SeRaceRoomMgr::IntoSelHero, SeRaceMgr::OnPlayerRaceViewBegin, SeRaceMgr::OnPlayerReconBegin, SeRaceRoomMgr::OnPlayerTalk, SeRaceMgr::OnPlayerView2Recon, SeRaceMgr::OnPlayerViewQuit, SeRaceRoomMgr::OnRaceLeave, SeRaceMgr::OnRaceModeEnd, RaceServer::ProcessBLR_SelectHeroAck, SeRaceRoomMgr::RecycleRoomPlayer, SeRaceRoomMgr::SelHero, SeRaceRoomMgr::SelHeroFight, SeRaceRoomMgr::SelHeroReady, SeRaceRoomMgr::SendRacePlayerBaseInfo.
bool SeMatchPlayer::IsValidSock(void)
bool SeMatchPlayer::IsValidate()
References SeMatchOtherInfo::akAcievementCounts, m_kOtherInfo.
Referenced by SeRaceRoom::GetAllSeatPlayer, SeRaceRoom::GetOneMatchPlayer, SeRaceRoomMgr::IsPlayerValidateEnd.
void SeMatchPlayer::SetValidate(bool bValidate)
Referenced by SeRaceRoomMgr::OnReconValidOK, SeRaceRoomMgr::OnViewValidOKRet, RaceServer::ProcessCR_RaceValidate.
DWord SeMatchPlayer::GetID()
Referenced by SeMatchReconMgr::AddPlayer, SeRaceRoomMgr::BeginRaceView, SeRaceRoomMgr::CancelHero, SeRaceRoomMgr::ClrSelectedHeroID, SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::GetReloadRoomInfo, SeMatchReconMgr::InitAllow, SeRaceRoomMgr::JoinRoomRecon, SeRaceRoomMgr::LeaveRaceView, RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, SeRaceMgr::OnPlayerBuyRaceItem, SeRaceRoomMgr::OnPlayerCancelHero, SeRaceMgr::OnPlayerGuanqiaEnd, SeRaceMgr::OnPlayerRaceCmd, SeRaceMgr::OnPlayerRaceEnd, SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnPlayerRaceLoadEnd, SeRaceMgr::OnPlayerRaceReplayReport, SeRaceMgr::OnPlayerRaceViewBegin, SeRaceMgr::OnPlayerReconBegin, SeRaceMgr::OnPlayerReportSyn, SeRaceRoomMgr::OnPlayerTalk, SeRaceRoomMgr::OnProcessRepeatPlayer, SeRaceRoomMgr::OnRaceLeave, SeRaceMgr::OnRaceModeEnd, SeRaceRoomMgr::OnReconValidOK, RaceServer::ProcessCR_RaceEndGuanqia, RaceServer::ProcessCR_RaceEndRace, RaceServer::ProcessCR_RaceLoadEnd, RaceServer::ProcessCR_RaceReportSyn, RaceServer::ProcessCR_RaceValidate, RaceServer::ProcessCR_SelHeroCancelHero, RaceServer::ProcessCR_SelHeroChoiceHero, RaceServer::ProcessCR_SelHeroPrapared, RaceServer::ProcessCR_SetAvatarReq, RaceServer::ProcessCR_SetEquipSetReq, SeRaceRoomMgr::SelHero, SeRaceRoomMgr::SelHeroFight, SeRaceRoomMgr::SelHeroReady, SeRaceRoomMgr::SendRacePlayerBaseInfo.
void SeMatchPlayer::SetSessionID(DWord dwSessionID)
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::OnReconValidOK, SeRaceRoomMgr::OnViewValidOKRet.
DWord SeMatchPlayer::GetRoomSessionID()
Referenced by SeMatchReconMgr::AddPlayer, SeRaceMgr::OnGetHeroInfo, RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, SeRaceMgr::OnPlayerBuyRaceItem, SeRaceRoomMgr::OnPlayerCancelHero, SeRaceRoomMgr::OnPlayerChoiceHero, SeRaceMgr::OnPlayerGuanqiaEnd, SeRaceMgr::OnPlayerRaceCmd, SeRaceMgr::OnPlayerRaceEnd, SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnPlayerRaceLoadEnd, SeRaceMgr::OnPlayerRaceReplayReport, SeRaceMgr::OnPlayerReportSyn, SeRaceRoomMgr::OnPlayerSelectHeroReady, SeRaceRoomMgr::OnPlayerTalk, SeRaceMgr::OnPlayerView2Recon, SeRaceRoomMgr::OnProcessRepeatPlayer, SeRaceRoomMgr::OnRaceLeave, RaceServer::ProcessBLR_SelectHeroAck, RaceServer::ProcessCR_RaceLoadEnd, RaceServer::ProcessCR_RaceReportSyn, RaceServer::ProcessCR_SelHeroCancelHero, RaceServer::ProcessCR_SelHeroChoiceHero, RaceServer::ProcessCR_SelHeroPrapared, RaceServer::ProcessCR_SetAvatarReq, RaceServer::ProcessCR_SetEquipSetReq, RaceServer::ProcessCR_Talk, SeRaceRoomMgr::RecycleRoomPlayer, SeRaceRoomMgr::SelHeroReady.
void SeMatchPlayer::SetPlayerSeat(int iSeat)
int SeMatchPlayer::GetPlayerSeat()
Referenced by SeMatchReconMgr::AddPlayer, SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::GetReloadRoomInfo, SeMatchReconMgr::InitAllow, SeRaceMgr::OnGetHeroInfo, SeRaceMgr::OnPlayerBuyRaceItem, SeRaceRoomMgr::OnPlayerCancelHero, SeRaceMgr::OnPlayerGuanqiaEnd, SeRaceMgr::OnPlayerRaceCmd, SeRaceMgr::OnPlayerRaceEnd, SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnPlayerRaceReplayReport, SeRaceMgr::OnPlayerReconBegin, SeRaceMgr::OnPlayerReportSyn, SeRaceRoomMgr::OnRaceLeave, SeRaceRoomMgr::SelHero, SeRaceRoomMgr::SelHeroFight, SeRaceRoomMgr::SelHeroReady, SeRaceRoomMgr::SendRacePlayerBaseInfo.
int SeMatchPlayer::GetTownRoomIndex()
Referenced by SeRaceRoomMgr::GetReloadRoomInfo.
void SeMatchPlayer::SetRoomPlayerCamp(SeRoomPlayerCamp eCamp)
SeRoomPlayerCamp SeMatchPlayer::GetRoomPlayerCamp(void) const
Referenced by SeMatchReconMgr::AddPlayer, SeRaceRoomMgr::CancelHero, SeRaceRoomMgr::GetReloadRoomInfo, SeRaceRoomMgr::IntoSelHero, SeRaceRoomMgr::IsValidHeroID, RaceServer::ProcessCR_RaceValidate, SeRaceRoomMgr::SelHero, SeRaceRoomMgr::SelHeroFight, SeRaceRoomMgr::SelHeroReady, SeRaceRoomMgr::SendRacePlayerBaseInfo.
void SeMatchPlayer::SetName(const char *pcName)
const char* SeMatchPlayer::GetName(void) const
Referenced by SeMatchReconMgr::AddPlayer, SeRaceMgr::OnPlayerRaceLeave, SeRaceMgr::OnPlayerReconBegin, SeRaceRoomMgr::OnRaceLeave, SeRaceMgr::OnRaceModeEnd, RaceServer::ProcessCR_RaceEndGuanqia, RaceServer::ProcessCR_RaceEndRace, SeRaceRoomMgr::SendRacePlayerBaseInfo.
int SeMatchPlayer::GetGold(void) const
Referenced by SeRaceMgr::OnRaceModeEnd.
int SeMatchPlayer::GetDiamond(void) const
Referenced by SeRaceMgr::OnRaceModeEnd.
int SeMatchPlayer::GetExp(void) const
Referenced by SeRaceMgr::OnRaceModeEnd.
int SeMatchPlayer::GetRaceArenaTime(void) const
Referenced by SeRaceMgr::OnRaceModeEnd.
int SeMatchPlayer::GetRaceCumuGolds()
Referenced by SeRaceMgr::OnRaceModeEnd.
int SeMatchPlayer::GetFightScoreFun()
int SeMatchPlayer::GetFailurePoint()
int SeMatchPlayer::GetMapFightScore()
int SeMatchPlayer::GetMapFailurePoint()
DWord SeMatchPlayer::GetAreaID()
Referenced by SeMatchReconMgr::AddPlayer, SeRaceRoomMgr::BeginRaceView, SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::GetReloadRoomInfo, RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, SeRaceMgr::OnRaceModeEnd, RaceServer::ProcessCR_RaceValidate, SeRaceRoomMgr::SendRacePlayerBaseInfo.
DWord SeMatchPlayer::GetServerID()
Referenced by SeMatchReconMgr::AddPlayer, SeRaceRoomMgr::BeginRaceView, SeRaceRoomMgr::GetReloadRoomInfo, RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, RaceServer::ProcessCR_RaceValidate.
void SeMatchPlayer::SetRaceID(const TeMD5 &kRaceID)
Referenced by SeRaceRoomMgr::LeaveRaceView, SeRaceMgr::OnPlayerRaceViewBegin.
const TeMD5& SeMatchPlayer::GetRaceID(void) const
Referenced by SeRaceMgr::OnPlayerView2Recon, SeRaceMgr::OnPlayerViewQuit.
bool SeMatchPlayer::IsSendReturnWait()
Referenced by SeRaceRoomMgr::OnRaceLeave.
void SeMatchPlayer::SetReturnWait(bool bSend)
Referenced by SeRaceRoomMgr::OnRaceLeave.
bool SeMatchPlayer::IsRaceEndReport()
Referenced by SeRaceMgr::OnPlayerRaceLeave, SeRaceRoomMgr::OnRaceLeave.
void SeMatchPlayer::SetRaceEndReport(bool bReport)
Referenced by SeRaceMgr::OnPlayerGuanqiaEnd, SeRaceMgr::OnPlayerRaceEnd.
VecSelHeroInfo& SeMatchPlayer::GetAllHeroInfo()
Referenced by SeRaceRoomMgr::IntoSelHero.
SeMatchFightInfo& SeMatchPlayer::GetMatchFightInfo()
Referenced by SeRaceMgr::OnRaceModeEnd.
int SeMatchPlayer::GetTeamMemberNum()
Referenced by SeRaceMgr::OnRaceModeEnd.
DWord SeMatchPlayer::GetTeamID()
Referenced by SeRaceMgr::OnRaceModeEnd.
SeScoreInfo& SeMatchPlayer::GetScoreInfo()
Referenced by SeRaceMgr::OnRaceModeEnd.
void SeMatchPlayer::AddPlayerInfo(SePtlMatchRaceInfo &rakRaceInfo)
References SeMatchOtherInfo::akEquipItems, SePtlMatchRaceInfo::akPlayerInfo, SePtlMatchRaceInfo::dwAreaID, SePtlMatchRaceInfo::dwPlayerID, SePtlMatchRaceInfo::dwServerID, SePtlMatchRaceInfo::dwTeamID, SePtlMatchRaceInfo::eCamp, SePtlMatchRaceInfo::iSeatIndex, SePtlMatchRaceInfo::iTeamMemberNum, SePtlMatchRaceInfo::iTownRoomIndex, SePtlMatchPlayer::kBaseInfo, SePtlMatchRaceInfo::kFightInfo, SePtlMatchPlayer::kOtherInfo, SePtlMatchPlayer::kScoreInfo, m_dwAreaID, m_dwPlayerID, m_dwServerID, m_dwTeamID, m_eCamp, m_iSeatIndex, m_iTeamMemberNum, m_iTownRoomIndex, m_kBaseInfo, m_kFightInfo, m_kOtherInfo, m_kScoreInfo, SSD_QUICK_EQUIP_MAX_NUM.
Referenced by SeRaceRoomMgr::CreateRoom.
void SeMatchPlayer::SetPlayerState(SeMatchPlayerState eState)
References m_eState.
Referenced by SeRaceRoomMgr::IntoSelHero, SeRaceMgr::OnPlayerRaceLoadEnd, SeRaceRoomMgr::OnRaceEnd, SeRaceRoomMgr::OnRaceLeave, SeRaceRoomMgr::OnReconValidOK, SeRaceRoomMgr::OnViewValidOKRet, RaceServer::ProcessCR_RaceValidate, SeRaceRoomMgr::StartLoad.
void SeMatchPlayer::ReconResetPlayerInfo(SeReconInitInfo &rkReconInitInfo)
References SeMatchBaseInfo::acName, SeReconInitInfo::acName, SeReconInitInfo::dwAreaID, SeReconInitInfo::dwPlayerID, SeReconInitInfo::dwServerID, SeReconInitInfo::eCamp, SeReconInitInfo::iSeat, m_dwAreaID, m_dwPlayerID, m_dwServerID, m_eCamp, m_iSeatIndex, m_kBaseInfo.
Referenced by SeRaceRoomMgr::OnReconValidOK.
void SeMatchPlayer::ViewSetPlayerInfo(SeViewInitInfo &rkViewInitInfo)
References SeViewInitInfo::dwAreaID, SeViewInitInfo::dwPlayerID, SeViewInitInfo::dwServerID, m_dwAreaID, m_dwPlayerID, m_dwServerID.
Referenced by SeRaceRoomMgr::OnViewValidOKRet.
SeMatchPlayerState SeMatchPlayer::GetPlayerState()
References m_eState.
Referenced by SeRaceRoomMgr::IsAllRoomPlayerLeave, RaceServer::OnNetDisconnect, RaceServer::OnNetUdpDisconnect, SeRaceRoomMgr::OnPlayerCancelHero, SeRaceRoomMgr::OnPlayerChoiceHero, SeRaceRoomMgr::OnPlayerSelectHeroReady, SeRaceRoomMgr::OnRaceEnd, SeRaceRoomMgr::OnRaceLeave, RaceServer::ProcessBLR_SelectHeroAck, RaceServer::ProcessCR_RaceEndGuanqia, RaceServer::ProcessCR_RaceEndRace, RaceServer::ProcessCR_SelHeroChoiceHero, RaceServer::ProcessCR_SetAvatarReq, RaceServer::ProcessCR_SetEquipSetReq, RaceServer::ProcessCR_Talk, RaceServer::ProcessMR_RaceBuyRet, SeRaceRoomMgr::UpdateRaceEndTime.
bool SeMatchPlayer::HasHero(DWord dwHeroID)
References SeMatchOtherInfo::akHeroList, SeSelHeroInfo::dwHeroTypeID, m_kOtherInfo.
Referenced by SeRaceRoomMgr::IsValidHeroID, RaceServer::ProcessCR_SelHeroChoiceHero, SeRaceRoomMgr::SelHero.
DWord SeMatchPlayer::RandGetHeroItem(DWord dwHeroID, int iItemClass)
const VAchievementCountsDat& SeMatchPlayer::GetAchievementCounts() const
Referenced by SeRaceMgr::OnRaceModeEnd.
const VAchievementID& SeMatchPlayer::GetAchievementCountsIDs() const
References SeMatchOtherInfo::akAllGetedAcievement, m_kOtherInfo.
Referenced by SeRaceMgr::OnRaceModeEnd.
const VPtlEquipItem & SeMatchPlayer::GetEquipItem() const
References SeMatchOtherInfo::akEquipItems, SeMatchOtherInfo::byEquipSetIndex, m_kOtherInfo.
Referenced by SeRaceMgr::OnRaceModeEnd.
DWord SeMatchPlayer::GetRespawnItemCount() const
References SeMatchOtherInfo::dwRespawnItemCount, m_kOtherInfo.
Referenced by SeRaceMgr::OnRaceModeEnd.
DWord SeMatchPlayer::GetSelHeroID() const
References m_dwSelHeroID.
Referenced by RaceServer::ProcessCR_SetAvatarReq, SeRaceRoomMgr::SelHeroFight, SeRaceRoomMgr::SelHeroReady, setAvatar.
void SeMatchPlayer::SetSelHeroID(DWord dwHeroID)
References SeMatchOtherInfo::akHeroList, SeSelHeroInfo::dwActiveSkin, SeSelHeroInfo::dwActiveWeapon, SeSelHeroInfo::dwActiveWing, SeSelHeroInfo::dwHeroTypeID, SeHeroAvatar::dwSkin, SeHeroAvatar::dwWeapon, SeHeroAvatar::dwWing, getAvatarTypeID, m_dwSelHeroID, m_kHeroAvatar, m_kOtherInfo, SeHeroAvatar::reset.
Referenced by SeRaceRoomMgr::SelHeroFight.
void SeMatchPlayer::setEquipSetIndex(Byte index)
References SeMatchOtherInfo::akEquipItems, SeMatchOtherInfo::byEquipSetIndex, m_kOtherInfo.
Referenced by RaceServer::ProcessCR_SetEquipSetReq.
const SeHeroAvatar & SeMatchPlayer::GetSelHeroAvatar()
References m_kHeroAvatar.
Referenced by SeRaceMgr::OnRaceModeEnd.
void SeMatchPlayer::setRandomAvatar()
References SeMatchOtherInfo::akRandomAvatars, g_kRaceServer, AvatarTableMgr::Get, getAvatarPointer, AvatarTableMgr::GetAvatarTable, m_kHeroAvatar, m_kOtherInfo, RaceServer::RandInt, RANDOM_AVATAR_BEGIN, RANDOM_AVATAR_END, AvatarTable::uiAvatarType.
Referenced by SeRaceRoomMgr::SelHeroReady.
int SeMatchPlayer::setAvatar(DWord dwItemID)
References SeMatchOtherInfo::akSelectableAvatars, AvatarTableMgr::Get, getAvatarPointer, AvatarTableMgr::GetAvatarTable, GetSelHeroID, m_kHeroAvatar, m_kOtherInfo, AvatarTable::uiAvatarType, AvatarTable::uiHeroID.
Referenced by RaceServer::ProcessCR_SetAvatarReq.
void SeMatchPlayer::pushHero(const SeSelHeroInfo &info)
References SeMatchOtherInfo::akHeroList, m_kOtherInfo.
Referenced by RaceServer::ProcessBLR_SelectHeroAck.
SeMatchPlayer::SeMatchPlayer(void)
SeMatchPlayer::~SeMatchPlayer(void)
void SeMatchPlayer::SetHSock(HSock kSock)
HSock SeMatchPlayer::GetHSock(void) const
bool SeMatchPlayer::IsValidSock(void)
bool SeMatchPlayer::IsValidate()
References SeMatchOtherInfo::akAcievementCounts, m_kOtherInfo.
void SeMatchPlayer::SetValidate(bool bValidate)
DWord SeMatchPlayer::GetID()
void SeMatchPlayer::SetSessionID(DWord dwSessionID)
DWord SeMatchPlayer::GetRoomSessionID()
void SeMatchPlayer::SetPlayerSeat(int iSeat)
int SeMatchPlayer::GetPlayerSeat()
int SeMatchPlayer::GetTownRoomIndex()
void SeMatchPlayer::SetRoomPlayerCamp(SeRoomPlayerCamp eCamp)
SeRoomPlayerCamp SeMatchPlayer::GetRoomPlayerCamp(void) const
void SeMatchPlayer::SetName(const char *pcName)
const char* SeMatchPlayer::GetName(void) const
int SeMatchPlayer::GetGold(void) const
int SeMatchPlayer::GetDiamond(void) const
int SeMatchPlayer::GetExp(void) const
int SeMatchPlayer::GetRaceArenaTime(void) const
int SeMatchPlayer::GetRaceCumuGolds()
int SeMatchPlayer::GetFightScoreFun()
int SeMatchPlayer::GetFailurePoint()
int SeMatchPlayer::GetMapFightScore()
int SeMatchPlayer::GetMapFailurePoint()
DWord SeMatchPlayer::GetAreaID()
DWord SeMatchPlayer::GetServerID()
void SeMatchPlayer::SetRaceID(const TeMD5 &kRaceID)
const TeMD5& SeMatchPlayer::GetRaceID(void) const
bool SeMatchPlayer::IsSendReturnWait()
void SeMatchPlayer::SetReturnWait(bool bSend)
bool SeMatchPlayer::IsRaceEndReport()
void SeMatchPlayer::SetRaceEndReport(bool bReport)
VecSelHeroInfo& SeMatchPlayer::GetAllHeroInfo()
SeMatchFightInfo& SeMatchPlayer::GetMatchFightInfo()
int SeMatchPlayer::GetTeamMemberNum()
DWord SeMatchPlayer::GetTeamID()
SeScoreInfo& SeMatchPlayer::GetScoreInfo()
void SeMatchPlayer::AddPlayerInfo(SePtlMatchRaceInfo &rakRaceInfo)
void SeMatchPlayer::SetPlayerState(SeMatchPlayerState eState)
void SeMatchPlayer::ReconResetPlayerInfo(SeReconInitInfo &rkReconInitInfo)
void SeMatchPlayer::ViewSetPlayerInfo(SeViewInitInfo &rkViewInitInfo)
SeMatchPlayerState SeMatchPlayer::GetPlayerState()
bool SeMatchPlayer::HasHero(DWord dwHeroID)
DWord SeMatchPlayer::RandGetHeroItem(DWord dwHeroID, int iItemClass)
const VAchievementCountsDat& SeMatchPlayer::GetAchievementCounts() const
const VAchievementID& SeMatchPlayer::GetAchievementCountsIDs() const
References SeMatchOtherInfo::akAllGetedAcievement, m_kOtherInfo.
const VPtlEquipItem& SeMatchPlayer::GetEquipItem() const
DWord SeMatchPlayer::GetRespawnItemCount() const
References SeMatchOtherInfo::dwRespawnItemCount, m_kOtherInfo.
DWord SeMatchPlayer::GetSelHeroID() const
References m_dwSelHeroID.
void SeMatchPlayer::SetSelHeroID(DWord dwHeroID)
void SeMatchPlayer::setEquipSetIndex(Byte index)
const SeHeroAvatar& SeMatchPlayer::GetSelHeroAvatar()
void SeMatchPlayer::setRandomAvatar()
int SeMatchPlayer::setAvatar(DWord dwItemID)
void SeMatchPlayer::pushHero(const SeSelHeroInfo &info)