SeNetStream
char SeNetStream::m_acData[65535][65535]
Referenced by GetAcData, InitData.
char* SeNetStream::m_pcData
Referenced by Attach, GetData, Read, ReadNetStream, SeNetStream, Write, WriteNetStream.
int SeNetStream::m_iSize
Referenced by Attach, GetSize, IsEnd, Read, SeNetStream, SetCurPos, Write.
int SeNetStream::m_iPos
Referenced by Attach, GetCurPos, IsEnd, Read, SeNetStream, SetCurPos, Write, WriteNetStream.
SeNetStream::SeNetStream(void)
References m_iPos, m_iSize, m_pcData.
SeNetStream::~SeNetStream(void)
bool SeNetStream::Attach(void *pkData, int iSize)
References m_iPos, m_iSize, m_pcData.
Referenced by SeRaceMgr::CreateRobotRace, DecodeMatchValueStru, DecodePlayerGrades, DecodePlayerGradeStru, DecodeSeAchieveFinish, DecodeSeAchievementCounts, DecodeSeAchievementPtlDat, DecodeSeAchieveSchedule, DecodeSeAttrUnit, DecodeSeAwardItem, DecodeSeCiTiao, DecodeSeCL_PlayerLogin, DecodeSeCL_PlayerLogin_NEW, DecodeSeCL_PlayerSteamLogin, DecodeSeCR_BuyRaceItem, DecodeSeCR_GetHeroInfo, DecodeSeCR_HeartPackage, DecodeSeCR_Ping, DecodeSeCR_RaceCmd, DecodeSeCR_RaceEndGuanqia, DecodeSeCR_RaceEndRace, DecodeSeCR_RaceLeave, DecodeSeCR_RaceLoadEnd, DecodeSeCR_RaceReportSyn, DecodeSeCR_RaceRobotLogin, DecodeSeCR_RaceValidate, DecodeSeCR_ReplayReport, DecodeSeCR_SelHeroCancelHero, DecodeSeCR_SelHeroChoiceHero, DecodeSeCR_SelHeroPrapared, DecodeSeCR_SetAvatarReq, DecodeSeCR_SetEquipSetReq, DecodeSeCR_Talk, DecodeSeCT_AchieveInfoReq, DecodeSeCT_BuyShopItem, DecodeSeCT_ClearItemNewFlag, DecodeSeCT_CloseIncompleteRaceList, DecodeSeCT_CreateChar, DecodeSeCT_CreateRoom, DecodeSeCT_DelayCheck, DecodeSeCT_DelelteItem, DecodeSeCT_DelReconInfo, DecodeSeCT_FriendLadderInfoReq, DecodeSeCT_GetItemGM, DecodeSeCT_GetRaceHistory, DecodeSeCT_GetTaskReward, DecodeSeCT_GMAddItem, DecodeSeCT_GMSetDiamond, DecodeSeCT_GMSetGold, DecodeSeCT_HeartBeat, DecodeSeCT_ItemExchange, DecodeSeCT_LadderDetailInfoReq, DecodeSeCT_LadderRankQueryReq, DecodeSeCT_LeaderDismissTeamReq, DecodeSeCT_LeaderKickMemberReq, DecodeSeCT_LeaveTown, DecodeSeCT_MailOpr, DecodeSeCT_MapTaskOpr, DecodeSeCT_MatchConfirm, DecodeSeCT_NexusFriendCleanRefuseNoticeReq, DecodeSeCT_NexusFriendDetailInfoReq, DecodeSeCT_NexusUserActionReq, DecodeSeCT_NexusUserPromotionDetailInfoReq, DecodeSeCT_NexusUserPromotionReq, DecodeSeCT_OpenRandBox, DecodeSeCT_PlayerGoDirect, DecodeSeCT_PlayerMatchCancel, DecodeSeCT_PlayerMatchReq, DecodeSeCT_PlayerRename, DecodeSeCT_PlayerValidate, DecodeSeCT_PutOnEquip, DecodeSeCT_QueryName, DecodeSeCT_QueryNearestRaceInfo, DecodeSeCT_QueryRaceBetInfo, DecodeSeCT_QueryRaceRoomList, DecodeSeCT_QueryRoomList, DecodeSeCT_RaceDetailInfoReq, DecodeSeCT_RaceEndGuanka, DecodeSeCT_ReconQuery, DecodeSeCT_ReqAchievement, DecodeSeCT_ReqAchievementCounts, DecodeSeCT_ReqIncompleteRaceKDA, DecodeSeCT_ReqIncompleteRaceList, DecodeSeCT_ReqItemCiTiaoChange, DecodeSeCT_ReqItemDepart, DecodeSeCT_ReqItemStrenth, DecodeSeCT_ReqView, DecodeSeCT_ReqViewList, DecodeSeCT_RoomInvite, DecodeSeCT_RoomInviteRsp, DecodeSeCT_RoomJoin, DecodeSeCT_RoomKickSomeone, DecodeSeCT_RoomLeave, DecodeSeCT_RoomStart, DecodeSeCT_RoomSwitchSeat, DecodeSeCT_SearchUserArchivesDetailInfoReq, DecodeSeCT_SearchUserArchivesInfoReq, DecodeSeCT_SetActiveAvatarReq, DecodeSeCT_SeUserRaceArenaDetailInfoReq, DecodeSeCT_ShopItemGM, DecodeSeCT_TakeOffEquip, DecodeSeCT_TaskQueryList, DecodeSeCT_TaskResel, DecodeSeCT_UserAlterAvatarFrameReq, DecodeSeCT_UserAlterAvatarReq, DecodeSeCT_UserAlterNickNameReq, DecodeSeCT_UserConfirmInviteReq, DecodeSeCT_UserInviteReq, DecodeSeCT_UserLeaveTeamReq, DecodeSeCT_UserMapRaceHeroReq, DecodeSeCT_UserPurchaseAvatarReq, DecodeSeCT_UserRefuseInviteReq, DecodeSeCT_UserStatusQueryReq, DecodeSeCT_ViewBegin, DecodeSeCWCS_ViewValidate, DecodeSeEquipSchemaInfo, DecodeSeExternAttrUnit, DecodeSeGuanqiaSendInfo, DecodeSeIncompleteRaceBaseInfo, DecodeSeItemNoti, DecodeSeLadderDetailInfo, DecodeSeLadderInfo, DecodeSeLadderRankInfo, DecodeSeLC_ClientVersion, DecodeSeLC_EncryptKey, DecodeSeLC_GateList, DecodeSeLC_PlayerLoginRet, DecodeSeLC_SteamCheckReturn, DecodeSeMailAttach, DecodeSeMailUpdate, DecodeSeMatchFightInfo, DecodeSeMatchRoomListInfo, DecodeSeMatchSelPlayerInfo, DecodeSeMatchStartInfo, DecodeSeMobileInfo, DecodeSeNexusFriendSyncInfo, DecodeSeNexusKeyInfo, DecodeSeNexusPlayerInfo, DecodeSeNexusTeamBaseInfo, DecodeSeNexusTeamMemberInfo, DecodeSeNexusUserBaseInfo, DecodeSeNexusUserInfo, DecodeSeNexusUserPromotionInfo, DecodeSeNoticeMatchPlayerInfo, DecodeSeOpenRoomInfo, DecodeSePlayerAchievementCounts, DecodeSePlayerAppear, DecodeSePlayerDisappear, DecodeSePlayerInfoSeat, DecodeSePtlExchange, DecodeSePtlFriend, DecodeSePtlFriendRequest, DecodeSePtlMail, DecodeSePtlMapTask, DecodeSePtlNetAddr, DecodeSePtlRaceBetInfo, DecodeSePtlRaceHistory, DecodeSePtlStaMap, DecodeSePtlTask, DecodeSeQueryPlayerRaceInfo, DecodeSeRaceBaseBuildingInfo, DecodeSeRaceCampBuildingInfo, DecodeSeRaceDetailInfo, DecodeSeRaceEndArenaBaseInfo, DecodeSeRaceEndArenaDetailInfo, DecodeSeRaceEndArenaResult, DecodeSeRaceGameInfo, DecodeSeRaceInfo, DecodeSeRaceMapBuildingInfo, DecodeSeRaceMapInfo, DecodeSeRaceMapPosInfo, DecodeSeRaceSendInfo, DecodeSeRaceTask, DecodeSeRaceUserHeroInfo, DecodeSeRaceUserInfo, DecodeSeRaceWaitPlayer, DecodeSeRandBoxItem, DecodeSeRC_BeginSelectHero, DecodeSeRC_EncryptKey, DecodeSeRC_GetHeroInfoRet, DecodeSeRC_HeartBeat, DecodeSeRC_PingRet, DecodeSeRC_RaceEndNotifyDown, DecodeSeRC_RaceGoldExpPlus, DecodeSeRC_RacePack, DecodeSeRC_RacePlayerLoadEnd, DecodeSeRC_RaceStream, DecodeSeRC_ReconPack, DecodeSeRC_ReconResult, DecodeSeRC_RoomPlayerBaseInfo, DecodeSeRC_SeatScoreNtf, DecodeSeRC_SelHeroList, DecodeSeRC_SelHeroMessage, DecodeSeRC_SelHorseList, DecodeSeRC_SelPetList, DecodeSeRC_SetAvatarAck, DecodeSeRC_SetEquipSetAck, DecodeSeRC_ShowNotice, DecodeSeRC_Talk, DecodeSeRC_ValidateRet, DecodeSeRC_ViewPack, DecodeSeRC_ViewPlayerInfo, DecodeSeRC_ViewResult, DecodeSeRoomMember, DecodeSeScoreInfo, DecodeSeSeatBaseInfo, DecodeSeSeatScore, DecodeSeSelHeroInfo, DecodeSeTC_AchieveInfoAck, DecodeSeTC_ActiveAvatarNtf, DecodeSeTC_AddIncompleteRace, DecodeSeTC_AskEnterWaitRace, DecodeSeTC_BiVoiceEnterInfo, DecodeSeTC_CancelMatchRep, DecodeSeTC_CardUpdate, DecodeSeTC_CreateCharRet, DecodeSeTC_CreateRoomRet, DecodeSeTC_DelayCheckRet, DecodeSeTC_EncryptKey, DecodeSeTC_EquipSchema, DecodeSeTC_ExchangeInit, DecodeSeTC_FriendAdd, DecodeSeTC_FriendDel, DecodeSeTC_FriendInit, DecodeSeTC_FriendLadderInfoNtf, DecodeSeTC_FriendRemarkRet, DecodeSeTC_FriendRequestAdd, DecodeSeTC_FriendRequestInit, DecodeSeTC_FriendUpdateStatus, DecodeSeTC_GetAchievement, DecodeSeTC_GetRaceHistoryRet, DecodeSeTC_HeartBeat, DecodeSeTC_InGameDisconn, DecodeSeTC_InitPlayerInfo, DecodeSeTC_ItemDel, DecodeSeTC_ItemExchangeRet, DecodeSeTC_KickPlayer, DecodeSeTC_LadderDetailInfoAck, DecodeSeTC_LadderRankQueryAck, DecodeSeTC_MailOprRet, DecodeSeTC_MatchRaceAddr, DecodeSeTC_NexusFriendCleanRefuseNoticeRes, DecodeSeTC_NexusFriendDetailInfoRes, DecodeSeTC_NexusFriendLimitRes, DecodeSeTC_NexusFriendStatusSync, DecodeSeTC_NexusUserActionSync, DecodeSeTC_NexusUserPromotionDetailInfoRes, DecodeSeTC_NotiMatcherPre, DecodeSeTC_NotiMatcherResult, DecodeSeTC_OpenRandBoxRet, DecodeSeTC_PlayerAppear, DecodeSeTC_PlayerDisappear, DecodeSeTC_PlayerGoPos, DecodeSeTC_PlayerLadder, DecodeSeTC_PlayerLeaveRet, DecodeSeTC_PlayerMoneyAndDiamond, DecodeSeTC_PlayerNewItem, DecodeSeTC_PlayerOperRep, DecodeSeTC_PlayerRename, DecodeSeTC_PlayerValidateRet, DecodeSeTC_PutOnEquipRet, DecodeSeTC_QueryMapTaskListRet, DecodeSeTC_QueryNameRet, DecodeSeTC_QueryNearestRaceInfoRet, DecodeSeTC_QueryRaceBetInfoRet, DecodeSeTC_QueryRaceRoomListRet, DecodeSeTC_QueryRoomListRet, DecodeSeTC_ReceiveMail, DecodeSeTC_RemoveIncompleteRace, DecodeSeTC_ReqMatchRep, DecodeSeTC_ResAchievementCounts, DecodeSeTC_ResAchievementDat, DecodeSeTC_ResIncmpRaceSeatBaseInfo, DecodeSeTC_ResIncompleteRaceList, DecodeSeTC_ResRaceDetailInfo, DecodeSeTC_ResView, DecodeSeTC_ResViewList, DecodeSeTC_RoomInviteNotify, DecodeSeTC_RoomJoinRet, DecodeSeTC_RoomKickSomeoneRet, DecodeSeTC_RoomLeaveRet, DecodeSeTC_RoomMemberNotify, DecodeSeTC_RoomStartRet, DecodeSeTC_RoomSwitchSeatRet, DecodeSeTC_SearchUserArchivesDetailInfoRes, DecodeSeTC_SearchUserArchivesInfoRes, DecodeSeTC_SetActiveAvatarAck, DecodeSeTC_SeUserRaceArenaDetailInfoRes, DecodeSeTC_ShopItemGmRep, DecodeSeTC_ShowNotice, DecodeSeTC_SingleMatchConfirm, DecodeSeTC_StartMatchRet, DecodeSeTC_TakeOffEquipRet, DecodeSeTC_TaskQueryListRet, DecodeSeTC_TaskReselRet, DecodeSeTC_TeamChangeSync, DecodeSeTC_TeamLeaderSync, DecodeSeTC_TeamMemberInfoRes, DecodeSeTC_TeamMemberSync, DecodeSeTC_TeamUserStateRes, DecodeSeTC_UpdateMail, DecodeSeTC_UpdateMisc, DecodeSeTC_UserAlterAvatarAndFrameNtf, DecodeSeTC_UserAlterNickNameAck, DecodeSeTC_UserHeroSync, DecodeSeTC_UserRaceMapHeroAck, DecodeSeTC_UserStatusQueryReqRes, DecodeSeTC_ViewResult, DecodeSeTeamMemberBaseInfo, DecodeSeUnlockHeroBaseInfo, DecodeSeUserArchivesInfo, DecodeSeUserArchivesNameInfo, DecodeSeUserBaseAttrInfo, DecodeSeUserHeroSyncInfo, DecodeSeUserRaceMapHeroBase, DecodeSeUserStatusBaseInfo, DecodeSeViewList, DecodeSeWCSC_EncryptKey, DecodeSeWCSC_ViewPack, DecodeSeWCSC_ViewPlayerInfo, DecodeSeWCSC_ViewValidateRet, DecodeSeWCSViewInfo, DecodeSeWSGuanqiaSendInfo, DecodeSeWSRaceSendInfo, DecodeShopItem, EncodeMatchValueStru, EncodePlayerGrades, EncodePlayerGradeStru, EncodeSeAchieveFinish, EncodeSeAchievementCounts, EncodeSeAchievementPtlDat, EncodeSeAchieveSchedule, EncodeSeAttrUnit, EncodeSeAwardItem, EncodeSeCiTiao, EncodeSeCL_PlayerLogin, EncodeSeCL_PlayerLogin_NEW, EncodeSeCL_PlayerSteamLogin, EncodeSeCR_BuyRaceItem, EncodeSeCR_GetHeroInfo, EncodeSeCR_HeartPackage, EncodeSeCR_Ping, EncodeSeCR_RaceCmd, EncodeSeCR_RaceEndGuanqia, EncodeSeCR_RaceEndRace, EncodeSeCR_RaceLeave, EncodeSeCR_RaceLoadEnd, EncodeSeCR_RaceReportSyn, EncodeSeCR_RaceRobotLogin, EncodeSeCR_RaceValidate, EncodeSeCR_ReplayReport, EncodeSeCR_SelHeroCancelHero, EncodeSeCR_SelHeroChoiceHero, EncodeSeCR_SelHeroPrapared, EncodeSeCR_SetAvatarReq, EncodeSeCR_SetEquipSetReq, EncodeSeCR_Talk, EncodeSeCT_AchieveInfoReq, EncodeSeCT_BuyShopItem, EncodeSeCT_ClearItemNewFlag, EncodeSeCT_CloseIncompleteRaceList, EncodeSeCT_CreateChar, EncodeSeCT_CreateRoom, EncodeSeCT_DelayCheck, EncodeSeCT_DelelteItem, EncodeSeCT_DelReconInfo, EncodeSeCT_FriendLadderInfoReq, EncodeSeCT_GetItemGM, EncodeSeCT_GetRaceHistory, EncodeSeCT_GetTaskReward, EncodeSeCT_GMAddItem, EncodeSeCT_GMSetDiamond, EncodeSeCT_GMSetGold, EncodeSeCT_HeartBeat, EncodeSeCT_ItemExchange, EncodeSeCT_LadderDetailInfoReq, EncodeSeCT_LadderRankQueryReq, EncodeSeCT_LeaderDismissTeamReq, EncodeSeCT_LeaderKickMemberReq, EncodeSeCT_LeaveTown, EncodeSeCT_MailOpr, EncodeSeCT_MapTaskOpr, EncodeSeCT_MatchConfirm, EncodeSeCT_NexusFriendCleanRefuseNoticeReq, EncodeSeCT_NexusFriendDetailInfoReq, EncodeSeCT_NexusUserActionReq, EncodeSeCT_NexusUserPromotionDetailInfoReq, EncodeSeCT_NexusUserPromotionReq, EncodeSeCT_OpenRandBox, EncodeSeCT_PlayerGoDirect, EncodeSeCT_PlayerMatchCancel, EncodeSeCT_PlayerMatchReq, EncodeSeCT_PlayerRename, EncodeSeCT_PlayerValidate, EncodeSeCT_PutOnEquip, EncodeSeCT_QueryName, EncodeSeCT_QueryNearestRaceInfo, EncodeSeCT_QueryRaceBetInfo, EncodeSeCT_QueryRaceRoomList, EncodeSeCT_QueryRoomList, EncodeSeCT_RaceDetailInfoReq, EncodeSeCT_RaceEndGuanka, EncodeSeCT_ReconQuery, EncodeSeCT_ReqAchievement, EncodeSeCT_ReqAchievementCounts, EncodeSeCT_ReqIncompleteRaceKDA, EncodeSeCT_ReqIncompleteRaceList, EncodeSeCT_ReqItemCiTiaoChange, EncodeSeCT_ReqItemDepart, EncodeSeCT_ReqItemStrenth, EncodeSeCT_ReqView, EncodeSeCT_ReqViewList, EncodeSeCT_RoomInvite, EncodeSeCT_RoomInviteRsp, EncodeSeCT_RoomJoin, EncodeSeCT_RoomKickSomeone, EncodeSeCT_RoomLeave, EncodeSeCT_RoomStart, EncodeSeCT_RoomSwitchSeat, EncodeSeCT_SearchUserArchivesDetailInfoReq, EncodeSeCT_SearchUserArchivesInfoReq, EncodeSeCT_SetActiveAvatarReq, EncodeSeCT_SeUserRaceArenaDetailInfoReq, EncodeSeCT_ShopItemGM, EncodeSeCT_TakeOffEquip, EncodeSeCT_TaskQueryList, EncodeSeCT_TaskResel, EncodeSeCT_UserAlterAvatarFrameReq, EncodeSeCT_UserAlterAvatarReq, EncodeSeCT_UserAlterNickNameReq, EncodeSeCT_UserConfirmInviteReq, EncodeSeCT_UserInviteReq, EncodeSeCT_UserLeaveTeamReq, EncodeSeCT_UserMapRaceHeroReq, EncodeSeCT_UserPurchaseAvatarReq, EncodeSeCT_UserRefuseInviteReq, EncodeSeCT_UserStatusQueryReq, EncodeSeCT_ViewBegin, EncodeSeCWCS_ViewValidate, EncodeSeEquipSchemaInfo, EncodeSeExternAttrUnit, EncodeSeGuanqiaSendInfo, EncodeSeIncompleteRaceBaseInfo, EncodeSeItemNoti, EncodeSeLadderDetailInfo, EncodeSeLadderInfo, EncodeSeLadderRankInfo, EncodeSeLC_ClientVersion, EncodeSeLC_EncryptKey, EncodeSeLC_GateList, EncodeSeLC_PlayerLoginRet, EncodeSeLC_SteamCheckReturn, EncodeSeMailAttach, EncodeSeMailUpdate, EncodeSeMatchFightInfo, EncodeSeMatchRoomListInfo, EncodeSeMatchSelPlayerInfo, EncodeSeMatchStartInfo, EncodeSeMobileInfo, EncodeSeNexusFriendSyncInfo, EncodeSeNexusKeyInfo, EncodeSeNexusPlayerInfo, EncodeSeNexusTeamBaseInfo, EncodeSeNexusTeamMemberInfo, EncodeSeNexusUserBaseInfo, EncodeSeNexusUserInfo, EncodeSeNexusUserPromotionInfo, EncodeSeNoticeMatchPlayerInfo, EncodeSeOpenRoomInfo, EncodeSePlayerAchievementCounts, EncodeSePlayerAppear, EncodeSePlayerDisappear, EncodeSePlayerInfoSeat, EncodeSePtlExchange, EncodeSePtlFriend, EncodeSePtlFriendRequest, EncodeSePtlMail, EncodeSePtlMapTask, EncodeSePtlNetAddr, EncodeSePtlRaceBetInfo, EncodeSePtlRaceHistory, EncodeSePtlStaMap, EncodeSePtlTask, EncodeSeQueryPlayerRaceInfo, EncodeSeRaceBaseBuildingInfo, EncodeSeRaceCampBuildingInfo, EncodeSeRaceDetailInfo, EncodeSeRaceEndArenaBaseInfo, EncodeSeRaceEndArenaDetailInfo, EncodeSeRaceEndArenaResult, EncodeSeRaceGameInfo, EncodeSeRaceInfo, EncodeSeRaceMapBuildingInfo, EncodeSeRaceMapInfo, EncodeSeRaceMapPosInfo, EncodeSeRaceSendInfo, EncodeSeRaceTask, EncodeSeRaceUserHeroInfo, EncodeSeRaceUserInfo, EncodeSeRaceWaitPlayer, EncodeSeRandBoxItem, EncodeSeRC_BeginSelectHero, EncodeSeRC_EncryptKey, EncodeSeRC_GetHeroInfoRet, EncodeSeRC_HeartBeat, EncodeSeRC_PingRet, EncodeSeRC_RaceEndNotifyDown, EncodeSeRC_RaceGoldExpPlus, EncodeSeRC_RacePack, EncodeSeRC_RacePlayerLoadEnd, EncodeSeRC_RaceStream, EncodeSeRC_ReconPack, EncodeSeRC_ReconResult, EncodeSeRC_RoomPlayerBaseInfo, EncodeSeRC_SeatScoreNtf, EncodeSeRC_SelHeroList, EncodeSeRC_SelHeroMessage, EncodeSeRC_SelHorseList, EncodeSeRC_SelPetList, EncodeSeRC_SetAvatarAck, EncodeSeRC_SetEquipSetAck, EncodeSeRC_ShowNotice, EncodeSeRC_Talk, EncodeSeRC_ValidateRet, EncodeSeRC_ViewPack, EncodeSeRC_ViewPlayerInfo, EncodeSeRC_ViewResult, EncodeSeRoomMember, EncodeSeScoreInfo, EncodeSeSeatBaseInfo, EncodeSeSeatScore, EncodeSeSelHeroInfo, EncodeSeTC_AchieveInfoAck, EncodeSeTC_ActiveAvatarNtf, EncodeSeTC_AddIncompleteRace, EncodeSeTC_AskEnterWaitRace, EncodeSeTC_BiVoiceEnterInfo, EncodeSeTC_CancelMatchRep, EncodeSeTC_CardUpdate, EncodeSeTC_CreateCharRet, EncodeSeTC_CreateRoomRet, EncodeSeTC_DelayCheckRet, EncodeSeTC_EncryptKey, EncodeSeTC_EquipSchema, EncodeSeTC_ExchangeInit, EncodeSeTC_FriendAdd, EncodeSeTC_FriendDel, EncodeSeTC_FriendInit, EncodeSeTC_FriendLadderInfoNtf, EncodeSeTC_FriendRemarkRet, EncodeSeTC_FriendRequestAdd, EncodeSeTC_FriendRequestInit, EncodeSeTC_FriendUpdateStatus, EncodeSeTC_GetAchievement, EncodeSeTC_GetRaceHistoryRet, EncodeSeTC_HeartBeat, EncodeSeTC_InGameDisconn, EncodeSeTC_InitPlayerInfo, EncodeSeTC_ItemDel, EncodeSeTC_ItemExchangeRet, EncodeSeTC_KickPlayer, EncodeSeTC_LadderDetailInfoAck, EncodeSeTC_LadderRankQueryAck, EncodeSeTC_MailOprRet, EncodeSeTC_MatchRaceAddr, EncodeSeTC_NexusFriendCleanRefuseNoticeRes, EncodeSeTC_NexusFriendDetailInfoRes, EncodeSeTC_NexusFriendLimitRes, EncodeSeTC_NexusFriendStatusSync, EncodeSeTC_NexusUserActionSync, EncodeSeTC_NexusUserPromotionDetailInfoRes, EncodeSeTC_NotiMatcherPre, EncodeSeTC_NotiMatcherResult, EncodeSeTC_OpenRandBoxRet, EncodeSeTC_PlayerAppear, EncodeSeTC_PlayerDisappear, EncodeSeTC_PlayerGoPos, EncodeSeTC_PlayerLadder, EncodeSeTC_PlayerLeaveRet, EncodeSeTC_PlayerMoneyAndDiamond, EncodeSeTC_PlayerNewItem, EncodeSeTC_PlayerOperRep, EncodeSeTC_PlayerRename, EncodeSeTC_PlayerValidateRet, EncodeSeTC_PutOnEquipRet, EncodeSeTC_QueryMapTaskListRet, EncodeSeTC_QueryNameRet, EncodeSeTC_QueryNearestRaceInfoRet, EncodeSeTC_QueryRaceBetInfoRet, EncodeSeTC_QueryRaceRoomListRet, EncodeSeTC_QueryRoomListRet, EncodeSeTC_ReceiveMail, EncodeSeTC_RemoveIncompleteRace, EncodeSeTC_ReqMatchRep, EncodeSeTC_ResAchievementCounts, EncodeSeTC_ResAchievementDat, EncodeSeTC_ResIncmpRaceSeatBaseInfo, EncodeSeTC_ResIncompleteRaceList, EncodeSeTC_ResRaceDetailInfo, EncodeSeTC_ResView, EncodeSeTC_ResViewList, EncodeSeTC_RoomInviteNotify, EncodeSeTC_RoomJoinRet, EncodeSeTC_RoomKickSomeoneRet, EncodeSeTC_RoomLeaveRet, EncodeSeTC_RoomMemberNotify, EncodeSeTC_RoomStartRet, EncodeSeTC_RoomSwitchSeatRet, EncodeSeTC_SearchUserArchivesDetailInfoRes, EncodeSeTC_SearchUserArchivesInfoRes, EncodeSeTC_SetActiveAvatarAck, EncodeSeTC_SeUserRaceArenaDetailInfoRes, EncodeSeTC_ShopItemGmRep, EncodeSeTC_ShowNotice, EncodeSeTC_SingleMatchConfirm, EncodeSeTC_StartMatchRet, EncodeSeTC_TakeOffEquipRet, EncodeSeTC_TaskQueryListRet, EncodeSeTC_TaskReselRet, EncodeSeTC_TeamChangeSync, EncodeSeTC_TeamLeaderSync, EncodeSeTC_TeamMemberInfoRes, EncodeSeTC_TeamMemberSync, EncodeSeTC_TeamUserStateRes, EncodeSeTC_UpdateMail, EncodeSeTC_UpdateMisc, EncodeSeTC_UserAlterAvatarAndFrameNtf, EncodeSeTC_UserAlterNickNameAck, EncodeSeTC_UserHeroSync, EncodeSeTC_UserRaceMapHeroAck, EncodeSeTC_UserStatusQueryReqRes, EncodeSeTC_ViewResult, EncodeSeTeamMemberBaseInfo, EncodeSeUnlockHeroBaseInfo, EncodeSeUserArchivesInfo, EncodeSeUserArchivesNameInfo, EncodeSeUserBaseAttrInfo, EncodeSeUserHeroSyncInfo, EncodeSeUserRaceMapHeroBase, EncodeSeUserStatusBaseInfo, EncodeSeViewList, EncodeSeWCSC_EncryptKey, EncodeSeWCSC_ViewPack, EncodeSeWCSC_ViewPlayerInfo, EncodeSeWCSC_ViewValidateRet, EncodeSeWCSViewInfo, EncodeSeWSGuanqiaSendInfo, EncodeSeWSRaceSendInfo, EncodeShopItem, InitData, SeRaceMgr::OnRaceModeEnd, MatchServer::OnSendRSValidatePlayerInfo, MatchServer::ProcessBLM_RaceMatchLoadDetailRet, RaceServer::ProcessMR_ValidatePlayerInfo, SeRaceRecord::ProcessRecordLabel, TownServer::ProcessTCPSvr_ReLoadReadyID.
void SeNetStream::InitData()
References Attach, m_acData.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail, TcpServer::ProcessParent_RegisterRet.
bool SeNetStream::IsEnd(int iSize)
References m_iPos, m_iSize.
Referenced by TownServer::ProcessTCPSvr_ReLoadReadyID.
char * SeNetStream::GetData()
References m_pcData.
Referenced by BlockServer::ProcessMBL_RaceMatchLoadDetail, TcpServer::ProcessParent_RegisterRet.
int SeNetStream::GetCurPos(void)
References m_iPos.
Referenced by SeRaceMgr::CreateRobotRace, DecodeMatchValueStru, DecodePlayerGrades, DecodePlayerGradeStru, DecodeSeAchieveFinish, DecodeSeAchievementCounts, DecodeSeAchievementPtlDat, DecodeSeAchieveSchedule, DecodeSeAttrUnit, DecodeSeAwardItem, DecodeSeCiTiao, DecodeSeCL_PlayerLogin, DecodeSeCL_PlayerLogin_NEW, DecodeSeCL_PlayerSteamLogin, DecodeSeCR_BuyRaceItem, DecodeSeCR_GetHeroInfo, DecodeSeCR_HeartPackage, DecodeSeCR_Ping, DecodeSeCR_RaceCmd, DecodeSeCR_RaceEndGuanqia, DecodeSeCR_RaceEndRace, DecodeSeCR_RaceLeave, DecodeSeCR_RaceLoadEnd, DecodeSeCR_RaceReportSyn, DecodeSeCR_RaceRobotLogin, DecodeSeCR_RaceValidate, DecodeSeCR_ReplayReport, DecodeSeCR_SelHeroCancelHero, DecodeSeCR_SelHeroChoiceHero, DecodeSeCR_SelHeroPrapared, DecodeSeCR_SetAvatarReq, DecodeSeCR_SetEquipSetReq, DecodeSeCR_Talk, DecodeSeCT_AchieveInfoReq, DecodeSeCT_BuyShopItem, DecodeSeCT_ClearItemNewFlag, DecodeSeCT_CloseIncompleteRaceList, DecodeSeCT_CreateChar, DecodeSeCT_CreateRoom, DecodeSeCT_DelayCheck, DecodeSeCT_DelelteItem, DecodeSeCT_DelReconInfo, DecodeSeCT_FriendLadderInfoReq, DecodeSeCT_GetItemGM, DecodeSeCT_GetRaceHistory, DecodeSeCT_GetTaskReward, DecodeSeCT_GMAddItem, DecodeSeCT_GMSetDiamond, DecodeSeCT_GMSetGold, DecodeSeCT_HeartBeat, DecodeSeCT_ItemExchange, DecodeSeCT_LadderDetailInfoReq, DecodeSeCT_LadderRankQueryReq, DecodeSeCT_LeaderDismissTeamReq, DecodeSeCT_LeaderKickMemberReq, DecodeSeCT_LeaveTown, DecodeSeCT_MailOpr, DecodeSeCT_MapTaskOpr, DecodeSeCT_MatchConfirm, DecodeSeCT_NexusFriendCleanRefuseNoticeReq, DecodeSeCT_NexusFriendDetailInfoReq, DecodeSeCT_NexusUserActionReq, DecodeSeCT_NexusUserPromotionDetailInfoReq, DecodeSeCT_NexusUserPromotionReq, DecodeSeCT_OpenRandBox, DecodeSeCT_PlayerGoDirect, DecodeSeCT_PlayerMatchCancel, DecodeSeCT_PlayerMatchReq, DecodeSeCT_PlayerRename, DecodeSeCT_PlayerValidate, DecodeSeCT_PutOnEquip, DecodeSeCT_QueryName, DecodeSeCT_QueryNearestRaceInfo, DecodeSeCT_QueryRaceBetInfo, DecodeSeCT_QueryRaceRoomList, DecodeSeCT_QueryRoomList, DecodeSeCT_RaceDetailInfoReq, DecodeSeCT_RaceEndGuanka, DecodeSeCT_ReconQuery, DecodeSeCT_ReqAchievement, DecodeSeCT_ReqAchievementCounts, DecodeSeCT_ReqIncompleteRaceKDA, DecodeSeCT_ReqIncompleteRaceList, DecodeSeCT_ReqItemCiTiaoChange, DecodeSeCT_ReqItemDepart, DecodeSeCT_ReqItemStrenth, DecodeSeCT_ReqView, DecodeSeCT_ReqViewList, DecodeSeCT_RoomInvite, DecodeSeCT_RoomInviteRsp, DecodeSeCT_RoomJoin, DecodeSeCT_RoomKickSomeone, DecodeSeCT_RoomLeave, DecodeSeCT_RoomStart, DecodeSeCT_RoomSwitchSeat, DecodeSeCT_SearchUserArchivesDetailInfoReq, DecodeSeCT_SearchUserArchivesInfoReq, DecodeSeCT_SetActiveAvatarReq, DecodeSeCT_SeUserRaceArenaDetailInfoReq, DecodeSeCT_ShopItemGM, DecodeSeCT_TakeOffEquip, DecodeSeCT_TaskQueryList, DecodeSeCT_TaskResel, DecodeSeCT_UserAlterAvatarFrameReq, DecodeSeCT_UserAlterAvatarReq, DecodeSeCT_UserAlterNickNameReq, DecodeSeCT_UserConfirmInviteReq, DecodeSeCT_UserInviteReq, DecodeSeCT_UserLeaveTeamReq, DecodeSeCT_UserMapRaceHeroReq, DecodeSeCT_UserPurchaseAvatarReq, DecodeSeCT_UserRefuseInviteReq, DecodeSeCT_UserStatusQueryReq, DecodeSeCT_ViewBegin, DecodeSeCWCS_ViewValidate, DecodeSeEquipSchemaInfo, DecodeSeExternAttrUnit, DecodeSeGuanqiaSendInfo, DecodeSeIncompleteRaceBaseInfo, DecodeSeItemNoti, DecodeSeLadderDetailInfo, DecodeSeLadderInfo, DecodeSeLadderRankInfo, DecodeSeLC_ClientVersion, DecodeSeLC_EncryptKey, DecodeSeLC_GateList, DecodeSeLC_PlayerLoginRet, DecodeSeLC_SteamCheckReturn, DecodeSeMailAttach, DecodeSeMailUpdate, DecodeSeMatchFightInfo, DecodeSeMatchRoomListInfo, DecodeSeMatchSelPlayerInfo, DecodeSeMatchStartInfo, DecodeSeMobileInfo, DecodeSeNexusFriendSyncInfo, DecodeSeNexusKeyInfo, DecodeSeNexusPlayerInfo, DecodeSeNexusTeamBaseInfo, DecodeSeNexusTeamMemberInfo, DecodeSeNexusUserBaseInfo, DecodeSeNexusUserInfo, DecodeSeNexusUserPromotionInfo, DecodeSeNoticeMatchPlayerInfo, DecodeSeOpenRoomInfo, DecodeSePlayerAchievementCounts, DecodeSePlayerAppear, DecodeSePlayerDisappear, DecodeSePlayerInfoSeat, DecodeSePtlExchange, DecodeSePtlFriend, DecodeSePtlFriendRequest, DecodeSePtlMail, DecodeSePtlMapTask, DecodeSePtlNetAddr, DecodeSePtlRaceBetInfo, DecodeSePtlRaceHistory, DecodeSePtlStaMap, DecodeSePtlTask, DecodeSeQueryPlayerRaceInfo, DecodeSeRaceBaseBuildingInfo, DecodeSeRaceCampBuildingInfo, DecodeSeRaceDetailInfo, DecodeSeRaceEndArenaBaseInfo, DecodeSeRaceEndArenaDetailInfo, DecodeSeRaceEndArenaResult, DecodeSeRaceGameInfo, DecodeSeRaceInfo, DecodeSeRaceMapBuildingInfo, DecodeSeRaceMapInfo, DecodeSeRaceMapPosInfo, DecodeSeRaceSendInfo, DecodeSeRaceTask, DecodeSeRaceUserHeroInfo, DecodeSeRaceUserInfo, DecodeSeRaceWaitPlayer, DecodeSeRandBoxItem, DecodeSeRC_BeginSelectHero, DecodeSeRC_EncryptKey, DecodeSeRC_GetHeroInfoRet, DecodeSeRC_HeartBeat, DecodeSeRC_PingRet, DecodeSeRC_RaceEndNotifyDown, DecodeSeRC_RaceGoldExpPlus, DecodeSeRC_RacePack, DecodeSeRC_RacePlayerLoadEnd, DecodeSeRC_RaceStream, DecodeSeRC_ReconPack, DecodeSeRC_ReconResult, DecodeSeRC_RoomPlayerBaseInfo, DecodeSeRC_SeatScoreNtf, DecodeSeRC_SelHeroList, DecodeSeRC_SelHeroMessage, DecodeSeRC_SelHorseList, DecodeSeRC_SelPetList, DecodeSeRC_SetAvatarAck, DecodeSeRC_SetEquipSetAck, DecodeSeRC_ShowNotice, DecodeSeRC_Talk, DecodeSeRC_ValidateRet, DecodeSeRC_ViewPack, DecodeSeRC_ViewPlayerInfo, DecodeSeRC_ViewResult, DecodeSeRoomMember, DecodeSeScoreInfo, DecodeSeSeatBaseInfo, DecodeSeSeatScore, DecodeSeSelHeroInfo, DecodeSeTC_AchieveInfoAck, DecodeSeTC_ActiveAvatarNtf, DecodeSeTC_AddIncompleteRace, DecodeSeTC_AskEnterWaitRace, DecodeSeTC_BiVoiceEnterInfo, DecodeSeTC_CancelMatchRep, DecodeSeTC_CardUpdate, DecodeSeTC_CreateCharRet, DecodeSeTC_CreateRoomRet, DecodeSeTC_DelayCheckRet, DecodeSeTC_EncryptKey, DecodeSeTC_EquipSchema, DecodeSeTC_ExchangeInit, DecodeSeTC_FriendAdd, DecodeSeTC_FriendDel, DecodeSeTC_FriendInit, DecodeSeTC_FriendLadderInfoNtf, DecodeSeTC_FriendRemarkRet, DecodeSeTC_FriendRequestAdd, DecodeSeTC_FriendRequestInit, DecodeSeTC_FriendUpdateStatus, DecodeSeTC_GetAchievement, DecodeSeTC_GetRaceHistoryRet, DecodeSeTC_HeartBeat, DecodeSeTC_InGameDisconn, DecodeSeTC_InitPlayerInfo, DecodeSeTC_ItemDel, DecodeSeTC_ItemExchangeRet, DecodeSeTC_KickPlayer, DecodeSeTC_LadderDetailInfoAck, DecodeSeTC_LadderRankQueryAck, DecodeSeTC_MailOprRet, DecodeSeTC_MatchRaceAddr, DecodeSeTC_NexusFriendCleanRefuseNoticeRes, DecodeSeTC_NexusFriendDetailInfoRes, DecodeSeTC_NexusFriendLimitRes, DecodeSeTC_NexusFriendStatusSync, DecodeSeTC_NexusUserActionSync, DecodeSeTC_NexusUserPromotionDetailInfoRes, DecodeSeTC_NotiMatcherPre, DecodeSeTC_NotiMatcherResult, DecodeSeTC_OpenRandBoxRet, DecodeSeTC_PlayerAppear, DecodeSeTC_PlayerDisappear, DecodeSeTC_PlayerGoPos, DecodeSeTC_PlayerLadder, DecodeSeTC_PlayerLeaveRet, DecodeSeTC_PlayerMoneyAndDiamond, DecodeSeTC_PlayerNewItem, DecodeSeTC_PlayerOperRep, DecodeSeTC_PlayerRename, DecodeSeTC_PlayerValidateRet, DecodeSeTC_PutOnEquipRet, DecodeSeTC_QueryMapTaskListRet, DecodeSeTC_QueryNameRet, DecodeSeTC_QueryNearestRaceInfoRet, DecodeSeTC_QueryRaceBetInfoRet, DecodeSeTC_QueryRaceRoomListRet, DecodeSeTC_QueryRoomListRet, DecodeSeTC_ReceiveMail, DecodeSeTC_RemoveIncompleteRace, DecodeSeTC_ReqMatchRep, DecodeSeTC_ResAchievementCounts, DecodeSeTC_ResAchievementDat, DecodeSeTC_ResIncmpRaceSeatBaseInfo, DecodeSeTC_ResIncompleteRaceList, DecodeSeTC_ResRaceDetailInfo, DecodeSeTC_ResView, DecodeSeTC_ResViewList, DecodeSeTC_RoomInviteNotify, DecodeSeTC_RoomJoinRet, DecodeSeTC_RoomKickSomeoneRet, DecodeSeTC_RoomLeaveRet, DecodeSeTC_RoomMemberNotify, DecodeSeTC_RoomStartRet, DecodeSeTC_RoomSwitchSeatRet, DecodeSeTC_SearchUserArchivesDetailInfoRes, DecodeSeTC_SearchUserArchivesInfoRes, DecodeSeTC_SetActiveAvatarAck, DecodeSeTC_SeUserRaceArenaDetailInfoRes, DecodeSeTC_ShopItemGmRep, DecodeSeTC_ShowNotice, DecodeSeTC_SingleMatchConfirm, DecodeSeTC_StartMatchRet, DecodeSeTC_TakeOffEquipRet, DecodeSeTC_TaskQueryListRet, DecodeSeTC_TaskReselRet, DecodeSeTC_TeamChangeSync, DecodeSeTC_TeamLeaderSync, DecodeSeTC_TeamMemberInfoRes, DecodeSeTC_TeamMemberSync, DecodeSeTC_TeamUserStateRes, DecodeSeTC_UpdateMail, DecodeSeTC_UpdateMisc, DecodeSeTC_UserAlterAvatarAndFrameNtf, DecodeSeTC_UserAlterNickNameAck, DecodeSeTC_UserHeroSync, DecodeSeTC_UserRaceMapHeroAck, DecodeSeTC_UserStatusQueryReqRes, DecodeSeTC_ViewResult, DecodeSeTeamMemberBaseInfo, DecodeSeUnlockHeroBaseInfo, DecodeSeUserArchivesInfo, DecodeSeUserArchivesNameInfo, DecodeSeUserBaseAttrInfo, DecodeSeUserHeroSyncInfo, DecodeSeUserRaceMapHeroBase, DecodeSeUserStatusBaseInfo, DecodeSeViewList, DecodeSeWCSC_EncryptKey, DecodeSeWCSC_ViewPack, DecodeSeWCSC_ViewPlayerInfo, DecodeSeWCSC_ViewValidateRet, DecodeSeWCSViewInfo, DecodeSeWSGuanqiaSendInfo, DecodeSeWSRaceSendInfo, DecodeShopItem, EncodeMatchValueStru, EncodePlayerGrades, EncodePlayerGradeStru, EncodeSeAchieveFinish, EncodeSeAchievementCounts, EncodeSeAchievementPtlDat, EncodeSeAchieveSchedule, EncodeSeAttrUnit, EncodeSeAwardItem, EncodeSeCiTiao, EncodeSeCL_PlayerLogin, EncodeSeCL_PlayerLogin_NEW, EncodeSeCL_PlayerSteamLogin, EncodeSeCR_BuyRaceItem, EncodeSeCR_GetHeroInfo, EncodeSeCR_HeartPackage, EncodeSeCR_Ping, EncodeSeCR_RaceCmd, EncodeSeCR_RaceEndGuanqia, EncodeSeCR_RaceEndRace, EncodeSeCR_RaceLeave, EncodeSeCR_RaceLoadEnd, EncodeSeCR_RaceReportSyn, EncodeSeCR_RaceRobotLogin, EncodeSeCR_RaceValidate, EncodeSeCR_ReplayReport, EncodeSeCR_SelHeroCancelHero, EncodeSeCR_SelHeroChoiceHero, EncodeSeCR_SelHeroPrapared, EncodeSeCR_SetAvatarReq, EncodeSeCR_SetEquipSetReq, EncodeSeCR_Talk, EncodeSeCT_AchieveInfoReq, EncodeSeCT_BuyShopItem, EncodeSeCT_ClearItemNewFlag, EncodeSeCT_CloseIncompleteRaceList, EncodeSeCT_CreateChar, EncodeSeCT_CreateRoom, EncodeSeCT_DelayCheck, EncodeSeCT_DelelteItem, EncodeSeCT_DelReconInfo, EncodeSeCT_FriendLadderInfoReq, EncodeSeCT_GetItemGM, EncodeSeCT_GetRaceHistory, EncodeSeCT_GetTaskReward, EncodeSeCT_GMAddItem, EncodeSeCT_GMSetDiamond, EncodeSeCT_GMSetGold, EncodeSeCT_HeartBeat, EncodeSeCT_ItemExchange, EncodeSeCT_LadderDetailInfoReq, EncodeSeCT_LadderRankQueryReq, EncodeSeCT_LeaderDismissTeamReq, EncodeSeCT_LeaderKickMemberReq, EncodeSeCT_LeaveTown, EncodeSeCT_MailOpr, EncodeSeCT_MapTaskOpr, EncodeSeCT_MatchConfirm, EncodeSeCT_NexusFriendCleanRefuseNoticeReq, EncodeSeCT_NexusFriendDetailInfoReq, EncodeSeCT_NexusUserActionReq, EncodeSeCT_NexusUserPromotionDetailInfoReq, EncodeSeCT_NexusUserPromotionReq, EncodeSeCT_OpenRandBox, EncodeSeCT_PlayerGoDirect, EncodeSeCT_PlayerMatchCancel, EncodeSeCT_PlayerMatchReq, EncodeSeCT_PlayerRename, EncodeSeCT_PlayerValidate, EncodeSeCT_PutOnEquip, EncodeSeCT_QueryName, EncodeSeCT_QueryNearestRaceInfo, EncodeSeCT_QueryRaceBetInfo, EncodeSeCT_QueryRaceRoomList, EncodeSeCT_QueryRoomList, EncodeSeCT_RaceDetailInfoReq, EncodeSeCT_RaceEndGuanka, EncodeSeCT_ReconQuery, EncodeSeCT_ReqAchievement, EncodeSeCT_ReqAchievementCounts, EncodeSeCT_ReqIncompleteRaceKDA, EncodeSeCT_ReqIncompleteRaceList, EncodeSeCT_ReqItemCiTiaoChange, EncodeSeCT_ReqItemDepart, EncodeSeCT_ReqItemStrenth, EncodeSeCT_ReqView, EncodeSeCT_ReqViewList, EncodeSeCT_RoomInvite, EncodeSeCT_RoomInviteRsp, EncodeSeCT_RoomJoin, EncodeSeCT_RoomKickSomeone, EncodeSeCT_RoomLeave, EncodeSeCT_RoomStart, EncodeSeCT_RoomSwitchSeat, EncodeSeCT_SearchUserArchivesDetailInfoReq, EncodeSeCT_SearchUserArchivesInfoReq, EncodeSeCT_SetActiveAvatarReq, EncodeSeCT_SeUserRaceArenaDetailInfoReq, EncodeSeCT_ShopItemGM, EncodeSeCT_TakeOffEquip, EncodeSeCT_TaskQueryList, EncodeSeCT_TaskResel, EncodeSeCT_UserAlterAvatarFrameReq, EncodeSeCT_UserAlterAvatarReq, EncodeSeCT_UserAlterNickNameReq, EncodeSeCT_UserConfirmInviteReq, EncodeSeCT_UserInviteReq, EncodeSeCT_UserLeaveTeamReq, EncodeSeCT_UserMapRaceHeroReq, EncodeSeCT_UserPurchaseAvatarReq, EncodeSeCT_UserRefuseInviteReq, EncodeSeCT_UserStatusQueryReq, EncodeSeCT_ViewBegin, EncodeSeCWCS_ViewValidate, EncodeSeEquipSchemaInfo, EncodeSeExternAttrUnit, EncodeSeGuanqiaSendInfo, EncodeSeIncompleteRaceBaseInfo, EncodeSeItemNoti, EncodeSeLadderDetailInfo, EncodeSeLadderInfo, EncodeSeLadderRankInfo, EncodeSeLC_ClientVersion, EncodeSeLC_EncryptKey, EncodeSeLC_GateList, EncodeSeLC_PlayerLoginRet, EncodeSeLC_SteamCheckReturn, EncodeSeMailAttach, EncodeSeMailUpdate, EncodeSeMatchFightInfo, EncodeSeMatchRoomListInfo, EncodeSeMatchSelPlayerInfo, EncodeSeMatchStartInfo, EncodeSeMobileInfo, EncodeSeNexusFriendSyncInfo, EncodeSeNexusKeyInfo, EncodeSeNexusPlayerInfo, EncodeSeNexusTeamBaseInfo, EncodeSeNexusTeamMemberInfo, EncodeSeNexusUserBaseInfo, EncodeSeNexusUserInfo, EncodeSeNexusUserPromotionInfo, EncodeSeNoticeMatchPlayerInfo, EncodeSeOpenRoomInfo, EncodeSePlayerAchievementCounts, EncodeSePlayerAppear, EncodeSePlayerDisappear, EncodeSePlayerInfoSeat, EncodeSePtlExchange, EncodeSePtlFriend, EncodeSePtlFriendRequest, EncodeSePtlMail, EncodeSePtlMapTask, EncodeSePtlNetAddr, EncodeSePtlRaceBetInfo, EncodeSePtlRaceHistory, EncodeSePtlStaMap, EncodeSePtlTask, EncodeSeQueryPlayerRaceInfo, EncodeSeRaceBaseBuildingInfo, EncodeSeRaceCampBuildingInfo, EncodeSeRaceDetailInfo, EncodeSeRaceEndArenaBaseInfo, EncodeSeRaceEndArenaDetailInfo, EncodeSeRaceEndArenaResult, EncodeSeRaceGameInfo, EncodeSeRaceInfo, EncodeSeRaceMapBuildingInfo, EncodeSeRaceMapInfo, EncodeSeRaceMapPosInfo, EncodeSeRaceSendInfo, EncodeSeRaceTask, EncodeSeRaceUserHeroInfo, EncodeSeRaceUserInfo, EncodeSeRaceWaitPlayer, EncodeSeRandBoxItem, EncodeSeRC_BeginSelectHero, EncodeSeRC_EncryptKey, EncodeSeRC_GetHeroInfoRet, EncodeSeRC_HeartBeat, EncodeSeRC_PingRet, EncodeSeRC_RaceEndNotifyDown, EncodeSeRC_RaceGoldExpPlus, EncodeSeRC_RacePack, EncodeSeRC_RacePlayerLoadEnd, EncodeSeRC_RaceStream, EncodeSeRC_ReconPack, EncodeSeRC_ReconResult, EncodeSeRC_RoomPlayerBaseInfo, EncodeSeRC_SeatScoreNtf, EncodeSeRC_SelHeroList, EncodeSeRC_SelHeroMessage, EncodeSeRC_SelHorseList, EncodeSeRC_SelPetList, EncodeSeRC_SetAvatarAck, EncodeSeRC_SetEquipSetAck, EncodeSeRC_ShowNotice, EncodeSeRC_Talk, EncodeSeRC_ValidateRet, EncodeSeRC_ViewPack, EncodeSeRC_ViewPlayerInfo, EncodeSeRC_ViewResult, EncodeSeRoomMember, EncodeSeScoreInfo, EncodeSeSeatBaseInfo, EncodeSeSeatScore, EncodeSeSelHeroInfo, EncodeSeTC_AchieveInfoAck, EncodeSeTC_ActiveAvatarNtf, EncodeSeTC_AddIncompleteRace, EncodeSeTC_AskEnterWaitRace, EncodeSeTC_BiVoiceEnterInfo, EncodeSeTC_CancelMatchRep, EncodeSeTC_CardUpdate, EncodeSeTC_CreateCharRet, EncodeSeTC_CreateRoomRet, EncodeSeTC_DelayCheckRet, EncodeSeTC_EncryptKey, EncodeSeTC_EquipSchema, EncodeSeTC_ExchangeInit, EncodeSeTC_FriendAdd, EncodeSeTC_FriendDel, EncodeSeTC_FriendInit, EncodeSeTC_FriendLadderInfoNtf, EncodeSeTC_FriendRemarkRet, EncodeSeTC_FriendRequestAdd, EncodeSeTC_FriendRequestInit, EncodeSeTC_FriendUpdateStatus, EncodeSeTC_GetAchievement, EncodeSeTC_GetRaceHistoryRet, EncodeSeTC_HeartBeat, EncodeSeTC_InGameDisconn, EncodeSeTC_InitPlayerInfo, EncodeSeTC_ItemDel, EncodeSeTC_ItemExchangeRet, EncodeSeTC_KickPlayer, EncodeSeTC_LadderDetailInfoAck, EncodeSeTC_LadderRankQueryAck, EncodeSeTC_MailOprRet, EncodeSeTC_MatchRaceAddr, EncodeSeTC_NexusFriendCleanRefuseNoticeRes, EncodeSeTC_NexusFriendDetailInfoRes, EncodeSeTC_NexusFriendLimitRes, EncodeSeTC_NexusFriendStatusSync, EncodeSeTC_NexusUserActionSync, EncodeSeTC_NexusUserPromotionDetailInfoRes, EncodeSeTC_NotiMatcherPre, EncodeSeTC_NotiMatcherResult, EncodeSeTC_OpenRandBoxRet, EncodeSeTC_PlayerAppear, EncodeSeTC_PlayerDisappear, EncodeSeTC_PlayerGoPos, EncodeSeTC_PlayerLadder, EncodeSeTC_PlayerLeaveRet, EncodeSeTC_PlayerMoneyAndDiamond, EncodeSeTC_PlayerNewItem, EncodeSeTC_PlayerOperRep, EncodeSeTC_PlayerRename, EncodeSeTC_PlayerValidateRet, EncodeSeTC_PutOnEquipRet, EncodeSeTC_QueryMapTaskListRet, EncodeSeTC_QueryNameRet, EncodeSeTC_QueryNearestRaceInfoRet, EncodeSeTC_QueryRaceBetInfoRet, EncodeSeTC_QueryRaceRoomListRet, EncodeSeTC_QueryRoomListRet, EncodeSeTC_ReceiveMail, EncodeSeTC_RemoveIncompleteRace, EncodeSeTC_ReqMatchRep, EncodeSeTC_ResAchievementCounts, EncodeSeTC_ResAchievementDat, EncodeSeTC_ResIncmpRaceSeatBaseInfo, EncodeSeTC_ResIncompleteRaceList, EncodeSeTC_ResRaceDetailInfo, EncodeSeTC_ResView, EncodeSeTC_ResViewList, EncodeSeTC_RoomInviteNotify, EncodeSeTC_RoomJoinRet, EncodeSeTC_RoomKickSomeoneRet, EncodeSeTC_RoomLeaveRet, EncodeSeTC_RoomMemberNotify, EncodeSeTC_RoomStartRet, EncodeSeTC_RoomSwitchSeatRet, EncodeSeTC_SearchUserArchivesDetailInfoRes, EncodeSeTC_SearchUserArchivesInfoRes, EncodeSeTC_SetActiveAvatarAck, EncodeSeTC_SeUserRaceArenaDetailInfoRes, EncodeSeTC_ShopItemGmRep, EncodeSeTC_ShowNotice, EncodeSeTC_SingleMatchConfirm, EncodeSeTC_StartMatchRet, EncodeSeTC_TakeOffEquipRet, EncodeSeTC_TaskQueryListRet, EncodeSeTC_TaskReselRet, EncodeSeTC_TeamChangeSync, EncodeSeTC_TeamLeaderSync, EncodeSeTC_TeamMemberInfoRes, EncodeSeTC_TeamMemberSync, EncodeSeTC_TeamUserStateRes, EncodeSeTC_UpdateMail, EncodeSeTC_UpdateMisc, EncodeSeTC_UserAlterAvatarAndFrameNtf, EncodeSeTC_UserAlterNickNameAck, EncodeSeTC_UserHeroSync, EncodeSeTC_UserRaceMapHeroAck, EncodeSeTC_UserStatusQueryReqRes, EncodeSeTC_ViewResult, EncodeSeTeamMemberBaseInfo, EncodeSeUnlockHeroBaseInfo, EncodeSeUserArchivesInfo, EncodeSeUserArchivesNameInfo, EncodeSeUserBaseAttrInfo, EncodeSeUserHeroSyncInfo, EncodeSeUserRaceMapHeroBase, EncodeSeUserStatusBaseInfo, EncodeSeViewList, EncodeSeWCSC_EncryptKey, EncodeSeWCSC_ViewPack, EncodeSeWCSC_ViewPlayerInfo, EncodeSeWCSC_ViewValidateRet, EncodeSeWCSViewInfo, EncodeSeWSGuanqiaSendInfo, EncodeSeWSRaceSendInfo, EncodeShopItem, SeRaceMgr::OnRaceModeEnd, MatchServer::OnSendRSValidatePlayerInfo, BlockServer::ProcessMBL_RaceMatchLoadDetail, TcpServer::ProcessParent_RegisterRet.
void SeNetStream::SetCurPos(int iPos)
References m_iPos, m_iSize.
Referenced by DecodeMatchValueStru, DecodePlayerGrades, DecodeSeCiTiao, DecodeSeCR_RaceEndGuanqia, DecodeSeCR_RaceEndRace, DecodeSeCT_NexusUserActionReq, DecodeSeCT_NexusUserPromotionReq, DecodeSeCT_PlayerValidate, DecodeSeCT_RaceEndGuanka, DecodeSeCT_SearchUserArchivesInfoReq, DecodeSeCT_ShopItemGM, DecodeSeGuanqiaSendInfo, DecodeSeItemNoti, DecodeSeNexusPlayerInfo, DecodeSeNexusUserInfo, DecodeSeNexusUserPromotionInfo, DecodeSeOpenRoomInfo, DecodeSeQueryPlayerRaceInfo, DecodeSeRaceCampBuildingInfo, DecodeSeRaceDetailInfo, DecodeSeRaceInfo, DecodeSeRaceMapBuildingInfo, DecodeSeRaceMapInfo, DecodeSeRaceSendInfo, DecodeSeRaceUserInfo, DecodeSeRC_RoomPlayerBaseInfo, DecodeSeRC_SeatScoreNtf, DecodeSeRC_SelHeroList, DecodeSeRC_ViewPlayerInfo, DecodeSeTC_AchieveInfoAck, DecodeSeTC_AddIncompleteRace, DecodeSeTC_AskEnterWaitRace, DecodeSeTC_CreateRoomRet, DecodeSeTC_EquipSchema, DecodeSeTC_ExchangeInit, DecodeSeTC_FriendAdd, DecodeSeTC_FriendInit, DecodeSeTC_FriendLadderInfoNtf, DecodeSeTC_FriendRequestAdd, DecodeSeTC_FriendRequestInit, DecodeSeTC_GetRaceHistoryRet, DecodeSeTC_InitPlayerInfo, DecodeSeTC_LadderDetailInfoAck, DecodeSeTC_LadderRankQueryAck, DecodeSeTC_MatchRaceAddr, DecodeSeTC_NexusFriendDetailInfoRes, DecodeSeTC_NexusUserActionSync, DecodeSeTC_NexusUserPromotionDetailInfoRes, DecodeSeTC_OpenRandBoxRet, DecodeSeTC_PlayerAppear, DecodeSeTC_PlayerDisappear, DecodeSeTC_PlayerLadder, DecodeSeTC_PlayerNewItem, DecodeSeTC_QueryMapTaskListRet, DecodeSeTC_QueryNearestRaceInfoRet, DecodeSeTC_QueryRaceRoomListRet, DecodeSeTC_QueryRoomListRet, DecodeSeTC_ReceiveMail, DecodeSeTC_ResAchievementCounts, DecodeSeTC_ResAchievementDat, DecodeSeTC_ResIncmpRaceSeatBaseInfo, DecodeSeTC_ResIncompleteRaceList, DecodeSeTC_ResRaceDetailInfo, DecodeSeTC_ResView, DecodeSeTC_ResViewList, DecodeSeTC_RoomJoinRet, DecodeSeTC_RoomMemberNotify, DecodeSeTC_SearchUserArchivesDetailInfoRes, DecodeSeTC_SearchUserArchivesInfoRes, DecodeSeTC_SeUserRaceArenaDetailInfoRes, DecodeSeTC_ShopItemGmRep, DecodeSeTC_TaskQueryListRet, DecodeSeTC_TaskReselRet, DecodeSeTC_TeamMemberInfoRes, DecodeSeTC_UpdateMail, DecodeSeTC_UserHeroSync, DecodeSeTC_UserRaceMapHeroAck, DecodeSeTC_UserStatusQueryReqRes, DecodeSeWCSC_ViewPlayerInfo, DecodeSeWSGuanqiaSendInfo, DecodeSeWSRaceSendInfo, EncodeMatchValueStru, EncodePlayerGrades, EncodeSeCiTiao, EncodeSeCR_RaceEndGuanqia, EncodeSeCR_RaceEndRace, EncodeSeCT_NexusUserActionReq, EncodeSeCT_NexusUserPromotionReq, EncodeSeCT_PlayerValidate, EncodeSeCT_RaceEndGuanka, EncodeSeCT_SearchUserArchivesInfoReq, EncodeSeCT_ShopItemGM, EncodeSeGuanqiaSendInfo, EncodeSeItemNoti, EncodeSeNexusPlayerInfo, EncodeSeNexusUserInfo, EncodeSeNexusUserPromotionInfo, EncodeSeOpenRoomInfo, EncodeSeQueryPlayerRaceInfo, EncodeSeRaceCampBuildingInfo, EncodeSeRaceDetailInfo, EncodeSeRaceInfo, EncodeSeRaceMapBuildingInfo, EncodeSeRaceMapInfo, EncodeSeRaceSendInfo, EncodeSeRaceUserInfo, EncodeSeRC_RoomPlayerBaseInfo, EncodeSeRC_SeatScoreNtf, EncodeSeRC_SelHeroList, EncodeSeRC_ViewPlayerInfo, EncodeSeTC_AchieveInfoAck, EncodeSeTC_AddIncompleteRace, EncodeSeTC_AskEnterWaitRace, EncodeSeTC_CreateRoomRet, EncodeSeTC_EquipSchema, EncodeSeTC_ExchangeInit, EncodeSeTC_FriendAdd, EncodeSeTC_FriendInit, EncodeSeTC_FriendLadderInfoNtf, EncodeSeTC_FriendRequestAdd, EncodeSeTC_FriendRequestInit, EncodeSeTC_GetRaceHistoryRet, EncodeSeTC_InitPlayerInfo, EncodeSeTC_LadderDetailInfoAck, EncodeSeTC_LadderRankQueryAck, EncodeSeTC_MatchRaceAddr, EncodeSeTC_NexusFriendDetailInfoRes, EncodeSeTC_NexusUserActionSync, EncodeSeTC_NexusUserPromotionDetailInfoRes, EncodeSeTC_OpenRandBoxRet, EncodeSeTC_PlayerAppear, EncodeSeTC_PlayerDisappear, EncodeSeTC_PlayerLadder, EncodeSeTC_PlayerNewItem, EncodeSeTC_QueryMapTaskListRet, EncodeSeTC_QueryNearestRaceInfoRet, EncodeSeTC_QueryRaceRoomListRet, EncodeSeTC_QueryRoomListRet, EncodeSeTC_ReceiveMail, EncodeSeTC_ResAchievementCounts, EncodeSeTC_ResAchievementDat, EncodeSeTC_ResIncmpRaceSeatBaseInfo, EncodeSeTC_ResIncompleteRaceList, EncodeSeTC_ResRaceDetailInfo, EncodeSeTC_ResView, EncodeSeTC_ResViewList, EncodeSeTC_RoomJoinRet, EncodeSeTC_RoomMemberNotify, EncodeSeTC_SearchUserArchivesDetailInfoRes, EncodeSeTC_SearchUserArchivesInfoRes, EncodeSeTC_SeUserRaceArenaDetailInfoRes, EncodeSeTC_ShopItemGmRep, EncodeSeTC_TaskQueryListRet, EncodeSeTC_TaskReselRet, EncodeSeTC_TeamMemberInfoRes, EncodeSeTC_UpdateMail, EncodeSeTC_UserHeroSync, EncodeSeTC_UserRaceMapHeroAck, EncodeSeTC_UserStatusQueryReqRes, EncodeSeWCSC_ViewPlayerInfo, EncodeSeWSGuanqiaSendInfo, EncodeSeWSRaceSendInfo.
bool SeNetStream::Read(void *pkVoid, int iSize)
References m_iPos, m_iSize, m_pcData.
Referenced by DecodeMatchValueStru, DecodePlayerGrades, DecodePlayerGradeStru, DecodeSeAchieveFinish, DecodeSeAchievementCounts, DecodeSeAchievementPtlDat, DecodeSeAchieveSchedule, DecodeSeAttrUnit, DecodeSeAwardItem, DecodeSeCiTiao, DecodeSeCL_PlayerLogin, DecodeSeCL_PlayerLogin_NEW, DecodeSeCL_PlayerSteamLogin, DecodeSeCR_BuyRaceItem, DecodeSeCR_GetHeroInfo, DecodeSeCR_Ping, DecodeSeCR_RaceCmd, DecodeSeCR_RaceEndGuanqia, DecodeSeCR_RaceEndRace, DecodeSeCR_RaceLoadEnd, DecodeSeCR_RaceReportSyn, DecodeSeCR_RaceRobotLogin, DecodeSeCR_RaceValidate, DecodeSeCR_ReplayReport, DecodeSeCR_SelHeroChoiceHero, DecodeSeCR_SetAvatarReq, DecodeSeCR_SetEquipSetReq, DecodeSeCR_Talk, DecodeSeCT_BuyShopItem, DecodeSeCT_ClearItemNewFlag, DecodeSeCT_CreateChar, DecodeSeCT_CreateRoom, DecodeSeCT_DelelteItem, DecodeSeCT_FriendLadderInfoReq, DecodeSeCT_GetItemGM, DecodeSeCT_GetRaceHistory, DecodeSeCT_GetTaskReward, DecodeSeCT_GMAddItem, DecodeSeCT_GMSetDiamond, DecodeSeCT_GMSetGold, DecodeSeCT_ItemExchange, DecodeSeCT_LeaderDismissTeamReq, DecodeSeCT_LeaderKickMemberReq, DecodeSeCT_LeaveTown, DecodeSeCT_MailOpr, DecodeSeCT_MapTaskOpr, DecodeSeCT_MatchConfirm, DecodeSeCT_NexusFriendCleanRefuseNoticeReq, DecodeSeCT_NexusFriendDetailInfoReq, DecodeSeCT_OpenRandBox, DecodeSeCT_PlayerGoDirect, DecodeSeCT_PlayerMatchReq, DecodeSeCT_PlayerValidate, DecodeSeCT_PutOnEquip, DecodeSeCT_QueryNearestRaceInfo, DecodeSeCT_QueryRaceRoomList, DecodeSeCT_QueryRoomList, DecodeSeCT_RaceDetailInfoReq, DecodeSeCT_RaceEndGuanka, DecodeSeCT_ReconQuery, DecodeSeCT_ReqAchievement, DecodeSeCT_ReqIncompleteRaceKDA, DecodeSeCT_ReqItemCiTiaoChange, DecodeSeCT_ReqItemDepart, DecodeSeCT_ReqItemStrenth, DecodeSeCT_ReqView, DecodeSeCT_ReqViewList, DecodeSeCT_RoomInvite, DecodeSeCT_RoomInviteRsp, DecodeSeCT_RoomJoin, DecodeSeCT_RoomKickSomeone, DecodeSeCT_RoomLeave, DecodeSeCT_RoomStart, DecodeSeCT_RoomSwitchSeat, DecodeSeCT_SearchUserArchivesDetailInfoReq, DecodeSeCT_SetActiveAvatarReq, DecodeSeCT_ShopItemGM, DecodeSeCT_TakeOffEquip, DecodeSeCT_TaskResel, DecodeSeCT_UserAlterAvatarFrameReq, DecodeSeCT_UserAlterAvatarReq, DecodeSeCT_UserConfirmInviteReq, DecodeSeCT_UserInviteReq, DecodeSeCT_UserLeaveTeamReq, DecodeSeCT_UserPurchaseAvatarReq, DecodeSeCT_UserRefuseInviteReq, DecodeSeCT_UserStatusQueryReq, DecodeSeCT_ViewBegin, DecodeSeCWCS_ViewValidate, DecodeSeEquipSchemaInfo, DecodeSeExternAttrUnit, DecodeSeGuanqiaSendInfo, DecodeSeIncompleteRaceBaseInfo, DecodeSeItemNoti, DecodeSeLadderDetailInfo, DecodeSeLadderInfo, DecodeSeLadderRankInfo, DecodeSeLC_ClientVersion, DecodeSeLC_GateList, DecodeSeLC_PlayerLoginRet, DecodeSeLC_SteamCheckReturn, DecodeSeMailAttach, DecodeSeMailUpdate, DecodeSeMatchFightInfo, DecodeSeMatchRoomListInfo, DecodeSeMatchSelPlayerInfo, DecodeSeMatchStartInfo, DecodeSeMobileInfo, DecodeSeNexusFriendSyncInfo, DecodeSeNexusKeyInfo, DecodeSeNexusTeamBaseInfo, DecodeSeNexusTeamMemberInfo, DecodeSeNexusUserBaseInfo, DecodeSeNoticeMatchPlayerInfo, DecodeSeOpenRoomInfo, DecodeSePlayerAchievementCounts, DecodeSePlayerAppear, DecodeSePlayerDisappear, DecodeSePlayerInfoSeat, DecodeSePtlExchange, DecodeSePtlFriend, DecodeSePtlFriendRequest, DecodeSePtlMail, DecodeSePtlMapTask, DecodeSePtlNetAddr, DecodeSePtlRaceBetInfo, DecodeSePtlRaceHistory, DecodeSePtlStaMap, DecodeSePtlTask, DecodeSeQueryPlayerRaceInfo, DecodeSeRaceBaseBuildingInfo, DecodeSeRaceCampBuildingInfo, DecodeSeRaceDetailInfo, DecodeSeRaceEndArenaBaseInfo, DecodeSeRaceEndArenaDetailInfo, DecodeSeRaceEndArenaResult, DecodeSeRaceGameInfo, DecodeSeRaceMapInfo, DecodeSeRaceMapPosInfo, DecodeSeRaceSendInfo, DecodeSeRaceTask, DecodeSeRaceUserHeroInfo, DecodeSeRaceUserInfo, DecodeSeRaceWaitPlayer, DecodeSeRandBoxItem, DecodeSeRC_BeginSelectHero, DecodeSeRC_EncryptKey, DecodeSeRC_GetHeroInfoRet, DecodeSeRC_PingRet, DecodeSeRC_RaceGoldExpPlus, DecodeSeRC_RacePack, DecodeSeRC_RacePlayerLoadEnd, DecodeSeRC_RaceStream, DecodeSeRC_ReconPack, DecodeSeRC_ReconResult, DecodeSeRC_RoomPlayerBaseInfo, DecodeSeRC_SelHeroList, DecodeSeRC_SelHeroMessage, DecodeSeRC_SelHorseList, DecodeSeRC_SelPetList, DecodeSeRC_SetAvatarAck, DecodeSeRC_SetEquipSetAck, DecodeSeRC_ShowNotice, DecodeSeRC_Talk, DecodeSeRC_ValidateRet, DecodeSeRC_ViewPack, DecodeSeRC_ViewPlayerInfo, DecodeSeRC_ViewResult, DecodeSeRoomMember, DecodeSeScoreInfo, DecodeSeSeatBaseInfo, DecodeSeSeatScore, DecodeSeSelHeroInfo, DecodeSeTC_AchieveInfoAck, DecodeSeTC_ActiveAvatarNtf, DecodeSeTC_AskEnterWaitRace, DecodeSeTC_BiVoiceEnterInfo, DecodeSeTC_CancelMatchRep, DecodeSeTC_CreateCharRet, DecodeSeTC_CreateRoomRet, DecodeSeTC_EncryptKey, DecodeSeTC_EquipSchema, DecodeSeTC_ExchangeInit, DecodeSeTC_FriendDel, DecodeSeTC_FriendInit, DecodeSeTC_FriendLadderInfoNtf, DecodeSeTC_FriendRemarkRet, DecodeSeTC_FriendRequestInit, DecodeSeTC_FriendUpdateStatus, DecodeSeTC_GetAchievement, DecodeSeTC_GetRaceHistoryRet, DecodeSeTC_InGameDisconn, DecodeSeTC_InitPlayerInfo, DecodeSeTC_ItemDel, DecodeSeTC_ItemExchangeRet, DecodeSeTC_LadderRankQueryAck, DecodeSeTC_MailOprRet, DecodeSeTC_MatchRaceAddr, DecodeSeTC_NexusFriendCleanRefuseNoticeRes, DecodeSeTC_NexusFriendDetailInfoRes, DecodeSeTC_NexusFriendLimitRes, DecodeSeTC_NexusFriendStatusSync, DecodeSeTC_NotiMatcherPre, DecodeSeTC_NotiMatcherResult, DecodeSeTC_OpenRandBoxRet, DecodeSeTC_PlayerAppear, DecodeSeTC_PlayerDisappear, DecodeSeTC_PlayerGoPos, DecodeSeTC_PlayerMoneyAndDiamond, DecodeSeTC_PlayerNewItem, DecodeSeTC_PlayerOperRep, DecodeSeTC_PlayerValidateRet, DecodeSeTC_PutOnEquipRet, DecodeSeTC_QueryMapTaskListRet, DecodeSeTC_QueryNameRet, DecodeSeTC_QueryNearestRaceInfoRet, DecodeSeTC_QueryRaceBetInfoRet, DecodeSeTC_QueryRaceRoomListRet, DecodeSeTC_QueryRoomListRet, DecodeSeTC_ReceiveMail, DecodeSeTC_RemoveIncompleteRace, DecodeSeTC_ReqMatchRep, DecodeSeTC_ResAchievementCounts, DecodeSeTC_ResAchievementDat, DecodeSeTC_ResIncmpRaceSeatBaseInfo, DecodeSeTC_ResIncompleteRaceList, DecodeSeTC_ResRaceDetailInfo, DecodeSeTC_ResView, DecodeSeTC_ResViewList, DecodeSeTC_RoomInviteNotify, DecodeSeTC_RoomJoinRet, DecodeSeTC_RoomKickSomeoneRet, DecodeSeTC_RoomLeaveRet, DecodeSeTC_RoomMemberNotify, DecodeSeTC_RoomStartRet, DecodeSeTC_RoomSwitchSeatRet, DecodeSeTC_SetActiveAvatarAck, DecodeSeTC_ShopItemGmRep, DecodeSeTC_ShowNotice, DecodeSeTC_SingleMatchConfirm, DecodeSeTC_StartMatchRet, DecodeSeTC_TakeOffEquipRet, DecodeSeTC_TaskQueryListRet, DecodeSeTC_TaskReselRet, DecodeSeTC_TeamChangeSync, DecodeSeTC_TeamLeaderSync, DecodeSeTC_TeamMemberInfoRes, DecodeSeTC_TeamMemberSync, DecodeSeTC_TeamUserStateRes, DecodeSeTC_UpdateMail, DecodeSeTC_UpdateMisc, DecodeSeTC_UserAlterAvatarAndFrameNtf, DecodeSeTC_UserAlterNickNameAck, DecodeSeTC_UserHeroSync, DecodeSeTC_UserRaceMapHeroAck, DecodeSeTC_UserStatusQueryReqRes, DecodeSeTC_ViewResult, DecodeSeTeamMemberBaseInfo, DecodeSeUnlockHeroBaseInfo, DecodeSeUserArchivesInfo, DecodeSeUserBaseAttrInfo, DecodeSeUserHeroSyncInfo, DecodeSeUserRaceMapHeroBase, DecodeSeUserStatusBaseInfo, DecodeSeViewList, DecodeSeWCSC_EncryptKey, DecodeSeWCSC_ViewPack, DecodeSeWCSC_ViewPlayerInfo, DecodeSeWCSC_ViewValidateRet, DecodeSeWCSViewInfo, DecodeSeWSGuanqiaSendInfo, DecodeSeWSRaceSendInfo, DecodeShopItem, Read, ReadByte, ReadChar, ReadDword, ReadFloat, ReadInt, ReadInt3Byte, ReadNetStream, ReadShort, ReadString, ReadStringB, ReadStringValue, ReadValue, ReadWord.
char SeNetStream::ReadChar(void)
References Read.
Referenced by ReadDBTime.
Byte SeNetStream::ReadByte(void)
References Read.
Referenced by ReadStringB.
short SeNetStream::ReadShort(void)
References Read.
Referenced by ReadDBTime.
Word SeNetStream::ReadWord(void)
References Read.
Referenced by ReadString.
int SeNetStream::ReadInt(void)
References Read.
float SeNetStream::ReadFloat(void)
References Read.
unsigned int SeNetStream::ReadDword(void)
References Read.
Referenced by TownServer::ProcessTCPSvr_ReLoadReadyID.
bool SeNetStream::ReadString(char *pcValue)
References Read, ReadWord, TOOL_MAX_STRING.
Referenced by DecodeMatchValueStru, DecodeSeCL_PlayerLogin, DecodeSeCL_PlayerLogin_NEW, DecodeSeCL_PlayerSteamLogin, DecodeSeCR_ReplayReport, DecodeSeCR_Talk, DecodeSeCT_CreateChar, DecodeSeCT_CreateRoom, DecodeSeCT_PlayerRename, DecodeSeCT_QueryName, DecodeSeCT_RoomJoin, DecodeSeCT_UserAlterNickNameReq, DecodeSeCT_UserInviteReq, DecodeSeLadderRankInfo, DecodeSeLC_ClientVersion, DecodeSeLC_EncryptKey, DecodeSeLC_GateList, DecodeSeLC_PlayerLoginRet, DecodeSeMatchSelPlayerInfo, DecodeSeMobileInfo, DecodeSeNexusFriendSyncInfo, DecodeSeNexusTeamBaseInfo, DecodeSeNexusTeamMemberInfo, DecodeSeNexusUserBaseInfo, DecodeSeNoticeMatchPlayerInfo, DecodeSeOpenRoomInfo, DecodeSePlayerInfoSeat, DecodeSePtlFriend, DecodeSePtlFriendRequest, DecodeSePtlMail, DecodeSePtlNetAddr, DecodeSePtlRaceHistory, DecodeSeRaceUserInfo, DecodeSeRC_EncryptKey, DecodeSeRC_RaceEndNotifyDown, DecodeSeRC_Talk, DecodeSeRoomMember, DecodeSeTC_BiVoiceEnterInfo, DecodeSeTC_EncryptKey, DecodeSeTC_FriendRemarkRet, DecodeSeTC_GetRaceHistoryRet, DecodeSeTC_InitPlayerInfo, DecodeSeTC_PlayerRename, DecodeSeTC_RoomInviteNotify, DecodeSeTC_ShowNotice, DecodeSeTC_TeamChangeSync, DecodeSeTC_TeamLeaderSync, DecodeSeTC_TeamMemberSync, DecodeSeTeamMemberBaseInfo, DecodeSeUserArchivesInfo, DecodeSeUserArchivesNameInfo, DecodeSeUserBaseAttrInfo, DecodeSeWCSC_EncryptKey.
std::string SeNetStream::ReadString(void)
References Read, ReadWord, TOOL_MAX_STRING.
bool SeNetStream::ReadString(char *pcValue, int iMaxLen)
References Read, ReadWord, TOOL_MAX_STRING.
bool SeNetStream::ReadDBTime(SeDBTime &rkTime)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear, ReadChar, ReadShort.
bool SeNetStream::ReadStringB(char *pcValue)
References Read, ReadByte, TOOL_MAX_STRING.
int SeNetStream::ReadInt3Byte()
References Read.
bool SeNetStream::ReadNetStream(SeNetStream *netStream, int iSize)
References m_pcData, Read.
int SeNetStream::ReadValue(int iSize)
References Read.
bool SeNetStream::ReadStringValue(char *pcValue, int Size)
References Read, TOOL_MAX_STRING.
bool SeNetStream::Write(const void *pkVoid, int iSize)
References m_iPos, m_iSize, m_pcData.
Referenced by EncodeMatchValueStru, EncodePlayerGrades, EncodePlayerGradeStru, EncodeSeAchieveFinish, EncodeSeAchievementCounts, EncodeSeAchievementPtlDat, EncodeSeAchieveSchedule, EncodeSeAttrUnit, EncodeSeAwardItem, EncodeSeCiTiao, EncodeSeCL_PlayerLogin, EncodeSeCL_PlayerLogin_NEW, EncodeSeCL_PlayerSteamLogin, EncodeSeCR_BuyRaceItem, EncodeSeCR_GetHeroInfo, EncodeSeCR_Ping, EncodeSeCR_RaceCmd, EncodeSeCR_RaceEndGuanqia, EncodeSeCR_RaceEndRace, EncodeSeCR_RaceLoadEnd, EncodeSeCR_RaceReportSyn, EncodeSeCR_RaceRobotLogin, EncodeSeCR_RaceValidate, EncodeSeCR_ReplayReport, EncodeSeCR_SelHeroChoiceHero, EncodeSeCR_SetAvatarReq, EncodeSeCR_SetEquipSetReq, EncodeSeCR_Talk, EncodeSeCT_BuyShopItem, EncodeSeCT_ClearItemNewFlag, EncodeSeCT_CreateChar, EncodeSeCT_CreateRoom, EncodeSeCT_DelelteItem, EncodeSeCT_FriendLadderInfoReq, EncodeSeCT_GetItemGM, EncodeSeCT_GetRaceHistory, EncodeSeCT_GetTaskReward, EncodeSeCT_GMAddItem, EncodeSeCT_GMSetDiamond, EncodeSeCT_GMSetGold, EncodeSeCT_ItemExchange, EncodeSeCT_LeaderDismissTeamReq, EncodeSeCT_LeaderKickMemberReq, EncodeSeCT_LeaveTown, EncodeSeCT_MailOpr, EncodeSeCT_MapTaskOpr, EncodeSeCT_MatchConfirm, EncodeSeCT_NexusFriendCleanRefuseNoticeReq, EncodeSeCT_NexusFriendDetailInfoReq, EncodeSeCT_OpenRandBox, EncodeSeCT_PlayerGoDirect, EncodeSeCT_PlayerMatchReq, EncodeSeCT_PlayerValidate, EncodeSeCT_PutOnEquip, EncodeSeCT_QueryNearestRaceInfo, EncodeSeCT_QueryRaceRoomList, EncodeSeCT_QueryRoomList, EncodeSeCT_RaceDetailInfoReq, EncodeSeCT_RaceEndGuanka, EncodeSeCT_ReconQuery, EncodeSeCT_ReqAchievement, EncodeSeCT_ReqIncompleteRaceKDA, EncodeSeCT_ReqItemCiTiaoChange, EncodeSeCT_ReqItemDepart, EncodeSeCT_ReqItemStrenth, EncodeSeCT_ReqView, EncodeSeCT_ReqViewList, EncodeSeCT_RoomInvite, EncodeSeCT_RoomInviteRsp, EncodeSeCT_RoomJoin, EncodeSeCT_RoomKickSomeone, EncodeSeCT_RoomLeave, EncodeSeCT_RoomStart, EncodeSeCT_RoomSwitchSeat, EncodeSeCT_SearchUserArchivesDetailInfoReq, EncodeSeCT_SetActiveAvatarReq, EncodeSeCT_ShopItemGM, EncodeSeCT_TakeOffEquip, EncodeSeCT_TaskResel, EncodeSeCT_UserAlterAvatarFrameReq, EncodeSeCT_UserAlterAvatarReq, EncodeSeCT_UserConfirmInviteReq, EncodeSeCT_UserInviteReq, EncodeSeCT_UserLeaveTeamReq, EncodeSeCT_UserPurchaseAvatarReq, EncodeSeCT_UserRefuseInviteReq, EncodeSeCT_UserStatusQueryReq, EncodeSeCT_ViewBegin, EncodeSeCWCS_ViewValidate, EncodeSeEquipSchemaInfo, EncodeSeExternAttrUnit, EncodeSeGuanqiaSendInfo, EncodeSeIncompleteRaceBaseInfo, EncodeSeItemNoti, EncodeSeLadderDetailInfo, EncodeSeLadderInfo, EncodeSeLadderRankInfo, EncodeSeLC_ClientVersion, EncodeSeLC_GateList, EncodeSeLC_PlayerLoginRet, EncodeSeLC_SteamCheckReturn, EncodeSeMailAttach, EncodeSeMailUpdate, EncodeSeMatchFightInfo, EncodeSeMatchRoomListInfo, EncodeSeMatchSelPlayerInfo, EncodeSeMatchStartInfo, EncodeSeMobileInfo, EncodeSeNexusFriendSyncInfo, EncodeSeNexusKeyInfo, EncodeSeNexusTeamBaseInfo, EncodeSeNexusTeamMemberInfo, EncodeSeNexusUserBaseInfo, EncodeSeNoticeMatchPlayerInfo, EncodeSeOpenRoomInfo, EncodeSePlayerAchievementCounts, EncodeSePlayerAppear, EncodeSePlayerDisappear, EncodeSePlayerInfoSeat, EncodeSePtlExchange, EncodeSePtlFriend, EncodeSePtlFriendRequest, EncodeSePtlMail, EncodeSePtlMapTask, EncodeSePtlNetAddr, EncodeSePtlRaceBetInfo, EncodeSePtlRaceHistory, EncodeSePtlStaMap, EncodeSePtlTask, EncodeSeQueryPlayerRaceInfo, EncodeSeRaceBaseBuildingInfo, EncodeSeRaceCampBuildingInfo, EncodeSeRaceDetailInfo, EncodeSeRaceEndArenaBaseInfo, EncodeSeRaceEndArenaDetailInfo, EncodeSeRaceEndArenaResult, EncodeSeRaceGameInfo, EncodeSeRaceMapInfo, EncodeSeRaceMapPosInfo, EncodeSeRaceSendInfo, EncodeSeRaceTask, EncodeSeRaceUserHeroInfo, EncodeSeRaceUserInfo, EncodeSeRaceWaitPlayer, EncodeSeRandBoxItem, EncodeSeRC_BeginSelectHero, EncodeSeRC_EncryptKey, EncodeSeRC_GetHeroInfoRet, EncodeSeRC_PingRet, EncodeSeRC_RaceGoldExpPlus, EncodeSeRC_RacePack, EncodeSeRC_RacePlayerLoadEnd, EncodeSeRC_RaceStream, EncodeSeRC_ReconPack, EncodeSeRC_ReconResult, EncodeSeRC_RoomPlayerBaseInfo, EncodeSeRC_SelHeroList, EncodeSeRC_SelHeroMessage, EncodeSeRC_SelHorseList, EncodeSeRC_SelPetList, EncodeSeRC_SetAvatarAck, EncodeSeRC_SetEquipSetAck, EncodeSeRC_ShowNotice, EncodeSeRC_Talk, EncodeSeRC_ValidateRet, EncodeSeRC_ViewPack, EncodeSeRC_ViewPlayerInfo, EncodeSeRC_ViewResult, EncodeSeRoomMember, EncodeSeScoreInfo, EncodeSeSeatBaseInfo, EncodeSeSeatScore, EncodeSeSelHeroInfo, EncodeSeTC_AchieveInfoAck, EncodeSeTC_ActiveAvatarNtf, EncodeSeTC_AskEnterWaitRace, EncodeSeTC_BiVoiceEnterInfo, EncodeSeTC_CancelMatchRep, EncodeSeTC_CreateCharRet, EncodeSeTC_CreateRoomRet, EncodeSeTC_EncryptKey, EncodeSeTC_EquipSchema, EncodeSeTC_ExchangeInit, EncodeSeTC_FriendDel, EncodeSeTC_FriendInit, EncodeSeTC_FriendLadderInfoNtf, EncodeSeTC_FriendRemarkRet, EncodeSeTC_FriendRequestInit, EncodeSeTC_FriendUpdateStatus, EncodeSeTC_GetAchievement, EncodeSeTC_GetRaceHistoryRet, EncodeSeTC_InGameDisconn, EncodeSeTC_InitPlayerInfo, EncodeSeTC_ItemDel, EncodeSeTC_ItemExchangeRet, EncodeSeTC_LadderRankQueryAck, EncodeSeTC_MailOprRet, EncodeSeTC_MatchRaceAddr, EncodeSeTC_NexusFriendCleanRefuseNoticeRes, EncodeSeTC_NexusFriendDetailInfoRes, EncodeSeTC_NexusFriendLimitRes, EncodeSeTC_NexusFriendStatusSync, EncodeSeTC_NotiMatcherPre, EncodeSeTC_NotiMatcherResult, EncodeSeTC_OpenRandBoxRet, EncodeSeTC_PlayerAppear, EncodeSeTC_PlayerDisappear, EncodeSeTC_PlayerGoPos, EncodeSeTC_PlayerMoneyAndDiamond, EncodeSeTC_PlayerNewItem, EncodeSeTC_PlayerOperRep, EncodeSeTC_PlayerValidateRet, EncodeSeTC_PutOnEquipRet, EncodeSeTC_QueryMapTaskListRet, EncodeSeTC_QueryNameRet, EncodeSeTC_QueryNearestRaceInfoRet, EncodeSeTC_QueryRaceBetInfoRet, EncodeSeTC_QueryRaceRoomListRet, EncodeSeTC_QueryRoomListRet, EncodeSeTC_ReceiveMail, EncodeSeTC_RemoveIncompleteRace, EncodeSeTC_ReqMatchRep, EncodeSeTC_ResAchievementCounts, EncodeSeTC_ResAchievementDat, EncodeSeTC_ResIncmpRaceSeatBaseInfo, EncodeSeTC_ResIncompleteRaceList, EncodeSeTC_ResRaceDetailInfo, EncodeSeTC_ResView, EncodeSeTC_ResViewList, EncodeSeTC_RoomInviteNotify, EncodeSeTC_RoomJoinRet, EncodeSeTC_RoomKickSomeoneRet, EncodeSeTC_RoomLeaveRet, EncodeSeTC_RoomMemberNotify, EncodeSeTC_RoomStartRet, EncodeSeTC_RoomSwitchSeatRet, EncodeSeTC_SetActiveAvatarAck, EncodeSeTC_ShopItemGmRep, EncodeSeTC_ShowNotice, EncodeSeTC_SingleMatchConfirm, EncodeSeTC_StartMatchRet, EncodeSeTC_TakeOffEquipRet, EncodeSeTC_TaskQueryListRet, EncodeSeTC_TaskReselRet, EncodeSeTC_TeamChangeSync, EncodeSeTC_TeamLeaderSync, EncodeSeTC_TeamMemberInfoRes, EncodeSeTC_TeamMemberSync, EncodeSeTC_TeamUserStateRes, EncodeSeTC_UpdateMail, EncodeSeTC_UpdateMisc, EncodeSeTC_UserAlterAvatarAndFrameNtf, EncodeSeTC_UserAlterNickNameAck, EncodeSeTC_UserHeroSync, EncodeSeTC_UserRaceMapHeroAck, EncodeSeTC_UserStatusQueryReqRes, EncodeSeTC_ViewResult, EncodeSeTeamMemberBaseInfo, EncodeSeUnlockHeroBaseInfo, EncodeSeUserArchivesInfo, EncodeSeUserBaseAttrInfo, EncodeSeUserHeroSyncInfo, EncodeSeUserRaceMapHeroBase, EncodeSeUserStatusBaseInfo, EncodeSeViewList, EncodeSeWCSC_EncryptKey, EncodeSeWCSC_ViewPack, EncodeSeWCSC_ViewPlayerInfo, EncodeSeWCSC_ViewValidateRet, EncodeSeWCSViewInfo, EncodeSeWSGuanqiaSendInfo, EncodeSeWSRaceSendInfo, EncodeShopItem, Write, WriteByte, WriteChar, WriteDword, WriteFloat, WriteInt, WriteInt3Byte, WriteNetStream, WriteShort, WriteString, WriteStringB, WriteStringValue, WriteValue, WriteWord.
bool SeNetStream::WriteChar(char cValue)
References Write.
Referenced by WriteDBTime.
bool SeNetStream::WriteByte(Byte byValue)
References Write.
Referenced by WriteStringB.
bool SeNetStream::WriteShort(short sValue)
References Write.
Referenced by WriteDBTime.
bool SeNetStream::WriteInt3Byte(int iValue)
References Write.
bool SeNetStream::WriteWord(Word wValue)
References Write.
Referenced by WriteString.
bool SeNetStream::WriteInt(int iValue)
References Write.
bool SeNetStream::WriteFloat(float fValue)
References Write.
bool SeNetStream::WriteDword(unsigned int dwValue)
References Write.
Referenced by TcpServer::ProcessParent_RegisterRet.
bool SeNetStream::WriteString(const char *pcValue)
References Write, WriteWord.
Referenced by EncodeMatchValueStru, EncodeSeCL_PlayerLogin, EncodeSeCL_PlayerLogin_NEW, EncodeSeCL_PlayerSteamLogin, EncodeSeCR_ReplayReport, EncodeSeCR_Talk, EncodeSeCT_CreateChar, EncodeSeCT_CreateRoom, EncodeSeCT_PlayerRename, EncodeSeCT_QueryName, EncodeSeCT_RoomJoin, EncodeSeCT_UserAlterNickNameReq, EncodeSeCT_UserInviteReq, EncodeSeLadderRankInfo, EncodeSeLC_ClientVersion, EncodeSeLC_EncryptKey, EncodeSeLC_GateList, EncodeSeLC_PlayerLoginRet, EncodeSeMatchSelPlayerInfo, EncodeSeMobileInfo, EncodeSeNexusFriendSyncInfo, EncodeSeNexusTeamBaseInfo, EncodeSeNexusTeamMemberInfo, EncodeSeNexusUserBaseInfo, EncodeSeNoticeMatchPlayerInfo, EncodeSeOpenRoomInfo, EncodeSePlayerInfoSeat, EncodeSePtlFriend, EncodeSePtlFriendRequest, EncodeSePtlMail, EncodeSePtlNetAddr, EncodeSePtlRaceHistory, EncodeSeRaceUserInfo, EncodeSeRC_EncryptKey, EncodeSeRC_RaceEndNotifyDown, EncodeSeRC_Talk, EncodeSeRoomMember, EncodeSeTC_BiVoiceEnterInfo, EncodeSeTC_EncryptKey, EncodeSeTC_FriendRemarkRet, EncodeSeTC_GetRaceHistoryRet, EncodeSeTC_InitPlayerInfo, EncodeSeTC_PlayerRename, EncodeSeTC_RoomInviteNotify, EncodeSeTC_ShowNotice, EncodeSeTC_TeamChangeSync, EncodeSeTC_TeamLeaderSync, EncodeSeTC_TeamMemberSync, EncodeSeTeamMemberBaseInfo, EncodeSeUserArchivesInfo, EncodeSeUserArchivesNameInfo, EncodeSeUserBaseAttrInfo, EncodeSeWCSC_EncryptKey.
bool SeNetStream::WriteDBTime(const SeDBTime &rkTime)
References SeDBTime::iDay, SeDBTime::iHour, SeDBTime::iMinute, SeDBTime::iMonth, SeDBTime::iSecond, SeDBTime::iYear, WriteChar, WriteShort.
bool SeNetStream::WriteStringB(const char *pcValue)
References Write, WriteByte.
bool SeNetStream::WriteNetStream(SeNetStream *netStream, int iSize)
References m_pcData, Write.
bool SeNetStream::WriteNetStream(SeNetStream *netStream)
References m_iPos, m_pcData, Write.
bool SeNetStream::WriteValue(int value, int numbit)
References Write.
bool SeNetStream::WriteStringValue(const char *value, int size)
References Write.
Referenced by WriteStringValue.
bool SeNetStream::WriteStringValue(const char *value)
References WriteStringValue.
int SeNetStream::GetSize()
References m_iSize.
const char * SeNetStream::GetAcData()
References m_acData.