LoginServer
char LoginServer::m_acSend[SSD_SEND_SIZE]
Referenced by LoginServer.
char LoginServer::m_acPraseBuf[SSD_PRASER_SIZE]
Referenced by LoginServer.
DWord LoginServer::m_dwTickCount
Referenced by LoginServer, Update.
DWord LoginServer::m_dwCurTime
Referenced by LoginServer, OnNetAccept, PreProcessGL, PreProcessWL, ProcessCL_PlayerLogin, ProcessCL_PlayerLogin_NEW, ProcessGL_AccountLoginFailed, ProcessGL_AccountLoginSuccess, ProcessWL_LoginFailed, ProcessWL_LoginSuccess, Update, UpdateFailed, UpdateLoginPlayer, UpdateLogShow, UpdatePassPlayerNum.
SeLoginConfig LoginServer::m_kConfig
Referenced by GetLogShowType, GetServerID, InitializeNet, LoadConfig, LoadDynamicConfig, OnNetAccept, ProcessGL_RegisterRet, ProcessWL_LoginSuccess, ProcessWL_RegisterRet, UpdateLogShow.
TeNetMgr LoginServer::m_kNetMgr
Referenced by Finialize, Initialize, InitializeNet, OnNetRecv, ProcessCL_PlayerLogin, SendLCData, SendLGData, SendLWData, Update, UpdateFailed, UpdateLoginPlayer.
SeVirtConn * LoginServer::m_pkWSConn
Referenced by GetAreaID, LoadConfig, LoginServer, OnNetAccept, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessWL, ProcessWL_RegisterRet, SendLWData.
SeVirtConn * LoginServer::m_pkGSConn
Referenced by LoadConfig, LoginServer, OnNetAccept, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessGL, ProcessGL_RegisterRet, ProcessWL_RegisterRet, SendLGData.
MapAllPlayer LoginServer::m_kAllPlayer
Referenced by Finialize, GetPlayer, GetPlayerByID, GetStatePlayerNum, OnNetAccept, OnNetDisconnect, OnNetRecv, UpdateLoginPlayer.
MapAllFailed LoginServer::m_kAllFailed
Referenced by OnNetAccept, OnNetDisconnect, UpdateFailed.
MapIPCount LoginServer::m_kIPCount
Referenced by OnNetDisconnect.
int LoginServer::m_iPassPlayerNum
Referenced by LoginServer, OnNetAccept, UpdatePassPlayerNum.
SeLoadInfo LoginServer::m_kLoadInfo
Referenced by SetLoginLogInfo, UpdateLogShow.
LoginServer::LoginServer(void)
References m_acPraseBuf, m_acSend, m_dwCurTime, m_dwTickCount, m_iPassPlayerNum, m_pkGSConn, m_pkWSConn.
LoginServer::~LoginServer(void)
bool LoginServer::Initialize()
References g_kVirtConnMgr, SeVirtConnMgr::Initialize, InitializeNet, LoadConfig, LoadDynamicConfig, m_kNetMgr, SeLogError, sendHeartPack, sendRegPack.
void LoginServer::Update(void)
References g_kVirtConnMgr, m_dwCurTime, m_dwTickCount, m_kNetMgr, SeVirtConnMgr::Update, UpdateFailed, UpdateLoginPlayer, UpdateLogShow, UpdatePassPlayerNum.
void LoginServer::Finialize(void)
References m_kAllPlayer, m_kNetMgr.
void LoginServer::ShowConsoleTitle(int iDTime)
References SeSynMgr::GetNum, GetStatePlayerNum, SPrintf.
SeServerActionResult LoginServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F5, LoadDynamicConfig, SeLogHideTime, SeLogInfo.
void LoginServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, g_kVirtConnMgr, SeNetAddr::iPort, SeVirtConn::kNetAddr, m_pkGSConn, m_pkWSConn, SeVirtConnMgr::OnServerConnected.
void LoginServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeLoginPlayer::acEncryptKey, SeNetAddr::acIP, SeLoginPlayer::dwStateTime, SeVirtConn::eState, SeLoginPlayer::eState, GenEncryptKey, SeLoginConfig::iPassPlayerNum, SeNetAddr::iPort, SeLoginPlayer::kNetAddr, SeLoginPlayer::kSock, LFR_SERVER_BUSY, LFR_SERVER_DISCONNECT, m_dwCurTime, m_iPassPlayerNum, m_kAllFailed, m_kAllPlayer, m_kConfig, m_pkGSConn, m_pkWSConn, SeLogError, SeLogInfo, SendLC_EncryptKey, SendLC_PlayerLoginRet, SLS_WAITING_ACCOUNT, SSD_EN_KEY_LEN, SVCS_REGISTERED.
void LoginServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References SeVirtConn::kSock, m_kAllPlayer, m_kNetMgr, m_pkGSConn, m_pkWSConn, ProcessCLData, ProcessGLData, ProcessWLData, SeLogError.
void LoginServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, g_kVirtConnMgr, SeLoginPlayer::kNetAddr, SeVirtConn::kSock, m_kAllFailed, m_kAllPlayer, m_kIPCount, m_pkGSConn, m_pkWSConn, SeVirtConnMgr::OnServerDisconnect.
bool LoginServer::SendLC_EncryptKey(const char *abyEncryptKey, void *pkReceiver=NULL)
Referenced by OnNetAccept.
bool LoginServer::SendLC_PlayerLoginRet(DWord dwPlayerID, SeLoginReason eReason, DWord dwSessionID, const char *strNickName, void *pkReceiver=NULL)
Referenced by OnNetAccept, ProcessCL_PlayerLogin, ProcessCL_PlayerLogin_NEW, ProcessGL_AccountLoginFailed, ProcessGL_AccountLoginSuccess, ProcessWL_LoginFailed, ProcessWL_LoginSuccess.
bool LoginServer::SendLC_GateList(const char *acIP, int iPort, void *pkReceiver=NULL)
Referenced by ProcessWL_LoginSuccess.
bool LoginServer::SendLC_ClientVersion(DWord main, DWord sub, const char *ver, void *pkReceiver=NULL)
Referenced by ProcessWL_LoginSuccess.
bool LoginServer::SendLC_SteamCheckReturn(SteamCheckResult eResult, void *pkReceiver=NULL)
bool LoginServer::SendLCData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
bool LoginServer::SendLW_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool LoginServer::SendLW_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool LoginServer::SendLW_KickAccount(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessGL_KickAccount.
bool LoginServer::SendLW_AccountLogin(DWord dwPackKey, DWord dwPlayerID, const SePtlAccountInfo &kAccountInfo, void *pkReceiver=NULL)
Referenced by ProcessGL_AccountLoginSuccess.
bool LoginServer::SendLW_AccountWillLogin(DWord dwPlayerID, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by ProcessGL_AccountWillLogin.
bool LoginServer::SendLWData(void *pkData, int iSize, void *pkReceiver)
References CMD_LW_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkWSConn, SVCS_REGISTERED, SeCMD::wCmd.
bool LoginServer::SendLG_Register(DWord dwLoginMagic, DWord dwServerID, DWord dwAreaID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool LoginServer::SendLG_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool LoginServer::SendLG_AccountLogin(DWord dwPackKey, DWord dwVersion, DWord dwIP, bool bForceKick, const char *acAccount, const char *acPassword, void *pkReceiver=NULL)
Referenced by ProcessCL_PlayerLogin.
bool LoginServer::SendLG_PlayerLogin(DWord dwPackKey, DWord dwVersion, DWord dwIP, int iPlatFlag, bool bForceKick, const char *acAccount, DWord dwAccountID, const char *acLoginType, const char *acToken, const char *acMobileInfo, void *pkReceiver=NULL)
Referenced by ProcessCL_PlayerLogin_NEW.
bool LoginServer::SendLG_PlayerTownIndex(DWord dwPlayerID, int iTownIndex, void *pkReceiver=NULL)
Referenced by ProcessWL_PlayerTownIndex.
bool LoginServer::SendLG_PlayerLogout(DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessWL_PlayerLogout.
bool LoginServer::SendLGData(void *pkData, int iSize, void *pkReceiver)
References CMD_LG_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkGSConn, SVCS_REGISTERED, SeCMD::wCmd.
DWord LoginServer::GetServerID()
References SeLoginConfig::dwServerID, m_kConfig.
Referenced by sendRegPack.
DWord LoginServer::GetAreaID()
References SeVirtConn::dwAreaID, m_pkWSConn.
Referenced by sendRegPack.
bool LoginServer::ProcessCLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool LoginServer::PreProcessCL(void *pkData, int iSize, void *pkSender)
References CMD_CL_PLAYERLOGIN, CMD_CL_PLAYERLOGIN_NEW, SeLoginPlayer::eState, SLS_LOGIN_OK, SeCMD::wCmd.
void LoginServer::ProcessCL_PlayerLogin(SeCL_PlayerLogin *pkData, int iSize, void *pkSender)
References SeCL_PlayerLogin::acAccount, SeNetAddr::acIP, SeLoginPlayer::acNickName, SeCL_PlayerLogin::acPassword, SeSynMgr::AddSynOpr, SeCL_PlayerLogin::bForceKick, SeCL_PlayerLogin::dwMSangoMagic, SeLoginPlayer::dwPlayerID, SeLoginPlayer::dwStateTime, SeCL_PlayerLogin::dwVersion, SeLoginPlayer::dwVersion, SeLoginPlayer::eState, g_kSynMgr, GetIPString2DWord, SeSynMgr::GetOutSynOpr, GetPlayerByID, SeLoginPlayer::kNetAddr, SeSynOpr::kSock, SeLoginPlayer::kSock, LFR_ACCOUNT_ERROR, LFR_SERVER_BUSY, LFR_SERVER_DISCONNECT, m_dwCurTime, m_kNetMgr, SAFE_DELETE, SeLogDebug, SeLogError, SendLC_PlayerLoginRet, SendLG_AccountLogin, SLS_WAITING_ACCOUNT, SLS_WAITING_GS, SSD_MAX_ACCOUNT, SSD_MSANGO_MAGIC.
void LoginServer::ProcessCL_PlayerLogin_NEW(SeCL_PlayerLogin_NEW *pkData, int iSize, void *pkSender)
References SeCL_PlayerLogin_NEW::acAccount, SeNetAddr::acIP, SeCL_PlayerLogin_NEW::acLoginType, SeCL_PlayerLogin_NEW::acMobileInfo, SeLoginPlayer::acNickName, SeLoginPlayer::acPlatAccout, SeCL_PlayerLogin_NEW::acToken, SeSynMgr::AddSynOpr, SeCL_PlayerLogin_NEW::bForceKick, SeCL_PlayerLogin_NEW::dwAccountID, SeLoginPlayer::dwPlayerID, SeLoginPlayer::dwStateTime, SeCL_PlayerLogin_NEW::dwVersion, SeLoginPlayer::dwVersion, SeLoginPlayer::eState, g_kSynMgr, GetIPString2DWord, SeSynMgr::GetOutSynOpr, SeCL_PlayerLogin_NEW::iPlatFlag, SeLoginPlayer::kNetAddr, SeSynOpr::kSock, SeLoginPlayer::kSock, LFR_SERVER_DISCONNECT, m_dwCurTime, SAFE_DELETE, SeLogError, SendLC_PlayerLoginRet, SendLG_PlayerLogin, SLS_WAITING_ACCOUNT, SLS_WAITING_GS, StrCpy.
void LoginServer::ProcessCL_PlayerSteamLogin(SeCL_PlayerSteamLogin *pkData, int iSize, void *pkSender)
bool LoginServer::ProcessWLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool LoginServer::PreProcessWL(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkWSConn.
void LoginServer::ProcessWL_RegisterRet(SeWL_RegisterRet *pkData, int iSize, void *pkSender)
References SeVirtConn::dwAreaID, SeWL_RegisterRet::dwAreaID, SeLoginConfig::dwServerID, SeWL_RegisterRet::eRegisterRet, SeVirtConn::eState, GetID2Str, m_kConfig, m_pkGSConn, m_pkWSConn, SeLogError, SeLogInfo, SRR_REPEAT, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_NULL, SVCS_REGISTERED.
void LoginServer::ProcessWL_HeartPackageRet(SeWL_HeartPackageRet *pkData, int iSize, void *pkSender)
void LoginServer::ProcessWL_LoginSuccess(SeWL_LoginSuccess *pkData, int iSize, void *pkSender)
References SeLoginConfig::acClientVerInfo, SeNetAddr::acIP, SeLoginPlayer::acNickName, SeLoginPlayer::acPlatAccout, SeWL_LoginSuccess::akGateList, ASLT_WSQUERY, SeLoginConfig::dwClientMainVer, SeLoginConfig::dwClientSubVer, SeWL_LoginSuccess::dwPackKey, SeLoginPlayer::dwPlayerID, SeWL_LoginSuccess::dwSessionID, SeLoginPlayer::dwStateTime, SeLoginPlayer::eState, g_kSynMgr, GetLogShowType, SeSynMgr::GetOutSynOpr, GetPlayer, SeWL_LoginSuccess::iNum, SeNetAddr::iPort, SeSynOpr::kSock, SeLoginPlayer::kSock, LFR_SUCCESS, m_dwCurTime, m_kConfig, SAFE_DELETE, SeLogInfo, SendLC_ClientVersion, SendLC_GateList, SendLC_PlayerLoginRet, SetLoginLogInfo, SLS_LOGIN_OK.
void LoginServer::ProcessWL_LoginFailed(SeWL_LoginFailed *pkData, int iSize, void *pkSender)
References SeLoginPlayer::acNickName, SeWL_LoginFailed::dwPackKey, SeLoginPlayer::dwPlayerID, SeLoginPlayer::dwStateTime, SeWL_LoginFailed::eReason, SeLoginPlayer::eState, g_kSynMgr, SeSynMgr::GetOutSynOpr, GetPlayer, SeSynOpr::kSock, SeLoginPlayer::kSock, LFR_WS_DB_ERROR, m_dwCurTime, SAFE_DELETE, SeLogInfo, SendLC_PlayerLoginRet, SLS_WAITING_ACCOUNT.
void LoginServer::ProcessWL_PlayerTownIndex(SeWL_PlayerTownIndex *pkData, int iSize, void *pkSender)
References SeWL_PlayerTownIndex::dwPlayerID, SeWL_PlayerTownIndex::iTownIndex, SendLG_PlayerTownIndex.
void LoginServer::ProcessWL_PlayerLogout(SeWL_PlayerLogout *pkData, int iSize, void *pkSender)
References SeWL_PlayerLogout::dwPlayerID, SendLG_PlayerLogout.
void LoginServer::ProcessWL_PlayerUpdateOnlineTime(SeWL_PlayerUpdateOnlineTime *pkData, int iSize, void *pkSender)
bool LoginServer::ProcessGLData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool LoginServer::PreProcessGL(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkGSConn.
void LoginServer::ProcessGL_RegisterRet(SeGL_RegisterRet *pkData, int iSize, void *pkSender)
References SeLoginConfig::dwServerID, SeGL_RegisterRet::eRegisterRet, SeVirtConn::eState, GetID2Str, m_kConfig, m_pkGSConn, SeLogError, SeLogInfo, SRR_REPEAT, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void LoginServer::ProcessGL_HeartPackageRet(SeGL_HeartPackageRet *pkData, int iSize, void *pkSender)
void LoginServer::ProcessGL_KickAccount(SeGL_KickAccount *pkData, int iSize, void *pkSender)
References SeGL_KickAccount::dwPlayerID, SeLogDebug, SendLW_KickAccount.
void LoginServer::ProcessGL_AccountLoginSuccess(SeGL_AccountLoginSuccess *pkData, int iSize, void *pkSender)
References SePtlAccountInfo::acAccount, SeLoginPlayer::acNickName, SePtlAccountInfo::acNickName, SeSynMgr::AddSynOpr, ASLT_GSQUERY, ASLT_SUCCESS, SePtlAccountInfo::dwLoginVersion, SeGL_AccountLoginSuccess::dwPackKey, SeGL_AccountLoginSuccess::dwPlayerID, SeLoginPlayer::dwPlayerID, SeLoginPlayer::dwStateTime, SeLoginPlayer::dwVersion, SeLoginPlayer::eState, g_kSynMgr, GetLogShowType, SeSynMgr::GetOutSynOpr, GetPlayer, SeGL_AccountLoginSuccess::kAccountInfo, SeSynOpr::kSock, SeLoginPlayer::kSock, LFR_SERVER_DISCONNECT, m_dwCurTime, SAFE_DELETE, SeLogError, SeLogInfo, SendLC_PlayerLoginRet, SendLW_AccountLogin, SetLoginLogInfo, SLS_WAITING_WS, StrCpy.
void LoginServer::ProcessGL_AccountLoginFailed(SeGL_AccountLoginFailed *pkData, int iSize, void *pkSender)
References SeLoginPlayer::acNickName, SeLoginPlayer::acPlatAccout, ASLT_GSQUERY, ASLT_OTHERERROR, SeGL_AccountLoginFailed::dwPackKey, SeLoginPlayer::dwPlayerID, SeLoginPlayer::dwStateTime, SeGL_AccountLoginFailed::eReason, g_kSynMgr, GetLogShowType, SeSynMgr::GetOutSynOpr, GetPlayer, SeGL_AccountLoginFailed::iParam1, SeSynOpr::kSock, SeLoginPlayer::kSock, m_dwCurTime, SAFE_DELETE, SeLogError, SeLogInfo, SendLC_PlayerLoginRet, SetLoginLogInfo.
void LoginServer::ProcessGL_AccountWillLogin(SeGL_AccountWillLogin *pkData, int iSize, void *pkSender)
References SeGL_AccountWillLogin::dwAreaID, SeGL_AccountWillLogin::dwPlayerID, SeLogDebug, SendLW_AccountWillLogin.
LoginServer::LoginServer(void)
LoginServer::~LoginServer(void)
bool LoginServer::Initialize()
void LoginServer::Update(void)
void LoginServer::Finialize(void)
void LoginServer::ShowConsoleTitle(int iDTime)
SeServerActionResult LoginServer::ExecuteAction(SeServerActionIndex eActionIndex)
virtual void LoginServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
virtual void LoginServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
virtual void LoginServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
virtual void LoginServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
bool LoginServer::SendLC_EncryptKey(const char *abyEncryptKey, void *pkReceiver=NULL)
bool LoginServer::SendLC_PlayerLoginRet(DWord dwPlayerID, SeLoginReason eReason, DWord dwSessionID, const char *strNickName, void *pkReceiver=NULL)
bool LoginServer::SendLC_GateList(const char *acIP, int iPort, void *pkReceiver=NULL)
bool LoginServer::SendLC_ClientVersion(DWord main, DWord sub, const char *ver, void *pkReceiver=NULL)
bool LoginServer::SendLC_SteamCheckReturn(SteamCheckResult eResult, void *pkReceiver=NULL)
bool LoginServer::SendLCData(void *pkData, int iSize, void *pkReceiver)
bool LoginServer::SendLW_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
bool LoginServer::SendLW_HeartPackage(void *pkReceiver=NULL)
bool LoginServer::SendLW_KickAccount(DWord dwPlayerID, void *pkReceiver=NULL)
bool LoginServer::SendLW_AccountLogin(DWord dwPackKey, DWord dwPlayerID, const SePtlAccountInfo &kAccountInfo, void *pkReceiver=NULL)
bool LoginServer::SendLW_AccountWillLogin(DWord dwPlayerID, DWord dwAreaID, void *pkReceiver=NULL)
bool LoginServer::SendLWData(void *pkData, int iSize, void *pkReceiver)
bool LoginServer::SendLG_Register(DWord dwLoginMagic, DWord dwServerID, DWord dwAreaID, void *pkReceiver=NULL)
bool LoginServer::SendLG_HeartPackage(void *pkReceiver=NULL)
bool LoginServer::SendLG_AccountLogin(DWord dwPackKey, DWord dwVersion, DWord dwIP, bool bForceKick, const char *acAccount, const char *acPassword, void *pkReceiver=NULL)
bool LoginServer::SendLG_PlayerLogin(DWord dwPackKey, DWord dwVersion, DWord dwIP, int iPlatFlag, bool bForceKick, const char *acAccount, DWord dwAccountID, const char *acLoginType, const char *acToken, const char *acMobileInfo, void *pkReceiver=NULL)
bool LoginServer::SendLG_PlayerTownIndex(DWord dwPlayerID, int iTownIndex, void *pkReceiver=NULL)
bool LoginServer::SendLG_PlayerLogout(DWord dwPlayerID, void *pkReceiver=NULL)
bool LoginServer::SendLGData(void *pkData, int iSize, void *pkReceiver)
DWord LoginServer::GetServerID()
DWord LoginServer::GetAreaID()
bool LoginServer::ProcessCLData(void *pkData, int iSize, void *pkSender=NULL)
bool LoginServer::PreProcessCL(void *pkData, int iSize, void *pkSender)
void LoginServer::ProcessCL_PlayerLogin(SeCL_PlayerLogin *pkData, int iSize, void *pkSender)
void LoginServer::ProcessCL_PlayerLogin_NEW(SeCL_PlayerLogin_NEW *pkData, int iSize, void *pkSender)
void LoginServer::ProcessCL_PlayerSteamLogin(SeCL_PlayerSteamLogin *pkData, int iSize, void *pkSender)
bool LoginServer::ProcessWLData(void *pkData, int iSize, void *pkSender=NULL)
bool LoginServer::PreProcessWL(void *pkData, int iSize, void *pkSender)
void LoginServer::ProcessWL_RegisterRet(SeWL_RegisterRet *pkData, int iSize, void *pkSender)
void LoginServer::ProcessWL_HeartPackageRet(SeWL_HeartPackageRet *pkData, int iSize, void *pkSender)
void LoginServer::ProcessWL_LoginSuccess(SeWL_LoginSuccess *pkData, int iSize, void *pkSender)
void LoginServer::ProcessWL_LoginFailed(SeWL_LoginFailed *pkData, int iSize, void *pkSender)
void LoginServer::ProcessWL_PlayerTownIndex(SeWL_PlayerTownIndex *pkData, int iSize, void *pkSender)
void LoginServer::ProcessWL_PlayerLogout(SeWL_PlayerLogout *pkData, int iSize, void *pkSender)
void LoginServer::ProcessWL_PlayerUpdateOnlineTime(SeWL_PlayerUpdateOnlineTime *pkData, int iSize, void *pkSender)
bool LoginServer::ProcessGLData(void *pkData, int iSize, void *pkSender=NULL)
bool LoginServer::PreProcessGL(void *pkData, int iSize, void *pkSender)
void LoginServer::ProcessGL_RegisterRet(SeGL_RegisterRet *pkData, int iSize, void *pkSender)
void LoginServer::ProcessGL_HeartPackageRet(SeGL_HeartPackageRet *pkData, int iSize, void *pkSender)
void LoginServer::ProcessGL_KickAccount(SeGL_KickAccount *pkData, int iSize, void *pkSender)
void LoginServer::ProcessGL_AccountLoginSuccess(SeGL_AccountLoginSuccess *pkData, int iSize, void *pkSender)
void LoginServer::ProcessGL_AccountLoginFailed(SeGL_AccountLoginFailed *pkData, int iSize, void *pkSender)
void LoginServer::ProcessGL_AccountWillLogin(SeGL_AccountWillLogin *pkData, int iSize, void *pkSender)
bool LoginServer::LoadConfig(const char *pcFile)
References SeVirtConnMgr::AddServerConn, SeLoginConfig::dwServerID, g_kVirtConnMgr, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeLoginConfig::kLocalServer, SeConfig::Load, m_kConfig, m_pkGSConn, m_pkWSConn, SeLogError, SeLogInfo, SSI_GS, SSI_WS, SVCS_NULL.
Referenced by Initialize.
bool LoginServer::LoadDynamicConfig(void)
References SeLoginConfig::acClientVerInfo, SeLoginConfig::dwClientMainVer, SeLoginConfig::dwClientSubVer, SeConfig::GetValue, SeLoginConfig::iLoginErrorCount, SeLoginConfig::iLoginErrorTime, SeLoginConfig::iLogShowType, SeLoginConfig::iPassPlayerNum, SeLoginConfig::iSameIPConnect, SeConfig::Load, m_kConfig, SeLogError, StrCpy.
Referenced by ExecuteAction, Initialize.
bool LoginServer::InitializeNet(void)
References SeNetAddr::acIP, CLIENT_BUFFER_SIZE, SeNetAddr::iPort, SeLoginConfig::kLocalServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo.
Referenced by Initialize.
void LoginServer::UpdateFailed(void)
References FAILED_TIMEOUT, m_dwCurTime, m_kAllFailed, m_kNetMgr.
Referenced by Update.
void LoginServer::UpdateLoginPlayer(void)
References CONNECT_TIMEOUT, SeLoginPlayer::dwStateTime, SeLoginPlayer::eState, m_dwCurTime, m_kAllPlayer, m_kNetMgr, SAFE_DELETE, SLS_LOGIN_OK, SLS_WAITING_ACCOUNT, SLS_WAITING_GS, SLS_WAITING_WS, WAIT_SERVER_TIMEOUT.
Referenced by Update.
void LoginServer::UpdatePassPlayerNum(void)
References m_dwCurTime, m_iPassPlayerNum.
Referenced by Update.
void LoginServer::UpdateLogShow(void)
References SeLoadInfo::dwOtherFailedCount, SeLoadInfo::dwPasswordFailedCount, SeLoadInfo::dwQueryGSCount, SeLoadInfo::dwQueryWSCount, SeLoadInfo::dwSuccessCount, SeLoadInfo::GetGSAvgTime, SeLoadInfo::GetWSAvgTime, SeLoginConfig::iLogShowType, m_dwCurTime, m_kConfig, m_kLoadInfo, SeLoadInfo::NeedShow, SeLoadInfo::ReSet, SeLogInfo.
Referenced by Update.
void LoginServer::SetLoginLogInfo(SeAddLogInfoType eType, DWord dwCount, DWord dwParam=0)
References ASLT_GSQUERY, ASLT_OTHERERROR, ASLT_PWERROR, ASLT_SUCCESS, ASLT_WSQUERY, SeLoadInfo::dwOtherFailedCount, SeLoadInfo::dwPasswordFailedCount, SeLoadInfo::dwQueryGSCount, SeLoadInfo::dwQueryGSSumTime, SeLoadInfo::dwQueryWSCount, SeLoadInfo::dwQueryWSSumTime, SeLoadInfo::dwSuccessCount, m_kLoadInfo.
Referenced by ProcessGL_AccountLoginFailed, ProcessGL_AccountLoginSuccess, ProcessWL_LoginSuccess.
int LoginServer::GetLogShowType(void)
References SeLoginConfig::iLogShowType, m_kConfig.
Referenced by ProcessGL_AccountLoginFailed, ProcessGL_AccountLoginSuccess, ProcessWL_LoginSuccess.
SeLoginPlayer * LoginServer::GetPlayer(HSock kSock)
References m_kAllPlayer.
Referenced by ProcessGL_AccountLoginFailed, ProcessGL_AccountLoginSuccess, ProcessWL_LoginFailed, ProcessWL_LoginSuccess.
const SeLoginPlayer * LoginServer::GetPlayerByID(DWord dwPlayerID)
References SeLoginPlayer::dwPlayerID, m_kAllPlayer.
Referenced by ProcessCL_PlayerLogin.
void LoginServer::GetStatePlayerNum(int &iWaitAccount, int &iWaitGS, int &iWaitWS, int &iOK)
References SeLoginPlayer::eState, m_kAllPlayer, SLS_LOGIN_OK, SLS_WAITING_ACCOUNT, SLS_WAITING_GS, SLS_WAITING_WS.
Referenced by ShowConsoleTitle.
bool LoginServer::LoadConfig(const char *pcFile)
bool LoginServer::LoadDynamicConfig(void)
bool LoginServer::InitializeNet(void)
void LoginServer::UpdateFailed(void)
void LoginServer::UpdateLoginPlayer(void)
void LoginServer::UpdatePassPlayerNum(void)
void LoginServer::UpdateLogShow(void)
void LoginServer::SetLoginLogInfo(SeAddLogInfoType eType, DWord dwCount, DWord dwParam=0)
int LoginServer::GetLogShowType(void)
SeLoginPlayer* LoginServer::GetPlayer(HSock kSock)
const SeLoginPlayer* LoginServer::GetPlayerByID(DWord dwPlayerID)
void LoginServer::GetStatePlayerNum(int &iWaitAccount, int &iWaitGS, int &iWaitWS, int &iOK)