SeVirtConnMgr
typedef bool(* SeVirtConnMgr::funSendPack)(int))(int)
TeNetMgr* SeVirtConnMgr::m_pkNetMgr
Referenced by Connect, HeartBeat, Initialize, SeVirtConnMgr, Update, UpdateClientConn.
SeTimer SeVirtConnMgr::m_kTimer
Referenced by SeVirtConnMgr, Update.
funSendPack SeVirtConnMgr::m_pkFunReg
Referenced by Initialize, Register, SeVirtConnMgr.
funSendPack SeVirtConnMgr::m_pkFunHeart
Referenced by HeartBeat, Initialize, SeVirtConnMgr.
SeVirtConn* SeVirtConnMgr::m_akServerConn[SSI_NUM][SSI_NUM]
Referenced by AddServerConn, OnServerConnected, SeVirtConnMgr, UpdateServerConn.
MSock2Conn SeVirtConnMgr::m_akClientConn[SSI_NUM][SSI_NUM]
Referenced by GetClientConnByAreaID, GetClientConnByID, GetClientConnByIndex, GetClientConnBySock, OnClientDisconnect, OnClientRegister.
MSock2Conn SeVirtConnMgr::m_kMAllClientConn
Referenced by AddClientConn, GetClientConnBySock, OnClientDisconnect, OnClientRegister, UpdateClientConn.
SeVirtConnMgr::SeVirtConnMgr()
References m_akServerConn, m_kTimer, m_pkFunHeart, m_pkFunReg, m_pkNetMgr, SeTimer::SetInterValue, SSI_NUM.
SeVirtConnMgr::~SeVirtConnMgr()
bool SeVirtConnMgr::Initialize(TeNetMgr *pkNetMgr, void *pFunSendReg, void *pFunSendHeart)
References m_pkFunHeart, m_pkFunReg, m_pkNetMgr.
Referenced by GlobalServer::Initialize, LoginServer::Initialize, HttpServer::Initialize, WorldServer::Initialize, MatchServer::Initialize, WatchServer::CWatchServer::InitializeNet, NexusServer::InitializeNetEx, RaceServer::InitializeNetEx.
void SeVirtConnMgr::Update(DWord dwCurTime)
References SeTimer::IsPassed, m_kTimer, m_pkNetMgr, SeTimer::Update, UpdateClientConn, UpdateServerConn.
Referenced by GlobalServer::Update, LoginServer::Update, BackendServer::Update, HttpServer::Update, NexusServer::Update, WorldServer::Update, WatchServer::CWatchServer::Update, MatchServer::Update, RaceServer::Update.
void SeVirtConnMgr::Finialize(void)
SeVirtConn * SeVirtConnMgr::AddServerConn(SeServerIdx eIndex, SeNetAddr &rkAddr, int iBufferLen, SeVirtConnState eState=SVCS_CAN_CONNECT)
References SeVirtConn::eIndex, SeVirtConn::eState, SeVirtConn::iBufferLen, SeNetAddr::IsEmpty, SeVirtConn::kNetAddr, m_akServerConn, SSI_NUM.
Referenced by WatchServer::CWatchServer::InitializeNet, RaceServer::InitializeNetEx, LoginServer::LoadConfig, HttpServer::LoadConfig, MatchServer::LoadConfig, NexusServer::LoadConfig, WorldServer::LoadConfig.
void SeVirtConnMgr::OnServerConnected(const HSock &rkSock, SeVirtConn *pkConn)
References SeNetAddr::acIP, SeVirtConn::eIndex, SeVirtConn::eState, GetServerNameByIndex, SeVirtConn::HasValidIndex, SeNetAddr::iPort, SeVirtConn::kNetAddr, SeVirtConn::kSock, m_akServerConn, SeLogError, SeLogInfo, SVCS_CAN_CONNECT.
Referenced by LoginServer::OnNetConnected, HttpServer::OnNetConnected, NexusServer::OnNetConnected, WatchServer::CWatchServer::OnNetConnected, MatchServer::OnNetConnected, RaceServer::OnNetConnected, WorldServer::OnNetConnected.
void SeVirtConnMgr::OnServerDisconnect(SeVirtConn *pkConn)
References SeNetAddr::acIP, SeVirtConn::dwStateTime, SeVirtConn::eIndex, SeVirtConn::eState, GetServerNameByIndex, SeNetAddr::iPort, SeVirtConn::kNetAddr, SeVirtConn::kSock, SeLogError, SVCS_CAN_CONNECT.
Referenced by LoginServer::OnNetDisconnect, HttpServer::OnNetDisconnect, NexusServer::OnNetDisconnect, WatchServer::CWatchServer::OnNetDisconnect, MatchServer::OnNetDisconnect, RaceServer::OnNetDisconnect, WorldServer::OnNetDisconnect.
void SeVirtConnMgr::AddClientConn(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeVirtConn::eState, SeNetAddr::iPort, SeVirtConn::kNetAddr, SeVirtConn::kSock, m_kMAllClientConn, SVCS_NULL.
Referenced by GlobalServer::OnNetAccept.
void SeVirtConnMgr::OnClientDisconnect(const HSock &rkSock)
References SeNetAddr::acIP, SeVirtConn::dwAreaID, SeVirtConn::dwServerID, SeVirtConn::eIndex, GetID2Str, GetServerNameByIndex, SeNetAddr::iPort, SeVirtConn::kNetAddr, SeVirtConn::kSock, m_akClientConn, m_kMAllClientConn, SeLogError, SSI_NUM.
Referenced by GlobalServer::OnNetDisconnect.
bool SeVirtConnMgr::OnClientRegister(SeVirtConn *pkConn, SeServerIdx eIndex, DWord dwServerID, DWord dwAreaID)
References CHECK_SERVER_INDEX, SeVirtConn::dwAreaID, SeVirtConn::dwServerID, SeVirtConn::eIndex, SeVirtConn::eState, SeVirtConn::kSock, m_akClientConn, m_kMAllClientConn, SVCS_REGISTERED.
Referenced by GlobalServer::ProcessHS_Register, GlobalServer::ProcessLG_Register.
SeVirtConn * SeVirtConnMgr::GetClientConnByID(SeServerIdx eIndex, DWord dwServerID)
References CHECK_SERVER_INDEX, SeVirtConn::dwServerID, m_akClientConn.
Referenced by GlobalServer::ProcessLG_Register.
SeVirtConn * SeVirtConnMgr::GetClientConnByAreaID(SeServerIdx eIndex, DWord dwAreaID)
References CHECK_SERVER_INDEX, SeVirtConn::dwAreaID, m_akClientConn.
Referenced by GlobalServer::OnLoginQueryRet.
SeVirtConn * SeVirtConnMgr::GetClientConnBySock(SeServerIdx eIndex, const HSock &rkSock)
References CHECK_SERVER_INDEX, m_akClientConn.
Referenced by GlobalServer::OnLoginQueryRet, GlobalServer::OnNetRecv, GlobalServer::ProcessDB_AccountQuery, GlobalServer::ProcessHS_DHAccountLoginRet.
SeVirtConn * SeVirtConnMgr::GetClientConnBySock(const HSock &rkSock)
References m_kMAllClientConn.
SeVirtConn * SeVirtConnMgr::GetClientConnByIndex(SeServerIdx eIndex)
References CHECK_SERVER_INDEX, SeVirtConn::eState, m_akClientConn, SVCS_REGISTERED.
Referenced by GlobalServer::ProcessLG_PlayerLogin.
void SeVirtConnMgr::UpdateServerConn(DWord dwCurTime)
References Connect, SeVirtConn::eState, HeartBeat, SeVirtConn::kSock, m_akServerConn, Register, SSI_NUM, SVCS_REGISTERED.
Referenced by Update.
void SeVirtConnMgr::UpdateClientConn(DWord dwCurTime)
References SeNetAddr::acIP, SeVirtConn::dwLastRecvTime, SeVirtConn::dwStateTime, SeVirtConn::eIndex, SeVirtConn::eState, GetServerNameByIndex, SeNetAddr::iPort, SeVirtConn::kNetAddr, SeVirtConn::kSock, m_kMAllClientConn, m_pkNetMgr, SeLogError, SVCS_REGISTERED.
Referenced by Update.
void SeVirtConnMgr::Connect(SeVirtConn *pkConn)
References SeNetAddr::acIP, SeVirtConn::eIndex, SeVirtConn::eState, GetServerNameByIndex, SeVirtConn::iBufferLen, SeNetAddr::iPort, SeVirtConn::kNetAddr, m_pkNetMgr, SeLogError, SVCS_CONNECTING.
Referenced by UpdateServerConn.
void SeVirtConnMgr::Register(DWord dwCurTime, SeVirtConn *pkConn)
References SeVirtConn::dwStateTime, SeVirtConn::eIndex, GetServerNameByIndex, m_pkFunReg, SeLogError.
Referenced by UpdateServerConn.
void SeVirtConnMgr::HeartBeat(DWord dwCurTime, SeVirtConn *pkConn)
References SeVirtConn::dwLastRecvTime, SeVirtConn::dwStateTime, SeVirtConn::eIndex, GetServerNameByIndex, SeVirtConn::kSock, m_pkFunHeart, m_pkNetMgr, SeLogError.
Referenced by UpdateServerConn.