SeXmlVisitor
virtual SeXmlVisitor::~SeXmlVisitor()
virtual bool SeXmlVisitor::VisitEnter(const SeXmlDocument &)
Visit a document.
Referenced by SeXmlElement::Accept, SeXmlDocument::Accept.
virtual bool SeXmlVisitor::VisitExit(const SeXmlDocument &)
Visit a document.
Referenced by SeXmlElement::Accept, SeXmlDocument::Accept.
virtual bool SeXmlVisitor::VisitEnter(const SeXmlElement &, const SeXmlAttribute *)
Visit an element.
virtual bool SeXmlVisitor::VisitExit(const SeXmlElement &)
Visit an element.
virtual bool SeXmlVisitor::Visit(const SeXmlDeclaration &)
Visit a declaration.
Referenced by SeXmlComment::Accept, SeXmlText::Accept, SeXmlDeclaration::Accept, SeXmlUnknown::Accept.
virtual bool SeXmlVisitor::Visit(const SeXmlText &)
Visit a text node.
virtual bool SeXmlVisitor::Visit(const SeXmlComment &)
Visit a comment node.
virtual bool SeXmlVisitor::Visit(const SeXmlUnknown &)
Visit an unknown node.