SeXmlPrinter
int SeXmlPrinter::depth
Referenced by DoIndent, VisitEnter, VisitExit.
bool SeXmlPrinter::simpleTextPrint
Referenced by Visit, VisitEnter, VisitExit.
SeXml_STRING SeXmlPrinter::buffer
Referenced by CStr, DoIndent, DoLineBreak, Size, Str, Visit, VisitEnter, VisitExit.
SeXml_STRING SeXmlPrinter::indent
Referenced by DoIndent, Indent, SetIndent, SetStreamPrinting.
SeXml_STRING SeXmlPrinter::lineBreak
Referenced by DoLineBreak, LineBreak, SetLineBreak, SetStreamPrinting.
SeXmlPrinter::SeXmlPrinter()
bool SeXmlPrinter::VisitEnter(const SeXmlDocument &doc)
Visit a document.
bool SeXmlPrinter::VisitExit(const SeXmlDocument &doc)
Visit a document.
bool SeXmlPrinter::VisitEnter(const SeXmlElement &element, const SeXmlAttribute *firstAttribute)
Visit an element.
References buffer, SeXmlText::CDATA, depth, DoIndent, DoLineBreak, SeXmlNode::FirstChild, SeXmlNode::LastChild, SeXmlAttribute::Next, simpleTextPrint, SeXmlNode::ToText, SeXmlNode::Value.
bool SeXmlPrinter::VisitExit(const SeXmlElement &element)
Visit an element.
References buffer, depth, DoIndent, DoLineBreak, SeXmlNode::FirstChild, simpleTextPrint, SeXmlNode::Value.
bool SeXmlPrinter::Visit(const SeXmlDeclaration &declaration)
Visit a declaration.
References buffer, DoIndent, DoLineBreak, SeXmlDeclaration::Print.
bool SeXmlPrinter::Visit(const SeXmlText &text)
Visit a text node.
References buffer, SeXmlText::CDATA, DoIndent, DoLineBreak, SeXmlBase::EncodeString, SeXml_STRING, simpleTextPrint, SeXmlNode::Value, SeXmlNode::ValueTStr.
bool SeXmlPrinter::Visit(const SeXmlComment &comment)
Visit a comment node.
References buffer, DoIndent, DoLineBreak, SeXmlNode::Value.
bool SeXmlPrinter::Visit(const SeXmlUnknown &unknown)
Visit an unknown node.
References buffer, DoIndent, DoLineBreak, SeXmlNode::Value.
void SeXmlPrinter::SetIndent(const char *_indent)
Set the indent characters for printing. By default 4 spaces but tab () is also useful, or null/empty string for no indentation.
References indent.
const char* SeXmlPrinter::Indent()
Query the indention string.
References indent.
void SeXmlPrinter::SetLineBreak(const char *_lineBreak)
Set the line breaking string. By default set to newline ( ). Some operating systems prefer other characters, or can be set to the null/empty string for no indenation.
References lineBreak.
const char* SeXmlPrinter::LineBreak()
Query the current line breaking string.
References lineBreak.
void SeXmlPrinter::SetStreamPrinting()
Switch over to "stream printing" which is the most dense formatting without linebreaks. Common when the XML is needed for network transmission.
References indent, lineBreak.
Referenced by operator<<.
const char* SeXmlPrinter::CStr()
Return the result.
References buffer.
size_t SeXmlPrinter::Size()
Return the length of the result string.
References buffer.
const std::string& SeXmlPrinter::Str()
Return the result.
References buffer.
Referenced by operator<<.
void SeXmlPrinter::DoIndent()
References buffer, depth, indent.
Referenced by Visit, VisitEnter, VisitExit.
void SeXmlPrinter::DoLineBreak()
References buffer, lineBreak.
Referenced by Visit, VisitEnter, VisitExit.