IndexofferTableMgr
std::map<unsigned int,IndexofferTable*> IndexofferTableMgr::m_kIndexofferTableMap
Referenced by FillData, GetIndexofferTable, GetIndexofferTableMap, GetIndexofferTableVec, ~IndexofferTableMgr.
IndexofferTableMgr * IndexofferTableMgr::m_pkIndexofferTableMgr
Referenced by Get, ReLoad.
IndexofferTableMgr * IndexofferTableMgr::Get()
References IndexofferTableMgr, m_pkIndexofferTableMgr.
Referenced by ReLoad.
IndexofferTableMgr * IndexofferTableMgr::ReLoad()
References Get, m_pkIndexofferTableMgr.
IndexofferTableMgr::IndexofferTableMgr()
References Load.
Referenced by Get.
IndexofferTableMgr::~IndexofferTableMgr()
References m_kIndexofferTableMap.
const IndexofferTable * IndexofferTableMgr::GetIndexofferTable(unsigned int iTypeID)
References m_kIndexofferTableMap.
const std::map< unsigned int, IndexofferTable * > & IndexofferTableMgr::GetIndexofferTableMap()
References m_kIndexofferTableMap.
TableResArray IndexofferTableMgr::GetIndexofferTableVec()
References m_kIndexofferTableMap, TableResArray::pushBack.
bool IndexofferTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by IndexofferTableMgr.
void IndexofferTableMgr::FillData(IndexofferTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, IndexofferTable::iDamaged, IndexofferTable::iHurt, IndexofferTable::iTreatment, m_kIndexofferTableMap, IndexofferTable::uiLocation, IndexofferTable::uiTypeID.
Referenced by Load.