VideoTagTableMgr
std::map<unsigned int,VideoTagTable*> VideoTagTableMgr::m_kVideoTagTableMap
Referenced by FillData, GetVideoTagTable, GetVideoTagTableMap, GetVideoTagTableVec, ~VideoTagTableMgr.
VideoTagTableMgr * VideoTagTableMgr::m_pkVideoTagTableMgr
Referenced by Get, ReLoad.
VideoTagTableMgr * VideoTagTableMgr::Get()
References m_pkVideoTagTableMgr, VideoTagTableMgr.
Referenced by TableMgr::LoadTable, ReLoad.
VideoTagTableMgr * VideoTagTableMgr::ReLoad()
References Get, m_pkVideoTagTableMgr.
Referenced by TableMgr::ReloadTable.
VideoTagTableMgr::VideoTagTableMgr()
References Load.
Referenced by Get.
VideoTagTableMgr::~VideoTagTableMgr()
References m_kVideoTagTableMap.
const VideoTagTable * VideoTagTableMgr::GetVideoTagTable(unsigned int iTypeID)
References m_kVideoTagTableMap.
const std::map< unsigned int, VideoTagTable * > & VideoTagTableMgr::GetVideoTagTableMap()
References m_kVideoTagTableMap.
TableResArray VideoTagTableMgr::GetVideoTagTableVec()
References m_kVideoTagTableMap, TableResArray::pushBack.
bool VideoTagTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by VideoTagTableMgr.
void VideoTagTableMgr::FillData(VideoTagTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, VideoTagTable::iTimePre, m_kVideoTagTableMap, VideoTagTable::uiContentProperty, VideoTagTable::uiRecordType, VideoTagTable::uiTagCondition, VideoTagTable::uiTagType, VideoTagTable::uiTypeID.
Referenced by Load.