CPerformanceTimingMgr
CPerformanceTimingMgr * CPerformanceTimingMgr::m_pMgr
Referenced by GetInstacne, SetInstance.
virtual class IPerformaceTiming* CPerformanceTimingMgr::MutiInstance()=0
Referenced by CPerformanceTiming::Instance.
virtual class IPerformaceTiming* CPerformanceTimingMgr::MutiInstanceQuick()=0
Referenced by CPerformanceTiming::InstanceQuick.
CPerformanceTimingMgr * CPerformanceTimingMgr::GetInstacne()
References m_pMgr.
Referenced by CPerformanceTiming::Instance, CPerformanceTiming::InstanceQuick.
void CPerformanceTimingMgr::SetInstance(CPerformanceTimingMgr *pMgr)
References m_pMgr.
Referenced by RaceServer::InitializeRaceService.