SeBase64
@49
Pad character.
uchar SeBase64::base64_encode[][]
Base64 Alphabet encoder-string.
Referenced by Decode, Encode.
SeBase64::SeBase64()
size_t SeBase64::CalcBufferSize(size_t length) const
Calculate buffer size requirement length size of binary data in bytes size of required buffer including NULL
References BASE64_NCHAR.
bool SeBase64::IsBase64Char(uchar c) const
Test if a character is a valid Base64 alphabet c character to test true if valid Base64 alphabet
References Decode.
uchar SeBase64::Encode(uchar c) const
Encode a unsigned char to Base64 encoding c unsigned char to convert to Base64 (6-bit) value unsigned char in Base64 alphabet, or error (-1) for invalid input
References base64_encode.
Referenced by Base64Encode, Encode.
size_t SeBase64::Encode(const uchar *in, size_t length, uchar *outbuf, size_t size, uint option=BASE64_STANDARD) const
Encode an array of bytes to Base64 string in unsigned char pointer of data source length size of data source outbuf unsigned char pointer of destination buffer size size of destination buffer option newline option number of bytes copied, or error (-1) for invalid input
References BASE64_LF, BASE64_NCHAR, BASE64_PAD, BASE64_STANDARD, Encode, to_uchar.
uchar SeBase64::Decode(uchar c) const
Decode a Base64 alphabet data to 6-bit representation c Alphabet data to convert to binary value binary value (0-63), or error (-1) for invalid input
References base64_encode.
Referenced by Base64Decode, Decode, IsBase64Char.
size_t SeBase64::Decode(const uchar *in, size_t length, uchar *outbuf, size_t size, uint option=BASE64_STANDARD) const
Decode an array of bytes to binary. It's safe for 'in' and 'outbuf' to be the same buffer. in unsigned char pointer of data source (Base64 Alphabet) length size of data source outbuf unsigned char pointer of destination buffer size size of destination buffer option newline option number of bytes copied, or error (-1) for invalid input
References BASE64_CR, BASE64_LF, BASE64_PAD, Decode.
static uchar SeBase64::to_uchar(char c)
Convert to uchar c ASCII character unsigned character
Referenced by Encode.