SeFormula
int SeFormula::m_aiLevelUpExp[HERO_MAX_LEVEL][HERO_MAX_LEVEL]
Referenced by GetCanLevelUpExp, Init, SeFormula.
int SeFormula::m_aiLevelExp[HERO_MAX_LEVEL][HERO_MAX_LEVEL]
Referenced by GetLevelUpExp, Init, SeFormula.
int SeFormula::m_aiHeroDeadExp[HERO_MAX_LEVEL][HERO_MAX_LEVEL]
Referenced by GetHeroDeadExp, Init, SeFormula.
int SeFormula::m_aiMonsterDeadExp[MONSTER_MAX_LEVEL][MONSTER_MAX_LEVEL]
Referenced by GetMonsterDeadExp, Init, SeFormula.
int SeFormula::m_aiHeroDeadMoney[HERO_MAX_LEVEL][HERO_MAX_LEVEL]
Referenced by GetHeroDeadMoney, Init, SeFormula.
int SeFormula::m_iBuyItemMoney[MAX_BUYITEM][MAX_BUYITEM]
Referenced by Init.
bool SeFormula::m_bInited
Referenced by Init, SeFormula.
SeFormula::SeFormula(void)
References m_aiHeroDeadExp, m_aiHeroDeadMoney, m_aiLevelExp, m_aiLevelUpExp, m_aiMonsterDeadExp, m_bInited.
SeFormula::~SeFormula(void)
void SeFormula::Init()
References LevelTableMgr::Get, LevelTableMgr::GetLevelTable, HERO_MAX_LEVEL, m_aiHeroDeadExp, m_aiHeroDeadMoney, m_aiLevelExp, m_aiLevelUpExp, m_aiMonsterDeadExp, m_bInited, m_iBuyItemMoney, MONSTER_MAX_LEVEL, LevelTable::uiDeadExp, LevelTable::uiKillGold, LevelTable::uiTotalExp.
Referenced by GetCanLevelUpExp, GetHeroDeadExp, GetHeroDeadMoney, GetLevelUpExp, GetMonsterDeadExp.
int SeFormula::GetLevelByCharScore(DWord dwScore)
References s_adwCharScoreTable.
Referenced by GetMaxPlayerChestNum, GetRaceBetStake.
int SeFormula::GetLevelByHeroScore(DWord dwScore)
References s_adwHeroScoreTable.
int SeFormula::GetScoreByCharLevel(int iLevel)
References s_adwCharScoreTable.
int SeFormula::GetScoreByHeroLevel(int iLevel)
References s_adwHeroScoreTable.
int SeFormula::GetLevelByPetScore(DWord dwScore)
References s_adwPetScoreTable.
int SeFormula::GetScoreByPetLevel(int iLevel)
References s_adwPetScoreTable.
int SeFormula::GetLevelByMountScore(DWord dwScore)
References s_adwMountScoreTable.
int SeFormula::GetCanLevelUpExp(int iHeroLevel)
References HERO_MAX_LEVEL, Init, m_aiLevelUpExp.
int SeFormula::GetLevelUpExp(int iHeroLevel)
References HERO_MAX_LEVEL, Init, m_aiLevelExp.
int SeFormula::GetHeroDeadExp(int iHeroLevel)
References HERO_MAX_LEVEL, Init, m_aiHeroDeadExp.
int SeFormula::GetMonsterDeadExp(int iMonsterLevel)
References Init, m_aiMonsterDeadExp, MONSTER_MAX_LEVEL.
int SeFormula::GetHeroDeadMoney(int iHeroLevel)
References HERO_MAX_LEVEL, Init, m_aiHeroDeadMoney.
bool SeFormula::GetHorseID2HorseFlag(const VIntVec &rkHorseID, int &iHorseFlag)
References TableMgr::Get, TableMgr::GetPosIndexByHorseID.
bool SeFormula::GetHorseFlag2HorseID(int iHorseFlag, VIntVec &rkVHorseID)
References TableMgr::Get, TableMgr::GetHorseIDByPosIndex.
int SeFormula::GetLevelByFightScore(DWord dwFightScore)
References g_aiFightScore2Level.
int SeFormula::GetMaxLevelByAccountLevel(int iAccountLevel)
References g_aiAccountLevel2MaxLevel.
int SeFormula::GetLeagueMMRLevelByScore(int iLeagueMMR)
Referenced by BlockServer::CalcChangedLeagueMMR.
int SeFormula::GetRaceBetStake(int iPlayerScore, int iBetLevel)
References GetLevelByCharScore, s_aiRaceBetBaseStake, SRBL_LVL1, SRBL_NUM.
int SeFormula::GetMailAliveTime(int iMailType, int iMailFlag, bool bHasAttach)
References SMAT_AWARD, SMAT_SYSTEM, SMF_IMPORTANT, SMF_READ.
int SeFormula::GetConsumeChestKeyByItemLevel(int iItemLevel)
int SeFormula::GetMaxPlayerChestNum(int iPlayerScore)
References GetLevelByCharScore.