TableResArray
std::vector<SeTableResBase*> TableResArray::m_kObjects
Referenced by getObjectAt, getSize, insert, pushBack.
TableResArray::TableResArray()
TableResArray::~TableResArray()
void TableResArray::pushBack(SeTableResBase *object)
References m_kObjects.
Referenced by AccountLevelTableMgr::GetAccountLevelTableVec, AchievementTableMgr::GetAchievementTableVec, AchievementTaskTableMgr::GetAchievementTaskTableVec, AcSystemTableMgr::GetAcSystemTableVec, AddtionalTableMgr::GetAddtionalTableVec, AIPrioTableMgr::GetAIPrioTableVec, AITableMgr::GetAITableVec, AppendCostTableMgr::GetAppendCostTableVec, AppendGroupTableMgr::GetAppendGroupTableVec, AppendSkillPRTableMgr::GetAppendSkillPRTableVec, AppendSkillTableMgr::GetAppendSkillTableVec, AttackArmorRatioTableMgr::GetAttackArmorRatioTableVec, AvatarAnimationTableMgr::GetAvatarAnimationTableVec, AvatarEffectTableMgr::GetAvatarEffectTableVec, AvatarModelTableMgr::GetAvatarModelTableVec, AvatarShopTableMgr::GetAvatarShopTableVec, AvatarTableMgr::GetAvatarTableVec, BattleTipsTableMgr::GetBattleTipsTableVec, BufferTableMgr::GetBufferTableVec, ChanceTableMgr::GetChanceTableVec, ChoiceItemTableMgr::GetChoiceItemTableVec, CreepTowerGrowthTableMgr::GetCreepTowerGrowthTableVec, DecomposeTableMgr::GetDecomposeTableVec, DressTableMgr::GetDressTableVec, EffectSwitchTableMgr::GetEffectSwitchTableVec, FreeHeroesTableMgr::GetFreeHeroesTableVec, HeroInfoTableMgr::GetHeroInfoTableVec, HorseTableMgr::GetHorseTableVec, IndexofferTableMgr::GetIndexofferTableVec, ItemComposeTableMgr::GetItemComposeTableVec, ItemExchangeTableMgr::GetItemExchangeTableVec, ItemTableMgr::GetItemTableVec, KillBountyTableMgr::GetKillBountyTableVec, LanguageTableMgr::GetLanguageTableVec, LeagueRankTableMgr::GetLeagueRankTableVec, LevelTableMgr::GetLevelTableVec, MapInfoTableMgr::GetMapInfoTableVec, MapMiscTableMgr::GetMapMiscTableVec, MapShopResTableMgr::GetMapShopResTableVec, MapsInfoTableMgr::GetMapsInfoTableVec, MissionInfoTableMgr::GetMissionInfoTableVec, ModelResTableMgr::GetModelResTableVec, PetTableMgr::GetPetTableVec, PresetShopTableMgr::GetPresetShopTableVec, PropagandaTableMgr::GetPropagandaTableVec, PVERuleTableMgr::GetPVERuleTableVec, RacedropTableMgr::GetRacedropTableVec, RacehelpTableMgr::GetRacehelpTableVec, RaceStaMissionTableMgr::GetRaceStaMissionTableVec, RaceTextTableMgr::GetRaceTextTableVec, RackTableMgr::GetRackTableVec, RandomNameTableMgr::GetRandomNameTableVec, RankStageTableMgr::GetRankStageTableVec, RenJiActionsTableMgr::GetRenJiActionsTableVec, RenJiConditionsTableMgr::GetRenJiConditionsTableVec, RenJiCustomDataTableMgr::GetRenJiCustomDataTableVec, RenJiTableMgr::GetRenJiTableVec, SearchChoiceTableMgr::GetSearchChoiceTableVec, SelHeroTableMgr::GetSelHeroTableVec, ShopTableMgr::GetShopTableVec, SkillTableMgr::GetSkillTableVec, SkillTipsTableMgr::GetSkillTipsTableVec, StarWheelTableMgr::GetStarWheelTableVec, StrengthenTableMgr::GetStrengthenTableVec, SystemPromptTableMgr::GetSystemPromptTableVec, TaskInfoTableMgr::GetTaskInfoTableVec, TaskRecomTableMgr::GetTaskRecomTableVec, TownItemTableMgr::GetTownItemTableVec, UnitHeadAreaTableMgr::GetUnitHeadAreaTableVec, UnitTableMgr::GetUnitTableVec, UpgradeCostTableMgr::GetUpgradeCostTableVec, VideoTagTableMgr::GetVideoTagTableVec, VoiceTableMgr::GetVoiceTableVec.
void TableResArray::insert(SeTableResBase *object, int index)
References m_kObjects.
SeTableResBase * TableResArray::getObjectAt(int index)
References m_kObjects.
Referenced by CItemMgr::ChangeCiTiao, FreshSkill, CItemMgr::ItemDepart.
int TableResArray::getSize()
References m_kObjects.
Referenced by CItemMgr::ChangeCiTiao, FreshSkill, CItemMgr::ItemDepart.