FreeHeroesTableMgr
std::map<unsigned int,FreeHeroesTable*> FreeHeroesTableMgr::m_kFreeHeroesTableMap
Referenced by FillData, GetFreeHeroesTable, GetFreeHeroesTableMap, GetFreeHeroesTableVec, ~FreeHeroesTableMgr.
FreeHeroesTableMgr * FreeHeroesTableMgr::m_pkFreeHeroesTableMgr
Referenced by Get, ReLoad.
FreeHeroesTableMgr * FreeHeroesTableMgr::Get()
References FreeHeroesTableMgr, m_pkFreeHeroesTableMgr.
Referenced by HeroMgr::createFreeHeroes, GlobalTableMgr::GetFreeHerosTable, HeroMgr::isValidHero, TableMgr::LoadTable, ReLoad, HeroMgr::unlockHero.
FreeHeroesTableMgr * FreeHeroesTableMgr::ReLoad()
References Get, m_pkFreeHeroesTableMgr.
Referenced by TableMgr::ReloadTable.
FreeHeroesTableMgr::FreeHeroesTableMgr()
References Load.
Referenced by Get.
FreeHeroesTableMgr::~FreeHeroesTableMgr()
References m_kFreeHeroesTableMap.
const FreeHeroesTable * FreeHeroesTableMgr::GetFreeHeroesTable(unsigned int iTypeID)
References m_kFreeHeroesTableMap.
Referenced by GlobalTableMgr::GetFreeHerosTable, HeroMgr::isValidHero.
const std::map< unsigned int, FreeHeroesTable * > & FreeHeroesTableMgr::GetFreeHeroesTableMap()
References m_kFreeHeroesTableMap.
Referenced by HeroMgr::createFreeHeroes.
TableResArray FreeHeroesTableMgr::GetFreeHeroesTableVec()
References m_kFreeHeroesTableMap, TableResArray::pushBack.
bool FreeHeroesTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by FreeHeroesTableMgr.
void FreeHeroesTableMgr::FillData(FreeHeroesTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, FreeHeroesTable::iResetTime, FreeHeroesTable::kHeroName, m_kFreeHeroesTableMap, FreeHeroesTable::uifeature, FreeHeroesTable::uiHeroID, FreeHeroesTable::uiUserType.
Referenced by Load.