MatchServer
char MatchServer::m_acSend[MATCH_SEND_SIZE]
Referenced by MatchServer.
DWord MatchServer::m_dwTickCount
Referenced by Initialize, MatchServer, Update.
DWord MatchServer::m_dwCurTime
Referenced by GetServerTime, MatchServer, PreProcessNM, PreProcessWM, Update.
SeMatchConfig MatchServer::m_kConfig
Referenced by GetConfig, GetDebugLevel, GetServerID, InitializeNet, LoadConfig, LoadDynamicConfig, SetDebugLevel, ShowConsoleTitle.
SeRandNum MatchServer::m_kRandNum
Referenced by RandInt.
bool MatchServer::m_bRunning
Referenced by MatchServer, ProcessRM_Register, ProcessTM_Register, Update.
TeNetMgr MatchServer::m_kNetMgr
Referenced by Finialize, Initialize, InitializeNet, OnNetRecv, ProcessRM_Register, ProcessTM_Register, SendHSData, SendMNData, SendMRData, SendMTData, SendMWData, Update, UpdateRSTOMSTime, UpdateTSTOMSTime.
SeVirtConn * MatchServer::m_pkWSConn
Referenced by LoadConfig, MatchServer, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessWM, ProcessWM_RegisterRet, SendMWData.
SeVirtConn * MatchServer::m_pkNSConn
Referenced by LoadConfig, MatchServer, OnNetConnected, OnNetDisconnect, OnNetRecv, PreProcessNM, ProcessNM_RegisterRet, SendMNData.
MapAllConnect MatchServer::m_kAllConnect
Referenced by getAllConnect, GetRandHttpSock, OnNetAccept, OnNetDisconnect, OnNetRecv.
DWord MatchServer::m_dwLogHeartPackage
Referenced by MatchServer.
SeRaceBet MatchServer::m_kRaceBet
Referenced by GetRaceBetInfo, InitRaceBetInfo, ProcessTM_QueryRaceBetInfo, SaveRaceBetInfo, UpdateRaceBetInfo, UpdateRaceBetOddsEnd.
DWord MatchServer::m_dwBetRaceCheckTime
Referenced by MatchServer, UpdateRaceBetInfo.
MatchServer::MatchServer(void)
References m_acSend, m_bRunning, m_dwBetRaceCheckTime, m_dwCurTime, m_dwLogHeartPackage, m_dwTickCount, m_pkNSConn, m_pkWSConn.
MatchServer::~MatchServer(void)
const SeMatchConfig& MatchServer::GetConfig()
References m_kConfig.
Referenced by SeRaceSvrMgr::GetBestNormalRaceSvr, SeMatchMgr::match.
bool MatchServer::Initialize(void)
References g_kRaceQueryMgr, g_kRaceSvrMgr, g_kResMgr, g_kTownMgr, g_kVirtConnMgr, InitFileData, SeRaceSvrMgr::Initialize, SeTownMgr::Initialize, SeReMgr::Initialize, SeRaceQueryMgr::Initialize, SeVirtConnMgr::Initialize, InitializeNet, LoadConfig, LoadDynamicConfig, m_dwTickCount, m_kNetMgr, SeLogError, sendHeartPack, sendRegPack.
void MatchServer::Update(void)
References g_kMatchBanMgr, g_kMatchMgr, g_kMatchPrepareMgr, g_kRaceMgr, g_kRaceQueryMgr, g_kTownMgr, g_kVirtConnMgr, moba::Clock::getInstance, GetServerTime, m_bRunning, m_dwCurTime, m_dwTickCount, m_kNetMgr, PrintUpdateTime, SeOpenRoomMgrInst, moba::Clock::setTime, SeTownMgr::Update, SeRaceMgr::Update, MatchBanMgr::update, MatchPrepareMgr::update, SeRaceQueryMgr::Update, SeVirtConnMgr::Update, SeMatchMgr::Update, UpdatePackage, UpdateRaceBetInfo, UpdateRSTOMSTime, UpdateTSTOMSTime.
void MatchServer::Finialize(void)
References SeRaceMgr::Finalize, g_kRaceMgr, m_kNetMgr.
void MatchServer::ShowConsoleTitle(int iDTime)
References SeMatchConfig::dwServerID, g_kRaceMgr, g_kRaceQueryMgr, g_kRaceSvrMgr, g_kTownMgr, GetID2Str, SeRaceMgr::GetRaceNum, SeRaceQueryMgr::GetRaceRoomNum, SeRaceSvrMgr::GetRaceSvrNum, SeTownMgr::GetTownArea, SeTownMgr::GetTownNum, m_kConfig, SPrintf.
SeServerActionResult MatchServer::ExecuteAction(SeServerActionIndex eActionIndex)
References AER_OK, AI_F1, AI_F5, LoadDynamicConfig, SeLogHideTime.
void MatchServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
References SeNetAddr::acIP, g_kVirtConnMgr, SeNetAddr::iPort, SeVirtConn::kNetAddr, m_pkNSConn, m_pkWSConn, SeVirtConnMgr::OnServerConnected.
void MatchServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
References SeNetAddr::acIP, SeConnect::dwStateTime, SeConnect::eState, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kAllConnect, SCS_UNKOWN, SSD_IP_LEN, StrCpy.
void MatchServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
References CMD_HS_REGISTER, CMD_RM_REGISTER, CMD_TM_REGISTER, SeConnect::dwRecvTime, SeConnect::eState, GetServerTime, SeVirtConn::kSock, m_kAllConnect, m_kNetMgr, m_pkNSConn, m_pkWSConn, ProcessBLMData, ProcessHSData, ProcessNMData, ProcessRMData, ProcessTMData, ProcessWMData, SCS_HTTP_OK, SCS_RACESVR_OK, SCS_TOWN_OK, SCS_UNKOWN, SeLogInfo, SSD_SEND_SIZE, STCB_BLS_MS, STCB_INTERVAL, SeCMD::wCmd, SeCMD::wFlag.
void MatchServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
References SeNetAddr::acIP, SeConnect::eState, g_kRaceSvrMgr, g_kTownMgr, g_kVirtConnMgr, SeNetAddr::iPort, SeConnect::kNetAddr, SeVirtConn::kSock, SeConnect::kTownSign, m_kAllConnect, m_pkNSConn, m_pkWSConn, SeRaceSvrMgr::OnRSDisconnect, SeVirtConnMgr::OnServerDisconnect, SeTownMgr::OnTSDisconnect, SAFE_DELETE, SCS_RACESVR_OK, SCS_TOWN_OK, SeLogError.
const MapAllConnect& MatchServer::getAllConnect() const
References m_kAllConnect.
bool MatchServer::SendMT_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
Referenced by ProcessTM_Register.
bool MatchServer::SendMT_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessTM_HeartPackage.
bool MatchServer::SendMT_StartMatchRet(DWord dwPlayerID, int iResult, DWord dwMapID, void *pkReceiver=NULL)
bool MatchServer::SendMT_CancelMatchRet(DWord dwPlayerID, bool bRet, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchSessionNotify(DWord dwPlayerID, DWord dwMatchSession, void *pkReceiver=NULL)
Referenced by loadMatchDetail.
bool MatchServer::SendMT_CommMatchMsg(DWord dwMatchSession, const SeCommMatchMsg &eMsg, DWord dwParam, int iParam, DWord dwParam2, void *pkReceiver=NULL)
Referenced by SeRaceMgr::DoRaceOver, SeRaceMgr::OnProcessAddIncompleteRace, SeRaceMgr::OnProcessCommRaceMsg, SeRaceMgr::SendMatchCommMsg.
bool MatchServer::SendMT_NotifyAddrToMatch(DWord dwPlayerID, DWord dwMatchSession, const SeNetAddr &kAddrToMatch, const SeNetAddr &kAddrToMatchUdp, DWord dwEnterKey, const SeRaceValidType &eValidType, int iSeat, int iNum, const SeNoticeMatchPlayerInfo *akPlayerInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessReconQuerySuccess, SeRaceMgr::OnProcessViewQuerySuccess, SeRaceMgr::SendMatchAddrMsg.
bool MatchServer::SendMT_NotifyAddrToMatch(DWord dwPlayerID, DWord dwMatchSession, const SeNetAddr &kAddrToMatch, const SeNetAddr &kAddrToMatchUdp, DWord dwEnterKey, const SeRaceValidType &eValidType, int iSeat, int iNum, std::vector< SeNoticeMatchPlayerInfo > &akPlayerInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_UpdateMisc(DWord dwPlayerID, DWord dwSession, const SeMMMiscType &eType, int iValue, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessUpdateMisc.
bool MatchServer::SendMT_RaceEndSend(DWord dwTime, DWord dwMapID, DWord dwRoomSession, const SeMatchRaceType &eMatchType, int iNum, const SeWSRaceSendInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessRaceEndReport.
bool MatchServer::SendMT_RaceEndSend(DWord dwTime, DWord dwMapID, DWord dwRoomSession, const SeMatchRaceType &eMatchType, int iNum, std::vector< SeWSRaceSendInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_GuanqiaEndSend(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, const SeWSGuanqiaSendInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessRaceEndGuanqia.
bool MatchServer::SendMT_GuanqiaEndSend(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, std::vector< SeWSGuanqiaSendInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_ReconQueryFail(const SeReconQueryFailReason &eReason, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by ProcessRM_ReconQueryFail.
bool MatchServer::SendMT_ViewQueryFail(const SeViewQueryFailReason &eReason, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessViewQuery, SeRaceMgr::OnProcessViewQuerySuccess, ProcessRM_ViewQueryFail.
bool MatchServer::SendMT_QueryRaceRoomListRet(DWord dwPlayerID, int iCurPage, int iMaxPage, int iRoomNums, const SeMatchRoomListInfo *akRoomInfo, void *pkReceiver=NULL)
Referenced by OnSendTSQueryRoomListRet.
bool MatchServer::SendMT_QueryRaceRoomListRet(DWord dwPlayerID, int iCurPage, int iMaxPage, int iRoomNums, std::vector< SeMatchRoomListInfo > &akRoomInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_BiVoiceEnterInfo(DWord dwPlayerID, int roomid, const char *acLoginSession, const char *acRoomSession, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnBiVoiceCreateRoom.
bool MatchServer::SendMT_AskEnterWaitRace(DWord dwPlayerID, DWord dwMapID, int iNum, const SeRaceWaitPlayer *akPlayerList, void *pkReceiver=NULL)
bool MatchServer::SendMT_AskEnterWaitRace(DWord dwPlayerID, DWord dwMapID, int iNum, std::vector< SeRaceWaitPlayer > &akPlayerList, void *pkReceiver=NULL)
bool MatchServer::SendMT_GetRaceCardInfo(DWord dwSession, DWord dwPlayerID, DWord dwHeroTypeID, DWord dwPetTypeID, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRaceLoad(DWord dwRoomSession, DWord dwPlayerID, DWord dwMapID, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessMatchRaceLoad.
bool MatchServer::SendMT_QueryRaceBetInfoRet(DWord dwPlayerID, DWord dwConstellIDA, DWord dwConstellIDB, float fOddsA, float fOddsB, void *pkReceiver=NULL)
Referenced by ProcessTM_QueryRaceBetInfo.
bool MatchServer::SendMT_RaceBuy(DWord dwSession, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessRaceBuy.
bool MatchServer::SendMT_MatchCreateRoomRet(DWord dwPlayerID, const SeCreateRoomRetType &eType, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeOpenRoomMgr::OnCreateRoom.
bool MatchServer::SendMT_MatchCreateRoomRet(DWord dwPlayerID, const SeCreateRoomRetType &eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchQueryRoomListRet(DWord dwPlayerID, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeOpenRoomMgr::OnQueryRoomList.
bool MatchServer::SendMT_MatchQueryRoomListRet(DWord dwPlayerID, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomJoinRet(DWord dwPlayerID, const SeRoomJoinRetType &eType, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
Referenced by SeOpenRoomMgr::SendRoomJoinRet.
bool MatchServer::SendMT_MatchRoomJoinRet(DWord dwPlayerID, const SeRoomJoinRetType &eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomMemberNotifyRet(DWord dwPlayerID, const SeRoomNtfCode &eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, const SeRoomMember *akInfo, void *pkReceiver=NULL)
Referenced by SeOpenRoomMgr::SendRoomNotify.
bool MatchServer::SendMT_MatchRoomMemberNotifyRet(DWord dwPlayerID, const SeRoomNtfCode &eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, std::vector< SeRoomMember > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomLeaveRet(DWord dwPlayerID, DWord dwRoomID, void *pkReceiver=NULL)
Referenced by SeOpenRoomMgr::OnRoomLeave.
bool MatchServer::SendMT_MatchRoomReadyRet(DWord dwPlayerID, DWord dwRoomID, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomSwitchSeatRet(DWord dwPlayerID, const SeRoomJoinRetType &eType, void *pkReceiver=NULL)
Referenced by SeOpenRoomMgr::OnRoomSwitchSeat.
bool MatchServer::SendMT_MatchRoomKickSomeoneRet(DWord dwPlayerID, DWord dwRoomID, int iseat, const SeRoomKickCode &eType, void *pkReceiver=NULL)
Referenced by SeOpenRoomMgr::OnRoomKickSomeone.
bool MatchServer::SendMT_AddIncompleteRace(const SeIncompleteRaceBaseInfo &oIncompleteRaceBaseInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_RemoveIncompleteRace(DWord dwRoomID, void *pkReceiver=NULL)
bool MatchServer::SendMT_ResIncmpRaceSeatBaseInfo(DWord dwPlayerID, DWord dwRoomID, int iNum, const SeSeatBaseInfo *oIncmpRaceBaseInfo, void *pkReceiver=NULL)
Referenced by ProcessTM_ReqIncompleteRaceKDA.
bool MatchServer::SendMT_ResIncmpRaceSeatBaseInfo(DWord dwPlayerID, DWord dwRoomID, int iNum, std::vector< SeSeatBaseInfo > &oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_ResIncompleteRaceList(DWord dwPlayerID, int iNum, const SeIncompleteRaceBaseInfo *akIncmpRaceList, void *pkReceiver=NULL)
Referenced by ProcessTM_ReqIncompleteRaceList.
bool MatchServer::SendMT_ResIncompleteRaceList(DWord dwPlayerID, int iNum, std::vector< SeIncompleteRaceBaseInfo > &akIncmpRaceList, void *pkReceiver=NULL)
bool MatchServer::SendMT_ReqMatchRep(DWord dwPlayerID, const MatchReqResult &ReqResult, void *pkReceiver=NULL)
Referenced by MatchPrepareMgr::onDataResult, MatchPrepareMgr::OnPlayerLeave, ProcessTM_PlayerMatchReq, MatchPrepareMgr::update.
bool MatchServer::SendMT_MatchCancelRep(DWord dwReceiver, const MatchCancelResult &CancelMatchResult, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by SeMatchMgr::OnMatchCancel, ProcessTM_PlayerMatchCancel.
bool MatchServer::SendMT_NotiMatcherPre(DWord dwPlayerID, DWord WaitID, DWord dwPlayerNum, void *pkReceiver=NULL)
Referenced by SeMatchMgr::addWaitRoom.
bool MatchServer::SendMT_NotiMatcherResult(DWord ResultKind, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by SeMatchMgr::OnConfirm, SeMatchMgr::UpdateRoom.
bool MatchServer::SendMT_SingleMatchConfirm(DWord PlayerID, bool BolConfirm, DWord PlayerIndex, DWord MaxPlayerNum, DWord dwReceiver, void *pkReceiver=NULL)
Referenced by SeMatchMgr::OnConfirm.
bool MatchServer::SendMTData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr, SeLogError, SeCMD::wCmd.
bool MatchServer::SendMR_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
Referenced by ProcessRM_Register.
bool MatchServer::SendMR_HeartPackageRet(void *pkReceiver=NULL)
Referenced by ProcessRM_HeartPackage.
bool MatchServer::SendMR_ValidatePlayerInfo(DWord dwSessionID, DWord dwTime, DWord dwMapID, DWord dwKey, int iDifficulty, bool bSvrRace, const SePtlRaceBetInfo &kRaceBet, const SeMatchFightInfo &kFightInfo, DWord dwScoreCampA, DWord dwScoreCampB, DWord dwScoreRobot, bool bRobot, int iSize, const char *acData, void *pkReceiver=NULL)
bool MatchServer::SendMR_ValidatePlayerInfo(DWord dwSessionID, DWord dwTime, DWord dwMapID, DWord dwKey, int iDifficulty, bool bSvrRace, const SePtlRaceBetInfo &kRaceBet, const SeMatchFightInfo &kFightInfo, DWord dwScoreCampA, DWord dwScoreCampB, DWord dwScoreRobot, bool bRobot, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool MatchServer::SendMR_PlayerModifyInfo(DWord dwSessionID, int dwPlayerID, void *pkReceiver=NULL)
bool MatchServer::SendMR_UpdateMiscInfo(DWord dwPlayerID, int iValue, void *pkReceiver=NULL)
bool MatchServer::SendMR_ReconQuery(DWord dwRoomID, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iSeat, int iOffset, DWord dwFrame, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessReconQuery.
bool MatchServer::SendMR_ViewQuery(DWord dwSession, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iViewDelay, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessViewQuery.
bool MatchServer::SendMR_ViewValidOKRet(DWord dwSession, const SeViewInitInfo &kInitInfo, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessReconViewValid.
bool MatchServer::SendMR_ValidFailRet(DWord dwSession, DWord dwPlayerID, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessReconViewValid.
bool MatchServer::SendMR_RaceBuyRet(DWord dwSession, bool bSuccess, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessRaceBuyRet, ProcessRM_RaceBuy.
bool MatchServer::SendMR_ReconPLayerName(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
Referenced by SeRaceMgr::OnProcessReconPlayerName.
bool MatchServer::SendMRData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr, SeLogError, SeCMD::wCmd.
Referenced by OnSendRSValidatePlayerInfo.
DWord MatchServer::GetServerTime(void)
References m_dwCurTime.
Referenced by SeRaceMgr::CreatEmptyRace, SeRaceMgr::DoRaceOver, SeRaceQueryMgr::GetRoomFun, SeOpenRoomMgr::OnCreateRoom, OnNetAccept, OnNetRecv, SeRaceMgr::OnProcessCommRaceMsg, SeRaceMgr::OnProcessReloadRoomList, SeRaceMgr::OnProcessValidateInfoRet, SeRaceMgr::OnProcessViewQuerySuccess, SeOpenRoomMgr::OnRoomInviteRspOk, SeOpenRoomMgr::OnRoomJoin, SeRaceSvrMgr::OnRSUpdateLoadNum, OnSendTSQueryRoomListRet, SeTownMgr::OnTSUpdateLoadNum, SeMatchMgr::openRoom, ProcessRM_Register, ProcessTM_Register, SeRaceQueryMgr::RoomFilter, SeOpenRoom::SeOpenRoom, SeOpenRoomMgr::StartMatch, Update, SeRaceQueryMgr::UpdateMD5VRoom, UpdateRaceBetInfo, UpdateRSTOMSTime, SeRaceMgr::UpdateSvrStaCount, UpdateTSTOMSTime.
DWord MatchServer::GetServerID(void)
References SeMatchConfig::dwServerID, m_kConfig.
Referenced by sendRegPack.
bool MatchServer::GetRandHttpSock(HSock &rkSock)
References SeConnect::eState, SeConnect::kSock, m_kAllConnect, SCS_HTTP_OK.
Referenced by ProcessRM_RaceEndGuanqia, ProcessRM_RaceEndReport, SeRaceMgr::SendMatchAddrMsg, SeMatchRace::~SeMatchRace.
void MatchServer::PrintUpdateTime(DWord *pdwDecTime, int iNums)
References CharToFileFun, GetLocalTime, SPrintf.
Referenced by Update.
int MatchServer::GetDebugLevel(void)
References SeMatchConfig::iDebugLevel, m_kConfig.
void MatchServer::SetDebugLevel(int iLevel)
References SeMatchConfig::iDebugLevel, m_kConfig.
int MatchServer::RandInt(void)
References m_kRandNum, SeRandNum::RandInt.
void MatchServer::OnSendTSQueryRoomListRet(HSock rkSock, DWord dwPlayerID, int iCurPage, int iMaxPage, const VRoomPtr &rkVRoomPtr)
References SeRoom::dwMapID, SeMatchRoomListInfo::dwMapID, SeRoom::dwRaceBeginTime, SeMatchRoomListInfo::dwRaceTime, SeMatchRoomListInfo::dwRoomSession, SeRoom::dwSession, g_kMatchServer, GetServerTime, SendMT_QueryRaceRoomListRet.
Referenced by SeRaceQueryMgr::OnPlayerQueryRoomList.
void MatchServer::OnSendRSValidatePlayerInfo(const HSock &rkSock, const SeMatchRace *pkRace, bool bSvrRace, SePtlRaceBetInfo &rkInfo, VMatchRaceInfo &rakRaceInfo)
References SeMR_ValidatePlayerInfo::acData, SeNetStream::Attach, SeMR_ValidatePlayerInfo::bRobot, calForce, SeScoreInfo::defeat, SeMR_ValidatePlayerInfo::dwKey, SeMatchRace::dwKey, SeMR_ValidatePlayerInfo::dwMapID, SeMatchRace::dwMapID, SeMatchRace::dwMatchSession, SeMR_ValidatePlayerInfo::dwScoreCampA, SeMR_ValidatePlayerInfo::dwScoreCampB, SeMR_ValidatePlayerInfo::dwScoreRobot, SeMR_ValidatePlayerInfo::dwSessionID, EMT_PVE, MapInfoTableMgr::Get, SeNetStream::GetCurPos, MapInfoTableMgr::GetMapInfoTable, SeMatchRace::groupA, SeMatchRace::groupB, SeMR_ValidatePlayerInfo::iDifficulty, SeMatchRace::iDifficulty, SeMR_ValidatePlayerInfo::iSize, SeMR_ValidatePlayerInfo::kRaceBet, MNew, SeScoreInfo::score, SendMRData, SSD_ENDSTR_LEN, SSD_RACEBET_MAP, SSD_SEND_SIZE, MapInfoTable::uiMatchType, Write.
Referenced by SeRaceMgr::RaceUpdate.
void MatchServer::InitFileData()
References InitRaceBetInfo.
Referenced by Initialize.
void MatchServer::InitRaceBetInfo()
References SeRaceBet::fAddtionA, SeRaceBet::fAddtionB, SeRaceBet::fOddsA, SeRaceBet::fOddsB, GetAString, GetDBTime, SeRaceBet::iConstellA, SeRaceBet::iConstellB, SeRaceBet::kUpdateTime, m_kRaceBet, SPrintf.
Referenced by InitFileData.
void MatchServer::SaveRaceBetInfo()
References SeRaceBet::fAddtionA, SeRaceBet::fAddtionB, SeRaceBet::fOddsA, SeRaceBet::fOddsB, GetDBTime2Str, SeRaceBet::iConstellA, SeRaceBet::iConstellB, SeRaceBet::kUpdateTime, m_kRaceBet, SPrintf.
Referenced by UpdateRaceBetInfo, UpdateRaceBetOddsEnd.
void MatchServer::GetRaceBetInfo(SePtlRaceBetInfo &rkInfo)
References SeRaceBet::fAddtionA, SePtlRaceBetInfo::fAddtionA, SeRaceBet::fAddtionB, SePtlRaceBetInfo::fAddtionB, SeRaceBet::fOddsA, SePtlRaceBetInfo::fOddsA, SeRaceBet::fOddsB, SePtlRaceBetInfo::fOddsB, SeRaceBet::iConstellA, SeRaceBet::iConstellB, SePtlRaceBetInfo::iConstellIDA, SePtlRaceBetInfo::iConstellIDB, m_kRaceBet.
Referenced by SeRaceMgr::RaceUpdate.
void MatchServer::UpdateRaceBetInfo()
References g_kResMgr, StarWheelTableMgr::Get, GetServerTime, StarWheelTableMgr::GetStarWheelTable, SeRaceBet::iConstellA, SeRaceBet::iConstellB, StarWheelTable::iOdds, IsDiffDay, SeRaceBet::kUpdateTime, m_dwBetRaceCheckTime, m_kRaceBet, NowTime, SeReMgr::RandGenDayConstell, SeRaceBet::Reset, SaveRaceBetInfo, SeLogError, SeLogInfo, SeRaceBet::SetOadds.
Referenced by Update.
void MatchServer::UpdateRaceBetOddsEnd(SeRM_RaceEndReport *pkEndInfo)
References SeRM_RaceEndReport::akInfo, SeRM_RaceEndReport::dwMapID, SeWSRaceSendInfo::eCmp, MapInfoTableMgr::Get, MapInfoTableMgr::GetMapInfoTable, MapInfoTable::iMaxPlayer, SeRM_RaceEndReport::iNum, SeRaceSendInfo::iRaceEndFlag, SeRaceBet::iWinsA, SeRaceBet::iWinsB, SeWSRaceSendInfo::kInfo, m_kRaceBet, SaveRaceBetInfo, SeRaceBet::SetOadds, SROT_RRESULT_FINISHED_SUCCES, SRPC_CAMPA, SSD_RACEBET_MAP.
bool MatchServer::SendHSData(void *pkData, int iSize, void *pkReceiver)
References m_kNetMgr.
Referenced by SendHS_BiVoiceCreateChatRoom, SendHS_BiVoiceDelChatRoom, SendHS_BiVoiceUserLoginRet, SendHS_HeartPackageRet, SendHS_RegisterRet, SendHS_SaveRaceRecord.
void MatchServer::SendHS_RegisterRet(const HSock &rkSock, int iRet)
References SeHS_RegisterRet::iRet, SendHSData.
Referenced by ProcessHS_Register.
void MatchServer::SendHS_HeartPackageRet(const HSock &rkSock)
References SendHSData.
Referenced by ProcessHS_HeartPackage.
void MatchServer::SendHS_SaveRaceRecord(const HSock &rkSock, const char *acRaceID, int iRaceServerID, int iRaceVersion)
References SeHS_SaveRaceRecord::acRaceID, SeHS_SaveRaceRecord::iRaceServerID, SeHS_SaveRaceRecord::iRaceVersion, SendHSData.
Referenced by ProcessRM_RaceEndGuanqia, ProcessRM_RaceEndReport.
void MatchServer::SendHS_BiVoiceUserLoginRet(const HSock &rkSock, int iPackKey, const char *pcAppKey, const char *pcAccount, int iReturn)
References SeHS_BiVoiceUserLoginRet::acAccount, SeHS_BiVoiceUserLoginRet::acAppKey, SeHS_BiVoiceUserLoginRet::iPackKey, SeHS_BiVoiceUserLoginRet::iReturn, SendHSData, StrCpy.
Referenced by ProcessHS_BiVoiceUserLogin.
void MatchServer::SendHS_BiVoiceCreateChatRoom(const HSock &rkSock, int iPackKey, const char *pcAppKey, const char *pcRoomName, const char *pcHead, int iRoomType, int iScope, int iMaxUser)
References SeHS_BiVoiceCreateChatRoom::acAppKey, SeHS_BiVoiceCreateChatRoom::acRoomName, SeHS_BiVoiceCreateChatRoom::iMaxUserNumber, SeHS_BiVoiceCreateChatRoom::iPackKey, SeHS_BiVoiceCreateChatRoom::iRoomType, SeHS_BiVoiceCreateChatRoom::iScope, SendHSData, StrCpy.
Referenced by SeRaceMgr::SendMatchAddrMsg.
void MatchServer::SendHS_BiVoiceDelChatRoom(const HSock &rkSock, int iRoomID)
References SeHS_BiVoiceDelChatRoom::iRoomID, SendHSData.
Referenced by SeMatchRace::~SeMatchRace.
void MatchServer::ProcessHSData(void *pkData, int iSize, void *pkSender=NULL)
References CMD_HS_BIVOICE_CREATE_CHAT_ROOM_RET, CMD_HS_BIVOICE_USER_LOGIN, CMD_HS_HEARTPACKAGE, CMD_HS_REGISTER, ProcessHS_BiVoiceCreateChatRoomRet, ProcessHS_BiVoiceUserLogin, ProcessHS_HeartPackage, ProcessHS_Register, SeCMD::wCmd.
Referenced by OnNetRecv.
void MatchServer::ProcessHS_Register(void *pkData, int iSize, void *pkSender=NULL)
References SeConnect::eState, SeConnect::kSock, SCS_HTTP_OK, SendHS_RegisterRet.
Referenced by ProcessHSData.
void MatchServer::ProcessHS_HeartPackage(void *pkData, int iSize, void *pkSender=NULL)
References SeConnect::kSock, SendHS_HeartPackageRet.
Referenced by ProcessHSData.
void MatchServer::ProcessHS_BiVoiceUserLogin(void *pkData, int iSize, void *pkSender=NULL)
References SeHS_BiVoiceUserLogin::acAccount, SeHS_BiVoiceUserLogin::acAppKey, SeHS_BiVoiceUserLogin::acPwd, SeHS_BiVoiceUserLogin::iPackKey, SeConnect::kSock, SendHS_BiVoiceUserLoginRet.
Referenced by ProcessHSData.
void MatchServer::ProcessHS_BiVoiceCreateChatRoomRet(void *pkData, int iSize, void *pkSender=NULL)
References g_kRaceMgr, g_kSynMgr, SeSynMgr::GetOutSynOpr, SeSynOpr::iID, SeHS_BiVoiceCreateChatRoomRet::iPackKey, SeHS_BiVoiceCreateChatRoomRet::iRoomID, SeRaceMgr::OnBiVoiceCreateRoom, SAFE_DELETE.
Referenced by ProcessHSData.
bool MatchServer::ProcessTMData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool MatchServer::PreProcessTM(void *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_Register(SeTM_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeTown::dwAreaID, SeTM_Register::dwAreaID, SeTown::dwDefaultMapID, SeTM_Register::dwDefaultMapID, SeTown::dwLastRecvTime, SeTown::dwServerID, SeTM_Register::dwServerID, SeConnect::dwStateTime, SeTM_Register::dwTownMagic, SeConnect::eState, g_kTownMgr, GetID2Str, GetServerTime, SeTownMgr::GetTown, SeTown::iMaxNum, SeTM_Register::iMaxPlayerNum, SeNetAddr::iPort, SeTown::iTownIndex, SeTM_Register::iTownIndex, SeConnect::kNetAddr, SeConnect::kSock, SeConnect::kTownSign, m_bRunning, m_kNetMgr, SeTownMgr::OnTSRegister, SeTown::pkConnect, SCS_TOWN_OK, SCS_UNKOWN, SeLogError, SeLogInfo, SendMT_RegisterRet, SRR_REPEAT, SRR_SUCCESS, SSD_MSANGO_MAGIC.
void MatchServer::ProcessTM_HeartPackage(SeTM_HeartPackage *pkData, int iSize, void *pkSender)
References g_kTownMgr, SeTM_HeartPackage::iPlayerConn, SeTM_HeartPackage::iRaceConn, SeConnect::kSock, SeConnect::kTownSign, SeTownMgr::OnTSUpdateLoadNum, SendMT_HeartPackageRet.
void MatchServer::ProcessTM_CommMatchMsg(SeTM_CommMatchMsg *pkData, int iSize, void *pkSender)
References SeTM_CommMatchMsg::dwMatchSession, SeTM_CommMatchMsg::dwParam, SeTM_CommMatchMsg::eMsg, SeConnect::eState, g_kRaceMgr, g_kTownMgr, SeTownMgr::GetTown, SeTM_CommMatchMsg::iParam, SeConnect::kTownSign, SeRaceMgr::OnProcessCommMsg, SeTown::pkConnect, SCS_TOWN_OK.
void MatchServer::ProcessTM_ReconQuery(SeTM_ReconQuery *pkData, int iSize, void *pkSender)
References g_kRaceMgr, SeRaceMgr::OnProcessReconQuery.
void MatchServer::ProcessTM_ViewQuery(SeTM_ViewQuery *pkData, int iSize, void *pkSender)
References SeConnect::eState, g_kRaceMgr, SeConnect::kSock, SeRaceMgr::OnProcessViewQuery, SCS_TOWN_OK.
void MatchServer::ProcessTM_QueryRaceRoomList(SeTM_QueryRaceRoomList *pkData, int iSize, void *pkSender)
References SeTM_QueryRaceRoomList::dwMapID, SeTM_QueryRaceRoomList::dwPlayerID, SeTM_QueryRaceRoomList::dwRoomSession, SeConnect::eState, g_kRaceQueryMgr, SeTM_QueryRaceRoomList::iPage, SeConnect::kSock, SeRaceQueryMgr::OnPlayerQueryRoomList, SCS_TOWN_OK.
void MatchServer::ProcessTM_QueryRaceBetInfo(SeTM_QueryRaceBetInfo *pkData, int iSize, void *pkSender)
References SeTM_QueryRaceBetInfo::dwPlayerID, SeConnect::eState, SeRaceBet::fOddsA, SeRaceBet::fOddsB, SeRaceBet::iConstellA, SeRaceBet::iConstellB, SeConnect::kSock, m_kRaceBet, SCS_TOWN_OK, SendMT_QueryRaceBetInfoRet.
void MatchServer::ProcessTM_RaceBuyRet(SeTM_RaceBuyRet *pkData, int iSize, void *pkSender)
References g_kRaceMgr, SeRaceMgr::OnProcessRaceBuyRet.
void MatchServer::ProcessTM_PlayerLeave(SeTM_PlayerLeave *pkData, int iSize, void *pkSender)
References SeTM_PlayerLeave::dwPlayerID, SeConnect::eState, g_kMatchMgr, g_kMatchPrepareMgr, SeConnect::kTownSign, MatchPrepareMgr::OnPlayerLeave, SeMatchMgr::OnPlayerLeave, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchCreateRoom(SeTM_MatchCreateRoom *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchQueryRoomList(SeTM_MatchQueryRoomList *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchRoomJoin(SeTM_MatchRoomJoin *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchRoomLeave(SeTM_MatchRoomLeave *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchRoomReady(SeTM_MatchRoomReady *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchRoomSwitchSeat(SeTM_MatchRoomSwitchSeat *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchRoomKickSomeone(SeTM_MatchRoomKickSomeone *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchRoomInvite(SeTM_MatchRoomInvite *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_MatchRoomInviteRsp(SeTM_MatchRoomInviteRsp *pkData, int iSize, void *pkSender)
References SeConnect::eState, SeConnect::kTownSign, SCS_TOWN_OK, SeOpenRoomMgrInst.
void MatchServer::ProcessTM_ReqIncompleteRaceKDA(SeTM_ReqIncompleteRaceKDA *pkData, int iSize, void *pkSender)
References SeTM_ReqIncompleteRaceKDA::dwPlayerID, SeTM_ReqIncompleteRaceKDA::dwRoomSession, SeConnect::eState, g_kRaceQueryMgr, SeRaceQueryMgr::GetIncmpRaceMap, SeConnect::kSock, SCS_TOWN_OK, SendMT_ResIncmpRaceSeatBaseInfo.
void MatchServer::ProcessTM_ReqIncompleteRaceList(SeTM_ReqIncompleteRaceList *pkData, int iSize, void *pkSender)
References SeIncompleteRaceBaseInfo::dwMapID, SeTM_ReqIncompleteRaceList::dwPlayerID, SeIncompleteRaceBaseInfo::dwRoomID, SeIncompleteRaceBaseInfo::emptySeatNum, SeConnect::eState, g_kRaceQueryMgr, SeRaceQueryMgr::GetIncmpRaceMap, SeConnect::kSock, SCS_TOWN_OK, SendMT_ResIncompleteRaceList.
void MatchServer::ProcessTM_ReconPLayerName(SeTM_ReconPLayerName *pkData, int iSize, void *pkSender)
References SeTM_ReconPLayerName::acName, SeTM_ReconPLayerName::dwPlayerID, SeTM_ReconPLayerName::dwRoomSession, g_kRaceMgr, SeRaceMgr::OnProcessReconPlayerName, SeLogDebug.
void MatchServer::ProcessTM_PlayerMatchCancel(SeTM_PlayerMatchCancel *pkData, int iSize, void *pkSender)
References CancelResultSuccess, g_kMatchMgr, GET_CUR_CONN_AND_TOWN, SeMatchMgr::OnMatchCancel, SeTM_PlayerMatchCancel::playerID, SendMT_MatchCancelRep.
void MatchServer::ProcessTM_MatchConfirm(SeTM_MatchConfirm *pkData, int iSize, void *pkSender)
References SeTM_MatchConfirm::BoolConfirm, g_kMatchMgr, SeMatchMgr::OnConfirm, SeTM_MatchConfirm::PlayerID, SeTM_MatchConfirm::WaitID.
void MatchServer::ProcessTM_PlayerMatchReq(SeTM_PlayerMatchReq *pkData, int iSize, void *pkSender)
References SeTM_PlayerMatchReq::bySeats, MatchPrepareMgr::collectData, SeTM_PlayerMatchReq::dwPlayerID, g_kMatchPrepareMgr, MapInfoTableMgr::Get, GET_CUR_CONNECT, MapInfoTableMgr::GetMapInfoTable, SeTM_PlayerMatchReq::IDArray, SeTM_PlayerMatchReq::MapID, SeTM_PlayerMatchReq::MemberNum, ReqResultSuccess, SendMBL_GetPlayerMatchValue, SendMT_ReqMatchRep, MapInfoTable::uiMatchType.
bool MatchServer::ProcessRMData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool MatchServer::PreProcessRM(void *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_Register(SeRM_Register *pkData, int iSize, void *pkSender)
References SeNetAddr::acIP, SeRaceSvr::bOpen, SeRM_Register::bOpen, SeRaceSvr::dwAreaID, SeRM_Register::dwAreaID, SeRaceSvr::dwLastRecvTime, SeRaceSvr::dwServerID, SeRM_Register::dwServerID, SeConnect::dwStateTime, SeConnect::eState, g_kRaceSvrMgr, GetID2Str, SeRaceSvrMgr::GetRaceSvr, GetServerTime, SeNetAddr::iPort, SeRaceSvr::iRegisterCount, SeRM_Register::iRegisterCount, SeRaceSvr::kAddrToMatch, SeRM_Register::kAddrToMatch, SeRaceSvr::kAddrToMatchUdp, SeRM_Register::kAddrToMatchUdp, SeConnect::kNetAddr, SeConnect::kSock, SeConnect::kTownSign, m_bRunning, m_kNetMgr, SeRaceSvrMgr::OnRSRegister, SeRaceSvr::pkConnect, SCS_RACESVR_OK, SCS_UNKOWN, SeLogError, SeLogInfo, SendMR_RegisterRet, SRR_REPEAT, SRR_SUCCESS.
void MatchServer::ProcessRM_HeartPackage(SeRM_HeartPackage *pkData, int iSize, void *pkSender)
References SeRM_HeartPackage::dwCurrRaceNum, g_kRaceSvrMgr, SeConnect::kSock, SeConnect::kTownSign, SeRaceSvrMgr::OnRSUpdateLoadNum, SendMR_HeartPackageRet.
void MatchServer::ProcessRM_ValidatePlayerInfoRet(SeRM_ValidatePlayerInfoRet *pkData, int iSize, void *pkSender)
References SeRM_ValidatePlayerInfoRet::dwSessionID, SeRM_ValidatePlayerInfoRet::eResult, SeConnect::eState, g_kRaceMgr, SeRaceMgr::OnProcessValidateInfoRet, SCS_RACESVR_OK.
void MatchServer::ProcessRM_CommRaceMsg(SeRM_CommRaceMsg *pkData, int iSize, void *pkSender)
References SeRM_CommRaceMsg::dwMatchSession, SeRM_CommRaceMsg::dwParam, SeRM_CommRaceMsg::eMsg, SeConnect::eState, g_kRaceMgr, SeRM_CommRaceMsg::iParam, SeRaceMgr::OnProcessCommRaceMsg, SCS_RACESVR_OK.
void MatchServer::ProcessRM_RaceGetCardInfo(SeRM_RaceGetCardInfo *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_UpdateMisc(SeRM_UpdateMisc *pkData, int iSize, void *pkSender)
References g_kRaceMgr, SeRaceMgr::OnProcessUpdateMisc.
void MatchServer::ProcessRM_RaceEndReport(SeRM_RaceEndReport *pkData, int iSize, void *pkSender)
References SeWSRaceSendInfo::abyRaceID, SeRM_RaceEndReport::akInfo, SeRM_RaceEndReport::dwMapID, HTownSign::dwServerID, g_kRaceMgr, GetID2Str, GetRandHttpSock, SeConnect::kTownSign, SeRaceMgr::OnProcessRaceEndReport, SeLogInfo, SendHS_SaveRaceRecord.
void MatchServer::ProcessRM_RaceEndGuanqia(SeRM_RaceEndGuanqia *pkData, int iSize, void *pkSender)
References SeWSGuanqiaSendInfo::abyRaceID, SeRM_RaceEndGuanqia::akInfo, SeRM_RaceEndGuanqia::dwMapID, HTownSign::dwServerID, g_kRaceMgr, GetID2Str, GetRandHttpSock, SeConnect::kTownSign, SeRaceMgr::OnProcessRaceEndGuanqia, SeLogError, SendHS_SaveRaceRecord.
void MatchServer::ProcessRM_MatchRoomLoadInfo(SeRM_MatchRoomLoadInfo *pkData, int iSize, void *pkSender)
References SeRM_MatchRoomLoadInfo::akLoadInfo, SeRM_MatchRoomLoadInfo::dwSession, g_kRaceMgr, g_kRaceQueryMgr, SeRaceMgr::GetRoomIndexBySession, SeRM_MatchRoomLoadInfo::iNum, SeRaceQueryMgr::OnRaceSvrUpdateRoomLoadInfo.
void MatchServer::ProcessRM_RefreshConfigInfo(SeRM_RefreshConfigInfo *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ReconQuerySuccess(SeRM_ReconQuerySuccess *pkData, int iSize, void *pkSender)
References g_kRaceMgr, SeRaceMgr::OnProcessReconQuerySuccess.
void MatchServer::ProcessRM_ReconQueryFail(SeRM_ReconQueryFail *pkData, int iSize, void *pkSender)
References HTownSign::dwAreaID, SeRM_ReconQueryFail::dwAreaID, SeRM_ReconQueryFail::dwPlayerID, HTownSign::dwServerID, SeRM_ReconQueryFail::dwServerID, SeRM_ReconQueryFail::eReason, g_kTownMgr, SeTownMgr::GetTown, SeConnect::kSock, SeTown::pkConnect, SendMT_ReconQueryFail.
void MatchServer::ProcessRM_ViewQuerySuccess(SeRM_ViewQuerySuccess *pkData, int iSize, void *pkSender)
References g_kRaceMgr, SeRaceMgr::OnProcessViewQuerySuccess.
void MatchServer::ProcessRM_ViewQueryFail(SeRM_ViewQueryFail *pkData, int iSize, void *pkSender)
References HTownSign::dwAreaID, SeRM_ViewQueryFail::dwAreaID, SeRM_ViewQueryFail::dwPlayerID, HTownSign::dwServerID, SeRM_ViewQueryFail::dwServerID, SeRM_ViewQueryFail::eReason, g_kMatchServer, g_kTownMgr, SeTownMgr::GetTown, SeConnect::kSock, SeTown::pkConnect, SendMT_ViewQueryFail.
void MatchServer::ProcessRM_ReconViewValid(SeRM_ReconViewValid *pkData, int iSize, void *pkSender)
References g_kRaceMgr, SeRaceMgr::OnProcessReconViewValid.
void MatchServer::ProcessRM_ReLoadRoomInfoList(SeRM_ReLoadRoomInfoList *pkData, int iSize, void *pkSender)
References SeRM_ReLoadRoomInfoList::akRoomInfo, g_kRaceMgr, SeRM_ReLoadRoomInfoList::iNum, SeConnect::kTownSign, SeRaceMgr::OnProcessReloadRoomList.
void MatchServer::ProcessRM_MatchRaceLoad(SeRM_MatchRaceLoad *pkData, int iSize, void *pkSender)
References g_kRaceMgr, SeRaceMgr::OnProcessMatchRaceLoad.
void MatchServer::ProcessRM_RaceBuy(SeRM_RaceBuy *pkData, int iSize, void *pkSender)
References SeRM_RaceBuy::dwParam1, SeRM_RaceBuy::dwParam2, SeRM_RaceBuy::dwPlayerID, SeRM_RaceBuy::dwSession, g_kRaceMgr, SeRM_RaceBuy::iType, SeConnect::kSock, SeRaceMgr::OnProcessRaceBuy, SendMR_RaceBuyRet.
void MatchServer::ProcessRM_AddIncompleteRace(SeRM_AddIncompleteRace *pkData, int iSize, void *pkSender)
References SeRM_AddIncompleteRace::dwPlayerID, SeRM_AddIncompleteRace::dwRoomSession, g_kRaceMgr, SeRM_AddIncompleteRace::iSeat, SeRaceMgr::OnProcessAddIncompleteRace.
void MatchServer::ProcessRM_RemoveIncompleteRace(SeRM_RemoveIncompleteRace *pkData, int iSize, void *pkSender)
References SeRM_RemoveIncompleteRace::dwRoomSession, g_kRaceMgr, SeRaceMgr::OnProcessRemoveIncompleteRace.
void MatchServer::ProcessRM_UpdateIncompleteRace(SeRM_UpdateIncompleteRace *pkData, int iSize, void *pkSender)
References SeRM_UpdateIncompleteRace::bSeat, SeRM_UpdateIncompleteRace::dwRoomSession, g_kRaceQueryMgr, SeRM_UpdateIncompleteRace::iSeat, SeRaceQueryMgr::OnProcessUpdateIncompleteRace.
void MatchServer::ProcessRM_ResIncmpRaceSeatBaseInfo(SeRM_ResIncmpRaceSeatBaseInfo *pkData, int iSize, void *pkSender)
References SeRM_ResIncmpRaceSeatBaseInfo::dwRoomID, g_kRaceMgr, SeRaceMgr::OnProcessIncmpRaceKDA, SeLogDebug.
bool MatchServer::SendMW_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool MatchServer::SendMW_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool MatchServer::SendMWData(void *pkData, int iSize, void *pkReceiver)
References CMD_MW_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkWSConn, SVCS_REGISTERED, SeCMD::wCmd.
Referenced by SendMBLData.
bool MatchServer::ProcessWMData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool MatchServer::PreProcessWM(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkWSConn.
void MatchServer::ProcessWM_RegisterRet(SeWM_RegisterRet *pkData, int iSize, void *pkSender)
References SeWM_RegisterRet::dwAreaID, SeVirtConn::dwAreaID, SeWM_RegisterRet::eRegisterRet, SeVirtConn::eState, m_pkWSConn, SeLogError, SeLogInfo, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void MatchServer::ProcessWM_HeartPackageRet(SeWM_HeartPackageRet *pkData, int iSize, void *pkSender)
bool MatchServer::SendMBL_RaceMatchLoadDetail(DWord dwPlayerID, DWord dwMatchSession, const MatchType &eMatchType, int iEquipmentType, void *pkReceiver=NULL)
Referenced by loadMatchDetail.
bool MatchServer::SendMBL_GetPlayerMatchValue(DWord dwPlayerID, const MatchType &eMatchType, void *pkReceiver=NULL)
Referenced by ProcessTM_PlayerMatchReq.
bool MatchServer::SendMBL_BlockRoomInvite(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
Referenced by SeOpenRoomMgr::OnRoomInvite.
bool MatchServer::SendMBLData(void *pkData, int iSize, void *pkReceiver)
References SendMWData.
bool MatchServer::ProcessBLMData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool MatchServer::PreProcessBLM(void *pkData, int iSize, void *pkSender)
void MatchServer::ProcessBLM_RaceMatchLoadDetailRet(SeBLM_RaceMatchLoadDetailRet *pkData, int iSize, void *pkSender)
References SeBLM_RaceMatchLoadDetailRet::acData, SeNetStream::Attach, SeBLM_RaceMatchLoadDetailRet::dwMatchSession, SeBLM_RaceMatchLoadDetailRet::dwPlayerID, g_kRaceMgr, SeBLM_RaceMatchLoadDetailRet::iSize, SeRaceMgr::OnProcessDetailInfoReturn, Read.
void MatchServer::ProcessBLM_GetPlayerMatchValueRet(SeBLM_GetPlayerMatchValueRet *pkData, int iSize, void *pkSender)
References g_kMatchPrepareMgr, MatchPrepareMgr::onDataResult.
bool MatchServer::SendMN_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
Referenced by sendRegPack.
bool MatchServer::SendMN_HeartPackage(void *pkReceiver=NULL)
Referenced by sendHeartPack.
bool MatchServer::SendMN_MatchPunishNtf(DWord dwPlayerID, DWord dwMs, void *pkReceiver=NULL)
Referenced by MatchBanMgr::banPlayer.
bool MatchServer::SendMNData(void *pkData, int iSize, void *pkReceiver)
References CMD_MN_REGISTER, SeVirtConn::eState, SeVirtConn::kSock, m_kNetMgr, m_pkNSConn, SVCS_REGISTERED, SeCMD::wCmd.
bool MatchServer::ProcessNMData(void *pkData, int iSize, void *pkSender=NULL)
Referenced by OnNetRecv.
bool MatchServer::PreProcessNM(void *pkData, int iSize, void *pkSender)
References SeVirtConn::dwLastRecvTime, m_dwCurTime, m_pkNSConn.
void MatchServer::ProcessNM_RegisterRet(SeNM_RegisterRet *pkData, int iSize, void *pkSender)
References SeNM_RegisterRet::dwAreaID, SeVirtConn::dwAreaID, SeNM_RegisterRet::eRegisterRet, SeVirtConn::eState, m_pkNSConn, SeLogError, SeLogInfo, SRR_SUCCESS, SVCS_CAN_CONNECT, SVCS_REGISTERED.
void MatchServer::ProcessNM_HeartPackageRet(SeNM_HeartPackageRet *pkData, int iSize, void *pkSender)
void MatchServer::loadMatchDetail(DWord dwPlayerID, DWord dwMatchSession, MatchType eMatchType, int iEquipmentType, HSock kTownSock)
References SendMBL_RaceMatchLoadDetail, SendMT_MatchSessionNotify.
Referenced by SeOpenRoomMgr::CreateRaceInfo.
MatchServer::MatchServer(void)
MatchServer::~MatchServer(void)
const SeMatchConfig& MatchServer::GetConfig()
References m_kConfig.
bool MatchServer::Initialize(void)
void MatchServer::Update(void)
void MatchServer::Finialize(void)
void MatchServer::ShowConsoleTitle(int iDTime)
SeServerActionResult MatchServer::ExecuteAction(SeServerActionIndex eActionIndex)
virtual void MatchServer::OnNetConnected(const HSock &rkSock, const char *pcIP, int iPort)
virtual void MatchServer::OnNetAccept(const HSock &rkSock, int iListenPort, const char *pcIP, int iPort)
virtual void MatchServer::OnNetRecv(const HSock &rkSock, void *pkData, int iSize)
virtual void MatchServer::OnNetDisconnect(const HSock &rkSock, TeDisconnectCode eCode, int iParam)
const MapAllConnect& MatchServer::getAllConnect() const
References m_kAllConnect.
bool MatchServer::SendMT_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
bool MatchServer::SendMT_HeartPackageRet(void *pkReceiver=NULL)
bool MatchServer::SendMT_StartMatchRet(DWord dwPlayerID, int iResult, DWord dwMapID, void *pkReceiver=NULL)
bool MatchServer::SendMT_CancelMatchRet(DWord dwPlayerID, bool bRet, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchSessionNotify(DWord dwPlayerID, DWord dwMatchSession, void *pkReceiver=NULL)
bool MatchServer::SendMT_CommMatchMsg(DWord dwMatchSession, const SeCommMatchMsg &eMsg, DWord dwParam, int iParam, DWord dwParam2, void *pkReceiver=NULL)
bool MatchServer::SendMT_NotifyAddrToMatch(DWord dwPlayerID, DWord dwMatchSession, const SeNetAddr &kAddrToMatch, const SeNetAddr &kAddrToMatchUdp, DWord dwEnterKey, const SeRaceValidType &eValidType, int iSeat, int iNum, const SeNoticeMatchPlayerInfo *akPlayerInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_NotifyAddrToMatch(DWord dwPlayerID, DWord dwMatchSession, const SeNetAddr &kAddrToMatch, const SeNetAddr &kAddrToMatchUdp, DWord dwEnterKey, const SeRaceValidType &eValidType, int iSeat, int iNum, std::vector< SeNoticeMatchPlayerInfo > &akPlayerInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_UpdateMisc(DWord dwPlayerID, DWord dwSession, const SeMMMiscType &eType, int iValue, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool MatchServer::SendMT_RaceEndSend(DWord dwTime, DWord dwMapID, DWord dwRoomSession, const SeMatchRaceType &eMatchType, int iNum, const SeWSRaceSendInfo *akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_RaceEndSend(DWord dwTime, DWord dwMapID, DWord dwRoomSession, const SeMatchRaceType &eMatchType, int iNum, std::vector< SeWSRaceSendInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_GuanqiaEndSend(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, const SeWSGuanqiaSendInfo *akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_GuanqiaEndSend(DWord dwTime, DWord dwMapID, DWord dwRoomSession, int iNum, std::vector< SeWSGuanqiaSendInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_ReconQueryFail(const SeReconQueryFailReason &eReason, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, void *pkReceiver=NULL)
bool MatchServer::SendMT_ViewQueryFail(const SeViewQueryFailReason &eReason, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, void *pkReceiver=NULL)
bool MatchServer::SendMT_QueryRaceRoomListRet(DWord dwPlayerID, int iCurPage, int iMaxPage, int iRoomNums, const SeMatchRoomListInfo *akRoomInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_QueryRaceRoomListRet(DWord dwPlayerID, int iCurPage, int iMaxPage, int iRoomNums, std::vector< SeMatchRoomListInfo > &akRoomInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_BiVoiceEnterInfo(DWord dwPlayerID, int roomid, const char *acLoginSession, const char *acRoomSession, void *pkReceiver=NULL)
bool MatchServer::SendMT_AskEnterWaitRace(DWord dwPlayerID, DWord dwMapID, int iNum, const SeRaceWaitPlayer *akPlayerList, void *pkReceiver=NULL)
bool MatchServer::SendMT_AskEnterWaitRace(DWord dwPlayerID, DWord dwMapID, int iNum, std::vector< SeRaceWaitPlayer > &akPlayerList, void *pkReceiver=NULL)
bool MatchServer::SendMT_GetRaceCardInfo(DWord dwSession, DWord dwPlayerID, DWord dwHeroTypeID, DWord dwPetTypeID, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRaceLoad(DWord dwRoomSession, DWord dwPlayerID, DWord dwMapID, void *pkReceiver=NULL)
bool MatchServer::SendMT_QueryRaceBetInfoRet(DWord dwPlayerID, DWord dwConstellIDA, DWord dwConstellIDB, float fOddsA, float fOddsB, void *pkReceiver=NULL)
bool MatchServer::SendMT_RaceBuy(DWord dwSession, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchCreateRoomRet(DWord dwPlayerID, const SeCreateRoomRetType &eType, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchCreateRoomRet(DWord dwPlayerID, const SeCreateRoomRetType &eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchQueryRoomListRet(DWord dwPlayerID, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchQueryRoomListRet(DWord dwPlayerID, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomJoinRet(DWord dwPlayerID, const SeRoomJoinRetType &eType, int iNum, const SeOpenRoomInfo *akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomJoinRet(DWord dwPlayerID, const SeRoomJoinRetType &eType, int iNum, std::vector< SeOpenRoomInfo > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomMemberNotifyRet(DWord dwPlayerID, const SeRoomNtfCode &eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, const SeRoomMember *akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomMemberNotifyRet(DWord dwPlayerID, const SeRoomNtfCode &eNoticeCode, DWord dwRoomID, DWord dwRoomLeaderID, int iNum, std::vector< SeRoomMember > &akInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomLeaveRet(DWord dwPlayerID, DWord dwRoomID, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomReadyRet(DWord dwPlayerID, DWord dwRoomID, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomSwitchSeatRet(DWord dwPlayerID, const SeRoomJoinRetType &eType, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchRoomKickSomeoneRet(DWord dwPlayerID, DWord dwRoomID, int iseat, const SeRoomKickCode &eType, void *pkReceiver=NULL)
bool MatchServer::SendMT_AddIncompleteRace(const SeIncompleteRaceBaseInfo &oIncompleteRaceBaseInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_RemoveIncompleteRace(DWord dwRoomID, void *pkReceiver=NULL)
bool MatchServer::SendMT_ResIncmpRaceSeatBaseInfo(DWord dwPlayerID, DWord dwRoomID, int iNum, const SeSeatBaseInfo *oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_ResIncmpRaceSeatBaseInfo(DWord dwPlayerID, DWord dwRoomID, int iNum, std::vector< SeSeatBaseInfo > &oIncmpRaceBaseInfo, void *pkReceiver=NULL)
bool MatchServer::SendMT_ResIncompleteRaceList(DWord dwPlayerID, int iNum, const SeIncompleteRaceBaseInfo *akIncmpRaceList, void *pkReceiver=NULL)
bool MatchServer::SendMT_ResIncompleteRaceList(DWord dwPlayerID, int iNum, std::vector< SeIncompleteRaceBaseInfo > &akIncmpRaceList, void *pkReceiver=NULL)
bool MatchServer::SendMT_ReqMatchRep(DWord dwPlayerID, const MatchReqResult &ReqResult, void *pkReceiver=NULL)
bool MatchServer::SendMT_MatchCancelRep(DWord dwReceiver, const MatchCancelResult &CancelMatchResult, DWord dwPlayerID, void *pkReceiver=NULL)
bool MatchServer::SendMT_NotiMatcherPre(DWord dwPlayerID, DWord WaitID, DWord dwPlayerNum, void *pkReceiver=NULL)
bool MatchServer::SendMT_NotiMatcherResult(DWord ResultKind, DWord dwPlayerID, void *pkReceiver=NULL)
bool MatchServer::SendMT_SingleMatchConfirm(DWord PlayerID, bool BolConfirm, DWord PlayerIndex, DWord MaxPlayerNum, DWord dwReceiver, void *pkReceiver=NULL)
bool MatchServer::SendMTData(void *pkData, int iSize, void *pkReceiver)
bool MatchServer::SendMR_RegisterRet(const SeRegisterRet &eRet, bool bRunning, void *pkReceiver=NULL)
bool MatchServer::SendMR_HeartPackageRet(void *pkReceiver=NULL)
bool MatchServer::SendMR_ValidatePlayerInfo(DWord dwSessionID, DWord dwTime, DWord dwMapID, DWord dwKey, int iDifficulty, bool bSvrRace, const SePtlRaceBetInfo &kRaceBet, const SeMatchFightInfo &kFightInfo, DWord dwScoreCampA, DWord dwScoreCampB, DWord dwScoreRobot, bool bRobot, int iSize, const char *acData, void *pkReceiver=NULL)
bool MatchServer::SendMR_ValidatePlayerInfo(DWord dwSessionID, DWord dwTime, DWord dwMapID, DWord dwKey, int iDifficulty, bool bSvrRace, const SePtlRaceBetInfo &kRaceBet, const SeMatchFightInfo &kFightInfo, DWord dwScoreCampA, DWord dwScoreCampB, DWord dwScoreRobot, bool bRobot, int iSize, std::vector< char > &acData, void *pkReceiver=NULL)
bool MatchServer::SendMR_PlayerModifyInfo(DWord dwSessionID, int dwPlayerID, void *pkReceiver=NULL)
bool MatchServer::SendMR_UpdateMiscInfo(DWord dwPlayerID, int iValue, void *pkReceiver=NULL)
bool MatchServer::SendMR_ReconQuery(DWord dwRoomID, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iSeat, int iOffset, DWord dwFrame, void *pkReceiver=NULL)
bool MatchServer::SendMR_ViewQuery(DWord dwSession, DWord dwAreaID, DWord dwServerID, DWord dwPlayerID, int iViewDelay, void *pkReceiver=NULL)
bool MatchServer::SendMR_ViewValidOKRet(DWord dwSession, const SeViewInitInfo &kInitInfo, void *pkReceiver=NULL)
bool MatchServer::SendMR_ValidFailRet(DWord dwSession, DWord dwPlayerID, void *pkReceiver=NULL)
bool MatchServer::SendMR_RaceBuyRet(DWord dwSession, bool bSuccess, DWord dwPlayerID, int iType, DWord dwParam1, DWord dwParam2, void *pkReceiver=NULL)
bool MatchServer::SendMR_ReconPLayerName(DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
bool MatchServer::SendMRData(void *pkData, int iSize, void *pkReceiver)
DWord MatchServer::GetServerTime(void)
DWord MatchServer::GetServerID(void)
bool MatchServer::GetRandHttpSock(HSock &rkSock)
void MatchServer::PrintUpdateTime(DWord *pdwDecTime, int iNums)
int MatchServer::GetDebugLevel(void)
void MatchServer::SetDebugLevel(int iLevel)
int MatchServer::RandInt(void)
void MatchServer::OnSendTSQueryRoomListRet(HSock rkSock, DWord dwPlayerID, int iCurPage, int iMaxPage, const VRoomPtr &rkVRoomPtr)
void MatchServer::OnSendRSValidatePlayerInfo(const HSock &rkSock, const SeMatchRace *pkRace, bool bSvrRace, SePtlRaceBetInfo &rkInfo, VMatchRaceInfo &rakRaceInfo)
void MatchServer::InitFileData()
void MatchServer::InitRaceBetInfo()
void MatchServer::SaveRaceBetInfo()
void MatchServer::GetRaceBetInfo(SePtlRaceBetInfo &rkInfo)
void MatchServer::UpdateRaceBetInfo()
void MatchServer::UpdateRaceBetOddsEnd(SeRM_RaceEndReport *pkEndInfo)
bool MatchServer::SendHSData(void *pkData, int iSize, void *pkReceiver)
void MatchServer::SendHS_RegisterRet(const HSock &rkSock, int iRet)
void MatchServer::SendHS_HeartPackageRet(const HSock &rkSock)
void MatchServer::SendHS_SaveRaceRecord(const HSock &rkSock, const char *acRaceID, int iRaceServerID, int iRaceVersion)
void MatchServer::SendHS_BiVoiceUserLoginRet(const HSock &rkSock, int iPackKey, const char *pcAppKey, const char *pcAccount, int iReturn)
void MatchServer::SendHS_BiVoiceCreateChatRoom(const HSock &rkSock, int iPackKey, const char *pcAppKey, const char *pcRoomName, const char *pcHead, int iRoomType, int iScope, int iMaxUser)
void MatchServer::SendHS_BiVoiceDelChatRoom(const HSock &rkSock, int iRoomID)
void MatchServer::ProcessHSData(void *pkData, int iSize, void *pkSender=NULL)
void MatchServer::ProcessHS_Register(void *pkData, int iSize, void *pkSender=NULL)
void MatchServer::ProcessHS_HeartPackage(void *pkData, int iSize, void *pkSender=NULL)
void MatchServer::ProcessHS_BiVoiceUserLogin(void *pkData, int iSize, void *pkSender=NULL)
void MatchServer::ProcessHS_BiVoiceCreateChatRoomRet(void *pkData, int iSize, void *pkSender=NULL)
bool MatchServer::ProcessTMData(void *pkData, int iSize, void *pkSender=NULL)
bool MatchServer::PreProcessTM(void *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_Register(SeTM_Register *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_HeartPackage(SeTM_HeartPackage *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_CommMatchMsg(SeTM_CommMatchMsg *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_ReconQuery(SeTM_ReconQuery *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_ViewQuery(SeTM_ViewQuery *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_QueryRaceRoomList(SeTM_QueryRaceRoomList *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_QueryRaceBetInfo(SeTM_QueryRaceBetInfo *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_RaceBuyRet(SeTM_RaceBuyRet *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_PlayerLeave(SeTM_PlayerLeave *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchCreateRoom(SeTM_MatchCreateRoom *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchQueryRoomList(SeTM_MatchQueryRoomList *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchRoomJoin(SeTM_MatchRoomJoin *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchRoomLeave(SeTM_MatchRoomLeave *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchRoomReady(SeTM_MatchRoomReady *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchRoomSwitchSeat(SeTM_MatchRoomSwitchSeat *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchRoomKickSomeone(SeTM_MatchRoomKickSomeone *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchRoomInvite(SeTM_MatchRoomInvite *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchRoomInviteRsp(SeTM_MatchRoomInviteRsp *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_ReqIncompleteRaceKDA(SeTM_ReqIncompleteRaceKDA *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_ReqIncompleteRaceList(SeTM_ReqIncompleteRaceList *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_ReconPLayerName(SeTM_ReconPLayerName *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_PlayerMatchCancel(SeTM_PlayerMatchCancel *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_MatchConfirm(SeTM_MatchConfirm *pkData, int iSize, void *pkSender)
void MatchServer::ProcessTM_PlayerMatchReq(SeTM_PlayerMatchReq *pkData, int iSize, void *pkSender)
bool MatchServer::ProcessRMData(void *pkData, int iSize, void *pkSender=NULL)
bool MatchServer::PreProcessRM(void *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_Register(SeRM_Register *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_HeartPackage(SeRM_HeartPackage *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ValidatePlayerInfoRet(SeRM_ValidatePlayerInfoRet *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_CommRaceMsg(SeRM_CommRaceMsg *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_RaceGetCardInfo(SeRM_RaceGetCardInfo *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_UpdateMisc(SeRM_UpdateMisc *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_RaceEndReport(SeRM_RaceEndReport *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_RaceEndGuanqia(SeRM_RaceEndGuanqia *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_MatchRoomLoadInfo(SeRM_MatchRoomLoadInfo *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_RefreshConfigInfo(SeRM_RefreshConfigInfo *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ReconQuerySuccess(SeRM_ReconQuerySuccess *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ReconQueryFail(SeRM_ReconQueryFail *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ViewQuerySuccess(SeRM_ViewQuerySuccess *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ViewQueryFail(SeRM_ViewQueryFail *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ReconViewValid(SeRM_ReconViewValid *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ReLoadRoomInfoList(SeRM_ReLoadRoomInfoList *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_MatchRaceLoad(SeRM_MatchRaceLoad *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_RaceBuy(SeRM_RaceBuy *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_AddIncompleteRace(SeRM_AddIncompleteRace *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_RemoveIncompleteRace(SeRM_RemoveIncompleteRace *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_UpdateIncompleteRace(SeRM_UpdateIncompleteRace *pkData, int iSize, void *pkSender)
void MatchServer::ProcessRM_ResIncmpRaceSeatBaseInfo(SeRM_ResIncmpRaceSeatBaseInfo *pkData, int iSize, void *pkSender)
bool MatchServer::SendMW_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
bool MatchServer::SendMW_HeartPackage(void *pkReceiver=NULL)
bool MatchServer::SendMWData(void *pkData, int iSize, void *pkReceiver)
bool MatchServer::ProcessWMData(void *pkData, int iSize, void *pkSender=NULL)
bool MatchServer::PreProcessWM(void *pkData, int iSize, void *pkSender)
void MatchServer::ProcessWM_RegisterRet(SeWM_RegisterRet *pkData, int iSize, void *pkSender)
void MatchServer::ProcessWM_HeartPackageRet(SeWM_HeartPackageRet *pkData, int iSize, void *pkSender)
bool MatchServer::SendMBL_RaceMatchLoadDetail(DWord dwPlayerID, DWord dwMatchSession, const MatchType &eMatchType, int iEquipmentType, void *pkReceiver=NULL)
bool MatchServer::SendMBL_GetPlayerMatchValue(DWord dwPlayerID, const MatchType &eMatchType, void *pkReceiver=NULL)
bool MatchServer::SendMBL_BlockRoomInvite(DWord dwInviteeID, DWord dwRoomID, DWord dwPlayerID, const char *acName, void *pkReceiver=NULL)
bool MatchServer::SendMBLData(void *pkData, int iSize, void *pkReceiver)
bool MatchServer::ProcessBLMData(void *pkData, int iSize, void *pkSender=NULL)
bool MatchServer::PreProcessBLM(void *pkData, int iSize, void *pkSender)
void MatchServer::ProcessBLM_RaceMatchLoadDetailRet(SeBLM_RaceMatchLoadDetailRet *pkData, int iSize, void *pkSender)
void MatchServer::ProcessBLM_GetPlayerMatchValueRet(SeBLM_GetPlayerMatchValueRet *pkData, int iSize, void *pkSender)
bool MatchServer::SendMN_Register(DWord dwLoginMagic, DWord dwServerID, void *pkReceiver=NULL)
bool MatchServer::SendMN_HeartPackage(void *pkReceiver=NULL)
bool MatchServer::SendMN_MatchPunishNtf(DWord dwPlayerID, DWord dwMs, void *pkReceiver=NULL)
bool MatchServer::SendMNData(void *pkData, int iSize, void *pkReceiver)
bool MatchServer::ProcessNMData(void *pkData, int iSize, void *pkSender=NULL)
bool MatchServer::PreProcessNM(void *pkData, int iSize, void *pkSender)
void MatchServer::ProcessNM_RegisterRet(SeNM_RegisterRet *pkData, int iSize, void *pkSender)
void MatchServer::ProcessNM_HeartPackageRet(SeNM_HeartPackageRet *pkData, int iSize, void *pkSender)
void MatchServer::loadMatchDetail(DWord dwPlayerID, DWord dwMatchSession, MatchType eMatchType, int iEquipmentType, HSock kTownSock)
bool MatchServer::LoadConfig(const char *pcFile)
References SeVirtConnMgr::AddServerConn, SeMatchConfig::bMatchTimeoutRobot, SeMatchConfig::dwServerID, g_kVirtConnMgr, SeConfig::GetNetAddr, GetStr2ID, SeConfig::GetValue, SeMatchConfig::kAddrToHttpServer, SeMatchConfig::kLocalServer, SeConfig::Load, m_kConfig, m_pkNSConn, m_pkWSConn, SeLogError, SeLogInfo, SSI_NS, SSI_WS.
Referenced by Initialize.
void MatchServer::LoadDynamicConfig(void)
References SeMatchConfig::dwMasterRS, GetStr2ID, SeConfig::GetValue, SeMatchConfig::iDebugLevel, SeConfig::Load, m_kConfig, SeLogError, SeLogInfo.
Referenced by ExecuteAction, Initialize.
bool MatchServer::InitializeNet(void)
References SeNetAddr::acIP, SeNetAddr::iPort, SeMatchConfig::kAddrToHttpServer, SeMatchConfig::kLocalServer, m_kConfig, m_kNetMgr, SeLogError, SeLogInfo, SERVER_BUFFER_SIZE.
Referenced by Initialize.
void MatchServer::UpdatePackage()
Referenced by Update.
void MatchServer::UpdateTSTOMSTime(void)
References SeNetAddr::acIP, SeTown::dwLastRecvTime, SeTown::dwServerID, SeConnect::eState, g_kTownMgr, SeTownMgr::GetAllTS, GetID2Str, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kNetMgr, SeTown::pkConnect, SCS_TOWN_OK, SeLogError.
Referenced by Update.
void MatchServer::UpdateRSTOMSTime(void)
References SeNetAddr::acIP, SeRaceSvr::dwLastRecvTime, SeRaceSvr::dwServerID, SeConnect::eState, g_kRaceSvrMgr, SeRaceSvrMgr::GetAllRS, GetID2Str, GetServerTime, SeNetAddr::iPort, SeConnect::kNetAddr, SeConnect::kSock, m_kNetMgr, SeRaceSvr::pkConnect, SCS_RACESVR_OK, SeLogError.
Referenced by Update.
bool MatchServer::LoadConfig(const char *pcFile)
void MatchServer::LoadDynamicConfig(void)
bool MatchServer::InitializeNet(void)
void MatchServer::UpdatePackage()
void MatchServer::UpdateTSTOMSTime(void)
void MatchServer::UpdateRSTOMSTime(void)