LeagueRankTableMgr
std::map<unsigned int,LeagueRankTable*> LeagueRankTableMgr::m_kLeagueRankTableMap
Referenced by FillData, GetLeagueRankTable, GetLeagueRankTableMap, GetLeagueRankTableVec, ~LeagueRankTableMgr.
LeagueRankTableMgr * LeagueRankTableMgr::m_pkLeagueRankTableMgr
Referenced by Get, ReLoad.
LeagueRankTableMgr * LeagueRankTableMgr::Get()
References LeagueRankTableMgr, m_pkLeagueRankTableMgr.
Referenced by TableMgr::GetLeagueLevelByScore, ReLoad.
LeagueRankTableMgr * LeagueRankTableMgr::ReLoad()
References Get, m_pkLeagueRankTableMgr.
LeagueRankTableMgr::LeagueRankTableMgr()
References Load.
Referenced by Get.
LeagueRankTableMgr::~LeagueRankTableMgr()
References m_kLeagueRankTableMap.
const LeagueRankTable * LeagueRankTableMgr::GetLeagueRankTable(unsigned int iTypeID)
References m_kLeagueRankTableMap.
const std::map< unsigned int, LeagueRankTable * > & LeagueRankTableMgr::GetLeagueRankTableMap()
References m_kLeagueRankTableMap.
Referenced by TableMgr::GetLeagueLevelByScore.
TableResArray LeagueRankTableMgr::GetLeagueRankTableVec()
References m_kLeagueRankTableMap, TableResArray::pushBack.
bool LeagueRankTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by LeagueRankTableMgr.
void LeagueRankTableMgr::FillData(LeagueRankTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, LeagueRankTable::iLevel, LeagueRankTable::iMaxScore, LeagueRankTable::iMinScore, LeagueRankTable::iResetScore, LeagueRankTable::kiRankName, LeagueRankTable::kleagueimg, LeagueRankTable::kName, LeagueRankTable::kSleagueimg, m_kLeagueRankTableMap, LeagueRankTable::uiID, LeagueRankTable::uiType.
Referenced by Load.