SelHeroTableMgr
std::map<unsigned int,SelHeroTable*> SelHeroTableMgr::m_kSelHeroTableMap
Referenced by FillData, GetSelHeroTable, GetSelHeroTableMap, GetSelHeroTableVec, UpdateLanguadgeContent, ~SelHeroTableMgr.
SelHeroTableMgr * SelHeroTableMgr::m_pkSelHeroTableMgr
Referenced by Get, ReLoad.
SelHeroTableMgr * SelHeroTableMgr::Get()
References m_pkSelHeroTableMgr, SelHeroTableMgr.
Referenced by TableMgr::GetAllCanSelHeroSet, TableMgr::GetRaceHelpMasterySkillTypes, GlobalTableMgr::GetSelHeroTable, GlobalTableMgr::GetSelHeroTableMap, SeRaceRoomMgr::GetSelHeroTypeID, TableMgr::InitHeroPosIndex, SeRaceMgr::InitSelHeroList, SeRaceRoomMgr::IntoSelHero, TableMgr::LoadTable, ReLoad.
SelHeroTableMgr * SelHeroTableMgr::ReLoad()
References Get, m_pkSelHeroTableMgr.
Referenced by TableMgr::ReloadTable.
SelHeroTableMgr::SelHeroTableMgr()
References Load.
Referenced by Get.
SelHeroTableMgr::~SelHeroTableMgr()
References m_kSelHeroTableMap.
const SelHeroTable * SelHeroTableMgr::GetSelHeroTable(unsigned int iTypeID)
References m_kSelHeroTableMap.
Referenced by TableMgr::GetRaceHelpMasterySkillTypes, GlobalTableMgr::GetSelHeroTable.
const std::map< unsigned int, SelHeroTable * > & SelHeroTableMgr::GetSelHeroTableMap()
References m_kSelHeroTableMap.
Referenced by TableMgr::GetAllCanSelHeroSet, GlobalTableMgr::GetSelHeroTableMap, SeRaceRoomMgr::GetSelHeroTypeID, TableMgr::InitHeroPosIndex, SeRaceMgr::InitSelHeroList, SeRaceRoomMgr::IntoSelHero.
TableResArray SelHeroTableMgr::GetSelHeroTableVec()
References m_kSelHeroTableMap, TableResArray::pushBack.
void SelHeroTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, SelHeroTable::kName_China, SelHeroTable::kName_ChinaK, m_kSelHeroTableMap.
Referenced by Load.
bool SelHeroTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by SelHeroTableMgr.
void SelHeroTableMgr::FillData(SelHeroTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, SelHeroTable::fAmorAddUp, SelHeroTable::fAttackSpeed, SelHeroTable::fAttackSpeedAddUp, SelHeroTable::fControlAbility, SelHeroTable::fDifficult, SelHeroTable::fDifficulty, SelHeroTable::fDPSAbility, SelHeroTable::fHpLevelAdd, SelHeroTable::fMagicAbility, SelHeroTable::fMagicAddUp, SelHeroTable::fMpLevelAdd, SelHeroTable::fOrgAddUpDamage, SelHeroTable::fTankAbility, SelHeroTable::iBasicHeroPower, SelHeroTable::iBeginPos, SelHeroTable::iCardPosX, SelHeroTable::iHeroHonor, SelHeroTable::iLevelAddHeroPower, SelHeroTable::iName, SelHeroTable::iOpen, SelHeroTable::iSelPos, SelHeroTable::iTalent1, SelHeroTable::iTalent2, SelHeroTable::iTalent3, SelHeroTable::iTalent4, SelHeroTable::iTalent5, SelHeroTable::iTalent6, SelHeroTable::iWeapon, SelHeroTable::kDesc_China, SelHeroTable::kHeroBackFile, SelHeroTable::kIcon, SelHeroTable::kName_ChinaK, m_kSelHeroTableMap, SelHeroTable::uiCamp, SelHeroTable::uiDreamHeroID, SelHeroTable::uiHeroType, SelHeroTable::uiIdle, SelHeroTable::uiInto, SelHeroTable::uiLinkHero, SelHeroTable::uiLocation, SelHeroTable::uiProperty, SelHeroTable::uiReady, SelHeroTable::uiUnitID.
Referenced by Load.