RenJiActionsTableMgr
std::map<unsigned int,RenJiActionsTable*> RenJiActionsTableMgr::m_kRenJiActionsTableMap
Referenced by FillData, GetRenJiActionsTable, GetRenJiActionsTableMap, GetRenJiActionsTableVec, ~RenJiActionsTableMgr.
RenJiActionsTableMgr * RenJiActionsTableMgr::m_pkRenJiActionsTableMgr
Referenced by Get, ReLoad.
RenJiActionsTableMgr * RenJiActionsTableMgr::Get()
References m_pkRenJiActionsTableMgr, RenJiActionsTableMgr.
Referenced by ReLoad.
RenJiActionsTableMgr * RenJiActionsTableMgr::ReLoad()
References Get, m_pkRenJiActionsTableMgr.
RenJiActionsTableMgr::RenJiActionsTableMgr()
References Load.
Referenced by Get.
RenJiActionsTableMgr::~RenJiActionsTableMgr()
References m_kRenJiActionsTableMap.
const RenJiActionsTable * RenJiActionsTableMgr::GetRenJiActionsTable(unsigned int iTypeID)
References m_kRenJiActionsTableMap.
const std::map< unsigned int, RenJiActionsTable * > & RenJiActionsTableMgr::GetRenJiActionsTableMap()
References m_kRenJiActionsTableMap.
TableResArray RenJiActionsTableMgr::GetRenJiActionsTableVec()
References m_kRenJiActionsTableMap, TableResArray::pushBack.
bool RenJiActionsTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by RenJiActionsTableMgr.
void RenJiActionsTableMgr::FillData(RenJiActionsTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, RenJiActionsTable::frate, RenJiActionsTable::iDelTime, RenJiActionsTable::kDiscription, m_kRenJiActionsTableMap, RenJiActionsTable::uiActionType, RenJiActionsTable::uiActionUnit, RenJiActionsTable::uiID.
Referenced by Load.