SeXmlHandle
SeXmlNode* SeXmlHandle::node
Referenced by Child, ChildElement, CreatePath, FirstChild, FirstChildElement, GetPath, operator=, SeXmlHandle, ToElement, ToNode, ToText, ToUnknown.
SeXmlHandle::SeXmlHandle(SeXmlNode *_node)
Create a handle from any node (at any depth of the tree.) This can be a null pointer.
References node.
Referenced by Child, ChildElement, CreatePath, FirstChild, FirstChildElement, GetPath.
SeXmlHandle::SeXmlHandle(const SeXmlHandle &ref)
Copy constructor.
References node.
SeXmlHandle SeXmlHandle::operator=(const SeXmlHandle &ref)
References node.
SeXmlHandle SeXmlHandle::FirstChild() const
Return a handle to the first child node.
References SeXmlNode::FirstChild, node, SeXmlHandle.
Referenced by CreatePath, GetPath.
SeXmlHandle SeXmlHandle::FirstChild(const char *value) const
Return a handle to the first child node with the given name.
References SeXmlNode::FirstChild, node, SeXmlHandle.
SeXmlHandle SeXmlHandle::FirstChildElement() const
Return a handle to the first child element.
References SeXmlNode::FirstChildElement, node, SeXmlHandle.
SeXmlHandle SeXmlHandle::FirstChildElement(const char *value) const
Return a handle to the first child element with the given name.
References SeXmlNode::FirstChildElement, node, SeXmlHandle.
SeXmlHandle SeXmlHandle::Child(const char *value, int index) const
Return a handle to the "index" child with the given name. The first child is 0, the second 1, etc.
References SeXmlNode::FirstChild, SeXmlNode::NextSibling, node, SeXmlHandle.
SeXmlHandle SeXmlHandle::Child(int index) const
Return a handle to the "index" child. The first child is 0, the second 1, etc.
References SeXmlNode::FirstChild, SeXmlNode::NextSibling, node, SeXmlHandle.
SeXmlHandle SeXmlHandle::ChildElement(const char *value, int index) const
Return a handle to the "index" child element with the given name. The first child element is 0, the second 1, etc. Note that only SeXmlElements are indexed: other types are not counted.
References SeXmlNode::FirstChildElement, SeXmlNode::NextSiblingElement, node, SeXmlHandle.
SeXmlHandle SeXmlHandle::ChildElement(int index) const
Return a handle to the "index" child element. The first child element is 0, the second 1, etc. Note that only SeXmlElements are indexed: other types are not counted.
References SeXmlNode::FirstChildElement, SeXmlNode::NextSiblingElement, node, SeXmlHandle.
SeXmlHandle SeXmlHandle::FirstChild(const std::string &_value) const
References FirstChild.
Referenced by FirstChild.
SeXmlHandle SeXmlHandle::FirstChildElement(const std::string &_value) const
References FirstChildElement.
Referenced by FirstChildElement.
SeXmlHandle SeXmlHandle::Child(const std::string &_value, int index) const
References Child.
Referenced by Child.
SeXmlHandle SeXmlHandle::ChildElement(const std::string &_value, int index) const
References ChildElement.
Referenced by ChildElement.
SeXmlNode* SeXmlHandle::ToNode() const
Return the handle as a SeXmlNode. This may return null.
References node.
Referenced by Node.
SeXmlElement* SeXmlHandle::ToElement() const
Return the handle as a SeXmlElement. This may return null.
References node, SeXmlNode::ToElement.
Referenced by Element.
SeXmlText* SeXmlHandle::ToText() const
Return the handle as a SeXmlText. This may return null.
References node, SeXmlNode::ToText.
Referenced by Text.
SeXmlUnknown* SeXmlHandle::ToUnknown() const
Return the handle as a SeXmlUnknown. This may return null.
References node, SeXmlNode::ToUnknown.
Referenced by Unknown.
SeXmlNode* SeXmlHandle::Node() const
Deprecateduse ToNode. Return the handle as a SeXmlNode. This may return null.
References ToNode.
Referenced by CreatePath, GetPath.
SeXmlElement* SeXmlHandle::Element() const
Deprecateduse ToElement. Return the handle as a SeXmlElement. This may return null.
References ToElement.
SeXmlText* SeXmlHandle::Text() const
Deprecateduse ToText() Return the handle as a SeXmlText. This may return null.
References ToText.
SeXmlUnknown* SeXmlHandle::Unknown() const
Deprecateduse ToUnknown() Return the handle as a SeXmlUnknown. This may return null.
References ToUnknown.
SeXmlHandle SeXmlHandle::GetPath(const std::string &_value)
References node, SeXmlDocument::Parse, SeXmlHandle.
SeXmlHandle SeXmlHandle::GetPath(const SeXmlHandle &_handle)
References SeXmlElement::Attribute, SeXmlElement::FirstAttribute, FirstChild, SeXmlNode::FirstChildElement, SeXmlAttribute::Name, SeXmlAttribute::Next, SeXmlNode::NextSibling, Node, node, SeXmlHandle, SeXmlNode::ToElement, SeXmlElement::ToElement, SeXmlNode::Value, SeXmlAttribute::Value.
SeXmlHandle SeXmlHandle::CreatePath(const std::string &_value)
References node, SeXmlDocument::Parse, SeXmlHandle.
SeXmlHandle SeXmlHandle::CreatePath(const SeXmlHandle &_handle)
References SeXmlElement::Attribute, SeXmlElement::FirstAttribute, FirstChild, SeXmlNode::FirstChildElement, SeXmlNode::LinkEndChild, SeXmlAttribute::Name, SeXmlAttribute::Next, SeXmlNode::NextSibling, Node, node, SeXmlElement::SetAttribute, SeXmlNode::SeXmlElement, SeXmlHandle, SeXmlNode::ToElement, SeXmlElement::ToElement, SeXmlNode::Value, SeXmlAttribute::Value.