AccountLevelTableMgr
std::map<unsigned int,AccountLevelTable*> AccountLevelTableMgr::m_kAccountLevelTableMap
Referenced by FillData, GetAccountLevelTable, GetAccountLevelTableMap, GetAccountLevelTableVec, ~AccountLevelTableMgr.
AccountLevelTableMgr * AccountLevelTableMgr::m_pkAccountLevelTableMgr
Referenced by Get, ReLoad.
AccountLevelTableMgr * AccountLevelTableMgr::Get()
References AccountLevelTableMgr, m_pkAccountLevelTableMgr.
Referenced by ReLoad.
AccountLevelTableMgr * AccountLevelTableMgr::ReLoad()
References Get, m_pkAccountLevelTableMgr.
AccountLevelTableMgr::AccountLevelTableMgr()
References Load.
Referenced by Get.
AccountLevelTableMgr::~AccountLevelTableMgr()
References m_kAccountLevelTableMap.
const AccountLevelTable * AccountLevelTableMgr::GetAccountLevelTable(unsigned int iTypeID)
References m_kAccountLevelTableMap.
const std::map< unsigned int, AccountLevelTable * > & AccountLevelTableMgr::GetAccountLevelTableMap()
References m_kAccountLevelTableMap.
TableResArray AccountLevelTableMgr::GetAccountLevelTableVec()
References m_kAccountLevelTableMap, TableResArray::pushBack.
bool AccountLevelTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AccountLevelTableMgr.
void AccountLevelTableMgr::FillData(AccountLevelTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AccountLevelTable::iNums1, AccountLevelTable::iNums2, AccountLevelTable::iNums3, AccountLevelTable::iNums4, AccountLevelTable::iNums5, AccountLevelTable::kDesc1, AccountLevelTable::kDesc2, AccountLevelTable::kDesc3, AccountLevelTable::kDesc4, AccountLevelTable::kDesc5, m_kAccountLevelTableMap, AccountLevelTable::uiLevel, AccountLevelTable::uiReward1, AccountLevelTable::uiReward2, AccountLevelTable::uiReward3, AccountLevelTable::uiReward4, AccountLevelTable::uiReward5, AccountLevelTable::uiTotalExp.
Referenced by Load.