PerformanceTiming::CIntervalClone
const char * PerformanceTiming::CIntervalClone::m_strFolderName
Referenced by CPerformanceTiming::EnumerateIntervals, GetFolderName.
const char * PerformanceTiming::CIntervalClone::m_StrName
Referenced by CPerformanceTiming::EnumerateIntervals, Name.
bool PerformanceTiming::CIntervalClone::m_bLastFrameClosed
Referenced by CPerformanceTiming::EnumerateIntervals, IsLastFrameClosed.
UInt32 PerformanceTiming::CIntervalClone::m_iLastFrameIntervalEntries
Referenced by CPerformanceTiming::EnumerateIntervals, GetLastFrameIntervalEntries.
Float64 PerformanceTiming::CIntervalClone::m_dLastFrameIntervalTimeSec
Referenced by CPerformanceTiming::EnumerateIntervals, GetLastFrameIntervalTimeSec.
CRC_ID PerformanceTiming::CIntervalClone::m_crcID
Referenced by CPerformanceTiming::EnumerateIntervals, GetFolderNameCRC.
unsigned int PerformanceTiming::CIntervalClone::m_iKey
Referenced by CPerformanceTiming::EnumerateIntervals, PerformanceTiming::Pred_StatKey::operator().
PerformanceTiming::CIntervalClone::DECLARE_POOL(CIntervalClone)
PerformanceTiming::CIntervalClone::CIntervalClone()
PerformanceTiming::CIntervalClone::CIntervalClone(const char *rName, const char *pFolderName, Float64 fLastTimeSec, UInt32 iLastEntries, bool bClosed, CRC_ID crc)
Float64 PerformanceTiming::CIntervalClone::GetLastFrameIntervalTimeSec() const
References m_dLastFrameIntervalTimeSec.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
UInt32 PerformanceTiming::CIntervalClone::GetLastFrameIntervalEntries() const
References m_iLastFrameIntervalEntries.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
bool PerformanceTiming::CIntervalClone::IsLastFrameClosed() const
References m_bLastFrameClosed.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
CRC_ID PerformanceTiming::CIntervalClone::GetFolderNameCRC() const
References m_crcID.
Referenced by CIntervalCloneFolderSet::BuildFolderSets.
const char* PerformanceTiming::CIntervalClone::GetFolderName() const
References m_strFolderName.
Referenced by CIntervalCloneFolderSet::BuildFolderSets.
const char* PerformanceTiming::CIntervalClone::Name() const
References m_StrName.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
PerformanceTiming::CIntervalClone::DECLARE_POOL(CIntervalClone)
PerformanceTiming::CIntervalClone::CIntervalClone()
PerformanceTiming::CIntervalClone::CIntervalClone(const char *rName, const char *pFolderName, Float64 fLastTimeSec, UInt32 iLastEntries, bool bClosed, CRC_ID crc)
Float64 PerformanceTiming::CIntervalClone::GetLastFrameIntervalTimeSec() const
References m_dLastFrameIntervalTimeSec.
UInt32 PerformanceTiming::CIntervalClone::GetLastFrameIntervalEntries() const
References m_iLastFrameIntervalEntries.
bool PerformanceTiming::CIntervalClone::IsLastFrameClosed() const
References m_bLastFrameClosed.
CRC_ID PerformanceTiming::CIntervalClone::GetFolderNameCRC() const
References m_crcID.
const char* PerformanceTiming::CIntervalClone::GetFolderName() const
References m_strFolderName.
const char* PerformanceTiming::CIntervalClone::Name() const
References m_StrName.