WatchServer::CWatchServerMgr
MapAllWCS WatchServer::CWatchServerMgr::m_mWCS
Referenced by getWCS, onReqView, registerWCS, removeWCS.
MViewRaceData WatchServer::CWatchServerMgr::m_mAllViewRace
Referenced by addViewRace, delViewRace, getAllRaceCounts, onReqView, onReqViewList.
void WatchServer::CWatchServerMgr::registerWCS(SeWatchServerInfo *pSrv)
References WatchServer::SeWatchServerInfo::getServertID, m_mWCS.
Referenced by WatchServer::CWatchServer::Initialize.
void WatchServer::CWatchServerMgr::removeWCS(DWord srvID)
References m_mWCS.
SeWatchServerInfo * WatchServer::CWatchServerMgr::getWCS(DWord srvID)
References m_mWCS.
void WatchServer::CWatchServerMgr::addViewRace(const TeMD5 &rID, DWord dwSrvID)
References TeMD5::abyMD5, WatchServer::SeViewRaceData::dwServerID, GetMD52Str, WatchServer::SeViewRaceData::kRaceID, m_mAllViewRace, SeLogError.
Referenced by WatchServer::CWatchServer::onHandleNewRace.
void WatchServer::CWatchServerMgr::delViewRace(const TeMD5 &rID)
References m_mAllViewRace.
Referenced by WatchServer::CWatchServer::onDelRace.
DWord WatchServer::CWatchServerMgr::getAllRaceCounts() const
References m_mAllViewRace.
Referenced by WatchServer::CWatchServer::ShowConsoleTitle.
void WatchServer::CWatchServerMgr::onReqView(const SeTown *pTown, DWord dwPlayerId, const TeMD5 &rID)
References TeMD5::abyMD5, SePtlNetAddr::acIP, WatchServer::SeViewRaceData::dwServerID, g_kWatchServer, SePtlNetAddr::iPort, WatchServer::SeInnerConnect::kSock, m_mAllViewRace, m_mWCS, WatchServer::SeTown::pkConnect, SeLogDebug, SeLogError, WatchServer::CWatchServer::SendWCMST_ResView.
Referenced by WatchServer::CWatchServer::ProcessTWCMS_ReqView.
void WatchServer::CWatchServerMgr::onReqViewList(const SeTown *pTown, DWord dwPlayerId, DWord iPage)
References WatchServer::SeWatchConfig::dwViewListNum, g_kWatchServer, WatchServer::CWatchServer::GetWatchConfig, WatchServer::SeInnerConnect::kSock, m_mAllViewRace, WatchServer::SeTown::pkConnect, SeViewList::raceID, SeLogDebug, WatchServer::CWatchServer::SendWCMST_ResViewList.
Referenced by WatchServer::CWatchServer::ProcessTWCMS_ReqViewList.
void WatchServer::CWatchServerMgr::onRaceDetailInfoReq(const SeTown *pTown, DWord dwPlayerID, int page_number, int page_counts)
References TeMD5::abyMD5, SeRaceUserInfo::dwPlayerID, WatchServer::g_kRaceMgr, g_kWatchServer, WatchServer::CSeRaceMgr::GetRaceDetailMap, WatchServer::SeInnerConnect::kSock, WatchServer::SeTown::pkConnect, SRaceDetail::race_info, SeRaceDetailInfo::race_info, SeRaceInfo::race_user, SRaceDetail::rase_id, SeRaceDetailInfo::rase_id, SeLogDebug, WatchServer::CWatchServer::SendWCMST_ResRaceDetailInfo.
Referenced by WatchServer::CWatchServer::ProcessTWCMS_RaceDetailInfoReq.
void WatchServer::CWatchServerMgr::onRaceWatchUserSync(DWord dwPlayerID, DWord dwStateID)
References g_kWatchServer, WatchServer::CWatchServer::SendWCMSN_RaceWatchUserSync.
Referenced by WatchServer::CWatchServer::RaceWatchUserSync.