PropagandaTableMgr
std::map<unsigned int,PropagandaTable*> PropagandaTableMgr::m_kPropagandaTableMap
Referenced by FillData, GetPropagandaTable, GetPropagandaTableMap, GetPropagandaTableVec, UpdateLanguadgeContent, ~PropagandaTableMgr.
PropagandaTableMgr * PropagandaTableMgr::m_pkPropagandaTableMgr
Referenced by Get, ReLoad.
PropagandaTableMgr * PropagandaTableMgr::Get()
References m_pkPropagandaTableMgr, PropagandaTableMgr.
Referenced by GlobalTableMgr::GetPropagandaTable, TableMgr::LoadTable, ReLoad, TableMgr::UpdateLanguageContent.
PropagandaTableMgr * PropagandaTableMgr::ReLoad()
References Get, m_pkPropagandaTableMgr.
PropagandaTableMgr::PropagandaTableMgr()
References Load.
Referenced by Get.
PropagandaTableMgr::~PropagandaTableMgr()
References m_kPropagandaTableMap.
const PropagandaTable * PropagandaTableMgr::GetPropagandaTable(unsigned int iTypeID)
References m_kPropagandaTableMap.
Referenced by GlobalTableMgr::GetPropagandaTable.
const std::map< unsigned int, PropagandaTable * > & PropagandaTableMgr::GetPropagandaTableMap()
References m_kPropagandaTableMap.
TableResArray PropagandaTableMgr::GetPropagandaTableVec()
References m_kPropagandaTableMap, TableResArray::pushBack.
void PropagandaTableMgr::UpdateLanguadgeContent()
References TableMgr::Get, TableMgr::GetText, PropagandaTable::kContent, PropagandaTable::kContentK, PropagandaTable::kTalkContent, PropagandaTable::kTalkContentK, m_kPropagandaTableMap.
Referenced by Load, TableMgr::UpdateLanguageContent.
bool PropagandaTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse, UpdateLanguadgeContent.
Referenced by PropagandaTableMgr.
void PropagandaTableMgr::FillData(PropagandaTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, PropagandaTable::kContentK, PropagandaTable::kIconRes, PropagandaTable::kTalkContentK, PropagandaTable::kVoiceID, m_kPropagandaTableMap, PropagandaTable::uiContentType, PropagandaTable::uiTypeID, PropagandaTable::uiYellingProerty.
Referenced by Load.