AvatarAnimationTableMgr
std::map<unsigned int,AvatarAnimationTable*> AvatarAnimationTableMgr::m_kAvatarAnimationTableMap
Referenced by FillData, GetAvatarAnimationTable, GetAvatarAnimationTableMap, GetAvatarAnimationTableVec, ~AvatarAnimationTableMgr.
AvatarAnimationTableMgr * AvatarAnimationTableMgr::m_pkAvatarAnimationTableMgr
Referenced by Get, ReLoad.
AvatarAnimationTableMgr * AvatarAnimationTableMgr::Get()
References AvatarAnimationTableMgr, m_pkAvatarAnimationTableMgr.
Referenced by ReLoad.
AvatarAnimationTableMgr * AvatarAnimationTableMgr::ReLoad()
References Get, m_pkAvatarAnimationTableMgr.
Referenced by TableMgr::ReloadTable.
AvatarAnimationTableMgr::AvatarAnimationTableMgr()
References Load.
Referenced by Get.
AvatarAnimationTableMgr::~AvatarAnimationTableMgr()
References m_kAvatarAnimationTableMap.
const AvatarAnimationTable * AvatarAnimationTableMgr::GetAvatarAnimationTable(unsigned int iTypeID)
References m_kAvatarAnimationTableMap.
const std::map< unsigned int, AvatarAnimationTable * > & AvatarAnimationTableMgr::GetAvatarAnimationTableMap()
References m_kAvatarAnimationTableMap.
TableResArray AvatarAnimationTableMgr::GetAvatarAnimationTableVec()
References m_kAvatarAnimationTableMap, TableResArray::pushBack.
bool AvatarAnimationTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by AvatarAnimationTableMgr.
void AvatarAnimationTableMgr::FillData(AvatarAnimationTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, AvatarAnimationTable::kName_China, AvatarAnimationTable::kResPath, AvatarAnimationTable::kStateName, m_kAvatarAnimationTableMap, AvatarAnimationTable::uiAniType, AvatarAnimationTable::uiAvatarModelID.
Referenced by Load.