Json::OurReader
TokenType
typedef std::deque<ErrorInfo> Json::OurReader::Errors
typedef std::stack<Value*> Json::OurReader::Nodes
typedef char Json::OurReader::Char
typedef const Char* Json::OurReader::Location
Nodes Json::OurReader::nodes_
Referenced by currentValue, parse, readArray, readObject.
Errors Json::OurReader::errors_
Referenced by addError, getFormattedErrorMessages, getStructuredErrors, good, parse, pushError, recoverFromError.
std::string Json::OurReader::document_
Location Json::OurReader::begin_
Referenced by decodeDouble, decodeNumber, decodeString, getLocationLineAndColumn, getStructuredErrors, parse, pushError, readArray, readObject, readValue.
Location Json::OurReader::end_
Referenced by getLocationLineAndColumn, getNextChar, match, parse, pushError, readCppStyleComment, readCStyleComment, readNumber, readString, readStringSingleQuote, skipSpaces.
Location Json::OurReader::current_
Referenced by getNextChar, match, parse, readArray, readComment, readCppStyleComment, readCStyleComment, readNumber, readString, readStringSingleQuote, readToken, readValue, skipSpaces.
Location Json::OurReader::lastValueEnd_
Referenced by parse, readComment, readValue.
Value* Json::OurReader::lastValue_
Referenced by addComment, parse, readValue.
std::string Json::OurReader::commentsBefore_
Referenced by addComment, parse, readValue.
int Json::OurReader::stackDepth_
Referenced by parse, readValue.
OurFeatures const Json::OurReader::features_
Referenced by parse, readObject, readToken, readValue, skipCommentTokens.
bool Json::OurReader::collectComments_
Referenced by addComment, parse, readComment, readValue.
Json::OurReader::OurReader(OurFeatures const &features)
bool Json::OurReader::parse(const char *beginDoc, const char *endDoc, Value &root, bool collectComments=true)
References addError, Json::OurFeatures::allowComments_, begin_, collectComments_, Json::commentAfter, commentsBefore_, current_, Json::OurReader::Token::end_, end_, errors_, Json::OurFeatures::failIfExtra_, features_, Json::Value::isArray, Json::Value::isObject, lastValue_, lastValueEnd_, nodes_, readValue, Json::Value::setComment, skipCommentTokens, stackDepth_, Json::OurReader::Token::start_, Json::OurFeatures::strictRoot_, tokenEndOfStream, tokenError, Json::OurReader::Token::type_.
Referenced by Json::OurCharReader::parse.
std::string Json::OurReader::getFormattedErrorMessages() const
References errors_, Json::OurReader::ErrorInfo::extra_, getLocationLineAndColumn, Json::OurReader::ErrorInfo::message_, Json::OurReader::Token::start_, Json::OurReader::ErrorInfo::token_.
Referenced by Json::OurCharReader::parse.
std::vector< OurReader::StructuredError > Json::OurReader::getStructuredErrors() const
References begin_, Json::OurReader::Token::end_, errors_, Json::OurReader::StructuredError::message, Json::OurReader::ErrorInfo::message_, Json::OurReader::StructuredError::offset_limit, Json::OurReader::StructuredError::offset_start, Json::OurReader::Token::start_, Json::OurReader::ErrorInfo::token_.
bool Json::OurReader::pushError(const Value &value, const std::string &message)
References begin_, Json::OurReader::Token::end_, end_, errors_, Json::OurReader::ErrorInfo::extra_, Json::Value::getOffsetLimit, Json::Value::getOffsetStart, Json::OurReader::ErrorInfo::message_, Json::OurReader::Token::start_, Json::OurReader::ErrorInfo::token_, tokenError, Json::OurReader::Token::type_.
bool Json::OurReader::pushError(const Value &value, const std::string &message, const Value &extra)
References begin_, Json::OurReader::Token::end_, end_, errors_, Json::OurReader::ErrorInfo::extra_, Json::Value::getOffsetLimit, Json::Value::getOffsetStart, Json::OurReader::ErrorInfo::message_, Json::OurReader::Token::start_, Json::OurReader::ErrorInfo::token_, tokenError, Json::OurReader::Token::type_.
bool Json::OurReader::good() const
References errors_.
Json::OurReader::OurReader(OurReader const &)
void Json::OurReader::operator=(OurReader const &)
bool Json::OurReader::readToken(Token &token)
References Json::OurFeatures::allowSingleQuotes_, Json::OurFeatures::allowSpecialFloats_, current_, Json::OurReader::Token::end_, features_, getNextChar, match, readComment, readNumber, readString, readStringSingleQuote, skipSpaces, Json::OurReader::Token::start_, tokenArrayBegin, tokenArrayEnd, tokenArraySeparator, tokenComment, tokenEndOfStream, tokenError, tokenFalse, tokenMemberSeparator, tokenNaN, tokenNegInf, tokenNull, tokenNumber, tokenObjectBegin, tokenObjectEnd, tokenPosInf, tokenString, tokenTrue, Json::OurReader::Token::type_.
Referenced by readArray, readObject, recoverFromError, skipCommentTokens.
void Json::OurReader::skipSpaces()
References current_, end_.
Referenced by readArray, readToken.
bool Json::OurReader::match(Location pattern, int patternLength)
References current_, end_.
Referenced by readToken.
bool Json::OurReader::readComment()
References addComment, collectComments_, Json::commentAfterOnSameLine, Json::commentBefore, Json::containsNewLine, current_, getNextChar, lastValueEnd_, readCppStyleComment, readCStyleComment.
Referenced by readToken.
bool Json::OurReader::readCStyleComment()
References current_, end_, getNextChar.
Referenced by readComment.
bool Json::OurReader::readCppStyleComment()
References current_, end_, getNextChar.
Referenced by readComment.
bool Json::OurReader::readString()
References current_, end_, getNextChar.
Referenced by readToken.
bool Json::OurReader::readStringSingleQuote()
References current_, end_, getNextChar.
Referenced by readToken.
bool Json::OurReader::readNumber(bool checkInf)
References current_, end_.
Referenced by readToken.
bool Json::OurReader::readValue()
References addError, Json::OurFeatures::allowDroppedNullPlaceholders_, begin_, collectComments_, Json::commentBefore, commentsBefore_, current_, currentValue, decodeNumber, decodeString, Json::OurReader::Token::end_, features_, lastValue_, lastValueEnd_, readArray, readObject, Json::Value::setComment, Json::Value::setOffsetLimit, Json::Value::setOffsetStart, skipCommentTokens, stackDepth_, Json::OurFeatures::stackLimit_, Json::OurReader::Token::start_, Json::Value::swapPayload, Json::throwRuntimeError, tokenArrayBegin, tokenArrayEnd, tokenArraySeparator, tokenFalse, tokenNaN, tokenNegInf, tokenNull, tokenNumber, tokenObjectBegin, tokenObjectEnd, tokenPosInf, tokenString, tokenTrue, Json::OurReader::Token::type_.
Referenced by parse, readArray, readObject.
bool Json::OurReader::readObject(Token &token)
References addErrorAndRecover, Json::OurFeatures::allowNumericKeys_, Json::Value::asString, begin_, currentValue, decodeNumber, decodeString, features_, nodes_, Json::objectValue, readToken, readValue, recoverFromError, Json::OurFeatures::rejectDupKeys_, Json::Value::setOffsetStart, Json::OurReader::Token::start_, Json::Value::swapPayload, Json::throwRuntimeError, tokenArraySeparator, tokenComment, tokenMemberSeparator, tokenNumber, tokenObjectEnd, tokenString, Json::OurReader::Token::type_.
Referenced by readValue.
bool Json::OurReader::readArray(Token &token)
References addErrorAndRecover, Json::arrayValue, begin_, current_, currentValue, nodes_, readToken, readValue, recoverFromError, Json::Value::setOffsetStart, skipSpaces, Json::OurReader::Token::start_, Json::Value::swapPayload, tokenArrayEnd, tokenArraySeparator, tokenComment, Json::OurReader::Token::type_.
Referenced by readValue.
bool Json::OurReader::decodeNumber(Token &token)
References begin_, currentValue, Json::OurReader::Token::end_, Json::Value::setOffsetLimit, Json::Value::setOffsetStart, Json::OurReader::Token::start_, Json::Value::swapPayload.
Referenced by readObject, readValue.
bool Json::OurReader::decodeNumber(Token &token, Value &decoded)
References decodeDouble, Json::OurReader::Token::end_, Json::Value::maxInt, Json::Value::maxLargestUInt, Json::Value::minLargestInt, Json::OurReader::Token::start_.
bool Json::OurReader::decodeString(Token &token)
References begin_, currentValue, Json::OurReader::Token::end_, Json::Value::setOffsetLimit, Json::Value::setOffsetStart, Json::OurReader::Token::start_, Json::Value::swapPayload.
Referenced by readObject, readValue.
bool Json::OurReader::decodeString(Token &token, std::string &decoded)
References addError, Json::codePointToUTF8, decodeUnicodeCodePoint, Json::OurReader::Token::end_, Json::OurReader::Token::start_.
bool Json::OurReader::decodeDouble(Token &token)
References begin_, currentValue, Json::OurReader::Token::end_, Json::Value::setOffsetLimit, Json::Value::setOffsetStart, Json::OurReader::Token::start_, Json::Value::swapPayload.
Referenced by decodeNumber.
bool Json::OurReader::decodeDouble(Token &token, Value &decoded)
References addError, Json::OurReader::Token::end_, Json::OurReader::Token::start_.
bool Json::OurReader::decodeUnicodeCodePoint(Token &token, Location &current, Location end, unsigned int &unicode)
References addError, decodeUnicodeEscapeSequence.
Referenced by decodeString.
bool Json::OurReader::decodeUnicodeEscapeSequence(Token &token, Location &current, Location end, unsigned int &unicode)
References addError.
Referenced by decodeUnicodeCodePoint.
bool Json::OurReader::addError(const std::string &message, Token &token, Location extra=0)
References errors_, Json::OurReader::ErrorInfo::extra_, Json::OurReader::ErrorInfo::message_, Json::OurReader::ErrorInfo::token_.
Referenced by addErrorAndRecover, decodeDouble, decodeString, decodeUnicodeCodePoint, decodeUnicodeEscapeSequence, parse, readValue.
bool Json::OurReader::recoverFromError(TokenType skipUntilToken)
References errors_, readToken, tokenEndOfStream.
Referenced by addErrorAndRecover, readArray, readObject.
bool Json::OurReader::addErrorAndRecover(const std::string &message, Token &token, TokenType skipUntilToken)
References addError, recoverFromError.
Referenced by readArray, readObject.
void Json::OurReader::skipUntilSpace()
Value & Json::OurReader::currentValue()
References nodes_.
Referenced by decodeDouble, decodeNumber, decodeString, readArray, readObject, readValue.
OurReader::Char Json::OurReader::getNextChar()
References current_, end_.
Referenced by readComment, readCppStyleComment, readCStyleComment, readString, readStringSingleQuote, readToken.
void Json::OurReader::getLocationLineAndColumn(Location location, int &line, int &column) const
References begin_, end_.
Referenced by getFormattedErrorMessages, getLocationLineAndColumn.
std::string Json::OurReader::getLocationLineAndColumn(Location location) const
References getLocationLineAndColumn.
void Json::OurReader::addComment(Location begin, Location end, CommentPlacement placement)
References collectComments_, Json::commentAfterOnSameLine, commentsBefore_, lastValue_, Json::normalizeEOL, Json::Value::setComment.
Referenced by readComment.
void Json::OurReader::skipCommentTokens(Token &token)
References Json::OurFeatures::allowComments_, features_, readToken, tokenComment, Json::OurReader::Token::type_.
Referenced by parse, readValue.