MapMiscTableMgr
std::map<unsigned int,MapMiscTable*> MapMiscTableMgr::m_kMapMiscTableMap
Referenced by FillData, GetMapMiscTable, GetMapMiscTableMap, GetMapMiscTableVec, ~MapMiscTableMgr.
MapMiscTableMgr * MapMiscTableMgr::m_pkMapMiscTableMgr
Referenced by Get, ReLoad.
MapMiscTableMgr * MapMiscTableMgr::Get()
References m_pkMapMiscTableMgr, MapMiscTableMgr.
Referenced by GlobalTableMgr::GetMapMiscTable, ReLoad.
MapMiscTableMgr * MapMiscTableMgr::ReLoad()
References Get, m_pkMapMiscTableMgr.
MapMiscTableMgr::MapMiscTableMgr()
References Load.
Referenced by Get.
MapMiscTableMgr::~MapMiscTableMgr()
References m_kMapMiscTableMap.
const MapMiscTable * MapMiscTableMgr::GetMapMiscTable(unsigned int iTypeID)
References m_kMapMiscTableMap.
Referenced by GlobalTableMgr::GetMapMiscTable.
const std::map< unsigned int, MapMiscTable * > & MapMiscTableMgr::GetMapMiscTableMap()
References m_kMapMiscTableMap.
TableResArray MapMiscTableMgr::GetMapMiscTableVec()
References m_kMapMiscTableMap, TableResArray::pushBack.
bool MapMiscTableMgr::Load()
References TiXmlDocument::Error, TiXmlDocument::ErrorDesc, FillData, TiXmlNode::FirstChildElement, TableMgr::Get, TableMgr::GetTableLoader, TableLoader::LoadTable, TiXmlNode::NextSiblingElement, TiXmlDocument::Parse.
Referenced by MapMiscTableMgr.
void MapMiscTableMgr::FillData(MapMiscTable *row, TiXmlElement *element)
References TiXmlElement::Attribute, MapMiscTable::fTowerAlertAlpha, MapMiscTable::fTowerAlertRange, MapMiscTable::iGodBarrackPos, MapMiscTable::iGodBarrackRot, MapMiscTable::iGodDownGankFinalPoint, MapMiscTable::iGodGankMiddlePoint, MapMiscTable::iGodGankPoint, MapMiscTable::iGodMiddleGankFinalPoint, MapMiscTable::iGodOtherBuilingPos, MapMiscTable::iGodTopGankFinalPoint, MapMiscTable::iGodTowerPos, MapMiscTable::iGodTowerRot, MapMiscTable::iHumenBarrackPos, MapMiscTable::iHumenBarrackRot, MapMiscTable::iHumenDownGankFinalPoint, MapMiscTable::iHumenGankMiddlePoint, MapMiscTable::iHumenGankPoint, MapMiscTable::iHumenMiddleGankFinalPoint, MapMiscTable::iHumenOtherBuilingPos, MapMiscTable::iHumenTopGankFinalPoint, MapMiscTable::iHumenTowerPos, MapMiscTable::iHumenTowerRot, MapMiscTable::iMapHomePos, MapMiscTable::iMapHomeRot, m_kMapMiscTableMap, MapMiscTable::uiMapTypeID.
Referenced by Load.