TaskMgr
VTaskInfo TaskMgr::m_akVTask
Referenced by Finalize, GetTaskVInfo, loadData.
SePlayer & TaskMgr::m_Player
Referenced by CheckReceiveCondition, getOwner, GetTaskReward, RefreshTask, ResetTask, SettleTask.
SeDBCharTask TaskMgr::m_TemData
Referenced by CharTaskInfoInsert, CharTaskInfoUpdate.
TaskMgr::TaskMgr(SePlayer &m_Player)
TaskMgr::~TaskMgr()
void TaskMgr::QueryTaskInfo(VPtlTask &vTaskInfo)
References GetTaskVInfo, RefreshTask.
SeTaskAckCode TaskMgr::ResetTask(E_TASKINFOTABLE_TYPE eType)
References CharTaskInfoUpdate, CurrTaskInfo, g_kWorldServer, SePlayer::GetID, GetNextTaskInfo, SePlayer::GetTaskResetCount, SeTaskInfo::iConditionNum, TaskInfoTable::iLimit, m_Player, SeTaskInfo::pkRes, WorldServer::SendDBServer_CharUpdateTaskResetCount, SePlayer::SetTaskResetCount, STAC_COUNT_NOT_ENOUGH, STAC_COUNT_USE_OUT, STAC_FORBID_RESET, STAC_SUCCESS, STC_RESET_TIME_PER_DAY, TASKINFO_CHANGE_FOU, TASKINFO_TYPE_RONGYU, TASKINFO_TYPE_SHENGCHANG, TASKINFO_TYPE_YINGXIONG, TASKINFO_TYPE_ZHANYI, TASKINFO_TYPE_ZHUXIAN, TaskInfoTable::uiChange.
SeTaskAckCode TaskMgr::GetTaskReward(E_TASKINFOTABLE_TYPE eType)
References CItemMgr::AddItem, CharTaskInfoUpdate, CMT_EXP, CMT_GOLD, CurrTaskInfo, SeTaskInfo::eState, SeTaskInfo::eTaskType, TaskInfoTable::fValue, SePlayer::GetExp, SePlayer::GetGold, SePlayer::GetItemMgr, GetNextTaskInfo, TaskInfoTable::iAwardExp, TaskInfoTable::iAwardGold, TaskInfoTable::iAwardItem, SeTaskInfo::iConditionNum, TaskInfoTable::iCondValue1, SeTaskInfo::ifinishCount, TaskInfoTable::iLimit, m_Player, SePlayer::NotifyOwnMoney, SeTaskInfo::pkRes, STAC_COUNT_NOT_ENOUGH, STAC_NOT_FINISH, STAC_SUCCESS, STS_AWARD, STS_COMPLETE, TASK_REWARD_LIST_LENGTH, TASKINFO_TYPE_ZHUXIAN, SePlayer::UpdateCharMisc.
const SeTaskInfo * TaskMgr::GetCurrTaskInfo(E_TASKINFOTABLE_TYPE eType)
References CurrTaskInfo.
bool TaskMgr::GetNextTaskInfo(SeTaskInfo *skTask, bool bIsDiffDay=false)
References SeTaskInfo::eTaskType, GetDailyTaskNextTask, GetMainTaskNextTask, GetWinTaskNextTask, TASKINFO_TYPE_RONGYU, TASKINFO_TYPE_SHENGCHANG, TASKINFO_TYPE_YINGXIONG, TASKINFO_TYPE_ZHANYI, TASKINFO_TYPE_ZHUXIAN.
Referenced by GetTaskReward, RefreshTask, ResetTask.
bool TaskMgr::RefreshTask()
References SePlayer::AddPlayerMail, CharTaskInfoInsert, CharTaskInfoUpdate, CheckReceiveCondition, SeTaskInfo::eState, SeTaskInfo::eTaskType, g_kWorldServer, GetDailyTaskNextTask, SePlayer::GetID, GetNextTaskInfo, SePlayer::GetTaskResetTime, GetTaskVInfo, GetWinTaskNextTask, SeTaskInfo::iConditionNum, InitPlayerVTaskInfo, IsDiffDay, m_Player, NowTime, SeTaskInfo::pkRes, WorldServer::SendDBServer_CharUpdateTaskResetTime, SePlayer::SetTaskResetCount, SePlayer::SetTaskResetTime, STS_COMPLETE, STS_DOING, STS_WAIT_CONDITION, TASKINFO_TYPE_RONGYU, TASKINFO_TYPE_SHENGCHANG, TASKINFO_TYPE_YINGXIONG, TASKINFO_TYPE_ZHANYI, TASKINFO_TYPE_ZHUXIAN.
Referenced by SePlayer::OperateLoading, QueryTaskInfo.
void TaskMgr::RefreshTaskByEvent()
References CharTaskInfoUpdate, CheckReceiveCondition, GetTaskVInfo, STS_DOING, STS_WAIT_CONDITION, TASKINFO_TYPE_RONGYU, TASKINFO_TYPE_SHENGCHANG, TASKINFO_TYPE_YINGXIONG, TASKINFO_TYPE_ZHANYI, TASKINFO_TYPE_ZHUXIAN.
void TaskMgr::SettleTask(E_TASKINFOTABLE_CONDITON eConditonType, DWord dwMapId, DWord value, DWord param1)
References GetTaskVInfo, SePlayer::IsPassChapter, m_Player, STS_COMPLETE, STS_DOING, TASK_MAP_LIST_LENGTH, TASKINFO_CONDITON_CANTUAN, TASKINFO_CONDITON_CANYUYOUXI, TASKINFO_CONDITON_CHENGSHANG, TASKINFO_CONDITON_CUIHUIFANGYUTA, TASKINFO_CONDITON_DUIWUWUSIWANGTONGGUAN, TASKINFO_CONDITON_FUJIA, TASKINFO_CONDITON_GETGOLD, TASKINFO_CONDITON_GUDAN, TASKINFO_CONDITON_JIESUOPIFU, TASKINFO_CONDITON_JIESUOYINGXIONG, TASKINFO_CONDITON_JISHA, TASKINFO_CONDITON_KILLNPC, TASKINFO_CONDITON_LIANSHA, TASKINFO_CONDITON_LIANXUSHENGLI, TASKINFO_CONDITON_MVP, TASKINFO_CONDITON_POFANG, TASKINFO_CONDITON_SHENZHU, TASKINFO_CONDITON_SHIYONGA, TASKINFO_CONDITON_SHIYONGB, TASKINFO_CONDITON_SHIYONGC, TASKINFO_CONDITON_SHIYONGD, TASKINFO_CONDITON_SHIYONGE, TASKINFO_CONDITON_SHOUSHENG, TASKINFO_CONDITON_SHUCHU, TASKINFO_CONDITON_TEAMJOIN, TASKINFO_CONDITON_TEAMMATCHINGWIN, TASKINFO_CONDITON_TIANTIJIFEN, TASKINFO_CONDITON_TIANTILIANXUSHENGLI, TASKINFO_CONDITON_TIANTISHENGLI, TASKINFO_CONDITON_TONGGUANDITU, TASKINFO_CONDITON_WANCHENGZHANGJIE, TASKINFO_CONDITON_WINA, TASKINFO_CONDITON_WINB, TASKINFO_CONDITON_WINC, TASKINFO_CONDITON_WIND, TASKINFO_CONDITON_WINE, TASKINFO_CONDITON_ZHANGHAODENGJI, TASKINFO_CONDITON_ZHANJIANG, TASKINFO_CONDITON_ZHIDINGSHIJIANTONGGUAN, TASKINFO_CONDITON_ZHUGONG, TASKINFO_CONDITON_ZIJIWUSIWANGTONGGUAN, TASKINFO_CONDITON_ZUDUITIANTISHENGLI.
Referenced by CItemMgr::AddItem, BlockServer::CheckTaskGuanqia, BlockServer::CheckTaskRace, BlockServer::ProcessRBL_UpdateScore, HeroMgr::unlockHero.
void TaskMgr::CharTaskInfoUpdate(const SeTaskInfo *pkTaskInfo)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataUpdate, g_kCharTaskStrategy, getOwner, SeTaskInfo::GetTaskInfo, m_TemData.
Referenced by GetTaskReward, RefreshTask, RefreshTaskByEvent, ResetTask.
void TaskMgr::CharTaskInfoInsert(const SeTaskInfo *pkTaskInfo)
References DefaultPlayerDataStrategy< TABLE, T, DATA >::dataInsert, g_kCharTaskStrategy, getOwner, SeTaskInfo::GetTaskInfo, m_TemData.
Referenced by InitPlayerVTaskInfo, RefreshTask.
SePlayer & TaskMgr::getOwner()
References m_Player.
Referenced by CharTaskInfoInsert, CharTaskInfoUpdate.
VTaskInfo & TaskMgr::GetTaskVInfo()
References m_akVTask.
Referenced by CurrTaskInfo, InitPlayerVTaskInfo, QueryTaskInfo, RefreshTask, RefreshTaskByEvent, SettleTask.
void TaskMgr::loadData(const SeDBCharTask &skTaskInfo)
References SeTaskInfo::Copy, SeTaskInfo::eTaskType, TaskInfoTableMgr::Get, TaskInfoTableMgr::GetTaskInfoTable, m_akVTask, SeTaskInfo::pkRes.
void TaskMgr::Finalize()
References m_akVTask.
TaskMgr::TaskMgr(SePlayer &m_Player)
TaskMgr::~TaskMgr()
void TaskMgr::QueryTaskInfo(VPtlTask &vTaskInfo)
SeTaskAckCode TaskMgr::ResetTask(E_TASKINFOTABLE_TYPE eType)
SeTaskAckCode TaskMgr::GetTaskReward(E_TASKINFOTABLE_TYPE eType)
const SeTaskInfo* TaskMgr::GetCurrTaskInfo(E_TASKINFOTABLE_TYPE eType)
bool TaskMgr::GetNextTaskInfo(SeTaskInfo *skTask, bool bIsDiffDay=false)
bool TaskMgr::RefreshTask()
void TaskMgr::RefreshTaskByEvent()
void TaskMgr::SettleTask(E_TASKINFOTABLE_CONDITON eConditonType, DWord dwMapId, DWord value, DWord param1)
void TaskMgr::CharTaskInfoUpdate(const SeTaskInfo *pkTaskInfo)
void TaskMgr::CharTaskInfoInsert(const SeTaskInfo *pkTaskInfo)
SePlayer& TaskMgr::getOwner()
VTaskInfo& TaskMgr::GetTaskVInfo()
void TaskMgr::loadData(const SeDBCharTask &skTaskInfo)
void TaskMgr::Finalize()
bool TaskMgr::InitPlayerVTaskInfo()
References CharTaskInfoInsert, SeTaskInfo::eTaskType, GetDailyTaskNextTask, GetMainTaskNextTask, GetTaskVInfo, GetWinTaskNextTask, TASKINFO_TYPE_RONGYU, TASKINFO_TYPE_SHENGCHANG, TASKINFO_TYPE_YINGXIONG, TASKINFO_TYPE_ZHANYI, TASKINFO_TYPE_ZHUXIAN.
Referenced by RefreshTask.
bool TaskMgr::CheckReceiveCondition(const TaskInfoTable *pkTaskTable)
References SePlayer::GetCharLevel, SePlayer::GetEquipFightScore, SePlayer::GetLadder, m_Player, TASKINFO_RECEIVECONDITION_DENGJI, TASKINFO_RECEIVECONDITION_PVEZHANGJIE, TASKINFO_RECEIVECONDITION_SHILI, TASKINFO_RECEIVECONDITION_TIANTIJIFEN, TASKINFO_RECEIVECONDITION_WU, TaskInfoTable::uiConditionParam, TaskInfoTable::uiReceiveCondition.
Referenced by GetDailyTaskNextTask, GetMainTaskNextTask, GetWinTaskNextTask, RefreshTask, RefreshTaskByEvent.
SeTaskInfo * TaskMgr::CurrTaskInfo(E_TASKINFOTABLE_TYPE eType)
References GetTaskVInfo.
Referenced by GetCurrTaskInfo, GetTaskReward, ResetTask.
bool TaskMgr::GetMainTaskNextTask(SeTaskInfo *skTask)
References CheckReceiveCondition, SeTaskInfo::dwTaskID, SeTaskInfo::eState, TableMgr::Get, TableMgr::GetNextMainTaskID, GetTaskConditionNum, SeTaskInfo::iConditionNum, SeTaskInfo::ifinishCount, SeTaskInfo::iSchedule, SeTaskInfo::pkRes, STS_DOING, STS_WAIT_CONDITION.
Referenced by GetNextTaskInfo, InitPlayerVTaskInfo.
bool TaskMgr::GetDailyTaskNextTask(SeTaskInfo *skTask)
References CheckReceiveCondition, SeTaskInfo::dwTaskID, SeTaskInfo::eState, SeTaskInfo::eTaskType, g_kWorldServer, TaskInfoTableMgr::Get, TableMgr::Get, TableMgr::GetDailyTaskIDList, GetTaskConditionNum, TaskInfoTableMgr::GetTaskInfoTable, SeTaskInfo::iConditionNum, SeTaskInfo::iSchedule, SeTaskInfo::pkRes, WorldServer::RandInt, SeLogError, STS_DOING.
Referenced by GetNextTaskInfo, InitPlayerVTaskInfo, RefreshTask.
bool TaskMgr::GetWinTaskNextTask(SeTaskInfo *skTask, bool bDiffDay)
References CheckReceiveCondition, SeTaskInfo::dwTaskID, SeTaskInfo::eState, SeTaskInfo::eTaskType, g_kWorldServer, TaskInfoTableMgr::Get, TableMgr::Get, TableMgr::GetDailyTaskIDList, TableMgr::GetFirstDailyTaskID, GetTaskConditionNum, TaskInfoTableMgr::GetTaskInfoTable, SeTaskInfo::iConditionNum, SeTaskInfo::iSchedule, SeTaskInfo::pkRes, WorldServer::RandInt, SeLogError, STS_DOING, TASKINFO_TYPE_SHENGCHANG.
Referenced by GetNextTaskInfo, InitPlayerVTaskInfo, RefreshTask.
const TaskInfoTable * TaskMgr::GetTaskConditionNum(DWord dwTaskID, int &value)
References g_kWorldServer, TaskInfoTableMgr::Get, TaskInfoTableMgr::GetTaskInfoTable, TaskInfoTable::iCondValue1, TaskInfoTable::iCondValue2, WorldServer::RandInt, SeLogError, TASKINFO_CONDITON_CANTUAN, TASKINFO_CONDITON_CANYUYOUXI, TASKINFO_CONDITON_CHENGSHANG, TASKINFO_CONDITON_CUIHUIFANGYUTA, TASKINFO_CONDITON_DUIWUWUSIWANGTONGGUAN, TASKINFO_CONDITON_FUJIA, TASKINFO_CONDITON_GETGOLD, TASKINFO_CONDITON_GUDAN, TASKINFO_CONDITON_JIESUOPIFU, TASKINFO_CONDITON_JIESUOYINGXIONG, TASKINFO_CONDITON_JISHA, TASKINFO_CONDITON_KILLNPC, TASKINFO_CONDITON_LIANSHA, TASKINFO_CONDITON_LIANXUSHENGLI, TASKINFO_CONDITON_MVP, TASKINFO_CONDITON_POFANG, TASKINFO_CONDITON_SHENZHU, TASKINFO_CONDITON_SHIYONGA, TASKINFO_CONDITON_SHIYONGB, TASKINFO_CONDITON_SHIYONGC, TASKINFO_CONDITON_SHIYONGD, TASKINFO_CONDITON_SHIYONGE, TASKINFO_CONDITON_SHOUSHENG, TASKINFO_CONDITON_SHUCHU, TASKINFO_CONDITON_TEAMJOIN, TASKINFO_CONDITON_TEAMMATCHINGWIN, TASKINFO_CONDITON_TIANTIJIFEN, TASKINFO_CONDITON_TIANTILIANXUSHENGLI, TASKINFO_CONDITON_TIANTISHENGLI, TASKINFO_CONDITON_TONGGUANDITU, TASKINFO_CONDITON_WANCHENGZHANGJIE, TASKINFO_CONDITON_WINA, TASKINFO_CONDITON_WINB, TASKINFO_CONDITON_WINC, TASKINFO_CONDITON_WIND, TASKINFO_CONDITON_WINE, TASKINFO_CONDITON_ZHANGHAODENGJI, TASKINFO_CONDITON_ZHANJIANG, TASKINFO_CONDITON_ZHIDINGSHIJIANTONGGUAN, TASKINFO_CONDITON_ZHUGONG, TASKINFO_CONDITON_ZIJIWUSIWANGTONGGUAN, TASKINFO_CONDITON_ZUDUITIANTISHENGLI, TaskInfoTable::uiConditon, TaskInfoTable::uiSpecialConditon.
Referenced by GetDailyTaskNextTask, GetMainTaskNextTask, GetWinTaskNextTask.
bool TaskMgr::InitPlayerVTaskInfo()
bool TaskMgr::CheckReceiveCondition(const TaskInfoTable *pkTaskTable)
SeTaskInfo* TaskMgr::CurrTaskInfo(E_TASKINFOTABLE_TYPE eType)
bool TaskMgr::GetMainTaskNextTask(SeTaskInfo *skTask)
bool TaskMgr::GetDailyTaskNextTask(SeTaskInfo *skTask)
bool TaskMgr::GetWinTaskNextTask(SeTaskInfo *skTask, bool bDiffDay)
const TaskInfoTable* TaskMgr::GetTaskConditionNum(DWord dwTaskID, int &value)