SeXmlDocument
bool SeXmlDocument::error
Referenced by ClearError, CopyTo, Error, SetError.
int SeXmlDocument::errorId
Referenced by ClearError, CopyTo, ErrorId, SetError.
SeXml_STRING SeXmlDocument::errorDesc
Referenced by ClearError, CopyTo, ErrorDesc, SetError.
int SeXmlDocument::tabsize
Referenced by CopyTo, SetTabSize, SeXmlDocument, TabSize.
SeXmlCursor SeXmlDocument::errorLocation
Referenced by ClearError, CopyTo, ErrorCol, ErrorRow, SetError.
bool SeXmlDocument::useMicrosoftBOM
Referenced by CopyTo, Parse, SaveFile, SeXmlDocument.
SeXmlDocument::SeXmlDocument()
Create an empty document, that has no name.
References ClearError, tabsize, useMicrosoftBOM.
Referenced by Clone.
SeXmlDocument::SeXmlDocument(const char *documentName)
Create a document with a name. The name of the document is also the filename of the xml.
References ClearError, tabsize, useMicrosoftBOM, SeXmlNode::value.
SeXmlDocument::SeXmlDocument(const std::string &documentName)
Constructor.
References ClearError, tabsize, useMicrosoftBOM, SeXmlNode::value.
SeXmlDocument::SeXmlDocument(const SeXmlDocument &copy)
References CopyTo.
SeXmlDocument & SeXmlDocument::operator=(const SeXmlDocument &copy)
References SeXmlNode::Clear, CopyTo.
virtual SeXmlDocument::~SeXmlDocument()
bool SeXmlDocument::LoadFile(SeXmlEncoding encoding=SeXml_DEFAULT_ENCODING)
Load a file using the current document value. Returns true if successful. Will delete any existing document data before loading.
References SeXmlNode::Value.
Referenced by LoadFile.
bool SeXmlDocument::SaveFile() const
Save a file using the current document value. Returns true if successful.
References SeXmlNode::Value.
Referenced by SaveFile.
bool SeXmlDocument::LoadFile(const char *filename, SeXmlEncoding encoding=SeXml_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
References LoadFile, SetError, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_OPENING_FILE, SeXml_STRING, SeXmlFOpen, SeXmlNode::value.
bool SeXmlDocument::SaveFile(const char *filename) const
Save a file using the given filename. Returns true if successful.
References SaveFile, SeXmlFOpen.
bool SeXmlDocument::LoadFile(FILE *, SeXmlEncoding encoding=SeXml_DEFAULT_ENCODING)
Load a file using the given FILE*. Returns true if successful. Note that this method doesn't stream - the entire object pointed at by the FILE* will be interpreted as an XML file. SeXml doesn't stream in XML from the current file location. Streaming may be added in the future.
References SeXmlCursor::Clear, SeXmlNode::Clear, Error, SeXmlBase::location, Parse, SetError, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR_DOCUMENT_EMPTY, SeXmlBase::SeXml_ERROR_OPENING_FILE.
bool SeXmlDocument::SaveFile(FILE *) const
Save a file using the given FILE*. Returns true if successful.
References Print, SeXml_UTF_LEAD_0, SeXml_UTF_LEAD_1, SeXml_UTF_LEAD_2, useMicrosoftBOM.
bool SeXmlDocument::LoadFile(const std::string &filename, SeXmlEncoding encoding=SeXml_DEFAULT_ENCODING)
STL std::string version.
References LoadFile.
bool SeXmlDocument::SaveFile(const std::string &filename) const
< STL std::string version.
References SaveFile.
const char * SeXmlDocument::Parse(const char *p, SeXmlParsingData *data=0, SeXmlEncoding encoding=SeXml_DEFAULT_ENCODING)
Parse the given null terminated block of xml data. Passing in an encoding to this method (either SeXml_ENCODING_LEGACY or SeXml_ENCODING_UTF8 will force SeXml to use that encoding, regardless of what SeXml might otherwise try to detect.
References SeXmlCursor::Clear, ClearError, SeXmlCursor::col, SeXmlParsingData::Cursor, SeXmlParsingData::cursor, SeXmlDeclaration::Encoding, SeXmlNode::firstChild, SeXmlNode::Identify, SeXmlNode::LinkEndChild, SeXmlBase::location, SeXmlBase::Parse, SeXmlCursor::row, SetError, SeXml_ENCODING_LEGACY, SeXml_ENCODING_UNKNOWN, SeXml_ENCODING_UTF8, SeXmlBase::SeXml_ERROR_DOCUMENT_EMPTY, SeXml_UTF_LEAD_0, SeXml_UTF_LEAD_1, SeXml_UTF_LEAD_2, SeXmlBase::SkipWhiteSpace, SeXmlBase::StringEqual, TabSize, SeXmlNode::ToDeclaration, useMicrosoftBOM.
Referenced by SeXmlHandle::CreatePath, SeXmlHandle::GetPath, LoadFile.
const SeXmlElement* SeXmlDocument::RootElement() const
Get the root element the only top level element of the document. In well formed XML, there should only be one. SeXml is tolerant of multiple elements at the document level.
References SeXmlNode::FirstChildElement.
SeXmlElement* SeXmlDocument::RootElement()
References SeXmlNode::FirstChildElement.
bool SeXmlDocument::Error() const
If an error occurs, Error will be set to true. Also, The ErrorId() will contain the integer identifier of the error (not generally useful)The ErrorDesc() method will return the name of the error. (very useful)The ErrorRow() and ErrorCol() will return the location of the error (if known)
References error.
Referenced by LoadFile.
const char* SeXmlDocument::ErrorDesc() const
Contains a textual (english) description of the error if one occurs.
References errorDesc.
int SeXmlDocument::ErrorId() const
Generally, you probably want the error string ( ErrorDesc() ). But if you prefer the ErrorId, this function will fetch it.
References errorId.
int SeXmlDocument::ErrorRow() const
Returns the location (if known) of the error. The first column is column 1, and the first row is row 1. A value of 0 means the row and column wasn't applicable (memory errors, for example, have no row/column) or the parser lost the error. (An error in the error reporting, in that case.)SetTabSize, Row, Column
References errorLocation, SeXmlCursor::row.
int SeXmlDocument::ErrorCol() const
The column where the error occured. See ErrorRow()
References SeXmlCursor::col, errorLocation.
void SeXmlDocument::SetTabSize(int _tabsize)
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column. It does not change the output or input in any way.By calling this method, with a tab size greater than 0, the row and column of each node and attribute is stored when the file is loaded. Very useful for tracking the DOM back in to the source file.The tab size is required for calculating the location of nodes. If not set, the default of 4 is used. The tabsize is set per document. Setting the tabsize to 0 disables row/column tracking.Note that row and column tracking is not supported when using operator>>.The tab size needs to be enabled before the parse or load. Correct usage: SeXmlDocument doc; doc.SetTabSize( 8 ); doc.Load( "myfile.xml" ); Row, Column
References tabsize.
int SeXmlDocument::TabSize() const
References tabsize.
Referenced by Parse.
void SeXmlDocument::ClearError()
If you have handled the error, it can be reset with this call. The error state is automatically cleared if you Parse a new XML block.
References SeXmlCursor::col, error, errorDesc, errorId, errorLocation, SeXmlCursor::row.
Referenced by Parse, SeXmlDocument.
void SeXmlDocument::Print() const
Write the document to standard out using formatted printing ("pretty print").
References Print.
Referenced by Print, SaveFile.
void SeXmlDocument::Print(FILE *cfile, int depth=0) const
Print this Document to a FILE stream.
References SeXmlNode::FirstChild, SeXmlNode::NextSibling.
void SeXmlDocument::SetError(int err, const char *errorLocation, SeXmlParsingData *prevData, SeXmlEncoding encoding)
References SeXmlCursor::Clear, SeXmlParsingData::Cursor, error, errorDesc, errorId, errorLocation, SeXmlBase::errorString, SeXmlBase::SeXml_ERROR_STRING_COUNT, SeXmlParsingData::Stamp.
Referenced by SeXmlNode::InsertAfterChild, SeXmlNode::InsertBeforeChild, SeXmlNode::InsertEndChild, SeXmlNode::LinkEndChild, LoadFile, SeXmlAttribute::Parse, SeXmlElement::Parse, SeXmlComment::Parse, SeXmlText::Parse, SeXmlDeclaration::Parse, SeXmlUnknown::Parse, Parse, SeXmlElement::ReadValue, SeXmlNode::ReplaceChild, SeXmlElement::StreamIn, SeXmlComment::StreamIn, SeXmlText::StreamIn, SeXmlDeclaration::StreamIn, SeXmlUnknown::StreamIn, StreamIn.
virtual const SeXmlDocument* SeXmlDocument::ToDocument() const
Cast to a more defined type. Will return null not of the requested type.
virtual SeXmlDocument* SeXmlDocument::ToDocument()
Cast to a more defined type. Will return null not of the requested type.
bool SeXmlDocument::Accept(SeXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
References SeXmlNode::FirstChild, SeXmlNode::NextSibling, SeXmlVisitor::VisitEnter, SeXmlVisitor::VisitExit.
SeXmlNode * SeXmlDocument::Clone() const
Create an exact duplicate of this node and return it. The memory must be deleted by the caller.
References CopyTo, SeXmlDocument.
void SeXmlDocument::StreamIn(std::istream *in, SeXml_STRING *tag)
References SeXmlNode::Identify, SetError, SeXml_DEFAULT_ENCODING, SeXml_ENCODING_UNKNOWN, SeXmlBase::SeXml_ERROR, SeXmlBase::SeXml_ERROR_EMBEDDED_NULL, SeXmlBase::SeXml_ERROR_PARSING_EMPTY, SeXmlNode::StreamIn, SeXmlBase::StreamTo, SeXmlNode::ToElement.
void SeXmlDocument::CopyTo(SeXmlDocument *target) const
References SeXmlNode::Clone, SeXmlNode::CopyTo, error, errorDesc, errorId, errorLocation, SeXmlNode::firstChild, SeXmlNode::LinkEndChild, SeXmlNode::NextSibling, tabsize, useMicrosoftBOM.
Referenced by Clone, operator=, SeXmlDocument.