moba
typedef long long moba::LONGLONG
typedef long long moba::TimeType
const int moba::DELAY_MAX_TIME
Referenced by moba::ServerSessionMgr::update.
static LONGLONG moba::systime()
References FACTOR.
Referenced by moba::Clock::gettimeofday.
MOBA_API void moba::printHex(const char *title, void *data, int size)
MOBA_API time_t moba::getDayStartTime(time_t time)
获得本地时区一天的开始时间
Referenced by getDiffDays, isSameDay.
MOBA_API time_t moba::getWeekStartTime(time_t time)
获得本地时区一周的开始时间
Referenced by isSameWeek.
MOBA_API bool moba::isSameDay(time_t a, time_t b)
是否是同一天
References getDayStartTime.
MOBA_API bool moba::isSameWeek(time_t a, time_t b)
是否是同一周
References getWeekStartTime.
Referenced by RaceDetailMgr::CheckRace_UserAttr_Bound.
MOBA_API int moba::getDiffDays(time_t a, time_t b)
返回b比a多的天数
References getDayStartTime.
Referenced by adjustDefeat.