PerformanceTiming
typedef std::vector< const CAverage * > PerformanceTiming::TConstAverageArray
typedef std::pair< CRC_ID, CAverage * > PerformanceTiming::TAverageMap_PairType
typedef std::tr1::unordered_map< CRC_ID, CAverage *, std::tr1::hash< CRC_ID >, std::equal_to< CRC_ID > > PerformanceTiming::TAverageMap
typedef std::vector< CCounter * > PerformanceTiming::TCounterArray
typedef std::vector< const CCounter * > PerformanceTiming::TConstCounterArray
typedef std::pair< CRC_ID, CCounter * > PerformanceTiming::TCounterMap_PairType
typedef std::tr1::unordered_map< CRC_ID, CCounter * > PerformanceTiming::TCounterMap
typedef std::vector< CInterval * > PerformanceTiming::TIntervalArray
typedef std::vector< const CInterval * > PerformanceTiming::TConstIntervalArray
typedef std::pair< CRC_ID, CInterval * > PerformanceTiming::TIntervalMap_PairType
typedef std::tr1::unordered_map< CRC_ID, CInterval * > PerformanceTiming::TIntervalMap
typedef std::vector< CHistoryCounter * > PerformanceTiming::THistoryCounterArray
typedef std::vector< const CHistoryCounter * > PerformanceTiming::TConstHistoryCounterArray
typedef std::vector< CCounterClone * > PerformanceTiming::TCounterCloneArray
typedef std::vector< const CCounterClone * > PerformanceTiming::TConstCounterCloneArray
typedef std::vector< CIntervalClone * > PerformanceTiming::TIntervalCloneArray
typedef std::vector< const CIntervalClone * > PerformanceTiming::TConstIntervalCloneArray
SePerformanceSave PerformanceTiming::g_kPerformanceSave
Referenced by CPerformanceIntervalFileDump::DumpIntervals.
UInt32 PerformanceTiming::m_uThreadIdx
const unsigned char PerformanceTiming::case_table[256][256]
Referenced by CRCString.
const UInt16 PerformanceTiming::crc_table[256][256]
PerformanceTiming::IMPLEMENT_POOL(CIntervalClone, 16, 8)
PerformanceTiming::IMPLEMENT_POOL(CCounterClone, 16, 8)
PerformanceTiming::IMPLEMENT_POOL(SePerformaceTask, 16, 16)
static void PerformanceTiming::DumpIntervalLine(Es::String &sText, bool bFoldered, bool bFolder, const Es::String &sName, Float64 dTimeMS, UInt32 uEntries, Float64 fPercentage, bool bOddLine, bool bClosed)
References PaddedString.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
static void PerformanceTiming::DumpCounterLine(Es::String &sText, bool bFoldered, bool bFolder, const Es::String &sName, UInt32 uValue, UInt64 uTotal, bool bHistory, bool bOddLine)
References PaddedString.
Referenced by PerformanceTiming::SePerformanceSave::DoWork.
std::string PerformanceTiming::MakePadString(const char *szString, Int32 dLen, char cPad)
std::string PerformanceTiming::PaddedString(const char *szSrc, Int32 iLen, char cPad)
Referenced by CPerformanceIntervalFileDump::DumpCounterLine, DumpCounterLine, CPerformanceIntervalFileDump::DumpHistoryIntervalLine, DumpIntervalLine, CPerformanceIntervalFileDump::DumpIntervalLine, CPerformanceIntervalFileDump::DumpPacketCounterLine.
static void PerformanceTiming::DumpIntervalLine(Es::String &sText, bool bFoldered, bool bFolder, const Es::String &sName, Float64 dTimeMS, UInt32 uEntries, Float64 fPercentage, bool bOddLine, bool bClosed)
References PaddedString.
static void PerformanceTiming::DumpCounterLine(Es::String &sText, bool bFoldered, bool bFolder, const Es::String &sName, UInt32 uValue, UInt64 uTotal, bool bHistory, bool bOddLine)
References PaddedString.
CRC_ID PerformanceTiming::CRCString(const char *_string)
References case_table, CRC_INIT.
Referenced by CPerformanceTiming::CreateOrLookupInterval, PerformanceTiming::CPerformanceStat::DoSetFolderFlag, PerformanceTiming::CPerformanceStat::DoSetFolderName, CPerformanceTiming::LookupInterval, CPerformanceTiming::TickNotify.