SeFlagBase
int SeFlagBase::m_iFlag
Referenced by ClrFlag, HasFlag, ReadFlag, SetFlag, WriteFlag.
SeFlagBase::SeFlagBase(void)
bool SeFlagBase::HasFlag(int iFlag) const
References m_iFlag.
Referenced by SeCacheMgr::GetCacheState, GlobalServer::OnLoginQueryRet, SeCacheMgr::Update.
void SeFlagBase::SetFlag(int iFlag)
References m_iFlag.
Referenced by SeCacheMgr::OnAccountLogin, SeCacheMgr::OnAccountLogout, SeCacheMgr::OnUpdateAccountDynamic.
void SeFlagBase::ClrFlag(int iFlag)
References m_iFlag.
Referenced by SeCacheMgr::OnAccountLogout, SeCacheMgr::Update.
void SeFlagBase::WriteFlag(int iFlag)
References m_iFlag.
int SeFlagBase::ReadFlag() const
References m_iFlag.