CItem
DWord CItem::uiID
Referenced by CItemMgr::AddNewMultiItem, CopyOwnToOther, CopyToProtoItem, CItemMgr::eraseItem, ActiveAvatarMgr::getAvatars, CItemMgr::getSelectableAvatars, CItemMgr::insertItem, load, CItemMgr::loadData, CItemMgr::notiChangeItem, EquipSchemaMgr::putOnEquip, save.
Word CItem::ucIndex
Referenced by CItemMgr::AddNewMultiItem, CopyOwnToOther, CopyToProtoItem, CItemMgr::doExchangeItem, CItemMgr::doMoveItem, CItemMgr::eraseItem, CItemMgr::insertItem, load, CItemMgr::loadData, save.
DWord CItem::uiItemID
Referenced by CItemMgr::AddNewMultiItem, CopyOwnToOther, CopyToEquipItem, CopyToProtoItem, CItemMgr::decRespawnItem, GenerateAddedAttr, GenerateAddedSkill, ActiveAvatarMgr::getAvatars, CItemMgr::getRespawnItemCount, CItemMgr::getSelectableAvatars, HeroMgr::isValidAvatar, EquipSchemaMgr::isValidEquip, load, loadData, CItemMgr::loadData, CItemMgr::openRandBox, save, saveData, CItemMgr::StrenthEquip.
DWord CItem::addedLevel
Referenced by CItemMgr::AddNewMultiItem, CopyOwnToOther, CopyToEquipItem, CopyToProtoItem, GenerateAddedAttr, loadData, saveData, CItemMgr::StrenthEquip.
DWord CItem::LostTime
Referenced by CItemMgr::AddNewMultiItem, CopyOwnToOther, CopyToProtoItem, load, save.
DWord CItem::uiOverLap
Referenced by CItemMgr::AddNewMultiItem, CopyOwnToOther, CopyToProtoItem, CItemMgr::decRespawnItem, CItemMgr::getRespawnItemCount, load, CItemMgr::openRandBox, save.
DWord CItem::dwNewFlag
Referenced by CItemMgr::AddNewMultiItem, CItemMgr::clearItemNewFlag, CopyOwnToOther, CopyToProtoItem, load, save.
SeItemOper CItem::ItemOper
Referenced by CopyOwnToOther, CopyToProtoItem, GetOper, SetOper.
SeAttrUnit CItem::pveAttr[SSD_MAX_ATTR_NUM]
Referenced by AddStrenAttr, CopyOwnToOther, CopyToEquipItem, CopyToProtoItem, GenerateAddedAttr, loadData, saveData.
SeAttrUnit CItem::pvpAttr[SSD_MAX_ATTR_NUM]
Referenced by AddStrenAttr, CopyOwnToOther, CopyToEquipItem, CopyToProtoItem, GenerateAddedAttr, loadData, saveData.
SeCiTiao CItem::citiaoAttr[SSD_MAX_ATTR_NUM]
Referenced by CopyOwnToOther, CopyToEquipItem, CopyToProtoItem, GenerateAddedSkill, loadData, saveData.
CItem::DECLARE_POOL(CItem)
CItem::CItem()
void CItem::CopyToProtoItem(SeItemNoti &tmpItem)
References addedLevel, SeItemNoti::bNew, citiaoAttr, SeItemNoti::citiaoAttr, SeItemNoti::dwAddedLevel, SeItemNoti::dwID, SeItemNoti::dwLostTime, dwNewFlag, SeItemNoti::dwOverlap, SeItemNoti::Index, SeItemNoti::ItemID, ItemOper, SeItemNoti::ItemOper, LostTime, pveAttr, SeItemNoti::pveAttr, pvpAttr, SeItemNoti::pvpAttr, SSD_MAX_ATTR_NUM, ucIndex, uiID, uiItemID, uiOverLap.
Referenced by CItemMgr::doExchangeItem, CItemMgr::doMoveItem, CItemMgr::notiChangeItem.
void CItem::CopyToEquipItem(int equipmentType, SePtlEquipItem &tmpItem)
References SePtlEquipItem::AddedAttr, addedLevel, citiaoAttr, SePtlEquipItem::dwAddedLevel, getAddedAttr, getCitiaoAttr, SePtlEquipItem::ItemID, MAPINFO_EQUIPMENTTYPE_PVE, MAPINFO_EQUIPMENTTYPE_PVP, pveAttr, pvpAttr, SePtlEquipItem::SkillAddedAttr, uiItemID.
Referenced by EquipSchemaMgr::getEquips.
void CItem::CopyOwnToOther(CItem &item)
References addedLevel, citiaoAttr, dwNewFlag, ItemOper, LostTime, pveAttr, pvpAttr, SSD_MAX_ATTR_NUM, ucIndex, uiID, uiItemID, uiOverLap.
void CItem::load(const SeDBCharItem &item)
References dwNewFlag, loadData, LostTime, ucIndex, uiID, uiItemID, uiOverLap.
Referenced by CItemMgr::loadData.
void CItem::save(SeDBCharItem &item)
References dwNewFlag, LostTime, saveData, StrCpy, ucIndex, uiID, uiItemID, uiOverLap.
Referenced by CItemMgr::doExchangeItem, CItemMgr::doMoveItem, CItemMgr::notiChangeItem.
void CItem::SetOper(SeItemOper oper)
References ItemOper.
Referenced by CItemMgr::AddNewMultiItem, CItemMgr::decRespawnItem, CItemMgr::notiChangeItem, CItemMgr::openRandBox, CItemMgr::StrenthEquip.
SeItemOper CItem::GetOper()
References ItemOper.
Referenced by CItemMgr::notiChangeItem.
void CItem::loadData(const std::string &data)
References addedLevel, Json::Value::asFloat, Json::Value::asInt, Json::Value::begin, citiaoAttr, SeCiTiao::dwID, SeAttrUnit::dwIndex, SeExternAttrUnit::dwIndex, SeExternAttrUnit::dwSubID, SeAttrUnit::dwValue, SeExternAttrUnit::dwValue, Json::Value::end, TownItemTableMgr::Get, TownItemTableMgr::GetTownItemTable, Json::Value::isArray, Json::Value::isObject, Json::Reader::parse, pveAttr, pvpAttr, SeCiTiao::SkillAdd, SSD_MAX_ATTR_NUM, TOWNITEM_CLASS_ZHUANGBEI, TownItemTable::uiClass, uiItemID.
Referenced by load.
void CItem::saveData(std::string &data) const
References addedLevel, Json::Value::append, citiaoAttr, Json::Value::clear, SeCiTiao::dwID, SeAttrUnit::dwIndex, SeExternAttrUnit::dwIndex, SeExternAttrUnit::dwSubID, SeAttrUnit::dwValue, SeExternAttrUnit::dwValue, TownItemTableMgr::Get, TownItemTableMgr::GetTownItemTable, pveAttr, pvpAttr, SeCiTiao::SkillAdd, SSD_MAX_ATTR_NUM, TOWNITEM_CLASS_ZHUANGBEI, TownItemTable::uiClass, uiItemID, Json::FastWriter::write.
Referenced by save.
CItem::DECLARE_POOL(CItem)
CItem::CItem()
void CItem::CopyToProtoItem(SeItemNoti &tmpItem)
References addedLevel, SeItemNoti::bNew, citiaoAttr, SeItemNoti::citiaoAttr, SeItemNoti::dwAddedLevel, SeItemNoti::dwID, SeItemNoti::dwLostTime, dwNewFlag, SeItemNoti::dwOverlap, SeItemNoti::Index, SeItemNoti::ItemID, ItemOper, SeItemNoti::ItemOper, LostTime, pveAttr, SeItemNoti::pveAttr, pvpAttr, SeItemNoti::pvpAttr, SSD_MAX_ATTR_NUM, ucIndex, uiID, uiItemID, uiOverLap.
void CItem::CopyToEquipItem(int equipmentType, SePtlEquipItem &tmpItem)
void CItem::CopyOwnToOther(CItem &item)
References addedLevel, citiaoAttr, dwNewFlag, ItemOper, LostTime, pveAttr, pvpAttr, SSD_MAX_ATTR_NUM, ucIndex, uiID, uiItemID, uiOverLap.
void CItem::load(const SeDBCharItem &item)
References dwNewFlag, loadData, LostTime, ucIndex, uiID, uiItemID, uiOverLap.
void CItem::save(SeDBCharItem &item)
References dwNewFlag, LostTime, saveData, StrCpy, ucIndex, uiID, uiItemID, uiOverLap.
void CItem::SetOper(SeItemOper oper)
References ItemOper.
SeItemOper CItem::GetOper()
References ItemOper.
void CItem::loadData(const std::string &data)
void CItem::saveData(std::string &data) const
void CItem::getAddedAttr(std::vector< SeAttrUnit > &vAttr, SeAttrUnit *attr)
References SSD_MAX_ATTR_NUM.
Referenced by CopyToEquipItem.
void CItem::getCitiaoAttr(std::vector< SePtlCiTiao > &vCitiao, SeCiTiao *citiao)
References SePtlCiTiao::dwID, SeCiTiao::dwID, SePtlCiTiao::SkillAdd, SSD_MAX_ATTR_NUM.
Referenced by CopyToEquipItem.
static void CItem::getAddedAttr(std::vector< SeAttrUnit > &vAttr, SeAttrUnit *attr)
static void CItem::getCitiaoAttr(std::vector< SePtlCiTiao > &vCitiao, SeCiTiao *citiao)