SeRoom
int SeRoom::iIndex
Referenced by SeRaceQueryMgr::Initialize, SeRaceQueryMgr::OnCreateRoom, SeRaceQueryMgr::OnDestroyRoom.
SeMatchRaceType SeRoom::eMatchType
Referenced by Clear.
DWord SeRoom::dwSession
Referenced by Clear, SeRaceQueryMgr::GetRoomList, SeRaceQueryMgr::OnCreateRoom, SeRaceQueryMgr::OnDestroyRoom, SeRaceQueryMgr::OnRaceSeatUpdateReverse, SeRaceQueryMgr::OnRaceSeatUpdateState, SeRaceQueryMgr::OnRaceSvrUpdateRoomLoadInfo, SeRaceQueryMgr::OnReloadPlayerInfo, MatchServer::OnSendTSQueryRoomListRet.
DWord SeRoom::dwMapID
Referenced by Clear, SeRaceQueryMgr::OnCreateRoom, MatchServer::OnSendTSQueryRoomListRet, SeRaceQueryMgr::RoomFilter.
int SeRoom::iMaxPlayerNums
Referenced by Clear.
DWord SeRoom::dwRaceBeginTime
Referenced by CanShowRace, Clear, SeRaceQueryMgr::OnCreateRoom, MatchServer::OnSendTSQueryRoomListRet.
bool SeRoom::bEscape
Referenced by Clear, SeRaceQueryMgr::OnRaceSeatUpdateState, SeRaceQueryMgr::OnRaceSvrUpdateRoomLoadInfo, SeRaceQueryMgr::OnReloadPlayerInfo.
SeMatchRoomPlayerInfo SeRoom::akPlayerSeat[SSD_MAX_ROOM_PLAYER]
Referenced by CanShowRace, Clear, SeRaceQueryMgr::OnProcessAddIncompleteRace, SeRaceQueryMgr::OnRaceSeatUpdateReverse, SeRaceQueryMgr::OnRaceSeatUpdateState, SeRaceQueryMgr::OnRaceSvrUpdateRoomLoadInfo, SeRaceQueryMgr::OnReconUpdatePlayerInfo, SeRaceQueryMgr::OnReloadPlayerInfo.
SeRoom::SeRoom()
References Clear.
void SeRoom::Clear(void)
References akPlayerSeat, bEscape, dwMapID, dwRaceBeginTime, dwSession, eMatchType, iMaxPlayerNums, SMRT_NONE.
Referenced by SeRaceQueryMgr::OnCreateRoom, SeRaceQueryMgr::OnDestroyRoom, SeRoom.
bool SeRoom::CanShowRace(DWord dwServerTime)
References akPlayerSeat, dwRaceBeginTime, SSD_MAX_ROOM_PLAYER.
Referenced by SeRaceQueryMgr::RoomFilter.
SeRoom::SeRoom()
References Clear.
void SeRoom::Clear(void)
References akPlayerSeat, bEscape, dwMapID, dwRaceBeginTime, dwSession, eMatchType, iMaxPlayerNums, SMRT_NONE.
bool SeRoom::CanShowRace(DWord dwServerTime)
References akPlayerSeat, dwRaceBeginTime, SSD_MAX_ROOM_PLAYER.