Json::BuiltStyledStreamWriter
typedef std::vector<std::string> Json::BuiltStyledStreamWriter::ChildValues
ChildValues Json::BuiltStyledStreamWriter::childValues_
Referenced by isMultineArray, pushValue, writeArrayValue.
std::string Json::BuiltStyledStreamWriter::indentString_
Referenced by indent, unindent, write, writeCommentBeforeValue, writeIndent.
int Json::BuiltStyledStreamWriter::rightMargin_
Referenced by isMultineArray.
std::string Json::BuiltStyledStreamWriter::indentation_
Referenced by indent, unindent, writeArrayValue, writeIndent.
CommentStyle::Enum Json::BuiltStyledStreamWriter::cs_
Referenced by writeArrayValue, writeCommentAfterValueOnSameLine, writeCommentBeforeValue.
std::string Json::BuiltStyledStreamWriter::colonSymbol_
Referenced by writeValue.
std::string Json::BuiltStyledStreamWriter::nullSymbol_
Referenced by writeValue.
std::string Json::BuiltStyledStreamWriter::endingLineFeedSymbol_
Referenced by write.
bool Json::BuiltStyledStreamWriter::addChildValues_
Referenced by isMultineArray, pushValue, write.
bool Json::BuiltStyledStreamWriter::indented_
Referenced by write, writeArrayValue, writeCommentBeforeValue, writeWithIndent.
bool Json::BuiltStyledStreamWriter::useSpecialFloats_
Referenced by writeValue.
unsigned int Json::BuiltStyledStreamWriter::precision_
Referenced by writeValue.
Json::BuiltStyledStreamWriter::BuiltStyledStreamWriter(std::string const &indentation, CommentStyle::Enum cs, std::string const &colonSymbol, std::string const &nullSymbol, std::string const &endingLineFeedSymbol, bool useSpecialFloats, unsigned int precision)
int Json::BuiltStyledStreamWriter::write(Value const &root, std::ostream *sout) override
Write Value into document as configured in sub-class. Do not take ownership of sout, but maintain a reference during function. sout != NULL zero on success (For now, we always return zero, so check the stream instead.) std::exception possibly, depending on configuration
References addChildValues_, endingLineFeedSymbol_, indented_, indentString_, Json::StreamWriter::sout_, writeCommentAfterValueOnSameLine, writeCommentBeforeValue, writeIndent, writeValue.
void Json::BuiltStyledStreamWriter::writeValue(Value const &value)
References Json::arrayValue, Json::Value::asBool, Json::Value::asDouble, Json::Value::asLargestInt, Json::Value::asLargestUInt, Json::booleanValue, colonSymbol_, Json::Value::getMemberNames, Json::Value::getString, indent, Json::intValue, nullSymbol_, Json::nullValue, Json::objectValue, precision_, pushValue, Json::realValue, Json::StreamWriter::sout_, Json::stringValue, Json::Value::type, Json::uintValue, unindent, useSpecialFloats_, Json::valueToQuotedStringN, Json::valueToString, writeArrayValue, writeCommentAfterValueOnSameLine, writeCommentBeforeValue, writeWithIndent.
Referenced by isMultineArray, write, writeArrayValue.
void Json::BuiltStyledStreamWriter::writeArrayValue(Value const &value)
References Json::CommentStyle::All, childValues_, cs_, indent, indentation_, indented_, isMultineArray, pushValue, Json::Value::size, Json::StreamWriter::sout_, unindent, writeCommentAfterValueOnSameLine, writeCommentBeforeValue, writeIndent, writeValue, writeWithIndent.
Referenced by writeValue.
bool Json::BuiltStyledStreamWriter::isMultineArray(Value const &value)
References addChildValues_, childValues_, hasCommentForValue, Json::Value::isArray, Json::Value::isObject, rightMargin_, Json::Value::size, writeValue.
Referenced by writeArrayValue.
void Json::BuiltStyledStreamWriter::pushValue(std::string const &value)
References addChildValues_, childValues_, Json::StreamWriter::sout_.
Referenced by writeArrayValue, writeValue.
void Json::BuiltStyledStreamWriter::writeIndent()
References indentation_, indentString_, Json::StreamWriter::sout_.
Referenced by write, writeArrayValue, writeCommentAfterValueOnSameLine, writeCommentBeforeValue, writeWithIndent.
void Json::BuiltStyledStreamWriter::writeWithIndent(std::string const &value)
References indented_, Json::StreamWriter::sout_, writeIndent.
Referenced by writeArrayValue, writeValue.
void Json::BuiltStyledStreamWriter::indent()
References indentation_, indentString_.
Referenced by writeArrayValue, writeValue.
void Json::BuiltStyledStreamWriter::unindent()
References indentation_, indentString_.
Referenced by writeArrayValue, writeValue.
void Json::BuiltStyledStreamWriter::writeCommentBeforeValue(Value const &root)
References Json::commentBefore, cs_, Json::Value::getComment, Json::Value::hasComment, indented_, indentString_, Json::CommentStyle::None, Json::StreamWriter::sout_, writeIndent.
Referenced by write, writeArrayValue, writeValue.
void Json::BuiltStyledStreamWriter::writeCommentAfterValueOnSameLine(Value const &root)
References Json::commentAfter, Json::commentAfterOnSameLine, cs_, Json::Value::getComment, Json::Value::hasComment, Json::CommentStyle::None, Json::StreamWriter::sout_, writeIndent.
Referenced by write, writeArrayValue, writeValue.
bool Json::BuiltStyledStreamWriter::hasCommentForValue(const Value &value)
References Json::commentAfter, Json::commentAfterOnSameLine, Json::commentBefore, Json::Value::hasComment.
Referenced by isMultineArray.