LadderRankItem
int LadderRankItem::m_rank
Referenced by GetRank, LadderRankItem, SetRank.
LadderRankItem::DECLARE_POOL(LadderRankItem)
LadderRankItem::LadderRankItem()
LadderRankItem::LadderRankItem(DWord dwPlayerID, Word wIconID, int level, int score, int playerLevel, const char *sName)
References SeLadderRankInfo::acName, SeLadderRankInfo::dwPlayerID, SeLadderRankInfo::iLadderLevel, SeLadderRankInfo::iLadderScore, SeLadderRankInfo::iPlayerLevel, m_rank, StrCpy, SeLadderRankInfo::wIconID.
void LadderRankItem::LoadInfo(DWord dwPlayerID, Word wIconID, int level, int score, int playerLevel, const char *sName)
References SeLadderRankInfo::acName, SeLadderRankInfo::dwPlayerID, SeLadderRankInfo::iLadderLevel, SeLadderRankInfo::iLadderScore, SeLadderRankInfo::iPlayerLevel, StrCpy, SeLadderRankInfo::wIconID.
Referenced by LadderRankMgr::JoinNewPlayerLadderInfo.
LadderRankIndex LadderRankItem::Index()
References SeLadderRankInfo::iLadderLevel, SeLadderRankInfo::iPlayerLevel.
Referenced by LadderRankMgr::JoinNewPlayerLadderInfo.
Word LadderRankItem::GetRank()
References m_rank.
Referenced by LadderRankMgr::JoinNewPlayerLadderInfo.
void LadderRankItem::SetRank(int wRank)
References m_rank.
Referenced by LadderRankMgr::JoinNewPlayerLadderInfo, LadderRankMgr::UpdateRank.
void LadderRankItem::DBDelete()
References SeLadderRankInfo::dwPlayerID, g_kTabMgr, SDTI_CharLadderRank, TabMgr::tabDelete.
Referenced by LadderRankMgr::RankDBDelete.
void LadderRankItem::DBUpdate()
References SeLadderRankInfo::dwPlayerID, g_kTabMgr, SeLadderRankInfo::iLadderLevel, SeLadderRankInfo::iLadderScore, SeLadderRankInfo::iPlayerLevel, SDTI_CharLadderRank, TabMgr::tabUpdate.
Referenced by LadderRankMgr::RankDBUpdate.
void LadderRankItem::DBInsert()
References SeLadderRankInfo::acName, SeLadderRankInfo::dwPlayerID, g_kTabMgr, SeLadderRankInfo::iLadderLevel, SeLadderRankInfo::iLadderScore, SeLadderRankInfo::iPlayerLevel, SDTI_CharLadderRank, TabMgr::tabInsert, SeLadderRankInfo::wIconID.
Referenced by LadderRankMgr::RankDBInsert.
LadderRankItem::DECLARE_POOL(LadderRankItem)
LadderRankItem::LadderRankItem()
LadderRankItem::LadderRankItem(DWord dwPlayerID, Word wIconID, int level, int score, int playerLevel, const char *sName)
void LadderRankItem::LoadInfo(DWord dwPlayerID, Word wIconID, int level, int score, int playerLevel, const char *sName)
LadderRankIndex LadderRankItem::Index()
Word LadderRankItem::GetRank()
void LadderRankItem::SetRank(int wRank)
void LadderRankItem::DBDelete()
void LadderRankItem::DBUpdate()
void LadderRankItem::DBInsert()