SeXmlCursor
int SeXmlCursor::row
Referenced by Clear, SeXmlDocument::ClearError, SeXmlDocument::ErrorRow, SeXmlDocument::Parse, SeXmlBase::Row, SeXmlParsingData::SeXmlParsingData, SeXmlParsingData::Stamp.
int SeXmlCursor::col
Referenced by Clear, SeXmlDocument::ClearError, SeXmlBase::Column, SeXmlDocument::ErrorCol, SeXmlDocument::Parse, SeXmlParsingData::SeXmlParsingData, SeXmlParsingData::Stamp.
SeXmlCursor::SeXmlCursor()
References Clear.
void SeXmlCursor::Clear()
References col, row.
Referenced by SeXmlDocument::LoadFile, SeXmlDocument::Parse, SeXmlDocument::SetError, SeXmlCursor.