SeLoadInfo
DWord SeLoadInfo::dwSuccessCount
Referenced by NeedShow, LoginServer::SetLoginLogInfo, LoginServer::UpdateLogShow.
DWord SeLoadInfo::dwPasswordFailedCount
Referenced by NeedShow, LoginServer::SetLoginLogInfo, LoginServer::UpdateLogShow.
DWord SeLoadInfo::dwOtherFailedCount
Referenced by NeedShow, LoginServer::SetLoginLogInfo, LoginServer::UpdateLogShow.
DWord SeLoadInfo::dwQueryGSCount
Referenced by GetGSAvgTime, NeedShow, LoginServer::SetLoginLogInfo, LoginServer::UpdateLogShow.
DWord SeLoadInfo::dwQueryGSSumTime
Referenced by GetGSAvgTime, LoginServer::SetLoginLogInfo.
DWord SeLoadInfo::dwQueryWSCount
Referenced by GetWSAvgTime, NeedShow, LoginServer::SetLoginLogInfo, LoginServer::UpdateLogShow.
DWord SeLoadInfo::dwQueryWSSumTime
Referenced by GetWSAvgTime, LoginServer::SetLoginLogInfo.
SeLoadInfo::SeLoadInfo()
References ReSet.
void SeLoadInfo::ReSet(void)
Referenced by SeLoadInfo, LoginServer::UpdateLogShow.
DWord SeLoadInfo::GetGSAvgTime(void)
References dwQueryGSCount, dwQueryGSSumTime.
Referenced by LoginServer::UpdateLogShow.
DWord SeLoadInfo::GetWSAvgTime(void)
References dwQueryWSCount, dwQueryWSSumTime.
Referenced by LoginServer::UpdateLogShow.
bool SeLoadInfo::NeedShow(void)
References dwOtherFailedCount, dwPasswordFailedCount, dwQueryGSCount, dwQueryWSCount, dwSuccessCount.
Referenced by LoginServer::UpdateLogShow.
SeLoadInfo::SeLoadInfo()
References ReSet.
void SeLoadInfo::ReSet(void)
DWord SeLoadInfo::GetGSAvgTime(void)
References dwQueryGSCount, dwQueryGSSumTime.
DWord SeLoadInfo::GetWSAvgTime(void)
References dwQueryWSCount, dwQueryWSSumTime.
bool SeLoadInfo::NeedShow(void)
References dwOtherFailedCount, dwPasswordFailedCount, dwQueryGSCount, dwQueryWSCount, dwSuccessCount.