SeTown
SeConnect * SeTown::pkConnect
Referenced by SeRaceMgr::GetTownSock, SeTownMgr::GetTownSockByArea, SeTownMgr::GetTownSockBySign, operator=, MatchServer::ProcessRM_ReconQueryFail, MatchServer::ProcessRM_ViewQueryFail, MatchServer::ProcessTM_CommMatchMsg, MatchServer::ProcessTM_Register, SeTown, MatchServer::UpdateTSTOMSTime.
DWord SeTown::dwServerID
Referenced by SeTownMgr::OnTSRegister, operator=, MatchServer::ProcessTM_Register, SetConnect, SeTown, MatchServer::UpdateTSTOMSTime.
DWord SeTown::dwAreaID
Referenced by SeTownMgr::GetTownSockByArea, SeTownMgr::OnTSRegister, operator=, MatchServer::ProcessTM_Register, SeTownMgr::RefreshAreaNum, SeTown.
int SeTown::iTownIndex
Referenced by operator=, MatchServer::ProcessTM_Register, SeTown.
DWord SeTown::dwLastRecvTime
Referenced by SeTownMgr::OnTSUpdateLoadNum, operator=, MatchServer::ProcessTM_Register, SeTown, MatchServer::UpdateTSTOMSTime.
SeNetAddr SeTown::kAddrToMatch
Referenced by operator=, SeTown.
int SeTown::iPlayerNum
Referenced by CanReturnPlayer, SeTownMgr::OnTSUpdateLoadNum, operator=, SeTown.
int SeTown::iRaceConnNum
Referenced by SeTownMgr::OnTSUpdateLoadNum, operator=, SeTown.
int SeTown::iMaxNum
Referenced by CanReturnPlayer, operator=, MatchServer::ProcessTM_Register, SeTown.
DWord SeTown::dwDefaultMapID
Referenced by operator=, MatchServer::ProcessTM_Register, SeTown.
int SeTown::iRegisterCount
Referenced by SeTownMgr::OnTSRegister, operator=, SeTown.
SeConnect * SeTown::m_pkConnect
Referenced by DelLoadPlayerID, SeTown, UpdateLoadData.
HSock SeTown::m_kSock
Referenced by SeTown.
DWord SeTown::m_dwServerID
Referenced by SeTown.
int SeTown::m_iTownIndex
Referenced by DelLoadPlayerID, SeTown, UpdateLoadData.
DWord SeTown::m_dwLastRecvTime
Referenced by SeTown.
bool SeTown::m_bClosed
Referenced by SeTown.
SeNetAddr SeTown::m_kAddrToPlayer
Referenced by Initialize.
DWord SeTown::m_dwGateWayIP
Referenced by SeTown.
int SeTown::m_iPlayerNum
Referenced by SeTown.
std::vector< SeLoadPlayerInfoAgain > SeTown::m_akLoadAgainPlayer
Referenced by DelLoadPlayerID, GetLoadAgainPlayerByID.
std::map< DWord, DWord > SeTown::m_akMLoadPlayerData
Referenced by DelLoadPlayerID, PushLoadPlayerID, UpdateLoadData.
bool SeTown::m_bLoadCompleted
Referenced by DelLoadPlayerID, LoadComplete, PushLoadPlayerID, SeTown, UpdateLoadData.
SeTown::SeTown()
References dwAreaID, dwDefaultMapID, dwLastRecvTime, dwServerID, iMaxNum, iPlayerNum, iRaceConnNum, iRegisterCount, iTownIndex, kAddrToMatch, pkConnect.
Referenced by SetConnect.
SeTown& SeTown::operator=(const SeTown &rkTown)
References dwAreaID, dwDefaultMapID, dwLastRecvTime, dwServerID, iMaxNum, iPlayerNum, iRaceConnNum, iRegisterCount, iTownIndex, kAddrToMatch, pkConnect.
bool SeTown::CanReturnPlayer()
References iMaxNum, iPlayerNum.
SeTown::SeTown()
References dwAreaID, dwDefaultMapID, dwLastRecvTime, dwServerID, iMaxNum, iPlayerNum, iRaceConnNum, iRegisterCount, iTownIndex, kAddrToMatch, pkConnect.
SeTown& SeTown::operator=(const SeTown &rkTown)
References dwAreaID, dwDefaultMapID, dwLastRecvTime, dwServerID, iMaxNum, iPlayerNum, iRaceConnNum, iRegisterCount, iTownIndex, kAddrToMatch, pkConnect.
bool SeTown::CanReturnPlayer()
References iMaxNum, iPlayerNum.
SeTown::SeTown(DWord dwServerID)
References dwServerID, m_bClosed, m_bLoadCompleted, m_dwGateWayIP, m_dwLastRecvTime, m_dwServerID, m_iPlayerNum, m_iTownIndex, m_kSock, m_pkConnect.
SeTown::~SeTown(void)
void SeTown::SetConnect(SeConnect *pkConnect)
References DECLARE_POOL1, dwServerID, SeTown.
Referenced by WorldServer::ProcessTW_Register.
SeConnect* SeTown::GetConnect()
Referenced by WorldServer::ProcessTW_Register, WorldServer::UpdateTSTOWSTime.
HSock& SeTown::GetHSock(void)
Referenced by WorldServer::GetPlayerTownSock, WorldServer::KickPlayerByID, WorldServer::ProcessBLW_PlayerLeave, WorldServer::ProcessBLW_PlayerOperRep, WorldServer::ProcessBLW_ShopItemGmRep, WorldServer::ProcessBW_IsPlayerExistRet, WorldServer::ProcessTW_LoadPlayerInfoAgain, WorldServer::SetWSReady, WorldServer::UpdateTSTOWSTime.
DWord SeTown::GetServerID(void)
Referenced by WorldServer::GetTSByID, WorldServer::OnTSDisconnect, WorldServer::ProcessTW_LoadPlayerInfoAgain, WorldServer::ProcessTW_Register, WorldServer::UpdateTSTOWSTime.
int SeTown::GetTownIndex(void)
Referenced by WorldServer::GetTSByIndex, WorldServer::HasTownIndex, WorldServer::OnTSDisconnect, WorldServer::ProcessTW_LoadPlayerInfoAgain, WorldServer::ProcessTW_PlayerLeave, WorldServer::ProcessTW_PlayerLeaveRace, WorldServer::ProcessTW_RaceEndRace, WorldServer::ProcessTW_Register.
const SeNetAddr& SeTown::GetAddrToPlayer(void)
Referenced by WorldServer::ProcessLW_AccountLogin, WorldServer::SeDBSerProcess_CharLoginLoad.
void SeTown::SetPlayerNum(int iPlayerNum)
Referenced by WorldServer::ProcessBLW_TSIncNum, WorldServer::ProcessTW_LoadPlayerInfoAgain.
int SeTown::GetPlayerNum(void)
Referenced by WorldServer::ProcessBLW_TSIncNum.
void SeTown::IncPlayerNum(void)
void SeTown::DecPlayerNum(void)
Referenced by WorldServer::ProcessBLW_PlayerLeave.
std::vector<SeLoadPlayerInfoAgain>& SeTown::GetLoadAgainPlayer()
Referenced by WorldServer::ProcessTW_LoadPlayerInfoAgain.
void SeTown::SetLastRecvTime(DWord dwTime)
Referenced by WorldServer::ProcessTW_HeartPackage.
DWord SeTown::GetLastRecvTime(void)
Referenced by WorldServer::UpdateTSTOWSTime.
void SeTown::SetClosed(bool bClosed)
Referenced by WorldServer::ProcessTW_Register.
bool SeTown::IsClosed()
Referenced by WorldServer::ProcessTW_Register.
void SeTown::SetGateWayIP(DWord dwGateWayIP)
DWord SeTown::GetGateWayIP(void)
void SeTown::Initialize(const SeTownInfo &rkInfo)
References SeTownInfo::kAddrToPlayer, m_kAddrToPlayer.
Referenced by WorldServer::ProcessTW_Register.
void SeTown::PushLoadPlayerID(DWord dwID, DWord dwStartTime)
References m_akMLoadPlayerData, m_bLoadCompleted.
Referenced by WorldServer::ProcessTW_LoadPlayerInfoAgain.
void SeTown::DelLoadPlayerID(DWord dwID)
References SeLoadPlayerInfoAgain::dwPlayerID, g_kWorldServer, SeConnect::kSock, m_akLoadAgainPlayer, m_akMLoadPlayerData, m_bLoadCompleted, m_iTownIndex, m_pkConnect, SeLogInfo, WorldServer::SendWT_LoadPlayerInfoAgainRet.
Referenced by WorldServer::ProcessBLW_LoadPlayerInfoAgainRet.
void SeTown::UpdateLoadData(void)
References g_kWorldServer, WorldServer::GetServerTime, SeConnect::kSock, m_akMLoadPlayerData, m_bLoadCompleted, m_iTownIndex, m_pkConnect, MAX_LOAD_WAIT_TIME, SeLogInfo, WorldServer::SendWT_LoadPlayerInfoAgainRet.
bool SeTown::LoadComplete(void)
References m_bLoadCompleted.
Referenced by WorldServer::IsAllTownLoadComplete, WorldServer::UpdateTSTOWSTime.
const SeLoadPlayerInfoAgain * SeTown::GetLoadAgainPlayerByID(DWord dwPlayerID)
References SeLoadPlayerInfoAgain::dwPlayerID, m_akLoadAgainPlayer.
SeTown::SeTown(DWord dwServerID)
SeTown::~SeTown(void)
void SeTown::SetConnect(SeConnect *pkConnect)
References DECLARE_POOL1, dwServerID, SeTown.
SeConnect* SeTown::GetConnect()
HSock& SeTown::GetHSock(void)
DWord SeTown::GetServerID(void)
int SeTown::GetTownIndex(void)
const SeNetAddr& SeTown::GetAddrToPlayer(void)
void SeTown::SetPlayerNum(int iPlayerNum)
int SeTown::GetPlayerNum(void)
void SeTown::IncPlayerNum(void)
void SeTown::DecPlayerNum(void)
std::vector<SeLoadPlayerInfoAgain>& SeTown::GetLoadAgainPlayer()
void SeTown::SetLastRecvTime(DWord dwTime)
DWord SeTown::GetLastRecvTime(void)
void SeTown::SetClosed(bool bClosed)
bool SeTown::IsClosed()
void SeTown::SetGateWayIP(DWord dwGateWayIP)
DWord SeTown::GetGateWayIP(void)
void SeTown::Initialize(const SeTownInfo &rkInfo)
void SeTown::PushLoadPlayerID(DWord dwID, DWord dwStartTime)
void SeTown::DelLoadPlayerID(DWord dwID)
void SeTown::UpdateLoadData(void)
bool SeTown::LoadComplete(void)
const SeLoadPlayerInfoAgain* SeTown::GetLoadAgainPlayerByID(DWord dwPlayerID)
SeTown::DECLARE_POOL1(SeTown, DWord)
Referenced by SetConnect.
SeTown::DECLARE_POOL1(SeTown, DWord)