SeRaceRoom
DWord SeRaceRoom::dwID
Referenced by SeRaceRoomMgr::GetReloadRoomInfo, SeRaceRoomMgr::IntoSelHero, SeRaceRoomMgr::JoinRoomRecon, SeRaceRoomMgr::OnPlayerReconQuery, SeRaceRoomMgr::OnProcessRepeatPlayer, SeRaceRoomMgr::OnRaceEnd, SeRaceMgr::OnRaceModeEnd, SeRaceRoomMgr::OnReconValidOK, SeRaceRoomMgr::RecycleRoomPlayer, SeRaceRoomMgr::SelHero, SeRaceRoomMgr::SelHeroFight, SeRaceRoomMgr::SelHeroReady, SeRaceRoom, SeRaceRoomMgr::StartLoad, SeRaceRoomMgr::UpdateRaceEndTime, SeRaceRoomMgr::UpdateReady, SeRaceRoomMgr::UpdateWaitRoom.
DWord SeRaceRoom::dwMapID
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::GetReloadRoomInfo, SeRaceRoomMgr::JoinRoomRecon, SeRaceMgr::OnRaceModeEnd, SeRaceRoomMgr::SendRacePlayerBaseInfo, SeRaceRoom, SeRaceRoomMgr::UpdateRaceEndTime, SeRaceRoomMgr::UpdateReady.
SeRaceModel SeRaceRoom::eRaceModel
Referenced by SeRaceRoomMgr::CancelHero, SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::GetSelHeroTypeID, SeRaceRoomMgr::IntoSelHero, SeRaceRoomMgr::SendRacePlayerBaseInfo, SeRaceRoom, SeRaceRoomMgr::UpdateSelHero.
MapInfoTable * SeRaceRoom::pkMapInfoRes
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::GetReloadRoomInfo, SeRaceMgr::OnRaceModeEnd, SeRaceRoomMgr::OnViewValidOKRet, SeRaceRoom.
DWord SeRaceRoom::dwStateTime
Referenced by SeRaceRoomMgr::ChangeRoomState, SeRaceRoomMgr::CreateRoom, SeRaceRoom, SeRaceRoomMgr::UpdateWaitRoom.
SeRaceRoomState SeRaceRoom::eRoomState
Referenced by SeRaceRoomMgr::ChangeRoomState, SeRaceRoomMgr::GetReloadRoomInfo, SeRaceRoomMgr::OnPlayerCancelHero, SeRaceRoomMgr::OnPlayerChoiceHero, SeRaceRoomMgr::OnPlayerReconQuery, SeRaceRoomMgr::OnPlayerSelectHeroReady, SeRaceRoomMgr::OnPlayerViewQuery, SeRaceRoomMgr::OnProcessRepeatPlayer, SeRaceRoomMgr::OnRaceEnd, SeRaceRoomMgr::OnReSendRoomInfo, RaceServer::ProcessBLR_SelectHeroAck, RaceServer::ProcessCR_SelHeroChoiceHero, RaceServer::ProcessCR_SetAvatarReq, RaceServer::ProcessCR_SetEquipSetReq, RaceServer::ProcessMR_RaceBuyRet, SeRaceRoom, SeRaceRoomMgr::StartLoad, SeRaceRoomMgr::UpdateRaceEndTime, SeRaceRoomMgr::UpdateReady, SeRaceRoomMgr::UpdateSelHero, SeRaceRoomMgr::UpdateWaitRoom.
TeMD5 SeRaceRoom::kRaceID
Referenced by SeRaceMgr::GetRaceByRoomIndex, SeRaceRoomMgr::GetReloadRoomInfo, SeRaceMgr::IsReconValidPlayer, SeRaceRoomMgr::IsValidRace, SeRaceMgr::OnPlayerRaceViewBegin, SeRaceRoomMgr::OnPlayerViewQuery, SeRaceMgr::OnRaceModeEnd, SeRaceRoomMgr::UpdateRaceEndTime.
DWord SeRaceRoom::dwModeTaskID
Referenced by SeRaceRoomMgr::ClearModeTask, SeRaceRoomMgr::IntoSelHero, SeRaceRoomMgr::OnPlayerCancelHero, SeRaceRoomMgr::SelHero, SeRaceRoomMgr::SelHeroReady, SeRaceRoom, SeRaceRoomMgr::StartLoad.
DWord SeRaceRoom::dwReadyTime
Referenced by SeRaceRoomMgr::SelHeroReady, SeRaceRoom, SeRaceRoomMgr::UpdateReady.
DWord SeRaceRoom::dwExchangeHeroTime
Referenced by SeRaceRoom.
DWord SeRaceRoom::dwRaceEndTime
Referenced by SeRaceRoomMgr::ChangeRoomState, SeRaceRoom, SeRaceRoomMgr::UpdateRaceEndTime.
SeMatchRaceType SeRaceRoom::eMatchType
Referenced by SeRaceRoomMgr::GetReloadRoomInfo, SeRaceMgr::OnRaceModeEnd, SeRaceRoom.
DWord SeRaceRoom::dwKey
Referenced by SeRaceRoomMgr::CreateRoom, RaceServer::ProcessCR_RaceValidate, SeRaceRoom.
bool SeRaceRoom::bSvrRace
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceRoomMgr::GetReloadRoomInfo, SeRaceMgr::OnRaceModeEnd, SeRaceRoom.
int SeRaceRoom::iDifficulty
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceMgr::OnRaceModeEnd, SeRaceRoom.
SeRaceRoomSeat SeRaceRoom::akRoomSeat[SSD_MAX_ROOM_PLAYER]
Referenced by SeRaceRoomMgr::CreateRoom, GetAllSeatPlayer, GetOneMatchPlayer, SeRaceRoomMgr::OnPlayerReconQuery, SeRaceRoomMgr::OnReconValidOK, SeRaceRoomMgr::RecycleRoomPlayer, SeRaceRoom.
SeMatchPlayer * SeRaceRoom::akDroppedPlayer[SSD_MAX_ROOM_PLAYER]
Referenced by AddDroppedPlayer, DelDroppedPlayer, SeRaceRoomMgr::DestroyRoom, GetDroppedPlayer, SeRaceRoom.
SePtlRaceBetInfo SeRaceRoom::kRaceBet
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceMgr::OnRaceModeEnd, SeRaceRoom.
DWord SeRaceRoom::dwScoreCampA
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceMgr::OnRaceModeEnd.
DWord SeRaceRoom::dwScoreCampB
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceMgr::OnRaceModeEnd.
DWord SeRaceRoom::dwScoreRobot
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceMgr::OnRaceModeEnd.
bool SeRaceRoom::bRobot
Referenced by SeRaceRoomMgr::CreateRoom, SeRaceMgr::OnRaceModeEnd.
VMatchPlayer SeRaceRoom::kVSeatPlayer
Referenced by GetAllSeatPlayer, SeRaceRoom.
SeRaceRoom::DECLARE_POOL1(SeRaceRoom, DWord)
SeRaceRoom::SeRaceRoom(DWord dwSession)
References akDroppedPlayer, akRoomSeat, bSvrRace, dwExchangeHeroTime, dwID, dwKey, dwMapID, dwModeTaskID, dwRaceEndTime, dwReadyTime, dwStateTime, eMatchType, eRaceModel, eRoomState, iDifficulty, kRaceBet, kVSeatPlayer, pkMapInfoRes, SMRT_NONE, SRM_ALLRANDOM, SRRS_WAIT.
const VMatchPlayer & SeRaceRoom::GetAllSeatPlayer(bool bValidate=true)
References akRoomSeat, SeRaceRoomSeat::Clear, SeRaceRoomSeat::dwPlayerID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::IsValidate, kVSeatPlayer, SSD_MAX_ROOM_PLAYER.
Referenced by SeRaceRoomMgr::CancelHero, SeRaceRoomMgr::GetReloadRoomInfo, SeMatchReconMgr::InitAllow, SeRaceRoomMgr::IntoSelHero, SeRaceRoomMgr::IsAllRoomPlayerLeave, SeRaceRoomMgr::IsPlayerValidateEnd, SeRaceRoomMgr::OnPlayerTalk, SeRaceRoomMgr::OnRaceEnd, SeRaceRoomMgr::SelHeroFight, SeRaceRoomMgr::SelHeroReady, SeRaceRoomMgr::SendRacePlayerBaseInfo, SeRaceRoomMgr::StartLoad, SeRaceRoomMgr::UpdateRaceEndTime, SeRaceRoomMgr::UpdateSelHero.
SeMatchPlayer * SeRaceRoom::GetOneMatchPlayer()
References akRoomSeat, SeRaceRoomSeat::dwPlayerID, SeRaceRoomMgr::GetPlayer, SeMatchPlayer::IsValidate, SSD_MAX_ROOM_PLAYER.
void SeRaceRoom::AddDroppedPlayer(int iSeat, SeMatchPlayer *pkPlayer)
References akDroppedPlayer, SSD_MAX_ROOM_PLAYER.
void SeRaceRoom::DelDroppedPlayer(int iSeat)
References akDroppedPlayer, SSD_MAX_ROOM_PLAYER.
Referenced by SeRaceMgr::OnRaceModeEnd, SeRaceRoomMgr::OnReconValidOK.
SeMatchPlayer * SeRaceRoom::GetDroppedPlayer(int iSeat)
References akDroppedPlayer, SSD_MAX_ROOM_PLAYER.
Referenced by SeRaceMgr::OnRaceModeEnd, RaceServer::ProcessCR_RaceValidate.
SeRaceRoom::DECLARE_POOL1(SeRaceRoom, DWord)
SeRaceRoom::SeRaceRoom(DWord dwSession)
References akDroppedPlayer, akRoomSeat, bSvrRace, dwExchangeHeroTime, dwID, dwKey, dwMapID, dwModeTaskID, dwRaceEndTime, dwReadyTime, dwStateTime, eMatchType, eRaceModel, eRoomState, iDifficulty, kRaceBet, kVSeatPlayer, pkMapInfoRes, SMRT_NONE, SRM_ALLRANDOM, SRRS_WAIT.
const VMatchPlayer& SeRaceRoom::GetAllSeatPlayer(bool bValidate=true)
SeMatchPlayer* SeRaceRoom::GetOneMatchPlayer()
void SeRaceRoom::AddDroppedPlayer(int iSeat, SeMatchPlayer *pkPlayer)
void SeRaceRoom::DelDroppedPlayer(int iSeat)
SeMatchPlayer* SeRaceRoom::GetDroppedPlayer(int iSeat)