SeOldRaceConInfo
int SeOldRaceConInfo::iRoomIndex
UINT SeOldRaceConInfo::iSeatFlag
Referenced by checkSeat, hasEmptySeat, setSeat.
TeMD5 SeOldRaceConInfo::kRaceID
SeOldRaceConInfo::DECLARE_POOL(SeOldRaceConInfo)
SeOldRaceConInfo::SeOldRaceConInfo()
void SeOldRaceConInfo::setSeat(int iSeat, bool bFlag)
References iSeatFlag.
Referenced by SeMatchReconMgr::AddRaceSeat, SeMatchReconMgr::RemoveRaceSeat.
bool SeOldRaceConInfo::checkSeat(int iSeat) const
References iSeatFlag.
Referenced by SeMatchReconMgr::CheckCon2OldRace, SeMatchReconMgr::RemoveRaceSeat.
bool SeOldRaceConInfo::hasEmptySeat() const
References iSeatFlag.
Referenced by SeMatchReconMgr::RemoveRaceSeat.
SeOldRaceConInfo::DECLARE_POOL(SeOldRaceConInfo)
SeOldRaceConInfo::SeOldRaceConInfo()
void SeOldRaceConInfo::setSeat(int iSeat, bool bFlag)
References iSeatFlag.
bool SeOldRaceConInfo::checkSeat(int iSeat) const
References iSeatFlag.
bool SeOldRaceConInfo::hasEmptySeat() const
References iSeatFlag.