SeBaseSynOpr
DWord SeBaseSynOpr::dwBeginTime
Referenced by SeSynMgr::AddSynOpr, SeSynMgr::CheckOverTime, SeSynMgr::GetOutSynOpr, SeBaseSynOpr.
SeBaseSynOpr::SeBaseSynOpr()
References dwBeginTime.
virtual void SeBaseSynOpr::OnOverTime(void)
Referenced by SeSynMgr::CheckOverTime, SeSynMgr::Finialize, SeSynMgr::GetOutSynOpr.