NexusLinkUserMgr
MNexusLinkUser NexusLinkUserMgr::map_nexus_link_user_
Referenced by check, create, get_link_user, get_link_user_map, get_online_users, get_town_users, update, verify, verify_battle_scores, verify_ladder_scores, verify_match_scores, verify_punish_time, verify_user_attr.
NexusLinkUserMgr::NexusLinkUserMgr()
NexusLinkUserMgr::~NexusLinkUserMgr()
void NexusLinkUserMgr::create(const DWord dw_player_id, const DWord dw_state_id, const DWord dw_login_time)
References NexusLinkUser::battle_scores, NexusLinkUser::ladder_scores, NexusLinkUser::login_time, map_nexus_link_user_, NexusLinkUser::match_scores, NexusLinkUser::name, NexusLinkUser::punish_time, NexusLinkUser::state_id, NexusLinkUser::team_id, NexusLinkUser::user_id, NexusLinkUser::user_level.
Referenced by make.
void NexusLinkUserMgr::update(const DWord dw_player_id, const DWord dw_state_id, const DWord dw_login_time)
References get_link_user, NexusLinkUser::login_time, map_nexus_link_user_, NexusLinkUser::state_id, NexusLinkUser::user_id.
Referenced by make.
void NexusLinkUserMgr::make(const DWord dw_player_id, const DWord dw_state_id, const DWord dw_login_time)
References check, create, update.
Referenced by NexusServer::ProcessRN_RaceLinkUserSync, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessWCMSN_RaceWatchUserSync.
void NexusLinkUserMgr::verify(const DWord dw_player_id, const DWord dw_team_id)
References get_link_user, map_nexus_link_user_, NexusLinkUser::team_id, NexusLinkUser::user_id.
Referenced by NexusTeamMgr::link_team.
void NexusLinkUserMgr::verify_punish_time(const DWord dw_player_id, const DWord dw_punish_time)
References g_kNexusServer, get_link_user, NexusServer::GetServerTime, map_nexus_link_user_, NexusLinkUser::punish_time, NexusLinkUser::user_id.
Referenced by NexusServer::ProcessMN_MatchPunishNtf.
void NexusLinkUserMgr::verify_user_attr(const DWord dw_player_id, SeUserBaseAttrInfo info)
References get_link_user, map_nexus_link_user_, NexusLinkUser::name, NexusLinkUser::user_id, NexusLinkUser::user_level.
Referenced by NexusServer::ProcessTN_UserAttrInfoSync.
void NexusLinkUserMgr::verify_scores(const DWord dw_player_id, const DWord dw_type, const DWord dw_scores)
References verify_battle_scores, verify_ladder_scores, verify_match_scores.
Referenced by NexusServer::ProcessWN_PlayerScoreNtf.
void NexusLinkUserMgr::verify_ladder_scores(const DWord dw_player_id, const DWord dw_ladder_scores)
References get_link_user, NexusLinkUser::ladder_scores, map_nexus_link_user_, NexusLinkUser::user_id.
Referenced by verify_scores.
void NexusLinkUserMgr::verify_match_scores(const DWord dw_player_id, const DWord dw_match_scores)
References get_link_user, map_nexus_link_user_, NexusLinkUser::match_scores, NexusLinkUser::user_id.
Referenced by verify_scores.
void NexusLinkUserMgr::verify_battle_scores(const DWord dw_player_id, const DWord dw_battle_scores)
References NexusLinkUser::battle_scores, get_link_user, map_nexus_link_user_, NexusLinkUser::user_id.
Referenced by verify_scores.
bool NexusLinkUserMgr::check(const DWord dw_player_id)
References map_nexus_link_user_.
Referenced by make.
bool NexusLinkUserMgr::check_offline(const DWord dw_player_id)
References check_state.
Referenced by get_link_user_online_state, get_online_users, get_town_users, NexusServer::ProcessTN_RoomInviteNotifyVerify, NexusServer::ProcessTN_UserInviteReq.
bool NexusLinkUserMgr::check_online(const DWord dw_player_id)
References check_state.
Referenced by get_link_user_online_state.
bool NexusLinkUserMgr::check_watching(const DWord dw_player_id)
References check_state.
Referenced by get_link_user_online_state, get_town_users, NexusServer::ProcessTN_RoomInviteNotifyVerify, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq.
bool NexusLinkUserMgr::check_racing(const DWord dw_player_id)
References check_state.
Referenced by get_link_user_online_state, get_town_users, NexusServer::ProcessTN_RoomInviteNotifyVerify, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq.
bool NexusLinkUserMgr::check_matching(const DWord dw_player_id)
References check_state.
Referenced by get_link_user_online_state, NexusServer::ProcessTN_RoomInviteNotifyVerify, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq.
bool NexusLinkUserMgr::check_state(const DWord dw_player_id, const DWord dw_state_id)
References get_link_user, NexusLinkUser::state_id.
Referenced by check_matching, check_offline, check_online, check_racing, check_watching.
NexusLinkUser * NexusLinkUserMgr::get_link_user(const DWord dw_player_id)
References map_nexus_link_user_.
Referenced by check_state, get_link_user_battle_scores, get_link_user_ladder_scores, get_link_user_level, get_link_user_match_scores, get_link_user_name, get_link_user_punish_time, get_link_user_state, get_link_user_team, update, verify, verify_battle_scores, verify_ladder_scores, verify_match_scores, verify_punish_time, verify_user_attr.
MNexusLinkUser & NexusLinkUserMgr::get_link_user_map()
References map_nexus_link_user_.
DWord NexusLinkUserMgr::get_online_users()
References check_offline, map_nexus_link_user_, NexusLinkUser::user_id.
DWord NexusLinkUserMgr::get_town_users()
References check_offline, check_racing, check_watching, map_nexus_link_user_, NexusLinkUser::user_id.
DWord NexusLinkUserMgr::get_link_user_team(const DWord dw_player_id)
References get_link_user, NexusLinkUser::team_id.
Referenced by NexusTeamMgr::invite, NexusTeamMgr::offline, NexusServer::ProcessTN_MatchTeamMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserInviteReq.
DWord NexusLinkUserMgr::get_link_user_online_state(const DWord dw_player_id)
References check_matching, check_offline, check_online, check_racing, check_watching.
Referenced by NexusServer::ProcessTN_NexusFriendDetailInfoReq, NexusServer::ProcessTN_NexusUserActionReq.
DWord NexusLinkUserMgr::get_link_user_state(const DWord dw_player_id)
References get_link_user, NexusLinkUser::state_id.
Referenced by NexusServer::ProcessTN_UserStatusQueryReq.
DWord NexusLinkUserMgr::get_link_user_punish_time(const DWord dw_player_id)
References get_link_user, NexusLinkUser::punish_time.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq.
DWord NexusLinkUserMgr::get_link_user_level(const DWord dw_player_id)
References get_link_user, NexusLinkUser::user_level.
DWord NexusLinkUserMgr::get_link_user_match_scores(const DWord dw_player_id)
References get_link_user, NexusLinkUser::match_scores.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq.
DWord NexusLinkUserMgr::get_link_user_ladder_scores(const DWord dw_player_id)
References get_link_user, NexusLinkUser::ladder_scores.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq.
DWord NexusLinkUserMgr::get_link_user_battle_scores(const DWord dw_player_id)
References NexusLinkUser::battle_scores, get_link_user.
Referenced by NexusServer::ProcessTN_LeaderKickMemberReq, NexusServer::ProcessTN_NexusLinkUserSync, NexusServer::ProcessTN_UserConfirmInviteReq, NexusServer::ProcessTN_UserLeaveTeamReq.
const char * NexusLinkUserMgr::get_link_user_name(const DWord dw_player_id)
References get_link_user, NexusLinkUser::name.