NexusMeasureMgr
MNexusMeasure NexusMeasureMgr::map_nexus_measure
Referenced by create_guest_measure, create_user_measure, get_nexus_measure, get_user_measure_map, verify_mark, verify_measure.
NexusMeasureMgr::NexusMeasureMgr()
NexusMeasureMgr::~NexusMeasureMgr()
NexusMeasureParam NexusMeasureMgr::gen_param(const DWord user_id, const DWord guest_id, const DWord mark, const DWord create_time, const char *user_name, const char *guest_name)
References NexusMeasureParam::create_time, NexusMeasureParam::guest_id, NexusMeasureParam::guest_name, NexusMeasureParam::mark, NexusMeasureParam::user_id, NexusMeasureParam::user_name.
void NexusMeasureMgr::create_measure(const NexusMeasureParam param)
References create_guest_measure, create_user_measure.
void NexusMeasureMgr::create_user_measure(const NexusMeasureParam param)
References NexusMeasure::create_time, NexusMeasureParam::create_time, NexusMeasure::friend_id, NexusMeasure::friend_name, NexusMeasureParam::guest_id, NexusMeasureParam::guest_name, map_nexus_measure, NexusMeasure::mark, NexusMeasureParam::mark, NexusMeasure::measures, NexusMeasure::user_id, NexusMeasureParam::user_id.
Referenced by create_measure.
void NexusMeasureMgr::create_guest_measure(const NexusMeasureParam param)
References NexusMeasure::create_time, NexusMeasureParam::create_time, NexusMeasure::friend_id, NexusMeasure::friend_name, NexusMeasureParam::guest_id, map_nexus_measure, NexusMeasure::mark, NexusMeasureParam::mark, NexusMeasure::measures, NexusMeasure::user_id, NexusMeasureParam::user_id, NexusMeasureParam::user_name.
Referenced by create_measure.
void NexusMeasureMgr::verify_mark(const DWord user_id, const DWord guest_id, const DWord mark)
References get_nexus_measure, map_nexus_measure, NexusMeasure::mark.
void NexusMeasureMgr::verify_measure(const DWord user_id, const DWord guest_id, const DWord measure)
References get_nexus_measure, map_nexus_measure, NexusMeasure::measures.
Referenced by clear_mutual_measure.
void NexusMeasureMgr::clear_mutual_measure(const DWord user_id, const DWord guest_id)
References verify_measure.
bool NexusMeasureMgr::check_friend(const DWord user_id, const DWord guest_id)
References ENM_Confirm, get_nexus_measure, NexusMeasure::mark.
bool NexusMeasureMgr::check_friend_limit(const DWord user_id)
References ENM_Confirm, get_user_friend_map, NexusMeasure::mark, nexus_friend_limit.
bool NexusMeasureMgr::check_nexus_measure(const DWord user_id, const DWord guest_id)
References get_nexus_measure.
bool NexusMeasureMgr::check_apply(const DWord user_id, const DWord guest_id)
References ENM_Request, get_user_guest_mark.
bool NexusMeasureMgr::check_confirm(const DWord user_id, const DWord guest_id)
References ENM_Confirm, get_user_guest_mark.
bool NexusMeasureMgr::check_reject(const DWord user_id, const DWord guest_id)
References ENM_Reject, get_user_guest_mark.
DWord NexusMeasureMgr::get_user_friend_measure(const DWord user_id, const DWord guest_id)
References ENM_Confirm, get_nexus_measure, NexusMeasure::mark, NexusMeasure::measures.
DWord NexusMeasureMgr::get_user_guest_mark(const DWord user_id, const DWord guest_id)
References ENM_Unknow, get_nexus_measure, NexusMeasure::mark.
Referenced by check_apply, check_confirm, check_reject.
NexusMeasure * NexusMeasureMgr::get_nexus_measure(const DWord user_id, const DWord guest_id)
References map_nexus_measure.
Referenced by check_friend, check_nexus_measure, get_user_friend_measure, get_user_guest_mark, verify_mark, verify_measure.
MMeasure & NexusMeasureMgr::get_user_measure_map(const DWord user_id)
References map_nexus_measure.
Referenced by get_user_apply_map, get_user_friend_map.
MMeasure & NexusMeasureMgr::get_user_apply_map(const DWord user_id)
References ENM_Request, NexusMeasure::friend_id, get_user_measure_map, NexusMeasure::mark.
MMeasure & NexusMeasureMgr::get_user_friend_map(const DWord user_id)
References ENM_Confirm, NexusMeasure::friend_id, get_user_measure_map, NexusMeasure::mark.
Referenced by check_friend_limit.